== Chapter II

[.centered]
=== The Friend and the Robber

The courage and presence of mind exhibited by the true soldier of Jesus Christ,
when permitted in the course of Divine Providence
to be cast into straits and trying situations,
is often conspicuous.
He not only knows the strength of that preserving arm,
which rules or overrules all circumstances for the good of those
that are faithful,--he not only is furnished for all occasions,
and "`out of weakness is made strong,`" so as even to "`stop
the mouths of lions,`" and "`quench the violence of fire,`"^
footnote:[Heb. 11]
but is abundantly furnished with resignation to submit unto the Lord in all things;
with one who was "`in perils of robbers,`" and "`in deaths often,`"^
footnote:[2 Cor. 11.]
he can say, "`Whether we live or die, we are the Lord`'s.`"^
footnote:[Rom. 14:8.]

The conduct of some of our Society who have _fallen among thieves,_
and who by their religious scruples were of course precluded
from retaliating violence even in their own defence,
is an exemplification of this feature in the Christian character.
It is recorded of Robert Barclay,
that as he was returning from a journey into Hertfordshire,
his life was in some danger from the attack of a highwayman.
His wife had observed him in the morning to be more pensive than usual,
and he then told her, he believed some uncommon trial would that day befall the company.
When the robber presented his pistol, Robert Barclay calmly asked him,
How he came to be so rude, and took him by the arm;
on which the robber let the pistol drop, and offered him no further violence.
It is also told of Leonard Fell, one of Judge Fell`'s sons, that, "`travelling alone,
he was attacked by a highwayman, who demanded his money, which he gave him;
then he desired to have his horse, Leonard dismounted and let him take it.
Then feeling the _power of Truth_ rise in his mind, he turned to the robber,
and under _its_ authority solemnly warned him of the evil of his ways: but he,
flying into a passion, asked the Friend why he preached to him,
and threatened to blow out his brains.
But Leonard replying to this effect,
'`Though I would not give my life for my money or my horse,
I would give it to _save your soul,_`' so struck the astonished robber, that he declared,
if he was such a man as that, he would take neither his money nor his horse from him;
and returning both to the faithful Friend, went his way,
leaving Leonard to the enjoyment of that peace attending
the honest discharge of his conscience,
to obtain which he had not counted his life dear.`"

[.asterism]
'''

John Woolman in his journal has given the following instructive relation, which,
it is believed, few that are rightly concerned for the interests of true piety,
and that practical religion laid down by the Head of the Church,
can read with indifference.
It were good perhaps for everyone, to lay to heart such considerations as arise,
on taking a view of primitive genuine Christianity, and to examine,
how far they as individuals are contributing by their
lives and conduct to the growth of that vanity,
pride, and earthly-mindedness, which are but too prevalent.

[.embedded-content-document]
--

At our yearly meeting at Philadelphia, the 25th day of the 9th month, 1764, John Smith,
of Marlborough, aged upwards of eighty years, a faithful minister, though not eloquent,
stood up in our meeting for ministers and elders,
and appearing to be under a great exercise of spirit,
informed Friends in substance as follows:
That he had been a member of our Society upwards of sixty years,
and well remembered that in those early times Friends were a plain lowly-minded people;
and that there was much tenderness and contrition in their meetings.
That at twenty years from that time the Society increased in wealth,
and in some degree conforming to the fashions of the world,
true humility was less apparent,
and their meetings in general not so lively and edifying.
That at the end of forty years, many of them had grown very rich;
that wearing of fine costly garments, etc. became customary with them, their sons,
and their daughters, and many of the Society made a specious appearance in the world;
which marks of outward wealth and greatness appeared
on some in our meetings of ministers and elders;
and as these things became more prevalent,
so the powerful overshadowings of the Holy Spirit were less manifest in the Society.
That there had been a continued increase of these ways of life even until now;
and that the weakness which has now overspread the Society,
and the barrenness manifest among us, is matter of much sorrow.
He then mentioned the uncertainty of his attending these meetings in future,
expecting his dissolution was now near; and having tenderly expressed his concern for us,
signified,
that he had seen in the true light that the Lord
would bring back his people from these things,
into which they were thus degenerated,
but that his faithful servants must first go through great and heavy exercises therein.

--

[.asterism]
'''

Thomas Story, in his travels, coming to the town of Mildorp in Germany,
tarried there to refresh himself.
He, with Pieter Leendaars, went into a place of worship that was open,
belonging to the Lutherans, of which he writes in his journal:

[.embedded-content-document]
--

We observed several pictures and images (as they say) of Christ in several conditions,
as on the cross, risen again, etc. and one was of a golden colour all over.
Here were painted and wooden Christs in statuary and imagery,
painted heaven and painted hell, painted saints, and this among professors of Christ,
pretending reformation from that Church which is condemned for idolatry;
and all is justly condemned by the holy scriptures,
and by the practice of the saints in all ages.
I asked our landlord, why they had so many images of Christ in their churches and houses?
He answered, "`It is to put us in mind of Christ,`" I replied,
"`It seems you do not love Christ so well as you should,
since you need so many outward mementos of his outward appearance;
but the primitives had the mind and spirit of Christ;
they bore in their own bodies the dying of the Lord, and wore his cross in their hearts,
by which they were crucified to the world, and the world unto them,
with all its show and vain-glory:
and this cross is that living virtue and life of Christ appearing in men`'s hearts now,
as well as in those days; working the same effects in all who believe, follow,
and obey it, being the saving grace and light of Christ unto all people.`"
This seemed strange to him, as appeared by his countenance,
yet I believe it answered his conscience, for he made no reply.

--

[.centered]
=== Account of Some Indians

Among the many instances,
tending to prove the universal operation of divine grace on the human heart,
a particular one appeared some years ago,
among a number of Indians in the Province of Pennsylvania.
These people were very earnest for the promotion of piety among themselves,
which they apprehended to be the effect of an inward work,
whereby the heart became changed from bad to good.
When they were solicited to join other Indians in the war against the English,
they absolutely refused, whatever might be the consequence to themselves,
even if the fighting Indians should make _slaves,_ or as they expressed it, _negros,_
of them, rendering this reason for it, that when God made men,
he did not intend they should hurt or kill one another.^
footnote:[In this disposition they have continued about thirty years,
notwithstanding the ill-treatment they have received from Indians and others;
more especially of late that they have been pillaged,
their settlements at three towns broken up,
and they carried away captives towards Canada.
Those Indians who carried them away, giving as a reason for this violence,
said that they were in their way,
and a great obstruction to them when going to war.
{footnote-paragraph-split}
See the [.book-title]#Pennsylvania Packet,# for the 12th Mo. 22,1781]

Upon being further conversed with, respecting their religious prospects,
he who had been a principle instrument in raising them to a sense of good,
gave in substance the following account:

[.embedded-content-document]
--

That being by a particular providence brought under difficulty and sorrow,
he was led into a deep consideration of the state of things in the world;
when seeing the folly and wickedness that prevailed among men, his sorrows increased.
Nevertheless, being impressed with a belief that there was a great Power,
who had created all things, his mind was turned from beholding this lower world,
to look towards Him who had created it,
and strong desires were begot in his heart for a further knowledge of his Creator.
He was then made sensible, that evil not only prevailed in the world,
but that he himself partook much of its baneful influence;
and he at last found his own heart was bad and hard.
Upon this, great dejection and trouble seized his mind, with an enquiry,
what would become of his soul?
In this situation he cried unto that powerful Being,
who he was sensible had made the heart of man;
and after a long time of sorrow and perseverance in seeking for help,
God was pleased to reveal himself to his mind, and to put his goodness in his heart.
He found he was, as he expressed it, raised above himself and above the world,
and felt that his heart had undergone some great change;
the hardness and badness he had so long groaned under, was taken away,
it was now become soft and good; he found so much love to prevail in it to all men,
that he thought he could bear with their revilings and abuses without resentment,
appearing sensible, that as the hearts of all men were bad and hard,
till God made them good, the ill-usage he received from them,
proceeded from the same evil seed, under which he himself had so long groaned.

This sense of the corruption of human nature,
accompanied with a constant application to his Maker,
to take away the badness and hardness of the heart, and make it soft and good,
was what he called _religion;_ and what, upon feeling the power of God to his comfort,
he was concerned to exhort his brethren to seek the experience of in themselves.
And further said, that under this dispensation,
he was made sensible the spirit of religion was a spirit of love,
which led those who obeyed it into love to all men;
but that men not keeping to this spirit of love,
an opposite spirit got entrance in their hearts;
that it was from here all those disorders arose, which so much prevailed among men.
He was also sensible there was still an evil spirit
labouring to get the mastery in his heart,
in opposition to the gospel spirit;
but that those who had been visited by a power from God,
and were obedient to the degree of light and love he was pleased to favour them with,
would be more and more strengthened and established therein.
He had also a prospect of the necessity of that baptism of the Spirit and fire,
which the scriptures and the experience of the faithful in all
ages testify every true disciple of Christ must undergo,
whereby, through mortification and death to self, the root of sin is destroyed.
This he described by the prospect he had of something,
like as an outward fire would be to the natural body,
which he must pass through in order to attain to that purity of heart he desired.
He further observed, that while he was anxiously beholding this fire,
he saw a very small path close to it, by walking in which he might go round the fire,
and the painful trial be avoided.
This he understood to represent the way,
by which those who were esteemed wise had found means to
avoid that probation they ought to have passed through,
and yet retained a name among men, as though they had been purified by it.

Thus this Indian, untaught by books and unlearned in what is called divinity,
through the inshining of the light of Christ on his understanding,
explained the mystery of godliness in a plain and sensible manner;
showing that true religion remains to be the power of God to salvation,
changing and purifying the heart,
and bringing it into true contrition and a submissive resignation to the will of God.
This has ever been found to be the effect of its operation on all those,
who by devoting themselves to God,
are become the truer followers and disciples of Jesus Christ.

[.signed-section-signature]
Extract from A. Benezet`'s [.book-title]#Preface to the Plain Path to Christian Perfection.#

--

[.centered]
=== George Whitehead`'s Travels and Hardships

Those of our Society, who in the present day enjoy a tranquil and easy life,
as respects outward persecution and suffering for conscience sake,
and who have no lack of "`this world`'s good,`" may derive some important
instruction from a view of the various trying circumstances under which
their Christian predecessors in many instances were placed.
The faith, the zeal, the courage, the patience of these,
whether known by our name or any other, are to be often recurred to and remembered,
not only as so many proofs of the divine efficacy of revealed Truth,
but as so many stimulating calls to follow them as they have followed Christ,
exemplifying like them the excellency and glory of his offered salvation.

The passages subjoined, from George Whitehead`'s journal,
are not perhaps so fully calculated to set forth the Christian`'s
conduct and conflicts in a general point of view,
as some others that might have been chosen; yet, to a certain extent,
and in a particular direction, they have their weight and import;
and the little abstract first given is especially introduced with an earnest hope,
that the _youthful_ reader may regard that all-sufficient Power,
through which so much was accomplished,--through which also
_they_ may live acceptably to Him who died for them,
fulfilling the end of their existence in the obedience of faith.

_Abstract._--In the year 1654, George Whitehead, then not eighteen years of age,
travelled on foot in the work of the ministry out
of Westmorland with Edward Edwards to York,
about sixty miles, in harvest time.
There they remained two or three days.
After this they parted; and George Whitehead went forward to Lincoln,
a distance of eighty miles, where he stayed one night;
from there he moved on to Cambridge, which journey,
being at least seventy miles in a strait line, he accomplished in less than three days,
"`Though my feet,`" says he,
"`were pretty much galled and blistered even before I came out of Yorkshire,
yet they amended while I travelled.`"
He was at Cambridge two or three days, and from there passed on to Wymondham,
which could not have been under fifty miles by any reckoning,
and to Norwich the next day.

[.embedded-content-document]
--

_Extract._--Our being shut out of our meeting houses for several years,
in and about the cities of London and Westminster,
and our meetings kept in the streets in all sorts of weather, winter and summer,
was a trial and hardship upon us, even upon old and young, men and women:
but that trial was not so great,
as to have our estates and livelihoods exposed to ruin by a pack of ravenous informers;
although it was no small hardship to our persons, to be kept out of doors,
in the streets, in the great, severe, and long frost and snow, in the year 1683,
for about three months together; when the river Thames was so frozen up, that horses,
coaches and carts could pass to and fro upon it, and a street also be erected,
and stand over it.
And yet in all that hard season, when we were so long kept out in the streets,
in the bitter cold air, I do not remember that I got any harm or injury thereby,
to the impairing my health,
although I frequently attended those our meetings in the streets;
wherein I took great and serious notice of the merciful providence
of Almighty God towards my self and many more of our Friends,
who were sharers in the same mercy and preservation in that suffering and exercise:
no thanks to our unmerciful adversaries and persecutors,
but to our heavenly Father be the glory and praise forever.

We had in those days some opportunities,
and were permitted to publish the Truth openly in the streets,
and also to make public supplication to God; yet more frequently not permitted,
but pulled away by force, by the trained bands and officers, and either sent to prison,
or turned into the meetinghouse,
and there detained under guard until the meeting was ended in the street.
Thus were the ministers and others among us often forcibly interrupted and served,
and scarcely permitted, many times, to declare two or three sentences,
without being haled away.
However we saw it our duty, in the fear of the living God, to keep our meetings,
and patiently to wait upon Him, where often we enjoyed His presence to our consolation,
even in our silent attention upon Him:
being not called to strive or contest with our adversaries,
or their servants whom they employed, but in faith and patience to bear all,
believing that in due time thereby we should obtain victory.
It was often then before me,
that the Lamb and his faithful followers should have the victory,
which was matter of secret comfort to me many times; glory to His name forever.

--

[.centered]
=== Edward Burrough`'s Preaching

[.embedded-content-document.testimony]
--

He was a man of undaunted courage, though but young,
the Lord set him above the fear of his enemies,
and I have beheld him filled with power by the Spirit of the Lord.
For instance, at the Bull and Mouth, when the room, which was very large,
has been filled with people, many of whom have been in uproars,
contending one with another, some exclaiming against the Quakers,
accusing and charging them with heresy, blasphemy, sedition, and what not;
that they were _deceivers and deluded the people;_ that they denied the holy scriptures,
and the resurrection; others endeavouring to vindicate them,
and speaking of them more favourably:--In the midst of all which noise and contention,
this servant of the Lord has stood upon a bench with his bible in his hand,
(for he generally carried one about him,) speaking to the people
with great authority from the words of John 7:12. "`And there
was much complaining among the people concerning him (Jesus):
for some said, He is a good man: others said, No, on the contrary,
he deceives the people,`"--and so suitably to the present debate among them,
that the whole multitude were thereby overcome, and became exceeding calm and attentive,
and departed peaceably and with seeming satisfaction,

[.signed-section-signature]
_William Grouch`'s Memoirs._

--

[.centered]
=== Christian Zeal

James Gough, in the narrative of his own life, relates of John Ashton of Kilconimore,
(who was an old man when James Gough saw him,) that "`he with his wife, when at liberty,^
footnote:[He was imprisoned for tithes soon after his convincemcnt.]
constantly attended the meeting at Birr twice a week, generally walking on foot there,
being about seven English miles and a very bad road,
wading through a river both going and returning.
In winter they sometimes had the ice to break in crossing this river;
and John said he had wept to see the blood on his wife`'s legs in coming through it.
In those days Truth was precious to its professors who also possessed it,
and no difficulties or dangers could prevent them from getting to their religious meetings,
to enjoy the renewings of divine love and life with their brethren.`"

[.centered]
=== Gospel Simplicity

The last mentioned writer gives a lively illustration
of the _practical_ effects of that divine anointing,
holy energy, or internal principle of action,
by which our Society has been always more or less characterized.
It may not be unsuitable to preface its insertion, with a passage from the same journal,
as follows:

[.embedded-content-document]
--

Truth has ever led to integrity, punctuality, and upright dealing in our outward affairs,
and to limit ourselves to few exigencies, and a humble condition in life,
rather than invade or risk the properties of other men.
We cannot all get a deal of the treasures of this world,
(nor is a deal necessary to our well-being,--"`a man`'s life consists not in
the abundance of the things which he possesses;`") but we may all live on a little,
if our minds be kept humble,
and the sensual appetites be subjected to the cross of Christ.

John Goodwin, of Escargogh, in Monmouthshire,
lived and maintained his family on a farm of four pounds a year,
but at length had purchased and improved it,
so that at that time he reckoned it worth six pounds a year.
The first journey he travelled in the ministry, which was to visit Friends through Wales,
he had then got of clear money above forty shillings in all, and he was free to spend it,
if there were occasion, in the Lord`'s service, knowing that he could give him,
or enable him to get more.
The first time he began to entertain travelling Friends,
(most of that meeting being gone to Pennsylvania,) he had but one bed,
which he left to them, he and his wife taking up their lodging in the stable.

--

Our predecessors in religious profession were remarkably
noted for their hospitality and disinterestedness,
and in them it seemed evidently to arise from a rooted sense of religious duty,
and the powerful constrainings of Christian love.

[.centered]
=== Thomas Chalkley on the Use of the Sword

[.embedded-content-document]
--

When I was in Barbados, P. M., who accompanied me from Bridgetown to Counsellor Week`'s,
told me, that when I was in the island before,
he and I had some discourse concerning the use of the sword,
he then (not being of our Society,) wore a sword, but now had left it off,
and his business also, which was worth some hundreds a year.
I had reminded him of Christ`'s words, that those who take the sword,
should perish with the sword,^
footnote:[Matt. 26:52.]
and, Resist not evil; and if any man smite you on one cheek, turn the other also:
Love enemies, do good to them that hate you, pray for them that despitefully use you,
and persecute you.^
footnote:[Matt. 5.]
After I had used these arguments, he asked me, If one came to kill me,
Would I not kill rather than be killed?
I told him, No; so far as I knew my own heart, I had rather be killed than kill.
He said, That was strange, and desired to know what reason I could give for it.
I told him, That I being innocent, if I were killed in my body, my soul might be happy;
but if I killed him, he dying in his wickedness, would consequently be unhappy;
and if I were killed, he might live to repent, but if I killed him,
he would have no time to repent, so that, if he killed me, I should have much the better,
both in respect to myself and him.
This discourse had made so much impression, and so affected him, that he said,
he could not but often remember it.
And when we parted at Bridgetown, we embraced each other, in open arms of Christian love,
far from that which would hurt or destroy.

--

[.centered]
=== John Churchman on the Names of the Days of the Week

[.embedded-content-document]
--

Before my going to Holland,
I was at the shop of a barber in this city (Norwich,) several times to be shaved:
the second time I was there, I had to wait a little for my turn, he having no assistant;
and when others were gone out, he told me he was sorry I had to wait,
and hoped he should have my custom: and that if I would come on Saturdays and Wednesdays,
in the forenoon, I need not wait; but in the afternoon others came.
I asked him what days in the week those were which he called Saturdays and Wednesdays:
he seemed to wonder at my ignorance, but knew not how to tell me otherwise.
I said, "`I do not read in the scriptures of any days so named:`" he replied,
"`That is true.`"
"`For what reason then,`" said I, "`do you call them so?`"
"`Because it is a common custom,`" said he.
"`Suppose then,`" said I, "`that we lived in a heathen country; among infidels,
who worshipped idols, should we follow their customs, because common?`"
He replied, "`By no means.`"
I then said, "`If I have understood rightly,
the heathens gave the days of the week those names.`"
"`I never heard that before,`" said he; "`pray for what reason?`"
I answered, "`They worshipped the sun on the first day of the week,
and named it after their idol, Sunday; the moon on the second day of the week,
so came Monday; and the other days after other idols, for they had many gods.
Third-day they called Tuesday, after their idol Tuisco; and after the idol Woden,
fourth-day they called Wednesday; and fifth-day, after their idol Thor,
they called Thursday; from Friga, Friday; and after Saturn they called the seventh-day,
Saturday.
And as I believe in the only true God, and Jesus Christ, whom he has sent,
and expect eternal life by no other name or power, I dare not, for conscience sake,
own the gods of the heathen, or name a day after them;
but choose the names which the days were called by,
when the Most High performed his several works of creation, namely, first, second, third,
and so on, which is scriptural, most plain, and easily understood.`"
He seemed somewhat affected with the information,
and I desired him to enquire into the matter for himself,
and not to think that I designed to impose upon him.

On my return from Holland to Norwich, a man ran to me in the street,
putting a paper into my hand, and immediately left me,
whom I soon found to be this barber.
The letter contained an innocent childlike acknowledgment to me for my freedom with him,
as is before mentioned,
in language rather too much showing his value for me as an instrument.
Believing him to be reached by the love of Truth,
and in measure convinced of the principle thereof,
I thought it best to leave him in the Lord`'s hands for further instruction.

I mention this passage with a view to stir up my friends of the same holy profession,
to let their language in words be the real language of truth to all men,
in purity of spirit,
and not to name the days of the week or months after the heathenish idolatrous customs,
saying for excuse, that they to whom they speak do best understand them,
and it saves them any further explanation;
which excuse is far from proceeding from a disposition _apt to teach,_
and letting the light of Truth shine as it ought.
"`Neither do men,`" said our blessed Instructor, "`light a candle,
and put it under a bushel, but on a candlestick,
and it gives light to all that are in the house.`"^
footnote:[Matt. 5:15.]
Nor does the Lord enlighten his candle, that is the spirit of man^
footnote:[Prov. 20:27.]
with the pure knowledge of Truth, that we should cover it,
either with an easeful disposition, to save ourselves trouble,
or hide the work thereof under the coveting bushel of worldly saving care,
after the gain and treasure of this world; but that it may stand on the candlestick,
and thereby crown those who are thus favoured with the holy light,
that as a city set on a hill they cannot be hid.
The corrupt language of You to a single person,
and calling the months and days by heathen names,
are esteemed by some to be little things;
but if a faithful testimony in these little things
was blessed in the instance before mentioned,
even to the raising an earnest inquiry after the
saving knowledge of God and his blessed Son,
whom to know is eternal life;
perhaps such who baulk their testimony to the pure
talent of Truth given to them to profit withal,
may one day have their portion appointed with the wicked and slothful servant.^
footnote:[See Matt. 25:24-25, etc.]

--

[.asterism]
'''

Thomas Chalkley, travelling in New-England, relates that about the year 1704,
the Indians were very barbarous in the destruction of the English inhabitants,
scalping some, and knocking out the brains of others (men,
women and children,) by which the country was greatly alarmed, both night and day.

[.embedded-content-document]
--

But +++[+++continues he,]
the great Lord of all was pleased wonderfully to preserve our Friends,
especially those who kept faithful to their peaceable principles,
according to the doctrine of Christ in the holy scriptures,
as recorded in his excellent sermon which he preached on the mount,
which is quite opposite to killing, revenge, and destruction even of our enemies.

And because our Friends could not join with those of fighting principles and practices,
some of them were put into prison;
many people railing and speaking very bitterly against their peaceable neighbours,
and wishing the Quakers might be cut off.
Among the many hundreds that were slain,
I heard but of three of our Friends being killed, whose destruction was very remarkable,
as I was informed; the one was a woman, the other two were men.
The men used to go to their labour without any weapons,
and trusted to the Almighty and depended on His providence to protect them,
(it being their principle not to use weapons of war to offend others,
or to defend themselves); but a spirit of distrust taking place in their minds,
they took weapons of war to defend themselves;
and the Indians who had seen them several times without them, and let them alone, saying,
they were peaceable men, and hurt nobody, therefore they would not hurt them;
now seeing them have guns, and supposing they designed to kill the Indians,
they therefore shot the men dead.

The woman had remained in her habitation,
and could not be free to go to a fortified place for preservation, neither she, her son,
nor daughter, nor to take there the little ones;
but the poor woman after some time began to let in a slavish fear,
and advised her children to go with her to a fort not far from their dwelling.
Her daughter being one that trusted in the name of the Lord,
the mighty tower to which the righteous flee and find safety,
could not consent to go with her;
and having left a particular account in a letter to her children of her and their preservation,
I think it worthy to be inserted here in her own words:

"`When the cruel Indians were permitted to kill and destroy, it was shown me,
that I must stand in a testimony for Truth, and trust in the name of the Lord,
that was a strong tower, and we should wait upon Him.
And I often desired my mother and husband to sit down, and wait upon the Lord,
and He would show us what we should do.
But I could not prevail with him, but he would say it was too late now,
and was in great haste to be gone; but I could not go with him,
because I was afraid of offending the Lord:
but still he would say I was deluded by the devil, so that my mother would often say,
A house divided could not stand; and she could not tell what to do,
although she had most peace in staying, yet she had thoughts of moving, and said to me,
'`Child, can you certainly say it is revealed to you we should stay?
if it be, I would willingly stay,
if I was sure it was the mind of God.`' But I being young and afraid to speak so high,
said, '`Mother, I can say that it is so with me,
that when I think of staying and trusting in the name of the Lord,
I find great peace and comfort more than I can utter,
with a belief we shall be preserved: but when I think of going, oh,
the trouble and heaviness I feel,
with a fear some of us should fall by them!`' And my dear mother sighed,
and said she could not tell what to do: but I said to them, if they would go,
I should be willing to stay alone; if they found freedom, I was very willing,
for I was afraid of offending the Lord.
But still my poor husband would say, I took a wrong spirit for the right.
And he would say how should I know?
for if I was right I should be willing to condescend to him; and then I said,
in condescension to him I would move; but I hoped the Lord would not lay it to my charge,
for was it not to condescend to him, I would not move for the world.

"`And after I had given away my strength,
in a little time there came men from the garrison with their guns,
and told us they came for us, and that they thought the Indians might be near;
and then away we went; and my mother went in with my brother-in-law,
although I persuaded her not to do it.
But she said, '`Why, my child is there:
and why may I not be with him as well as you?`' And so we went along to Hampton,
to my husband`'s brother`'s. But Oh the fear and trouble that I felt! and told my husband,
it seemed as if we were going into the mouth of the Indians.
And the next day was the first day of the week:
and our dear Friend Lydia Norton came with my dear mother; and in her testimony,
she said, there was there that was very near to her life, that was very near death.
O then I was ready to think it would be I,
because I believed we had done amiss in moving, and great trouble was I in,
and told dear Lydia of it, but she comforted me as much as she could,
and said she did not think it would be I. And my
dear mother went to my sister`'s again to the garrison,
where she found herself not easy; but as she often said to many,
that she felt herself in a beclouded condition,
and more shut from divine counsel than she had ever been since she knew the Truth;
and being uneasy, she went to move to a Friend`'s house, that lived in the neighbourhood;
and as she was moving, the bloody cruel Indians lay by the way, and killed her.

"`O then how did I lament moving! and promised if
the Lord would be pleased to spare my life,
and husband and children, and carry us home again, I would never do so more.
But O the fear and trouble, and darkness that fell upon me,
and many more at that time! three or four of us kept our meeting,
but although we sat and waited as well as we could,
yet we sat under a poor beclouded condition till we returned home again;
then did the Lord please to lift up the light of his love upon our poor souls.

"`O then I told my husband, although he had built a little house by the garrison,
I could not move again.
So he was willing to stay while the winter season lasted,
but told me he could not stay when summer came, for then the Indians would be about;
and that if I could not go to the garrison,
I might go to a Friend`'s house that was near it;
and I was willing to please him if the Lord was willing,
and then applied my heart to know the mind of Truth, and it was shown me,
that if I moved again, I should lose the sense of Truth,
and I should never hold up my head again.
Still he would say it was a notion: till our dear Friend Thomas Story came and told him,
he did not see that I could have a greater revelation than I had,
and satisfied my husband so well, that he never more asked me to go,
but was very well contented to stay all the wars; and then things were made more easy,
and we saw abundance of the wonderful works,
and of the mighty power of the Lord in keeping and preserving of us,
when the Indians were at our doors and windows, and at other times;
and how the Lord put courage in you my dear children; don`'t you forget it,
and don`'t think that as you were young, and because you knew little,
so you feared nothing; but often consider how you stayed at home alone,
when we went to meetings, and how the Lord preserved you, and kept you,
so that no hurt came upon you.
And I leave this charge upon you, Live in the fear of the Lord,
and see you set Him always before your eyes, lest you sin against Him;
for if I had not feared the Lord and felt the comforts of
His holy Spirit I never could have stood so great a trial,
when so many judged and said I was deluded,
and that all the blood of my husband and children would be required at my hands;
but the Lord was near to me and gave me strength and courage, and faith to trust in Him,
for I knew His name to be '`a strong tower,`' yes, and stronger than any in the world;
for I have oftentimes fled there for safety.
O blessing and honour, and everlasting high praise be given to the Lord and his dear Son,
our Saviour and Mediator, Christ Jesus.
Amen.`"

[.signed-section-signature]
Mary Doe.

A neighbour of the aforesaid people +++[+++continues Thomas Chalkley,]
told me, that as he was at work in his field, the Indians saw and called him,
and he went to them.
They told him that they had no quarrel with the Quakers, for they were a quiet,
peaceable people, and hurt nobody, and that therefore none should hurt them.
Those Indians began about this time to shoot people as they rode along the road,
and to knock them on the head in their beds, and very barbarously murdered many:
but we travelled in the country and had large meetings,
and the good presence of God was with us abundantly,
and we had great inward joy in the Holy Spirit in our outward jeopardy and travels.
The people generally rode, and went to their worship armed,
but Friends went to their meetings without either sword or gun,
having their trust and confidence in God.

--

[.asterism]
'''

John Churchman, while on a religious visit to friends on the eastern shore of Maryland,
met an elderly man, who asked if he saw some posts standing, pointing to them, and added,
the first meeting George Fox had on this side Chesapeake Bay,
was held in a tobacco house there, which was then new;
the posts that were standing were made of walnut.
At which his companion rode to them, and sat on his horse very still and quiet;
then returning again, with more speed than he went,
John Churchman asked him what he saw among those old posts; he answered,
"`I would not have missed of what I saw for five pounds;
for I saw the root and ground of idolatry.
Before I went,
I thought perhaps I might have felt some secret virtue
in the place where George Fox had stood and preached,
whom I believe to have been a good man; but while I stood there, I was secretly informed,
that if George was a good man, he was in heaven, and not there,
and virtue is not to be communicated by dead things, whether posts, earth,
or curious pictures, but by the power of God, who is the fountain of living virtue.`"
"`A lesson,`" says John Churchman "`which, if rightly learned,
would wean from the worship of images, and adoration of relics.`"

[.asterism]
'''

The following is a remarkable testimony to the power
which attended the ministry of our early Friends.

A person of some note, who had been an officer under Oliver Cromwell,
related the anecdote to some people at an inn, among whom was James Wilson,
who thereby became more favorably disposed towards Friends,
and willing to attend their meetings,
he having been before that time much prejudiced against them.

[.embedded-content-document]
--

After the battle of Dunbar, as I was riding in Scotland at the head of my troop,
I observed at some distance from the road a crowd of people,
and one higher than the rest; upon which I sent one of my men to see,
and bring me word what was the meaning of the gathering;
and seeing him ride up and stay there, without returning according to my order,
I sent a second, who stayed in like manner; and then I determined to go myself.
When I came there, I found it was James Nayler preaching to the people,
but with such power and reaching energy, as I had not till then been witness of,
I could not help staying a little, although I was afraid to stay;
for I was made a Quaker, being forced to tremble at the sight of myself.
I was struck with more terror by the preaching of James Nayler,
than I was at the battle of Dunbar, when we had nothing else to expect,
but to fall a prey to the swords of our enemies, without being able to help ourselves.
I clearly saw the cross of Christ to be submitted to, so I dared stay no longer,
but got off, and carried condemnation for it in my own breast.
The people there, in the clear and powerful opening of their states,
cried out against themselves, imploring mercy, a thorough change,
and the whole work of salvation to be effected in them.
Ever since I have thought myself obliged to acknowledge on their behalf,
as I have now done.

[.signed-section-signature]
_James Gough`'s Journal._

--

[.centered]
=== A Glimpse at a Quarterly Meeting

At Masham in Yorkshire John Churchman lodged at the house of John Kelden,
who related to him something that passed between
a knight of the shire and one of his tenants,
a member of our religious Society, in manner following:

[.discourse-part]
_Landlord._
So, John, you are busy.

[.discourse-part]
_Tenant._
Yes; my landlord loves to see his tenants busy.

[.discourse-part]
_Landlord._
But, John, where were you,
that you were not at your quarterly meeting at York the other day?^
footnote:[The court sessions were held at York always at the time of the quarterly meeting.]
I saw most of your staunch Friends there, but you I missed.

[.discourse-part]
_Tenant._
Why, you know I have a curious landlord, who loves to see his tenants thrive,
and pay their rent duly, and I had a good deal in hand that kept me at home.

[.discourse-part]
_Landlord._
Kept you at home?
you will neither thrive nor pay the better for neglecting your duty, John.

[.discourse-part]
_Tenant._
Then I perceive my landlord was at quarterly meeting.
How did you like it?

[.discourse-part]
_Landlord._
Like it!
I was at one meeting, and saw what made my heart ache.

[.discourse-part]
_Tenant._
What was that?

[.discourse-part]
_Landlord._
Why, the dress of your young folks; the men with their wigs,
and young woman with their finery, in imitation of fashions.
And I thought I would try another meeting: so next day I went again,
and then I concluded,
there was little difference but the bare name between
us whom you call the world`'s people,
and some of you;
for you are imitating us in the love and fashions of the world as fast as you can.
So that I said in my heart, these people do need a Fox, a Penn, and a Barclay among them:
so he turned from his tenant.

[.small-break]
'''

"`I thought it would be a pity,`" adds John Churchman,
"`that the true and solid remark of this great man should be lost,
understanding that it was rather expressed in pity than derision.`"

[.centered]
=== Some Account of the Pestilential Fever at Philadelphia in 1699

[.section-author]
Taken from [.book-title]#Thomas Story`'s Life#

[.embedded-content-document]
--

We went after this to Jericho, Jerusalem, and other places, having meetings;
at Newtown we had a meeting,
in which Friends were much affected with trouble
at the account given by my companion Roger Gill,
in his testimony, of many being taken away at Philadelphia by a pestilential fever,
then greatly prevalent, ten being buried in one day, and four died on the same day;
several of them being good Friends;
his testimony was by way of warning to Friends in that meeting,
to be prepared to meet the Lord,
if peradventure the stroke of his hand might reach those parts.
And then Samuel Jennings reminded the meeting,
that it was no new nor strange thing for the people of God to suffer in common calamities:
but the love and favour of God being assured to them, whether life or death ensued,
as it might best please the Lord, there was no occasion of fear,
or to be dismayed at such things, especially to those who were prepared, as the apostle,
when he said, "`For to me to live is Christ, and to die is gain.`"^
footnote:[Phil. 1:21.]
And that,
since a translation through death to life is the exceeding great gain of the saints,
we have no ground to repine at the loss of their society here, though most grateful,
but rather patiently and with diligence wait upon the Lord,
till it may become our own lot.

From this time my companion was very desirous of
going to Philadelphia to the distressed Friends;
but I kept to our purpose, settled before we heard of their condition and exercise.
We went to New York, Wood bridge, and Burlington,
being met in the way by some Friends from there:
here we heard more and more of the sad effects of
the pestilential distemper still prevailing at Philadelphia.
My companion went from there directly to Philadelphia,
and after having some meetings in the way, I arrived there, and found him well,
but many Friends on their sick and dying pillows; yet much of the settled,
remaining presence of the Lord was with them at that time:
such is the goodness of God to his people, that in their bodily,
or any other afflictions, His holy presence greatly abates the exercises of nature,
by its divine consolation.

O the love that flowed in my soul to several in the times of my
visits to them! in which I was lifted over all fear of the contagion,
and yet not without an awful regard toward the Lord therein.
In this distemper had died six, seven, and sometimes eight a day,
for several weeks together; and the yearly meeting being to begin there next day,
we had some exercise and consultation about it,
arising from the prevalency of the distemper in the city at that time;
and yet not much in the country.
Some Friends had therefore written from Burlington,
proposing to Friends of Philadelphia that the meeting
should be adjourned to a cooler time;
to which it was answered, That till the meeting was come together,
they had no power to adjourn; but thought it might do well to discourage, in all places,
the great numbers of young people and servants that usually came to town on those occasions;
and such only to come as were necessarily concerned in the service of the meetings,
because of the great infection, and incapacity of Friends and inns in the town,
at such a juncture, to lodge and entertain them,
there being few (if any) houses free from the sickness.

In the morning meeting of ministers and elders, on the seventh day of the week,
at Philadelphia,
we were under great concern about holding of the
meeting in the usual time generally known,
or whether better to suspend it: and as we waited on the Lord for counsel,
the testimony of Truth went generally against the adjournment or suspension;
and the Lord`'s presence was greatly with us to the end,
though some opposition we met with from the prudentially wise men among us then present,
who consulted their own reason, but not the Truth; who has all power,
and can do and prevent what He pleases.

Accordingly the next day, being the first of the week, the meeting was held,
and was large, all circumstances considered; and the Lord so evidently appeared with us,
that there was no room left for doubt,
but that it was His will that we should hold our meetings; and serve God therein,
as well in time of adversity and affliction, as in prosperity, and less seeming danger.

Friends were generally much comforted in the divine Truth,
the fear of the contagion was much taken away,
and the testimony of Truth was exceeding glorious in several instruments,
as well as over the meeting in general, and so continued to the end: the first, second,
and the third days were for worship, and the fourth for business;
which was also managed in wisdom and unanimity, and ended in sweetness and concord;
as becomes all meetings of the people of God everywhere.

But that which was very remarkable, was,
that though the distemper was very raging and prevalent all the week before,
yet there was not one taken ill during the whole time of the meeting,
either of those who came there on that occasion, or of the people of the town,
that could be remembered by such Friends as made observation;
and yet presently after there were many taken ill thereof in town, and several died,
but few in comparison of what had died before; and a little after that,
it was finally stopped by the good hand of divine Providence.

My companion and I both remained in town for some time, visiting the sick Friends,
as we found it necessary or expedient:
and great was the presence of the love of God with this people,
in the midst of this trying visitation; which gave us occasion to say,
"`Good is the Lord, and greatly to be feared, loved,
and obeyed;`" for though he allows afflictions to come upon his own chosen people,
in common with other men, yet that which otherwise would be intolerable,
is made as nothing,
by how much the sense thereof is swallowed up and immersed in His divine love.
O the melting love!
O the immortal sweetness I enjoyed with several,
as they lay under the exercise of the devouring evil
(though unspeakably comforted in the Lord):
let my soul remember it, and wait low before the Lord to the end of my days!
Great was the majesty and hand of the Lord!
Great was the fear that fell upon all flesh!
I saw no lofty or airy countenance; nor heard any vain jesting, to move men to laughter;
nor witty repartee, to raise mirth; nor extravagant feasting,
to excite the lusts and desires of the flesh above measure:
but every face gathered paleness, and many hearts were humbled,
and countenances fallen and sunk,
as such that waited every moment to be summoned to the bar and numbered to the grave.
But the just appeared with open face, and walked upright in the streets,
and rejoiced in secret, in that perfect love which casts out fear;
and sang praises to Him who lives and reigns and is worthy
forever! being resigned unto his holy Will in all things;
saying, "`Let it be as you will, in time and in eternity, now and forevermore.`"
Nor love of the world, nor fear of death, could hinder their resignation,
abridge their confidence, or cloud their enjoyments in the Lord.

My companion now was taken ill, and appeared to,
be under symptoms of the common distemper.
Some meetings being appointed, I could not stay with him; and though he told me,
when I took leave of him, he was pretty easy, and not very ill;
yet I departed under a great load upon my spirit, and suspected the worst,
for he had prayed in the yearly meeting with great zeal and earnestness,
"`That the Lord would be pleased to accept of his life as a sacrifice for his people,
that a stop might be put to the contagion;`" and therein
appeared his great love and concern for Friends,
whom he had come so far to see.

I went to Burlington, and had a pretty large meeting at John Shin`'s;
and returning to Philadelphia in a few days, I found my companion very ill;
and my concern for the yearly meeting in Maryland increasing,
it came very near me to leave him in these circumstances:
but having duly considered every part, and finding I could not be of much service to him,
I took leave of him, though not without being greatly affected:
and in the company of several Friends set forward for Maryland,
having meetings in the way, and the Lord`'s comfortable presence was with us,
to the praise of his own holy name, who lives, and is worthy to reign forever!
In about a week`'s time I had the afflicting news of the death of my companion,
Roger Gill, at Philadelphia; at which my soul was greatly bowed, and my heart tendered,
so that the ground whereon I sat was watered with my tears;
in the conclusion whereof I was fully satisfied he had obtained
a crown of everlasting peace with the Lord,
and that his memory should not rot,
nor his living testimony fall in those American parts, wherein we had laboured together,
from Carolina to New England; where many hearts had been tendered by him,
and souls comforted, and several convinced;
and all through that divine power by which he is now raised to glory,
to sing praises to Him who sits on the throne, and rules, and reigns,
and is alone worthy forever and ever!
Amen!

This afforded matter of deep humiliation, and consideration,
how long and how often the Lord had spared me, and to what end;
since I have no interest in the world,
nor anything for the enjoyment whereof I could desire to live;
but that it may please the Lord and giver of life to spare mine,
till I may be more fit to appear with my accounts before him.

--
