== Chapter III

William Crouch in his memoirs has left on record a narrative,
which it is thought may be not devoid of interest to those readers,
who love to mark the rise and breaking forth of sacred Truth
in its various and successive manifestations on the earth.
It is as follows.

[.embedded-content-document]
--

About the beginning of the year 1654,
some workings of the power of Truth came to be felt among
some tender people in and about the city of London,
and some few were convinced and turned unto the Lord.
About this time two women, coming out of the north to the city, namely,
Isabel Buttery and her companion, by what providence I cannot tell,
became acquainted with Amos Stodart, (some time a captain in the Parliament army,
who when convinced of Truth had left his command,) and Simon Dring of Moorfields.
These women had an epistle or testimony, given forth by George Fox,
(the first inserted in the volume of his [.book-title]#Doctrinal Books,#
addressed "`To all that would know the way to the kingdom, whether they be in forms,
without forms, or got above forms`") which directed people to turn their minds within,
where the voice of God is to be heard: this epistle, being printed, they delivered,
or dispersed abroad to such as would receive it.^
footnote:[This tract has very lately been reprinted.]

This Isabel Buttery, and the other woman,
being in company with Amos Stodart and Simon Dring,
walking in the fields towards Stepney, were overtaken by Ruth Brow,
then about sixteen years of age, (who afterwards became my wife);
Isabel Buttery steadfastly looking on her, gave her one of the said printed epistles,
in the reading whereof she was convinced of the Truth,
and added to the small number who then did believe.
After this, these women had private meetings at Robert Dring`'s house, in Watling Street,
and at Simon Dring`'s in Moot fields, in which they did now and then speak a few words:
to which places my wife went with great expectation, and there met with Ann Downer,
afterwards Ann Whitehead, a worthy young woman, who grew in Truth,
and became an eminent instrument in the Lord`'s hand in her day,
as appears by several testimonies given of her after
her decease by sundry men and women Friends,
who were witnesses of her faith towards God, and service in his church.

Moreover, in the Fifth month of this year, 1654,
it pleased God to send two of his faithful messengers
and able ministers to the city of London,
namely, Francis Howgill and Edward Burrough,
who were the first that declared Truth publicly there,
and whom He made instruments in his holy hand for the gathering
of many that were "`waiting for the consolation of Israel:`" these,
upon hearing the glad tidings of the gospel, could say, "`We have waited for Him,
and we will be glad;`" and with good old Simeon,
who when the child Jesus was brought into the temple, took him in his arms,
and blessed God, saying, "`Now let your servant depart in peace;
for my eyes have seen your salvation: a light to enlighten the Gentiles,
and the glory of your people Israel.`"

Now, as the Lord was pleased to visit a tender seed in and about
the city of London by these his chosen instruments,
and as he opened the hearts of a remnant to receive the word of life and
believe in it,--such opened their doors for meetings in their houses,
and for some time it so continued, that they met from house to house.

And now they having sounded an alarm,
and proclaimed the great and notable day of the Lord, in the city and parts adjacent,
the Lord moved them to visit the nation of Ireland,
and the time being come for their departure from the city,
a meeting was appointed at Robert Dring`'s in Watling-street,
there to take their leave of their friends and brethren;
at which time there was great brokenness of heart,
and the melting power of God was among them, which caused great sorrow,
and abundance of tears to flow from the eyes of many tender plants.
There are yet living, at the penning hereof, that were than and there present, who do,
in a fresh remembrance thereof, give thanks and praise to God,
with a single and upright heart.

In the time of their absence and stay in Ireland,
the Lord was pleased to send others of his messengers and servants to the city of London,
namely, Thomas Aldam, Christopher Atkinson, Richard Hubberthorn, George Fox,
Alexander Parker, John Stubbs, Thomas Salthouse, and some others,
who published and declared the word of the Lord freely.

--

[.asterism]
'''

George Fox gave forth in writing a testimony concerning Thomas Taylor,
part of which is here transcribed.

[.embedded-content-document.testimony]
--

He had been an eminent parish priest, and of note among the professors and other priests,
and also a lecturer in several parts of the country, preaching sermons on the week days.
And he, coming to Swarthmore in Lancashire, with some other priests,
I asked him and them before Judge Fell, whether he or any of them could say,
that they ever heard a voice from God or Christ, from heaven,
that bid them go to speak to any people,
as God and Christ did to the prophets and apostles?
And Thomas said before them all, that he never heard any such voice or command.
And I asked him, what he preached to the people then?
He made answer, and said, His experiences.
I told him _his_ experience might not reach to every condition;
but he that had _the word of the Lord_ might preach it, whom God sent,
and _that_ would reach all conditions.
So the Lord`'s word and power struck him that he was silent;
but the rest of the priests were high and opposed, and came to nothing.
And Judge Fell wondered and was astonished at what he heard Thomas say,
that he had never heard the voice of God nor Christ
to command him to preach to any people;
the said Thomas Taylor being looked upon as a high priest, and above the common priests,
and a sober man, and beloved among the outward professors.
I went along with him that day to a place called Newton in Lancashire,
where he used to preach sometimes; and he was very much down, and sad,
and groaned that night.

And the next day we went to a meeting which we had in the worship house yard,
but he would have gone into the house, but the priest would not let us;
and I told him it was no matter.
And there came another priest from Underbarrow, and several others;
and Thomas sitting still, at last a tender spring of life sprang up in him,
and he spoke very well in it to the people, both of his own condition, and the people`'s;
and now how they must turn to the Lord Jesus Christ.

And the Underbarrow priest and some other professors were offended and opposed him;
but the Lord`'s power came over them all:
for he was looked on in the time of his priesthood to be above them.
And Thomas Taylor grew in the grace and truth of Christ,
and came to know the word of the Lord, and preached Christ freely,
as then he had received freely, and forsook his parish steeple-house,
and his old parish wages, and the rest of the priests that preached for hire;
and he travelled up and down in many parts of England,
preaching the word of the Lord and His gospel freely, as he was commanded.

--

The foregoing is a plain man`'s account of a plain matter of fact.
It is not set off by the beauties or power of language,
yet the unprejudiced reader discovering a native intrinsic excellency in the piece,
will not despise it because of its simplicity.
George Fox, who penned the narrative, it is well known,
was what would now be called an unlettered and a homely kind of man,
not accustomed to the refinement of the age _he_ lived in, much less to those of _our_ day:
partaking therefore in our view a certain roughness
or plainness in his mode of speaking and writing,
as well as in his general habits;
at the same time a _gentleman_ in the literal and strictest sense of the word,
a Christian in his manners and deportment,
endeavoring to his utmost to promote "`peace on earth, and good will towards men.`"
The subject to which he thought fit, in the present instance,
to direct the attention and discourse of his company, is one of great importance,
comprehending, it is believed, the most main characteristic of the ministry of Friends;
as such the passage is in particular recommended
to the serious consideration of our youth,
being calculated to convey much instruction without much formality.
It is indeed to be feared, whether some under our profession of riper years and judgment,
may not stand in need of being reminded by this simple relation,
that the minister of Christ must receive nothing short of _the word of the Lord,_
and when commissioned must preach it where and as he is commanded.

This view of the matter cuts short the elaborate
contrivances of most professors of Christianity,
to arrive at a supposed proficiency in preaching, by human skill.
Certainly it is holiness, an entire submission or yielding to the divine will,
so far as we know it,
and a quiet expectation and endeavour after further acquaintance with the same,
can alone prepare the soul to become (through mercy) instrumental
in the Lord`'s hand for the everlasting good of others.
Remarkable is the exemplification of this truth in the case before us.
Thomas Taylor was a man of erudition and piety;
he had been in the way of imbibing whatever a college education could impart;
and being strict in his profession,
was no doubt earnestly engaged in attaining all the helps and props,
which a ministry like that he had been brought up to evidently required;
yet he came to see by the fresh extended power of divine help,
that his views of the ministry were defective.
With the apostle he could say in the language of sincerity, "`That which we have seen,
heard, and felt, declare we unto you;`" he preached his experiences,
(as he acknowledged:) but he had not apprehended it his duty to look for the
manifestations of that "`Word of Life,`" of which the apostle there speaks,
through which alone the true preacher of the gospel is enabled
to administer effectually to the states and needs of his hearers.

The great Shepherd declared,
that "`his sheep _hear his voice_`" and that he calls
his own sheep "`by name,`" and "`leads them out.`"
And when he "`puts forth`" his own sheep,
he "`goes before them,`" and his sheep follow him, for they "`know his voice.`"
Nevertheless this zealous pastor confessed,
he had not been sensible of such distinct dealings towards him.
He no doubt spoke of good things to the people, perhaps with the best of motives,
but had he known the inward appearance and voice of Christ unto his soul,
and come under its directions and limitations in his religious services,
he would have preached, when he preached, with the authority of a divine commission,
even "`as the oracles of God.`"
Where a person professing the ministry,
is brought to see all his ability for real usefulness, all the good springing up in him,
to be wholly dependent on the particular and express
extensions of heavenly grace _at the time;_
where he is brought to resign himself to these without reserve on all occasions,
then may he most truly be said to be "`an instrument in the divine hand.`"

The effect and influence of gospel preaching in such an instance is often very striking,
as in that of Thomas Taylor, who in a short time became an eminent preacher of _the Word;_
and it may be said of him as it was of his holy Pattern and Teacher,
"`he spoke as one having authority,`" even "`in the demonstration of the Spirit,
and of power;`" many thereby were turned from darkness to the light,
prevailed on to bring their deeds to it, and enabled to walk in the same.
His writings will always be valuable to those who look for substance, not show;
something of the meekness and gentleness of Christ appears on the face of them:
there is also much Christian experience evinced in parts,
and what is very rarely seen in the productions of
those who have some share of literary acquirements,
there is throughout an uncommon simplicity of language and plainness of style,
with so little semblance of study,
that one might fancy his parentage and education
to have been as humble and homely as His,
who was called the "`carpenter`'s Son,`" or as his fishermen apostles.

[.centered]
=== Anecdote From John Richardson`'s Life

The governor of Virginia wanted a cooper to mend his wine, cider, and ale casks,
and some told him there was a workman near, but he was a Quaker; he said,
if he was a workman, he made no matter what he professed; so the Quaker, such as he was,
was sent for, and came with his hat under his arm:
the governor was somewhat at a stand to see the man come in after that manner,
and asked if he was the cooper he had sent for?
He said, "`Yes.`"
"`Well,`" said the governor, "`are not you a Quaker?`"
"`Yes,`" replied the man, "`I am so called, but I have not been faithful.`"
He then asked, "`How long have you been called a Quaker?`"
The poor man said, "`About twenty years.`"
"`Alas for you, poor man,`" said the governor, "`I am sorry for you!`"

[.embedded-content-document]
--

By this we may clearly see +++[+++observes John Richardson,]
that such who walk most up to what they profess,
are in most esteem among the more thinking and religious people;
and the unfaithful and loose libertine professors of the Truth are slighted,
and I believe will be more and more cast out as the "`unsavoury
salt,`" which is good for nothing in religion,
and is indeed trodden under the feet of men;
for great part of the men in the world have such
an understanding as to know what we profess,
and also what we should do and be, in many things.
Let us therefore walk wisely before all,
and not be "`an occasion of stumbling,`" nor give offence either to Jew or Gentile,
nor to the Church of God, that so we may be as "`a city set upon a hill,
which cannot be hid;`"--indeed, that may not desire to be hid,
but rather that the inhabitants of the earth might see our good works,
and have an occasion from there administered, to glorify the Father which is in heaven.

--

[.centered]
=== Anecdote From Thomas Ellwood`'s Life

[.embedded-content-document]
--

While I was in London I went to a little meeting of Friends,
which was then held in the house of one Humphry Bache, a goldsmith in Tower-street.
It was then a very troublesome time, not from the government,
but from the rabble of boys and rude people, who upon the turn of the times,
at the return of the king, took liberty to be very abusive.

When the meeting ended,
a pretty number of these unruly folks were got together at the door,
ready to receive the Friends as they came forth, not only with evil words but with blows;
which I saw they bestowed freely on some of them that were gone out before me,
and expected I should have my share when I came among them.
But quite contrary to my expectation, when I came out, they said one to another,
"`Let him alone; don`'t meddle with him; he is no Quaker, I`'ll warrant you.`"
This struck me, and was worse to me than if they had laid their fists on me,
as they did on others.
I was troubled to think what the matter was, or what these rude people saw in me,
that made them not take me for a Quaker.
And upon a close examination of myself, with respect to my habit and deportment,
I could not find anything to place it on,
but that I had then on my head a large mountier cap of black velvet,
the skirt of which being turned up in folds, looked, it seems,
somewhat above the then common garb of a Quaker;
and this put me out of conceit with my cap.

--

[.asterism]
'''

Samuel Bownas received a religious education,
his parents being upright and zealous Friends,
who suffered much for their faithfulness towards their Maker.

When a child his mother often took opportunities of admonishing him to a holy life,
and to the fear of God, as the only way of obtaining His favour and blessing:
and occasionally she would relate to him some circumstances
of his father`'s sufferings in times of persecution,
who had been removed by death before his son Samuel was a month old.
And when she took him to meetings,
where frequently she had a testimony to bear in public to the Lord`'s power and goodness,
he would particularly notice, when very young,
the tenderness and broken-heartedness that prevailed over those present,
and would enquire of her, why they wept so much, and why she wept.
But when placed out as an apprentice, though with an honest loving Friend,
he grew up with very little consideration about religion, or any taste of it,
addicting himself to the pleasures of the times.
And when at meeting, for lack of a proper engagement of mind,
he often spent those precious opportunities of religious improvement in sleep;
for preaching, of which there was much, he took slight account of.
Thus passed two or three years of his apprenticeship,
with very little inward sense of God or religion.
He was indeed considered a witty and sensible young man,
(for he took much liberty in discourse,) but often on his
bed he ruminated on his way of life with reluctance,
yet fell into the same course again and again.

No one could charge him with any gross vice; but what he gave way to most,
was jesting and foolish talking, and turns of wit to provoke mirth,
which the apostle tells us are not convenient;^
footnote:[Eph. 5:4.]
and he often found it so after it was over,
and that "`the end of that mirth was heaviness of heart.`"^
footnote:[Prov. 14.13.]
However, the Lord who is rich and plenteous in mercy, even to the rebellious,
gave him a remarkable visitation,
which no doubt he remembered with gratitude through life,
as it appears to have been the means of awakening him to a sense of his condition,
and impressed him with the most deep conviction of
the necessity of a change of heart and life.

For being one first-day at meeting, Anne Wilson, a young woman, was present and preached.
She was very zealous, and Samuel looking upon her,
she with great energy pointed her finger at him, uttering these words with much power:
"`A traditional Quaker, you come to meeting as you went from it,
and you go from it as you camest to it,
but are no better for your coming:--what will you do in the end?`"
This language came so home to his state at that time,
that like Saul it might be said he was smitten as it were to the ground,
being pricked to the very heart; and turning his mind inward, he cried in secret.
"`Lord, what shall I do to help it?`"
when a voice spoke within him, "`Look unto me,
and I will help you:`" then he found such comfort
to flow through him as made him shed tears abundantly.
From that day he experienced the scriptural assertion to be true,
that "`what is to be known of God`" and true religion "`is manifested within:`" for
upon this eventful circumstance his conduct and even his countenance became much altered,
his soul being bowed down under heavy exercise,
so that he could neither eat nor sleep as he used to do; yet, he writes,
his work never succeeded better in his hands than it did at that time,
nor was his mind ever less in it.

He longed for the next meeting-day, and when the hour of meeting came,
his mind was soon fixed and stayed upon the one great Object of worship and dependence,
and he felt therein an uncommon enjoyment and satisfaction.
Relying on the Lord for strength and salvation,
who had begun thus wonderfully to reveal His power in him,
his understanding seemed opened, and all his faculties so sensible,
that he appeared to himself another man,
a divine and spiritual sweetness abiding with him night and day for some time.
The scriptures also became wonderfully clear and plain to his view,
and the truths of the gospel, therein spoken of, he readily understood and embraced,
so that in a very short time the Lord engaged him
with a concern to preach those truths to others;
and through faithfulness in that service his ministry was blessed to many.

[.asterism]
'''

Humphrey Smith, a valuable minister of our Lord and Saviour Jesus Christ,
and patient sufferer for his gospel cause, even to imprisonment and death,
gave forth a short and impressive address to "`_All parents of children_ upon the face
of the whole earth,`" which was printed with his collected writings about the year 1683.
It contains some valuable remarks in the shape of exhortation,
a few of which are subjoined:
but the parts most consonant with the design of this compilation,
are those in which the writer makes mention of certain _circumstances_ or _incidents,_
relative to his own conduct and experience in very early life.
_These_ are lively illustrations of his meaning;
they prove that simplicity of heart and sensibility
of conscience form the best groundwork in youth,
and are capable of being easily wrought on and regulated for the highest purposes.
To such also who admire the sobriety of deportment and quiet regulated habits,
usually to be met with among the children of Friends,
the extracts that follow may be interesting and useful;
they may explain and enforce some practical views which this Society has always taken,
and may elucidate in what manner these views result from
their _"`grand tenet`"_ the Life of God in the soul of man.

It is scarcely needful to notice,
that Humphrey Smith knew nothing of Friends at the time of which he speaks;
indeed he became a public preacher among the high professors of that day,
before he joined our Society.

[.embedded-content-document.address]
--

This do I know, that in many tender babes and young children, there is a meek, innocent,
harmless principle from God, who wills not the death of any;
and they have a light from Christ that enlightens every man that comes into the world,
which light is _in them._
He said, "`Let the little children to come me,
and do not forbid them,`" for of such who come unto Him
that is meek and low in heart "`is the kingdom of God.`"
Therefore you should allow them to come unto and
keep unto that which is meek and low in the heart;
"`for that which may be known of God is manifest in them.`"
Christ, the Light, had a love to little children, and said,
"`He that will enter the kingdom of God must become as a little child.`"
Therefore as you love their good, both of soul and body, see that you bring,
and in all things keep them to _God`'s witness in them,_
and that will judge and reprove them for any evil they have done,
and will keep them more out of all evil, than you by any other reproof can do,
and will show them that
your chastising for any evil is just, when done in the true moderation,
not exceeding the offence committed,
nor proceeding from the least motion of the _wrathful nature_ in you.

And that you may the more consider my words,
and come into moderation and the wisdom of God, to walk exemplarily before your children,
and to be to them patterns of gravity, meekness, and sobriety,
therefore shall I set before your eyes some plain and simple
truths of my own experience when I was a child.

My heart was much affected with tenderness,
and tears were as my food and drink night and day;
and often was my heart refreshed with love from God,
when I came unto _that_ which came from Christ, the "`Man of sorrows.`"
But many despised my tears, and vilified my mournful state,
not knowing (as they said) what was the matter with me;
and much provocation was used to get me out of that condition,
and as I grew up to hurry me _into the earth:_ and by the violent, fierce,
wrathful nature that ruled in others, was my quietness disturbed,
which begat wrath and anger in me again towards them;--this may be a warning to you:
yet something of God in me was not wholly overcome.

The first words according to scripture that pierced my heart, and remained with me, were,
"`He has filled the hungry with good things,
and the rich he has sent empty away:`" which words
remained as a thing printed and sealed in my heart.

The love of God was exceeding prevalent upon my little tender heart;
and so much the greater was my grief, when by the earthly-mindedness,
and wrathful hasty nature in parents and others, I was even forced out of it,
and provoked to wrath, grief, and discontent,
and so not permitted to come to nor keep with Christ, who says,
"`I am the Light;`" which light I felt to be _meek and low in the heart._
Therefore was my trouble great many times,
and wrath and hastiness began to have entrance in me; which being sensible of,
and finding a love towards God to be much more precious than anything of the world,
and having a hope towards Him, when I was but a little child, I would often pray to God,
even earnestly did I pray with tears, and my heart was opened with His love.
I would also sometimes make my complaint to Him in secret upon my knees,
when I could get into such a place that none could see me, nor come to know it:
and sometimes as I went along the way, when it came into my heart,
then would I even (as it were) _beg and cry with many tears,_ and had _boldness towards God,
as towards a familiar friend,_ though much in submission and fear, as one unworthy,
because I had sinned against him.
And for these things I had no creature to be my example, nor to learn it of;
and not knowing of any that did the like, I dared not let any know of it,
nor why I so often wept, when any saw me; for I saw none but despised that condition,
and were insensible of my state.

And thus, not having any that were sensible of that tender _principle of God_ in me,
to cherish that, or be a help to me in it,
the evil earthly thing that was begotten in me was nursed up
by that nature my leaders were in; so that as I grew in years,
_that_ was apt to grow in me,
(my father being more eager than most men in labouring and caring for earthly
things,) and so the tender principle of God in me was veiled from me,
and I became in after years as a child of wrath, _disobedient to God._

And this I write to be an example unto you, and a warning,
that you may not bring your children into the like alienation, torment, and condemnation,
which I was brought into,
especially as few afterward return to God with all their hearts,
and enter in at the strait gate.
So train them up in the fear of the living God,
that you may have comfort in them at the last,
and that they may grow up in the wisdom of God, to rule over such outward earthly things,
as the Lord or you may commit to their hands.

Therefore that it may go well with them and you,
and that God may do them good at the latter end,
let all your children everywhere be trained "`in
the way they should go,`" which way is Christ,
and He says,
"`I am the Light;`" and his light in them will let them see that they should not lie,
nor speak wicked words, nor do any violence one to another:
it is in this light they come to _know_ God and _hear his voice,_
for God speaks by Him that is the Light.
God called Samuel, being yet a child, and Eli bid the child answer the call of the Lord.
And the child who answered the call of the Lord reproved old Eli the priest.
Those sons of his were sons of Belial, and knew not God, and it is remarkable
they were the first priests that ever took tithes by force,
and they came to an untimely death, under the judgments of God, as did their father,
__+++[+++who restrained them not].__

And take heed how you cause or allow your children to babble many vain words,
with a delight to hear them prattle when there is no need;
for thereby afterward the tongue becomes "`an unruly member, set on fire of hell,`"^
footnote:[James 3:6.]
as I found, and bore the fierce indignation of the Lord for it.
Their words and yours should "`be few, seasoned with salt,
that they may minister grace to the hearers;`" for to God
an account Must be given for "`every idle word.`"
Many little children would not come to speak so many vain and evil words,
which _"`corrupt`"_ the _"`good manners,`"_ if they were not much provoked thereto,
and if they did not see people delight to hear them speak subtle crafty words.
Some indeed send their children from home to have them learn subtlety and craft,
and how to be too hard for others; then they say of such,
they can live by their wits and forecast or shift for themselves,
oftentimes indeed to deceive others; yet in some of these there is such a plain, honest,
simple principle, that they cannot be brought into this volubility
though they themselves have much endeavoured to attain it;
these sometimes could not defend their own cause, when it was just,
but have been pleaded down by others that had more of the serpent`'s subtlety;
they have been more plain and simple, and the Lord preserves the simple.^
footnote:[Ps. 116:6.]
In this also I have had much experience.

For when very young I saw much into the vanity of needless words,
and was very backward a long time in speaking,
and in that and some other things much differing from other children,
many thought I would have been a fool, as they call it,
who despise "`the foolishness of God;`"^
footnote:[1 Cor. 1:25.]
and therefore oftentimes much means were used to cause me to speak,
and many provocations long together, and yet not all scarce made me to speak a word,
tor I saw that it was needless; neither could I ask one _how he did,_
when I saw he was well, nor answer that which was needless.
And when I was a little grown up, and sent upon any small errand,
I would deliver my message in very few words,
so that people thought I should never be like a man.

At about ten years of age, my father _in the flesh_ would sometimes send me to market,
and it was long before he and all others could make me ask
any more than the price he allowed me to sell at:
or if he did not set me a certain price,
then I would resolve on a price in my mind according as I saw the market,
and so I often sold with the cheapest, being unwilling to take too much,
and therefore was often esteemed and called a fool and a dunce:
but it had been easier for me, if I had never been drawn out of that state,
wherein I was taught of God, _to do unto others as I would be done unto._

I was also fearful to strike anyone, but rather gave way to them that struck me,
and so was by many of my equals abused:
and it was hard for me to take away the life of any creature,
and I pleaded much against it with my father and mother, when they commanded me to do it,
though it were but to kill a young dog or cat, or the like;
my life in me was grieved to do it, and much was I forced to harden my heart,
before I could do any such thing, though commanded by my parents:
which may be a warning to all parents,
that they be not the cause of the hardening of their children`'s hearts,
and then say of them, they are hardy lads;
for that which _hardens the heart separates the heart from God,_
who is _love_ and from Christ who came to _save the life,_
and so _the sacrifice of God_ is not known, which is in _the broken heart,_
but the Lord is with the humble and the brokenhearted.
Take heed also of provoking your children to disquietude,
neither disturb them when disposed to be quiet;
for many are not content to see them sober and quiet,
but provoke them to lightness and vain pleasure, when they would be sober, like lambs;
for it is written, "`In quietness and rest shall you be saved,`" and,
"`_Study_ to be quiet,`" and, "`Commune with your own hearts, and be still.`"

When a child, I would often sit or stand quiet _long together,_
pondering many things in my mind, and as I grew up, if I were not disturbed,
for an hour or some hours I would sit quiet, either _waiting on the Lord for counsel,_
or searching which motion^
footnote:["`Impulse or impression`"--Johnson.]
in me to be guided by.
And when I have been riding along the way,
when I have found the right thing in me did not lead me,
I have turned back and not rode that journey.
And my _silent sitting_ like a fool, my father has often called _studying,_
and has often sharply reproved me for it, saying, by way of reproach,
I would surely study to be some great preacher.
And my mother has come to me, it is likely hundreds of times,
both when a child and a young man, and in her pity laid hands upon me,
and bid me not sit _studying so,_ for surely I would make myself a fool;
not knowing what my condition was.
And being so usually disturbed and grieved, sometimes on first days, or when I could,
I would get into some wood or place so private, that none should find me,
and there wait in quietness three or four hours:
and sometimes the love of God would break through
me and His Word would make my heart soft,
and I felt the _same then which now is my life;_ for now I know,
that "`those that wait on the Lord renew their strength;`"^
footnote:[Isa. 40:31.]
and though it is written, The Lord was weary of the people`'s sacrifices,
and with their words,^
footnote:[Mal. 2:17.]
yet it was never written, The Lord was weary of those that waited upon Him.

Therefore you should allow your children to wait upon God, or at least to be quiet,
for "`that which may be known of God is manifest in them.`"^
footnote:[Rom. 1:19.]
And the Lord has not left himself without a witness in every conscience;
for it is Christ __is given for a Witness,__^
footnote:[Isa. 55:4.]
and _His_ light shines in their hearts, who says,
"`Come unto me,`" and "`Learn of me;`" for He is the Shepherd and Bishop of souls,
who teaches all to profit.^
footnote:[Isa. 48:17.]
And He is that true Prophet of whom Moses spoke, which whosoever hears not,
the soul is cut off; and certainly my soul was cut off from the life,
when I was forced from hearing His voice in me, who is a man of sorrows,
and as a lamb dumb.
Therefore take heed of provoking your children to hearken to a stranger,
or another teacher than He that is a living minister within the veil;
and the veil is over the heart,^
footnote:[2 Cor. 3:15.]
where I have found that instructor that shall never be removed;
but all teachers without may be removed, and priests and men may die,
but this abides a priest forever, being made by the power of an endless life.^
footnote:[Heb. 7:16.]

So now all such as come to know something of God in them,
they also come to sit in silence and quietness, to receive instructions from God.
This is no new thing invented by the will of man, or learned one from another,
but is the same with that which guided the prophets,
and was in my heart from God even when a child:
and I do affirm that I had never returned out of that degenerate state,
into which I was hurried, if I had not waited in,
and been obedient unto the light of Christ which was in me from a child.
And you may all mind, that all along there has been something in you,
which in secret reproved you for sin, and let you see the sins of your youth,
and that is the _light of Christ, the Son of God,_ who, "`so loved the world,
that he gave his Son a Light into the world;`" which
light is in the conscience of a child,
and will testify against him, after he has done evil,
and _his countenance will fall like Cain`'s;_
but before they have done evil they are not ashamed, as Adam was, being innocent.

This was my teacher when I knew no other, and before I knew what it was;
this is that which _comes from God,_ and is not put in them by man or human learning,
but men by their eloquent speeches and vain deceit may lead them forth from _that_ in them,
and so break the command of Christ, who said, "`Go not forth.`"^
footnote:[Matt. 24:26.]
And when they are led forth after "`Lo here`'s`" and "`Lo there`'s,`" from the Rock,
which is Christ, and from the sure foundation, which _God has laid,
and no man can lay another,_ they despise this precious corner-stone,
refusing this light which shines in their hearts to give the knowledge of God,
and thus they are liable to follow any devised fables, and imaginations, and sects,
and opinions, and to be scattered upon every dry, barren, and dark mountain,
as the Lord knows I long was, not knowing where to find rest.

For having been led out from my true guide, and the tender motions of it quenched,
whereby at first I could pray _with the Spirit,_
as in measure the Spirit that was within me helped my infirmities with sighs and tears,
then, after I grew up, I was taught to say prayers,
and some that others learned out of books; and this they laid upon me to say every night;
but I found it was as a dry heath, instead of a honey comb.
And so being led on in a form, and to look after things and teachers _without,_
the light _within_ became darkened,
as also my understanding of the Son of God`'s love _shed abroad in my heart._

And being sometimes sensible of this,
I began when very young to look after priests and sermons,
and thought to have found the true thing there;
but they did me more harm than all the rest,
and led me farther from my teacher than ever,
and from the sense of the feeling after God,^
footnote:[Acts 17:27.]
to _find Him_ near me, and begot in me abundance of the serpent`'s subtlety;
and the more so because I, being sensible of a deficiency in me,
received their fair speeches with much eagerness and earnest desires,
believing them that _that_ was the way to peace;
so that I grew much in that _knowledge which puffs up,_
and this did indeed increase my sorrow.
Thus by them was I deceived, the Lord God knows I lie not,
but speak the truth in _plainness, having no envy towards any of their persons:_
and this is the very truth of my heart, that it was harder for me to leave, and deny,
and know redemption out of that, which I learned from and among the priests,
than to leave the fruits of all the sin that ever by temptations I did run into.

Therefore let the Lord God be the teacher of your children,
who has given them life and being, and a better teacher you cannot provide for them,
nor direct them unto: let _Him_ then lead them^
footnote:[See Ps. 43:3]
and guide them in his fear;
for thus they will see they should be faithful and diligent unto you in all things.
And you should not require of them many other things, lest you grieve them,
but be examples of righteousness unto them in all your words and actions.
And if you are not able to send them to school to learn to read,
yet they have the light from Christ in them already,
and that will show them plainly of the Father,^
footnote:[John 16:25.]
for the way-faring man, though a fool, cannot err in that path.
And though you set them to school ever so long to read and write,
and with their learning to search the scriptures, which is good,
yet they are to come to Christ the Light, that they may have life,
and they are to learn of him and to follow him,
so as to know him to be _in them the hope of glory,_
and the way out of sin unto the Father,
to obey him in all the manifestations of his will.
Then will it go well with them, and they will come to receive a blessing from God,
and be a blessing to their parents who fear him,
and at last in God`'s everlasting covenant lie down in peace and rest.

--

[.asterism]
'''

John Woolman, in the memoir of his life,
gives the following account of the Lord`'s healing
power being remarkably extended towards him;
and it is one of the many which might be brought forward
to encourage the poor sufferer on his bed of languishing,
though he may have as it were "`the sentence of death`"^
footnote:[2 Cor. 1:9.]
in himself, yet to trust in the living God, and be resigned to bear and do his will;
for "`blessed are they that do His commandments,
that they may have right to the tree of _life._`"

[.embedded-content-document]
--

It pleased the Lord to visit me with a pleurisy; and after I had lain a few days,
and felt the disorder very grievous, I was thoughtful how it might end.
I had of late, through various exercises,
been much weaned from the pleasant things of this life; and I now thought,
if it was the Lord`'s will to put an end to my labours,
and graciously receive me into the arms of his mercy, death would be acceptable to me;
but if it was his will further to refine me under affliction, and make me, in any degree,
useful in His Church, I desired not to die.
I may with thankfulness say, that in this case I felt resignedness wrought in me,
and had no inclination to send for a doctor; believing if it was the Lord`'s will,
through outward means to raise me up,
some sympathizing Friends would be sent to minister to me; which were accordingly:
but though I was carefully attended, yet the disorder was at times so heavy,
that I had no thoughts of recovery.
One night in particular, my bodily distress was great; my feet grew cold,
and cold increased up my legs towards my body;
and at that time I had no inclination to ask my nurse to apply anything warm to my feet,
expecting my end was near; and after I had lain ten hours in this condition,
I closed my eyes, thinking whether I might now be delivered out of the body;
but in these awful moments, my mind was livingly open to behold the Church;
and strong engagements were begotten in me,
for the everlasting well-being of my fellow creatures;
and I felt in the spring of pure love, that I might remain some time longer in the body,
in filling up according to my measure, that which remains of the afflictions of Christ,
and in labouring for the good of the Church;
after which I requested my nurse to apply warmth to my feet, and I revived.

--
