== Chapter IV

=== Extracts From James Gough`'s Life, on the State of our Society

"`God has said, I will dwell in them, and walk in them; and I will be their God,
and they shall be my people.
Therefore come out from among them, and be separate, says the Lord,
and touch not the unclean thing; and I will receive you and will be a Father unto you,
and you shall be my sons and daughters, says the Lord Almighty.`"
2 Cor. 6:16, etc.

By this call were our honorable predecessors in the beginning
separated from the spirit and ways of the world,
and incited to refuse touching the unclean thing,
or whatever sprang from an impure source,
what persecution soever that refusal might cost them;
knowing that He whom they obeyed and in whom they trusted,
would carry them through all opposition;
this they experienced to their unspeakable joy to be fulfilled,
and testified to the world, many of them, both living and dying.
In those days the meetings of Friends were more eminently favored with divine power,
as they lived more devoted to Christ,
and consequently more abounding with His love flowing in their hearts.

I remember when a child^
footnote:[James Gough was born in the year 1712.]
some whose very countenances seemed to command awe,
and impress observers with serious consideration;
as "`the salt of the earth,`" seasoning those among whom they walked,
with a sense of the Truth which lived and predominated in them.
Those happy men and women left the Lord`'s vineyard (through their faithful
labors with the divine blessing upon them) well fenced and clean,
(having gathered out the stones thereof,) and abounding
with the excellent fruits of the holy Spirit of Christ.

At my first going +++[+++to Ireland about the year 1737,]
there were yet living in most parts of the nation, where meetings were settled,
some of the good old stock, both ministers and elders, who loved God and mankind,
and were esteemed and beloved, being kind and open-hearted,
as well as faithful and circumspect in all branches of our Christian testimony,
closely uniting in tender love one with another in supporting
and keeping things in good order in the Church.
Their pious care herein was like a fence about the flock,
which kept them together in nearer unity and greater safety,
so that the young people in most parts were generally trained up
in innocence of manners and in plainness of habit and speech.
In process of time these worthy men and women,
in whose hearts the love of God and his people had by long growth become deeply rooted,
one after another honorably finished their course
leaving an excellent savour behind them;
but when they were removed, very few of the youth or others,
succeeded them in the right line, to fill up their vacant places with propriety.

Of their survivors, on the one hand,
a considerable number retained the ancient plainness of language and habit,
and rigidly censorious of any deviation therefrom, valued themselves upon this,
as if it were the only test and badge of discipleship;
while their hearts were gone after their covetousness,
in eagerly pursuing and sordidly hoarding temporal wealth.
On the other hand, a large body of youth and others were shooting up in self-indulgence,
in conformity to the world and rushing headlong into the temptations of the times.
Yet, amidst this inundation of negligence and revolt,
there remained in most places a number of sincere-hearted Friends,
a few worthy ministers and elders: but within these twenty years past,
there has been a great alteration for the worse.
The love of God in many waxes cold!
How they make light of religious duties!
What a slender attendance of week-day meetings for the worship of God,
as well as those which are held for our united care of the good of the Body.
So that it may now be said of many, as in sorrowful days formerly,
"`The ways of Zion mourn, because none come to her solemn feasts.`"

Again, what restlessness in meetings, what outward indications of spiritual indolence,
of absent or wandering minds, of neglect of the awful duty of worship,
due from us to our great Creator.
What gazing about, or falling asleep!
What violations of our Christian testimony in its sundry branches,
what weakness in conduct, and inconsistency with that divine principle which we profess.
Again,
how many in these perilous days run back and draw
others with them into the vanities of the times,
into a conformity with the world, both in dress and address,
into the company of such as indulge the same dispositions,
till the plain honest manners of sincere and affectionate Friends are falling into disuse,
being such as some are ashamed of.
From these pernicious liberties have proceeded mixed marriages,
running out to the priests, confusion in families,
affliction and anguish of parents,--painful wounds to our Christian Society.

If we look over our Society in this nation,^
footnote:[Ireland.]
and take a view both of those who are plain in dress and who are otherwise,
how many have their minds fast rooted in this present world,
devoting all their talents to it, rejecting the counsel of Christ,
who directs us to "`seek first the kingdom of God.`"
Hence, in some places, what poor lifeless meetings!
How little of the sacred fire of divine love burning!
How little of the glory of God shining!
No living minister left among them, and scarce one living member of the body of Christ,
to feel for the others and take some tender care of them for their good;
their lamps gone out, and scarcely any oil retained in a single vessel.
Thus have some meetings died away and are lost;
and others appear to be in a languid sickly condition,
seeming scarce likely to live long,
except they timely apply to the great and good Physician,
who is both able and willing to restore life, health, soundness and vigour,
to raise up "`judges as at the first and counsellors as at the beginning.`"

=== Narrative of Thomas Chalkley, When a Child

I may not forget the dealings of God with me in my very tender years.

When between eight and ten years of age,
my father and mother sent me near two miles to school.
I went mostly by myself to the school;
and many and various were the exercises I went through
by beatings and stonings along the streets,
(being distinguished to the people, of what profession I was,
by the badge of plainness which my parents^
footnote:[Thomas Chalkley states,
"`I was born of honest religious parents who were very careful of me,
and brought me up in the fear of the Lord, and oftentimes counselled me to sobriety,
and reproved me for looseness and that light spirit which is incident
to youth they were very careful to nip in the bud;
so that I have cause to bless God through Christ on behalf of my tender parents.`"]
put upon me,) some telling me, it was no more sin to kill me than it was to kill a dog.

About this time the Lord began to work strongly on my mind by his grace,
insomuch that I could not forbear reproving those lads,
who would take the name of the Lord God in their mouths in vain;
reminding them of the third commandment,
"`You shall not take the name of the Lord your God in vain,
for the Lord will not hold him guiltless that takes
His name in vain,`" and of Christ`'s saying,
"`Every idle word that men shall speak,
they shall give account thereof in the day of judgment;`"
for which I was mocked and derided by some,
and others would sometimes refrain from such bad words when I reproved them.

One time, I remember I was among some men, one of whom I had reproved,
and he told the rest of it, and turned to me, and said, that I was no Christian,
and asked me when I said the Lord`'s Prayer; I asked him, if he said it; he said, yes.
I then asked him, how he could call God Father,
and be so wicked as to swear and take God`'s name in vain,
which I had often heard him do; and I told him what Christ said to the Jews,
"`You are of your father the devil,
and the desires of your father you want to do;`"
and that those that did the devil`'s work,
could not truly call God Father, according to Christ`'s doctrine.
So being convicted in their consciences that what I said was true, they were all silent,
and wondered that I, being so young, should speak in such a manner:
in which I remember I had great peace and good satisfaction;
and from thenceforth these men let me alone.

[.asterism]
'''

William Penn, during a season of intense cold, soon after his arrival in America,
when the fields are described to have been as cakes of ice, slept one night at Merion,
where a boy about twelve years old, son of the person at whose house he lodged,
being a lad of curiosity, and not often seeing such a guest as William Penn,
privately crept to the chamber door, up a flight of steps on the outside of the building,
which was only a log-house.
On peeping though the latchet hole, he was struck with awe,
in beholding this great man upon his knees by the bedside, and in hearing what he said,
for he could distinctly hear him in prayer,
and in thanksgiving that he was then provided for in the wilderness.
This circumstance made an impression upon the lad`'s mind,
which was not effaced in old age.

=== The Unchangeable Teacher

From Benjamin Bangs`' Memoirs

After the conclusion of the Dublin half-year`'s meeting, in the third month, 1683,
I intended to have returned to England,
and in order to it I sold my horse and prepared for the voyage;
but the wind proving contrary, I could not get off; and besides,
I found some stop in myself, a further service being presented to my view;
to which I gave up, though much contrary to my inclination.
It fell with some weight upon me to have a meeting at Tralee in the county of Kerry.
Accordingly I set out from Dublin, taking meetings in the way, and went to Cork,
and from there to Tralee (a journey of 158 miles,)
and had a comfortable opportunity there;
many hearts were tendered, the Lord`'s presence attending;
after this I visited several meetings in Leinster province, and went to the north again.
As I was going from Antrim to the Grange, I saw ten or twelve men upon the road,
walking in a very solitary manner; and it arose in my heart,
"`These are sheep having no shepherd.`"
When I came up to them, I slackened my pace, and queried of them, "`What news?`"
The men were startled at the question, and answered,
"`We know of none;`" continuing to go softly, I said "`Are you going to a meeting?`"
they answered, "`Our minister is silenced;
for orders are come down commanding all dissenters not to assemble;
so now we have no teacher.`"
This brought to my remembrance what I had been concerned
to deliver at an evening meeting I had at Antrim,
where I met with much rudeness, namely, "`The time draws nigh,
that you will be blown away like chaff before the summer threshing-floor,
and the place of your meeting will not be found.`"
At this time all dissenters, except Friends, had declined keeping up their meetings.

I proceeded to discourse with the men, and said,
"`The hireling flees because he is a hireling,
and cares not for the sheep;`" referring them to the text, John 10:11-13;
and further showing them,
that it is happy for those who are come to the knowledge of that Teacher,
which cannot be removed into a corner.
God said he would teach his children Himself;
and the children of the Lord are taught of the Lord.^
footnote:[See John 6:45, and Isa. 54:13.]
And they might read in the 1st epistle of John 2:27,
"`The anointing which you have received of him abides in you,
and you need not that any man teach you,
but as the same anointing teaches you of all things,`" etc.
And in Titus 2:11. 12; "`The grace of God,
that brings salvation has appeared unto all men, teaching us.`"
Thus I labored to bring them from their hireling teachers,
to the teaching of God and Christ in themselves,
by which they might come to the knowledge of God, and walk in the ways of his salvation;
for the "`manifestation of the Spirit is given to every man to profit withal,`"^
footnote:[1 Cor. 12:7.]
advising them to turn their minds inward, and mind the secret operation of it,
whereby they would find, through a lively experience,
that it checks and reproves for bad words and actions; and as they turned to that,
they would find it would lead them into all truth; with many words to this effect.
They were well pleased with this discourse, declaring at parting,
that they had never heard things so opened to them in their lives.

=== The Seaman`'s Best Anchor

From Thomas Chalkley`'s Journal

After some few months I acquainted my wife and my father, with her father and mother,
that I thought it my duty to go over and live in America.
To which proposal my father consented, though with tenderness of heart,
considering that I must be so far separated from him;
I also laid it before the monthly meeting of Friends at Horslydown,
of which I was a member, who consented to it, though somewhat unwilling to part with us;
and gave us their certificate,
to let our brethren know that we were in love and unity with them,
and walked according to our profession.
And when we were in order for going,
we agreed for the freight of our goods and servants in a vessel bound for Maryland.
When it was at Gravesend, and ready to sail,
several of our dear friends and relations accompanied us to the ship,
on board of which we had a good meeting, and took our solemn leave of one another,
as never expecting to see each other any more in this world.
It was a solemn time indeed! we prayed for one another and so parted,
our ship sailing that evening, and we got to Margate Road, where we anchored;
and the wind sprung up very fresh, and blew tempestuously, so that we broke our cable,
and lost our best bower anchor, and drove violently towards the Goodwin Sands.
We let go our sheet anchor and three more, which were all we had,
but they did not stop her;
upon which the master ordered the carpenters to stand
by the main mast with their axes on their shoulders,
and when he gave the word, then they were to cut the mast.

The people in the ship (there being many passengers) were in great consternation,
expecting nothing but death; one of the passengers came weeping and said,
our case was very bad.
The doctor also came in the same manner, and cried, "`O Mr. Chalkley,
we are all dead men!`" then I thought with myself
I would go on deck and see what the matter was;
and when on deck I went to the pilot, who had the lead in his hand, and he sounded,
and cried out, "`Lord have mercy upon us! she is gone, she is gone,
she is gone!`'`" by which I perceived we were very near the Goodwin Sands,
on which many ships have been lost with all their crew.
In this sense of danger I sent for all the passengers into the cabin, and told them,
that I thought it would be well for us to sit still together, and look unto,
and wait upon God, to see what he would be pleased to do for us; that if death came,
we might meet him in as good a frame of mind as we could,
and not be surprised beyond measure.
And as we were thus composed in our minds, a concern came upon my dear wife,
and she prayed to God the Father in the living power and sense of his Son,
and He heard from his holy habitation, and answered the prayer; for immediately after,
the wind abated and our anchors held us.

This was a great deliverance, which is not to be forgotten.
When we saw the longed-for morning, we were very near the sands,
and the sea ran prodigiously high, and broke upon them mightily,
so that we were forced to leave our cables and anchors,
and make the best of our way to Deal.

=== Reliance on Providence

From the Same

After I had finished my concerns in England I embarked in the sloop Dove,
for Philadelphia, she being consigned to me in this and the former voyage.
It being often calm and small winds our provisions grew very scanty.
We were about twelve persons in the vessel, and but one piece of beef left in the barrel;
and for several days; the winds being contrary, the people began to murmur,
and told dismal stories about people eating one another for lack of provisions;
and the wind being still against us, they murmured more and more,
and at last against me in particular, because the vessel and cargo were under my care,
so that my inward exercise was great about it; for neither myself,
nor any in the vessel did imagine that we should be half so long as we were on the voyage:
but since it was so, I seriously considered the matter,
and to stop their murmuring I told them they should not need to cast lots,
which was usual in such cases, which of us should die first,
for I would freely offer up my life to do them good.
One said, "`God bless you, I will not eat any of you.`"
Another said, he would die before he would eat any of me; and so said several.

I can truly say, at that time my life was not dear to me,
and that I was serious and ingenuous in my proposition:
and as I was leaning over the side of the vessel
thoughtfully considering my proposal to the company,
and looking in my mind to Him that made me,
a very large dolphin came up towards the surface of the water, and looked me in the face;
and I called to the people to put a hook into the sea and take him,
"`For here is one come to redeem me,`" said I to them; and they put a hook into the sea,
and the fish readily took it, and they caught him.
He was longer than myself; I think he was about six feet, and the largest that ever I saw.
This plainly showed us, that we ought not to distrust the providence of the Almighty.
The people were quieted by this act of providence, and murmured no more.
We caught enough to eat plentifully of, until we got into the Capes of Delaware.
Thus I saw it was good to depend upon the Almighty, and rely upon his eternal arm,
which in a particular manner did preserve us safe to our desired port;
blessed be His great and glorious name through Christ forever!

[.asterism]
'''

Richard Davies, travelling in Pembrokeshire on a religious account,
with his companion Thomas Ellis, appointed a meeting at Newcastle in Carmarthenshire,
some Friends accompanying them there.
Several magistrates of the place came to the meeting, and were very civil.
Richard Davies says:

The weight and service of the meeting lay chiefly upon me:
for though our friend Thomas Ellis had been reckoned a deacon,
and an eminent preacher among the Independents,
yet his mouth was but very little as yet opened by way of testimony among Friends.
He was an understanding man in the things of God,
and was not hasty to offer his offering till he found a very weighty concern on him.
As I was declaring to the people in the Welch language,
I stood opposite a great window that opened to the street,
and there was an evil-minded man in the street, that had a long fowling-piece,
who put the mouth of it through the window, and swore,
that if I would speak another word, I was a dead man.
But, blessed be God, I was kept in that which is above the fear of man,
and the Lord kept me in dominion over all.
There were but two women sitting in the window,
and the mouth of the gun came between them both; one of them turned her back upon it,
and said in Welch, when the man threatened as before, "`I will die myself first.`"
And there was one in the meeting went to this man, and took the gun away from him,
and that wicked man came into the meeting and was pretty quiet there;
the Lord`'s good presence was with us, a good meeting we had,
and I may say "`They that trust in the Lord, are as Mount Zion, that cannot be moved.`"
And as it was said of old, As the hills were round about Jerusalem,
so is the Lord round about his people,
to be a present help to them in every needful time.

=== The Colonel of Dragoons

During the revolutionary war in America,
a part of the American army lay near the Gunpowder Falls meetinghouse,
which however did not prevent Friends from holding their meetings for worship.
Among these troops there was a colonel of dragoons,
whose resentment against Friends was raised to such a pitch of malice, that one day,
when traversing the country, he came to the most extraordinary and cruel resolution,
of putting to the sword the Friends who were then collected at their place of worship;
considering them as no better than a company of traitors.
Drawing up his men near the spot, he ordered them to halt,
in order to make arrangements for the execution of his dreadful purpose.
At this moment an awful silent pause took place,
in which he felt his mind so powerfully smitten with conviction,
that he not only drew off his men,
but conceived very favourable sentiments of the Society:
and continuing to yield to his convictions,
he afterwards joined in communion with Friends,
and continued faithful to the principle of Truth professed by them.

Sutcliff`'s Travels.

=== Extract of a Letter From Anthony Benezet to John Pemberton

It is amazing what an influence the love of the world, its esteem and friendship,
and the desire of amassing wealth, living themselves and children in delicacy and show,
in conformity to the world, have upon many in our Society,
who in other respects appear under some impressions of good;
notwithstanding they cannot but be sensible of its woeful
effects upon the religious welfare of their offspring,
who hereby, as mentioned by the apostle, fall into snares and hurtful lusts,
often to their perdition; notwithstanding also the nature of our profession,
and a conformity to the example and precepts of our Lord,
lay such an absolute prohibition on such a state.

"`Lay not up for yourselves treasure upon earth,`" says our blessed Saviour,
"`How hardly shall they that have riches enter,`" etc.
"`Woe unto you that are rich.`"
"`Be not conformed,`" "`but be transformed,`" that you
may be better qualified to follow Him who has called you,
in the way of the cross, to be soldiers in his holy warfare.
Learn of him who was meek and low; who though he was Lord of all,
chose to come in the form of a servant, walked on foot, fed on barley loaves, etc.
Some injunctions, less likely to effect the heart,
we take according to the full force of the expressions, as with respect to taking oaths,
etc.; while others, whose hurtful nature is more apparent,
and as positively prohibited by our Saviour,
(as that of laying up treasures,) we make nothing of.
An instance, which not long since occurred,
caused me to make some painful reflections upon this most weighty subject.

A Friend died,
reputed to have left sixty or seventy thousand pounds to a number of children and grandchildren,
already so elevated by the fortunes they were possessed of,
as to be ready to take wing and fly above the Truth, in conformity to the world,
its friendships, fashions, etc.
This happened in the depth of winter, one of those intense cold days,
which we all have felt to be very trying, even to those who are best provided with fuel,
suitable clothing, etc.
As I passed along, I observed aged people and others tottering about the streets,
or standing in the cold in pursuit of a few pence, towards a scanty subsistence;
many of these, doubtless, poorly provided with fuel or bedding:
both of which articles were then exceedingly scarce and dear.

I compared the situation and necessity of these aged people with the superfluous
wealth and delicate living of the children of the rich man lately deceased and
could not but be astonished at the selfishness and caprice of the human heart.
I queried with myself: Are both these children of the same Father,
equally under his notice?
Are they enjoined and do they profess, to love each other as they love themselves?
Why is not at least three quarters of this wealth,
and three quarters of the wealth of a number of other rich Quakers,
laid out in procuring a place of refuge and comfort, and moderate provision,
for such weak and aged people?
that they may, in the decline of life,
be put in the most suitable situation to think of and prepare for their latter end,
and enjoy a moderate state of comfort.

Is it honest to God or man?
Is it doing justice as stewards of the wealth committed to our care?
Is it loving our neighbours as ourselves?
If mankind are indeed brethren, can it be agreeable to the good Father of the family,
that one should engross so much, and employ it to feed the corruptions of his offspring;
while others are under such manifest disadvantages for lack of help.

The preceding letter cannot properly be accounted an anecdote,
though the circumstance brought forward in it seems
to have been the occasion of those whole some remarks,
which form the greater portion of it.

The remarkable character who wrote it,
was not a theoretic or an ostentatious philanthropist;--a
Christian in the most appropriate sense of the term,
he had learned, (not in the school of custom or conformity,) to devote his talents, time,
and substance to the service of his fellow creatures--and that for Christ`'s sake.
In a biographical memoir published respecting him are delineated some uncommon trails
of benevolence--he has even been known to take off his own coat in the streets,
and give it to one that was in great need of clothing:
but his useful life and labors on every occasion
appear to have evinced a heart under the influence,
restraint,
and direction of the best of principles,--the will
of God as made known by the Spirit of His Son.

=== A Peaceful Profitable Old Age

From Thomas Chalkley`'s Journal

In Virginia, near James River, I met with an aged Friend, whose name was William Porter.
He was ninety-two years of age; and had then a daughter two years old.
Some years after, I saw him, and he was weeding Indian corn with a hoe.
He was then about a hundred and six years of age, and had upwards of seventy children,
grandchildren, and great grandchildren.
We went, (various Friends) to see him,
and he preached to us a short but very affecting sermon, which was,
as near as I remember, verbatim thus: "`Friends,
you are come to see me in the love of God.
God is love, and those that dwell in God dwell in love.
I thank God I feel His divine life every day and every night.`"

He lived to see his above mentioned daughter married;
and died aged one hundred and seven years.

[.asterism]
'''

William Penn, while in Pennsylvania,
undertook a journey through the province and territories as a minister of the gospel.
Among the places he visited in this capacity was Haverford;
an anecdote is recorded of him while going there, which is worth relating.
A Friend of the name of Rebecca Wood, when a little girl,
used sometimes to walk from Derby, where she resided, to Haverford meeting.
One day as she was walking along, she was overtaken by a Friend on horseback,
who proved to be William Penn.
On coming up with her, he enquired where she was going and with his usual good nature,
desired her to get up behind him; and bringing his horse to a convenient place,
she mounted, and so rode away.
Being without shoes or stockings,
her bare legs and feet hung dangling by the side of the governor`'s horse.
Although William Penn was at this time both governor and proprietor,
he did not think it beneath him,
thus to help along a poor barefooted girl in her way to meeting;
and notwithstanding the maxims and customs of the world,
these little kind offices to those in low stations in life,
were so far from lowering him in the estimation of those he was appointed to govern,
that perhaps there never was a governor,
who stood higher in the opinion of those governed by him, than William Penn.

Sutcliff`'s Travels

=== John Woolman and the Robin

A thing remarkable in my childhood was, that once going to a neighbour`'s house,
I saw on the way a robin sitting on her nest, and as I came near she went off,
but having young ones, flew about, and with many cries expressed her concern for them;
I stood and threw stones at her, till one striking her, she fell down dead.
At first I was pleased with the exploit, but after a few minutes was seized with horror,
as having in a sportive way, killed an innocent creature,
while she was careful for her young.
I beheld her lying dead, and thought those young ones for which she was so careful,
must now perish without their mother to nourish them;
and after some painful considerations on the subject, I climbed up the tree,
took all the young birds and killed them;
supposing that better than to leave them to pine away and die miserably;
and believed in this case that scripture proverb was fulfilled,
"`The tender mercies of the wicked are cruel.`"
I then went on my errand, but, for some hours,
could think of little else but the cruelties I had committed, and was much troubled.
Thus He whose tender mercies are over all his works,
has placed a principle in the human mind,
which incites to exercise goodness towards every living creature;
and this being singly attended to, people become tenderhearted and sympathizing;
but being frequently and totally rejected,
the mind becomes shut up in a contrary disposition.

This little circumstance, recorded in the life of John Woolman,
may be also recorded in the experience of many a youthful reader, who,
in a like schoolboy freak of thoughtlessness, may have acted similarly many a time.
To these the language of tender expostulation may be less
reaching than the simple tenor of this instructive passage,
which it is thought cannot fail to touch the feeling heart
and awake susceptibility in the consciences of most.
It may be noticed as a thing remarkable, that this little fellow,
who had thus early evinced the strength and growth of the corrupt tree,
by allowing the axe of divine judgment and reproof to be laid at its root, soon became,
through the prevalence of the tendering power of Truth,
an eminent example and advocate of Christian benevolence towards the whole human race,
as well as of gentleness in the treatment of the brute creation.
Often in the pure love of God would he plead with
those that oppressed either man or beast,
and by the persuasive eloquence of conduct testified that his spirit
was united with the Father of spirits and Preserver of all flesh.

[.asterism]
'''

Thomas Chalkley, speaking of his childhood, says:

I loved music, dancing and playing at cards,
and was followed with the judgments of God for it in the secret of my soul.

I remember that unknown to my parents I had bought a pack of cards,
with intent to make use of them when I went to see my relations in the country,
where there was liberty in the family so to do, at a place called Woodford,
where I got leave sometimes to go; and at the time called Christmas, I went to see them,
and on my way went to a meeting at Wanstead;
at which meeting a minister of Christ declared against the evil of gaming,
and particularly of cards;
and that the time which people pretended to keep holy for Christ`'s sake,
many of them spend mostly in wickedness, sports and games;
even some pretending to be religious: and, generally speaking,
more sin and evil is committed in this time,
than in the like space of time in all the year besides;
so that the devil is served instead of honouring Christ.
From this meeting I went to the house of my relations,
where the parson of the next parish lodged that night,
who used to play at cards with them sometimes;
and the time drawing near that we were to go to our games,
my uncle called to the doctor (as he called him,) and to me and my cousin,
to come and take a game at cards;
at which motion I had strong convictions upon me not to do it, as being evil;
and I secretly cried to the Lord to keep me faithful to Him; and lifting up my eyes,
I saw a bible lie in the window, at the sight of which I was glad.
I took it, and sat down and read to myself,
greatly rejoicing that I was preserved out of the snare.
Then my uncle called again, and said, "`Come, doctor,
for I see my cousin is better disposed.`"
Then he looked upon me, and said he was better disposed also.
So their sport for that time was spoiled, and mine in that practice forever;
for I never (as I remember) played with them more, but as soon as I came home,
offered my new and untouched pack of cards to the fire; and of this I am certain,
the use of them is of evil consequence,
and draws away the mind from heaven and heavenly things;
for which reason all Christians ought to shun them as engines of Satan:
and music and dancing having generally the same tendency,
ought therefore to be refrained from.

[.asterism]
'''

James Wilson was at a meeting in London with Thomas Wilson,
where was a great concourse of people,
and among them two persons of high rank in the world,
who sat very attentively while a Friend was speaking,
and seemed to like what was delivered; but when Thomas stood up, being old,
bald and of a mean appearance, they despised him, and one said to the other, "`Come,
my lord, let us go, for what can this old fool say?`"
"`No,`" said the other, "`let us stay, for this is Jeremiah the prophet,
let us hear him:`" so as Thomas went on, the life arose,
and the power got into the dominion,
which tendered one of them in a very remarkable manner;
the tears flowed in great plenty from his eyes, which he strove in vain to hide.
After Thomas had sat down, he stood up,
and desired he might be forgiven of Thomas and the Almighty,
for despising the greatest of His instruments under heaven, or in his creation.

Samuel Neale`'s Journal.

=== Encouragement Early to Seek the Lord

The early experience of those,
that have shone as fixed stars in the glorious firmament of God`'s invisible power,
have stood their ground in the strength and steadfastness of that holy faith,
which He is pleased to communicate--the beginnings and breakings forth of his love,
grace, mercy, and truth in and to their souls,
will always prove preciously acceptable to the kindred spirit,
of those that have been in any measure made partakers of the like heavenly hope.

A few particulars relative to the convincement of Thomas Thompson of Skipsea in Yorkshire,
have appeared worthy a place in these sheets.

The reader may notice, that in such biographical insertions as the following,
incident and fact are preferred to mental exercise, conflicts, or spiritual experiences,
agreeable to the design and title of this work.
Much deep instruction, however, may be gathered from most of them,
and reflections may often arise on the recurrence of these passages to the mind,
and prove as watchwords to the wise and upright in heart, especially among the youth.
Even to those who do not, in matters of faith, profess with us,
such a brief memorial as that of Thomas Thompson,
if examined with seriousness and candour,
may not be devoid of interest--these may at least be made acquainted
in some degree with the efficacy of that secret influence,
which is not of us, though in us,
by which all that come among us should be regulated both in heart and conduct,
and without which indeed we consider religion to be an empty name,
though ever so near in resemblance to "`the Truth as it is in Jesus.`"

Respecting this worthy man of God, his character, services,
and sufferings for conscience sake, much might be added; let it suffice to say,
that he lived to his 73rd year, and as he lived so he died,
in the full and entire possession of that peace, assurance,
and joy in the Lord God of his life, which is the portion of His faithful children,
the followers of Jesus Christ.

When I was very young, it pleased the Lord to incline my heart to seek after him;
and when I was about eight years of age, his word sounded in me,
"`Now is the axe laid to the root of the tree;
every tree therefore that brings not forth good fruit,
shall be hewn down and cast into the fire:`" then were desires begotten in me,
that I might be found as one of the trees bringing forth good fruit.
And the Lord discovered unto me many things that were evil,
generally used by such as I then was, as swearing, lying, and profane speaking,
and not only discovered the same to be evil,
but through mercy raised in my heart a detestation and abhorring thereof;
and as I kept to that principle which manifested
these things to be contrary to the will of God,
I was preserved out of the evil,
though I knew not yet it was the Lord that was so near me, and striving with me.

Then I began frequently to go to hear sermons,
and to follow those that were accounted the most conscientious
and able preachers in the parts where I lived.
And I greatly longed to have a Bible, having then never had one to read in,
which when my parents understood, they quickly got me one; and when I came to read in it,
I was greatly affected with the relation of God`'s speaking to his people, as Noah,
Abraham, Isaac, and Jacob,
etc. and accounted them happy that had such familiarity with God;
not understanding that he was still a God "`near at hand,`" and "`not afar off`" only,
unto all that truly sought after him.
And for several years I earnestly endeavoured to get understanding,
but my mind was outward, for I knew not the light of Christ to guide me,
with which he has enlightened everyone;
but I sought unto the most able and godly ministers, as they were then accounted,
and I also greatly loved the company of the most godly, wise,
and professing people that I could become acquainted with,
and delighted to be discoursing of the things of God.

But, Oh! as I grew up and increased in knowledge,
my heart was not kept so near the Lord as formerly,
neither were my desires so fervent towards God,
nor my care so great to walk in holiness of life before him,
so as to bring forth fruits to his praise.
For I began to get into a false rest, and apprehended all was well with me,
because I knew the scriptures and could repeat much of sermons,
and the exposition of chapters, which the priests then used;
and the priests also spoke smooth things to me, daubing me up with untempered mortar,
saying, I was a hopeful boy, and needed not doubt but that it would be well with me, etc.
Howbeit, the Lord in his everlasting love and tender compassion to my soul,
again raised His witness in my heart,
whereby he let me see that my immortal soul was still lacking,
and that all was not right with me, though I then could speak much of God,
Christ and faith.

So some desires through mercy were again begotten in me towards the Lord;
and my soul could receive no satisfaction in what I heard from the priests,
notwithstanding I went from one to another, as it were from mountain to hill,
seeking rest, but found none to my wearied soul, which still lacked satisfaction,
and hungered for the Bread of life.^
footnote:[John 6:33.]
Then I went to some meetings of the people called independents;
but neither there could I find what my soul lacked, namely, the life of Jesus,
which I could not then be satisfied without the enjoyment of;
so being tired out with going from one to another, in a little time I left them,
and grew retired in my mind, delighting much to be alone,
meditating on the things of God,
or reading such books as were published of the experiences of those,
that had any openings of the way of life.

And in the forepart of the year 1652,^
footnote:[Thomas Thompson being then about 21 years of age.]
it pleased the Lord to order his faithful and valiant servant and messenger,
dear George Fox, into these parts; but I had not then opportunity to see him,
though I greatly desired it.
But some of my familiars that were with him, gave me an account of his manner of life,
and also of his doctrine: they told me, that he was in his behaviour very reserved,
not using any needless words or discourses that tended not to edification,
and that he used not respect of persons, very temperate in his eating and drinking,
his apparel homely yet decent; as for his doctrine,
he directed people to the light of Christ in their consciences, to guide them to God.
At hearing of these things, though at second hand,
the Lord was pleased mightily to work upon my spirit,
and brought me to a wonderful retiredness,
and my mind was truly turned inward to wait on Him and desire his teachings.

Thus, by degrees, the Lord manifesting one thing after another,
I became weaned from my former lovers, and by the working and power of God,
self came to be denied, and I in many things humbled to the cross;
so that several of my neighbours and acquaintances marvelled to see me so changed,
and some said I should be distracted.
But their words were little to me; for as I obeyed the Lord,
I found peace and satisfaction, and the return of God`'s love into my bosom,
which I had long before been seeking: and as I gave up anything for Truth`'s sake,
I found peace, and more strength was given me; so that I can truly say,
It is good to keep in the counsel of God, and to give up wholly to serve him,
for he is good to them that trust in him, and they that faith fully serve him,
shall in no way lose their reward.

Now it happened, that, about the 6th or 7th month of the year 1652,
we heard of a people raised up at or about Malton, that were called Quakers,
which was the first time that I heard of that name being given to any people.
They were by most persons spoken against; but when I strictly enquired,
what any had to lay to their charge,
that might give cause for such aspersions as were thrown upon them,
I met with none who could justly accuse them of any crime; only they said,
they were a fantastical and conceited people,
and burnt their lace and ribbons and other superfluous things,
which formerly they used to wear,
and that they fell into strange fits of quaking and trembling.

These reports increased my desires to see and be acquainted with some of them;
and in the 8th month of the aforesaid year,
I heard that the Quakers were come to Bridlington,
whereat I greatly rejoiced in my spirit,
hoping that I should get some opportunity to see them; and on the 5th day next following,
I heard that they were come to Frodingham--(this
was that faithful labourer and minister of the gospel,
William Dewsbury.) And I, being on my master`'s work in Brigham, could not go in the day,
but determined to go in the night,
and would gladly have had some of my acquaintances to have gone with me;
but the night being very dark, none would go, so I went alone.
And coming into the room where William was, I found him writing,
and the rest of his company were sitting in great silence,
seeming to be much retired in mind, and fixed towards God;
their countenances were grave and solid, which preached unto me,
and confirmed what I had before believed, that they were the people of the Lord.

After a little time, William ceased writing, and many of the town`'s people coming in,
he began in the power and wisdom of God to declare the Truth;
and oh! how was my soul refreshed, and the witness of God reached in my heart,
I cannot express it with pen; I had never heard nor felt the like before,
for he spoke as one having authority, and not as the scribes;
so that if all the world said no,
I could have given my testimony that it was the everlasting Truth of God.
And in the same month, my mouth was livingly opened to declare the name of the Lord,
and preach repentance to the people;
and the work of the Lord prospered in the hands of his faithful servants;
and I knew a bridle to my tongue,
and was greatly afraid lest I should offend Him in thought, word, or deed.
And the word of the Lord was in me, "`You shall not do your own works,
nor think your own thoughts, nor speak your own words, on this my holy day.`"^
footnote:[Isa. 58:13.]
And though I suffered and went through many great exercises,
yet the Lord bare up my spirit, and carried me on, while I abode faithful to Him,
to the praise of his own name.

Thomas Thompson`'s Life.

[.asterism]
'''

George Whitehead, (of whom some notice has been already taken,
and respecting whom it may be said with propriety and truth,
that he was a highly dignified servant of the Church,) relates,
that being at a meeting of the people called Quakers,
(the first of their meetings he had attended,) when probably about sixteen years of age,
he took especial notice of the mighty power and work of the Lord,
that was over and upon that assembly, breaking the hearts of many into great sorrow,
weeping, and contrition.
One young woman in particular, went mourning out of the meeting,
whom he with much serious concern followed, to observe her sad condition.
And on beholding her seated on the ground, with her head hanging down,
and her face turned towards the earth, as not regarding anyone,
and hearing how bitterly she mourned, crying out, "`Lord, make me clean!
O Lord, make me clean!`" his mind was, he declares,
far more deeply affected than with what he had heard in the meeting,
and more indeed than with all the preaching he had ever heard from man.
He believed this was a godly sorrow for sin, in order to an unfeigned repentance.
This real work of the power and Spirit of God upon
her heart operated also in the hearts of others,
causing even their bodies to tremble at the presence of the Lord,
his inward call to their souls.

These things made deep and serious impression upon
George Whitehead`'s mind and he felt assured,
the Lord was at work among that small despised people in a peculiar manner,
and that He was about to gather and raise them up to be a people unto Himself,
to show forth in that day the spirituality of gospel worship,
which in the early times of the Church was not set up in those dead forms,
since contrived by the wisdom of man.

It may be further observed, that George Whitehead,
after being fully convinced and persuaded to turn his attention
to that which inwardly discovered to him his condition,
met with George Fox at a meeting.
"`I was then,`" says he, "`very low, serious and intent in my mind,
willing to see and taste for myself, for my own inward satisfaction;
and I saw and felt his testimony was weighty and deep,
and that it proceeded from life and experience, that it bespoke divine revelation,
and tended to bring to an inward feeling and sense of the life and power of Christ,
and its sanctifying operation in the heart.
His speech was not with affecting eloquence or oratory, or human wisdom,
but in the simplicity of the gospel, to turn the mind to the light and life of Christ.`"

In that day of the springing forth of light and truth out of obscurity,
the meetings of those that were gathered into the pure worship were held,
as the same writer declares,
"`much and often in silence,`" or but few words delivered among them;
the minds of those present being centered and stayed on the divine Word of Life,
and much exercised before the Lord,
waiting the times of refreshment that come from his presence.^
footnote:[Acts 3:19.]
Thus, in His way, strength and time,
they were enabled effectually to put off the body of sin,
and to become truly renewed in the spirit of their minds, so that from among them,
the Lord was pleased to bring forth a stock of true witnesses,--able
ministers of that which dwelt in them richly,
and was as "`rivers of living water.`"^
footnote:[John 7:38.]

=== Awful Realities

Although scarcely anything has been herein inserted that might be said
to be calculated to stagger the belief of the most rational Christian,
yet the two following very awful and extraordinary anecdotes,
given by that man of the world, and servant of Christ, Thomas Chalkley,
with every appearance of the greatest claim to authenticity and credibility,
shall be subjoined:--and they are admitted with an especial
view to those in early life among the members of our Society.
These passages may possibly meet the eye of someone in that class,
whose habits and views may not be so closely interwoven with those of his fellow-members
as to make the lesson wholly useless to him in the course of his life.

Thomas Chalkley, being on his return from America,
where he had been engaged as a minister in various parts,
gives the following passage in the journal of his life.

About this time our doctor dreamed a dream, which was to this effect,
himself relating it to me: He said,
he dreamed that he went on shore at a great and spacious town, the buildings,
whereof were high, and the streets broad; and as he went up the street,
he saw a large sign, on which was written in great golden letters "`Shame.`"
At the door of the house, to which the sign belonged,
stood a woman with a can in her hand, who said to him, "`Doctor, will you drink?`"
He replied, "`With all my heart,
I have not drank anything but water a great while,`" (our wine and cider being all spent,
we having had a long passage,) and he drank a hearty draught, which he said,
made him merry; so went up the street reeling to and fro,
when a grim fellow coming behind him, clapped him on the shoulder, and told him,
that he arrested him in the name of the governor of the place.
He asked him for what, and said, "`What have I done?`"
he answered, "`For stealing the woman`'s can.`"
The can he had indeed, and so he was taken before the governor,
who was a mighty black dog, the biggest and grimmest that ever he saw in his life;
and witness was brought in against him by an old companion of his,
and he was found guilty, and his sentence was, to go to prison, and there to lie forever.

He told me this dream so punctually,
and with such an emphasis that it affected me with serious sadness,
and caused my heart to move within me; for to me the dream seemed certain,
and the interpretation sure.^
footnote:[Dan. 2:45.]
I then told him he was an ingenious man and might
clearly see the interpretation of that dream,
which exactly answered to his state and condition, which I thus interpreted to him:
"`This great and spacious place, wherein the buildings were high and the streets broad,
is your great and high profession:
the sign on which was written '`shame,`' which you saw, and the woman at the door,
with the can in her hand, truly represent that great, crying,
and shameful sin of drunkenness, which you know to be your great weakness;
the grim fellow that arrested you in the devil`'s territories, is death,
who will assuredly arrest all mortals; the governor whom you saw,
represented by a great black dog,
is certainly the devil who after his servants have served him to the full,
will torment them eternally in hell.`"
So he got up as it were, in haste, and said, "`God forbid! it is nothing but a dream.`"
But I told him it was a very significant one, and a warning to him from the Almighty,
who sometimes speaks to man in dreams.

In seven weeks after we left sight of the land of America, we saw the Scilly Islands,
and next day we saw the land of England, which was a comfortable sight to us,
in that God Almighty had preserved us hitherto, and that we were so far got on our way.
We drove about the Channel`'s mouth for several days for lack of wind; after which,
for two days the wind came up, and we got as far up the Channel as Lime Bay,
and then an easterly wind blew fresh for several days, and we turned to windward,
but rather lost than got on our way, which was tiresome and tedious to some of us.

Now about this time,
(being some days after the doctor`'s dream,) a grievous accident happened to us.
We met with a Dutch vessel in Lime Bay, a little above the Start, hailed her and she us.
They said they came from Lisbon, and were bound for Holland.
She was laden with wine, brandy, fruit, and such like commodities;
and we having little but water to drink,
(by reason our passage was longer than we expected,) therefore we sent our boat on board,
in order to buy us a little wine to drink with our water.
Our doctor, and a merchant that was a passenger, and one sailor, went on board,
where they stayed so long until some of them were overcome with wine,
although they were desired to beware thereof: so that when they came back,
a rope being handed to them, they, being filled with wine to excess,
were not capable of using it dexterously, insomuch that they overset the boat,
and she turned bottom upwards, having the doctor under her.
The merchant caught hold of a rope called the main sheet, whereby his life was saved.
The sailor, not getting so much drink as the other two,
got nimbly on the bottom of the boat,
and floated on the water till such time as our other boat was hoisted out,
which was done with great speed, and we took him in;
but the doctor was drowned before the boat came.
The seaman that sat upon the boat saw him sink, but could not help him.

This was the greatest exercise that we met with in all our voyage; and much the more so,
as the doctor was of an evil life and conduct, and much given to excess of drinking.
When he got on board the aforesaid ship, the master sent for a can of wine and said,
"`Doctor, will you drink?`"
he replied, "`Yes, with all my heart, for I have drank no wine a great while.`"
Upon which he drank a hearty draught, that made him merry (as he said in his dream);
and notwithstanding the admonition which was so clearly
manifested to him but three days before,
and the many promises he had made to Almighty God, some of which I was a witness of,
when strong convictions were upon him, yet now he was unhappily overcome,
and in drink when he was drowned.
This is, I think,
a lively representation of the tender mercy and just
judgment of the Almighty to poor mortals;
and I thought it was worthy to be recorded to posterity,
as a warning to all lovers of wine and strong liquors.
This exercise was so great to me; that I could not for several days get over it;
and one day while I was musing in my mind on those things relating to the doctor,
it was opened to me, that God and his servants were clear,
and his blood was on his own head: for he had been faith fully warned of his evil ways.
This happened about the year 1699.

The other circumstance occurring in Thomas Chalkley`'s journal is thus given.

In this year, +++[+++1722,]
I was at the burial of our Friend, Jonathan Dickenson,
at which we had a very large meeting;
he was a man generally well beloved by his Friends and neighbours.
In this meeting, a passage he had often told me in his health,
was brought to my remembrance, I think, worthy to be recorded to the end of time,
which is as follows:

It happened at Port Royal, in Jamaica, that two young men were at dinner with Jonathan,
and several other people of account in the world,
and they were speaking about earthquakes; there having been one in that place formerly,
which was very dreadful,
having destroyed many houses and families These two young men argued
that earthquakes and all other things came by nature,
and denied a supernatural power, or Deity; insomuch that several,
surprised at such wicked discourse, and being ashamed of their company, left it;
and at the same time the earth shook, and trembled exceedingly,
as though astonished at such treason against its Sovereign and Creator,
whose footstool it is: and when the earth thus moved,
the company which remained were so astonished, that some ran one way, and some another;
but these two atheistical young men stayed in the room, and Jonathan with them,
he believing that the providence of Almighty God could preserve him there if he pleased,
and if not, that it was in vain to fly.
But the hand of God smote these two young men, so that they fell down; and,
as Jonathan told me, he laid one on a bed, and the other on a couch,
and they never spoke more, but died soon after.
This was the amazing end of these young men: a dreadful example to all atheists,
and dissolute and wicked livers.
Oh! that young people might be warned, that the hand of God might be upon them for good,
and that they would tenderly be concerned for their salvation.
