== Chapter V

[.centered]
=== Law and Gospel

[.embedded-content-document]
--

Once a company of Irishmen came to Pall Mall, when George Fox was there,
but the meeting was already broken up; and he, being gone up into a chamber,
heard one of those rude persons, who was a colonel, say, he would kill all the Quakers.
Whereupon George Fox came down and told him, "`The law said, '`An eye for an eye,
and a tooth for a tooth;`' but you threaten to kill all the Quakers,
though they have done you no hurt;`" but said he further, "`Here is gospel for you;
here is my hair, here is my cheek, and here is my shoulder,`" turning it to him.
This so surprised the colonel, that he and his companions stood amazed, and said,
"`If this is your principle, as you say, we never saw the like in our lives.`"
To which George Fox said, "`What I am in words, I am the same in life.`"
The colonel then carried himself lovingly; though a certain ambassador who stood without,
and then came in, said, that this Irish colonel was such a desperate man,
that he dared not come in with him, for fear he should have done great mischief.

[.signed-section-signature]
_Sewel`'s History of Friends._

--

[.centered]
=== The Trumpeter

The grievous sufferings and bitter persecution, which it was the lot of those to undergo,
who early became one with our Society in religious faith and practice,
need not be here enlarged on.
Our historians, Sewel and Gough in particular, may be consulted by those,
who wish to acquaint themselves with the nature and extent thereof,
and with the Christian patience, fortitude and meekness,
evinced by our forefathers in profession.

Extraordinary, however, was often the influence of these heavenly tempers upon beholders,
as in the foregoing instance;--that supernatural support and strength,
which they who were faithful to Christ their Lord received,
many times reached and overpowered the hearts of opposers.
Magistrates on the bench became favourable to those they were about to convict,
and took up the very conduct and belief, which they had been ready to condemn;
jailers and others were brought to acknowledge,
and embrace those truths they had despised:--And no wonder, when it is considered,
that these patterns of the "`meek and quiet spirit,`" prescribed by the gospel,
had been themselves in many instances abject slaves
to their own corrupt propensities and passions:
some of them too, of that fierce and boisterous nature,
that cannot brook the slightest provocation, but afterwards,
so struck by the terrors of the Lord for sin,
so humbled under the power of the cross of Christ,
as to become clothed with the harmless peaceable spirit of the Lamb,
bearing all the revilings of their enemies with an even mind,
and with a gentle forgiving deportment.
Such facts are not brought forward,
with a view of ascribing these excellent "`fruits
of righteousness`" exclusively to a name or a party;
but rather, to exalt that heavenly power and grace, which,
by the one great Sacrifice for sin, is purchased for everyone,
and which most assuredly may be partaken of, in some measure or other,
by all that stand ready to receive it, whatever be the condition they are in,
or the dispensation they are under.

The succeeding account is of similar import with the preceding,
and comes in aid of the above observations.

[.embedded-content-document]
--

A certain trumpeter, coming into a meeting of Friends,
began in an insolent manner to sound his trumpet,
thereby to drown the voice of him that was preaching; but this had a contrary effect,
and stirred up the zeal of the preacher the more,
so that he went on as if none disturbed him.
The trumpeter at length, to recover his breath, was willing to cease blowing;
but being still governed by an evil spirit, after some intermission began to sound again;
but whatever he did, he was not able to divert the preacher from his discourse,
though he might hinder the auditory from hearing what was spoken.
Thus he wearied himself so much, that he was forced to rest again for respiration;
whereby, in spite of his evil will, he came to hear what the preacher spoke,
which was so piercing, that the trumpeter came to be deeply affected with it,
and bursting into tears, confessed his crime, and came to be a true penitent.

[.signed-section-signature]
Sewel

--

[.asterism]
'''

William Caton was a lively instance of the efficacy of divine grace,
and an eminent instrument in the Lord`'s hand to promote
his own work of reformation and righteousness in the earth.
He lived at a very early period in the annals of our Society;
and some passages of his diligence, zeal and devotedness in the cause he espoused,
may be revived for the benefit of the present generation.

When about the age of fourteen, he became an inmate in Judge Fell`'s family,
at Swarthmore in Lancashire.
Long before this, however, his heart was visited with impressions of divine goodness,
under the influence of which, he was often, while musing on the works of his Creator,
affected and overcome with tenderness,
and at times restrained from the vices incident to children.
At length the witness for God in him came to be more thoroughly awakened,
whereby his sins were set in order before him.
And though at first like the wild heifer unaccustomed to the yoke,
he sought to get from under it,
and by sportive thoughtlessness and folly often extinguished the good within him;
yet the love of God was such towards him, that lie was pursued with judgment,
when overtaken by evil.
Sometimes, indeed, he would get aside into a retired spot, and wait upon the Lord,
and ponder on his marvellous works,
in which practice he met with frequent refreshment of soul.

George Fox`'s first visit to the Fell family, at this juncture,
seems to have been the occasion of greatly opening and enlarging his views,
and of settling his mind on the Rock of true religion, Christ Jesus;
whose kingdom of grace and truth came thenceforward to be set up in his heart,
and the powers of his understanding, with the tendencies of his will,
to be in some degree subjected and sanctified.
Many spiritual conflicts and provings, however, he had to pass through,
before his soul might be said to be measurably redeemed from the earth,
and liberated from the earthly spirit,
"`created anew in Christ Jesus,`" and established in faith and holiness.
In this interval, he speaks of his studies at school becoming his burden,
and of finding himself, when under trouble and exercise of mind,
unfit to get through his themes and Latin verses, etc.

The glorious visitations of Almighty goodness unto him,
about the seventeenth year of his age, were such, that his spirit was melted,
and as it were broken under the sense of them;
great were the enjoyments and consolations he partook of,
and many were the precious promises that were opened and confirmed to him.
The freshness of the heavenly power that was with him,
and also with that family under whose roof he resided,
the nearness and dearness that prevailed among them one towards another,
their zeal and faith, were more, he writes, than could be fully described.
Meetings were exceedingly precious to them in that day,
insomuch that some of them would commonly spend part of the evening,
in waiting on the Lord "`with one accord in one place,`"
often after the rest of the family were gone to bed.
The comfort and recruiting benefit they reaped hereby was very great.
"`For if,`" says William Caton, "`we had suffered loss in the day time,
when abroad about our business, or the like,
then we came in great measure to be restored again, through the love, power,
and mercy of our God, which abounded very much unto us.`"

Such gracious dealings,
accompanied by that instrumental aid and care he received from George Fox,
and also from Margaret Fell and others, were evidently not for nothing.
The designs of inscrutable Wisdom respecting him were not disturbed or retarded, but,
through resignation to, and reliance on the forming hand of the divine Workman,
His blessed work went forward, and an honourable vessel was the result,
fit for the Master`'s use, and bearing the inscription of "`holiness unto the Lord.`"
A faithful and skillful soldier, he was no longer at his own disposal,
but became quickly called to a prominent post in the service of his Leader; strength,
courage, and hardihood were given him on every occasion,
preservation and peace was his portion,
and the name of his God was indeed glorified through him.

About the year 1655, being then no more than eighteen years of age,
he began his career as a minister of that good Spirit,
which was "`shed on`" him "`abundantly through Jesus Christ.`"
His diligence in the duty of this sacred office almost exceeds belief;
passing over much of this kingdom chiefly or altogether on foot,
often in the depth of winter, and during the still more wintry time of persecution.
No doubt, his preaching carried its own evidence in the hearts of his hearers;
as he writes,
that "`the word of the Lord grew mightily and many were added to the faith.`"
As a summary specimen of his labours in this first year of his public engagement,
some of the districts or places which bounded his journeyings,
without mentioning the intervening track, are here recited.

From Swarthmore he travelled to Norwich, from there to London, Kent, Calais in France,
Yarmouth, Sunderland, Lancashire, Shields; Flushing to Middleburg, Rotterdam, etc.
Yorkshire, by Durham to Lancashire, Berwick, Edinburgh, Glasgow, Stirling,
etc. and back through Northumberland, Durham and Westmoreland to Swarthmore.
Some of these visits were by no means transient, as might be supposed:
alluding to a succeeding journey, he observes, "`time would fail me,
to relate particularly the extraordinary good service which we had,
sometimes in steeple houses,^
footnote:[It seems scarcely needful to remark,
that the word "`church`" is in holy scripture never
applied to an outward temple or building,
but to a company of believers,
whether generally or particularly.
{footnote-paragraph-split}
A
Friend being interrogated by a bishop,
Why he did not go to church?
replied, "`I do go to _church;_ and sometimes _the church comes to me._`"
(See 1 Cor. 16:19. Col. 4:15. and Phil. 2.) Thus the
use of this term appears to have crept in among Christians,
and with it a superstitious consecration of those places,
as possessing some latent quality, not affecting other works of art or nature.
To this, Stephen the martyr evidently alluded, when he said, "`Howbeit,
the Most High dwells not in temples made with hands,`" etc. Acts 7:48.
{footnote-paragraph-split}
The term "`Steeple-house`"
not infrequently occurs in the early writings and records of Friends.
It may sound harsh to most ears,
if it does not seem to savour of the scurrility and intolerance of that zealous age:
yet the reader may be assured, that this,
or any other mode of speech adopted by us as a people,
was by no means taken up for the purpose of opprobrium,
but rather significantly to discover the little veneration
or distinction they could show for these buildings,
more than for their own habitations;--they believing
that the Almighty is equally present everywhere,
to bless and to sanctify every place and everything to
those that walk uprightly on the earth--his footstool.]
sometimes in streets and markets, etc.`" besides his private,
as well as public engagements among his fellow professors.
But every other year of his life until its termination, was perhaps equally marked,
by alacrity in running the Lord`'s errands,
by faithfulness in occupying with that gift committed to him,
by a diligent taking heed to the ministry which he had received in the Lord,
to fulfill it.^
footnote:[Col. 4:17.]

It is not thought altogether ill suited with the scope of these sheets,
to close the account of William Caton, with some remarks made by him in his journal,
on this _important subject of the ministry._
Connected as it is with his own experience,
it may illustrate in a lively way to the understandings of some,
that state of entire dependance and emptiness,
into which gospel ministers must be brought,
before the Lord can be known to give them "`a mouth and
wisdom,`" and open for them "`a door of utterance.`"^
footnote:[Luke 21:15. and Col. 4:3.]

[.embedded-content-document]
--

Many precious and large meetings I had in the county +++[+++says William Caton,
speaking of Kent,]
and the Lord was very much with me, who furnished me plenteously with his word and power;
insomuch, that I stood admiring, at sundry times, from whom I had that fulness.
And it was not admired at
by me only, but by many more,
who looking with the eye of reason upon my earthly tabernacle or outward man,
could not expect any great thing from me, being then but about twenty years of age,
neither had I ever been in much profession, until I was convinced of the Truth of God;
yet plenty of heavenly things the Lord was pleased to open in me and through me,
to the end that I might communicate the same to the multitude,
which sometimes being very great, I was ready to say within myself,
"`Where shall I get bread to satisfy all of these?`"
And when I looked out at my own weakness and insufficiency as of myself,
I was ready to faint within me; but when I looked only at the Lord,
and put my confidence entirely in Him, I was strong and courageous.
For the Lord showed me this by his eternal light, upon a time,
when I was bemoaning my own weakness,
and groaning under the sense of the weight of the
burden of the service and work of the Lord;
saying, or thinking within myself,
Oh! such and such (meaning the ablest and wisest
of the brethren) are so and so fitted and furnished,
that they need not care what service they are called unto.
But as for me, I am so simple, I am so weak, and I never have anything beforehand,
neither do scarce ever know when I go into a meeting of several hundreds,
what I shall say, or whether anything or nothing.

And even when I was full of those and such like reasonings, the Lord showed me.
I say, how "`they that had much had nothing over,
and they that had little had no lack,`" even as it was with the Israelites of old.
For the brethren that were wise and eminent, who had received much from the Lord,
behold there was so much the more required of them: so that of all they had,
they had nothing over, but what they were to employ in the work and service of God.
As for my own part, I, who was so little in my own eyes,
and so mean and contemptible in the eyes of others, had no cause to complain;
for though I was often, that I knew not what I should say, when I went into a meeting;
yet even at such a time has the Lord been pleased to give me his word so plentifully,
that through Him I was enabled to speak two, or three,
or sometimes four hours to the congregation, with little or no intermission.
And often it has been with me,
that as I knew not _before_ the occasion what I should speak in the meeting,
neither could I remember _after_ the meeting what I had spoken in it;
and yet had plenty and fulness, though I was often daily at meetings, and not only so,
but in the evenings also:
and the Lord gave fresh supply always out of that _good treasury,_
which affords _things both new and old._

Now these things I rehearse +++[+++continues William Caton--and
the reader will no doubt believe his assertion,
as well as that of the compiler of this sketch,
whose object is the same]--not for my own praise; but do say, "`Not unto me, not unto me,
that have nothing but what I have received, be the praise, but unto the Lord alone,
who is the giver of every good and perfect gift.`"
I can truly say, that which I received from Him,
I delivered unto his people;--and did much rejoice in the Lord,
notwithstanding my great travels and sufferings,
all which through Him were made easy to me, neither were they much to me,
with all the perils and dangers I went through both by sea and land,
in comparison of the power and presence of the Almighty,
which did so sweetly and eminently accompany me in those days.

--

[.asterism]
'''

William Bennit, an early and eminent member of our Society,
was a prisoner for conscience sake in Bury Jail, in the year 1668.
One day, he seriously accosted a certain young woman, who was a criminal, and asked her,
whether during the course of her life she had not
many times transgressed against her conscience?
and whether she had not often thereupon felt some secret checks, and inward reproofs,
and been troubled in her mind on account of the evil committed?

This he did in such a convincing way,
that she not only assented to what he laid before her, but,
her heart being reached by his discourse, came clearly to see,
that if she had not been so stubborn and disobedient to those inward reproofs,
in all probability she would not have come to such a miserable fall, as she now had.
For man, not desiring the knowledge of God`'s ways, and departing from Him,
is left helpless, and cannot keep himself from evil,
even though it be such as he would formerly have abhorred in the highest degree,
and have said with Hazael, "`What, is your servant a dog,
that he should do this great thing?`"^
footnote:[See 2 Kings 8:13.]

William Bennit, thus opening matters to her,
by his wholesome admonitions so wrought upon her mind,
that she who never had conversed with the Quakers,
and was altogether ignorant of their doctrine,
now came to apprehend that it was "`the grace of God,
that brings salvation,`" which she had so often withstood;
and that this grace had not yet quite forsaken her,
but now made her sensible of the greatness of her transgression.
This consideration weighed so powerfully with her, that from a most grievous sinner,
she became a true penitent, and with hearty sorrow she cried to the Lord,
that it might please him not to hide his countenance.
And continuing in this state of humiliation, and sincere repentance,
and persevering in supplication, she felt in time some ease;
and at length attained to a sure hope of forgiveness
by the precious blood of the immaculate Lamb,
who came into the world to save sinners and call them to repentance,
who died also for the sins of the world.

Of this her change, she gave manifest proofs, at her trial before Judge Hale, who,
having heard how penitent she was, would eagerly have spared her,
and accordingly had on purpose got the words "`willfully
and designedly`" inserted in the indictment,
that from there she might find occasion to deny the charge,
and so to quash the indictment.
But she, being asked according to the form, "`Guilty, or not guilty?`"
readily answered, "`Guilty.`"
This astonished the judge; and he told her,
that she seemed not duly to consider what she said; since it could not well be believed,
that such a one as she, who, it might be inconsiderately, had handled her child roughly,
should have killed it willfully and designedly.
Here the judge opened a back door for her to avoid the penalty of death.
But now, the fear of God had got so much room in her heart, that no tampering would do,
no fig-leaves could serve her for a cover,
for she knew now this would have been adding sin to sin,
"`and to cover herself with a covering, but not of God`'s Spirit.`"^
footnote:[Isa. 30:1.]
And therefore she plainly signified to the court,
that indeed she had committed the mischievous fact intentionally;
and that she having sinned thus grievously, and being now affected with true repentance,
she could by no means excuse herself,
but was willing to undergo the punishment the law required:
she could not therefore but acknowledge herself guilty,
since otherwise how could she expect forgiveness from the Lord?

This undisguised and free confession, being spoken with a serious countenance,
so affected the judge, that, tears trickling down his face he sorrowfully said, "`Woman,
such a case as this I never met with before: perhaps you, who are but young,
and speak so piously, as being struck to the heart with repentance,
might yet do much good in the world; but now you force me,
that _ex officio_ I must pronounce sentence of death against you,
since you will admit of no excuse.`"
Standing to what she had said, the judge pronounced sentence of death.
And when afterwards she came to the place of execution,
she made a pathetic speech to the people, exhorting the spectators,
especially those that were young, to have the fear of God before their eyes,
to give heed to his secret reproofs for evil,
and so not to grieve and resist the good Spirit of the Lord:
she not having timely minded this, it had occasioned her to run on in evil,
and thus proceeding from wickedness to wickedness, had brought her to this dismal exit.
But since she firmly trusted in God`'s infinite mercy, and surely believed her sins,
though of a bloody dye, were washed off by the pure blood of Christ, her Redeemer,
she could contentedly depart this life.

Thus she preached at the gallows a doctrine very
consonant with the views of the people called Quakers,
and gave heart melting proofs that her immortal soul was to enter into paradise,
as well as anciently that of the thief on the cross.

[.asterism]
'''

George Fox, in the course of his travels in the work of the ministry, came to Drayton,
in Leicestershire, about the year 1654.
After leaving this his native place, he passed on to one or two towns,
but had not gone far, before he was taken by a party of horsemen,
and brought before colonel Hacker.
At this time there was a noise of a plot against Oliver Cromwell,
so that though George Fox could sufficiently clear himself in this respect,
yet as he dare not promise to make his home a prison,
by giving up the attendance of religious meetings, he was sent up to London,
to be taken before the Protector.

The Protector, on having an account of him, required that he should sign a paper,
promising not to take a weapon against him or the government, as it then was.
This was done on the part of George Fox in a paper, wherein he says,
that he was sent of God to stand a witness against all violence,
and against the works of darkness, and to turn people from darkness to the light,
and to bring them from the occasion of war and fighting to the peaceable gospel.
After some time, the messenger returning, took him to Whitehall.
Being shown into the apartment where the Protector was, George Fox said,
"`Peace be in this house,`" and bade him keep in the fear of God,
that he might receive wisdom from Him, that he might be ordered by it,
and order all things under his hands to God`'s glory.
He had also much discourse with him concerning religion,
wherein Cromwell carried himself very moderately;
but said that George Fox and his friends quarrelled with the ministers.
George Fox signified, that they rather quarrelled with him and his friends;
for he could not uphold such ministers as they were, nor put into their mouths,
seeing they were not such as Christ ever ordained, but such as the Prophets, Christ,
and the Apostles expressly declared against, covetous and greedy,
preaching for dishonest gain, etc.
He further said, That all Christians had the scriptures,
but they lacked the power and Spirit, which _they_ had who gave them forth;
and _that_ was the reason they were not in fellowship with the Son, nor with the Father,
nor with the scriptures, nor one with another.
While he was thus speaking, Cromwell several times said, it was very good, it was truth.

George Fox exchanged many more words with him, but seeing people coming in,
he drew a little back: and as he was turning, Cromwell caught him by the hand,
and with tears in his eyes, said, "`Come again to my house;
for if you and I were but an hour of a day together,
we should be nearer one to the other:`" adding that he wished him no more ill,
than he did to his own soul.
To which George Fox returned, that if he did, he wronged his own soul:
and bade him hearken to God`'s voice that he might stand in his counsel, and obey it;
and if he did so, that would keep him from hardness of heart;
but if he did not hear God`'s voice, his heart would be hardened.^
footnote:[See Ps. 95:7-8.]
This so reached the Protector, that he said it was true.

Then George Fox went out; and Captain Drury his conductor following, told him,
that the Lord Protector said he was at liberty and might go wither he would.
He was then brought into a great hall, where the Protector`'s gentlemen were to dine;
and he asking, what they brought him there for, they told him,
it was by the Protector`'s order, that he might dine with them.
But George Fox, in his mode of speech, bade them tell the Protector,
he would not eat a bit of his bread, nor drink a sup of his drink.
Cromwell, on hearing this said, "`Now I see there is a people risen and come up,
that I cannot win either with gifts, honors, offices, or places;
but all other sects and people I can.`"
But it was told him in reply, that the Quakers had forsook their own,
and were not likely to look for such things from him.

[.centered]
=== The Wrestling Champion

[.embedded-content-document]
--

At London there is a custom in summer time, when the evening approaches,
and tradesmen leave off working, that many lusty fellows meet in the fields,
to try their skill and strength in wrestling,
where generally a multitude of people stand gazing in a ring.
Now it so fell out, that Edward Burrough passed by the place where they were wrestling,
and standing still among the spectators,
saw how a strong and dexterous fellow had already thrown three others,
and was waiting for a fourth champion, if any dared venture to enter the lists.
At length, none being bold enough to try, Edward Burrough stepped into the ring,
which was commonly made up of all sorts of people;
and having looked upon the wrestler with a serious countenance,
the man was not a little surprised, instead of an airy antagonist,
to meet with a grave and awful young man; and all stood as it were amazed at this sight,
eagerly expecting what would be the issue of this combat.
But it was quite another fight Edward Burrough aimed at.
For having already fought against spiritual wickedness, that had once prevailed on him,
and having overcome in measure by the grace of God,
he now endeavoured also to fight against it in others,
and to turn them from the evil of their ways.

With this intention, he began very seriously to speak to the by-standers,
and that with such a heart-piercing power, that he was heard by this mixed multitude,
with no less attention than admiration;
for his speech tended to turn them from darkness to the light,
and from the power of Satan to God.
To effect this he laboured with convincing words,
showing how God had not left himself without a witness,
but had given to man a measure of his grace,
and enlightened everyone with the light of Christ.
Thus zealously he preached; and though many might look upon this as a novelty,
yet it was of such effect, that some were convinced of the Truth:
for he was a breaker of stony hearts, and therefore by a certain author,
not unjustly called "`a son of thunder;`" though he omitted not in due
season to speak a word of consolation to those that were of a broken heart,
and of a contrite spirit.

[.signed-section-signature]
Sewel

--

[.asterism]
'''

Gilbert Latey, a native of Cornwall, was brought up to the trade of a tailor there,
which he afterwards continued to follow, on settling in London.
He was of a sober life and conduct, and having breathings of soul after the Lord,
sought out such as were the most zealous in that day.
The Lord, beholding the integrity of his heart, prospered him in such a manner,
that he grew into great reputation in the world;
having good business in the way of his trade,
and being employed and respected by persons of the
first rank and quality then in the kingdom.
However, through all these outward enjoyments,
his mind and desires were still to find peace with the Lord,
in the knowledge of his pure Truth and way of worship.
Having, in this seeking condition,
gone after those who seemed to him the most refined in their professions,
but with little satisfaction, he fell in with Edward Burrough at a meeting in London;
and being directed by this faithful minister to the only guide to true peace,
not consulting with flesh and blood,
he yielded to the "`heavenly vision,`" taking up the cross and despising the shame,
accounting all things but as dross and dung, that he might "`win Christ,
and be found in Him.`"^
footnote:[Phil. 3:8. 9.]

He had not long enlisted himself under the banner of the Lord, and made profession of,
and confession to, his blessed Truth,
before it pleased the Lord to bring upon him a sore trial,
like the cutting off of the right hand, or pulling out the right eye;
for being still in great business in the world,
and concerned by reason thereof with persons of considerable rank and quality,
who would have their apparel set off with much cost and superfluities of lace and ribbons,
he came under a conscientious concern to decline this superfluous part of his trade,
and not to permit his servants to put such things on the garments of the great.
Upon this, some said he was mad or would be so,
and his fashionable rich customers generally left him, and his trade decayed so much,
that having a great many servants, he was now obliged to part with them;
and knew not but he, who had lately had such extensive business,
might himself be a servant to some of the trade, and work at day labour for his bread.
This his trial was very great, for he was now despised of his own mother`'s children,
and, as it were, banished from his father`'s house;
yet waiting the Lord`'s season in patience, he was sustained under it,
and strengthened to prefer _leaving all,_ to losing his peace with his Maker.

Thus He, who never forsakes those that trust in Him, and are faithful,
bore up his spirit in cheerful resignation under all his exercises,
and not only provided for all his needs,
but enabled him to administer to the needs of others; which he did in various ways,
especially by his influence among persons of rank and high station in the world.
It may be added,
that very soon after he had thus sacrificed to the Lord in obedience to his will,
as before mentioned,
the Lord ordained him a minister of those precious truths and consolations,
for which he had shown so great a preference and value.

[.centered]
=== The Lord D`'Aubigny

The same pious and useful character began early to use his interest
and acquaintance with great personages for the benefit of others,
especially those of the same "`household of faith;`" for whose relief,
under the grievous sufferings allotted them, he was frequently engaged.
On one occasion he thought it his duty to wait upon the Lord D`'Aubigny, who,
on the accession of Charles the Second, came over with the Queen`'s mother,
and was lord almoner to her.
This lord had great influence and power in the Island of Malta,
where two Friends had been closely confined in the prison of the Inquisition,
and treated with cruelty and hardship, for testifying the gospel of the grace of God,
and warning the people to turn unto the Lord.
Gilbert got access to him, and found him to be a well-tempered man;
and though he was a priest in orders,
and Friends at that time almost "`everywhere spoken against`" and ill-treated,
he was very kind and free in his behaviour to Gilbert; and would reason with him,
like Felix with Paul, about the principles of truth, and way of the Lord.

One time, being in discourse with Gilbert, the Lord D`'Aubigny said,
"`Let me talk with you ever so long, you will tell me of the Spirit of God,
and the grace of God, and the works and operation thereof,
and the love of God of which you are made witnesses through Jesus Christ,
which I believe may in a measure be true; but,
do you not think it is well to have something to represent that which you so much love?`"
To which Gilbert answered, that the substance of all things is come, "`Christ _in us,_
the hope of glory;`" and that all the outward types, representations, and shadows,
must come to an end, and be swallowed up in our blessed Lord, who told his disciples,
It was expedient for them he should go away; "`for,`" said he, "`If I go not away,
the Comforter will not come, but if I depart,
I will send him unto you,`" "`even the Spirit of Truth,
which shall guide you into all truth;`" and also said, that He who was then
_with them,_ should be _in them._
So that this being witnessed,
there needed nothing outwardly to represent or put them in mind, He,
being so near man and woman, was the saints`' daily remembrancer.

Upon this they parted; but Gilbert often visited him,
and reminded him to show kindness to the suffering Friends
that were under confinement for conscience sake,
at so great a distance from their friends and native country.
Coming on another occasion to visit him, he bade Gilbert follow him;
when he led him into the Queen`'s chapel, where Gilbert seeing the people on their knees,
and the candles lighted on the altar,
made a halt and asked the Lord D`'Aubigny what he meant, by bidding him come in there;
"`for,`" said he, "`you know, I can bow to nothing;`" upon which he answered,
"`Follow me, and nobody shall hurt you or meddle with you.`"
Upon which, Gilbert followed him through the chapel to a room behind the altar,
where there was another of the Queen`'s priests; and there being some lesser altars,
the Lord D`'Aubigny said to Gilbert.
"`You never yet saw me in my priestly habit,
but now you shall;`" and while he was making ready,
the power of the Lord worked so much on Gilbert,
that he stepped up on a place they called a private altar,
and the word of the Lord came to him to preach unto them; where, among other expressions,
one used by him was, "`We have an altar whereof you have no right to eat.`"
Whereupon the Queen`'s priest asked, "`What altar is this you speak of?`"
Said Gilbert, "`The altar I speak of,
is that on which the saints daily offer up their prayers to the living God:`"^
footnote:[See Rev. 8:8.]
then the priest replied, "`Friend,
there is no greater state attainable than what you speak of;`" and so they parted.

[.asterism]
'''

It is recorded in the history of our religious Society,
that a dismal scene of persecution was opened at Bristol in the year 1682;
the various particulars of which, though they cannot be suitably detailed here,
may perhaps be glanced at,
especially for the sake of one or two little incidents connected with them.

The meetings of Friends were grievously disturbed, their houses broken into,
and almost all manner of violence and abuse committed,
chiefly at the instigation of a cruel sheriff.
It is true, the meetings of other Protestant dissenters were then also disturbed;
but it seems they did not so persist in their religious testimony,
and accordingly were not by any means so obnoxious to that insolent outrage,
to which this people, from their constancy and non-resistance, were liable.
The vilest characters were permitted and encouraged to commit
every kind of "`excess of riot,`" without regard to sex,
age, or condition:
even ancient men and women were hurried to prison with force and blows,
and the little children beaten on the head till they became giddy,
and then taken to Bridewell, and terrified by the prospect of whipping,
unless they would promise to come no more to meetings.

But the malice and threats that were used, even to this class of sufferers,
did not succeed in subduing their constancy.
Scarce a stone was left unturned, in their attempts to afflict the Friends,
and deter them from assembling to worship their Maker.
These disturbances continued till nearly all the men were taken to prison; _there,_
however, their persecutions did not cease,
but were greatly increased by privations and ill-treatment--they were so closely thronged,
that there was barely room for them to rest themselves at night on the floors;
and in other respects also their health and lives were so far endangered,
that four physicians of Bristol thought fit to give forth a certificate to that effect.
After this, the religious meetings of Friends continuing to be kept up, chiefly by women,
they also were seized, till at length few or none but children,
that remained with the servants in the houses of their parents, were left free.

It is very remarkable, however, that those of this description under the age of sixteen,
now performed what their parents were hindered from
doing--they met for the purpose of divine worship,
and continued faithful without fainting, through all the insults of a wicked rabble,
from whom they suffered exceedingly.
Nineteen of them were carried to the House of Correction, and kept some time there,
though they were not within the reach of the law;
and when threatened with whipping if they returned to the meeting,
so great was their zeal, that, despising all reproach and insolence,
they remained steadfast to their duty.
This persecution lasted till the next year,
as it did in many other places throughout the nation at about the same time.

But the above specimen of the sufferings of this Society in early times,
should not be taken by any means as an extreme case.
Those who consult the records of their sufferings,
many of which are recited in their history, or in the memoirs of individuals among them,
may be readily satisfied in this respect.

The foregoing narrative shall be closed with some account of the death of the jailer,
who was the chief instrument of cruelty to the sufferers, after their imprisonment.
Some of the prisoners would have willingly worked in prison,
to earn something for their sustenance, but he would not permit it.
Other prisoners fell sick of the spotted fever, and some died of it.
Yet all this did not soften the hard-hearted jailer.
At length a heavy stroke fell upon him.
He became ill, and was seized with terrible anguish of mind,
and in his distress desired some of those called Quakers to pray for him,
and to forgive him for what he had done.
To which they answered, They forgave him; but he should ask forgiveness of God.
His anguish increased; and when the physicians ordered him to be bled, he said,
No medicine would benefit him, his distemper was another thing:
that no man could do him good, his day being over,
and there was no hope of mercy for him from God!
Friends told him, they desired, if it was the will of God,
he might find a "`place of repentance.`"^
footnote:[Heb. 12:17.]
But whatever was advanced, encouraging him yet to try to obtain peace and mercy,
he would repeat, that his day was over, and that he had no faith to believe.
He remained about a month in this lamentable condition,
and died without any visible signs of forgiveness;
but the judgment thereof must be left to God.

[.asterism]
'''

In the year 1679, Gilbert Latey, being on his way to London out of Cornwall,
where he had gone to visit his native place, came to Exeter;
here he thought proper to wait on the bishop,
whose moderation and kindness had been in a general
manner extended to Friends in his diocese,
and who had done Gilbert several favours in respect
to Friends under sufferings in those parts.
The bishop received him with a great deal of kindness, and taking him in his arms,
expressed his benediction; after which, he led him into a private room, and said,
"`All must not know how well you and I love one another.`"
And then asked Gilbert, what wine he should give him; to which he replied,
he had given him that which was better.
"`Pray,`" said the bishop, "`what mean you by that?`"
Said Gilbert, "`You have given me your love, which is better than wine.`"
"`Then,`" said the bishop, "`if so, pray sit down by me; and, if it may be no offence,
how far have you been, or are going in these parts?`"
To which Gilbert answered how far he had been, and told him of the enquiry he had made,
respecting the condition of his friends, up and down in that diocese,
as he had passed along, and how they had been dealt with in the ecclesiastical courts,
and concerning the moderation shown to Friends by the officers.
"`Well,`" said the bishop, "`and I am sure you will not flatter anybody,
and therefore tell me, what name I have where you have been;`" To which Gilbert replied,
that he had no tidings to give but what was well;
upon which the bishop thanked him both for his enquiry and report.
After acknowledging his kindness and favours, Gilbert in a little time took his leave.

Having at all times easy access to the bishop,
and also liberty freely to address him by letter, when there might be occasion,
Gilbert Latey, in the year 1683, wrote to him on behalf of his friends.
The reply is worthy a Christian bishop, and the insertion of it,
together with the foregoing, may agreeably show, that,
at a period when this kingdom appears to have been
distracted with party spirit and bitter intolerance,
instances were to be found, however rare,
even among the more prominent characters of that day,
of Christian principle imbuing their conduct and conversation with candour,
condescension, and charity.

[.embedded-content-document.letter]
--

[.salutation]
Mr. Latey,

I had acknowledged the receipt of your civil letter before now,
but that I stayed till our court sessions were over,
that I might see what proceedings were made against any of your persuasion;
and I can hear of none.
I find no process of late against them in any of my courts,
for I have examined my officers about it.
What the justices of peace have done in their monthly meetings, I know not;
but sure I am, that such as live quiet and peaceable in the land, by any order from me,
are no way disturbed;
and I believe the justices are gentle enough to such as do not affront them.
I never was, nor will be for persecution, but shall endeavour that by any amicable way,
such as have erred, may be brought into the way of Truth,
and that we may all enjoy one another in heaven.
I am now somewhat indisposed: writing is irksome to me.
God Almighty bless you.
I am your truly loving friend,

[.signed-section-signature]
Thomas Exon.

[.signed-section-context-close]
Exeter, March the 24th, 1684.

--

[.centered]
=== Popularity

[.offset]
George Fox, speaking of his travels in America, says:

[.embedded-content-document]
--

We went to Narraganset, about twenty miles from Rhode Island,
and the governor of Rhode Island
went with us.
We had a meeting at a justice`'s, where Friends never had any before;
the meeting was very large, for the country generally came in;
and people from Connecticut, and other parts round about.
There were four justices of peace.
Most of these people had never heard Friends before; but they were mightily affected,
and a great desire there is after the Truth among them.
So, that meeting was of very good service; blessed be the Lord forever!

At another place I heard some of the magistrates said among themselves,
If they had money enough, they would hire me to be their minister:
this was where they did not well understand us, or our principles.
But when I heard of it, I said, It was time for me to be gone;
for if their eye was so much to me, or any of us,
they would not come to _their own Teacher._
For this thing, namely, _hiring_ ministers, had spoiled many,
by hindering them from improving their own talents;
whereas our labour is to bring everyone to their own Teacher in themselves?^
footnote:[1 John 2:27.]

--

[.offset]
To the above may be subjoined an extract or two from an epistle of the same writer,
as follows:

[.embedded-content-document.epistle]
--

In the days of the apostles, when some were crying up Paul and Apollos, and so forth,
Paul judged them as carnal;
and exhorted and admonished them that their faith should not stand in men,
nor in the words of man`'s wisdom, but in the power of God.^
footnote:[1 Cor. 2:5.]
He said, He would not know the speech of them, but the power among them;
for the kingdom of God is not in word, but in power.^
footnote:[1 Cor. 4:19.]
So is it to be now.
Everyone`'s faith must stand in the power of God, and not in men,
nor their speeches upon the good words.
For we have seen by experience, when they begin to cry up men,
and their faith stands in them; such as would have people`'s faith to stand in them,
love popularity, and bring not people`'s faith to stand in the power of God.
Such do not preach Christ, but themselves.
Such cannot exalt Christ; and when such fall, they draw a great company after them.
They, whose faith stands in men, will make sects; the faith of such,
Christ is not the author of; if he has been, they have erred from it,
and made shipwreck of it.
All that are in the true faith, that stands in the power of God,
will judge them as carnal,
and judge down that carnal part in them that cries up Paul or Apollos;
that their faith may stand in the power of God, and that they may exalt Christ,
the author of it.

Therefore all should know one another in the spirit, life and power, and look at Christ;
this keeps all in humility.
For everyone`'s eye ought to be to Jesus,
and every just man and woman may live by their faith,^
footnote:[Heb. 10:38]
of which Christ is the author and finisher.
By this faith every man may see God, who is invisible; which faith gives the victory;
so everyone`'s faith and hope standing in the power of God, therein all have unity,
victory, and access to God`'s throne of grace; in which faith they please God.
By this faith they are saved, obtain the good report,
and subdue all the mountains between them and God.

--

[.centered]
=== Two Visits at Isaac Penington`'s

[.embedded-content-document]
--

During my father`'s abode in London +++[+++says Thomas Ellwood,]
in the time of the civil wars, he contracted a friendship with the Lady Springett,
then a widow, and afterwards married to Isaac Penington, esquire; to continue which,
he sometimes visited them at their country lodgings, as at Datchet,
and at Causham Lodge near Reading.
And having heard that they were come to live upon their own estate,
at Chalfont in Buckinghamshire, about fifteen miles from Crowell,
he went one day to visit them there, and to return at night, taking me with him.

But very much surprised we were, when, being come there, we first heard, then found,
they were become Quakers; a people we had no knowledge of, and a name we had, till then,
scarce heard of.

So great a change, from a free, debonair, and courtly sort of behaviour,
which we formerly had found them in, to so strict a gravity as they now received us with,
did not a little amuse us,
and disappoint our expectation of such a pleasant visit
as we used to have and had now promised to ourselves.
Nor could my father have any opportunity, by a private conference with them,
to understand the ground or occasion of this change;
there being some other strangers with them, related to Isaac Penington,
who came that morning from London to visit them also.

For my part, I sought,
and at length found means to cast myself into the company of the daughter,
whom I found gathering some flowers in the garden, attended by her maid,
who was also a Quaker.
But when I addressed myself to her, after my accustomed manner,
with intention to engage her in some discourse, which might introduce conversation,
on the foot of our former acquaintance; though she treated me with a courteous demeanor,
yet, as young as she was,
the gravity of her look and behaviour struck such an awe upon me,
that I found myself not so much master of myself,
as to pursue any further converse with her.
Therefore, asking pardon for my boldness,
in having intruded myself into her private walks, I withdrew, not without some disorder,
as I thought, at least of mind.

We stayed dinner, which was very handsome, and lacked nothing to recommend it to me,
but the lack of mirth and pleasant discourse: which we could neither have with them,
nor by reason of them, with one another among ourselves;
the weightiness that was upon their spirits and countenances,
keeping down the lightness that would have been up in us.
We stayed, notwithstanding, till the rest of the company took their leave of them;
and then we also, doing the same, returned, not greatly satisfied with our journey,
nor knowing what in particular to find fault with.

Yet this good effect that visit had upon my father,
who was then in commission for the peace,
that it disposed him to a more favourable opinion of,
and carriage towards those people when they came in his way.

Some time after this, my father,
having gotten some further account of the people called Quakers,
and being desirous of being informed concerning their principles,
made another visit to Isaac Penington and his wife, at their house called the Grange,
in Peter`'s Chalfont, and took both my sisters and me with him.

It was in the tenth month of the year 1659, that we went there,
where we found a very kind reception, and tarried some days; one day at least longer,
for that, while we were there,
a meeting was appointed at a place about a mile from there;
to which we were invited to go, and willingly went.
It was held in a farm house called the Grove, which,
having formerly been a gentleman`'s seat, had a very large hall, and that well filled.

To this meeting came Edward Burrough, besides other preachers, as Thomas Curtis,
and James Nayler: but none spoke there at that time but Edward Burrough.
Next to whom, as it were under him, it was my lot to sit on a stool,
by the side of a long table, on which he sat; and I drank in his words with desire;
for they not only answered my understanding, but warmed my heart with a certain heat,
which I had not till then felt from the ministry of any man.
When the meeting was ended, our friends took us home again; and after supper,
the evenings being long, the servants of the family (who were Quakers) were called in,
and we all sat down in silence.
But long we had not so sat, before Edward Burrough began to speak among us.
And although he spoke not long, yet what he said did touch, as I suppose,
my father`'s religious "`copyhold,`" as the phrase is.
And he having been from his youth a professor,
(though not joined in that which is called close communion with any one
sort,) and valuing himself upon the knowledge he esteemed himself to have,
in the various notions of each profession,
thought he had now a fair opportunity to display his knowledge:
and thereupon began to make objections against what had been delivered.

The subject of the discourse was the universal free grace of God to all mankind;
to which he opposed the Calvinistic tenet of particular and personal predestination.
In defence of which indefensible notion, he found himself more at a loss than he expected.
Edward Burrough said not much to him upon it, though what he said was close and cogent.
But James Nayler interposing, handled the subject with so much perspicuity,
and clear demonstration, that his reasoning seemed to me irresistible:
and so I suppose my father found it, which made him willing to drop the discourse.
As for Edward Burrough, he was a brisk young man, of a ready tongue, and might have been,
for all I then knew, a scholar, which made me the less to admire his way of reasoning.
But what dropped from James Nayler had the greater force upon me,
because he looked like a plain simple countryman,
having the appearance of a husbandman or a shepherd.
As my father was not able to maintain the argument on his side,
so neither did they seem willing to drive it on to an extremity on their side; but,
treating him in a soft and gentle manner, did after a while let fall the discourse;
and then we withdrew to our respective chambers.

The next morning we prepared to return home (that is, my father, my younger sister,
and myself; for my elder sister was gone before by the stage coach to London.) And when,
having taken our leaves of our friends, we went forth,
they with Edward Burrough accompanying us to the gate,
he there directed his speech in a few words to each of us severally,
according to the sense he had of our several conditions.
And when we were gone off, and they gone in again, they asking him what he thought of us,
he answered them, as they afterwards told me, to this effect: "`As for the old man,
he is settled on his lees; and the young woman is light and airy:
but the young man is reached, and may do well if he does not lose it.`"
And surely that which he said to me, or rather that spirit in which he spoke it,
took such fast hold on me, that I felt sadness and trouble come over me,
though I did not distinctly understand what I was troubled for.
I knew not what I ailed, but I knew I ailed something more than ordinary;
and my heart was very heavy.
I found it was not so with my father and sister; for as I rode after the coach,
I could hear them talk pleasantly one to the other,
but they could not discern how it was with me, because I riding on horseback,
kept much out of sight.

--
