== Chapter VI

[.centered]
=== Admiral Tyrrell

Samuel Fothergill, being at Scarborough,
observed that admiral Tyrrell attended several meetings of Friends at that place,
and took particular notice of the solemnity and reverence
of the admiral`'s behaviour during the meeting,
especially in the time of silence.

A little after this, the admiral came up to Samuel, in the public rooms,
before many of the nobility and gentry, and said, "`Mr. Fothergill,
I have a very high opinion of your people`'s principles and practice,
especially the inwardness and spirituality of your silent worship.`"
Samuel replied, "`Admiral,
I think such a testimony as this rather extraordinary from you, as a man of war,
concerning us and our principles, which are for peace and against all fighting.`"
The other continued, "`Sir, I am of your opinion in that particular;
and fully believe that the time will come,
when '`nation shall not lift up sword against nation,
neither learn war any more:`' but as every dispensation
of unerring Wisdom must have a beginning,
so this has had among you, but has not yet reached us.
And as to what you hold, of a union and communion with the divine Intelligencer,
I know by happy experience it is attainable in this age;
one instance of which now occurs to me.

"`When I had the honour to command three of his majesty`'s ships of war as commodore,
a little before the last peace was concluded,
an account was brought that five large French ships of war were bearing towards us,
all superior to us in men and guns;
a council of war was immediately called upon this occasion, and while they sat,
I retired into my cabin alone; and after getting into perfect silence,
I heard in the secret of my mind a voice intelligible to
my understanding as any words ever were to my outward senses,
'`Go, and fight the French fleet,
for I have delivered them into your hands.`' I rose
reverently thankful for this divine intimation,
letting the council know, that we should fight the French fleet,
and that I was sure of victory.
All things were made ready,
and the event proved the certainty of the gracious intimation;
we having gained a complete victory, as set forth in the history of that war.`"

The above particulars of this interview were communicated
by Samuel Fothergill to a Friend,
as they were travelling together on their way from
London after the yearly meeting of 1770;
and having been in print, may, consistently with the title of this collection,
occupy a place in it.
It conveys a very clear illustration of one view which we take on the subject of war,
while it is also confirming to those who believe in the manifestations of the Holy Spirit.

We cannot consider these manifestations, or discoveries of the divine will,
to be limited to any age of the world, or to any set of people,
or even to any hour of a man`'s life,
nor can we in any way confine the influence and operations of it, either as to the kind,
mode, extent or purpose of them.
Divine grace, mercy, light, truth or power, visiting and redeeming the soul of lost man,
constitutes, undoubtedly, the main-spring of _religion;_
and he who does not resist _this_ in its palpable suggestions,
but on the contrary thankfully and simply avails of the
ability it never fails to bring with it--this man,
according to his capacity or gift of grace,
begins to know something of the rudiments of religion; and in our apprehension,
if he follows on to know the Lord, and _thus to_ believe on and abide in Him,
will in the end be accepted of Him.
Without this heavenly breath of life in him, poor man is _as dead,_
he cannot move one step forward in the way of salvation.

How great then is the free and universal gift of God in his Son,
"`the quickening Spirit.`"^
footnote:[1 Cor. 15:45.]
"`The Light of the world,`" the only way to the Father.
It was through this "`obedience of faith`" to the one great object of faith,
that all the faithful, from righteous Abel to this day, inherited the promises.
It was through the revelation of the eternal Spirit _inwardly,_
in their hearts and consciences, that the ancient patriarchs, prophets, and apostles,
according to their several dispensations of light,
became acquainted with the path of peace;
and by the help of the same were they enabled to please God and to worship him.
Visions and the ministry of angels appear to have each formed
a channel of divine communication in _that_ day,
as those and many other means have since; but whatever method, direct or indirect,
the Lord in the riches of his mercy is pleased to
provide for the service of his creature man,
it still remains most strictly a truth, that "`no man knows the Son, but the Father;
neither knows any man the Father save the Son,
and he _to whomsoever the Son will reveal Him._`"^
footnote:[Matt. 11:27.]
So that where instrumental aid is vouchsafed,
the recipient as well as the poor agent are alike beholden to the Author of all good,
for the _immediate_ extension of his blessing--even for the capacity to understand, apply,
and put in practice His essential saving Truth, the same yesterday, today, and forever.

The summary remarks just given,
on _some_ of the bearings only of this deeply important and very extensive subject,
it is hoped, may not stumble any sincere enquirer in the way to Zion.
It did not seem properly the place here to go into
the connecting links and numerous branchings,
that may readily occur to the mind on perusing the above;
and perhaps on this account it might be well for the reader,
not thoroughly acquainted with our tenets,
to be cautious in making deductions from this brief notice,
lest he should causelessly attribute error to his fellow-professors of Christianity.^
footnote:[William Penn`'s [.book-title]#Christian Quaker# is calculated to convey
much information and instruction connected with this subject.]

One other observation may be added to the foregoing.
Many who unite with us in regard to these things, do not so fully see with the admiral,
that the position of mind best calculated to perceive and receive
the secret but intuitively evident pointings of divine Wisdom,
is that of a frequent and positive abstractedness, as much as may be,
from "`the things`" that "`are seen`" which "`are temporal,`"--a listening stillness
of soul,--a turning from the mere wanderings of the unsubjected imagination,
accompanied by an express surrender of our whole hearts to our Maker,
with desire that he may make and keep them fit temples
for the indwelling of his holy Spirit.
That this is hard work, and a great attainment, is not denied;
yet those who have been constrained to be attempting to walk in this way,
find it a path of pleasantness and of inward peace:
these too do assuredly know hard things rendered easy,
help being laid upon One that is mighty.
In the course of their duties among their fellow-mortals,
these are engaged to weigh well their words, and their actions,
and even their very thoughts come under regulation;
their general demeanour is accordingly such as on _every_ hand becomes the gospel of Christ,
for they profess to walk with God, and to believe and feel him present,
a God nigh at hand indeed in the hearts of his dependent children.

[.centered]
=== George Fox and the Papist

[.embedded-content-document]
--

While I was in London in the year 1668,
I went one day to visit him that was called esquire Marsh,
who had showed much kindness both to me and to Friends.
I happened to go when he was at dinner.
He no sooner heard of my name, than he sent for me up,
and would have had me sit down with him to dinner; but I had not freedom to do so.
Several great persons were at dinner with him; and he said to one of them,
who was a great Papist, "`Here is a Quaker; which you have not seen before.`"
The Papist asked me, Whether I owned the christening of children?
I told him, There was no scripture for any such practice.
"`What,`" said he, "`not for christening`' children?`"
I said, "`No;`" and told him,
the _one baptism_ by the _one Spirit_ into the _one body_ we owned; but,
to throw a little water in a child`'s face, and say,
_that_ was baptizing and christening it, there was no scripture for that.

Then he asked me, Whether I owned the Catholic faith?
I said, Yes; but added, that neither the Pope nor the Papists were in the Catholic faith;
for the true faith works by love,^
footnote:[Gal. 5:6.]
and purifies the heart;^
footnote:[Acts 15:9.]
and if they were in that faith that gives victory,
by which they might have access to God,^
footnote:[Eph. 3:12.]
they would not tell the people of a purgatory after they were dead, for the true,
precious divine faith, which Christ is the author of,
gives victory over the devil and sin, that separates man and woman from God.
And if they (the Papists) were in the true faith, they would never use racks,
prisons and fines, to persecute and force others to their religion,
that were not of their faith.
This was not the practice of the apostles and primitive Christians,
who witnessed and enjoyed the true faith of Christ;
but it was the practice of the faithless Jews and heathens so to do.

"`But,`" said I, "`seeing you are a great leading man among the Papists,
and have been taught and bred up under the Pope; and seeing you say,
_there is no salvation_ but in your church; I desire to know of you,
what it is that does bring salvation in your church?`"
He answered, "`A good life.`"
"`And nothing else?`"
said I. "`Yes;`" said he, "`good works.`"
"`Is this it that brings salvation in your church; a good life and good works?
Is this your doctrine and principle?`"
said I, "`Yes,`" said he.
"`Then,`" said I, "`neither you, nor the Pope,
nor any of the Papists know what it is that brings salvation.`"
He asked me, What brought salvation in our church?
I told him, That which brought salvation to the Church in the apostles`' days,
the same brought salvation to us, and not another; namely, "`the grace of God,`" which,
the Scripture says, "`brings salvation,
and has appeared to all men;`" This taught the saints then, and teaches us now.
This grace, which brings salvation, teaches "`to deny ungodliness and worldly lusts,
and to live godly, righteously, and soberly.`"
So it is not the good works, nor the good life, that brings salvation, but the grace.

"`What,`" said a the Papist, "`does this grace, that brings salvation,
appear to all men?`"
"`Yes,`" said I. "`Then,`" said he, "`I deny that.`"
I replied, "`All that deny _that_ are sect-makers, and are not in the universal faith,
grace and Truth, which the apostles were in.`"
Then he spoke to me about the mother-church.
I told him, The several sects in Christendom had accused us, and said,
We forsook our mother-church.
The Papists charged us with forsaking their church, saying,
Rome was the only mother-church.
The Episcopalians taxed us with forsaking the old protestant religion,
alleging theirs was the reformed mother-church.
The Presbyterians and Independents blamed us for leaving them, each of them pretending,
theirs was the right reformed church.
But, I said, if we could own any outward place to be the mother-church,
we should own _Jerusalem,_
where the gospel was first preached by Christ himself and the apostles,
where Christ suffered, where the great conversion to Christianity by Peter was,
where were the types, figures, and shadows which Christ ended,
and where Christ commanded his disciples to wait,
until they were endued with power from on high.

If any outward place deserved to be called the mother, that was the place,
where the first great conversion to Christianity was.
But the apostle says, "`Jerusalem, which now is, is in bondage with her children.
But Jerusalem, which is above, is free, which is the mother of us all.`"^
footnote:[Gal. 4:25. 26.]
And though this title,
"`mother,`" has been given to places and sects by the degenerate Christians,
yet we say still, as the apostle said of old, "`Jerusalem, which is above,
is the mother of us all.`"
We can own no other, neither outward Jerusalem, nor Rome,
nor any sect of people for our mother, but Jerusalem, which is above, which is free,
the mother of all that are born again, become true believers in the Light,
and are grafted into Christ, the heavenly Vine.
For all who are "`born again of the immortal seed, by the Word of God,
which lives and abides forever,`" feed upon the "`milk of the Word,`" the breast of life,
grow in life by it, and cannot acknowledge any other to be their mother,
but Jerusalem which is above.

"`Oh!`" said squire Marsh to the Papist, "`you do not know this man.
If he would but come to church now and then, he would be a brave man.`"

[.signed-section-signature]
_George Fox`'s Journal._

--

[.centered]
=== Thomas Ellwood`'s Account of His Marriage

[.embedded-content-document]
--

I had always entertained so high a regard for marriage, as it was a divine institution,
that I held it not lawful to make it a sort of political trade to rise in the world by.
And therefore as I could not but in my judgment blame those,
who made it their business to hunt after,
and endeavour to gain such as were accounted _great fortunes;_
not regarding so much what _she is,_ as what _she has,_ thus making wealth the chief,
if not the only thing they aimed at:
so I resolved to avoid in my own practice that course;
and however much my condition might have prompted me, as well as others,
to seek advantage that way, never to engage on the account of riches,
nor at all to marry, till judicious affection drew me to it;
which I now began to feel at work in my breast.

The object of this affection was a friend, whose name was Mary Ellis,
whom for several years I had had an acquaintance with,
in the way of common friendship only;
and in whom I thought I then saw those fair prints of Truth and solid virtue,
which I afterwards found in a sublime degree in her:
but what her condition in the world was, as to estate, I was wholly a stranger to,
nor desired to know.

I had once, a year or two before, had an opportunity to do her a small piece of service,
in which she needed some assistance;
wherein I acted with all sincerity and freedom of mind,
not expecting or desiring any advantage by her, or reward from her,
being very well satisfied in the act itself,
that I had served a friend and helped the helpless.
That little interaction of common kindness between
us ended without the least thought (I am verily persuaded,
on her part, and well assured on my own,) of any other or further relation,
than that of free and fair friendship;
nor did it at that time lead us into any closer conversation,
or more intimate acquaintance one with the other, than had been before.

But after a considerable while,
I found my heart secretly drawn and inclining towards her:
yet was I not hasty in proposing,
but waited to feel a satisfactory settlement of mind in it before any step was taken.

After some time, I took an opportunity to open my mind to my much honoured friends,
Isaac and Mary Penington, who then stood _paretum loco,_
in the place or stead of parents to me.
They having solemnly weighed the matter, expressed their unity therewith:
and indeed their approbation was no small confirmation to me.
Yet I took further deliberation, often retiring in spirit to the Lord,
and crying to Him for direction, before I addressed myself to her.
At length as I was sitting all alone,
waiting upon the Lord for counsel and guidance in this, in _itself_ and to _me,_
so important affair, I felt a word sweetly arise in me, as if I had heard a voice,
which said, "`Go, and prevail.`"
And faith springing in my heart with the word,
I immediately rose and went nothing doubting.

When I was come to her lodgings, which were about a mile from me,
I desired the maid to acquaint her mistress, that I was come to give her a visit:
whereupon I was invited to go up to her.
And after some common conversation had passed, feeling my spirit weightily concerned,
I solemnly opened my mind unto her, with respect to the particular business I came about;
which I soon perceived was a great surprisal to her.
For she had taken in an apprehension, as others also had done,
that my eye had been fixed elsewhere, and nearer home.
I used not many words to her; but I felt a divine power went along with the words,
and fixed the matter expressed by them so fast in her breast, that,
as she afterwards acknowledged to me, she could not shut it out.

I made but a short visit.
For, having told her, I did not expect an answer from her then: but desired she would,
in the most solemn manner, weigh the proposal made,
and in due time give me such an answer thereunto, as the Lord should give her;
I took my leave of her and departed, leaving the issue to the Lord.

I had a journey then at hand, which I foresaw would take me up about two weeks.
Therefore, the day before I was to set out, I went to visit her again,
to acquaint her with my journey and excuse my absence;
not yet pressing her for an answer,
but assuring her that I felt in myself an increase of affection to her,
and hoped to receive a suitable return from her in the Lord`'s time;
to whom in the meanwhile, I committed both her and myself, and the concern between us.
And indeed, I found at my return, that I could not have left it in a better hand;
for the Lord had been my advocate in my absence,
and had so far answered all her objections, that when I came to her again,
she rather acquainted me with them, than urged them.

From that time forward,
we entertained each other with affectionate kindness in order to marriage;
which yet we did not hasten to but went on deliberately.
Neither did I use those vulgar ways of courtship, by making frequent and rich presents;
not only for that my outward condition would not comport with the expense,
but because I liked not to obtain by such means, and preferred an unbribed affection.

I continued my visits to my best beloved friend, until we married;
which was in the year 1669.
We took each other in a select meeting, of the ancient and grave Friends of that country,
held in a Friend`'s house; where, in those times,
not only the monthly meeting for church discipline, but the public meeting for worship,
was sometimes kept.
A very solemn meeting it was, and in a weighty frame of spirit _we_ were;
in which we sensibly felt _the Lord with us, and joining us;_
the sense whereof remained with us all our lifetime,
and was of good service and very comfortable to us on all occasions.

--

[.centered]
=== Extract From George Fox`'s Journal

[.embedded-content-document]
--

About the year 1660
we received account from New England,
"`That the government there had made a law to banish the Quakers out of their colonies,
upon pain of death in case they returned; that several of our Friends,
having been so banished, and returning, were thereupon taken and actually hanged,
and many more were in prison,
and in danger of the like sentence to be executed upon them.`"
When those were put to death I was in prison at Lancaster,
and had a perfect sense of their sufferings as though it had been myself,
and as though the halter had been put about my own neck,
though we had not at that time heard of it.
But as soon as we heard of it, Edward Burrough went to the king, and told him,
"`There was a vein of innocent blood opened in his dominions,
which if it were not stopped would overrun all,`" To which the king replied,
"`But I will stop that vein.`"
Edward Burrough said, "`Then do it speedily,
for we know not how many may soon be put to death.`"
The king answered, "`As speedily as you will.
Call,`" said he to some present, "`the secretary, and I will do it presently.`"
The secretary being called, a mandamus was forthwith granted.

A day or two after,
Edward Burrough going again to the king to desire the matter might be expedited,
the king said, He had no occasion at present to send a ship there,
but if _we_ would send one, we might do it as soon as we would.
Edward then asked the king,
if it would please him to grant his deputation to one called a Quaker,
to carry the mandamus to New England?
He said, "`Yes, to whom you will.`"
Whereupon Edward Burrough named Samuel Shattock,
who being an inhabitant of New England was banished by their law,
to be hanged if he came again; and to him the deputation was granted.
Then he sent for an honest Friend, who was master of a good ship,
and agreed with him for three hundred pounds (goods or no goods) to sail in ten days.
He forthwith prepared to sail, and with a prosperous gale, in about six weeks,
arrived before the town of Boston, upon a first-day morning.
With him went many passengers, both of New and Old England, Friends,
whom the Lord had moved to go and bear their testimony against those bloody persecutors,
who had exceeded all the world in that age in their bloody persecutions.

The townsmen of Boston, seeing a ship come into the bay with English colours,
soon came on board, and asked the commander if he had any letters?
He said, "`Yes.`"
They asked if he would deliver them?
He said, "`No, not today.`"
So they went ashore, and reported.
There was a ship full of Quakers, and that Samuel Shattock was among them,
who they knew was by their law to be put to death for coming again after banishment;
but they knew not his errand nor his authority.
Next morning Samuel Shattock the king`'s deputy, and the commander went on shore,
and sending back to the ship the men who landed them,
they went through the town to the governor`'s door, and knocked.
He sent out a man to know their business.
They sent him word their business was from the king of England,
and they would deliver their message to none but the governor himself.
Thereupon they were admitted, and the governor came to them;
and having received the deputation and mandamus, he put off his hat,
and looked upon them.
Then going out, he bade the two Friends follow him.
He went to the deputy governor, and after a short consultation came out to them,
and said, "`We shall obey his majesty`'s commands.`"

After this the master gave liberty to the passengers to come on shore,
and presently the noise of the business flew about;
and the Friends of the town and passengers of the ship met together
to offer up their praises and thanksgivings to God,
who had so wonderfully delivered them from the teeth of the devourer.
While they were thus met, in came a poor Friend, who,
being sentenced by their law to die, had lain some time in irons expecting execution.
This added to their joy, and caused them to lift up their hearts in high praises to God,
who is worthy forever to have the praise, the glory, and the honour;
For He only is able to deliver, to save,
and support all that sincerely put their trust in Him.

--

[.centered]
=== The Illiterate Preacher

[.offset]
John Churchman, visiting New England in 1742, had a meeting near Newberry.
Of this meeting, he says:

[.embedded-content-document]
--

I was concerned to speak in a brief manner of the beginning
of the reformation from the errors of the church of Rome,
and the sufferings of the Protestants, particularly in England,
some of whose successors turned persecutors,
and were very cruel to those whom they called Sectarians; among these,
the Presbyterians came into America, and settled into New England,
expecting there to enjoy that reasonable right, and liberty of their conscience.
But forgetting the golden rule of doing to others as they would be done unto,
they became persecutors of the people called Quakers,
even to the death of several of them.

And I had to speak of the nature and ground of persecution,
and the great inconsistency thereof with Christianity.
Several of the Presbyterians were present; and an old man from Newberry,
one of their leaders and an elder among them, when the meeting was over,
desired he might speak with me.

I being withdrawn into a little parlour, a Friend came and informed me,
that the old man wanted to be admitted to me, to which I felt no objection,
being quiet and easy in my mind, though I expected he would be for disputing.
When he came in, he let me know he had some observations to make to me; he said,
he supposed I was a man that had read much,
or I could not be so fully acquainted with the reformation,
and that he also supposed I had had a college education.
As to the last, I told him that I never had been at a school but about three months,
and the man I went to, being a weaver, sat in his loom and heard his scholars read;
that I was so far from having had a popular education,
that I was born in a wilderness place, where a few families had settled,
many miles remote from other inhabitants: at which, lifting up his hands,
he blessed himself and added, "`Heaven has then anointed you to preach the gospel,
and you have this day preached the Truth; but I can assure you,
though I have been a parish officer,
I never did take anything from your friends the Quakers, for I am against persecution;
so God bless you with a good journey.`"

--

[.centered]
=== Visit at Weiwart

The succeeding relation is given by William Penn,
in the account he has left of his travels in Holland and Germany, in the year 1677.
This journey appears to have been undertaken solely on a religious account; in part,
to visit and confirm his fellow professors in that precious testimony and doctrine,
of which they had partaken,
and partly that he might contribute (under the express appointment, direction,
and assistance of his holy Leader,) to the expansion and spread of the kingdom
of Christ,--that blessed kingdom which is declared to be "`righteousness,
peace, and joy in the holy spirit.`"^
footnote:[Rom. 14:17.]

[.embedded-content-document]
--

Having refreshed ourselves with food, we took waggon for Wiewart,
the mansion-house of the family of the Somerdykes, where J. de Labadie`'s^
footnote:[In another part of the journal William Penn thus describes
this person.
{footnote-paragraph-split}
"`This man was a Frenchman,
who being dissatisfied with the looseness and deadness of the French Protestants,
even at Geneva itself, left them and came to Holland,
and so vehemently declaimed against the apostasy of the priests and people there,
that the clergy were enraged, and stirred up the magistrates against him; and the rather,
because many followed him,
and several women of great quality.
{footnote-paragraph-split}
"`I
was moved to visit this man and his company six years ago,
and did see him and his two great disciples;
but they would not allow me to see the people, which I laboured for.
I in that day saw the airiness and unstableness of the man`'s spirit,
and that a '`sect-master`' was his name; and it was upon me,
both by word of mouth and writing, to let them know,
that the enemy would prevail against them to draw them into inconvenient things,
if they came not to be stayed in the light of Jesus Christ, and to know the holy silence;
and that at last they would come to fall out one with another and moulder away.
This is in some measure come to pass, as I feared; for I clearly perceived,
that though they had received some divine touches,
there was a danger they would run out with them, and spend them like prodigals,
not knowing then where to stay their minds for _daily bread._
Indeed, though they were something angelical, and like to the celestial bodies,
yet if they kept not their station, they would prove fallen stars.
They moved not in the motion of Him that had visited them,
but were filled with gross mixtures.
Yet I believed well of some of the people, for a good thing was stirring in them.`"]
company resides, it being strong upon my spirit to give them a visit.
We got there about five; and as we were walking over a field to the house,
we met a young man of that company, who conducted us in.
I asked for Ivon the pastor, and Anna Maria Schurmans.
Ivon presently came with his co-pastor; they received us very civilly,
desiring me to come in.
But foreseeing my time would be too short for my message, the sun being near setting,
and having two English miles of unknown way to our lodging, on foot, I desired them,
that they would give me an opportunity the next morning,
which they readily complied with.
So I took my leave of them, who in a friendly manner brought us a little on our way.
That night a great weight was upon my spirit, and especially the next morning;
yet my faith was in the power of God,
and I had a plain sense that I should have a good
service among them that I should clear my conscience,
and my peace should rest with me.

The next morning I returned to them, and John Claus with me.
So soon as we came we were shown into Anna Maria Schurmans`' apartment,
where also was with her one of the three Somerdykes.

Anna Maria Schurmans is above sixty years of age, of great note and fame for learning,
in languages and philosophy,
and has obtained a considerable place among the most learned men of this age.
The Somerdykes are daughters of a nobleman of the Hague,
people of great breeding and inheritances.
These, with several other persons,
being affected with the zealous declamation of J. de Labadie,
against the dead formal churches of the world,
and awakened to seek after a more spiritual fellowship and society,
separated themselves from the common Calvinist churches,
and followed him in the way of a refined independency.

They are a serious, plain people, and are come nearer to Friends,
as in silence in meetings, women`'s speaking, preaching by the Spirit,
plainness in garb and the furniture of their houses.
With these two, we had the company of the two pastors, and a doctor of medicine.
After some silence, I proposed this question to them:
What was it that induced them to separate from the common way they formerly lived in?
I desired them that they would be pleased to be plain and open with me,
as to the ground of their separation; for I came not to cavil,
but in a Christian spirit to be informed.

Upon this, Ivon, the chief pastor, gave us the history of J. de Labadie`'s education,
how he was bred among the Jesuits, and deserted them,
and embraced the Protestant religion,
and of his great dissatisfaction with the Protestant churches.
Adding several solemn appeals concerning the simplicity
and integrity of their hearts in these things.

Ivon having done, Anna Maria Schurmans began.
She told us of her former life, of her pleasure in learning,
and her love to the religion she was brought up in;
but confessed she knew not God or Christ truly all that while.
And though from a child God had visited her at times,
yet she never felt such a powerful stroke, as by the ministry of J. de Labadie.
She saw her learning to be vanity, and her religion like a body of death;
she resolved to despise the shame, desert her former way of living and acquaintance,
and to join herself with this little family, that was retired out of the world;
among whom she desired to be found a living sacrifice, offered up entirely to the Lord.
She spoke in a very serious and broken sense, not without some trembling.
These are but short hints of what she said.

Then one of the Somerdykes began, in a very reverent and weighty frame of mind,
and in a sense that very well suited her contempt of the world:
she told us how often she had mourned from her young years,
because she did not know the Lord as she desired; often saying within herself,
"`If God would make known to me his way,
I would trample upon all the pride and glory of the world.`"
She earnestly expressed the frequent anguish of spirit she had,
because of the deadness and formality of the Christians she was bred among,
saying to herself, "`O the pride, O the lusts,
O the vain pleasures in which Christians live!
Can this be the way to heaven?
Is this the way to glory?
Are these the followers of Christ?
O no!
O God, where is your little flock, that will live entirely to you, that will follow you?
Make me one of that number.

"`And when,`" continued she, "`the servant of the Lord, J. de Labadie, came into Holland,
I among others had a curiosity to hear him, and with several was deeply affected.
He spoke the very thoughts of my heart; my heart was pricked when I heard him;
and I resolved by the grace of God to abandon all the glory and pride of this world,
to be one of those that should sit down with him in a separation
from the vain and dead worships of this world.
I count myself happy that I ever met with him, and these pastors,
who seek not themselves, but the Lord.
And we are a family that live together in love, of one soul and one spirit,
entirely given up to serve the Lord; and this is the greatest joy in the world.`"

After, Du Lignon, the other pastor,
gave us also an account of his inducement to embrace J. de Labadie, but not so livelily.

After him the doctor of medicine, that had been bred for a priest,
but voluntarily refused that calling, expressed himself after this manner,
"`I can also bear my testimony in the presence of God,
that though I lived in as much reputation at the university, as any of my colleagues,
and was well reputed for sobriety and honesty,
yet I never felt such a living sense of God, as when I heard the servant of the Lord,
J+++.+++ de Labadie:`" adding, "`The first day I heard him,
I was so struck and affected that I can truly say,
through the good grace of God and the conduct of the holy Spirit,
it was to me as the day of my salvation;
he did so livingly touch my heart with a sense of the true Christian worship: upon which,
I forsook the university, and, resolved to be of this family.
And this I can say in the fear of the Lord.`"

Then Ivon thus concluded,
"`This is what we have to say concerning the work of God among us.`"

All this while, I minded not so much their words,
as I felt and had unity with a measure of divine sense that was upon them.
Certainly the Lord has been among them; yes, I had a living sense in my heart,
that something of the breath of life had breathed upon them,
and though they were in great mixture, yet that God`'s love was towards them.

After some silence, I began on this wise:

"`I come not to judge you, but to visit you; not to quarrel or dispute,
but to speak of the things of God`'s kingdom; and I have no prejudice,
but great love and regard in my heart towards you:
therefore hear me with Christian patience and tenderness.

"`I do confess and believe that God has touched your hearts with His divine finger,
and that his work is among you:
that it was his Spirit that gave you a sight of the vanity and folly of this world,
and which has made you sensible of the dead religions that are in it.
It is this sense I love and honour;
and I am so far from undervaluing or opposing this tender sense I feel upon you,
that this it is I am come to visit, and you for the love of it.
And as for the reproaches that may attend you on the score of your separation,
with all the reports which therefore go concerning you, they are what I respect you for,
being well acquainted with the nature and practice
of this world towards those that retire out of it.

"`Now since I have with patience, and I can truly say, with great satisfaction,
heard your account of your experiences,
give me the like Christian freedom to tell you mine,
to the end you may have some sense of the work of God in me:
for those who are come to any measure of divine sense,
they are as looking glasses to each other, as face answers face in a glass.`"

Here I began to let them know how, and when, the Lord first appeared unto me,
which was about the twelfth year of my age, anno 1656.
How at times, between that and my fifteenth, the Lord visited me,
and the divine impressions He gave me of himself: of my persecution at Oxford,
and how the Lord sustained me in the midst of that gross darkness and debauchery:
of my being banished the college;
the bitter usage I underwent when I returned to my father; whipping, beating,
and turning out of doors in 1662.
Of the Lord`'s dealings with me in France, and in the time of the great plague in London.
In fine, the deep sense He gave me of the vanity of this world;
of the _irreligiousness_ of the religions of it.
Then of my mournful and bitter cries to Him,
that he would show me his own way of life and salvation,
and my resolutions to follow him, whatever reproaches or sufferings should attend me,
and that with great reverence and brokenness of spirit.
How, after all this, the glory of the world overtook me,
and I was even ready to give up myself unto it,
seeing as yet no such thing as the primitive spirit and church on the earth;
and being ready to faint concerning my hope of the restitution of all things.

It was at this time that the Lord visited me with
a certain sound and testimony of his eternal Word,
through one of those the world calls Quakers, namely, Thomas Loe.
I related to them the bitter mockings and scornings that fell upon me,
the displeasure of my parents, the invectives and cruelty of the priests,
the strangeness of all my companions: what a sign and wonder they made of me;
but above all,
that great cross of resisting and watching against
my own inward vain affections and thoughts.

Here I had a fine opportunity to speak of the mystery
of iniquity and ungodliness in the root and ground,
and to give them an account of the power and presence of God,
which attended us in our public testimonies and sufferings;
after an indirect manner censuring _their_ weaknesses,^
footnote:[The work of the Lord among man; serious persons in that day and country,
appears from William Penn`'s account to have been obstructed by a fear of man,
a shame of the cross, and a shrinking from persecution;
which inclined them rather to a retired way of life,
than to an open profession of their religious opinions.]
by declaring and commending the contrary practices among Friends,
too large to be here related.
And notwithstanding all my sufferings and trials by magistrates, parents, companions,
and above all from the priests of the false religions in the world,
the Lord has preserved me to this day, and has given me a hundred fold in this world,
as well as the assurance of life everlasting:
informing them of the tenderness of my father to me, before and at his death; and how,
through patience and long-suffering, all opposition was conquered.

Then I began my exhortation unto them, which was as follows.
That since God had given me and them a divine sense of Himself, our eye should be to Him,
not to man; that we might come more into a silence of ourselves,
and a growth into that heavenly sense.
That this was the work of the true ministry, not to keep people to _themselves,_
ever teaching them, but to turn them to God, the new covenant Teacher, and to Christ,
the great gospel Minister.
Thus John did, and thought it no dishonour that they left _him,_ to go to _Christ._
"`Behold the Lamb of God,`" said he, "`that takes away the sin of the world!`"
And even John`'s disciples left him to follow Christ.
Indeed, John testifies of himself,
that he was to _"`decrease`"_ and Christ was to _"`increase.`"_
Therefore I pressed them to have their eye to Christ that takes away the sin,
who is from heaven, heavenly; to see that He increase in them.
Yes, that henceforth they should "`know no man after the flesh;`" no,
not even Christ himself.^
footnote:[2 Cor. 5:16.]
That their knowledge of, and regard to, and fellowship with, one another,
should stand in the revelation of the Son of God in them;^
footnote:[Gal. 1:16.]
who is God`'s great Prophet, by whom God speaks in these latter days.
And if their ministers were true ministers,
they would count it their glory to give way to Christ, and that they decrease,
and Christ increase; that the instrument give way to Him that uses it,
the servant to the Lord.
This, though it might seem to detract from the ministers,
yet it is the glory of a true minister, that God and Christ should be _all in all,_
and that his will should be fulfilled.
For, I told them, the day of the Lord God was come,
and all people must look to Him for salvation;
that all people must now come to keep God`'s great sabbath, to rest from _mere man,_
and the spirit of man, and from all men`'s thoughts, words and works;
and that if they were true believers, they were at least _entering_ into their rest.^
footnote:[Heb. 4:1. 3.]

I closely recommended to them, that they might not be of those that begin in the Spirit,
and end in the flesh;^
footnote:[Gal. 3:3.]
"`Therefore,`" said I, "`let Christ have his honour; let Him preach and speak among you,
and in you, and you in him; and by him only sigh, groan, pray, preach, sing,
and not otherwise, lest death come over you: for thereby the apostasy came in,
by _their_ going before Christ, instead of Christ going before _them._`"

I further directed them to wait in the Light and
Spirit of judgment which had visited them,
that all might be wrought out that was not born of God;
so would they come to be born of the incorruptible seed, "`by the Word of God,
which lives and abides forever,`"^
footnote:[1 Peter 1:23.]
that they might be a holy priesthood,
that offers up a living sacrifice with God`'s heavenly fire,
that He might have his honour in them all, and through all, by Jesus Christ.^
footnote:[1 Peter 2:5.]
And turning myself towards the Somerdykes, with a serious and tender spirit,
I thus expressed myself: "`That _you_ should be pilgrims in the inheritance of your Father,
I have a deep and reverent sense of: O that you might dwell with Him forever,
and exalt him that has so visited you,
with whom are the rewards of eternal blessedness.`"

So I left the blessing and peace of Jesus among them,
departing in the love and peace of God: and I must needs say,
they were beyond expectation tender and respectful to us;
all of them coming with us to the outer door, except the ancient Anna Maria Schurmans,
who is not able to walk; giving us their hands in a friendly manner,
and expressing their great satisfaction in our visit.
And being come to the porch, and meeting several persons of the family,
I was moved to turn about and exhort them, in the presence of the rest,
to keep to Christ, that had given them a sense of the spirit of this world,
and had raised desires in them to be delivered from
it:--and to know no man after the flesh,
but to have their fellowship in Christ, union and communion with God,
and one with another; that all their worship and performances might stand in _Him,_
that _He_ might be _all in all:_
desiring that the Lord might keep them in his fear all the days of their appointed time,
that so they might serve Him in their generation, in his own universal Spirit,
to his glory, who is blessed forever!

The Lord comforted my soul in this service:
yes all that is within me magnified his holy name,
because of his blessed presence that was with us!
O let my soul trust in the Lord, and confide in him forever!
O let me dwell and abide with him that is faithful and true, and blessed forevermore!

The two pastors and the doctor came with us a field`'s length, where we took waggon;
and the chief of them took occasion to ask me, if the Truth rose not first among
a _poor, illiterate,_ and _simple_
sort
of people?
I told him, yes, _that_ was our comfort,
and that we owed it not to the learning of this world: "`Then,`" said he,
"`let not the learning of this world be used to defend
that which the Spirit of God has brought forth;
for scholars now coming among you,
will be apt to mix school-learning among your simpler and purer language,
and thereby obscure the brightness of the testimony.`"
I told him, it was good for us all to have a care of our own spirits, words and works,
confessing what he said had weight in it, telling him,
it was our care to write and speak according to the divine sense,
and not human invention.
So, in a very sober and serious manner, we parted.

--

[.asterism]
'''

[.offset]
The [.book-title]#Select Anecdotes# shall be closed with a short extract from a controversial pamphlet,
written by Samuel Fothergill, and bearing the date of 1763.

[.embedded-content-document]
--

A number of people in the seventeenth century,
made sensible of the inutility of empty profession,
and having long sought the living among the dead,
were excited to look for the substance of religion as an inward spiritual work;
they had spent their money for that which was not bread,
and their labour for that which satisfied not.^
footnote:[Isa. 4:2.]
They found themselves impoverished amidst the imaginary treasure of exterior profession,
and famished among the multiplicity of forms.
Their situation was like that of the poor woman,
mentioned in Mark 5:26. who "`had suffered many things of many physicians,
and had spent all that she had, and was nothing bettered, but rather grew worse.`"

In this exercised condition, labouring and heavy laden,
they remained without any prospect of relief from exterior rites and observations,
having proved their inefficacy by long trial; they therefore turned towards God,
and earnestly sought Him whom the Father had appointed to give rest to the weary soul.
The anxious concern of their minds was evident, and sometimes might occasion,
upon some of them, the literal accomplishment of that most necessary injunction,
"`Work out your own salvation with fear and _trembling._`"^
footnote:[Phil. 2:12.]
Hence the name of Quakers was given to them, at first in scorn,
and by many continued from the same motive.
The apprehension of imminent danger to the _body,_ has often produced this effect,
without reproach to the parties affected;
and why should it be thought to merit any epithet of contempt,
to tremble at the sense of danger to that _immortal part,_
which must inevitably abide the decisive sentence
of "`Come you blessed,`" or "`Go you cursed?`"
I freely and thus publicly acknowledge,
that notwithstanding the contempt poured upon the name of a Quaker,
I would rather sustain it with propriety,
than any of the most dignified titles among the sons of men.

But to proceed: a degree of divine light arose upon their minds,
to show them wherein the essential help consisted,
which was accompanied by faith in the name of Jesus Christ,
by whom salvation and strength are only attainable.
Through a fight of afflictions they followed Him; cruel mockings, severe imprisonments,
banishments, sequestration of their goods,
and almost every species of oppression and cruelty were exercised upon them,
and even death.
Yet as a collective body, no occasion was ever found against them,
except concerning the law of their God.^
footnote:[Dan. 6:5.
{footnote-paragraph-split}
See the two volumes of [.book-title]#Friends`' Sufferings,#
by Besse; [.book-title]#G. Fox`'s Journal,# Sewel`'s and Gough`'s [.book-title]#Histories,# etc. etc.]
This fervent cry of soul after substance, was graciously regarded by a God hearing prayer.
He led them in the way to peace, and spoke comfortably to them,
raised in many thousands the same religious hunger,
and by the baptism of the holy Spirit united them together, as men of one heart.
_To this we owe our being as a people separate from others._

--

[.the-end]
The End
