[quote.epigraph, , "Hooker`'s Ecclesiastical Polity, Preface, sect. ix"]
____
If Truth do anywhere manifest itself, seek not to smother it with glossing delusion;
Acknowledge the greatness thereof, and think it your best victory,
when the same prevails over you.
____

== Preface to the First Edition.

The following Work consists of two distinct parts.
The first part is a religious Diary, nearly two hundred years old,
now for the first time committed to the press;
the Writer of which filled some responsible public
stations about the period of the Commonwealth,
but, shortly after the close of his narrative, and while in the meridian of life,
was among the earliest in his native city of Aberdeen,
to join himself in communion with the people called Quakers,
The second division of this Work,
carries forward what is known of the subsequent career of Alexander Jaffray,
in conjunction with historical MEMOIRS of his contemporaries and
companions in the profession of the same Christian principles.

With regard to the Diary, it came into my hands in the following manner.
Travelling in Scotland in the autumn of 1826, I visited Ury, near Stonehaven,
the place of my ancestors,
and well known to the Society of Friends as the residence of Robert Barclay their "`Apologist.`"
My mingled feelings of interest,
in passing a night or two under the roof of the hospitable proprietor, my cousin,
I need not enlarge on; yet must not forbear expressing the emotions of desire and hope,
which attended me from the first, that the inquiry and search I was about to make,
for documents relative to that family as Friends,
might be turned to a beneficial account,
by throwing light upon the history of that remarkable religious experience,
for which some of them in former times were distinguished,
and are to this day deservedly held in reputation.
Among other MSS.
to all appearance much neglected,
and which might have been ere long utterly lost sight of,
lay the earlier portion of the present Diary, in a corner of the Apologist`'s study;
and in another place, [.book-title]#A Brief Historical Account of the Rise, Progress,
and Persecutions of the People called Quakers, in the North of Scotland.#
Of the latter MS. I shall presently have occasion to speak; but of the former,
the paper was highly discoloured, and the writing in some places much injured by time;
the character of it was at first not easily deciphered,
so that many parts were for a time almost wholly unintelligible;
and the name of the writer no where appearing, furnished a further source of difficulty.
This first pocket Journal or Diary extends only to the 120th page of the present volume:
detached fragments of another MS. were, however discovered, leaf after leaf,
in a very tattered condition, in a loft of a farm-house not far from the old mansion;
these were quickly recognised, among heaps of waste paper,
as being in the same handwriting, and proved to be a counterpart of the other.
The intrinsic value of the document, as a whole, being at length ascertained,
no obstacle that presented was sufficient to deter
from a close investigation of the subject;
nor could any after-discouragements prevail to turn aside the conclusion,
which now results in producing such treasure,
for the participation of my friends and the public.

I am unable to state, how this MS. came into the possession of the Barclays of Ury; but,
from the great intimacy which subsisted for several
generations between that family and the Jaffrays,
it is highly probable,
that it was consigned by some branch of the latter to the care of the former,
with a view to its publication.
The most prominent design of the Writer,
in taking down these observations on the Lord`'s goodness towards him,
is set forth at the commencement of the Diary; being expressively opened,
by the introduction of two Scriptural passages, which he there adopts as his motto,
and to which, as a watchword, he often recurs +++_______+++, namely,
that he might stir up himself, and engage his heart to the Lord forever.
Yet besides this primary design of self-improvement, it becomes manifest as we proceed,
that he includes a further object, and that he is not without hope, his successors,
especially his children,
may derive instruction from a recital of the passages and exercises of his life.
Many interesting circumstances of his public career are, however, but slightly traced,
while others are wholly passed over; on which account, it was thought desirable,
to endeavour to supply by Notes such additional information,
as could at this distance of time be gathered from other sources.
An opportunity was likewise thus afforded,
of illustrating in various ways the facts and sentiments adduced.
An APPENDIX OF NOTES AND ILLUSTRATIONS will therefore
be found immediately at the close of the Diary;
which, it is hoped, will in all cases be regularly turned to,
at the place where the reference to it is given.

The disadvantages under which this plan was carried into effect,
and the difficulties which were encountered,
cannot in any adequate manner be understood by the general reader.
It will, however, be only proper to mention, that, in pursuing these investigations,
I was led to travel much further than could have been anticipated,
and over a great deal of ground,
from which little could be gleaned that was convertible to my purpose;
and that no personal labour nor expense has been spared
which seemed likely to contribute to it-- however imperfectly,
after all, my own wishes in regard to this part of the Work are fulfilled.
I must here acknowledge the very kind assistance I have derived from some of my friends,
and also from some literary characters, both at Edinburgh and Aberdeen;
towards the latter, as I have no personal acquaintance with them,
I cannot but consider myself the more indebted for their prompt attentions.
In drawing up these illustrations,
I always preferred making use of original matter and original sources of authority,
where it could be done, rather than inserting statements in my own terms,
though grounded upon intermediate or even original testimony.
Fully sensible how much they need indulgence, I shall be well satisfied,
if those to whose hands the Work may come, are led,
by a careful examination persons have of the Notes,
more fully to appreciate the nature of those circumstances to which the Diary alludes;
but above all, the spirit of those reflections,
which with so much lively weight and ingenuous simplicity he unfolds.

With regard to the character of the times in which Alexander Jaffray lived,
especially the times of the Commonwealth, there has been a great disparity of opinion,
according to the favourable or unfavourable medium,
through which been disposed to view this question.
I would, however, venture to submit the following passage from a modern publication,
as embracing some just and judicious considerations.

[.embedded-content-document]
--

Of the true state of religion during the period of Cromwell`'s government,
it is difficult to form an accurate estimate.
Judging from certain external appearances,
and comparing them with the times which followed, the opinion must be highly favourable.
Religion was the language, and the garb of the court;
prayer and fasting were fashionable exercises; a profession was the road to preferment;
not a play was acted in all England for many years,
and from the prince to the peasant and common soldier,
the features of Puritanism were universally exhibited.
Judging, again, from the wildness and extravagance of various opinions and practices,
which then obtained, and from the fanatical slang, and hypocritical grimace,
which were adopted by many merely to answer a purpose,
our opinion will necessarily be unfavourable.
The truth, perhaps, lies between the extremes of unqualified censure,
and undistinguishing approbation.
Making all due allowance for the infirmity and sin,
which were combined with the profession of religion--making
every abatement for the inducements,
which then encouraged the use of a religious vocabulary--admitting
that there was even a large portion of pure fanaticism,
still, we apprehend, an immense mass of genuine religion will remain.
There must have been a large quantity of sterling coin,
when there was such a circulation of counterfeit.
In the best of the men of that period, there was, doubtless,
a tincture of unscriptural enthusiasm,
and the use of a phraseology revolting to the test of modern time; in many, perhaps,
there was nothing more: but to infer, that therefore all was base, unnatural deceit,
would be unjust and unwise.
A reformation,`' says Jortin, +++[+++in his Remarks on Ecclesiastical History,]
'`is seldom carried on, without heat and vehemence, which borders upon enthusiasm.
As Cicero has observed, that there never was a great man sine aflatu divino; so,
in times of religious contests, there seldom was a man very zealous for liberty,
civil and ecclesiastical, and a declared active enemy to insolent tyranny,
blind superstition, political godliness, bigotry, and pious frauds,
who had not a fervency of zeal,
which led him on some occasions beyond the bounds of sober,
temperate reason.--Orme`'s [.book-title]#Memoirs of the Life of Owen.#

--

But it will be needful to pursue the subject of enthusiasm somewhat further;
inasmuch as it may have, in the minds of some,
a particular reference not only to Jaffray, as he is in the Diary,
leaning to the Independents, but to Jaffray,
as he is among his colleagues in the Memoirs,
a zealous "`Quaker`"--It is most unreasonable,`"
observes a descendant of the family of Cromwell,
in rebutting the animadversions of Hume against the Independents of that day,
"`to deny to religious characters, their fervours in the pursuit of their great object,
and to indulge the worldly in all their ardours and extravagances,
in the comparatively trifling objects of their pursuits.
By the men of the world, the arduous, persevering Christian of the Parliament party, was,
in those times, deemed an enthusiast and an hypocrite,
and his best actions represented as influenced by
the most sinister and mischievous motives;
all was resolved into hypocrisy or enthusiasm.`"
"`Lord Clarendon speaks contemptuously of the expression seeking God,`' which, he says,
was a new phrase brought from Scotland with their Covenant.
It might have been a new phrase in England;
but it is perfectly expressive of the thing meant, namely,
a devout and humble application by prayer to the Almighty, by a nation or individuals,
to avert impending public or private calamities; or to remove them if incurred;
or for direction and assistance in concerns of importance,
too great for human accomplishment.
In religious language,
perhaps it may be generally best to avoid what may be called technical phraseology:
particular words frequently used,
expressive (for brevity sake) of any particular religious act or observance,
are liable to be caught at by the world,
and used for the purposes of turning into ridicule everything serious.
In the succeeding licentious reign of King Charles the 2nd,
all semblance of religion was studiously put out of sight;
it was become quite unfashionable; and the ridicule of its professors,
and of all the religious language and acts of the preceding times,
was considered a kind of test of loyalty to the then sovereign and government.
This phrase of '`seeking God,`' then used as expressive of the act of prayer,
public or private,
became after the Restoration with other religious phrases or expressions,
subjects of ridicule.
Lightly or contemptuously, however, as the men of the world,
when in health and prosperity,
may treat this application to and reliance upon Divine Providence,
the religious part of the Christian world are in
the constant and habitual practice of it,
and thence, there can be no doubt, derive the greatest comfort and assurance.
Independently of prayer being a commanded duty, it is surely a reasonable service,
inasmuch as it is an acknowledgement of our dependence upon the Supreme Being, to whom,
feeble and insufficient as we are,
we must be constantly looking for the support of our existence,
and for the continuance of all our comforts and enjoyments.`"
After some other remarks, delivered in a strain very becoming this subject;
but not so directly bearing upon our purpose,
this author proceeds--"`Our holy religion teaches us to expect
this assistance through and by the means of the Holy Spirit;
for which assistance, and for whose influence, we all ask in the most expressive terms,
in our attendance upon the public worship of our Established Church,
and in the prayers of our Liturgy.
Strange, then, to tell how all these acts of devotion,
and all the religious professors of the above times, were afterwards,
in the succeeding reign of King Charles the 2nd, held up to ridicule and contempt,
as the vilest of canting, enthusiastical hypocrites and knaves,
and as masking their political, ambitious designs,
under the show and pretence of religion.
And in this light, it is to be lamented,
that the more than common strict religious professor in succeeding times,
hath been too often viewed by the less religious part of the community;
nothing appearing to afford them more pleasure,
than the real or imagined detection of any of those professors in any sin or folly.
In this unfavourable light do Lord Clarendon,
and all other writers for the royal cause represent the Parliament and its adherents;
allowing them no good motive for any of their proceedings,
but attributing them wholly to concealed ambition, and sinister views;
and thus stigmatized,
they have been handed down to the present day.`"--[.book-title]#Memoirs of Oliver Cromwell,#
by Oliver Cromwell; vol.
ii. p. 400-405.

On the subject of the religious qualities of this fragment of auto-biography,
it will be readily perceived there prevails throughout the Diary,
every symptom of a salutary and genuine exercise of mind, uniformly directed,
in the first place, for the well-being of the Writer`'s own soul,
next for that of his family,
then on account of "`the godly,`" but in its full
scope reaching towards all of every class.
Those great duties and attainments so mainly pressed upon
us by our Divine Saviour while personally on earth,
and which it was one main end of His appearing to enforce,
are here everywhere upheld and sought after; such as self-denial, humility, charity,
and watchfulness unto prayer.
One feature, not common in productions of this kind,
but which forms in the present instance a chief attraction,
is the gradual and continued enlargement in spiritual growth.
We here trace, in the unaffected outline of Jaffray`'s views and feelings,
the intimate workings and movements of a mind,
superior to those temporizing compliances with systems and parties,
which has ever proved a vast impediment to the pious and the dedicated,
in their heavenly race.
We see, in his narrative,
to what conclusions the pure dictates of the Holy Spirit brought him,
to what they tended, and how they operated on an honest,
and humble soul--even to break down the strongest bias; as it were, to remould the man,
reducing all things "`to the obedience of Christ.`"
I earnestly desire for my readers, whatever be their standing in the universal church,
that they may be enabled profitably to reflect upon this feature of his case,
that thus they may be favoured to arrive at just conclusions with regard to it.
This individual was truly led,
as "`the blind by a way`" that he had not hitherto
"`known,`" into paths--the good old paths,
indeed--but which were then newly cast up,`" and "`everywhere spoken against.`"

While dwelling upon the important changes,
which the mind of Jaffray successively underwent, until,
from the Presbyterian and Independent persuasions,
he became at length wholly assimilated with the Society of Friends;
I cannot but introduce the valuable and very apposite remarks of the biographer of Owen.
"`Every change of religious sentiment is important to the person who makes it,
and ought to be gone into with caution and deliberation.
To be given to change is a great evil, and indicates a weak and unsettled mind.
On the other hand,
to be afraid of change is frequently the result of
indifference or sinful apprehension of consequences.
It is the duty of every Christian,
to follow the teaching of the Spirit in the word of revelation, and to recollect,
that for his convictions he must be accountable at last.
The attempt to smother them is always improper;
and when successful must injure the religious feelings of their subject.
To allow hopes or fears of a worldly nature to conquer our persuasion of what the +++[+++Scripture]
requires, is to forget the important intimation of our Lord--that
if any thing is loved more than Him,
it is impossible to be his disciple.
By such conduct the tribulations of the kingdom may often be avoided,
but the consolations and rewards of it will also be lost.
"`If any man serve me let him follow me; and where I am, there shall also my servant be;
if, any man serve me, him will my father honour, John 12:26.`"
--Orme`'s [.book-title]#Memoirs of the Life of Owen,# p. 60.

Some slight observations are yet to be subjoined,
before we pass on to the subject of the second division
of this volume--It cannot be said,
that the whole of what came to my hands, of the Diary of Alexander Jaffray,
is now presented to the public.
Some passages are omitted,
as being almost repetitions of what elsewhere is better expressed;
others did not seem of sufficient moment to be retained.
Very small and unimportant transpositions or substitutions of words,
are likewise here and there made use of,
merely so far as to render the sense more plain and intelligible; it is possible,
however, from the state of the MS+++.+++, that I myself may have failed, though but rarely,
in rendering his actual meaning.
The Scripture texts are quoted as they were found; they are, I believe,
strictly correct in substance, though not always after the words of our present version.
Proper names of persons and places in Scotland are so variously spelt,
even in some modern publications,
that it was sometimes difficult to decide upon the most correct mode;
the ancient spelling is, however, preserved in the Diary,
and explained where needful in brackets; and, in the Appendix,
the quotations from Scottish authorities are given with
a close adherence even to the spelling of the dialect.

My design of a second part to the present publication,
had its origin in the following circumstances--The Diary breaks off abruptly,
and only a short time before Alexander Jaffray,
together with a number of his intimate associates,
settled in the profession of the Friends.
It was to be regretted,
that the narrator had not carried forward his account
as far as this interesting period in his experience,
or rather perhaps that such account had not been spared to us.
On examining, however, more closely into the MS. Chronicle,
which has been before mentioned as being discovered at Ury,
and which treats of the Rise and Progress of the
people called Quakers in the north of Scotland,
this loss appeared to be in some measure compensated,
by a regular and connected detail of their history,
expressly collected for the use of posterity.
For although, in the course of it,
no large portion has allusion to our worthy Diarist himself; yet I found, that,
not only in these parts but in every other, is held up to view,
a glowing exemplification of many of those very themes of meditation and of sentiment,
upon which he had so largely dwelt.
And besides this,
on looking into the Records kept by the Monthly Meeting of Friends at Aberdeen,
a remarkable fact appeared, namely, that the Author of the Diary himself,
only a year before his own decease,
was the first to set his hand to the work of preparing this ancient document; and that,
after that event, his son Andrew in particular,
together with "`the Apologist`" and others, became a chief contributor.

These things thus coming to my knowledge and to my charge,
perhaps it was not very unnatural for me to conclude,
such memorials of the just were not designed to be buried in oblivion;
but were equally calculated for the service of the present,
as for generations that had gone before.
Neither could I, in reference to them,
divest myself of the feeling of a trust consigned to me,
(however unworthy,) for this end--namely, to bear them forth, as a testimony,
to the church and to the world.
The religious Society of Friends has ever had a high sense of the obligation there is,
to treasure up and to proclaim such evidences of the faithfulness
of the Most High in his dealings with his children;
and they have ever considered themselves as subjects and witnesses
of his redeeming mercy and all-sufficient grace in Jesus Christ.
In conformation of this position,
may be brought forward the language of William Penn at the
beginning of his Preface to Robert Barclay`'s Works.
"`Our blessed Lord having effectually gathered and
fed his people by his disciples in this generation,
it is a duty we owe to God and ourselves, as well as to them,
that we gather up the remainder of the testimonies of love and service,
that so nothing be lost.`"

The foregoing being the acknowledged ground-work of the ensuing Memoirs, it may be added,
that various original and other sources have been consulted in the present compilation.
Besse, in forming his "`Collection of the Sufferings of Friends,`" 1753,
evidently had access to a copy of the above Record; and Gough, in his History, 1790,
takes his chief authority from Besse;
but both these accounts of the affairs of the Society
in Scotland are defective and incorrect.
In the arrangement of the materials for the present division of this volume,
very little liberty of composition has been indulged in;
so that the reader is here furnished with a faithful,
and in many places almost a literal transcript of events,
oftentimes expressed in nearly the words of the eye-witnesses.
So far, then, as applies to the correctness of the details themselves,
and even the mode of stating them, I consider myself divested of responsibility;
at the same time, the Society of Friends, as a body,
are not committed by the reflections interspersed among those details.
Some of the accounts, of rather an extraordinary nature,
are here represented in the light of direct Providential interpositions:
and it may possibly be thought, that matters of this kind,
as well as the comments upon them, had better have been wholly excluded,
or at least not turned to so high an account.
But, let it be observed, how much more chargeable an author would have been,
himself a member of this religious community,
had he been disposed to expunge from their History,
a feature so well known and so fully sanctioned, not only in all their recorded annals,
but in most of their standard publications.

There may also be those, who, in perusing these recollections of earlier days,
would incline to think, that the unchristian conduct and principles,
which appear at one time to have governed any individuals or set of men,
had better not be thus revived,
lest it should seem too much like aggravating occasions
of repulsion among the followers of the same Lord.
This objection, however, must apply with equal weight, to all other subjects of history,
and would have its parallel in every age of the church.
But, it should be distinctly understood,
that the controversy of the people called Quakers never was against any set of men,
as such; on the contrary,
they always loved and esteemed that which is excellent and of good report in all;
and if such classes or persons, on whom any degree of opprobrium has rested,
testify against the conduct of those that have given cause for it,
their system of religious policy is not by any means chargeable with faults,
that have been disowned by them,
and condemned although this very course has been pursued towards the Friends,
by some whose character ranks well in the estimation of the public.--See Joseph Gurney
Bevan`'s Refutation of some of the more modern Misrepresentations of the Friends.
Such instances, however, of individuals, who have in any wise failed of the grace of God,
must not be expected, nor are they often allowed, altogether to go into oblivion;
they more ordinarily remain,--as the stranded vessel or as the warning
beacon--a sea-mark to deter the ignorant or too daring mariner;
nor (to drop the metaphor) would any of these,
when brought into a penitent and reformed state, even desire to have it otherwise,
if they are of the Apostle Paul`'s way of thinking
on this subject.--1 Tim. 1:12 to 16.

It is, moreover, due to the memory of those, who,
in the spirit of their meek and self-denying Saviour,
endured such contradiction of sinners against`" themselves,
that the temper and tendency of that age should be manifested;--otherwise,
very superficial and incorrect notions might be readily taken up respecting them;
and the peculiar line of behaviour,
so uniformly observed by these true friends of the true spiritual liberty,
might be greatly misunderstood.
This remark leads to the notice of one trait, in particular, which has ever been,
and I believe must ever be attributable to the real "`Quaker,`" and which
is strikingly apparent throughout the greater part of these Memoirs:
namely, an unconceding and close adherence to that course of conduct,
which their sense of duty has at any time indicated.
Clarkson, in his "`Portraiture`" of us,
has adverted to it in these words.--"`It was observed, in the time of George Fox,
of the members of this Society, that they were as stiff as trees;
and this idea concerning them has come down to the present day.
The origin of this defective feature must be obvious to all.
The Quakers, as we have seen, will neither pay tithes, nor perform military service,
nor illuminate their houses, like other people,
though they are sure of suffering by their refusing to comply with custom in these cases.
Now, when individuals, few in number, become singular,
and differ from the world at large, it is generally considered,
that the majority are in the right, and that the minority are in the wrong.
But, obstinacy may be defined to be,
a perseverance in that which is generally considered to be wrong.
This epithet has attached, and will attach to those, who resist the popular opinion,
till men are better educated, or till they lose their prejudices,
or have more correct and liberal notions on religion.
The early Christians were themselves accused of obstinacy,
and this even by the enlightened Pliny.
He tells us,
that they would not use wine and frankincense before the statues of the emperors;
and that there was no question, that for such obstinacy they deserved punishment.
In judging of this trait, two questions will arise: First,
Whether the members of this Society,
in adhering rigidly to those singularities which have produced it,
are really wrong as a body of Christians?
And Secondly, whether they do not conscientiously believe themselves to be right?
In the case of the early Christians, which has been mentioned, we who live at this day,
have no doubt, that Pliny put a false estimation on their character.
We believe them to have done their duty,
and we believe also that they considered themselves as doing it,
when they refused divine honours to the emperors.
The action, therefore, which Pliny denominated obstinacy, would,
if it had been left to us to name it, have been called inflexible virtue,
as arising out of a sense of the obligation imposed upon them by the Christian religion.
In the same manner we may argue with respect to the Quakers.`"--Vol.
iii. p. 248. But this candid writer, in an earlier page,
has himself given the best explanation of their motives:--and may such motives,
and such line of conduct ever continue to prevail individually in their hearts,
and collectively in their assemblies! "`It has been,`" says he,
"`an established rule with them, from the formation of the Society, not to temporise,
or to violate their consciences; or, in other words, not to do that which,
as a body of Christians, they believe to be wrong, though the usages of the world,
or the government of the country under which they live, should require it;
but rather to submit to the frowns and indignation of the one,
and the legal penalties annexed to their disobedience by the other.
This suffering, in preference to the violation of their consciences,
is what they call '`the bearing of their testimony,`' or a demonstration
to the world by the testimony of their own example,
they consider it to be the duty of Christians rather to suffer,
than have any concern with that which they conceive to be evil.
The Quakers, in putting this principle into practice, stand, I believe, alone;
for I know of no other Christians, (unless it be the Moravians,) who, as a body,
pay this homage to their scruples, or who determine upon an ordeal of suffering,
in preference to a compromise with their ease and safety.`"
"`This noble practice of bearing testimony,
by which a few individuals attempt to stem the torrent
of immorality by opposing themselves to its stream,
and which may be considered as a living martyrdom, does, in a moral point of view,
a great deal of good to those who conscientiously adopt it.
It recalls first principles to their minds.
It keeps in their remembrance the religious rights of man.
It teaches them to reason upon principle, and to make their estimates by a moral standard.
It is productive both of patience and of courage.
It occasions them to be kind, and attentive,
and merciful to those who are persecuted and oppressed.
It throws them into the presence of the Divinity, when they are persecuted themselves.
In short, it warms their moral feelings, and elevates their religious thoughts.
Like oil it keeps them from rusting.
Like a whetstone, it gives them a new edge.
Take away this practice from the constitution of the members of this Society,
and you pull down a considerable support of their moral character.`"--"`It
is a great pity,`" continues this worthy and enlightened philanthropist,
"`that, as professing Christians,
we should not more of us incorporate this noble principle individually into our religion.
We concur unquestionably in customs, through the fear of being reputed singular,
of which our hearts do not always approve; though nothing is more true,
than that a Christian is expected to be singular,
with respect to the corruptions of the world.
What an immensity of good would be done, if cases of persons,
choosing rather to suffer than to temporize,
were so numerous as to attract the general notice of men!
Would not every case of suffering operate as one of the most forcible
lessons that could be given to those who should see it?
And how long would that infamous system have to live,
which makes a distinction between political expediency and moral right?`"

This brings me to the subject of persecution and suffering for conscience sake,
of which the early history of the Friends in general, and these Memoirs in particular,
present so full a series of illustrations.
And on this point, I cannot but consider it of much importance,
that the sentiments conveyed by Robert Barclay should be here revived, and,
though at some length, brought under the notice of my readers.
He observes,
that the occasion which obtained reputation for Christians of old under persecution, was,
their willingness to suffer, being innocent,
while by principle they precluded themselves from injuring any; whereas, says he,
"`there is little reason to pity one, who is but dealt by,
according as he would deal with others.`"
Such a doctrine at this last instance involves, would make,
(as Barclay proceeds to show,) "`all suffering for religion,
which of old was the glory of Christians, to be but of pure necessity; whereby,
they are not led as lambs to the slaughter, as was the Captain of their salvation,
but rather as wolves caught in the snare, who only bite not again,
because they are not able, but, could they get force,
would be as ready to lead those the same way, that lead them.
Where is the faith and patience of the saints?
For, indeed, it is but a small glory to make a virtue of necessity,
and suffer because I cannot help it.
Every thief and murderer is a martyr, at that rate;
experience hath abundantly proved this in these last centuries.`"

Having thus cleared his way,
this author proceeds to show that the true ground of persecution is,
an unwillingness to suffer; "`for,`" says he,
"`no man that would persecute another for his conscience, would suffer for his own,
if he could avoid it; seeing, his principle obliges him, if he had power,
by force to establish that which he judges is the Truth, and so to force others to it.`"
With these preliminary remarks, may be introduced the succeeding important sentiments;
and,
though written before the time when Friends in Scotland
had to endure a large portion of their ill-treatment,
they are, nevertheless, equally and very specially applicable to the troubles,
which so quickly after came upon them.
Therefore, I judge it meet,
briefly to add something in this place concerning the nature of true Christian sufferings;
whereunto a very faithful testimony has been borne by God`'s witnesses,
whom he hath raised up in this age--beyond what has been
generally known or practised for these many generations,
yea, since the apostacy took place.
Yet, it is not my design here,
in any wise to derogate from the sufferings of the Protestant martyrs;
whom I believed to have walked towards God,
according to the dispensation of light in that day appearing; and of whom,
many were utter enemies to persecution,
as by their testimonies against it might be made appear.

"`But the true, faithful, and Christian suffering, is,
for men to profess what they are persuaded is right,
and so practise and perform their worship towards God,
as being their true right so to do; and neither to do more in that,
because of outward encouragement from men, nor any whit less,
because of the fear of their laws and acts against it.
Thus, for a Christian man to vindicate his just liberty,
with so much boldness and yet innocency, will in due time, though through blood,
purchase peace; as this age has in some measure experienced,
and many are witnesses of it--which yet shall be more apparent to the world,
as Truth takes place in the earth.
But they greatly sin against this excellent rule, that, in time of persecution,
do not profess their own way so much as they would, if it were otherwise; and yet,
when they can get the magistrate upon their side,
not only stretch their own liberty to the utmost,
but seek to establish the same by denying it to others.

"`But of this excellent patience and sufferings,
the witnesses of God in scorn called Quakers, have given a manifest proof.
For, so soon as God revealed his Truth among them, without regard to all opposition,
or what they might meet with, they went up and down as they were moved of the Lord,
preaching and propagating the truth in market-places, highways, streets,
and public temples, though daily beaten, whipped, bruised, haled,
and imprisoned therefore.
And when there was any where a church or assembly gathered,
they taught them to keep their meetings openly, and not to shut the door,
nor do it by stealth; that all might know it, and who would might enter.
And as, hereby,
all just occasion of fear of plotting against the government was fully removed,
so this their courage and faithfulness,
in not giving over their meeting together--(but more especially
the presence and glory of God manifested in the meeting,
being terrible to the consciences of the persecutors)--did
so weary out the malice of their adversaries,
that oftentimes they were forced to leave their work undone.
For when they came to break up a meeting, they were +++[+++obliged]
to take every individual out by force, they not being free to give up their liberty,
by dissolving at their command; and when they were haled out,
unless they were kept forth by violence,
they presently returned peaceably to their place.
Yea, when sometimes the magistrates have pulled down their meetinghouses,
they have met the next day openly upon the rubbish; and so,
by innocency kept their possession and ground, being properly their own,
and their right to meet and worship God being not forfeited to any.
So that, when armed men have come to dissolve them, it was impossible for them to do it,
unless they had killed every one; for they stood so close together,
that no force could move any one to stir, until violently pulled down: so that,
when the malice of their opposers stirred them to take shovels,
and throw the rubbish upon them--there they stood, unmoved; being willing,
if the Lord should so permit, to have been there buried alive, witnessing for him.
As this patient, but yet courageous way of suffering,
made the persecutors`' work very heavy and wearisome unto them;
so the courage and patience of the sufferers, using no resistance,
nor bringing any weapons to defend themselves,
nor seeking any ways revenge upon such occasions,
did secretly smite the hearts of the persecutors,
and make their chariot wheels go on heavily.
Thus, after much and many kind of sufferings thus patiently borne,
which to rehearse would make a volume of itself;
(which may in due time be published to the nations,
for we have them upon record;) a kind of negative liberty has been obtained, so that,
at present, for the most part we meet together without disturbance from the magistrate.

"`But, on the contrary, most Protestants,
when they have not the allowance and tolerance of the magistrate, meet only in secret,
and hide their testimony; and if they be discovered,
if there be any probability of making their escape by force,
though it were by cutting off those that seek them out, they will do it; whereby,
they lose the glory of their sufferings,
by not appearing as the innocent followers of Christ,
nor having a testimony of their harmlessness in the hearts of their pursuers;--their
fury by such resistance is the more kindled against them.
As to the last part, of their resisting such as persecute them,
they can lay claim to no precept from Christ,
nor any example of him or his apostles approved.`"--Apology, Prop.
xiv. sect.
6+++.+++ A late writer on political rights and obligations, might well affirm,
that "`The Reformation prospered more by the resolute non-compliance of its supporters,
than if all of them had provided themselves with swords and pistols.`"
He adds, "`The most severely persecuted body of Christians,
which this country has in latter ages seen,
was a body who never raised the arm of resistance.
They wore out that iron rode of oppression,
which the attrition of violence might have wetted into a weapon,
that would have cut them off from the earth;--and
they now reap the fair fruit of their principles,
in the enjoyment of privileges from which others are still
debarred.`"--[.book-title]#Essays on the Principles of Morality,#
etc., by Jonathan Dymond.

It is, then, to a recital of such circumstances as these,
under which a small portion of this small class of Protestant dissenters,
had their origin and became established in the north of Scotland,
that my readers are now invited.
However generally despised this class once were,
however despicable they may still seem to many,
and must always continue to be in the estimation of the thoughtless, the worldly,
the profane--and even in the opinion of those,
who are self-seeking and self-satisfied professors of religion;--there is, I believe,
solid ground for the assumption, that the more they adhere to first principles,
the more uniformly and conspicuously they will prove as
salt that has not lost its savour--as a little leaven,
that is calculated to diffuse its wholesome influence wherever distributed.
Can any among the successors of such a people,
be willingly indifferent with regard to the transactions of those times,
when their predecessors, instructed and strengthened from on high,
first broke through the host of impediments by which they were surrounded,
and notwithstanding a "`fight of afflictions,`" succeeded
in rearing this standard of Truth among the nations?
And, indeed,
there are those "`not of this fold,`" whose eyes have been truly anointed to see;
so that they cannot but unite in the substance and
general ground of that spiritual testimony,
which has in a special manner been delivered to us.
Some readers of this description,
fully prepared to admire the unfoldings of heavenly
light on the mind of Jaffray in the Diary,
may, it is hoped, be led to follow him further,
and with increasing interest in the MEMOIRS; these will be qualified,
with him and many others,
to enter into the force of such an acknowledgment as the following--"`Indeed
it was great matter of satisfaction to our hearts,
when the Lord turned us to his Truth, that we found it to be no new thing,
but that which we had witnessed in the days of our former profession.
For, we well remembered, that we had been acquainted with it then;
and God now gives us the true and certain sense, that all the prayers, and knowledge,
and understanding of the Scriptures, faith, love, zeal, meekness, patience, humility,
and whatever we then had, which was dear unto us, and precious in the eye of God,
came from this Spirit of life,
this principle of life which God hath now manifested to us,
and turned our minds unto.`"--Penington`'s Letters, 2nd edit. p. 9.
By such individuals, above alluded to, as well as by the Society of Friends,
the several valuable epistles and other documents interspersed through their history,
will doubtless be viewed as so many lively tokens of the
condition of this portion of the Church of Christ;
and may, I trust,
be accepted as forming no unsubstantial addition to their stock of religious reading.
On the other hand, those who are much strangers to us,
and have been under misapprehensions as to our early proceedings or character,
may very probably find many obstructing clouds cleared away
from their minds by a candid perusal of these pages.

I have only, in conclusion,
to add,--my sincere and earnest prayer has been unto the Author and Giver of all good,
that, through his Divine blessing, which can give success to the feeblest efforts,
this collection may, according to the abundance of his grace in Christ Jesus,
our Redeemer, redound to his own praise!

[.signed-section-signature]
John Barclay.

[.signed-section-context-close]
Croydon, 2nd month, 1833.
