== Chapter II.

The birth of Alexander Jaffray in 1614, and his education at Aberdeen--1632:
His marriage with Jane Dune--He spends some time with Robert Burnet, advocate,
in Edinburgh--Takes a journey to London--1633:
Attends the coronation of King Charles the first at Edinburgh--Travels to France twice--1636:
Settles at Aberdeen--His lifeless formality in private and public duties--1644:
The death of his wife--"`Sir George Gordon,`" Laird of Haddo,
violently assaults and imprisons him for the space of five weeks.

The way of God with me, before, as well as since my conversion,
(if I may so speak,) hath been full of kindness and love:--he saw and loved me,
while I was cast out and lying in my blood. Ezek. 16:6.
--Being born at Aberdeen, in the month of July, 1614,
I was bred at +++[+++the grammar]
school there by my parents, and sometimes with my uncle +++[+++of]
Pittodrie, and at Banchory under Gilbert Leslie, Mr. David Wederburne,
Mr. Alexander Strachan, and Mr. Robert Dewine, as school-masters.
This was the evil and inconvenience of these times to me,
that occasioned my little profiting:--I had, through the indulgence of my parents,
too much liberty, in being sent here and there,
from school to school,--as also the little care of these men who had charge over me;
some of them being openly scandalous,
and none of them having much profession of religion, except Mr. Robert Dewine,
and he having so little natural prudence,
that he was not very capable to teach and educate children in the fear of God,
nor yet careful, making conscience of their education in letters.
My parents,--though in everything they were most tender,
and evidenced much love and respect to me,--yet,
not being themselves much acquainted with the great advantage
there is in breeding young ones timely in the fear of God,
and keeping them closely and diligently at their
studies,--in this they were some way deficient.
And I am likely myself to fall into the same fault,
which will be much more inexcusable in me than in them;
their breeding being very different from mine,
and especially considering the opportunities I have had, both at home and abroad.

Yet the goodness of my God was such, that all this while he was watching over me,
so that I was preserved from falling into any scandalous, known sin.
Having formerly some way expressed what I desire may be
forever kept upon my heart of other guiltiness,
I shall say nothing of these here; my good God having pardoned them,
I purpose not to give Satan advantage any more to accuse me of them.
Only some few things I shall +++[+++revive,]
wherein, as the goodness of God and his loving providence towards me may be remembered,
so may I be made more and more sensible of my unthankfulness,
and unanswerable walking to such mercies wonderful and rich deliverances!

Having spent divers years very idly,
from the time of my first entry at the grammar-school, which was, as I suppose,
about the ninth year of my age,--sometimes with my uncle +++[+++of]
Pittodrie in the Gorioch, and in Buchan, where I had no occasion to learn any good thing,
and for one year or two at the school in Banchory;
by this unfixed and unsettled way of getting too much liberty, I lost much,
especially in attaining a knowledge of the Latin tongue.
About the middle of the year 1631, being then about seventeen years of age,
I came from the school in Banchory to the College, where, passing the first class,
having made the manner to learn some Greek in Banchory,
I entered to my logics under Mr. Hugh +++[+++or Howe]
Gordon, regent, and Dr. Dune, then principal,
who were both of them unfit for training up youths,
so that I had no good example from them.

Having stayed a short time in the College, and profited as little, I was,
in the month of April, the last day thereof, in the year 1632,
married to Jane Downe +++[+++or Dune,]
being then eighteen years of age.
It hath been sometimes thought upon,
as a thing for which I owe much praise and thankfulness to God, when I consider,
that the motives and ends of my parents in this marriage were not right,
but carnal and worldly;--and so brutish and senseless was I,
that I never minded nor sought God in the matter,
but went on in blindness as they directed me,
not ever considering the Lord`'s mind in it,
nor the qualities of the person with whom I was to join.
And yet, such was the goodness of my God unto me, that in this +++[+++engagement]
he directed me well, whereas he might have made the circumstance a cross and curse to me;
but it pleased him to bless it,
giving me not only much contentment of a meek and quiet yokefellow, who,
all the time of our being together, was very comfortable and pleasing to me;--even this,
is matter of very great mercy, for which I ought to praise God.
There was also more in it; for, I trust I have good grounds to say,
that the seeds of grace in good measure were begun to be sown in her heart,--as
her sober and Christian carriage during her life witnessed,
but more especially God`'s presence with her at her death,
which hereafter I shall mention,
as it occurs in the story of my being violently withdrawn at that time,
and taken from her.

Some twenty days after my marriage, I went to Edinburgh,
my father thinking fit to send me there for some time,
where I stayed the space of five or six weeks.
And here I am obliged to remember,
the kind respect I met with from my worthy friend Mr. Robert Burneit, +++[+++Burnet]
advocate, who kept me much of that time in his house,
where I had good occasion to hear and see some good things;
not only to learn some things of the law and practice of the Tolbooth,
but some things as to the practice of holiness and charity,
especially of observing the Sabbath-day,
for the neglect of which he ofttimes challenged and reproved me.
+++[+++see Appendix, B.]

About the end of July,
(I having come there in the beginning of June,) my father advertised me,
that it was his purpose to send me, with Robert Skeine and Andrew Birnie,
two merchants of Aberdeen, to London, to see the country; and desired me to make ready,
against their coming to Edinburgh, to go with them.
But I resolved, I would first see my wife; and presently came from Edinburgh to Aberdeen,
where I stayed only about the time of eight days, and so went for London.
I went by the way of Leeds and Wakefield,
and there had occasion to see the form of their buying of Yorkshire cloth.
I stayed at London only the space of twenty days or a month,
and in September or thereabouts returned home.

In the month of January, 1633, the King being then to come to Edinburgh to be crowned,
I went over and attended that ceremony.
+++[+++see Appendix, C]

In July thereafter I came home, my wife being, before my coming,
brought to bed of her first son, called Alexander.
Shortly thereafter, I went again to London, in company with Robert Skeine, Andrew Birnie,
and George Jamieson.
+++[+++see Appendix, D.]
I stayed some time longer, and... on my return, went off the road,
and visited the University of Cambridge by the way.

In September, 1634, I went to France; and there stayed in Caen in Normandy,
for the space of three months; in which time, I learnt so much of the French language,
that I was able to travel without a guide.
From Caen I went to Rouen, and from thence to Paris,
where I stayed for the space of two or three months; from thence I returned to Rouen,
and so to Dieppe, and in the month of June I landed in Leith.
In September thereafter I went again to France, and stayed five or six months,
most part of the time in +++[+++Neufchatel]
dispatching some +++________+++, and had them with me,
and made some +++_______+++ but to very little purpose.
+++[+++see Appendix, E.]

In these my two journeys to France,
many things of the goodness and kind providence of God towards me,
might have been observed.
These few only, for the present, occur to my memory.
I was wonderfully preserved by sea, both going and coming,
and during my abode in the country:--and more especially was I
preserved from the sins of drunkenness and +++[+++licentiousness,]
whereunto there was there great provocation.
Having so much liberty and a full purse, (for I wanted not +++[+++inclination]
to spend,
my nature being as perverse and vile as any,) and
having these occasions of provocation administered,
I have often since thought it a great mercy and wonder,
that I was kept from open scandal and out-breaking.
This hath many times given me occasion to think of recommending to my children,
not to venture upon such a way of traveling abroad,
until they have first attained to some more experience,
especially in the knowledge of God and the fundamentals of religion.
Without this, to travel to France or elsewhere, as I did, and most part of young men do,
is to expose them, not only to the hazard of being tempted to all abominable vices,
but to be insnared in the abominable and gross errors of Popery.
Therefore, it were expedient for young men not to go there,
before they were well grounded in the knowledge of God,
and were in some measure acquainted with the controversies; and,
if their condescension may allow it, to have a wise governor with them were of great use;
and next to that, good company will be to them of much benefit,
whereof there would be had special care.
Next to these, bodily dangers on highways are mostly to be feared and shunned,
especially in traveling late in the country or city, but chiefly in Paris.
It pleased the Lord very wonderfully to deliver me
from some perils of this kind in Paris,
where I was very near losing my life,
being wounded in my left hand and in my back by a drunken soldier;
but the Lord delivered me by the help of two gentlemen, whom I knew not.
And thirdly, the danger of being cheated, in borrowing or lending money,
is ordinary to young men there,
and of being too prodigal in spending upon clothes and other such like things;
for afterwards, when a more retired life is taken up,
there is commonly much repentance and regret for these things.

Being the second time returned from France,
in the end of the year 1635 or beginning of 1636, about Whitsunday in that year,
I entered to dwell by myself; all the time before that,
having stayed in my father`'s house,
where my wife most easily supported to be with my parents,
and grudged neither at her long stay with them, nor at my long absence;
for of these first three years of my marriage, I was not with her one of them at home.
+++[+++A passage is here omitted respecting his father`'s behaviour towards him, etc.]

Albeit at this time, I mean, when I took up my own house,
I was about the age of twenty-two years, yet I was very ignorant;
not only in the things of God, which in the first place I have much matter to regret,
but also even in the things of civil and private concernment,
as to the management of the affairs of my estate and family; so that,
within some few years, I had not only spent the rent of what was my estate,
but four or five thousand merks of the stock.
Some few things I think fit here to express, of which had I been timely advertised,
and had well adverted to them,
might have been much to my advantage in spiritual as well as temporal things;
in both which, through my sloth and ignorance, I suffered.

My ignorance of God made me slow in seeking to him, and unclose in my walking with him,
in my private conversation and in my family; performing duties,
whether in a more private or public manner,
but very seldom and superficially,--though I durst not omit doing them,
yet there was nothing more than a resting on that, either on the week or sabbath days.

I desire here to admonish my children, to beware of this lifeless formality and laziness,
but to be diligent in seeking God in private, morning and evening.
Not that I intend a tying up to particular hours;
there may be much formality and a snare in that;
and yet there should be diligent heed taken, that, whilst the evil of this be shunned,
another snare be not run upon, that of growing slack and negligent in prayer.
Though I dare not peremptorily tie to hours in the day, yet that day,
in which God is not more than once sought to by prayer, is not well spent.
This neglect should be diligently adverted to, not only that the duties of prayer,
reading the Scriptures, and conference upon it, be performed in private;
but also together with thy family,
and more particularly at some times with some of thy family apart,
having observed the disposition and temper of thy wife, children,
or any servant that is seeking God.
To admonish and exhort them, is looked on by every godly man as a duty; but,
few think of praying with any or every one of them apart, which, doubtless,
would be found a blessed means of doing much good,
and is promised as a blessing to the families under the gospel. Zech. 12:12-13.
The right performance of such duties,
in a conscientious and loving way, would make more reverence, love,
and comfortable fellowship to be among all sorts of relations,
which many times is wanting; God either justly depriving,
even sometimes his own children, of the comfort of these enjoyments,
or embittering them with many sour fits of distempered passions,
for their neglect of conversing in this spiritual way together.

+++[+++Here follow some recommendations to his children, as parents of families,
resulting from, or as he expresses it,
verified by his own experience of the benefit of them; namely, on meditation and prayer,
on conference, and catechising the members of their families,
attending the public ordinances of religion,
and frequenting special meetings for religious conference; also taking down sermons,
and enlarging on them.
The Diary then proceeds.]

Commonly, in reading books of religion or of human story, I found most profit,
by so pondering and digesting what I found most to speak to my condition,
or that might be most useful to me thereafter, so as to put it in writing shortly,
in some notes in a little book I carry along with me.

+++[+++After this, the writer informs us, how ignorant he was,
up to the time of his father`'s death,
of the state of his father`'s property and affairs,
and "`what was likely to come`" to him, etc.;
with some observations on the propriety of keeping clear and correct accounts, etc.;
but adds, that his main design in this book is more to spiritual subjects,
and "`the observation of the goodness of God, for the engaging of my heart to him.`"]

In the year 1644, the 19th day of March, or thereabout,
it pleased God to remove my wife by death; which was hastened, much to my grief,
by the Laird of Haddo ^
footnote:[A predecessor of the Earl of Aberdeen.
The Family residence, Haddo Castle,
is a few miles N. W. Of Old Meldrum.]taking me prisoner out of my own house,
the occasion of which was as follows:--Some time before that,
I committed a servant of his to prison for a riot done in Aberdeen.
Thereafter he pursued me near to Kintore, +++[+++about twelve miles from Aberdeen,]
for my life; after some strokes had passed between us,
he left me wounded in the head and my brother John in the arm,
for no other cause than is mentioned above.
After this, I having pursued +++[+++prosecuted]
him, obtained the laws of the country, the riot being proved; and he not comparing,
was declared fugitive, and fined in twenty thousand merks,
whereof fifteen thousand to the State, and five thousand to my brother and me.
+++[+++see Appendix, F.]

The country being then in a loose and broken condition, he joining with his chief,
the Marquis of Huntly, declared themselves enemies to the State,
and took up arms for their defence.
The first act of his appearing was at Aberdeen, with the Laird Drum the younger,
+++[+++son of Sir Alexander Irvine,]
where he took captives myself, my brother John, Mr. Robert Farquhar, and Patrick Leslie,
and carried us to Strathboggie, where we were kept.
Ten or twelve days after, we were sent to Auchindown Castle,
and kept there five weeks close prisoners; until,
by the Marquis of Argyle`'s coming north,
the Marquis of Huntly and his friends quitted the field; himself came to Auchindown,
where any little treasure he had was;
and fearing that the keeping of us prisoners might have drawn some siege to that house,
he dismissed us.
We were, by him and his order, very cruelly used all the time of our imprisonment.
The quarrel he alleged against us, was, that we were Covenanters,
and had given bad information against him and his friends.
+++[+++see Appendix, G.]

We being dismissed by him, went first to Murray,
where we were kindly received by our friends there; thereafter to Keelie +++[+++Kelly,]
the Laird of Haddo`'s house,
about which the Marquis of Argyle and his forces were then lying.
The house being rendered, I had leave to go in with an order to the Laird,
to render to me some rights, +++[+++that is, writs or writings,]
and my wife`'s rings and chains,
and some other silver work he had taken from me at my seizure in Aberdeen;
the most part of which, afterwards, I had back from him.
I spoke my mind to him there some way freely,
exhorting him to repent for the wrong done to me;--especially that great wrong,
above all the rest,--his fury and violence in taking me,
by which he had hastened the death of my dear wife, who,
within three or four days after my being taken, departed this life.
I was married to her twelve years, during which time I had very much contentment,
she being a most kind and loving wife; she bore me ten children,
whereof there is but one now living, called Alexander;
he was baptized by Mr. Andrew Cant, +++[+++one of the ministers of Aberdeen,]
the 17th day of October, 1641.
As her life was blameless before the world,
so was she beginning to be a serious seeker of God, and departed this life,
having given good evidences of her hope of a better:--as was testified
to me by the ministers and other Christians of that place,
who were much comforted with her Christian expressions,
especially with her free and most Christian exhortations to her uncle Dr. Dune the elder,
and other her friends and mine.
I desire, upon every remembrance of her, to be thankful to the Lord,
who so ordered me in my choice; though I was then so ignorant,
that I remember not if I sought it of him,--but his goodness in this,
as in many things more, did prevent me.

In that contest I had with the Laird of Haddo,
I was wonderfully delivered from extreme danger.
The first time that we encountered near Kintore, he fired two pistols at me,
one after another, being then within twice the length of his horse from me;
both of them misserved; whereat he was in great fury, alleging,
they had never done the like before.
And that same night, in Old Aberdeen, to try them if they would misserve again,
he put out the candle at which he shot.
The other time was that day when he took me prisoner: he,
having entered my father`'s study, fired a pistol at me from the window,
whence he pursued me in another study.
Just opposite to the window where he was, that pistol also misserved, at which he cursed,
alleging, he would never get me felled.
I knew nothing of this second attempt, before he himself told it me in Aberdeen,
as he was going prisoner to Edinburgh, sent by the Marquis of Argyle,
after the taking of his house.
