== Chapter III.

[.chapter-synopsis]
* 1644: The Irish, entering Scotland under Macdonald and Montrose, advance to Aberdeen; they are ineffectually opposed by the citizens under the Lord Burleigh
* Alexander Jaffray, retiring from Aberdeen, is kindly received by the Earl Marischall
* Being taken prisoner by Harthill the younger, he is kept several weeks at Pitcaple
* He is nominated on a commission of parliament to try delinquents
* 1647: His second marriage with Sarah Cant
* The death of his parents
* A pestilence at Aberdeen; he being a magistrate there
* 1640: Being a member of the Scottish Parliament for Aberdeen, he is twice sent to Holland, with other commissioners, to treat with King Charles the Second.

Shortly after this, +++[+++namely, in 1644,]
the Irish that entered Scotland under Alester Macdonald and Montrose,
having come the length of Aberdeen, were fought by a regiment of the country soldiers,
under the command of the Lord Burghly +++[+++or Burleigh,]
accompanied with some country gentlemen, and most of all the citizens of Aberdeen;
where about seven or eight score men, besides women and children, were killed.
I was at that time in no small hazard, having stayed too long on the field,
after our men began to run; yet it pleased God to deliver me.
Being very evilly horsed, I was well near among the Irish hands; yet,
by the good providence of God, I escaped, carrying a pair of colours with me,
which I had taken from one of our soldiers,
who was casting the same from him in the flight.

Thereafter, the country being so loose and broken, I could not safely stay at Aberdeen,
so went with sundry other honest families to Dunnotter,
where we were very kindly received by the Earl Marischall, having house-room from him,
and our entertainment from Aberdeen and Stonehaven.
One day, having gone with Mr. Andrew Cant to Crathes, to visit his son Mr. Alexander;
on our way back, we were encountered by the Laird of Harthill the younger,
who was then returning from the battle of Kelsyth,
where Montrose had gained the sixth and last battle he had over Scotland.
We were by the said Harthill and the Laird of Newton Gordon taken prisoners,
(Mr. Andrew Cant, my brother Thomas,
and I,) after very much threatening presently to have killed us,--especially I was threatened,
as being guilty, they alleged, of Haddo`'s death,
who had been executed for his rebellion against the State.
Yet it pleased the Lord to restrain their fury.
We were that night kept prisoners at Aberdeen, and the morrow carried to Pitcaple,
where we were kept under the custody of one Petrie Leathe, brother to old Harthill.
Many things might I remember, that would be too tedious here to insert;
only some few I shall point out, wherein the Lord`'s goodness,
and his wonderful hand in delivering us, did most eminently appear.
+++[+++see Appendix, H.]

At first, at our taking,
where they with great fury and main fearful oaths did threaten sore,
yet not one hair of our heads did fall to the ground.
Secondly, all the time of our being prisoners,
which was for the space of either five or seven weeks,
though they were a company of as vile, profligate men as any I did ever see;
yet was there so much restraint laid on them,
as that they carried themselves civilly before us.
And sometimes some of them were content to be present
at our private exercise of God`'s worship,
morning and evening,
which was constantly performed by that gracious and worthy man Mr. Andrew Cant,
who on the Lord`'s day occasionally preached publicly in the great hall;
sometimes all of them were present,
and had something like convictions at the hearing of the word,
which was preached unto them with much boldness and freedom.
Yet did they go on, in the frequent practice of their drunkenness and abominable vices;
so that we, being very weary of their company,
frequently would project and talk among ourselves of ways to escape.
At last, we attempted a very desperate-like piece of service, which,
had it not pleased the Lord in a wonderful manner
both to give us courage and success more than ordinary,
we could never in any probability have been able to have carried through.
But,--to the praise of the majesty of the Lord, let it be said,
as an obligation forever to be upon me!--I was,
that twenty-four hours during which we kept the house,
wonderfully assisted and borne out with more activity and courage; so that,
in the most dreadful times of our danger, while we were almost in the very jaws of death,
I had not any sense of danger or fear.

One day in the afternoon, all the men except two being abroad,
whereof one was an old decrepit body, we resolved to go and shut the gate.
Having had advertisement that some of our friends, commanded by Major General Middleton,
were that night at Aberdeen, having come north after the battle of Philiphaugh,
+++[+++which took place on the 13th of the month called September;]
we were confident, that if we could get possession,
and maintain the house till the morrow morning,
our friends would before that time be at us for our relief.
We having gone down, (I and my brother Thomas, with a soldier of Middleton`'s,
whom the garrison had taken straggling from his colours,) found, by our expectation,
two as able men as any in the company, standing in the very passage of the door,
being about the flaying of an ox, which they had lying within the door.
I being first, when I saw them, began to think of returning,
but fearing that they would espy what we were about by the others following me,
I resolved to go forward; and was much encouraged,
by their withdrawing a little without the door,
to make sharp their knives for the work they were about.
Finding them without, though they were close at the door,
we went down and offered to make it fast, which at last with much ado we got done.
Then, having full possession of the house, we made fast the iron gate,
and put ourselves in a posture of defence.
The rest, being advertised, came about the house, and so continued until night.
By reason of their being there, one of our servants,
who had undertaken to give advertisement to our friends at Aberdeen,
that they should come for our relief, was forced to lie and hide himself all that day,
so that it was the morrow at nine hours before he
came to Aberdeen--and then our friends were gone.
So our help that way was disappointed; but the Lord provided for us another way.

The Laird of Leslie the younger, having advertisement from the country people,
that we had taken the house, gave advertisement to some friends,
who came on the morrow by one or two hours in the afternoon: the Lord Frisell,
the Laird of Echt, Colonel Forbes, with the number of thirty horse or thereabout,
and fifty or sixty foot.
This was very observable, that as they came without any advertisement from us,
so did they come in the most seasonable time, when we were well near spent,
having been pursued very sharply from nine hours until then.
After we had beat them several times off, and killed one of them,
at last they were driving through the wall,
at a place where we could get no sight of them;
and when they were almost gotten fully through, then our friends came,
when we were even fainting and going to give over.
We received our friends, and entertained them the best we could;
and parted that night with them, having set our prison on fire, it not being tenable.
+++[+++see Appendix, I.]

Thereafter, we went to Dunnotter, and from thence to St. Andrew`'s,
where the Parliament was then to sit; and having returned home to Aberdeen,
I was called to sit as one of a Committee +++[+++of Parliament,]
for borrowing of money and censuring delinquents.
We sat at Dundee for the space of three months,
and proceeded too rigorously in these things committed to us; and sometimes since,
I have had some desires to repent for that unwarranted zeal.
+++[+++see Appendix, J.]

Shortly after this, namely, in the year 1647, the 4th day of May,
I married my wife Sarah Cant, who now lives, +++[+++daughter of Andrew Cant before mentioned.]
What mercies we enjoy, as the blessing of God upon our marriage,
how long we may enjoy them, and what use we shall make of them,
the Lord give us rightly to know and thankfully to acknowledge;
lest abused mercy may draw sad strokes out of God`'s hand.
She hath borne to me five sons and three daughters;
whereof at present there are only three living.
The eldest, called Andrew, was born the 8th day of August, 1650; the second,
called Rachael, was born the 28th July, 1653; the third, called John,
was born the 22nd December, 1654.

From this forth, I shall mention what mercies I may remember, what mercies my wife,
my children, or any in my family received; for, what any of them received,
ought to engage and oblige my heart to my God, as much as if they had been to myself.

+++[+++The writer then commemorates "`the manifold goodness and singular
providence of God,`" on several occasions of "`great extremity,`"
during his wife`'s confinement with some of her children,
when "`he was pleased to vouchsafe preservation and help in a wonderful manner,
in answer to prayer.`"]

Having omitted to mention my father`'s and mother`'s death,
I shall touch a little on them here.
My mother, having lived twenty-nine years after her marriage with my father,
departed this life the 28th September, 1640; my father being then in Edinburgh.
After his coming home, he lived in his own house until Whitsunday thereafter;
when he was pleased to call me to enter home with my family to his house;
he promising to pay me whatever sum should be spent more when we were together,
than I spent when I was apart by myself.
We lived together thus for the space of three years and a half; until,
in the end of the year 1644, the Irish having, after the fight at Aberdeen,
so spoiled his house, that he had no plenishing +++[+++furniture]
left him; and then he did board himself and me, with one servant to attend him,
in the house of our cousin Alexander Burnet the elder,
where he and I entered in November, and stayed November, December,
and the beginning of January, 1645.
He took sickness, and died the 10th day thereof, in his own house.
He was much reformed, and withdrawn from company-keeping in taverns, before his death;
and I trust he found mercy, and died in favour with God and men.
He was a very kind and loving father unto me all his life;
and so did he give much evidence of it at his death, as may yet appear by his testament,
where he puts much power in my hand in dealing with the T... +++[+++town;]
and also much confidence in his hopes of my being kind to them; in which I hope,
through the strength of Christ, never to deceive him.
Yet was he, during his even time, very strict in counting with me;
but at his death supplied all very fully, according to his power.
I have sometimes, since his death, observed God`'s goodness,
in directing me in walking so with my father, as that I gained his affection much,
which moved him to deal so kindly with me in the end.
In worldly things, though he dealt something strictly with me, I never troubled at it;
but having sometimes made my condition known to him, and,
with much circumspection and fear to offend, told him,
that I thought he had dealt strictly with me; still I referred all to himself,
which was the only way that gained him.
Whereas, if I had contended with him, he being a very passionate man,
it is likely he might have disinherited me, or have taken some such course.
Another particular of my carriage much engaged his affection to me: he,
having some little time before his death a purpose to marry,
thought that I should not have assented thereto, and have hindered it what I could;
but when he found it otherwise, that I was fully consenting,
it made him the more to regard me, and the less the purpose he was about.
Whereas, if I should have opposed him,
I knew well it would have made him run to it the faster.
Yet I had other, and more worthy considerations, moving me to consent,
which I spare here to mention; but the Lord ordered it well, etc.
+++[+++see Appendix, K.]

In the year 1647, the pestilence raged in Aberdeen for the space of five or six months.
All this time, my family was preserved; which was the more observable,
as I was every day among the sick people, being a magistrate: for the time,
I removed to Kingswells.
+++[+++see Appendix, L.]

In the year 1649, I being then a member of Parliament for the town of Aberdeen,
was sent unto Holland, with the Earl of Cassles, Lord Brodie, and Lord Libertone,
for to treat with and bring home our young King.
I shall spare to mention many things, for shortness: only, by the way,
I must observe this, that having gone there in the simplicity of our hearts,
minding what we conceived to be duty,
it pleased the Lord to bring us safely off without any snare or entanglement.
But, being again sent there by the Parliament, in the year 1650, for that same business,
we did sinfully both entangle and engage the nation and ourselves,
and that poor young prince to whom we were sent; making him sign and swear a covenant,
which we knew, from clear and demonstrable reasons, that he hated in his heart.
Yet, finding that upon these terms only, he could be admitted to rule over us,
(all other means having then failed him,) _he_ sinfully complied
with what _we_ most sinfully pressed upon him:--where,
I must confess, to my apprehension, _our_ sin was more than _his_ +++_______+++.

+++[+++Here, one leaf of the manuscript is evidently _torn out,_
containing nearly as much as one page of this letter-press.]... and knew well,
that what he was doing, was but through plain force and constraint.
In this, he was not so constant to his principles as his father,
in yielding to this act of so gross dissembling:
but his strait and our guiltiness was _the greater,_ especially +++[+++that of]
some of us,--I mean especially by myself,
who had so clear convictions of this to be wrong, _that I spoke of it to the King himself,_
desiring him not to subscribe the Covenant,
if in his conscience he was not satisfied,--and yet went on to close the treaty with him,
who, I knew so well, had for his own ends done it against his heart.
But I may say,--so did I desire him to do it against mine,--so weak and inconstant was I;
being overcome with the example and advice of others, gracious and holy men,
that were there,
whom in this I too simply and implicitly followed,--choosing
rather to suspect myself in my judgment to be wrong,
than theirs.
But the Lord taught me in this, and in things of that nature,
not so implicitly to depend on men.

What the sad effects and bitter fruits of that business hath been,--I
shall spare to mention,--__that__ not being the business I intend here.
Only, I think, the Lord hath very justly reproved us,
and the whole nation,--especially the leading men
of church and state,--for so much prevarication;
in pretending to be for his glory, in carrying on his work; while,
it may be evident as the light,
what the design of that second message was,--in sending for and closing with _him,_
whom we knew, to be no less opposite to the carrying on of any work for God`'s glory,
than ever his father was.
But the English, having disappointed so far our expectation,
in carrying on the work of union and uniformity in the three nations,
conformably to the model and design of Scotland,--so cunningly
plotted and contrived in the League and Covenant,--were likely,
in establishing both civil and ecclesiastical affairs,
to carry it plain contrary another way than was intended
and hoped for;--wherein the Kirk,
(as we call it,) was likely to suffer not a little.
For, instead of Presbytery being established, in the way of the Kirk of Scotland,
whereby _they_ might rule all,
there was likely to be set up a lawless liberty and toleration of all religions;
whereby _they_ would be altogether disappointed,
and rendered incapable to rule in any thing, either in church or state,--but merely such,
in church affairs, as willingly should submit to them.
To prevent this deluge and overflowing scourge,
as it was then thought to be,--the prevailing of the Sectarian
army,--no means was thought to be so fit,
as to bring home our King; otherwise, it was conceived inevitably to follow,
that both Monarchy and Presbytery would be ruined.
And so, the leading men both of church and state,
however otherwise divided among themselves, are unanimously joined in this.
Most of the royal party and Presbyterians in England, being in this no less concerned,
their concurrence was confidently looked for,--as in the issue it did appear.

But, how has the Lord overturned all these contrivances and devices of men`'s wits,
for upholding their own devices and inventions! _his_ work, and the glory of it, being,
as of another kind, so to be brought about in another manner:--this we might have seen,
had our eyes been opened--dear-bought and precious experience gives us now to know it.
Having said enough +++[+++on the subject,]
it was my purpose to leave it;
but that I find myself obliged to remember one passage relating to this business,
wherein the Lord`'s goodness and sincerity did both so eminently appear to me,
that I desire my heart may be ever kept in memory of it while I live.
+++[+++see Appendix, M.]
