== Chapter V.

[.chapter-synopsis]
* 1652: Alexander Jaffray is made Director of the Chancellry
* 1683: He becomes, with four others of Scotland, Member of The Parliament of England
* He remains in the House, together with about 30 other members, when that assembly is broken up
* Cromwell offers to make him a Judge for Scotland
* He contracts much weakness of body while in London
* 1656: Removes his residence to Edinburgh
* In a view of mercies, temporal and spiritual, he resolves "`To make haste and follow hard after God,`" and on bearing the cross; also something relative to the sufferings of Christ:
* 1667: The illness of his son Andrew--On the state of the church.

Thereafter, I was called by the Judges at Edinburgh to be Director of the Chancellry,
in the month of March, 1652, which I accepted of in the month of June.
+++[+++see <<note-W-diary,Appendix, W.>>]

In the month of June, 1653, I was called, with other four out of Scotland,
to sit as Member of the Parliament of England.
I came there the 5th of July, and stayed until the 6th of February, 1654.
I had there good occasion to meet, and be acquainted with many godly men;
though I can say little of any good we did at that Parliament: yet,
it was on the hearts of some there,
to have done good for promoting the kingdom of Christ; but, the time not being come,
when these things were to be brought forth, we were dissolved the 12th of January, 1654.
I came for Scotland the said 6th of February thereafter; having gotten, at that time,
from the Lord Protector and his Council,
an order for paying to me by the Commissioners at Leith, £1500 sterling,
for paying my part of that debt we contracted in Holland in the year 1650.
When that Parliament was broken up, I not being satisfied with the reasons thereof,
was one of thirty or thirty-one that stayed in the house.
Yet, the Protector was pleased to give me the aforesaid order, of which I got payment;
and did offer me to be one of the Judges in Scotland; but this I refused,
finding myself not capable for discharge of that duty.
+++[+++see <<note-X-diary,Appendix, X.>>]

In this journey, having sought of the Lord,
that I might be directed and kept from doing wrong, and kept from snares and temptations,
I had matter to acknowledge the goodness of God to me, who brought me off,
without doing any thing willingly to grieve him or wrong my conscience;
nevertheless of some temptation that for the time I was under,
yet was I graciously delivered,--to the eternal praise of his grace!

Having stayed at London for the space of seven or eight months,
I was at this time convinced, that thereafter,
it was not fit for me to be so long time from my wife and family;
except it were for a very necessary business,
and that I had her consent more fully thereto.

I contracted, when in London, very much weakness of body,
which in part sticks to me to this day.
I cannot positively assert the reasons why it was so,--only this much,
in the general:--Satan being very busy, I was much assaulted with variety of temptations;
wherefore, I found it convenient to make use of a spare diet.
I dare not say, that I was much in prayer; but sure,
I was never more called to it,--and yet, very negligent.
My purse also invited me much to be sparing; and in this,
I did afterwards much blame myself,
that I did not take what lawfully the Lord allowed me,
for upholding my crazy body:--though a body of sin
and death be some way fed by our +++[+++over-]
feeding the natural body, yet we must not +++[+++neglect]
the natural body by +++_______+++ withholding necessary +++_______+++.

+++[+++Here a leaf of the manuscript is mutilated and torn off,
so as to make a chasm of more than half a page of this letter-press; in which,
something is said respecting Christ being the fountain
or well of life itself in our hearts;
and that, when we know this, we shall thirst no more,
nor be satisfied with any thing short of this experience.]

On my coming from London, in the year 1654,
I continued living the one half of the year at Aberdeen, and the other half thereof,
namely, the six months of the Session, at Edinburgh, attending on my charge,
as Director of the Chancellry.
But finding this way of living, the one half of the year _from_ my family, not convenient,
neither for myself in body and mind, nor for my family;
I therefore resolved with my family, to come and live in the south;
seeing I could usually get my affairs in the north dispatched by another,
which in the south I could not do,
being for six months in the year tied to necessary attendance.
And therefore, upon the 4th day of November, 1656, I parted from Aberdeen,
with my wife and three children, and the 7th day of the aforesaid month,
we came safely to Leith;
where we found our two women servants and our plenishing +++[+++furniture,]
come thither by sea, a day or two before us.

Among other of God`'s goodnesses unto me,
I have matter to look on this,--his direction and presence with me and my family,
both in resolving upon and prosecuting our journey;
where so much of his care and tender providence was manifested to us,
and to all in our company or that concerned us, both by sea and land,
that we were carried, as it were, on eagles`' wings,
without the least trouble to the mother, then about four or five months gone with child,
or to the young ones that were with her;
though the season of the year was not very convenient for such to travel in; yet,
by the good hand of our God with us,
we were all safely brought to New-battell +++[+++Newbattle, near Edinburgh,]
the 15th of November aforesaid.
+++[+++see <<note-Y-diary,Appendix, Y.>>]

Upon the remembrance of these, and other the wonderful goodness of God to me,
in matters of this and of a better kind, I have sometimes been thinking and +++[+++minding]
_at the engaging of my heart anew again unto him;_
but find this of more concernment and difficulty to me rightly to be performed,
than I had at any former time thought of.
Of _so much_ concernment to me +++[+++did I find it,]
to make haste and follow hard after God, as the Psalmist says,
in closing more closely with him,
or inevitably to be miscarried and brought to a further
and more dreadful distance from him;--that,
upon this account, were stirred in me all the considerations following.

Besides the temporal favours received,
of which not a few instances have been given in these notes, my obligation unto God,
for mercies of another kind, was _infinitely great, to love him much;_ being persuaded,
and that without presumption, yea, rather with fear and trembling,
that there is _much forgiven._
The necessity of this was wonderfully cleared up to me.
The difficulty of attaining to this, on the other hand, is no less heightened,
through a busy enemy, with insuperable difficulties.
But at last, after some serious thoughts and seeking of God, as I could,
that which follows was at divers occasions presented to me.

That, while I walked so loosely, as to admitting into the heart vain and unprofitable,
yea, sometimes, sinful thoughts,--while my watch was so often down and asleep,
as to thoughts, words, and looks,--I need not but expect a snare _in everything,_
to hinder any fixedness in such resolution of seeking further communion with God; yea,
+++[+++I need not but]
fear being overcome of _every_ temptation +++[+++that might be]
suggested by Satan, who was not slow, but very active +++[+++herein.]

That I was eminently called upon,
before any nearer access and communication with God could be attained,
to remember former mercies and be thankful for them;
more especially to call to mind former guiltiness,--the
sins of my youth,--these having been many and great;
though they be blotted out and freely forgiven me, yet ought they to be,
(and the more for this) _always before me._ Ps. 51:3.
By frequent remembrance of these,
I found the goodness of God heightened in my view,
which has pardoned and overcome so much, and therefore__ an engagement to love him much,__
as it is said in Luke 7:47 of that good woman.
It also served to humble my heart greatly, when I perceived,
not only how vile I have been, but still am;--these sins, as to the root of them,
being still in me, and in no wise to be subdued,
but by going on in a daily course for mortifying
them,--even by near and close walking with God,
in watching against the first motions and risings of sin in the heart.
This consideration put me, sometimes, upon the desire,
to be preparing patiently to bear what cross or affliction
the Lord should think fit to exercise me with;
seeing that, as a kind father, he chastiseth and scourgeth every son whom he receiveth,
Heb. 12:6; as the church saith in Mic. 7:9,
"`I will bear the indignation of the Lord, because I have sinned against him.`"

And the Lord does evidently speak out many excellent lessons,
by this way of exercising his children to the cross.
Thus, he makes sin vile and loathsome to them, teaching them,
by the effects and fruits that it produces, thereby to judge of it.
Albeit, I be persuaded of this, yet _most hardly_ could I find my heart made sensible,
experimentally to know what it is to hate sin,--what is meant by that hatred,
indignation, and revenge mentioned by the Apostle, 2 Cor. 7:11,--which, doubtless,
in some measure, does accompany every godly sorrow.
But, oh! there is much difference between a speculative notion hereof,
and having the reality of the thing made out in experience unto the heart; so that now,
not only can it hate sin _in others,_ and, it may be, too severely censure them for it,
but doth find _the idol itself_ in its nature restrained,
so as with real indignation to say, as Ephraim, Hos. 14:8,
"`What have I to do any more with idols,`" and then,
to cast them "`to the moles and to the bats.`"

One good lesson the Lord offers to teach us, by the exercise of bearing the cross,
is,--__how rightly to value and think of the bitter sufferings and death of Christ.__
If there be so much as we conceive of bitterness, and that which is unpleasing to us,
in _our_ petty sufferings, what was there in the sufferings of _Him,_
who endured the Father`'s wrath for our sakes.
But, this not being my purpose to insist on here,
I shall leave the enlarging of it to every heart,
as the Lord shall be pleased to _enlarge them,_ in their meditation of it.
Only, because, in experience, I have found the truth of one observation relating thereto,
let me shortly give it.

Much of the cause, why many godly persons,
who meditate and think much on the death of Christ,
yet find very little right and true advantage by so doing,
may be,--that the thing mainly looked at,
is the tragical story of his death and sufferings.
This is the chief use which the Papists, and many carnal Protestants also,
make of Christ`'s sufferings,
to meditate and set out to themselves _the grievousness of them,_
so to move their hearts to a relenting and compassion to him,
and indignation against the Jews for their crucifying of him;
with an admiring of his incomparable love.
And to get the heart thus affected, is by many _counted to be grace;_ whereas,
it is no more than what the like tragical story of
some great and noble personage will work,
and useth ordinarily so to do in ingenuous spirits, who read or hear of it,--yea,
and that, oftentimes, though it be but in a way of fiction.
This, when it reacheth _no higher,_ is so far from being _faith,_
or a thing any-wise acceptable in God`'s sight, is but _carnal and fleshly devotion,_
springing from fancy, which is pleased with such a story.
Such stories use to stir up principles of humanity in men unto compassionate love,
which Christ himself, at his sufferings, found fault with,
as being not spiritual nor raised enough, in those women,
who went weeping to see him so handled: "`Weep not for me,`" says he; that is,
"`Weep not so much for this, to see me so unworthily handled by these for whom I die.`"
But then, if it be inquired, _What is it in Christ`'s passion,
that should be most minded and looked to?_
Answer.
The chief and main thing to be looked unto,
when the heart would rightly view and meditate on the sufferings of Christ, is, the end,
meaning, and intent of God, and of Christ himself in his sufferings.
It is the right consideration of this, _eyed by faith,_
which draws the heart to rest on Christ; when it perceives,
that _his_ aim and end in suffering for poor sinners,
so fully answers to what is its aim and desire,--to wit, that sinners might be saved.
When it perceives, that Christ`'s heart was as full in this, to _procure_ it,
as the sinner`'s heart _can_ be to _desire_ it.
This consideration, borne home on the soul, draws it to Christ, _to rest on him;_
which all the considerations else,
let the heart be as much enlarged and taken with them as may be, can never do; they,
being but fruits of the flesh, can never produce so high an end.
And the like may be said of human inventions, as crucifixes,
lively representations of the passion of Christ, unto the sight of fancy,
do exceedingly provoke men to such devotional meditations and affections.
But, all they work is an historical faith, only an historical love and remembrance;
and no other than such effects are produced in many,
by reading the history of the Bible,--even in many,
who are yet much against such crucifixes, etc.
But, as God looks principally _at the meaning of the Spirit in prayer,_ Rom.
viii., so doth faith look principally to _the meaning of Christ in his sufferings._
And as, in all other truths, a believer is said to have the mind of Christ, (1 Cor. 2:16)
so especially,
he minds what was _the mind and heart of Christ in all his sufferings;_ for,
it is _that in them which answers to his aim and purpose,_ namely,
a desire to be saved from sin and judgment; and, to effectuate this,
was the very aim and end of God in sending Christ,
and of Christ in suffering so cheerfully.
+++[+++See <<note-Z-diary,Appendix, Z.>>]

Another lesson, which ordinarily the Lord useth to teach his children,
by exercising them with the cross,
is,--that thereby they may be learning _more soberly to think of,
and less to engage their hearts unto, the things of a present world:_ so,
commonly it falls out, that every rose we taste of here,
has a thorn and prick under the leaf of it.
And therefore, if, in every comfort of this kind that thou enjoyest here,
there be some mixture of bitterness, some water amongst thy wine; mistake not,
but look on it as proceeding from the wisdom and love of God to thee, thereby,
not only to let thee see by speculation, but find from experience,
how vain and empty the things of a present world are.
So found he, that had the largest experience of them, Solomon, Eccles. 1. etc.
and from this, he is drawn to a good conclusion, 12:13.
Let us therefore consider the whole matter:--"`fear God and keep his commandments,
for this is the whole duty of man.`"

Again, the exercise of the cross serves much for the _increase and exercise of grace._
Rom. 5:3, "`Tribulation works patience,`" etc.; and therefore says the Prophet,
"`It is good for a man that he bear the yoke in his youth.`" Lam. 3:27.
The Psalmist found it so. 119:67,
"`Before I was afflicted I went astray, but now have I kept thy word.`"
In Heb. 12:11, there is a remarkable expression respecting chastisements,
or bearing the cross:--"`No chastisement for the present seemeth to be joyous,
but grievous,
afterward it brings forth the peaceable fruit of
righteousness to them that are exercised thereby.`"
Observe the word _exercised;_
the cross affords fruit to none but to them that are exercised thereby, that is,
whose daily exercise it is, to be under the cross.
They that make the patient bearing of the cross their daily exercise, shall, doubtless,
find grace much exercised and growing thereby.

But one might ask me, What I mean by the cross?--as sometimes my own heart did.
Having considered, that the cross was not only of so much use and advantage,
but so necessary to Christians, as that,
without walking in this way of the cross after Christ, they could not come to the crown;
I was sometimes putting this query to myself, What cross was I under?
And indeed, it seemed to me, I was under none,--having abundance of all earthly comforts;
and though not in such measure as covetous hearts desire,
yet I thought myself the more free of the cross in
this,--that I was satisfied with what I had,
as not being much troubled with sickness, nor with poverty,
nor with want of contentment in my wife, or children, or sisters, etc.
And thus, it did not appear to me, what cross I was under, or how exercised thereby.
I was sometimes not far from concluding my state to be, on this account,
_very dangerous;_--for God deals so, not with sons, but with bastards, Heb. 12:7-8.
The thoughts following occurred to me thereon.

First, that a believer may be much exercised, though he be under no such dispensation,
as, to the world`'s eye, may appear a cross; yet may he be, in Christ`'s account,
taking up his cross daily, when he is _preparing for it._
So is it well said to this purport,
_That a Christian is always a martyr in action or in affection;_ that is,
either actually under the cross, or preparing his affections so to frame with the cross,
that he may contentedly undergo it,
when it comes.--The consideration of that Scripture,--Job 3:25,
"`The thing that I greatly feared is come upon me,
and that which I was afraid of is come unto me,`"--afforded some help +++[+++on this point.]
I considered, it is a duty for a believer, that would not be surprised with the cross,
when he is enjoying earthly comforts in the largest measure,
(as who could have them more than Job had,) then to be supposing that the time may come,
wherein he may want all these things; and not only so,
but the contrary evils ought to be provided for.
So, it is evident, Job was doing;
not only forecasting the want of what he was then enjoying,
but greatly fearing the very height of that extremity to which he was reduced.
This, rightly dwelt upon, may serve very much for the humbling of our hearts,
who are so exceedingly short in such duties; and should make us also clearly see,
why the cross is so scared at, and so impatiently borne, when it comes.
We habituate not ourselves to serious thoughts of it,
so are we surprised and confounded when it comes.
But, happy is that man, who is daily habituating himself to such foresight; and,
for the making of his purpose the more effectual,
is sometimes _abridging himself of the utmost extent
to which he might go_ in the use of lawful pleasures;
knowing that, without this, it is not possible he can escape _going beyond bounds._
Add further, he will sometimes, for a season,
deny himself the satisfaction of such a lawful comfort,
wholly secluding himself from any use of it;
being very sensible of the goodness of God in permitting him the use of it,
yet he keeps it as it were _without doors,_ that he may keep Christ the closer _within._
Not as though Christ and this lawful pleasure,
might not be both enjoyed together;--for he gives us large allowance even in these things,
(see Neh. 8:10) and, as is there signified,
the comfortable use of them is sometimes much for the advantage of believers;
but,--in order to the preparing his heart to live
without all these things,--is he _often denying himself,
and forecasting +++[+++the loss of them,]_
especially of those which he finds his heart to dote upon,
or where he has cause to fear this.

Another way whereby a believer may be exercised in bearing the cross daily,
though actually he be under no visible cross for the present,
is,_--when he rightly reflects upon past corrections and warnings,_
how he hath sometimes _mistaken_ what such a dispensation did _speak_ to him.
It may be, when he considers of it again,
with all the observable circumstances both of mercy and judgment,
he shall _now_ find the mind of God more clearly made known to him +++[+++in it,]
and much matter of humiliation for his dulness, sloth,
and negligence;--also much occasion to admire God`'s goodness,
who yet continues to spare him, notwithstanding his so frequent mistaking,
and so unanswerable walking to these dispensations.
For when the Lord points at some fault, which he wills thee to amend;
and advertises thee of this,
by some messenger of peace,--some act of mercy and goodness beyond thy expectation,
or some messenger of his anger,--the voice of his rod, which speaks to the man of wisdom,
Mic. 6:9; I say,--when thou considerest, that thus the Lord deals with thee; and yet,
thou seest not, or mindest not,--this is no small aggravation of sin.
And what matter of praise and admiration will be here,--that
thou hast yet an opportunity offered thee to mend!
When the heart is enlarged to this purpose by the hand of God,
there will be matter of sanctified exercise, which Christ will as acceptably account of,
as bearing any cross whatsoever.

A third, and special way, in which a gracious heart,
that has no external want or cross upon him,
may yet be daily under sad and heavy exercise of the cross,
+++[+++is this.]--Suppose thy condition be such,
as that thou enjoyest all earthly things at thy will; yet, as the Apostle says,
1 Cor. 15:19, "`If in this life only we have hope in Christ,
of all men we are most miserable,`" so, I may say,
if thou be satisfied with what thou hast of these things, sad is thy cross,
though thou knowest it not.
But, I suppose, thou be one of those,
that count the enjoying of a blink of Christ`'s face worth all these things,
and his withdrawing or hiding of himself but a little,
to be a more sad affliction to thee than the want
of any of these things could possibly be.
If Abraham could say, Gen. 15:2, that while he wanted a child,
he counted little else that God could give him; how much more mayst _thou_ say so,
if thou go Christ-less, _what hast thou?_
+++[+++Here some parts of the manuscript are omitted,
being chiefly reflections on Rom. 7:24, and an allusion to the case of Hezekiah, 2 Chron. 32:26.
]

The 24th day of February, 1657, I was advertised by my wife,
of a sore and sudden illness that had overtaken my child Andrew;
the like unto which had formerly overtaken my daughter Margaret,
of which she died unexpectedly in two days`' sickness.
This circumstance did affright her sore, and make her apprehend danger of present death;
yet the Lord was pleased, the next morning,
to refresh me with good news of the child`'s being better:--I,
having sought it of the Lord,
_must_ acknowledge it a new mercy and return of prayer.--Upon the consideration of it,
I conceive myself obliged to endeavour, for myself and my wife,
to have our hearts more loosened from our misplaced affection to that child in particular;
so that, if the Lord shall remove him, we may with contentment submit;--which,
for the present, I clearly perceive,
neither I nor she are so well fitted for as we should be.
Also further--to consider more, what the meaning of that Scripture is, Jer. 10:24,
"`O Lord, correct me, but with judgment, not in thine anger,
lest thou bring me to nothing.`"

Having for many days put up some desires to the Lord, on behalf of his people and work,
I was this day, 10th of April, 1657, convinced,
that my way was but very slight and formal;
and that the consideration of the work of God, and his people`'s condition at this time,
hath been but very superficially looked on by me.
Therefore was I some way desirous, to be humbled before the Lord for my former neglect,
and my not observing what the Lord is about, in these times;
and what he is so wonderfully working, by such contrary means to those we had proposed,
as the way for carrying on his work.
That Scripture came to my mind, Jer. 45:2 to 5. May not the Lord be said,
in these days, to be _breaking down_ what formerly he had _builded,_
and _plucking up_ what he had _planted;_ and yet, for the most part,
how senseless are his people!
But let my thoughts be confined rather to _myself;_ for,
if I may presume to be counted among the Lord`'s people, sure I am, there hath been none,
who hath had any measure of light or impression from the Lord of these things,
that have proved more lifeless, formal, and negligent,
as to a right minding of the concernment of the Lord and his people.
What a sad matter is it, for the Lord`'s people, in such a time,
not only to be in darkness as to their duty, but so far deserted,
as they have been for a long time,
and unfitted to carry on _what remains to be done of the Lord`'s work,_
that they are generally _inclining to sit down and be satisfied with what they have._
Yea, (which is worse,--if worse may be,) are there not many of the servants of Christ,
who hath been eminently carried forth to be glorious instruments
in bringing forward the work to this length;
but who are clearly turning back again,
and ready to sit down upon the things of a present world,
so as to be in hazard of being bewitched by these?--or, if not,
are they not generally seeking to sit down upon _the dawnings_ +++[+++only,]
of the morning light?
While as, Jesus Christ, like the sun in his brightness, is mounting up,
and calling them to _follow on,
unto the perfect day;_--until his enemies be altogether made his footstool,
_and the earth be filled with the glory of the Lord,_
as is promised in Numbers 14:21. Yea,
(which is yet more sad,--if any thing can so be said to be,) does
not _this_ appear very dreadful in their condition?--that,
while many of them are thus deserted, _others,_ who profess they would be _furtherwards,_
in carrying on what remains to be done, are +++[+++themselves]
so deserted and forsaken of the Lord,
(as to the knowledge of his mind about the right
way of prosecuting what may be their duty,
and that which they would so far be about,)--that they are +++[+++even]
in close opposition and contrary terms one to another,
bitterly persecuting and like to beat one another.
And yet, their contending is about trifles, or matters disputable,--matters in which,
though they differed, they might well allow charity one to another,
and sweetly carry on the work together,
but that the Spirit of the Lord is departed from them:--__this__
is a circumstance aggravating their distraction,
and the miserable evils of it; so that it may be said,
"`The princes of Zoan are become fools,`" Isa.
19:13;--but the sun is gone down over the prophets,
and the day is dark unto them. Micah 3:6.

Yet, in this sad apprehension of the present condition of things,
there was matter for me to be comforted, +++[+++even]
in this,--that, out of such darkness, our Lord can bring light; and not only that he _can,_
but also _that he will do it._
And though this dark,
deserted condition doth speak out much cause for lamentation and woe unto us;
because of the influence, which, doubtless,
our sins have had in occasioning this,--(and well
were it for that man who is rightly affected,
laying it to heart;) yet all this, ought not to lead to the discouragement of any,
or the fainting of their confidence __in the truth of what is promised--__that
Jerusalem shall be made the praise of the earth,
and that this is the time when the Lord is about to do it.
Yea,--(which is observable, if I mistake not the Scriptures,)--this,
the deserted and dark condition of the godly, may be warrantably a ground,
on which they may conclude, the time of their deliverance and redemption draws near.
So Christ saith, Luke, chap.
xxi. "`When these things begin to come to pass, then look up and lift up your heads,
for your redemption draweth near.`"
Consider, when shall this be?--in verse 24th, it is said,
when the times of the Gentiles shall be fulfilled, then Jerusalem shall be delivered.
And what are the signs accompanying these times?--"`perplexity and distress
of nations,`" and "`men`'s hearts failing them for fear,
and for looking after those things which are coming on the earth,`" etc.
The Prophet Zechariah 14:6, speaking of this time,
tells plainly,--that it shall be a time of strong confusion, neither light nor dark;
and that the expected light shall not come _until the evening,_--even _then,_
when people are giving over hope of light, and expecting nothing but more darkness.
_Then_ will _the living waters go out from Jerusalem,_
and _then_ will "`the Lord be King over all the earth;`" _then_ will "`there be but one Lord,
and his name one.`"
_Then_ will he "`turn to the people _a pure language,_ that they may _all call upon his name,_
to serve him _with one consent._`" Zeph. 3:9.

The Lord`'s people should therefore be laboring to stay and establish their hearts,
not to be shaken in their confidence of the truth of the promises of his coming;--for,
lo!
He comes, _with power and great glory._ Matt. 24:30.
--"`But who may _abide_ the day of his coming?`" Mal. 3:2.
--They should labor, so to be established in the faith of his promises,
as not to be shaken at what has already, or may as yet come,
of a day of darkness and desertion.
Is there not also warrant for them, to be waiting for _a dreadful time of suffering,_
with which they may be tried?--as the Scriptures
do very plentifully hold forth,--in which Satan,
having transformed himself into an angel of light, shall so far prevail, that,
if it were possible, he should deceive the very elect.
This day, as it hath, in a great measure, already come on us in this generation;
yet not so, but that more, and much more of this kind, may be our lot to be tried with.
It appears very evident from the Holy Scriptures, Isa. 1:25 and iv.
4, that before _that great and glorious appearing of Christ,_
the dross and tin of his people must be purely purged away by the
spirit of judgment and of burning,--a day of such trouble,
says Daniel 12:1, "`as never was,`"_--such a day must there be,_
before The Lord`'s People "`shall be delivered;`" such a day,
wherein _two parts_ shall be cut off and die,
and _a third part_ shall be saved "`through the fire,`" +++[+++after]
being "`refined`" and "`tried`" as "`silver`" and as "`gold.`"

O! that, by the consideration of these things, I might stir up my own heart,
so to labor to be rooted and grounded in the love of the truth,
and knowledge of the gospel of Christ; that no temptation on the one hand,
or on the other, should shake me, in those dreadful, shaking, and trying times,
when the Lord is about _the searching "`Jerusalem with candles.`"_ Zeph. 1:12.
This search is there said to be,
for the punishment of those that are settled on their lees._--Lord! save me from settling,
either in a lifeless form of religion, without the power thereof,
or in any bait or temptation that may arise from the allurements of a present world;
that I may, by grace, be saved from the errors of the times,
to which so many are given up, to the dreadful offence and scandal of the gospel!_
So also, I pray, that the Lord, of his goodness and free grace,
would save me from _resisting_ or _refusing to receive light,
when it does proceed from Himself,_ who is the _Fountain of light and life;_ +++[+++especially]
when He is about these glorious manifestations and discoveries of himself,
which shall _consume the man of sin,_ even with the brightness of his coming,
2 Thess. 2:3 and 8,--and +++[+++which shall also]
make _his own_ shine more brightly than the sun in the firmament,
through the abounding measure of the graces of his Spirit in them.
See Dan. 12:3, and Isa. 30:26. _Then_ shall a little one be like David,
and the house of David like the angel of God. Zech. 12:8.
How far are the _least_ of the saints from having attained to this pitch!
and yet no less than this ought to be in their eye and aim;--the kingdom of Christ,
which by himself we are taught daily to pray that it may come, will produce no less.
But _how_ far are we +++[+++the religious professors of this day]
from it! and _how much_ may we, in all appearance, be likely to suffer,
before _our dross and tin_ be taken away,
that we may be accounted worthy to win "`places`" among the number of those that shall
get leave to "`stand by;`" +++[+++according to that place in Zech. 3:4,7. "`Behold,
I have caused thine iniquity to pass from thee.`"
"`If thou wilt walk in my ways, and if thou wilt keep my charge,
then thou shalt also judge my house, and shalt also keep my courts,
and I will give thee places to walk among these that stand by.`"]
