== Chapter VI.

[.chapter-synopsis]
* Alexander Jaffray commemorates the providential kindness of the Lord to his family
* His views and resolutions at this period with regard to prayer, etc.
* Some reflections on "`Having a name to live,`" and on "`Strengthening the things that remain,`" etc.
* On being "`sober, and watching unto prayer.`"

This day, I had been labouring to remember with thankfulness,
the kindness of the Lord to my family; and, in particular,
his sweet providence towards us in our journey here, and since we came here; and now,
of late, that he hath brought our youngest child, John, safely to us.
This was a mercy, which I had divers times sought of the Lord; and which, now and ever,
I desire to remember with all thankfulness, as the fruit and answer of prayer.
My desire was also to the Lord,
that he would save me from letting these my dear children,
or any thing else of my enjoyments, get too much room in my heart.
I also sought of the Lord, that my wife`'s condition, at this time of her delivery,
may be remembered; and that the neglect of former deliverances,
at such times of strait both to her and me, may not now be remembered +++[+++against us;]
but that we may be helped to remember with much thankfulness these straits and difficulties,
with the out-gets we then had, and the vows and promises we then made;
hoping that the Lord will yet be gracious,
and even particularly at this time will spare and pity her,
and give us once more occasion to praise his name!

The 11th day, being Saturday,
I had been some time of the afternoon until six o`'clock at the fields: when I came in,
I intended to have taken up the rest of that evening with prayer and meditation,
in reference to a better preparation for the sabbath.
Yet was I entangled with some worldly business, of no necessary or present use,
but which might have been very well done at another time, without any loss or danger.
A little before eight o`'clock, _I set myself to prayer;_ but, owing to a loose,
roving heart, distracted with worldly business, not a word could I get expressed.
Here, I began to consider the language of this dispensation,
to speak no less than a sad check and challenge for my former laziness and negligence,
in not stirring up myself with delight to be about these holy duties of prayer and meditation.
And having thought a little on this point,--not only in relation to some
more time to be hereafter spent for preparation against the sabbath;
but also in relation to all my exercises in divine worship,
both on sabbath and other days,--I found, upon a more exact examination of my way,
both in private when I am alone, and more publicly when I am with my family,
and elsewhere in the assemblies for public worship,--there was much matter
of humiliation for many things both wanting and wrong in these duties,
which, by the grace of the Lord and in his strength, I intend to amend.

[.numbered-group]
====

[.numbered]
_First,_ In the morning, I resolve to labor, when with convenience I can,
_to have some time before private prayer,_
for reading some portion of Scripture and meditation thereon,
as relating not only to my own private case, but to the condition and case of my family;
so that I may be fitted to pray for and with them,
and also to exhort and edify them from the words, as all, or any of them,
shall be observed to stand most in need; not doubting,
but I shall find it a way profitable both for them and me, and blessed of God.
And not only to read Scripture with them; but some time, if conveniently it may be had,
every day, to interrogate the meaning of such a place,
or what any of them could observe from it.
By this means there may be good occasion had,
not only to acquaint myself and them with the history of the Bible;
but of catechising them, and of commending any virtue or reproving any vice,
of which they may stand in need.

[.numbered]
_Secondly,_ To labor to watch more over my heart _in time of prayer,_
either private or more public, against wandering and vain thoughts; which,
as at all times they are wrong and sinful, so more especially then. Ecc. 5:1.
"`Keep thy foot;`"--by foot there, is meant the affections, which,
as they are _at all times_ to be kept, so _especially,_ says the Spirit, _there,_
"`when thou goest to the house of God;`" and, verse 2, there is a notable reason added,
why it should be thus,--which, were it well observed,
might be a good means for keeping the heart right in time of prayer,--"`God is in heaven,
and thou upon earth; therefore let thy words be few.`"
If the majesty of God, to whom we speak, were considered, it might help us much,
not only against _sinful speaking,_ but _sinful thinking_ also,
as the Spirit there clearly intimates.

[.numbered]
_Thirdly,_ That the heart may be the better helped to be watchful in prayer,
I find it necessary,
to be more watchful _between the times of approaching to God_ by prayer; being convinced,
that in this duty I am more wanting, and have more frequently failed,
than in any thing else; yea, I conceive,
my failing in everything else is mostly owing to this,--that
I have not actively bestirred myself up,
in the strength of Christ, to be more in this duty of _watching._
The Lord help me, therefore,
to think of the absolute necessity and great advantage of prosecuting,
by the strength of Christ,
a more diligent and close way of watching over my heart! for without so doing,
there is _no hope of making further progress_ in the ways of Christ,
nor any quenching of the fiery darts and buffetings of Satan,
wherewith I am so frequently and furiously assaulted.

====

While I was thinking on these things, two Scriptures occurred to my thoughts; the one,
affording motives and pressing arguments persuading to the duty; the other,
offering a notable means, teaching how it may be done.
The first Scripture was, Rev. 3:1-3. "`These things, saith He,
that hath the seven Spirits of God, and the seven stars.`"
Observe, it is _Christ_ that is the speaker, and it is to the _lively-like,_
but _dead_ creature.
O how lively a description of _me!_ and how dreadful a guiltiness is it,
to have _much in appearance before men,_ when in the sight of God;
there is nothing but _deadness at the heart!_
And what is it, that Christ saith to such a soul, what bids he it do,
for the remedy of its dead condition?
"`Be watchful`"--__there__ is the duty; and the effect of it shall be,
that _the things which remain,_ which yet are not _fully dead,_
but _ready to die,_--these shall be strengthened.
O what a speaking Scripture unto my condition; who, through unwatchfulness,
have sensibly lost much,
and the sin and corruption of my nature become stronger exceedingly!
Yet,--glory to the Lord Jesus!--who tells me,
by his Spirit bearing witness to mine in these Scriptures,
that there is yet some little life which remains, not yet dead; and that, by grace,
through watching, it may be strengthened.
In verse 3, motives inducing to watchfulness are offered:--First,
_"`Remember how thou hast received,`"_ Second, _"`How thou hast heard,`"_ Third,
_"`Holdfast,`"_ and Fourth, _"`Repent`"_ The duty of watchfulness, is of difficult,
yet most necessary use; and therefore the Spirit presseth it much.
Mark 14:38, Christ appoints +++[+++his disciples]
to watch and pray, as if it were _the only means_ to prevent temptations; and in chap.
xiii.
ver. 37, as if he were to leave _no other_ direction to any or all of his disciples,
he saith, "`What I say to you, I say to you all, Watch.`"

Now, the means whereby one may best attain to know the worth of this duty,
and how to perform it, is, first,
by remembering "`how thou hast received,`" etc. says the text.
It will prove a notable means to help us to keep what we have, if we consider rightly,
_what_ it is that we have, and _how_ we have received it.

What is it that a believer hath, that he must so carefully watch over?
In verse 11 of the said chapter of Revelation,
it is called _a crown._--"`Hold fast that which thou hast, let no man take thy crown.`"
Crowns are thought to be things of most worth and account among men: and _therefore,_
grace is compared to a crown.
How careful are men to get, and to keep a crown, when they have it.
Yet what sorrow and vexation does many times accompany them; and, at the best,
they are but perishing and transitory things.
But, there is no such inconvenience accompanying _this_ crown,--"`it is a crown
of life,`" and lasts forever:--therefore _make much of it,_
and _keep it well_--therefore, "`watch.`"
The thing we have to keep, and for which we are to watch,
is of infinite worth,--beyond all the crowns of the world; yea,
beyond the worth of earth and heaven too; yea,
infinitely beyond the worth of all the things imaginable--is _communion with God._
"`My Beloved is _mine,_ and I am _his,_`" saith the spouse. Song. 2:16.
Jesus Christ is _ours:_--O, what a treasure!
The Apostle reasons to this purpose, and concludes sweetly,
1 Cor. 3:21-23,--"`All things are yours; ye are Christ`'s, and Christ is God`'s.`"

Yea, the Holy Ghost is also ours and dwells in us,
1 Cor. 3:16-17,--"`Know ye not that ye are the temple of God,
and that the Spirit of God dwelleth in you?
If any man defile the temple of God, him will God destroy; for the temple of God is holy,
which temple ye are;`" and in chap.
vi. 19, 20, "`What?
know ye not that your body is the temple of the Holy Ghost which is in you,
which ye have of God, and ye are not your own?
For ye are bought with a price: therefore, glorify God in your body, and in your spirit,
which are God`'s.`" What strong language is there here!
The Holy Ghost is in you, your body is his temple, therefore glorify God in your body.
Have ye got so honourable a guest in your house,
will ye not watch diligently to keep him well.
+++[+++see <<note-AA-diary,Appendix, AA.>>]
See in Canticles. 2:7, how the soul that has gotten him,
will be careful to keep him; and again, chap.
viii.
4,--"`I charge you,--that ye stir not up nor awake my Love, until he please.`"
This charge is again repeated in chap.
Hi. 5, and in verse 7 and 8; because of fear in the night,
lest any thing should disturb him, she sets a strict watch,
_sixty valiant men about his bed, expert in war, holding swords on their thigh._
What watchfulness is there here!
No less will be _thy_ care and diligence,
to watch against everything that may displease him,
or interrupt his remaining and resting with thee,
if thou hast indeed received him and knowest his worth.
Not knowing the excellent worth of Jesus, and his precious company,
makes us to be so little watchful over our hearts,
in entertaining every motion of his Spirit, and stirring up ourselves thereto, and,
avoiding every "`appearance of evil,`" 1 Thess. 5:22. What
evils may be thought of less importance than a look or a thought,
when it is not consented to; yet these, if thou be not humbled for them,
much more if given way to, are a letting down of thy watch,
and may deprive thee of communion with Christ.
For, Matt. 5:28, a light look of the eye, if not carefully watched over, may,
in the sight of Christ, become adultery; and therefore, that prudent and precious man,
Job 31:1, that he might not think a wrong thought, resolves not to look a wrong look;
he knew how the one draws on the other,
and that both of them were sinful in the sight of God.
And doubtless thou dost so, if thou knowest what it is,
to keep up a watch for entertaining of Christ; and, on the contrary,
if thou canst dispense with thyself in these or the like things, thou knowest him not,
nor the worth of his company,--thou dost not watch,
live otherwise how blamelessly and diligently, in the practice of religious duties,
thou wilt.

Consider, further, _how thou got this_ that thou hast;
and this may very much stir up the heart to attention and watchfulness.
Thou hast received it very freely,--never was there so free a gift as grace is.
The Spirit of God by the Prophet Ezekiel, chap.
xvi. sets this very notably forth under the type of a wretched infant,
lying in the open fields in its blood, etc.
Consider, then, how freely, how fully, he hath given to thee.
These points are of great importance, and may be largely extended in meditation.
How exceedingly is the love of God commended to us,
from the consideration of the _freedom_ of it.
Rom. 5:10-9, "`For if, when we were enemies,
we were reconciled to God by the death of his Son; much more, being reconciled,
we shall be saved by his life.`"
Then consider also, how _fully_ thou hast received, John 1:16,
"`Of his fulness have we all received, and grace for grace.`"
In thy proportion, thou hast received some measure of every grace,
that Christ received without measure, and these he augments and perfects by his presence;
and wilt thou not therefore watch to make him welcome?
In Col. 2:10, we are said to be _complete in him;_ and how does Christ, John 15:11.
and xvi.
24, press his disciples to ask of him, that their joy may be full.
If thou hast Christ as thy portion, mayst thou not say with the Prophet, Ps. 16:6,
that the lines are fallen to thee in pleasant places,
and that thou hast a goodly heritage?
How do men ordinarily contend for their heritage!--contend for keeping Christ,
by watching over thy heart,--__diligently keep it__ +++[+++even]
_with all keeping._ Prov. 4:23.

The other Scripture, which was offered to my thoughts,
as one holding forth a notable means to help us in the duty of watchfulness was,
1 Peter 4:7, "`But the end of all things is at hand; be ye therefore sober,
and watch unto prayer.`"

There are three things in these words,
the right consideration of which may very much help us, in setting up,
and keeping up a daily watch over our hearts.
First, A right consideration of things present, and of things to come.
Secondly, Sobriety in the use of everything that we have, or may enjoy here.
And thirdly, A daily renewing of the act and exercise of watching,
with an eye unto prayer.

+++[+++After some reference had to that text, Eccl. 1:2, and i. 17, 18,
on the first of the above heads, the writer cites 1 John 2:15-16; then John 4:13-14;
then Isa. 64:4, as quoted by the Apostle Paul,
in 1 Cor. 2:9. Under the second head, the following sentences occur;
the rest being here omitted.]

A sentry may be very punctual in his duty, yet if he be not a sober man,
but one that is distempered in body by drunkenness, or in mind with giddiness,
frequently gives untimely and uncertain alarms.
And though he may discern the enemy and give warning of his coming,
yet falls not on the right way of resistance;
but instead of making him stand at a due distance, lets him come too near,
and falls a parleying with him; without calling his corporal,
whereby the main guard may be advertised, and so the whole city be put in arms.
And as in this case, the experience of a good soldier can well tell him,
there is nothing more dangerous for a place besieged, than such a sentry;
so _my_ experience does sadly give me to know,
that there is no case more dangerous for a besieged soul,
than watchfulness without sobriety.
And therefore, how fitly does the Apostle, 1 Peter 5:8, join them together, "`Be sober,
be vigilant:`" the reason he adds, is also very observable:--ye have a busy, subtle,
deceitful, and desperate enemy; therefore sobriety, as well as watchfulness,
will be needful for your watchman.
He puts sobriety also in the _first_ place +++_______+++.

The Apostle says, 1 Cor. 6:12, "`All things are lawful for me,
yet I will not come under the power of any:`"--beware, then, that +++[+++things lawful]
get not too much power to command over you, or to be looked on as absolutely necessary.
Consider; ye _may,_ yea, ye _must_ be without them;
and it will prove not a little for your advantage,
even while ye have them most at your command,
sometimes to be denying yourself the comfort of them,
the better to habituate yourself to live without them; seeing ye know, _ye_ may leave them,
or _they_ must leave you, before it be long.
+++[+++Here the writer briefly adverts to the snare which there may be, to some,
in the other extreme; and that such have need to mind the exhortation given to Timothy, 5:23.]
It is likely, Timothy, was in this respect to be admonished;
therefore the Apostle advises him to forbear drinking water,
and to take a little wine,--but it was for his "`often infirmities.`"
There may be not only a defect, but a sinful extremity and acting in these things,
which have but "`a show of wisdom in will-worship and humility,
and neglecting of the body.`" Col. 2:23.
But the other extremity is, sometimes,
a surprising temptation even to the godly.
Solomon, in the 23rd of Proverbs, having spoken of that abominable sin of drunkenness,
in verse 31, gives warning of the danger there is,
in giving way so far as with delight to look upon the good qualities of the wine, namely,
its motion and colour in the cup; intimating, that we may be allured to lust after it,
which, in Christ`'s account, is no less than the very acting of the sin itself;
see Matt. 5:28. O, what matter of humiliation and mourning,
may there arise from this consideration,
for by-gone guiltiness! what matter of sobriety and
watching unto prayer for the time to come!
How ignorant have I been of the wiles of the devil,
of his devices and methods in tempting! as the Apostle expresseth
it in 2 Cor. 2:11. --It is not merely _exorbitancy,_
or giving way to satisfy the several appetites in eating or drinking,
that is here spoken against, but everything of the like kind or nature,
wherein _the feeding,_ much more _the satisfying of the lust of the eye,
the lust of the flesh, or the pride of life,_ are given way to. 1 John 2:16.

There is, +++[+++however,]
a very large and comfortable portion, even of these outward enjoyments,
allowed unto the godly; "`all things are`" theirs, 1 Cor. 3:21, yea,
all these things _were made for them;_ but it is a mercy, above all this,
to know how rightly to enjoy _our portion in its place,_
which is mainly attained unto by a watchful, modest, and sober using of them.
But, many times,
for want of this excellent gift of sobriety in the using of our lawful comforts,
do we make our comforts to be blasted and cursed unto us:--so,
the Lord threateneth to do with his people, Mal. 2:2, to _curse_ their _blessings;_ yea,
he tells them, he had done it already,
because of their unwatchfulness in not laying his commandment to heart.
Doubtless, it is not only lawful,
for God`'s servants to have a lawful and liberal use of his best creatures;
but they have also the _best right_ to them.
"`The finest of the wheat,`" and "`honey out of the rock,`" which is the best,
was also their allowance.
But the believer knows well, what a snare many times he hath found in these things.
It is to guard against this, that they are called.
The Apostle Jude, in verse 12,
lays it as a great blot to the charge of _such as feed without fear._
Canst thou partake of these things at any time, (especially,
when the use of them is most liberally enjoyed,) without fear of a snare?
then doubtless thou art _in the snare,_ though thou knowest it not;
and the best way for thee to fear, and thus prevent the snare, is,
frequently to abridge thyself of that liberty thou mightst lawfully take; otherwise,
if thou dare go the utmost end of that which is lawful,
thou canst not miss going beyond it, before thou art aware.
The wise man, Prov. 28:14, saith, that he is happy who _feareth always._
What a dreadful snare found Noah, and also Lot, Gen.
ix. and xix, by their failing to observe this rule!
It is worthy our observation,
that though doubtless the apostles were moderate and very sober men,
yet Christ thought fit to warn them of the danger
of being overcome with _surfeiting_ and _drunkenness,_ Luke 21:34.
So liable are the best of men to miscarry,
if they watch not against the worst of sins.

To conclude this point, of sobriety in the use of lawful things,
I shall only mention that one Scripture, 1 Peter 2:11, "`Dearly beloved, I beseech you,
as strangers and pilgrims,
abstain from fleshly lusts;`"--and observe the reason the Apostle gives,
why this abstinence should be,--"`They war against your soul.`"
Any thing that the flesh or carnal appetite is fed with,
more than is necessary or convenient,
for the supplying of the body to the service of Christ,
may be here taken for a fleshly lust.
And Paul, in Rom. 8:13, calls them by another name, which, being considered of,
may give light to this:--"`The deeds of the body.`"

These inordinate appetites of the body, must be mortified by the Spirit.
By _walking in the Spirit,_ as we are exhorted, Gal. 5:16,
we shall be enabled _not to fulfill these lusts;_ which, if we do fulfill,
though we live in the body, we shall die in the Spirit; that is,
_the gifts and graces of the Spirit shall die and wither on our hand daily._
