== Chapter VII.

[.chapter-synopsis]
* 1657: Remarks relating to "`integrity, sobriety, and modesty in the use of spiritual gifts`"
* Thoughts on death
* The danger of murmuring when Mourning
* Alexander Jaffray sets apart a day for seeking God by fasting and prayer, on several accounts
* The birth of a son; His thoughts on that, and other mercies of a domestic nature
* His scruples as to "`baptizing`" his infant "`in the national way.`"

+++[+++Our Diarist next proceeds with the following remarks on "`integrity, sobriety,
and modesty of the mind, in the use of inward and spiritual gifts.`"]

"`As a man _thinketh in his heart,_ so is he,`" saith the wise man. Prov. 23:7.
Therefore are we commanded to "`keep the _heart_ with all diligence,
for out of it are the issues of life.`" Prov. 4:23.
And, if we would have an evidence, that we are serving God _as sons,_
we must then _give him the heart;_ Prov. 23:26, "`My son, give me thy heart,
and let thine eyes observe my ways;`"--as if there were no more required,
but the heart and the eye to be right.
How much account does God put upon the integrity
of an honest heart!--"`Behold an Israelite indeed,
in whom is no guile!`"
John 1:47:--such an one will get a _"`Behold`"_ put on him, _even from Christ._
Amaziah,
though he "`did that which was right in the sight
of the Lord,`" yet is he blotted for this,
that it was "`not with a perfect heart.`" 2 Chron. 25:2.
See a strong expression to this purpose,
Jer. 4:18,--"`Thy way and thy doings have procured these things unto thee;
this is thy wickedness, because it is bitter, because it _reacheth unto thy heart._`"
What duty, therefore, is there on us to be watchful, especially, _over the heart!_
Iniquity regarded _there,_ may make God not hear thy prayers, Ps. 66:18;
_a vain thought_ must not be allowed to lodge _there_ for a moment. Jer. 4:14.
Nothing does more evidence a man to be in a good condition,
as to the watching over his heart, than low and sober thoughts of himself,
especially when in any measure eminency of gifts and parts are attained unto.
See some Scriptures to this purpose, as Rom. 12:3, "`For I say,
through the grace given unto me, to every man that is among you,
not to think of himself more highly than he ought to think; but to think soberly,
according as God hath dealt to every man the measure of faith.`"
How true is that which the Apostle saith, 1 Cor. 8:1,
"`Knowledge puffeth up:`"--__they__ are in a good condition that can apply the next words,
in verse 2, as a pertinent check to their vain mind,
"`If any man think that he knoweth any thing,
he knoweth nothing yet as he ought to know.`"
"`For if a man think himself to be something, when he is nothing, he deceiveth himself.`" Gal. 6:3.
See the excellency of this frame of spirit notably set forth by David,
as being his own condition, Ps. 131:1-2, "`Lord, my heart is not haughty,
nor mine eyes lofty, neither do I exercise myself in great matters,
or in things too high for me,`" etc.
What a rare mercy, for _such_ a man, raised from such a low condition to so high a degree,
both in goods of the body and gifts of the mind,
and yet to set and behave himself so low as _a weaned
child!_ what a great evidence of a sincere heart,
and of a quiet and sober mind!

But I shall shortly speak a word to some particulars, which I have found,
both in practice and observation, in myself and others,
as to the exercise of this notable gift of sobriety,
evidenced by the modesty of the mind in the use of spiritual and inward gifts.--Commonly,
we have more in our account the _gifted_ man than the _gracious_ man; whereas,
he that cannot speak good sense, or six right words to purpose,
may yet have more grace and sincerity in the heart,
than he who can _talk like a parrot and pray like an angel._
For _such there are,_ and too sad experience, in these times, makes the truth of it appear,
without need of probation.
+++[+++see Appendix, BB.]
Even the gracious heart, (for want of such a proportion of humility,
as may keep him low in the exercise of these his excellent gifts,) may be so far deserted,
as not to see, that _these_ are withering and decaying daily,
nor are improved to the honour of his Master.
The evil of this judgment, the Lord, in much mercy to his faithful servants,
does many times prevent; by letting loose, either some bitter, persecuting enemy,
or some raging corruption, as a messenger of Satan,
to buffet them;--thus bringing and keeping them low.
Paul`'s experience, 2 Cor. 12:7, very fully warrants this point.
How was he, by such means, kept from a very dreadful evil,--even that of being,
through the abundance of revelations, exalted above measure!
Yea, how was he, notwithstanding all his great privileges and eminent parts,
brought to be _very low;_ and so kept there,
as that he dares not now glory in any such thing, but rather in his infirmities!
The considerations, which may conduce most for keeping low the heart of a believer,
eminently furnished with grace and gifts,
+++[+++are such as these,]--that he has nothing but what he has received,
1 Cor. 4:7,--that if he could attain to do all that he is commanded,
yet were he to look upon himself but as an unprofitable servant. Luke 17:10.

+++[+++And further,]
the humble believer is kept always very sober,
because he knows that he hath in him _the root of all evil;_ yea,
he finds the actings of this dreadful, and soul-humbling evil,
of _a body of sin and death,_ so abounding in him daily,
that were there no other consideration to keep him humble and sober all his days,
_this_ would do it.
No eminency of parts, nor degree or measure of grace,
is so attainable by the best of believers here,
but,--from the consideration of the being and lively stirrings of a body
of death within him,--he shall find _matter of much sobriety,_--yea,
_of being brought low and laid in the dust;_ so as to cry out with Paul,
that eminently furnished and gifted saint, Rom. 7:24,
"`O wretched man that I am! who shall deliver me from the body of this death?`"
+++[+++see Appendix, CC]

Again,
the heart of the believer,--being so very sensible of its vileness and loathsome nature,
and of the inexpressible holiness and glorious purity of the majesty of God,
"`who is of purer eyes`" than that he can "`behold evil`" or "`look
on iniquity,`" Heb. 1:13,--is rather taken up with admiration,
why he is not, for the defects and vileness of his best service, consumed.
A true sight of the majesty of the God whom we serve, would, doubtless,
put us so far out of the hazard of being vainly puffed up with any thing we have,
or can do; that, with the Prophet in the like case, Isa. 6:5,
having seen the Lord in his glory, "`high and lifted up,`" we should cry out,
"`Woe is me, for I am undone; because I am a man of unclean lips!`"
O, then, how may we wonder with David, Ps. 8:4,
that ever he should have _minded_ us! how much more,
that thus he should admit us in his presence,--yea, send messengers and ambassadors,
to _beseech_ us to be reconciled to him! 2 Cor. 5:20,--that
the majesty of so glorious a God,
who inhabiteth eternity, and fills heaven and earth, should yet profess,
that it is _his delight_ to hear the voice of such _a chattering crane!_
Canticles. 2:14, and Isa. 38:14,--that He, of whom it is said,
he "`humbleth himself to behold the things that are in heaven and in the
earth,`" who hath the heaven for his throne and the earth is but his footstool,
Isai.
lxvi.`"
I, whom the heaven and the heaven of heavens cannot contain,
1 Kings 8:27,--that He who made all these things, and even before he made them,
should have counted _his delights to be with the children of men!_ Prov. 8:31.
And yet _all this_ is but little,
in comparison of what he hath done to and for us.
"`For God SO Loved The World, _that he gave his only begotten Son,
that whosoever believeth in him should not perish,
but have everlasting life,_`" John 3:16. Here there is _such a SO,_
that neither angels nor men, nor all of them in heaven and earth together,
can imagine any thing comparable to it.
The angels, who are the quickest-sighted of any of God`'s creatures,
though they have been now beholding, for divers thousands of years,
this mystery of God`'s love manifested to lost man,
yet have they not _attained,_--nor ever shall they; for,
throughout all eternity it shall be _their exercise,_
to pry into and behold this mystery. 1 Peter 1:12.
As also they have it, in time,
more fully made out to them _by the dispensations of God_ to his church,
than formerly it hath been. Eph. 3:10.
I say, the right discovery,
but of a little of these things that are to be known of the glory of our God,
may serve to bring the creature _very low;_ and so to keep him, in a sober manner,
_at the use of his duty,_ without pride or ostentation,
though he had even attained to _angelical perfection_ in gifts and grace.
For, albeit, _they_ be very far beyond any thing we have, or can attain to;
yet they _stand amazed,_ and _cover their feet and faces_ too,
at the beholding of His excellent glory! Isa. 6:2.

Though the believer be very sensible of what he hath received, and be ready,
upon all occasions, to praise God for the least measure of what he hath,
either of grace or gifts,
knowing that it is purchased to him _only through the mediation of Jesus Christ;_
yet the consideration of _what he wants,_ keeps him very low.
If Paul, that chosen vessel, so eminently furnished for the work of God,
counted himself _not to have attained,_ but that it was his duty to strive hard after more,
Phil. 3:12-13, how much more matter hast _thou_ to be very humble,
even upon this account! thou art far short not only of what thou _shouldst,_
but of what thou _mightst_ have been at,
hadst thou been rightly improving the opportunities of grace thou hast had in thy offer.
Perfection, (I mean,
that measure of it which is attainable here.) is that which thou oughtst to be at,
and shouldst be striving for.
"`Be ye perfect, as your heavenly Father is perfect,`" Matt. 5:48; and,
2 Cor. 7:1,
"`Perfecting holiness in the fear of God;`"--__here__ is held forth the duty of our endeavour;
and that the will of God _may_ "`be done on earth,`" with
as cheerful willingness "`as it is in heaven,`" (that is,
in a good measure,
according to the capacity of our low condition,) is not doubted,--or
else our Lord would never have taught us daily to pray for it.
But,--have what measure thou wilt,--how far short
art thou both of gifts and grace! +++[+++see Appendix,
DD.]

Thus, +++[+++in order]
to be about thy duty, _be therefore sober, and humbly make use of what thou hast,
as the readiest way to come by more;_
for God "`gives grace to the humble,`" 1 Peter 5:5, and in Isa. 57:15, he says,
that he will "`revive the spirit of the humble.`"
Again, in the humiliating consideration of what we might have been,
had we rightly improved the opportunities put into our hands,
may we not take up that complaint against ourselves,
and justly find ourselves liable to censure for it, which the Apostle, Heb. 5:12,
hath against the Christians of those times,--"`For
when for the time ye ought to be teachers,
ye have need that one teach you again,
which be the first principles of the oracles of God.`"
How gross is our ignorance,
how little are our enjoyments in comparison of what they might have been,
had we been diligent seekers of and close walkers with God!
How might our knowledge have been increased as the morning light,
that shineth more and more unto the perfect day! Prov. 4:18.
But, as the Lord threatens to do to the wicked,
as a great judgment on them, that their knowledge shall be darkened,
when they have most to do with light, Prov. 24:20,
and Job 21:17;--see if the _godly_ may not be afraid, that, many times,
_their candle be blown out,_ and _they left in much darkness,_
because they have not _entertained and walked up to
the practice of the light which they had._
So then, our not improving the blessed opportunities we have had,
being the cause why we are so far short of what we might have been
at,--__this__ should make us rather mourn and be humbled for our shortcomings,
than any way puffed up with what we have.

Moreover, the believer knows well, that if he hath _much,_ he has _the more to do with it;_
Luke 12:48, "`For to whomsoever much is given, of him much will be required.`"
And not only so, but where _God gives much, Satan envies much._
He tempted the disciples of Christ _before_ their conversion, as he does _other_ men;
but _now_ Christ tells them, Luke 22:31, especially Peter,
that Satan desired to have him, that he might sift him as wheat.
When Joshua is before the angel of the Lord, about the putting off his filthy garments,
then Satan is nearest and most ready at his right hand to resist him, Zech. 3:1-3.
If there be a Job in the land, that hath more than all his neighbours,
so that there is none for grace and eminent parts like unto him;
if there be any possibility to find him in a snare,
how will Satan set hell on work to find it out.
I say, nothing may prove more effectual for keeping humble the holy heart,
than a due consideration of watchful diligence of so powerful and desperate an enemy;
whose malice and diligence they know well to be much against them,--therefore
are they much in the exercise of these duties of _sobriety_ and _watchfulness._

The believer considers duly,
how great offence his miscarriage would give:--"`If the light that is in thee be darkness,
how great is that darkness!`" Matt. 6:23.
How does the Lord by the Prophet Nathan, 2 Sam. 12:8 and 14,
+++[+++adjudge or enhance]
the sin of David?`"
I gave thee thy master`'s house, and thy master`'s wives into thy bosom,
and gave thee the house of Israel and of Judah; and if that had been too little,
I would moreover have given unto thee such and such things.`"--Hast thou gotten much?
Guide it well; else, the miscarriage of it,
will be a sad ingredient in the bitter cup of thy just and severe censure from the Lord.
O,
the fear of giving occasion to the enemies of the
Lord to blaspheme! how powerful a means may it be,
to keep a humble heart in a constant, sober frame; seeing they know,
that _at no passage_ can Satan have _more easy entry_ to the heart,
than _by opening this backdoor of vain glory._
Solomon also, who, as to great and eminent parts,
was beyond all that went before or hath come after him,--how was he assaulted, and,
nevertheless of all his large and great endowments,
was prevailed over! may this give matter of _fear_ and _trembling_ to every one,
especially to _the ablest and best-gifted believers._
1 Kings 11:1-3, etc.
But observe, from verse 9, how his guiltiness is +++[+++adjudged or enhanced]
from this--that he had _turned from the Lord, who had appeared unto him twice;_
God`'s appearing to him, and appearing to him twice, is by the Spirit observed, as that,
which should have had the _more_ obligation to him to sobriety and watchfulness.
The humble believer, however large his endowments may be, yet knowing well,
that it is not against flesh and blood that we wrestle,
but against principalities and powers, against rulers of the darkness of this world,
and spiritual wickedness in high places--I say, knowing this his enemy,
he knows well also, that though he have on the whole armour of God,
he will find work enough to withstand in the evil day; and having done all that he can,
he will find no small difficulty to be kept from fleeing,
and turning his back upon Christ;--for so much is imported in the words,
"`And having _done all_ to __stand.__`"
See Eph. 6:10 to 13. Wherefore, remembering the exhortation of the Apostle,
1 Cor. 10:12, he makes it his daily work, though he know that he stands,
to be taking heed lest he fall.

There is another thing, which is an evil too frequent and common, even to good men,
by which is evidenced very much the want of this excellent gift of sobriety; namely,
When a good man, who, formerly, both for eminency of grace and parts,
hath been deservedly much in account and estimation with
all men,--when such a man begins to find himself to be undervalued,
and others, who some time were far _below_ him,
now to be preferred _before_ him,--this is not ordinarily found, by the best of men,
easy to be borne; and yet this excellent gift of sobriety, were it well learned,
might very much help, _sweetly and contentedly to go under it._
Take two or three considerations, which may help to a quiet,
sober submitting in this or the like case.

Let the gracious heart soberly consider,
if there may not be good cause why their estimation,
purchased upon the account of the eminency of their parts, may not _justly_ be denied them;
the Lord, who _gave_ these things, having, for causes known to _himself,_
and it may be also to _thee, withdrawn_ them again,
how darest thou complain?--rather sit down, and admire and praise him for his goodness,
that he has not taken away gifts and grace too.
I confess, there may be much offence and too just cause for it,
from the imprudent carriage of many godly persons,
who know not rightly how to demean themselves in such a case; not considering,
that they stand still obliged, where God continues _grace_ and _honesty,_
there to continue due _respect_ and _regard_ to the _person,_
whatever his _decay of parts_ may be.

John was a man extraordinarily sent, and eminently furnished for his work:
when it is told him, John 3:26, that _all_ men were leaving _him_ and following _Christ,_
what answers he? verse 30, "`__He__ must increase,
and _I_ must decrease,`" and "`my joy is _therefore_ fulfilled,`" verse 29.
--O what abundance of sobriety is here!
See also Numbers 11:29. The case is the same in our days; though, to some,
it may appear very absurd to say it.
It is true, it does not hold in main things; nor is it needful it should; but,
in the many, it does.
O that _the good old men,_ and some _younger_ also,
who have worthily deserved praise for their faithfulness
and honesty in the work of God hitherto,
would observe, and condescend to see themselves outstripped,
seeing _Christ is thereby_ getting glory: however _they_ may be decreasing, (yea,
and it must be so,) yet, if _He_ be increasing, will they not rejoice?
I am persuaded many of them would, yea, I dare not doubt, but all of them,
who are truly such, would become _any thing_ for Christ.
But they see not the truth of what is alleged, yea,
they have strong apprehensions that it is otherwise;
yet are they warranted in bearing with the infirmities of such,
and in adoring our glorious Lord, as well as in wondering at his way,
who can so make out his purposes, by manifesting all flesh to be as grass, Isa. 40:6.
_So it hath been in all generations before us:_
the providence of God is carrying on his work in the _present_ age, though, ordinarily,
his dispensation is _obscure_ and _dark_ to most of _those,
who have been active and eminent instruments in bringing it thus far;_
the Lord in his wisdom thinking fit so to dispose,
lest any creature should share in his glory.
See a very clear instance of this in Ezra 3:12-13,--"`But
many of the priests and Levites,
and chief of the fathers, who were ancient men, that had seen the first house,
when the foundation of this house was laid before their eyes, wept with a loud voice;
and many shouted aloud for joy,`" etc.
But it is a sad case, when God`'s servants, through their passion, prejudice,
or mistake of the work of God, draw this desertion on themselves;
so hath it been formerly: see it clearly held forth in the case of Moses and Aaron,
Numbers 20:12,--"`The Lord spake unto Moses and Aaron, Because ye believed me not,
to sanctify me in the eyes of the children of Israel,
therefore ye shall not bring this congregation into the land which I have given them.`"
And, would God! there were not too much cause to say,
that _so it is in these nations with many godly men at this day._
See, to this purpose also, that notable place in Ezek. 44:7-9,
compared with verse 15, 16, etc.

But I shall leave this sad subject; and close up my thoughts on 1 Peter 4:7,
with some considerations on the last words, "`Watch unto prayer.`"
How much advantage it may be of to us, in all our exercise of daily watching,
to be frequently minding death,--the experienced Christian knows.
And, should I tell my own experience here, (though it be but very little,
as to any thing of this kind,) I hope I may say,
that considerations of a dying condition, which I have been in, now,
for divers years together, have been very useful to me.
If we were once brought this length,
to be denying ourselves as to the things of a present world, so as, though using them,
it were in a manner _by constraint,_ our daily exercise and delight +++[+++being centered in]
desires _to be away_ and _to be with Christ;_--if we knew, with the Apostle, what that means,
Phil. 1:23, to be in a strait betwixt two,
having a desire to depart and to be with Christ, which is best of all;--if, for this,
we were groaning earnestly, to be clothed upon with our house which is from heaven,
2 Cor. 5:2;--then would our watching, in the daily course thereof,
be not a little furthered, by our always bearing in view thoughts of death,
waiting with Job 14:14, all the days of our appointed time until our change come.

As Satan ofttimes keeps back many gracious hearts from receiving Christ,
by making them rest on their _performances_ and the
actings of _gracious habits_ that are in them;
so, many times, when this snare is discovered, he has another hard at hand,
by which he keeps off many such from closing in with Christ,
so as to give him welcome entertainment;--and that is,
by making them go faintingly and with much discouragement
about the duty of receiving him.
And in this snare, they are the more easily entangled,
inasmuch as it passeth with them _under the name of humility,_
for them to be always in this _mourning_ or, as I may rather call it, _murmuring_ condition.

While I was thus about thoughts of _mourning,_
and the right properties and qualifications of it, I began to think,
what matter of mourning and humiliation I had; and therefore resolved,
to set apart the next day, being Friday the 8th day of May, 1657,
for seeking God by fasting and prayer.
The causes that then did most occur to my consideration, were mainly these three.--First,
In relation to my own condition,--that I might lament and mourn for _the sins of my youth,_
which I desire may be "`ever before me.`"--Secondly,
In relation to _the condition of the people of God_
in these times,--that the Lord would arise,
and carry on his great work, which seems, as matters now go,
to be at a very great loss.--Thirdly, In relation to _my family,_
and more especially my wife,--to seek God on her behalf,
both for her soul`'s and body`'s condition, +++[+++she being near her confinement.]

And, to the praise of God, I must acknowledge his goodness,
that however dull and senseless I was that day, in the duty of seeking to him, yet,
in this, he was gracious unto me;--that though, as to _the external performance,_
and assistance in the outward duty, I had less that day than ordinarily;
yet were _the things themselves more on my heart,_ and, I trust, I may say,
in a more believing way, hoped for.
_That_ day was my wife taken ill,
and the next morning was well brought to bed of a
son;--which I take as an answer to prayer,
yea, a preventing of me rather,
according as is promised in Isa. 65:24,--"`And it shall come to pass,
that before they call, I will answer; and while they are yet speaking, I will hear.`"
I conceive myself, (and have expressed it so to the Lord,) as more obliged than ever,
to watch over my heart in keeping communion with God; and more particularly,
seeing he continues the comfort of wife and children with me,
I am the more obliged to watch over my heart, as to the enjoying of them,
and all things else of that kind;
that I may honour to get and keep loose my heart from being sinfully engaged.
And I dare to honour to make use of this time, that hereafter shall be granted to me,
of the sweet comfort of their fellowship, for the preparing my heart,
and having it so framed, that I may know how to be content to want, as well as to abound,
Phil. 4:12,--how to want any or all of them, if the Lord should so think fit.
In this endeavour, I conceive myself called to be very diligent,
seeing my heart to be too much engaged and entangled with them, or tempted so to be;
that if the Lord should be pleased to remove any of these from me, or me from them,
I might quietly and contentedly submit, and agree to his blessed will.
Another reason is, that I conceive I have not long to enjoy them,
but either I am to be removed from them, or they from me;
and that this time is given me of the Lord, to prepare for such a case.

My wife being brought to bed of a son,
I was a little straitened about the baptizing of him; at last,
after seeking God in the matter, I resolved to have him baptized in the ordinary manner,
if I could find any godly minister,
(though he were of the Presbyterian judgment,) that
would perform the duty in a private manner,
and would give me liberty, at the doing of it,
to declare,--that it was not my desire to have my son baptized upon any other account,
than as a member of the _catholic or universal church;_ seeing I do not believe that,
in the Holy Scriptures,
there is any warrant for constituting gospel churches _in a national way._
After conference with Mr. John Sinclair, minister of Ormston, about this point,
I found him clear on that point,--that baptism was no constituting ordinance;
and that he could very freely baptize my child, on that same account which I desired,
as a member of the catholic church,
seeing he knew my judgment to be against the national way of constitution.

Thus I resolved, for the present, for peace sake;
_I not being a member of any gathered church,_ and at a distance from those Christians,
with whom formerly I walked in fellowship at Aberdeen, (which, if I could have enjoyed,
I should have thought it my duty rather to have chosen it,
than any other;)--+++[+++and this was done,]
that I might give an evidence to the godly men of the Presbyterian way,
of my willingness to live peaceably and in love with them,
partaking with them in all duties, so far as I may do it without sin;
though in the matter of their constitution and form of government I differ from them.

The 12th day being appointed by the said Mr. John Sinclair and me,
for his coming to Newbattle to baptize the said child, when he came,
he was unwilling that I should make any such declaration.
He alleged, that if I should speak this publicly,
it would occasion the Presbytery to trouble him, and therefore besought me to forbear.
I having, a long time before that, thought of the matter, concluded,
that without some such expression in public, at the time of baptizing the child,
I could not admit the doing of it by any of the national church.
Whereupon he moved, that some other might present the child, to which I yielded,
being loath to be the occasion of his trouble; so, Robert Porteous the younger,
bailie +++[+++or alderman]
of Newbattle, presented the child, the 12th of May, 1657; his name being Thomas,
after my dear brother that was killed at Dunbar.

What the Lord`'s purpose to me in this may be, I desire to observe,--that,
these six years by-gone,
the opportunity of presenting any of my children
to receive that ordinance hath been denied me,
sometimes by my absence, either in London or Edinburgh; only, at this time,
I was in the place, and yet could not be present at that action, as aforesaid.
