== Chapter VIII.

[.chapter-synopsis]
* 1657: Observations on Matthew 12:43, etc.
* Encouragement from certain portions of Holy Writ
* Prosperity and adversity
* Alexander Jaffray engages himself afresh unto the Lord
* His desires in prayer on behalf of some at Aberdeen
* He meets with an accident
* Uprightness in keeping from iniquity
* Journey to Aberdeen
* He notices some unwatchfulness
* The illness of his son Andrew
* He removes his residence to Abbey Hill
* Vows and promises are vain without striving against sin
* 1658: Comfort from some Scriptures
* He is insnared in temptation
* The death of his son John
* He recounts the manifold mercies dealt out to him
* The birth of twin children
* On conformity.

It is said in Matt. 12:43,--When the unclean spirit is gone out of a man,
he seeks rest and finds none; that is to say,
he has no pleasure so much to be in any place as in _that_ heart,
out of which he has been once removed or cast out; and therefore his endeavour is,
by all means, to be in there again.
And finding the room, since his removal,
not washed and thoroughly purged as it should have been,
(see Jer. 4:14) but only emptied, swept, and garnished,
as the word there is,--that is to say, all outward scandalous sins are abstained from,
and duties diligently practised,--the house is emptied of the one,
and well swept and garnished with the other,
but there is no inward purging and washing out of "`vain thoughts`" and the like,--I say,
when the poor heart`'s case is thus _very well in its own estimation;_ yet,
now is it in no less hazard than that of being, on Satan`'s re-entrance,
made worse than before.
O let us then be careful, if Satan be not out, to get him out; and if he be gone,
to keep him out.
And, if I be not mistaken greatly in my experience,
there will be much more work for thee to do, to keep him out,
than there was at first to put him out.
For sometimes at first, he will remove with _consent,_ intending _to return with advantage;_
then brings he with him, seven worse devils than himself.
But, being out, if thou strive to keep him so, by closing doors on him,
and opening them to Christ, he will then be on thee as a lion,
to tear and rend thee to pieces.

The truth of this, though it hath formerly been made out to me in my experience,
yet never so, as at this present time; Satan having, now for some years,
been without doors with me, as to the practice of any open or scandalous sin;
and finding, upon his return,
the house of my heart in some good measure _adorned with public, private,
and secret duties,_ O how he is endeavouring now again to enter!--and woe to me, if he do!
This day, the 16th of May, was set apart for the purpose of suing help in this case.
So strong and mighty an adversary have I to do with,
that it is of the Lord`'s admirable goodness,
I am not _utterly run down_ and undone before him.
I find that Scripture, Eph. 6:12, made well out unto me,
"`We wrestle not against flesh and blood, but against principalities, against powers,
against the rulers of the darkness of this world,
against spiritual wickedness in high places.`"
There is, indeed, a mighty enemy; but we have an almighty Lord against him,
who hath already, on our behalf, wholly routed and subdued him; he,
having led captivity captive, hath ascended on high, Ps. 68:18,
and there he hath all power in heaven and earth given to him, Matt. 28:18;
so that now, the serpent`'s head being broken,
he can only but bruise our heel He will not leave off, still, to be about our heels,
and at our right hand to resist us; but our Lord will rebuke him, Zech. 3:1-2; for,
we have not a High Priest, which cannot be touched with the feeling of our infirmities,
but was in all points tempted like as we are, yet without sin, Heb. 4:15; and,
in that he suffered, being tempted, he is able to succour them that are tempted, chap.
ii. 18 Let us, therefore, come boldly to the throne of grace, that we may obtain mercy,
and find grace to help in time of need, chap.
iv. 16.

But Satan, not willing so to give over his hope of reentrance in the heart,
hath made on me more furious assaults than ever; taking most advantage now,
where he is not a little strengthened against me,
by his knowledge of my temper and frame of natural constitution.
Most frequent and furious are his temptations, and more than formerly,
where he finds my temper and natural disposition to be most inclined.
But my Lord, who can bring light out of darkness, and meat out of the eater,
Judges 14:14, I trust, _is to give me, ere it be long, a blessed advantage,
by drawing me the more close and near home, to himself._
Blessed be my Lord! my hope was this day confirmed, that it _will_ be so;
and the desires and stirrings up of my soul were renewed to follow hard after him,
as I might attain to.
Ps. 63:8-9, "`My soul followeth hard after thee, thy right hand upholdeth me;
but those that seek my soul to destroy it,
shall go to the lowest parts of the earth,`" that is, to the lowest hell.
O, when shall that unclean spirit be bound, and cast into that bottomless pit,
and shut up there, that he may deceive the nations no more! Rev. 20:2-3.

I was this day much encouraged from the consideration of these,
and some such Scriptures.--Ps. 27:13, "`I had fainted,
unless I had believed to see the goodness of the
Lord in the land of the living.`"--Verse 14,
"`Wait on the Lord; be of good courage, and he shall strengthen thine heart: wait, I say,
on the Lord.`"--Prov. 24:10, "`If thou faint in the day of adversity,
thy strength is small.`"--Isa. 38:14, "`O Lord!
I am oppressed; undertake for me;`" compared with Acts 10:38,
where it is said of Christ, that he "`went about,
healing all that were oppressed of the devil.`"--Heb. 12:4,
"`Ye have not yet resisted unto blood, striving against sin.`"--Heb. 10:36,
"`Ye have need of patience, that, after ye have done the will of God,
ye might receive the promise;`" +++[+++as connected with those other passages]
1 Peter 5:10, and Eph. 1:13, "`But the God of all grace,
who hath called us unto his eternal glory by Christ Jesus,
after that ye have suffered awhile, make you perfect, establish, strengthen,
settle you.`"
"`In whom, after that ye believed, ye were sealed with that Holy Spirit of promise.`"

Adversity and an afflicted condition, either inward or outward, or both together,
is no sure mark of God`'s displeasure, no more than prosperity is of his love.
The truth of this was not well known to those of older times.
Job`'s friends mistook +++[+++in this point;]
they conceived, God never dealt with a believer +++[+++as he had with Job.]
"`To which of the saints wilt thou turn? said they,
chap. 5. ver. 1--as if none of the saints had ever been so dealt with;
and therefore they concluded _him_ a hypocrite.
Job himself also, though rightly, against his friends, he maintains his integrity; yet,
how ignorant was he of the mind of God in the dispensation towards him,
until the Lord himself made it known; and then, he abhorred himself in dust and ashes.
How far was Asaph +++[+++disposed]
to mistake,--+++[+++even so]
that he was ready to conclude, it was vain to serve God +++[+++and cleanse his heart,
Ps. 73:13,17, until he went into the sanctuary,
then he understood the end of the wicked.]
So Jeremiah 12:1, and Habakkuk 1:13-14, etc.
Albeit, the truth of this case was not so unknown, but that some of God`'s servants,
at their dear-bought experience, knew his mind herein.
As Solomon, in Ecc. 9:1,
"`No man knoweth either love or hatred by all that is before them.`"
So then, neither from prosperity nor adversity +++[+++merely,]
may there be any sure conclusion drawn, of a good condition;
and the ignorance of this was, and is to this day,
the occasion of much mistake to many a good man, in judging of their state.
If, in the sight of God, thou mayst truly say, in the sincerity of thy heart,
that the first motions and risings of corruption,
and the suggestions and buffetings of Satan,
are indeed matter of grief and sorrow to thee;
that thou art often with the Lord in the duties of prayer, fasting,
etc. for the removing of these; though Satan be raging,
and corruption appear more than ever, _fear them not:_--wonder and praise God, that,
both in the timing and moderating of the temptation, _thou knowest and seest thy enemy._
Might he not have let thee have been surprised?
O, then, what duty is there for thee _to fear!_--but _fear not to be overcome;_--for,
as truly as God lives, thou wilt get the victory--if thou wilt but _stand,_
Satan then will flee away, James 4:7; and thou wilt get power,
even to trample him under thy feet shortly. Rom. 16:20.
Yet again, I say, fear not to be overcome,
but rather that thou turn lazy or weary, and let down thy watch.
"`Happy is the man that,`" in this sense, "`feareth alway.`" Prov. 28:14.

It was, this day, the 30th of May, 1657, my earnest desire to the Lord,
for his help to practise what I know.
I find from sad experience, that Satan +++[+++has taken advantage]
by reason of my unwatchfulness, and not stirring up myself to the exercise of faith in,
and hope of the Lord`'s coming, who would give me a full out-get +++[+++from the power]
of some corruptions, not yet mortified in me.
For which cause I did, this day,
_more solemnly engage myself to the Lord than ever before,_
that in his strength I would strive more against sin,
resisting more the first motions and risings of it in my heart;
and resolved to abridge myself more, even in the use of lawful pleasures; lest,
if the full length of what may be conceived lawful, be reached unto,
I may not be able to know where thereafter to stop.
The Lord help me to sobriety and watchfulness; for sad is my case,
if I be not now in _these_ more than ever.
But, I trust my Lord is near me, and was this morning; for,
all I undertake is in his strength to be done--without him I can do nothing.

The 4th of August, I put up a desire to the Lord,
for direction in my going or not going to Aberdeen; my good father,
and other friends there, having desired me and my wife to come.
For answer in this, I purpose to wait, with some confidence,
that the Lord _will order me in it._

I was laboring to remember such as fear God _there;_ in particular,
my father-in-law and his family;
+++[+++see <<note-EE-diary,Appendix, EE.>>]--that the Lord would pity him,
and give him, before his death, to repent for his bitterness to,
and persecution of such as fear God there;--that the Lord would direct his son,
Mr. Andrew, in his undertaking of the ministry, _that he run not unsent,_
but that he may be _furnished_ and _directed of the Lord;_ and particularly,
that the Lord would order his coming, or not, to Newbattle,
so as may be most for his glory,
and the good of these poor people;--that the Lord _would find out some way,_
that the gospel may be more powerfully preached at Aberdeen,
and the ordinances of Christ in a pure, gospel way administered;
that he would furnish and thrust forth Mr. Alexander White and
Mr. Alexander Gordon for that purpose;--that the Lord would forgive
Mr. John Menzies and Mr. Alexander Cant for their scandal and offence,
by their bitter and unchristian-like carriage one towards another;
whereby God is so much dishonoured,
the mouths of the wicked being thereby so much opened,
and the hearts of the godly made sad;
and that he would prevent any thing further of that kind, among those that fear him.

I was also, this day, convinced, that I am and have been, these divers weeks by-gone,
in hazard of withering and decaying,
rather than making any progress in advancing in holiness and mortification,
nevertheless of all the vows and promises that are on me; and therefore again purposed,
in the strength of Christ, to set about my duty anew;
waiting for the performance of that promise, Isa. 40:31,
"`They that wait on the Lord shall renew their strength,`" etc.

The 11th day, I had new occasion to praise God,
for delivering my son Andrew and me from the danger of a fall from my horse;
and for ordering, that the horse did run very near by, and not over him, etc.

The 14th day, and the night preceding, I had a large experience of my weakness,
by reason of unwatchfulness against the wiles and subtleties of the devil; whereupon,
I was intending, in the strength of Christ, again to renew my vows,
of endeavouring more closely to walk with God; especially against that sin,
wherein I am most assaulted, and which I may call _my iniquity._
And, considering that place, Ps. 18:23, where David says, "`I was upright before him,
and kept myself from my iniquity.`"
I find,
there must be _much_ integrity and uprightness in the
heart that would keep itself from its iniquity.
Want of this uprightness, this _sincerity,_ which the Spirit, Rev. 3:2,
challenges in the church of Sardis, is the cause of unwatchfulness; without which,
the things that remain and are ready to die cannot be strengthened.
My desire and prayer to the Lord, therefore, was, for grace to be more upright,
more sincere, and "`perfect`" in his sight, and so be better kept from my iniquity.

The 22nd, having resolved upon my journey to Aberdeen, I was seeking of the Lord,
that his presence may go with me, and abide with my family; and having spoken to them,
and such of my children as understand, and exhorted them the best I could;
my heart was some way helped to rely on God for direction to them.
My wife being at this time to go with me, who formerly always was present with them,
makes me the more afraid for their miscarriage in this place,
where there are so few to visit them, or take care of them;
and therefore was I the more earnest, in recommending them to the Lord; and,
by his grace, I intend to observe,
and be more thankful for the mercies they shall meet with.
It was also, this day, remembered by me,
with a desire of thankfulness,--how gracious the Lord was to me and my family,
in directing our journey _hither;_ and in guiding us by the way, both by sea and land;
and in blessing us since with health and protection; for these and many such mercies,
what matter of praise have I to God, and of engagement of heart again anew unto him!

The 1st of September, being advanced on my journey the length of Stonehaven,
and made to stop there by a stormy day,
I had some assistance in prayer,--both to praise
God for his presence with me so far in my journey,
and to seek of him, with some confidence,
his direction and presence for the time to come.

The 2nd day being yet a more tempestuous day of rain, I was stayed at +++[+++Gillybrands;]
but before my coming thither, I was, with my wife and servant,
very mercifully delivered at the burne +++[+++stream]
of Muchels +++[+++a few miles north of Stonehaven,]
where we were very near to have been carried down with the speat +++[+++or land flood;]
but the Lord rescued us, and within some short time thereafter,
these burnes were past all possibility of riding.

The 3rd day, having come safely with my wife to Aberdeen,
I found matter of rejoicing that all my friends were well;
and stayed there until the 17th day.
Though my time was not so well spent as it should have been; yet was I minding,
as I could, to seek God on behalf of such as fear him there, apart for some,
and together with others, exhorting and admonishing, weakly, as I could;
but I failed most in this,--that I could not,
(by reason of some differences betwixt my father-in-law and me,
about some civil particulars,) attain so fit and convenient occasion,
of speaking my mind to him and his two sons about divers things,
that have for a long time been on my mind as a duty I owe them,
on the account both of natural and spiritual obligation.

The 17th day, I parted from Aberdeen, and came to Newbattle the 21st day;
where I was desiring,
to remember with thankfulness the Lord`'s goodness and sweet providence,
in leading me and my wife abroad, in being with us there,
and returning us so safely home again,
also making me to meet with my family and dear children in health and peace.

Having had so large experience of my Lord`'s willingness to hear prayer,
I do think myself the more engaged, to wait upon and believe in him, while I live;
+++[+++according to the language,]
Ps. 116:1-2, "`I love the Lord, because he hath heard my voice and my supplications.
Because he hath inclined his ear unto me,
therefore will I call upon him as long as I live.`"

The 23rd of September, I was much convinced of my heart`'s corruption,
and Satan`'s working on it, taking advantage of my weakness and unwatchfulness,
to stir me up to the sin of passion, _in speaking too sharply to my servants;_
and therefore I was desiring, in the Lord`'s strength,
to watch and pray more against that sin of passion and bitterness. Matt. 5:22.
"`Whosoever is angry with his _brother_ without a cause,
shall be in danger of the judgment;`" and again, Eph. 6:9, "`Ye masters,
do the same +++[+++good]
things unto them, forbearing threatening: knowing that your Master also is in heaven;
neither is there respect of persons with him.`"
Considering these passages, I find much cause to moderate my way in this;
and in order that the tongue may be ruled, which is such an unruly evil, James 3:6,
the heart must be purged, and the evil +++[+++dried up, extirpated]
at the root, or all will be in vain.
Ezek. 36:26, _a new heart and a new spirit_ is promised;
for _that_ is the fountain out of which proceedeth all the evil we are guilty of. Matt. 15:19.

The 25th of October, my son Andrew having been visited with sickness,
I caused him to be carried to Edinburgh;
and both in the timing and way of his carriage and return, the Lord was very merciful,
and his hand observable in directing the cure applied to him;
for which there remains much duty on us to be thankful.
But yet, there was sad matter of regret for unthankfulness, and much unwatchfulness;
and cause of fear, that we may miss the mind of the Lord in such dispensations.
This is, as I conceive, one main thing the Lord aims at,
both in me and my wife,--that our hearts may be loosed
from the inordinate and extravagant love to him,
or any of the rest of our children; and that we may learn to give them up,
and _wholly over unto God,_--to be continued with, or removed from us, at _his_ pleasure.
But alas, how little evidence of any such thing,
does there appear in any of us! therefore, I take it much my duty,
to be very earnest with God in this particular; lest He be offended,
and even _they_ may suffer _for our sakes._

That day, I was seeking of the Lord, that I might be directed,
in transporting my family from this place,
_when and where the Lord should please._--The 6th of November,
having taken a house near the Abbey, I meant to carry my children the first fair day,
and was seeking direction for that effect.
The 7th day, three of my children were conveyed thither, upon the return of the servants,
+++[+++who]
went with them.
When I was giving thanks to the Lord for the fair day and safe passages they had gotten,
it was borne in upon my mind,--that the Lord,
who so frequently heard me in these and the like things,
_was ready to hear me in better things,_ if faith were more acted,
in seeking and waiting for them.
I was also here remembering my laziness in watching,
and looseness in keeping communion with God; and in his strength labored anew,
to engage my heart to more closeness, and watchful walking with him.

The 9th and 10th days, myself, my wife, and the rest of my children,
came safely to our house near the Abbey, called the Abbey Hill,
all in good health,--which I promised to remember, as a mercy from the Lord.
Yet was I, very shortly, forgetful,
and by unwatchfulness miscarried in some things in my conversation, which,
before the Lord, I had more than once very solemnly promised to strive against,
and in his strength to abstain from.
But I perceive, that,--to strive against _the act of sin_ by vows, promises, and the like,
when the _root of the evil_ is not most of all striven against in the heart,
and faith acted, upon the faithfulness, power, and love of Christ,
for casting out the idol, or mortifying the lust that is striven against;--I say,
while this course is fallen upon, all other endeavours will be but vain.
_If iniquity be regarded in the heart, God will not hear thy prayer,_ Ps. 66:18,
though it be never so frequent and fervent.
Endeavour therefore to get that abhorring, that indignation,
that revenge against the very first motions and rising of sin in thy heart,
which is mentioned in 2 Cor. 7:11.

The 11th of January, 1658.
I find not only no progress made,
nor victory obtained against the evils of my heart,--especially
against the predominant evils of my nature and complexion;
but rather, their prevailing against me.
These three Scriptures occurred, with some advantage and comfort to me.
First, that of Prov. 24:10, "`If thou faint in the day of adversity,
thy strength is small:`"--fear to dishonour God by misbelief was like a staff to me,
setting me yet to work, _still to wait on him for victory,_
notwithstanding my frequent and sad failings.
Secondly, that in Isa. 38:14, "`O Lord!
I am oppressed; undertake for me:`"--when my oppression is greatest,
then is my deliverance nearest, as in Isa. 41:17,
"`When the poor and needy seek water, and there is none,
and their tongue faileth for thirst, I the Lord will hear them,
I the God of Israel will not forsake them,`" etc. also Isa. 59:19,
"`When the enemy shall come in like a flood,
the Spirit of the Lord shall lift up a standard against him.`"
The third Scripture was that language of Hezekiah, in Isa. 38:15,
"`I shall go softly all my years in the bitterness of my soul,`"--taking the sense,
with the Dutch divines,
in their annotations on the place--because of my
former failings and the bitterness I now find,
thereby, I mind to walk more warily and more circumspectly, all my days.
To do this, was my purpose and desire in the strength of Christ.

Not many days thereafter, namely, upon the 25th day of the said month,
notwithstanding all my former resolutions and engagements,
I was again overcome by the slight and subtlety of my adversary;--or rather, I may say,
through the unwatchfulness and desperate wickedness of my own heart,
insnared in the same guiltiness,
which I was laboring and praying to resist and to get subdued,--but all in vain,
for Christ is not yet come for my delivery; and it is only by Christ and grace from him,
that the body of sin and death must be subdued.
It is, through the Spirit, that the deeds of the body must be mortified. Rom. 8:13.
--Upon the very next day, my son John,
having been sick but two days before, was removed by death.
The concurring of these things so together,
gave me matter of much humiliation and fear.--Whereupon, on the 1st of February,
I set some time apart, in this my sad condition, to seek the Lord;--for yet, I hope,
he may be found,--yea, I know, and desire to rest fully assured,
_He is near that justifies me,_ Rom. 10:8-9,
and, in due time, will sanctify me wholly, 1 Thess. 5:23.
My special desire, this day,
to the Lord was,--seeing I had so good ground to believe,
sin should not have dominion over me,
Rom. 6:14,--that he would stay and establish my faith, as to this point; for Satan,
by his often assaulting, and so frequent prevailing against me,
would have me doubt of this,--as if my corruption were _so great,_
and _deeply rooted in my nature,_ that God either _could not_ or _would not_ help me.
But, having laid aside this temptation, and, through grace,
in some measure gotten the upper hand of it,--so as that I resolve, through his strength,
_never to doubt of his power,_ nor yet _of his willingness,
and faithfulness to fulfill his promise;_--my exercise was most,
what and how to do in the mean time, until _the vision speak,_
as it is said in Hab. 2:3:--I know I must wait,--and though it tarry long,
yet I _must_ wait for it; for it will come, and will not _lie._
I bless the Lord, I think I am, in some weak measure,
fixed in this also--__to hope__ that my Lord _is coming,_ and that the day _shall_ be,
when Satan shall be trampled under my feet, Rom. 16:20.
Not only do I desire to wait for the fulfilling of this promise, fully,
_after death,_ in glory; but that, in a good measure, according to the riches of his grace,
it _shall_ be fulfilled to me _here,_ even in _this_ life; so that, although, as it were,
_trodden upon by Satan,_ I shall, ere long, (as to these particular evils,
by which now he prevails and buffets me so sore,) prevail over him,
and _trample on him and them,_ by obtaining the victory;--but that my Lord,
who is only wise, and knows best _how_ and _by what temptations to exercise me,_
is pleased thus to prove me for a while.

I was also seeking of the Lord, for myself and my wife,
that we might be prepared for death,--and might have our hearts
loosed from too much engagement to the rest of our dear children,
that are left behind;--and for grace to them, that whether they die or live,
they may be the Lord`'s; and that we may be ready heartily to give them up to him,
to be disposed of at his pleasure.

The 22nd of March, 1658, my body being a little indisposed, I was seeking, as I could,
a blessing on the means +++[+++to be used,]
that both soul and body might be better disposed; and if the Lord shall prosper,
so that my health and strength be prolonged, then my desire and promise was,
in his strength to be more forthcoming for his service.
Many such vows are upon me:--Lord! help me to perform them better for the time to come,
than I have done in times that are gone by.

The 24th day, in my reading in my family, Matt. 5:21, etc. and chapter vi.,
I was much convinced, that I had many ways failed,
and exceedingly come short of the gospel rules there prescribed,
in watching over our thoughts, words, looks,
and the first risings of and motions to sin in the heart.

The 30th of April, being the day of the year on which I was first married,
I was laboring, as I could,
to have my thoughts exercised in the consideration
of the manifold mercies I have enjoyed since,
now, for the space of twenty-five years: they are many, both temporal and spiritual;
some of them were these following.
The Lord gave me, that day, a comfortable yokefellow,
when I had not so much as grace to seek it of him.
Many outward, bodily deliverances,--as from that trouble I had from Haddo,
and thereafter with Harthill, and at Pitcaple,
and at Dunbar;--many vows and promises--much obligation to thankfulness, is upon me,
because of these and the like;--as the appearance of an
out-get from the burden of that debt I contracted in Holland,
in bringing home our late King,
which once I feared would have ruined me and my children;--also some +++[+++probability]
of an out-get from that troublesome business of Caskoben.
+++[+++see <<note-FF-diary,Appendix, FF.>>]
So that my mind, in these things, is delivered from a great deal of anxiety and fear,
which, too sinfully, I had in these and the like matters.
I was, thereupon, seeking of the Lord to be kept from covetousness,
and satisfying myself with the things of a present world.--But, more especially,
the spiritual mercies I have met with! and yet,--after
so little improvement of grace and gifts,
that there should still be any offer of that kind made unto me.--O! what wonder is it,
and how much does the goodness of God therein appear!
The Lord help me to be more mindful, and more thankful,
and more diligent _to engage my heart unto him._

May the 4th, being the day of my second marriage, that day and some thereafter,
I was desiring, as I could,
to remember the continuance and increase of the aforesaid mercies on me and my family,
and endeavouring, weakly, as I could, to engage my heart to be thankful.
Having now, far contrary to my expectation,
for divers years enjoyed the comfortable use of the blessings of a married condition,
(which I have many times so earnestly sought after, as being much convinced,
that I could bear more hardly the being deprived of these comforts,
than of any other earthly thing whatsoever,)--and now,
having beyond my expectation had a large time of them, I think it my duty,
upon many considerations, not only to be thankful,
but to have my heart more composed with the apprehension
of the want of things of that kind.
Thus, if the Lord should be pleased to exercise me with any such dispensations,
as to remove my dear wife or children, any or all of them,
I might not be thereby surprised, so as to miscarry either before God or men,
or with any the least thought of murmuring or repining;
but contentedly submit to his blessed will, who can supply all their rooms to me,
exceeding abundantly, above all that I can ask or think,
so that all my faithless fears shall be disappointed.
It is therefore the desire of my heart, to be so habituating myself to such meditations,
and so to have both my heart and my house put in order; that,
whatever the Lord`'s will may be,
I may be ready sweetly and contentedly to submit thereto.
But, it is the Lord alone, that must help me to do rightly any thing in this,
_for without Him I can do nothing:_ and therefore I desire in his strength,
to be about my duty, and to wait on in faith, as I may,
putting up their and my own conditions to the Lord,
with relation to both these cases;--and, in particular,
laboring to remember my wife`'s condition, and to pray and believe on her behalf,
that the Lord would not remember her unthankfulness for former mercies, nor mine,
but that he would add this of her happy delivery to the rest,
that we may yet have more occasion to praise him together.

The 14th of May, 1658, my wife having taken her pains in the evening,
the next morning was happily brought to bed of two children, a son and a daughter.

There is, by this new mercy, a further obligation put upon us, to be thankful;
the Lord having not only heard our desires,
but wonderfully disappointed our faithless fears, prevented and gone beyond our desires,
in giving us not only some hope of being yet awhile spared to each other; but giving us,
instead of one, two pleasant and well-favoured children,
and the mother having been very mercifully dealt with in her pains:--this
lays great obligation on us to be more for God in our family,
apart and together, _in all holiness of conversation_ and good example,
in stirring up ourselves and others, especially those of our family and servants,
to do him better service than ever.
And in particular, both of us, the parents,
are by this so sweet a mercy very clearly spoken with,
to beware of making our children to be our idols.
It is not long since God removed one sweet child from us, and now he has given two;
in this, now, he would have us to know how to borrow and lend with him.
Lord, help us to learn well this necessary lesson!

+++[+++In giving some of the grounds of his objection,
against taking any part in presenting his twin-children
for the ceremony of baptism by water,
and in stating the liberty he felt, to permit his wife to present them for that purpose,
under certain limitations, Alexander Jaffray has this following remark:--]

Minding the Apostle`'s rule, Phil. 3:16, "`Whereto we have already attained,
let us walk by the _same_ rule, let us mind the _same_ thing,`" and verse preceding,
"`And if in any thing ye be _otherwise_ minded,
God shall reveal _even this_ unto you,`"--I ever thought it, and still think it my duty,
so far as I may without sin,
to go along with any of the Lord`'s people:--while +++[+++or until]
the Lord clear up our darkness, we must bear one with another, or +++[+++we shall be likely to]
devour each other.
And I am confident, it is our duty, not only to bear with one another,
wherein we may without sin, but to walk together.
Only special care should be had in this case, that,
(in the peremptory and peevish disposition of _the most part of the godly in this land,_
who can be satisfied with no less,
than to have all men conform to _them_ and be of _their_ judgment,)--I say,
especial care should be had, that, by our conforming to such,
we do not _confirm_ them in their _sinful mistakes;_ and therefore,
upon all occasions that are convenient, would testimony be given against their errors.
