== Chapter IX.

[.chapter-synopsis]
* 1668: The duty of mortification; and that of minding the condition of the Lord`'s people, etc.
* Thomas Goodwin`'s treatise
* Observation on a case in the criminal court
* Qualifications of true zeal
* Allusion to a conference between Alexander Jaffray and "`the Laird of Swintoune`"
* Owen`'s treatises on mortification and on watchfulness
* Alexander Jaffray writes "`some reasons relative to partaking the Lord`'s supper`"
* He laments his unthankfulness, and reviews the mercies bestowed on him and his family
* Recommends his friends at Aberdeen to the Lord
* Journey to Aberdeen
* The tidings of Cromwell`'s death.

The 29th day of May, 1658, I set some time apart, to seek God in these two things:
namely, First, For help to make progress in the business of _mortification,_
which does so much concern me.
Secondly, For grace from the Lord to be rightly directed,
about inquiring and finding out _the duty of the times;_
that I may not therein be deserted and given up to delusion, on the one hand,
or sit down and be satisfied with my prosperous, outward condition,
and not regard the condition of the land,
nor the sad condition of the Lord`'s people therein,--so
eminently deserted in many respects;
and, +++[+++that I may]
fear, on the other hand, lest,--inquiring after what may be the Lord`'s mind,
in some things relating to controversies of the time, about church constitution,
discipline,
and government,--I may be diverted from seeking after better things,--mortification,
self-denial, and tender walking with God.

+++[+++Then follow "`some thoughts of the duty and means of mortification,
as they were that day on my mind; these, though very cogent,
and rich in Scriptural illustration,
are for the most part comprehended in meditations already herein recorded.
The writer then proceeds:]

Some further thoughts on the matter above mentioned, were spoken home to my heart,
I hope, from the Lord; wherein I was helped,
by reading that Treatise written by Thomas Goodwin, _Against Relapsing;_ finding my case,
as I conceive, very clearly spoken to therein, to the following purpose; 2 Cor. 5:14,
"`The love of Christ constraineth us, because we thus judge, that if Christ died for all,
then they that live should not live unto themselves,`" etc.

+++[+++Some few pages are here omitted to be given,
being apparently a recital of Goodwin`'s Treatise.
+++[+++see <<note-GG-diary,Appendix, GG.>>]

The 7th of July, 1658, I was desiring direction of the Lord,
in the two particulars following.
First, That I may be directed to find out his mind,
in partaking of that ordinance of his supper; it having been moved by some good men,
whether, (seeing there is not appearance, in haste,
to have any other occasion in this place,) we might
lawfully partake with such of this nation,
as do most purely administer the same.
It is my desire to enjoy that ordinance,
having been for divers years deprived of the use of it; and yet I am not clear,
as I conceive, upon many weighty considerations to partake of it, as above mentioned.
Secondly, My affairs calling me to go to Aberdeen,
I was desiring the Lord to order and direct me in that journey.

The 8th day.
Upon the consideration of a vile fact of incest, pursued +++[+++or prosecuted]
before the criminal court,
wherein there was great presumption and appearance that the parties were guilty;
yet did they, both of them,
(the one having judicially confessed the fact,) escape
the sentence;--upon consideration of this,
and many such horrid guiltinesses committed in the land,
I was desiring to be humbled before the Lord; and, more especially,
that such sins should go without more strict inquiry and censure.
These Scriptures being considered,
may give much matter of humiliation to such as fear the Lord, in such cases,
to make them mourn for the sins and abominations of the land.
Hosea 4:1-2, "`The Lord hath a controversy with the inhabitants of the land,
because there is no truth nor mercy, nor knowledge of God in the land.
By swearing, and lying, and killing, and stealing, and committing adultery,
they break out, and blood toucheth blood.`"
Also, Jer. 9:12, and xii.
11; and again, Isa. 59:12, to 15. "`Our transgressions are _multiplied before thee,_
and our sins _testify against us:_ for our transgressions _are with us;_
and as for our iniquities, _we know them;_ in transgressing and lying against the Lord,
and departing away from our God, speaking oppression and revolt,
conceiving and uttering from the heart words of falsehood.
And judgment is turned away backward, and justice standeth afar off,`" etc.

The 11th day.
Having, some days before, been upon the consideration of the reasons,
why I conceive it not lawful +++[+++for me,]
to partake in the ordinance of the Lord`'s supper,
as it is here in this nation administered; I was, this day,
pertinently spoken to by Mr. James Horne, from that text, James 1:20;
and had given divers good qualifications of zeal in contending for the Truth,
which were very closely to my case; such as these.--First,
Right zeal in contending for any truth of God,
would be accompanied with much love to those, with whom we contend.--Secondly,
It would be carried on with much meekness, without heat or passion;
for "`the wrath of man worketh not the righteousness of God.`"--Thirdly,
There is much need of the exercise of humility and fear; for _the best_ know but in part,
1 Cor. 13:12-9; and frequent experience, doubtless,
hath taught every one that is observant,
to be wary in asserting so positively what now they think to be truth,
in these _doubtable_ matters, about which good men are so much divided.--Fourthly,
When zeal in these matters, is not accompanied with much exactness in trying ourselves,
and does not begin at our own bosom,
in finding out the errors either of our judgment or practice, and in abandoning them;
then may we justly suspect our zeal to be "`not according to knowledge.`" Rom. 10:2.
--Again, Right zeal is equally carried out,
in all points wherein God`'s honour is concerned.--Again,
Our calling to appear in such matters, would be well examined;
and that we be not thereby made negligent in things more necessary.--Again,
Although there be truth in the matter of difference betwixt you and good men,
it should be well examined, whether it will carry all the weight of what may follow,
upon your appearing in it.--Again,
All the consequences of the opinions maintained by your opposer,
would not be imputed unto him, except you know that he owns them,
but in charity you would think the best; for charity "`thinketh no evil.`" 1 Cor. 13:5.
--And further, Where you cannot agree,
you would tolerate and bear with your weak brother,
until God reveal what is wanting to him. Phil. 3:15-16.
--Lastly, It would be well examined,
that there be no siding with any party or other interest, but simply the glory of God,
that makes you appear in such a matter.

Upon second thoughts _of the matter above mentioned,_
and of a conference on _the same_ which I had with the Lord Swintoune a day before,
I resolve to examine more narrowly and diligently the thoughts of my heart concerning it;
and, by the grace of God, to have my corruption more mortified,
and my heart in a better frame, that I may warrantably proceed in that matter.
+++[+++see <<note-HH-diary,Appendix, HH.>>]

The 22nd day.
Having formerly gotten some good, by reading a little Treatise, _Of Mortification,_
written by Dr. Owen, and now finding another Treatise, by the same author,
_On the Duty of Watchfulness;_ I was seeking,
that the Lord may bless the reading of that Treatise to me,
that I may be helped in the knowledge and practice of that duty.
+++[+++see <<note-II-diary,Appendix, II.>>]--I was also recommending to God the condition of my
family,--that my wife and children may find mercy.
And more particularly for my eldest son,
+++[+++Alexander,]--that God would now give him the graces
and gifts necessary for one of his years,
he being now about sixteen years of age; and that the Lord would bless his studies,
that he may be directed in them; especially that he may learn _to know Christ;_
and that I may be ordered of the Lord, what calling to direct him to follow.

The 8th of August, 1658, I was earnestly seeking of the Lord,
that I might know his mind in relation to _the dispensation I am under._
And I thought I had liberty in prayer, and also direction,
to fall rightly upon one thing,
among others intimated to me by _my present indisposition_ and weakness of body;--namely,
too much carefulness and provision-making for the body,
too much looseness and liberty taken in satisfying the flesh,
the affections and lusts thereof, has made the Lord, in love to my soul,
a little to afflict the body.--I was also seeking direction in my journey north,
that I may be guided in my going and abiding there, that my carriage may be so ordered,
as that I may be comfortable, and not justly grievous, to any that fear the Lord there.
And also,
having now written _some reasons about partaking the
Lord`'s supper with the good people of this nation,_
I desired of the Lord to be directed in revising them;
so that I may not be left to my own spirit,
in mistaking or affirming rashly or uncharitably any thing,
that the Lord will not allow of, or that hereafter I may repent of;
but that I may soberly and humbly walk in that matter, as becomes a poor, dark,
ignorant creature, who yet dares not but desire to be established,
and to walk upon clear grounds in every such matter.

The 13th day, having come from Edinburgh to my own house at the Abbey Hill,
I was desiring to bless the Lord, that I find them all there preserved and in health;
and that the Lord had returned me there, in any measure and hope of better health.
But alas!
I find no change upon my heart,--no more love to Christ,
no more hatred and indignation against sin, no more sense of the goodness of God,
who might justly have consumed me, and have sent me to the pit;--yet has he spared,
and pardoned all my sins, and, only out of love, is gently shaking a rod on me.
O that the heart of a child, were making suitable returns to such a Father!

The 14th day, I set apart, to seek the Lord, and to praise him for mercies by-gone;
wherein, it was my desire, to take a view of all such mercies as may be remembered; for,
otherwise, they are innumerable.
I know not where to begin,
nor how to proceed in this inquiry,--his mercies to me have
been so many.--Lord! help me to praise thee for Christ;
since _in Him and for Him,_
are all my mercies given and sanctified to me!--I
was also desiring to have all my sins before me,
that I might lament and mourn for them, my God being now pacified towards me.
O how this consideration, of God`'s being pacified towards me,
should heighten the matter of lamentation and woe! that when I was sinning against him,
he was minding mercy to me; and while I was still sinning yet more against him,
_in the days of my greater knowledge,_ yet even _then,_ when I was worst and vilest,
did he manifest love;--how ought this to overcome my heart _forever to love Him,
who hath thus loved me, and given himself for me!_--I was this day, also,
desiring to bless the Lord for the mercies bestowed
on my family--how oft hath he heard me for them,
for the mother, the children, and the servants! as well for the hope I have,
that he will still hear me on their behalf, and be a God to me and my seed forever.
He takes the care of them off me, +++[+++while]
here; and when I shall be gone, I have none else to leave them to, like him!

I was also desiring to remember my friends and acquaintance at Aberdeen,
and to recommend them to the Lord,--and, even in a particular manner,
_my friends in the Lord;_ that his grace may be multiplied unto them,
and that the gospel may prosper _there,_
and that _gospel ordinances_ may be _in a right and pure way of administration_
set up there;--__that__ the Lord would direct _such_ who are _waiting for this,_
and are deprived of some ordinances, to walk humbly, +++[+++even looking]
_for that day of his mercy,_
when he will bring forth his promise,--__until the offerings
of Judah and Jerusalem be pleasant unto the Lord,
as in the days of old and in former years.__ Mal. 3:4.
And further, that the Lord would help _such others who fear him there,_
that they oppose no more _what he is calling for in this matter;_
and that they may find mercy and favour,
so as to be humbled for their opposition in these matters,
and to give some expression of it, before they part from this world.
Also, that the Lord would rebuke _a spirit of pride and contention,_ which _rages there;_
that thus, all such as fear him,
may "`walk in love,`" as becomes the children of one Father.

The 15th day, being a sabbath day, I had much matter to regret, for a lifeless,
formal way of spending it.
I was laboring to remember, as I could, the condition of the Lord`'s people in general,
and, in particular, _that handful who fear him at Aberdeen;_ they being now,
by the death of that worthy man Mr. James Duram,
disappointed of help for carrying on the work of God there;--that
he would be pleased to _point out some other way,_
whereby the work of the gospel and the ordinances, in purity may be administered there.
And I was desiring, that the Lord would let me see something of this kind,
before my return from that place, if I go thither at this time;
and that he would help me to be instrumental in so good a work.
And yet, +++[+++I longed that,]
before appearing any way instrumental therein, +++[+++I might]
be very earnest in seeking God, +++[+++as to]
when, how,
and for whom I shall act any thing in that matter;--for there may be more in it,
than hitherto I have considered of.

The 19th day, I was earnestly seeking of the Lord, his direction in my journey north,
(and the more so, my health not being wholly recovered,
and my physician and other friends being against
my journey,)--that he would abide with my family,
and be a God and a Father to them, and go with me where I am going; promising,
by his grace, to observe and be thankful for his presence.

The 20th day, I took my journey, and came that night safely to Brunt Island +++[+++Burntisland,]
and from thence to Kirkaldie, +++[+++proceeding]
the next day to Dundee.
The 26th day, I came to Aberdeen, in better health than I expected,
and found my friends there well.
The Lord help me to be thankful, and to walk humbly with my God,
and to remember my promise,
of observing his kindness and providence to me in this journey!

The 27th day, I was informed of the sinful and scandalous fall of Jane Ramsey,
who was sometime a professor, and one that _walked with us in fellowship in this place;_
her carriage was light and unchristian before, but now her fall +++[+++was worse.]
O what matter of grief and heaviness of heart ought it to be to professors here,
that God should be so offended! and what matter of
fear does it administer for those that stand,
to take heed lest they fall! for the devil is _very busy,_ and we _weak._

The 28th day, I visited that gracious woman, Elsinet Smith.

The 11th of September, I was desiring the Lord to order my thoughts of returning;
having now, by his good hand with me, come to some point in my affairs,
so that I may think upon the time and manner of returning.
I was also desiring to be helped, to remember the condition of that precious woman,
Barbara Forbes, widow of D. Wil.
Johnstone; she having imparted something of an outward cross and difficulty she is under.
My desire in particular for her was, that the Lord would make use of this dispensation,
so that she may learn _to behave herself as a weaned child,_ Ps. 131:2;
for I hope the Lord is about something of that kind towards her.

I was also remembering _this sore season,_ +++[+++in allusion, it is supposed,
to the circumstances explained in the next paragraph;]
and desiring the Lord _to prevent the sad event thereby threatened._

Upon the 14th of September, _report of the death of the Protector_ being come +++[+++to Aberdeen,]
and confirmed some days thereafter, I found myself very dull in conceiving rightly,
what the Lord by that dispensation was speaking to the land,
and to those that fear him in it.
There being also, at this time, very sad evidences of the Lord`'s anger against the land,
_by unseasonable weather, so that the fruits of the earth are threatened to be destroyed;_
this thought of the abuse of so much peace and plenty, as formerly we have been enjoying,
did much continue on my heart--and that we were, in the righteous judgment of God,
to be exercised with famine and war,
and _a sharper trial to pass over such as fear the Lord, than ever they had yet met with;_
especially for their unthankfulness for the peace we have been enjoying,
these years by-gone.
Therefore was it my desire,
to lament before the Lord for my own guiltiness and that of the land,
and to be prepared for the trials that are likely to follow.

The 18th day, I was desiring the Lord to direct me,
in resolving upon my return to my family; and praising him, as I could,
for his gracious and kind providence,
in so ordering me and my family and my affairs hitherto: and further,
that I may be directed to part from this place, with the contentment of all my relations,
both spiritual and natural; and that I may do nothing unworthy of my profession,
or that in any measure may give just occasion of offence.

The 26th day.
I had much matter to be thankful, for the Lord`'s presence with me in my journey,
since I came from my own house; not only in restoring me to better health,
but also for the success I had in my affairs, beyond my expectation;
wishing that the Lord`'s goodness, in these things, may not be forgotten,
and that he would direct me, in the rest of my journey, and in my pilgrimage here,
until he bring me unto glory!
And O! that I could walk worthy to that hope of glory,
and thankful for all the mercies I am meeting with here,
both to myself and family,--of whom I had gotten late advertisement,
that they were all in good health.

The 30th of September, 1658, I came safely to my own house at Abbey Hill,
and found my wife and children all in good health

+++[+++Here, at the 189th page, or rather leaf,
the first part or book of the manuscript breaks off, the remainder being, doubtless,
lost.
That which follows,
is taken from some tattered fragments of another similar pocket volume,
in the same hand-writing, but in a much worse state of preservation.]
