== Chapter X.

[.chapter-synopsis]
* 1659: Alexander Jaffray visits General Monk
* The afflicted condition of the three nations
* His own "`formality in performing ordinances,`" etc.
* He contemplates "`saluting`" General Monk on his marching for England
* His occasions for humiliation
* 1660: "`The still small voice to be heeded,`" etc.
* On the motions of the flesh, and of the Spirit
* Birth of a son: His views on having him "`baptized`"
* He is committed prisoner to the Tolbooth of Edinburg
* On dying daily to temporal delights
* The illness of several of his children
* His strong temptations
* He uses endeavours for liberation from prison
* Petitions the committee of estates
* The Lord Chancellor`'s prejudice against him
* The light of the Lord`'s countenance withheld from him: He is reduced to silence in prayer
* On enlargement in Prayer
* The death of his daughter Sarah
* His concern on behalf of his son Alexander.

The 26th and 27th days +++[+++of "`October,`" 1659,]
I had, from sad experience,
a proof of the truth of what is expressed in the end of the last page, +++[+++__this__ page,
or rather leaf, of the manuscript,
being marked the 40th,]--that _the victory over sin_ is not attained,
but through _much wrestling and fear;_ for want of which, I was sadly insnared,
_and my corruption had victory over me._
Upon which, my desires of being, for the time to come, more watchful,
were weakly renewed, as I could attain to; and these two Scriptures were looked on,
and some way made use of, Isa. 38:14, "`I am oppressed;
undertake for me;`" and Ps. 79:8, "`O remember not against us former iniquities:
let thy tender mercies speedily prevent us; for we are brought very low!`"

About this time, also, through my unwatchfulness, I was well near run upon another snare.
In a visit given to General Monk, (after his engaging for the Parliament,
in the division betwixt them and the army,) though
I did no ways approve of his way and acting;
yet I had matter to be afraid, that my visit and carriage, at that time,
might have seemed to have imported the contrary.
And in this,
was I the more to blame myself,--that I did not seek God`'s direction by prayer,
before I gave him that visit; which, I hope,
will teach me to be more wary for the time to come, in matters of that kind,
that my carriage do not contradict my judgment in any thing.

The 29th day,
I was desiring to remember the sad and afflicted condition of these three nations,
now so rent and divided, as never was their case so low, _God having written vanity upon,
and stained the pride of all our glory;_ the Parliament being not only broken,
but the Prince broken that brake them, and yet more like to break in pieces one another.
I read Isai.
ii. +++[+++beginning]
from verse 10:--"`Enter into the rock, and hide thee in the dust, for fear of the Lord,
and for the glory of his majesty.
The lofty looks of man shall be humbled,`" etc. also chap.
li. 18, 19, 20; and concluded with a few thoughts and desires,
put up upon the consideration of these Scriptures, and that of Micah 7:9; wishing,
that the Lord`'s people in these lands may be prepared
_to bear the indignation of the Lord,_
while he comes forth so dreadfully threatening it against them.
And, O! that I may be helped rightly to consider, what great duty there is on me,
to be very earnest and serious with God in this case;
I having so much both private and public guiltiness to mourn for.

The 31st day, I set apart some time, to seek God in the particulars following:

[.numbered-group]
====

[.numbered]
_First_, My own condition being so very dark and much deserted,
by reason of distance from God, before I durst venture to seek God on behalf of others,
I was laboring to make sure an interest for myself.

[.numbered]
_Secondly,_ My desire was,
to present the condition of these three nations +++[+++before the Lord;]
being much convinced of the justness and equity of what the Lord
is threatening against us:--should he inflict it to the uttermost,
I chose rather to desire _the removal of the sin,_ than of _the threatened judgment for it,_
and that the Lord`'s people may be prepared to bear his indignation,
because they have sinned against him. Micah 7:9.
Only I was desiring to seek, as I might,
that the Lord would rather let _his own hand_ be immediately on us,
than that _his people_ should be so far divided, as to "`devour one another.`"
Another thing I was helped, as I thought,
to seek of the Lord,--that if _the wicked_ of these lands,
shall be _the rod_ by which the Lord will have his people corrected,
he would provide so far against their insulting,
that they may not blaspheme his holy name or insult over his work,
by denying that ever he owned it, or has done any thing for his people in it;--that thus,
his glory for what is done may not, because of our guiltiness, be so cancelled; but that,
though _we,_ for our drawing back, and not carrying on his work with singleness of heart,
_may justly be deprived of the honour of seeing more of the glory of it,_
He may _not_ want his praise _for what is already done;_--and then,
that our poor posterity may behold _the rest of it,_
and though _our_ carcasses should justly fall _in this wilderness,_
yet _they_ may behold the glorious presence of the Lord _in that promised land._
Further, that he would provide against the reproach of religion and holiness,
the increase of error, blasphemy, antichristian persecution, and idolatry;
which being granted, and the increase of light,
and promotion of the gospel made way for,--let come of us what pleaseth him,
I was desiring to seek of the Lord, such a humble, submissive frame of spirit,
as I could, both for myself and all that fear him,
_against whom his hand is at this time so lifted up._
+++[+++see <<note-JJ-diary,Appendix, JJ.>>]

[.numbered]
_Thirdly,_ I was presenting the condition of my family,
and more particularly that of my son Andrew, to the Lord.

====

The 9th of November.
In prayer, I was helped to desire of the Lord,
that he would search and try my heart to the uttermost,
and find out and discover to me the vileness and vanity thereof to the full;
for I dare no more listen to _my own searching,_ having been thereby deceived so often.
I thought I was desirous to be honest, in this my prayer, to have my evil heart,
and the vileness and deceitfulness of it, wholly made known to me;
and that grace and strength might be given, to hate and abhor what I +++[+++do]
see.--I was also desiring to remember,
the sad deserted condition of the work and people of God, in these lands.

The 21st day.
I was putting up in prayer these things.--First,
Being sensible of much deadness and formality in my performing of ordinances,
I was desiring to be quickened and made more lively; and if, as to the external,
sensible way of assistance, I were not helped, that yet,
as to the inward frame and fervour of heart, my desires might be enlarged that way;
that so, although sense were not pleased, faith might be more exercised,
and I fitted to meet such a case as is mentioned in Isaiah 1:10,
_to stay myself on my God,_ though I were left _in darkness and had no light._--Secondly,
That I might move more upon a principle of love in all my duties and performances,
both to God, and to men for God`'s sake; and that I might be helped to discern my love,
in the reality and truth of it, from obedience and keeping Christ`'s commandments; +++[+++for,
said Christ, "`If ye love me, keep my commandments.`" John 14:15.
]--Thirdly, That the Lord would remember his people in these lands,
and deliver them yet once more from their dark and dangerous condition;
so as government on a right and sure foundation might be settled,
as one of the greatest mercies this present time calls for.
And that he would prevent the dreadful threatening of a bloody sword,
to rage more amongst us.

General Monk being shortly to take his march for England,
I was desiring counsel of the Lord, whether I should salute him before he go;
and to be guided, if I do,
that I may not approve any thing which my light serves me not to do,
nor yet speak any thing rashly, without a warrant and clear call thereto.

The 29th day, I was desiring to remember the condition of Wil.
Dowine +++[+++or Downe]
and Mrs.
Ward, that the Lord would sanctify their present condition; and +++[+++also]
that worthy man, the Lord Brodie, that he may be directed in these times,
and be made more and more useful for God and his people.

The 2nd December, 1659, I was desiring to be helped,
to remember what I was;--how vile and wretched a sinner,
in the days of my youth,--how young when I began to miscarry,
and what length I went in miscarriage;--what I have been since, and am to this day,
vile and miserable! for though sin be restrained, yet how little subdued or mortified;
yea,
how often does corruption in me appear and break
out,--though _man_ sees not all of that kind,
yet how much is there, and what matter of humiliation therefore!
These considerations aggravate my guiltiness and unthankfulness,
and ought to enlarge my heart to the eternal praising of the free grace of God,--that,
while _so vile and miserable,_ did yet extend and evidence _so much mercy and love,_
and while continuing so ungrateful, has not broken off his love towards me; but,
on the contrary, has enlarged it more, giving me so many proofs of it,
in such great and observable outward mercies,--and not only so,
but I trust in that which is of infinitely more worth,--even an interest in himself.
_This hope,_ I desire, notwithstanding all my misery and low condition by reason of sin,
_to hold fast;_ and, from the consideration thereof,
to have my heart forever engaged to honour and serve Him, who hath so loved me.
For, it is the _appearance_ of the grace of God that _brings salvation,_
and teacheth to deny ungodliness and worldly lusts, and to live soberly, righteously,
and godly in this present world. Titus 2:11-12.
O that this rich, and so free grace of God,
_were made more to appear unto me!_
I see but little of it, and very darkly,
and therefore is there so little denying of worldly lusts, etc.

+++[+++Alexander Jaffray, in this place, speaks of his son William`'s illness and recovery,
and of his sister Anna`'s intended marriage.]

The 15th of January, 1660, after much striving against sin,
and many vows and promises for amending some particular evils,
in which I find Satan prevail against me,
through the advantage he hath from my natural temper and disposition;
the Lord gave me in some measure to discern where the fault lies:--namely,
in not enough diligently watching over my own heart,
and listening to and receiving the motions of his Spirit,
so frequently given _by convictions_ against those evils.
By doing this, in a holy, sober, believing +++[+++manner,]
he is pleased many times insensibly to give strength,
rather than in that great and overpowering way, in which it is usually expected.
For, though _that_ may also be afterwards known,
yet ordinarily it is not the first way by which he communicates strength against corruption,
but by _this small and still voice in the conscience;_ which,
not being diligently observed and received, many times makes the creature _long,_ yea,
it may be, _all his life,_ the more unsuccessfully to strive against sin.
As the power of the enemy, at first, was received by Eve`'s hearkening to him;
so the power of the Spirit is received,
in hearkening to and receiving the reproofs thereof.
_That which checks the evil,_ that which stands against thy mind,
smiting it in its course of vanity and pleasure, _in that is the power;_
for it comes from the Spirit of power to make way for him; it lies _there,_
in that little thing of conviction, which is the first of the Spirit`'s work. John 16:8.
The power thou wouldst have for thy help to hate sin, lies hid _there,_
in that little grain of seed, which, being received and cherished,
though it may lie for a time, as grain or seed does, undiscerned,
will grow up to thy great comfort to a mighty tree.. The light, life, wisdom,
and power thou seekest after, lies hid in the Spirit`'s being present with thee:
any honest heart that is seeking him will easily acknowledge this;
but,--__here__ is the point,
wherein many an honest heart may be for a long time mistaken--they, like Elijah,
1 Kings 19:11, look for the Lord in some glorious, powerful way, and do not observe,
but slight this little, despised thing, _the small voice of conscience,_ wherein he is.
Listen to and receive this voice of God _behind thee,_ speaking in thy conscience,
Isa. 30:21, and the Lord will come in, and abide, and sup with thee, Rev. 3:20.
Every check and challenge thou hast against the evil,
or to the good thou art in pursuit of, is, and must be taken and received,
_as his knock at thy door;_ unto which, as thou openest, and receivest him,
so he comes in and abides with thee; or, if otherwise, he will depart.
The success thus to be expected, should also be _waited for:_ for the Lord,
for some other blessed end, may be exercising thee with some messengers of Satan, which,
for a time, he may continue with thee; yet, ordinarily, grace is then growing apace,
especially that grace of humility,
without which all else is but vanity:--so found the Apostle in the like case, 2 Cor. 12:7-8.
Then, often, the Lord is about to make out to the poor,
fainting creature, more of the fulness, freeness, and sufficiency of his grace,
than ever it could have expected or looked for.
Therefore, mistake not the Lord`'s way, but wait for him;--I say, _My soul,
wait thou for the Lord!_

The 9th of February, I had some comfortable use of that Scripture, 2 Cor. 10:4-5,
"`The weapons of our warfare are not carnal,`" etc.;
hoping that the Lord would help me to get what is here promised performed in my heart,
even my very imaginations and thoughts to be brought into "`subjection`" to "`Christ.`"

I was acknowledging the Lord`'s great goodness to me and my family,
in bringing us from Aberdeen to this country,
and his presence so manifested unto us since; and +++[+++desired,]
that now he would give direction what to do,
as to our further abode here or removal north again; this matter being now,
upon many considerations, necessary to be thought upon, I was, this 28th of February,
desiring the Lord`'s direction to order my thoughts respecting it.

The 22nd of March, I found the Lord speaking to my heart,
and confirming me in the truth of that which was so frequently made out to me formerly,
but not so fully received and entertained as should have been; namely,
That strength to resist, and comfort in prevailing over corruptions, will not be given,
but proportionally as light, when it is offered, is received and entertained,
and closely walked up to.
And, for this purpose, a diligent watch should be kept up,
as well for resisting the first risings and suggestions of the flesh against the Spirit,
as for receiving the motions and lustings of the Spirit against the flesh,
the one to good, the other to evil;
"`for the flesh lusteth against the Spirit and the Spirit against the flesh,
and these are contrary the one to the other.`" Gal. 5:17.
Now, my heart was directed of the Lord to consider,
that the desires of the flesh have had more easy access and better entertainment in me,
than the lustings of the Spirit; and therefore, it were well to observe,
and more diligently to wait for, the appearings of these; for,
it is said in Gal. 6:8,
"`He that soweth to his flesh shall of the flesh reap corruption,
but he that soweth to the Spirit shall of the Spirit reap life everlasting.`"
How true I have found this to be in my experience, the Lord give me rightly to consider!
And, as the first risings of evil should be in time, even in the beginning, resisted; so,
in doubtful cases, wherein, (it may be,
through the mistiness and darkness of our understandings,
by reason of our inclination to the thing,) the case
is not so clear whether it be sin or not,
rather, on this account, should we _choose_ the forbearance and abstinence from doing it.

+++[+++The writer usually notices the birth of each child, both before and after the event,
in a very pious and becoming strain.
Here he mentions the birth of a son, on the 23rd of the month called April.]

On the 29th day, my wife _caused baptize_ her son; I being,
upon the grounds formerly mentioned in my other book, in the pages 135 and 163,
+++[+++97 and 116 of this volume,]
unclear to present him, she employed my good friend, William Dowine,
to perform that duty; and Mr. John Sterling,
minister of that part of Edinburgh where I dwell, to administer the ordinance.
He was named James.
My desire of being wary and tender of giving offence,
even in those things wherein it might be but _taken_ and not _given,_
with the consideration of my former reasons, moved me thus also, at this time,
to order my carriage in this matter as formerly.

+++[+++From this page, being the 54th of the manuscript, to the 87th is wanting;
in which interval of time,
Alexander Jaffray was committed prisoner to the Tolbooth of Edinburgh.
The occasion and circumstances of this trying "`dispensation,`" are further
on explained by himself.--The next observation preserved on record,
is, the great fear he had, lest he should fall,
under the grievous and furious assaults of the unwearied enemy of souls,
who seemed let loose to buffet and well nigh to overwhelm.
In this state of mind, two Scriptures were presented to him,
as "`sad matter of meditation,`" Ezek. 24:13
and Jer. 2:19.--The Diary then proceeds.]

One of the main things I am called to learn, _under this present dispensation,_
+++[+++his imprisonment,]
is, to be more content with a suffering lot,--that great lesson,
of cheerfully taking up my cross to follow Christ; and in order thereto,
to learn to _die daily_ unto all the things of a present world;
especially to the too great and excessive desire I always have hitherto had,
of enjoying the sweet contentment of my wife and children; yea,
so excessive was I in this, as if I could have had no contentment without it.
This, the Lord is very clearly calling me off from,
that I may learn that great lesson of _parting with all for Christ,_ so +++[+++that,]
while God gives me the freedom of enjoying them,
I may labour to have it to be _in himself._--While I was thus endeavouring,
to have my heart and affections to run in a right channel to earthly
comforts,--having since my imprisonment had frequent advertisement,
that my three children, William, Rachel, and Sarah, were sick; and that,
by my wife`'s attendance on them, and her own bodily weakness,
she is unable to come to me, (though her being with me was desired,
and upon some considerations needful;)--yet, when I had least expectation,
she is unexpectedly sent to me,
having had a very prosperous voyage by sea +++[+++from Aberdeen.]
This, I was laboring to observe, as an answer to prayer; wherein,
the time of granting it was most observable; it being _then,_
when my heart was _most near_ to a contented submission in the want of the thing desired.

The 10th of November, 1660, my affliction was augmented: while even in the furnace,
my dross did sadly appear,--my strong and unmodified corruption prevailed over me,
and was very near prevailing more; but I was helped with a little help to restrain,
in time of the temptation.
But, both then and afterwards, I was seeking of God to have it more made out to me,
that my striving was from a right ground, not from slavish fear of punishment,
either temporal or eternal, but from love of Christ constraining.
I thought, my heart never sought more fervently to have this frame.
To have the heart brought and kept to the sense of love to God,
and of love so abundantly flowing from him to thee,--were sweet indeed!
Lord, help me to do it!

Divers times during my imprisonment, I was making some attempts for my liberty,
but still without success; so, I was thinking,
that there is something in it the Lord was about to bring forth,
which yet I did not know of; and was seeking of him, as I could,
to know and submit to his mind thereabout.
But, what I desired my heart might be most affected with, was,
that my mind should be so out of order and perplexed
with the thoughts of disappointments before mentioned,
as that I was rendered many times unfit for prayer, both apart,
and together with my fellow prisoner;--this was, often,
to me the greatest part of my affliction.
It evidenced, as I conceive, much unmodified corruption and weakness of faith,
much unwatchfulness and want of tenderness of heart, in judging hardly of God;
as if he would not help me,
or were unconcerned in my affliction,--in this my
sad affliction of having his face hid from me,
and shutting out my prayer.
This, I think I may, with some bit of honesty, say, as in his sight,
was sometimes more grievous to me,
than the want of any outward enjoyment that I was _put by,_
or the fear of any bodily danger that I may be under.

The 29th of December, I gave in a petition to the _Committee,_
+++[+++see <<note-KK-diary,Appendix, KK.>>]
desiring liberty to be prisoner in the city; that so I might, by my physician`'s advice,
prevent further sickness, so much threatened by the manifold distempers my body is under.
The truth of this my condition,
was witnessed by a testimony under the hands of Dr. Cunningham and Dr. Purvis,
given in also with my petition.
But this, my so just and reasonable desire, was judged otherwise of by them, and refused,
without any reason, so far as I have learned; but proceeding, as I suppose,
from the same hand that my first imprisonment +++[+++that is,
my imprisonment _in the first place_]
did, and the refusal of my other petition.
The Lord Chancellor +++[+++the Earl of Glencairn]
being by the Lord made use of, as an instrument of my affliction, without any just cause,
as to him, or, for any thing I know, to any man whatsoever.
The _LORD,_ should _He_ count with me,--just and righteous were He, if I were consumed; but,
blessed be God! _he_ has absolved, though _they_ would condemn and censure if they could.
I was desiring, as I could, of the Lord to forgive them, especially the Chancellor,
whose prejudice or other design, whatever it be, is, as I suppose,
the cause of all the present trouble I am under.
Though I desire to look to a higher hand than his in it,
and confidently to wait for another and better out-get
than he or they can hinder me from.--+++[+++No doubt he,
in this place, anticipates being delivered from the shackles of mortality; pressed down,
as he then was, by bodily and mental conflicts, insomuch,
that he was ready to despair even of life.]

The Lord, who knows me well, knows well also what need I have thus to be exercised;
the saddest part of which exercise, is, the hiding of his face,
and shutting out my prayer,--than which there can be nothing more grievous
to a tender heart:--I was desiring that it might be so to _mine;_
and hoping, that, when I know more how to prize his presence and entertain his Spirit,
he will help me, so as that I may enjoy more of him; also,
to know better how to keep free, as of sinful, so of needless, anxious,
perplexing thoughts,
by which my heart is not a little marred in the enjoying of God;--the
avoiding too of needless cares of a present world,
and of what may be dear to me in it,--to have a loose grasp of these,
and know how to lay them wholly upon God.
_This_ is _one,_ among _the great lessons,_ the Lord is giving me at this time to learn.

So far was the distemper and distraction of my spirit heightened, that, sometimes,
in the time of prayer, _while I was speaking, I was forced to be silent,
and could not utter one word,_
but was forced to desire my fellow-prisoner to proceed in the duty.
Some days thereafter, I turned over to some Scriptures,
where there is something like this case,
mentioned to have been incident to the people of God formerly; as, Ps. 77:4,
"`Thou holdest mine eyes waking;
I am so troubled that I cannot speak;`" and Ps. 39:2, "`I was dumb with silence,
I held my peace, even from good;`" and Ps. 40:12,
"`Mine iniquities have taken hold upon me, so that I am not able to look up;
my heart faileth me.`"
But, I could not so well apply these places to my own case, seeing that it appears,
the Prophet`'s +++[+++situation]
there differs from _mine._
Though I dare not altogether say, that the sense of sin was not a part of my exercise;
yet was it (so far as I could discern) more from the vanity and looseness of my heart,
needlessly burdening itself with anxious,
perplexing thoughts of my outward condition;--so little
was I rightly acquainted with the way of being about _duty,_
and leaving _events_ to God,
or making a difference between what was _necessary_ and what was _superfluous,_ +++[+++so as to be]
about these necessary things, in the way of God, without distraction; as, doubtless,
the believer may attain to,
when he goes about them upon spiritual considerations and for spiritual ends.

A main consideration in my present case, and frequently obvious to my thoughts,
+++[+++was this:]--that I was eminently called of God,
to better ordering of my whole conversation,
in walking with him all the day long,--watching _unto_ prayer,--observing
every motion and outgoing of the heart,
and admitting or rejecting them, according as they were conformable, or not,
with the rule:--as also _in_ prayer, when +++[+++it is]
to be gone about, either apart or together with others,
_to observe the motions of God`'s Spirit to enlargement;_--and,
though I durst not conclude upon _this, as a rule,_--namely, _not to pray,_
but when enlargement and inclination was thereto beforehand given,
seeing it many times comes at the time, and not before venturing on the duty;--yet,
_so to walk in every particular, in doing and saying, as that nothing may escape,
which may be feared to obstruct enlargement in prayer:_--and, on the other hand,
so to observe every passage in my whole conversation throughout the day,
and every motion of the Spirit,
as thereby the mind may be stored with good matter;--and
so may enlargement be warrantably waited for.
Thus, _to be in the fear of the Lord all the day long,_ Prov. 23:17,
is the highway to it; for so it is promised, Isa. 60:5,
"`Thy heart shall _fear_ and be __enlarged.__`"
Without this, whatever fits or flashes of enlargement may be at times attained to; yet,
no fixedness, for staying the heart in prayer upon God, is attainable.
And ordinarily,
according to the measure and proportion of the heart`'s _being stayed on God,
between the times of prayer, in close walking with him,_
so does it attain this fixedness and enlargement _in time of prayer._

But here, it is to be observed, that, in my case,
not only fixedness and enlargement +++[+++seem suspended, or removed from me,]
_but even words also, many times, so that I could not speak a word;_
and yet I could not tell wherefore, or how, it was thus with me: insomuch, that,
upon the 6th of December, I was necessitated to desire of Mr. James Simpson,
my fellow-prisoner,
_to forbear to press me any more to perform that duty of praying publicly,_
as I was before accustomed to do, in our little prison-family.
I was _above a month_ under this exercise,
before I did adventure thus to desire to be forborne, fearing to be mistaken by him,
and to give him offence.
But, having informed him a little of my case,
and of the weakness and great infirmity of my body;
and having a little reasoned with him,
about laboring to have our hearts more in a _fittedness_ and disposition for prayer,
_before venturing so rashly on it as ordinarily we
do;_--some discourse of this kind having past,
at last, he agreed for some time to forbear me.
+++[+++see <<note-LL-diary,Appendix, LL.>>]

Upon the 13th of December, my heart was some way enlarged in private prayer,
and therewith was I _desiring to be comforted;_ but with this caution,
that I should beware of placing _too much_ of my satisfaction and comfort,
upon _enlargement and liberty given in prayer._
For, though this be a rich mercy, for which God is to be praised,
and for which the heart may rejoice and be comforted,--+++[+++as the Psalmist saith,]
"`I love the Lord, because he hath heard my voice and my supplications,`" +++[+++and as Elihu,]
"`I will speak,
that I may be refreshed,`" (for much refreshment may and does come
that way;)--yet the _person_ and the _prayer_ may both be very acceptable,
_when this is wanting._
Faith is commonly _most alive,_ when _sense is least satisfied;_ humility,
and the like rooting and bedewing graces, do then ordinarily most abound.
And if _thus_ the heart does find it, or has hope (though not presently,
yet afterwards) so to find it, there may be comfort in this case; for,
this may be a part of that "`peaceable fruit of righteousness,`" which
the sad affliction of apparent desertion shall in due time bring forth. Heb. 12:11.
And therefore, +++[+++such an one]
should be _most_ stirred up and lively, when sense is _least_ satisfied, +++[+++as is intimated in]
Isa. 1:10, "`Who is among you that feareth the Lord,
that obeyeth the voice of his servant, that walketh in darkness, and hath no light?
let him trust in the name of the Lord and stay upon his God.`"

The 15th day, I was advertised,
that my daughter Sarah departed this life upon the 9th day, she having been long sick.
I was desiring of the Lord, as I could,
to have this addition of exercise sanctified to me,
and to my wife and the rest of my family.

I had been, for some time before that day,
seeking of the Lord for mercy to my son Alexander,
that he may be helped to come out of a snare that I fear he is in;
and that I may be helped, to fall upon the right way of dealing with him in that matter;
that his innocency or guiltiness may be made appear, and he not suffered, if guilty,
to deny or cover his sin, nor I too sharply to challenge him, if innocent.
My heart was some way exercised towards him with fear and love,
upon reading that Scripture, Prov. 28:13,
"`He that covereth his sins shall not prosper;
but whoso confesseth and forsaketh them shall have mercy;`" and so, found it my duty,
with all diligence to prosecute that matter, until it be in God`'s time brought to light.
