== Chapter XI.

[.chapter-synopsis]
* 1661: Alexander Jaffray laments his dull condition
* The voice of God in the conscience
* The views of Alexander Jaffray at this period respecting the people called Quakers
* The Earl of Middleton moves in Parliament for his enlargement from the Tolbooth of Edinburgh
* On minding the dawnings of the light of professors; with his own situation, as compared with that of Baruch, in Jeremiah 45:2

The most part of a month following,
my time was spent without any advantage or progress made in the way of holiness,
or prevailing over corruption; but sin rather prevailing over me,
my deadness and dulness of heart continuing:--this makes me sometimes fear much,
what may be the event of such a sad case; +++[+++especially]
at a time, when vigour and liveliness was never more called for, nor more looked for.
O that I knew, in this desertion as to sense, how I am called to live by faith;
and to believe, that He who will not take his holy Spirit from me,
will also in due time _restore unto me the joy of his salvation!_
When I have sufficiently and experimentally found, how evil and bitter a thing sin is,
how soon shall I, through grace,
have attained to the right exercise of this my sad condition!--then
may I confidently wait for the out-get as not far off.
The vision is for the appointed time, Hab. 2:3,--he that believes makes no haste,
Isai.
xxviii.16; yet in chap, li.
ver. 14, it is said, "`The captive exile _hasteneth_ that he may be loosed,
and that he should not die in the pit, nor that his bread should fail;`"--yea,
and in that case, he`'ll even bid God _make haste to help him,_ Ps. 22:19, +++[+++and again,
his cry will be in unison with David`'s,]
"`Hear me _speedily,_`" "`for I am in trouble.`"
But alas! _my_ heart is not so affected with _my trouble_ as my case requires;
dulness and deadness of heart, in this dreadful, searching time,
is my judgment and plague.
_This_ my wound stinks, because of my foolishness, Ps. 38:5;--my laziness,
my unwatchfulness, alas! has much made it so.

My thoughts have sometimes run, for remedy against this evil of unwatchfulness,
upon a resolution diligently to watch over thoughts, words, and actions, which,
doubtless, is a duty, and, when conscientiously done, will be blessed of God;
but my striving hath been for the most part in vain,
minding the thing in my own strength, more than in the strength and way of God.

And many days striving, and waiting for strength rightly to watch against vain thoughts,
etc., and for strength to come in against them, but without finding it,
I began to consider of that place, Duet. 30:11-12, etc.,
repeated Rom. 10:6-8. The voice of God in the conscience, there said to be _near,_
in the heart and in the mouth, must be more attended to, diligently watched over,
and obeyed in what it commends and reproves.
Strength against sin must be waited for; it comes in, not _all at once,_ but gradually,
as the voice of God is there minded and adverted to,
in love and tenderness of obedience to his commands.
The kingdom of heaven, thus sown in the heart,
is at first but as a grain of mustard seed; but, being attended upon diligently,
it grows to a tall tree. Matt. 13:31.
It is, by rightly observing Christ speaking in the conscience,
that he comes in with strength, to give victory over sin.
Observe, what Moses, in verses 10 and 20, calls _"`the voice of the Lord,`"_ Paul,
in verses 6 and 7, calls _Christ,_ which is _in the mouth and in the heart;_
then consider this well, that when the voice in thy heart and conscience,
which is Christ, is slighted and not hearkened unto,
strength against the sin that masters thee, is slighted and refused.
And, as he is observed, thus speaking in the conscience,
he _makes out himself_ more and more for thy comfort, making thee victorious,
conquering and to conquer.

Whatever may be of mistake in the way and opinion of the
people called Quakers _about the Light within them,_
as to the universality and operation of it; after some inquiry thereabout,
my resolution is, to _wave the debatable part thereof,_ and, as I may,
in the strength of the Lord,
to improve and make use of what truth I find _in the
thing itself_--of more duty to be on me,
to mind seriously, and more closely to walk up to, _the Light in the conscience._
For, I do verily find and believe, _there is light appearing from,
and holden forth at this time, by these despised people, in that and some other things,_
which, if prejudice and passion did not hinder, might be received with much advantage.

Upon the 16th of January, 1661, the Earl of Middleton,
Commissioner for the King`'s Majesty to the Parliament,
was pleased to move in Parliament, that, because of my valitudinary condition,
I might be somewhat enlarged from my imprisonment in the Tolbooth,
to have the liberty of the city and suburbs; which accordingly was done,
upon the 17th day; I having given bond, under +++[+++penalty]
of £20,000,
not to remove out of those bounds without leave of the Commissioner and Parliament,
and to appear when I should be cited.
+++[+++see <<note-MM-diary,Appendix, MM.>>]--My desire to the Lord was,
that I might be helped to the right understanding of his mind in my restraint,
and his way with me under it, and as to my enlargement thus far.
And, O! that my _heart_ may be _enlarged_ to wait on him,
for a right understanding to be granted to me in this thing;
that I may not miss the end of the Lord, by either despising his chastisement,
or fainting when he rebukes. Heb. 12:5.

The 14th day of February, 1661, I was led to consider more seriously,
how the Lord is pleased to help, and give in strength to the subduing of sin;
which has been long my inquiry; but, little has been learned,
as to the practical use of it.
These two particulars appeared necessary to be taken more heed to.--First,
To mind the light, as it _begins_ to appear and dawn in the conscience; for,
accordingly as this is done, the day dawns, and the day-star (that is,
Christ himself) arises; first, as the bright and morning star, Rev. 22:16, whereby,
"`the day-spring from on high`" visits such as "`sit in darkness,`" Luke 1:78-79;
and at last, "`the Sun of righteousness`" itself arises, Mal. 4:2,
and abides with them.
Secondly, The next thing to that of minding the light, is,
to wait and stand still from self-willing and acting, which darken the heart;
for "`it is not of him that willeth, nor of him that runneth,
but of God that showeth mercy.`"
The way, then, to receive the light, and strength by and from it, is, to stand still,
in a sober frame of spirit; on the one hand, not to reach after it in a self-will,
which obscures it; nor, on the other, to flee back from it,
because it makes manifest the evil deeds in their first motions; but,
to lie down under and submit to the smitings and judgments of the power of the light,
which first wounds, and then cures.
And thus it is, that the Lord communicates strength; _not all at once,_ but _by degrees,_
as the light is attended to and patiently waited for; _not by willing and running,_
but by _sitting still,_ as is said by the Prophet, Isa. 30:7,
"`Their strength is to sit still,`" and verse 15,
"`In returning and rest shall ye be saved,
in quietness and in confidence shall be your strength.`"

By reaching after light and strength in a self-will,--I mean,
_too much activity in a formal way of performing duties,
such as prayer and fasting at set times,_ and the like; as if,
by the very frequent and fervent performing of such acts, strength were to be obtained.
And thus, many times, the heart is _rather more darkened_ and +++[+++__rendered__]
_dead_ to a lively and diligent _attendance upon the voice of God in the conscience,_
than stirred up thereto; the attendance unto which,
for direction and strength to be about every action, word, and thought,
with a suitable walking accordingly, _is the chief and main means,_
by which the Lord communicates further light, life, and strength for subduing sin.

Again, by fleeing back from the light, when it makes manifest the evil deeds,
on the other hand,--I mean,
_the want of that sober and serious observation of the Lord`'s reproofs for sin,_
at its _first_ rising in the heart, which would put a stop to its _further_ proceeding.
In _quieting thy spirit,_ sitting down, as it were, satisfied,
in _confidence_ of thy help "`and strength coming, _even in this unlikely way,_
(for so it is, not only in the eyes of natural reason, but, many times,
even of enlightened reason,
until experience makes out the contrary,)--in this quietness and confidence,
shall be thy strength.

And, as in the business of having sin weakened, and strength against it attained, so,
in going about to compass any other business of worldly concernment,
_this_ must be thy way of doing it:--sit down, and leave off following thy business,
so as to be taken up with perplexing anxiety or care about it,
or the issue of it;--absolutely give up thyself to an entire dependence upon Him,
who orders everything for thy good; and doubtless,
he will make _that_ turn out best for thee,
which thou hast thought otherwise,--and in a way which thou wast not looking for.
Labour, then, to observe and follow his way of leading thee; or,
a _snare_ and _perplexity_ may more attend thee,
than thou art aware of,--even when thou hast things to thy heart`'s desire.

Some communication of light and clearness, in these respects,
has been the work of God to me, during this sad time of my imprisonment; wherein,
for the most part, I was never more under desertion,
and darkness as to _all that he was doing,_ both in judgment and mercy,
towards his people in general, and myself and family in particular.
Yet, if it shall please Him, who hath given me some way to _know_ these things,
of his goodness, +++[+++to enable me]
_savingly and experimentally, in all my conversation,
to practise them accordingly,_--I hope to bless him for thus having been with me in prison,
though I knew him
not +++[+++in these dispensations;]
for, +++[+++assuredly,]
he is faithful unto those that wait for him.

The 24th day.
I shall here shortly mention the occasion of my being made a prisoner.
It was my unclearness about a bond, presented to me to be subscribed for the peace:
to subscribe this, I was very loath, for divers reasons aforementioned, +++[+++perhaps,
in that part of the Diary which is lost.]
Yet, after some time, having considered the same, I _did_ offer to subscribe it;
though I would willingly have declined the same; mainly, because of that clause in it,
reflecting upon the carriage of many good Christians in the west, whose carriage,
though I could not approve, yet I would not willingly have concurred in the severity,
that was likely to be used in the censuring of them.
And accordingly, the Lord was pleased to order my business,
so as that I was no more put to it to subscribe the same.

Having, with too much earnestness, sought after my liberty from prison,
it was still withheld from me; and _all the means I could make use of,
both in this place and at London,_ frustrate.
At this, both myself, and some of my relations,
did evidence too much impatience and want of submission.
And yet, afterwards, the Lord brought about a great part of the thing I was seeking,
in another and better way than I did imagine.

For the Lord Chancellor had been much stirred up
to oppose me in everything I sought after,
though without a cause, so far as I yet knew; alleging,
that he had written to the King`'s Majesty particularly about me,
and until he should know his mind, he would not consent to my liberty,
nor to allow me any favour; and so was I, by his means,
continued prisoner in the Tolbooth four months, namely,
from the 20th day of September to the 17th of January thereafter.
And when all my endeavours had failed me,
and my difficulties were increased by the coming of the King`'s Commissioner, who,
as I supposed, had been by the Chancellor so fully informed to my prejudice; yet, by him,
the Lord was pleased to order the means of my relief
from the Tolbooth to the liberty of the city,
and so to restrain the Chancellor`'s prejudice against me,
that when my liberty was moved for in Parliament, he did not oppose it, though, formerly,
he would not suffer it to be mentioned in the Committee of Estates.
In the consideration of which, I thought there was given to me a very lively check,
warning me, not to be so earnest and anxiously perplexed,
about the means of my out-get from my present trouble; but _to wait on God,_
who will order what remains of it better than I could wish.

The 3rd of March, 1661, I was seeking of the Lord,
for more stayedness of heart to rely on him,
not only for the bodily out-get from my bodily restraint,
but for the sanctified use of my present case,
and that he would save me from _making haste,_--which the _believer_ does not. Isa. 28:16.
For, having been by a +++[+++writ,]
upon the 9th of February, cited to appear before the Parliament on the 5th of March,
_for divers matters of treason,_ as the summons bears; I was, this day,
seeking to know the Lord`'s mind about my appearing, and challenging myself,
for not seeking counsel of the Lord,
before I made use of means to decline the said citation; with a desire,
to submit to him as to the success of these means, and +++[+++also as to the success of the]
promises made to me _by some great men,_ to prevent my appearing that day;--hoping,
if the Lord approve me in declining to appear, he will order it for my good, and,
if otherwise, that he will direct and furnish me how to carry myself, and what to say,
if I be called there; according to the promise, Matt. 10:18,
etc. also see Mark and Luke.
Thus, may I be helped to be less anxious and perplexed,
in forethinking what to say then and there, if I be called; but wholly in that,
to give up myself to God, who has and will order what concerns me here and hereafter:
glory, glory,
and praise to his name! for he is faithful and true to all that patiently wait on _him._

The 5th of March being come, and the Parliament not sitting that day,
I thought it my duty to spend it in private,--and, as the Lord would help me,
to wait on him,
for the having my heart more drawn near him and stayed on him for direction;
being some way sensible of the great dulness and deadness of my heart,
and of my little profiting under my present exercise:--which
makes me desire much to fear and tremble before him,
lest I may be, through my negligence,
in not stirring up myself rightly to improve this present opportunity,
deprived of the advantage of _laying in provision_ from the Lord,
against the apparently _increasing storm of this dreadful day,
that seems coming on professors._

How sad has it, sometimes, been to my heart,
that so little of the true sense of this is to be found, either with myself,
or _any else I meet with or can hear tell of!_
The case _of the generality of professors of this time,_ (against whom, as I conceive,
_the Lord`'s controversy mainly is,_) in many things,
seems like unto that of God`'s people of old, as it is expressed in Isa. 42:24-25,
where he says, "`Who gave Jacob for a spoil, and Israel to the robbers?
did not the Lord, he against whom we have sinned?
for they would not walk in his ways, neither were they obedient unto his law.
Therefore He hath poured upon him the fury of his anger, and the strength of battle:
and it hath set him on fire round about, yet he knew not; and it burned him,
yet he laid it not to heart.`"
And again, li.
18, etc.
"`There is none to guide her among all the sons whom she hath brought forth;
neither is there any that taketh her by the hand,
of all the sons that she hath brought up.
These two things are come unto thee; who shall be sorry for thee?
desolation, and destruction, and the famine, and the sword: by whom shall I comfort thee?
Thy sons have fainted,`" etc.
Also Jer.
xii. "`I have forsaken mine house,
I have left mine heritage;`" etc.--"`no flesh shall have peace.`"

I think, sometimes, the words of Baruch, Jer.
xlv. from verse 2 to the end,
hold forth something like the case of the people of God in this time,--at least,
what I find to be the unhappy frame of my own heart,
which I fear may also be too much the case of others.
Baruch, in a time much like this, when the Lord was so pulling up and casting down,
(as he is also now doing,) was more taken up with his private and personal case,
than with the public condition of the work and people of God;
and therefore was he so sharply taken up and reproved of the Lord,
for his thus preferring his private case to the public,
and _then,_--in such a time of desolation and affliction,
seeking for great things to himself.

Consider, how he is challenged for what he had said.
"`Thou didst say, Woe is me now! for the Lord hath added grief to my sorrow;
I fainted in my sighing, and I find no rest.`"
There are three or four things, for which he is here challenged.

[.numbered-group]
====

[.numbered]
_First,_ His impatient bearing the common calamity of the time.
To be impatient under affliction, at any time, is wrong; but, most especially,
when the Lord`'s hand is out against his people, and he is overturning all, as it were;
then, for any of the godly to be so far from being content to suffer with them,
as to be more sensible of their particular case than that of the public; this is wrong,
and that which the Lord will reprove.

[.numbered]
_Secondly,_ Some of the _great things_ he seeks here, may be these.
Freedom from having his sorrow augmented by the addition of grief.
Freedom from fainting under his sad condition.
And yet, many times, the Lord _will_ have the grief of his children so to be increased,
as that the deliverance shall not come, until they be brought very near,--yea, sometimes,
even unto fainting.
Ps. 27:13, Ps. 61:2. And therefore, they are not, with Baruch here,
too peremptorily to seek to decline this condition; but only to seek grace,
so to be borne out, as not to dishonour God by fainting; especially,
when the cause +++[+++and need]
of it is so eminently held forth, as in _his_ time it was,
and _now_ is in _ours,_--when all God`'s precious interests, yea, piety and religion itself,
seems to be at stake.

[.numbered]
_Thirdly,_--"`I find no rest,`" says he.
He would have been in a quiet, peaceable condition,
while God was intending no such thing to his people: _this,_ God reproves him for,
and counts it _a great thing,_ sought for himself, which he would not give him,
because it is not good for him.
Neither must _we_ seek it, or count greatly of it, in such a time.
When the Lord intends a general stroke upon a people,
as here,--"`I will bring evil upon all flesh,`"--then,
the godly may not promise themselves exemption; they may, yea,
they must suffer with the rest,--at least in sympathizing, with the godly especially.

====

But yet, observe,--"`Thy life will I give to thee for a prey,`" etc.; that is,
not only the preservation of his natural life,
but a lively frame of spirit,--which is the very
_life_ of a believer`'s soul,--is here promised,
in this time of calamity, in all places where he should go.
Without this, especially in time of trouble, they dwindle and die,
and their very life becomes a burden to them.
This day, the Lord was pleased, I hope in mercy to my soul,
to open the said Scripture to me; and, in some measure, a desire +++[+++prevailed],
to sit down contentedly under the want of all the aforesaid "`great things,`"
if I may but attain to have a daily increase of _this good thing,_
my "`life for a prey;`"--a more distinct knowledge and observation of,
and conformity to the presence and power of Christ, who is the true Life within me.
