== Chapter I.

[.chapter-synopsis]
* 1653: Rise of the Society of Friends in Scotland
* Their first meetings and ministers
* 1662: Alexander Jaffray and others at Aberdeen join them
* Meetings established at Inverury, Ardiharrald, and Kinmuck
* George Gray
* 1663-4: Imprisonment of Richard Rae, George Keith, and Patrick Livingston
* Alexander Jaffray summoned before the high commission court, examined by Archbishop Sharpe, and fined, etc.

In the preceding division of this Work,
has been disclosed the religious Diary of an individual,
whose allotment and avocations in life gave him occasion
to mix freely with most classes of his fellow-men.
We have now followed him in his career, nearly through the space of half a century.
Thus far, then,
we have been very intimately made acquainted with the character of Alexander Jaffray.

Amidst all the vicissitudes of his day,
we have beheld the earnest exercise of his spirit, in a search after substantial good;
he has laid open before us, in a vivid and most ingenuous manner,
his longings for complete deliverance from the malady of our species;
and he has described some of the steppings of his soul in its progress heavenward.
We may have noticed,
what great cause of humiliation he found on account of his
early deviation from "`the path of life;`" long afterwards,
also, had he to pine over the too many successful attempts of our deadly enemy.
But it was within the scope of that gracious Arm of power, on which he depended,
to heal all his backslidings, to bruise Satan under his feet,
and fully to bring about within him the new creation in Christ Jesus.
As a part of this great work,
he found that the very bias and tendencies of his nature were gradually to be dislodged,
together with all those views and attachments,
to which by education or custom we are every one of us variously bound,
so far as these were clearly seen to be at variance with the rule of gospel light.
On our approach towards the close of the Diary,
we must have especially marked that excellent position,
towards which the mental eye of the writer so _constantly turned,_
and on which it was becoming _more and more intensely fixed;_--a
state of _pure and full reliance upon the Lord`'s direction,_
of _simple, quiet resignation unto the Lord s disposal in all things,_
according as his will and power should be made known in the secret of the heart.
This state of mind has been abundantly held up to us in various parts
of the Sacred Records,--as _a rest which remains for the people of God,_
into which the true believer, while in this state of existence,
is permitted to enter,--even all such as come unto Christ spiritually, that is,
receive him into their hearts, learn of him,
and take his yoke upon them:--these find rest to their souls.

But Alexander Jaffray was not without his companions in this description of pious dedication.
What therefore remains to be offered to the reader, of his history and religious course,
is now to be produced connectively with that of some of those Christian people,
in the north of Scotland, unto whom, henceforward,
he became firmly linked in the fellowship of Christ.

In the south of Scotland, as in the north, there were individuals,
whose minds had been for some years more or less similarly affected.
Weary and heavy laden under a sense of their own manifold shortcomings,
they yet believed there was to be known, a more purely spiritual way of worship,
and of life and conduct, than that which they,
or any with whose profession they were acquainted, had arrived at.
Deeply burdened with the formality, superstition, and will-worship prevalent around them,
and under which the various public preachers too generally detained their hearers,
these serious inquirers had separated from the several congregations of the people;
and at length some of them began to meet together by themselves,
waiting upon God in a holy silence and awful humility of soul,
for ability to draw nigh unto him in true spiritual worship.
On these occasions, they were at times made sensible of the quickening virtue, power,
and life of the Holy Spirit,
enabling some of them to speak forth the praises of the Almighty,
and from an inward experience of his goodness,
to extend instrumentally a hand of help to others.

Such religious meetings in the south of Scotland,
after the manner of the people called Quakers,
appear to have been held at a place called Drumbowy, and also at Heads,
as early as the year 1653; and the first experimental preachers,
in this manner raised up from among them, were William Osborne, a colonel in the army,
Richard Ree, or rather Rae, and Alexander Hamilton.
It is distinctly stated,
that these meetings had been established for the full space of a year,
before any in connection with the Friends found them out and visited them.
So that if, as it would seem,
James Nayler had preached in Scotland at least two years earlier than this date,
it must be concluded that he did not fall in with this little flock.
+++[+++see Appendix, A.]
They had not then, as yet, been recognised by the Society of Friends in England,
nor had they received instrumental encouragement, except from those of their own number,
to persevere in the course so remarkably opened before them.

Very soon, however,
were the feet of several gospel messengers from England turned in this direction; as,
Christopher Fell, George Wilson, John Grave, George Atkinson, Sarah Cheevers,
and Catherine Evans.
In the year 1654, Miles Halhead and James Lancaster travelled into Scotland;
and in the succeeding year, William Caton and John Stubbs.
George Fox was at Edinburgh in the year 1657; and,
in company with Robert Widders and Alexander Parker,
passed through the adjacent country in several directions,
"`sounding the day of the Lord, preaching the everlasting gospel of salvation,
and turning people to Christ Jesus who died for them,
that they might receive his free teaching.`" [.book-title]#G+++.+++ Fox`'s Journal,# 3rd edit. p. 255.

It does not appear that any of these dedicated honorers,
unless it were John Grave and George Atkinson, advanced so far as Aberdeen;
nor did Stephen Crisp, who, in the year 1659,
being then recently come forth in the ministry, left his home in Essex,
in order to bear witness to the Truth of Christ, in Scotland.
His own account of this undertaking,
although affording no additional particulars on the subject immediately before the reader,
contains so fair an illustration of the grounds and
motives of the early ministers of this Society,
in their religious embassies,
that it is thought well to give it a place in the Appendix to these Memoirs.
+++[+++see Appendix, B.]

Nearly a year prior to this, John Burnyeat of Cumberland,
was engaged in a similar concern; and he being the first who makes mention,
though very briefly, of Aberdeen, in the account he has left of his visit to that nation,
it will be proper to detain the reader by an extract from his published Journal.--"`Now,
while I was in prison, +++[+++in the common jail of Carlisle,]
something came upon me for Scotland; but, I being a prisoner,
and not yet deeply acquainted with the way and work of the Lord`'s power and Spirit,
as in relation to such a service, great was the exercise of my spirit that I went under;
and, for want of experience and a clear understanding, I was swallowed up,
and for a time quite lost in the deep, where, great was the distress of my soul,
beyond utterance!
But, the merciful God, by his powerful arm, and healing, saving Word of Life,
did restore and bring up my soul out of the deep, where it was for a time buried,
and renewed life and understanding, and caused the light of his countenance to shine,
and the sweetness of his peace to spring; so that I may truly say,
he caused _the bones that he had broken to rejoice._
And then, when he had thus crushed, and humbled,
and let me see how he could make all things become as nothing again,
and so hide all glory from man,--then, in His goodness, he revealed his glory, and power,
and presence, and reviving life, and so opened to my understanding his good pleasure;
which, with all readiness and willingness of mind, I gave up unto,
in my heart and spirit.
After my being kept about three and twenty weeks in prison, I had my liberty;
and so came home, and followed my outward calling that summer;
and grew more and more into the understanding of the mind and will of the Lord,
in that which I had a sight of, while I was in prison.
And so, keeping to meetings, and waiting upon the Lord,
in a true travail of spirit after more acquaintance with him,
and more enjoyment of his power and word, I grew, not only into an understanding,
but also into a degree of strength and ability fit to answer that service,
which the Lord had called me unto.

"`And so, then, in the faith, that stood in God`'s power,
about the beginning of the eighth month, 1658, I took my journey into Scotland,
and travelled in that nation about three months;
and was both in the north and west of it, as far north as Aberdeen,
and back again to Edinburgh, and so down west to Lithgow, Hamilton, Ayr,
and as far as Port Patrick; and back to Ayr and Douglas.
And our service was at their _steeple-houses,_ and markets, and other places,
where we met with people; and sometimes at Friends`' meetings, where there were any.
And our work was, to call people to repentance, out of their lifeless,
hypocritical profession and dead formalities,
wherein they were settled in the ignorance of the true and living God;
and so to turn them unto the true light of Christ Jesus in their hearts,
that therein they might come to know remission of sins,
and receive an inheritance amongst the sanctified.
And, being thus clear of that nation, we returned into England,
and came over the water to Bowstead-hill, the first day of the eleventh month, 1658.`"
+++[+++see Appendix, C.]

[.small-break]
'''

The gospel messages of these and other zealous witnesses,
reached the consciences of many who heard them.
Yet, with regard to Aberdeen and the district thereabouts,
no open espousal of the tenets peculiar to the people called Quakers took place,
until towards the end of the year 1662; when William Dewsbury was drawn,
in love to these prepared and panting souls,
to proclaim among them "`the acceptable year of the
Lord,`" even _deliverance from the bondage of corruption,
by the law of the spirit of life in Christ Jesus._
Thus was the remarkable work of convincement,--which had been secretly going on,
in some of their hearts for several years,
through many deep conflicts of spirit,--helped forward to such a point,
that they were made willing, even in all things, to take up the daily cross,
_though in various respects as bitter as death,_
and to follow the guidance of Christ by his Spirit within them,
whithersoever he should be pleased to lead.

On the list of this little, but noble band, the name of Alexander Jaffray stands foremost.
He is described, in the ancient Record which forms a ground-work to this History,
as having been chief magistrate of the city of Aberdeen,
_"`and a man of great account as to religion, among the highest professors all along.`"_
With what lively emotions of entire satisfaction,
these doctrines were likely to have been embraced, at this time, by these individuals,
may best be conveyed in his own language:--that,
when first he heard that God had raised up a people in England,
directing all to his pure light, Spirit, and grace in their own hearts,
as the most sure Teacher and Leader into all truth, religion, and worship;
_his very heart did leap within him for joy._

In an early part of the preceding Diary,
the Writer makes some favourable allusion to the principles of the Independents,
nearly at that time, when, from conscientious motives,
he thought it his duty to withdraw from communion with the Scottish Presbyterians.
There is little doubt, but that, up to the season when the narrative breaks off,
he belonged to no distinct society of Christian professors.
After that period,
during the short space which intervened before his joining the Society of Friends,
he may possibly have been _considered_ an Independent;
agreeable to the statement given of him in that excellent publication, now called, [.book-title]#Piety Promoted.#
But hitherto, it is evident, he represents himself to us,
as _reserving himself_ for some further manifestation of a more excellent way,
than that which had hitherto come within the line of his experience.
The frame and breathing of his spirit seems constantly to have sent forth this petition,
_"`That which I see not, teach thou me;`"_ whilst his unshaken,
uniform dependence on Divine direction and help,
would doubtless oftentimes bring home to him the
Scriptural promise and accompanying exhortation, Phil. 3:15-16.
"`And if in any thing ye be otherwise minded,
God shall reveal even this unto you.
Nevertheless, whereto we have already attained, let us walk by the same rule,
let us mind the same thing.`"

It is to be regretted, that no documents have been met with,
throwing light upon that interesting, though small portion of his life,
which extends from the last date occurring in the Diary,
to the time when he was actually united to the Society of Friends;
a period of about a year and a half.
And truly, the few scattered notices respecting him, which afterwards occur,
or of events in which he was concerned, however valuable so far as they go,
the reader will observe,
set forth but imperfectly the retiring qualities of his spiritual habit and walk.
For, while the same general features of his character as hitherto portrayed,
are plainly discernible throughout, matured indeed by wisdom,
even that which is from above,--"`pure, peaceable,
gentle;`" yet are we in great measure deprived of
all that near access to the workings of his soul,
unto which the form of a Diary admits us.

Among the names of those others, who are recorded as the first Friends in Aberdeen,
convinced by the instrumental means of William Dewsbury, are Alexander Gellie; Margaret,
wife of Gilbert Molleson, a magistrate of the city,
whose spiritual endowments gave her eminence and weight among the strictest classes;
Elizabeth, wife of Andrew Goodall, merchant; Margaret, wife of John Scott,
also a magistrate of the same place; with some others.
+++[+++see Appendix, D.]

It will not now be doubted,
that the motive influencing persons in these stations of life to such a change,
was a conscientious desire to yield unreserved obedience
to the teachings of the grace of God.
It may also be as safely asserted, to have been their earnest prayer,
that they might in no wise limit or exceed these,
nor yet confound them with the dictates of human policy, custom, tradition, or imitation.
Widely different, however, were at that day the conclusions taken up respecting them,
especially by the public teachers of religion;
nor can the virulent opposition to these views, and to all who held or propagated them,
be in any wise palliated or disguised.
Robert Barclay, who some years after became one of their number,
in the preface to his first piece,
entitled "`Truth Cleared Of Calumnies,`" forcibly but justly
describes the low estimation in which the Friends were held,
not only at this time,
but even before any settlement of them had been formed in this section of Scotland.
The passage alluded to, is as follows.

"`After the Lord had raised up the witnesses of _this Day,_
and had opened in them and unto them the light and glory thereof,
divers of them at sundry times were moved of the Lord to come into these parts,
and unto the town of Aberdeen, in love to the seed which _there_ was to be gathered;
but their acceptance for divers years together, was very unsuitable.

"`For the enemy that had wrought, and was exalted in the mystery of iniquity,
to darken the appearance of this Day, had prepared and stirred up his ministers,
to resist them and their testimony, by aspersing them with many gross calumnies, lies,
and reproaches; _as demented, distracted, bodily possessed of the devil,
practising abominations under colour of being led to them by the Spirit;_
and as to their principles, _blasphemous deniers of the true Christ, of heaven, hell,
angels, the resurrection of the body, and day of judgment; inconsistent with magistracy,
nothing better than John of Ley den and his accomplices._
+++[+++see Appendix, E.]
This was the vulgar and familiar language _of the pulpits,_
which was for a time received for unquestionable truth; till about the year 1663,
some sober and serious professors in and about the said town,
did begin to weigh these things more narrowly,
and find _the savour of that Life_ in the testimony of this so much reproached people,
which _some years before_ had stirred in others,
who were now come to a great loss and decay.
And this gave them occasion to examine the principles and ways of that people more exactly;
which proving, upon inquiry, to be _far otherwise_ than they had been represented,
gave them a further occasion to see the integrity and soundness
of that despised people and of their principles,
on the one hand; and on the other,
to see the prejudiced disingenuousness and enmity of their accusers.
In _these,_ the Lord caused his word to prosper, (who were _few in number,
yet noted as to their sobriety in their former way of profession,_)
and raised them up to own that people and their testimony,
and to become one with them.`"

Alexander Jaffray, shortly after his convincement, removed from Aberdeen to Inverury,
sixteen miles distant, and was instrumental in settling a meeting there.
By this means, some, hearing the joyful sound of Truth, gladly closed in with it,
as a day of merciful visitation, for which their languishing,
weary souls had long waited.
Among these, were James Urquhart and his wife, Robert Gordon, and John Robertson.

About the same time were also joined to their number, George Gray and Nancy Sim,
persons of very good repute,
both with regard to their religious qualifications and worthy conduct;
insomuch that the appointed minister of the parish where they dwelt,
Samuel Walker of Monkeggie, boasted of them, saying, _that he had a weaver,
and a poor woman, whom, he would defy any of the Quakers to equalise,
either for knowledge or good life._
But when, shortly after, these very individuals, his hearers,
respecting whom he was so highly opinionated, withdrew from under his teachings,
and joined the people called Quakers, this minister was exceedingly incensed.

Respecting George Gray, it should here be briefly stated, that he afterward became,
through sincere and steadfast adherence to the intimations of Christ`'s Spirit,
a highly valued servant of the gathered church; being called into the ministry,
during the time of his subsequent long and hard imprisonment at Aberdeen.
Poor as to this world, and barely acquainted with the very rudiments of learning,
_the word of God`'s wisdom, the word of faith, dwelt richly in him;_
and his understanding being much enlarged in heavenly experience, he brought forth,
as a faithful steward, the good things committed to him,
to the great refreshment of the Lord`'s heritage,
and to the building up of many in the Truth.
As none could justly blame the upright, even tenour of his conduct, so was he,
through watchfulness, preserved and directed in the exercise of his ministerial gift;
nor could any critical opposer, it is said, ever find him wrong in a word.
On the other hand, many persons would confess their admiration at the excellent matter,
utterance, and pertinent connection observed in the testimonies of one,
_so devoid of acquired learning, and yet,
so thoroughly furnished in all respects unto his holy calling._
Thus, in this instance, was very clearly held up to view,
what it is that constitutes _the best adorning_ of gospel preachers,
and what is the only right qualification for speaking "`as the oracles of God.`"
+++[+++see Appendix, F.]

Nancy Sim, who was also in low circumstances, readily opened her house,
at a place called Ardiharrald, for the purpose of keeping religious meetings.
But the people of the neighbourhood flocked to them so greatly,
that her house would by no means contain those who assembled; on which account,
they were often obliged to meet in the open field.--Thus did the word of the Lord prevail,
which had been proclaimed among them,--the word of his grace,--unto which
they had been commended,--and it "`was precious in those days.`"
Such as were made willing to yield to it, esteemed it more than their necessary food;
indeed, it was with them, in their measure, as it was with the Prophet Jeremiah,
where he says, "`Thy words were found, and I did eat them;
and thy word was unto me the joy and rejoicing of my heart.`"
It is evident, they received it "`not as the word of men, but as it is in truth,
the word of God,`" so that it effectually wrought in them, being mixed with faith.

Among others who "`honoured in the Lord,`" Elizabeth Johnston, daughter of a physician,
Dr. William Johnston, being a faithful and enlightened woman,
became "`a succorer of many,`" and a considerable "`helper in Christ;`" her mother,
Barbara Forbes, who is mentioned in Jaffray`'s Diary, having also joined the Society.
But the principal instrument made use of, in these parts,
for the gathering of many from the barren mountains of an empty profession,
to feed in the green pastures of life, under the leadings of the Shepherd of Israel,
was Patrick Livingston, whose name will frequently occur in the course of this History.
He was born near Montrose, and was convinced about the year 1659.
Near three years after this, coming northward in the work of the ministry,
when but twenty-eight years of age,
the good Husbandman was pleased singularly to own
and bless his faithful honours by evident fruits;
so that he became the means of planting a flourishing meeting of Friends at Kinmuck,
which afterward grew to be the largest in the nation,
and is still upheld in the same place to the present day.
The following is described as one out of the many remarkable opportunities,
which it is said that he had with the tender and serious people thereabouts.
While he was sitting waiting on the Lord,
among the first handful that were gathered into the
like profession in that part of the country,
there being many other persons present,
the Friends were much bowed down and low in their minds,
in a sense of "`great straitness and hardness over the meeting.`"
Patrick Livingston broke silence, by declaring, that,
for a sign and token of the lovingkindness of the Lord,
towards a seed or remnant raised and to be raised up in that country,
_He would reveal his glorious presence among them in a wonderful manner,
before they parted._
So little appearance of this was there, when he spoke, and for a while after,
that some of the Friends present who were weak in the faith, fell under a great concern,
lest this should not have been by any means fulfilled.
But the Lord, who never fails to be a very present help in time of need,
unto all his patient, dependent little ones,
was pleased at length to grant a plentiful outpouring
of his mighty power through his servant,
"`even as a rushing stream, to the overcoming of the hearts of his children,
and to the amazement of the people; of which circumstance,`" says the account,
"`there are yet living several witnesses.`"

The public preachers of Aberdeen now began to be considerably alarmed,
at finding that so many, both of the higher as well as lower classes,
withdrew from their communion.
By calumnies and reproaches poured from the pulpits,
they endeavoured to incense the magistrates to suppress this people,
and to raise among the ruder and less intelligent of their
hearers a spirit of indignation and of vindictive abuse.
Hence it was, that whenever any of this persuasion appeared among them,
they were received by the populace with stoning and beating in the streets,
pulling by the hair, and other lawless abuses, which the magistrates,
instead of reproving, too often countenanced.
By their order, Richard Rae, before mentioned, a shoemaker of Edinburgh,
was arrested and kept close prisoner in the Tolbooth or public prison of Aberdeen,
for the space of six months.--This seemed like the signal for the
commencement of a determined course of persecution--a persecution,
unattended indeed by those extreme acts of savage cruelty,
which were exercised towards the Presbyterians in the south of Scotland,
about the same period; and yet, embracing such a series of unrighteous proceedings,
carried on against a harmless and unresisting people,
as cannot fail to prove affectingly interesting to the mind of every considerate Christian.
And why?
Because he loves to mark the progress of "`the true Light`" of the gospel,
in dispelling the various shades of apostasy and spiritual darkness;--__on this account,__
must he own and duly appreciate _every stand_ that has been made or is making,
in integrity, meekness, faith, and patience,
against the delusions and encroachments of antichrist.
+++[+++see Appendix, G.]

In the next year, 1664, George Keith,
who had been convinced of the rectitude of the doctrines held by Friends,
coming to visit his brethren at Aberdeen in the love of the gospel, was cast into jail,
and detained there ten months.
Patrick Livingston also, for the same offence,
became his fellow-prisoner during the space of seven months.
While they were here, one Peter Strachan, son to Andrew Strachan,
the public minister of Kintore, confined with them for debt or some misdemeanour,
violently beat and abused them: and, taking away their papers,
sent them to the magistrates.
This man afterwards became troubled in his conscience; and,
under a sense of his wickedness in thus ill-treating the innocent, cried out fearfully,
that the judgments of God were upon him for his behaviour towards them,
and repeatedly begged forgiveness of them in the presence of several witnesses.
+++[+++see Appendix, H.]

But the envy of the professed ministers of Aberdeen, George Meldrum and John Menzies,
appears to have been now principally bent against Alexander Jaffray.
His blameless life, and the high estimation in which he had for many years been held,
by the more candid and serious inhabitants,
appeared in their view to render him the more dangerous seducer.
They accordingly stirred up against him Patrick Scougal, Bishop of Aberdeen,
and through him the Archbishop Sharpe also.
Upon this, he was summoned to appear before the High Commission Court of their church;
and on that occasion was enabled to bear a faithful testimony to the Truth of Christ,
experiencing his promise to be fulfilled, Luke 21:15,
"`I will give you a mouth and wisdom,
which all your adversaries shall not be able to gainsay or resist;`" for,
even the Archbishop himself, who condescended to confer with Alexander Jaffray,
could get no advantage in argument against him.
Nevertheless, to satisfy these ministers, the sentence of the court was,
_that he should be confined to his own dwelling-house, and keep no meetings therein,
nor go any where without the Bishops licence, under the penalty of a fine of 600 merks,_
Scots money, which is £33. 15s. sterling:
this sum they esteemed to be one fourth part of his yearly rents.
To such an unjust sentence his answer was,
that _it was better to obey God than man:_--and this obedience, afterward,
cost him various sufferings.

Some readers may need to be reminded,
that the Episcopal form of church-government was reestablished in Scotland in 1662,
after an interruption of twenty-four years.
Sharpe was made metropolitan.
He is described by some writers to have been one of the
most unprincipled men of the age in which he lived.
And certainly, to go no further than the testimony of Bishop Burnet,
this character of him is amply confirmed.
With regard to the other bishops in general, and of Scougal in particular,
that writer thus speaks, in his History.
"`I observed the deportment of our bishops was, in all points,
so different from what became their function,
that I had a more than ordinary zeal kindled within me upon it.
They were not only furious against all that stood out against them,
but were very remiss in all the parts of their function.
Some did not live within their diocese; and those who did,
seemed to take no care of them: they showed no zeal against vice:
the most eminently wicked in the county were their particular confidants:
they took no pains to keep their clergy strictly to rules, and to their duty:
on the contrary, there was a levity and a carnal way of living about them,
that very much scandalized me.
There was, indeed, one Scougal, Bishop of Aberdeen, that was a man of rare temper,
great piety, and prudence: but I thought he was _too much under Sharpe`'s conduct,_
and was at least too easy to him.`"
Burnet`'s History, vol. i. p. 304.
It was scarcely to be expected,
that men of this stamp should be mild and temperate
in the exercise of that secular and inordinate power,
with which they were now invested.
In fact, one of them,--"`so great a man as Leighton,`" who
had indeed accepted the bishopric of Dunblane,
but with the single view of endeavouring to promote
the harmony of the church of Christ,--often declared,
in Burnet`'s hearing, "`that, in the whole progress of that affair,
+++[+++the setting up of Episcopacy,]
there appeared such gross characters of an angry Providence, that,
how fully soever he was satisfied in his own mind as to Episcopacy itself,
yet it seemed _that God was against them;_
and that they were not like to be the men that should build up his church;
so that the struggling about it, seemed to him, like __a fighting against God.__`"
