== Chapter III.

[.chapter-synopsis]
* 1665: George Keith`'s ill-usage, and the imprisonment of Alexander Forbes and others
* David and Robert Barclay join the society
* Some account of them, especially of David Barclay previous to this circumstance.

George Keith, in the year 1665, under a sense of religious duty towards his Maker,
and with a desire for the good of souls,
publicly confessed and upheld "`the way of the Lord,`" in an address to
the congregation who assembled at _"`the great place of worship,`"_ in Aberdeen.
In attempting that service, he was violently assaulted, beaten,
and knocked down by one James Horne, their bell-ringer.
It was observed, that, a short time after this, the same individual,
going up the steeple to ring the bell, suddenly fell down through a hole,
above four stories high, was instantly killed by the fall,
and on the very same place of the pavement,
where he had beaten the Friend above mentioned.--The reader is
of course left to make his own reflection on this latter circumstance;
whilst the conduct of such as George Keith, may be further explained in the Notes.
+++[+++see Appendix, K.]

The following year, Alexander Forbes of Achinhamper,
who had then lately shown a decided preference for the Friends,
having withdrawn from the teachings of James Gordon, minister at Alford,
in whose parish he dwelt,
the latter individual thought proper to excite the Bishop of Aberdeen to prosecute him;
upon which, at length,
both he and Alexander Gellie were apprehended and carried away to Edinburgh,
being imprisoned in the Cannon-gate Tolbooth there,
whither they were committed for six months.
Their deliverance was, however, happily effected before that time had expired,
and without a violation of conscience on their parts,
or submission in any wise to the will of their adversaries.--Towards
the close of the same year,
John Glennie, James Urquhart, John Brown, and William Gellie were also taken,
while at their own place of worship,
and imprisoned for two months in a place called the _Iron-house_ at Aberdeen,
where the worst of felons and murderers were usually confined.

But by such rigorous proceedings, those termed the clergy did not attain their object;
on the contrary, others from time to time fell off from their congregations,
and joined the despised people called Quakers.
This year, in particular, 1666, David Barclay of Ury,
descended from "`an ancient and honourable family among men,`" and,
about the close of the same year, his son Robert,
openly and thoroughly attached themselves to this Society.
Of these distinguished characters, a small memoir was long since published;
and of Robert Barclay, in particular, a more recent account,
well known to many readers of the present volume.
The transactions of their lives are, however,
so closely mixed up with this period of our church history in the north of Scotland,
that it becomes needful to revive them in the present shape;
interspersing also some additional particulars, from sources not hitherto availed of.

With regard to "`Colonel David Barclay,`" as he did not
enlist under the pacific banner of the cross of Christ,
till past the meridian of life,
it is thought proper to travel somewhat out of the course of this history,
by touching upon his career before he became a Friend.
This digression, it is hoped, will not prove devoid of interest and instructive bearing.
It is after having taken a view of the stations occupied
by such individuals in the world,
and their connection and influence with those in political power,
that we are more fully prepared to realize the difficulties
of the path they afterward had to walk in;
at the same time that we are better qualified to appreciate the depth, and strength,
and beauty of that spiritual work, which was effected in them.
We can then more duly estimate what it cost them, _to refuse the glory of this world,_
with all the various opportunities that presented, of gratifying "`the lust of the flesh,
the lust of the eyes,
and the pride of life;`" as well as to accept with cheerful resignation
"`the reproach of Christ,`" _by becoming fools for his sake,_
that so they might be "`to the praise of his glory.`" Eph. 1:12.

[.small-break]
'''

David Barclay was born in the year 1610, at Kirktounhill,
the seat and birthplace of his father, of the same name; who, living much at court,
and being of an easy disposition, became embarrassed in his affairs,
and was obliged in 1633 to sell the ancient estates,
which had been held by the family for upwards of five hundred years.
He, however, paid off his debts, and gave his son David, with the rest of his children,
a liberal education.
David went on his travels into (Germany,
and there enlisted as a volunteer in the army of Gustavus Adolphus, King of Sweden; but,
after having been engaged in many battles, and quickly risen to the rank of major,
on the breaking out of the civil wars in his native country, he returned home.

Being a man of "`great modesty,`" he seldom if ever adverted to his military actions;
nor is it likely he would do so, after he became one with the Friends in sentiment,
as to the origin of "`wars and fightings,`"--except it were to testify against them.
Some of these circumstances of his life, however,
are alluded to in the histories of the times,
_and also bear upon certain points connected with the foregoing Diary;_
they are therefore deemed by no means unfit to have a place in these Memoirs.
Circumstances of this description,
like those of a similar cast relating to Alexander Jaffray,
may assist the reader in contemplating the strong contrast, there is,
between views of worldly and warlike policy,
such as _then_ influenced the conduct of these individuals,
and that line of conscientious practice taken up by them in _after life,_
which induced them to become comrades in the spiritual warfare.

The following narrative is taken, nearly verbatim,
from a manuscript now before the Author, written by the grandson of Robert Barclay;
his ultimate or chief authority, however, with regard to David`'s military exploits,
seems to be one Gordon of Sallach, who, it it said,
wrote an account of the Sutherland family, in which he relates many events,
that he had himself witnessed.

"`Colonel Barclay was sent with an army, in 1646,
to quell an insurrection made by the Earl of Crawford, who,
with a number of Irish as well as Scottish forces,
had wasted the north parts of the kingdom, and burnt several towns.
But, the Colonel coming up with him at Banff, entirely routed him.`"

The above writer states, that, in the same year "`Major General +++[+++afterwards, the Earl of]
Middleton, and the Colonel were sent with an army to relieve Inverness,
then besieged by the Marquis of Montrose and the Earl of Seaforth.
The Colonel, crossing the river with his regiment of horse above the town,
and falling upon Montrose`'s forces, routed both him and Seaforth,
and made both flee to the mountains; having taken all their baggage and cannon.
From thence they went to Chanrie of Ross, which they took after four days`' siege,
where they seized all Montrose`'s ammunition; after which,
they restored the castle to the Lady Seaforth, whom they used very discreetly.`"
"`On their return to Edinburgh, the Marquis of Huntly attacked the town of Aberdeen,
where Colonel Henry Barclay, Colonel David`'s relation, lay with two regiments; who,
notwithstanding all the defence he could make, with the assistance of the inhabitants,
became master of the place, Colonel Henry being taken prisoner,
with about twenty officers, and a number were killed.
Upon which the Parliament, in 1647, sent the General and Colonel David to reduce Huntly,
who, upon their approach, retired to the Highlands.
And, that he might not return, they took all the castles and towns,
in which were placed garrisons; Colonel David being appointed Governor of Strathboggie,
then a strong place, and Middleton Governor of the Bog of Gicht, now Castle Gordon.`"

The spring following, according to the same author,
David Barclay married "`Catherine Gordon,
eldest daughter of Sir Robert Gordon of Gordonstoun,
second son to the Earl of Sutherland.
This Sir Robert, the first Knight Baronet of Scotland,
was a man of great parts and honour, which, with his near relation to the Royal family,
made him much esteemed at court;
he being second cousin to King James the 6th of Scotland and 1st of Great Britain,
to whom and his son King Charles the 1st, he was Gentleman of the Bedchamber,
Vice Chancellor of Scotland, and Privy Counsellor.`"

"`David Barclay continued a Colonel of horse,
being appointed to command in the shires of Ross, Sutherland, and Caithness.
The nation being at that time alarmed with the sad condition of King Charles the 1st,
then in captivity in the Isle of Wight, came to the resolution to rescue him;
and the Parliament, for that purpose, having sent an army into England,
under the command of the Duke of Hamilton, the protection of the kingdom,
(and of the Prince of Wales`' person,
who was expected to land in Scotland,) was committed to three individuals:
the Earl of Lanark, who was Hamilton`'s brother, and the Laird of Garthland,
each with 500 horse, were stationed south of the Tay,
and Colonel David Barclay with the same number, besides his own regiment,
was to keep in order the country north of that river.
This trust was executed on the part of the latter, with vigour and fidelity.
But after Duke Hamilton`'s overthrow at Preston, the opposite party,
being assisted by Cromwell,
procured the engagement to relieve the king to be declared unlawful;
in consequence of which, all the officers were turned out of their posts.
Among these, Colonel David Barclay was one;
nor does it appear that ever after he was concerned in military affairs.`"

The above account of his conduct, is said to have been given,
in a manuscript preserved in the family, _all written with his own hand;_
he also takes notice, that being, for the reason just mentioned,
rendered incapable of further service to his Prince,
he retired to Gordonstoun for several years.
During this time, the Earl Marischall, being taken prisoner at Eliot, in Angus,
by the English under General Monk, and his estate forfeited, they seized it,
together with the lands of Ury, which the Colonel had purchased from him; on the pretext,
that the _rights_ (or perhaps _writings)_ of the latter were not fully completed.
Upon this, by the advice of the Earl and his other friends,
he availed himself of the interest he had by his wife`'s cousin-german,
the Earl of Sutherland, and other relations,
and became elected member of Parliament for that shire; and in the next Parliament,
by his own interest, for the shires of Angus and Kinkardine or the Mearns.
This was looked upon as the only method left, to get possession of his own estate of Ury,
as well as to do service to his country and friends,
particularly the family of Marischall, towards whom he bore a great respect.
With regard to these objects, he was so successful, that he got access to his own lands,
and obtained large concessions in favour of the Earl Marischall`'s family,
so that there was little made by that forfeiture to the party then in power.
This, with his strenuous endeavours on behalf of the other forfeited nobility and gentry,
made him so popular, that he was again, in the year 1656,
elected member of Parliament for those two shires;
where he vigorously opposed and voted against Cromwell`'s being made King.

After this, he disentangled himself from all public affairs, living in much privacy,
sometimes at Edinburgh, and sometimes at Gordonstoun, with his mother-in-law;
until the month called March, 1663, when he lost his excellent wife, Catherine,
aged forty-three years.
About the same time, in addition to this source of affliction, he was,
by order of the government, after the Restoration,
committed close prisoner to Edinburgh Castle.
This treatment was said to be occasioned by his having been "`a trustee
under the Usurper,`" as Mackenzie`'s [.book-title]#History of Scotland# states;
and yet he had suffered in the cause of Charles the 1st,
not only by being thrust from all his posts on that account,
but by having his estates seized for several years.
It was even suspected, there was a design that he should forfeit both estate and life,
had it not been for the strong interposition of the General, and then Earl of Middleton,
under whom he had served in the late civil wars; and by whose interest,
as the King`'s Commissioner to the Parliament, he was liberated,
without any thing being laid to his charge, or reason given for his commitment.

David Barclay had now passed through many vicissitudes,
had tasted of prosperity and adversity, and by his general conduct among men,
had obtained the approbation of most with whom he had been concerned.
His retirement from the world, had given him a sight of his own heart,
and of the uncertainty of all temporal things;
each day giving fresh evidence of their instability in every condition,
from that of the King upon his throne to that of the most destitute.
He observed too, that neither justice nor innocency could protect, nor good offices done,
secure a man from malice, envy, and persecution.
In this perplexity, he thought it was high time for him,
who had spent so much of his day in the service of others,
(being then between fifty and sixty years of age,) to bestow
the remainder wholly in the service of God,
and by so doing more directly answer the great end of his creation.
Under these considerations,
he looked around him with the greatest anxiety and earnestness, to know,
in the midst of so many pretenders, what society of Christians to join with.
One observation he had made upon all the different persuasions,
that each of them laid claim to be the only true Christians, yet not only differed from,
but persecuted one another with the greatest violence,
as opportunity came into their hand; and this,
for the very reason which had rendered themselves the object of persecution, namely,
their differing from others.
His intercourse with the world, both abroad and at home,
had given him ample occasion to make such remarks on their _practice;_
while the perusal of their several systems of divinity, whilst in his retirement,
had afforded him full insight into their several _credenda._
Upon the whole, he concluded, that the Christian religion _must in itself be very good,
and the only true religion,_ since all valued themselves upon their claim to it;
and further, that all could not be right, when they so widely differed one from another.
To relieve himself by arriving at a determinate choice,
he betook himself to the close reading of the New Testament,
as the only certain way of knowing the religion of Christ in its primitive purity.
By such means was he brought clearly to see, in what this essentially consists,
and what was the shape its several professors had put upon it.
He saw, that in itself it was "`righteousness, and peace,
and joy in the Holy Ghost,`"--that it taught to be humble, patient,
self-denying,--to endure all things,
to suffer all things;--not to place our happiness or comfort on this world,
or the things of it.

Whilst under these considerations, he heard of a people, called in derision Quakers,
who under great reproach for their singularity and abstractedness from the world, bore,
in much plainness and simplicity,
a remarkable testimony against all the follies and vanities of the world,
as well in their practice as in words; and he considered within himself,
that if they were really such as even their enemies were forced to acknowledge,
there must be somewhat extraordinary about them.
These his private thoughts, he afterward communicated on several occasions to his friends.

Accordingly,
with the greatest earnestness did he set about an
examination and inquiry relative to _this way,_
which was indeed "`everywhere spoken against.`"
Being in London about this time,
he "`had converse with several Friends both there and elsewhere,`"
as the Record preserved at Ury distinctly states,
"`whereby his mind became convinced`" with regard to the tenets held by Friends.
Some months after this, being a prisoner in Edinburgh Castle, as before recited,
together with John Swintoune,
respecting whom some particulars have already been given in a Note to Jaffray`'s Diary,
David Barclay was considerably "`strengthened and
assisted`" instrumentally by this individual,
in making an open avowal of his sentiments.
It is said of Swintoune,
that during his imprisonment he was more concerned to spread the views he had adopted,
than to defend his own life; and it appears, that on this occasion,
the Governor of the Castle, to prevent the infection of his opinions,
shut him up for several weeks close prisoner, debarring him from all sort of intercourse.
With much wisdom, however, as well as patience and caution,
did David Barclay pursue his inquiry, before he moved in so important a step.
He ascertained,
that notwithstanding all the calumnies and reproach with which their enemies loaded them,
this class of men were a sober, plain, self-denying, religious people;
that they never shunned suffering or persecution for their testimony;
that they gave up _their all_ for the sake of their religion;
_that they had beat their swords into ploughshares, and their spears into pruning-hooks,
and neither taught nor exercised war any more,--the certain mark of the gospel times,_
according to the language of the evangelical prophet, Isa. 2:4. Further,
_that they loved one another,--the infallible character our blessed Saviour hath given,
of their being his disciples,_ John 13:35; in short,
that their practice and principles were most agreeable
to the primitive standard recorded in the New Testament.
He therefore came to this fixed and certain conclusion
within himself;--__if Jesus Christ hath followers,
disciples, or a visible church upon earth, these must be they.__
So, upon full conviction, he joined with them,
and became eminent for his religious and exemplary life, as formerly for his bravery,
resolving to suffer indignities and injuries for conscience
sake,--a virtue he was before very much unacquainted with.

This change in his resolutions, belief, and practice,
made him suffer nothing in the esteem of the generous and better part of his acquaintances;
but it had the contrary effect among the more mean and malicious;
and the laws being then against all meetings for worship,
not conducted after the prescribed national standard,
these greedily laid hold of the occasion, to molest so peaceable a people;
although it was clearly the main intention of the government,
in the enactment of these laws,
to put down those field conventicles of armed men among
the Presbyterians in the south and west of Scotland,
where few of the Quakers ever were disturbed.
In the north, on the other hand, chiefly at Aberdeen,
they were often "`mobbed by the dregs of the town, set on by the zealots of that day.`"
It was remarked,
that none bore these indignities with greater calmness than did David Barclay.
One of his relations, upon an occasion of uncommon rudeness,
lamenting that he should be now treated so differently from what formerly he had been;
he answered, _that he found more satisfaction as well as honour,
in being thus insulted for his religious principles, than when, some years before,
it was usual for the magistrates, as he passed the city of Aberdeen,
to meet him several miles, and conduct him to a public entertainment in their townhouse,
and then convey him so far out again, in order to gain his favour._

His humility and sincerity as to religion was "`most remarkable in his whole
conduct;`" but his deportment is said to have been particularly awful and striking,
when engaged in public prayer.
In his person, he is represented as "`one of the largest, strongest,
and handsomest men that could be seen among many thousands: his hair,
as he advanced in life, became white as the flax, but bald upon the top of his head,
so that he wore commonly a black satin cap under his hat.`"

It appears, that David Barclay resided at Edinburgh at the time of his convincement,
which, as before remarked, took place in 1666.
In the 4th month following he sent his son Robert to reside on his estate of Ury,
near Stonehaven, being accompanied by his agent, David Falconer, a worthy Friend,
who had several times suffered imprisonment for conscience sake at Edinburgh.
The first public meeting for the purpose of worship was kept at Ury,
with some others in that neighbourhood, that same month and year;
Robert being then not nineteen years of age,
and having quite newly become united in faith and fellowship with this religious body.
Such a fact is thought worthy to be pointed out;
and it is affectionately recommended to the contemplation of the youthful reader,
taken in connection with the extensive religious growth and fruitfulness of "`this blessed
young man`" in afterlife:--it seems to have been as an _early offering_ by way of earnest,
and, doubtless, not merely indicated, but opened the way to further acts of dedication.
His father soon after, settling with his family at Ury,
meetings of the like kind continued from that time to be regularly held,
in a building close to the family mansion, for the space of, probably,
more than one hundred and twenty years.

The foregoing biographical account being brought thus far,
what remains to be portrayed of David Barclay,
will be given with other events in the order of time.

His son Robert was born at Gordonstoun in the shire of Moray, the 23rd of the 10th month,
1648.
When very young he had the appearance of a promising genius; and,
after passing through the best schools in his native country,
was sent by his father to the Scottish College at Paris,
of which his uncle was the rector.
Here he made so great proficiency in his studies,
as to gain the notice and particular approbation of the masters of the college;
and became especially a favourite with his uncle,
who offered to make him heir to all his property,
(which was very considerable,) if he would remain with him.
But his father, fearing that he might become tainted with the superstitions of Popery,
and in compliance with his mothers dying request,
went to Paris in order to bring him home,
when he was not much more than sixteen years of age.
The uncle still endeavoured to prevent his return; and proposed to purchase,
and give to him immediately, an estate greater than his paternal one.
Robert replied, "`He is my father, and must be obeyed.`"
Thus he sacrificed interest to filial duty; and the uncle, disobliged,
left his property to the college, and to other religious houses in France.

Robert Barclay returned to Scotland in 1664; two years after which,
his father became united in membership to the Friends.
So far from endeavours being used to gain over the son to this persuasion,
it was the express desire of the parent,
that he should have his religion from conviction, rather than from imitation;
which accordingly proved the case.
For, having freely and extensively visited all his relations and friends,
in different parts of the country, of whatever religious denomination,
and particularly those of the Roman Catholic body;
having also strictly examined how far both their principles
and practices were consonant with the Scriptures of truth;
he found himself constrained,
upon the same ground of real conviction as his father had been,
to embrace the same doctrine and course of life.
It is by no means evident, that he was induced simply through the means of preaching,
to make this change; indeed, his own clear explanation, which will be shortly given,
leads us to an opposite conclusion; but more especially the testimony of Andrew Jaffray,
one of his intimate friends, who asserted that he was "`__reached__ in the time of silence.`"
Although, during his father`'s imprisonment in Edinburgh Castle,
the governor denied him all access to him for the space of several months;
yet he had had sufficient occasion to observe the circumspect
example and genuine piety of his worthy parent,
as well as that of other servants of the Lord, who entertained similar views;
and his mind was in consequence imbued with some
"`general impressions`" in favour of Friends;
till at length, according to the language of the _Ury Record,_
"`he came by the power of God to be reached and made to bow`" before the Truth.
At this juncture,
John Swintoune and James Halliday were particularly helpful to him as instruments;
and perhaps it might have been one of these individuals, who uttered those few words,
attributed to some minister who was present at the first meeting Robert Barclay attended,
and which are said to have had considerable effect on his
mind:--they were these--"`In stillness there is fulness,
in fulness there is nothingness, in nothingness there are all things.`"

His own explanation above alluded to,
appears in the following passage in the "`Apology,`" where, speaking of himself,
he says,--"`Who, not by strength of argument,
or by a particular disquisition of each doctrine,
and convincement of my understanding thereby,
came to receive and bear witness to the Truth;
_but by being secretly reached by this Life._
For, when I came into the silent assemblies of God`'s people,
I felt a secret power amongst them which touched my heart; and as I gave way unto it,
I found the evil weakening in me, and the good raised up;
and so I became thus knit and united unto them,
hungering more and more after the increase of this power and life,
whereby I might find myself perfectly redeemed.`"--Prop.
xi. sect.
7.

Some account of his religious experience from his youth,
is contained in the succeeding extract, given nearly in his own words,
from another of his publications,
which is a treatise on "`Universal Love:`"--"`My first education from my infancy,
fell among the strictest sort of Calvinists;
those of our country being generally acknowledged to be the severest of that sect;
in heat of zeal surpassing not only Geneva, from whence they derive their pedigree,
but all other reformed churches abroad.
I had scarce got out of my childhood, when I was, by permission of Divine Providence,
cast among the company of Papists; and my tender years and immature capacity,
not being able to withstand the insinuations, that were used to proselyte me to that way,
I became quickly defiled with the pollutions thereof; and continued so for a time,
until it pleased God, through his rich love and mercy, to deliver me out of those snares,
and to give me a clear understanding of the evil of that way.
In both these sects,
I had abundant occasion to receive impressions contrary to this principle of love:
seeing the straitness of several of their doctrines,
as well as their practice of persecution, do abundantly declare,
how opposite they are to universal love.
The time that intervened between my forsaking the Church of Rome,
and uniting with those with whom I now stand engaged,
I kept myself free from joining with any sort of people,
though I took liberty to hear several.
My converse was most with those, who inveigh much against _judging,_
and such kind of severity: which latitude may perhaps be esteemed the other extreme,
opposite to the preciseness of these other sects;
whereby I also received an opportunity to know,
what usually is pretended on that side likewise.
As for those I am now united to,
I justly esteem them to be the true followers and servants of Jesus Christ.`"

Through great love, watchfulness, and fidelity to the inward appearance of Jesus Christ,
"`the true Light,`" Robert Barclay early came forth a zealous and able witness for it,
taking up his cross to the glory and friendship of this world,
and despising the shame that attended his owning this testimony;
for he esteemed "`the reproach of Christ greater riches than the treasures
in Egypt,`" and counted all things but loss in comparison of _winning Christ,
and being found in Him._
After this manner, he rapidly advanced, it may be said,
both with regard to stature and strength, to such a growth in grace and saving knowledge,
as has been the admiration of many.
It was not long, before he was called out to the public ministry; and,
receiving this gift "`as his greatest crown or dignity,`"
honoured to fulfill the services required at his hand,
in bringing others to the Truth as it is in Jesus;
and his honour was not in vain in the Lord.
Although he did not believe it required of him,
to travel so extensively as some others in this work,
(there being ample room for variety in the administrations
of heavenly wisdom to her children;) we find him,
in this respect, very highly esteemed in love by his fellow servants.
William Penn styles him an "`accomplished minister of Christ;`" though, perhaps,
not intending to convey what may in this day be understood by that phrase.
George Fox, who was by no means addicted to eulogy,
but rather sententious in his commendations, testifies of Robert Barclay,
that he was "`a wise and faithful minister of Christ,
who did good service for the Lord turning people from darkness to light.
Much more might be written concerning this faithful
brother in the Lord and pillar in the church of Christ,
who was a man I very much loved for his honour in the Truth.`"
Of his father, the same Friend writes,
that he "`was _a noble man_ for the Lord and his Truth.`"

Before turning from these striking specimens of the effect
of submission to Divine power in its operation on the soul,
it will be proper, for the sake of those readers who may need such information,
at least to advert very briefly to Robert Barclay`'s character as an author,
and to one of his engagements in that line.
He was considerably exercised in controversy,
from the many contradictions which in that day were
poured forth upon this view of the Truth,
and upon him for its sake, chiefly in his own country.
In these, he ever acquitted himself with honour to his religious profession;
but particularly by [.book-title]#An Apology for the True Christian
Divinity,# held by the people called Quakers,
which volume was published in Latin so early as the 28th year of his age;
his first piece having appeared in print six years before.
"`This was,`" says William Penn, "`the most comprehensive of all his pieces.
It came out at the close of a long and sharp engagement between us of this kingdom,
and a confederacy of adversaries of almost all persuasions.
It was his happiness both to live in a more retired corner,
and to enjoy at that time a space of quiet above his brethren: which,
with the consideration of their three or four years`' toil,
and a sense of service in himself,
put him upon undertaking and publishing this discourse,
as an essay towards the prevention of future controversy:
It first lays down our avowed principles of belief and practice, +++[+++after which]
he has put the objections which he had collected
out of our adversaries`' books and answers them;
and lastly cites divers authors, both ancient and modern,
especially some of the primitive ages, for further illustration and confirmation.
The method and style of the book maybe somewhat singular, and like a scholar;
for we make that sort of learning no part of our divine science.
But that was not _to show himself;_ but _out of his tenderness to scholars,_ and,
as far as the simplicity and purity of the Truth would permit,
_in condescension to their education,_ and way of treating those points herein handled.`"
It has passed through many English and also foreign editions,
being translated into several languages.
Among those, who from that day to the present have joined the Society by convincement,
_not a few have been led to do so, from the perusal of this book._
Several have been the testimonies given in its favour by authors of repute.
"`I am not ashamed,`" says one, "`to own,
that I have with great pleasure read over Mr. Barclay`'s Apology for Quakerism;
and do really think it the most masterly, charitable, and reasonable system,
that I have ever seen.
It solves the numerous difficulties raised by other sects,
and by turns thrown at one another,
and shows all parts of Scripture to be uniform and consistent.`" [.book-title]#Cato`'s Letters, or, Essays on Liberty, Civil and Religious,# by Gordon and Trenchard,
1720, vol.
iv. p. 226. Another author, Norris, a minister of the "`Established Church,`" declares,
"`I cannot think Quakerism inconsiderable,
as the principles of it are laid down and managed by Barclay.
That great and general contempt they lie under,
does not hinder me from thinking the sect of Quakers to be far
the most considerable of any that divide from the Church,
in case the Quakerism that is generally held,
be the same with that which Mr. Barclay has delivered to the world as such;
whom I take to be so great a man, that I profess freely,
I had rather engage against a hundred Bellarmins, Hardings, and Stapletons,
than with one Barclay.`"
And again, That he knew of no religion so rich in reputation for great men,
but might be glad of the accession of such a writer.
_Of Divine Light,_ Tract, ii. p. 32.

In truth, to adopt nearly the words of a candid writer,
Robert Barclay`'s qualifications for controversial honour, were unusually eminent;
being not only master of useful literature, but of a clear comprehension,
a capacious reach of thought, a close and convincing manner of reasoning,
delivered in a forcible style, though plain and unaffected.
The excellency of his temper, heightened by the influence of religion,
preserved him in coolness, that his judgment was not blinded by any degree of passion;
whilst his regard to undisguised truth prevented him from flattering error,
or excusing calumny.
His enlightened mind penetrated to the bottom of his subject;
and this imparted a clearness of method, which, with the weight of his arguments,
proved him an overmatch for his antagonists.

It is not requisite, here to enlarge any further on this author`'s productions.
An ample survey of them has been given by the author of [.book-title]#A Short Account
of the Life and Writings of Robert Barclay,# published in 1802.
William Penn also wrote a preface to his Collected Works,
in which there is a particular recommendation of the several treatises of which it consists.
This introduction, for the lively spiritual sentiments pervading it,
can scarcely be read without advantage by those who have a true relish for divine things.
