== Chapter IV.

[.chapter-synopsis]
* 1806: James Urquhart excommunicated by the Presbytery: A remarkable circumstance befalls the person who publishes this act
* 1667: Violence of "`Sir John Keith`" against the Friends
* 1668: Illness of Alexander Jaffray
* He is imprisoned at Banff
* His address to the Bishop of Berdeen
* 1669: Lilias Skene`'s convincement
* Her husband, from an opposer, becomes a Friend
* 1671: The public preachers of Aberdeen endeavour to excite the civil power against this people
* A synod of the clergy address the king`'s council against them
* 1672: The king`'s declaration of indulgence
* Friends relieved by the judges on the subject of oaths
* The sudden and dismal end of some persecutors.

It happened about the year 1666, that James Urquhart,
whose name has been before mentioned,
for his conscientious separation from the national church of the day,
fell under the censure of the Presbytery, and was excommunicated.
The excommunication was sent to one William Forbes,
a minister of the place where Urquhart lived,
with an injunction of the Presbytery for him to publish it from the pulpit.
The minister, conscious in himself of the honesty and integrity of the person,
against whom he was enjoined to read the sentence, fell under strong convictions,
and great reluctancy of mind against the performance of what he was commanded.
But, when he considered, that the consequence of his disobeying the Presbytery would,
in all probability, issue in the loss of his stipend,
covetousness overcame his convictions;
and he publicly pronounced the sentence against James Urquhart,
in direct opposition to the dictates of his own conscience.
This, afterward, gave him much uneasiness, and his mind became so discomposed,
that he could not, for some time,
proceed in performing the usual offices of his function; until, at length,
he publicly and ingenuously came to confess,
that his discomposure was a just judgment of God upon him,
for cursing with his tongue a person,
whom he believed in his own conscience to be a very honest man.
Yet, notwithstanding his convictions were so clear and overpowering,
he again fell into the like error, and in a way more nearly affecting him.
His own daughter, Jane Forbes, was convinced of the Truth,
and joined the people called Quakers.
Church proceedings were carried on against her to an excommunication,
which her father was required by the Presbytery to pronounce.
The poor man`'s case, under so difficult a dilemma, was really to be pitied.
Hard was his choice, either to lose his living by disobeying the Presbytery,
or wound his conscience by pronouncing excommunication against his own daughter,
whom he knew to be a virtuous and religious woman.
But alas! both his conscience and natural affection gave place to the love of money;
so that he was determined to read the excommunication,
and had uttered some kind of prayers previous thereto,
when he was suddenly struck by death,
at the very time he had purposed to deliver that sentence.
A melancholy and remarkable exit,
wherein nature was observed to sink under the weight and
oppression of a conflict between conscience and self-interest.

Sir John Keith, who in those days, and afterward, was very violent against Friends,
having, in the year 1667, brought away, under a guard,
several of this people from Inverury, where they had been previously imprisoned;
the magistrates of Aberdeen, to whom they were delivered,
after keeping them in confinement some time,
caused them to be conducted through the streets, with great contempt and reproach,
to the Bow-bridge, where a guard was provided to conduct them southward to Edinburgh,
from shire to shire, as the worst of malefactors.
When they had proceeded a little way out of the town, one of the prisoners,
William Gellie, a man of very weakly and infirm habit, sat down;
and the rest of the Friends followed his example, refusing to go further,
unless horses were provided.
At this, one of the bailies or magistrates, named +++_______+++ Alexander, who attended,
in order to see them set out, was much enraged,
commanding William Gellie to rise and go forward on foot;
and because of his refusal he struck him piteously.
Friends, however, continued to sit still; upon which, the magistrate with all his train,
not being able to prevail in their purpose, returned to Aberdeen,
and the Friends to their respective dwelling places.
But, what was remarkable,
the first object that presented itself to this persecutor on reaching his own house,
was his son, who had by a fall broken his arm,
and in the very same time that the father had been using
his arm to strike the harmless servant of the Lord;
which circumstances, thus coinciding, so awakened the conscience of this person,
that he said,
(and afterward told it to some Friends,) _he should never strike a Quaker again._

We return to our worthy, and now, infirm _Diarist,_ Alexander Jaffray,
who at this period honoured under much affliction with a quinsy;
for some time he could not speak, nor scarcely eat or drink,
insomuch as to be given over for death by all that beheld him.
Yet, while in that state, he signified by writing, _the steadfastness of his faith in God;_
and also his belief,
that he should yet be preserved for further service to the Lord and his Truth;
which prediction the sequel fully verified.
It is said, that, at that juncture, a certain female, a noted professor,
was much impressed, observing the calmness, resignation,
and faith evinced by this devoted Christian, in an hour which was judged to be his last,
and his unshaken firmness in the testimony which he had received to bear; hereupon,
she went to one of the ministers of the city, and asked,
whether they durst deny that Jaffray had once been a truly gracious man.
They said, they would not deny it.
"`Then,`" said she, "`either Quakerism must be a right way, or else your doctrine false,
who say, there is no total nor final fall from true grace; for he is dying,
confirming that way.`"

Shortly after, on the 11th of the 9th month, 1668,
he was taken from his own house at Kingswells, in a sickly, debilitated condition,
and carried by three messengers to Banff prison,
at the instigation of the Bishop of Aberdeen,
under the pretence of a fine of six hundred merks,
formerly imposed upon him by the High Commission Court,
for suffering religious meetings at his house, contrary to their order.
Thus, the Bishop and those termed clergy discovered the malignity of their disposition,
in imprisoning this faithful man thirty miles distant from his habitation; which,
to him in a delicate and enfeebled state, proved no less than three days`' journey.
He was there detained prisoner nine months and sixteen days,
to his great expense and detriment,
(some of his family being mostly with him,) as well as to the endangering of his life;
for he might have died there,
had not the civil power relieved him from ecclesiastical tyranny;
the King`'s Privy Council giving order for his release,
without his paying any thing whatever for the fine, or for fees or charges,
neither of which he could conscientiously have defrayed.

It was during this his meek endurance, and participation of the sufferings of Christ,
that Alexander Jaffray addressed an epistle to the Bishop,
who had thus been a willing instrument in occasioning his unrighteous bondage.
It is here given, though somewhat condensed in parts.

[.embedded-content-document.letter]
--

[.letter-heading]
To Patrick Scougal.

Not in my own will, am I thus drawn forth,
but in the will and authority of the living God,
to warn thee to beware of persecution,--to beware of oppression!

It was reported of thee, at one time, that thou wouldst not be, as others,
in the use of these '`the instruments of a foolish shepherd. Zech. 11:15-16.
But, if any simplicity of that kind have been truly found with thee,
how is it, that thou hast so sinfully betrayed it,
by countenancing and approving the actions of those, who, while absolute in power,
drove so furiously, as to make themselves, and the highest censures of their church,
slighted and scorned!

Will not every judicious and seriously sober person, find more cause now than ever,
thus to judge of them and their proceedings,
and still more so of thy concurrence with them;
while the weight of your indignation is so mainly turned against that sober,
harmless people, _the witnesses of Jesus Christ,_ in scorn called Quakers?
they, above all others,
being most falsely charged with owning blasphemous and heretical tenets,
and such abominable practices as their soul abhors;
who have by no means been wanting in vindication of themselves, both by word and writing,
from such charges.

But, so greatly hath iniquity prevailed,
that men are not ashamed thus to _detain the Truth of God in unrighteousness;_
not only obscuring and hiding that which we gave forth for the
clearing of our principles and practices in these respects,
and which they themselves called for at our hands; but,
in order to keep us in disgust among the people,
still make it their work to exclaim against us,
as though they knew nothing to the contrary, but we were guilty of the very same things.
In due time, however, God will arise and judge for these things; yea,
sad is the judgment already meted out, although it be not discerned by you.

With regard to thy proceedings towards myself in particular,
(some things as to my bodily weakness considered,) it will be found,
that this present imprisonment, and the usage I am meeting with,
may very warrantably be termed, cruel severity and oppression.
But, I am not intending to mention this, or to take notice of thy hand herein,
further than my testimony for the Lord and his Truth is concerned in it.

And therefore, finding that thou, and some others, interested persons,
who act by thy order, endeavour to weaken this my testimony, by affirming,
that my present sufferings are only occasioned by my own willfulness,
or my relations`' neglect, who, by paying a little money,
might have prevented the same;--to undeceive thee and them herein,
I find it my duty to tell thee,
I am engaged upon far other grounds than those of willfulness or peevishness,
_to decline paying or in any way to assent to the payment of that money,_--even,
on that of a real and well-grounded fear of God.
For, as thou well know`'st, that fine was incurred, not for any crime or guiltiness,
but _for my testimony to the work of God_ imposed upon me.
And, _to do any thing to weaken this,_ either by paying,
or permitting to be paid on my behalf, any part of that money,
would be _a very betraying of the cause of God_ into the hands of its enemies.`"

Thus do I warrantably and truly judge of this matter,
however thou or others may conclude, through the darkness that is in you,
_as to a discernment of the work of God in this day,
and what is required of the true witnesses of it._
I can truly say, my own particular case should not have been so much as mentioned,
were it not _for the sake of my testimony,_ which _above my natural life,
and all that is on that account dear to me, I desire to preserve full and entire._
God hath so overruled, and I know that he will continue to overrule,
the sharpest of my sufferings, to his own glory and my soul`'s advantage,
and hath likewise so overruled your designs therein; that, through his grace,
I am made willing,
(so far as I am alone concerned,) to pity and freely forgive both them,
and thee in particular, who hast so mainly acted in this matter; for which,
most assuredly, you will have before God to answer.

And this, further, I may not forbear to tell thee.
Such severity against the people called Quakers,
will not produce that which thou and others intend by it.
For, though ye should be permitted to bring many more than myself _to die in prison;_--as,
how many for this, the cause and work of God, not loving their lives unto death,
have been cheerfully brought thereto; yet,
shall _that_ only tend to the further service and advancement of our testimony,
which is indeed gloriously come forth, and shall further,
to the terror and astonishment of all opposers.

[.signed-section-signature]
Alexander Jaffray the elder.

[.signed-section-context-close]
From the Tolbooth in the town of Banff, the 4th day of the 11th month, 1668.

--

While in this place of confinement,
Alexander Jaffray also wrote "`A Testimony to the Truth,
given forth for the good of all to whom it may come;
more particularly intended for the magistrates and
inhabitants of the shire and town of Banff.`"
This paper, which is dated the 24th of the 1st month, 1669,
and chiefly consists of general exhortation and warning,
he gave in with his own hand before a great head court of that shire,
which sat in a room adjoining his prison-chamber,
having also distributed some copies of it among them.

About this time, Lilias Skene, wife of Alexander Skene,
one of the magistrates of Aberdeen,
a woman held in high estimation there for her religious attainments,
and especially by George Meldrum the minister before mentioned,
was brought under a great concern of mind to join
herself in society with the despised "`Quakers.`"
A material circumstance attending her convincement merits observation.
While her mind was deeply exercised in a serious inquiry after the way of Truth,
she found her progress impeded by notions and prepossessions against that people,
industriously instilled by the preachers into her mind,
and into the minds of others of their hearers;--as, _that they denied the Scriptures,
and did not pray in the name of Jesus._
This impediment was removed in the following manner.
She happened to be taken ill, and kept her chamber, in an apartment,
under the same room where Barbara Forbes dwelt.
Barbara Forbes, it may be remembered, was noticed by Jaffray in his Diary,
as an individual particularly favoured of the Lord,
and endeavouring to live in communion with him.
Since that time, she had found her way into fellowship with the Friends,
having measurably arrived at that difficult attainment,
which Jaffray desired for her--namely,
that she might _behave and quiet herself as a child that is weaned of its mother._
At her house, the Friends were accustomed occasionally to meet,
so near to the apartment of Lilias Skene, that she could distinctly hear what passed.
Attentively listening on one occasion,
she plainly heard two English women exercised both in preaching and prayer,
whose lively testimonies she observed to be _full of Scripture expressions,_
and their petitions put up _in the name of Christ,_
as well as accompanied by his life and power.
Thenceforward, she was effectually reached by the Truth,
and brought under subjection to it;
being also thoroughly convinced of the falsehood of those slanderous accusations,
with which the preachers whom she formerly admired,
had been accustomed to calumniate the Friends.
+++[+++see <<note-L,Appendix, L.>>]

This valuable woman had not long entertained and
adopted such a change in religious views,
when her husband, Alexander Skene, from a zealous opposer of this people,
became a sincere convert to their Christian principles; as did also Thomas Mercer,
"`late dean of guild,`" about the same time.
The civil stations occupied by these individuals in Aberdeen,
and the general repute in which they stood,
appeared only to add to the alarm and indignation evinced by the ministers,
on occasion of such persons withdrawing from their communion.
The name of Alexander Skene, in particular,
has already occurred in the former part of this Work;
being one of those who were sent for to Edinburgh,
by a religious assembly held there in 1651,
that he might be present at certain conferences on the important inquiry,
as to "`the causes of the Lord`'s controversy with the land:`" we may therefore assume,
that he was considered to possess some solid qualifications as a Christian professor;
and yet this is hardly to be in any wise traced or discerned in
the account he gave of his own conduct on one particular occasion.
For, after he had joined the Society, he related the following singular circumstance,
that befell him _in the time of his ignorance and
height of unsanctified zeal against Friends;_
and which he desired might be remembered,
as a warning instance of the providential hand of the Almighty against _a bitter,
railing spirit,_ which he acknowledged _then ruled in him._--Being in company,
at his own house, with one Alexander Gordon, a Nonconformist preacher, he said,
_It were well to take that villain George Keith, and hang him up at the cross of Aberdeen._
Within a very few hours after he had uttered these words,
he was smitten in his cheek and mouth with that complaint,
called _cynicus spasmus_ or _snarling_ spasm, by which his mouth continually turned about;
in this condition he remained for some weeks,
so that the witness for God in his conscience convinced him of the justice of this visitation,
for his hasty, furious speeches against that innocent person, and against Friends.

Notwithstanding this sad specimen of the outbreaking of the unregenerate nature,
aggravated, as it certainly was,
in one who had laid high claims to the religion of Jesus; it is still very possible,
in the face of his own self-loathing, that the case,
so far as regards the bitterness of the intention, might admit of some modification.
For, independent of the general estimate of his character, we find his acquaintance,
Robert Barclay, thus testifies of him.
"`Alexander Skene was a man very modest, and very averse from giving offence to others.`"
The same author further intimates respecting him,
that being overcome by the power of Truth, in regard to the subject of spiritual worship,
he found it incumbent on him to refrain from all
other public modes of performing this great duty,
and to join himself to us: that he also gave the reason of his change,
comprehending his views in the form of short questions,
which he offered to the public preachers of the city.
These questions were thought fit by Robert Barclay to be inserted in his
"`Apology;`" and being well worthy the consideration of those,
who are marking the Rise and Progress of this class of Nonconformists,
they are placed in the Notes.
+++[+++see <<note-M,Appendix, M.>>]

But such endeavours, on the part of Friends,
to explain the grounds of their conscientious dissent
from the "`national church`" hitherto utterly failed.
The leaders among their opponents, desisted not on every occasion,
from their attempts to excite the civil power to proceed with rigour, against them;
though hitherto, through the moderation of the magistrates, without much success.
For, in 1671, when the Judges visited Aberdeen on their circuit, Meldrum,
whose inimical disposition towards this people has already been shown,
in his sermon before the Judges, represented them, in his usual strain,
_as a most dangerous and pernicious sect,_
at the same time urging the exercise of the utmost severity of the law against them.
Nor was he satisfied with this; but, in company with his colleague, John Menzies,
he waited upon the Judges at their chambers, where they also met with the Bishop:
to them they complained,
that the magistrates of Aberdeen had several times broken up the Quakers`' Meetings,
had imprisoned, fined, and even banished some of them; and yet,
were not able to suppress them.
Upon which, the Judges asking, _What they would have them do further?_
Menzies "`made a proposal so cruel, that the Bishop was ashamed,
and the Judges would return no answer.`"
And when some of the said people, who were cited, appeared before them,
they declined passing any sentence against them,
or giving any countenance to the purposes of these professed ministers of the gospel,
which they clearly saw to be malicious.
+++[+++see <<note-N,Appendix, N.>>]

Immediately upon the convincement of the two individuals above mentioned,
Alexander Skene and Thomas Mercer,
at the joint solicitation of the four ministers of Aberdeen, a sub-synod, or, perhaps,
more correctly speaking, a Synod was convened by the Bishop; which met soon after,
and drawing up an address to the King`'s Council at Edinburgh,
sent two of their number to present it; in which, they petitioned the Council,
_to take some effectual course to curb and rid the land of the Quakers,
who were increasing among them._
The deputies from the Synod expected to obtain some fresh order from the
Council against the "`Quakers,`" but met with fresh disappointment;
the Council only referring them to a precedent Act of Parliament, which ordained,
that all who withdrew "`from their parish church,
be admonished by the preachers before two sufficient witnesses,`" and then,
after an absence of three successive weeks,
"`they be fined one eighth of their valued rents.`"
Returning to Aberdeen, these deputies reported to the town Council,
the issue of their application; upon hearing which,
the provost or mayor made this remark, "`What signifies all this?
we had this before: take you care to do your own work, and we shall do ours.`"
Two of them, George Meldrum and David Lyall, thereupon,
immediately set about doing their part towards bringing
the Act into force against this people;
and were busily engaged in performing their monitory office from house to house, when,
that same night, the King`'s _Declaration of Indulgence to all Nonconformists,_ in 1672,
reached Aberdeen, and put a stop to their proceedings at that time.
This was accepted as a providential deliverance by the persons, whose ruin they sought.

_The Declaration of Indulgence_ came very seasonably
to prevent the execution of an Act of Council,
which the preachers had prevailed upon the magistrates of Aberdeen to pass;
by which they had resolved,
_"`that no Quaker should be made a burgess or freeman of that city,`"_
and that _"`whosoever received a Quaker into his house,
without leave of the magistrate, should be fined five shillings.
And that if any person should let a house for Quakers, either to meet or dwell in,
he should be fined five hundred merks Scots money, or £28. 2s. 6d. sterling.`"_

About the same time, the people called Quakers in this kingdom received relief,
in a case of conscience, in which they, in common with their brethren in other parts,
were greatly exposed to suffering.
It was the custom and legal practice of Scotland, in suing for a debt,
where proof failed, to put the defendant to clear himself upon oath:
this exposed the Friends, who could not swear at all, to be made a prey,
by ill-designing persons prosecuting them frequently for unjust claims.
The Judges,
perceiving the advantage this conscientious scruple gave their antagonists in such suits,
and regarding the case with that equity which became their station, humanely determined,
that in such cases a simple declaration of the truth should be accepted from that people:
a favour they had not then obtained in England.

But, as they did not fail to admire that providential Goodness,
through whose hand every blessing flows towards his children; so could they do no less,
than notice the remarkable interposition of the same overruling power in another direction;
either by unexpectedly baffling the designs of the persecutors,
or by weakening their hands in various respects: sometimes,
even constraining them to penitence, at other times,
in an awful manner cutting short the lives of those,
that still proceeded in their wickedness.
Several instances are on record of this description;
some as regards the persecuting preachers and magistrates of the day.--Among others,
James Skene, who was generally known by the name of _White James,_
to distinguish him from a very abusive and wicked man of the same name,
called _Black James,_ took great delight in inventing malicious slanders against Friends.
On one occasion, whilst he was repeating some wicked verses, which he had composed,
on purpose to defame a worthy and innocent person, he was _in that instant,_
suddenly struck down, as one dead, and was for some time deprived of his senses.
When he recovered, he acknowledged the just judgment of God upon him,
confessed the offence he had committed against this innocent people,
and gave proof of repentance by abstaining from such practices.--Alexander Gordon,
professedly a minister of the gospel,
procured the imprisonment of George Keith for preaching
the Truth In the graveyard at Old Deer,
and caused him, with another Friend, to be kept all night in a very filthy dungeon,
called the _Thieves-hole,_ where there was no window, either for light or air;
he was immediately after cut off by death in a sudden and
surprising manner.--Nor should the case of Robert Petrie,
provost or mayor of Aberdeen, be altogether omitted; who,
at the furious instigations of his brother-in-law, John Menzies,
and the other stated preachers in Aberdeen, had been very violent against Friends;
often breaking up their meetings, and causing them to be roughly dragged away to prison.
This same magistrate, some years after,
on account of some public transactions in the Convention of burroughs,
in which he thought himself altogether innocent,
was ordered to be imprisoned at Edinburgh, fined in a thousand pounds,
and declared incapable of public office: but further,--he was conveyed to Aberdeen,
the scene of his unmerciful conduct,
and there affronted by being himself imprisoned in the very same place,
where he so often had had the persons of his worthy fellow-citizens cruelly detained.
So sensibly, however, was his conscience touched by this act of providential retribution,
that he very ingenuously confessed to some Friends, "`How just is this upon me,
for causing honest men to be so unjustly imprisoned,
that I should be thus put into this same place myself!
But I hope I shall never meddle with any of you again all my life.`"

Although much occasion remains for us all, in humility and fear,
to look well to our own standing,
rather than improperly to dive into the counsels of unsearchable Wisdom respecting others;
yet surely, in regard to cases like these,
we are bound with reverence to acknowledge _the hand behind the scene,_
even that eternal Justice and Truth which has declared,
"`He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them,
shall have mercy.
Happy is the man that feareth always:
but he that hardeneth his heart shall fall into mischief.`"
"`He that is perverse in his ways shall fall at once.`"
"`He that being often reproved, hardeneth his neck, shall suddenly be destroyed,
and that without remedy.`" Prov. 28. and 29.
