== Chapter V.

[.chapter-synopsis]
* 1669: Death of Margaret Molleson
* Her daughter becomes the wife of Robert Barclay
* A monthly and a half-yearly meeting established at Ury
* Observations on church discipline; and Robert Barclay`'s treatise on that subject
* 1672: His deep exercise respecting the inhabitants of Aberdeen
* Remarks on the zeal and care of Friends in several respects.

The preceding chapter closed with the exhibition
of some dark and gloomy shades of human character.
We have now to turn to a brighter scene:--and strong indeed is the contrast.
Truly,
"`The way of the wicked is as darkness;`" but we are about to contemplate
the life and latter end of one whose path was as "`the path of
the just,`"--and this is said to resemble "`the shining light,
that shineth more and more unto the perfect day.`" Prov. 4:18-19.

On the 16th of the 10th month, 1669,
a year or two earlier than the date of some of the last foregoing occurrences,
the little company of Friends at Aberdeen,
had to resign one of their earliest and most exemplary members
to that state of rest and fruition beyond the grave,
which can never more be interrupted by sin or sorrow.
This individual, Margaret Molleson, it may be remembered, has been before named,
as the wife of Gilbert Molleson, a magistrate.
In her youth she was an inquirer after the best people,
and joined herself in worship with the most strict
and refined in profession then in that city.
But, it having pleased God,
who beheld her hungering desires after himself and his righteousness,
to send some witnesses and servants, called Quakers,
from England into the north of Scotland, who preached the everlasting gospel;
she was among the first in those parts that received their message.

Coming to taste the unspeakable love of God in Christ Jesus,
she delighted often to retire therein,
out of the encumbering cares of her family and business;
and although her love to her husband, and cares of her many children, were great,
yet her chief source of peace and joy, her chief desire and care,
was to draw nearer and nearer unto the true and living God,
the Beloved of her wrestling soul.
For this end,
were the public meetings of the people called Quakers her frequent place of resort,
and she continued "`instant`" in more private approaches to the Lord;
insomuch that her husband, who was not at that time in profession with Friends,
had cause to say, _her knees were worn with kneeling at prayer._
For about four months before her departure, when he awoke in the night season,
he usually found her in meditation; and after her decease,
he said before several people who came to visit him,
that he had lost a true Mary and a Martha, none knowing how great his loss was,
so that he could not but deeply lament it.

On the 16th of the 10th month, 1669, in the morning, she was suddenly taken ill,
and in the evening of the same day died in childbirth,
having been for some time before made sensible that her end was approaching.
Yet her physician, not supposing that she had been in so dangerous a state, said to her,
_She needed not fear--his life for hers;_ to which she answered, "`Fear?
I have no cause; but thou wilt see, thou art mistaken.`"
At this time, many relations and neighbours being in her chamber, were in much sorrow;
among whom was an eminent professor, and an old acquaintance of hers,
who desired those about her to pray for her; which she hearing,
when others thought she had been dying, answered, "`My Advocate is with the Father,
and my peace is made: I am feeding at a table none of you perceiveth.`"
Some lamenting much her being likely to be taken away from her nine children,
who were all around her bed, she said, "`As many of them as shall truly fear the Lord,
and follow him, shall be provided for:`"--which has been since truly fulfilled.
And, fixing her eyes on her son Gilbert, who was then about ten years of age, she said,
in a heavenly frame of mind, "`Truth is precious; cleave to it!`"
Observing the people in her chamber lamenting much, she said to them,
"`Settle yourselves, and be stayed in your minds, for ye are now to see the last!`"
Then, in a sense that she was about to reap the fruit of all her spiritual labors,
she declared, "`Now interruption is to cease, and my eternal joy is already begun!`"
Soon after this she expired.

[.small-break]
'''

A few months subsequently to the removal of this exemplary character,
one of her daughters, Christian, was married to Robert Barclay.
She had, through much suffering and hardship, in her sixteenth year,
publicly embraced the testimonies held by Friends, and was one,
whose _name_ and _character_ truly coincided; a daughter worthy of such a mother,
and a wife worthy of such a husband.
As there will be further occasion to speak of her in the course of these Memoirs,
her character shall not here be enlarged on; yet it may be interesting to some readers,
to contemplate the grounds and motives for entering on the marriage state,
which appeared to influence such a mind as that of the _"`Apologist`"_ at
the age of twenty-one years,--at least so far as these are developed in
the following letter addressed to the worthy object of his choice.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
28th of 1st month, 1669.

[.salutation]
Dear Friend,

Having for some time past had it several times upon my mind,
to have saluted thee in this manner of writing,
and to enter into a literal correspondence with thee, so far as thy freedom could allow;
I am glad that this small occasion hath made way for the beginning of it.

The love of thy converse, the desire of thy friendship, the sympathy of thy way,
and meekness of thy spirit, has often, as thou mayst have observed,
occasioned me to take frequent opportunity to have the benefit of thy company; in which,
I can truly say, I have often been refreshed,
and the life in me touched with a sweet unity,
which flowed from the same in thee,--tender flames of pure
love have been kindled in my bosom towards thee,
and praises have sprung up in me to the God of our salvation,
for what he hath done for thee!
Many things in the natural will concur to strengthen
and encourage my affection towards thee,
and make thee acceptable unto me; but that which is _before all and beyond all, is,_
that I can say in the fear of the Lord,
that I have received a charge from him to love thee,
and for that I know his love is much towards thee;
and his blessing and goodness is and shall be unto thee,
so long as thou abidest in a true sense of it.

I write not these things to draw out thy mind, but as being with me so to do;
that thou mayst rather be humbled, and love the more to abide in the low, meek, quiet,
satisfied, peaceable, contented habitation,
from which there is _safety that cannot be hurt,
and peace that cannot be broken,_--a place of rest and quietness,
where the children of light and babes of the household of faith have fellowship together,
and embrace one another in the pure love, which is mysterious,
and hid from such as are led away by the foolish loves and fond affections of this world.
+++[+++For]
when any that bear the name of Truth,
or have at any time tasted of the good thereunto belonging, are entangled +++[+++herein,]
they cannot but receive great hurt,
and much damage to their spiritual prosperity and advancement.
Against +++[+++this]
it is my study to watch, and my earnest desire to be enabled so to do.
My friendship and respect for thee doth engage me to offer the same advice to thee;
because thou and I are those, amongst the small handful in this place,
whose private condition puts in a capacity to be obvious to temptation of that kind;
by yielding to which, I fear it will be found, some have received hurt.
That such as are behind, may be preserved from the like danger, is the cry of my soul.
I am sure it will be our great gain so to be kept,
that all of us may abide in _the pure love of God; in the sense and drawings whereof,
we can only discern and know how to love one another._

In the present flowings thereof, I have truly solicited thee, desiring and expecting,
that, in the same, thou mayst feel and judge.

[.signed-section-signature]
Robert Barclay.

--

About this time, the jealousy and enmity of magistrates, preachers,
and people in and around Aberdeen, began to grow very strong towards the Friends;
so that, at the Monthly Meeting, the rabble, being stirred up by some envious spirits,
had nearly laid violent hands upon John Swintoune, Patrick Livingston,
and some others who happened to be there.
But when Robert Barclay`'s marriage took place, their fury was yet more heightened,
that being the first proceeding of the kind that had been performed in the city.
The couple were married in the usual simple but solemn manner,
before many witnesses of various classes, and at the house of Gilbert Molleson,
the father of the young woman, who then filled the office of bailie or magistrate.
The public preachers of the place, thought their authority so slighted by this act,
and were so exasperated at it,
that by the Bishop`'s means they procured letters to summon Robert
Barclay before the Privy Council for an unlawful marriage.
"`This matter was however so overruled of the Lord,`" as the Friends of Ury express it,
"`that they never had power to put their summons into execution,
so as to do us any prejudice.`"

On another occasion, in the 1st month, 1670,
a number of Friends being collected to hold their Monthly Meeting,
the magistrates were further incited to send officers to disperse the assembly.
With violence they conveyed all the men to the Council house,
where the magistrates used their endeavours to dissuade them from the practice;
and taking a list of those who came from the country, dismissed them.
Upon this, they straightway returned to their own company,
the time of their gathering not yet being expired; there they found the women Friends,
together with other people,
attempting to perform the sacred and imperative duty of worship.
They had not long been there, however, when the officers appeared again,
and with greater fury than before dragged them back to the Council-house,
where the provost and Council reprimanded them for
contumacious resistance of civil authority,
using much threatening language.
But Friends were preserved in a tranquil and innocent boldness,
so that "`neither the big words nor yet the barbarous deeds`" of their opponents,
could make them flinch from an honest confession of the true reasons for their conduct.
One of them saying, in defence of their alleged disobedience to magistracy,
that it was _better to obey God than man,_ the provost scoffingly answered,
"`So we must all, forsooth, be apostles and disciples.`"
On this, John Hampton, a poor illiterate young lad, observed,
that it seemed he did not reckon himself a disciple of Christ,
seeing he thought it such presumption in others.--They
were all committed to the lower Tolbooth,
and at night closely confined, excepting Robert Barclay and Patrick Livingston,
who were set at liberty, and were very loath to part from their brethren.
Among their number, are the names of William Gellie and James Forbes;
the latter having held the rank of major in the army,
was probably the same Colonel Forbes, named in Jaffray`'s Diary.

Robert Barclay settling with his father at Ury,
a Monthly Meeting was established there soon after,
for transacting the affairs of the little rising church in that district;
also a more public or general meeting, held half-yearly, the first,
convened on the opening of the year 1669,
was remarkable for the convincement "`of several people of good account.`"

With regard to meetings of the above description, it may be observed,
that in this Society, as in that of the first converts to Christianity,
ecclesiastical government,
or what is often by Friends emphatically termed "`the
order of Truth,`" arose with the occasions for it.
If the poor required to be cared for and helped,
this would have the attention of the gathered church; if any failed of the grace of God,
and obeyed not the gospel, these would be admonished,
and their restoration diligently sought; but if such labor of love took no effect,
the terms of fellowship being broken,
there would remain no alternative for those who might desire to be of Christ,
but to withdraw from such brother, and acknowledge him not, in a religious sense,
by so endearing a tie.
In like manner,
would other subjects of interesting concern demand
the watchful eye and wise decision of a body,
whose Head "`is not the author of confusion but of peace.`"
In England, such measures had been generally adopted among Friends in the year 1667,
at the recommendation of George Fox;
but it does not appear that in Aberdeen any settled plan of this kind took effect,
until the commencement of the year 1672; when,
(to use the language of one of their ancient records)--"`Friends in Aberdeen and thereabout,
being increased and prospered of the Lord,
both as to their number and growth in the Truth, did,
in an unanimous love and zeal for the blessed Truth, and its work and service,
set up a Monthly Men`'s Meeting for affairs,
in administering true and righteous judgment among themselves in all things,
and taking care of the poor, etc.; and appointed a register or record book,
to be hereafter carefully kept,
for recording what is _condescended upon_ at these meetings:
to which book eleven men Friends and fourteen women did set down their names,
as belonging to that meeting.`"

The legitimate objects and extent of church government,
appear to have been very early and clearly made out to the view of some Friends; indeed,
no sooner were they constituted as a distinct religious body,
than the need of established order became evident to them,
and their minds were enlightened and instructed upon the subject.
A strong instance of this,
is furnished us in the individual experience of Robert Barclay; who,
not many years after his own convincement,
and at a time when the revival of such primitive and wholesome discipline,
might be said comparatively to be in a state of infancy,
wrote his admirable Treatise in its favour.
The original title, as it stood at length, was, "`The Anarchy of the Ranters,
and other Libertines, the Hierarchy of the Romanists, and other pretended Churches,
equally refused and refuted, in a twofold Apology for the Church and people of God,
called in derision Quakers.
Wherein they are vindicated from those that accuse
them of confusion and disorder on the one hand,
and from such as calumniate them with tyranny and imposition on the other; showing,
that as the true and pure principles of the gospel are restored by their testimony,
so is also the ancient apostolical order of the church of Christ,
reestablished among them, and settled upon its right basis and foundation.`"
This piece appears to have been written about the year 1674,
the author being then not above twenty-six years of age.
The compiler of [.book-title]#A Short Account of the Life and Writings of Robert Barclay,#
says respecting it,--"`The work has passed through several impressions;
and as its title when abridged to the few words,
'`The Anarchy of the Ranters,`' conveys little or no information of its contents,
the Yearly Meeting lately ordered an additional title to be prefixed, namely,
'`A Treatise on Christian Discipline.`' It is a work worthy of general perusal;
and particularly claims the attention of all persons,
who think it their duty to be active in supporting
and executing the discipline of the church.`"
To the above may be subjoined the observation of the writer of his life
in the [.book-title]#Biographia Britannica,#--"`A very curious and instructive work,
in which he with much solidity and perspicuity lays open the causes,
and displays the consequences of superstition on the one hand,
and fanaticism on the other, clearing the Quakers from both.`"
It is unquestionable, that the soundness and cogency of his arguments,
though often attempted to be overthrown, have stood unshaken; while the views of those,
who, from one generation to another,
have been rightly engaged in this respect to uphold "`the ark and the testimony,`"
have been not only confirmed but enlarged by consulting so sterling a production.
+++[+++see <<note-O,Appendix, O.>>]

With regard to this yet youthful author, some evidence has been given,
how early and how powerfully his soul was affected with a sense of the Truth,
and its inestimable value.
Though surrounded by temporal blessings, and now enjoying that chief one,
a pious and devoted partner, it does not appear that, on such accounts,
he considered himself at liberty to surrender up the ripening
powers of manhood to selfish ease or supineness;
but rather, that he received these gifts as so many tokens of Divine favour,
as marks of promotion to further trust and responsibility, as fresh signals for grateful,
vigorous engagement in the warfare of life.
Indeed, (to use the language of his grandson,
from whose Memoir much of this delineation is obtained,) as though he
had a foresight of the shortness of his time in this state of being,
he _"`posted`"_ through those affairs, which he thought himself concerned to perform,
with equal alacrity, wisdom, and meekness.

Having now described one of the productions of his pen,
and at a preceding page having given some account
of his _Apology,_ it may here be further noticed,
that all his publications, together comprising a folio volume of nine hundred pages,
were put forth in the course of the first nine years after his marriage,
between the age of twenty-two and thirty-one years.
Among his other works,
the [.book-title]#Catecthism and Confession of Faith# still continues to be from time to time reprinted,
and is found to be serviceable in explaining the religious tenets held by the Society.
It first appeared in 1673; previous to which time, as we have seen,
the Friends were confidently represented as despising and denying the Bible:
this compilation, formed entirely from the words of the Sacred Volume,
was intended to disprove such groundless assertions.
"`As the days in which we live,`" observes his biographer,
"`are marked by bold attempts to vilify the Scriptures; and as,
even _under our profession,_ there have been persons,
who have endeavoured to bring them into discredit,
thinking to succeed the more easily with a people,
who believe in the superior excellence of the Spirit;
it is peculiarly interesting to behold in what light Robert Barclay,
the able asserter of that superior excellence, viewed the Scriptures.
It is further interesting, because some persons have imagined,
that Robert Barclay himself countenanced opinions
not favourable to the Divine authority of the Scriptures.
His works, nevertheless, teem with references to Scripture authority.
He never shrinks from the test of Scripture, on disputed points; and in the present work,
he declares, that it is his design to let the simple words of Scripture, uncommented on,
be the advocates of the cause which he espouses.`"

It was not, however, by his pen alone,
that he endeavoured to serve the world and his Maker; he acted and suffered,
like a true reformer, for the honour of the great name.
Yet, since he kept only a slight diary of the transactions of his life,
with still less allusion in it to his religious feelings,
we are deprived of much that might have evinced the extent of his views of dedication,
and his fruitfulness as a branch of the true Vine.

In common with many of his fellow-honorers in the
glorious cause of spirituality and real holiness,
Robert Barclay came under that humbling description of exercise and service,
which often engaged them to testify, in various ways against the unsound, mixed,
and even corrupt profession of religion, in that day so much prevailing.
We are informed,
he gave up to obey the call to some hard and weighty requisitions of this kind;
sometimes visiting the congregations of such people, with a word of warning or rebuke.
On one occasion in particular, about the beginning of the year 1672, it was his concern,
under a strong sense of duty, _to pass through three of the principal streets of Aberdeen,_
clothed in sackcloth, after the manner of some of the ancient prophets,
and with similar motives.
After he had thus become "`a spectacle to men,`" he wrote
a short address to the inhabitants of that place,
explaining the nature of this exercise, which the reader will find is given in the Notes.
+++[+++see <<note-P,Appendix, P.>>]
The sweet savour appearing throughout this paper,
the consistency of the whole with sound reason, sobriety, and Christianity,
it is presumed, must at least call forth, in the perusal,
some sympathetic feeling from hearts that glow with love to souls,
and who long that Zion`'s prosperity may with increasing brightness go forth.

This action is branded,
by the writer of his life in the [.book-title]#General Biography,# with the name of enthusiasm,
and is even stigmatized with marks of contempt by his eulogist
in the [.book-title]#Biographia Britannica;# by each of them,
however, his sincerity is admitted.
But whatever may be the impression made on different readers,
according to their particular habits or mode of thinking,
with regard to this extraordinary act of an individual,
whose character stands too high to be attainted by evil imputation;
one point is clear,--that the everlasting Father of his people,
has in all ages deputed some of his children to be
as delegated shepherds over the flocks of his heritage,
and as lights in the midst of "`a crooked and perverse generation.`"
To these _he has ever committed a testimony, of some description or other,_
to be borne for his Truth`'s sake,--a standard to be upheld, in some especial manner,
against the course of the prince of darkness,
whose machinations and whose maxims are for the most part closely interwoven with,
and wrought into, the present constitution of mankind.
Of what primary importance, then, is it,
that each one of us should give the closest attendance upon those things,
that obviously make for our own peace of mind,
and individual progress in the life of Christ; rather than presume,
in such a case as that before us,
to define the precise line of testimony that may or may not be meted out to _another;_
especially where the uniform tenour of conduct and conversation,
must be allowed to place _that man in very near connection with his own Master,_
to whom he must, even in this life, either stand or fall.

But to bring to a close these digressive reflections.--In
the general history of this period,
there are circumstances recorded,
which strongly mark the decrepit state of vital religion and sound scriptural morality,
then existing as well in England as in Scotland; and it is not surprising,
that such wisdom and mercy as rules or overrules all things here below,
should raise up _remarkable instruments,_
to effect his own beneficent ends,--by restoring safe paths to walk in,
by improving the tone of piety, and thus renewing this portion of the face of his earth.
There was surely great occasion for these to be men of plain, uncompromising stamp,
that they might effectually do the work assigned,--as it were,
to _thresh the very mountains,_ to break up the tough and rugged ground,
and in other respects, as they might be commissioned, prepare anew the way of the Lord.

The public honorers raised up in this corner of the vineyard,
on which our attention is more exclusively fixed,
may be said to have been by no means few in number,
in proportion to that of the members generally;
and especially considering the small extent of district over which Friends were distributed.
Nor did the Lord of the vineyard spare to assign them instrumental
help in good measure _from other quarters;_
the records of their meetings often stating the names of numerous visitors from England,
whom the love of Christ and love to souls,
constrained to pass up and down among the flock,
confirming their spirit in these times of trial.
On one occasion, it would seem, that at a meeting for worship,
such as usually was held introductory to the consideration of their church affairs,
the showers of doctrine were so largely dispensed,
as to occupy nearly the space of seven hours,
and thus to preclude for that time the transaction of all other appointed business.

As "`a city that is compact together,`" or rather as a besieged people within it,
vigilance and alacrity,
with united cooperation for the safety and for the welfare one of another,
sometimes pleasingly shone forth at these meetings,
as well as zeal for the spread of the dominion of grace and truth.
When, in a particular case,
there had transpired some "`appearance of a breach
and separation`" in one or more of their number,
the others speedily and simultaneously met with the party,
all exceptions were thoroughly heard, and "`a plain reckoning`" ensued; after which,
as the record states,
"`to the praise of the Lord`'s free goodness and mercy to his poor people,
all differences were taken away, with much brokenness and tenderness of heart,
in embracing each other: for which blessed opportunity, Friends publicly and jointly,
in his own Spirit and life, returned praises to the Lord.`"
Such a successful illustration of the true labor of love,
in the spirit of meekness and of wisdom,
is not held up as one peculiarly confined to _that_ generation;--by no means;--rather
as an additional encouraging proof of the preciousness of brotherly admonition,
order, and concord in the body of Christ.

So, with regard to the promotion of the cause of Christianity,
and the furtherance of those that were looking towards Zion,
with faces thitherward turned, it is pleasing to find many instances, where Friends,
in the line of unreserved dedication, have held themselves open, with all readiness,
to entertain and give way to clear intimations of their duty in these respects.
Hence we find a minister in good estimation, George Gray of Caskieben,
about eight miles from Aberdeen, informing Friends at their Monthly Meeting,
of a people in his neighbourhood,
who _thirsted after_ the assemblies of this despised Society,
although they could not as yet "`well digest silent meetings;`" and what he desired was,
that Friends would consider their case, "`that if so be,
the Lord may be pleased to move some Friends +++[+++of Aberdeen]
to come thither;`" a meeting having, as he informed them,
been already appointed to be held twice in the month
at John Glennie`'s at Colliehill Mill on that account.

Connected with this last remark, is another circumstance worthy of preservation,
as follows: "`John Forbes, merchant in Ellon,
having left the preachers and public meetings there,
and come into the mid-monthly meeting, showed Friends,
that he had been before the Kirk Sessions, being cited for forsaking their ordinances,
as they call them; and that he had asserted their minister to be no minister of Christ,
neither these ordinances those of Christ`'s;
upon which he was cited to the Presbytery of Ellon: and withal,
having read a paper he had drawn, with which Friends have good union,
wherein many pertinent Scriptures were cited for several points of our testimony against
the common doctrine of the nation--Friends thought fit to go to Ellon next First day,
and keep a meeting in his house.`"
Accordingly, "`R. Barclay, G. Keith, D. Falconer, T. Mercer, A. Harper, J. Cowie,
T+++.+++ Milne, J. Skene, A. Somervill, and A. Skene went all to Ellon,
and kept a meeting in John Forbes`' house from half-hour
to twelve till the fourth hour in the afternoon;
where we had a good meeting, the people not only filling the room,
but flocking about the door and windows, which were purposely opened unto them.`"
About one month after this, John Forbes is requested on behalf of Friends,
to look out for some more convenient place for the congregation
who assemble at his house every First day,
_one half_ of their number not being able, it is said, to gain admittance.
