== Chapter VII.

[.chapter-synopsis]
* 1673: The magistrates make a second application to the king`'s council, and the "`clergy`" solicit Archbishop Sharpe against the "`Quakers`" proclamation against house and field conventicles
* 1674: Friends are forcibly put out of their meetinghouse
* Thomas Dockery taken from prayer to prison, also William Gellie
* Friends are denounced by name as rebels at the market-cross, and their personal property declared forfeited to the king
* David Rait`'s disturbance of them in their meetings; his fearful end
* 1675: Conference of Robert Barclay and George Keith with some college students, four of whom join the society
* 1676: Declaration relative to
conventicles-* Thirty-four Friends are imprisoned
* They are tried by a court of commissioners
* Their defence, sentence, and treatment
* Letter of Isaac Penington
* Robert Barclay, visiting the churches, on his return from Holland and Germany, petitions the king on behalf of Friends further proceedings of the commissioners
* Case of John Thompson

The magistrates of Aberdeen were not discouraged by their
late unsuccessful attempts against the Society of Friends,
but renewed their application to the King`'s Council at Edinburgh;
whilst those called clergy, on their part,
strenuously solicited Archbishop Sharpe`'s patronage; alleging,
that "`the Quakers`' schism was prejudicial to the interest of the Church,
and that by using a separate burial-place,
they prevented the payment of the fees customary on these occasions.`"
But this complaint, when laid before the Council,
was effectually obviated by the representation of Friends,
with regard to their disinterment of the dead bodies, before related.
The Council, upon hearing both sides,
did not think proper to interpose their authority in this case;
the deputation were accordingly dismissed, and returned home,
without attaining their purpose.

This people, however, were not long left unmolested.
A proclamation had lately been issued from the King`'s
Council against _house or field conventicles,_
with a bond attached, to be subscribed by heads of families and others,
obliging themselves and those under them not to keep such meetings or be present at them,
under a penalty.
The magistrates of Aberdeen, making use of this handle,
came several times to the meetings of Friends in that city,
requiring all present to subscribe the bond; and on their refusal, took down their names.
But, on the 7th of 5th month, 1674, in particular, the provost,
with other magistrates and officers, commanded them to depart, and because they refused,
directed that they should be forcibly put out of their meetinghouse; which was done.
Friends, nevertheless, quietly resumed their station within the walls,
on the magistrates withdrawing from the spot; and in the performance of their reasonable,
unobtrusive service towards their Maker,
felt the strength of his divine presence in measure amongst them, whereby some,
particularly Robert Barclay and George Keith, were enabled to declare of his goodness,
and vocally to celebrate his worthy name!

On that and a succeeding day, Friends were generally fined according to the bond; and,
on the 15th, Thomas Dockery, an English Friend, being engaged in prayer,
was taken by the town-sergeants,
and lodged in the Tolbooth for upwards of thirteen weeks;
as was also William Gellie soon after, for the like offence,
during nearly the same period.
The next step taken against Friends,
in pursuance of the act of Parliament against conventicles, and the order in Council,
was, _to denounce them all by name at the market-cross as rebels against the state,
and to declare their personal property forfeited to the Kings use._
It will be supposed, that all reasonable measures were taken by a people so abused,
to represent their case to those in power,
as well as to remonstrate with their immediate oppressors.
A declaration was addressed to the Council by the sufferers,
and signed individually by them,
which sets forth in appropriate terms the dutiful demeanour and principles of
this religious body towards the government,--well known even in those early days,--and
their conscientious scruple against signing the bond in question.

The example of such, who in the line of official duty,
should have been a terror only to evil doers,
no doubt would operate powerfully in encouraging
the more ignorant and debased among the people,
to acts of turbulent malice;
while the incentives to persecution openly offered to both these classes,
by the teachers of religion, must have had a still greater effect.
The meetings of Friends were, in consequence, not unfrequently attended by those,
whose minds seemed bent on disturbance and despitefulness.
It was, doubtless, to this state of things as it then existed in Aberdeen,
that Robert Barclay alludes in his _Apology,_ a
quotation from which is given in the Notes.
+++[+++see Appendix, T.]
One envious opposer, David Rait, was especially active: for the space of _two years,_
was he in the practice of using all endeavours to interrupt
them in the hours appropriated for divine worship;
being usually accompanied and abetted by a number of the college students,
whose conduct was insulting and outrageous in the extreme.

About this time, Thomas Fern, who came from England to visit his brethren in Scotland,
was concerned to preach in one of their public meetings; and whilst thus engaged,
was often interrupted by this David Rait,
whom he repeatedly cautioned to desist from so evil
a practice as this of turbulent railing;
at length, after long forbearance, he solemnly warned him to beware,
lest he should very shortly incur some remarkable judgment from the hand of God.
Within a few days after,
this wicked man fell under extreme anguish and terror of conscience,
crying out continually,
that the judgments of God were upon him for his abuses and
molestations of this people in their religious meetings.
Under which concern, he was incessantly restless,
until he had sent for David and Robert Barclay from Ury to visit him; upon whose coming,
with some Friends from Aberdeen, he begged them, with many tears, to forgive him,
crying out, "`Help, help, help!
I never wronged any but you, and will beg your help on my knees,`" etc.
Moved with compassion, Friends not only expressed their forgiveness of him,
but prayed unto the Lord on his behalf; after which he recovered,
and his mind became easy and quiet.
On the restoration of his health, this man, notwithstanding,
returned to his former practices,
the iniquity of which seemed to be aggravated by his notorious ingratitude.
Thus he continued, until a spirit of distraction seized and settled on him,
under which he ended his days.

On the 14th of the 2nd month, 1675,
a public conference or dispute was held at Aberdeen
in the presence of some hundreds of people,
between Robert Barclay and George Keith on one part, and some students of _divinity,_
so called, on the other: the occasion of which was this.
Robert Barclay, with a view of rescuing the Society from the odium under which they lay,
through gross misrepresentation of their doctrines from the pulpits,
published his _"`Theses,`"_ which was the ground-work of the _Apology;_
giving a brief and plain account of the principles owned by them,
that the public might have a fair opportunity of candidly considering the subject.
At the end of these Propositions, he offered to defend them in those places,
where they had been thus misrepresented,
and against such persons as had so traduced them.
But none of these, namely, the public preachers, choosing to accept the proposal,
and by a fair and sober discussion to inform themselves what they were;
this method seems to have been pitched upon;--namely,
to select some from among the students of their University to take up the cause,
as of themselves; that if those termed Quakers should have the advantage,
the consequence would be immaterial, in a contest with young men.
Friends were under no obligation to join issue with these youths, as it was not to them,
but to the public preachers, who propagated these misrepresentations,
the proposal was made.
But, as they were not afraid of meeting the greatest and ablest, so the Truth,
they thought, led them not to despise any,
who might be disposed in a becoming manner to treat with
them on the "`reason of the hope`" that was in them.
The dispute was accordingly held for the appointed space of three hours; but terminated,
as such disputes generally do, in tumult and disorder;
the students handling serious subjects with levity,
and at last triumphing in a victory which they had not obtained.
Having numbers on their side, they used clamour and personal abuse,
and wounding them with clods and stones, thus put an end to the debate.
But the result proved on which side the advantage lay; for four of the students present,
though not disputants,
were so fully convinced of the reasonableness of Friends`' principles,
that they joined them in society, and gave forth a written declaration under their hand,
stating the grounds of their change,
which was afterward printed at the close of a controversial piece of Robert Barclay`'s,
in reply to the students`' objections.
+++[+++see Appendix, U.]

In the month called March, 1676, the Council at Edinburgh issued a declaration,
reinforcing former acts of Parliament against conventicles,
and recommending the execution of them to the sheriffs and magistrates of corporations.
Although this proclamation expressly related to such as had been outlawed by the Council;
yet the civil and ecclesiastical rulers of Aberdeen took occasion from it,
to oppress those persons, of all others,
against whom they well knew it was never intended to be stretched.
So precipitate was their malice, and so ready were they for the work of persecution,
that, upon the mere information of a traveller,
and before the regular notification reached them, or was proclaimed in their town,
the provost, bailies, and officers came to the Friends`' meetinghouse,
on the 12th of the month, and committed twelve of them to the new Tolbooth;
several days after which, the prisoners heard, from their windows,
the public proclamation of the law that had been thus eagerly put in force
against them.--The like measures were pursued for the space of two months,
by which time the number of those lodged in prison amounted to thirty-four.

At length, the prisoners received a summons to appear before the Earl of Errol,
the Earl Marischall, and "`Sir John Keith,`"afterwards Earl of Kintore,
three of the Privy Council,
appointed Commissioners to put into execution the acts made against keeping conventicles.
Accordingly, being called up before these, on the 26th of the 3rd month,
a long libel was exhibited against them,
reciting the heads of the acts of Parliament against conventicles,
and the withdrawing from that mode of worship established by law.
The libel being read, was to be enforced by Patrick Hay,
the only lawyer who could be procured to plead against them; but his oratory failing him,
his plea was confined to this brief query, "`Who gave you leave to preach?`"
which, for want of pertinent matter, he repeated several times.

The inquiry being put to the prisoners,
Whether or not they were guilty according to the indictment;
David Barclay replied:--That, though it was ordinary,
for such as were stated under the circumstances it had pleased God to put them,
to entertain lawyers to plead for them; yet they,
having _the One Advocate with the Father,_
that would and could plead their innocency in the hearts of all their opposers,
they might not employ any man to plead for them.
And, inasmuch as none of them had followed the practice of law, it was desired,
that no advantage might be taken against them on account of their ignorance of the intricacies
of it;--also that the rigour of it might not be extended towards them,
if they should be found transgressors,
(which they hoped to make appear was not the case,) there being a maxim, owned by all,
that _Summum jus is summa injuria._
He further added, That the prisoners were most unjustly charged,
with having kept three meetings in the week since the 1st month, 1674;
whereas several of them had been, in that time, beyond the sea, others in England,
and many had not been in Aberdeen for several months during those years.

Hereupon, he was interrupted by the inquiry,
Whether they would own that they had been at any conventicles; to which they made answer,
That they were not to be their own accusers.
It was said, This could be proved by witnesses; to which David Barclay said, He expected,
that, according to law, equity, and reason, he might except against these.
Upon this, several college students were called in, against whom David Barclay objected,
that they were _socii criminis,_ having themselves joined in keeping such meetings;
and further, that they had lately published a book expressly against the prisoners,
in the very title page of which,
they accuse them of blasphemy and treason,--and therefore
were manifestly prejudiced persons.
Then the magistrates, who committed them, were called upon;
but these also were excepted against, as those who had to put the laws in force,
and were accusers.
To this, the Earl Marischall replied, They should then have no witnesses at all.
Yet did the Commissioners overrule these objections; and such evidence was received.

The prisoners then gave in their written defence; showing, at some length,
and by various legal pleas,
that they were not the persons against whose practices the acts in question were levelled;
also taking notice of their imprisonment, contrary to law,
by the magistrates for near three months; and further, boldly testifying,
that it was merely out of that duty they owed to God, and in obedience to his commands,
that they dare not forsake the assembling of themselves together in his name,
and not out of any contempt of those in authority.
"`And if for this,`" continues the document, "`the Lord should permit us to suffer,
we trust he will furnish us with such a measure of _resignation of all that we have,
to his disposing,_ that we shall not _count any thing too dear,_
when it comes in competition with His honour and our duty to Him.
But, we shall not wish any in present authority to be instruments thereof,
seeing the Lord hath said to his people, '`He that toucheth you,
toucheth the apple of mine eye.`'`"

After an hour or two spent by the court in deliberation, the prisoners,
being called one by one, were severally asked,
Whether they would oblige themselves not to go any more to meetings?
which every one of them refusing to do, they were again ordered to withdraw;
and after some time, being called in again, the sentence of the court was read to them,
whereby David Barclay, Alexander Gellie, Robert Burnett, Alexander Harper,
Alexander Skene, Andrew Jaffray, and Alexander Forbes were fined,
each in one fourth of their respective valued rents, for their own keeping conventicles,
and an eighth part of the same each for withdrawing from the public worship.
Three of the above were, besides, to pay an eighth part for their wives`' transgressions,
conformable to the tenour of the act.
Those that were not landed proprietors, were fined as follows: Andrew Galloway,
Thomas Milne, and George Keith, £30. each; William Sparke, £40.; James Forbes, £25.,
and the rest twenty merks apiece.
And, over and above, John Skene and George Keith,
because they were "`found to have preached and prayed at
these unwarrantable meetings,`" were "`to find caution,
under the pain of five thousand merks, __not to do the like hereafter,
or else to enact themselves to remove out of the kingdom,__`" agreeable to the act of
Parliament.--This John Skene is thus described by Proud in his History of Pennsylvania,
introduction, p. 160. "`John Skene was a person of great service and integrity,
both in his religious and civil conduct; he was near two years Governor of West Jersey,
and died in the year 1687.
He was a preacher among the Quakers,
had suffered much for his religion in his native country,
where he had distinguished himself in its cause.`"

The whole number were then remanded to prison, till payment of the fines,
where their number was increased by the repeated imprisonment
of others of their friends from their religious meetings.
While thus kept in close confinement,
some of them were concerned at times to preach to the people,
who would come up to the windows of the prison to hear them; but the magistrates,
to prevent this, and to incommode the prisoners,
caused the windows to be closed up with boards for a whole week together,
and also removed several of them into the higher prison.
On one occasion, Alexander Gordon, a bailie of Aberdeen,
came in great anger to the lower courthouse, where Friends were then imprisoned,
and took Andrew Jaffray, while he was declaring, through the window,
the gospel of peace and salvation to the people,
forthwith thrusting him into the higher prison,
where no Friends had as yet been confined.
This place is represented as filthy and disgusting beyond most prisons in the nation.
The persecutor was, however, so troubled in his conscience for such cruelty,
that he afterward confessed to a Friend,
he could get no peace nor rest in his mind that night,
until he had caused Andrew Jaffray to be returned to the spot, whence he had taken him.

Very seasonable to this unoffending,
yet zealous company of "`the Lord`'s freemen,`" must have proved the succeeding
remarkable strain of sympathetic and encouraging communication,
coming from so tried a servant of the Lord as Isaac Penington,
and meeting them after they had completed their fourth month of imprisonment.

[.embedded-content-document.epistle]
--

[.letter-heading]
For my dear suffering Friends in Scotland.

[.salutation]
Dear Friends and Brethren,

Who have partaken of the tender mercy and blessed visitation of the Lord.
O! blessed be the Lord, who pitied and helped us in our low estate,
and whose tender love and mercy hath followed us,
from his first visiting us to this present day.
And indeed, the Lord is with us,--what can we desire more?--preparing us for himself,
preserving us in the life of his blessed Truth, building us up more and more,
and causing his Spirit of glory and living power to rest upon us,
and the virtue thereof to spring up in us day by day.

O! the beauty and glory of
the day of our God increaseth upon his heritage;
O! blessed be the name of the Lord!
And to what tend all the workings of the contrary spirit and power,
but to eat out its own interest and kingdom,
through the Lord`'s blessed ordering of things;
so that all things work together for good, and for the advancing of Truth,
and the growth of it in the hearts of God`'s heritage.

So, my dear Friends, none look out, either at outward or inward sufferings;
but to the Lord only, whose life, Spirit, and power is above them,
and bears up all over them, who are in spirit joined to him, faithfully waiting upon him;
which God daily teaches and enables his to do.
Thus, my dear Friends, feel the Lord`'s presence and power among you,
who is always near his, but especially in the time of their straits, trials,
and sufferings; and wait to feel the life, springing,
and doing its proper work in each of you day by day,
working out what is to be wrought out in any,
and working more and more into the glory of the heavenly image; that,
through the sufferings, ye may come into the glory, and be crowned with the glory,
virtue, holiness, righteousness, and dominion of life over all;
and thus the Son may sit upon his throne in you,
and wield his holy and righteous sceptre,
and give you dominion in and with him over all that would veil life,
or keep it under in any of you.
So, my dear Friends, be strong in the Lord, with the strength of the Lord,
with which he is clothing those, whom he hath emptied and made weak; for the trials,
temptations, and afflictions prepare for,
and (as I may say,) lead into the possession of the desired inheritance;
where all that the soul hath breathed and waited for,
is bestowed upon it by the bountiful hand of the Father of mercies,
who keeps covenant and mercy forever, and renews covenant and mercy day by day.

So, the tender God of my life,
and Father of the blessings and mercies of my once greatly distressed and miserable soul,
instruct you, preserve you, watch over you; exercise your spirits most advantageously,
daily open you to himself,
keep you empty and naked before him of all your own clothing and righteousness,
and fill you with that which flows from the pure, living fountain,
to the unspeakable joy of your hearts, and the glory of his own name over all forever!

Be of good faith, my dear Friends, look not out at any thing,
fear none of those things ye may be exposed to suffer, either outwardly or inwardly;
but trust the Lord over all, and your life will spring, and grow, and refresh you,
and the love and power will purge out and keep out what would hinder its growth.
And ye will learn obedience and faithfulness daily more and more,
even by your exercises and sufferings; yea,
the Lord will teach you the very mystery of faith and obedience;
(oh blessed lesson!) and ye shall not be disappointed of your hope or crown,
by any thing the enemy can plot or bring about against you,
but have the weight of glory increased and enlarged
by his temptations and your many sufferings;
the wisdom, power, love and goodness of the Lord ordering everything for you,
and ordering your hearts in everything,--you having given up to him,
and keeping them continually given up to him in the holy seed of Truth,
in which he hath in some measure already joined,
and is daily more and more joining you to himself.

This is the salutation and tender visit of the love of your brother in the Truth,
whose breathings are to God for you, and his praises unto Him,
through the sense of His being with you, and daily showing mercy to you,
upholding and preserving you in the midst of your sore trials and afflictions.

[.signed-section-signature]
Isaac Penington.

[.signed-section-context-close]
London, 5th of 5th month, 1676.

--

Robert Barclay was at this time engaged from home,
in visiting his friends and the churches of Christ as a minister,
and went with this object to London; thence, crossing the water,
he travelled into Holland and Germany.
It is to be regretted,
nothing is preserved as to the particulars of this journey on the continent.
In the course of it, he commenced acquaintance with Elizabeth,
Princess Palatine of the Rhine, who was distantly related to his mother,
and with her he had some satisfactory opportunity of conference on religious subjects.
The publication of his _Apology_ this year, which was printed in Latin at Amsterdam,
may very probably have formed a part of his engagement abroad;
and it is more than conjectural, as his biographer intimates,
that on his return by way of London,
the author presented his book to Charles the 2nd. See the [.book-title]#Short Account of R. B`'s Life and Writings,# 1802, p. 31.
To the credit of the King, he took no offence at the Christian freedom,
used by Robert Barclay in his well-known address to him, prefixed to that work, which,
for its manly style, religious boldness, yet decent respect, has been much admired.

While at the English metropolis,
he received intelligence of the imprisonment of his
honoured father and other Friends in Scotland;
upon which, beginning to have some interest at court, and access to the King`'s presence,
he delivered into his own hands the following petition on their behalf.

[.embedded-content-document.address]
--

[.blurb]
=== The State of the Case of the People called Quakers in Scotland, presented unto the King`'s consideration.

The Council of Scotland having about three months ago emitted a declaration,
to reinforce former acts of Parliament against conventicles,
and recommended the execution of them,
because of the abuse several persons had made of the King`'s Indulgence,
as the said declaration intimates; some inferior magistrates have taken occasion thereby,
to imprison many of them +++[+++the "`Quakers,`"]
and some deputies of the Council have stretched the laws
against conventicles to the highest degree of severity,
by heavy fines and tedious imprisonments,
although their practices and principles never gave ground for such procedure.

It is therefore on the behalf of the said suffering people, with all sincere respect,
desired,
that it would please the King favourably to recommend their case to the Council of Scotland;
that a difference of character may be put upon them,
who have ever lived and behaved themselves peaceably under the present government,
from such as are said to have abused the Indulgence;
with some present relief to those harmless sufferers, to prevent that utter ruin, which,
in all probability, will attend so many of them, that live by their honour and trade.

[.signed-section-signature]
R+++.+++ Barclay.

--

The King`'s secretary, the Duke of Lauderdale,
was thereupon instructed to underwrite a favourable reference of the matter,
which was done in these words:

[.embedded-content-document]
--

His Majesty is graciously pleased to refer this paper to the right
honourable the Lords of his Majesty`'s Privy Council in Scotland.

[.signed-section-signature]
Lauderdale.

[.signed-section-context-close]
Whitehall, August 7th, 1676.

--

In a collection of manuscript correspondence, belonging to Colchester Monthly Meeting,
is an original letter of Robert Barclay, addressed to Stephen Crisp,
and dated the 3rd of the preceding month,
which shows that this favourable reference was not
obtained without much persevering effort.
"`I have at last,`" says he, "`after long and tedious attendance,
near finished my business; for the Duke of Lauderdale tells me yesterday,
he has received order to give me a letter to the Council in Scotland,
in order to grant Friends their liberty; which he has promised to give me tomorrow,
so that I purpose in two or three days to be going homewards.`"

On the 7th of the 7th month, September,
the above statement and reference were presented to the Council,
then sitting at Edinburgh; and at the same time was delivered in,
a brief but respectful "`Memorial`" from those people at Aberdeen and its vicinity,
"`in derision called Quakers.`"

But the Council at Edinburgh did not think proper to interfere in a matter,
which they had formerly appointed their Commissioners at Aberdeen to determine,
and concerning which those Commissioners had already pronounced their decree.
They therefore still left the matter to the decision of the same judges,
only appointing three others to join them; namely,
"`Sir Richard Maitland`" of Pittrichie, Baird of Auchmedden, and Ogilvie of Aboyne.

The six Commissioners accordingly sat at Aberdeen on the 28th of this month;
and the prisoners being called in, the Earl of Errol, who was president, told them,
That they had called them again, to know whether they were yet better advised,
than when they were last before them?
and whether they would give bond not to hold any more meetings?
To which John Skene answered, That the last time they were before the King`'s Council,
he, being one of those accused for speaking in the meeting,
desired the accusers might be asked, Whether himself, or any other of them,
had ever been heard to speak any thing in the least tending to sedition,
or to withdraw any of the King`'s subjects from their
due obedience and subjection to his authority?
To this the Earl replied, "`It is enough: that matter was spoke to at our last sitting,
and you were then found guilty.`"
John Skene answered, That there had not been any seditious act proved against them,
and that they had been kept prisoners about seven months,
for no other cause than meeting in a peaceable manner
to worship God "`in spirit and in truth.`"
But the Earl of Errol again interrupted him, saying,
"`It is enough:`" then directing his speed to the other Commissioners, "`My Lords,
I have delivered your minds, and therefore it is fit they should remove.`"
Upon this, John Skene further added, "`Though you now sit as our judges,
yet I cannot forbear but put you in mind, from the zeal of the Lord,
and from that respect I owe you as the King`'s counsellors, that the day is coming,
when both you who are now sitting as our judges, and we who are judged,
must stand before the judgment seat of the just Judge of heaven
and earth:--and therefore I wish ye may so judge now,
as that, in that day, ye may have peace.`"
The Earl observed, "`You are not to be our lawgiver;`" to which John Skene replied, "`No:
I only in all humility lay these things before you.`"

The Earl then queried, Whether they were all of that mind?
Alexander Skene answered, "`I hope there are none of us here,
that will be so unfaithful to our God, as to give any bond,
whereby we should bind ourselves not to meet together and worship
God;`" and further submitted to their consideration the circumstance,
that, so far as he knew,
there were at that time none of their Friends suffering
on this account in either of the three kingdoms.
"`The King,`" he continued, "`hath referred us to his Council,
and the Council hath referred us to you here,
so that ye have all the power of the civil authority,
to do with us as it shall seem right to you, from whom we may expect as much moderation,
as our Friends elsewhere have met with.
But, if it shall please the Lord to permit you to be the instruments of our sufferings,
I hope he will enable us to bear it with that patience
and submission which becometh Christians.`"

The Earl of Errol then addressed himself to the other Commissioners, "`My Lords,
"`if ye have any more to say than I have said, ye may speak it.`"
Upon this, the Earl Marischall remarked,
"`They plead themselves _not guilty_ of seditious conventicles,
as would seem by what that young man spoke,
whereas the law concludes their very meetings seditious.`"
Alexander Skene replied, That they could not help all the constructions of that kind,
for it had been the lot of God`'s people in all ages
to have misrepresentations cast upon them;
"`but we hope,`" said he, "`we shall behave ourselves so peaceably and dutifully,
that where for conscience-sake we cannot give active, we shall give passive obedience.`"
Then said the Earl of Errol, "`Qualified loyalty smells of disloyalty: it seems, then,
you will not give bond.`"
To which John Skene answered, "`Let never that day dawn,
in which we shall be so unfaithful to the Lord! but if any should prove so,
let neither the King nor his Council trust that man;
__for he that is not faithful to the Lord,
will never be faithful to his King and country.__`"

The prisoners being ordered to remove, as they were withdrawing,
the Earl of Errol said again to Alexander Gellie,
That the Quakers`' loyalty was a qualified loyalty.
Alexander replied, That he did not understand _that_ to be loyalty,
which was not qualified with the fear of God, and by obedience to him rather than man.

After some hours,
the prisoners were called into court to hear the
decree of the Commissioners to this purport:
That they should pay their respective fines to one Captain George Melvill,
and that upon payment, they should be set at liberty; that,
in default of payment within a limited time,
Melvill was empowered to distrain them for the same,
and that when the fines should be levied, the prisoners were to be released.

The Earl of Errol departing out of town the next morning,
the remaining Commissioners were unwilling to have further trouble,
by issuing afresh a particular process against those who
had been committed to prison since the rest were fined;
and therefore added a clause to their former decree, by virtue of which,
John Forbes of Aquorthies, Robert Gerard, and six others were liberated.
Among these, was John Thomson, an aged and a poor man.
He had been a soldier in the King`'s service at the battle of Worcester,
was taken prisoner, and sent as a slave to Barbados, where he remained five years.
There was something in this case peculiarly calling for
the indulgent interference of the higher authorities,
when inferior servants of the crown could thus overlook the character, services,
and bitter sufferings of a man, who had hazarded his life for his King and country,
and was now made willing to lose his all,
rather than relinquish the free exercise of his conscience towards the King of kings.
He appears to have had his goods distrained and disposed of, and to have lain in prison,
at one time, for about eight or nine months together, without being either called for,
found guilty, or heard in his own defence.
