== Chapter VIII.

[.chapter-synopsis]
* 1676: Fines levied by Melvill
* John Skene and Robert Burnett address the provost of Aberdeen
* His severity; and Melvill`'s conduct
* Patrick Livingston and James Halliday`'s preaching
* Further distraints and fresh imprisonments
* David Barclay`'s liberation
* Letter of the Princess Elizabeth to Robert Barclay
* His imprisonment on his return home
* Letter of the Princess to Prince Rupert on behalf of Friends
* Melvill executes his warrant of distraint at Ury

Soon after the Court of Commissioners had come to this decision,
Melvill set himself to work to put in execution the authority given him,
by levying the fines.
He began with Thomas Milne, a shoemaker; from whom, for his fine of £30.,
he took goods of three times that value; and thereupon,
this poor man was released from his imprisonment.
He, being discharged,
was present when his goods were conveyed to the market-cross to be appraised;
and finding that they were doing him much wrong by underrating them,
testified against their injustice; and, withal, _kneeling down,
he prayed God to forgive them._
This act, however truly savouring of a meek and Christian spirit, was by the provost,
George Skene, resented as a high affront to him and his office;
he therefore again committed Thomas Milne to prison, where he was detained four days.
Many of the sober and moderate inhabitants of the
place justly esteemed this as a great severity;
and two of the prisoners found themselves concerned each of them to plead with him,
in the following remarkable letters of expostulation.

[.embedded-content-document.letter]
--

[.letter-heading]
John Skene to the Provost Of Aberdeen.

[.signed-section-context-open]
Aberdeen Prison, 25th of 8th month, 1676.

[.salutation]
Provost!

Read and consider seriously without passion or prejudice.--Is there no God in heaven?
Is there no judgment day?
Must man only die as the beast,
and make no account how he hath improved his time in this world,
or how he hath answered the end of his creation?
If so,
then I should think it no strange thing to see thee
so devoted to please the spirit of this world,
this persecuting spirit, both in thyself and others.
But if otherwise,--as I desire to hope thou dost believe,--+++[+++then]
is there a just and righteous God, who seeth the actions of mankind,
and hath a book of remembrance,--+++[+++then]
the day cometh, wherein that which hath been done in secret,
shall be proclaimed as on the house-tops,--+++[+++then]
there is an after-reckoning,
and man must receive his reward conformable to the deeds done in the body,--and +++[+++then]
man hath something in him not common with the beasts, even an immortal soul;
for the salvation of which, he ought to be more concerned to please God than any man,
whose breath is in his nostrils, who, as the flower of the field, is here today,
and tomorrow is cut down!
I say, it cannot but seem strange to me, and to all God`'s people,
that one who believes these things, however great in the outward his power be,
dare venture on such actions as thou hast this day done,
to cause or suffer a man to be imprisoned for no
other reason than obeying Christ`'s command,
as it is recorded in Matthew 5:44, '`Love your enemies, bless them that curse you,
do good to them that hate you,
and __pray for them which despitefully use you and persecute you.__`'

Now, I warn thee, that thou seek not to cover this, and such rigorous practices,
lest thou add to thine iniquity;
for no excuse will stand thee in stead in the day of the Lord;
and their power and influence, by which thou proceedest as thou dost,
shall not cover thee from the hand of that God, who hath said concerning his people,
'`He that toucheth you toucheth the apple of mine
eye.`' Wherefore let not _the self-seeking clergy,_
nor their emissaries, sow pillows under thy arm-holes,
as the false prophets did of old to those in authority, by telling thee,
that we are not the people of God.
For, know assuredly, the word of the Lord hath been to me, with others of my brethren,
since we came in here, that as there is no variableness nor shadow of changing _in Him,_
so shall He be the same to us, as He hath been to our brethren and sisters in England,
Ireland, and _New England_ too, where some _suffered martyrdom for His name`'s sake._
And as we continue faithful in owning him before men, so he shall own us,
not only before our very persecutors, but also in the great and terrible day of the Lord,
before his Father and his angels.
And _we shall be as the palm-tree,_ +++[+++the emblem of constancy, fruitfulness, patience,
and victory,]--the more devils and men endeavour to _oppress_ us in our
public testimonies for His inward appearance,--__we shall rise the higher.__

Wherefore, I beseech thee, in God`'s holy fear,
take heed to thy proceedings against an innocent people; and let not the enemy within,
nor his instruments without, drive thee further on in this path,
wherein thou art walking,
lest thou be found fighting against God--then will God fight against thee,
and thou shalt not be honourable: for God hath said in the Scriptures,
_He will honour them that honour him,_ and on the contrary,
_They shall be lightly esteemed that dishonour him._
So, repent; and be warned from the Lord!--despise it not,
though it come through a weak instrument; for if thou do not mind it,
all thy endeavours in this persecuting way,
shall but tend to the filling up of the cup of thy secret and public
sins,--and thou shalt wish thou hadst died beyond seas,
and never seen thy native country.

Receive this as thou pleasest:--this I can say,
I have written it in true love and respect, both to thy soul and body,
as likewise in obedience to the Lord.
And what I have written shall stand as a witness against thee in the day of account,
and I shall be clear of thy blood:--but,
it is the earnest prayer of my soul to the God of power, that he may so second it,
as that it may produce fruits most acceptable to God, and refreshing to his people.

I rest, as formerly, however esteemed by thee, thy true and faithful friend,

[.signed-section-signature]
John Skene.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Robert Burnett to the Provost of Aberdeen.

[.signed-section-context-open]
Aberdeen Tolbooth, 28th of 8th month, 1676.

In the zeal of the Lord God, and in love to thy soul, do I write to thee,
being moved thereunto by his Spirit, which hath arisen in my heart,
with a mighty indignation and wrath against _that_ in thee,
which doth oppress his innocent seed in thine own heart,
and hath taken much rule in thy whole man.
This doth evidently appear, by what thou hast done,
in the entry of thy rule in this place, against God and his people,
whom he hath called out in this place to bear a testimony to his everlasting Truth.
They are made to suffer, for the exercise of their conscience towards God,
by an unrighteous generation,
who can lay no other deed to their charge but innocency and uprightness:
for this we rejoice, in the midst of our sufferings, and shall more rejoice,
through the strength of our God,
who rules heaven and earth,--that _all_ shall turn
to his glory and the good of them that fear him.
For, whoever may combine against him and his anointed, they shall not prosper;
their designs shall be turned backward, and their contrivances come to nought;
and our God shall arise, and be avenged on his enemies,
who would not that He should reign over them.

Friend, I am exceeding sorry for thee, that thou, of whom other things were expected,
should have a hand appearing against God,--yea, and his witness in thine own heart,
which, if thou mindest seriously,
will show thee the injustice and unrighteousness of thy proceedings,
contrary to what once were thine own principles.
Oh! shall the honour of this world, or any enjoyment of it,
which passeth away with the using, draw thee, or so prevail,
as to make thee provoke the glorious King of righteousness
to shut thee up in everlasting darkness and death,
and to lose the crown immortal, and the heavenly mansion that endures forever!
Oh! let nothing arise in thee, to deceive thee of thy birthright,
or to cause thee to think thou so standest that thou canst not fall.
A fall is abiding all those, that lift up their heel against the Almighty: for,
'`Who ever hardened himself against him, and prospered?`'

Let this be a warning to thee from thy true friend,

[.signed-section-signature]
Robert Burnett.

[.postscript]
====

Postscript.--Let none deceive themselves with that colour or pretence,
that they are commanded to do what they do by the higher powers,
and so think to be justified.
If so, then Pilate may plead the same; yea, and more,
who publicly declared his unwillingness to pass sentence against Christ,
who esteemed him a good and just man, and washed his hands, as innocent of his blood;
and yet,
if _he_ was not free of the murder of our blessed Lord,--no
more shall any of the present rulers,
who have an hand in the present persecution.

====

--

The last letter, being delivered into the provost`'s own hand by Margaret Cassie, was,
with the other,
received by the party addressed in a very different
spirit from that which actuated the authors of them;
the provost threatening to complain against them to the Council, and have them punished.

But the magistrates of Aberdeen seem now for some time,
to have been effectually brought over by the professed spiritual leaders of the people,
to exert their power in oppressing and persecuting this religious Society.
George Skene, the provost during the present year,
even exceeded his predecessors in executing his malice and cruelty upon them.
Almost immediately upon his entering into office,
he caused the prisoners to be more closely kept;
debarring them the liberty of going into the lower council-house, a privilege,
which they had before been permitted at times to enjoy;
and threatened some of the officers with the loss of their places,
for not acting up to the rigour of his orders.
And now, observing,
that these conscientious people were not to be deterred by the forfeiture of their property,
from returning to their meetings, he not only continued to send them again to prison;
but, in order to render their imprisonment as severe and incommodious as he well could,
would frequently remove them from one room to another,
merely to perplex them with the trouble of replacing their bedding and utensils.
This being in the winter season,
and one of these rooms having no chimney or other convenience for firing,
several of their relations solicited for their removal into another place;
this proposal some of the more moderate magistrates approved, as only reasonable.
But the provost would by no means give his consent, and even prevented,
so far as he could, any application to that effect being made to the Commissioners.
On the contrary, his evil disposition prompting him to be still more vexatious to them,
he proposed petitioning the Commissioners to give orders for the close
shutting up of all the prisoners in the higher part of the jail,
which was a very disgusting place; but in such a piece of downright cruelty,
he could not obtain the concurrence of the other magistrates.

With regard to Melvill, the person to whom the fines were made payable,
he went forward in his work of making havock among the little church,
as to their outward substance.
In order, however, to leave him inexcusable, as far as in them lay,
some of the prisoners found themselves under the necessity to address him: this they did;
setting before him, how unchristian an office he had undertaken,
and in much love cautioning him to beware how he proceeded further in his course.
+++[+++see Appendix, V.]
But he, likewise, turned a deaf ear to all their searching and persuasive exhortation,
and determined to proceed.
Fearing he had exceeded the bounds of his authority,
he applied to the Council`'s Commissioners, sitting at Turriff, for a fresh decree;
and this he procured from them.
Thinking himself now completely authorized, on the 30th of the month called October,
he took measures effectually to accomplish his purpose.
Twelve soldiers of the militia, with two messengers, came to John Skene`'s shop; and,
pretending his goods were not sufficient to cover the fine,
although those in sight were three times the value, proceeded to his dwelling-house,
where entrance was denied them.
On this, they applied to the provost for a warrant to break open his doors;
but before they could obtain it, night came on.
Next day, they came with smiths and hammers,
to break open the gate and doors of his house; but James Skene went to the magistrates,
then assembled, and made a legal protest,
importing that there were goods enough in the shop to answer their claim,
and if they should break open the house,
the magistrates must expect to be accountable for the damage incurred.
They advised Melvill to seize on the shop goods, which he did, to the amount of £130,
by their own valuation, carrying away the whole to the captain`'s house,
besides two other seizures made on Friends the same day.

His career was at length stopped for a season; for,
being obliged to secrete himself from a messenger and sergeants,
who were in quest of him for debt, he durst not appear, till that demand was compromised.
But no sooner had he got this effected,
than he returned to the prosecution of his commission,
and in the like unreasonable manner.
Coming again to the same individual`'s shop,
on pretence of the former seizure being defective, he took away more goods,
making in the whole £230 for a fine of £100. This plunder was not, however,
altogether gain clear of vexation and disappointment; for it appears,
that when John Skene`'s property was brought to the cross on a market-day to be appraised,
Patrick Livingston and James Halliday,
(of whom further mention is about to be made,) so spoke to the people out of their prison-windows,
that no man could be found, who would be concerned in the matter of appraisement.

These Friends, who both resided in England,
in the course of a religious visit to their brethren in this nation,
had come to Aberdeen, and being apprehended, were put into the _upper_ prison.
Here they had frequent opportunities, especially on market days,
to preach to the people the doctrine of Truth out of their prison-windows;
having more hearers there,
than probably they would have had in their own meetinghouse in more peaceable times.
Thus, even their confinement tended to promote the testimony they had to bear.
At this, the provost and others of their adversaries were greatly exasperated,
and held several consultations upon the means to prevent it;
but were at a loss to devise any plausible expedient,
fearing to give umbrage to the people, who were eagerly attentive to hear them,
should they proceed in any unusual method of severity against them.

In the meanwhile, further distraints and fresh imprisonments were going forward.
From Andrew Jaffray, Melvill and his followers took five or six oxen;
and from Alexander Skene cattle to the value of two hundred merks,
being nearly twice the amount of his fine.
In the latter instance, not finding purchasers to his mind for the cattle at the cross,
Melvill had them killed, and their flesh exposed to sale in the public shambles.
But the people generally refused to buy; so that, in the end, he found these cattle,
living or dead, were brought to a bad market.

David Barclay, it would seem, had by this time obtained his liberty.
No express record is made of the occasion of such
partiality being shown him by his oppressors,
so different from the treatment they meted out to his fellows.
Yet is there ample ground to impute this to the exertion used by his son, when in London;
which, though made on behalf of the sufferers _generally,_
and not at all pointedly on behalf of David Barclay,
(as is indeed evident in the foregoing address to the King,) took effect, it would seem,
with regard to _him,_ while it failed, at least for the present,
to obtain for the rest of the prisoners the reasonable indulgence sued for.
These exertions of Robert Barclay, were not confined to a direct application to royalty.
He wrote to the Princess Elizabeth; and by her reply,
which he received while he was still in London, it is clear,
she had already endeavoured to interest her brother, the Prince Rupert,
to use his influence for the liberation of the whole number,
but especially marking out _David Barclay_ to notice,
_his wife_ standing in the relation of third cousin to the Princess.
Her letter,
which opens a correspondence that subsisted between these eminent characters till death,
and is remarkable for its Christian simplicity, is here given.
+++[+++see Appendix, W.]

[.embedded-content-document.letter]
--

[.letter-heading]
Elizabeth, Princess Palatine of the Rhine, to Robert Barclay.

[.signed-section-context-open]
July 21st--31st, 1676.

My dear Friend in our Saviour Jesus Christ!
I have received your letter, dated the 24th of June, this day;
and since I am pressed to take this opportunity to
make a certain address unto your brother,
Benjamin Furly, I must give you this abrupt answer.

Your memory is dear to me,--so are your lines and exhortations very necessary.
I confess myself still spiritually very poor and
naked:--all my happiness is,--I do know I am so;
and whatever I have studied or learned heretofore, is but dirt,
in comparison to the true knowledge of Christ.
I confess also my infidelity to this Light heretofore,
by suffering myself to be conducted by false, politic lights.
Now that I have sometimes a small glimpse of the true Light, I do not attend it,
as I should; being drawn away by the works of my calling, which must be done;--and,
as your swift English hounds, I often overrun my scent,
being called back when it is too late.

Let not this make you less earnest in your prayers for me,--you see I need them.
Your letters will always be welcome to me, so will your friends,
if any please to visit me.

I should admire God`'s providence,
_if my brother could be a means of releasing your father and forty more in Scotland;_
having promised to do his best,
I know he will perform it,--he has ever been true to his word:--And you shall find me,
with the grace of our Lord,

[.signed-section-closing]
A true Friend,

[.signed-section-signature]
Elizabeth.

[.postscript]
====

P+++.+++ S. The Princess of Hornes sends you her most hearty commendations.

====

--

Robert Barclay had not long returned to his native country, and the bosom of his family,
when he was himself apprehended by order of the provost, together with Thomas Moor,
Thomas Milne, and John Forbes,
while they were attending their meeting for worship at Aberdeen.
The three latter were conveyed to the _higher_ jail;
and because the keeper did not confine him in the same place with them,
the provost was highly offended.
His commitment was on the 7th of the 9th month; and by the next month,
the news of his confinement reached his friend, the Princess Palatine,
probably with some circumstances of exaggeration,
as appears from the following letter to her brother, the Prince Rupert.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Herford, December 19th, 1676.

[.signed-section-signature]
Dear Brother,

I have written to you some months ago by Robert Barclay, who passed this way,
and hearing I was your sister, desired to speak with me.
_I knew him to be a Quaker by his hat,_
and took occasion to inform myself of all their opinions:
and finding they were so _submiss_ to the magistrates in real, omitting the ceremonial,
I wished in my heart, the King might have many such subjects.
And since, I have heard,
that notwithstanding his Majesty`'s gracious letter
on his behalf to the Council of Scotland,
he has been clapped up in prison with the rest of his friends;
and they threaten to hang them, at least those they call preachers among them,
unless they subscribe their own banishment; and this,
upon a law made against other sects,
that appeared armed for the maintenance of their heresy;--which
goes directly against the principles of those,
who are ready to suffer all that can be inflicted,
and still love and pray for their enemies.

Therefore, dear Brother, if you can do any thing to prevent their destruction,
I doubt not but you would do an action acceptable to God Almighty,
and conducive to the service of your royal master:
for the Presbyterians are their main enemies, to whom they are an eye-sore,
as bearing witness against all their violent ways.

I care not, though his Majesty see my letter;
it is written no less out of an humble affection for him,
than in a sensible compassion of the innocent sufferers.
You will act herein according to your own discretion; and, I beseech you,
still consider me as

[.signed-section-closing]
Yours,

[.signed-section-signature]
Elizabeth.

--

One brief comment on the foregoing letter, merely by way of information,
may perhaps be due to some of the younger classes of readers,
who profess with the Society of Friends,
as well as to others who do not.--The Princess knew Barclay to be a Quaker by his hat,
and _thereupon_ took occasion to inform herself of all their opinions.
Neither the Princess, nor Barclay, nor the Friends of Barclay in that day,
placed any undue value upon singularity of external appearance, merely as such.
The costume of the Friends had, before this date, become peculiar,
and conspicuous for its simplicity,
in consequence of the extravagance and preposterous fashions generally prevalent.
They kept, with but very slight variation,
to the mode of dress in use among sober-minded people
at the time they had their rise in these kingdoms;
and considered it one mark of a little and degraded mind, to be frequently,
or without some sufficient occasion, adopting "`changeable suits of apparel.`" Isa. 3:22.
It was this view of the subject,
which made them nonconformists to the fashion of a passing world,
as well as to the manners of those that love it;
their close scrutiny into the motives for all their conduct, induced a caution,
a jealousy, a precision in these respects, which while wholesome and beneficial,
appeared to be consistent with the apostolic injunction,
"`Be ye holy __in all manner of conversation__`" 1. Peter, i. 15.

While Robert Barclay lay in the Tolbooth of Aberdeen, Melvill,
who had been one of his father`'s troopers, came to Ury with his party,
bent on executing against David Barclay,
the warrant he had from the Commissioners to distrain for the fine.
The iron gate being shut, and the family at dinner,
the man had to wait awhile for admission, which might have somewhat irritated him.
For when his former master and colonel, on examining the warrant, told him,
_that_ could give him no authority within his estate, which lay in the shire of Mearns,
whilst the decree of the Commissioners, under whom he acted,
extended only to the shires of Aberdeen and Banff;
he would by no means desist from his purpose, but, adding one illegal act to another,
proceeded to take away ten honouring oxen, in the ploughing season,
(which was by act of Parliament prohibited, even in case of a just debt,) also two cows,
a bull, and a quantity of corn.
These cattle proved a troublesome acquisition,
for he could find no man that would buy them,
and the expense of keeping them was a continual burden to him;
so that he seems to have been well tired of them,
before he could at any rate get them disposed of.
At last, this remarkable opportunity offered.

The Friends engaged in the dispute with the students of Aberdeen,
thought themselves unhandsomely treated on that occasion, and also by the reports of it.
They accordingly published a particular account of the whole circumstance,
to which the students drew up a reply;
but no printer being willing to undertake their proposed publication at his own risk,
they with some difficulty raised the money,
hoping to be reimbursed by the sale of their book.
But to their mortification almost the whole impression remained on their hands unsold:
this induced them to represent their loss by petition to the Commissioners,
and to request some relief out of the exchequer.
By the Archbishop`'s influence in their favour,
these students obtained from the Commissioners an order upon Captain Melvill,
to pay them a part of the "`Quakers`'`" fines in his hand;
upon which he gave them David Barclay`'s oxen,
and with this they raised the money they wanted.
