== Chapter XI.

[.chapter-synopsis]
* 1677: Pretence, that the "`Quakers`" were Popishly affected
* The king`'s commissioners grant them present relief: some of the prisoners obtain their liberty, others are removed to Banff
* Previous to this, Friends address the council, and Robert Barclay writes to Archbishop Sharpe
* Misunderstanding between the magistrates of Aberdeen and the under-sheriff
* Disgraceful affair among the instigators of persecution
* John Forbes, deputy-sheriff, and the magistrates of Banff, treat the prisoners with great civility
* Aberdeen prison for a short interval cleared of Friends

One of the chief pretences, which the public preachers and magistrates made use of,
to palliate their unjustifiable treatment of the people called Quakers, was,
that they were _Popishly affected,_
and advancers of the interests of the Church of Rome:--a
pretence altogether false and groundless.
At the same time,
they themselves were by no means clear of openly flattering
and caressing the most eminent Papists in the land;
as the following instance proves.

The Marquis of Huntly, as noted a Papist as any in Scotland,
and one who greatly promoted that class, was bringing home his wife,
the daughter of the Duke of Norfolk,
one of the foremost among the same persuasion in England,
and she herself very zealous in the Roman Catholic religion.
On their entrance into Aberdeen,
the magistrates drew together a great number of the citizens,
and with much parade went forth to meet them,
expressing all the usual tokens of the utmost respect; so that on that occasion,
"`the whole town appeared in a manner taken up with the grandeur of the ceremony.`"
This was not noticed by the Friends of that day,
with a view of detracting from the station of the Marquis;
but only to show the hypocrisy of those, who,
while they themselves publicly flattered and paid great attentions to the chief Papists,
could thus colour their cruel persecution of the poor "`Quakers`"
with the pretence of their affinity to Popery.

In the second month, 1677, the Commissioners of the Council met again at Ellon,
where Burnett the bailie was again deputed to attend them,
and strenuously endeavoured to justify their proceedings against this people,
under the idle pretext, that they had not room for their better accommodation.
But, many persons appearing on behalf of the prisoners,
and representing the cruelty of their confinement,
the Commissioners resolved to afford them some present relief; and thereupon decreed,
That, _considering the extraordinary trouble sustained by the magistrates and burgh of Aberdeen,
through the many Quaker conventicles held in the Tolbooth,
and that others have been urged to throw themselves into the snare of imprisonment,
for the purpose of molestation,_--the following persons be
removed from thence to the Tolbooth of the burgh of Banff,
till further orders; namely, Robert Barclay, George Keith, Patrick Livingston,
John Skene, James Halliday, Thomas Mercer, John Lesk, John Cowie, and Thomas Milne.
Likewise, that David Barclay, Alexander Skene, Robert Burnett, Alexander Gellie,
and Andrew Jaffray, be removed from the prison of Aberdeen,
and confine themselves to their country houses and parishes; at the same time,
to be prohibited from permitting unlawful meetings in their houses,
or frequenting them elsewhere.

In making this decree, there is reason to believe,
that the Commissioners were some way influenced by the King`'s
recommendation to the Council at Edinburgh before recited.
This recommendation, as we have seen, had been referred by the latter body,
to certain Commissioners appointed for carrying into
execution some acts of the Scottish Parliament,
against what was termed "`keeping conventicles, and withdrawing from divine worship.`"
It was under these acts, that the Friends in the north of Scotland had been persecuted;
and it was by some of these same Commissioners, that the above decree was made.

Pursuant to such decision, five of the prisoners were set at liberty; but,
on being told the purport of the Council`'s order,
as to their confinement within their respective parishes,
and prohibition from attending meetings, they answered, That they accepted their liberty,
but as to the restriction enjoined upon them,
they must act as they should find it their duty.
Those who were ordered to be removed to Banff, were delivered over to the sheriff,
who gave them also their liberty, on condition of being forthcoming,
when he should appoint a time to convey them thither.

Before this took place, however,
the Friends had thought it right to represent their
case in an address to the Council itself.
And further, Robert Barclay, being informed, that the Archbishop Sharpe,
was a chief instigator of their sufferings,
had expostulated with him in a very plain and forcible letter,
full of "`sound wisdom and discretion.`"
The address and letter are as follow.

[.embedded-content-document.address]
--

[.letter-heading]
Unto The King`'s Council, the suffering People of God, called Quakers,
in and about Aberdeen,

[.salutation]
Showeth,

That albeit the nature of our known principles,
and our practice thereunto corresponding since we were a people in this nation,
free us of all just ground of suspicion of being disturbers of the common peace,
or prejudicial to the present government;
and that the innocent and harmless exercise of our
consciences in our peaceable and Christian assemblies,
doth not, as we conceive,
come under the genuine purpose of those laws made against the seditious conventicles.
Yet, upon the Council`'s declaration emitted a year ago, upon the 12th of the month,
called March, 1676, several of us were taken prisoners,
and afterward at sundry times to the number of forty and upwards;
against whom these acts being executed to the rigour,
many of them have had their goods miserably spoiled,
most to the double and some to the treble, of their fines uplifted,
of which divers are again retaken,
to the great prejudice and apparent ruin of several poor and desolate families,
and the impairment of our health,
having wanted the accommodation of fire this cold winter season.
And now of late, to sum up all with an unparalleled piece of inhumanity,
certain of the magistrates of this place,
have by importunity obtained an order from some of the Council`'s Commissioners here,
to dispose of us in some other place;--upon pretence that their
courthouse could not be spared longer for a prison for us,
notwithstanding they have an empty place where they could,
and others of them would have secured us;--yet, by a certain malicious barbarity,
shameful to be named among Christians, _they have thronged up fifteen of us in two narrow,
stinking holes,
where each of us have not so much room as could not be denied us in the graveyard,
and so are forced to lie one above another with boxes,_ notwithstanding the vault below,
and not water-tight; and others of us they have put in a cold, dark,
narrow place within the town.

May it therefore please the King`'s Council,
seriously to weigh and consider our condition, who have been now _above a year_ in prison,
and order our releasement: leaving to the magistrates of this place,
to inform the Council of what they have or can say against our peaceableness,
to make use of the pretence of law to execute their
private prejudices by continually imprisoning us.
And we shall then be always most ready to present ourselves before the Council,
upon the smallest intimation;--as at this time we are willing to do,
in case the Council shall see meet,
or think we have aggravated our sufferings;--not doubting,
but upon a full and impartial hearing,
it will appear we have been (all circumstances considered)
very forbearing and modest in this address;
and therefore shall expect, that the Council,
according to the wisdom and justice becoming their station,
will comply with this our most reasonable desire,
as such who regard equity without respect of persons.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To James Sharpe, Archbishop of St. Andrews (so called.)

My being personally unknown to thee,
hath hindered me to give way to that pressure of mind,
whereby I have felt myself oftentimes moved to write to thee,
because I was loath to trouble thee.
But, since there is an address intended to be presented to the Council,
at their first sitting, in behalf of me and my friends,
I could no longer forbear upon this occasion,
to signify unto thee what hath been upon my mind for some time towards thee.
The address itself will inform thee, how we have been upwards of a year prisoners,
and the goods of many poor people miserably spoiled; of which,
thou art said to be the chief and principal author;
and that the attempting to persecute us, as well as the prosecution of it,
doth proceed from thy influence, as being done either at thy express desire,
or by some others, in hopes thereby to gratify thee.

How far thou art truly guilty thereof, thine own conscience can best tell.
But surely, such practices (if thou hast, either directly or indirectly,
had a hand in them) will neither commend thee to God nor good men.
I presume, thou lookest upon it as thy chiefest honour, to be reputed a Christian bishop,
deriving thy authority from Christ and his apostles:
but they never gave warrant for any such doing,
being preachers and practisers of patience and suffering, but never of persecuting,
or causing rob any of their goods or liberties, for their conscience sake.
And long after, even several centuries,
the primitive bishops abhorred and detested such proceedings.
Hence, the excellent and zealous Athanasius saith, That it is the devil`'s work,
and not God`'s, to force men`'s consciences; affirming,
That the blasphemous Arians (who were the first bearing the name
of Christians that used this practice) have learned so to do,
not of God, but of the devil and his wicked angels.

Considerable are the testimonies of Tertullian, Haesius, Hilarius, Jerom, and others,
given to the same truth; so that Ambrose declares, That, going into France,
he refused all communion with such bishops,
that had any fellowship with those that sought to
destroy even such as were departed from the faith.
I confess, the bloody bishops of Rome gave large precedents of such actings; but,
I suppose, thou art not ambitious to be ranked among them,
or to be accounted an imitator of them in that respect.

How far thou art justifiable in thy concurring with,
or advising the persecution of the Presbyterian dissenters,
is not my business to determine.
But I am confident, thou art willing it should be judged, that thy so doing against them,
is not merely for their consciences; but because their principles do naturally,
or necessarily, imply an innovation in the State, and thy personal ruin;--believing,
not only military resistance just, to protect themselves against authority,
but also an offensive endeavour to turn out their superiors,
and establish themselves in their overthrow,
both lawful and laudable,--as their practice hath sufficiently demonstrated.

But should thou now be found a positive persecutor of such,
against whom nothing of that kind, neither from principle nor practice, can be alleged,
but only the simple exercise of their conscience; would not that give plentiful occasion,
for such as desire to represent thy other actions with the worst aspect, to show,
(whatever thou pretendest of the State`'s security,)
yet thou art a persecutor of _pure conscience,_
since thou showest thyself such towards those,
against whom the former reason doth not hold?

And surely, it would seem,
that the more our peaceable principle takes place among other dissenters,
thy interest will be the more secure;--which is a
consideration not unworthy of thy notice,
as deserving thy favourable aspect towards us.
Perhaps the violence as well of the preachers, as of some magistrates here,
from whom our sufferings originally do flow, may at first view seem acceptable to thee,
as faithful friends as well of the public as of thy interest;--and, no doubt,
they judge with themselves, that they ingratiate themselves with thee, in so doing;--yet,
did thou know them as well as some of us do,
thou mightst think it no great absurdity to conclude,
as well from their practices as principles,
that they would be no less ready to give thee this same treatment,
had they but the like opportunity of doing it; and rejoice more in it,
as a great service both to God and the '`Kirk of Scotland:`' however, that now +++[+++being]
out of their reach, they make what use of the law they can,
both to execute their malice on us, and flatter thee, at this juncture.
In short, we have more than reason to believe,
that if thou oppose thyself to this our address, it will not be granted;
and if thou show thyself moderate and flexible,
it will not be denied,--as no mean persons have hinted to us.
So, as the one will be an evidence of thy moderation,
the other will be a testimony of thy inclination to persecute.
I wish then, for thy sake as well as ours, that this occurrence may rather commend thee,
than discommend thee.

And thou mayst assure thyself, that the utmost rigour that can be used to us,
shall never be able to make us doubt of, or make us depart from that living,
precious Truth, that God in his mercy hath revealed to us,
and by us is embraced:--nor yet fright us from the public profession of it;--yea,
though we should be pursued to death itself, which, by the grace of God,
we hope _cheerfully_ to undergo for the same: and we doubt not,
but God would out of our ashes raise witnesses,
who should outlive all the violence and cruelty of man.
And albeit thou should thyself be most inexorable and violent towards us,
thou mightst assure thyself, not to receive any evil from us therefore; who,
by the grace of God, have learned to suffer patiently, and with our Lord and Master,
Jesus Christ, to pray for and love our enemies.
Yet, as thy so doing to an innocent and inoffensive people,
would be an irreparable loss to thy reputation; so, the God of truth,
whom we serve with our spirits in the gospel of his Son, and to whom vengeance belongs,
(so we leave it,) would certainly, in his own time and way, avenge our quarrel;
whose dreadful judgments should be more terrible unto thee,
and much more justly to be feared,
than the violent assaults or secret assassinations of thy other antagonists.

That thou mayst prevent both the one and the other, by a Christian moderation,
suitable to the office thou layest claim to, is the desire of thy soul`'s well-wisher,

[.signed-section-signature]
R+++.+++ Barclay.

[.signed-section-context-close]
From the Chapel Prison of Aberdeen, the 26th of the 1st month, 1677.

--

It is more than probable, that both these documents had weight with that body,
of which Sharpe was so prominent a member.
For, thereupon, they issued an order to the Commissioners,
appointing a day for receiving from them information as
to the condition and circumstances of the prisoners;
and directed, that, in the mean time, they should be provided with better accommodations.
This order of Council caused much dispute between
the magistrates of Aberdeen and the under-sheriff:
the former insisting,
that the sheriff should take to Banff such prisoners as
had been ordered thither by the decree of the Commissioners;
and the latter refusing to convey them,
and pressing the magistrates to accommodate them better,
in accordance with the Council`'s order,
which bore a date subsequent to the Commissioners`' decree.
The contention grew violent,
and each party entered formal protests at law against the neglect of the other.
Under these circumstances,
when neither of the contending parties would accept the disposal of the prisoners,
Robert Barclay and five of his companions went before a notary and protested,
that _they were freemen, and should pass away about their lawful occasions._

Most of those who by this means obtained their liberty, went away to Edinburgh,
that they might do their utmost to procure the enlargement or relief of their brethren,
still detained in bondage; whose condition was in no wise alleviated,
notwithstanding the Council`'s injunction to that purport.
But the magistrates were not satisfied with continuing
thus unfeelingly and wantonly to oppress their prey;
for, even on the very day of the liberation of these Friends above mentioned,
they stirred up the Commissioners at Aberdeen, and jointly with them,
wrote a virulent letter to the King`'s Council at Edinburgh against the "`Quakers;`"
in order to hinder them from having access to be heard in their just complaints,
which some of their number were at that time attempting to lay before the Council,
and for whose sakes Robert Barclay in particular
was then strenuously soliciting at Edinburgh.

There happened also at this juncture an occurrence,
in which the zeal of the Friends who were still prisoners at Aberdeen,
having offended some of the public preachers,
excited in like manner the Synod at that place,
to join in misrepresenting them to the Council.
The case was as follows.--A Synod of the diocese being convened at Aberdeen,
several of these professed ministers, having drank too freely,
were observed to be staggering in the streets,
and actually incapable of walking without the assistance of others.
Some of the Friends, taking notice of this fact from the window of their prison,
were incited to warn the people against such conduct; showing,
that while those called "`Quakers`" were imprisoned
for meeting peaceably to worship the Almighty,
these teachers, whose ministry they were persecuted for relinquishing,
were permitted with impunity to stagger up and down the streets with drunkenness,
at the very time they professed to be met for the government of the church.

This public rebuke was highly resented as a great
indignity to those termed the clergy in general,
several of whom wrote to the King`'s Council expressly about it,
representing the Quakers in prison as so insolent and abusive,
_that a clergyman could not quietly pass the streets for them._
The magistrates also wrote largely to the Archbishop,
earnestly requesting his assistance _"`in suppressing the Quakers.`"_
Thus, by a joint concurrence of the Commissioners, the magistrates of Aberdeen,
the Synod of ministers, and the Archbishop,
the cause of the innocent sufferers was obstructed;
the honours of their brethren with the Council in a great measure frustrated;
and the business concerning them again remitted to the Commissioners in the north.

These Commissioners, meeting at Aberdeen on the 16th of the 3rd month,
passed a declaration, ratifying, as might be expected,
their former sentence against Friends;
the execution of which had been hitherto impeded
by the intervention of cross orders from the Council.
Pursuant to such decision, John Forbes, the deputy-sheriff,
had apprehended several of the Friends, in order to convey them to the Tolbooth of Banff.
But this individual, being humane and utterly averse to persecution,
treated them with great civility; ordering a guard to attend them thither,
with directions to let them have all suitable accommodations on their way,
and to take their own time;
so that they were allowed the opportunity of visiting their friends,
and holding several religious meetings as they passed along;
in which they had such remarkable service, that some of their conductors were convinced,
and effectually converted to the blessed, pure, gospel Truth promulgated by them.
On their arrival,
the prisoners met with a reception far different from that which they had had at Aberdeen;
for the magistrates of Banff were courteous and even liberal,
not only granting the most commodious arrangements of which the Tolbooth was capable,
but permitting them to make use of an inn in the town at their pleasure,
during their continuance in the place.
In addition to this,
these magistrates used their influence with the Commissioners
and sheriff to procure the release of the prisoners;
nor did they cease from their exertions,
until they had obtained liberty for them to return to their several habitations.

But the civil authorities of Aberdeen, on the other hand,
had suffered their spirits to be so far embittered against this people,
who had done them no wrong, that neither the example of others,
the manifest dislike of the sober and moderate inhabitants,
the disgrace they had incurred by their cruelty, nor a regard to justice and equity,
had any power to move them to sentiments of humanity.

In one instance, indeed, the provost appears to have been induced,
from motives of policy, to suspend the exercise of his malice towards Friends,
and to act with some semblance of lenity.--Many of
the prisoners of Aberdeen being now at liberty,
in consequence of the above-mentioned misunderstanding between the magistrates and sheriff,
and others of them, who had lands, being also at large,
although considered prisoners on their own estates;
the provost had no longer in his custody those,
against whom his prejudice and indignation chiefly burned: that he might, therefore,
appear to have some generosity and feeling towards the poorer class,
he came to the conclusion, that,
_as the greater ones among the "`Quakers`" had all escaped,
he would let go the smaller ones._
They were nine in number; and among them, is the name of poor George Gray, the weaver,
who has been before noticed as an example in patient suffering.
Accordingly, on the 23rd of the 3rd month, 1677,
these presumed offenders against the laws were dismissed from their confinement;
but with the fixed intention, on the part of the provost, to recommit them,
on the earliest occasion of their meeting together for their well-known
conscientious purpose,--the worship of an Almighty Creator,
the Father of mercies!
