== Chapter XIII.

[.chapter-synopsis]
* Lilias Skene`'s expostulatory letter to Robert Macquare
* 1677:Robert Barclay`'s second journey to Holland and Germany: his letter to the Princess Elizabeth
* Continuance of persecution during the space of two years and a half-reflections
* Constancy of Patrick Livingston
* 1678: He, with George Gray, and Andrew Jaffray are thrust up into the iron house
* The favour and providence of God towards the sufferers
* Archbishop Sharpe`'s end, with the removal by death or otherwise of the most active persecutors

An early portion of these Memoirs has been appropriated
to an Exhortation from the pen of Alexander Jaffray;
and it was designed that, in the present chapter,
should be revived a Piece of similar description, but by another hand,
and of no ordinary character.
It was however found needful, in the arrangements for the volume,
that the Piece now alluded to should be consigned to the Notes.
This measure was adopted with some reluctance;
and therefore the reader is particularly invited to a perusal of the document,
before he proceeds further.
+++[+++see <<note-X,Appendix, X.>>]

The Friends at Aberdeen were last noticed, as being,
through the summer and autumn of 1677, continually harassed with a prison allotment.
Before reverting, however, to their condition,
and carrying onward the narrative of their trials to its full extent of severity,
and to its termination; it will be needful, in the order of events,
to turn for a short interval to some engagements of one of their little band,
whose temporary separation from his companions and from this scene,
placed him in a condition for renewed exertions on their behalf,--and in a way, which,
it is believed,
materially operated towards their recovery of those civil and religious privileges,
from which they had been so long debarred.

Robert Barclay`'s acquaintance with the Princess Elizabeth of the Rhine,
and the intimation she gave of her purpose to intercede, so far as lay in her power,
for the liberation of the Friends in Scotland,
will doubtless be fresh in the recollection of the reader.
Very shortly after his release from prison, in the 2nd month, 1677,
Robert Barclay travelled into the south, was at London in the following month,
and early in the 6th month paid a visit to his friend, the Princess,
at Herwerden in Germany.
The objects which he had before him by this journey into England,
and a tarriance there for the space of two months, may have been various;
but on these points there are no documents that supply scarce any information.
It is clear, however, with regard to his travels on the Continent,
that he had expressly in view,
to pay a visit in the character of a minister among those churches,
that were then gathered to the same religious acknowledgment with Friends,
as well as among others whom he might find seriously disposed to seek the way of salvation.
His companions were George Fox, William Penn, George Keith, and Benjamin Furly,
with two or three more.
At Amsterdam, it appears,
they proposed to the General Meeting of Friends then convened there,
a method of regularly transacting church discipline,
adapted to the state and exigency of that body.

But it does not altogether come within the scope of these Memoirs,
to go into Robert Barclay`'s services in particular, while on this gospel errand,
much less those of his fellow-helpers;
nor even to give an account of their visit to the Princess Elizabeth; William Penn,
in the Journal of his travels,
having drawn a very lively and touching description of their interviews,
the reader is referred to his account.
The object of this digression from the transactions of Friends in the north of Scotland,
has rather been, to explain the absence of Robert Barclay from that scene of action;
and to show,
by the statement of collateral circumstances,--but especially by the succeeding letter,
which he wrote to the Princess soon after his return to England,--that
the painful subject of the persecution of his fellow-countrymen,
did not cease to lie very near his own heart, and that of his valuable correspondent.

[.embedded-content-document.letter]
--

[.letter-heading]
Robert Barclay to the Princess Elizabeth.

[.signed-section-context-open]
Theobald`'s, near London, 12th of the 7th Month, 1677.

[.salutation]
Dear Friend,

By thy letter of the last of the month past,
I understood that the Friends were with thee,
and was refreshed by the account they gave me of thy kind and Christian
entertainment of them,--they having overtaken me in Holland.
God will not be wanting to reward thy love, as well as to increase the same.

Finding no ready passage for Scotland, I came over here;
and albeit I had no great expectation of success, I resolved once more to try thy cousin,
the Duke of York, +++[+++afterward James the 2nd.]
So I told him, that I understood from Scotland, notwithstanding Lauderdale was there,
and had promised, ere he went, to do something,
yet our Friends`' bonds were rather increased;
and that there was now only one thing to be done,
which I desired of him,--and that was,--To write effectually to the Duke of Lauderdale,
in that style wherein Lauderdale might understand, that he was serious in the business,
and did really intend the thing he did write concerning,
should take effect;--which I knew he might do,
and I supposed the other might answer;--which, if he would do,
I must acknowledge as a great kindness.
But if he did write, and not in that manner,
so that the other might not suppose him to be serious,
I would rather he would excuse himself the trouble; desiring withal,
to excuse my plain manner of dealing,
as being different from the court way of soliciting:
all which he seemed to take in good part, and said, he would so write as I desired,
for my father and me, but not for the +++[+++persecuted Friends of Aberdeen in]
general.
So, he hath given me a letter: whether it will prove effectual or not,
I cannot determine; but of this thou mayst hear hereafter.

I am now entered into my journey, and intend to pass by the way of Ragley.

What thou writest of the counsellor of the Elector, and the other preachers,
is very acceptable to me to hear; whose joy it is,
to understand that the eyes of any are opened to see the Truth,
as it is in this day revealed;--as it should be much more,
to hear that any came into that universal obedience,
which the life and power thereof lead to: which life and power,
as they are felt in the inward part,
are more than all the words that can be spoken;--of which, I know,
_thou_ hast at some times not been insensible.
And therefore my soul`'s desire for thee is,
that thou mayst more and more come out of all that which cumbers,
to feel this virtue of Truth to operate in,
and redeem thy soul from all the difficulties that do or may attend thee.
This, in the nature of it, it is powerful to do,
albeit thy temptations were greater and more numerous than they are;
if received by thee in the love of it,
and with a heart fully resigned to obey it in all its requirings;
without consulting with flesh and blood,
or turning by the plain and simple leadings thereof by wise and fleshly reasonings,
which will never admit of the government and rule of the cross
of Christ:--as thou well knowest and wilt not refuse to acknowledge,
and therefore art the more concerned to watch against it in thy own particular,
as I hope in measure thou dost, and my heart`'s desire is.

Thou mayst make mention of my dear and tender love to Anna, whose servant,
as also the French woman, I forget not.
To Anna I thought to have written apart; but must now leave it until another opportunity.
If thou seest meet to salute that counsellor of the Elector in my name, thou mayst do it.

I shall add no more at present, but that I am thy real and unfeigned friend,

[.signed-section-signature]
Robert Barclay.

--

One or two circumstances occurring in the above letter,
are briefly adverted to in the Notes, to which the reader is referred.
+++[+++see <<note-Y,Appendix, Y.>>]
It is pleasing to derive fresh evidence from its contents,
that the influence that Robert Barclay, as well as his father,
possessed with some who at that time moved in the highest circles,
was by no means turned to the gratification of pride, avarice, or ambition;
but rather applied for the purpose of advancing the interests of sober piety, and that,
with a sincere regard for the real welfare of all with whom he had to do.

We are not informed,
what effect was produced by the letter obtained from
the Duke of York in favour of the Barclays,
to which allusion is made in the foregoing.
There is, however, no reason to doubt, it was delivered to the Duke of Lauderdale,
on Robert Barclay`'s arrival in Scotland.
The Memoirs of the family, indeed, state in general terms,
that the release of both the father and son took place _"`by an order from court,
with a reprimand for meddling with either of them;`"_ and that _the "`son afterward
procured the liberation of his other friends who were detained after them.`"_
It is presumed,
this must be understood of the above-mentioned imprisonment
of David Barclay and others in the course of this year:
but it does not expressly appear, _how soon_ Robert`'s lot was cast among the prisoners,
after his return home, nor _when_ his release, with that of his father, was effected.

It may here be briefly named, that about two years subsequently,
he journeyed a third time on the Continent.
His engagements in this instance are but little known,
beyond the circumstance of his having proceeded _by way of London to Holland,_
"`upon account of visiting and acting for his friends;`" also that at Rotterdam,
he again addressed the Princess by letter,
"`excusing himself for not seeing her at that time;`" _"`a
copy of which,`"_ continues his grandson in the Memoirs,
_"`I have.`"_

In the ancient record which has furnished a chief groundwork for the present
historical account of this persecution of a Christian people,
there occurs, about this period, a considerable chasm;
so that the touching circumstances of their afflictive allotment,
can no longer be portrayed, as hitherto, in detail.
This deficiency in the narrative, it is of course in vain to expect,
at this distance of time, should be in any wise supplied from other sources.
We are only informed, in general terms, of the continuance of the scene,
which has been largely opened before us in former pages;
the like treatment being dealt out to the sufferers,
and by them received in a similar spirit,
_during the protracted space of about two years and a half;_ that is,
from the date of their last-mentioned commitment in the 4th month, 1677.

But, perhaps, enough has been said in proof of that assertion,
the truth of which cannot be too strongly fastened on the mind of the believer,
and which was well expressed by Calvin in these few
words,--"`God never in any thing hath failed those,
who have been led and guided by his Spirit.`"
Enough, also, has been already brought forward,
in illustration of the cruel and vindictive character of an earthly or "`carnal
mind,`" proving this to be at once "`enmity against God`" and all goodness;
and showing, as the Scripture imports, that he who is _born after the flesh,_
will ever be disposed to persecute him that is _born after the Spirit._
Yet might it have proved interesting,
to have known more minutely the history of this interval; a period,
which was probably marked, in the remembrance of the sufferers,
as strongly as all others,
both by the bitterness of the cup permitted to be meted out to them,
and by the heavenly drops that; were in mercy mingled with it.
And truly, how inadequately are developed, in many parts of the foregoing memorials,
those glowing beauties of holiness,
that "`peace of God which passeth understanding,`" and that "`lively hope`"
which is as "`an anchor to the soul,`"--the portion of all such as "`receive`"
and "`obey`" "`the Truth as it is in Jesus,`" loving "`his appearing.`"
How often were these meek and patient followers of the Lamb, as we may truly believe,
"`strengthened with might in the inner man,`" by "`the effectual
working`" of that power in which they believed,
for which they waited, and towards which they fervently aspired!
When deprived of their domestic comforts, day after day and month after month,
as well of the endearments of home, as of all those minor accommodations,
for which flesh and blood plead, and unto which poor human nature is so apt to cling;
how were they from season to season raised up,
and carried aloft in the spirit of their minds,
above "`the things which are seen`" and "`perish with the using!`" how
were they made to "`sit together in heavenly places in Christ Jesus,`"
and enabled to return unto the Lord all the thanks and all the glory,
for the exceeding riches of his grace,--the aboundings of his lovingkindness!
Nor are we short of being amply borne out in such conclusions;
as will appear by reference to a small portion of the rough outline traced by themselves,
where, in a summary and general way,
they wind up the ancient memoir of their troubles to its close.

__Extract--__"`And it is never to be forgotten, but worthy everlastingly to be recorded,
how wonderfully and gloriously '`the Lord from heaven`' countenanced and owned our sufferings,
by the signal pouring forth of his Holy Spirit and power among us,
beyond whatever we had formerly known, for our encouragement in our trials,
within a month or thereby after our imprisonment; that,
not only was our prison turned to a house of prayer and praises,
but so mightily did the Lord`'s power break in upon and amongst us, and the glorious,
heavenly sound thereof go forth, that it amazed our very enemies.`"

Among the foremost champions in this prolonged contest for the excellent,
pure liberty of the gospel of truth and righteousness, was Patrick Livingston.
He was born near Montrose, as has been before stated; but marrying in England,
about two months after, he came into his native country to visit his friends; where,
as we have seen, he soon partook of their ordinary portion--that of incarceration.
To the great disadvantage of his temporal concerns,
and grievous trial of the faith of his partner in life,
the term of his detention in prison, from first to last, proved to be three years;
during all which time, he was never called to appear before any judge or court,
that he might have his crime laid to his charge or proved against him; although,
at the desire of some who commiserated his hard condition,
he was several times allowed his freedom, for very short intervals of a day or two only,
speedily becoming entrapped again in the same snare.
For, being of an upright and noble spirit,
and having come into that country with an innocent, nay, most commendable intention,
he could not see it right for him, when dismissed from prison,
to withdraw himself from the scene of action, as one who had been guilty of evil;--and,
moreover, he felt bound by the ties of brotherly sympathy and Christian love,
to stand by his companions in their afflictions.
No sooner, therefore, was he at any time set at liberty, than he returned to his post,
as a good soldier of the Prince of peace, not daring to turn his back,
or shrink from exposing himself in the line of that most essential duty,
of publicly drawing near "`in spirit and in truth`" to Him "`who is a spirit.`"

In this way, by example as well as exhortation, did Patrick Livingston,
whether in bonds or out of bonds,
greatly uphold and strengthen the hands of the little flock,
towards some of whom in an especial manner,
he stood in the relation of "`a faithful minister in the Lord,`" having been the means
of gathering their souls to the inward appearance and "`patient waiting for Christ.`"
So sensible of this, were those who vehemently sought to lay waste this testimony,
and so troubled at his unwearied and unyielding zeal,
that they would several times _let him go forth_ from among his companions in custody,
or _miss_ some meeting he was known to be at; and,
being conscious how they had wronged him,
would have been glad of some means of being disencumbered of him,
could they have effected this with credit to themselves.
He would often acknowledge to his friends, that he still felt his mind fettered,
so that he could not be satisfied to leave them; but,
after attending the Monthly Meeting in the 9th month, 1679,
he appeared to have a prospect of the cessation of persecution,
and signified that he was wholly clear,
both in the sight of his Maker and with respect to all men,
to return to his home in England.
It was remarkable, that, after this period,
Friends were left to enjoy without interruption their religious meetings;
nor were they afterward deprived of their personal liberty,
for endeavouring to fulfill the apostolic injunction--"`I will that men pray everywhere,
lifting up holy hands, without wrath and doubting.`" 1 Tim. 2:8.

During the close imprisonment of many of this people in the Tolbooth of Aberdeen,
three out of their number, namely, Patrick Livingston, just noticed,
with George Gray and Andrew Jaffray, were the most frequently engaged,
in the aboundings of Christian love,
to preach to the people "`out of their prison-windows, especially on market-days,
exhorting them to fear the Lord, and to obey the gospel of his grace.
This practice was highly displeasing to the magistrates.
They therefore sought to prevent it,
by causing these three individuals to be separated from the rest of their companions,
and violently thrust up into a close vaulted cell, situated on the top of the jail,
and called the _Iron-house,_ where the worst of felons and murderers were usually confined.
They had neither light nor air, except through a long hole in the thick wall,
which had a double grating of iron on the outside, and another within.
Here they were kept night and day, in the heat of the summer of 1678;
when the filthiness of the place, and the corruption of the air so closely pent up,
produced "`a multitude of worms, called _white maggots, and other vermin,_
which swarmed about,
even upon their beds and victuals,`" and manifestly tended
to the extreme danger of their health and lives.
Yet, through the Divine goodness, while in this melancholy situation,
and "`thus as it were buried alive,`" they were preserved in cheerfulness;
and "`their very natural voices strengthened, and raised up as trumpets,
mightily to sound forth God`'s glorious truth and power,
through the said hole in the wall;--and though four or five stories high,
and double grated as aforesaid,
so that their faces could not _win_ near to see into the street below,
yet were they distinctly heard all over the street
by the people,`" who the more frequently got together.
After _seven weeks`'_ continuance under the pressure
of these aggravated circumstances of cruelty,
the persecutors, not finding their end answered,
but rather that their endeavours to prevent the prisoners from preaching,
had increased the desire of the people to hear them,
at length allowed Patrick Livingston and George Gray to rejoin the rest of their friends,
who were in the prison below: Andrew Jaffray,
at the urgent complaint of some of his relations who were not Friends,
having been admitted to this state of comparative liberty somewhat sooner.

The last religious meeting of the Society in Aberdeen,
from which any of their number were conveyed to prison,
appears to have been held on the 4th of the 9th month, then called November, 1679,
when George Keith, Patrick Livingston, Thomas Mercer, Robert Gordon, Robert Winchester,
Robert Burnett, Robert Barclay, Ochiltrie Ferindaile, John Milne, John Mercer,
Andrew Jaffray, George Gray, William Alexander, Robert Sandilands, John Forbes,
Daniel Hamilton, and John Skene were apprehended and taken into custody; but,
in about three hours after, they were all set at liberty.
From which period,
their solemn assemblies were held without molestation from the magistrates;
on whose minds, the constancy and patience of the sufferers,
could scarcely fail of producing some favourable effect.
This, however, is but conjecture.
The most satisfactory mode of accounting for the cessation
of these unchristian proceedings against this body,
would appear to be, the persevering efforts of one of their number, Robert Barclay,
who possessed great interest with the Duke of York, afterward James the 2nd. For,
in an Address to the King, soon after his accession to the throne,
drawn up and presented by this Friend on behalf of the Society in Scotland,--__he
attributes the opening of their prison doors in the year 1679,
to the influence of King James (when Duke of York) with the government of that country.__

It was a settled observation among this people, as they strongly testify,
that during their deepest sufferings at Aberdeen,
they not only found the favour of God attending,
but also his hand of Providence preserving them;
so that while their spirits were continued cheerful,
praising the Lord in the midst of the most grievous of their afflictions,
even their bodies were kept in health and strength, beyond human expectation,
under all that very unwholesome confinement.
And further, through the same overruling power,
even the malice of those who rose up against them,
was made subservient to the spreading of that doctrine,
which it had been the design of such to crush.
For, during this persecution, their appointed meetings in that city,
were not only held at the usual times, but greatly increased in the number of attendants.
The _women,_ whose husbands were so frequently shut up in prison, failed not,
_with their children,_ to draw together for the worship of the Almighty,
at the stated seasons and in the accustomed places;
so that the unflinching constancy of these,
with the accession of other persons out of the country,
and the returning of the prisoners as soon and as often as they were released,
disappointed thus far the intentions of the magistrates,
_who were unable to prevent the holding of any one
of the public assemblies of the people called Quakers,
during the whole course of the persecution._

While this conscientious class of protesting Christians,
felt themselves in duty bound passively to submit to what might
be permitted to come upon them at the will of ungodly men;
and while they richly partook of that all-sufficient help,
which never fails the faithful and upright-hearted;
they yet looked forward with quiet expectation, with firm and full assurance,
to the time, when they should be ridden out of the hand of the wicked;
when their Lord and Master,
who will not allow any to be tried beyond what he knows is best,
should be pleased to cut short their trials, and in effect to say, "`It is enough.`"
There was no people, who had better claim to those words of the Psalmist, Psal.
xxxi.
"`My times are in thy hand:`"--for their _all_ was surrendered up unto his sovereign disposal.
There was no people, whom that language more fitly became,
which was first uttered by King David, in the same Psalm, and afterward by David`'s Lord,
"`Into thine hands I commit +++[+++or commend]
my spirit.`"
In the lips of such, the succeeding prayer, ver. 15, was altogether appropriate, and,
we may believe, accepted, "`Deliver me from the hand of mine enemies,
and from them that persecute me.`"
They had cause to trust, that "`the cry of the humble`" would not be forgotten; but that,
in due season,
"`for the oppression of the poor,`" the Lord would most assuredly "`arise.`"
They had read, that He "`preserveth the faithful,
and plentifully rewardeth the proud doer,`" that he "`judgeth
the righteous,`" and "`is angry with the wicked everyday.`"
"`If he turn not,`" continues the same inspired writer, "`He will whet his sword;
he hath bent his bow, and made it ready.
He hath also prepared for him the instruments of death;
He ordaineth his arrows against the persecutors.`"
Entertaining these Scriptural views,
it was rather with mingled feelings of awful admiration than of mere surprise,
that they beheld "`the reward of the wicked.`"
They could not but notice the remarkable concurrence of several unusual events,
which overtook the principal instruments of their wrongs,
whereby the cause of the persecutors was weakened; and, in these things,
they saw and acknowledged so many tokens of Divine displeasure,
manifested against the workers of iniquity; according to that declaration,
"`God is known by the judgment which he executeth;`" and again,
"`God shall wound the head of his enemies,
and the hairy scalp of such an one as goeth on still in his trespasses.`"

But to whom do these remarks apply?
Most certainly, in a primary and prominent sense, though not by any means exclusively,
to _him_ whose character the voice of history has indelibly stamped,
as "`the most unprincipled man of his day,`"--the Archbishop Sharpe,--to him,
who added _this_ to the black catalogue of those things, which, it cannot be doubted,
were registered against him by the just Judge of all the earth,--that
he fought against God and those who meekly feared him,
against those who loved their very enemies, and purely sought the good of all.
+++[+++see <<note-Z,Appendix, Z.>>]
The Friends of Aberdeen testify of him,
that he "`was the very chief and principal instrument of all our sufferings,
by his power in the Council:`" and the same document states,
that he was one of those who procured _that Commission_ to be appointed,
by whom the Friends were so unjustly censured;
and that he himself spoke very pressingly to some of the members of it,
_to endeavour to root out the Quakers._
Indeed, it was signified to some of the Friends, as they say,
"`by those who well knew it,
_that it was only he_ who stopped any favourable answer
from being given by the Council to our bills;
and that if he would _lie by,_ they would undoubtedly be well answered.`"
It will not be forgotten, that to him were addressed, upwards of two years before,
those faithful, weighty words of warning, contained in a letter of Robert Barclay,
before recorded, but worthy of being here repeated.--"`So, the God of truth,
whom we serve with our spirits in the gospel of his Son, and to whom vengeance belongs,
(so we leave it,) would certainly, in his own time and way, avenge our quarrel,
+++[+++in case thou should prove inexorable towards us;]
whose dreadful judgments should be more terrible unto thee,
and much more justly to be feared,
than _the violent assaults or secret assassinations_ of thy _other antagonists._
That thou mayst prevent _both the one and the other,_
by a Christian moderation suitable to the office thou layest claim to,
is the desire of thy soul`'s well-wisher, R. Barclay.`"

"`How remarkable,`" exclaim the sufferers, in their notice of the fact,
which soon after transpired, "`was the just judgment as from the Lord,
though the hand of man was cruel and barbarous therein,--one
cruel spirit punishing another,--in what befell`" the Archbishop;
"`although,`" continued they "`we neither wished him evil,
nor approved but abhorred`" the act and the spirit of it.--It is presumed,
that the reader will scarcely need to be informed, that, in the 3rd month, 1679,
the Archbishop Sharpe was waylaid by some of the Presbyterians,
as he passed in his coach and six, and inhumanly assassinated,
his murderers calling him _an apostate, a betrayer, and a persecutor._

The three public preachers of Aberdeen, Meldrum, Menzies, and Mitchell,
who had so furiously and maliciously set themselves against Friends,
as well as the spiritual testimony upheld by these,
were about the same time removed from their office, one by death,
the others by law,--being deprived of their power, and silenced from preaching.
With regard to Meldrum, who had been the most active in this work of persecution,
even beyond any of his class in Scotland, and had threatened that he would,
if practicable,
absolutely put a stop to the meetings of the "`Quakers`"
in Aberdeen;--it was singular enough,
that this man should not only have had his own mouth actually stopped by man,
but that impediment so effectually continued upon him,--as the sufferers
relate,--even after the King had given such ample toleration to all Nonconformists,
and notwithstanding his own desires,
and the endeavours of that city that he might be reinstated in his charge.--Surely,
in such an instance, "`The lying lips`" were "`put to silence,
which speak grievous things proudly and contemptuously against the righteous.`" Ps. 31:18.

A further evidence of the Lord`'s tender care over his little ones in this district,
appeared in the case of the Laird of Haddo; who, being made Chancellor,
and "`lending an ear to the wicked lies that were
fabricated to the prejudice of the Society,
set himself against that _stumbling-stone and rock of offence laid in Zion,_
the lowly appearance of Jesus Christ in the heart.`"
Being violent in the King`'s Council, on one occasion,
together with the Bishop of Aberdeen,
_to have the meetinghouse that Friends had built at Kinmuck pulled down,
and their school destroyed;_
he found the more moderate of his colleagues were averse to the measure.
For they said, It was against law to pull down a dwelling fire-house, as it was termed;
and if one Quaker meetinghouse was pulled down,
it behooved them to pull down every Quaker dwelling-house also;
_for as long as they had one, they would meet in it._
Upon this; it is credibly stated, on certain information, that he said,
_He would not trouble more, but do it with his own authority._
"`After this,`" proceeds the manuscript, "`within a very short time, our God, who says,
_They that dishonour me shall be lightly esteemed,_ stirred up a faction against him,
who got him, not without disgrace, to be displaced from his office,
having been in it scarcely two years.`"

Surely, after such repeated cases of a similar description and tendency,
these poor people had some sufficient ground administered,
for taking up that beautiful song of David, Psal.
cxxiv.--"`If it had not been the Lord who was on our side,
now may Israel say;--if it had not been the Lord who was on our side,
when men rose up against us; then they had swallowed us up quick,
when their wrath was kindled against us:
then the waters had overwhelmed us,--the stream had gone over our soul:
then the proud waters had gone over our soul.
Blessed be the Lord, who hath not given us a prey to their teeth!
Our soul is escaped as a bird out of the snare of the fowlers: the snare is broken,
and we are escaped.
Our help is in the name of the Lord, who made heaven and earth!`"
