== Chapter XIV.

[.chapter-synopsis]
* 1681: The harmony of Friends in some danger
* Visit of John Burnyeat
* 1686: David Barclay`'s death
* 1689: Account of George Gray
* His letter to his friends

In the course of the preceding pages,
a connected historical detail has been brought together,
principally exhibiting the conduct of this portion of the flock of Christ,
under that system of opposition and oppression,
with which they were for many years assailed.
Other biographical particulars of the Friends in Scotland,
in a somewhat more detached shape, are now to follow:
they chiefly embrace the little which has been preserved,
relative to the pious career and closing hours of several of these,
who were counted worthy to bear the burden and heat of that day.

No sooner had persecution of this description in great measure ceased,
than we find the enemy of all good devised a snare for their hurt,
more likely to prove successful against them than any open hostility.
By infusing into certain individuals of this little band,
who had hitherto been of one heart and of one mind,
evil surmisings and malicious jealousies against the body of Friends,
but especially against those who occupied conspicuous stations
among them;--in this way did he seek to break in upon and
lay waste "`the unity of the Spirit in the bond of peace.`"
Happily, and, as they testify,
through the remarkable care as well as tender regard of the great Shepherd,
who sleepeth not by day, nor slumbereth by night,
this undermining evil was timely discovered and exposed; those few who joined with it,
and were the chief occasion of this division,
being formally excluded from fellowship among them.
Alexander Harper and Isabella Keillo,--names that appear
in the early part of the Memoirs,--were of this number.
It appears,
that one ground of their dissatisfaction and calumnious reproaches against the Friends,
is to be traced to their reception of the baneful principles of Rogers and Bugg,
two noted apostates from the faith and practice of the Society in England.--It is recorded,
that very shortly previous to this affair breaking out, George Rook,
a Friend from Cumberland, wholly uninformed as to their situation, visited Aberdeen,
and had to declare in the meeting, that his mind was under suffering,
while sitting among them, "`From an undermining, murmuring, wicked spirit,
that was working against the faithful, and the unity of the body,
which God would in due time discover and judge out from among his people.

In the year 1681, John Burnyeat, together with Peter Fearon,
paid their Scottish fellow-professors a visit, in the line of gospel love and honour.
The former Friend, it may be remembered,
had discharged among them this important office of a Christian minister,
almost as early as there were any in Scotland,
stigmatized by their neighbours under the scornful appellation of "`Quaker.`"
Three years only elapsed,
ere we find this individual engaged a third time in the same weighty duty.
For, by a letter of his, dated Leith, the 6th of the 8th month, 1684, it is clear,
that he had taken journey _north_ from that place, with two others,
and had spent about three weeks in holding meetings almost every day;
"`having`" as he describes it,
"`a blessed open service through the Lord`'s power amongst Friends; for there is an open,
tenderhearted people, and they were glad of my coming;
for there had not been an English Friend among them of a long time.`"
It appears, he was particularly concerned, that decent order and care,
becoming a Christian church, should prevail and be maintained in all its branches.

It will not be forgotten, that among those champions,
who fearlessly withstood the encroachments of intolerance, was David Barclay of Ury;
respecting whom, indeed, it is to be regretted,
considering his station in life and the noble character he bore with all classes,
that so few and inadequate notices have been preserved.
After his son had been the means of procuring his liberation from prison,
where the last mention of him is made, he was not much molested;
his influence with those in power, or rather their respect for him,
very much serving to ward off the malice of inferior magistrates.
On one occasion, in his declining years, we find, he accompanied his old acquaintance,
John Swintoune, to London,
chiefly with the view of "`visiting his friends:`" and sometimes
we trace him at Edinburgh on the like account.
Again, in the spring of 1683, he was in London, his friend Andrew Jaffray being with him;
also his son Robert and wife with their eldest boy,
whom they were conveying to George Keith`'s boarding-school at Theobald`'s in Hertfordshire.
But, for the most part, David Barclay,
passed the remainder of his days on his own estate of Ury; enjoying, as it is stated,
with much satisfaction, the tranquillity of a country life,
after many years of hardship and of trial; possessing also, in a high degree,
the esteem of all who knew him;--but, above all, that inestimable treasure,
"`the peace of God,
which passeth all understanding,`" and which is alone
able to keep the soul "`through Jesus Christ.`"

A few fleeting years thus spent in preparing to meet his Judge and Saviour,
brought him to the 76th year of his age; soon after this, he took a fever, which,
in about a fortnight, was the means of removing him from this earthly scene.
Upon the 12th of the month called October, 1686,
his body was borne to a new burial-place, selected as such by himself,
situated on a rising eminence near a mile to the north-west of his house; he having,
when in perfect health, and some time before his death,
ordered the manner of his interment by a writing under his hand.
But notwithstanding his particular request,
that none might be expressly invited on that occasion,
except those of the Society and his own tenants; yet, the hour being known,
a numerous train attended, especially of the higher rank, who,
from the regard they bore to him while living,
came to pay this last office of respect to his memory.
The account of his religious departure, drawn up by his son,
can scarcely be read without effect,--it is so touching, so weighty, yet so simple;
discovering that dignified composure and humble trust,
which drew from survivors the declaration of their belief,
that he was "`kept in the patience and faith of Jesus.`"

During the time of his last sickness, David Barclay was preserved in a quiet,
contented mind, freely resigned to the will of God;
and gave several living testimonies to the Truth, and to the love of God,
shed abroad in his heart by the Holy Ghost.
Although there was hardly to be found one in a thousand
like him for natural vigour at his age,
and although his fever was at times very strong;
yet he never was "`insensible`" nor did any wrong expression or action proceed from him,
nor yet the least symptom of discontent or fretfulness.
He had previously been troubled with a very painful disorder,
and after the commencement of his illness, had much suffering from that cause; and,
about two days before his death, while those around were helping him up,
in a sense of his weakness and in an agony, he said,
"`I am going now`"--then instantly checking himself, he added,
"`But I shall go to the Lord, and be gathered to many of my brethren,
who are gone before me,--and to my dear son.`"--This was his youngest son, David,
who died at sea about a year before, on his voyage to East Jersey.
He was an amiable youth, of exemplary life and conversation,
and was an acceptable preacher among friends.

On the 11th of the 8th month,
(continues Robert Barclay,) about two or three o`'clock in the morning,
he growing weaker, I drew nigh to him.
He said, "`Is this my son?`"
I said, Yea; and spake a few words, signifying my travail,
that He who loved him might be near him to the end.
He answered, "`The Lord is nigh,`" repeating it,
"`You are my witnesses in the presence of God, that the Lord is nigh.`"
A little after, he said,
"`The perfect discovery of '`the Day-spring from on high`'--how
great a blessing it hath been to me and to my family!`"
My wife desiring to know, if he would have something to wet his mouth, he said,
It needed not.
She said, It would refresh him: he laid his hand upon his breast, saying,
He had _that inwardly_ which refreshed him.
After a little while he added at several times these words, _"`The Truth is over all!`"_

He took my eldest son to him, and blessed him, saying, He prayed God,
he might never depart from the Truth.
My eldest daughter Patience coming near, he said, "`Is this Patience?
Let _patience_ have its perfect work in thee!
And after kissing the others, he laid his hands upon them, and blessed them.
He called for my father-in-law, and two of his daughters that were present,
and spake some weighty words very kindly.
And perceiving one of them, who was not a Friend, weeping much, he desired for her,
that she might come to the Truth; and bade her not weep for him, but for herself.

A sober man, an apothecary, that waited upon him in his weakness, coming near,
he took him by the hand, saying, "`Thou wilt bear me witness, that in all this exercise,
I have not been curious to tamper nor to pamper the flesh.`"
He answered, "`Sir, I can bear witness,
that you have always minded the better and more substantial part;
and rejoice to see the blessed end the Lord is bringing you to.`"
He replied, "`Bear a faithful and true witness:--yet, it is _the life of righteousness,_
it is the life of righteousness, that we bear testimony to,
and not to an empty profession.`"
Then he called "`several times, _"`Come Lord Jesus, come, come!`"_
And again, "`My hope is in the Lord.`"--Now and then he slept,
perhaps during the space of ten hours.
On observing a countryman come into the room, he thought it had been one of his tenants,
_a carpenter;_ I telling him, it was not _he,_ but another, he said to me,
"`See thou charge him, to make no manner of superfluity upon my coffin.`"

About three in the afternoon, there came several Friends from Aberdeen to see him.
He took them by the hand, and said several times, They were come in a seasonable time.
After some words were spoken, and Patrick Livingston had prayed, which ended in praises,
he held up his hands, and said, _"`Amen!
Amen, forever!`"_
And afterward, when they stood looking at him, he said,
"`How precious is _the love of God_ among his children, and _their_ love one to another.
Thereby shall all men know that ye are Christ`'s disciples, if you love one another.
How precious a thing it is, to see brethren dwell together in love!
My love is with you--I leave it among you.`"

About eight at night, several Friends standing around the bed, he,
perceiving some of them weep, said,
"`Dear Friends! all mind the _inward man_--heed not the _outward:_--there
is One that doth regard--the Lord of hosts is his name!`"
After he heard the clock strike three in the morning, he said, "`Now the time comes!`"
A little after, he was heard to say, "`Praises, praises,
praises to the Lord!--Let now thy servant depart in peace.--Unto thy hands, O Father!
I commit my soul, spirit, and body.--Thy will, O Lord! be done in earth,
as it is in heaven.`"--These sentences he spoke by short intervals, one after another;
and at a little after five in the morning, the 12th day of the 8th month,
_fell asleep like a lamb, in remarkable quietness and calmness._

[.small-break]
'''

Many were the pious lessons conveyed by the dying, which an all-wise Providence saw meet,
in the course of a few years, to lay before the view of a rising generation in Scotland,
the successors of these faithful witnesses of _Emmanuel, God with us:_
Three years only elapsed, and they had to resign another of their number, George Gray;
who, on the 8th of the 12th month, 1689-90,
was called away to give account of his stewardship.

He is represented by his friends, to have been a worthy, precious,
and useful honorer in the Lord`'s vineyard thereaway,
the savour and power as well as fruits of whose comfortable ministry,
remained in the hearts of many.
"`His memorial,`" say they, "`is sweet and flourishing,
and shall live in generations to come, as a faithful servant of the Lord,
and steward of his manifold gifts and graces in the church.`"
By trade he was a weaver, and worked very hard with his hands,
up to nearly the close of his life,
in all intervals of disengagement from his _higher calling;_
not only that he might in nowise make the gospel chargeable,
but in order to set a good example of honest industry.
His care and zeal was great, in the first place,
to have his own conversation well ordered, and then,
that the least appearance of evil might be abstained
from throughout the whole circle of his friends;
that thus, all things truly lovely, comely, of good report,
and for the honour of the blessed cause, might be thoroughly followed,
by himself as a pattern to the flock, and by his fellow-professors.
The cheerful patience and steadfastness,
with which he underwent that portion of suffering that befell him for the Truth,
was very conspicuous,
especially during the long imprisonment which he and his Friends sustained at Aberdeen.

He was one much exercised and engaged on all public occasions, as at fairs and markets;
especially would he, when under close confinement,
often address the people from his prison-windows--indeed, it was _there,_
that he was first put forth in that service.
He not only endured much in his person,
counting it joy to suffer shame for the Lord Jesus, that _His power_ might rest upon him;
but was permitted to undergo the spoiling of "`a great part
of the mean outward substance`" which he possessed.
He loved to spend and be spent in the service of his good Master;
so great was his zeal in this respect, that it seemed _to consume his natural strength:_
thus, he swiftly ran out his blessed race,
laying down his earthly tabernacle as early as the 49th year of his age.
A little before his departure, being filled with the power of the Lord,
he gave weighty exhortation and counsel to all that were present,
especially to his children.
To some Friends who came to see him, he declared,
_He had not kept back the word and counsel of the Lord from them; and now he could say,
it was good doctrine to leave nothing to do till a dying bed._

A letter addressed by George Gray to the Friends of the country meeting at Colliehill,
at a time when he was very young in the Truth, and but entering into his public ministry,
may serve,
not only "`for some taste of his spirit;`" but as depicting
also in certain respects the state of that meeting,
for whose advancement in grace, and in saving knowledge, we may remember,
George Gray was especially interested.
It is dated from the Tolbooth of Aberdeen, the 8th of the 3rd month, 1676.

[.embedded-content-document.epistle]
--

[.salutation]
My dear Friends in the Truth!

The salutation of life and love be multiplied in and among you,
from the Father of love and life!

In the sense of the pure love of God, which flows in my heart towards you,
do I warn and exhort you, _to walk in the cross of our Lord Jesus Christ,_
which crucifieth us to the world and the world to us.
And watch in patience, and meekness,
and calmness of spirit against everything that would draw out the mind, in any measure,
from _the true meeting-place,_ either in or out of meeting.
For truly, my Friends, he or she that doth not watch diligently _out of meeting,_
but let their minds go a gadding to the ends of the earth,
and take no heed to have them gathered in _before_ they come to meeting--truly,
it is no wonder to see such disappointed.
And therefore, my dear Friends, be careful, every one in particular,
to have your minds stayed upon the Lord, and the Lord will not be wanting to you;
for great is his condescending to us in this day,
and wonderful is his work to those that truly watch and wait upon him!

Therefore, my dear Friends, every one know your place, and let not any go out,
nor look out beyond your measures; and let none speak, nor sing, nor sigh, nor groan,
but in a true sense of their conditions;
and let none make haste _to speak any thing before the Lord,_
which they know not to be from the true power; but all wait for the power and life,
and the love of God.
For, truly, where the love of God is not placed in the heart,
the true power will not attend their performances,
neither will God regard their speech or prayer.
Therefore, dear Friends, dwell in love, and walk in love towards all men and women;
and feel the love of God in your hearts flowing forth to all,
whether they love you or hate you.
For where hatred is brought forth against any person, upon whatsoever account it be,
although you may think the cause just, yet it will separate you from the love of God;
for envy and hatred are of the devil, and _he_ is there where _this_ is;
and Christ Jesus will not dwell with _him_ in unity.
And therefore, my dear brethren and sisters,
love one another with that love wherewith _Christ_ hath loved you,
and likewise your enemies; for love gathereth to God, but envy scattered.
Therefore, I warn you, in the fear and dread of the everlasting God,
that ye be not _hinderers of the work of the Lord;_ for dreadful will their portion be,
that let or hinder it in this day, or _bring an evil report upon it._
So, take warning, my Friends, and every one look to their way,
and to the prosperity of Truth.
And, my Friends, I thought the zeal of Truth should have had more effect upon _some,_
than I see it hath; but I shall forbear,
leaving every one to their own Master:--but they that _follow for loaves and fishes,_
when they get them not, will fail even in _that_ zeal also.

My little children, love one another.

[.signed-section-signature]
George Gray.

--
