== Chapter XV.

[.chapter-synopsis]
* 1690: Religious progress and latter end of Robert Barclay
* Letter of George Fox to his widow
* His character

But the loss which the Friends in this part of the country sustained,
by the removal of such men as George Gray and David Barclay, was not all;
it was quickly followed, and without doubt _exceeded_ by the death of _one,_
whom they and the Society at large were bound in a more than ordinary manner to esteem,
as "`worthy of double honour.`"
"`Surprising,`" says William Penn, "`was the death of dear Robert Barclay,
_to me particularly,_ from the share I claimed in him, and the esteem I had for him:
but that which gave weight to my sorrow,
was the loss which thereby comes to the church of God, and especially in Scotland.
That _he_ lived no longer,
who was so well fitted to live for the service and honour of the Truth,
and the good of God`'s people, must render his death more afflicting to all those,
who desire to be reckoned among this number.`"--__"`O Friends!`"__ continues the same writer,
_"`if precious in the eyes of the Lord be the death of his saints,
ought not their honours and death to be precious to the Lord`'s people?`"_

But before touching upon his close,
we must take a view,--such a superficial view as the existing documents
oblige us to take,--of those transactions which throw light upon
the religious progress of this "`prince in Israel,`" 2 Sam. 3:38,
during the last ten years of his pilgrimage.
Hitherto his course has been that of _the Christian advocate,_ strenuous and firm,
yet tender and discreet, in all his services for the cause in which he engaged;
meek and patient also, under those numerous provocations which were poured upon him.
But the days of public persecution being now over, as regards the Friends in Scotland,
and the principles they uniformly held becoming better understood by the public,
we do not find that fresh occasions presented for such laborious exercises as those,
in which Robert Barclay had been hitherto involved
for the defence and spreading of the gospel.
_The same voice,_ which had sounded an alarm in the ear of his soul,
which had girded him for this description of warfare and put him forth in it,
many a time giving him the victory through our Lord Jesus Christ,
doubtless conveyed to his submissive spirit a release from the field of controversy.
It was _this,_ which now led him in a line of duty, less conspicuous indeed,
and less accounted of by men,
but in its place and season no less acceptable in the sight of God.
Not that it was the easeful, inert, instinctive observance of such duty,
either in a private, social, or more enlarged scale,
that could satisfy the cravings of his enlivened soul;--for if so,
the character of Barclay has been strangely misrepresented.
We have, on the contrary, good cause to assume,
however few the traces of his latter years which have come down to us,
that this portion of his life was equally passed
under the blessed influence of that Sun of righteousness,
which had gilded his earlier path,--that the evidences of his peace
and adoption grew brighter and brighter till his final change.

We find him represented during this period,
as being warmly alive to the welfare of his fellow-men, his family and relations,
his friends and his acquaintance; but more especially so,
in what concerned the cause of his brethren in religious connection.
He employed himself in many acts of kindness and friendship towards each of these;
and was several times from home at Edinburgh or in London,
more often on behalf of others than on account of his own affairs;
but particularly applied his interest at court, which was considerable,
and the frequent access which he had to the person of King James the 2nd,
for the benefit of his friends and of others.
Being connected, or on terms of intimacy,
with some families of the highest rank in Scotland, he had great opportunity of evincing,
in his daily intercourse, the practical operation of those religious principles,
respecting which both vocally and with his pen he had so largely treated.
And there are sufficient proofs,
that he possessed the esteem and confidence of that class in no common degree.
On one occasion, it appears, he was made use of,
in composing a difference between the Duke of Gordon
and "`Sir Ewen Cameron,`" who had married his sister,
Jean Barclay; and undertook a journey to London chiefly with this view;
which object was at length accomplished, as it is said, by the King`'s interposition.
+++[+++see Appendix, A A.]

In the Memoirs of the family, it is also stated, that "`In 1682,
the Earls of Perth and Melfort, with the other proprietors,
elected him Governor of East Jersey, North America; and to induce him to accept thereof,
they gifted him a large propriety with five thousand
acres more for him to bestow as he should think fit,
the government being confirmed to him during life by King
Charles the 2nd`'s letter;--his commission bears,
that such is his known fidelity and capacity, that he has the government during life,
but that every Governor after him, shall have it three years only.
He had likewise the power of appointing a deputy governor,
with a salary of four hundred pounds per annum.`"--Whatever
worthy purposes he might have had,
in accepting this post, it is clear,
that patronage rather than riches would be the immediate result; and this,
with a very considerable weight of care and responsibility.
But it seems, that the settlement of his two younger brothers in that province,
became part of the design, although with regard to the youngest, David, this plan,
owing to his death while on the voyage, was not permitted to take effect.

The little incident, well known to readers among the Society of Friends,
of Robert Barclay`'s rencounter with highwaymen, on his way back to Scotland from London,
in 1683, will not _by them_ be expected to be passed over,
in these recollections of his life and conduct.
His grandson`'s own account, now before the Author, may at least be fresh to every one.

"`Having stayed most of the summer +++[+++in London]
visiting his friends, as he, with his wife and brother in law +++[+++Gilbert Molleson,]
and his intimate friend Aaron Sonemans, an eminent merchant in Holland,
were traveling homeward in company together,
they were upon the 8th of August attacked in Stonegatehole, in Huntingdonshire,
by highwaymen.
One of them presented a pistol to my grandfather; he took him by the arm very calmly,
asking him _how he came to be so rude_--for he knew his business.
The fellow, trembling, dropt the pistol out of his hand upon the ground,
in great surprise, and did not so much as demand any thing.
But his brother-in-law was riffled, and poor Sonemans was shot through the thigh,
+++[+++it was thought more by accident than design,]
who being with some difficulty brought to Stilton, died in a few days of the wound.
I had the above accounts from my grandmother,
who likewise told me that she observed my grandfather,
that morning before they were attacked, _more pensive than usual;_ and that he told her,
it was his opinion, some unusual trial or exercise was to befall them that day;
but when the affair happened, __he enjoyed a remarkable serenity.__`"

He was again in London in the year 1685, and also in 1687; the latter time,
very much in compliance with the pressing solicitations of Friends,
especially of George Fox; an extract from whose original letter,
in the possession of the writer of these pages, may best explain their wishes,
while it will serve as a standing testimonial of their love,
and of the sense which they had of Robert Barclay`'s
usefulness in serving the cause he had espoused.

[.embedded-content-document.letter]
--

[.salutation]
Dear Friend, R. B.,

Now the occasion of my writing unto thee at this time is,--that Friends are very sensible
of the great service thou hadst concerning the Truth with the King and at the court,
and that thou hadst their ears more than any Friend, when here,
and freedom and liberty on Friends`' and Truth`'s behalf.
And now, dear Robert, we understanding,
that the occasion of thy sudden return +++[+++homeward was now passed,]
I do desire thee, and it is the desire of several other Friends, that now,
while the door is open and the way so plain,
thou wouldst be pleased to come to London with speed,
or as soon as may be,--for there is a great service in it, thou having such free access;
and when thou art here, Friends may let thee know their minds further.--And so,
dear Robert, there is a great service in thy coming, upon several accounts,
more than I shall speak of at this time;--and so I hope the Lord
will incline thy heart to weigh and consider thy service in it.
And so, once more, with my love,

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Edmonton, 19th of the 5th month, 1686.

--

The death of his worthy parent, David Barclay, before recited,
and that of a sister soon after, with the various concerns that would, in consequence,
devolve upon him as representative of the family,
sufficiently account for his apparent slackness in
acceding to so urgent a request as the foregoing.
When in the metropolis,
he drew up and presented to the King the sincere acknowledgments of the Friends in Scotland,
on account of his proclamation in favour of liberty of conscience;
and there is little doubt, he attended the Yearly Meeting of the Society,
held in London in the 3rd month, 1687.
But it is not clearly made out, what special benefit resulted to that body,
from any exertions of his at this juncture on their behalf.
Direct persecution had then, generally speaking, ceased;
yet the legal incapacity of this people, in consequence of their refusing to swear;
the ruinous processes usually instituted against them for tithes even of small amount;
together with the little security which they felt,
whilst the penal laws were only suspended, and that,
by a power which they knew to be incompetent;--such considerations would naturally,
induce them to wish, that the degree of ease which they now enjoyed,
might rest on a more satisfactory basis.
Indeed, it is evident by the address,
which went up to the King this year from the Society at large,
that they looked for _"`such a concurrence from the Parliament, as will,`"_ they say,
"`secure it to our posterity.`"
Whatever might have been the principles of James the 2nd,
(as the compiler of the Life of Robert Barclay justly observes,) the latter,
probably influenced by the personal kindness he received from the King,
seems to have thought him sincere in his professions; while it may be further suggested,
whether a fervent Christian desire and charitable hope respecting him,
might not have been the origin of that real regard,
which Barclay evidently cherished towards the misguided and imprudent monarch.

While in London, our Friend had an interview with the seven bishops,
then confined in the Tower.
It will be recollected, they had refused to distribute, in their respective dioceses,
the King`'s declaration of indulgence,
and had represented to the King the grounds of their objection to the measure.
The popular opinion was in favour of the bishops;
yet the former severities of some of that order against dissenters,
particularly against Friends, occasioned some reflections on them; which,
coming to the knowledge of the imprisoned bishops,
they declared _that the Quakers had belied them,
by reporting that they had been the death of some._
Robert Barclay being informed of this, went to the Tower;
and gave the bishops a well substantiated account of some,
who had been detained in prison till death, by order of bishops,
though they had been apprized of the impending danger by physicians who were not "`Quakers.`"
He, however, told them,
that since they themselves through change of circumstances were now under oppression,
it was by no means the intention of the Friends,
to give the King or their adversaries any advantage against them,
by publishing such incidents.

On his way home from London in the 6th month, Robert Barclay stopped two days at Chester,
where the King then was, upon a progress.
There, in the Tennis Court,
he and William Penn had "`a most large meeting,`" as he calls it in his Diary;
the King himself being present at one of the religious opportunities,
held in the Friends`' meetinghouse.
Passing through Lancashire, Robert Barclay visited Swarthmore,
formerly the house of Judge Fell, whose widow was married to George Fox.

Soon after the commencement of the next year, 1688, he took his last journey to London,
where he stayed the whole summer,
"`visiting and serving his friends to the utmost of his power.`"
His eldest son Robert,
who discovered a heart "`devoted to religion from his infancy,`" was with him,
being then but sixteen years of age.
The father, judicious and discriminating, as he is described to have been,
in his care over his children,
did not object to introduce him to the court of King James at Windsor;
where he remained some considerable time, being much caressed, it is said,
on account of his father`'s interest, which occasioned numerous dependents.

Though this fact is probably calculated, at first sight, to startle most minds;
such feeling may be measurably allayed considerations like the following.
It cannot with reason be said, _that in every supposable case,_
this line of conduct in a parent would be _altogether_ unwarrantable or inexpedient.
Yet, it is freely admitted,
the present instance should form _by no means_ a warrant
or precedent for any to venture upon,
unless under circumstances that may _equally_ bear the weight of the risk and responsibility.
It may safely be concluded,
that Robert Barclay had duly reflected on the subject;--that he
was _fully_ acquainted with the character and propensities of his
child,--that he had _thoroughly before his view_ the degree of exposure,
which, under his own firm and prudent control, was likely to be incurred.
And further we are assured, that he himself was _no novice,_
with regard either to the allurements of this present evil world,
the weakness of the creature, or the wiles of the destroyer.
On the other hand, few had more occasion to trust in Divine protection and grace,
wherever duty called or Providence might lead him.
It is an interesting appurtenance to the foregoing statement,
and gives some force to the remarks which follow it,--that when this youth grew up,
had run his course, and had done with time,
his friends could in their expressive way testify of him, that,
even _throughout this critical time_ to which we are precisely referring,
"`his conversation was clean and void of offence:`"--and
how is this accounted for?--they add,
in the same sentence,
that which is the best explanation--"`He may be truly said
to have __remembered his Creator in the days of his youth.__`"

Previous to quitting London, Robert Barclay had an interview with the King,
which shall be described in the words of his grandson.--"`At
this time he took his last leave of the King,
for whose apparent misfortunes he was much concerned; having,
as my grandmother informed me,
several times discoursed with him upon the posture of affairs at that juncture,
about settling the differences like to arise;
and _sometimes agreeable resolutions were taken,_
but _one way or other_ prevented from being executed.
At their parting, being in a window with the King, where none other was present,
who looking out said, _The wind was now fair for the Prince of Orange_ coming over;
upon which my grandfather took occasion to say,
_It was hard that no expedient could be found out to satisfy the people:_
to which the King replied, _That he would do any thing becoming a gentleman,
except to part with liberty of conscience, which he never would while he lived._

On his return home,
Robert Barclay spent the remaining two years of his life in much retirement,
chiefly at home, enjoying the esteem and regard of his neighbours,
the comforts of domestic society, and doubtless partaking also in good measure,
a soul-sustaining evidence of Divine approbation.
In the year 1690, he accompanied James Dickenson, a minister from Cumberland,
in a religious visit to some parts of the north of Scotland: coming to Ury,
from a meeting at Aberdeen, he immediately sickened, being seized with a violent fever,
which continued upon him about eight or nine days,
when it pleased the Lord to take him out of this world,
to a kingdom and glory that is eternal.

James Dickenson was with him at the time of his illness.
It was a solemn season: and as he sat by him,
the Lord`'s power and presence bowed their hearts together,
and Robert Barclay was sweetly melted in a sense of God`'s love.
Though much oppressed by the disorder, an entirely resigned, peaceful,
and Christian frame of mind shone through all.
With tears, he expressed the love he bore towards "`all faithful brethren in England,
who keep their integrity to the Truth,`" and added,
"`Remember my love to Friends in Cumberland, at Swarthmore,
and to _dear George_ +++[+++meaning George Fox,]
and to all the faithful everywhere;
concluding with these comfortable words--"`God is good still:
and though I am under a great weight of sickness and weakness as to my body,
yet _my peace flows._
And this I know,--that whatever exercises may be permitted to come upon me,
they shall tend to God`'s glory and my salvation:
and in that I rest.`"--He died on the 3rd of the 8th month, then called October, 1690,
in the 42nd year of his age;
the remains being attended to the grave in the family burial-place at Ury,
by many Friends and others of the neighbourhood.

Among the numerous letters of condolence addressed to the widow,
by different classes of their intimate acquaintance,
are two,-- the first from the Countess of Errol,
said to have been "`one of the most religious as well as accomplished ladies
of her time;`" and the other from Robert Barclay`'s very especial Friend,
George Fox, with whom he maintained a frequent correspondence.
The former may be allowed a place; in the Notes to this volume,
as an expressive proof of the estimation in which he was held by one of that rank;
+++[+++see Appendix, BB]; but the latter is too extraordinary an effusion of the _ancient,
evangelical_ spirit, to be withheld from a prominent place in these pages.
It proved the _last_ letter, except one, which that worthy ever wrote.

[.embedded-content-document.letter]
--

[.letter-heading]
George Fox to Christian Barclay.

[.signed-section-context-open]
28th of 10th month, 1690.

[.salutation]
Dear Friend!

With my love to thee and thy children, and all the rest of Friends in the holy Seed,
Christ Jesus, that reigns over all; in whom ye have all life, and salvation, and rest,
and peace with God!

Now, dear Friend, though the Lord hath taken thy dear husband from thee, his wife,
and his children, the Lord will be a Husband to thee, and a Father to thy children.
Therefore, cast thy care upon the Lord, and trust in Him: let Him be thy confidence,
and let thy eye be unto Him at all times; who is a great Ruler and Orderer of all,
both in heaven and earth, and hath the breath and souls of all in his eternal,
infinite hand!
And all the creation is upheld by his Word and power,
by which they were made;--so that a sparrow cannot fall to the ground
without his will and pleasure;--and his sons and servants in his image,
are in greater value in his eye than many sparrows.
Therefore, thou and thy family may _rejoice,_
that thou hadst _such an offering to offer up unto the Lord,_ as thy dear husband; who,
I know, is well in the Lord, in whom he died, and is at rest from his labours,
and his works follow him.

And, now, my dear Friend, do thy diligence in thy family,
in bringing up thy children in the fear of the Lord, and his new covenant of life;
that thou mayst present them to God _as his children,_ and all thy servants and tenants,
in the wisdom of God.
_Thou must answer the Truth in them all,_ in truth, holiness, righteousness, and justice,
and walking humbly before God.
_Thou wilt always feel his presence to assist,
and enable thee to perform whatsoever he requires of thee;_ so that whatever thou dost do,
it may be to the honour and glory of God.
And _do not look at the outward presence of thy husband;_ but look at the Lord,
and serve Him _with a joyful heart,_ mind, soul,
and spirit all the days thou livest upon the earth.

From him, who had a great love and respect for thy dear husband,
for his work and service in the Lord, who is content in the will of God,
and all things that he doeth:--__and so must thou be.__
And so, the Lord God Almighty,
settle and establish thee and thine upon the heavenly Rock and Foundation; that,
as thy children grow in years, they may grow in grace, and so in favour with the Lord.
Amen!

[.signed-section-signature]
George Fox.

[.postscript]
====

Postscript.--I know thy husband hath left a good savour behind him,
so I desire _thou mayst do the same._

====

--

The following faithful delineation of the character of "`this
worthy young man of God,`" as William Penn styles him,
may be fresh to many readers; but is worthy the _repeated_ attentive perusal of those,
who claim connection with the Society of Friends, especially among the younger classes.
To adopt the language and motives of the same writer, William Penn,
on the like occasion,--"`For _their_ example and encouragement,`" is this account given,
"`who have or hereafter may receive the eternal Truth,
as well as __for a testimony to the power and goodness
of God in raising him up to his church.__`"
It is prepared from documents,
put forth by those contemporaries of Robert Barclay who knew him well,
and appears in the pages of [.book-title]#A Short Account of His Life and Writings.#

[quote]
____
He was distinguished by strong mental powers, particularly by great penetration,
and a sound and accurate judgment.
His talents were much improved by a regular and classical education.
It does not, however, appear,
that his superior qualifications produced that elation of mind,
which is too often their attendant: he was meek, humble,
and ready to allow others the merit they possessed.
All his passions were under the most excellent government.
Two of his intimate friends, in their character of him, declare,
that they never knew him to be angry.
He had the happiness of early perceiving the infinite superiority of religion,
to every other attainment; and Divine grace enabled him to dedicate his life,
and all that he possessed, to promote the cause of piety and virtue.
For the welfare of his friends, he was sincerely and warmly concerned; and he travelled,
and wrote much, as well as suffered cheerfully,
in support of the society and the principles,
to which he had conscientiously attached himself.
But this was not a blind and bigoted attachment.
His zeal was tempered with charity; and he loved and respected goodness,
wherever he found it.
His uncorrected integrity and liberality of sentiment, his great abilities,
and the suavity of his disposition,
gave him much interest with persons of rank and influence;
and he employed it in a manner that marked the benevolence of his heart.
He loved peace; and was often instrumental to settling disputes,
and in producing reconciliation between contending parties.

In the support and pursuit of what he believed to be right,
he possessed great firmness of mind;
which was early evinced in the pious and dutiful sentiment he expressed to his uncle,
who tempted him with great offers to remain in France, against the desire of his father:
"`He is my father,`" said he, "`and must be obeyed.`"
All the virtues harmonize, and are connected with one another:
this firm and resolute spirit in the prosecution of duty,
was united with great sympathy and compassion towards persons in affliction and distress.
They were consoled by his tenderness, assisted by his advice, and as occasion required,
were relieved by his bounty.
His spiritual discernment and religious experience,
directed by that Divine influence which he valued above all things,
eminently qualified him to instruct the ignorant, to reprove the irreligious,
to strengthen the feeble-minded,
and to animate the advanced Christian to still greater degrees of virtue and holiness.

In private life, he was equally amiable.
His conversation was cheerful, guarded, and instructive.
He was a dutiful son, an affectionate and faithful husband, a tender and careful father,
a kind and considerate master.--Without exaggeration, it may be said,
that piety and virtue were recommended by his example; and that,
though the period of his life was short, he had, by the aid of Divine grace,
most wisely and happily improved it.
He lived long enough to manifest, in an eminent degree,
the temper and conduct of a Christian,
and the virtues and qualifications of a true minister of the gospel.
____
