== Concluding Observations

[.chapter-synopsis]
* On the state of the church at large, with reference to the successive stages of her reformation, and occasioned by a view of that share and interest, which the Society of Friends have ever taken therein

The Author of these Memoirs, having now finished the task he ventured to take in hand,
or rather that allotment of honour which seemed to devolve upon him,
apprehends there is yet a duty he owes,
not only to his subject but to the reader,--to take his leave of both,
with some general and concluding observations.

He does not hesitate to avow his belief,
that the religious Society of Friends were a people originally raised up,
in the line of the Apostles, martyrs, and confessors of Christ Jesus,
the blessed Mediator, "`whose goings forth have been from of old, from everlasting.`" Micah 5:2.
He rests assured,
they were designed to be faithful and living witnesses of the revival of that
"`time of reformation,`" Heb. 9:10. when the holy Head and High Priest,
having ascended up on high,
visibly separated and eminently sanctified to himself "`a glorious church,`" whose character
and constitution is best set forth in the disencumbered pages of Sacred Writ.
Doubtless, through the long night of apostasy,
which succeeded the first establishment of the Christian church, there has been,
at every period, a "`remnant of her seed, which keep the commandments of God,
and have the testimony of Jesus Christ.`" Rev. 12:17.
These,--however they may differ in some respects one from another,
according to that measure of light and knowledge which has been assigned them,
according to the particular share in this testimony,
with which they may have been entrusted,--while they
continue to occupy with the talent of grace received,
and to walk in the way of the cross,
as mercifully cast up before them,--are all under the special
notice and care of the great Shepherd of the sheep.

The church, then, coming up more and more from a wilderness state,
"`leaning on her Beloved,`" out of that oppressed and beclouded condition,
into which she has been driven; it is certain,
she will be more and more clothed with the glory of the Sun of righteousness,
and there will be more clear vision among her children.
The power of Antichrist will be more unveiled before them in all his delusions,--that is,
they will be given to know what has contributed to
eclipse the brightness of the gospel day,
and to detain her in weakness and in bondage: also, "`they shall see eye to eye,
when the Lord shall bring again Zion.`" Isa. 52:8.
But, in the mean while, it behooves every of her sons and daughters,
who are from time to time made sensible of any degree of _captivity,
to shake themselves as from the dust, and to loose the bands of their neck,_
Isa. 52:2; in other words,
no longer to be resting satisfied with any thing
short of that perfect reformation and redemption,
which the Deliverer is opening before them.

It was to be expected,
in the progress of this glorious work,--a work to be begun and
to be carried on in the hearts of individuals,--that there should
be different classes of students in the school of Christ;
and that as each of the "`members of his body, of his flesh,
and of his bones,`" were attracted to acknowledge one another in the covenant of life,
according to the vision of the Prophet, they should come _"`bone to his bone.`"_
How precious is the consideration,--that as the various
professors of the saving faith of Jesus,
more largely and more purely drink into his Spirit,
they will be _by this one Spirit baptized into one body;_ and will feel themselves to be,
far more truly than can at present be said to be the case,--__bone of His bone,__
who is espoused to be their Husband,--and "`every one members one of another!`"
Thus, there is cause to believe, that,
"`in the dispensation of the fulness of times,`" will be gathered "`together in one,
all things in Christ, both which are in heaven, and which are on earth, even in Him.`" Eph. 1:10.

The situation and prospects, in every age, of the true disciples of our Lord and Saviour,
must prove to the Christian mind a subject of vast importance;
and it deeply concerns every one of us to know for ourselves, how far we are promoting,
by individual reception of the leaven of his gospel,
that universal diffusion of unmixed "`glory,`" which, we are assured,
"`shall cover the earth, as the waters cover the sea.`" Hab. 2:14.
The government and dominion of`" the Prince of Life,`" "`the Prince
of Peace,`" which is ultimately to subdue and reduce all things unto itself,
Dan. 2:44, the Society of Friends have preeminently held,
to be wholly of a spiritual character: it is to be set up within man,
and "`cometh not by observation,`" neither stands in any mere outward observances,
but in "`righteousness, peace, and joy in the Holy Ghost.`"
They have all along considered the standing, lasting,
and indispensable ordinance of the gospel to be,
_the manifestation of the Saviour by his Spirit, as the Guide into ALL truth;_
according to the whole tenour of the 14th chapter of John,
and likewise that language of the Apostle to the Hebrews:--"`Christ
was once offered to bear the sins of many;
and __unto them that look for him, shall he appear the second time, without sin,
unto salvation.__`" Chap. ix. ver. 28. +++[+++see Appendix, GG.]
This Society has therefore deemed it essential _to know the reality
of the presence of Christ dwelling in their hearts by faith;_
and has judged it in the highest degree needful,
_to love and wait for his appearing and counsel,_ to bow the neck to his yoke,
and _to commit themselves in all things most unreservedly to his leadings._
In this way they believe it was,
that our blessed Redeemer engaged _to manifest himself_ unto those,
and make his abode with them, who should keep his commandments; and thus also it is,
that such who do his will are given to know of his doctrine.
For, of the Spirit of Truth,
which "`teacheth`" the believers "`all things,`" our Lord himself declared,--"`HE
shall _testify_ of ME`"--"`HE shall _glorify_ ME.`" John 15:26, and 16:14.
_This_ remains to be a chief test or proof of discipleship; insomuch, that,
_if we have not the Spirit of Christ, we are none of his,_ Rom. 8:9.
This also is the only channel,
whereby we may savingly believe or confess him;
for--"`Whosoever believeth that Jesus is the Christ,
is born of God,`" and _"`hath the Witness in himself;`"_ and again, seeing,
"`no man can say that Jesus is the Lord,
__but by the Holy Ghost,__`" "`Whosoever shall confess that Jesus is the Son of God,
__God dwelleth in him and he in God.__`"
1 John 5:1, and 10; 1 Cor. 12:3; 1 John 4:15, +++[+++see Appendix, HH.]

It may be freely and with thankfulness admitted,
that such a scriptural acknowledgment as the foregoing,
does not by any means exclusively belong to those of one particular class or persuasion;
but has ever been, though with various degrees of clearness,
substantially and virtually the experience of a cloud of witnesses,
through every age of the church.
And while there seems room to hope,
that these practical yet momentous views of doctrinal truth,
have been of late more distinctly avowed and more
duly appreciated by the generality of religious professors;
still, even among the worthiest of these, abundant occasion remains,
to sigh for a further clearing of the _ancient, primitive ground;_
that so the doctrine of the Spirit might be, in many respects, more consistently upheld,
more particularly applied,
more fully followed out into its legitimate and genuine bearings.
Can there be a doubt,
that the more closely the churches of Christ have been ingrafted into Him,
the Vine of Life,
the more they have participated in all those blessed privileges provided for them?
and have they not uniformly found the less need, as well as the less liberty,
for the intervention and use of human props, human shackles, human rudiments?
Nor is it derogatory to the scope and character of the Sacred Page,
or the merciful designs of its Divine Author, to believe,--that,
were the various Christian denominations more thoroughly disentangled from these things,
were they to "`cease from man`" and "`the commandments of men,`"
implicitly and disinterestedly _following on_ to know the Lord,--following
"`the Lamb _whithersoever_ he goeth;`"--they would come to witness,
in a marvellous manner,
"`his going forth`" to be "`prepared as the morning,`" and his coming in among them,
even "`as the rain, as the latter and former rain unto the earth.`"
Their glorious Lawgiver, and Judge, and King would also be in the midst of Zion,
the city of their solemnities,--the "`quiet habitation,`"--as "`a place
of broad rivers and streams,`" wherein should go "`no galley with oars,
neither gallant ship pass thereby.`" Isa. 33:20-21.

With regard to the Society of Friends,
whose history in a corner of the land has been now portrayed,
they have been cordially willing, to own in their place,
_all such as these,_--that love the Lord Jesus Christ in sincerity,
and are following him in the regeneration.--"`We have ever had,`" says Alexander Skene,
one of the subjects of these Memoirs, "`__a reverent esteem__ of all faithful ministers,
who in simplicity and sincerity of heart have endeavoured to preach the gospel;
though in many things short of those blessed discoveries which God hath manifested _to us._
And we do remember those that were such with due respect,
_as having been faithful according to measure in their day,
and blessed instruments in God`'s hand to the good of many._
But, it is not the duty of any Christian to stand still,
and shut out all further discovery than that to which they attained.
For, as all the degrees of the apostasy came not at once,
nor with the first or second trumpet, Rev.
viii.; so, neither is the reformation to be completed by the first or second vial, Rev.
xvi.`" Again, George Keith, another of the Friends in Scotland,
at a time when he was much respected among his brethren,
had this record to bear concerning some who preceded them.--"`There
have been holy and spiritual men in the _Presbyterian Church,_
that have in a blessed measure known communion with God in spirit,
and were _faithful_ in the talents given them of God:
I believe their souls are entered into everlasting rest,
and their memory is _as a box of precious ointment,_
among others of the Lord`'s witnesses in +++[+++different]
professions and places of the world.`"

So that, whatever disposition may _appear_ to have existed,
on the part of the first preachers among the people termed "`Quakers,`"
towards the various denominations then prevalent around them;
it is certain, their controversy was not with the tender,
teachable disciples of a crucified Saviour,
but rather with the "`man of sin,`" the deceiver, and antichrist,
in his various transformations among men.
He had obtained a strong hold in many hearts, by persuading them,
that they were secure from delusion,
because they possessed the specious charm of a high
profession--even an appropriation of the experiences,
with an imitation of the performances, of the saints.
In this state, had he too successfully endeavoured to settle the minds of people,
not a few of whom had once truly "`tasted that the Lord is gracious,`"--who
had "`begun`" well "`in the Spirit,`" and in the "`newness of life.`"

It was this view, which led William Penn,
among a multitude of other writers and preachers,
to give forth such a paragraph as the following, which appears in his piece,
entitled _The Christian Quaker:_ "`He is as well taught to deny the religions,
as cares and pleasures of the world:
Such as profess religion from what they have either been taught by others,
or read and gathered after their carnal minds out of the Scriptures,
intruding into the practices of either prophets or apostles,
as to external and shadowy things, not being led by the same power _they_ had,
he can have no fellowship with:--he counts all _such_
faith and worship the imagination of men,
or a mere lifeless imitation.
He prefers one sigh, begotten from a sense of God`'s work in the heart,
beyond the longest prayers in _that_ state.
_He leaves them all, walks as a man alone,
fearing to offer God a sacrifice that is not of his own preparing._
He charges all other faiths and worships, with insufficiency, and mere creaturely power,
which are not held and performed from a holy conviction
and preparation by the Angel of God,
the Light of his presence in the heart and conscience.
_Therefore,_ it is,
that he goes forth in the strength of his God against the merchants of Babylon;
and woes and plagues are rightly in his mouth against
those buyers and sellers of the souls of men.
He is jealous for the name of the Lord, and therefore dares not speak peace unto them,
neither can he put into their mouths, but testifies against all such ways.
__Freely he received, freely he gives.__`"--[.book-title]#Penn`'s Works,# fol.
vol. i. p. 587.

It is important, that the views of this Society, at its earliest period,
with regard to what may be styled, _the day of reformation and the true sons of reform,_
should clearly be understood; and therefore three additional extracts,
somewhat simplified in the form of expression, shall be subjoined,
from distinguished authorities among them.
In the first of [.book-title]#Robert Barclay`'s Works,# published in the year 1670,
when he was but 22 years of age,
this explicit statement appears.--"`God does not frequently
discover his will to his children _all at once,_
nor _in an instant_ lead them thoroughly out of things +++[+++from]
which they are to come; and yet, that he countenances them _in their travel,_
cannot be denied.
Did not the Lord countenance Cornelius, before Peter came unto him? Acts 10:4.
And yet this was no argument,
that Cornelius should _not_ own the apostles and Christians.
And did not the Lord countenance the disciples, when they were following him,
though even +++[+++then]
they were ignorant of many things, and in some things +++[+++were]
wrong?
And did not the Lord countenance Luther, in his testimony against the Pope,
as well in the first as in the last steps of it; although it appears,
that when he first began to preach against indulgences,
he did not intend such a thing as afterward followed.
But things opened more and more before him, till they came to that period,
to which they were brought before his death.
And who will say, that God did not countenance him _from the beginning,_
whilst he held many things, which +++[+++afterward]
he himself came to see were wrong?
The like may be said of John Huss, and others.`" [.book-title]#R.B.`'s Works,# fol. p. 5.
Again, in his [.book-title]#Apology,# he has this language:--"`The great apostasy
came not upon the Christian world all at once,
but by several degrees, one thing making way for another;
until that thick and gross veil came to be overspread,
wherewith the nations were so blindly covered,
from the 7th or 8th until the 16th century.
Even as the darkness of the night comes not upon the outward creation all at once,
but by degrees, according as the sun declines in each horizon.
So, neither did that full and clear light and knowledge
of the glorious dispensation of the gospel of Christ,
appear all at once;
the work of the first witnesses being more to testify
against and discover _the abuses of the apostasy,_
than _to establish the Truth_ in purity.
He that comes to build a new city, must first remove the old rubbish,
before he can see to lay a new foundation;
and he that comes to a house greatly polluted and full of dirt,
will first sweep away and remove the filth,
before he put up his own good and new furniture.
The dawning of the day dispels the darkness,
and makes us see the things that are most conspicuous;
but the distinct discovering and discerning of things,
so as to make a certain and perfect observation, is reserved for the arising of the sun,
and its shining in full brightness.
And we can from a certain experience boldly affirm, that _the not waiting for this,_
but _building among, yea, and with, the old Popish rubbish,
and setting up_ before a full _purgation,_
hath been to most Protestants the foundation of many a mistake,
and an occasion of unspeakable hurt.`"
Prop. 5 and 6, sect. 10.

But Penington enters yet more into particulars in the succeeding passages,
taken from "`An Answer to the Objection,
That the Quakers Condemn All but Themselves:`" first
printed in the year 1660.--"`The Protestant churches,
the blessed martyrs, who suffered for the testimony of a pure conscience towards God,
and all the worthies of the Lord in their several generations,
who fought against '`the scarlet whore,`' were accepted
of God in their testimony against her,
and are not disowned by us, but _dearly owned and honoured therein._
But all things were not discovered at once.
The times, were then dark, and the light small;
yet they being faithful according to what was discovered,
were precious in the Lord`'s eyes; and what through ignorance they erred in,
the Lord winked at and overlooked,
being pleased with that sincerity and simplicity of heart,
which he had stirred up in them towards himself.
But if they were now alive in _these_ our days,
and should depart from the sincerity which was _then_ in them,
and oppose the light of this age, they would not then be accepted of the Lord;
but their former sincerity would be forgotten.
_For the light shineth more and more towards the perfect day:_
and it is not the owning of the light as it shone in the _foregoing_ ages,
which will _now_ commend any man to God; but the knowing and +++[+++being]
subject to the light of the _present_ age.
Even as, in these our days, there was, some years ago,
an honest and true simplicity stirring in the Puritans,
especially among the Nonconformists, _which was of the Lord, and was very dear to him._
And had the generations of this age abode there,
they would have been able to have followed the Lord
in every _further_ step and leading of his Spirit.
But departing from that, into some form or other, the true simplicity withered,
and another thing began to live in them; and so they settled upon their lees,
magnifying the form they had chose to themselves,
till at length their hearts became hardened from the pure fear,
even to the contracting of a spirit of profaneness; insomuch,
that they could mock at the _next remove_ and discovery of the Spirit, as some _new light;_
and so, by degrees have grown persecutors of _that_ Spirit
in its outgoings in the people of the Lord,
which they themselves had once some taste of,
while they were reproached for being Puritans.
And the god of this world, who at first tempted them aside into the form,
hath at length prevailed so far to blind them therewith,
that they can neither see what spirit they themselves are of,
nor what spirit it is they persecute.

If there be any among the Episcopal sort, that in truth of heart desire to fear the Lord,
and look upon the Common Prayer Book as an acceptable way of worshipping him;
we pity their blindness, yet are tender towards them,
and would not have the simplicity persecuted in them because of this,
but rather cherished.
If there be any among the Presbyterians, Independents, Anabaptists, Seekers,
or any other sort, that in truth of heart wait upon the Lord in those ways,
_and do not find a deadness overgrown them,_ but a pure, fresh, lively zeal towards God,
with an unfeigned love to his people,--__our hearts are one with this.__
And we cannot fight against this good thing in any of them;
though in love to them we testify,
that their form and way of worship is their present loss and hinderance.
Yet, we doubt not,
but that the Lord in his time will make manifest to such __the light of this age.__`"
See his [.book-title]#Works,# oct. edit, vol. ii. p. 149, etc.

While it may be readily conceded, with a late writer, that "`it is not wonderful,
the views of the Puritans on many subjects were imperfect; but rather surprising,
that they saw _so much,_ and that, with those views,
they were able so boldly to contend for what they believed
to be the cause of God:`"--([.book-title]#Orme`'s Life of Owen,# p. 6.)--yet is
there reason to believe, on the other hand,
that Penington`'s description of their declining state, as given above,
was strictly appropriate; and that they did not retain that tender, teachable,
and humble spirit,
which at an early period so strikingly characterised many of their number.

It would scarcely be excusable to pass by, on this occasion,
that memorable and comprehensive language used by John Robinson,
one of the primitive pastors among the Independents,
on taking leave of his congregation about the year 1620,
as mentioned in Neale`'s [.book-title]#History of the Puritans.#--"`I
charge you before God and his blessed angels,
that you follow me no further than you have seen me follow the Lord Jesus Christ.
If God reveal any thing to you by any other instrument of his, be as ready to receive it,
as ever you were to receive any truth by my ministry; for, _I am verily persuaded,
I am very confident, the Lord has more truth yet to break forth out of his holy word._
For my part, I cannot sufficiently bewail the condition of the reformed churches,
who are come to a period in religion,
and will go at present no further than the instruments of their reformation.
The Lutherans cannot be drawn to go beyond what Luther saw;
whatever part of his will our great God has revealed to Calvin,
they will rather die than embrace it; and the Calvinists, you see,
stick fast _where they were left_ by that great man, who yet saw not _all things._
This is a misery much to be lamented;
for though they were burning and shining lights in their times,
yet they penetrated not into _the whole counsel of God;_ but were they now living,
would be as willing to embrace further light, as that which they first received.
I beseech you, remember it, it is an article of your church covenant,
That you be ready to receive whatever truth shall
be made known to you from the written word of God.
Remember that, and every other article of your sacred covenant:
But I must herewith exhort you, to take heed what you receive as truth.
Examine it, consider it, and compare it with other Scriptures of truth,
before you receive it; for it is not possible,
the Christian world should come so lately out of such thick antichristian darkness,
and __that perfection of knowledge should break forth at once.__`"

But, whoever, with unprejudiced eyes,
looks into the best estate and brightest transactions
of the different periods of _reformation_ in the church,
(taking this term in an enlarged sense,) must perceive,--that the views, and hopes,
and prayers of _the most godly,_ have uniformly verged onward towards a purer standard,
both of doctrine, discipline, and general practice, than that to which,
under those obstructions attendant,
_they themselves_ were enabled to bring their followers.
Accordingly, we find, that even _the writings of many such,
among the "`Established Church of England,`"_ have, as is well known,
been frequently adduced by the different classes of Dissenters from that body,
in confirmation of the several occasions of their dissent.
Authors of some note, also, under our own name,
have made considerable use of _such testimony,_
in setting forth the necessity for a still greater remove, from the precincts,
and approaches, and back-ways to Babylon.
And it is believed, that much more might in this line be produced,
tending to place in strong light the sentiment with which the present chapter was opened:
namely, that the Society of Friends have travelled along in the footsteps,
and as successors of the earlier servants of Christ;
and have believed themselves raised up to bear a faithful and clear witness to the simplicity,
perfection, and spirituality of his holy religion.

And, as the time drew on,
when these people began to be discernible throughout these kingdoms,
in the shape of a gathered church, during that unsettlement,
both in political and religious affairs,
to which [.book-title]#The Diary Of Jaffray# so frequently refers,--has not the impartial reader observed,
(even if altogether unacquainted with collateral evidence of a similar description,)
_what hunger and thirst after a growth in righteousness very generally prevailed._
On all hands the inquiry was excited,
after the more perfect discovery of a knowledge of the Truth;
thousands of awakened and prepared spirits were _reaching
forth unto those things_ of the kingdom of God,
_which were before,_ and which many of them believed,
were about to "`break forth as the morning.`"
Every journal of the experience of individuals,
who at this crisis entered into communion with the Friends,
gives ample proof--to go no further---as to the existence of numerous classes of seeking,
waiting souls; who longed, not only for deliverance from the bondage of sin,
but from the thraldom of unavailing speculation,
and from the commandments and traditions of men.
The very names, which were given, often in contempt,
to the various parties who separated by turns from each other,
in some degree betoken the presence of _that leaven, which was at work underneath,_
in the minds of many, notwithstanding all the conflicting elements and confused heaps,
that lay upon it.
On this subject, the small publication, well known to the Society of Friends,
which William Penn entitles _A Brief Account of the Rise and Progress
of the People called Quakers,_ may be consulted with advantage;
as conveying no inappropriate epitome of the ground successively
taken by those under various religious denominations,
whose origin preceded that of our own: but our historians, Gough and Rutty,
having both made use of copious extracts in their introductions,
it becomes the less needful here to recur to it.

[.small-break]
'''

The Author of the present volume, has thus, in the conclusion of it, attempted,
however inadequately, to set down some observations,
which have been often present with him, while pursuing his interesting engagement.
They have reference, chiefly, to the condition of the living,
baptized believers in our holy Redeemer,
since the time when first a door of degeneracy was opened amongst them.
In the course of these remarks, he has adverted, somewhat,
to the occasion of all well-grounded revival or reform
in religion--an inward sense of deficiency,
and of departure from the true gospel standard, testified of in the Sacred Oracles.
He has also briefly thrown out the view, so strongly entertained by those,
whose history he has been tracing,--that Protestants in general have,
in a lamentable degree, fallen short of that path of perfect reformation, which,
he cannot doubt, would have been long since cast up before them;
had they more entirely yielded themselves to the disposal of the Bishop of souls,
unfettered by the bias of mere creaturely constructions and contrivance.
And further, he has shown, that, when those individuals,
afterward designated "`Quakers,`" were drawn away from all other forms of worship,
systems of faith, and modes of practice,
so as to originate in these kingdoms a distinct people;--this
circumstance purely arose out of a most deep conviction,
on their parts,
of the essential reality of such views,--from a fervent desire
after _that all-important attainment_--even to be "`built up,
an habitation of God, through the Spirit.`"
They undoubtedly believed themselves called upon, in awful humility of mind,
and with a just sense of the privileges bestowed upon _preceding_ generations,
to go _further_ in this glorious work,
even _beyond_ all other "`sons of the morning,`"--to take _higher_ ground than that,
which was held out by the _highest_ in religious profession around them.
This being the case, it is by no means a very unnatural assumption to take up, that,
while other Christian denominations continue at the point where they have even now arrived,
and we ourselves are favoured to keep that which is still committed to us,
(unworthy as we are,)--there is great probability, a testimony such as this,
to the spiritual standard of the gospel, will not altogether cease,
or be suffered utterly to fail.

The Society of Friends, when bowed in gratitude before the Lord,
in a view of the extent of his long-suffering lovingkindness
and faithfulness towards them,
can surely do no other than hold themselves most deeply responsible,
for that station they are called upon to occupy in the ranks of the army of the Lamb.
And whatever this station _may actually have been, or may yet be,_
whether in the van or in the rear, whether among the reserved corps,
or as an advanced guard in extending the limits of his sway;
it is enough for them--without yielding to that curiosity reproved in one of old,
who asked his Lord, "`And what shall this man do?`"--simply, but fervently,
to seek to know their own allotment of service and
of suffering in the universal family of God;
and, _by keeping within the range of his leadings, to the work of their day,_
in this manner to evince their allegiance, and give him glory.

Another subject, touched upon in the course of the present observations,
as forming a prominent feature in the character of those principles,
maintained by this religious community from their earliest appearance,
is--that latitude of feeling towards, that hopeful and tender perception of,
_the least dawnings of good in others._
The writer of these pages trusts he has sufficiently proved--and he wishes
again to confirm the assertion--how desirous they have always been,
to cherish a real esteem for all those, who,
by straight though ever so feeble steppings in the line of heavenly guidance,
are contributing to "`prepare the way`" of the Lord,
whether among their own class or amongst others;
and thus to "`take up the stumbling-block out of the way`" of his people.
_They must continue_ to approve and own the symptoms and proceedings
of Christ`'s Spirit wherever discoverable--divested,
indeed, of that mass of adulterations and superadditions,
which the will and wisdom of the natural man,
in league with the cunning of our restless adversary,
has ever sought to mix in with them.
So far, then, from deprecating, we cannot but hail every, the least effort,
which those who fear God have made,
toward the restoration of primitive Christianity,--that is,
wherever we can believe this to have been purely under the conduct of the grace of Jesus.
With such an understanding, we are most cordially in unison with,--first,
the ancient _Evangelical_ spirit, in its day; the true _Catholic_ spirit, in its day;
the zealous _Reforming_ spirit, in its day; the _Puritan_ spirit; the _Nonconforming_ spirit,
of every kind, in its best and lowly estate.
While, on the other hand, our objection continues to be, as it ever has been,
to traditions and injunctions of men, not authorised by the counsels of Truth;
to forms and modes, notions and observances,
which,--while the Spirit of Truth hath tenderly borne with,
sweetly owning the integrity of those who used them--__that
heavenly Counsellor himself__ never prescribed or appointed.
Nay;
doth not the controversy of this people lie still deeper?--is
it not consistent with their apprehensions of duty,
even to "`turn away`" from such as are settled in the very _"`form of godliness`" itself,_
should these _deny_ that _power,_ which alone can preserve alive,
in the acceptable use of any of the ordinances of God?

[.the-end]
End of the Memoirs.
