== Chapter I.

The Design of Alexander Jaffray in Recording his Religious Experience--The
Way of the Lord with Him in his Youthful Days,
and the Sins And Vanity of Youth--Respecting his Conversion,
with the Ground of his Hope on this Point--His Exercises of Spirit,
in Desire of More Full Assurance,
and Victory Over Sin--The Duty of Wrestling with Cheerfulness against Corruption.

A Journal or Diary, wherein some things are observed,
making appear the wonderful goodness of God in way of Providence towards me,
and my unthankfulness and unanswerable walking;
serving for the further humbling of my heart, and the engaging thereof to him forever.
Jeremiah 30:21.
--"`For who is this that engages his heart to approach unto me,
says the Lord?`"
Isaiah 64:7.
--"`There is none that calls upon your name,
that stirs up himself to take hold of you,`" etc.

Among some confused thoughts I have had on these Scriptures, this was one:--that,
for the better stirring up and engaging the heart to approach unto God,
it might be useful for a believer to be very punctual in
observing all the passages of Divine Providence +++[+++that concern]
him, and those related to him,
for whom he is making daily supplications and putting up petitions;--and that these,
for the better remembering of them, be written down and often perused.
So, the Lord appointed Moses, Ex. 17:14, for a memorial of Amalek`'s destruction,
to write it in a book, that it might be rehearsed to Joshua.
It is observable here, that it was Joshua who was general when Amalek was defeated,
and yet it must be written in a book, to be rehearsed to Joshua.
Why? Because God would have him hereby engaged, upon every remembrance of this victory;
and lest it should be forgotten, it must be written.
The like charge he gives them in Duet. 4:9,
and 6:12. And how is their forgetfulness laid to their charge, Ps. 78:11,42, and cvi.
7, 13, 21;--they forgot their Saviour, who had done great things in Egypt.

My thoughts having stayed a little upon this subject, I resolved to set down, shortly,
what I could attain to remember of the Lord`'s dispensations towards me,
both of mercies and corrections; having weakly sought of him,
that this means may be blessed,
and prove effectual for the engaging of my barren and backsliding heart to him,
never to depart from him any more!

What was his way and goodness towards me in my younger days,
so slothful and sluggish have I been, that little or nothing else I remember,
only if I may say with the Psalmist, 22:10, "`I was cast upon you from the womb:
you are my God from my mother`'s belly!`"--and,
praise to him! that by him I was "`fearfully and wonderfully made,`" Ps. 134:14,
and that he slew me not there, +++[+++as Jeremiah expresses himself,]
20:17. It is a part of the misery of children,
that they are incapable of observing God`'s goodness to them in their younger years.
But, much more are they miserable in this,--that not only then,
but their youth and more perfect age is also, for the most part,
spent in vanity and much looseness; and so was mine.
Many things might I here remember,
to my shame and great confusion;--which indeed have
been at some times so remembered by me,
to the eternal praise of the free grace and goodness of God,
who I trust has blotted them out, and freely forgiven me.
And therefore, I will spare to mention them; hoping, through the blood of Jesus Christ,
they shall never be remembered to me here,
nor in the world to come;--wishing of the Lord,
that the sins of my youth may be always remembered by me,
and serve for matter of much humiliation to me all my days;
as it is promised in Ezekiel 6:9,
"`And they shall loathe themselves for the sins which
they have committed in all their abominations.`"
This shame and loathing will be much upon the heart that
is sensible of God`'s being pacified towards it.
Ezek. 16:63, and 36:31.

How needful is it for young men to look back upon their
young and tender years,--how these were spent in vanity,
and many times in much looseness!
How few are there that rightly consider how they are kept underlings
in grace all their days! and temptations many times,
for this very cause, are let loose upon them,--that they have not considered,
nor rightly been humbled for the sins of their youth.
It is said of the wicked, Job 20:11,
"`Their bones are full of the sins of their youth;`" so may it be, many times,
even with the dear children of God, if they do not advert to,
and consider what they were in that time of their youth.
David, in Ps. 25:7, prays fervently for pardon of these sins;
and how few are there that consider that the very remembering of the sins then committed,
without humiliation for them and loathing of them, is, in the sight of God,
a multiplying of the same sin upon them.
See this clearly from Ezekiel 23:21 and 19.

How far are right thoughts of this matter from the consideration of many young fools,
who excuse themselves from these things, as being but the tricks of their youth;
and thus notably play the fool, not considering, as the wise man says, Ecc. 11:9,
that for these things God will bring them to judgment.
Happy is the young man that begins early to seek after God,
while his mother is his teacher, Prov. 31:1; that timely inquires with the prophet,
Ps. 119:9, wherewithal he may cleanse his way.
And, for this purpose, he should not faint nor be weary, nor mistake God`'s dealing,
if He be accustoming him to bear the yoke in his youth.
"`It is good,`" says Jeremiah in Lamentations 3:27,
"`for a man to bear the yoke in his youth,`" when
like a bullock he is unaccustomed to it, Jer. 31:18.
I may, if I mistake not my case,
speak something of this from my experience;
and exhort my dear children to walk more warily and
circumspectly in their youth than I have done.
It is not enough to be of mild and douce natures,
and blameless as to public ways before men.
I thought, in some measure I could say, it had been so with me;
that for many years together I had lived in a blameless way before men,
and had never a thought all this while of the sins of my youth; or if there was,
it was but a very overly word of confession, until I was near forty years old; and then,
and ever since,
how have the sins of my youth been presented to me--how
many times have I been laid in the dust,
upon the consideration of them!
Yet--to the eternal praise of the free grace of my God,
I desire to speak it--his goodness was such to me, pitying my poor and weak condition,
that I was not much troubled with thoughts of desperation;
which might justly have been my case,
considering how vile and loathsome a wretched creature I have been.
But all this while, for some years together,
there was left for me good and solid grounds to have hope in his mercy;
only some vile and violent temptations, as messengers of Satan,
were let loose to buffet me.
And among other ends, which I conceive the Lord pointed out by these unto me,
was the bringing me more solidly to remember and be humbled for the sins of my youth,
than ever formerly I had been; and to make me, in his strength,
seek and resolve more closely to walk with him, and to make use of that Scripture,
1 Thess. 5:22, "`Abstain from all appearance of evil.`"
O! what mercy is it, when the creature is helped rightly and timely to consider,
the great advantage it will be to him, when the case seems doubtful,
to incline to the safest hand of abstaining; and not only then,
but to abridge himself in the extent of his liberty,
not coming near to the out-most bounds of what is lawful.
For, if he make use of taking liberty to come this length,
he cannot long escape falling into the ditch; and how deeply he may be plunged,
before he recover again, the Lord knows.
Thrice happy is he, that is helped of the Lord timely and seriously to think of this,
and to make conscience of such abstinence and abridging, etc.

The goodness of God to me is in this the more to be observed,--that
he was pleased while I was thus in the heat of youth,
and very ignorant and grossly guilty before him, I must say, in a wonderful,
and to me an inexpressible manner, to bring me from darkness to light.
I can neither tell the time nor place when I was converted,
my ignorance of which did sometimes trouble me;
it not being ordinary for great sinners to be so situated.
For it seems to have been a prophecy of the times of the gospel, Ps. 87:5-6; so,
Paul could tell all the circumstances of time, place, etc. Acts 22:6-7.
He could also say, that Andronicus and Junia were in Christ before him. Rom. 16:7.
If there was cause for Israel to remember
the day of their deliverance from their bondage in Egypt,
as it is commanded, Ex. 13:3,
how much more matter have we to remember the day of our deliverance from spiritual bondage.
However much this ought to be endeavoured for and aimed at by every believer;
yet I dared not conclude, that therefore I was not converted,
because I could not tell either the time when, the place where, or manner how it was.
I +++[+++rather]
concluded, and I think warrantably so,
that the pressing of this too much was but a temptation,
God`'s way in it being very various.
Only, the thing which I looked upon as my duty was,--to have the point itself made clear.
And in this, though I knew not well what to say, having much cause,
by reason of much corruption, and a body of death yet unmodified in me,
to fear and tremble when I think to speak of my being converted;
yet I dare not but affirm it, to the eternal praise of his free grace,
through Jesus Christ, that he has had mercy on me!

For, first, I think I may say, in some measure of simplicity and sincerity of heart,
that though I be sensible of exceeding much vileness and corruption in me,
yet I desire to be holy.

Secondly, That in any measure I was sensible I was vile,
and that this sense for a good time together was
growing with me:--here was another ground.

Thirdly, Though I dare not say that secondary and selfish ends had no place with me,
in my desire to have sin subdued and holiness perfected in me--such ends, I mean,
as fear of wrath and punishment here and in hell,
and to eschew shame and disgrace in the world;--yet, I think I may say,
(and many times had I liberty in prayer to take God to be my witness,
when none but he was present)--that fear to offend so good
a God--to make the wicked blaspheme his name and mock religion,
(which I had avowedly made some profession of,)--fear to stumble the weaker, yes,
some of the stronger Christians of my acquaintance, or that should hear of me,
with whom I differed in the matters of government
and constitution of the church of Christ;
that they, by my fall or miscarriage,
might be confirmed in their prejudice conceived against these truths,
wherein I differ from them;--fear thus to dishonour so good a God,
and to offend any of his little ones, was also frequently, and I hope I may say,
much upon my heart, and a very great restraint unto me against sin.

Fourthly, Some measure of light and affection was granted,
though I remain in much darkness and ignorance of God; yet,
comparing my state now with what formerly it was, I cannot but, to the praise of God,
acknowledge with the blind man, John 9:25, "`Whereas I was blind, now I see.`"
+++[+++see Appendix, A.]
If the Lord shall be pleased, so to continue with me the sight and sense of my vileness,
as thereby to make and keep me more and more humble and low before him; and thereupon,
to seek to have my dependence and walk with him more close and near than formerly,
I know I may judge this to be a very sound and sure ground.

Fifthly, Whereas I was sometimes, and naturally am,
of a very sharp and censorious disposition, of a bitter and persecuting humour,
especially to such as in matters of opinion differed from me;
it has pleased the Lord a little to frame my heart another way;
inclining me rather to compassion and pity those that err,
and through darkness or delusion, are, in this time of temptation,
miscarried in their judgments about those matters wherein good men differ among themselves;
especially when the Foundation is kept, and a conduct blameless according to the gospel,
there, I think, much pity and charity is to be exercised.
"`Charity thinks no evil:`" where it may think good,
it thinks no evil;--and I desire to extend it no further.
So, this desire which I had to do the people of God service,
and love to them as such--which I dare not but confess, to the praise of God,
he has in some measure granted to me--that was another ground.

Sixthly, Love to and desire after the most home-speaking and soul-searching ministry,
that discovers sin and its abominable nature most,
and distinguishes and discerns best between real and true grace and its counterfeit.
I have been many times glad to find it so,
even when the doctrine has most opposed my corruption and idol,
or the sin of my natural complexion and temper; which corruption in me I would,
+++[+++according to the propensity of the unregenerate part,]
most willingly have dallied with.
Yet, how sorely have I been foiled again and again, after all this,
by the strivings of these corruptions in me!

Seventhly, A desire I had to be useful to God in my generation,
to know the work of my generation; and--if I could do no more--I was willing,
and sometimes was helped, to pray for it.
The mistakes and ignorance of God`'s people about this,
is not the least part of their judgment--if I mistake not.
And, that the Lord was pleased to give me any desire after the knowledge of his mind,
in observing his wonderful way of dispensations, I count it no small mercy,
and another ground or proof of his love towards me.

Though these and the like signs are good, yet,
that assurance and testimony is made out but as it
were in part,--it is not full and complete,
without the Spirit`'s +++[+++express]
testimony, bearing witness with our spirits that we are the children of God. Rom. 8:16.
And the Spirit (not of the world,
but the Spirit of God) is given for this end--that we might
know the things that are freely given us of God,
1 Cor. 2:12: wherein,
this is clearly intimated--that every believer has the Spirit for this end given to him,
that he may determine rightly between the graces of the Spirit; as it follows, verse 15,
"`The spiritual man judges all things.`"
And where this judgment cannot be thus infallibly made,
there the heart is not in that good frame and approved condition it ought to be; for,
"`Do you not know not that Christ is in you, unless you are reprobates.`" 2 Cor. 13:5.

It pleases my Lord, who is only wise, to keep me in a hungry, low condition; that,
though I dare not say but there is hope, yet,
how exceeding far am I from that measure and full assurance, which I desire to wait for!
And, in waiting, I have been much assaulted,
and brought nigh to the very gates of despair.
Oh, what a dreadful sin is misbelief! it counts God a liar. 1 John 5:10.
When I was, many times, through renewed assaults of a busy enemy,
brought very low,--even near fainting as to the hope of victory,
there was then ordinarily brought to my mind some Scriptures:
a few of them I shall mention;
for the consideration of them has been of much use
to me.--"`There has no temptation befallen you,
but such as is common to man; but God is faithful,
who will not allow you to be tempted above what you are able;
but will with the temptation also make a way to escape,
that you maybe able to bear it.`" 1 Cor. 10:13.
The faithfulness of God is engaged to make way for your escape.
But misbelief said, he was long a coming.
Answer: "`The vision is for the appointed time,
but at the end it shall speak and not lie: though it tarry, wait for it;
because it will surely come, it will not tarry.`" Hab. 2:3.
See Ps. 27:14, and Isa. 28:16.

A special means, by which I was +++[+++prevailed upon]
the more willingly to wait, was this,--that I could not deny,
but it was clearly for my advantage, even to be delayed in having granted unto me,
what my soul so much sought after.
For my gracious Lord was pleased to let me see, that, by leading into this wilderness,
and pleading with me there, would he bring me into the bond of the covenant. Ezek. 20:35,37.

The mercies I found most obvious to my discerning, in this dispensation, were, First,
That by this means, he made me study to be humble, very humble,
when I saw so much cause of humiliation, so much vileness, in me.--Secondly,
I was thereby drawn to pray oftener, and sometimes to set days apart.--Thirdly,
I was the more convinced of the necessity of a constant,
continued influence of grace from him, or be overcome.--Fourthly,
That I was not already overcome,
did speak clearly out that the almighty power and arm of the Lord was to be seen in it,
or I could not have resisted one assault for one moment.--Fifthly,
I was by this means also,
stirred up some way to seek after more close fellowship and communion with him:
this thought being, in meditation one night, offered to me,
and on the morrow written down,--that I should not be free of raging devils to assault,
and a loose heart to give way,
until I were helped to make more account of Christ`'s company than formerly.--Sixthly,
I learned hereby, to pity others that were tempted,
and to know how to speak of and to such.--Seventhly, Sometimes I was brought by this,
to think a little of death, and of the happiness of their condition who were away,
because they were not thus molested with sin.--On such accounts,
did I conclude it to be my duty,
not only to go on wrestling with grief and sore distress,
through this miserable valley of tears, but with cheerfulness to proceed.

The consideration of these Scriptures following,
afforded not only matter patiently to wait, but to desire to do it cheerfully:
and I must say this,
that I found it a way much blessed to me of the Lord,--and so shall you,
if you rightly essay it.
See Ps. 27:14, where waiting on the Lord is joined with good courage.
He gives those much that thus wait on him; more than ear can hear of, or eye can see,
has he prepared for them that wait for him, Isa. 64:4; and it is added,
that he meets them that rejoice.
See how, in Duet. 16:14-15, the people are commanded to rejoice, and in xxviii.
47, how they are threatened with wrath for not doing it: surely,
whoever attains rightly to act in this duty,
so to rejoice as to do it "`evermore,`" 1 Thess. 5:16; and yet to fear always,
Prov. 28:14, he shall find the joy of the Lord to be his strength,
as it is promised in Neh. 8:10.

And, as this is the way much recommended,
so has it been blessed with success unto the saints in all ages.
When they were brought to the greatest extremity of difficulties,
then did they take comfort and rejoice in the Lord; and when all help failed,
he was a strong tower of refuge unto them; for he waits to be gracious, Isa. 30:18,
and his eye runs through all the earth, seeking to show himself so. 2 Chron. 16:9.
See it made good in David`'s experience, 1 Sam. 30:6,
when he was brought to the greatest strait that ever he was in, it is then said,
he encouraged himself in the Lord his God,
and went on and got victory over all his enemies.
And in Hab. 3:18, "`Although the fig-tree shall not blossom,
nor fruit be in the vines,`" etc. he concludes, albeit all the course of nature,
and heaven and earth, should fall and turn upside down, "`yet will I rejoice in the Lord,
and joy in the God of my salvation.`"
So are we exhorted to do in Isa. 1:10, when we are in darkness and have no light,
as the child of God may be, then is he to "`trust in the name of the Lord,
and stay himself on his God.`"
Asa did thus, in a great strait, 2 Chron. 14:11, and found blessed success; and so,
in these two notable places of Isaiah it is promised, chap.
xli. 17, to the poor and needy, when their tongue fails them for thirst,
then will God hear them; and chap.
xl. 30, 31, "`They shall renew their strength, and mount up with wings as eagles;
they shall run and not be weary, and walk and not be faint;`" and, chap.
lix. 19, "`When the enemy comes in like a flood,
then the Spirit of the Lord shall lift up a standard against him.`"
