== Chapter IV.

1650: At the battle of Dunbar, Alexander Jaffray receives four wounds,
and is taken prisoner--His courteous treatment, and liberation;
and the frequent interviews he has with Cromwell, Fleetwood,
and Dr. Owen--Writes a paper on "`the causes of the lords controversy
with the land,`" and on the solemn league and covenant,
etc.--1651: he has conferences at Edinburgh with a meeting of ministers and professors:
his reflections thereon--Some individuals at Aberdeen, in common with himself,
entertain scruples as to the mode of administering "`the
ordinances`"--Conferences are held on this subject,
both at Edinburgh and Aberdeen, with Rutherford, Guthrie, Gillespie, Carstairs,
and others.

The King being come home, we were not well landed,
when England was on our border with an army,
to succour themselves against our invading them.
It is not my purpose here to speak to that business, or the unwarrantableness of it,
or of our defence and the lawfulness of it; but the thing I aim at is,--to remember (and,
O that I could do it with a heart rightly thankful!) the just severity
and yet merciful dispensation of my blessed Lord,
who, by a very sad blow at that battle of Dunbar, the 3rd day of September, 1650,
brought me to the very gates of death;--my horse being shot under me,
and I having received two wounds in my head, one in my right hand,
and another in my back.
So good was the Lord unto me,--that, albeit for my manifold guiltinesses,
and particularly for my accession to and compliance
in that matter of our acting about our King,
he might have left me there,--and forever to his wrath in hell;
yet--glory to his name!--that guiltiness was blotted out,
and all my sins pardoned through Jesus Christ.
But, thereby was I called to remember my folly,
and to look back and examine my ways since my infancy; I having that day got again,
as it were,
a new take of my life for this end,--to hold it upon a new account,--of the Lord,
and for him.
And more particularly was I then called to reexamine my
way and miscarriages in the matter of that negotiation,
and to be more humbled for them before the Lord;--I being preserved
from the fury of those who first encountered me in the field,
I may say, very wonderfully.
Having gotten three of the wounds afore mentioned,
while the fourth stroke was coming to have made an end of me,
the hand that drew it was diverted, before he could bring his sword from his shoulder,
which he was drawing with great passion, to my throat, who was then lying on the ground,
not recovered since my horse fell with me, he being lying on my left leg;--I say,
before his stroke could come at me, in that very nick of time, his hand was diverted,
and carried to give that stroke to one +++_______+++ Loundre, an officer in our army, who,
at that very instant of time, being hardly pursued,
run close by him who was drawing the stroke at me;--and yet, for all his haste,
he was heard to call, desiring to spare me.
Thereafter, I, having gotten quarter, and rendered my arms,
was wounded by a thrust in the back, which made me to be in more danger than ever;
being thereby unable to walk, I was like to have fallen among the common soldiers.
But the Lord provided a gentleman, who took care of me,
and having mounted me on horseback, carried me to Major General Lambert,
and by his order to Broxmouth, where my wounds were very carefully +++[+++stanched.]
And being, through the loss of much blood and weakness of body, brought to faint,
I was very kindly refreshed with what the place could afford,
and thereafter by my Lord General +++[+++Cromwell]
brought to Dunbar; where I was most civilly and courteously used,
beyond what was due to one of my capacity or rank.
Here I lost my dear brother Thomas, who undoubtedly was killed,
though we could never get word when or how; for once I saw him taken prisoner,
when I fell: as also my servant James Beza was here killed.

I continued five or six months prisoner, but was used most courteously all the time;
at last, I with other two, ministers, whereof that excellent, precious man,
Mr. John Carstairs, was one,
were exchanged with the Captain Skeiper and company of an English ship, who,
being taken on the Irish seas, were then prisoners at St. Johnstone +++[+++now Perth.]
So, in the end of February or March, 1651, I came to Aberdeen.
+++[+++see Appendix, N.]

During the time of my being a prisoner,
I had good opportunity of frequent conference with the Lord General +++[+++Cromwell,]
L+++.+++ Gen.
+++[+++Lieutenant General Fleetwood,]
and Doctor Owen; by occasion of whose company, I had first made out unto me,
not only some more clear evidences of the +++[+++Lord`'s]
controversy with the family and person of our King,--but more particularly,
the sinful mistake of the good men of this nation,
about the knowledge and mind of God as to the exercise of the magistrate`'s
power in matters of religion--what the due bounds and limits of it are.
The mistake and ignorance of the mind of God in this matter,--what evils
has it occasioned! fearful scandals and blasphemies on the one hand,
and cruel persecution and bitterness among brethren on the other! +++[+++see Appendix, O.]
The consideration of this,--with some other points relating to the Covenant,
and League and Covenant,--our mistakes of the mind and will of God,
(with the selfish ends of the most,
in contriving and carrying on these Covenants,) being at
that time very clearly made out to me,--I was forced,
for reducing my confused thoughts in order, to set them down in writing; which, at first,
were drawn forth the length of near twenty sheets of paper,
but after reduced to ten or twelve.
I think I have matter to acknowledge the goodness of God unto me, who,
so timely and +++[+++sweetly]
began to give me light in these things,
though accompanied with much deadness and unanswerable walking on my part.

I was sometimes,
after so much opposition as I found in these things from good and holy men in this land,
put to it, to examine over again, from what spirit I had been led forth,
to think and conclude so differently of these things from what formerly I did.
Especially as I perceived, that the reach of my thoughts would tend to no less,
than the overturning of what we had concluded to have been the work of reformation;
for the maintenance of which, we were so solemnly engaged,
both ourselves and our posterity, in the Covenant and League and Covenant.
The thoughts of these things, did for some months very much perplex me; and,
being overswayed sometimes with too many prudential considerations,
I was brought very near to have fully waved and laid aside all thoughts of that kind,
and to have suppressed them; because I saw reproach to come thereby,
not only upon myself but on the nation,
and also so great appearance of suffering and hazard that way, if the king`'s party,
who were then in good hopes, should then, or any time thereafter, prevail.
But, for all this, it could not be;
the clear discovery of the thing being so made out to me, that I could not contain;
but went to some few at Aberdeen, as Mr. Andrew Cant, Mr. John Menzies, Mr. John Rowe,
+++[+++Principal of the College,]
and Mr. William Moire +++[+++Moor.]
To all of them I not only spoke my thoughts freely,
but gave them my notes before mentioned to read,--which they did; except Mr. Andrew Cant,
who refused to read them.
Thereafter, having written to some good men in the south, and finding no satisfaction,
I came south to them; and, by Providence, found about fifty or sixty of them,
ministers and professors together, about the very thing I was desirous of inquiring;
and every one speaking publicly,
what they thought might be the causes of the Lord`'s controversy with the land.
+++[+++see Appendix, P.]
This inquiry having been my work for some months before,
I was ready to have communicated my thoughts to them;
but knowing how offensive it would be, and also fearing,
lest through any temptation or mistake I had been wrong, I was content,
rather at first to speak in private with the Lord Warristoun, Mr. James Guthrie,
and Mr. John Levinstone +++[+++Livingstone.]
But finding no satisfaction, nor any reason why I should forbear,
except it were loathness to offend men, I did in their public meeting-place in Edinburgh,
upon the +++_______+++ day of +++_______+++ 1651, speak some few words, and thereafter gave in,
under my hand,
a paper containing my thoughts of the causes of the Lord`'s controversy with the land.
I do not here insert it, but leave it to be found,
together with the aforesaid papers of my thoughts at large, bound together; from which,
at this day,
(there being near six years passed since,) I find no reason to alter in the least;
though many things more might be added, if that were now my present business.
After the reading of this paper, there were some much offended; yet,
by the mediation of Mr. Levinstone +++[+++Livingstone,]
Mr. Rutherford, and Mr. John Carstairs, (with whom Mr. James Guthrie,
being moderator at that time, concurred,) they appointed a time,
and so many of their number, for conference with me.
All this time, since our being in Edinburgh, Mr. John Menzies, Mr. William Moire +++[+++Moor,]
and Mr. Alexander Skene, (these, having been sent for by the meeting,) went along with me.
But, before my giving in that paper, they withdrew; (though they were put in the place,
yet would they not concur with me in it;) and after the meeting was dissolved,
they returned home to Aberdeen.
But I stayed to attend their conference with me, according to their appointment.
And, having kept several meetings, for the space of three or four days,
I found no satisfaction in anything I doubted of,
nor cause to change my mind in anything I had positively asserted; but,
on the +++[+++other hand,]
was rather confirmed, when I heard they could say so little to the contrary,
and some division among themselves.
Whereupon, we parted; and I returned home to Aberdeen.
+++[+++see Appendix, Q.]

I am not here to forget the occasion of my search,
and inquiry in the matters of church government; I having been always, before this time,
(according to my measure, weakly, as I could,) zealous for Presbytery.
Being led forth to inquire and search out,
what had been the ends of the good men of this nation,
that had carried them forth so zealously in that matter of the Covenant, I found,--that,
among the rest,
this was one of the many ends that first led our zealous predecessors to the contriving,
and thereafter ourselves and others to the carrying on of the Covenant:--namely,
thereby to maintain the doctrine, worship, discipline,
and government of the Kirk of Scotland, as we call it.
Our worthy and zealous predecessors, at the first Reformation,
had advanced no small length,
according to the dispensation and measure of light of that time; but,
the generations then succeeding, did not consider,
that as the mystery of iniquity did not grow to its
height in one age or two,--but we were involved,
after a long tract of time, in that deluge,
which at last overflowed great part of the Christian world--they, I say,
did not consider, that as by degrees we were involved, so, in the same way,
were we to wait for our deliverance; for, as in Ps. 97:11,
"`light is sown,`" so must the growth of it be waited for by the righteous.
These good men,--deeming that they had attained to the full perfection
of what was in the Holy Scriptures about the government of God`'s house,
because they were as far on as Geneva,--yes,
in some things beyond her,--and so very far beyond England,
who were still kept under that anti-christian form of Prelacy,--concluded,
there was no better way for them to keep what they
had attained from being again brought back to Popery,
(or at least to Prelacy,
which they so much and justly abhorred,) than by a solemn vow and covenant,
to engage themselves and their posterity forever
to maintain that which they had now attained,
conceiving it to be the only way of Jesus Christ.

Thus, after seeking of God for direction,
and the use of all means that I could attain unto for information,
I did then clearly discover, this their way to have been a sad snare and temptation;
which has led them forth, not only to the making of the Covenant at first,
but to all the ways of human prudence and policy,
that the wits of godly and pious men could invent for maintaining the same.
And finding that the maintaining of Presbytery was one,
if not the main and chief end proposed,
by those that were most honest and single-hearted,
in contriving and carrying on the Covenant,--(others, as statesmen and politicians,
had other ends;
but I speak of the godly,)--thus having found that we were so engaged to Presbytery,
as the only way of Christ,
I was necessarily led on to inquire about the thing itself,--if indeed it was truly so.
This was the true occasion and rise of my inquiry in these matters; and not,
as some have conceived, that I was thereto engaged and insnared by men`'s persuasions,
or other base and corrupt ends;--though good men, as Mr. Wood,
has both spoken and written so of me and others.
I think they were the rather confirmed in this their apprehension of us,
because our inquiry and search into these things,
and our public appearing contrary to them, did fall out to be near about the time,
or not long after, the coming of the English into this nation.
However thus they might have mistaken us and the occasion,
willingly would we have kept out of the way, but could not, (the Lord having formerly,
but then more pressingly, put us to it,
to search and find out our snare in these things;) yet the Lord knows,
how far some of us were misapprehended in these things, who may say,
(so far weakness and frailty will allow,) that neither the hand of man,
nor other by or base ends whatsoever, were persuading in this matter.
But, indeed,
the true occasion and first rise of my inquiry in these matters were shortly these.
+++[+++see Appendix, R.]

The dreadful appearance of God against us at Dunbar,
after so many public appeals to him--we were +++[+++not only]
so visibly forsaken, and at that time given over of the Lord for our correction, but,
in a very short space, so broken and divided among ourselves,
(as to this day remains,) as who could not but see that we were eminently called,
not only to examine our guiltiness in the breach of all the holy laws of God,
(whereon much has been well expressed by many good men;) but more particularly
this was at that time with a strong hand from the Lord,
Isa. 8:11, borne in upon my heart, and so does continue to this day;
+++[+++namely]--that there was something,
both in the matter and manner of our carrying on
of what we conceived to be the work of God,
that was more particularly pointed at by our stroke, as sinful and wrong,
than any guiltiness else that we were under whatsoever.
+++[+++see Appendix, S.]

As to the result of my inquiry about the +++[+++church]
government that was then established in this land, I shall say very little to it,
only in the general.
I think I have full persuasion warrantably to say
this:--However it may be a way of Christ,
which for the time he did make use of,--as formerly he had done of Episcopacy,
until the upholders of that way became so insolent,
as to impose it as the only way of Christ upon the consciences of his people;--yet,
sure I may say, without doing Presbyterians any wrong, it is not the only way of Christ,
as they would have it, and as in the Covenant all are sworn to it.
Yes, if I may say further, without offence,
that it is very far from being the only way of Christ; though I think,
if it were soberly managed, it may be looked on as a step nearer to the way of Christ,
than Episcopacy; yet, still it is in my apprehension,
after the best and most diligent search that I could make, but a human invention,
composed with much prudence and policy of man`'s wit, fitted for those times,
when it had its rise in Geneva, from that precious and worthy man, Calvin.
Nor is it any derogation to him, who served God worthily in his generation,
that others coming after, and far inferior to him, see more in these things than he; yes,
the least of +++[+++those in]
the kingdom of heaven in this respect is greater than John himself. Matt. 11:11.

And my spirit became at last satisfied as to these things of government, discipline,
and constitution of churches, upon this ground:--That, for many ages now past,
the truths of Christ, not only of government, but of doctrine and worship, yes,
the very being of the church itself, as to its external and formal way of constitution,
having been given over into the hands of antichrist, Rev. 11:1-2,
we have been much in the dark,
and are to this day but beginning to break through these clouds,
which Christ with the brightness of his coming (whereby
he is said to destroy antichrist) is about to dispel.
Then shall we see clearly the mind of God in these things;
truths of doctrine having been the work of Christ in the ages past,
for the clearing of which he fitted many worthy instruments;
he is now to be about the clearing up his mind +++[+++to us]
in these points of the constitution and government of his house; which, doubtless,
will be acknowledged by all intelligent and sober men,
to be more darkly expressed in the Holy Scriptures than other matters.
+++[+++see Appendix, T.]

But here it is to be observed, and much to be regretted, that good men,
who formerly in all their debates about points of doctrine against Papists, were one,
Lutherans, Arminians, etc. concurring and strengthening one another among themselves;
yet so unhappily are they, in these times, about the debate of government,
etc. divided one from another, that they are ready, in bitterness,
to pursue and persecute one another.

One observation yet, and I shall leave this theme.
+++[+++With regard to]
there being an appointed time for the rise and reign of antichrist,
and the day of his doom determined, whenever that period shall be,
of the end of these 1260 days or 42 months, +++[+++see Rev. 13:5.]
it certainly is not yet come to pass;
and therefore are we in the dark as to these things,
which then we are clearly and purely to enjoy, according to their institution.
I say, that during this time of our darkness,
he shall be found to have most of the mind of God made known to him as to these things,
that walks soberly, and in his judgment is least engaged to any +++[+++one]
of these forms, so as to account it the only way of Christ;
thus reserving for a more full discovery of His mind, in these things as yet fixed,
and adhering to the conscientious use of all the ordinances of Jesus Christ;
practising with those who, according to his light,
he conceives to come nearest to the +++[+++written]
word; without passion or bitterness in contending with others,
but embracing in love all that are truly gracious,
and walk soberly according to the gospel of Christ.
For this is worth the observing,--that how sure soever
the authors and maintainers of these forms have become,
so to idolize and cry them up, as to conclude them to be the only way of Christ,
and so to have them imposed upon the consciences of their brethren;--then
has the Lord visibly appeared against them and their way,
and overturned it to the sight of all men.
So he did with Episcopacy: when they were at the height of their pride,
and become very insolent; then are they overturned, first in Scotland,
then in England and Ireland.
And so has he begun to do with Presbytery;
when they were at the top and height of their confidence;
having by the League and Covenant engaged the three nations thereto,
and the Assembly of Divines fully for them;--accommodation to the
persons of some good men was that only which could be obtained,
but toleration to no way but that;--when they are thus at their height, then, there,
the Lord leaves them, and their business goes back every day.
Not only in England, the power of the state turns opposite to them,
and offers liberty to such as would serve God in other gospel ways; but also in Scotland,
(the power from them there, upon a double sort of account, both civil,
and ecclesiastical, being fully in their hands,) the Lord appears visibly against both,
by breaking the one in the open fields of Dunbar,
and the other in the open meetings at St. Andrews and Dundee,
through needless contests and prejudices one with another,
irreconcilably dividing them one from another,--which has
tended more to the prejudice and overturning of their way,
than all the power and policy of men could have done against them.
Let Independents beware, and keep close to their principles, which so far as I know,
(if men`'s pride and corruption lead them not to
it,) tend not to persecution or imposing upon others.
+++[+++see Appendix, U.]

Some time after this, some Christians in Aberdeen, men and women,
having for a long time been convinced of these things,
(long before ever a thought of them was with me,) found themselves obliged
to endeavour to have the ordinances administered in a more pure way,
than there was any hope ever to attain to have them in the national way.
But before we would conclude to do anything of this, it was thought necessary,
first to impart our purpose to some Christian friends,
and to be willing to hear what they could object against our resolution.
Whereupon, by common consent, a letter was drawn up and subscribed,
in the name of the rest, by Mr. John Rowe, Mr. John Menzies, Mr. William Moire, +++[+++Moor]
and me, and directed to the Lord Warristoun, Mr. David Dicke, Mr. John Levinstone,
+++[+++Livingstone]
Mr. James Guthrie, and Mr. Samuel Rutherford, to be communicated to whom they pleased;
which letter was of date, at Aberdeen the +++_______+++ day of +++_______+++ and +++_______+++.

After this, very shortly, we had large letters from many good men, both south and west,
written to us; the scope of which was, to dissuade us from our purpose,
or at least beseeching us not to fall on any such dividing way, as they called it,
until we should first meet with them and confer thereabout,
promising to endeavour our satisfaction as much as could be.
After seeking of God in this,
we could not see how we could refuse this their offer of conference,
as a means by which the Lord might further make known his mind to us,
for our confirmation in these things,--which we hoped for; yet so,
as being reserved to receive whatever light the Lord should offer to us.
And therefore, having notice of a meeting of these good men,
to be at Edinburgh +++_______+++ day of +++_______+++, it was resolved,
that Mr. John Menzies and I should go there, and confer with them.
We, being there, met with them,--not in their public meeting-place, yet not in a corner,
but publicly in Warristoun`'s chamber, for several days together; but in the end,
came to no other conclusion than formerly,--that we were
clearly called upon to endeavour to have the ordinances,
(especially the sealing ordinances of Christ,) administered
unto us in a way nearer the institution,
and more pure in way of administration, than it was possible,
or there was any ground of hope, to have in the national way.
Upon this, we having told them so much, in a very calm manner,
and that we were the more confirmed in this our resolution since we came there,
parted calmly,
they having exonerated themselves very freely and
lovingly to us:--only Mr. Andrew Cant went out,
before our dissolving, in some passion, and left us.
Yet they left it not thus; but resolved that four of their number, namely,
Mr. Samuel Rutherford, Mr. James Guthrie, Mr. Patrick Gilespie, and Mr. John Carstairs,
should come to Aberdeen, and there confer with us together; pressing us much,
to delay any public appearing until then.
To which we would terms agree; promising, only to do as the Lord should direct us.
Within some few months thereafter, namely,
the +++_______+++ day of +++_______+++ they came to Aberdeen.
They stayed seven or eight days, and had frequent meetings with us all,
together and apart,--but to no purpose for the errand they came about;
all of us being rather more confirmed to our former grounds;
Mr. John Menzies and Mr. William Muire not being with us, by reason of sickness.
Thereafter, in the month of November,
in the year +++_______+++ we did together partake of the ordinance of the supper of the Lord,
publicly, in the meeting-place called Gray Friars.
+++[+++see Appendix, V.]
