== Chapter XII.

1661: Alexander Jaffray visits some prisoners in the Tolbooths as, Robert Trail,
John Stirling, Gilbert Hall,
and Alexander Moncrief--He has an interview with James Guthrie,
on "`the causes of the Lord`'s controversy with the land`"--His
desires on behalf of his wife--Christ`'s voice in the heart--The
duty and benefit of being "`quiet,`" and not repining,
or being dismayed at the Lord`'s way of exercising
the soul--He obtains access to Robert Macquare,
then a close prisoner for high treason:
his conferences with him and other prisoners--On conformity to the world--3rd July, 1661:
The danger of setting up "`duties`" in the place of Christ--On keeping close to Christ,
the fountain of Life, etc.

The 8th of March, 1661, having been, some days before this,
some way moved and pressed in spirit, to visit some of the prisoners now in the town,
I did, at various times, visit Mr. Robert Trail, and Mr. John Sterling,
ministers of Edinburgh, Mr. Gilbert Hall, and Mr. Alexander Moncreife,
minister at +++[+++Scoonie]; minding, as occasion should offer,
to have communicated with them my thoughts of the dangers and duties of this time,
and to have heard theirs.
But, partly through lack of opportunity, and by reason of much darkness,
that both they and +++[+++I lay under], nothing worthy the mentioning, to any purpose,
was among us.
+++[+++see Appendix, NN.]

That day, I went to visit Mr. James Guthrie in the Tolbooth; and resolved,
to be more free and plain with him,
than I thought safe or convenient to be with any other, which at last I +++[+++ventured]
to do, laying +++[+++open]
further my thoughts freely to him.
And, lest he might have been jealous of me, as being under a temptation,
because of these times,
(seeing my present thoughts of the Lord`'s controversy with his people,
seems to fall in and suit with what the men that are now in power, for their own ends,
are acting,) I desired him not so to judge of me, as favouring them or their ends,
in what they do: for, I am very confident, God is highly displeased herewith,
and will overturn them, and their doings and ends both, if they repent not.
But, I desired him to mind a paper,
he did see me give in to a meeting of ministers and professors here, in Edinburgh,
in October, 1651; containing my judgment and thoughts,
of what might be the occasion and cause of the Lord`'s controversy with his people.
The which paper he did well remember.
And I told him, that my present thoughts were much the same, that then they were.
And the Lord had been ever since, and now was more plainly, making it appear to be so;
by having, in a great measure, shaken loose and overturned the national way of +++[+++church]
government, in its method and way, and all the dependencies of it, as they were formerly,
and +++[+++as they were]
later, in these times, framed and carried on,
by the will and inventions of men--as the uttermost height and pitch of reformation,
to which the Lord was to have his work brought, in these latter days.
In like manner, the national Covenant,
and League and Covenant,--which were the great idols of our invention,
for carrying on of these things,--the Lord had, these several years by-gone,
in a great measure +++[+++shaken;]
by this, testifying so eminently against them,
after solemn appealations,--likewise his so dividing
and renting them among themselves about them;--thereby,
as I suppose, very clearly calling to lay them by, as means not of his appointment,
but of their own invention, and that he would no more bless for carrying on +++[+++his work].

+++[+++Here, the manuscript once more breaks off:--the only remaining fragment of the Diary,
that was discovered, is as follows.]
...and exercising me with various and manifold dispensations,
both of mercy and judgment;--especially at such a time,
I should be thus assaulted and brought sometimes well near to the gates of hell;
so that hell itself should not be more terrible and loathsome to me,
than some fits of distemper and sad exercise,
that it pleased Him to permit me frequently to be under: +++[+++my desire was,]
that the Lord would show me, why it is thus, and what he would have me to do in this case.
To this purpose, was the desire of my soul laid out to him;
with expectation and some hope, that he will make way for my escape from this sad,
distressed, and miserable condition, or else enable me to bear it,
as becomes a soldier of Jesus Christ, with courage and confidence;
knowing that his grace is sufficient for me,
and that his strength is made perfect in weakness.

The 17th day of June, 1661, I received a line from my wife; wherein I perceived,
and was desiring much to pity, her confused and dark condition,
being nothing comforted and less edified by her letter.
As I could, I was desiring of the Lord on her behalf,
that she may be helped to improve the dispensation,
and saved from the sad stroke of being deprived of the right use of it,
which would look more sad and judgment-like than
anything she or I have ever yet met with.

The 18th day.
Having been, for many days, sadly exercised,
by reason of the abounding corruption of a carnal, light, and unstayed mind;
this morning, I found the Lord speaking to me, and telling me, that without him,
I could do nothing for the helping of myself out of this sad, deserted frame of spirit,
that now I am in, and have most frequently been under from my youth up unto this day;
which is shortly this:--Satan, and his suggestions and allurements to sin,
familiarly and frequently admitted into the heart, at his pleasure;
so that I could but very little, if at all, in any measure,
essay to resist him with success;--and, on the other hand, Christ,
and all He brings with him, kept at the door, without entry or entertainment,
though sometimes longed for and in some sort inquired after.
Now, I thought, the Lord`'s voice was to me this morning, that,
as He alone could help me, so his help was only to be found by me,
as his voice (being attended to) should be found speaking in the conscience;
and that all noises and voices else, speaking there, behooved to be silenced,
or his could not be heard.

For clearing up this truth, these particulars were thus made out to me; that there,
and only there, he is to be found effectually speaking to and determining every case,
and the cure of it.

He is to be seen in his works of creation, in his works of providence,
and by the judgments that he executes,
and in the Scriptures there is much of him to be
seen and learned by a diligent perusal of them;
but no life is to be found +++[+++merely]
by what may be learned from any or all of these.
"`Search the Scriptures;`"--that is a duty, "`for they testify of me,`" says Christ;
"`but you Must come to ME`" to get life,--your life is there,
even "`hid with Christ in God.`"
See John 5:39-40, and Col. 3:3. My life, then, being only to be found in Christ,
and no where else, in prayer, preaching, nor Scriptures;--where is he to be found?
Though Christ may be said to be, and truly is, everywhere, and everywhere to be found;
yet not to the particular end for which he is sought, namely,
for mortifying and subduing sin,--but as enthroned in the heart.
The Apostle, speaking to this same case, of a soul that is seeking,
and knows not where to find Christ, says,
He is nearer than you believe,--in your heart and in your mouth; so,
he is effectual only there, to do the business you desire.
Find him ever so much elsewhere,--if you find him not, nor observe him well there,
you will lose your honour;
your case will grow worse,--your wound will stink and become
more corrupt,--you will profit nothing by all your pains,
nor by all the dispensations you are under, either of mercy or correction.

But who, among professors, will not acknowledge all this, willingly?
and yet do find themselves still at a loss, as to their idol, in being kept from it;
or some corruption, that always has been predominant, or, it maybe,
is let loose only for a time against them, does yet master and vex them sore.
I find this to have been, and still to be my case; being ready, and very willing,
to acknowledge the necessity of giving Christ the heart, to have his throne there,
and to expect help for the subduing of corruption only from him;
and yet corruption remained, yes,
seemed to increase to more strength and vigour than before.
As the Lord may have many glorious ends,
why he thus exercises his children,--this is not my business now to speak to.
Although, among other things, I conceive, a special end of my present exercise is,
to draw and lead me on, not only to acknowledge that Christ ought to have the heart,
and to be willing to give it to him; yes, to pray him to come and take it,
and set up his throne in it,
and this to do with uprightness and much sincerity;--this length I came long since; but,
I see a necessity of making progress and advancing; or to remain,
without comfortable success, far short of hope of victory.

It is one thing, to be willing to receive Christ,
and to desire heartily that he would come; and another thing,
to know that he is there already.
I know it is the judgment of many, that Christ is in every one, etc.; but, sure I am,
that every believer has Christ in him, or else he is none of his, Rom. 8:9;
he also knows that he has Him, or he is not in an approved condition, 2 Cor. 13:5.
How sad, then, is it, that He should be there,
and so little taken notice of, as not to be known how he comes,
or what he says and does in the heart!`"
Surely the Lord is in this place; and I knew it not,`" said Jacob; so, surely, may I say,
Christ has been long in my heart sorely slighted and not observed.
O, for a heart to mourn for this! and to wonder at this patience and unchangeable love,
that yet is to be found when he is sought; and to count my affliction,
inward and outward, as a fatherly correction, (how sharp soever,) for my neglect,
and slighting so great salvation.
Lord! help me, that I do so no more.

Christ is in the heart, as he was in the world, but little known or observed; yes,
sometimes mocked and reproached.
Why? Because he came not then, nor comes now "`with observation.`"
And, as he came to Elijah, and was found to be where he was least to be looked for,
not in the stormy wind, the earthquake, nor the fire, but in the small, still voice;
so is Christ to be found in the heart, as a despised, little,
small thing,--a grain of seed,--as a word that you hear at a distance, behind you.
And, who takes notice of the like of that?
especially, when so great things are to be done, as Satan to be cast out,
and a hard heart made soft, wonders are then more ordinarily looked for.
But, O the wisdom of God! "`Hear,`" says he,
"`and your soul shall live`"--"`Look unto me, and be saved,`" Isa. 55:3, and 45:22.
Christ observed and listened unto,--that is all you have to do; anything more,
is so far from furthering, that it hinders your progress.
It is not of him that wills or runs, Rom. 9:16;
your "`strength is to sit still,`" Isa. 30:7.

There is something in the heart and conscience that reproves evil:
there is no need of proof for this, every one`'s experience tells him the truth of it;
if you will hear this check and reproof it gives to evil,
you will find also that it will stir up to good,
and encourage you to go on in the one way, and to flee from the other.
Now, believe and know for certain, This Is Christ; and this is the voice, that, he says,
his sheep hear and know, John 10:3-4; even this,
that has been so long slighted and neglected in the
conscience,--this so much baffled and slighted voice,
is that way +++[+++by which]
Christ speaks: HEAR HIM THUS, OR NOT AT ALL.
Christ`'s voice was thus, and no other way, heard,
while he was here upon earth in the body, wherever it was effectual for doing good.
The world could not understand his speech,
and he gives the reason of it in the next words,
"`Even because you cannot hear my word,`" says Christ, John 8:43.
He was speaking audibly to their ears, and yet he says,
they could not hear his word.

The truth of this may be somewhat more made out, by considering what the Apostle,
in Gal. 5:17, says, "`The flesh lusts against the Spirit,
and the Spirit against the flesh;`"--the one is no less than the very devil,
stirring up and acting towards the bringing forth the lusts of the flesh,
till they be finished in death, James 1:13, etc.;--and the other,
none else but Jesus Christ in the heart, stirring up,
and acting holiness and every good work.
How sensible are we of the one, that they tend to death; and yet how +++[+++at]
home and familiar are they with our hearts,--how easily received,
and admitted to abide there!
And, on the contrary, how are the lustings of the Spirit neglected!
If it were believed firmly, that Christ, or the devil, were admitted or rejected,
as these their messengers are; and that the strength and growth of corruption,
or the withering and decay of it,
depend upon the distinct observation and entertainment which these get,
in all their several motions and suggestions in the heart;
there would be other sort of advantage over corruption, and growth in grace,
than is now gained.
But such a tumult and noise is kept up in the heart,
by the ready access that Satan has in every of his suggestions; that,
what with tumultuous and incessant desires of some one idol lust or other,
or some one or other diversion from what is good, the mind is kept on,
in a hurry of confusion;--so, there is no room for Christ to enter.
Now, to have this tumult silenced, it is Himself must do it: "`Be silent, O all flesh,
before the Lord.`" Zech. 2:13.
So, in Matt. 9:25, when a miracle was to be performed,
the tumult must be removed; and when the people were put forth, he went in,
and the maid arose.
All flesh, as well the rational or reasoning part, as that which is more gross,
visibly and sensibly so, must be struck down.
For Christ, at his entry in your heart,
may receive no less opposition from the one than from the other;
for the wisdom of the natural man, as well as his more fleshly lustings,
is enmity against God;--it cannot be reconciled with him, but must give place,
or he will not come in.

And, having received him, keep him well; keep near to him, yes, in him; abide in him,
and let his words abide in you.
His words are not +++[+++merely]
as they are spoken in the Scriptures, or any other outward way only,
to the ear or eye of the body; but it is his words in you,
it is the hearing of them thus, as they are spoken in you,
that will be profitable for you and bring salvation.
The branch, by being in the Vine,
has sap flowing constantly to it from the root;--so will you feel that,
if you abide in Him; even as the woman, who felt virtue coming from Jesus.
The spirit has its senses, as well as the body; it feels, it handles, it tastes,
it touches, 1 John 1:1. But these spiritual senses are, for the most part,
benumbed and dead for lack of exercise.
When the eye of the mind is darkened, O how great is that darkness!
Matt. 6:22-23:--be, therefore, very careful to keep open this eye,
the light that is in you; as Christ there calls that, the eye of the mind;
which being kept open, all the body is full of light.

The 21st day.
I find the Lord saying to my heart, that it should be quiet,
and not repine or fret at his way of exercising me,
however bitter it be;--if it be more and more so,
I am not allowed to despond or be discouraged, seeing,
God gets more glory by sustaining me to strive against
such a case than he could do by my getting victory.
It will also be, in the end, more for my advantage; and while there,
he will be with me,--even in the fire and in the water--he is with me;
why then should I be dismayed?
The enemy, that is buffeting me, will be better buffeted, beleaguered, yes,
trampled upon shortly.
It is, then, a duty which I desire to essay,--to take courage, and be still;
and--as a dear friend said yesterday to me, The best way to discourage and render a mad,
furious enemy hopeless in his attempts,
is to slight and neglect him as absurd and vile,--yes, to abhor being a servant of sin.

That day,
finding some easier access to meet with Mr. Robert
Macquare,--(he having been kept close prisoner,
since his libel was found proved, and he guilty of treason)--but, this day,
having found access to him, I was speaking something of my thoughts to him,
in relation to these times,
and the guiltiness that the Lord may be pursuing his people for, in this day.
And having, in some sort, made way for it, I told him, at last, that I had a paper,
which did more fully contain my thoughts, both as to the matter of guilt and of duty.
This paper, I left with him to be read; and he promised, that neither the paper,
nor what was in it, should be communicated to any.
He only told me, that he could not promise so speedily to peruse it,
seeing he was preparing some papers for the scaffold.
Whereupon, I was fearing, it may meet with the like success with him,
as with Mr. James Guthrie, to whom another copy of it was sent for the same end.
But he, being advertised, that the Parliament was to be about his sentence very shortly,
had no time to peruse the same; +++[+++see Appendix, OO.]
I was desiring, that it may be otherwise ordered with this good man;
and that he may receive what truth there is in it, without prejudice or passion.
And, if any error or mistake, upon my part, be in it, that the Lord may be pleased,
to make him an instrument to discover the same to me, and help me; that I may not,
through weakness or willfulness, refuse to take out what is wrong,
when so it shall be made out to be; and if otherwise, what truth there is in it,
I may be more and more confirmed and established therein.

The 26th, I went to visit the prisoners in the Tolbooth.
And first, I went to Mr. Robert Macquare; who,
after some discourse of the paper I had left with him,
evidencing his great dissatisfaction thereat, delivered it to me,
and declined to reason with me in it; but desired, that none other should see it,
and said, he hoped I was not fixed in the matter of it.

I told him, that none had seen it, but Mr. James Guthrie and he;
and as for my judgment and fixedness thereabout, I told him,
that it had been my judgment, now, for many years.
Yet was I very willing to hear from him or any other, what could be said against it.
Some further discourse of this kind having passed, I came away.

The 27th day, I sent the said paper to Mr. Andrew Cant, Junior, at Liberton,
desiring him to consider of it, and give me his judgment thereupon.

The last day of June, being a sabbath, I having been, for many days before,
under a sad piece of exercise, by reason of the unmortifiedness of my heart,
two Scriptures, also some others, were that day, and the next morning very early,
brought to my mind and opened to me; so that I had good ground given me to hope,
that as the exercise of his servants Hezekiah and Paul, (see 2 Chron. 32:25-26,
and 2 Cor. 12:7-8) might have been somewhat like unto mine;
the mind of the Lord may be, in his mercy, to give the like blessed outcome and event,
as he did to them, his grace being as free and sufficient for me as for them.
+++[+++A third Scripture, Alexander Jaffray then adduces, Jer. 2:19-20,
as applicable to his own condition; and concludes,
that the first rise and approaches of sin, should have been more watched against,
and in the true fear of God, resisted and denied, etc.]

In the end of that evening, the last of June, and in the morning of the 1st of July,
these truths were sealed unto my heart.--Lord! help me to walk humbly and soberly,
under the sharp, and yet more bitter, and furious assaults of the enemy;
which I am to expect daily, and rather to be increased, than lessened.

And, in order to a desire, put up for direction in this case,
I fell to read that excellent place, Rom. 12:2, "`Be not conformed to this world;
but be transformed by the renewing of your mind, that you may prove what is that good,
and acceptable, and perfect will of God.`"
"`All that is in the world,`" says the Apostle, 1 John 2:16, "`the lust of the flesh,
and the lust of the eyes, and the pride of life, is not of the Father,
but is of the world;`"--no conformity to the world in any of these,
or in things leading to them;--there`'s much in that.
The mind is to be renewed, so as even to have it transformed.
Old things, then, pass away,--all things, to such, become new; new knowledge +++[+++also,--for]
they know more, and in another manner than before.
These new creatures know what the "`new commandment`" means, and in what sense it is new.
Their love is not now bounded by an external, outward conformity, which, some time,
was its snare to seek after; and beyond which, ordinarily, its love did not exceed,
at least, in the manifestation of it; but now,
it is enlarged far beyond that,--if an inward conformity may be
hoped for:--wherever the Father`'s image in any measure appears,
there it is one, or desires to be so.

+++[+++A little further on, under the date of the "`3rd of July,
1661,`" our Author speaks of the danger of resting in a form,
without the life and power of godliness;
where the heart is apprehensive of being emptied of filthiness and pollutions,
and excellently garnished with all duties, (see Isa. 58:2,
compared with Mark 6:20) there may be "`great danger of much
disease,`" "`in setting up duties in the place of Christ.`"]
For, +++[+++he continues,]
their comforts and peace now flow, for the most part, if not wholly,
from this frequency and diligence in duties; to which they look,
more than to the life and power in which they are done.
And so are they satisfied with, and apt to contend most for the form,
+++[+++and appear to be endeavouring,]
in their activity, to be saviours to themselves.
So unwilling is the enemy of their souls to let them go further on,
to come to Christ:--as He said to the Jews in a similar case, John 5:39-40,
"`Search the Scriptures; for in them you think you have eternal life;
and they are they which testify of me; and (observe it) you will not come unto me,
that you might have life.`"
Life is not to be found,--no, not in the Scriptures;
(which may comprehend all other duties of that kind,)
though ever so diligently made use of;
Christ himself must be come to, for that which no where else is to be found.
It is well for those that are thus set to seek, and are kept seeking,
until they know where to find Him,--even in their heart and mouth, Rom. 10:8;
and thus get grace, to give up themselves closely to wait upon and follow him here.
Then their out-get will be easy;
for his "`yoke is`" truly "`easy and his burden light,`" when, in this way,
we begin to be helped to take it upon us.

But, being by this digression drawn off from the particular of this day`'s experience,
to which I was to speak, I shall say a word to it shortly, as follows.

That, among other occasions, when Satan is most busy to assault the believer, it is,
ordinarily, when they have been most seeking after,
or have attained to any nearness in communion with God; then,
they may be sure he will make them, if he can, to abuse that mercy.
And so did I find in my experience;--though I can say but little of any access that then,
or at any time, I ever had; yet,
blessed be the Lord! for the hope that was given to get more;
to deprive me of which the enemy has been very busy.
O! by what wanderings and diversions,
has he been endeavouring to get the heart to its old bias again,
to pore upon either sinful, vain, or unprofitable thoughts; knowing,
that life from Christ, the Fountain of it, is ordinarily conveyed into the heart,
when He is made use of for keeping out of these.
Then comes He in, (the soul having patiently waited for him,) like a mighty speat,
+++[+++inundation,]
with free love overrunning all the banks that formerly stood in his way,
and carrying them all down before him,--the mountains flow down at his presence. Isa. 64:1.
O! then, the creature thinks, its waiting on him well +++[+++bestowed,]
and begins to feel its work to be easy; for,
whatever were the former apparently insuperable difficulties,
now it sees through and finds an out-get from them all.
Not as if there were now any such thing, either promised or expected,
as immunity from assaults, or freedom from hazard of falling,
either into sin or judgment for it.
No; the heart is now more in expectation of the one,
and in true fear and dread of the other, than ever.
For Satan, who was but angry before,
comes now in full fury to set himself and all his instruments.
+++[+++Thus in hazard of being mastered, the soul]
was never so on his watch, as now he desires to be; knowing,
that the very being and preservation of his life, depends entirely upon his being near,
and keeping close to Christ; who is the Fountain of life, and from whom,
+++[+++as the Psalmist says,] 87:7; all his springs do flow.
"`My soul follows hard after you,`" Ps. 63:8;--the soul can now be at no quiet,
but as and when it finds its refreshments,
every moment flowing out from the streams of this, the true Fountain of living waters;
as the Prophet says, in the name of the Lord, "`I will water it every moment,`" etc.
Isa. 27:3; and see Jer. 2:12-13. For now he knows,
that he has this Fountain in himself, as "`a well of water,
springing up into everlasting life,`" John 4:14; so he desires never to rest,
but to be drawing and drinking "`abundantly.`" Canticles. 5:1.

Some thoughts of this kind, having been very sweet to me this morning,
I was desiring to know of the Lord,
what course might be most suitable and conformable to his blessed will,
for +++[+++enabling me,]
in keeping near and close to him.
My +++[+++heart]
did most conclude, as follows:--With his grace and help, by which alone I stand,
to endeavour to keep close to Christ, the true Light,
as he enlightens himself forth in the conscience; and in his strength to honour,
to shut and keep out every sinful, vain, unprofitable thought,
so as to get and keep in holy, wholesome,
and good thoughts;--while I find the truth of what Paul experienced in this way,
2 Cor. 10:5, by managing rightly the weapons of our Christian warfare,
to bring every thought into subjection and obedience to Christ.
So likewise,
for words and actions,--to endeavour to have a warrant
for every one of them;--when to speak,
or what to do;--when to go abroad, or keep within:--+++[+++in this way]
to see and know my Guide,--even He who was my Guide of old, in my youth,
when I followed him in a wilderness, in a land that was not sown, Jer. 2:2.
--And shall I not from this time cry unto him,
"`My Father! you are the Guide of my youth!`"
Jer. 3:4; and shall I be as one, "`which forsakes the Guide of her youth,
and forgets the covenant of her God!`" Prov. 2:17.
Thus, may I see and behold him,
so as even to say or do nothing without him,

+++[+++and--may it not be added--by "`beholding as in a glass
the glory of the Lord,`" be "`changed into the same image,
from glory to glory, even as by the Spirit of the Lord.`"
"`Now the Lord is that Spirit;
and where the Spirit of the Lord is, there is liberty.`"] 2 Cor. 3:17-18.

End of the Diary.

[.asterism]
'''
