== Appendix of Notes and Illustrations to the Diary.

=== Note A.

It does not very clearly appear,
at what precise period Alexander Jaffray commenced his narrative.
From the allusion that is made in the preceding paragraph,
to his views on the constitution and government of the church,
as well as from that passage respecting his age, it is evident,
the date of its first production must have been subsequent to 1654.
Other circumstances, however, incline the Author of these Notes,
to place the earliest insertion as late as 1656.

In a future Note, some further remark will be made,
on the retrospective form of this part of the Diary.

=== Note B.

This Robert Burnet was the father of Bishop Burnet,
and married a sister of the Lord Warristoun,
who is several times named by our Author in future pages of his Diary.
In Row`'s Supplement to Blair`'s Life,
a MS. in the Library of the Writers to the Signet at Edinburgh,
he is mentioned as being "`both a good man and a
good advocate;`" and in Nicoll`'s Diary of Occurrences,
a MS. in the Advocate`'s Library there, he is termed, "`a very good honest,
and religious Christian.`"
After the Restoration, he was made a judge in the Court of Session,
by the title of Lord Crimond.
The preface to Burnet`'s History of his own Times, represents him,
agreeably to Jaffray`'s description,
as "`so remarkable for his strict and exemplary life,
that he was generally called a Puritan.`"

According to the same testimony, "`he was the younger brother of a family,
very considerable for its authority as well as interest in the
shire of Aberdeen;`" his father being Alexander Burnet of Leys.
See Dougl.
Baronage, 42. The reader, as he proceeds, will find, that in 1645, Alexander Jaffray,
with his father, took up their abode for a time with their "`cousin,
Alexander Burnet the elder.`"
Now, the maiden name of Jaffray`'s grandmother was Christian Burnet,
and she is described in the genealogy of the family,
as daughter to the then proprietor of Leys.
Burnet, in the Diary, and in some other documents, is uniformly spelt with one "`t`",
which, however, does not appear to be the correct mode.--That the Burnetts,
who are mentioned in the succeeding Memoirs, as being of the Society of Friends,
were connected with the above family, is not distinctly ascertained.

=== Note C.

"`In the year 1633,`" says Bishop Burnett, in the History of his own Times,
"`the King +++[+++Charles the 1st.]
came down in person to be crowned.
His entry and coronation were managed with such magnificence,
that the country suffered much by it: all was entertainment and show.`"
Spalding, in his History of the Troubles, etc., edit.
1830, p. 14, gives a particular account of each day`'s banqueting and ceremony.

=== Note D.

George Jamieson is named in Kennedy`'s Annals of Aberdeen as "`an eminent portrait
painter,`" who also "`not infrequently applied his talent to history,
landscape, and miniature.`"
He was employed by the magistrates of Edinburgh to make paintings of the Scottish monarchs;
and in 1633, King Charles, when there on the occasion of his coronation,
sat to him for his portrait.
Vol. i. p. 268.

=== Note E.

The Editor has been wholly at a loss to English the
expressions made use of in this place;
although he has examined a glossary of Scottish phrases.--He was equally unable,
even to decipher, with any certainty,
two or three words towards the close of the preceding paragraph,
where the hiatus is denoted: as nearly as could be made out,
they are these,--"`and made some waring of wattglen or thereby.`"
But a clue has occurred, while looking over the Annals of Aberdeen,
from which it may be conjectured, that he alludes to some woollen goods,
or other description of manufacture.--"`In the year 1636,`" that is,
two years after the time we are now arrived at in the Diary, our Author being,
as we shall see, provost or chief magistrate of Aberdeen,
"`the magistrates obtained from King Charles the
1st. a patent for establishing a house of correction;
chiefly with the view of reforming the morals,
and of promoting good order and industry among a certain description of the inhabitants,
who were to be employed in manufacturing broadcloths, kerseys, says,
and other coarse cloths.`"
"`The manufacture of cloths was carried on in the house
of correction for several years by a joint stock company,
to a pretty considerable extent.`"
Annals,
etc. vol. i. p. 257. Connecting the circumstance
of Jaffray`'s going by Leeds and Wakefield to London,
and his notice of the Yorkshire cloths, with his expressions above,
there is little doubt,
but that he was a chief promoter of this undertaking
for bettering the condition of the poor,
whether interested on his own account, or not, in any concern of a similar description.

=== Note F.

This affair is related in Spalding`'s History of the Troubles,
etc. p. 336.--"`Upon Saturday, the 1st of July, +++[+++1643,]
Sir George Gordon of Haddo unhappily hurt Alexander Jaffray, late bailie,
and John Jaffray their father, +++[+++or rather his brother]
at Broomend, in coming frae the good-man of Brakay`'s burial; because the said A. J.,
being a bailie, had caused ward the said George`'s servant, for hurting another fellow.
This was no just quarrel, to pursue a judge for doing justice.`"
And further, at p. 342, "`You heard before,
how the Laird of Haddo hurt A. J. and J. J. They go over with their father,
recommended by the burrow of Aberdeen to the burrows of Scotland,
and makes them all their friends; and raises letters,
charging Haddo to appear before the council, justice,
or Commissioners of Estates at Edinburgh, the 2nd day of August,
to answer at the instance of the said complainers,
and of the King`'s advocate for his interest.--Wherefore he is fined in 20,000 merks,
whereof 5000 to the complainers, and 15,000 to the public.`"
// lint-disable invalid-characters "½"
The merk, Scots money, being 1s 1½d+++.+++, makes the fine £1,125 sterling.

=== Note G.

This aggression of Haddo, with the date of its occurrence,
is particularly noticed by Spalding.--"`Upon Tuesday, the 19th of March, +++[+++1644,]
the young Laird of Drum, Robert Irvine, his brother, the Lairds of Haddo, Gight,
etc. with some others, about the number of sixty horse, about seven hours in the morning,
came galloping through the Old town to New Aberdeen; and suddenly took provost Lesly,
Mr. Robert Farquhar, and Alexander Jaffray, late bailies, and John Jaffray,
dean of guild, his brother, out of their houses,
and had them to skipper Anderson`'s house.
It was said, there was plundered out of Alexander Jaffray`'s house,
some gold rings and chains, but gat little money; they mist Mr. Alexander Jaffray,
+++[+++the father,]
for he was not in town.
Surely, it is to be marked, the like seldom has been seen, that so few men,
so pertly and publicly, should have disgraced such a brave burrow,
by taking away their provost and the rest, men of note,
without any kind of contradiction or obstacle.`"
History of the Troubles, etc. p. 384. See also Baillie`'s Letters and Journals.
The above writer adds, that "`the Marquis +++[+++of Huntly]
left the four captives at Strathboggie,
who were transported therefore to Aucbindown upon the 2nd of April.`"
No sooner had Huntly`'s party evacuated Aberdeen, than it was entered,
according to Spalding, p. 405, "`on the 2nd of May,`" by the army of the Covenanters,
which consisted of 6000 horse and foot, together with the Marquis of Argyle,
the Earl Marischall, the Lord Burleigh, and other noblemen.

With respect to Jaffray being a Covenanter, it is concluded,
that he took the Covenant in 1638,
when his father and others of the inhabitants of Aberdeen subscribed it;
being urged to that measure by the Commissioners for the Covenanters, who,
according to Spalding, came to Aberdeen "`on the 20th of July.`"

=== Note H.

It will be proper,
briefly to furnish some information respecting the parties
and circumstances alluded to in this paragraph and the preceding
one.--The real name of Alester Macdonald was Alexander,
but he was indiscriminately called Alexander, Allester, and Alcester.
Bishop Burnet thus explains this affair of the Macdonalds.
'``' A great body of the Macdonalds, commanded by one Colonel Killoch,
came over from Ireland to recover Kintire, the best country of all the Highlands,
out of which they had been driven by the Argyle family,
who had possessed their country about fifty years.`"
Montrose, who, at the commencement of these civil commotions,
had been greatly attached to the interest of the Covenanters,
now devoted himself to the cause of the King.
In the encounter of Macdonald and Montrose with the Lord Burleigh,
which took place on the 13th of the month called September, the latter was defeated,
the town was pillaged, and, as the Diary correctly states,
160 of the inhabitants were massacred.
Immediately after this, Burleigh`'s shattered force was joined by Argyle,
so that Montrose did not retain his position at Aberdeen;
and this may account for Jaffray`'s expression,
that he could not well stay there;--the place was yet in the hands of his friends,
but it had been successively taken and retaken by opposite parties,
so that in that spot there was no safe abiding.
See Kennedy`'s Annals of Aberdeen; also Spalding, p. 447.

Dunotter, or Dunnotter Castle, now in ruins, is situated on a lofty perpendicular rock,
almost surrounded by the sea, a little to the south of Stonehaven.
It belonged to the Earl Marischall:--so did also the estate of Ury, not far from there,
and well known to the Society of Friends,
as having since been in the possession of the Barclay family; Colonel David,
the father of their "`Apologist,`" having about this time purchased it of the Earl.
Thorns, in his History of Aberdeen, relates, that the Earl,
with sixteen Covenanting ministers and others, had taken refuge in Dunotter,
while Montrose, with his Highland clan, ravaged the country;
and that the latter wrote a letter to him, requesting him to support the royal cause,
but that Marischall, counselled by Andrew Cant,
one of the chief ministers among the Covenanters, refused to comply.
Vol. i. p. 321.

With regard to Haddo`'s death,
Balfour`'s Annals conveys the decision of the Parliament on his trial:
so far as applies to that part of his accusation, in which the Jaffrays were concerned,
it is as follows.
"`July 10th, 1644.--The taking of Patrick Lesley, provost of Aberdeen,
Mr. Robert Farquhar, commissary for the public, bailie Jaffray, and his brother,
the dean of guild, and putting them in private prison in the castle of Auchindowne,
and detaining them therein, they being the King`'s free leidges,
and public persons--Whether this crime be punishable be death, treason,
or arbitrament of the Parliament?
This being putt to the voices of the house, it was found by plurality of voices,
that this crime is capital, and punishable be the pain of death.`" Vol, iii. p. 213.

=== Note I.

In the Parliamentary Records of Scotland, under the date of "`the 19th of February,
1649,`" is "`the supplication of Forbes of Leslie, Alexander Jaffray, bailie of Aberdeen,
Andrew Cant,`" and others, that they may not be censured,
for having burned "`the house of Pitcaple, in the month of September,
1645,`" and the report of the Committee of Parliament thereon; and a vote is passed,
that "`they deserve the approbation of the Parliament.`"
The petition states, that "`the Lord, in the very neck of time,
furnished us unexpected and wonderful deliverance,
by sending to our assistance the Master of Forbes, Lord Fraser, the Lairdis of Skene,
Monymusk, Echt, Leslie the younger, etc.`"--The name Fraser, in the Public Records,
is written promiscuously, Fraser, Frazer, Fraiser, Frissil, Frizell.
"`Lord Fraser`" is occasionally styled "`Lord Frizell.`"

=== Note J.

On an examination of the Acts and Minutes of the Scottish Parliament,
at the date of the 3rd of the month called February, 1646,
Alexander Jaffray is found to be one of "`a Commission
for Proceedings against Malignants and Delinquents.`"
According to Balfour`'s Annals, this was a Committee for "`Fines, Processes,
and Excise.`"--Although he notices thus cursorily
his being a member of Parliament in 1646,
and again, at a future page, in 1649; yet, by the Acts and Minutes, it would seem,
that he also stood in that character in 1644 and 1648.
The following are some of the occasions upon which
his name appears in the Parliamentary Records,
as being on committees or otherwise;
but which are wholly passed over by Jaffray in his Diary.

1644, 5th month,
(July) 19th. He is nominated with others a Commissioner for Suppressing the Rebellion,
which was put down by Argyle.

24th. On a Committee of War for the county of Aberdeen.
1646, 12th mo: 2nd. On a similar appointment.

1648, 2nd mo: 18th. On a similar appointment.

1649, 11th mo: 5th. On the Committee of Burgesses, or Commons,
for Dispatches and Public Affairs.
(note.
The Lords and Burgesses sat in the same house.)

12th. Appointed, with Robert Barclay,
(no description given of R. B.,) on behalf of the Burgesses, on a Committee.

12th mo: 14th. Joins in a Report to Parliament, on a Petition of the Earl of Sutherland.

15th. On a General Committee for putting the kingdom in a posture of defence.

1st mo: 14th, 1650.
On the Committee of Estates

15th. On the Commission for Plantation of Kirks; and a Commissioner of Exchequer.

16th. Is added to the Committee on Dispatches; also on Valuations.

26th. On a Committee, to report on the most effectual way of paying the troops,
and gratuities to wounded soldiers.

5th mo: 31st. On a Commission for visiting the College at Aberdeen.

6th mo: 7th. On the Committee of Estates.

5th mo: 4th. Along with the Earls of Cassilis, Buccleugh, Lothian, the Lairds Brodie,
Libertoun, and others, "`to repair to his Majesty,
and congratulate him on his happy arrival in this kingdom.`"

During the course of this chapter, as in others,
our Diarist enters rather at large on some circumstances in which he was engaged,
and especially on the progress of his mind,
in relation to subjects deeply interesting to him;
while he forbears to lay out to view the part he took in some other public events,
where these have no immediate application to his spiritual career.
Such omissions, of even important transactions of his life,
may have in part arisen from the professed design of the Diary,
which is purely religious; but, it is believed,
they are also in some degree attributable to the Writer`'s unusually humble
views and feelings.--One circumstance wholly passed over at this period,
is the following.
In 1651, Alexander Jaffray was provost or mayor of Aberdeen; and,
in the course of that year, according to the records of the town Council,
was deputed a Commissioner to General Monk at Dundee
"`concerning certain important matters.`"
What these matters were, the town Records do not state; but,
in Kennedy`'s Annals of Aberdeen,
the most probable explanation of one of these affairs occurs.
That place surrendered at discretion to the army of General Monk, as this author relates,
"`on the 7th of September,`" when the English took possession of the town.
They immediately imposed upon the citizens a contribution of £12,000. A representation,
however being made "`to General Monk by a deputation of the citizens,
of the various hardships which they had suffered during the civil wars,
and of the distress occasioned by the pestilence, which had lately infested the town,
he was pleased to suspend the exaction of the money.`"
Vol. i. p. 228.

=== Note K.

Alexander Jaffray`'s father may here be briefly spoken of,
as having been provost of Aberdeen, also a member of the Scottish Parliament,
and of the Committee of Estates; a Commissioner, likewise,
on one occasion to the General Assembly of the Church of Scotland.
Spalding, who evidently is not partial to him, notices that, in 1645,
"`he departed this life in New Aberdeen; a rigorous Covenanter.`"

=== Note L.

"`The plague, which had existed in the southern districts of Scotland for two years,
broke out in Aberdeen about the 1st of June, 1647,
and continued its ravages till almost the end of October.
The election of the magistrates this year, was held at Gilcomston,
on account of the pestilence, which cut off in Aberdeen 1600 of the inhabitants.`"
Thorns`' History, vol. i. p. 330.
According to Kennedy,
the population may be computed to have then stood at 9000.--Jaffray
is conjectured to have been at that time a bailie or magistrate,
not the provost or mayor.
He repeatedly filled both these offices; his name appearing as provost in the years 1636,
1639, 1642, 1649, and 1651; and as bailie in 1634, 1641, 1643, 1645, and 1648.
There is, however, some difficulty in precisely fixing the dates,
as the election took place in the latter part of each year for the ensuing.
This must account for the discrepancy between Spalding`'s statement,
and that which has been obligingly furnished the Editor, by James Hardie,
the city chamberlain of Aberdeen, from the Records of the town Council.
The name of Jaffray`'s father being likewise Alexander,
this circumstance should probably strike off the
two first years of his nomination to each office,
as belonging, it is supposed, to the father rather than the son,
who would be only twenty years of age in 1634.--In the year 1648,
he was deputed to repair to Edinburgh,
to confer with the Committee of Estates about the mode of election of the provost.
Annals of Aberdeen, vol. i. p. 243.

=== Note M.

Thus modestly, no scantily, does our humble-minded,
amiable Author narrate the matter of fact respecting his important appointment,
at two distinct periods,
as a delegate from the Parliament of Scotland to King Charles the 2nd; attended,
as such a negotiation must have been,
with circumstances of difficult and critical adjustment.
Under whatever veil of delusion, or of deficiency,
we suppose him at that period to be partially disguised, doubtless,
it would have been interesting, to have viewed the man, as a religious character,
in his interactions with his colleagues on such a business,
and much more so on the occasion of interviews with their exiled Monarch;
especially as the space of time embraced by each
of these engagements was nearly three months.
But while regretting the loss we sustain, both by a chasm in this part of the Diary,
as well as by the summary glance which is taken of this transaction of Jaffray`'s life,
let us not omit to mark,--amidst his reflections upon it
as a political event,--how liberal he is in self-condemnation.
Nor does he spare to animadvert with freedom on what he
considered to be the carnal policy and contrivances of others;
yet, through all, his heart is not obstructed from rising into grateful admiration,
at that powerful and pitiful Hand, who in all that He permits or dispenses,
is willing to overrule every occurrence to the good
of those who truly humble themselves before Him.

It will not be thought, either assuming the character of historian,
to which indeed the Editor lays no claim,
or assigning to the reader any lack of acquaintance with this portion of Scottish affairs,
if he attempts, from such authorities as have been met with,
to bring together some information relative to this treaty; which,
as it does not form part of Jaffray`'s own recital, may add some interest to his subject.
Before, however, expressly adverting to that point,
a strong testimony may here be adduced in favour of his public-spirited character,
evinced towards the place he represented in Parliament,
on the occasion of being called upon to join in this national embassy:
it is conveyed in a publication, entitled,
"`Memorials for the Government of the Royal Burghs of Scotland;
with some overtures laid before the nobility and
gentry of the several shires in this kingdom, etc.
By a Lover of the public welfare.
Aberdeen, 1685.`"

"`The Parliament made choice of Alexander Jaffray of Kings wells,
Commissioner for Aberdeen, who was a very wise, pious, and discreet man all his time,
to be one of the burrowes to go over to Holland to the King.
And he, to be faithful to the city he had his commission from,
entreated the Parliament to consider the most important article in his commission,
that so he might undertake that weighty employment with the greater alacrity; which was,
to visit the counts of the extraordinary loss of Aberdeen relating to the people.
The Parliament had that respect to him, and was so desirous to grant his so just demand,
that forthwith they did depute some fit members; who, after hearing and considering,
made their report; and thereupon, the Parliament by an Act did acknowledge themselves,
as the representatives of the nation,
to be justly resting to the city of Aberdeen the sum of
nine hundred three score and nine thousand merks,
+++[+++upwards of £56,000 sterling]
and did grant the cess of the city to be allowed to them
for as many months as drew to eighteen thousand merks;
because this great sum that was due to them,
had exhausted the sums of money that were mortified to hospitals, schools, the college,
and the common poor of that city, and had ruined almost the common thesaurie thereof.
But this was all they could spare at that time,
till an opportunity might fall out to make them more full payment;
which hitherto has ever failed, and has been the cause of the several heavy,
burdensome taxations, that have of late years been laid on.
Our above-mentioned Commissioner obtained, also, an Act of Parliament,
that no soldier should be quartered in Aberdeen for three years thereafter:
such was the great respect the Parliament had to him.
Whereupon,
he went to the King with the rest of the Commissioners
of the three Estates.`"--The same author states,
that "`when he was Commissioner to the Convention of burrowes at Queensferry,
Jaffray obtained half a merk down of Aberdeen`'s
proportion of the one hundred pounds of stent roll,
which was a great advantage to the city.`"--But to return.

In addition to the four Commissioners mentioned by Jaffray, including himself,
who were deputed by the Scottish Parliament in 1649 to treat with the King, Godwin,
in his History of the Commonwealth, numbers one other,
besides three appointed by the General Assembly of the Church of Scotland;
and he refers to Balfour as his authority.
Lamont, in his Diary, p. 2, speaks only of two for the Church, "`namely, Mr. James Wood,
minister of St. Androus, and Mr. Robert Baillie, minister of Glascowe.`"
They "`shipped in,`" he continues, "`at Kirkekaldie in Jhon Gillespie`'s ship,
and loused on Saturday the 17th of March at night:
they returned to this kingdom the 11th of June, 1649,
much unsatisfied.`"--With regard to those who were Commissioners in 1650, Whitelocke,
in his Memorials, p. 444, takes notice, that "`six Lords, two gentlemen,
and three ministers, were to go to Breda with new propositions to the King.`"
Godwin, quoting the same authority as before, says,
"`The Commissioners that were sent were Cassils and Lothian for the Peers,
with two for the barons, two for the boroughs, and three for the church;
and they sailed from Scotland on the 9th of March.`" Vol. iii. p. 208.
Again, Lamont mentions but two ministers, James Wood and "`Thomas Levistone.`"
Thus do these authors differ from each other.

It will not be deviating from the scope of these annotations,
to insert an extract or two from the Journal of the last individual,
while engaged on this business; Jaffray being particularly alluded to by him.
The Editor obtained access to this small volume at the Library of the British Museum,
the purport of its title being, The Life of John +++[+++not Thomas]
Livingstone.--"`When I considered,`" says the writer,
"`the Commissioners sent by the State,
I was not willing to embark in any business with them.
Cassels, Brodie, and A. Jaffray, I had no exception against; the other three +++[+++Lothian,
George Wynram, styled, the Laird Libertoun, and Sir John Smith,]
I suspected, would be ready to condescend to an agreement upon unsafe terms.`" p. 39.
Again, at p. 43, "`None of us three ministers ever went to the King alone,
but often all together, or at least two of us.
We went seldom, but whenever we went, we had access and liberty to stay,
and speak so long as we pleased.
We often urged, that if the King had any scruples against the Covenant,
or any of the parts of uniformity, or desires of the treaty,
that he would impart them to us: but he never propounded any such thing.`"
Jaffray and Brodie, it appears, often united in sentiment,
in opposition to that of Lothian, Libertoun, and Smith,
"`who ordinarily agreed in one voice, and that, sometimes,
such as some of us were not well pleased with.`" p. 42.
One more passage, relative to their departure, will suffice.
"`Brodie, Jaffray, and we three ministers stayed on shore,
after the other Commissioners went on board, and hesitated to go at all,
seeing the King had those about him in the vessel,
whom the Parliament had objected should not accompany him.
Brodie and A. Jaffray said, it were to have been wished that they had stayed ashore;
but now as matters stood, it was best to go aboard,
and discharge their trust in the last instructions from the Parliament.`" p. 48.
--The only observation which the Editor would hazard upon the foregoing statements,
is, the mere conjecture that the three individuals,
against whom Livingstone had no exception, were men of sincere, however mistaken, views;
each, perhaps, meriting a share in that language,
which Bishop Burnet applies to one of them,
the Earl of Cassilis,--"`a man of great virtue and
of a considerable degree of good understanding;
he was so sincere, that he would allow no man to take his word,
in any other sense than as he meant them:
he adhered firmly to his instructions +++[+++as Commissioner]
but with much candour.`"
They appear to have found more points of union among themselves than with the rest,
and accordingly consorted together; Jaffray, in another part of his Diary,
expressing particular and pious interest on the behalf of his friend, "`that worthy man,
the Laird Brodie.`"
Yet he also tells us, he found it safe,
not too implicitly to trust or follow even such as these.

Some readers may wish to have placed before them,
the conditions on which the treaty with the King stood.
They are thus given by Neale, in the History of the Puritans.
"`First, That all persons excommunicated by the Kirk, should be forbid the court.
Second, That the King by his solemn oath, and under his hand and seal,
declare his allowance of the Covenant.
Third, That he confirm those Acts of Parliament, which enjoin the Covenant.
That he establish the Presbyterian worship and discipline, and swear never to oppose,
or endeavour to alter them.
Fourth, That all civil matters be determined by Parliament,
and all ecclesiastical affairs by the Kirk.
Fifth, That his Majesty ratify all that has been done in
the Parliament of Scotland in some late sessions,
and sign the Covenant upon his arrival in that kingdom,
if the Kirk desired it.`"--"`The King arrived in Scotland June 23rd,`" continues Neale;
"`but, before his landing, the Commissioners insisted upon his signing the Covenant,
and upon his parting with all his old counsellors;
which he did.`"--It is not needful to insert the Covenant at full length;
but the tenor of it,
is thus set forth by the author of the "`Hind let loose,`" p. 65. It imported,
and required of subscribers, "`their sincere and constant endeavours,
in their several places and callings,
for the preservation of the uniformity in reformation, in doctrine, worship, discipline,
and government; the extirpation of Popery, Prelacy, error, and profanity;
the preservation of the rights and liberties of the people,
and of the magistrate`'s authority, in the defence of the true religion and liberty;
the discovery and punishment of incendiaries;
the retaining of the peace and union of the kingdoms;
the mutual assistance and defence of all under the bond of this Covenant,
and the performing all duties we owe to God,
in the amendment of our lives and walking exemplary one before another.`"

The day after his arrival, the King was conveyed to Aberdeen,
where "`he was lodged in a merchant`'s house opposite the Tolbooth,`"
as appears by a very particular account of his landing and reception,
given in "`Historical Discourses, etc. by Sir Edward Walker.`"
A letter is recorded in the Council register of Aberdeen, vol.
53, signed by Jaffray and his fellow-commissioners at this juncture,
and addressed to the magistrates, as follows.

"`Worshipful and good Friends,

"`We have directed these to let you know, that the King is safely arrived, and intends,
if God permits, to be at Aberdeen on Thursday at night;
therefore you will take such care to provide such lodgings for him,
and for the Commissioners, and for the train,
as may be best had on so short advertisement.
And we beseech you,
let nothing be lacking which may testify your affection to the native King,
who has fully assured all the desire of his people.
No further, but we are your very assured friends,

Cassillis, J. Brodie, J. Smith, Lothiane, George Wynram, Al. Jaffray.

Speymouth, 23rd June, 1650.

The only remaining document to be laid before the reader,
connected with and winding up the whole subject of these observations,
is the following "`Act of approbation of the Commissioners,
their faithfulness and diligence in their commission.`"
It is taken from a tract,
which the Editor met with at the Library of the London Institution, entitled,
"`The proceedings of the Commissioners of the Church and Kingdom of Scotland,
with his Majesty at the Hague; and the papers interchanged between his Majesty and them,
as they were reported in Parliament and the General Assembly.
Appointed by authority to be published, 1649.`"
There is also another tract,
with a similar "`Act of Approbation of the Commissioners,`" etc., dated 1650;
its title running "`Some Passages in the Parliament of Scotland,`" etc.

"`At Edinburgh, the 14th day of June, 1649.
The Estates of Parliament, now presently convened,
in the third session of this second triennial Parliament,
having received from John Earl of Cassils, Alexander Brodie of that ilk,
Master George Winrame of Libbertoun, and Alexander Jaffray, burges of Aberdeen,
their Commissioners sent to the King`'s Majesty,
the report of all their proceedings with the King,
and read the papers delivered therewith to this Parliament;
and being fully satisfied with their integrity, faithfulness, and diligence,
in contributing their utmost endeavours for prosecuting their instructions,
and for obtaining satisfaction to the desires of this kingdom;
do therefore unanimously and heartily acknowledge their faithfulness and diligence,
and approve their proceedings,
and render to them the hearty thanks of this kingdom for the same.

Sic subscribitur,

Arch.
Johnstoun.

=== Note N.

In a tract, "`printed in London, September 9th,
1650,`" containing "`An Official Account of the Battle of Dunbar,
etc. certified by Letters from the Headquarters of the Army,
under date 4th September,`" there is a list of the Scottish prisoners;
and among them are named "`Lord Liberton, Mr. Alexander Jaffray,
of the Committee of Estates, Mr. Gillespy, minister, Mr. John Waugh,
minister.`"--It also appears by a letter inserted in Thurlow`'s State Papers,
from Oliver Cromwell to Lieutenant General Lesly, that "`Provost Jaffray, Custairs,
and Wauch`" were the prisoners exchanged for the
seamen and their officers.--Among some extracts,
taken from the town Records of Aberdeen, by permission of James Hardie,
the city chamberlain of that place, is an order to John Jaffray, brother of Alexander,
and one of the bailies or magistrates, "`to repair to Perth,
etc. to obtain his speedy liberation.`"--During his imprisonment, being at Edinburgh,
while Cromwell and his army lay before the Castle, previous to its surrender,
the following curious and important transaction took place,
in which Alexander Jaffray was concerned.
It is taken from the work entitled, "`Cromwelliana,`" p. 95.

"`The General having all things in readiness for battering the Castle,
on Thursday last sent a summons to the Governor Dundas, for the surrender thereof;
a copy of it, and the answers, replies,
and other interactions that passed upon that occasion between the Lord General and him,
you have hereafter.`"
Then, one from the Governor requests "`to hear the information
of late proceedings from such as I dare trust,
and have had occasion to know the certainty of things.`"
"`Such,`" he adds, "`I hope you will permit to come alongst at the first convenience,
and during that time,
all acts of hostility and prosecution of attempts be forborne on both sides.`"
Dated, "`14th December, 1650.`"
To this Cromwell replies, "`If you please to name any you would speak with now in town,
they shall have liberty to come and speak with you for one hour, if they will,
provided you send presently.
I expect there will be no loss of time.`"--"`Then
the Governor sent a letter to his excellency,
to desire two Scotch gentlemen, then in Edinburgh, to come in to speak with him.
Hereupon,
his excellency returned these papers following to the Governor of Edinburgh Castle:

Sir, Having acquainted the gentlemen with your desire to speak with them,
and they making some difficulty of it, have desired me to send you this enclosed.
I rest, Sir, your servant,

Oliver Cromwell.
Edinburgh, 14th December, 1650.
For the Governor of Edinburgh Castle.

Right honourable,
We now hearing that you were desirous to speak with
us for your information of the posture of affairs,
we would be glad, and we think you make no doubt of it,
to be refreshing or useful to you in anything; but the matter is of so high concernment,
especially since it may be,
you will lean somewhat upon our information in managing
that important trust put upon you,
that we dare not take upon us to meddle:
you may therefore do as you find yourselves clear and in capacity,
and the Lord be with you.

We are, Sir, your honour`'s humble servants, well-wishers in the Lord,

M+++.+++ Jaffray.
Jo. Carstairs.
Edinburgh, 14th December, 1650.
For the Right honourable, etc.`"

It is evident, on inspection of Alexander Jaffray`'s signature,
that this should stand "`Al.`" not "`M. Jaffray.`"

=== Note O.

John Owen, whose views of religious liberty are thus particularly adverted to by Jaffray,
and whose edifying conversation was, at this juncture,
the means of throwing a considerable degree of light upon his mind,
with regard to some other topics,
was not styled "`Dr. Owen,`" till after he became "`Dean
of Christchurch`" and "`Vice-chancellor of Oxford.`"
It may assist such readers as have not perused the Memoirs of his Life by Orme,
to introduce from that work some few observations respecting him,
as connected with this passage of the Diary.

Owen was, in 1649, appointed by the Parliament chaplain to Cromwell,
whom he accompanied to Ireland.
In 1650, he was ordered by the same authority, to proceed to the army in Scotland;
and he joined Cromwell at Berwick.
He continued with the army till early in 1651.
For a considerable time, he had advocated the cause of liberty of conscience;
and especially in 1649, when called to preach before the Parliament,
the day after the execution of Charles the 1st. He faithfully told them on that occasion,
that "`much of the evil which had come upon the country,
had originated within their own walls,`" and warned them against "`oppression,
self-seeking, and contrivances for persecution.`"
But that which forms the chief reason for bringing forward this discourse,
is an Essay on Toleration annexed to it.
In this piece,
he examines particularly the arguments of the Scottish
General Assembly in favour of a forced uniformity,
and exposes their fallacy.
"`Gospel constitutions,`" says he, "`in the case of heresy or error,
seem not to favour any course of violence, I mean, of civil penalties.
Foretold it is, that heresies must be; but,
this is for the manifesting of those that are approved,
not the destroying of those that are not.
Admonitions, and excommunications upon rejection of admonition,
are the highest constitutions against such persons;
waiting with all patience on them that oppose themselves,
if at any time God will give them repentance to the acknowledgment of the truth.
Imprisoning, banishing, slaying, is scarcely a patient waiting.
God does not so wait on unbelievers.`"
Memoirs of Owen, p. 89--104.

=== Note P.

These meetings of ministers and professors at Edinburgh,
convened soon after the battle of Dunbar,
chiefly related to a schism which at that time took place in the Church of Scotland,
and lasted till the Restoration.
Burnet thus describes its origin, vol. i. p. 75.
"`A question had been proposed,
both to the Committee of States and to the Commissioners of the Kirk, whether,
in this extremity, those who had made defection,
or had been hitherto too backward in the work, might not,
upon the profession of their repentance, be received into public trust,
and admitted to serve in the defence of their country.
To this, answers were distinctly given, by two resolutions: the one was,
that they ought to be admitted to make profession of their repentance: the other was,
that after such professions made,
they might be received to defend and serve their country.
Upon this, a great division followed in the Kirk:
those who adhered to these resolutions were called the Public Resolutioners: but,
against these, some of those bodies protested; and they,
together with those who adhered to them, were called the Protesters.`"
In the progress of this difference, other occasions of debate arose.
Warristoun, Guthrie, Patrick Gilespie,
Rutherford and others were on the side of the Protesters;
whether Jaffray wholly identified himself with them, does not appear; but if so,
it was but for a short space, as the complexion of his interviews with them,
and his subsequent more decided separation from the Scottish Presbyterian Church,
fully prove.

Row`'s Supplement to Blair`'s Life, a manuscript before referred to,
notices "`some deserting the cause of monarchy and Presbytery,
especially of the Malignant temper, with a few formerly accounted pious and gracious men;
their minds being corrupted by Sectarian principals.`" p. 102.
This writer further speaks of the extrajudicial meeting of Protesters,
both ministers, elders, and professors, at Edinburgh, "`in the end of December,
1651;`" and that one object they had, was to converse with some of these,
for preventing their compliance with the enemy, meaning, the Parliament`'s army.
He observes, "`they war not all alike but for a sinful compliance,
and following of the Sectaries courses, and favouring their errors.`"
"`The main business that was agitat at this meeting
was anent a letter to be written to Cromwell.`"

=== Note Q.

Of these individuals, with whom Jaffray had interviews, both publicly and more privately,
it seems needful to give some very brief account.

In the life of Bishop Burnet, prefixed to the History of his own Times,
it is said of "`Sir Archibald Johnstoun,`" that he was called Lord Warristoun, and was,
during the civil wars, at the head of the Presbyterians,
for many years being entrusted with the whole government of Scotland.
Burnet`'s mother was his own sister.
After the Restoration, in 1663, Warristoun went abroad, to avoid the fury of his enemies;
sentence of forfeiture and death was passed against him by the Parliament in his absence;
and at length he was apprehended in France, brought over prisoner, and executed.
Cruickshank`'s History, vol. i. p. 162.
--According to the last-named author, James Guthrie was minister at Stirling;
of him some further notice will be taken in a succeeding page.--John Livingstone,
minister of Ancrum, has been before mentioned in Note M,
as one of the Commissioners appointed by the Scottish Kirk,
to treat with King Charles the 2nd at Breda.
When, however, the King was restored, and Episcopacy reestablished,
he was banished and went to Holland.--Rutherford,
whose "`Letters`" are well known to the serious classes of the present day,
had been one of the Commissioners from the General
Assembly to the "`Assembly of Divines`" at Westminster.
Soon after the Restoration, his noted Book,
"`Lex Rex,`" was ordered to be publicly burnt, at the cross of Edinburgh,
and at the gate of New College "`St. Andrews,`" where he was "`professor of divinity.`"
He was summoned before the Parliament of Scotland for high treason; but,
being then in a dying condition, was taken away from the evil to come.--Carstairs,
"`that excellent, precious man,`" as Jaffray terms him, it will be remembered,
was taken prisoner with the latter at the battle of Dunbar.
He was minister at Glasgow; and, being similarly situated with others now spoken of,
about the same period, underwent the sentence of banishment,
but owing to illness was allowed for a time to remain;
yet afterwards he withdrew to Holland.--Alexander Skene was a magistrate of Aberdeen,
and, it is probable, stood in the station of ruling elder or deacon;
as he was sent for by this meeting of ministers,
there can be no question about his standing among his fellow-professors.
He became a valued member of the Society of Friends,
as the ensuing Memoirs of that people will show.^
footnote:[His house, Parkhill, lies on the north side of the Don,
and may be seen from the Bridge of Dyce to the east.]

=== Note R.

"`Mr. James Wood was, some time after the year 1651,
made Provost or Principal of the Old College of St. Andrews,
and one of the ministers there`"
"`and continued in the service of the foresaid offices until 1663.`"
"`He refuted the Independents, and asserted the Presbyterial government.`"
--Biographia Scotticana, or Scotch Worthies, p. 271.
James Wood, it will be recollected,
was one of the Commissioners from the General Assembly of the Church of Scotland,
to treat with the King, both in 1649 and 1650.

In addition to the above information, the Editor is enabled,
by a search in the library of the British Museum, to lay before the reader,
as he supposes, the very allusion to Jaffray in one of Wood`'s publications, entitled,
"`An Examination and refutation of Mr. Lockyer`'s Lecture,
preached at Edinburgh anno 1651,
concerning the matter of the visible Church, etc.; Edinb. 1654.`"
The appendix to part 1st of the above contains this sentence:
"`Last summer some persons, ministers and others in Aberdeen,
did write a letter of the date 24th of May, to some godly men in the south,
declaring their separation from the communion of the Church of Scotland,
upon two points of controversy between us and these of the Independent way, namely,
the constitution of the visible church and the government thereof.`"
In an appendix to part 2nd of the same work,
Wood brings forward what they of Aberdeen had averred in their letter,--that when thoughts
of questioning the Presbyterian government were first borne in upon them,
they did a long time suppress them as temptations.
"`Because we had so solemnly (though too implicitly) engaged to the maintenance thereof:
yet, afterwards, knowing that truth cannot lose by a search,
we brought the matters to the balance of the sanctuary.
And now, after seeking of God as he was pleased to give us grace,
and using all helps which we could have, we profess, so far as we can see,
(with reverence to precious and learned men of another judgment,) the congregational
way comes nearer to the pattern of the word than the classical form.`"
In reply to this, Wood writes, p. 361, "`It may be just matter of inquiry to others,
and haply may be of good purposes to themselves, to reflect and consider,
when these thoughts began first to be borne in upon them, at least,
when they began to out anything of them.
Did we hear anything of such thoughts in them,
but since the great revolution of state in this kingdom, after Worcester?`"
meaning the battle of Worcester, when the Scottish army and their King were defeated.
"`This,`" adds he, "`may seem to be ground of searching of heart,
which is deceitful above measure.`"
There is too much of genuineness and sincerity about Jaffray`'s
account of the progress of his own mind in these matters,
for us to question the purity of his motives for
a change from Presbyterian to Independent sentiments.
Certainly, Wood`'s quotation from the Aberdeen letter tends rather to confirm,
the respect we must have for that cautious, humble, and tender disposition,
with which these scruples were entertained and communicated.
The Editor sees much of Jaffray`'s cast of thought
and of expression in the letter alluded to:
it cannot be ascertained, that he himself wrote it, but this appears highly probable;
that he took much interest in the subject of it,
and was one of those who signed such a paper, the reader will observe as he proceeds.

Since the preceding part of this Note was penned,
by favour of "`Dr. Lee,`" the present Clerk of the
General Assembly of the Church of Scotland,
permission has been obtained to take a copy of the identical letter above referred to,
which was ascertained to be among the Woodrow MSS.
fol. 30. 24. in the possession of that religious body.
Though long, there needs no apology for its insertion; inasmuch as,
while by its tenour and weight the motives of Jaffray are
completely cleared from the imputations of James Wood,
his views in regard to the change he was then about making, are materially developed.
It is accompanied by two answers, one from Warristoun,
of considerably greater length than this letter.

Aberdeen, May 24th, 1652.

Right honourable, reverend, and much honoured in the Lord!

Fear to offend you and other precious men in the land,
has made us hitherto to bear up sundry things that were upon our spirits;
but our consciences will permit us to keep silence no longer;
wherefore we have made bold, before we appear more publicly,
to give you a short account of our thoughts;
being confident you will use freedom with us in love.

What secret smitings of heart the people of God through the land have, we know not;
but to us it seems,
there is much more to be read in the Lord`'s dispensations toward the land,
than as yet has been publicly taken with or acknowledged by them.
There be two things, among others, as we humbly conceive,
which the Lord is calling his people in this nation to look more narrowly to than before;
namely, the constitution of our church, and government thereof.
It is far from our thoughts to say, the Lord has no church in Scotland;
but we must crave leave to say, (and, O that we had +++[+++prepared]
hearts for it!) that the holy ordinances of Jesus
Christ have been prostituted among us to a profane,
mixed multitude; yes, and for aught we understand,
the rule of constitution of gospel churches, according to the word,
has never been so looked to as it ought:--and so, at best, we have but an impure church.
And this we speak, without any derogation to those worthy men,
who were instrumental in our first reformation, whose memory is precious to us; no,
we verily judge, that if those holy men were alive in our times,
they would exceedingly offend at us, who have sat down in their dawning light,
which had its own mixture of darkness.

To us it seems, for aught we can search in the word,
that none should be admitted as constituent members of a visible church,
but such as with a profession of the Truth join such a blameless and gospel-like behaviour,
as they may be esteemed, in a rational judgment of charity, believers,
and their children.
Such were the churches founded by the apostles, which ought to be patterns for us,
as appears by the titles given to them, "`saints, sanctified, justified,
purchased by the blood of Christ,`" etc.
We cannot acquiesce to that common answer,
that these expressions are to be understood of the better part;
for that they are to be understood of them all, according to the judgment of charity,
the Holy Spirit has clearly said, Rom. 1:7, "`To all that be in Rome, beloved of God,
called saints;`" and again, ver. 8, "`I thank my God through Jesus Christ for you all.`"
We hope, when the Apostle says, 1 Cor. 6:18,
"`Flee fornication,`" none will deny that he speaks to the whole church; yet,
to the same persons he immediately adds, ver. 19, 20,
"`Your body is the temple of the Holy Spirit which is in
you--you are not your own--you are bought with a price.`"
This is an argument taken from the persons whom he thus exhorted.
But the exhortation is to all the church of Corinth, therefore they were all such,
as the Apostle judged in charity, the redeemed of the Lord.
Neither has +++[+++that]
any weight with us, on the contrary, which is objected,
that there were gross faults among them, such as divisions, intemperance,
questioning the resurrection, incest, etc.
Will not Lot`'s drunkenness and incest, David`'s adultery, Peter`'s denial, etc.
+++[+++say they,]
prove these to be sins incident to saints, though justly censurable?
As the incestuous Corinthian was excommunicated;--a man who once, as is spoken of Gaius,
had been approved of the Truth itself;--though he be overtaken with a gross infirmity,
albeit for it he be censurable, according to the nature of his offence, yes,
though the highest ecclesiastical censure pass against him; yet, +++[+++say they,]
is he to be esteemed +++[+++or treated with]
as a brother, 2 Thess. 3:15. But this is not our case.
Our churches are overflowed with a deluge of profane atheists,
who have been such from their birth unto this present hour.
John Baptist thought not a bare verbal profession,
ground to admit those to baptism who came to him to be baptized; as is clear,
if we compare Matt.
iii. with Luke 7:30. The Pharisees were not baptized of John.
If it be replied, that Christ, in Luke, speaks only of some of the Pharisees,
the sense of the context will easily refute it; for, there,
he chides the Pharisees as worse than the Publicans in this,--that
the Publicans came to John`'s baptism in a capacity to be baptized,
and were baptized of him, which the Pharisees did not.
But if these many Pharisees, spoken of in Matt. 3:7. had been baptized of John,
and only some others of them rejected his baptism; surely the Pharisees, in this,
had been nothing behind the Publicans,
for neither were all the Publicans baptized of John.

Many more, and more pressing grounds from the word,
might be alleged to make forth this point; but we are unwilling to be tedious;--only,
sure we are, holiness becomes the house of our God.
It is certain, our churches were not constituted according to this rule,
in the full extent of it; yes,
alas! few of our most precious men will acknowledge it to be the rule.
But our consciences convince us,
that we are under a sinful snare by reason of our mixtures.
There are some of the most holy ordinances of Jesus Christ,
as the sacrament of the supper, which we know not how to partake of, without sin,
with our multitude. 1 Cor. 10:16-17.
"`The cup of blessing which we bless,
is it not the communion of the blood of Christ?
the bread which we break, is it not the communion of the body of Christ?
For we being many are one bread and one body;
for we are all partakers of that one bread.`"
If then we should communicate with those who are knownly profane, should we not,
upon the matter, own and acknowledge such, as the members of Christ?
Does not even that charge reach us, 2 Cor. 6:17. "`Come out from among them,
and be separate, says the Lord, touch no unclean thing, and I will receive you.`"
Here, indeed, he speaks of a cessation from the heathen; but the mediums which he uses,
to infer this particular conclusion, are general,
and will no less bear the weight of another particular conclusion relating to our case.
Thus, ver. 14, 15, he reasons, "`What fellowship has righteousness with unrighteousness,
and what communion has light with darkness, and what concord has Christ with Belial,
or what part has he that believes with an unbeliever?`"
Who can deny,
but these general terms will comprehend gross public wickedness among professed Christians,
as well as heathenish idolaters.
It is far from us to intend a separation from the godly in Scotland; they shall be,
through the Lord`'s grace, dear to us as our own souls, aye,
though they should persecute us, our hearts shall cleave to them.
But may not a purge remedy all this?
O that it could!
But shall a tenth, shall one of a city, two of a tribe, purge a whole nation?
Is not a little leaven ready to leaven the whole lump?
What then may be expected, when the whole lump is leavened,
and only a small remnant through the goodness of God kept pure?
Is there any hope that the ministry of Scotland, considering our present posture,
can be purged?
Have not the corrupt party, which are the more numerous,
began to thrust out the more precious ministers?
and are they not likely to proceed?
Can we have purged elderships or congregations?
are there not many congregations,
where all are involved under gross ignorance and public scandals, as swearings,
+++[+++or sneerings,]
who shall be elders there to purge out the sour leaven?
We have been these several months endeavouring,
with our brethren in the province and in the presbytery, yes,
and with some primely interested in our own congregations, for a purge;
but we have travailed long, and brought forth nothing but wind.
But lastly, is it not in vain to speak of purging,
when our best men will not agree upon the rule of purging;
and therefore to talk of purging, considering our posture,
seems to us but a specious notion, to entangle our spirits and keep us from duty.

Touching Presbyterial government, indeed,
when thoughts of questioning it were first borne in upon us,
we did a long time suppress them as temptations; because we had solemnly,
though too implicitly, engaged to the maintenance thereof.
Yet afterwards, knowing that a truth cannot lose by a search,
we brought the matter to the balance of the sanctuary; and now, after seeking of God,
as he was pleased to give grace, and using all helps which we could have, we profess,
so far as we can see,
(with reverence to precious and learned men of another judgment,) the congregational
way comes nearer to the pattern of the word than our classical form.
And to us it appears, that Christ has furnished a congregation, with their elderships,
with complete power of jurisdiction and censure within themselves;
as from several other Scriptures, so in particular from that remarkable text,
Matt. 18:15 to 18, "`Tell it unto the church.`"
The church there spoken of, has complete power of binding and loosing,
as is clear from ver. 17, 18; but that church is not the classical presbytery,
but the eldership with the congregation; therefore, etc.
The assumption is clear: First, Because it is not to be found in all the gospel,
that a company of elders, either of a class or of a congregation,
apart from the congregation, is called a church.
Indeed, a congregation, with elders commonly, yes,
and sometimes as contradistinguished from elders, aye, and sometimes also without elders,
is sometimes termed a church, Acts 15:22-4, and 14:23.
Now, what an absurdity were it,
to reject the usual acceptation of the word in the New Testament, and,
without any colour of reason,
to coin a sense which no where is to be found in all the gospel,
though the word be most frequently used in it.--Second,
The church spoken of in this text, +++[+++Matt, xviii.]
which has complete power of binding and loosing, is the first ecclesiastical judicatory,
to which belongs judicial cognizance of offences;
for if private admonition do not gain the offender, then the command is, Tell the church.
But our classical presbytery is not the first judicature
to which appertains judicial cognizance of offences;
for first they come to sessions,
and only by reference from the sessions to the presbyteries.
Therefore this church, here spoken of as having complete power of binding and loosing,
cannot be the classical presbytery, but the eldership with the congregation.
No where do we read in the gospel,
of jurisdiction in relation to censure committed to a classical presbytery;
all the power we find exercised by that meeting at Jerusalem, Acts, xv.,
is dogmatical--("`You people and brethren`"--having their interest like-ways)--which
the congregation divines willingly yield all the certificate they use,
is, "`If you do these things, you shall do well,`" ver. 29,
but do not threaten to sentence those who disobey, with excommunication.
There might be something said from antiquity,
that the government of the church was partly aristocratical, partly democratical,
in much of the first 300 years;
and that the people had no small influence in matters of discipline; but we forbear,
as desiring to lean on a surer foundation.

It is not any by-respect for what we know of our own hearts,
as our consciences bear us witness, but conviction of duty, which puts us out to this;
and though precious people in the land shall have hard thoughts of us for it,
we hope to find mercy to have tender thoughts of them.
The Lord has highly honoured you to bear witness, oftener than once,
to contradicted truth; but we dare say, if the Lord would clear your judgments,
to appear upon the head of this business,
it would be the greatest honour which ever God conferred on you; and we, poor creatures,
would gladly come under your shadow.
It would be no shame for you to acknowledge,
the Lord`'s work has outgrown your expectations; but it fears us, while you stand +++[+++at]
a distance from the duty, the Lord`'s hand shall be "`stretched out still.`"
And we humbly desire you to take heed,
(we trust you will pardon our freedom,) lest you
be snares to the people of God in the land;
for the eyes of all are upon you, and many depend upon your motions.
It is not presumption, but love and respect to you, makes us so bold,
and to use such plainness of speech.
Therefore we hope we shall not be mistaken; yet if the Lord, by you or yet any other,
will hold forth convincing light to us, discovering our mistakes,
we should gladly close with it; only,
if we be necessitated to take any course for expeding +++[+++ridding]
ourselves from the present snares and guiltiness, under which we lie,
we desire you will not construe it hardly.

Now, that light may be let forth to you and us both,
from Him who is the Father of lights,
shall be the earnest desire of your loving brethren in Christ,

In name of others in this place, sic subscribitur,

Alexander Jaffray, Mr. William Moore, Mr. John Row, Mr. John Meinzies, Andrew Birnie.`"

=== Note S.

The following quotation from Orme`'s Life of Owen, p. 127,
may throw some light on these reflections of Jaffray.

The state of religion in Scotland, during the ten years preceding the English invasion,
and the rule of the Commonwealth afterwards, has been much misunderstood.
The zealous friends of Presbyterian discipline,
have represented the period from 1638 to 1649, as the golden age of religion in Scotland,
and the following years, as exhibiting a lamentable falling off.
And indeed, if true religion consists in the regular meeting of church courts,
and the overwhelming power of ecclesiastical rulers,
the former period would be very distinguished.
But, if much of the form may exist without the power of religion,
we shall be cautious how we judge of the state of religion from the proceedings of Assemblies.
That there were then many excellent men in the Church is beyond dispute;
but that not a few of the clergy were destitute of genuine piety,
and that a vast majority of the people were in no better state,
are equally unquestionable.
The Assemblies were exceedingly zealous in putting down Episcopacy,
in establishing uniformity, and in passing persecuting laws;
but had much less of the Spirit of Christ than their office required.
The English army and ministers had but a low opinion of the state of religion,
on their coming into Scotland.`"--This view of the subject seems to be confirmed
by the succeeding passage from Bishop Burnet`'s History of his own Times.
Speaking of the Covenanters, he says, "`Then they took up the name of Malignants,
by which all who differed from them were distinguished:
but the strictness of piety and good life,
which had gained them so much reputation before the war, began to wear of;
and instead of that, a fierceness of temper,
and a copiousness of many long sermons and much longer prayers,
came to be the distinction of the party.
This they carried even to the saying of grace before and after meals,
sometimes to the length of a whole hour.
But as every new war broke out,
there was a visible abatement of even the outward show of piety.`"
vol. i. p. 47.

"`It does not appear,`" continues Orme, "`that the influence of the English army,
and of Cromwell`'s government, was unfavourable to the state of religion in Scotland.
On the contrary, there is reason to believe, that true religion was, during this period,
in rather a prosperous state.
It is true, Cromwell put down the Assemblies,
and curbed the spirit of interference with politics,
which then so much prevailed among the ministers.
But he interfered with none of the other rights of the Church,
and encouraged the profession of the gospel in all ranks.
'`I remember well,`' says Bishop Burnet, '`three regiments coming to Aberdeen.
There was an order and discipline, and a face of gravity and piety among them,
that amazed all people.
Most of them were Independents and Anabaptists: they were all gifted men,
and preached as they were moved.`"
"`But the strongest testimony to the prosperous condition of religion in Scotland,
is from the pen of Mr. James Kirton, afterwards one of the ministers of Edinburgh,
who from his opportunities was well able to judge, and,
from his sentiments as a Presbyterian,
unlikely to overrate the salutary influence of the measures of the Commonwealth.
'`They did indeed,`' he says,
'`proclaim a sort of toleration to dissenters among Protestants,
but permitted the gospel to have its course,
and presbyteries and synods to continue in the exercise of their powers;
and all the time of their government, the gospel prospered not a little, but mightily.
At the King`'s return, every parish had a minister, every village had a school,
every family almost had a Bible; yes, in most of the country,
all the children could read the Scriptures, and were provided with Bibles,
either by their parents or their ministers.`' History of the Church of Scotland, p. 54,
etc.`"

=== Note T.

We have seen that Jaffray, in his interactions with Cromwell,
and with that party who were then generally termed "`Sectaries,`"
had his mind much cleared upon the subject of the due limits
of the magistrate`'s power in matters of religion;
that he saw into the error and guiltiness, as he describes it,
of the good men of his own nation,
in their carrying forward what they called the work
of God and of reformation--"`whereon,`" says he,
"`much has been well expressed by many good men;`" and further, that he was led onward,
to institute a close impartial search into the scriptural
constitution and government of churches.
There is strong ground for the assumption,---although,
from the sparing detail of matter of fact in the Diary,
it cannot be ascertained,--that our earnest, yet discriminating inquirer,
while thus engaged, had met with William Dell.
This individual, as an author,
had then recently put forth several very prominent treatises
in illustration or in vindication of gospel liberty;
while, as a popular preacher and chaplain to General Fairfax,
his close attendance at the headquarters of the same army which Cromwell now commanded,
gave him great opportunity of propagating those views of religious toleration,
for which he was so deservedly noted.
Indeed, Dell may fairly be regarded,
to use the words of Crosby in his History of the Baptists,
as one of the heads or champions of that party in the nation,
who were opposed to persecution;
and appeared among the most forward in promoting a reformation in religion,
beyond what many were prepared for.
Among his various pamphlets upon these favourite topics,
and which are collected into 2 vols.
8vo. in the edition of 1817,
there is one entitled "`The Way of true Peace and Unity in the true Church
of Christ,`" etc. from which the Editor thinks proper to quote a passage,
presenting remarkably close analogy to that peculiar train of conclusion,
taken up by Jaffray in the foregoing paragraph now under notice.

While upon the subject of the government of the church,
after quoting that text of the Apostle, Eph. 5:32, "`This is a great mystery:
but I speak concerning Christ and the church,`" Dell thus proceeds--"`And as the Lord,
in the former age, has been pleased to reveal to the church the mystery of the Head,
after a long time of its obscuring and darkening under the reign of antichrist; so now,
we wait in hope, that he will, in this present age, reveal the mystery of the Body,
which has been no less obscured than the former;
that so the whole mystery of whole Christ, may both be known and accomplished among us,
according to the riches of his glory by the gospel.`"--"`The
constitution of the church,`" says a more modern writer,
"`was among the last subjects the Reformers were likely to study, and,
from their peculiar circumstances, the one they were most likely to misunderstand.
Believing, as they did, that Christianity could scarcely exist without state-patronage,
and that conscience was the subject of human legislation,
the simple form of Independency was not likely to occur to them; or, if it did occur,
would be speedily rejected as unsuitable to the state of the church, and of the world.`"
Orme`'s Life of Owen, p. 65.

The Editor is unwilling to pass away from William Dell,
without recommending him as an author of remarkably spiritual cast,
to the particular notice of the Society of Friends;
many of whom are acquainted with some of his works,
so nearly congenial with their own views.
Nor will Christians of other denominations be disappointed
of instruction and comfort from the perusal,
in proportion as they look beyond men, to the essential teachings of the grace of Jesus.

=== Note U.

Allusion has several times been made in these Notes to the Independents.
"`The distinguishing principle of Independency,`"
says a late valuable member of that body,
"`may be expressed in a single sentence; namely,
That a church of Christ is a voluntary society of Christians,
regularly assembling in one place,
and with its officers possessing the full power of government, worship,
and discipline in itself.`"
Orme`'s Life of Owen, p. 63. In the appendix to the same volume,
there is a note upon the early state of Independency in Scotland.
After some recital of the rise of that community, under the designation of Brownism,
from one Brown,
who came out of the Low Countries to Edinburgh with a number of adherents;
this author goes on to quote a passage from Spalding`'s History of the Troubles, p. 303,
much to our purpose.
"`About this time, September, 1642, there came in quietly to Aberdeen,
one called Othro Ferrendail, an Irishman, and a skinner to his calling,
favoured by Mr. Andrew Cant, and by his moyan admitted freeman.
He was trapped for preaching on the night in some houses in the town before their families,
with close doors, nocturnal doctrine or Brownism, as was said.`"
"`Mr. Cant,`" continues Orme,
"`was more favourable to innovation than some of his brethren.`"
This is the first notice we have of Independency in Aberdeen,
towards which our Diarist would now be considered as fast verging.
Indeed, it appears as if either this Ferrendail, or one of his family, like Jaffray,
found no rest there for his mind, but passed onward to the principles of the Friends;
for, one of that name became a member, and sufferer for conscience-sake in the Society,
as will be seen in the succeeding part of this volume.
"`In the provincial assembly at Aberdeen, 1642,`" Orme proceeds to remark,
"`There was,`" quoting Spalding, "`great business about Brownism,
lately crept into Aberdeen and other parts.`"
At length it appears, "`the General Assembly of 1647, passed an act,
prohibiting the importation of all books and pamphlets containing Independency and Anabaptism,
and forbidding reading the same; or harbouring any persons infected with such errors.
Presbyteries and synods are enjoined to process such as shall offend against these injunctions;
and civil magistrates are recommended to aid and
assist ministers in everything to that effect.
Acts of Assemblies from 1638 to 1649, printed at Edinb.
1682.--These were the blessed days of Presbyterian supremacy;
and such was the use which they made of their power.
The English army entering Scotland soon after this,
prevented the execution of this unjust law,
and imported Independency in such a way as could not be resisted.`"
It is to such measures and laws as these, that Jaffray, doubtless,
has reference in the paragraphs now under notice;
and in tracing the progress of his mind hitherto,
his objections to the Presbyterian body may be pretty
much comprehended in the heads of a Declaration,
presented by the English Commissioners to the General Assembly of the Church of Scotland,
in the month called July, 1652,
which is very near to the date of these his observations in the Diary.
It is entitled, "`A Declaration in favour of Congregational Discipline,
Purity of Communion, and Toleration.`"

=== Note V.

In Row`'s Supplement to Blair`'s Life,
we have the following account of this conference.--"`In September,
Mr`'s Samuel Rutherfoord, James Guthrie, Pat.
Gillespie, and Jhone Carstaires went to Aberdeen,
to confer with these who had declared themselves for separation.
But Mr. Jhone Menzies, who was their ringleader, and the greatest dispute among them,
being sick, they could doe the less; notwithstanding, for the space of six days,
they conferred and debated with one other two ministries and some regents in the college,
in the hearing of many that hankered after that way.
Alexander Jaffray, late provost of Aberdeen, was much for separation:
there was some also there that was against infant baptism
and were in danger to be tainted with other errors.`" p. 106.--In the Woodrow MSS+++.+++,
already referred to in a previous note, quarto, volume 29,
No. 61, Gilespie`'s return home to Glasgow from Aberdeen is noticed,
where he had gone to endeavour to keep or recover some there:
No. 63,(is from a number of Protesting ministers in the south or west,
to some in hazard of Independency; the scope of which, no doubt, is,
as Jaffray expresses it, to persuade them from falling on any such dividing way.

=== Note W.

In Nicoll`'s MS. Diary, before cited, under date "`May 8--18,
1652,`" a list of public functionaries is given, on the English Judges sitting down;
and among these, is the name of "`Provost Jaffray,
keeper of the great seal and Director of the Chancellarie, etc.`"
A similar notice occurs in the same MS+++.+++, at the end of the year 1657,
in enumerating the officers of state for Scotland; the writer adds,
"`But the keeper of the great seal was my Lord Desburrow.`"--With
regard to this high appointment,
which under Cromwell`'s government Jaffray was called to fill,
the Editor is able but barely to supply that kind of information
which he could have wished had been explained by our Diarist himself,
in connection with his own incidental observations on the office.
We are thus deprived of that which might possibly have thrown
light upon his line of public action in those peculiar times,
The office of Director of the Chancellry or Chancellary,
was in some respects similar to that of Lord Chancellor
in England,--supreme Head of the Court of Chancery;
but it has no judicial functions, and is at present, as the Editor understands,
a place of honour more than of business.

By favour of Richard Jaffray of London,
the present hereditary descendant of the Jaffray family,
the following copy of the original instrument is subjoined, conveying,
under the great seal of the Commonwealth,
the above-mentioned office of Director of the Chancellary to Alexander Jaffray.

Oliver, by the grace of God, Lord Protector of the Commonwealth of England, Scotland,
and Ireland, and dominions thereto belonging,
To all men to whose knowledge these presents shall come, greeting:

That, forasmuch as we, by our letters of gift, superscribed with our hand,
of the date at Whithall, the second day of March,
one thousand six hundred and fifty six years,
nominated and appointed our loved Alexander Jaffray esquire
to the office of Director of our Chancellarie in Scotland;
which office the said Alexander Jaffray is to hold and exercise by himself or
such deputy or deputies as shall be allowed of by our Council in Scotland,
so long as he shall therein well and faithfully demean himself.
And our will and pleasure was, that the yearly salary of two hundred pounds,
usual money of England, be allowed to the said Alexander Jaffray,
for the execution of the said office,
and our Council of Scotland to give order for payment thereof accordingly
And we did thereby ordain the Commissioners of exchequer to extend,
and cause the said gift or nomination to be past our great seal of Scotland,
in due and competent form.
And our aforesaid nomination and enrollment in our buikes of exchequer
should be to our said Commissioners are sufficient warrant in that behalf.

"`Therefore we, with advice and consent of the Commissioners of our said exchequer,
have given, granted, and disponed, like as we be the tenour hereof give, grant,
and dispone to the said Alexander Jaffray esquire,
so long as he shall therein well and faithfully demean himself,
the said office of Director of our Chancellarie,
and of the custody of the testimonial of our great seal, then vacant, in our hands,
and our gift and disposition.
With full power to the said Alexander Jaffray esquire,
during the time of his said office, he himself or his deputies,
for whom he is to be answerable, of using, exercising,
and enjoying of the fore-said office as freely, in all respects,
as any Director of the Chancellarie at any time bygone used or enjoyed the same,
with all honours, privileges, dignities, and immunities whatsoever,
which any of his predecessors, Directors of the Chancellarie,
enjoyed or possessed at any time bygone, with the said fee of two hundred pounds,
money of England, which the said Alexander Jaffray for the present possesses.

In testimony whereof we have append our great seal to their presents.
At Edinburgh, the twentieth day of November,
the year of our Lord one thousand six hundred and fifty seven years.

By warrant signed be the Commissioners of the exchequer.`"
+++[+++Endorsement]

Presented and sealed at Edinburgh the 27th of November, 1657.

Abernethie

Johesone dept.

Alexander`'s Brodie`'s name has already appeared in a preceding page,
as one of the Commissioners to treat with the King at Breda.
He had been one of the Lords or Judges in the Court of Session in 1650,
as he afterward was in 1658.
About the same time that Jaffray was called by the
Judges to the Directorship of the Chancery,
Brodie, in his Diary, has the following memoranda.
After numerous references on toleration, church government, admission to ordinances,
etc., as if he had been discussing these subjects with persons not named:--"`21st June,
1652.
Memorandum with Mr. Jaffray--1st. To consider my last letter,
and correct an expression in it anent church members, their qualification,
and restrict it to admission to the sacraments.--2nd. To see how far he
agrees with me in these things I write of.--3rd. To show that,
since my last, my mind is much alienated with General Dean`'s discourse; therefore,
to inquire,
how can we consent or submit to rulers of such principles?--4th.
To ask anent the General Assembly and others.--5th. What overtures
of peace or agreement are fallen upon for those in the west,
and others,
with the English and among ourselves?--6th. To consider their paper and propositions,
how far we agree and can close.--7th. What way they settle the government, seals,
and justice?
The feudary elections in burgh and shire?--8th. Walter Cochrane.--9th.
The money which we rest to the men of Campoore,
how to be relieved.--To see the Acts, and borrow the book.`"

There is another set of memoranda bearing the same date,
which though it has still less relation to the former subject of this Note,
cannot so well be inserted in another place as in the present.
It proves the respect in which Jaffray`'s sentiments were held by this estimable Judge.--"`1st.
What he takes to be the causes of the Lord`'s departure?--2nd. What he takes to be the
present signs of it?--3rd. What is the incumbent and the special duty of the time,
beside seeking of Him;
and what neglected duty is he calling us unto?--4th. What corruptions in worship
and ordinances does he observe?--5th. What takes he to be the causes of the bitter
differences and divisions which are springing up among the godly in the land,
no, in both the lands?`" p. 26.--The "`Diary of Alexander Brodie of Brodie Esq.`"
was printed in 1740, at Edinburgh; it consists of 148 pages octavo,
and extends only from 1652 to 1653-4;
so that we are deprived of his sentiments connected with that important
engagement upon which he was united with his friend Jaffray,--the
Commission to treat with the King at Breda.

=== Note X.

It is far from the design of the Author of these historical illustrations,
very minutely to enter into the political circumstances
of the times in which Jaffray lived.
Rather than this,
he would prefer a close adherence to the example so uniformly set in the Diary,
of passing slightly over matters of this nature.
A middle course, however, will better comport with the views of the Writer,
and with those claims which his readers may justly have upon him.
He will therefore produce a few authorities,
which advert in particular to the constitution,
and to some of the transactions of this singular legislative body,
usually termed the Little Parliament,
of which we find Jaffray to have been chosen a member.

"`Though historians differ so much in their characters of this assembly,`"
as the authors of the Parliamentary History of England observe,
"`yet they all seem to agree,
in passing over their proceedings with the most affected neglect;
they do little more than mention their coming together,
and their dissolution.`" Vol. xx. p. 180.
With the view of shunning so exceptionable a course, these associated writers,
with every appearance of candour and discrimination,
go into the investigation of the subject,
devoting to it out of their twenty-four octavo volumes above fifty pages.
"`We are very far,`" they continue,
"`from entering into a vindication of this unconstitutional assembly.
It is certain, that the manner of their being convened,
in obedience to Cromwell`'s warrant of nomination,
was the most flagrant instance of invasion upon the rights
and liberties of all the electors of the three nations,
our whole history affords;
and was absolutely subversive of the very being of parliaments.
But whether they deserve all that ignominy, which has been cast upon them,
by the contemporary historians we have cited in our account of their transactions,
and some modern writers who have implicitly copied them, will best appear,
by the laws they made, and the bills they were employed about,
at the time of their dissolution.`"

The warrant of nomination is now to be given, in submission to which,
our worthy Author became involved in so high responsibility:
it is inserted in "`Cromwelliana,`" p. 125.

"`A copy of the Letter of his Excellency the Lord General Cromwell,
sent to the members called to take upon them the trust of the government of this Commonwealth.

"`Forasmuch as upon the dissolution of the late Parliament, it became necessary,
that the peace, safety, and good government of this commonwealth, should be provided for;
and in order thereunto, various persons fearing God,
and of approved fidelity and honesty, are by myself,
with the advice of my Council of officers, nominated,
to whom the great charge and trust of so weighty affairs is to be committed.
And having good assurance of your love to, and courage for God,
and the interest of his cause, and of the good people of this Commonwealth:

I, Oliver Cromwell, captain general and commander in chief of all the armies,
and forces raised and to be raised within this Commonwealth,
do hereby summon and require you,
(being one of the persons nominated,) presently to be and appear at the Council Chamber,
commonly called or known by the name of the Council Chamber at Whitehall,
within the city of Westminster, upon the 4th day of July, next ensuing the date hereof;
then and there to take upon you the said trust, unto which you are hereby called,
and appointed to serve as a member for the county
of +++____________+++. And hereof you are not to fail.

Oliver Cromwell.`"

Given under my hand and seal, "`The +++_______+++ day of June, 1653.

By virtue of this instrument was a House of Commons convened,
and agreeably to the tenour of it, Lingard in his History of England, asserts,
that the chief qualification of the members was to consist in holiness of life.
He proceeds to state, vol.
vii. p. 142, that, "`With this view,
the ministers took the sense of the congregational churches in the several counties;
the returns contained the names of the persons, faithful, fearing God,
and hating covetousness, who were deemed qualified for this high and important trust;
and out of this, the Council, in the presence of the Lord General,
selected 139 representatives for England, 6 for Wales, 6 for Ireland,
and 4 for Scotland.`"
He speaks of them as being men of independent fortunes; while Ludlow had expressly said,
that this assembly was composed for the most part of honest and well-meaning persons.
But Godwin, in the History of the Commonwealth, goes further, and affirms,
they included in their numbers "`some of the most eminent and respectable
persons in the community,`" adding the remark of Whitelock,
that, "`It was much wondered at by some, that these gentlemen,
many of them being persons of fortune and knowledge, would, at this summons,
and from these hands, take upon them the supreme authority of the nation.`"

Having thus touched upon the general character given of
this legislative body by some writers of respectability;
it may be now observed,
that though Jaffray has left us no account of his motives
for compliance with the requisition thus put upon him,
he was, doubtless,
influenced by a consideration of the peculiar position of public affairs at that crisis,
and by a hope that some opening might follow for
measures productive of good to his country.
His colleagues chosen for Scotland, according to Nicoll, by the English Council of State,
were, "`the Laird Brodie,`" who has been mentioned in the preceding Note;
"`Sir James Hope,`" styled "`the Laird of Hopetoun;`" Colonel Lockhart of Ley;
and "`the Laird Swintoune,`" respecting whom some
further account will appear in ensuing pages.
Several of these stood as Lords or Judges in the Court of Session.
Alexander Brodie, the first named, in his private Diary,
under the date of "`the 17th June,`" alludes to the receipt of Cromwell`'s "`letter,
or rather citation and summons to come to London,`" and on the 10th of the next month,
he writes, "`I spread Mr. Jaffray`'s letter before the Lord,
and found it could not stand with former resolutions.
I am not the man which others vainly imagine me to be; no,
nor indeed come I up to my profession.--If the Lord would uphold my soul,`"
continues he, "`+++[+++I] would rather choose to suffer at the hands of men,
than to fall into the snare and temptation of public
employments.--26th. I got the provost`'s letter,
showing, they collected from my letter, that I would come and take employment.
This did humble, and my soul desired to be cast down under it.
I got Warristoun`'s letter and papers against it: these I spread before the Lord,
and besought him through the Lord Jesus, on whose name I believed, for direction, light,
strength, stability, and counsel.--27th July, I wrote back to the provost,
and with all the fervency of my heart I assured him,
I would not take any employment on me;
and that I laid aside all thoughts of coming to London;
and I resolved on all hazards that could befall me,
before I ran myself on that rock.--13th August,
I received another letter from provost Jaffray, desiring me to come up.--16th September,
I received letters from London, and from the Earl of Cassils.`"
Thus it would seem, that Jaffray at length succeeded in prevailing with his friend:
and without hesitation, it may be assumed,
judging from what is already seen of his character,
that he had a high sense of the duty imposed upon him,
and of the benefits which might result from fulfilling it,
or he would not have thus urgently and repeatedly pressed the matter,
against the apparently conscientious objections of Brodie.

With regard to the proceedings of this Parliament, Lingard, in the following terms,
conveys a summary of particulars,
which tend to place these legislators in no contemptible light:
"`They established a system of the most rigid economy;
the regulations of the excise were revised;
the constitution of the treasury was simplified and improved;
unnecessary offices were totally abolished,
and the salaries of the others considerably reduced;
the public accounts were subjected to the most rigorous scrutiny.`"
He further informs us, the Court of Chancery was to be remodeled or abolished,
the punishment of death for theft was not to be tolerated, tithes were to be done away,
and the choice and maintenance of the minister to be vested in the body of the parishioners.`"
Thus much is at least due, in explanation of Jaffray`'s laconic expressions,
"`It was on the hearts of some there,
to have done good for promoting the kingdom of Christ.`"--Among
the numerous Committees appointed for those and other purposes,
are specified in the Parliamentary History the following:
For trade and corporations--for receiving proposals for the advancement of the Commonwealth--for
the poor--for inquiring into the revenues of hospitals--for regulating the commissions
of the peace throughout the nation--for public debts--for receiving accusation of bribery,
public frauds,
and breach of public trust--also for the advancement of learning--for removing all laws
and ordinances which are hindrances to the progress of the gospel,---besides others,
+++[+++n a tract, preserved in the Library of the British Museum, entitled,
"`True manner of the sitting of the Parliament, etc.
August,
1653,`" Jaffray`'s name appears on a Committee "`for
the affairs of Scotland,`" on that for tithes,
for the business of trade, for corporations,
and for receiving propositions for the advancement of the Commonwealth.
With regard to the first of these, it is to be understood, that the most important,
and perhaps main business devolving on that Committee, was, the settlement of a union,
then attempted, between England and Scotland:--Cromwell`'s name, of course,
stands foremost upon it.
This is evident from Lamont`'s Diary, p. 68.--"`1663,
June 24th. The Commissioners for Scotland being called
for by General Cromwell and his council of officers,
to treat about a union of their nations, went for England at this time.`"
Nor must a remark of Godwin`'s, in his History of the Commonwealth, be here omitted, vol.
iii. p. 568. "`The Parliament also applied itself
with diligence to the bill of union with Scotland,
and made several important and useful regulations relative to that country.
But its sittings were finally terminated, without bringing the bill of union to a close.`"

The dissolution of this Parliament is thus given by the last-mentioned author, vol.
iii. p. 588.--Col.
Sydenham moved the dissolution of the assembly.
Upon this question there ensued a debate,
"`The debate promised to be of considerable duration.
Every instant the house increased by the resort of members.
This did not suit the views of Cromwell`'s followers,
who began to fear that the motion might be carried against them.
They therefore devised a new and irregular expedient, suited to the energy, Rous,
the speaker, was on their side of the question.
Suddenly he rose, and left the chair.
The sergeant took up the mace, and carried it before him, as he quitted the hall;
and as many members as were favourable to the motion, followed him,
and immediately repaired to Whitehall, to demand admission to Cromwell.
There appears to have been about 70 members present in the house;
and when Rous and his supporters were gone, there remained 34 or 35. This secession,
however, immediately put an end to their business.
They had no speaker; and the numbers that remained did not constitute a quorum, which,
by the rules of the house,
must consist of not fewer than 40. They continued
in consultation as to what was to be done.
Presently, however, two officers, Colonel Goffe and Major White,
came in and entreated them to withdraw.
This they refused to do, but upon compulsion.
Accordingly, a file of musketeers was introduced; the house was cleared,
and the doors closed.`"--So far, in amplification of the words of Jaffray,
"`When that Parliament was broken up, I, not being satisfied with the reasons thereof,
was one of 30 or 31 that stayed in the house.`"
Godwin`'s closing character of it, cannot properly be withheld,
as given at p. 578 of the above cited volume of his History,
after which this subject will be disposed of:--"`There
was much of public virtue in this assembly;
they possessed no common portion of that wisdom and penetration
into the spirit and consequences of social institutions,
which might seem to qualify them to secure essential benefits to that age,
and to ages which should succeed.`"

The curious circumstance,
which in the Diary of Alexander Jaffray stands closely appended to the foregoing; namely,
that of Cromwell`'s offer to make him a judge for Scotland, will, doubtless,
be fresh in the recollection of the reader:
this evidently took place very shortly after his release from the senatorial office,
while yet he remained in London.
A similar instance occurred in the case of Bishop Burnet`'s father;
which also strongly illustrates the independent line of conduct adopted by Cromwell,
in the choice he made of officers for high, responsible stations.
The Bishop says, "`He studied to seek out able and honest men, and to employ them:
and so,
having heard that my father had a very great reputation in Scotland for piety and integrity,
though he knew him to be a royalist, he sent to him,
desiring him to accept of a judge`'s place, and to do justice in his own country,
hoping only that he would not act against his government;
but he would not press him to subscribe or swear anything.
My father refused it in a pleasant way.`"

On Jaffray`'s return home from London, within this same year,
Nichol`'s Diary notices his name on a list of those persons appointed "`for the provinces
benorth Angus,`" "`for the approval of ministers newly ordained,`" in accordance with
"`an ordinance brought down from the Protector by Patrick Gillespie.`"
This was, doubtless, a similar appointment to that in England,
of Commissioners for ejecting scandalous, ignorant, and insufficient ministers,
which took place about the same time.
Their business was, to inquire particularly "`into the grace of God in the candidate,
his holy and unblameable conduct; also into his knowledge and utterance,
and fitness to preach the gospel.`"
With regard to Jaffray`'s acceptance of such a post, arbitrary, objectionable,
and difficult as it must have been, we may fairly conclude,
from what is known of his character and sentiments at this period, that,
so far as he was concerned as an individual among his colleagues in office,
it was his desire and aim to benefit the interests of solid piety and Christian faith.
Baxter, while by no means favourable to the commission,
speaks in general terms thus favourably of the results of their proceedings.
"`They saved many a congregation from ignorant, ungodly,
drunken teachers that sort of ministers, that either preached against a holy life,
or preached as men that never were acquainted with it:--all
those who used the ministry as a common trade to live by,
and were never likely to convert a soul:--all these they usually rejected,
and in their stead admitted any that were able, serious preachers,
and lived a godly life, of what tolerable opinion soever they were.`"

=== Note Y.

The reader will probably have remarked,
that the preceding portion of the narrative is by no means, correctly speaking, a Diary;
the actual period of its production, as before hinted,
being presumed to be about the latter end of the year 1656.
The comprehensive review and acknowledgment of past mercies, which now follows,
on the writer`'s settlement near Edinburgh,
together with his more diffuse meditations "`On being exercised in bearing the
cross,`" appear to wind up the retrospective part of the narrative to a close.
After this, at the date, "`10th of April, 1657,`", proceeds the Diary, as a diary,
in its more appropriate form, each observation bearing the date of insertion.

=== Note Z

A passage remarkably similar to this,
occurs in Archbishop Leighton`'s Commentary upon the First Epistle of Peter.
Speaking on the words, ch. 5. ver. 1.
"`Who am also an elder, and a witness of the sufferings of Christ,`"
that wonderful man, as Doddridge deliberately styles him, proceeds to show,
that a spiritual view of Christ crucified,
is certainly very requisite for the due witnessing of him,
and displaying the excellency and virtue of his sufferings.
"`Men,`" continues he, "`commonly read and hear, and may possibly preach,
of the sufferings of Christ as a common story; and that way, it may a little move a man,
and wring tears from his eyes: but faith has another kind of sight of them,
and so works other kind of affections,--and without that,
the very eyesight of them availed the apostles nothing:
for how many saw him suffer as they did, who reviled, or at least despised him.
But, by the eye of faith to see the only begotten Son of God,
as stricken and smitten of God, wounded for our transgressions, etc. this is the thing,
that will bind upon us most strongly all the duties of Christianity, etc.`"

In the succeeding Note, the reader will find some observations relative to Leighton,
tending to throw light upon that coincidence,
which is occasionally to be discerned between the
sentiments of this author and our worthy Diarist.

=== Note AA.

"`There is a noble guest within us--Oh! let all our business be,
to entertain him honourably,
and to live in celestial love within;--that will make all things without
be very contemptible in our eyes.`"--This almost parallel passage,
is taken from a letter of Archbishop Leighton`'s,
published in his Whole Works, Lond. edit. 1818.
There are parts of Jaffray`'s Diary, and the paragraph now under notice is one,
which, both in turn of thought and of expression,
bear a vivid resemblance to this eminent Christian author.
It cannot be now ascertained,
that there actually existed between them any intimacy or even acquaintance,
though this may very probably have been the case.
It appears that Leighton was the appointed minister of Newbattle, near Edinburgh,
until the year 1653; when he resigned that charge,
and was chosen Principal of the University of Edinburgh,
which office he filled for about nine years.
Jaffray, on the other hand, as we have seen,
resided at or near that city for six months together out of the twelve;
from 1654 to 1656; after which, that is, at the date of this part of the Diary,
he made Newbattle itself his more permanent abode.
The high public stations held by each,
their reputation for an undisguised and unselfish
regard to the interests of genuine piety,
their mutual abhorrence of those animosities,
which led many of the professors of that day to "`bite and devour one
another,`" might have occasionally thrown in contact these worthies.
And yet, with that lowly, retiring habit of soul which characterised them both,
and differing from each other on many important questions
which then agitated the most religiously disposed,
it is still matter of doubt, whether Jaffray had any interactions with Leighiton,
so as to derive light or comfort through his means.
We may, however, rest satisfied with the conclusion,
that though they saw not in all things "`eye to eye,`" yet,
in regard to much essential experience, they were learning in the same school,
endeavouring "`to walk by the same rule,`" and to "`mind the same
thing,`" even "`the law of the spirit of life in Christ Jesus.`"
To perceive in any striking degree this assimilation and accordance,
as in the quotation which has now been brought forward,
must be cordial to every lover of the church universal.
Such instances are cheering,
amidst much that still continues to sever and to scatter those,
who desire to love our Lord Jesus Christ in sincerity;--they
are symptoms of that harmonizing oneness,
which it was the blessed will of the Father should subsist among believers,
which the Son himself interceded for,
and which his Holy Spirit is fully able to bring about.

=== Note BB.

Jaffray seems to have imbibed such a sentiment as this,
much earlier in his religious progress,
than many who have made an eminent profession of Christian experience.
The Editor is pleased to be able to notice the similarity of view
taken by a well-known writer contemporary with our Diarist.

In a summary review of Richard Baxter`'s matured experience in regard to religion,
taken by himself towards the latter part of his life,
in which much enlargement of view and abasement of self is discovered,
we have the following sentence.--"`I less admire gifts of utterance,
and the bare profession of religion than I once did; and have much more charity for many,
who by the lack of gifts do make an obscurer profession.
I once thought, that almost all who could pray movingly and fluently,
and talk well of religion, had been saints.
But experience has opened to me, what odious crimes may consist with high profession.
While I have met with various obscure persons,
not noted for any extraordinary profession or forwardness in religion,
but only to live a quiet, blameless life, whom I have after found to have long lived,
as far as I could discern, a truly godly and sanctified life.`"

=== Note CC.

It would seem, by this paragraph, as if Alexander Jaffray`'s opinion then was,
that a believer could not, by grace, through watchfulness,
escape being actually polluted by sin,--that he must
carry about with him "`a body of sin and death.`"
With regard to the text here quoted, the Apostle`'s answer seems to follow his own query,
"`I thank God,`" or, as some render it,
(and Archdeacon Paley in one of his Sermons inclines to this translation,)
"`The grace of God through Jesus Christ our Lord.`"
No doubt, Jaffray came to see, and unite in belief with his fellow-countryman,
contemporary, and friend, Robert Barclay, that Paul here speaks,
not of his own condition of the time, but rather was personating that of one,
not yet fully arrived at an established state; especially, as in verse 14 he says,
"`But I am carnal,`" etc., and yet in chap. 8. verse 2, he avers,
that the law of the spirit of life in Christ Jesus
had made him free from the law of sin and death.
A similar mode of speech, the Apostle James uses, chap. 3. verses 9, 10.

=== Note DD.

At the latter end of this paragraph,
Alexander Jaffray makes allusion to a part of that very memorable and excellent prayer,
which the Lord Jesus was pleased, in condescension to the request of his disciples,
to give forth as a model for the utterance of their inward exercises towards God.
Whatever might, at this time, have been the sentiment of our Author,
with regard to the duty of using daily this precise form of words in prayer,
it is evident he supposed our blessed Saviour commanded
a daily recurrence to one subject of petition--namely,
the coming of the kingdom of God.
In justice, however, to those views which he subsequently adopted,
it seems needful to revive the language of his friend, Robert Barclay,
on this express subject.--"`We find,
that Jesus Christ the author of the Christian religion,
prescribes no set form of worship to his children,
under the more pure administration of the new covenant; save that he only tells them,
that the worship now to be performed, is spiritual, and in the Spirit.
And it is especially to be observed, that, in the whole New Testament,
there is no order nor command given in this thing,
but to follow the revelations of the Spirit,--save only, that general +++[+++one,]
of meeting together,--a thing dearly owned, and diligently practised by us.
True it is, mention is made of the duties of praying, preaching, and singing;
but what order or method should be kept in so doing,
or that presently they should be set about,
so soon as the saints are gathered,--there is not one word to be found: yes,
these duties are always annexed to the assistance, leadings,
and motions of God`'s Spirit.`"
Then, in a note, he subjoins--"`If any object here,
That the Lord`'s prayer is a prescribed form of prayer, and therefore of worship,
given by Christ to his children:--I answer; First,
This cannot be objected by any sort of Christians that I know; because,
there are none who use not other prayers, or that limit their worship to this.
Secondly, This was commanded to the disciples, while yet weak,
before they had received the dispensation of the gospel;
not that they should only use it in praying, but that he might show them by one example,
how that their prayers ought to be short, and not like the long prayers of the Pharisees.
And that this was the use of it, appears by all the prayers,
which many saints afterward made use of, whereof the Scripture makes mention:
for none made use of this, neither repeated it; but used other words,
according as the thing required, and as the Spirit gave utterance.
Thirdly, That this ought so to be understood, appears from Rom. 8:26,
where the Apostle says, We know not what we should pray for as we ought,
but the Spirit itself makes intercession for us, etc.
But if this prayer had been such a prescribed form of prayer to the church,
that had not been true; neither had they been ignorant what to pray,
nor should they have needed the help of the Spirit to teach them.`"
Apology, Prop. xi. sect. 10.

=== Note EE.

Andrew Cant, the father-in-law of Alexander Jaffray,
whose name has already occurred in the Diary, particularly, was minister at Newbattle,
near Edinburgh; but in 1640, becoming an appointed minister at Aberdeen,
he removed there.
When Prelacy was introduced at the Restoration,
he came again to the neighbourhood of Edinburgh,
his son Andrew being then the officiating minister at Libberton, close to the city.
They were both, according to Cruickshank, vol. i. p. 148,
summoned to appear before the King`'s Council in 1662,
in common with their brethren of the same persuasion;
but it does not appear that they suffered; on the contrary, the son conformed to Prelacy.
In Row`'s Supplement to Blair`'s Life,
Andrew Cant is described as "`very forward and zealous,
being of a fiery temper;`" which agrees with the account here given of him.

=== Note FF.

Caskieben is repeatedly mentioned in the "`Retours,`"
as being Alexander Jaffray`'s property.
He probably refers to some lawsuit respecting it, or to the sale of it; for,
in the Records of the Scottish Parliament in the year 1669, is a charter of the crown,
granted to "`Sir James Keith, of Keith Hall,`" (ancestor of the present Earl of Kintore,
who lives at Keith Hall,) "`of the lands and barony of Caskieben,
lying in the parish of Keith Hall.`"--Kinmuck,
where the Society of Friends still have a meetinghouse, is in that parish,
and very near the Earl of Kintore`'s residence.

=== Note GG.

"`Dr. Thomas Goodwin, whom Wood,
in the Athena Oxonienses denominates,`' one of the atlases and
patriarchs of Independency,`' was President of Magdalen College, Oxford.`"
He is represented, in the Memoir of the Life of Owen, "`as rather too high a Calvinist,
but distinguished for his piety, learning, and industry;
as the five folio volumes of his posthumous works bear ample testimony.`" p. 175.

=== Note HH.

The name of Swintoune, has already been introduced in a preceding Note,
as one of the representatives for Scotland to Cromwell`'s Little Parliament.
Although the present is the only place in the Diary wherein he is spoken of,--and here
but briefly,--there is reason to believe he was intimately acquainted with its Author.
He became, like his friend Jaffray,
early and firmly associated in fellowship with the despised
"`Quakers;`" and accordingly there will be found,
in the succeeding division of this Work, a few additional particulars respecting him,
as standing in that character.
On these accounts,
it may not be irrelevant here to bring together some very imperfect notices of him,
extending to the period when he joined the Society of Friends,
and chiefly taken from writers of that day.

The Biographia Britannica describes Swintoune "`as of a very good family;`"
and that he "`had as good education as almost any man in Scotland,
which joined to very strong natural parts, rendered him a most accomplished person.`"
But little has been met with concerning him,
previous to the coming of Cromwell`'s army into Scotland.
Before that period, however,
he stood member of the Scottish Parliament for the county of Berwick or the Merse,
in which the family estates lay; and according to Balfour`'s Annals, he voted,
in the Committee of Estates,
against the sending Commissioners to Breda to treat with Charles the 2nd,
as well as "`against a levie, when as the Parliament was informed certainly,
that Cromwell and a strong army of Sectaries were marching down to invade the kingdom.`" p. 80.
Independent of political views, it seems clear,
that Swintoune gradually became dissatisfied with the principles
and proceedings of the Presbyterian body in his own country.
Lamont speaks of him,
as "`one formerly cried up for his piety;`" and that he "`went in to the English army,
while they lay at Edenbroughe.`"
Diary or Chronicle of Fife, p. 32. The testimony in Row`'s Supplement to Blair`'s Life,
is similar, with regard to the time and manner of his acting,
and evidently marks him out as among the "`few formerly
accounted pious and gracious men,`" who,
he says, had deserted the cause of Presbytery as well as that of monarchy.
"`Some officers, shortly after Dunbar fight,`" Row observes,
"`having layed down their charges and gone in to the enemy,
(especially the young lairde of Swintowne, who, before the invasion,
was suspected to favour the enemy and some sectarian
errors,)--"`p. 88. He was excommunicated in 1651,
as the same MS. sets forth, by the Commission of the General Assembly at Perth;
but after this, in 1656, Nicoll`'s Diary relates,
he "`was relaxed from that sentence of excommunication,`"
"`without personal appearance`"--for what reason,
is not specified, although,--from a controversial pamphlet afterward published,
with the title, Some Sober Animadversions--this seems to have taken place,
"`without his desiring any such thing.`"

During the Commonwealth, Swintoune several times served in the Scottish Parliament,
was one of the Lords or Judges of the Court of Sessions,
and a member of the Council of State for the government of Scotland.
Nicoll again speaks of him in 1658,
as signing the proclamation of Richard Cromwell at Edinburgh, on the death of Oliver;
and shortly afterward, as being chosen member to Richard`'s Parliament.
He joined in a petition to that body, "`with the other deputies then in London,
who in 1652 consented to the union of Scotland with
England,`" "`for perfecting that union.`"
The following are the next passages in Nicoll`'s Diary relating to him.
"`Judge Swynton also, being repute to half secret correspondence with this Lord Lambert,
was taken notice of heir in Scotland, apprehended and secured in the citadel of Leith,
upon the 16th day of January, 1660.`"
"`July 20th, Lord Swynton was taken in King Street, out of his bed, in a Quaker`'s house,
and was brought to Quhytehall, and hereafter sent fettered to the prison of Gaithous,
where the thieves and robbers are imprisoned.
"`December, 21st. As for the Lord Swynton, he was also transported to Scotland,
and in the same ship with the Marques of Ergyll;
and went along with him through Edinburgh, being one person for falt and excommunicate.
The Marques was tenderly conveyed between two bailleis of Edinburgh;
but Swynton by the town officers, environed with thousands of people, men and women,
being one fanatic person and one Quaker,
and was committed to close prison within the Tolbooth of Edinburgh.`"
These circumstances are also related in Baillie`'s Letters and Journals,
and in Woodrow`'s History, but with less of descriptive point.
Bishop Burnet gives the outcome of his trial:
"`Swinton had been attainted in the Parliament at Stirling, for going over to Cromwell:
so he was brought before the Parliament, to hear what he could say,
why the sentence should not be executed.
He was then become a Quaker, and did with a sort of eloquence that moved the whole house,
lay out all his own errors, and the ill spirit he was in,
when he did the things that were charged on him, with so tender a sense,
that he seemed as one indifferent what they should do with him:
and without so much as moving for mercy, or even for a delay,
he did so effectually prevail on them, that they recommended him to the King,
as a fit object of his mercy.`"

A more modern and finished narrative of his case, drawn by the pen of Walter Scott,
who it seems was a descendant of Swintoune`'s,
shall close the present Note.--The Editor cannot, however, introduce this extract,
without acknowledging, in terms of sincerity and plainness,
the kind interest and attention manifested to him by the Writer of it,
on application being made for particulars respecting the families Swintoune and of Scott.

"`The celebrated John Swinton, of Swinton,
nineteenth baron in descent of that ancient and once powerful family, was,
with Sir William Lockhart of Lee,
the person whom Cromwell chiefly trusted in the management
of the Scottish affairs during his usurpation.
After the Restoration, Swinton was devoted as a victim to the new order of things,
and was brought down in the same vessel which conveyed the Marquis of Argyle to Edinburgh,
where that nobleman was tried and executed.
Swinton was destined to the same fate.
He had assumed the habit, and entered into the Society of the Quakers,
and appeared as one of their number before the Parliament of Scotland.
He renounced all legal defence, though several pleas were open to him,
and answered in conformity to the principles of his sect,--that,
at the time these crimes were imputed to him,
he was in the gall of bitterness and bond of iniquity;
but that God Almighty having since called him to the light,
he saw and acknowledged these errors, and did not refuse to pay the forfeit of them,
even though, in the judgment of the Parliament, it should extend to life itself.
Respect to fallen greatness,
and to the patient and calm resignation with which a man once in
high power expressed himself under such a change of fortune,
found Swinton friends; family connections,
and some interested considerations of Middleton the Commissioner,
joined to procure his safety; and he was dismissed,
but after a long imprisonment and much dilapidation of his estates.`"

=== Note II.

Owen`'s work On the Mortification of Sin in Believers was published in 1656.
"`It discovers,`" says Orme his biographer.
"`a profound acquaintance with the corruption of the human heart,
and the deceitful workings of the natural mind.
It is not the mortification of a voluntary humility,
or the infliction of self-devised and unnecessary pain, which it recommends;
but the gradual weakening and final destruction of the principle of sin,
by the operation of spiritual influence, and the application of Divine truth.`"
Memoirs p. 220.--The Treatise On Watchfulness,
must have been that entitled Of Temptation; the nature and power of it;
the danger of entering into it; and the means of preventing that danger, 1658;
being the substance of some sermons on Matt. 26:41.--"`Watch and pray,
that you enter not into temptation.`"--Memoirs, p. 501.

=== Note JJ.

Remarkable, certainly, is the coincidence between Alexander Jaffray`'s forebodings,
with regard to the prospects of the "`three nations`" at this crisis--thus developed too,
as they are throughout this paragraph, in a way of pious,
chastened meditation and secret prayer,--when compared
with the descriptions given by historians,
of that state of things which soon ensued.
Bishop Burnet in particular, in the History of his own Times, conveys,
briefly indeed but very sufficiently,
a realization of the apprehension of his fellow-countryman and contemporary, our Author.

"`With the restoration of the King, a spirit of extravagant joy spread over the nation,
that brought on with it the throwing off the very profession of virtue and piety:
all ended in entertainments and drunkenness,
which overrun the three kingdoms to such a degree,
that it very much corrupted all their morals.
Under the colour of drinking the King`'s health,
there were great disorders and much riot everywhere: and the pretences of religion,
both in those of the hypocritical sort,
and of the more honest but no less pernicious enthusiasts, gave great advantages,
as well as they furnished much matter, to the profane mockers of true piety.
Those who had been concerned in the former transactions,
thought they could not redeem themselves from the
censures and jealousies that those brought on them,
by any method that was more sure and more easy, than by going into the stream,
and laughing at all religion, telling or making stories,
to expose both themselves and their party as impious and ridiculous.`"
vol. i. p. 127. See also Neale`'s History of the Puritans, vol.
iv. p. 269.

=== Note KK.

This was the Committee of Estates.
Bishop Burnet, in allusion to this precise time, thus adverts to it.--"`In August,
the Earl of Glencairn was sent down to Scotland,
and had orders to call together the Committee of Estates.
This was a practice begun in the late times: When the Parliament made a recess,
they appointed some of every state to sit,
and to act as a Council of State in their name till the next session;
for which they were to prepare matters,
and to which they gave an account of their proceedings.`"
"`A great many offenders were summoned, at the King`'s suit,
before the Committee of Estates, and required to give bail,
that they should appear at the opening of the Parliament,
and answer to what should be then objected to them.`" vol. i. p. 155, 156.

=== Note LL.

James Simpson was minister at Airth in Stirlingshire.
"`He was a person of singular piety, considerable learning,
and a most affectionate and melting preacher.`"
Towards the beginning of the month called June, 1661,
being accused in Parliament by the King`'s advocate of seditious practices,
he was banished the King`'s dominions,
without being heard by the Parliament in his own defence.
He died in Holland.--Woodrow`'s
History of the Sufferings of the Church of Scotland, vol. i. p. 71.

=== Note MM.

In the Acts and Minutes of the Parliament of Scotland,
under date of "`the 16th of January,
1661,`" is recorded the following Petition of Alexander Jaffray,
together with the decision of the house upon it.

To the Lord Commissioner his Grace, and the honourable Estates of Parliament.

The humble petition of Alexander Jaffray shows,

That when your Lordship`'s Petitioner was required by the
Committee of Estates to subscribe the public bond,
your Lordship`'s Petitioner desired some time for getting of cautioners +++[+++securities,]
and satisfying himself anent the bond, which he heard was granted to others.
But this favour being denied to your Lordship`'s Petitioner,
he was upon the 20th day of September last committed prisoner to the Tolbooth of Edinburgh,
where he has remained ever since; albeit, within few days after his imprisonment,
having satisfied himself of the said bond, he offered to subscribe the same,
and did supplicate for liberty, whereunto he received no answer.
Through which imprisonment, your Lordship`'s Petitioner,
being of one infirm and valetudinarian condition,
his health is much impaired and life endangered,
for lack of his ordinary helps and free air,
as the certificate of two known physicians does make appear.

May it therefore please your Grace and the honourable Estates of Parliament,
to grant warrant to put your Petitioner to liberty,
upon caution for his peaceable deportment,
and to answer for his by-past behaviour when he shall be called,
as your Grace and the honourable Estates of Parliament shall appoint.

And your Lordship`'s answer the Petitioner expects.

+++[+++Signed]
Alexander Jaffray.

The Lord Commissioner, with advice of the Estates of Parliament,
ordains the supplicant to be put to liberty,
he finding caution to stay within the town of Edinburgh,
and not to remove forth thereof but by order of Parliament, under the pain of 20,000 lib.

+++[+++Signed]
"`Glencairne, Cancellarius, "`I. P. D. Pari.`"

The Lord Commissioner of Estates of Parliament,
gives hereby warrant and order to the magistrates of Edinburgh,
to set the person of Alexander Jaffray at liberty forth of their Tolbooth,
he finding caution to the Lord Register`'s sight to stay within
the town of Edinburgh until the Parliament`'s further order.`"

=== Note NN.

The following quotation from Skinner`'s Ecclesiastical History of Scotland, will,
in general terms, convey the occasion of the imprisonment of these individuals.
"`The Committee,
which had been appointed by the King`'s last Parliament at Stirling in 1651,
met on the 23rd of August, +++[+++1660, after his restoration]
to prepare matters for the Parliament; and by the King`'s order,
the Earl of Glencairn presided in it.
This convention, among other things,
gave orders to apprehend ten or twelve ministers of the Remonstrator party,
who had met at Edinburgh, and had drawn up a new remonstrance,
putting the King in mind of the Covenant,
which he had solemnly sworn when he was among them,
and declining his having any power or authority in the settlement of the church.
The Committee likewise summoned sundry suspected persons to appear before them,
and find bail for their answering in the next Parliament.`"--vol. ii. p. 446.
Among these ten or twelve ministers, Cruickshank, in his History, vol. i. p. 68,
gives the four names here mentioned, as well as that of James Guthrie,
concerning whom Jaffray next speaks; among the suspected persons,
the same historian introduces the name of our Diarist himself.
With regard to Guthrie, "`He was accused,`" says Bishop Burnet,
"`of accession to the remonstrance, when the King was in Scotland,
and for a book he had printed,
with the title of The Causes of God`'s wrath upon the Nation; in which,
the treating with the King, the tendering him the Covenant,
and admitting him to the exercise of the government were highly aggravated,
as great acts of apostasy.`"
He was executed on the 1st of the month, called June, 1661, and his head,
according to the sentence passed against him by the Parliament,
was affixed on the chief gate of Edinburgh.
Moncrief had nearly shared the same lot, but his life was spared;
yet he was declared incapable of exercising any public trust, civil or ecclesiastical,
and afterward underwent much hardship and persecution.
Trail was tried before the Parliament; and the next year was banished,
and went to Holland.

=== Note OO.

"`One Macquare, a hot man and considerably learned,
did in his church at Glasgow openly protest against this act,
as contrary to the oath of God, and so void of itself.
+++[+++This was the act asserting the King`'s power in treaties of peace and war,
in consequence of which the League and Covenant was condemned.]
To protest against an act of Parliament, was treason by their law.
And Middleton, +++[+++the King`'s Commissioner,]
was resolved to make an example of him, for terrifying others.
But Macquare was as stiff as he was severe, and would come to no submission.
Yet he was only condemned to perpetual banishment.
Upon which, he and some others who were afterwards banished,
went and settled at Rotterdam.`"
Burnet`'s History of his own Times, vol. i. p. 161.

[.asterism]
'''
