== Chapter II.

[.blurb]
=== 1664: Alexander Jaffray writes A Word of Exhortation, addressed to professors.

About this time, George Keith published a few sheets addressed _To those,
who passed under the denomination of the Church of Scotland,
especially to such as had once known a zealous profession,
but had then greatly degenerated._
On that occasion, Alexander Jaffray was induced to write a preface to this Address,
entitled,
"`A Word of Exhortation,`" stated to be "`from a lover of the true
interest of those to whom it is directed,`" and signed by himself.

This faithful and feeling expostulation of our Diarist,
shall here be transcribed nearly at full length.
It conveys, in beautiful but true colours,
_the nature and ground of that spiritual testimony,_
which both he and his associates were eminently concerned to bear.
There may also be plainly seen, in this paper, one evidence,
in addition to those that have gone before, of that heavenly love, meekness, and charity,
with which the soul of Alexander Jaffray was replenished to the end of his course.

Whatever be our views of the deficiencies apparent in the style of writing of this period,
especially religious composition,
and even of authors whose advantages were by no means small; yet,
if we wish to reach beyond the surface of things,
and to appreciate what is of truth and wisdom, we must patiently dig into the mine.
We shall often feel ourselves amply repaid for our honour;
in meeting with that richness and depth of thought, which, indeed,
seemed to have occasionally carried some of these
authors far beyond the niceties of diction.
This remark may not be thought particularly applicable to the present instance;
but it applies to many productions written by early members of the Society of Friends.
They cared not to please the vain mind and corrupt taste in any;
but their aim was to _satisfy the longing soul,_
to _reach the witness for God in every conscience;_
believing in the practical import of that saying of Solomon`'s,
"`The full soul loaths a honeycomb;
but to the hungry soul every bitter thing is sweet.`" Prov. 27:7.

[.embedded-content-document]
--

[.blurb]
=== Jaffray`'s Word Of Exhortation.

How is it that you do not yet discern this time?
how long will you shut out the discoveries of it,
and thus provoke the Lord to shut you further out from beholding them?
O fear, fear to be found any more in that guiltiness, which, if persisted in,
may shut you out even forever!
And let none so look on themselves, as to suppose they are past this hazard,
if they yet continue neglecting, opposing, and persecuting,
or approving those who persecute, the growing light of this day,
as it is come and coming forth, even with power and great glory.

Truly, Friends, think what you will,
the chief thing in the controversy that is between God and you,
is this;--your keeping up men`'s traditions in place of the true institutions of Christ,
while he now so evidently comes forth to vindicate and restore them--your adhering to,
and preferring the oldness of the letter to the newness of the Spirit; which first,
indeed, had its glory, but is not comparable to _this_ which excels.
Think not, that such a case and state of things as was in the primitive days,
ended with those, who were so zealous for, and unwilling to part with,
the law and the outward ministration thereof in the letter.
No, Friends; consider seriously of it in the fear of the Lord;
lay by your passion and prejudice, for it nearly concerns you;
consider of it in soberness, and you shall truly find it _your_ very case at _this_ day,
as _then_ it was _theirs;_--that same spirit acting now, as then,
for the outward ministration, in opposition to the inward,
and more heightened in its actings now than ever.
O when shall that be dead to you, or you to it,
wherein you have been so long held from beholding the glory of the Lord,
as it comes forth in the work of this day!--And how contrary to,
and inconsistent with it, was that work, which by might and power you were leading on;
though you had attained what you proposed,
in the furthest and highest extent of that Uniformity,
which you so endeavoured to have imposed upon all.
Are you not yet sensible of your mistakes and snares in these matters,
so as to be made willing to glorify God, (as some of you have, it may be,
ingeniously gratified men,) with a humble confession
of your over-reachings and other guiltiness,
brought upon yourselves and the people of these nations?

Many times has it been in my heart thus to have spoken some few words unto you,
as unto those whom I dearly love in the Lord, and to whom I stand by many bonds obliged,
if in any service I could be useful.
But, being somewhat sensible what _I_ had to do in my own particular case,
and not altogether unacquainted with the deceit of the busy enemy,
who in this day lies so near, ready to draw out the mind to vent its own imaginations,
and to speak of the things of God without his warrant; I have hitherto withheld,
in expectation of a more fit occasion, which, on the perusal of the ensuing papers,
was very clearly given me.
And indeed, the subject spoken to, and the truths inserted in them,
had been some years ago much on my heart,
and seriously inquired after;--and that this inquiry and search was of the Lord,
attended with a blessing to me, I can very clearly testify;
and finding the same things for the most part,
so sweetly and with such a spirit of meekness offered unto you,
I see it only my duty at present to be concurring in my testimony,
agreeing fully with what is said in them,
as being most fit and necessary to be seriously minded by you.

Dear Friends, it is high time for you to awake, and to consider what you are doing:
there is another thing to be brought forth in this day than you have yet conceived;
your guiltiness for opposing it, is greater than you are aware of; nor,
if you so persist in the way of provocation,
will your apparent zeal for God and his ordinances serve the turn; although I do think,
it has hitherto lain very near the hearts of some of you,
where singleness of heart in any measure yet remains.
Consider, if something of the same snare and temptation be not on you,
as was on them who so zealously contended for Moses and the prophets;
the same was their plea, and upon the same grounds did they go on,
to the rejecting and crucifying of Christ, as you,
(some of you ignorantly and others more perversely,) are at this day in the way to do.
Bear with my freedom; for, truly I can say it,
there is no bitterness nor passion at my heart, while thus I use it;
but the deep sense of the dreadful hazard you are running, has drawn it from me; that,
if so, in the will of the Lord, you may return to your first love,
and again embrace the _Guide of your youth;_ the missing and departing from whom,
has always been the cause of the shortcomings and mistakes of our fathers,
the first Protestants, as well as of ours, with regard to the work of God.
These, indeed, were not in everything come to own their true Guide;
though in some things they did it, and, according to the simplicity that was in them,
they were sweetly ordered by him, and accepted of him.
Thus was it with them; thus also has it been with many who succeeded them;
and was it not so, of late, among us also?
yes, it was eminently so, both in Scotland, England, and Ireland?
In this, mainly, is our great guiltiness exceedingly aggravated,
even beyond what was theirs;--that, although the discovery of this duty,
of _waiting to find the immediate direction of our Guide in everything,
as absolutely necessary,_ has more clearly come forth,
and at a time when this guidance is more fully bestowed than formerly;
yet is it now (dreadful to think of) more than ever
disowned and persecuted;--and by those very persons,
whom I well knew to have sometimes sweetly enjoyed the blessed
effects of the Spirit`'s immediate teachings in themselves,
and thus to have been instrumental to the great advantage of others.--Such wonderful
and astonishing effects do the deep and fiery trials of this day bring forth,
when every work of man is to be consumed, as well the gold and precious stones,
as the wood, hay, and stubble!
That which is born of the flesh is but '`flesh;`' even that which
is begotten _only_ through the knowledge of Christ after the flesh,
must be left behind and parted with, else the Comforter cannot come;--in this way,
the fruitful field may become a wilderness,
and the wilderness and solitary place a fruitful field;--thus it is,
_the Lord alone may be exalted in this day, and all flesh must be low as grass before him._

Let, therefore, the dread and terror of the Lord seize upon all,
especially the professing people of this generation;
that they may no more transgress in this thing,
_of despising or neglecting the immediate teachings of his Spirit,_--this
'`key of knowledge,`' which the lawyers '`have taken away,`' Luke 11:52,
this little '`stone`' which must '`fill the whole earth.`'
Dreadful is the judgment that is to be met with by such,
whatever they be, who shall still be found refusing to receive Jesus Christ,
thus coming to his kingdom in their hearts! and what, then,
shall become of those who shall be found _rebelling_ against
'`the true Light,`' so as to mock and persecute it?

Dear Friends, as you love your peace and safety, beware of this;
for it borders too near upon that guiltiness _+++[+++of speaking against the Holy Spirit,]_
which '`shall not be forgiven, neither in this world,
neither in the world to come.`' What,
need you to be so afraid at the coming of Christ to his kingdom,
that _so his will may be done in earth as it is done in heaven?_
has it not been the matter of your prayers many a day, and do you well to be angry,
when it is so gloriously coming to pass?
O! how can this become you ill, to desire,
with _him_ who so long since wished for and rejoiced at it,
_that all the Lord`'s people were prophets,
and that he would pour out his Spirit upon them?_
This would not have wronged, nor diminished anything from _his_ ministry _then,_
who was so eminent; nor will it _now,_ from the true ministers of Christ.
Those who make but a trade of preaching, thereby to win their living,
as other tradesmen do,
it is no marvel to see them very angry at the approaching glory of this day.
'`If every one is to have the Spirit, and be permitted to speak publicly,
what shall then become of our ministry,`' say they,
'`and how shall we live?`' And though there be some, yes, there may be many among you,
who upon this account do not own these men, nor this plea for their pretended ministry;
but it may be, really think in your hearts, that, were there no other thing in it,
you could with Moses wish for and rejoice thereat,
even that all the Lord`'s people were prophets;--pleading,
that it is a _gospel_ ministry and maintenance you stand for, and no other; and this,
being an institution of Christ, which you now perceive to be so struck at by the Quakers,
you may not so part with it.
Yet consider seriously of this matter, and it will not be found so, either on your part,
or on theirs whom you with the world in scorn call Quakers:
for we do really own both a gospel ministry and a
suitable maintenance according to the Scriptures;
and you do neither own the one nor the other, but in words only.
For, though you seem to disown those men,
who seek after the ministry and the standing of it mainly on account of their hire; yet,
consider it seriously, if on this matter you do not the very same thing with them,
and harden them in their guiltiness, and the people in their prejudice, against us;
while, by your profession and practice, you justify an imposed and forced maintenance,
which is so well known to be contrary to the gospel, and condemned by your predecessors,
and many others of the martyrs and servants of God.
And again, however you pretend to be for a gospel ministry, it is not so; no,
you are downright opposers and persecutors of it:--and,
alas! that I should have cause so to speak.
Can you produce any institution of Christ`'s for justifying a ministry,
which cannot be maintained,
but as descended through a line of succession from the great enemy of Christ;
and for keeping up of which, a door must be set open even for the ungodly.
For, it is plainly affirmed by many of greatest note among you,
that _grace_ belongs only to the _well-being,_
and not to the _being_ of such a ministry and ministerial
qualifications as are required by you:
see [.book-title]#Durhame on the Revelation Concerning Ministerial Qualifications,# page 199. And,
where it is thus, a door is set open for an ungodly man to enter,
if he be furnished with gifts of human learning; and closely shut upon another,
however he may be known to be eminently pious,
and well furnished with spiritual knowledge and gifts of the Holy Spirit.
Is this your gospel ministry?
And yet, thus it is,
according to the acts and appointments of your (supposed) most pure and incorrupt assemblies,
that have been of late: so far are you in this also become contrary to your predecessors,
who both by their practice and profession affirmed,
_that every faithful man and woman was a priest;_ this is fully testified to,
both by [.book-title]#Knox`'s Chronicle,# and _Spotswood in his History,_ 2nd book, p. 60. Are you not,
therefore, ashamed any longer to own such a ministry?
O Friends! comedown, and lie in the dust; for,
greatly has the Lord been thus provoked by you,
and lamentable is the case of the people of these nations,
who are perishing in their sins,
because of such a ministry,--such leaders of the people so causing them to err.

And if it be here asked, What is that ministry, and what are the qualifications thereof,
which the Quakers require?
To this I need say but little;
the author of the ensuing papers having fully and faithfully spoken to it,
and various other particulars; whose testimony, if not made use of,
will one day bear witness against you; as well against the multitude of time-servers,
who go along with everything, as of others,
who at present are under some sort of suffering (though in part) for a true testimony,
given in some particulars,
yet no ways answerable nor suitable to what is required in this day.
And all of you, in your several interests and capacities,
as you stand related to the Kirk of Scotland, as it is styled,
and to the pretended work of reformation, are very much called upon,
seriously to mind what is therein said unto you; and then,
the thing intended may very clearly appear,--that
hitherto you have been honouring but in the fire,
as to producing any work of reformation which God allows of; yes,
and going rather backward from what was once attained to,
losing and plainly contradicting the true and honest principles of your worthy predecessors:
which one thing, rightly considered, may evidently demonstrate to you,
that your work has not been, nor is, of God.
The presence of God having been very evidently with the author of these papers,
in his inquiry after these things,
this his service may be very useful for you;--and
will be so found and acknowledged by those,
whose eyes shall be opened to behold, how the Lord comes forth in this day of his power,
to try every work of man, and _by the foolish things of the world to confound the wise._
And as to what is there said on that particular,
respecting the qualifications of a true minister,
I shall only add these few words:--That which was so necessary from the beginning,
that which we have heard, and seen, and handled with our hands,
of the Word of life,--even the power and presence of the Lord in his people,--do we,
whom in scorn you call Quakers, declare unto you,
as the only essential qualification of a true minister of Christ.

And if this be it, you are so afraid of, that through the increase of this,
_the spirit of prophecy,_ the true church and ministers of Christ shall suffer loss;
your fear upon this account is groundless;
for only in _that_ way must these stand and prosper,
so as that the gates of hell shall never prevail against them.
But, if your fear be for the fall of that supposed church, which _they_ (the hirelings,
I mean,) and _you_ so contend for, both among yourselves and with others,
(which is truly antichristian and no better;)--then, undoubtedly,
your fear is coming upon you.--And for preventing it, as you may think, it is no marvel,
that you so fall in with them for the defence of Rome and her ministry; or else,
(as some, who have been and yet are famous among you,
have both spoken and written,) that you must not only lose your church and ministry,
but your baptism and the Bible also.
The witness of God in your consciences cannot but tell you,
how much you did once detest and abhor to say or think so; until of late,
your skirts are discovered and your heels made bare,
through the growing light of this day, in these and many other points of the like nature,
and your way is so hedged up of the Lord,
that you cannot escape,--either to own Rome as your mother church,
and so return to her again,
or fully to part with and come out of her forever;--__and
from there not to bring with you a stone of hers,
either for a foundation to Zion, or for a corner.__
No, Babylon _must_ not be; you have been for a long time endeavouring otherwise;
but she _must_ be destroyed forever; agreeably to that of Jeremiah 51:9,
'`We would have healed Babylon, but she is not healed: forsake her,
and let us go every one into his own country; for her judgment reaches unto heaven,
and is lifted up even to the skies.`' And the time of her judgment draws near; and yet,
neither the church, nor ministers of Christ, nor the true baptism,
nor the Holy Scriptures of truth, nor any other of his true ordinances,
shall thereby suffer loss;
but great and glorious advantage will be to those who wait for it.

And because there are some, with whom I have had sweet fellowship in the Lord, who,
it is very likely, would have expected some other thing from me,
than such sharp and peremptory expressions and conclusions,
both against them and the way of the Kirk of Scotland, as they term it,
in which I was bred with them, and had my beginning in the way of godliness;--now,
to speak shortly a word to this.--I am not without hope, that a day is coming,
(and frequently have I sought it of the Lord on your behalf,)
when you shall come to see the truth of what I say,
and the necessity which was on me for it on your account;
even so as that you shall willingly acknowledge,
it was the greatest evidence of my dear and tender love in the Lord towards you, which,
next to his glory, led me to it; and that, otherwise,
I should be lacking in the expression of that true and sincere love,
which I still have towards you.

As to the advantages I have found in owning these despised people, called Quakers,
I need say but little,
if what is contained in this and the following pages be considered.
I know, indeed, it is my place to lie low in the fear of the Lord,
and to speak but little as to advantages, or any progress that I have made;
and I acknowledge, no man has more matter so to do; yet, in this case,
I may not be silent, but must, in the fear of the Lord,
thus give my testimony to this precious people,
and the truths of God asserted by them,--that they do truly and
really both profess and practise the new and living way,
in which holiness is attained, by mortification and subduing a body of sin and death;
having indeed come to the discovery of these things, even in the life and power,
which throughout the dark night of apostasy has lain much hid,
and has been but very little felt or known.
Such is the goodness of God to that precious people;
(count of them and call them what you will,) the power of
life and holiness is more truly known among them,
and eminently held forth by them,
than by any people else that have come forth since the apostles`'
days;--and a greater measure do they yet wait for,
and as they are faithful, it will be multiplied on them;
for the presence of the Lord is with them,
and all their opposers must fall +++[+++yield or give way]
before them.

Dear Friends, consider then, how far you have been mistaken concerning them,
being carried on with groundless jealousies and prejudice against them,
as though they were grossly erroneous, blasphemous, and the like.
No, no, Friends, it is not so; and upon search, you shall find it far otherwise;
let your informers (many of whom sinfully take things on report without trial,
and others, for the maintenance of your own interests,
_have made lies their refuge_)--let such say what they may,--this people is,
and will be found to be, a blessed people; who, as instruments in the Lord`'s hands,
may be called _the repairers of the breach, and the restorers of the paths to dwell in._
+++[+++see Appendix, I.]
They dearly own and rejoice in the use of the Holy Scriptures,
and desire to live up to the practice of all the truths of God declared in them.
Beware, then, what you say or think of them,
and that you approve not in the least their persecutors.
And if, as yet, you cannot receive what they offer,
yet beware to reject or to judge of it, because you cannot as yet close with it;
the time may come, when you shall both see and receive it.
If _the work_ they are about, _be of God,_ (as undoubtedly it is,) then it must prosper;
beware therefore to be found any more opposing it,
_lest you be found also fighters against God._

As for me, I am but a child, and as one of yesterday;--yet, through grace,
I am what I am: and although I own that state wherein I was, when I walked with you;
(for, truly, I can say, there was a measure of singleness and sincerity within me in it,
and therefore I _may_ not disown it,--__nor any,__ while they so continue there,
if they be not willfully opposing further discovery;)--yet, this I verily know,
and can truly say, I then was, and now am, called of the Lord _to go further,
forgetting the things that are behind,
to press forward for the prize of the high calling of God in Christ Jesus._
This is what I aim at: and what, through the help of my God,
as I keep faithful to what I know of it,
I have hope more than ever to attain,--even in _that_
way so much slighted and despised by you.

Now, that I may come to a close; I have but a few more words to say,
to such of those to whom these papers are directed, _who are gone beyond the sea,_
if at any time this shall come to their hands:--it is,
to desire them in the fear of the Lord to consider seriously
what is herein in particular said unto them;
and if, without prejudice and in soberness, they wait for it,
I am hopeful it shall be said unto them,
'`How did you come here, and what are you doing here,
_seeking to uphold that which I am pulling down,
and to bear down that which I am setting up?_
this is not your proper work: return from where you came,
and it shall be shown unto you.`' +++[+++see Appendix, J.]

Dear Friends! (for so you are to me,) whether you will hear or forbear,
yet know of a truth, I speak not unto you without a warrant.

[.signed-section-signature]
Alexander Jaffray.

[.signed-section-context-close]
Written in the 11th month, 1664.

--
