== Chapter VI.

1672: The "`clergy`" and magistrates of Aberdeen, further incensed against this people,
procure the demolition of the walls of their burial-ground,
and the disinterment of their dead--Letter of William Dewsbury,
John Swintoune and Robert Barclay imprisoned at Montrose,
together with some Friends at that place, for holding a meeting:
their address to the magistrates--1673: Andrew Jaffray convinced,
and several more--The provost and magistrates of Aberdeen strenuously
importune the king`'s council against the "`Quakers`"--They are
examined and fined--Hugh Neilson`'s disappointment of the fines,
by a proclamation of the government--Death of Alexander
Jaffray--His wife`'s convincement and death.

In a preceding page,
allusion was made to the defective state of moral and religious feeling,
so variously developed in the history of the times now under notice.
In connection with this subject, one sad illustration is here to be introduced,
of the length to which men may be carried,
when they release themselves from the obligations of Christianity and a civilized state.

About the beginning of the year 1672, several persons both in Aberdeen and its vicinity,
withdrawing from the religion established by law,
the public preachers of the city were so incensed as to procure,
by their influence with the magistrates,
the pulling down and demolishing the walls of a burial-ground,
which the people called Quakers had purchased with their own money;
and wherein a child of Thomas Milne had been a few days before interred.
The body of this child, after three days`' interment, was,
by order of the provost and bailies, taken out of the ground,
and carried to a village called Futtee, or Foot of Dee,
where they had a grave made for it.
But a rumour being raised by some malicious persons, as if Friends had,
to deceive the magistrates, taken out the child`'s body,
and filled the coffin with somewhat else, they ordered the coffin to be broken open;
in doing which, the corpse was injured,
and actually was made to bleed though so long dead.
In the same year in which this piece of wanton inhumanity was acted,
an unusual mortality is stated to have taken place among the children of that place,
such as had not occurred in the memory of any person then resident there.
The very next day after the raising of the body of this child, it so happened,
that John Scott,
one of those magistrates who had been the most active instrument in this affair,
had his own favourite grandchild unintentionally killed by the servant,
which occasioned much outcry of distress in that family.
Going on in his usual course of wickedness, among similar acts,
often causing the walls of the burial-place and premises to be pulled down, etc. he was,
shortly after, suspended in his career by a fall which fractured his leg.
They, nevertheless,
continued to remove every corpse that was interred in the same ground;
nor did the barbarous practice cease,
till a representation being made to the King`'s Council, a secret check was given them,
and this more than ordinary inhumanity put a stop to.
+++[+++see Appendix, Q.]

In the latter part of this year,
Alexander Skene produced at the Monthly Meeting a letter,
addressed to Friends in Scotland, from William Dewsbury;
the minister by whose instrumentality, it will be recollected,
Alexander Jaffray and others at Aberdeen, were first induced more fully to adopt,
as well as publicly to avow in that city, the principles of Friends.
Without doubt,
there were not any likely to appreciate such epistolary counsel more duly than these,
who could regard the writer of it as their spiritual father, one that,
to a certain extent,
had in Christ Jesus begotten them through the gospel,--themselves
also as his work in the Lord.--A copy of the letter is preserved,
as follows.

Warwick, 29th of 8th month, 1672.

My dear Friends,

All watch and wait in the light of the Lord, that every thought be judged down,
that is contrary to the light;
then will the cross be laid to the ground of your own thoughts,
and the true baptism of Christ +++[+++be]
known, which will bury you in such deep humility and sense of the free mercy of the Lord,
+++[+++as]
to raise you up in the living faith, to reign over your own thoughts and wills.
Then will you be born again into a pure subjection to the pure light, +++[+++to the]
thoughts and will of God,
which is our sanctification and perfection of glory manifested within us, etc.:
and so will you witness the new and holy birth, which makes self of no reputation,
neither boasts in anything it does; but follows the Lord in his pure leadings,
to serve him and his people in love, in whatever he calls into,
to the perfecting of his praises, and the comfort of his people forever!

In which life, feel the yearning bowels of your brother towards you,
who are truly poor in spirit; for, the unspeakable mercies of the Most High God,
is your inheritance forever!
The Almighty God keep all your garments clean in his holy power, and in it exercise you,
to the building up one another in your most holy faith; that, in the pure chaste love,
you may grow up in the unity of the spirit and bond of peace,
to shine forth as the morning stars to enlighten the people in that nation.
Oh! be faithful, my dear Friends; for the Lord has a great people in Scotland;
for whom I, with many of our brethren, have travailed, in jeopardy of our lives,
in years past, casting our bread upon the waters, with hopes to find it after many days.
And seeing God has called you to be the first fruits, and to make you a blessing,
as you wait to be ordered of the Lord,
as before written,--then will my great expectation
be answered in the behalf of the holy Seed,
whom my soul loves in that land,--and remains your dear brother in the light, thoughts,
and will of our God forever!

William Dewsbury.

Read this in the fear of the Lord,
and send copies among the meetings of his holy people in Scotland.

A transaction recorded in manuscript,
as having taken place in the course of this year in the neighbourhood of Montrose,
should here be brought into notice.--John Swintoune, who had been in the north,
and was then on his return southwards, in conjunction with Robert Barclay,
had it on their minds to be at the meeting of Friends belonging to Kinnaber and Montrose,
which was proposed to be held at the latter place on the 8th of the 10th month,
being the First day of the week.
The circumstances in which this little company then stood, were as follows.
There had been for some years a meeting for worship kept up at Kinnaber, near Montrose;
but, the views held by the Society coming to be adopted by some persons at Montrose,
it was deemed desirable, they should occasionally assemble in that town.
During the space of at least two months before,
most or all of these Friends had been detained in prison,
on account of this public testimony towards God;
but by an order from the King`'s Council at Edinburgh,
their freedom had been just then acquired.
So that they were about to evince,
on this the first occasion that presented after dismissal from confinement,
their grateful sense of allegiance to the Majesty of heaven,
by humbling themselves before His presence,
who had granted them support and deliverance in the time of trouble.
Thus situated, J. Swintoune and R. Barclay came to visit them,
and lodged at William Napier`'s, where the meeting was to be held the next day.
They met accordingly, and enjoyed a good season together in solemn worship;
undisturbed by the magistrates, although they had declared,
they would recommit the Friends whenever they assembled after that manner.
Having separated and mostly withdrawn, the town officers entered, saying,
that they had orders from the magistrates to detain them there,
till their own worship should be over, it being then near three o`'clock.
About an hour after this, William Napier, the master of the house,
was called for to the council-house, where the magistrates were then met.
J+++.+++ Swintoune and R. Barclay did not think fit to forsake their host,
though the officer endeavoured to prevent their accompanying him.
On this, they asked him, if they also were prisoners?
he said, No: they were not called for.
J+++.+++ S. and R. B., however, went forward.
William Napier being called up, the magistrates demanded,
Whether he would still trouble their town?
He asked, Wherein?
They said, In having meetings in his house.
He, without confessing or denying the fact, said,
He hoped there was no law against the worship of God, and that this could be no crime.
They told him, He was to go back to prison, from which he had been so lately released.
J+++.+++ S. and R. B., having intimated their desire to speak to the magistrates,
were next called; upon which the former,
not knowing their decision with regard to Napier, addressed them to this effect:
That he and his friend, coming to town the night before,
were resolved to stay the next day, being the First day of the week,
and took up their quarters at W. Napier`'s house.
On which occasion, several of his friends were there; and how employed,
any of the magistrates might have been witnesses, had they been so disposed;
but his friends,
being about to repair to their respective places of abode on their lawful occasions,
were detained by their officers.
The provost said, They had been at a meeting, which was contrary to law.
J+++.+++ S. called upon him to prove this, as they were not about to accuse themselves.
The provost said, They were not going to dispute with them; and,
without going aside or consulting with the rest, told them,
They also were to go to prison; for it was clear, they were at a meeting;
and if the Friends thought themselves wronged, they might complain against them.
J+++.+++ S. told them, Their being sent to prison was a preconcerted measure,
and reasoned with them on the injustice of their proceedings, desiring them,
for their own sakes, to consider further what they were doing,
now that they had heard what he and his friends had to say; else they might repent it,
if they sent them to prison.
On this, the magistrates seemed to hesitate, and conferred together;
but quickly returned, repeating, They were to go to prison.
After some further demur, the Friends told the magistrates,
They were not afraid of their prison;
that the weight of their proceedings would come upon themselves,
and reflect on their justice.
They replied,
It would but cost them an application to the King`'s
Council for their release;--thereby meaning to reflect,
(it was thought,) on J. S., by whose means the former release had been procured.

"`On the 12th,`" to use the language of their record,
"`we found it with us to send a letter to the provost, bailies, and Council of Montrose,
a copy of which hereafter follows; and now, at the writing hereof,
being the 21st of the 10th month, we are in prison, quiet, and in much love together;
our way being hitherto hedged up from making any application
to those in supreme authority in this nation,
were it but to represent the iniquity and injustice of these men`'s proceedings,
who are filled with wrath, malice, and envy against the Seed, Christ,
and those that are in Him.
+++[+++Indeed]
we have notice, signified under the hand of one that is somewhat friendly,
that they have threatened, (in case the King`'s Council shall release us,
which they think likely,) to send men in disguise into our meetings to break our bones.
But the Lord is with us, and is on our side;
and we are filled with quietness and contentedness here: glory to his name, his arm,
his power, forever, who has done it!--and, indeed, it is well with us!
And this is written for the satisfaction of Friends and others,
to whose hands it shall come; desiring to be remembered by all Friends,
as the dear remembrance of them is with us,--yes,
of all the Friends of Truth and followers of the Lamb, far and near.
And it is our purpose and resolution, in the strength of the Lord,
not to go from off this place, but as clear men; being in all six, namely,
John Swintoune, Robert Barclay, William Napier, John Milne, William Low, James Nuccoll.`"

The following is a copy of the letter above alluded to,
addressed by them to the magistrates of Montrose--a nobly-toned and touching appeal,
at once exhibiting the fortitude and patience with which Christianity would invest us.

Friends,

Our case being as it was, and as some of us fully represented it to you,
how could you in justice deal with us as you have done,--in the middle of winter,
to send us, whose occasions lie elsewhere, to a cold and desolate prison?
Well! the just God beholds your injustice and oppression; iniquity lies at your door,
and we are to lay it upon you, and to charge you in the name of the Lord God,
that you beware for the future to be found in such practices, and,
in the sense that you have done evil herein, be resolved to do so no more; that,
if possible, your iniquities in this and the like cases,
(for this is not the first,) may be forgiven you.
As well, also, the thoughts of your hearts,--which are,
to banish Truth and a true people out of your coasts, or to vanquish them,
by tempting them to unfaithfulness, and to forsake that testimony,
which they are to bear among you--which they must bear, and cannot forbear it.
You have undertaken, with many of this day, to raise the burdensome stone,
which many have found too heavy for them, and many have dashed themselves upon it,
and many have been ground to powder by it, whose remembrance is as a stink in this day!
And therefore, be warned, to take heed, and consider in time what you have done, that,
if possible, you may find a place of repentance, and do so no more.

As for us, we are not afraid of you, nor ashamed of our testimony,
and you cannot vanquish us.
You imagine a vain thing, and you will herein weary yourselves with very vanity.

Now, whereas you may think to cover yourselves with this +++[+++plea:]
'`We are but inferior magistrates; and we must obey the laws,
that require us to suppress conventicles, and to punish conventiclers.`' Well,
it is confessed, you are but inferior magistrates,
and therefore have not an arbitrary power; but are to proceed according to law,
when you proceed--though they were found blameable,
who walked willingly after the unjust commandment, Hosea 5:11. But,
let the laws be what they may, you have proceeded herein without and contrary to all law,
and shadow of it; and have therein manifested your injustice,
and the unreasonableness of your proceedings,
through your malice against the Truth and its friends.
And herein lies the weight and depth of your iniquity;
in which you have manifested yourselves and your spirit,
and may procure the plagues and judgments of the Lord to be poured upon this town,
and many may come to feel the smart of your doings.
Verily, we were ashamed on your behalf, in the instant of time,
and on the behalf of our native country; that, in a place so considerable as this,
you should demean yourselves so unjustly, so palpably,
having no shadow of a rational cover for your proceedings.

Well! we ask nothing of you, but that you come to a sense of your past way,
that you may not fall into the like for the future.
And as for us, we are well contented to stay here,
until the due time of our deliverance come; and our expectations,
(be it known to you,) are neither from the hills nor from the mountains,
but from God alone.
Our case is committed to Him who judges righteously!
We are, as regards our testimony and for its sake, well contented, well pleased,
well satisfied, to be here; our bonds are not grievous to us:
glory to the Lord forever!--who has not, who never will fail us,

John Swintoune, Robert Barclay, William Napier, James Nuccoll, John Milne, William Low.

We are not informed, in the above record,
how long these sufferers for the testimony of a good conscience, were thus detained,
or by what means their liberation was effected;
although it may be presumed this was brought about soon after,
as a minute of Aberdeen Monthly Meeting,
states the release of John Swintoune to have taken place early in the 11th month,
in consequence of an order from the King`'s Council,
and that he was then on his way to Edinburgh,
with the view of laying the case of his friends in general before the government.
+++[+++see Appendix, R.]

The convincement of Andrew, son of Alexander Jaffray,
and that of several others of Aberdeen and parts adjacent,
about the beginning of the year 1673,
afresh excited the indignation of those termed the clergy.
At their instigation, the provost, and others of the magistrates,
came to a Monthly Meeting held by Friends, on the 6th of the 3rd month,
and took the names of all present, both men and women;
this list they forwarded by William Gordon, their agent, to the King`'s Council,
charging him with instructions,
strenuously to importune the Council against this peaceable people.
His business, as it appears, he executed with the utmost assiduity.
But shortly after, it happened,
that he went down from Edinburgh to Leith to hear a sermon; and, in the time of it,
going out of the place of worship, he was presently after found dead.

Upon the solicitation of this William Gordon, the Council, on the 1st of the 5th month,
sent a summons to nineteen of this people;
who accordingly appearing before them at Edinburgh on the 10th,
after two sittings of the Council, were fined,
and their several fines assigned to one Hugh Neilson, an apothecary of that city.
While he was busying himself in a process at law for recovering the fines,
the King`'s Commissioners and Council issued a proclamation,
remitting all penalties and fines for nonconformity, except such as were already paid,
or engaged for by the parties`' bond, or other security.
This cleared the people called Quakers; for their principle was,
neither to pay the fines, nor in any wise to compound for them;
their strict observance of which, entitled them to the benefit of the above proclamation,
and disappointed Hugh Neilson in his attempts against them.

Previous to the issuing of this proclamation,
some of the Friends who were likely to be sufferers by the endeavours of Hugh Neilson,
addressed him a letter, dated the 30th of the 7th month;
in which they strongly pleaded their innocency of any crime,
for which in justice they ought to be fined,
urging their conscientious objection to fulfill his demand, and warning him,
in solemn language, to "`despise the gain of oppression.`"
This paper is signed by Alexander Skene, David Barclay, and others.
It is further stated, that this person was so wrought upon,
either by the letter above alluded to, or which is more probable,
by his own utter disappointment of his prey, that he exclaimed,
he should never trouble the Quakers more,
for it was unhappy to have anything to do against them.

Thus did the Lord, who is the keeper of his people and their shade upon their right hand,
remarkably appear in many instances of his protecting
care towards those that trusted in him,
some of which are not here enumerated.
While, therefore, the Scriptural language is grievously true of many wicked,
"`When your hand is lifted up, they will not see;`" yet are there in all ages,
such ample proofs of providential interposition and disposal of events,
as should certainly tend to bring about, in the hearts of those not yet utterly hardened,
that blessed crisis, when "`all men shall fear, and shall declare the work of God;
for they shall wisely consider of his doing.`"

We are now to approach the close of Alexander Jaffray`'s career,
whose religious experience, developed in his Diary,
has occupied so large a portion of this Work,
and may be considered as having opened the very root and
ground of the rise of the Society of Friends in Scotland.
On the 7th of the 5th month, 1673, at the age of fifty-nine years,
he was removed from among them, and from the warfare of this life,
in full assurance of a glorious and immortal inheritance among the blessed of all generations.

During his illness, which lasted twelve days, he gave forth,
in the presence of many Friends and others,
very substantial attestation to that most excellent
dispensation of gospel light and truth,
unto which he had of late years been more perfectly and fully brought; in which also,
he had given up with all readiness of mind to walk, and in defence of which,
resignedly to suffer.
Among other expressions,
these following abundantly prove the blessed condition of his spirit,
up to the awful change.

He remarked, it was his great joy and comfort in that trying hour,
that ever he had been counted worthy to bear a testimony to,
and suffer for that invaluable principle of Christ`'s inward
appearance in the hearts of the children of men,
visiting all by his light, grace, and good Spirit, which convinces of sin.
And further, that the great judgment and condemnation of many in the nation,
especially the religious professors, was and would be,
their having so slighted and despised, yes, hated this Divine light,
and the witnesses of it.

Being overcome in spirit, he occasionally said, "`Now, Lord,
let your servant depart in peace, for my eyes spiritually have seen, my heart has felt,
and, feeling, shall forever feel, your salvation!`"

He also left this prediction among his friends,
that a time of great and near trial was shortly coming
upon Friends in that corner of the land,
wherein hypocrites should be discovered and made manifest; but that a faithful remnant,
even the upright, lowly ones, the lowly shrubs,
should be preserved and brought through the fiery trial with great comfort,
when tall and sturdy oaks should be overthrown.
And further, that this winnowing season should be attended with, or followed by,
a breaking forth of a greater glory and power,
than he or others had ever known in that quarter.
This remarkable language was judged to be plainly verified in all its parts,
as well by the great accession of sufferings, which, within three years of his decease,
was permitted to befall the Friends of Aberdeen,
as by the opposite effect these sufferings had upon the dedicated and upon the disobedient.

Sometimes, when very sick, he would bless the Lord,
that now fighting with a natural death, he had not an angry God to deal with.
"`Oh!`" said he, "`the sting of death is fully gone, and death is mine;
being reconciled to me, as a sweet passage, through Him that loved me.`"
And again, he signified, that the Lord had given him the garments of praise,
instead of the spirit of heaviness.
Another time, seeing a candle in the room almost gone out, he said,
"`My natural life is near an end, like that candle,
for lack of nourishment or matter to entertain it; but in this +++[+++respect]
we shall differ, that if it be let alone, that goes out with a stink,
but I shall go out with a good savour: praises to my God forever!`"

A little before his breath ceased, he declared, He had been with his God,
and had seen deep things: about which time,
he was filled in a wonderful manner with the power of Christ,
which much affected those present: and very shortly after, he gently passed away!

One of the earliest minutes recorded by the Monthly Meeting of Friends at Aberdeen,
in the book provided for the purpose of entering the affairs of the Society,
to which allusion has been already made, has the following simple notice of his death:
"`It pleased the Lord to remove out of the body our dear and precious Friend,
Alexander Jaffray, at his own house at Kingswells, the 7th of the 5th month, 1673,
at one in the morning; who was buried in his own burial-ground there, upon the 8th day.
He was a sincere, upright-hearted man all his time,
and one that had been a seeker of the Lord from his youth up,
and had much of the life of Jesus and spirit of holiness attending his heart all along,
as his conduct witnessed;
and died with blessed and living testimonies to the honour of Truth,
before many professors and profane, who came to see him.`"

Little more than three months elapsed after the death of Alexander Jaffray,
when Sarah his wife was called away,
to join him and "`the spirits of just men made perfect.`"
Her maiden name, it may be remembered, was Cant, a daughter of Andrew Cant,
several times noticed in the preceding Diary.
From one passage of this volume, it may be inferred, that,
at least on the particular occasion of trial there alluded to,
this helpmeet of our Friend was in some danger of adding, by her unbelief or impatience,
to his many sources of trial, rather than of mitigating his sorrows.
However this may have actually been, the sequel will prove,
that her end was a striking comment on her husband`'s path,
and even as a seal to his dying testimony:--so remarkably, oftentimes,
are the expectations, endeavours, and prayers of the faithful answered;
whether they be permitted or not, to see the travail of their soul accomplished,
the ends of their faith fully brought about.--The above authentic record,
which has been just quoted,
furnishes us with this short but very interesting document respecting her:
"`The 2nd of 7th month, 1673:`"--"`The same day, Sarah Cant,
relict of our late dear Friend, Alexander Jaffray, came into our meeting,
and owned +++[+++the way of]
Truth publicly, +++[+++as it is professed by Friends;]
which was a speaking testimony, considering her parentage and education; +++[+++she]
being mightily wrought upon to avow Truth publicly,
by her worthy husband`'s remarkable dying,
with such demonstration therein.`"--Her decease took place as early after this circumstance,
as the 24th of the next month, and her remains were interred at Kingsvvells.
+++[+++see Appendix, S.]

The Author of these pages has not been able definitively to ascertain,
that Alexander Jaffray was ever actually considered in the light of a minister;
although he is fully prepared to suppose this was not the case.
At this early period,
it does not appear to have been a stated practice among the Friends in Scotland,
to give forth any testimonial, either in the name of one or more individuals,
or in that of a congregation, declaratory of the character of deceased worthies,
and of the estimation in which they had been held by their friends.
This obligation towards the departed, soon, however, fastened on the minds of the living,
in such a way, that few,
especially among those whose doctrine and life had conspicuously shone forth,
but were held up to the view of succeeding generations,
as examples "`whose faith`" they might be encouraged to "`follow,
considering the outcome of their conduct, Jesus Christ, the same yesterday, today,
and forever.`"

Without conceding, in the slightest degree, the safe and true position,
that those in this character must be expressly ordained, raised up, put forth,
and furnished for the awfully-humbling work committed to them;
there is great occasion for us prominently to bear in mind, that these,
thus selected for a particular service,
are but vessels,--as indeed are all other members of the church,--mere instruments,
made use of just in such manner and so long as the chief Shepherd, "`the Lord,
has need of`" them.
When Peter, accompanied by John, wrought a special miracle on the lame man, Acts,
3rd chapter, he said, "`Such as I have, give I unto you;`" and afterward, to the Jews,
"`Why do you look so earnestly upon us, as though by our own power or holiness,
we had made this man to walk?`"
And certainly,
"`His name,`" (which comprehends his power,) "`through faith in his name,`"--yes,
"`the faith which is by him,`" when rightly received and
applied,--is that which the followers of a crucified Redeemer,
in every age, as well ministers as hearers,
have alone to look to for sufficiency unto every good word and work.
Various are the dispensations of what are termed the ordinary spiritual
gifts conveyed to the members of that mystical body,
of which Christ is the Head; and,
if we have been baptized by one Spirit into this one body,
we have each of us "`severally`" received a share in these,
which it becomes our duty to occupy with and to improve.
While, then, we are bound to "`esteem`" those "`very highly in love,
for their work`'s sake,`" who honour in word and doctrine,
let us also deeply sympathize with them.
These messengers have no exclusive claim or prerogative on Divine bounty.
Like the beautiful cloud in the heaven, they may be laden with a blessing,
like the trumpet, they may be filled with "`a certain`" and a thrilling sound;
but we have no proof,
they are privileged beyond what may be the attainment
of those who have no such peculiar vocation.
God has preeminently chosen, in every age, the weak things, the foolish things,
and things that are not, to be his instruments in this line,
lest we should unduly look to or lean upon them,
and that "`no flesh should glory in his presence.`"
And those that "`will be the chiefest,`" that seem to be somewhat,
that are even "`worthy of double honour,`" commonly
have laid upon them the heavier burdens,
have to pass under more humiliating baptisms,
and are placed obvious to greater temptations.
Not only have they nothing but what they receive, but they have the more to account for,
and in a more full sense than any others, are made servants of all.
They point to the Giver of every good and perfect gift,--which is also the case
with all who let their "`light shine;`" they testify of that grace and truth,
which is at once sufficient for others as for themselves,
and which can come by Him alone,
who is given to be "`Head over all things to the church.`"

With these observations on the agency and help of our fellow-mortals,
shall the memorial of so estimable a Christian as Alexander Jaffray be dismissed;
under a fervent feeling of desire,--which has uniformly attended the mind of his Biographer,
while holding up so bright an example,--that, as of men he sought not glory,
so all may be ascribed to the Great First Cause,
who is supremely and everlastingly worthy!
