== Chapter IX.

[.chapter-synopsis]
* 1676: Further seizures and imprisonments
* Letter of Gavine Laurie to Friends
* George Gray and Alexander Seaton`'s treatment at Old Meldrum
* Case of Alexander Chalmers and wife
* 1677: Alexander Burnett, bailie, endeavours to incense the commissioners against Friends
* To prevent the prisoners from preaching, their prison windows are closed up
* Some of them are removed to a place called the Chapel, others from the lower to the higher prison
* Their situation and hard usage
* A friend of the prisoners addresses the provost

But Melvill had not yet finished his work in making seizures;
some further instances of which may be mentioned, as tending,
in connection with what has gone before, to set forth the persecuting spirit of that day,
when our predecessors had, at a rate thus dear,
to pay for even _attempting_ to worship their God in
the way of his leading.--From George Grey,
a poor weaver, for a fine of twenty merks, were taken cattle and goods worth £28,
besides linen, which the soldiers privately stole and carried off.
From William Wishart, John Glenny, Alexander Gellie, and William Spark of Stonehaven,
the several amounts of £40, £40, £140,
and £50. The last named individual had obtained his liberty to go home from Aberdeen,
where he was prisoner, that he might look to his own affairs;
but as soon as the undersheriff of Stonehaven knew of this, and that he was returned,
he caused him to be put into prison at the latter place, till,
the above distraint taking place, he was obliged to discharge him.
The same undersheriff had several times before, during David Barclay`'s imprisonment,
committed those who met there for the purpose of divine worship;
and detained them several days, until he was ordered to release them,
they being mostly the servants of David Barclay.

On the 6th of the 12th month, 1676, the last mentioned Friend, together with George Gray,
John Forbes, and Robert Milne, were taken at a Monthly Meeting, and recommitted;
three of these being put into the upper prison, but David Barclay,
by the express interference of one of the magistrates, into the lower jail.
About a month after this, Andrew Jaffray was again taken into custody:
for the constancy of these sufferers was such, that when,
upon the levying of their fines, they were liberated,
forthwith they frequented their religious assemblies,
where they were consequently soon retaken, and consigned to their previous allotment.

While thus situated,
the prisoners were saluted with the succeeding effusion
of gospel love from a brother at a distance.

[.embedded-content-document.letter ]
--

[.letter-heading]
To George Keith, Robert Barclay, and the rest of Friends.

[.signed-section-context-open]
11th of 12th Month, 1676.

[.salutation]
Dear Friends,

Your letter some time since I saw, which was read at London in the meeting,
and copies sent as you did desire.

O dear hearts! my soul melted at the reading thereof, for joy and gladness,
that the Lord has raised up living witnesses for his name,
and that he has appeared in his mighty power in my native country,
to raise him up a people there, to bear witness to his blessed Truth,
and to be valiant sufferers for the same,--to count nothing too dear unto them,
being willing to give all up for the blessed testimony of his Truth,
forsaking what is near and dear unto them, that they may follow his leadings.
Oh! blessed day forever, that we should come to be witnesses of it.

And now, you valiant lambs,
whom the Lord has honoured to stand under the banner that he has
lifted up in that corner of the nation,--the Lord has blessed you,
and will bless and prosper you; as you abide faithful, you shall overcome;
the cedars shall fall before you, and the mountains be trodden down.
Your strength is in the Lord, who will go through the briars and thorns,
which are set in battle array against you.
You are the seed of the Blessed and the offspring of the Lord, whom he has made,
and will yet make as threshing instruments in his hands,
to be a dread and a terror to the enemies of his Truth.
O dear lambs! keep your habitation, in subjection to the weighty Life,
which keeps all low, meek, and humble, feeling all to be from Him,
your strength and courage.
My soul is united with you in the one bundle of life, and in this I feel your strength;
here I can lie down and even rejoice with you in your bonds!
Many a blessed night and day have I felt, when the body has been in bonds;
and I know the same Life is with you.
_That_ fountain is but one, and your refreshings are from it.
This gives patience to wait, until he say to the winds and storms,
and foaming boisterous sea, _'`Be still:`'_--for he will not let his people be overwhelmed.

And it is in my heart, that the Lord has a day of breaking through, yet more and more,
in that nation.
There has been a darkness over the land as yet, only some seed sown here and there;
and by suffering, will the Lord raise it yet more plentifully.
And the cry is in my heart, and many a day has been for the land of my nativity,
that the veil might be rent, that the power of death might be broken,
that the captives might come forth: and a faith is with me, that the Lord will visit,
and the blessed day will yet break forth more and more there.
You have been made to sound the alarm;--glory to our God for it forever!
Rejoice and be glad, that you are some of '`the first fruits`' there unto God.
And the breathing of my soul to the Lord is, that you may be preserved and kept,
over all temptations and snares, suffering patiently,
waiting the Lord`'s way and time for your bonds to be taken off.
Our God is a God of love, pity, and compassion; he has been with us in trials,
has visited us in bonds; yes, our strength has been renewed,
and in the patience have we overcome.
Dear hearts! it is a part of your way.
The time is not long--we are near our homes,
where the devil and his instruments shall not reach us.
"`We are now traveling in our journey; and they seek to hinder us,
and now and then buffet us; this is all they can do.
The body is often in their power, for the trial of our faith; but,
glory to our God! our anchor is sure; they cannot break our hold: but, as gold,
shall all the faithful sufferers come forth, to the eternal praise of our God.

O how have I been filled with joy, when I have heard,
how God`'s power has broke forth among you in prison,
and how the glory of the Lord has filled your vessels!--no news was so welcome to me;--yes,
I have tasted of that joy with you.

Dear Friends, I could write much; but I know God`'s presence is _your all,_
and is beyond all words:--only, that you may feel my joy in the Lord for you,
and may feel my love to you all, who are the faithful sufferers for his Truth.
Yes, dear Friends, I could lie down with you in your bonds,
if it were the will of my Father; and I wait till it may be his will that I see you.

Friends were refreshed in reading your letter,--yes, it was gladness to them.
We are well here.
God`'s Truth prospers, and _that_ is the joy of our hearts,
when we see the gathering to the Lord`'s standard,
and when many are inquiring the way to Zion with their faces thitherward.

So, the Lord God of my life preserve you all in faithfulness to him forever,
who am your brother in the same Truth,

[.signed-section-signature]
Gavine Lawrie.

--

This individual, whose name is also sometimes written, Gawen Laurie,
was a merchant of London, possibly residing in Hertfordshire, where,
it appears by Besse`'s [.book-title]#Sufferings of Friends,# he underwent distraint on his property;
but some years after the date of this letter, Robert Barclay,
when chosen governor of East Jersey, North America,
appointed him deputy-governor of the province,
to which was annexed a salary of four hundred pounds.
This circumstance and a similar one,
that of his being a joint trustee with William Penn and Nicholas Lucas in the
assignment of West Jersey for the benefit of the creditors of Bylinge the proprietor,
are mentioned, in default of other information,
as evidence of the estimation in which he was held by his friends.

It was scarcely to be expected, but that Christians thus oppressed in so tender a point,
as that of their unalienable right to worship God according to their conscience,
should feel themselves bound in duty to warn their
fellow-professors of the name of Christ,
to depart from this gross iniquity; it was not to be wondered at, that,
in love and pity to immortal souls, and not merely with a view to their own relief,
they should boldly declare against such proceedings.
No, their earnestness of concern would probably increase
in some proportion to the pressure of their trials,
urging them to proclaim the right way of the Lord,--the
more excellent way,--to set forth the blessed,
and opposite, and peaceable fruits that spring from the root of Life,
the tree of righteousness, "`the incorruptible Seed,`" "`the true Vine.`"

Thus, we find one of the sufferers, George Gray,
in the short interval that elapsed between his discharge and fresh commitment,
had it heavily on his mind,
to testify the gospel of the grace of God among his
neighbours of the town of Old Meldrum on their market-day.
No sooner had he finished what he deemed to be his duty in this line of communication,
followed through the street by a concourse of people, than he found his friend,
Alexander Seaton, entering the place at the opposite extremity,
with the like intention of religious usefulness.
It was seldom, perhaps, that such opportunities passed off,
without some palpable evidence appearing on the part of those addressed,
that they needed being exhorted to repentance and amendment of life.
On this occasion, John Urchart, the bailie of the town,
sadly abused these inoffensive individuals, violently beating them,
particularly George Gray, in the very time when he was honouring for their best welfare.
Immediately after, as the account states,
this furious opponent was seized with very sore pains
in his bones and throughout his body,
which continued upon him for the greater part of a year.
His conscience was at the same time so awakened by this circumstance,
that he often confessed his wickedness, in thus ill-treating those who sought his good,
promising never to do the like again.

The case of George Chalmers, living at Kinmuck, was somewhat similar to the foregoing.
Coming into the Friends`' meeting there,
with great cruelty he dragged out his wife by the hair, and sorely beat her;
shortly after which, he was strangely smitten, so that he could not speak,
and remained as it were in a senseless state for the space of three or four days.
On his recovery, the first words he made use of, were,
a confession of his guilt in his grievous conduct towards his wife, and towards Friends.

Alexander Burnett, one of the bailies of Aberdeen,
and of a like persecuting disposition with the provost,
being deputed to attend a meeting of the Commissioners,
strove to his utmost to incense them against the "`Quakers,`" strenuously urging,
that they might be prevented preaching to the people out of their prison-windows.
The Commissioners, willing to put a stop to such supposed danger,
gave him an order to remove Patrick Livingston, George Keith, Robert Barclay, John Skene,
and Andrew Jaffray to a place out of the town, called the Chapel,
where the commissary courts used to sit,
and where _they_ thought the prisoners might have better accommodation.
With this order the provost and bailie were by no means well pleased; and,
their aim being rather to incommode than to alleviate,
they were not very forward to execute it.
But a few days after,
observing some of the prisoners in the high prison preaching to the people,
great numbers of whom stood in the streets listening with much attention,
they were exceedingly angry; and the more so, when they perceived,
that after those in the higher prison had done speaking,
Andrew Jaffray began to address the multitude out of the lower prison.
On this, they immediately employed workmen to nail up the windows of the upper prison,
and to stop the very chinks which let in light upon the stairs;
and were even for contriving, how they might place iron bars so far within the windows,
as that the prisoners might not come near enough to be heard in the streets.
The provost, with Burnett and others, then went into the lower council-house,
(a place divided from that in which the prisoners were,
only by a boarded partition,) where they swore and raved awfully.
At length they concluded to execute the last order of their superiors; only, that,
instead of Patrick Livingston, they determined to substitute David Barclay;
at the same time, they had John Lesk, Andrew Galloway, Robert Gordon,
Ochiltrie Ferindaile, Alexander Seaton, Andrew Fisher,
and John Cowie removed from the lower to the higher prison.
This was done on the 17th of the 1st month, 1677.

Those, however, who were sent to the Chapel, instead of having better accommodation,
were put into a small, cold, narrow place, at the end of it,
which had a great door opening to the eastern ocean, without any fence.
Here, there was very little room more than to contain their beds, and only one window,
so small, that the inmates could not see, even to eat their food, unless by candle-light,
or while the door was set open by the keeper,
at the times when he came to let in their provisions.
On these occasions, it was usual for a servant to come and sweep out the place; and when,
to make room for him to do this,
some of the prisoners would step a few paces on the outside of the door,
the provost sharply reproved the keeper,
for letting them have that liberty for a few minutes`' breathing.
The little room they were confined in, had a chimney, but very subject to smoke.
They would occasionally have a fire;
but being obliged to send each time into the town for fuel,
it was proposed to allow them the use of a small place under their chamber,
to lay some peat in.
This the jailer dare not do without the consent of the provost, who, when applied to,
roughly chid the man that kept the key for offering to mention it.
Another window might have been readily opened, to give them a little more light;
but this suggestion, when made, was rejected with indignation.
Thus hardly were the prisoners in the Chapel dealt with;--and,
to adopt the words of the biographer of Robert Barclay,
"`Such was then the treatment of a man, who had lately been well received at courts;
who had then published a work which will long render
his name eminent in the religious world;
and, it may not be un-instructive to add,
many of whose numerous descendants are now surrounded with
most of the accommodations which opulence can bestow,
and with much more than the simplicity of the Christian life requires.`" [.book-title]#R+++.+++ Barclay`'s Life,# p. 36.

But the case of those confined in the higher prison at the Tolbooth was yet more grievous.
They were so straitened for room, that they could not lay their beds,
but were obliged to place them one above another on boards,
that so they might have some little space to move upon in the daytime;
and sometimes the rain, beating in upon them, by wetting the floor,
still more narrowed up their standing ground.
Add to all this, the unwholesome closeness of the prison, together with its darkness,
the windows being blocked up with boards, and the reader may form some idea,
how deplorable must have been the condition of men thus confined,
and for so long a period.
Every night were they locked up in two rooms for the space of fifteen hours,
nor had they for several days together such attention paid them as even decency requires.
While they lay in this miserable state, _eight_ others of their brethren,
taken at their religious meetings, were added to their number, namely, Alexander Skene,
(the same that had formerly been a magistrate,) Robert Burnett of Lethentie,
Alexander Gellie, John Forbes of Aquorthies, John Robertson, Robert Sandilands,
Robert Milne, and John Mercer; but some of these, for lack of space,
were obliged to lodge themselves among the debtors and other prisoners,
who lay in the lower vaults much thronged.

The relations and acquaintance of these sufferers,
with many sober inhabitants of the town, being sorely grieved at such inhuman usage,
applied to the magistrates to prevent their death,
of which the physicians actually declared them to be in danger.
With this view, they sued for their removal into the great room of the Chapel;
but the provost and bailie Burnett would not admit it, the latter saying,
_He would pack them like salmon in a barrel,
and though they stood as close as the fingers on his hands,
yet they should have no more room; and that if they had not room in the chambers,
they might lie on the stairs:_--the passage of which stairs was so narrow,
that one person could hardly pass another.

At length, a friend of the prisoners, under a great concern,
wrote the following letter to the provost, which is thought worthy to be here inserted,
as showing,
that the prisoners or their friends were not lacking in the Christian
duty of warning and rebuking unjust and cruel rulers.

[.embedded-content-document.letter]
--

[.letter-heading]
To the Provost of Aberdeen.

[.salutation]
Provost!

The King of kings, who is Lord both over you and me, has laid it upon me,
so that I may not forbear, without incurring his displeasure,
to write unto you touching your present office, and your exercise thereof in this city.
Wherefore, in his fear and dread consider it, and reject not, I beseech you,
what is thus offered, because coming from one whom you despise,
but seek to hear the voice of the Lord, and to know his will thereby.

You are appearing cruel against the servants of the living God,
whom one day you will see he owns,
and to whom he will give a better kingdom than an earthly one.
But because you are not willing to see and acknowledge them such,
what I am to lay before you shall be,
laying aside that part of the difference between us, _Whether they be, or be not,
the people of the Lord:_ for it is beyond doubt to me,
the Lord having made me to see they are his,
and joined my heart unto them and their testimony; and you, it seems,
are not yet come to begin the question in good earnest: _From where have they come?_

Your hard thoughts and hard speeches of them are beside the law,
wherewith you defend some of your actions,
and their manner of imprisonment is your own deed.
Ah! remember, and still keep in your mind,
that for these and all other deeds done in the body you must give
an account,--and you will find your need of forgiveness;
but how can you seek or expect it, if you be void of mercy to any?
Albeit there were of us that had wronged you, what do we owe you?
But _a few pence_ in comparison of what you owe the Lord.
And will you fulfill our Lord`'s parable in plain deeds, to imprison cruelly,
and beyond your superior`'s orders, for your own private offence?
Verily, though before this time much had been forgiven you,
yet for that very act all your iniquities may be laid to your charge,
as you may read in Matthew 18:32-34. Were we your enemies,
as it is likely you judge us to be, you ought, as a Christian,
to relieve our necessities; and in so doing you would heap coals of fire on our heads,
and might expect your reward from the Lord.
But how much contrary +++[+++to this]
is it, to increase our necessities,
and add to our burdens by closer imprisonment than the law requires,
and where there is no necessity for it;
there being other convenient houses and places for imprisonment,
where there is room enough.
Reflect seriously on the measures which you are giving to others;
and be not ashamed to stop, when and where you see you have done amiss.
If you think, thereby you are executing justice, and act righteously,
because they walk contrary to your will, mind what the wise man said,
'`Be not righteous overmuch, nor make yourself over-wise:
why should you destroy yourself?`' Why should it offend you,
that they preach repentance and remission of sins by believing in Christ _near,_
to a multitude of poor wicked people?
Can you think worse of them than some formerly really were,
who preached Christ out of envy,
supposing to add affliction to the afflicted Apostle`'s bonds?
and yet he was far from being cruel unto them, or bidding any so to be,
although he was an eminent witness for Truth, and against all deceit.
And that they cry aloud from a prison-window, and lift up their voices like a trumpet,
is it an injury to you, or matter of offence justly given?
Or can you allege, God or man will lay that practice of theirs to your charge?
So that, upon no account, need you to be afraid or offended, to suffer them,
when _they_ are willing for Christ`'s sake to run all hazards,
and be lightly esteemed among men.
It is far less for _you_ to bear it.
Therefore leave them to their Master, to whom they must stand or fall,
that so you may give up your charge and account with approbation of the Lord,
whose favour will be of use, when that of all men will fail.

--
