== Chapter X.

[.chapter-synopsis]
* 1677: Lilias Skene`'s warning to the magistrates and inhabitants of Aberdeen
* Consolatory letters to the prisoners from William Penn, Richard Rae, and Hector Allane.

About this time, Lilias Skene,
whose husband Alexander Skene with others had been then recently incarcerated,
as we have seen, among all sorts of prisoners, merely for the act of public worship,
was constrained,
in true honesty and earnestness of desire for the welfare of her neighbours,
to lay before them the hazardous consequences of such conduct.
In her exhortation may be discovered that Christian love which flows towards enemies,
and which enables to pray for those who despitefully use and persecute.
Her language is enlivened and confirmed by many apt passages from the Sacred Volume; for,
it appears, she was especially versed in these writings,
and had much improved in her understanding and application of them,
by obeying the dictates of the Spirit of Christ.

[.embedded-content-document.address]
--

[.blurb]
=== A warning to the Magistrates and Inhabitants of Aberdeen, written the 31st of the 1st month, 1677.

At several times, and in diverse manners,
I have witnessed against the will-worship and blind
obedience of the inhabitants of this city,
since the Lord opened my eyes, and drew me out of that fearful pit.
So, at this season, I am moved in the same zeal for the Truth,
and compassion towards your souls, Magistrates, Preachers, and People,
to bear an open testimony against the _spirit of persecution,_
whereunto you are now arrived in such a measure,
as does exceed the bounds of humanity and the severity of your predecessors.

Wherefore, in the fear of the Lord, and in tender love towards you,
I warn you to consider what you are doing;
that you draw not upon yourselves and this city innocent blood; for, assuredly,
the Lord will not hold you guiltless.
Every one of you will find it so, according to the measure of your accessions,
when the Lord deals with you:--truly, you will have enough to account for,
though you keep your hands free from the blood of the innocent people,
who suffer for conscience-sake.

O consider!
_If the righteous scarcely be saved, where will the ungodly and unmerciful sinner appear?_
What favour or mercy you have shown to particular persons,
has not been done unto them as friends of God,
but that you might appear to be men not wholly void of gratitude or natural affection,
they being near unto you and in friendship with you: therefore will you lose your reward.
How will you answer the Lord one day, for thus using his friends and followers?
When he shall say unto you, '`I was sick, and you visited me not; hungry, naked,
and in prison, and you were so far from extending pity or help,
that you made me (in my members) prisoner, naked, hungry,
thirsty.`' In place of supplying their necessities,
you were instrumental in occasioning them to be greater; for, like Egypt`'s task-masters,
you have increased the tale of bricks, and instead of setting them at liberty,
have added to their bonds.

And if the magistrates, ministers, and people of this place should say,
'`When saw we you so and so?`' Hereby is it manifest to all who will open their eyes,
that Christ may sometimes suffer in his members, when people believe it not,
nor are concerned about it.
This ought to make all, who have but the letter of the Scripture, tender and cautious;
for one answer shall be given unto all, both to those who have not showed mercy,
who did not all the good they had power to do, and to those who have done evil,
and are willing to do more:--'`Inasmuch as you did
so and so to one of the least of these little ones,
you did it unto me.`' It will be no cover for you,
that the magistrates are under the authority of others above them: no,
examine your own hearts, and you will find,
you have '`willingly walked after the commandment,`'
as it is written in Hosea 5:11-12. Assuredly,
the Lord is observing who are doing thus, and who is not.
Neither will it excuse you, that your ministers informed you,
such men were seducers of the people, and therefore enemies, not friends to God;
and that your ministers strengthened your hands,
by accounting it _nobility_ in magistrates to curb error.
These hills and mountains will not cover you:--__they__ will need coverings for themselves,
if they obtain not mercy to repent and reform.

But not all that you say, or that you act against the Lord`'s work and witnesses,
will discourage a remnant from desiring to be faithful even unto death.
For my part, your severities and cruelties are a confirmation unto me,
that Truth is not on your side who are persecutors: for, in all ages,
he that was born after the flesh, persecuted him that was born after the Spirit.
We feel the old hatred; we see the envy of the people; we hear the cry of Edom, crying,
'`Raze it, raze it,
even to the foundation:`' Esau`'s rough voice has been often
heard from your pulpits these thirteen years past,
and has caused us to feel rough hands from civil authority,
especially during these last thirteen months.
But, glory be unto God forever! the faithful and obedient are
enabled to put their seal to Christ`'s faithful word,
_In the world you shall have trouble, but in me you have peace._
I have seen in the light of the Lord,
this day of trial is come for the fall and for the rise of many in this place,
and our testimony for the Truth is _as a sign spoken against;_ yes,
the sharpest sufferings the seed has met with, or shall meet with, are permitted,
_that the thoughts of many hearts may be revealed,_ both among you and among us.

Wherefore, I beseech you, love your own souls; harden not your hearts from God`'s fear;
neither despise this warning,--the Lord having sent one, _as from the dead,_ to warn you;
though you have the testimony of Moses and the prophets among you,
which whosoever will not hear, there is little ground of hope,
such will hear other testimonies, how true soever.
If you had hearkened to that word to which Moses directed,
near in the mouth and in the heart, and to which the Lord Christ pointed,
teaching every man to do to others as he would be done by,
there would be little need of other testimonies.
Neither would you unnecessarily throng in honest men in prison, who have families,
wives and children, deeply suffering with them,--and in these cold, nasty,
stinking holes,
where you have shut them up,--who have been as neatly
handled and tenderly educated as any among you,
and as useful in their generation.

I desire you to acquaint yourselves better with the
histories of the church in former ages;
and with the remarkable judgments that have befallen persecutors in Old and in New England.
And search the Scriptures of truth:
where now are all the persecutors of the people of God in former ages?
and, before long, where will those be that tread in their steps?
Where is he that hardened his heart, and refused to let Israel go to serve the Lord?
Where is he now, who resolved,
that his little finger should be heavier than his predecessor`'s loins?
And where is he, of whom it was said,
that he did evil in the sight of the Lord above all that went before him?
Does not the Lord observe those that are at ease in Zion,
and forget the afflictions of Joseph, who live gorgeously, and fare delicately every day,
and despise the poor?--who put the evil day far away,
and cause the seat of violence to come near, that lie upon beds of ivory,
and stretch themselves upon their couches, and eat the lambs out of the flock,
that drink wine in bowls,
and anoint themselves with the chiefest ointments,--but
are not grieved for the afflictions of Joseph?

O consider these few instances, with many more such! and say not in your hearts,
as those atheists recorded in Scripture,
'`All things continue as they were at the beginning,`' and '`Where
is the promise of his coming?`' Death and judgment _will_ come,
and it may be before long; but though it should not hastily, yet remember,
in the Lord`'s account, _a thousand years are but as one day._
Moreover, there is another Scripture, which has weightily arisen in my heart,
as applicable to Aberdeen, Jer. 51:1. '`Thus says the Lord; Behold,
I will raise up against Babylon,
and against them that dwell in the midst of them that rise up against me,
a destroying wind,`' etc.
My desire is, you may not be _behind,_
with that generation whom John the Baptist addressed,
who were forewarned to flee from the wrath to come.

And now having exonerated my conscience toward you, by obedience towards God,
and love towards the inhabitants of Aberdeen,
I hope the Lord shall enable me to bear what he may permit you to do towards me or mine,
even with that patience which becomes a disciple of the crucified Jesus, and,
nevertheless, to remain your souls`' well-wisher,

[.signed-section-signature]
Lilias Skene.

--

While some of this faithful band thus pleaded with the _oppressors,_
others of their number, at a distance from the spot,
were brought near in spirit to the _oppressed;_ and deeply sympathizing,
endeavoured to animate and console them, their language in effect reviving,
as well as sealing the assurance of an Apostle formerly,
"`But and if you suffer for righteousness sake, happy are you;
for the spirit of glory and of God rests upon you.`"--One or more effusion bearing
this character has been produced in the course of the preceding pages;
and it may be satisfactory to such as entertain a value for the remains of William Penn,
to have the opportunity of perusing an unpublished
letter of this description from his hand.
It does not bear a date;
but the circumstances indicate with sufficient precision
where it should obtain a place in this simple chronicle.

[.embedded-content-document.epistle]
--

[.letter-heading]
To the Brethren imprisoned at Aberdeen for the testimony of Jesus.

[.salutation]
Dear Brethren!

Salvation and peace by Jesus Christ, the Light of the world, our eternal, glorious Day,
be multiplied among you,--who is the Rock of safety,
and Fountain of everlasting consolations,
from whose pure life descend sweet refreshment into
the souls of all that love Him in truth and sincerity.

And I doubt not, my Brethren, but you are witnesses of the same;
as a letter from our dear brother, George Keith,
gives me with others hereaway to understand.
Which being read among us, broke our hearts and deeply affected our souls,
to behold with you the goodness of the Lord unto you in your tribulations.
These '`wars and rumours of wars`' are certain forerunners
of the redemption of your country:
and great will their reward be from the Lord, that fly not in this winter time,
nor on this sabbath day.

I feel an immortal spring of pure life rising among you; and can say,
I am with you in spirit, and behold the _aurora_ of the day of the Lord over Scotland.
My Brethren, all, be scattered unto and settled in _your own,_
and wait for the feeling of the power of the Lord, that subjects all to him;
then wait for the signification of that power: let none quench the Spirit,
nor miss of the Spirit`'s mind; that you may now grow spiritual soldiers, expert,
and fitted by these exercises for such spiritual conflicts,
as the Lord has for you to go through, in the Lamb`'s war.
O! these trials are blessed mortifyings to the sensual and worldly man,
and for the awakening of the soul to the things that are beyond time and mortality.

O! you little leaven, and salt of that country, love the pure power,
the true and certain power, and grow in it, as trees in winter, downwards,
that your root may spread; so shall you stand in all storms and tempests.
And, O! blessed are they that firmly believe,
patiently and contentedly wait for God`'s salvation to be completed;
God will '`stay`' such with his everlasting arm, with '`flagons`' of love,
and in that pure peace which persecutors neither know nor can take away.
My dear Brethren, this suffering is not strange, neither is it for nought.
All wait to see the end of the Lord therein, and all bow thereto,
and none resist the Lord`'s purpose; for this is,
to bring up the seed and power into dominion,
to make his righteousness and truth known to the world,
and his love and his faithfulness unto you, and to keep that down,
which for lack of exercise might overgrow the Truth in the particular.
Much I see of the Lord`'s wisdom, mercy, and goodness in this thing,
and it will end for his glory, I am persuaded; wherefore I can say, be of good cheer,
for everlasting strength is with you and in you.

The affairs of Truth hereaway are very well.
The Lord`'s power reigns over public and private oppositions.
Our meetings are very large and quiet, and Friends generally well:
yet great sufferings upon the 1st, 23rd, 29th, 35th of Elizabeth,
and the 2nd and 3rd of James; and I see not but sufferings hasten upon us more and more.
You are in our remembrance to be mentioned with others to the King and Council.
And so, +++[+++we must]
leave our cause with the Lord, who will arise in his due time for his poor seed`'s sake;
and blessed are they that are not offended in him, nor his dealings, dispensations,
or tribulations.
Many are the troubles of the righteous,
but out of them all shall they be delivered in time,--that is,
not ours but the Father`'s time, whose will must be done in earth as it is in heaven.

This, with my endeared salutation to you all, my heavenly kindred,
and fellow travellers in the narrow way that leads to the eternal rest,
concludes this epistle, from your faithful,
sympathizing Friend and Brother in the tribulation and patience of the kingdom of Jesus,

[.signed-section-signature]
William Penn.

--

Two other epistolary communications are also recorded,
as being about this time welcomed by those,
who had learned in the school of Christ Jesus to love one another,
and that "`with a pure heart fervently,`"--being engaged
in good measure to purify their "`souls in obeying the Truth,
through the Spirit, unto unfeigned love of the brethren.`" 1 Peter 1:22.
The first of them is as follows.

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Edinburgh, 16th of 11th month, 1676.

Dearly beloved Friends in and about Aberdeen, and especially you that are in bonds,
who suffer for the testimony of a good conscience!
As you keep innocent and blameless before God, and labor continually so to do,
and look back and read in your hearts the ground and cause for which you suffer,
it will minister joy and soul-satisfaction unto you.
For it ever did so to me: I bless my God, outward imprisonment was never a prison to me;
though I suffered _near two years together_ in Edinburgh,
_and was never a quarter of an hour all that time from under their fingers;_
being deprived of the enjoyment of _all good Friends,_ and was cast among _thieves,
and robbers, and murderers,_--such unclean spirits,
as I never yet did see worse upon the earth.
And, as I remember, _for the space of two months and upwards,
I could not say there was one quiet hour either by night or day;_--and
this fell to my lot even in the time of my weakness.
Then, the consideration what I suffered for, did still minister satisfaction unto me;
for I could take the Lord to record,
that I suffered for the testimony of a good conscience;
the remembrance of which caused my inward man exceedingly to rejoice.
And so, blessed forever be the God of my salvation, that caused me,
in his love which '`is stronger than death,`' to rejoice over all my sufferings!
Thus, in this love of God, I reigned over all my enemies; and though in prison,
yet was I a _freeman,_ for '`where the Spirit of the Lord is,
there is liberty.`' And my sufferings were even _joyous_ unto me, but never _grievous;_
for the Lord revealed it unto me,
that it was a more honourable crown than all the crowns of the whole creation,
to be a sufferer for the Truth of God!
And this he made clear to me, at a time when I was near to sink;
then he raised me up above all,
and gave me strength to press forward towards the mark for the prize of our high calling.

And now, my dear Friends, be faithful, noble,
and valiant for the Truth upon the earth! _for you may bless the day,
that ever you were born, who are called unto such a blessed calling,
as to suffer for the testimony of a good conscience._
So, my dear Friends, _keep your testimony, for it is your life._

And now, my dear Friends, I beseech you, keep in innocency,
and commit your cause unto the just God,
for he will certainly plead the cause of the innocent: this I do infallibly know.
Therefore, my dear Friends, love your enemies, and pray for them, and entreat the Lord,
that he may open their eyes, if it be his blessed will,
and convince them of the evil of their doings.

[.signed-section-signature]
Richard Rae.

--

It will be readily perceived, that the foregoing production came from the pen of one,
very differently qualified, in respect both to education and natural endowment,
from the writer of the epistle that precedes it.
In fact, Richard Rae was by trade a shoemaker; and it may be remembered,
he has been already noticed in preceding pages of this volume,
as one of the first in Scotland that became a "`Quaker
preacher;`" being also the individual who,
earlier than any other of that people, tasted imprisonment at Aberdeen,
where he had come in the love of the gospel to visit his brethren.
It is not by any means improbable, that the following circumstance,
named by Robert Barclay in his [.book-title]#Apology,# may have allusion to this Friend: namely,
That he knew a poor shoemaker, not able to read a word,
who was taken before a magistrate of a city,
for preaching to some few that came to hear him; when,
being assaulted with a false citation of Scripture from a learned professor of divinity,
who constantly asserted his saying to be a Scripture sentence,
the poor man still maintained,
that the Spirit of God never said such a thing as the other affirmed:
a Bible was brought, and it was found to be as the illiterate shoemaker had said.
Should the reader be of the number of those, who can believe with William Penn himself,
that from among the _shoemakers, mechanics,_ and _husbandmen_ may be,
and once were called forth, "`our best preachers;`" and with Robert Barclay,
that "`the Spirit and grace of God can make up the lack of literature
in the most rustic and ignorant;`" he will be likely no less to
appreciate the "`savour of Life`" and simplicity of the Truth,
conveyed through homely language, than through a more refined medium.
See "`Select Anecdotes`" relating to the Society of Friends,
by the Author of this volume, p. 10;
also R. Barclay`'s Works 1692, fol. p. 423.--Indeed, to the quickened mind,
that has the spiritual "`senses`" "`by reason of use`" "`exercised
to discern both good and evil,`" it is beautiful to observe,
what a harmonizing tendency there is,
in all the various administrations of Divine virtue
to the different members of the one body;
each part that is "`fitly compacted together,`" being rendered subservient
to the well-being of the whole--"`to the edifying of the body in love.`"
The little "`household of faith`" at Aberdeen, no doubt had their occasion,
to feel the worth and import of what the Apostle Paul declared to the Corinthians:
"`The eye cannot say to the hand, I have no need of you.`"
For "`those members of the body, which seem to be more feeble,
are necessary,`" and such also as "`we think to be
less honourable;`" seeing "`God has set the members,
every one of them,
in the body as it has pleased him,`" "`that there should be no schism in the body,
but that the members should have the same care one for another.`" 1 Cor. 12.
This subject is beautifully touched upon in the next letter,
addressed to the same party; and which afresh discovers,
how this people watched over each other for good, and by love served one another.

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Leith, 3rd of 11th month, 1676.

[.salutation]
Dear Friends,

In the sense of that Life, which visited me in the beginning,
am I drawn forth to write unto you,
who are now _stayed_ for the blessed testimony of our God.
I know the Lord is with you, and his everlasting arm is near,
and underneath to uphold you in this great trial, +++[+++even He]
who has not failed to prepare you for this honourable service.
Dear Friends, I am one with you in your sufferings and in your joy;
and I feel a travail for you in the general,
that you may stand faithful witnesses for the Lord,
as many faithful brethren have done before you, in this and former generations,
who now reap the fruit of their labors, and their memory is blessed +++[+++even]
to all eternity.

Friends! feel the everlasting Life,
and drink of the living springs that proceed therefrom, which God has opened unto you:
_this_ is your reward at the hand of the Lord; let your minds be stayed in _that,_
and you are over all that the devil and his instruments may do unto you.
Look not out, neither be weary in well-doing,
and your deliverance will come in the Lord`'s season.
He that has wrought your _soul`'s_ deliverance,
is not unmindful of you that are faithful unto him.
But if any draw back, they will lose their reward, and the Lord will be provoked.

So, dear Brethren, encourage one another in the Lord: and you that are strong,
(whom the Lord has made so,) help the weak, and bear with them,
and travail one with and for another, in the spirit of love and meekness;
_and have a high esteem of, and respect unto, the weakest member for the Head`'s sake,_
Christ Jesus our Lord, who shed his blood for all,
and is near unto you to behold your conduct inwardly and outwardly.
Grieve him not, nor oppress his seed in one another;
so shall you be known to be the children of the heavenly and royal birth; and,
in due time, when the Lord has done his work in you and by you,
he will bring you forth with a high hand in the sight of your enemies,
and you shall shine with the beauty of the Lord, and the Lord will add unto you,
and you will rejoice to behold the wisdom and power of God.
And care not for your outward loss, which in the end will be great gain:
they that have laid down their heads in our Father`'s bosom, repent not,
that they have suffered these things for Christ`'s sake.

So, in the love of our God, have I written these few things unto you,
my dearly beloved Friends; in _this_ let us dwell together,
and we are sure our dwelling is in God, whatever the world may say.
And to Him that is able to keep you, both in soul and body,
both in your inward and outward afflictions and temptations, I leave you,
who is God only wise and powerful, blessed forever! "`From your Friend and Brother,

[.signed-section-signature]
Hector Allane.

--
