== Chapter XII.

[.chapter-synopsis]
* 1677: Observations on the nature of the testimony committed to these witnesses of Christ
* Andrew Jaffray`'s very unusual exercise
* Fresh imprisonments of Friends, on account of meetings for worship
* Case of Robert Gerard
* The firmness and meekness of the sufferers
* Letter of George Fox "`to the suffering Friends in Scotland`"
* Their situation at Montrose; they are debarred, in the winter season, from working for their families
* Alexander Seaton confined among them
* All passages for light or air closed, to hinder his preaching to the people
* Andrew Jaffray boldly expostulates with the chief instigator of persecution at that place; and is thrust into a dungeon vault, and cruelly beaten
* Remarkable sense of retributive justice

The present was the first time, since the commencement of the persecution,
that the prison of Aberdeen was altogether clear of these sufferers.
But thus it did not long continue: for very shortly afterward, as might be anticipated,
were they more closely imprisoned and more hardly used than ever;
so as to leave little doubt on their minds,
that the design with some of the persecuting parties,
was nothing short of cutting off the very lives of such faithful
and uncompromising witnesses to the Spirit of Christ Jesus.
The plain and constant testimony of these, by conduct and conversation,
by word and doctrine, by doing and by suffering,
was _no other than it still remains to be at the present day,_--and will yet continue,
so long as they are preserved a living remnant on the sure Foundation.
They could not, when and as they felt Divine Love and Wisdom constraining,
neither dare they, withhold the word of warning, where they believed it to be due,
"`to flee from the wrath to come;`"--they could not spare sin, nor soothe people in sin,
nor prophesy sin-pleasing deceits, neither could they approve of those who did so.
It was this that rendered them, as it always must,
an eyesore and an offence to evil doers,
and to all who corrupt or pervert the doctrine of Christ,
which is indeed "`according to godliness;`" it was this that occasioned them to be reputed,
and actually called,
"`a trouble,`" "`a plague,`" "`a contagion,`" of
which it were well to cleanse the polluted district;
and thus the language of an apocryphal writer of old,
became well fitted to the mouths of these persecutors:
"`Therefore let us lie in wait for the righteous; because he is not for our turn,
and he is clean contrary to our doings.
He professes to have the knowledge of God, and he calls himself the child of the Lord.
He was made to reprove our thoughts.
He is grievous unto us even to behold: for his life is not like other men`'s,
his ways are of another fashion.
We are esteemed of him as counterfeits: he abstains from our ways as filthiness:
he pronounces the end of the just to be blessed.--
Let us examine him with despitefulness and torture,
that we may know his meekness, and prove his patience.`"
Wisdom of Solomon, ii.
12, etc.

During such a state of things,--when evil was called good, and good evil,
when darkness was put for light, and light for darkness, bitter for sweet,
and sweet for bitter;--when,
independently of the gross and defective moral condition of the people _generally,_
they that worked wickedness were set up, such leaders among them causing them to err,
and keeping them from the light of righteousness,
so that judgment was turned away backward, and justice stood afar off;
(for truth might be said to have fallen in the street, and equity could not enter;)--yes,
when truth as it were failed,
and he that departed from evil made himself a prey,--a snare being laid
for him that reproved sin in the gate;--was it to be marvelled at,
was it to be stumbled at, that singular burdens, suited in some sort to unsound,
unreasonable times,--burdens similar to those,
that were laid upon servants of the Holy One in ancient days,
should be also devolving upon such, as endeavoured to follow in _their_ footsteps,
upholding the same testimony, speaking the same language,
standing upon the same ground of faith, upon the same Rock?

But, quitting the line of presumptive reasoning from analogy,
as to what the supreme Orderer of human affairs and human conduct might see fit,
on peculiar occasions, to require at the hands of any,--as, indeed,
"`he gives not account of any of his matters,`" further than he may please;--and
without venturing to denounce sentence on such cases;--the reader is now
to be made acquainted with the very unusual impression of duty which befell
the zealous son of _our humble-minded Diarist._

Andrew Jaffray, of whose parentage, condition in life, education,
and conversion to the faith and practice of this Society,
some intimation has been already given, became deeply affected and laden in his mind,
under an unusual sense of the corrupt and ungodly condition of many of his fellow-citizens.
Their practices, however highly esteemed or justified by men, he had reason to apprehend,
were as an abomination in the sight of One, who sees not as man sees,
and whose eyes are _as a flame of fire._
He believed they were covering themselves with a covering, but not of the Lord`'s Spirit,
and that their case resembled that of the "`whited
sepulchres,`" which _inwardly were full of all uncleanness._
This religious exercise growing upon him, he wrote an address to his neighbours,
urging upon them to turn to the Lord with a true heart,
from whom they had deeply revolted, and with full purpose of soul to serve him.
At length he was led to believe,
that he could not divest himself of the burden that lay upon him,
nor obtain relief to his tried spirit, so as to be "`clear of the blood`" of such,
without _himself becoming as a spectacle and a sign among the people,_
to rebuke and expose, in a prophetic manner in his own person, the offensiveness of sin.
Accordingly, on the 1st of the 4th month, being the market-day,
he gave up to the humiliating act,
of passing through the streets of Aberdeen,--(the scene where his honoured father
had obtained the favour even of royalty)--the upper part of his body being naked,
and having in his hand, that which might prove in the view of beholders,
as fit an emblem as could be chosen,
of the loathsomeness of all their performances and profession in religion,
without _washing their hearts from iniquity._

This very significant, though uncommon appearance of his,
from which poor nature revolted,
was accompanied by a zealous exhortation to timely repentance,
and thorough amendment of life.
His sincere and Christian earnestness for their reformation,
harmless and also disinterested as at least it must have been, but prompted, he avers,
by true love to their immortal souls, met with such reception from the magistrates,
that he was violently dragged away to prison,
and closely shut up as a most dangerous person.
The windows of the prison (where it appears there were others of the Friends
by this time in durance) were thereupon ordered to be effectually blocked up;
which, however,
by no means precluded some powerful addresses from
being sounded forth in the ears of the people,
who collected in the streets below.
It was observed,
that the professed ministers of religion joined with the magistrates
in this treatment of an innocent man for preaching repentance;
when, on the same day, they suffered a great deal of vanity and abomination, yes,
blasphemy against the Holy Spirit of God,
to be acted and uttered on a public stage in the open market-place,
without any the least restraint or rebuke either from magistrates or ministers;
whose zeal, totally employed in persecuting the innocent,
could pass by the most public inducements to vice and immorality,
as things beneath their notice.

It is only due to this individual, whose name has been thus prominently put forth,
in conjunction with so strange a procedure,
to introduce in this place a passage from the testimony written concerning him,
after his decease, by his friend Robert Barclay, _junior,_ (as he has been called,
being the son of the _Apologist_ of the same name.) Should
anything be needed in the view of general readers,
to substantiate the estimable character of Andrew Jaffray,
both in a civil and religious point of view, such a passage is calculated to do so.
And with regard to members of the same denomination in this day,
it may serve as an encouraging confirmation to them,
of the intrinsic value of endeavouring to maintain, through life, _the straight-forward,
even tenour of adherence to known duty._
The latter class of readers will surely be prepared to anticipate
and enlarge on reflections such as this,--that it is the truest,
safest, happiest policy, "`herein`" to "`exercise`" ourselves,
"`to have always a conscience void of offence toward God, and +++[+++so far as in us lies]
toward man;`" knowing beyond all doubt,
"`it _shall_ be well with them that fear before Him,`" and "`them that honour _him,_
_he_ will honour.`"

_Extract from R. B.`'s testimony respecting A. J._--"`This was particularly
observed concerning him,--that in the streets of the same city,
where he had often been reproachfully pointed at,
for the Truth`'s sake and his testimony to it, he, in his latter years,
was _wishfully looked upon, with affection and veneration, and blessed,
as he passed along;_ of which I have _often_ been both an eye and an ear witness.`"

Through the summer and autumn of this year, 1677,
the Friends continued to be molested in their peaceable assemblies; and,
upon their refusal to obey the command of those who required them to separate,
were from time to time seized, and even with violence dragged away to prison.
The list of names,
of those committed from their Monthly Meeting on the 15th of the 4th month,
stands as follows: David Barclay, Robert Burnett of Lethinty, Patrick Livingston,
George Gray, John Glennie, Robert Gordon, James Birneise, George Melvill, Andrew Fisher,
John Mercer, and Alexander Seaton:
these were all "`thronged up`" into the usual place of confinement.
On the 2nd of the 8th month, John Watson, an Englishman, and James Findlay,
a Friend from the western part of the country, who had come to visit their Friends,
received the like treatment, together with Alexander Skene and two others.
Among such instances as these, Robert Gerard, having been absent from home,
was intercepted on his return to Aberdeen,
and led away to jail;--and this appears to have been the occasion.
A child of his, removed by death, had been interred during his absence,
in the Friends`' burial-ground; a fine was imposed upon him,
for the alleged avoidance thereby of certain burial-fees usually demanded in such cases;
his goods were seized to satisfy the fees,
and he torn from his family and home under circumstances of affliction,
which rendered his case a peculiarly aggravated one.

But, this people, fervently seeking of the Lord,
in like manner as the Apostle for his fellow-believers, Col. 1:11,
that they might be "`strengthened with all might, according to his glorious power,
unto all patience and long-suffering with joyfulness,`" were abundantly favoured with
ability to sustain what was permitted to befall them at the hands of unreasonable men.
It was by "`looking unto Jesus,`" and considering "`him that endured
such contradiction of sinners against himself,`" that they,
through his grace, were kept from being weary and faint in their minds.
Indeed,
their very enemies were induced to marvel at their meekness and
patience--so cheerfully did they take the spoiling of their goods;
even "`rejoicing that they were counted worthy to
suffer`" any kind of shame for His sake,
who had taught and engaged them by his presence and goodness,
not to forsake the assembling of themselves together.
Yet, in order to take off from the weight and effect of such conduct,
these opponents would tauntingly disparage their motives, by affirming,
that _the Quakers liked well to go to prison, they had such good fare there._
In order to meet as well as to manifest such malicious aspersions,
"`the Lord stirred in them a resolution,`" (as the account
states,) for the space of two or three months together,
merely to give up their bodies _passively_ to the operation of the law, or rather,
of the wills of those who hated them; and by no means actively, in any wise,
even to appear to procure or promote their own bondage.
So long as this exercise continued with them, they were, in consequence,
actually _"`hauled down as beasts for the slaughter`"_ and "`clasped
together by the workmen`" employed to carry them away.

It was during the continuance of this state of things,
that the succeeding comfortable and enlivening lines from the hand of George Fox,
reached the company at Aberdeen.

[.embedded-content-document.epistle]
--

[.letter-heading]
For the Suffering Friends in Scotland.

[.signed-section-context-open]
4th of 5th month, 1677.

[.salutation]
My dear Friends,

To whom is my love, in the everlasting Seed, that reigns over all,
and '`will grind to powder`' all your persecutors,
and the devil that is the cause of them, who fights against the light,
which is the life in Christ, as he did against Him in the flesh,
above sixteen hundred years ago.

And now, my Friends, suffer as lambs in the time of your sufferings:
let all your wills be subjected with patience, which has the victory, and runs the race,
and obtains the crown of life:
and be as willing to go to suffer for Christ`'s sake,--as the Apostle said:
And it is not only given you to believe, but to suffer for His name`'s sake,
in whom you have salvation; for they that suffer for righteousness`' sake are blessed,
and theirs is the kingdom of God.
And, by faith the holy men of God had the victory,
as you may see at large in Hebrews 11th ch.
So, nothing is overcome by any man`'s will, but by faith that gives access to God,
in which they please God.
And +++[+++thus]
I do believe, that all your sufferings will be for good;
both to the establishing yourselves upon the holy Rock of life,
(who was the foundation of the sufferers, the prophets and the apostles,
who is the Anointed and the Saviour,) and to the answering that of God
in all people:--For the Lord has a great work and seed in that nation.

So, live in the Spirit, that mortifies all, and circumcises all, and baptizes all, that,
in the Spirit, you may sow to the Spirit, and of the Spirit reap life eternal.
For there are seedsmen enough in your nation,
and makers of seedsmen in the form and the letter, which sows to the flesh,
and in their field they may reap abundance of corruption.

So, my desires are, that you may be all alive to God,
and live in the living unity of the Spirit, which is the bond of the heavenly peace,
which passes the knowledge of the world;
so that the eternal joys may transcend all your sufferings, and carry you above them;
and thus, in love to God and in love to your persecutors, you can pray for them,
in that you suffer for their good.
And this suffering is above all the sufferings in the world without love and charity,
which makes one another to suffer for getting the upper hand.
But such are not the sufferers of the true Lord Jesus, who suffered,
though he was a-top of all, yet he made none to suffer; and when he was reviled,
he reviled not again, but said, '`Father,
forgive them,`' and committed himself to him that judges righteously.
So, let the same mind be in you, as was in Christ Jesus; for the apostle said,
that they had the mind of Christ; and He, the Lamb, overcame,
and the Lamb has the victory, and his sanctified ones follow him:
_glory to his name forever, amen!
Holy! worthy of praises!_

So, remember me to all Friends in Scotland, both north, and west, and south;
and let them have copies of this.

[.signed-section-signature]
George Fox.

--

Some few further statements, in addition to those given,
are now to be laid before the reader,
relating to the situation of the Friends at Montrose, who, it will be recollected,
were but few in number.--The true worship of the Almighty,
which is "`in spirit,`" whether divested of or clothed in words,
continued to be so great an occasion of offence, and so repugnant to the persecutors,
that they went on in increasing malice and fury,
shamefully to entreat these "`poor innocents,`" as if they even thirsted for their blood.
No sooner did any meet together to perform this reasonable service,
than they were cast into prison; and at length, from one of them, James Nuccoll,
a tailor by trade, they took away his work, alleging, he was not a freeman of the town;
whereas, he had long before obtained from them a promise of his freedom, and had sought,
but in vain, to pay for and enter it.
In this course, they were mightily incited by the same David Lyall,
their stated preacher, who had been so active in the like wicked work at Aberdeen.
The magistrates,
having sent to prison several of these individuals in the midst of the winter of 1677,
were so cruel, as to deprive those of work,
who could labor at their outward callings for a livelihood,
at the same time threatening all those who should in any wise pity or relieve them.
And when Alexander Seaton, a Friend among the prisoners at Aberdeen,
had got liberty to visit his imprisoned friends at Montrose,
he was himself detained with them.
On one occasion, because he exhorted the people that passed by the window in the street,
to fear the Lord, and mind his light and Spirit in themselves that strove with them,
these oppressors were much incensed,
and had all the windows and passages for light or air, wholly closed up for several days.

About this time also, Andrew Jaffray,
having set out on some occasion from the prison in Aberdeen,
felt an impression of duty to go to Montrose,
and to bear a testimony to the Truth of Christ in the public place of worship there.
It seems, David Lyall had been grievously railing from his pulpit against the Friends,
endeavouring to render them odious in the eyes of the people,
both as to their doctrine and practice.
On hearing this, the mind of Andrew Jaffray became confirmed,
and settled in the intention, of publicly expostulating with this person,
before his own people on the very next day, being the 29th of the 11th month.
Accordingly, he waited in the graveyard,
till the congregation were beginning to withdraw; then went in,
and addressed him in bold and plain terms on his unjust allegations, made, as they were,
against Friends, at a time when there was no one who could or dared reply to him;
desiring him then to make good his charges, and that he was ready to reply to them.
But, as soon as words to this effect could be pronounced,
at the instigation of David Lyall,
Andrew Jaffray was hurried away with great violence into _a dungeon vault,
under one of the aisles of the building,_ and there confined within two doors,
quite out of the reach of anyone`'s hearing, and among the graves of the dead.
But mark the language in which this narrative proceeds.
"`Yet was this place made very comfortable through the sweet
presence of the Lord with him`" during his abode there,
_from the said 3rd day of the week to the 6th,_ when, in the night season,
they released him from his state of jeopardy;
some of those who had sorely beaten him being much ashamed
at this their inhuman conduct.--It was remarkable,
that one of the persons who had thus ill-used this Friend, going to sea shortly after,
the vessel was encountered by a Turkish pirate, when, being seized,
he was beaten most sadly, beyond all the others.
And at that very time, as he afterward feelingly confessed to a Friend,
his conscience so smote him for his cruelty to Andrew Jaffray,
that he could not but accept it as a righteous and heavy judgment upon him from God.
Thus, the language of Scripture respecting a persecutor appears to have been literally fulfilled,
"`His mischief shall return upon his own head,
and his violent dealing shall come down upon his own pate.`" Ps. 7:16.
