== Chapter XVII.

[.chapter-synopsis]
* 1680 to 1700: The Christian concern and care of Friends, during this period, with regard to the education of their children, and the administration of church government, etc.
* Visits of Robert Barrow and John Gratton
* 1697: Andrew Jaffray and Robert Barclay Junior travel to the highlands
* Death of Lilias Skene and Patrick Livingston

The comforts and advantages that attach to the liberty of serving God according to conscience,
were now, as regards this Christian community, in full operation.
The present chapter will be opened with some agreeable symptoms that have been collected,
of their state and progress under these circumstances: showing,
during a considerable space of time,
what use they made of the clemency and toleration extended towards them.

In the year 1681, the little cluster of Friends in this northern region,
insulated in great degree, as they then felt themselves to be,
and cut off from the privileges of communication
with more populous districts of their fellow-professors,
concluded to establish two schools, one at Aberdeen and the other at Kinmuck,
for the benefit of their children.
On this subject,
there is ample proof of the continuance of their enlightened and weighty concern.
In the epistles issued by their collective assemblies, they hold out,
in a manner very fit for a Christian society to do,
the primary importance of training up children in the fear, nurture,
and admonition of the Lord; "`that they may, through the blessing from above,
come to have an inheritance and portion in the heritage of Jacob.`"
They frequently urge,
their being early made acquainted with what the Lord had done for this people,
in separating them for Himself out of all other kindreds of the earth; and that,
in the liberty and fear of God,
the nature of that spiritual standard which they are called upon to uphold,
should be explicitly conveyed to the tender mind.
They also advert to the pernicious example and fellowship of ungodly children,
and the great advantage of having their youth sheltered under the care of such Friends,
as, being _in the Truth themselves,_
would not allow them to "`be corrupted from the simplicity`" of it,
either by heathenish books, or other unsound sentiments.
This exercise on behalf of the children of their members,
in a particular manner rested on the mind of Christian Barclay;
herself the parent of a large and interesting family, and "`a mother in Israel.`"
She addressed several epistles to her Friends,
stimulating those who stood in this responsible station,
to a steadfast zeal for the best welfare of their families;
desiring they might feel themselves far more strongly bound to provide,
so far as in them lay, for the sustenance of these in a spiritual,
than in an outward sense.
"`Because,`" she remarks, "`we have felt the virtuous Power of God,
which has visited us in our hearts, to be to our souls __the Bread of life.__`"
Therefore, (she intimates,) should we rest at ease,
while our children are feeding on the barren spirit of this world,
without breathing to the Lord for their _souls`' provision,_
we are much below _the very infidels._
She expresses the belief, that the Lord is near,
and ready by his power to help the upright-hearted,
in answering his righteous will in these important respects; and that we, of all people,
are left without excuse,
since He has given us to know _the fountain of strength and goodness in ourselves,_
so that we need never be at a loss, if we are but rightly retired to the gift of God,
and submit ourselves to his holy ordering.--Her "`well-accomplished`" mind was,
in the like earnest manner, directed towards those in the relation of master and servant,
as well as towards her poor neighbours.

On the subject of a wholesome administration of church government,
the origin and nature of which,
has been somewhat explained in a previous chapter of this history, we find that,
early in the year 1680,
so soon as the long interruption occasioned by persecution would permit,
they quickly resumed their former practice,
of meeting monthly or oftener for the regulation of such affairs.

Towards the close of the year 1690, they received a letter from George Fox,
just before his own removal by death; recommending to them,
in common with the Society at large,
a design so fraught with extensive and permanent benefit,
that it may be called a _legacy_ of no common value.
It was his wish, they should separate certain of their number whom they approved,
to have upon them the express charge of corresponding with
Friends in London on the state and welfare of their brethren;
that thus, in this corner of the camp, as well as elsewhere,
they might be reciprocally cheered, as George Fox expresses himself,
by _a continual report of the prosperity of the church,
and the spreading of the Truth in all parts of the world;_
while they would be in the way of receiving that sympathy and help,
in cases of difficulty or distress, which the Friends of London,
from their central position and other circumstances, were especially qualified to render.
A further purpose, which he had in view by this excellent systematic connection,
was the circulation of books, tracts, and epistles,
which might serve either to edify their own members, or to inform others.
The sound wisdom and excellent feeling, which first prompted these arrangements,
are indisputable; the advantages, also, resulting from them, have been very great,
even to the present day; but we are scarcely competent to say,
what might be the effect of these measures, were they carried to the full extent,
which the projector seemed to have in view.

In the year 1693,
another commendable practice was concluded to be adopted
by the Friends at Aberdeen,--a practice then prevalent,
as they state,
both in Ireland and in many parts of England--that two weighty Friends
in the meeting should be appointed from one quarter to another,
_to have more especially upon them_ the care and oversight of their members.
They were to visit them in their families, and to give them advice, in meekness, wisdom,
and love, as they might see needful.
With regard to the minutiae and the routine of these things, it is obvious,
that circumstances will occasion variation of practice,
in different ages and in different places;
but the savour and intent of them will ever be uniformly the same.
And in proportion as the gathered churches, that profess faith in Christ Jesus,
more purely come into the Spirit of their holy and blessed Head,
the management of their affairs of this description will become more simple,
more efficient,--tending to the honour of God, the preservation, the restoration,
and the growth one of another in spiritual things,
as well as to the admiration of those that are not of the same "`fold.`"

A further instance of the zest with which those of this generation
pursued the imperishable things that pertain to life,
and peace, and godly edifying,
is that of their _weekly family meetings at each other`'s houses in rotation;_
which they justly notice, as resembling the practice of the primitive Christians,
and as affording a spiritual "`repast`" to such as wish to feed at the Lord`'s
table.--Not that these faithful watchmen had no causes of anxiety and grief,
as to some of those towards whom they yearned,
and for whose welfare the breathing of their spirits
went daily up to the Father of mercies.
_There were such causes_--and among these,
is specified a degree of slackness in coming up to the help of the Lord,
by presenting themselves with their brethren before him in some of their solemn feasts.
Yet, certainly, on the whole,
the observations made by one upon the state of this Society in another land,
at about the same period, may be said to apply with equal truth to Scotland:
"`In those days, the meetings of Friends were more eminently favoured with Divine power,
as they lived more devoted to Christ,
and consequently more abounding with his love flowing in their hearts.
Those happy men and women left the Lord`'s vineyard, (through their faithful labors,
with the Divine blessing upon them,) well fenced and clean,
(having gathered out the stones thereof,) and abounding
with the excellent fruits of the Holy Spirit of Christ.`" [.book-title]#James Gough`'s Life.#

Many were the gospel embassies which this people were favoured with, about this period,
from messengers in the Lord`'s service; the number of those who came from England,
and were at Aberdeen, being noticed as amounting to twenty-one,
in the space of four months.
Among such, appear the names of Robert Barrow in the year 1691,
and John Gratton about three years after.
Both of them were much exercised on behalf of their brethren;
they were especially desirous that the rules and plans of
church discipline prevailing in their own country,
might be steadily maintained here also, in all its branches;
and from the pen of each was an address prepared,
with a view to provoke to love and to good works.
The former of these individuals,
after adverting very particularly to methods of good order, says, "`So,
seeing here is _preaching_ enough, and you _know_ enough,
it is greatly needful to practise and perform religious duties,
and to bring forth fruits of righteousness, to the praise of the good Husbandman.
_For preaching is but an information,_ to reach the witness,
or stir up the pure mind by way of remembrance, being as _the suburbs of religion;_
but life and practice,
in a performance of doing God`'s will on earth,--the seed
being raised that delights therein,--this is the substance,
even the very essence and marrow of the matter; in the enjoyment of which, +++[+++both]
male and female come to have _the seal of the Spirit,_ that we are his people,
and concerned in our day for God`'s glory.`"

In a letter from this Friend, Robert Barrow,
addressed to George Whitehead and Stephen Crisp, dated the 15th of 11th month, 1691-2,
from Kingswells near Aberdeen, the estate of the Jaffray family,
he speaks of his visit to these parts in the following terms:

[.embedded-content-document.letter]
--

Blessed be the Lord, I find things generally well, in unity and good order,
which makes Friends`' travel both easy and comfortable.
And about Aberdeen and somewhat northward of it, there is a fine openness,
many of late convinced, and hopeful to continue; and many inclinable and willing to hear,
and the name of an Englishman is _famous_ among them.
And though I be but a weak instrument,
and having no fellow traveller nor outward companion; yet, blessed be the Lord,
I have had a very comfortable journey, as my heart could desire.
And though it be the winter season and shortest days,
that I have sometimes travelled before day, and after day has been gone,
yet the Lord has given me health in all weathers, both wet and dry.

[.postscript]
====

Postscript.--Dear George Whitehead, this youth, that comes to be apprentice to J. Danson,
is come of good parents; his father`'s name is _Andrew Jaffray_--may be,
you have heard of him--he is the most noted man among Friends, both in testimony,
and in a church care and government, in the affairs thereof.
So, after you be acquainted with the boy,
I could wish you to take a little oversight of him;
and see that J. and his wife be tender to him.
I hope the lad may be deserving,--so do it for his parent`'s sake.--Colchester
Monthly Meeting Collection of Manuscript Correspondence.

====

--

A short account has been preserved of a journey,
performed in the work of the ministry by Andrew Jaffray, Robert Barclay, David Wallace,
and Alexander Spark, as far north as Inverness, and westward among the Highlands,
where no Friends had before that time travelled.
It is as follows.

[.embedded-content-document]
--

Robert Barclay, David Wallace, Alexander Spark, and Andrew Jaffray,
took journey from Aberdeen, in the love of God and unity of the Friends of Truth,
upon the 17th of 6th month, called August, 1697.
We tarried some time by the way at Inverness,
where A. Jaffray had some good service among Friends.
Rode that night to Adamstoun, two miles from Strathbogie, twenty-two miles,
where we had a very kind reception in a discreet house;
the landlord of which being very sick,
A+++.+++ Jaffray felt it with him to speak to and pray for him.
Next day, the 18th, at Fochabers, where we dined,
A+++.+++ Jaffray declared Truth among the people at the market-place; and in our quarters,
we had good service with one Calder, a noted priest, and one Dr. Steinson.
Rode that night to Elgin, where A. Jaffray was concerned to preach in the street,
and had a peaceable time among the people at the cross about the 7th hour; though,
at our first coming into that town, hardly any would receive us:
we travelled that day twenty miles.
Next day, the 19th, in our journey to Inverness, we breakfasted by the way at Forres,
eight miles, at one Alexander Stewart`'s whose wife was a very serious, discreet woman:
with them we left some books.
Dined at Nairn, eight miles, at one John Dollar`'s; whose wife, in his absence from home,
promised to give up their house for a meeting on our return.
We there called upon Daniel Monro`'s sister, and had some service in that family;
and so rode on to Inverness that evening, in all twenty-eight miles.

Next day, the 20th, rode up through Strath Erick,
having furnished ourselves with a guide and food,
and came that night to a place called Killwheimmy, at the head of Loch Ness;
lodging at one Miles Macdonald`'s, where we had a good little evening meeting.
The master of the house, though a Papist, was made to confess, after the meeting,
to the Truth declared.
That day we rode twenty-four miles.
On the next, we went to Lochiel`'s house, with great difficulty,
up the sides of Loch Oich and Loch Lochy, eighteen miles.
This seat is called Auchnacarry, near Loch Arkieg.
There we remained next day, being 1st day,
and had a very good meeting among several people that understood English,
and some other good services.
On the 24th, A. Jaffray and D. Wallace rode down to the garrison at Inverlochy; where,
the next morning, we had a notable opportunity with Colonel Hill,
who received A. Jaffray`'s message very soberly and discreetly,
acknowledging the truth of his testimony, which was to this purport:
That there are greater enemies to be subdued within, than all outward rebels and enemies,
even the passions and lusts of our own hearts; from which enemies of a man`'s own house,
come all outward wars, insurrections, rebellions, and disorders.
These inward enemies can only be subdued, quelled, and overcome,
by following the conduct of Christ, the inward captain, by his Light and Spirit;
not by might, nor by outward power, but by his grace, which has appeared unto all men,
and teaches or enables all who obey it,
to deny and subdue all ungodliness and worldly lusts, as well as to live soberly,
righteously, and godly in this present world.
And this victory over one`'s self by the Christian weapons,
is a greater conquest than the subduing of all countries,
according to that ancient distich,

[verse]
____
He that commands himself is more a prince
Than he who nations keeps in awe;
And they who yield to that their soul`'s convince
Shall never need another law.
+++[+++see <<note-DD,Appendix, DD.>>]
____

To this inward principle of Divine grace he was directed;
and he confessed thereto very lovingly.
Afterward, A. Jaffray had a notable opportunity with the priest of the garrison,
in the presence of a great company of the soldiers.
So, being clear,
D+++.+++ Wallace and he rode back that afternoon to Lochiel`'s house at Auchnacarry;
this being the furthest point of our journey, one hundred and twenty-two miles.

We stayed the 26th, there being a very great rain, and had a very good meeting; at which,
Lochiel the elder and younger were present, and several people that understood English,
who were very evidently reached;
and we sensibly felt the love and openness of Lochiel`'s family,
more after the meeting than before.
+++[+++see <<note-EE,Appendix, EE.>>]
Next morning, the 27th, we came away in tender love,
Lochiel the younger conveying us eight or ten miles on our way;
and we were wonderfully preserved that evening, in a great danger,
in passing through a water, called Ballaloyn, which was greatly inundated,
and which we were obliged to get over,
or else lose our service at Inverness next 1st day.
That night, we lay at a very mean house on the water-side,
and could scarce get any roof to be under.
On the 28th, we all four came safely to Inverness with our guide,
having been preserved through several dangers--blessed be the Lord our God!
We took up our quarters in the Castle Street,
at our former lodging at one Isabel Cowie`'s, a discreet woman; where, that evening,
we had an excellent opportunity with three townsmen of the place,
who came on purpose to pay us a visit and to confer with us, namely,
Robert Cuming of Relugas, a very sharp, discreet, pertinent man; George Duncan,
a modest Presbyterian; and one Falconer, an Episcopalian.
The principles of Truth were fully opened to them, in some of the deepest points;
particularly as to the first motive of credibility, and ultimate judge of controversy;
and Robert Cuming most ingenuously conceded to our openings thereupon,
when his understanding and the witness for God was reached.
Also, with regard to the possibility of falling from true grace,
Friends were fully vindicated from a gross slander,
which George Duncan told us was laid upon us, namely,
That we boasted of our own strength and abilities to keep God`'s commandments;
wherein we gave him and the company abundant satisfaction.
It was, indeed, a blessed opportunity;
and the Lord was most preciously present with R. Barclay and A. Jaffray,
who only were concerned with them at that season:--blessed be His faithful name forever!

The next day, being the 1st day of the week,
we had a very precious little meeting among ourselves, about the 10th hour,
where we were sweetly comforted together in the feeling
of the heart-breaking love of our God.
A+++.+++ Jaffray having signified, that it lay upon him as a duty,
to speak to the people when they should come out from their forenoon worship;
we went all four together, in the unity of the Spirit,
to the end of the street where their worship house stands.
And having attended, and walked to and again, till the throng of the people came forth,
both from the English and Erse houses--for, in one of them,
they preach to the country people in Erse,
though many of them also understood English--a living,
open testimony was borne there to the true worship of God, the spirituality of it,
the way and manner of it; also the nearness of the Spirit of Christ to people,
as an inward principle, and how to know the same from all other spirits not of God;
that so therein they might worship the Father in the one true and living way.
The people stood exceedingly attentive and sober, both great and small,
there being a very great crowd, and no disturbance in the least was made; after which,
we walked peaceably up the street to our quarters.
We had intimated to the people, at the end of the public testimony,
that it was our intention in the Lord`'s will, to have a meeting at our quarters,
that afternoon about the 4th hour, after the dissolution of their public worship.
At the hour appointed,
our landlady having very willingly yielded to let
us have the use of her house for that end,
we had a very full and large meeting.
Not only the large room wherein it was, but the next room, chambers above,
and the stairs, being all crowded with people;
who were exceedingly sober and serious all the time.
And the Lord`'s power and blessed presence, as a fountain suitable to the occasion,
was largely let forth for his own work:--blessed be his holy name forever!
That night, A. Jaffray went to visit the old Bishop of Murray, called Hay,
who was sore diseased in his body by a palsy.
The following day, finding ourselves clear, and having dispersed several books,
we set forward on our journey homewards.
We were at John Dollar`'s at Nairn,
where the woman had promised us the use of her house for a meeting.
Accordingly, her husband being then returned, gave it up freely;
and we had a most precious season among a great many people, who,
upon the very first intimation of a meeting, filled the room, stairs, and streets;
where there was a wonderful breaking in of the tender, melting,
opening life and love of God, _as if they had been all settled Friends._
Indeed, such a season of life and glory, among a people not gathered into the Truth,
none of us did ever see!
Surely, the Lord has a great seed to gather in that place and thereaway:
O that it may be often visited, watered, and prepared for a harvest,
and brought into his garners!

After this blessed season, we rode that night to Elgin to William Douglas`'s,
our former lodging, being twenty-eight miles in all; then to Edomstoun,
where our former discreet landlady fell a blessing the Lord,
who had sent His servants to her house; having declared, that,
after A. Jaffray had prayed for her husband, when we were there before,
he had daily recovered from that time.
The next day, we came safely to Aberdeen, being the day before the Monthly Meeting,
being a journey of two hundred and forty-four miles.

--

This year, as the records of the Meeting testify, "`Upon the 21st of the 4th month, 1697,
it pleased the Lord our God, to bring to the sweet harbour of his everlasting rest,
a long-tossed vessel upon the waves of many afflictions, namely, Lilias Skene,
+++[+++whose maiden name was]
Gillespie, the widow of Alexander Skene, some time bailie, of Newtyle.
+++[+++She was]
a woman of a serious life from her childhood,
attended with much sickness of body and exercise of mind--+++[+++also]
afflictions of many sorts.
Among the professors, she was one of the most eminent; +++[+++but was brought out from them,
by a strong hand, into the precious Truth, about the year 1667;
in which she lived about thirty years, in a true measure of honesty,
though attended with deep temptations and tribulations;
and died in the 71st year of her age.
Her body was buried on the 24th at Kingswells, beside that of her husband,
+++[+++who died in 1693.]`"

But it had pleased the Lord, about three years before,
to remove from works to rewards another of these worthies--Patrick Livingston,
at about the age of 60 years--one of the most laborious
instruments whom he had seen fit to make use of,
in this district, at the first springing up of such a people.

Although the scene of his last days was the neighbourhood of London; yet,
as he spent the morning and the prime of his time,
in the defence and propagation of the gospel,
among his fellow-countrymen in this part of Scotland,
it will be proper to subjoin some further information respecting him,
in addition to that which has gone before; showing that the standard of Truth,
which he had been called upon to display, was only laid down with his life.
He travelled, in the exercise of his gift as a minister,
in many parts of England and Ireland, and to most places in his native country.
In the year 1669, in company with James Halliday, he visited the Orkney Islands;
in which journey, it is said, they had good service,
and several remarkable circumstances occurred, which were not committed to writing;
particularly at the Synod in Elgin, Murrayshire, at Kirkwall in Orkney,
and in the Isle of Stroma.
Besides his long detention in the jail of Aberdeen,
he had to bear a testimony to the Truth, by imprisonment in Newgate, London,
for a considerable time, about the year 1684.
The condition of the prisoners at the latter place, is briefly set forth in a petition,
addressed by Friends to King James the 2nd and his Parliament,
soon after his accession to the throne.--"`And here in London,`" say they,
"`the jail of Newgate has been from time to time crowded, within these two years,
sometimes near twenty in a room, to the prejudice of their health;
and several poor innocent tradesmen have of late
been so suffocated by the closeness of the prison,
that they have been taken out sick of a malignant fever,
and died in a few days after.`"--In his latter years, Patrick Livingston left Nottingham,
where he had resided, and came with his family to London; there,
he continued a diligent honorer in the Lord`'s vineyard,
several times visiting his friends in Scotland, especially in 1693,
the year before his death.
Respecting this engagement they declare, that, _of all the times he had been among them,_
his ministry was attended, throughout his visit,
with _the largest and most plentiful measure of the Lord`'s blessed power_ they had witnessed,
he being wonderfully borne up through all, though very weak in body;
so that they term it, "`his endeared farewell to his spiritual kindred.`"

After his return home, he grew weaker, until he departed this life,
on the 15th of the 4th month, 1694, at the house of John Kirton, Kensington, near London,
where he had been removed for the benefit of the air.
Several Friends were present with him in his last hours,
during which time these heavenly expressions flowed from him.
The day before his departure, he said, "`I am in unity with all faithful Friends,
and in love to all men.`"
About an hour previous to his close, he cried, "`O Father!
O Father!
A little while after, mentioning his weakness of body,
as if he desired more strength to utter what was on his mind,
_and this being then apparently granted to him,_ he said,
"`Let Life reach unto all here;`" and pulling off his nightcap with his own hand,
about half an hour before he was removed hence, he said, "`Blessed, praised, magnified,
and exalted, be the mighty, powerful, great, and everlasting name of the Lord God,
forevermore!--Oh! that your Life may arise in full dominion over all,
and that Friends may feel it so, in all their assemblies;--that they may be kept in love,
concord, and unity together, and show it forth in word, work, testimony, life,
and conduct unto all!`"--adding, "`Life being over all, here we have all we need,
and here there is a lying down in true submission to the will of the Lord;
and laying down our heads in peace and rest with Him forevermore, forevermore!`"
Then said, "`Here is victory over death, hell, and the grave,
and resting in peace with the Lord forevermore.`"
+++[+++see <<note-FF,Appendix, FF.>>]
