== Chapter XVIII.

1699: Visit and epistle of Samuel Watson to Friends in Scotland--1723:
Memoirs of Alexander Seaton, Robert Scott, and David Wallace;
Also some account of Christian Barclay and her family.

The preceding chapter has carried forward to the close of the 17th century,
these memorials of the faithfulness of a covenant-keeping God towards a little remnant,
who had made a covenant with him by sacrifice.
They had embraced that law in the inward parts, to which the Prophet Jeremiah,
when describing the new covenant dispensation,
makes allusion,--"`the law of the spirit of life in Christ
Jesus,`" who remains the blessed Mediator of it.
While a people thus separated unto God, abide true to him,
while their heart is right in his sight,
while they continue steadfast in his covenant of light and life,
how excellent is their heritage,
how desirable their portion! and how fully does it come up to that prediction
of the evangelical messenger of the Lord concerning these times,
when "`the Spirit,`" being "`poured upon us from on high,`" "`My people,`" says he,
"`shall dwell in a peaceable habitation, and in sure dwellings,
and in quiet resting-places.`" Isa. 32:15,18.

That this was in good degree the experience of the Friends in Scotland,
up to the time of the opening of another century,
maybe somewhat seen by the tenour of an epistle,
in gospel love addressed to them by Samuel Watson, an able and weighty minister,
whose residence was in England.
He had then recently, in his old age,
paid them a second general visit through their meetings; and was on his way home.
Having, as he intimates,
at a very early period,--and probably before there were any Friends at Aberdeen or its
neighbourhood,--witnessed the first breaking forth of that heavenly faith and zeal,
which was remarkable among the precursors of this people; he was well qualified,
sensibly to perceive any departure from the purity and strength of primitive days.

Samuel Watson to Friends in Scotland.

Hamilton, 29th of 5th month, 1699.

My dear Friends in Scotland!

The Lord of the whole earth has drawn me, out of my own country,
to visit you in the ancient Truth,
having been formerly in this nation about forty years ago,--a
time of hazarding my life for the elect`'s sake,
when little appearance of that heavenly life was brought forth,
which now is made manifest, and shines over the cloudy day.
Many are now brought into the fold,
where the true Bishop and Shepherd of their souls is teaching them;
and they know a feeding in the green pastures of divine love,
and a sitting down where none shall make them afraid--living praises to our God,
who has wrought this great and marvellous work for a remnant!
And this I do witness in my travel, in the several parts of this nation;
wherein I have been comforted in the sweet appearances of divine life,
and the overflowings of heavenly love have run forth as a glorious stream,
to the watering God`'s heritage; and the plants of renown spring up together,
and are more and more strengthened to bring forth fruit to the honour and renown of Him,
who not only plants but gives an increase.

O you tender-hearted ones, and honourable! who spring from the royal seed,
where is no mixture of wickedness,--you are as marrow to my bones,
and so near to my life,
that I am made to rejoice in the feeling of this great work of salvation,
which God has wrought among you.
O keep in the tents of holiness, and to the Rock of your salvation! and then,
(it is the word of the Lord to you,) no tempest or storm,
which may come for the trial of your faith, shall remove you;
but you shall be built upon Mount Zion, which cannot be removed.
Let the weak be assisted and strengthened by your gentle and tender care over them;
let them never be discouraged by your neglect, or by a lack of godly care to help them,
even the very hinder most of the flock; for over these, the enemy seeks to get advantage,
and, Amalek like, to destroy them.
But the camp of the Lord is full of love and of power,
and the shout of a king is among them; and the Captain of our salvation is with us,
and He teaches us to make war in righteousness,
and He it is that will overcome all our enemies; everlasting praises be to Him,
and that forevermore, amen!

And further, I declare it unto you,
as it appears unto me--O let your hearts be tendered in
the love of God--This visiting again of your nation,
did often stir in me as a fire in my bosom, which could not be quenched;
being of the nature of that love, which, it is said, "`many waters cannot quench,
neither can the floods drown,`"--(for if it could,
I had many reasonings to stop it)--but divine love is of that force,
that it prevails over all, and possesses the kingdom.
In which love, I was prevailed with, to come and visit you who are gathered of the Lord,
and who feel divine refreshing,
as well as those who are not yet gathered among the lost sheep
of Israel;--that they may come and feel the touches of His love,
who would not the death of any, but that all might come to Him, who is the Life,
and gives life unto the saints.
And for no other end was I drawn to visit this nation,
together with these two striplings who are with me, the one being my own daughter,
and the other an innocent Friend +++[+++Janet Stow;]
both of them being my spiritual relations.
And the Lord`'s power has gone along with us, according to our upright intention;
we not coming in the enticing words of man`'s wisdom,
but in plain evidence and demonstration of the Spirit of God;
that the holy witness might be reached in all, and that life might spring in all,
that death and dead works might be reigned over in every individual,
and life and immortality might be brought to light through the gospel,
of which He has made a remnant publishers, to his praise and glory forever!
And the good effects of the love of God, we have felt,
in the places where we have been traveling;
and we can now return to our own nation with sheaves of joy in our bosom,
and give good tidings to our friends, that the Lord`'s power and presence is with you,
and his mighty and glorious work of redemption and sanctification is going on.
And we have been truly comforted in a remnant, who are valiant for the Truth upon earth,
and find nothing too dear to part with,
for the honour of his name and that blessed Truth,
of which they are made living partakers; so that, with one spirit and one consent,
we can praise and magnify His power, which has.
called us unto this great work of his gospel.

And finally, my Friends, brethren and sisters in the fellowship of the gospel,
considering the great care and pains the Lord has taken with us,
to make us polished stones for the building of his church;
how great is the need we daily have, to keep in the feeling of his power,
as members of his body; every one doing some work and service for him.
Our God has mightily wrought for the establishing of his people in an excellent order,
and he has raised up many, out of the graves of sin and dead formality,
to meet together in his name; so that now, we have particular meetings, both Monthly,
Quarterly, and Yearly.

Now, dear Friends, though you know these things,
I would stir you up by way of remembrance: as it was in the days of Moses,
it should be now with us,
who are under the government and teaching of our spiritual Moses.
In every meeting, some faithful men and women, fearing God and hating covetousness,
which is idolatry, should be appointed,
duly to inspect into the families of their particular meeting;
to see that there be no neglect of the poor,
no disorderly walking on the part of any person that professes the Truth,
neither unfaithfulness in any degree:
and an account should be brought up to the Monthly Meeting,
according to the gospel order.
And in your meetings, a weighty course should be had,
in calling each meeting to examination, how things are among them;
that thus all things maybe brought to the Light, and proved by it,
whether they be wrought in God, yes or no.
Then, you can come up to your Quarterly Meeting, in a true sense,
how things are with you: and so, all being kept in good order,
you can sit down in the peaceable gospel, in love and unity,
being refreshed in the love of God and one with another.

This I desire, as an ancient brother, in the love of God,
who has made us partakers of his grace, wherein, while keeping in obedience,
we feel a being bound up in the bundle of divine love, never to be separated.
In which love I salute you all, and take my leave of you.

Samuel Watson.

While we may, with some feeling of instruction and delight,
be allowed to dwell upon or cling to such evidence,
as that which the above document affords us, of the favourable condition of a church,
professing to be guided by the Spirit of Christ; we must, still,
prepare for and accept the unwelcome intelligence,--that these scenes in their brightness,
did not long continue.
Another century was opening--and opening alike upon the ardent, hopeful,
generous spirit of youth,
as upon the ripening graces of "`the ancient and honourable;`"--these
last were being fast gathered to the garner of eternal rest,
while the former were but girding on the armour of righteousness,
beginning the good fight of faith against a host of enemies.
The age of intolerance, of popular violence, of systematic persecution was gone by;
but the age of prosperity and of self-indulgence, the age of formality,
of spiritual lethargy, and leanness was stealing on.
That which the Sacred Volume has recorded, respecting outward Israel of old,
might in measure be applied to the case of these--a
very small division of the spiritual Israel:
"`The people served the Lord all the days of Joshua,
and all the days of the elders that outlived Joshua,
who had seen all the great works of the Lord,
that he did for Israel.--And there arose another generation after them,
which knew not the Lord, nor yet the works which he had done for Israel.`" Judges 2:10-7.

A worthy, living remnant has indeed been hitherto preserved among the Society of Friends,
even in these districts, where their principles were so boldly, so nobly maintained,
though they be only as "`gleaning grapes,`"--"`two or three
berries in the top of the uppermost bough`"--so "`few,
that a child may write them.`"
Through the merciful hand and renewed visitations of the Most High upon them,
he has been pleased, from season to season, to water, to dig about,
and to dress the plants of this portion of his vineyard,
as well as to introduce among them of the choicest of his stock,
enabling them to bring forth the fruits of holiness abundantly,
"`to the praise of the glory of his grace.`"
Yet, certainly,--considering the allotment and the privileges, which,
from one generation to another, the Lord has freely dealt out to them,
among those that fear him,--it must be admitted, they have too generally, by no means,
been that "`willing people,`" which "`the day of his power`" would have made them,--a
people "`watching at his posts,`" waiting to hear his gracious will respecting them,
and remembering his commandments to do them.--May the awful
"`song of the Beloved touching his vineyard,`" Isa. 5:50,
etc. never be pronounced upon them!

But, breaking away from these musings, again to revert to the Memoirs of earlier times;
and passing by all minor transactions relating to the Friends in the north of Scotland;
there are now to be given a few brief sketches of individuals among them,
some of whose names may be familiar to the reader,
as frequently occurring in the foregoing history:--these,
having kept the faith that is in Christ Jesus, and held out to the end in well-doing,
were, we may believe, crowned with immortality and the joys of the blessed.

In the year 1723, died four of these associates in the warfare of life, Alexander Seaton,
Robert Scott, David Wallace, and Christian Barclay.--The first mentioned,
Alexander Seaton, was the son of John Seaton of the Seaton family of Meldrum,
being born near Lethinty, in the shire of Aberdeen, about the year 1652.
It will probably be recollected,
he was one of those students of the University of Aberdeen,
who joined the Society in consequence of being convinced
of the scriptural rectitude of their principles,
when they were publicly advocated by Robert Barclay and George Keith,
against the sophistry of his fellow-collegians.
The candid confession, which he published under his own signature,
at the end of the account of this controversy, is not unworthy perusal in this place:
it is as follows.--"`I also declare, (who,
being a student at that time in the Old Town College, was present at the dispute,
and heard the same with attention,) that the students, in their account,
have grossly belied the Quakers in many things.
And although since that, it has pleased God to join me unto that people,
yet at that time I had no mind to be of their way.
However, when I saw their account, I did approve it, as ingenuous as now also I do;
and disapprove the students`',
as false in many things.--Alexander Seaton.`"--While we are given to understand,
that the bright example set before him in his relations, Alexander Forbes and wife,
under whose roof he lodged while attending college,
had previously had some favourable effect on his mind; yet,
it is clear by the above language,
he was by no means prepared to acknowledge the religious views of Friends,
until after this public exposition of them had taken place.

Thus nobly beginning to confess Christ, the Truth, before men,
while yet about 23 years of age, he grew and became established in Him, so that,
cleaving to His all-sufficient grace, the persecution and close imprisonment,
which shortly after became his portion,
only served to enlarge his experience of the power and goodness of God towards him.
Being thrust into Aberdeen jail, he was soon called upon, it is said,
in rather a remarkable manner, publicly to give testimony by the word of exhortation,
to that which had wrought so effectually in him.
He is represented to have been a sincere and weighty man,
of good understanding and solid judgment; a faithful, zealous,
and sound minister of Jesus Christ;
especially exemplary in humility and lowliness of mind,
living in peace and unity with his friends, well esteemed likewise among his neighbours.
He used daily to devote some part of his time to religious retirement; and,
although a scholar, was not much known to be such in his public ministrations,
valuing that learning but little in comparison of the cross
of Christ and the operation of his Holy Spirit.
After his marriage, from a sense of duty, he removed to Glasgow,
where the few Friends in that city were undergoing some sharp trial,
as well by abuses from the magistrates, as from the rude rabble.
Here his faithfulness and constancy were further put to the test,
and proved of considerable use, both in comforting and strengthening his friends,
and in overcoming the malice of their enemies.
At length in 1699, he settled with his family in Ireland;
and it appears that his character and services were, in several respects,
much appreciated by the Society in that land.

In the latter part of his life,
after various exercises and honours in the gospel of his Redeemer, both in England,
Scotland, and Ireland, he was visited with much bodily affliction.
He bore all with remarkable patience, was attended with much sweetness in his spirit,
and before he left this world uttered these comfortable expressions.--On one occasion,
his family being about him, he said,
"`Do not put off repentance and amendment of life until the time of a dying bed; for,
commonly, it has enough to do for itself.
The Lord has been very good to me, even from my youth,
and has followed me with his goodness,
and never left me in the time of various exercises:--his presence is near;
and it is manifested to me, that when my departure comes, it shall be in peace.
The Comforter is near, and will endure, +++[+++while these]
afflictions will have an end.`"
To some Friends, who came to see him--"`I have partaken of the earnest of that joy,
which will never have an end: my Rock, my Fortress, my strong Tower, dwells with me,
and does not leave me nor forsake me; blessed be his name!
I hope to be with him forever,--and that is more than a thousand worlds.
There is a mansion of glory prepared in my Father`'s house;--said Christ,
'`There are many mansions; if it had not been so,
I would have told you`'--there has been a discovery of a mansion of glory!`"
Some Friends coming before meeting to visit him, he observed, "`Job was hard put to it,
and his friends were all mistaken, in that they did not believe,
that the Lord did afflict man without a sinful cause.`"
His wife persuading him to take something, lest he should faint, he cheerfully consented,
saying, "`Let me try to eat one bit with my friends;`" but turning the case, added,
"`Christ said,
Labour for the bread that perishes not--but nourishes up
to eternal life.--Praises wait for the Lord in Zion:
np trials, no afflictions,
no temptations can obstruct his presence from the inhabitants thereof:
'`praise is comely for the upright,`' but becomes no wicked person.`"

Sometimes, being much pained with his disorder, he would say, "`Lord! give me some ease,
or take me to yourself.
O Lord! give patience;--sustain and support me under these sharp afflictions:
let the lifting up of my hands be as the evening sacrifice, acceptable unto you!
O Lord! you are my Rock--the shadow of a mighty rock in a weary land.
The Lord has promised to be with his children through the region and shadow of death,
and +++[+++to]
bring them to a lasting eternity, where there is joy forevermore`"--and then,
turning to his wife, he applied the foregoing language to her,
by very briefly intimating that, having such precious promises, she, in particular,
had great occasion to be content under the divine appointments.
At another season, having got some rest in sleep, he queried, "`Why am I kept here?
Let me go home--Lord! receive my spirit,--I recommend my soul +++[+++to you]--receive
me into your everlasting kingdom and the mansion you showed me.`"
A dear friend of his coming in, inquired how he was?
to which he replied, "`I would willingly be gone; the Lord has been very good to me,
and led me through the cross to inherit the crown.`"
Again, he addressed those about him--"`The Lord has been good to me from my childhood:
he began to place his fear in my heart very early.
The Lord never fails those who trust in him; he will be with them to death,
and through death unto eternity.
Fear God, and serve him; prefer his fear above all things, and he will provide for you.`"
And further, to his wife, "`My dear, the Lord is a Father to the fatherless,
and a Husband to the widows that love and fear him;
therefore be content and resigned to the will of the Lord.`"
Some little time before his decease, several Friends who had been at meeting,
coming in to see him, after a season of silence, and one present had spoken a few words,
Alexander, being very much broken into tears, said,
"`It is the invisible power that supports under affliction: Moses endured,
as seeing him that is invisible.`"
Several Friends belonging to Lurgan, Ballindery, and Lisburn meetings visiting him,
in his extreme weakness, his wife asked him, if he knew them?
he replied, "`I do very well; but it is a trouble to me to speak: but all is well,
and will be everlastingly well.`"

His distemper was tedious, and at times exceedingly painful,
but he was preserved in resignation to the last, and in great peace and quietness,
yielded up his earthly being, it is concluded in exchange for an endless inheritance,
on the 23rd of the 1st month, being about 71 years of age.

Robert Scott was convinced of the Truth, as held by this Christian people, at Montrose,
the place of his nativity, where he several times suffered imprisonment;
enduring his share of ill usage,
which largely fell upon them in that town for their
testimony and allegiance to the living God,
who is ever worthy to be waited upon, worshipped, and adored!
Afterward, he settled at Stonehaven: here, it is stated, that the public preachers,
in like manner as at Montrose, began persecuting him,
with a view of inducing him to remove away from the spot.
But, by the judicious counsel of David Barclay, he was induced to stay,
and to endeavour to live down, or wear out so very unworthy a disposition.
This he most completely effected,
by patient continuance in peaceable and upright conduct: for,
betaking himself to merchandizing, by honest dealing and blameless conduct,
his influence won upon his neighbours, and actually prevailed even over his opposers,
so that most of those called clergy round the country sent to him for goods;
and the Lord blessed his endeavours with such success,
that he was reckoned one of the best traders in the place.
Yet was he not in any wise puffed up, but abode in humility,
thankful to the Giver of every good gift, and often praising him for his mercies.
He was a great lover of the assemblies of the Lord`'s children and people; often,
in the throng of business,
leaving all to attend the meetings held in the middle of the week,
and would frequently remark, that he never lost, but often gained by this practice,
saying, these meetings were made to him the best of any.
After his wife`'s death, advancing in years, he wisely retired from business;
and his only son also dying,
he was kindly cared for by a daughter-in-law to the end of his days.
Thus freed from anxiety about the things of time,
he was often giving glory and praise to the Lord, who had bountifully provided for him,
and had graciously afforded him both ease and also contentment in his old age;
so that he had now nothing to do, but to make up his accounts with his heavenly Master.
In this, the first business of his life, he was very diligent; often, in his closet,
three times a day, would he pour forth his prayer to the Almighty;
and a living power attended these ministrations,
whether more privately or in the public gatherings.
At length, about the 75th year of his age,
feeling exceedingly bound to this blessed privilege, and now,
on account of bodily infirmity,
no longer able to meet his friends in their usual place of resort,
he begged they would come and sit down with him in his own apartment;
which request was readily acceded to,
and the practice continued for a month previous to his removal.
Indeed, it so occurred, that one of these solemn opportunities of worship,
was held in his chamber only two hours before he expired, on the 31st of the 3rd month;
when he was so filled with the power and presence of the Lord, that,
with a clear and audible voice,
he presented his supplications unto him who had been with him all his life long,
greatly to the tendering of the hearts of those present, both Friends and others.
After which, in a fervent manner, he several times recommended his own soul to God,
desiring him to finish that great work of gathering his soul; for he could do nothing,
but "`stand still and see`" or "`wait for his salvation.`"
Then, with clasped hands and uplifted eyes,
calling upon the Lord to take his spirit to himself, he yielded it up to Him who gave it.

David Wallace was also of Stonehaven, being born in the year 1660 of honest parents;
his father was a farmer in the parish of Arbuthnot, some miles from there.
When he was about 18 years of age, he began to think upon true religion;
and there being about that time some young men in the neighbourhood,
who struck off from the national way of worship,
and assorted with the people called Quakers,
he came to be much in conversation with them.
And as they discoursed upon the things that belong to life and salvation,
he was often satisfied in their company,
and at length went with them to one of their meetings, which gave him some comfort.
A Friend in the ministry afterward visiting Ury,
he was also inclined to be at that meeting,
where his mind was thoroughly reached by the power of the Lord,
and he became persuaded these were the people with whom he could have fellowship,
and that this was for him the pathway to peace.
On his return home that night, he appeared to his parents to be a changed man;
but they were mightily troubled at the circumstance.
David Wallace had his companions in this straight and narrow way of self-denial,
though few of them faithfully stood their ground in it,
being turned aside by the fear of man, or the love of this present world.
Among these few, was his brother, and especially one David Donaldson, of Allardice.
They met with opposition and difficulties of various kinds,
from both "`professors and profane,`" as also from their own near relatives:
this occasioned them many and heavy exercises; but through all,
the Lord supported and strengthened them by his Divine presence,
his arm being extended for their help, when refuge failed,
so that they were borne above all storms and threatenings.
David Wallace, in particular, came forward steadily,
in all things standing by that cause, which he had thus conscientiously taken up.
Endued with good abilities, he had also a deep judgment in spiritual things,
and his memory in Scripture was so remarkable, that he was termed by some,
the Concordance, being commonly able to give chapter and verse to most passages.
In the place where he lived, Stonehaven,
he was a useful character among his neighbours in their town concerns;
but towards the church to which he belonged, he was serviceable in many respects,
loving to help forward on their way traveling ministers,
and on some occasions accompanying them for a considerable time together,
far distant from his own home.
In his last illness, he signified, that his peace was made with the Lord,
and that he had finished his day`'s work; admonishing those who came to see him,
to be obedient to God in their day,--that he was now ready to be dissolved,
and longed to be with his dear Saviour; to whom, at times, he would pray fervently,
that He would be pleased to be with him through the
untrodden valley of death;--"`yet,`" added he,
"`I will fear no evil, for the Lord will be with me.`"
In this happy state of mind, resigning his own soul,
also his wife and children to the care and protection of the Almighty,
he quietly passed away, on the 4th of the 6th month, being 63 years of age.

Of the next individual, Christian Barclay, no additional particulars have come to hand,
beyond the instructive document, which was issued after her decease,
by those who could best estimate the value of her character.
An abstract of the principal parts of it,
are here subjoined.--Her mind was remarkably turned
to religious considerations from her youth,
publicly embracing the testimony of Truth, in the love of it,
about the 16th year of her age, and that, through many hardships and sufferings;
in this path she all along steadfastly trod, giving evidence both by doctrine,
and by an example becoming the gospel, of her great concern for its prosperity.
She was a well accomplished woman every way, and of singular virtues;
grave and weighty in conduct,
"`diligent in business,`" as well as "`fervent in spirit;`" and therein "`serving
the Lord,`" he was pleased to afford her many precious seasons of refreshment,
wherein she was enabled livingly to testify of his dealings to the children of men,
being plentifully attended with his love and power,
to the great joy and comfort of the faithful; and to the praise of Him,
who has so gloriously revealed himself in this latter age.
In the same love for her fellow creatures,
she laid herself out to assist and give advice to sick people; especially the poor,
whose necessities she freely supplied.

Many of her patients would come ten, twenty, thirty,
and some even forty miles and upwards;
receiving through her care and skill very considerable benefit,
for her success was wonderful; so that, among these classes,
much lamentation prevailed on account of her removal.
Her great and daily concern for the preservation and advancement of her family,
in those things that are most worthy and excellent, has been before adverted to,
as well as for the welfare of the youth in general, who came under her notice.
The bright influence of her example had great effect upon her children and grandchildren,
eight or ten of whom she usually had at a time under her roof;
and she was permitted to see the Divine approbation and blessing,
remarkably crown her endeavours on their behalf.
But her efforts and exercises, not confined here, were directed for the good of all;
especially for the church--that no slackness or unconcern might be entertained,
and that every one professing Christ,
might use all diligence to make their calling and election sure.
During her last illness, many were her pious expressions,
all tending to the same purpose,--for sickness altered not her frame of spirit;
the earnest, unabated desire prevailing with her to the last, that in life and in death,
she might be a faithful servant of the Lord.
At length she yielded up her spirit in great peace, joy, and quietness,
on the 14th of the 12th month, having outlived her husband 32 years,
and being herself in the 76th year of her age.

Respecting the family left by this "`mother in Israel,`" there have already
been some promising and rather unusually hopeful circumstances recorded.
That they were favoured to hold on their way,
in the line so highly recommended to them by the piety, the prayers,
and spiritual nurture of their parents, there is no cause to doubt:
but the information which might have cleared up this point, is,
with regard to some of these children, defective.
They were seven in number.
Christian, one of the daughters, treading in the footsteps of her mother,
was valued as a faithful honorer in the gospel field.
She was married in 1699 to Alexander Jaffray, son of Andrew Jaffray;
and her decease took place as late as the year 1751; after a long life spent,
according to the representation of survivors,
"`from early youth to her latest moments,`" in sincere dedication to the path of duty.
The three other daughters were married into the Forbes family of Aquorthies;
while two of the sons, David and John, settled,
the one in London and the other in Dublin.
Robert, the eldest, succeeded to the estate of Ury,
which is still in the family:--and he succeeded also, as we have already seen,
to the spiritual heritage of those that fear the Lord,
through acceptance of "`the spirit of adoption,`" whereby the children
of all true believers may become the children of God.
Besides his journey to the Highlands, he travelled several times,
in the line of ministry, to London and other parts of England and Scotland;
was zealous in propagating that which he believed to be the truth of the gospel,
among his Friends and others; charitable to the poor,
humble and meek in his deportment, benevolent to all.
He also wrote one or two small treatises.
About two years before his removal by death, which took place in 1747,
on the completion of his 75th year, he contracted much weakness of body; which, however,
did not prevent him from being diligent in attending religious meetings in the neighbourhood.
In a submissive state of mind, he waited his last change;
and when much afflicted by disease, used to say, "`Not my will,
but the Lord`'s be done in everything.`"
And, a short time before he became speechless, one standing by his bedside,
thinking he did not hear, whispered to another,
that she was surprised to perceive such a sweat upon him;
on which he answered with a strong voice,
"`This is the sweat which comes before death--and I shall
now soon be among the spirits of just men made perfect.`"
Shortly afterward he, as it were, slept away, expiring at his house of Springhalt,
near Ury; and giving ample proof, to the last,
that he had been made partaker of those highly spiritual views of the gospel dispensation,
which the Society of Friends have been called to uphold;
the consistency of which standard, has been of late, in several respects,
increasingly acknowledged by most other Christian communities.
