== Chapter XIX.

[.chapter-synopsis]
* 1736: Sketch of Andrew Jaffray`'s life, death, and character, with some account or his family

The Jaffrays have been prominent throughout the greater part of this volume.
As the _first_ portion of it was wholly devoted to
the religious experience of _one of that family,_
who became the foremost in the north of Scotland to show
himself a convert to the opinions of the Friends;
so has their name been conspicuous in the _present_ division of the work,--holding
no unimportant position among their associates of this persuasion.
For no sooner had the memoirs of Alexander Jaffray been pursued to a conclusion,
than we find _his son Andrew,_
deliberately attaching himself to the same stock of Christian reformers; and proving,
through a long life of dedication, the sincerity of his views.
And now, that the reader is about to quit these historical collections,
there are yet to be submitted to his attention a few summary particulars concerning
the life and latter end of this individual,--__the last of that generation of worthies,__
whose memory deserves to be held up to a succeeding age.

Andrew Jaffray, from his earliest years, was one,
on whose behalf ascended the continual incense of parental prayer.
This, the Diary of his father gives full warrant for asserting,
if the general character and profession of both parents
is not alone sufficient to prove it.
He was also permitted the inestimable privilege of their counsel, example, and care,
up to the period when he became of age; shortly after which,
and within a very short interval, it may be remembered,
he was by death deprived of both of them.
They seemed, indeed, at their departure, to have set a broad seal of recommendation,
not likely soon to be effaced from the mind of their son,
in favour of those gospel views, which they themselves had so firmly embraced.
Of Andrew, it is recorded,
that in his very youthful days he was reached unto by the power of God; so that,
many times, in secret places, he would be broken into mourning and tears before him;
being attended with a fear,
lest he should be utterly cast off from the Divine presence and favour.
Yet afterward,
this good concern and working of the Holy Spirit upon his heart was considerably withdrawn,
by giving way to youthful vanity, and his own desires and devices; although at times,
on these accounts, still pursued with strong convictions,
as well as wonderfully preserved by merciful interposition
from the more gross outbreakings of evil.
When arrived at about the 24th year of his age,
the Lord once more condescended effectually to visit him,
and to awaken him to a deep sense of his miserable condition while in a state of nature.
Submitting to those righteous judgments,
which lay heavily upon him for sin and transgression, he became as a tender penitent,
prostrated before the all-seeing and holy God,
being made altogether willing to undergo the secret but
effectual operation of the heavenly leaven within him.
Thus, in due season, was he given to know in his measure,
the fulfilment of that Scripture passage,
which the Apostle applies to some believers in his day, "`But you are washed,
but you are sanctified, but you are justified, in the name of the Lord Jesus,
and by the Spirit of our God.`" 1 Cor. 6:11.

At length he was called upon by Christ, who had become his Saviour, his Leader,
and his Light, to proclaim unto others that grace by which we must be saved,
and of which he had so richly partaken.
His father had given him a liberal education;
but when brought to behold the simplicity and beauty of the Truth as it is in Jesus,
we are told, that he quickly came to esteem all learning but as dross and dung,
compared with the learning and knowing Jesus Christ according
to his second or spiritual coming in the soul,
and a being hereby purified from all dead works to serve the living God.
For this appeared to him to be one end and purpose of His coming in the flesh,
that he might put an end to sin, finish transgression,
and bring in everlasting righteousness.
In the promulgation of such glad tidings, he soon became a zealous, faithful,
and able minister; for his heart was freely given up to labor,
as well for the convincement of those who were scattered
upon the barren mountains of an empty profession,
as for the confirmation of such as were acquainted with the things of God`'s kingdom.
His utterance is represented as clear, full, and penetrating;
in doctrine and argument he was sound, bold, and perspicuous;
on many occasions to the confusion and defeat of those who undertook to oppose his testimony,
which was often levelled with great power against _all description of will-worship,
and a spurious or man-made ministry._
Yet in his demeanour, there was remarkable humility manifested,
being always disposed to esteem others better than himself,
though a great despiser of the honour, riches, and vain glory of this world.
He was eminently led forth as an instrument on various public occasions;
and had a peculiar talent in visiting the sick,
but especially the distressed of every rank, profession,
and character within his reach--and with great acceptance;
"`many,`" as his friend Robert Barclay _the younger_ observes,
"`bearing grateful remembrance of his love and service,
and of the strength and efficacy that attended his ministry of consolation.`"
For, he was a man who, through life,
had travelled much in the track of the "`weary and heavy laden,`" having had
in his own experience to pass through many deep and bitter exercises of spirit,
with manifold temptations of the enemy.
This kept him in a fresh and humble condition, and in great tenderness towards others;
always admiring the boundless mercy and long-suffering of God, who, through all,
had preserved him from fainting and showed him favour,--raising him over all,
to bless his holy name!

It is not needful here to specify the cheerfulness and alacrity,
with which he underwent any hardship that might befall him,
in those services to which he believed himself called;
his sufferings for conscience sake having been amply
testified of in the course of this publication.
He was a very useful man among his neighbours,
endeavouring to serve the interests of vital godliness,
to disseminate the true faith of Christ, and to follow peace with all men.
Among his friends, he was a pattern of good works and of gospel order;
one who tenderly cherished whatever in religion savoured of that heavenly life,
without which all observances are vain; at the same time,
strenuous and unyielding in his opposition to that which
he fully believed _gendered to bondage_ and spiritual death.

Andrew Jaffray travelled in the work of the ministry
in various parts of his native country,
and in England; once, in the year 1698, being accompanied by his daughter Margaret, who,
like some females of old, _laboured with him in the gospel._ Phil. 4:3.
She also, two years afterward,
undertook a journey on the like errand of love both to England and Ireland,
being then but a young woman.
Her friends describe her to have been a worthy and zealous preacher of righteousness,
as well in life and conduct as in word and doctrine.
On one occasion, she addressed the inhabitants of Aberdeen with a paper,
on the subject of an appointed fast which had been then recently kept;
the danger of hypocrisy and formality in such stated observations,
no doubt had strongly affected her serious and feeling mind.--Another circumstance,
it will be proper to notice respecting this individual,
before resuming the account of her father.

Among the _Excerpts_ from the Register of the Presbytery of Aberdeen,
as given in a History of that place,
the following appears among the remarkable events "`1698. 17th February.--Last Sabbath,
at Newhills, Margaret Jaffray, daughter of Andrew Jaffray of Kingswells,
coming with other Quakers, entered the church, and cried, '`Do not believe that deceiver,
etc.`' "`--The Author did not think himself at liberty
to omit the insertion of this record;
for unquestionably, Andrew Jaffray, as well as his daughter,
with Robert Barclay _the Apologist,_ and many other ministers among the early Friends,
several times took their share in such very humiliating line of testimony.

In several publications relating to these times,
some of them of late years brought before the public,
statements somewhat similar have been made;
without being accompanied by any explanation of the attendant circumstances,
under which such extraordinary conduct took place.
It would be surely better for the interests of religion in _general,_
that facts so peculiar in their nature were not revived at all,
than that they should be exhibited in an inadequate and unsatisfactory manner.
Otherwise, there is reason to apprehend, the _"`obnoxious`"_ practice simply considered,
will not have by any means excited that contempt and prejudice against the sacred cause,
which the _recital_ of the fact is likely to do.
The enemies of the cross of Christ are thus, perhaps unintentionally, strengthened;
whereas, had these themselves witnessed the whole transaction,
and known the situation of the parties concerned, it is not improbable,--no,
_it has happened,_ that some present on such occasions,
have been so impressed with the scene,
as actually to have protected the poor individual from the insults of those,
who should have been examples to others.
The undistinguishing outcry of enthusiasm and fanaticism has not ceased;
but is from time to time still poured upon the more
deeply exercised votaries of the Lamb.
Let us not forget,--__He__ was a man of sorrows,
whose visage was more marred than that of any man, despised and rejected,
so that many hid as it were their faces from him;--and it is to be feared,
that thus his followers and little ones are oftentimes treated.
When we view a set of men, upright, sincere, and consistent in all their actions,
of a sober and sound mind, studying to be quiet and to do their own business;
when we see such as these, fervent also in spirit, serving the Lord in much simplicity,
the zeal of whose house has, to appearance, eaten them up--and this,
not merely for selfish ends or to obtain popularity,
not to preach only _the name_ of Christ and the forms of godliness,
but likewise _his transforming power;_--should we not
pause?--should we not endeavour to discriminate,
and look to the bottom of their motives,
who are so raised above the variable and ambiguous rules of refinement and of custom,
in the desire to clear their own consciences of the blood of their brethren,
as in the sight of that Searcher of hearts,
whose ways are higher than our ways and his thoughts than our thoughts?
Do we see nothing in their _unmannerly protest,_
in any respect analogous (however distant and feeble the analogy
must be,) to that procedure of the lowly and holy Jesus,
when he went into the temple of God,
and so severely expostulated with those who had appropriated the
solemn occasion of Divine service to the purposes of merchandize?
Or can we imagine nothing in _our own_ practice, approaching to the conduct of those, who,
when Paul and Barnabas had given proof of their mission,
according to that which was committed to them, blasphemously though ignorantly cried out,
"`The gods are come down to us in the likeness of men`"? And,
were thoughts in any degree resembling these to steal over us,
should we brand with enthusiasm the sudden impulse of godly jealousy,
which might urge a Paul or a Barnabas to run in between us and _our impious
sacrifices at the shrine of men?_--Not that by this train of reasoning,
it is to be understood,
that a religious community must be responsible for every wild act
of intemperate pretenders to a Divine and Scriptural commission.
"`Believe not every spirit,`" said the Apostle, "`but try the spirits,
whether they are of God.`" 1 John 4:1.
And if it be asked, _How?_
Hear the Master himself:--"`He that does truth comes to the light,
that his deeds may be made manifest, that they are wrought in God.`" John 3:21.

In addition to the above observations,
those of the judicious and candid historian of this Society, Sewell,
may here be properly brought in upon the same subject.--"`Perhaps some will think
it was very indecent that they went so frequently to the steeple-houses,
and there spoke to the priests.
But whatsoever any may judge concerning this,
it is certain that those teachers generally did not bring forth the fruits of godliness,
_as was well known to those who themselves had been priests,_
and freely resigned their ministry, thenceforth to follow Christ in the way of his cross;
and _these were none of the least zealous against that society,
among whom they formerly had ministered with an upright zeal._
Yet they were not for using sharp language against such teachers,
who according to their knowledge feared God;
but they levelled their aim chiefly against those who were only rich in words,
without bringing forth true Christian fruits, and works of justice.`" [.book-title]#Sewell`'s History,# vol. i. p. 128.

Having thus adverted to one of the daughters of Andrew Jaffray,
this will be the most fit place to introduce a brief but precious memorial of another,
Lilias, who was so named in remembrance of her honoured grandmother, Lilias Skene.
The Friends in Aberdeen and the neighbourhood, in their united capacity,
were induced to convey their genuine unsophisticated feeling, upon occasion of her death,
by a simple record of her worth.
This they did, not with any view of puffing up the vain mind in youth or others;
but as an encouragement to survivors of every class, to aim at, wrestle for,
and breathe after that purity of heart,
which the filial fear of our beneficent and heavenly Father will not fail to bring forth.
Her example, thus held up,
is an illustration of the force and value of Solomon`'s beautiful language:--"`The
fear of the Lord is the beginning of wisdom--get wisdom,
get understanding--forsake her not, and she shall preserve you; love her,
and she shall keep you--exalt her,
and she shall promote you--she shall give to your head an ornament of grace;
a crown of glory shall she deliver to you.`"

"`Upon the 1st of the 4th month, 1694,
it pleased the Lord to remove out of the body a dear young plant, Lilias Jaffray,
eldest daughter to Andrew Jaffray, being near 20 years of age; who,
as she was of a very loving, sweet, innocent nature from her infancy,
had also drank in a tender, sweet love to the Truth and to Friends, being beloved of all,
both Friends and other people, that ever knew her.
She was exceeding subject and obedient to her parents in the Lord;
so she laid down her body in a sensible feeling of God`'s love and favour,
and unity of Friends, the said day, a little before one in the morning.
Her body was buried in her father`'s burial-ground at Kingswells,
upon the 3rd day of the said month, being a 1st day,
after a good meeting and good service at the burial-place.`"

After this servant of the Lord, her father, had been honoured by bearing witness,
for upwards of fifty years,
to the excellency of the saving and spiritual knowledge of Christ Jesus,
having conducted himself in the world in much simplicity and godly sincerity,
"`not with fleshly wisdom,
but by the grace of God,`"--he was cast upon the bed of sickness,
and seemed not likely again to be restored to the church.
During that dispensation, a calumnious report was industriously propagated in Aberdeen,
that he totally denied those principles, which he had so long and so nobly defended.
This circumstance, as he subsequently acknowledged, in a writing dictated by himself,
and signed only two days before his death, "`made me, after my last great sickness,
the more willing to be restored, in subjection to the will of God; and I am made willing,
though some years after,
to leave this testimony,--whatever evil men or others may say against
me,--that if it be the Lord`'s will to remove me at this time,
I die in unity with the Friends of Truth.`"
Though favoured with some degree of returning health,
the pressure of natural infirmity was latterly very heavy upon him;
yet was he again and again strengthened publicly to advocate
the gospel of the free and unmerited grace of God;
for, even up to the last day before he took to his chamber,
he exhorted and commended his friends to cleave to it.
When confined to the bed for some months, under much bodily weakness, distress,
and conflict,
not without the buffetings of Satan,--the energies of the outward man gradually
decaying,--he experienced the frequent rekindling of his desires and hopes heavenward;
and was often engaged in a lively, clear strain,
to set forth his admiring sense of the Lord`'s goodness towards his soul.
He breathed his last on the 1st of the 2nd month, 1726, in great peace,
and full assurance of an everlasting portion among the followers of the Lamb;
his remains being interred in his own burial-ground on the family estate of Kingswells.

In the paper above referred to, taken down so shortly previous to his removal,
he thus alludes to the memorable outpouring of the Holy Spirit,
of which he and others were made partakers,
during the time of their long imprisonment at Aberdeen.--"`Oh! the unutterable glory,
that broke forth and spread even in this country,
wherein God Almighty raised up some mean instruments, as well as some more honourable,
and myself among others, though very unworthy!
And when thirty or forty of our ancient Friends were shut up in prison,
I cannot but remember this particular instance;
that when we were all met in the low Tolbooth, and not a word had been spoken among us,
either in prayer or preaching,--we breathing in our hearts for power to do the
Lord`'s will;--his power at last broke in among us in a wonderful manner,
to the melting and tendering our hearts.
And though I was kept very empty a long time,
yet at last the glorious power of God broke over the whole meeting, and upon me also,
and ravished my heart,--yes, did appear as a ray of divine glory,
to the ravishing of my soul, and all the living ones in the meeting.
So that some of those that were in the town-council above us,
confessed to some of our number with tears, that the breaking in of that power,
even among _them,_ made them say one to another, '`O! how astonishing it is,
that our ministers should say, _the Quakers have no psalms in their meetings;_
for such a heavenly sound we never heard in either old or new church.`' After this,
our meetings were often filled with heavenly, divine comfort,
to the satisfaction of our souls, and we were often overcome with the love of our God,
and many innumerable instances of his miraculous power attended us;
_many of which are recorded in a book for posterity to come._
And God will tread down Satan under the feet of his power in due time,
let him rage as he will.`"
