[short="Notes to the Memoirs"]
== Appendix of Notes and Illustrations to the Memoirs.

[#note-A.centered]
=== Note A.

A person of some note, who had been an officer under Oliver Cromwell,
related to James Wilson the following anecdote.--"`After the battle of Dunbar,
as I was riding in Scotland at the head of my troop, I observed,
at some distance from the road, a crowd of people, and one higher than the rest;
upon which I sent one of my men to see, and bring me word,
what was the meaning of this gathering.
And seeing him ride up and stay there, without returning according to my order,
I sent a second, who stayed in like manner; and then I determined to go myself.
When I came there, I found it was James Nayler preaching to the people;
but with such power and reaching energy, as I had not till then been witness of.
I could not help staying a little, although I was afraid to stay;
_for I was made a Quaker, being forced to tremble at the sight of myself._
I was struck with more terror by the preaching of James Nayler,
than I was at the battle of Dunbar, when we had nothing else to expect,
but to fall a prey to the swords of our enemies, without being able to help ourselves.
I clearly saw the cross to be submitted to; so I dared stay no longer, but got off,
and carried condemnation for it in my own breast.
The people there, in the clear and powerful opening of their states,
cried out against themselves, imploring mercy, a thorough change,
and the whole work of salvation to be effected in them.`"--See [.book-title]#J. Gough`'s Journal.#
<<note-A__xref_src,?LINKABLE-BACK>>

[#note-B.centered]
=== Note B.

Extract from [.book-title]#Memoirs of the Life of Stephen Crisp,# 1824, p. 53.
"`About the year 1659, I often felt the aboundings of the love of God in my heart;
and a cry, to stand given up to his will;--which I thought I was,
not knowing or foreseeing what the Lord was intending to do with me;
but his eye saw further than mine.
This love, and tenderness, and bowels of compassion wrought so in me,
that it extended even to all men on the whole face of the earth,
so that I cried in spirit, _Oh, that all men knew You and your goodness!_
And, upon a time, as I was waiting upon the Lord, his word arose in me,
and commanded me to forsake and part with my dear wife and children, father and mother,
and to go and bear witness to his name in Scotland,
to that high professing nation.`"--"`Oh! how I would have pleaded my own inability,
the care of my family, my service in that particular meeting, and many more things;
and all, that I might have been excused from this one thing which was come upon me,
that I thought not of, or looked not for.
But after many reasonings, days and weeks by myself,
I thought it best to speak of it to some of the faithful
elders and ministers of the everlasting gospel;
not knowing but they might discourage me, and something there was which hoped it,
but contrarily, they encouraged me, and laid it upon me to be faithful.
So then I gave up, and acquainted my dear wife therewith, which began me a new exercise,
the enemy working in her strongly to stop me.
But, in much patience was I kept, and in quietness;
and went and visited Friends`' meetings about Essex, and part of Suffolk,
chiefly to see them, and to take my leave of them;
and in some meetings the Lord would open my mouth
in a few words to the refreshing of Friends;
but I rather chose silence, when I might so.
The winter drew nigh, and something would have deferred it till next summer;
but the Lord showed me, it was not to be _my time,_ but _his time._
Then, I would have gone by sea; but the Lord withstood me, and showed me,
it must not be _my way,_ but _his way;_ and if I would be obedient,
he would be with me and prosper my journey, otherwise his hand would strike me.
So I gave up _all;_ and pretty much with cheerfulness, at last, I obeyed;
and about the end of the 7th month +++[+++old style]
I went forth, and visited the churches of Christ.

"`As I went along in Lincolnshire and Yorkshire, I quickly perceived,
that the Lord was with me, more than at other times; and my journey became joyful,
and the more so, in that though I were but weak, poor, and low,
yet God gave me acceptance among the elders of his people; and, in every place,
my testimony was owned, and many were convinced of the everlasting Truth:
then I marvelled, and said, _Lord! the glory alone belongs to you,
for you have wrought wonders for your name`'s sake, and for your holy seed`'s sake._
I got into Scotland in the 9th month that year,
and travelled to and fro that winter on foot with cheerfulness.
Many straits and difficulties attended me, which I forbear to mention;
it being the time of the motion of the English and Scottish armies,
upon which succeeded the revolution of government,
and the bringing back of King Charles the 2nd into England.
Well, about the 11th or 12th month I returned, and travelled into the west,
to Westmoreland, part of Lancashire, and so up to the southward;
and in about five or six months`' time, was, by the good hand of God,
brought home to my wife, and children, and relations;
in all my journey having been sweetly accompanied with the presence of the Lord;
and his power often filled my earthen vessel, and made my cup to overflow;
praises forever be to his name! says my soul.`"
<<note-B__xref_src,?LINKABLE-BACK>>

[#note-C.centered]
=== Note C.

In explanation of the use of the term "`steeple-houses`" in this paragraph,
readers not connected with the Society of Friends,
are referred to the following note which occurs in "`Select
Anecdotes,`" etc. illustrative of their sentiments and conduct,
by the Author of the present volume.

"`It seems scarcely needful to remark,
that the word _'`church`'_ is in Holy Scripture never
applied to an outward temple or building,
but to a company of believers, whether generally or particularly.
A Friend being interrogated by a bishop, Why he did not go to church?
replied, '`I _do_ go to church;
and sometimes the church comes to me.`' See 1 Cor. 16:19, Col. 4:15, and Philem.
2+++.+++ Thus the use of this term appears to have crept in among Christians,
and with it a superstitious _consecration_ of those places,
as possessing some latent quality, not affecting other works of art or nature.
To this, Stephen the martyr evidently alluded, when he said, '`Howbeit,
the Most High dwells not in temples made with hands,`' etc. Acts 7:48.
The term '`steeple-house`' not infrequently
occurs in the early writings and records of Friends.
It may sound harsh to most ears,
if it does not seem to savour of the scurrility and intolerance of that zealous age:
yet the reader may be assured, that this,
or any other mode of speech adopted among us as a people,
was by no means taken up for the purpose of opprobrium,
but rather significantly to discover the little veneration
or distinction they could show for these buildings,
more than for their own habitations;--they believing,
that the Almighty is equally present everywhere,
to bless and to sanctify every place and everything to those that
walk uprightly on the earth--his footstool.`"
<<note-C__xref_src,?LINKABLE-BACK>>

[#note-D.centered]
=== Note D.

Elizabeth Goodall has been already thus briefly mentioned
by Jaffray in his Diary,--__"`that gracious woman,
Elsinet Smith.`"__
Some readers may not be aware,
that the married woman in Scotland usually retained her maiden name.
_Elsinet_ and _Elspit_ are concluded to be Scottish variations of _Elizabeth._
In the Records of the Society of Friends at Aberdeen,
this minute appears on occasion of her death.--"`Upon the 21st day of the 12th month,
1691-2, it pleased the Lord to remove from the visible +++[+++church,]
our dear and ancient friend, Elspit Smith, relict of Andrew Goodall,
who was one of the first gathered hereaway, an honest and serious woman,
whose body was peaceably and honourably buried in Friends`' burial-ground
in this city on the 23rd day:--The Lord having given his children
victory over that wicked and inhuman spirit,
that so often and long stopped our burials and raised our dead; +++[+++so]
that now they are as peaceable and quiet as any other,
and attended with many people and the magistrates of the city.`"
This last passage will be explained in the course of the history.
<<note-D__xref_src,?LINKABLE-BACK>>

[#note-E.centered]
=== Note E.

John Boccold, a tailor of Leyden, leader of a mob, who,
entertaining wild notions about liberty and equality,
possessed themselves of Munster in Westphalia,
about the year 1535. The inhabitants of the Low Countries joined him,
and Munster became in their imagination Mount Zion,
and this man fancied he was called to sit on the throne of David.
His fanaticism was connected with the most unrestrained licentiousness and extravagant
conduct.--[.book-title]#Mann`'s Lectures on Ecclesiastical History and Nonconformity,# p. 225.
<<note-E__xref_src,?LINKABLE-BACK>>

[#note-F.centered]
=== Note F.

Doubtless, it was in allusion to such instances as this of George Gray,
that Robert Barclay thus speaks: "`If in any age since the apostles`' days,
God has purposed to show his power by _weak instruments,_
for the battering down of that carnal and heathenish wisdom,
and restoring again the ancient simplicity of Truth, this is it.
For, in our day, God has raised up witnesses for himself, as he did fishermen of old;
many, yes, most of whom are laboring and mechanic men: who,
altogether without that learning,
have by the power and Spirit of God struck at the very root and ground of Babylon;
and in the strength and might of this power, have, by reaching their consciences,
gathered thousands into the same power and life, who, as to the outward part,
have been far more knowing than they,
yet not able to resist the virtue that proceeded from them.
Of +++[+++this]
I myself am a true witness, and can declare from a certain experience,
because my heart has been often greatly broken and tendered by that virtuous life,
that has proceeded _from the powerful ministry of those illiterate men:_
so that by their very countenance, as well as words,
I have felt the evil in me often chained down, and the good reached to and raised.
What shall I then say to you, who are lovers of learning and admirers of knowledge?
Was not I also a lover and admirer of it,
who also sought after it according to my age and capacity?
But it pleased God in his unutterable love, early to withstand my vain endeavours,
while I was yet but eighteen years of age; and made me seriously to consider,
(which I wish also may befall others,) that without holiness no man can see God,
and that the fear of the Lord is the beginning of wisdom,
and to depart from iniquity a good understanding; and how much knowledge puffs up,
and leads away from that _inward quietness, stillness, and humility of mind,
where the Lord appears and his heavenly wisdom is revealed._
If you consider these things, then will you say with me, that all this learning, wisdom,
and knowledge, gathered in this fallen nature,
is but as dross and dung in comparison of the cross of Christ;
especially being destitute of that power, life, and virtue,
which I perceived these excellent (though despised,
because illiterate) witnesses of God to be filled with.
And therefore, seeing that in and among them I, with many others,
have found _the heavenly food that gives contentment,
let my soul seek after this learning, and wait for it forever!_ [.book-title]#Barclay`'s Works,# fol. p. 426. or [.book-title]#Apology,# Prop. 10. sect 23.
<<note-F__xref_src,?LINKABLE-BACK>>

[#note-G.centered]
=== Note G.

Respecting the persecution of the Scottish Presbyterians,
between the time of the Restoration and the Revolution, Cruickshank, their historian,
in his preface has this comprehensive language.--"`Many were exorbitantly fined,
unjustly imprisoned, oppressed by soldiers,
plundered by dragoons and a lawless Highland host.
Multitudes were forced to wander about in dens and caves of the earth.
Not a few were tortured by boots, thumbkins, firematches, etc.
Some were beheaded, others were hanged and quartered; women as well as men,
suffered death; some of them were hanged, and others drowned;
prisons were crowded and ships were loaded with prisoners,
who were banished from their native country, of whom many perished.`"
etc. etc.--It is much to be regretted, that this class of Protestants,
do not appear as a body,
to have been sensible of the imperative duty there is upon Christians,
when they are called to suffer, not to resist the evil, nor even to threaten evil,
but to commit themselves and their cause to His keeping,
who rules "`the raging of the sea,`" and ever sustains
his children that trust in Him alone.
Certainly, by adopting another course,
the Covenanters obscured the brightness of their testimony, and provoked their enemies,
instead of heaping "`coals of fire`" on their heads.

Cave, in his [.book-title]#Primitive Christianity,# has this passage relative
to the conduct of the first followers of our blessed Lord:
it is deemed particularly worthy the attention of the reader,
before he enters upon the narrative of the persecution of the Friends in Scotland.

"`And if they did not run away from suffering, much less did they oppose it,
and make tumults and parties to defend themselves; no,
they were led as lambs to the slaughter, and as sheep before the shearers are dumb,
so opened not they their month, but committed their cause to Him who judges righteously,
and who has said, Vengeance is mine, and I will repay it.
None of us, says Cyprian to the Governor, when apprehended, makes resistance: nor,
though our party be large and numerous,
revenges himself for that unjust violence that you offer to us.
We patiently acquiesce in the assurance of a future vengeance;
the innocent truckle under the unrighteous,
the guiltless quietly submit to pains and tortures; knowing for certain,
that whatever we now suffer, shall not remain unpunished;
and that the greater the injury that is done us in these persecutions we endure,
the more just and heavy will be that vengeance that will follow it.
_Never was any wicked attempt made against Christians,
but a divine vengeance was seen at the heels of it.`"_ 3rd edit. p. 175.
<<note-G__xref_src,?LINKABLE-BACK>>

[#note-H.centered]
=== Note H.

The following is a brief outline of the career of George Keith,
whose name does not often appear prominent in these Memoirs:
it is principally abstracted from the supplement
to the last edition of [.book-title]#Thomas Ellwood`'s Life.#

George Keith was educated in the Presbyterian Church, was a man of talent and learning,
and had obtained the degree of Master of Arts in the University of Aberdeen,
the place of his nativity.
During a period of about thirty years,
he had been a public and zealous advocate of the principles held by Friends;
but becoming one of the earliest settlers in Pennsylvania,
after residing there about ten years,
he was the means of aggravating by a religious schism,
the political differences which then agitated that infant colony.
He had imbibed notions subversive of all social order,
which led him to conduct himself with great disrespect
towards the civil authorities in the state;
and rendered him dissatisfied also with those wholesome restraints,
which the Society in its church discipline enjoins upon its members.
Not stopping here, he opposed and ridiculed some of those very doctrines and practices,
in support of which, he had both written, preached, and suffered: at length,
having formed a separate congregation,
they assumed the denomination of _Christian Quakers._
His adherents, however, gradually forsook him,
perceiving that his religious tenets were fast verging
towards those of the "`Established Church of England.`"
He actually obtained the living of Elburton parish in Sussex,
where he ended his days in the year 1715, maintaining nearly, if not quite, to the last,
a violent opposition against the Friends and their principles.

The following affectingly interesting letter,
was addressed by the Friends at Aberdeen to George Keith and his wife Elizabeth,
not long after the former had discovered sentiments,
at variance with those of the Society.
Elizabeth`'s maiden name was Johnston; of whom honourable mention has been made,
among others of the earliest supporters of this cause and people.

[.embedded-content-document.letter]
--

[.salutation]
Our ancient Friends, George and Elizabeth Keith!

What love and respect has, and does all along live in our hearts to you both,
we shall leave to Him that best knows our hearts,--as to those,
whom the Lord made eminently instrumental in your several stations,
to build up his church and people hereaway in love and unity, in the most holy faith,
upon that sure foundation, Christ within, our '`hope of glory:`'--and also,
the one of you so valiantly to defend the principles
of this holy Truth against its opposers,
to the confounding of them.
And +++[+++it]
rejoiced the hearts of God`'s children, in seeing,
(by his precious gifts of understanding and opening the mysteries
of this glorious gospel and inward treasures thereof,) the universal,
free love of God to all mankind, to be so excellently demonstrated both from Scripture,
inward experience,
and testimonies of many sorts;--especially by these two excellent treatises of '`Immediate
Revelation,`' and '`The Universal Light or free grace of God asserted,`' etc.
And how glad should our hearts have been, to have found you, George, going on,
as moved thereunto, to improve your talents, which the Lord has liberally given you,
for further spreading the beauty, fame, excellency, and loveliness of this precious,
inward plant of renown; and so edifying, comforting,
and strengthening the flocks of Christ, as in pastures of love,
that the beauty of the love of brethren in unity might flow as sweet ointment,
to make the lamp of Truth shine with lustre throughout
the world,--as in due time we believe it shall.

But with what grieved and bowed down hearts and spirits we first heard,
and afterward came to see, _that_ to be published by you, and some others joined with you,
which,
(as is found in the very entry of one of the treatises) will grieve the honest-hearted,
and make the uncircumcised rejoice, and say, '`Ah! so would we have it:--they, yes,
the chief champions among them, are now confessing what their enemies preached,
That there are as great errors among them, called Quakers,
as among other people,--and particularly +++[+++your]
undervaluing the outward appearance and sufferings of the Son of God, and not +++[+++being]
sound about the resurrection.--O George! bear with us in love, for we can say,
it is in tender breakings of heart we utter it,
and in tender breathings for you,--that if that sweet, healing, meek,
self-denying spirit of lowly Jesus had been kept and abode in,
your breaches thereaway would have been handled after another manner;
and such a sad occasion to amuse the world, sadden the hearts of God`'s children,
and rejoice the enemies of Zion`'s peace and prosperity, had never been told in Gath,
nor published in Askelon.
Though we doubt not, but there have been provocations on both sides,
(and we own the errors of none,) yet we must say, that that bitter, rending,
forward spirit, that would publish so hastily to the world such sad tidings,
was not of God: and as for our spreading the books, or accounts thereof,
we are in no way free thereunto.
Blessed be the Lord our God! though we be but a few in number, yet love, unity,
and peace, is in a measure among us; and our esteem of the most precious, saving,
sufficient Light and grace of Christ within, the hope of glory,
is rather growing than diminishing among the faithful; and we know assuredly,
all in every nation that fear God, (who is Light) and work righteousness, are,
and shall be accepted of him; and no more is required of any, than he gives them,
though ignorant as to +++[+++the] outward.

So, our dear and ancient Friends,
we earnestly desire you to receive in a right mind our innocent freedom and love; and,
in the cool of the day,
go forth again with your brethren into the ancient green pastures of love,
and to the healing springs of life: giving up to fire and sword that which is for it;
so the first and the last works shall be precious together;
then '`righteousness and peace shall kiss each other:`' And we can say,
(appealing to the Lord our God, the searcher of hearts,) our joy shall be great,
to hear that the sweet, healing, and uniting life has,
or shall make up all these breaches in Israel`'s camp, by all of us submitting to it,
and the true judgment thereof in his church; and,
in this sweet ancient spring of our Father`'s love,
wherein we have often been sweetly refreshed together many years ago,
shall we truly rejoice to hear from you,
and also to see your faces,--who remain your true Friends and well-wishers.

[.signed-section-context-close]
Aberdeen, 23rd of 3rd month, 1694.

--

Gough, in his [.book-title]#History of Friends,#
states his reasons for supposing that George Keith was favoured,
particularly near his latter end, with seasons of serious reflection; wherein,
he viewed the peaceful state of his mind,
while in unity and peace with the "`Quakers`" as brethren,
and felt remorse under the loss of it.
On one occasion, as he lay ill on his deathbed,
he was visited by Richard Hayler of Sussex; and, among other things that passed,
he expressed himself in these words,--"`I wish I had died when I was a Quaker; for then,
I am sure, it would have been well with my soul.`" vol. iii. p. 452, and vol. iv. p. 147.
At the latter page, this author closes his narrative with some weighty cautions,
adapted especially _to the gifted members of this,_
or indeed _of any religious body,_--to beware of _an exalted spirit._

The reflections, likewise, made in their Journals,
by two highly respectable members of the Society, who were contemporary with George Keith,
deserves the attention of those who read his history.
The first occurs in the [.book-title]#Memoirs of John Whiting,# p. 496.

"`I would not say, as some are apt, when any fall away, that they were never right,
_for a righteous man may turn from his righteousness;_ knowing by his writings,
that he had a true convincement and work of God upon him; and was enlightened,
and had _tasted of the heavenly gift, and of the powers of the world to come;_
as his '`Help in time of need,`' his '`Immediate Revelation,`' '`The Benefit, Advantage,
and Glory of Silent Meetings`' with several others of his writings, do show:
and he was serviceable with Robert Barclay in some controversies in defence of the Truth,
and in some others, and +++[+++was]
valued for his gifts,
while he used them in humility and subserviency to the Truth.`"--John
Richardson winds up a narrative of many pages,
with these important observations.--"`This account carries in it an admonition to us,
and to Friends in future ages, into whose hands it may come,
to beware of letting in the spirit of envy, prejudice, and pride of heart,
which I clearly saw was that which,
with too much leaning to his natural abilities and learning, was his overthrow;
he not keeping to the Lord`'s Holy Spirit, the Life and strength of his faithful people,
and the key of true knowledge, the good remembrancer, and leader into all truth,
which the Lord sees fit in his wisdom to open and lead us into.
Without the help of this anointing and Holy Spirit,
we are apt to be cold and forgetful in our duties towards God,
and also in our love and duties one to another.
But, as the measure of this Spirit is faithfully kept to and improved,
we grow more and more fruitful in every good work and word,
to the glory of God and comfort of our own souls; and as the salt of the earth,
help to season those who are not seasoned.`" [.book-title]#J+++.+++ Richardson`'s Life,# p. 130.
<<note-H__xref_src,?LINKABLE-BACK>>

[#note-I.centered]
=== Note I.

William Dell, whose name has been already introduced in the earlier part of this Work,
as a writer gifted with no ordinary insight into
the spiritual character of the kingdom of Christ,
at the close of his preface to a treatise on "`The Doctrine of Baptisms,`"
has these following remarkable words.--"`But because I see this _present_
generation so rooted and built up in the doctrines of men,
I have the less hope that this truth +++[+++respecting the one saving baptism of Christ]
will prevail with them; and therefore I appeal to the next generation,
which will be further removed from these evils, and will be brought nearer to the word;
__but especially to that people whom God has and shall form by his Spirit for himself,--for
these only will be able to make just and righteous judgment in this matter,
seeing they have the Anointing to be their teacher, and the Lamb to be their light.__`"
And in the very conclusion of the same piece, after having fully wound up his subject,
and as it were laid down the pen, he resumes it,
to introduce this isolated sentence:--"`Isaiah 58:12.
'`And they that shall be of you,`'--'`that is,`' says he,
'`of the church that is born of the Spirit`'--'`shall build the old waste places,`'--made
such by the church that is born of the flesh--'`you shall raise up the foundations
of many generations,`'--by the clear revealing of Christ,
his kingdom, and all his things,
according to the ministration of the Spirit--`' and you shall be called,
__The repairer of the breach,
the restorer of paths to dwell in.__`' Here Christ writes upon the aforementioned
church his own new name.`"--To what shall we attribute the peculiar congeniality
and oneness of religious perception on this precise point,
thus manifested in the latter expressions of Dell,
and in those of Jaffray to which this Note is attached?--may it not be said,
that these men were taught in the same school, were "`baptized by one Spirit?`"
<<note-I__xref_src,?LINKABLE-BACK>>

[#note-J.centered]
=== Note J.

On the restoration of Episcopacy in Scotland in 1662,
many of the ejected Presbyterian ministers,
who were banished by order of the King`'s Council,
sought an asylum "`beyond the sea`" in Holland.
The Notes to the Diary,
show that several of the former associates of Jaffray were among this number;
and it is clear by this last paragraph of the "`Word of Exhortation,`"
how expressly his solicitude is directed towards that class.
<<note-J__xref_src,?LINKABLE-BACK>>

[#note-K.centered]
=== Note K.

The following quotation from a writer well approved among the Society, will, it is hoped,
throw some light upon this subject.
"`At the first appearance of this people,
several of them thought it their duty to go to the public places of worship,
to declare to the priests or people '`the burden of the word`' on their minds;
mostly waiting till their worship was ended,
and then delivering or attempting to deliver their sentiments in quietness,
and in as few words as possible,
for which they were often treated with great violence and outrage.
And to palliate such treatment, irreconcilable to the professed _purity_ of this period,
or to the good order of civil society,
great pains have been taken to describe their conduct
in terms of aggravation to a heinous offence,
and at this day may seem to deserve censure.
Let us take a retrospective view of the manners and principles of that age,
and I think we may find some cause of excuse for their seeming intrusion.

"`This people were not single, at that time,
in their sentiments concerning the gospel liberty of prophesying;
but the Independents as well as the Baptists adopted the opinion,
that the ordained ministers or pastors had not,
by any ordination of Christ or the order observed among the primitive Christians,
an _exclusive_ right of speaking in the church,
but that _all_ properly gifted might speak '`one by one.`' It had been,
during the time of the civil war, and still continued to be,
no unusual practice for laymen, soldiers, and others,
to speak or preach in the public places of worship and elsewhere, with the connivance,
if not with the approbation of the ruling powers.
Oliver Cromwell, in his correspondence with the ministers of Scotland, in the year 1650,
after the battle of Dunbar, vindicates the practice.
Oliver, having made an offer to the ministers who had taken
sanctuary in the Castle of Edinburgh or had fled,
of free privilege to return to their respective parishes; the Scotch ministers, in reply,
objected his opening the pulpit doors to all intruders,
by which means a flood of errors was broken in upon the nation; to which Oliver answered,
'`We look upon you as _helpers_ of,
not _lords over_ the faith of God`'s people:--where do you find in Scripture,
that preaching is included within your function?
Though an approbation from men has order in it, and may be well,
yet he that has not a better _than_ that has none at all.
I hope, He that ascended up on high, may give his gifts to whom he pleases;
and if those gifts be the seal of mission,
are not you envious though Eldad and Medad prophesy?
You know who has bid us covet earnestly the best gifts, but chiefly that we may prophesy;
which the Apostle explains to be, a speaking to instruction, edification,
and comfort--this, the instructed, edified,
and comforted can best tell the energy and effect
of.`'--'`Indeed you err through mistake of the Scriptures.
Approbation is an act of convenience in respect to order; not of necessity,
to give faculty to preach the gospel.
Your pretended fear lest error should step in,
is like the man that would keep all the wine out of the country,
lest men should be drunk.
It will be found an unjust and unwise jealousy,
to deny a man the liberty he has by nature,
upon a supposition he may abuse it.`' And in answer to the Governor`'s complaint,
that men of secular employments had usurped the office of the ministry,
to the scandal of the reformed churches, he queries,
'`Are you troubled that _Christ is preached?_
Does it scandalize the reformed churches, and Scotland in particular?
Is it against the Covenant?
away with the Covenant, if it be so.
I thought the Covenant and these men would have been willing,
that any should speak good of the name of Christ; if not,
it is no Covenant of God`'s approving, nor the kirk you mention, the spouse of Christ.`'

"`By this it appears evident, that a participation by the laity in ministerial offices,
was not only allowed, but patronized by some of the leading men of that time.
If then some members of this infant Society, under persuasion of duty,
at times made use of the liberty allowed to others, (and to several of _themselves,_
till they joined this Society,) to deliver a short exhortation,
most generally at the close of their worship, to the people assembled,
as a full opportunity to discharge their duty;--to give
them contumelious and violent abuse on that account,
was as contradictory to the professed principles of the Independents,
and those free notions of civil and religious liberty,
which they had been so active in disseminating, as +++[+++it was]
to religion and the civilization boasted of;&hellip;`"
Gough`'s [.book-title]#History of Friends,# vol. i. p. 86, etc.
<<note-K__xref_src,?LINKABLE-BACK>>

[#note-L.centered]
=== Note L.

It may be requisite to give an illustration of those numerous calumnies,
represented to have been vented forth by some in that day,
who stood in the character of spiritual watchmen, as Jaffray says,
for the purpose of _"`detaining the Truth of God in unrighteousness,`"_ and keeping
those who embraced it "`in disgust among the people`"--a practice which,
it is to be feared, has not altogether ceased to exist in less flagrant forms,
even among some who name the name of Christ;
however lamented and abhorred such conduct must be, by all his true followers.

In the 9th month, 1666, George Meldrum, accounted one of the chief ministers of Aberdeen,
preached _a whole sermon expressly against the people called Quakers,_
full of virulence and unjust slanders, such as, if believed,
would scarcely fail to excite the indignation of his hearers against them;
and to secure his discourse from refutation,
he actually enjoined such of his hearers as had taken it down in writing,
by no means to let the Quakers have a copy of it,--as
if conscious of the falseness of his statements.
Not long after,
church proceedings being instituted against Alexander Jaffray in order to excommunication,
some of his relations, not Friends, intimated to the Bishop,
that it was irregular to excommunicate an offender,
before attempts had been made to reclaim him.
Upon this, the Bishop himself offered to confer with Jaffray,
in the presence of Meldrum and his colleague Menzies.
Jaffray said, he could not yield to this, unless he were permitted to have witnesses;
as these men had repeatedly misrepresented in public,
what had been said to them in private; of which he could bring proof.
At length, _Friends being objected to,_ Jaffray`'s brother and son, not Friends,
were allowed to be present; when,
"`the Lord remarkably assisted him in declaring the Truth,`"
and defending himself and it against their unjust allegations;
so that the Bishop charged Meldrum,
to give the Friends a copy of the sermon preached against them.
Instead of this, however, he sent Alexander Jaffray another paper,
which he called "`The state of the controversy between the Protestants and the
Quakers,`" and half a sheet containing thirty Queries for them to answer.
These papers, together with the sermon,
which with much difficulty was at length procured from one of his hearers,
Alexander Jaffray and George Keith readily replied to;
and "`it had a very good service`" among their neighbours.
<<note-L__xref_src,?LINKABLE-BACK>>

[#note-M.centered]
=== Note M.

The Queries, which were offered to the public preachers of Aberdeen by Alexander Skene,
a magistrate of that city,
are preceded by some very important observations of Robert Barclay,
on the subject of joining with other Christian professors in worship,
by external signs of concurrence.--"`If it were`" says he,
"`their known and avowed doctrine, not to pray without the motion of the Spirit,
and that, seriously holding thereunto,
_they did not bind themselves to pray at certain prescribed times precisely,_
(at which times they determine to pray, though _without_ the Spirit,)--then, indeed,
we might be accused of uncharitableness and pride, _if we never joined with them;_
and if they so taught and practised, I doubt not but it should be lawful for us so to do,
unless there should appear some manifest and evident hypocrisy or delusion.
But seeing they profess, that they pray without the Spirit,
and seeing God has persuaded us, that _such_ prayers are abominable,
how can we with a safe conscience join with an abomination?
That God sometimes condescends to them, we do not deny,--(albeit,
now when the spiritual worship is openly proclaimed, and all are invited unto it,
__the case is otherwise,
than in those old times of apostasy and darkness,__)--and
therefore albeit any should begin to pray in our presence,
not expecting the motion of the Spirit, yet, _if it manifestly appear,
that God in condescension did concur with such a one, then, according to God`'s will,
we should not refuse to join also._
But, _this is rare;_ lest, from there, they should be _confirmed_ in their false principle.
And albeit _this seem hard in our profession,_
nevertheless it is so confirmed by the authority both of Scripture and right reason,
that many, convinced thereof,
_have embraced this part before other truths_ which were easier, and,
as they seemed to some, clearer.`" [.book-title]#Apology,# Prop. xi. sect. 24.
The case of Alexander Skene`'s convincement is then given;
and his reasons for separation from those,
with whom he had been associated in religious fellowship,
appear in the following Queries.

[.embedded-content-document]
--

[.blurb]
==== Queries On Worship By Alexander Skene.

1st.--Should _any_ act of God`'s worship be gone about, without the motions, leadings,
and actings of the Holy Spirit?
2nd.--If the motions of the Spirit _be necessary_ to every particular duty,
whether should He be waited upon,
that all our acts and words may be _according as he gives utterance and assistance?_
3rd.--Whether everyone that bears the name of a Christian,
or professes to be a Protestant, has _such an uninterrupted measure thereof,_ that he _may,
without waiting,_ go immediately about the duty?
4th.--If there be _an indisposition and unfitness at some times_ for such exercises,
at least as to the spiritual and lively performance of them,
ought they to be performed _in that case_ and _at that time?_
5th.--If any +++[+++such]
duty be gone about, under pretence that it is in obedience to the external command,
without the spiritual life and motion necessary, whether such a duty, thus performed,
_can in faith be expected to be accepted of God,_
and not rather reckoned as a bringing of '`strange fire`' before the Lord?
seeing it is performed, at best, by the strength of natural and acquired parts,
and not by the strength and assistance of the Holy Spirit,
which was typified by the fire, that came down from heaven,
which alone behooved to consume the sacrifice, and no other.
6th.--Whether +++[+++such]
duties, gone about in the mere strength of natural and acquired parts,
either in public or in private, be not _as really,_ upon the gross matter,
_an image of man`'s invention, as the Popish worship,_
though not so gross in the outward appearance?
And therefore,
whether it be not as real superstition to _countenance_ any worship of that nature,
as it is to countenance Popish worship, though there be a difference _in the degree?_
7th.--Whether it be a ground of offence or just scandal,
to countenance the worship of those, whose professed principle it is,
_neither to speak for edification nor to pray,
but as the Holy Spirit shall be pleased to assist them,_ in some measure, less or more;
without which, they rather choose to be _silent,_ than to speak without this influence?

--

The tone of utter aversion and prejudice, in regard to true spiritual worship,
and the necessary preparation of soul for this solemn exercise,
which was evidently held out, at this period,
by the professed preachers of the gospel in Aberdeen,
headed by their Bishop,--and which indeed gave ample occasion for
the promulgation of the above _Queries,_--is the more remarkable,
when contrasted with that beautifully clear stream
of evangelical sentiment on this very point,
given forth only about twenty years afterward, by _Henry Scougal,_
a "`professor of divinity`" in the same place, and a son of the same Bishop.
In his valuable treatise, entitled,
"`The Life of God in the Soul of Man,`" after reference to the promise
of the Holy Spirit to those who sue for this inestimable gift,
he thus proceeds.--"`In prayer, we make the nearest approaches to God,
and lie open to the influences of heaven: then it is,
that the Sun of righteousness does visit us with his directest rays,
and dissipates our darkness, and imprints his image on our souls.`"
"`As there is one sort of prayer, wherein we make use of the voice,--and another wherein,
though we utter no sound, yet we conceive the expressions and form the words, as it were,
in our minds; so there is a third and more sublime kind of prayer,
wherein the soul takes a higher flight,
and having collected all its forces by long and serious meditation, it darts itself,
(if I may so speak) towards God in sighs and groans, _and thoughts too big for expression._
As when, after a deep contemplation of the Divine perfections,
appearing in all his works of wonder,
it addresses itself unto him in the profoundest adoration
of his majesty and glory:--or when,
after sad reflections on its vileness and miscarriages,
it prostrates itself before him with the greatest confusion and sorrow,
not daring to lift up its eyes, _or utter one word in his presence:_--or when,
having well considered the beauty of holiness,
and the unspeakable felicity of those that are truly good, _it pants after God,_
and sends up such vigorous and ardent desires, _as no words can sufficiently express;_
continuing and repeating each of these acts,
as long as it finds itself upheld by the force and impulse of the previous meditation.

"`This mental prayer is, _of all other,_ the most effectual to purify the soul,
and dispose it unto a holy and religious temper,
and may be termed _the great secret of devotion,_
and one of _the most powerful instruments of the divine life:_ and, it may be,
that the Apostle has a peculiar respect unto it, when he says,
that _the Spirit helps our infirmities,
making intercession for us with groanings which cannot be uttered,_ or,
as the original may bear, __that cannot be worded.__`" p. 98, 99.
<<note-M__xref_src,?LINKABLE-BACK>>

[#note-N.centered]
=== Note N.

Of Meldrum, the historian of the church of Scotland, Cruickshank says,
"`This great man was _remarkably useful,_ with his colleague, Mr. Menzies, in Aberdeen,
against the Quakers and Jesuits,`" vol. i. p. 150.
The same author, nine pages further on,
has another sentence relating to the Friends,
which does not seem capable of bearing a very favourable
construction.--"`On the 2nd of June,
1663, they made _a very good act against the Quakers;_
but the bishops gave the council so much to do against the Presbyterian Nonconformists,
that _these people were suffered to rest in quiet;_
for they mightily increased during this reign.`"

The next paragraph of the Memoirs will show, that, _at least_ the Bishop of Aberdeen,
was not altogether an idle spectator of the success of this _new heresy,_
and that by no means was he lacking in the attempt to give the
King`'s Council some substantial work in this line of persecution,
though their hands were already so full.
<<note-N__xref_src,?LINKABLE-BACK>>

[#note-O.centered]
=== Note O.

Among the early opponents of the principles of religious
order laid down in this work of Barclay`'s,
was William Rogers, of Bristol, and his followers.
Much reproach and invective was dealt out by these separatists against him; but,
on a conference being held with this individual, in 1677, at Robert Barclay`'s request,
William Rogers could not substantiate his arguments against the system,
and acknowledged he had mistaken the import of these principles.
Yet afterward, this man and his adherents persisted in controverting the very same views,
spreading papers abroad, unknown to Robert Barclay, and personally reflecting on him;
this induced the latter, to write a Vindication of his Treatise on Discipline,
by way of explanation; which, certainly, exhibits the author in an amiable point of view.
See [.book-title]#Gough`'s History,# vol. iii. p. 16; also [.book-title]#Barclay`'s Life.#

An original manuscript letter on this subject,
addressed by George Fox to Robert Barclay near two years after,
has come into the possession of the Author of these pages,
which may be worthy the perusal of Friends in the present day.
It is as follows.

[.embedded-content-document.letter]
--

[.salutation]
Dear Robert,

With my dear love to you and your father, and to George Keith,
with all the rest of Friends in the holy Seed of Life, that is over all, and changes not,
but reigns, _the First and the Last;_ in whom you have life and salvation!
And so, my desire is, that you all may be valiant for the Truth upon the earth,
and spread it abroad; and that those who are brought into the Truth,
may keep in the holy order of it, in the glorious gospel of Christ, the heavenly Man;
so that the Lord may be glorified in all your assemblies,
and Christ may have his joy in you all,
and '`your joy may be full`' _in Him_ who _draws up to God._
And so, the Lord God Almighty, in his glorious power,
preserve you all,--__and over all that which makes to suffer.__

And, dear R. B., I desire you to send _the little epistle,_ with the substance of this,
to the prisoners and to Friends.
And this unruly spirit of J. S. and W. R. and J. W. I saw,
_as I was at prayer to the Lord for Friends in my
chamber,_--that it was _for the trial of Friends,_
as the _other_ that had risen before; and when it has done its work,
_it will pass the way after those that have gone before it.
And I saw Friends, sitting low, and wet, and watered with the dew of heaven._
So, it is for the trial of Friends,--of _their standing to God,_
and of _their keeping their habitation,_ and of _holding the Head, with the light, grace,
spirit and truth, power and faith, that comes from Christ._
And so, _all will be good in the end to all Gods people._

I am sorry, that William Rogers should do so basely with you, and that,
after he was satisfied,
and a paper was signed,--for him to send your name again
in his book up and down the nation it was five or six months,
before I could get a copy of it; and yet it so spread.
So, dear R. B., I do send you this, +++[+++some extracts;]
but if you were here at Swarthmore, you might see the book, which might be well,
and I should be glad to see you here.
So, in haste, with my love,

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
29th of 1st month, 1679.

--

The accompanying _little epistle_ must not be withheld, though, in this place, out of date:
it is as follows.

[.embedded-content-document.epistle]
--

[.letter-heading]
George Fox To The Prisoners.

[.signed-section-context-open]
Swarthmore, 1st month, 1678-9.

[.salutation]
My dear Friends,

Who are sufferers for the Lord Jesus`' sake, and for the testimony of his truth!
The Lord God Almighty uphold you with his power,
and support you in all your trials and sufferings,
and give you patience and content in his will;
that you may stand valiant for Christ and his truth upon the earth, over the persecuting,
destroying spirit, which makes to suffer,--+++[+++even]
_in Christ,_ who bruises his head,--__in whom__ you have both election and salvation.
The Lord has done much for the sake of his elect,
as may be seen from the foundation of the world,
and as maybe seen throughout the Scriptures of truth; _and those who touch them,
touch the apple of God`'s eye,_ they are so tender to him.
And therefore, it is good for all God`'s suffering children to trust in the Lord,
and to wait upon him; for these shall be as Mount Zion,
that cannot be removed from Christ their Rock and salvation,
who is the foundation of all God`'s elect, the prophets and apostles,
and God`'s people now, and to the end: glory to the Lord and the Lamb over all!

And _do not think the time long,_ for all time is in the Father`'s hand, his power;
and therefore _keep the word of patience,_ and exercise that gift,
and the Lord strengthen you in your sufferings, in his holy spirit of faith, amen!

[.signed-section-signature]
G+++.+++ F.
<<note-O__xref_src,?LINKABLE-BACK>>

--

[#note-P.centered]
=== Note P.

[.embedded-content-document.address]
--

[.blurb]
==== A Seasonable Warning and serious exhortation to, and expostulation with the Inhabitants of Aberdeen, concerning this present dispensation and day of God`'s living visitation towards them.

Great, unutterably great, O you Inhabitants! is the love of God,
which flows in my heart towards you;
and in bowels of unspeakable compassion am I opened,--am I enlarged unto you,
in the sight and sense of your conditions,
which the Lord has discovered and revealed unto me.
O that your eyes were opened,
that you might see and behold _this day of the Lord!_ and that your ears were unstopped,
to hear his voice,
that cries aloud and calls one and all of you to Repentance! and that your hearts were
softened and inclined to discern and perceive this blessed hour of his present visitation,
which is come unto you!
He has lifted up a standard in the midst of you, and among your brethren,
he has called already a remnant, and enrolled them under his banner,
and he is calling all to come; he has not left one without a witness:
blessed are they that receive him and hear him, in this day of his appearance!
He has sent forth, and is daily sending forth his servants and messengers,
to invite you to come and partake with him of the
supper,--of the feast which he has prepared.
And among many others, whom at sundry times he has caused to sound forth his testimony,
I also have, in the name, and power, and authority of God,
proclaimed his everlasting gospel among you, and preached,
and held forth the glad tidings of this glorious dispensation,--__which is Christ,
manifesting and revealing himself in and by his Light
and Spirit in the hearts of all men,
to lead them out of all unrighteousness and filthiness both of flesh and spirit,
unto all righteousness, truth, holiness, peace, and joy in the Holy Spirit.__

But, because many of you have despised this day,
and as you have made merry over _God`'s witness in your hearts,_
not liking _there_ to entertain him in his meek, lowly, yet lovely appearance;
so have you despised, mocked,
and rejected that which testifies to this witness _without_ you.
Therefore was I commanded of the Lord God,
to pass through your streets covered with sackcloth and ashes, calling you to repentance;
that you might yet more be awakened and alarmed,
to take notice of _the Lord`'s voice_ unto you,
and not to despise these '`things which belong to your peace,`' while your day lasts,
lest hereafter they be '`hid from your eyes.`' And
the command of the Lord concerning this thing,
came unto me that very morning as I awoke, and the burden thereof was very great, yes,
seemed almost insupportable unto me;--for such a thing, until that very moment,
had never before entered me, not in the most remote consideration.
And some whom I called, to declare to them this thing, can bear witness,
how great was the agony of my spirit,--how I besought the Lord with tears,
that this cup might pass away from me!--yes,
how the pillars of my tabernacle were shaken, and how exceedingly my bones trembled,
until I freely gave up unto the Lord`'s will.

And this was the end and tendency of my testimony,
_to call you to repentance_ by this signal and singular step; which I,
as to my own will and inclination, was as unwilling to be found in,
as the worst and most wicked of you can be averse from receiving or laying it to heart.
Let all and every one of you,
in whom there is yet alive the least regard to God or his fear,
consider and weigh this matter in the presence of God,
and by the Spirit of Jesus Christ in your hearts,
_which makes all things manifest;_--search and examine every one his own soul,
how far this warning and voice of the Lord is applicable unto them;
and how great need they have to be truly humbled in their spirits,
returning to the Lord in their inward parts with such true and unfeigned repentance,
as answers to the outward clothing of sackcloth and being covered with ashes.
And, in the fear and name of the Lord, I charge all upon this occasion,
to beware of a slight, frothy, jeering, mocking spirit.
For though such may be permitted to insult for a season;
yet God will turn their laughter into howling, and will laugh when their calamity comes:
such are seen to be in one spirit with those, who spat in the face of the Lord Jesus,
and buffeting him, bid him prophesy, who smote him.

Therefore, consider, O you Inhabitants! and be serious, standing in fear: +++[+++for]
where are you, who are called Christians?
among whom it is become a wonder, a stone of stumbling, or matter of mockery,
or a ground of reproach,
for one in the name of the Lord to invite you to repentance in sackcloth and ashes!
Would not the heathen condemn you in this thing,
and will not Nineveh stand up in judgment against you?
How is it, that you who are called Christians,
can willingly give room to every idle mountebank,
and can allow your minds to be drawn out to behold these sinful divertisements,
which indeed divert the mind from the serious sense of God`'s fear?
The people can be gathered there, and neither the magistrates complain of tumult,
nor yet preachers nor professors cry out against it, as delusion or madness.
O my Friends! consider; can there be any more strongly deluded,
than for people daily to acknowledge and confess in words, +++[+++that]
they are sinners and sinning; and to startle at that, which did +++[+++in]
so lively +++[+++a manner]
represent unto them, what they own to be their condition?
Were it in good earnest, or were it from a true sense of your sins,
that you so frequently seem to acknowledge them,
you would not despise nor overlook that which calls you to repentance for it.
How is it, that you can so confidently array yourselves in all
manner of gaudy and superfluous apparel,
and exceed in lustful powderings and perfumes;
and yet are ashamed and amazed at sackcloth and ashes, which,
according to your own acknowledgment, is so suitable to your states?
It not this __to glory in your shame, and to be ashamed of that which ought to be,
and would be your greatest glory__--+++[+++even]
true and unfeigned repentance?

I shall add that which, upon this occasion,
I declared unto you,--I was for a sign from the Lord unto you;
and desire you may not be among those that '`wonder and perish,`' but
rather '`repent and be saved.`'--And this is my testimony unto you,
whether you will '`hear or forbear,`'--I have peace with my God in what I have done,
and am satisfied that his requirings I have answered in this thing.
I have not sought _yours,_ but _you;_ I have not coveted your gold or silver,
or anything else; nor do I retain or entertain the least hatred, grudge,
or evil will towards any within or without your gates;
but continue in pure and unfeigned love towards all and every one of you,
even those who do most despise or reject me and my testimony;--being ready to '`bless
those that curse,`' and to '`do good to those that despitefully use`' me;
and to be spent in the will of the Lord _for your sakes,_ that your souls may be saved,
and God over all may be glorified! for which I travail
and cry before the throne of grace,
as becomes a servant of the Lord Jesus Christ.

[.signed-section-signature]
Robert Barclay.

[.signed-section-context-close]
This came before me to signify unto you by writing, at Ury, the 12th of the 1st month,
1672.
<<note-P__xref_src,?LINKABLE-BACK>>

--

[#note-Q.centered]
=== Note Q.

In this place, it will be proper to mention,
that the facts thus substantiated by the united testimony of many witnesses,
themselves the objects of this course of violent treatment,
receive all that confirmation from the history of the place, which could,
in the nature of the case,
be expected to be handed down respecting a people at once so insignificant and despised,
so misrepresented and abused.
The intelligent author of the [.book-title]#Annals of Aberdeen,# has furnished
the public with such corroborative evidence as he possessed,
of the unjust and unworthy line of conduct pursued
in ancient time by the predecessors of some,
who are now, it is believed,
honourable for their dedication to better principles and feelings.
He gives the following candid, and as far as it goes,
accurate outline of the commencement of this persecution.

"`In the year 1663,
the religion of the Quakers began to gain ground among some of the inhabitants.
It had, by this time, made considerable progress in England,
under the famous George Fox and James Nayler;
and its enthusiasm having spread to this place,
occasioned no little disturbance both to the magistrates and to the ecclesiastics.
Mr. George Keith, William Nepper, shipmaster, and William Stewart, three citizens,
having broken off all connection with the established church,
and openly avowed the principles of the Quakers,
the magistrates considered that this religious innovation deserved their serious attention.
They convened these people before them;
condemned them to be immediately conducted out of the town by sergeants,
and _prohibited the inhabitants from harbouring them in their houses,
under heavy penalties._
These severities they bore with their usual patience,
persisting in holding occasional meetings in the town,
and increasing the number of their proselytes.
The magistrates, alarmed at their success in gaining converts, and, _perhaps,
instigated by the clergy,_ without further inquiry,
issued their orders to apprehend all male Quakers at their next convention,
to imprison them in the jail, and to shut up their meetinghouse.
Such, however, was their enthusiasm,
that they were not to be intimidated by these rigorous measures.
They persevered in the profession of their religious doctrines,
and were _subjected to every indignity of imprisonment and disfranchisement._
Having appropriated a piece of ground, on the east side of the Gallowgate,
to the interment of their dead, they buried the bodies in it,
without any religious ceremony;
but this having attracted the attention of the magistrates,
they ordered these to be raised,
and the walls of their burial-place to be demolished.--To
all these oppressions they submitted without the least murmur.`"
vol. i. p. 254. In a note,
attached to the words "`perhaps instigated by the clergy,`"
the same author appends the following circumstance.
"`Note--Thomas Milne, shoemaker, having become a convert to the Quakers,
was called before the Church Session; but,
having persevered in maintaining his principles,
was remitted to the three ministers of the town, to use their influence with him;
which seems to have had very little effect,
and the matter was dropped.--Records of the Church Session, 25th Nov.
1661.`" "`In the year 1674, Thomas Dockery and William Gelly,
two of these inoffensive people, were imprisoned, under a warrant from the magistrates,
upon a charge which was brought against them, _for deriding the holiness of the kirk,
by calling it a steeple-house, and for attending their conventicle._
These men remained in jail for some time;
but a representation being made to the Lords of the Privy Council, they were ordered,
by a letter from the Lord Chancellor, to be liberated.
After this period, the Quakers appear to have been allowed to practise their devotions,
and religious duties agreeably to the principles which they professed,
and to bury their dead according to their own custom, without molestation.`"

This concluding observation,
is certainly not borne out by the vouchers which that people hold.
<<note-Q__xref_src,?LINKABLE-BACK>>

[#note-R.centered]
=== Note R.

Of John Swintoune, we read nothing more in the [.book-title]#Memoirs of the Friends in Scotland;#
the few additional particulars which have come to the hand of the Author,
he subjoins in the present Note.

At an early page of this Appendix, we have had before us in the career of George Keith,
a sorrowful illustration of the continual necessity there is,
for every one that "`__thinks__ he stands,`" to "`__take heed__ lest he fall.`"
We have seen, that, while he walked in the light of the Lord,
and moved in His strength and wisdom, maintaining the good fight of faith,
in all humility, patience, and watching unto prayer,
George Keith was kept an eminent and serviceable instrument.
But so soon as ever he forsook the Lord, trusted in his own heart,
and leaned to his own understanding, he was left to his own devices;
notwithstanding his great endowments, he became weak and even weaker than other men,
inconsistent with himself, confused in his views,
and unsanctified in his spirit.--With regard to the individual now under notice,
it may be remembered,
that few men of his day and country were blessed with greater advantages,
or had better worldly prospects than John Swintoune.
His influence had been great with those, under whose appointment he at one time served,
when it might be almost said, _he led the counsels of Scotland;_ while, on the other hand,
his very enemies and those who sought his life,
were struck down with sympathy and admiration at
the way in which he bowed under his reverses.
Favoured with that high and extensive view, which the Society of Friends have taken,
of the spirituality of the gospel dispensation, and under a deep sense of its value,
he had been the means of engrafting a stem of Truth in his native land;
he had helped forward its budding, in the hearts of such,
as a Provost Jaffray and a Colonel Barclay,--men of a noble stamp,
of an excellent spirit,
whose sons and successors were the valiants of the Society in that country in after time.
Expounding unto these, like Aquila,
"`the way of God more perfectly,`" he might be called
an antecessor and leader of this people in Scotland.
He had likewise tasted his share of those various indignities,
which abundantly befell all,
who counted it their joy and crown to follow the footsteps of the
grace of Jesus.--Yet after all this,--he stood not "`steadfast,
immovable,`" he did not continue in this grace of God, but fell from it,--no,
he frustrated it,--no, he turned it into an occasion for actual immorality, for adultery.
Suffice it to say--(and it cannot be properly withheld)--his case, like that of David,
which is recorded for our warning and instruction,
gave "`great occasion for the enemies of the Lord to blaspheme,`"
made the hearts of the righteous sad,
and though followed by swift conviction and unfeigned penitence,
was most probably the means of crippling him in his
spiritual standing for the remainder of his days.
He was of course excluded from the fellowship of his brethren in religious profession,
and they testified against his conduct accordingly; judging it,
as they express themselves,
to be a duty to recommend that a _visible distance
and separation be kept as to near converse,_
until repentance be further manifested.
Yet, when he had given full evidence to their satisfaction,
not only of the sincerity of his sorrow,
but of his restoration and settlement as a sound member of Christ,
there is little doubt he again partook of the unity of his friends.

A letter of his now lies before the Author, addressed to Margaret Fox,
the wife of George Fox, but previously the wife of Judge Fell,
who possessed great influence throughout the Society,
and maintained a large correspondence with its members.
It is dated the 8th of the 10th month, 1673,
perhaps not much above a year subsequent to his fall.
He was then in London, having paid his correspondent a visit at Swarthmore Hall,
in Lancashire, on his way from Scotland.
He speaks with the freedom of friendship upon the
posture of political affairs at that juncture,
as they might be likely to affect the interest of Friends,
and of the proceedings that were then before Parliament in relation to liberty of conscience;
having, that day, been in attendance "`at the Hall.`"
He concludes his sheet with the endearing salutation,
so usual among brethren and sisters in the Truth, and so worthy of them,--that of love.
But the best proof of the peaceful condition of mind,
he was favoured through redeeming mercy to arrive at,
is furnished in two precious documents,
one of them written by himself during his last illness; and the other by his widow,
after his decease.
They are, with some slight verbal amendment, as follow.

[.embedded-content-document.testimony]
--

[.blurb]
==== A Testimony Left by John Swintoune of Swintoune.

I, John Swintoune of Swintoune, being surrounded with weakness of body,
so that there is more probability than to the contrary, that I may lay it down;
therefore, in the seriousness and sense that becomes a dying man, I thus write.

That my faith and belief firmly is and has been,
that the contemned people called Quakers are _a blessed people,_ and their _testimony,_
as to every part and parcel of it, is _blessed,_ and may not be forgone, one hoof of it;
but is to run and be _glorious,_ even _to the ends of the earth,_
and is for _the healing of the nations,_
as it shall prevail--which it shall not fail to do,
(the mouth of the Lord of hosts has spoken it,) to the shame
and confusion and disappointment of all those,
that look upon them and it with an evil eye.

And it is my advice, and desire, and request to all my relations and acquaintance, that,
in the fear and dread of God, they leave off having any hand in,
nor be in the least consenting to _any hardship_ put upon _that blessed people;_
but rather travail to cleave to them _in their hearts,_
whose heart is not raised to stand up _openly_ for them; for,
as the Lord God _has pleaded their cause_ and stood by them,
so he _will yet more abundantly,_ as ever he did Israel in the land of Zoar,
and _no weapon formed against them shall prosper,_
and the great ones of the earth he will reprove for their sakes.

Writ and subscribed with my own hand, at Borthwick, this 15th of the 2nd month, 1679.

[.signed-section-signature]
(Sic subscribitur) J. S.

--

[.embedded-content-document.testimony]
--

[.blurb]
==== His Wife`'s Testimony Concerning Him and the Truth.

Let _substance_ +++[+++Christ the living, eternal substance,]
be the aim of every one: oh, keep to it, every one that knows it;
for a needful time may come!
Oh, travail for it every one that knows it not! let your cry be,
that you may come into acquaintance with it, and be joined unto it,
and _be one with it forever!_ for nothing below this, can support in the needful time.

In this living faith and principle of life,
my dearly beloved husband _laid down his outward man, in peace,_
and had in measure the possession of it before he went hence.
Both before he fell into his weakness of body, and many a time in his deep exercises,
he gave many a true and living testimony to this ever blessed Truth,
which is _Life and Light;_--and it was his life, and is the life of all that believe in it,
and walk in obedience to it.
And, to the truth hereof, I can set my seal,--and was one with him in spirit;
so that our nearness was not only in the outward, which was to be separated,
but _in that which can never be separated;_--which
is the life of _all the faithful_ in this day,
and in all ages.
So, it is _with the Father, and with the Son,_
and _with the spirits of just men made perfect,_ that our _union_ and _fellowship_ is:
_here_ is our strength, at this day,--__in Christ, the substance and fulness,__
and _fulfiller of all in us._
Here _self is of no reputation, nor outwards trusted in;_ for they must all come to an end,
how glorious soever they may be in their day or age, whether persons or _professions._
No, I can say, of a truth,
_the profession of Truth will not serve in the needful time,--it
must be the possession of substance,--that to be our inheritance,_
our _strength,_ our _life forever!_
And when we find anything separate from this, then--trouble and anguish of spirit;
as one said, in his day, '`You did hide your face, and I was troubled`'; Ps. 30:7.
but, Through Judgment, Redemption Is Witnessed,
and through waiting in the light, life springs in the inward parts,
and strength is renewed.
_So, here is the Rock of ages, a Foundation of many generations,_--oh, living praise! oh,
everlasting renown and eternal thanksgiving be sounded
forth unto _the Author and Finisher of our faith,_
which is, Christ Jesus in us, _the hope of glory,_--blessed forever, and forevermore!

[.signed-section-signature]
Frances Swintoune.

[.signed-section-context-close]
Borthwick, 22nd of 6th month 1679.
<<note-R__xref_src,?LINKABLE-BACK>>

--

[#note-S.centered]
=== Note S.

The small estate of Kingswells, lying about five miles west of Aberdeen,
came into the possession of the Jaffrays in the year 1587, being purchased,
as the family records state, by Alexander Jaffray, bailie or magistrate of Aberdeen,
who married Christian Burnet, _daughter of the then proprietor of Leys,_ and died 1645.
His son, Alexander, married Magdalen Erskine, daughter of Erskine of _Pittodrie,_
and had a son Alexander, _the author of the present Diary,_ born 1614.
He married Jane Dune 1632, by whom he had a son Alexander, who died 1672.
His second wife, Sarah Cant, whom he married in 1647, died a few months after him,
in 1673.
Their eldest son, Andrew, born 1650, married Christian, daughter of Alexander Skene,
of the family of Skene of Skene, and had Lilias, Margaret, Alexander, Christian, Andrew,
Sarah, John, Patience, James, and Anna.
He died 1726.
His son Alexander, grandson of the Diarist, in 1700, married _Christian Barclay,_
daughter of "`the Apologist,`" and had ten children.

The language of Richard Claridge, a learned and eminent member of the Society of Friends,
is well worthy attention in this place:
it was written on occasion of his acknowledging the
receipt of the genealogy of the Claridge family,
which had been taken out of the Herald`'s Office by some of the relations,
and by one of them kindly forwarded to him--"`There is a _pedigree,_ namely, _the Christian,_
which is noble indeed, and is worthy of our most diligent search and earnest inquiry.
To be the children of God,
and co-heirs with Christ,--__to have our robes washed in the blood of the Lamb,
and to be made kings and priests unto God;__--and to know this _ourselves,_
by the testimony of the Holy Spirit in our hearts, whereby we can cry, Abba,
Father!--this, this, my dear kinsman, is far above all in this sublunary world!
O let this piece of _divine and spiritual heraldry,_ be our main care and concern;
omitting no opportunity, under those blessed means that are so plentifully afforded us,
of __making our calling and election sure.__`" [.book-title]#Claridge`'s Life and Posthumous Works,# p. 315.
<<note-S__xref_src,?LINKABLE-BACK>>

[#note-T.centered]
=== Note T.

[.embedded-content-document]
--

[.blurb]
==== Treatment Received By Friends In Their Worship, and Their Support Under It.

But when people meet together, and their worship consists not in such outward acts,
and _they depend not upon anyone`'s speaking,_ but merely sit down to wait upon God,
and to be gathered out of all visibles, and to feel the Lord in spirit;
none of these things can hinder them: of which we may say of a truth,
we are sensible witnesses.
For when the magistrates, stirred up by the malice and envy of our opposers,
have used all means possible--and yet in vain--to deter us from meeting together,
and that, openly and publicly, in our own hired houses for that purpose; both death,
banishments, imprisonments, finings, beatings, whippings,
and other such devilish inventions have proved ineffectual
to terrify us from our holy assemblies.
And we having thus oftentimes purchased our liberty to meet by deep sufferings,
our opposers have then taken another way;
by turning in upon us the worst and wickedest people, yes, the very offscourings of men;
who, by all manner of inhuman, beastly, and brutish behaviour, have sought to provoke us,
weary us, and molest us--but in vain.
It would be almost incredible to declare, and indeed a shame,
that among men pretending to be Christians it should be mentioned,
what things of this kind men`'s eyes have seen, and I myself with others have shared of,
in suffering!
_There,_ they have often beaten us, and cast water and dirt upon us;
_there_ they have danced, leaped, sung, and spoken all manner of profane and ungodly words;
offered violence and shameful behaviour to grave women and virgins; jeered, mocked,
and scoffed, asking us _If the Spirit was not yet come,_--and much more,
which were tedious here to relate:--and _all this,_
while we have been seriously and silently sitting together, and waiting upon the Lord.

So that, by these things, our inward and spiritual fellowship with God,
and one with another in the pure life of righteousness, _has not been hindered._
But, on the contrary,
the Lord knowing our sufferings and reproaches for his testimony`'s sake,
has caused his power and glory _more to abound among us,_
and has mightily refreshed us by the sense of his love,
which has filled our souls;--and so much the rather,
as we found ourselves gathered _into the name of the Lord,_
which is _the strong tower of the righteous,_
whereby we felt ourselves sheltered from receiving
any inward hurt through their malice,--and also,
that he had delivered us from that vain name and profession of Christianity,
under which our opposers were not ashamed to bring forth these bitter and cursed fruits.--Yes,
sometimes, in the midst of this tumult and opposition,
God would powerfully move some or other of us by his Spirit, both to testify of that joy,
which, notwithstanding their malice, we enjoyed, and +++[+++also]
powerfully to declare, in the evidence and demonstration of the +++[+++same]
Spirit, against their folly and wickedness; so +++[+++that]
the power of Truth has brought them to some measure of quietness and stillness,
and stopped the impetuous streams of their fury and madness.
That, as ever of old Moses by his rod divided the waves of the Red sea,
that the Israelites might pass; so, God has thus by his Spirit made a way for us,
in the midst of this raging wickedness, peaceably to enjoy and possess Him,
and accomplish our worship to him:--so that sometimes, upon such occasions,
several of our opposers and interrupters have hereby been convinced of the Truth,
and gathered from being persecutors to be sufferers with us.--[.book-title]#Barclay`'s
Apology,# Prop. xi. Sect. 13.
<<note-T__xref_src,?LINKABLE-BACK>>

--

[#note-U.centered]
=== Note U.

In the daily interactions of private life, there is no doubt,
Robert Barclay had abundant occasion given him,
(though in a less notorious and permanent manner than the public arena
of controversy,)--to evince his love to the cause he had espoused,--as
well as his deep and clear knowledge of the truth of it,
by the exercise of those unusual qualifications be
had received for declaring and defending it.
Many of his relations are stated to have been Roman Catholics; others of them,
we may conclude,
belonged to the Presbyterian and Episcopal bodies.--The Writer of these sheets,
when at Ury, discovered in the library _a thick quarto volume in manuscript,_
of between 300 and 400 closely written pages, bound in leather, and entitled,
"`Questions proposed by Mr. Charles Gordon, concerning the Quakers`' principles,
to Robert Barclay: with his answers thereunto,
and Mr. Charles his considerations of the said answers:
copied out of Mr. Charles his papers by his brother, Mr. Robert Gordon; 1678.`"
The date of this correspondence is concluded to have been at least as early as 1670,
when the first of Barclay`'s publications came out.
These Gordons were his uncles; and the latter, Robert, appears to have lived at Cluny,
a few miles distant from Aberdeen.
There is, in this _mass of deeply polemical theology,_
enough to show the intricate labyrinth of words and of notions,
in which most religious professors of the age were involved;
and in these metaphysical niceties, Charles Gordon proves himself to have been, indeed,
_thoroughly furnished._
Robert Gordon, too, must have been a disputant _of no mean account,_
at least in the estimation of the college students of Aberdeen;
or they would not have _brought him in,_ when they raised a story,
about his appointing a dispute with his nephew, which, they said,
the latter _out of fear_ had deserted. [.book-title]#R. B.`'s Works,# fol. p. 670.
Thus closely pressed upon and beset on all sides, the early Friends generally,
and this Friend in particular, must have found it hard, and even almost incessant work,
to have replied to all the objections raised against their sentiments and practice.
In allusion to this part of Barclay`'s career, the writer of his life,
in the [.book-title]#Biographia Britannica,# observes, "`Though it might be conceived,
that so many undertakings, within so narrow a compass of time,
must have wholly taken him up, and left him not so much as _a moment_ to spare; yet,
it is certain, that at this very time, he was meditating his great work, +++[+++the [.book-title]#Apology.#]`"

But it cannot be considered, that these undertakings are likely to have, by any means,
comprehended _all_ that the energies of Robert Barclay`'s mind were employed upon.
From some memoranda in his own hand-writing, it would seem far from improbable,
that he had some design and _plan_ of a _History of the Church._
<<note-U__xref_src,?LINKABLE-BACK>>

[#note-V.centered]
=== Note V.

At this page, there is allusion to a letter, addressed by Friends to George Melvill,
who had been appointed by the Commissioners of the Scottish Privy Council,
to distrain the property of the prisoners, in payment of the fines decreed against them.
It appears, the Commissioners were offended at the letter,
and looked upon it as an instance of great provocation in the prisoners.
This was not surprising; nor, on the other hand, was it surprising,
that _they_ should have _so written._
It would have too much interrupted the narrative,
to have interposed this letter in the body of the work;
nor is there contained in it aught,
but what we might expect under such circumstances,--a plain, but solid expostulation:
original documents, however, even on ordinary subjects and of no extraordinary stamp,
occasionally throw a very material interest and light upon past transactions,
giving often a just insight into the springs of character and conduct.
It is here subjoined.

[.embedded-content-document.letter]
--

[.salutation]
George Melvill,

Being informed that you have undertaken that ungodly and unchristian employment,
to poind out goods for our keeping meetings to wait upon the Lord and to worship him;
we have found freedom to lay it before you,--that it is
the duty of every one who professes the name of a Christian,
to consider _by what spirit they are led,_ in all their actions and undertakings.
For, it is certain, there are but two spirits,
by which all the inhabitants of the earth are led in their thoughts, words, and actions;
either the Holy Spirit of Jesus, that leads into all truth and righteousness,
or the spirit of the world, which is +++[+++the spirit of]
the devil.
Accordingly, we exhort you, in God`'s fear, to weigh and consider,
_which of these is your leader in this undertaking._
If it be the Lord, you may judge by the principle it comes from,
and his light in the conscience will discover it unto you.
And if it be from Satan,
who is the god of this world,--your covetousness and fear of men,
more than the fear of God,--__that Light__ will clear it to you.
You must acknowledge, that whoever are serving the devil, are enemies to God; and God,
in his own time, will recompense every man according to the deeds done in the body.
And though a little profit or gain, or satisfying any corrupt affection,
may be for a season _sweet as honey in the mouth,_
yet before long it will be _as gravel in the belly._
And when the Lord shall enter into judgment with you, it will not excuse you,
that you were forced to it by the threats of great men, or were otherwise necessitated;
for all _that_ is but the fruit of an unbelieving heart, which knows not the power of God,
nor his faithfulness,--that he is able and will certainly
reward every one as they have sown,
whether they '`sow to the flesh`' or to the Spirit.

We must tell you,
that we have had such frequent proofs of the Lord`'s
_owning us and his Truth professed by us,_
that there are few of the instruments of our sufferings,
but have sometimes met with evidences of the Lord`'s displeasure against them;
as we can give instances, not only in England and in New England,
but even very remarkable ones in this place,--though little regarded by those,
__who observe not the works of God,
nor '`the operation of his hands.__`' And this is no strange thing;
for the Lord has said to his people, '`He that touches you,
touches the apple of his eye.`' Zech. 2:8.--There
are many who are far short of your outward deportment,
that would have been unwilling to have undertaken such an employment;
and we are persuaded, even in the eyes of sober men, this will make your name to stink,
and stain your reputation as a man,
and put such a blot upon you that you will not rub off.
You shall know,
our friends in England have published to the world in print their sufferings,
and have manifested the cruelties and unjust dealings, and the instruments thereof,
to be read and seen of all men, for the honour of the Truth,
and the convincing of those that otherwise lay little of this to heart.
_And what if, before long, there may somewhat of this proceed from us:_
for there is nothing of this kind, that as yet has slipped us, of being put upon record;
and you may judge what savour this may have in after ages, when, even in this also,
you shall be recorded for your unjust doing towards us.

We write not this out of any fear of what you or any else can do against us;
for we are serving the Lord, and are his people;
and through his grace and strength assisting,
_shall rejoice to be counted worthy to suffer for
his name_--not only the spoil of our goods,
but the worst that devils and men shall be permitted to do,
because of so blessed a testimony as we hold.
For, we believe _nothing shall befall us,
but that which shall have a tendency to the advancement of his blessed
Truth:_--and who will not willingly suffer for such blessed ends,
that has any true measure of the love of God in them?
But if you shall engage to be an instrument of our persecution,
we desire you may look over Scripture records,
and see what the Spirit of the Lord testifies concerning Cain,
the first persecutor of his brother, because his worship was accepted of the Lord,
and not his own; also how it was with Pharaoh and his people,
for hindering the Lord`'s people from going to worship him.
And consider, that, in the gospel times,
_none did ever persecute but the antichristian spirit,_
nor did impose upon men`'s consciences but the beast mentioned in Revelation 13:16-17;
who caused all ranks of men to receive his mark,
and in other respects had no common privilege with other men, so as to buy or sell.
Remember, that in Galatians 4:29, the Apostle declares, '`But as then,
he that was born after the flesh persecuted him that was born after the Spirit,
even so it is now.`' We suppose, _you_ would not be satisfied that any should do so to you.
Now as this we can say in the presence of God and man, so we remain,

[.signed-section-signature]
Your Friends.
<<note-V__xref_src,?LINKABLE-BACK>>

--

[#note-W.centered]
=== Note W.

Elizabeth, Princess Palatine of the Rhine, was the eldest daughter of Frederick the 5th,
Elector Palatine and King of Bohemia, by Elizabeth,
daughter of King James the 1st of England.
This excellent Princess possessed only a small territory;
but she governed it with great judgment, and attention to the happiness of her subjects;
on which account, she was greatly beloved and respected by them,
as well as by many persons of learning and virtue, not resident in her dominions.
"`Her meekness and humility appeared to me extraordinary;`"--says William Penn,
who knew her well, and has left an account of her in his [.book-title]#No Cross,
No Crown;#--"`she never considered the _quality,_ but the _merit,_
of the people she entertained Though she kept no sumptuous table in her _own_ court,
she spread the tables of the poor in their solitary cells.
Abstemious in herself, and in apparel void of all vain ornaments.
I must needs say, her mind had a _noble_ prospect;
her eye was to a better and more lasting inheritance than can be found below:
which made her often to despise the greatness of courts, and learning of the schools,
of which she was an extraordinary judge.`"
On one occasion she said to William Penn,
_"`It is a hard thing to be faithful to what one knows.
O, the way is strait!
I am afraid,
I am not weighty enough in my spirit to walk in it.`"_--"`She
lived till about 60 years of age,
and then departed this life at her own house in Herwerden, in the year 1680;
as much lamented, as she had been beloved by her people.`"

The correspondence stated to have been maintained between this Princess and Robert Barclay,
is noticed by his _grandson,_ in the Account of his family, now before the Author.
He remarks, "`Though I have many more of the said Princess`'s letters,
and copies of my grandfather`'s answers, I shall refer to the originals,
for those who want to see them.`"
These valuable documents, the Author, by favour of the present proprietor of Ury,
has searched for--but in vain.
<<note-W__xref_src,?LINKABLE-BACK>>

[#note-X.centered]
=== Note X.

It is believed,
that the present will prove the most eligible occasion
of reviving "`An Expostulatory Epistle,
directed to Robert Macquare, and delivered to him at Rotterdam,`" where he then resided:
it bears the date of 1678, and the signature of _Lilias Skene._

Of Robert Macquare, some information was given in the Diary of Jaffray,
as well as in the Appendix which follows it.
With regard to his female correspondent, it may be remembered,
she had been held in very unusual estimation among the worthiest,
as well as the highest in profession, of the citizens of Aberdeen.
She however found, as related in these Memoirs,
the peace of her enlightened and enlarged mind,
to consist in joining the Society of Friends; by this act,
more completely _taking up the cross to self,_ than she had hitherto seen the need of,
especially with regard to its more refined appearances and workings.
Thus, she was reduced to sit down as at the feet of Jesus,
and learn of him in _all things,_
who is "`meek and lowly in heart;`" herein "`proving what is acceptable
unto the Lord,`" through a deep searching of soul,
and a continued subjection of her own spirit to his.
The ensuing Epistle bears abundant token,
that she was no "`forgetful hearer`" in the school of Christ,
"`but a doer of the work,`" not "`ever learning and never
able to come to the knowledge of the Truth;`"--one who,
ceasing from an undue _leaning upon man,_ or unlawful _trust_ even in _princes,_
had attained to _more understanding_ in "`the mystery of godliness`" _than all her
teachers._--No mere admiration of the contents of this Piece would have prevailed
for its insertion here,--more especially as Robert Barclay has given it a place
in one of his publications,--had not its tendency been,
in every part, strikingly to develop the _work and character of that day,_--also,
the spirit of those,
who had to contend thus earnestly for the faith and liberty of the gospel.

[.embedded-content-document.epistle]
--

[.letter-heading]
Expostulatory Epistle To Robert Macquare.

[.salutation]
Friend,

My tender love and sympathy has been great in times past towards many of the Nonconformists,
who were suffering for conscience sake, and not for interest espousing that opinion.
And you being one of these, were often very near to me; notwithstanding I knew,
that generally the Nonconformists are more embittered
and prejudiced against us who are called Quakers,
than against any other men.
Yet this I often construed to flow from misinformation,
they being so little conversant among us.
And your being so _shy,_ was but like the disciples in a storm;
who seeing their Master appear in a manner they had not seen him before,
though he was coming nearer for their deliverance, yet cried out through fear,
as if it had been the appearance of some evil spirit.
At other times, I have looked upon the great prejudice many had against us,
as answerable to Christ`'s saying, '`No man having drunk old wine,
straightway desires new, for he says, The old is better.`'

Such constructions have hitherto, and do yet cause me to bear with you,
as well as to love that which is good among you, wherever it appears.
And because of this love towards you,
I am the more concerned at what you have lately published.
For though my acquaintance and intimacy with you, was not so great as others,
yet it was during a very serious season with us both, as I well remember;
_you being then shut up close prisoner, and daily in expectation of the sentence of death._
And I retain the fresh sense of your deliverance from such a situation; so that it was,
and still is (with many such occasions, wherein the Lord has prepared my heart,
and bended his ear,) a sweet encouragement to trust him,
as well as a singular engagement on me to wait for
the manifestations of his will at all times.

But oh! since I heard of and read your Postscript to John Brown`'s Book,
+++[+++entitled [.book-title]#Quakerism the Path-way to Paganism,#]
and S. R.`'s Letters, I am astonished and much ashamed on your behalf!
Are these the best fruits of so many years affliction,
which you have to publish to the world,--that one who is called
and is actually suffering as a Nonconformist to this sinful time,
should have learned no more conformity to meek and lowly Jesus,--of whom it is said,
'`He learned obedience by the things which he suffered?`' Surely,
none who read your language will say, _This man has been with Jesus;_ but rather,
that in whose company soever you have been,
you have learned to be a cunning artist at the scolding trade;
and are therein so vainly puffed up, as even to fly aloft, though with waxen wings,
above the lowly, meek, and harmless spirit of Christ.
In truth, had I all your rhetoric, whether natural or acquired,
and which you so much misimprove,
gratifying that part in yourself and your followers which needs rather
to be crucified,--it would not be my desire to imitate your example.
Nor shall I wish,
that ever you may have an answer from any of the Lord`'s people in your own terms;
which indeed are such, that all sober, unprejudiced people who read them,
will see your spirit, that it is most strongly embittered,
and your pen dipped as it were in gall.
I say, it is not my desire to bring forth one '`railing accusation`' against you,
neither to answer many things you have vented forth
against the Lord`'s present work and witnesses,
whom you so despise and defy.
Yet, if the living God, a part of whose host they are, should see fit,
he can raise up the very least among them to deal with you,
and make you feel '`worm Jacob`' a '`threshing-instrument
having teeth,`' to thresh that lofty,
malicious spirit that breathes through you.

The consideration of this your condition, upon your own soul`'s account,
is the occasion of this letter; wherein I desire to lay some things before you,
which are with weight upon me; my compassion on your behalf being kindled, lest,
when the Lord comes to visit the earth, you should be found among those,
who _are beating their fellow servants_--the hazard of which state, you know, and many,
no doubt, will feel, when the Lord _rises up to the prey._
For, indeed, his eyes '`are upon the righteous,
and his ears are open unto their cry.`' Although he be now trying the children of men,
permitting some to suffer, and others to do '`hard things;`' yet, a hope lives in me,
the time is approaching, wherein the Lord will more manifestly appear,
to the joy and refreshment of the single in heart, who suffer with him,
and patiently wait for him; as well as to the shame and utter overthrow of his opposers.

One of the particulars I would lay before you, is,
a desire you would yet in the Lord`'s light search your own heart more,
till you find out,
what secret affinity has remained with you to any
of the Lord`'s enemies in your own heart.
For, if all were brought under the government of the Son of God inwardly,
I am fully persuaded, your outward opposition to the Lord`'s work could not long stand.
The outward is a true figure of the inward: for I know by true experience,
all that despite, together with all those disdainful, undervaluing epithets,
you squeeze up your engine to coin, (and which one may feel,
answer not fully your own satisfaction,) for the purpose of bespattering
and loading this people and their principles,--is but,
alas! a mirror-glass set up to represent the low, mean,
unworthy esteem you bear to the light of Christ in
its appearance as a reprover within you.
For, whosoever turns universally at the reproofs of God`'s light in the conscience,
shall witness the pouring forth of his Spirit in larger manifestations;
according to Proverbs 1:23, '`Turn at my reproof: behold,
I will pour out my Spirit unto you,`' etc.
But that spirit, rather, speaks in you, of which Isaiah prophesied, liii.
2, 3, etc. when he alluded to the outward appearance of the same Christ, our Head,
and the Captain of our salvation.
His sufferings, death, resurrection, and glory, we dearly own,
and wait from day to day to feel more of the precious virtue thereof.
He was then '`despised and rejected of men,`' and they '`hid as it were their faces
from him,`' because His outward appearance was '`as a root out of a dry ground;
neither was there '`form,`' or '`comeliness,`' or
'`beauty,`' that he should be desired by that mind,
that was looking after great things, and expected outward glory and advantage.
Thus was Christ`'s appearance mistaken by the learned rabbis in that day;
notwithstanding they had Moses`' and the prophets`' testimonies and read the letter,
with others in this day.
And as it was then, so is it now,--he was and is mistaken by all,
who seek _anything to glory in, save the cross of Christ._
For the wisdom of the flesh ever has,
and ever does lift fallen man above the _innocent Seed_ in themselves,
through which alone they can see the invisible glory of the kingdom of God,
and find an abundant entrance unto the righteousness, peace, and joy in the Holy Spirit,
of which it consists.
Wherefore, take heed of being lifted up above '`the Seed of the kingdom,`' the Light,
Life and Spirit of Christ in you;
so will you see occasion to work out your salvation with fear and trembling,
and will not sit down upon former attainments or experiences when the Life is gone.
Another thing, of which I would put you in remembrance in these times is this;
The great danger of sinning at '`the waters of strife;`' of which
the example of Moses may be a standing monument to all generations.
Was it not said of him, that he was '`very meek,
above all the men which were upon the face of the earth?`' yet,
'`at the waters of strife`' '`he spoke unadvisedly with his lips;`' because of which,
he was debarred from entering into the promised rest.
And are there not some in this day,
who with sorrow of heart have observed the heat and bitterness of spirit which exist,
and how differences and controversy concerning religion
have eaten out the life of love and tenderness,
that was in many?
And those who have hurt the green thing in themselves and one another,
have brought on death, darkness, dryness,
and sensible withering,--and cannot fail to do so;
seeing bitterness of spirit and prejudice, with similar frames of mind, in man or woman,
separate from God.
For God is love, and he that dwells in love, dwells in God,
and God in him.`' And Christ has said, '`He that abides in me and I in him,
the same brings forth much fruit; for without me, you can do nothing.
If a man abide not in me, he is cast forth as a branch, and is withered.`' So,
not abiding in this pure love to God and his image in his children,
has caused many to fall short, and has hindered their progress,
and made them lose sight of their way, and the '`Guide of their youth:`' thus,
they have not fully followed the Lord in the regeneration,
who renews according to the increase of light, and the measures of his manifestation;
whereby they might know, even in this life, a being '`changed into the same image,
from glory to glory, even as by the Spirit of the Lord.`'

If you had the help of the Spirit`'s immediate teachings in your own hearts,
without which you will not yet understand aright the signs of this time,
you would see the Lord coming out of his holy habitation _to silence all flesh,_
'`to stain the pride of all glory,
and to bring into contempt all the honourable of the earth,`' that '`the Lord
alone may be exalted.`' Has not the Lord removed the most of all those,
who were eminently instrumental to serve him in the work of the ministry?
And is he not daily making bare the skirts of such as remain,
even daily making those to cease,
'`who rejoice in your pride?`' Is not his voice sounding aloud unto such of you as remain,
You shall '`no more be haughty, because of my holy mountain:`' therefore,
'`if today you will hear his voice, harden not your hearts.`' For, I am sure,
_the Teacher,_ that will tell you infallibly what you are called to do _is near,_
and is not '`removed into a corner.`' But it is the enemy`'s
work to veil and cover present duties and opportunities,
and to represent what is past and lost as very desirable;
and even to prompt a people or person to bewail their past failings and shortcomings,
who little heed the worth of the remaining season,
wherein they may yet '`redeem the time.`' Wherefore,
my advice in tender love to your soul, is, That you wait on the Lord,
to understand aright the import of such signs as are now appearing;
when the Lord is proceeding '`to do a marvellous work and a wonder among the people;`'
and is making '`the wisdom of their wise men`' to '`perish,`' and '`the understanding
of their prudent`' to be '`hid;`' and _pouring out of his Spirit upon sons and daughters,
servants and handmaids, provoking to jealousy, and angering_ the mighty, learned,
wise men of this generation,
by the _'`foolish`'_ appearance of a company of illiterate tradesmen,
who were never bred up at schools and universities, even weavers, and shoemakers,
and fishermen.

I also desire you to consider how inconsonant with
true Christianity a spirit of persecution is;
and how much more unsuitable and unequal for a people or person under the same condemnation.
Surely, that poor man, who had been but a little time in Christ`'s company,
was so far influenced by his meek and moderate spirit,
as not only himself to forbear railing against suffering Christ,
but to rebuke his companion for so doing:
which instance will stand in judgment against you for the contrary practice.
Neither will your denying us to be members of Christ, and that we suffer for well-doing,
and your accounting us demoniacs, avail you anything, nor cover you from that woe,
(if you obtain not mercy to repent,) denounced against those that '`call evil good,
and good evil; that put darkness for light, and light for darkness,`'--in that day,
when the Lord Jesus shall declare before men and angels,
we are his friends and followers.
O Robert! your hard speeches have manifested your own sad acknowledgment to be very true:
_the holy fire is indeed gone out_ with you; in the place of which, that which never was,
nor is of _God`'s kindling,_ is brought forth.
And this is not now to be found merely '`by secret search`' in corners,
or by secret surmises; but is by many of you laid open, and in your late Postscript,
as on a theatre, set up, so that those who run may read--the holy fire,
if ever there was any, is quite extinct.

Concerning this compound of unjust, groundless accusations and malicious inventions,
I nevertheless hope I may say, there are many sober, serious people,
who fear and serve the living God,--inward Jews,
whose hearts the Lord has circumcised to love him,
and who desire continually in the integrity of their hearts to serve him,--against whom,
no divination nor enchantment of devils or men shall prosper.
Of this blessed company, I do avouch myself one, through the free grace of God; and,
I trust,
we have put all your and your brethren`'s writings in the Lord`'s own hand to answer,
for the vindication of his glory, and the manifestation of his Truth;
nor do I desire to make any worse use of your Postscript,
than Hezekiah made of the writings of Rabshakeh in that day.
Unto the righteous Lord '`which searches the reins and hearts,`' do I appeal,
for his immediate help, and seasonable, powerful appearance.
I desire both to hope, and patiently to wait,
until he have '`performed his whole work upon Mount
Zion and on Jerusalem,`' both among you and us:
then shall be brought to pass the sure promise,
'`I will punish the fruit of the stout heart of +++[+++my adversary,]
and the glory of his high looks.`' In that day,
he will inwardly and outwardly both '`plead our cause,
and execute judgment for us;`' he will bring forth '`our righteousness
as the light,`' and make his judgments for us manifest '`as the
noon day,`'--although we now lie among the black pots of your reproaches.
The Lord will _bring_ us _forth unto the light,_ and we _shall behold his righteousness,_
either fulfilled within you, or manifested upon you.
My witness is in heaven--I am one who '`have not desired the evil day;`' but am willing
to embrace all the sweet opportunities of the drawings of my Father`'s love,
and the arisings of his life, to '`stand in the gap`' for the single-hearted among you.

When the Lord called me out from among the Presbyterians, I was one,
who according to my education, and information, and inclination from my childhood,
was a true lover of that +++[+++which was then]
called the glorious gospel, and a constant attender upon the declarations thereof.
The '`messengers`' feet`' who published it, were '`beautiful`' to me,
so long as those ordinances of man were unto me as the ordinances of Christ,
which was for the space of more than thirty years.
I loved them more than all things else in this world:
I '`passed through`' them '`hardly bestead and hungry`' for many years,
feeling after life and immortality, but could not find it: something was raised in me,
which words and reports could not feed: names and notions I minded little;
but _Christ to dwell in me_ was that, and still is that, which more and more I press after.

And now I must, for the Truth`'s sake, say somewhat,
(and I know the Lord will not impute it to be boasting,) respecting that season,
wherein the Lord revealed to me the true way unto life and immortality by his inward
appearance in my soul--which I humbly mention under a fresh remembrance of the love,
power, and tender mercy of God, who enabled me.
It was a time,
in which he had mercifully turned me from all that his light
inwardly and law outwardly had ever condemned me for.
My heart also did bear witness for me,--whatsoever I had known would please Him,
_that_ was I choosing to do;
nor was I hereby seeking justification in my own righteousness,
but rather a sure evidence of my interest in Him, who '`is made unto us wisdom,
righteousness, justification, and redemption.`' This blessed glimpse of my begun freedom,
was given me in a seasonable time,
that I might thereby be enabled to speak with my enemy in the gate,
and be encouraged to believe in the light, and wait upon the Lord,
to feel his virtue perfectly cleansing me,
'`from all filthiness of flesh and spirit.`' Neither was I an undervaluer of the Scriptures:
they were my rule _then,_ and I hope forever my life shall answer to them.
_I think they honour the Scriptures most, who live most according to them;_ not they,
who call them the only rule, yet do not make them their pattern.
The Scriptures of truth were precious to me; and by them was I taught,
not to walk nor worship in the way of the people; the Spirit showing me his mind in them.
And then I saw, in his light, that it is not the Scriptures many adore so much,
as their own corrupt glosses upon them.--Neither can my experience go
along with what you affirm of the hazard of converse with that people,
+++[+++Friends.]
It is very well known to all that lived in the place were I sojourned,
I was not one who conversed with them: I was never at one of their meetings:
I never read one of their books, unless accidentally I had found them where I came;
and then only looked to them, and laid them by again.

So now it remains with me to tell you, what was the occasion of my joining with them,
since it was none of those you mention; which I will very singly,
and can do very comfortably.
It was that thing, you school-men call _immediate, objective revelation,_ (with which,
it is my desire you were more particularly and feelingly acquainted,)
whereby the Lord raised in my soul his feeling life;
so that I could not sit down satisfied with hearing
of what the Son of God had done outwardly,
(though I believe, thereby he purchased all that grace and mercy,
which is inwardly wrought in the hearts of his children,) until
I should be a partaker of the virtue and efficacy of it,
and thereby possess '`the substance of things hoped for.`' I saw,
a historical faith would neither cleanse me nor save me: if that could save any,
the devils were not without a door of hope: I felt,
I needed _the revelation of the Son of God in me._
All that ever I read or heard, without this,
could not give me the saving knowledge of God.
'`None knows the Father, save the Son,
and he to whomsoever the Son will reveal him?`' Through the virtue of this,
were my eyes by degrees more and more opened.
For the tender-hearted Samaritan had pity upon my wounded soul,
when both _priest and Levite passed by,_
and '`the watchmen rent my veil;`' and when there was no eye to pity, nor hand to help,
_He drew near, and poured in wine and oil_ as he saw needful,
fulfilling in measure the promise, on which he had long caused me to hope,
'`He that follows me, shall not walk in darkness,
but shall have the light of life.`' And again, that sweet saying,
so confirming and comforting to me,
'`If a son shall ask bread of any of you that is a father, will he give him a stone?
etc. If you then, being evil, know how to give good gifts unto your children,
how much more shall your heavenly Father give the Holy Spirit
to them that ask him?`' These precious Scriptures,
and many similar to them,
being powerfully and seasonably opened up and applied by the Spirit of truth,
times above number, both before and since, in effect speaking forth this language,
'`Be not faithless, but believing,`'--have made me set to my seal those words of Christ,
'`It is the Spirit that quickens; the flesh profits nothing:
the words that I speak unto you, they are spirit,
and they are life.`' And as I _walk with Him,_ and _abide in Him,
watching at the posts of Wisdom`'s gate,_
traveling onward in spirit more and more to bring forth fruit unto Him,
endeavouring to walk worthy of Him,
'`unto all well-pleasing,`' as also daily to die unto self,
that Christ may live in me,--thus I become _a passive creature,_ and He _an active Christ,_
in the increase of whose government, I feel the increase of my peace.

And thus, my Friend, have you here, by some touches at things,
occasion to see how far you are mistaken concerning us;
and how far contrary to the truth as it is in Jesus,
you represent many things to the world,
speaking evil of things you know not--and if you _do_ know them,
the greater is your sin.--On two particulars, indeed,
I cannot strain charity so far as to believe you think of us.
Do we deny Jesus Christ and justification through his righteousness,
because we make the sufficiency thereof of a more universal extent than you?
or because we love _whole Christ_ so much, and his seamless garment,
that we will not have him divided?
No, we dare not _divide_ justification and sanctification, neither _confound_ them:
we have felt the _blood_ and the Spirit _distinct,_ yet, _inseparable._
Neither can you think, we make void the Scriptures, because we honour the Spirit,
which was before the Scriptures were written,
and bear testimony against all who deny the Spirit`'s immediate
teachings to be the universal privilege of the Lord`'s people.
Thus do you take away the key of knowledge, and neither enter the kingdom,
nor allow others who would; but monopolize knowledge to yourselves,
and intrude your _meanings_ upon the consciences of men, _as the rule:_--which meanings,
indeed, I do not own, either as the only rule or as any rule,
further than as the Spirit of Christ in my conscience answers it.

The testimony of the Spirit of Truth in thousands with me,
will stand and rise up against you, in the presence of the Lord,
when all your unjust reproaches and malicious accusations shall melt away
before the presence of the glory of the heart-searching God.
Before his tribunal, I desire daily to stand,
that he may more narrowly search me by his light;
and not only discover but destroy what he finds contrary
to his own pure nature and holy will,
whether mediately or immediately revealed.
Before this tribunal, you and I will before long more solemnly appear,
to give an account of the things we have done in the body!
That you may be able to do this with joy, and not with grief,--may you,
on future occasions, when you commend your writings to others,
have so much mercy on your own soul and the souls of your readers,
as to desire them to _ponder the path of their feet,
and let all their ways be established, neither turning to the right hand nor to the left._
And, be sure they come to the _holy faith,_
and not merely to an implicit belief of _the tradition of men._
By so doing, you, and as many as you can influence,
may come indeed to _fare well in the Lord._

I am one who, in my measure, travail for the redemption of the Seed of God in all souls,
and in yours.

[.signed-section-signature]
Lilias Skene.

--

The Author should have stated, that some few passages in the above letter are omitted,
and that some very slight alterations have been made in the phraseology.
<<note-X__xref_src,?LINKABLE-BACK>>

[#note-Y.centered]
=== Note Y.

Robert Barclay left his companions at Herwerden, and _they_ took that place, again,
on their way home.
See [.book-title]#W. Penn`'s Travels.#--James the 2nd has been accused
of pretending to be the champion of liberty of conscience,
for the sake of opening a way for the establishment of the Roman Catholic party.
This limitation of his good offices to the Barclays only,
and his refusal to interest himself for the relief of the sufferers generally,
does indeed favour the opinion that he was a timeserver,
and not a real friend to liberty of conscience.
See [.book-title]#R. B.`'s Life#.--Ragley, was a seat of the Lord Conway,
whose Lady may be said to have been one of _the excellent of the earth,_ and was,
doubtless, a particular acquaintance of the Princess Elizabeth,
as she certainly was of the writer of this letter.
For some extraordinary account of her,
see _a supplementary note_ at the end of [.book-title]#Penington`'s Letters,# 2nd edit.
1829, published by Holdsworth and Ball, London.
<<note-Y__xref_src,?LINKABLE-BACK>>

[#note-Z.centered]
=== Note Z.

Bishop Burnet declares of Archbishop Sharp,
that "`he stuck neither at solemn protestations, both by word of mouth and by letters,
nor appeals to God, of his sincerity in acting for the Presbytery,
both in prayers and on other occasions; joining with these many dreadful imprecations,
if he did prevaricate.
He was all the while maintained by the Presbyterians as their agent,
and continued to give them a constant account of his negotiations in their service,
_while he was indeed undermining it._
This piece of craft was so visible,--he having repeated his protestations to
as many persons as then grew jealous of him,--that when he threw off the mask,
about a year after this, _it laid a foundation of such a character of him,_
that nothing could ever bring people to _any tolerable thoughts_ of a man,
whose dissimulation and treachery were so well known,
and of which so many proofs were to be seen under his own hand.`"--"`A monster of hypocrisy,
perjury, and vileness,`" says Cruickshank in his [.book-title]#History;#
"`he betrayed the Church of Scotland, and persecuted the true members of it.`"
vol. i. p. 124.--Laing, another historian of Scotland, among other expressions,
in his review of the character of the Archbishop, has the following:--"`that he was vain,
vindictive, perfidious, at once haughty and servile, rapacious and cruel,
__his friends have never attempted to disown:__`" "`-- he became an unrelenting persecutor,
like most apostates:`"-- vol.
iv. p. 95.
<<note-Z__xref_src,?LINKABLE-BACK>>

[#note-AA.centered]
=== Note AA.

Particulars of this difference,
may be seen in [.book-title]#Memoirs of the Life and Actions of Sir Ewen Cameron of Lochiel,# vol.
ii. p. 49, etc. and especially of the part taken by Barclay in that troublesome affair.
He evinces much disinterested and unambiguous friendship towards his brother-in-law,
who had a very powerful opponent in the Duke of Gordon.
After writing on his behalf to several of the English nobility,
with whom he was intimate;--all of whom however declined
giving their assistance in that business,
though they offered their good offices in any other respect
in which they could serve him;--Barclay recommends him,
to endeavour by all means to obtain private access to the King.
But his friend did not stop here.
He followed up this recommendation,
by himself undertaking to solicit the interference of James the 2nd;
and succeeded in obtaining from him a full hearing upon the whole matter,
in the presence of the Marquis of Powis and the Earls of Murray and Melfort,
who were requested to become referees.
Persevering through all obstructions raised by the opposite party,
Barclay was at length enabled to obtain a final settlement,
much to the advantage of Cameron of Lochiel.
<<note-AA__xref_src,?LINKABLE-BACK>>

[#note-BB.centered]
=== Note BB.

[.embedded-content-document.letter]
--

[.letter-heading]
Ann, Countess of Errol, To Christian Barclay.

[.signed-section-context-open]
Slains, 27th February, 1690-1.

[.salutation]
Much honoured,

As there was none had a greater esteem of the merit
of your worthy husband while alive than I,
so there is none values his memory more than I shall always do;
and this remembrance of him, which you have been pleased to send me,
shall on that account be as carefully kept as I preserve anything,--which I accept
of with very sincere gratitude to yourself and all the rest of his family.
I cannot fail to have a kindness for them,
by reason of their relation to one I considered as
so deserving a friend both to myself and to my brothers.
For I have been often very well pleased to hear him mention them very affectionately,
even at a time when most of the world had a vanity in railing at them;
but I cannot deny him the justice to own,
that I found his friendship for them rather increase than diminish,
as their misfortunes grew upon them;
and I am sure they are both very sensible of their loss,
by being deprived of so worthy and disinterested a friend as he proved on all occasions.
But besides all the obligations I owe you upon his account,
either for my relations or myself,
I am now particularly bound to yourself for minding to bestow one of his books on me;
though I cannot but value the favour you do me,
in believing me one that had a real esteem of his
virtues more than is possible for me to express.
And, by the little time which I had the satisfaction to see your son,
_I was very well pleased to see so good appearances
in him of supplying the place of so deserving a father;_
and it shall be a very acceptable satisfaction to me to see any of your
family at this place;--for I am affectionately at your service,

[.signed-section-signature]
Ann Errol.
<<note-BB__xref_src,?LINKABLE-BACK>>

--

[#note-CC.centered]
=== Note CC.

"`In the year 1694, Peter Gardner, a Friend who lived in Essex,
had a concern to visit Friends in Scotland; but being in low circumstances,
and having a wife and several children, was under discouragement about it.
The Lord in mercy condescended to remove his doubts,
by letting him know he would be with him; and though he had no horse to ride,
and was but a weakly man, yet he would give him strength to perform the journey,
and sustain him so that he should not go without what was sufficient.
Having faith,
with innocent weight he laid his concern before the monthly meeting to which he belonged:
they highly esteemed his gift, and had full unity with his concern;
and proposed procuring him a horse for his journey.
But he said, '`No: My Master has promised to give me hind`'s feet.`'

"`He accordingly went on his journey along the east side of the nation, through Norfolk,
Lincolnshire, and Yorkshire; and coming to a week-day meeting at Bridlington,
where John Richardson then dwelt, he lodged at his house.
In the evening, the doors being shut, he said to John,
pointing his finger in a particular direction,
'`Is there any Friend lives that way?`' John told him.
He pointed towards the sea, which was not far from there.
He said, He believed he must go and see somebody that way in the morning.
John asked him, If he should go with him; he said, He believed it would not be best:
and so, went to bed.
In the morning, after John had walked over his grounds, and done his usual business,
he came in, and inquired after Peter; his wife said, She had not seen him,
and believed he was not risen.
John went up into his chamber, and finding him not there, came down,
and in a pleasant way said to his wife, '`There is the nest,
but the bird is flown.`' Soon after, came in Peter.
He had risen before the sun, and went to the village,
by no other direction than that internal intelligence he immediately received; and,
at sun-rising, beheld a Friend leaning on a post at his own door,
in a pensive and solitary mood.
Peter went to him, and asked him after his welfare, and if he had any family; he said,
He had a wife, confined to her bed with a dangerous illness, and invited him to see her;
to this, he replied, '`For that end am I come.`' He went up stairs,
and sitting down retiredly by her side, in an awful and solemn manner, said,
'`You have long had a concern on your mind to visit the churches in America,
but your husband has hindered you:`' and told her,
The will and resignation of her mind was accepted for the deed,
and she was excused from the journey which was before her;
and should die in peace with God and man.
Then addressing her husband, he said, '`Your wife,
had a concern to visit the churches in another country beyond the sea,
but you would not give her leave; so, she shall be taken from you:`' and,
repeating part of what he had said to her, added, '`Your wife will be happy:
but the Lord will blast both you and yours; for behold the Lord`'s hand is against you,
and you shall be reduced to beg your bread.`' This message was not received in that love,
in which it was delivered; but in heat and passion, he came after Peter; and,
calling in great haste, as he sat on horseback, at John Richardson`'s door,
seemed very angry with John, and asked, What man and message he had sent to him?
'`As to __message,__`' said John, '`I know nothing of it; but as to _the man,_ I may tell you,
he is a man of God, and whatever he has said to you, be it upon you.
Therefore be still, and weigh the matter: for I knew not of his going to your house,
but thought he was in bed, and did not inform him about you, nor your wife.`' At which,
he went away in great haste.

"`So, Peter pursued his journey towards Scotland,
John Richardson and another Friend going with him to Scarborough
on horseback--for he would not let them go on foot with him.
He kept before them full as fast as they chose to ride:
and when they had got about half way, he gained ground upon them:
John was filled with admiration, for he seemed to go with more slight and ease,
he thought, than ever he had seen any man before.
And riding fast to overtake him, and going over a field for a nearer cut,
he appeared to be surrounded by glory, and his feet seemed not to touch the ground.
When he overtook him, John said, '`You do travel very fast:`' Peter replied,
'`My Master told me before I left home, that he would give me hind`'s feet;
and he has performed his promise to me.`' When they came in sight of Scarborough,
he said, '`Do take me to some Friend`'s house--__a Friend`'s indeed,__
for I am greatly distressed.`' '`I will have you to a house where I lodge,
and have spent many hours with pleasure; and if you are not easy there,
I will go until we find a place, if it may be.`' And just as they entered the door,
_they heard some one go up stairs;_ and anon, the woman Friend coming down,
with a neighbour of hers, invited them to sit down.
In a little while, Peter appeared _very uneasy;_ which John perceiving, asked,
how it was with him; he said, '`I cannot stay in this house: __here is light and darkness,
good and bad.__`' The woman, after she had got them some refreshment, came and asked John,
'`Who have you brought here?`'-- '`A man of God,`' he replied.
Whereupon, they went away.

"`Having a meeting at Scarborough the next day, John Richardson stayed with him; and said,
he had good service.
He also went with him to several Friends`' houses there;
and he frequently spoke his sense of the state of the families:
but as they were near entering one house, Peter stopped, and said,
'`My Master is not there--I will not go in:`' so they turned away.
Being about to part, he queried with John, If the small-pox was in any town on his way?
John replied '`Why?
Peter, what have you to do with that?`'--he answered,
_'`I am satisfied I shall die of that distemper;_
and my Master told me to make speed in this visit,
for I had but a _short_ time to do it in;`' repeating
his promise of giving him hind`'s feet.
John felt himself much affected: and, considering his mean appearance, asked,
how he was prepared for money?
telling him his journey was long, it being expensive traveling in Scotland,
Friends being so thin.
Peter answered, '`I have enough: my Master told me I should not be in want;
and now a bit of bread, and some water from a brook,
refreshes me as much as a set meal at a table.`'
But John insisted to see how much money he had:
it was but two half-crowns.
He felt an immediate impulse to tender him some money; and,
putting his hand into his pocket, took out a number of small pieces,
which Peter modestly refused, saying, He doubted not of his Master`'s provision.
John forced him to take it; telling him, It was as free to him as his own;
for so the Lord had put it into his heart.--Thus they parted.

"`In about two weeks after, the man`'s wife, before mentioned, died,
as Peter had foretold.
At that time, the same man had three ships at sea; his son was master of one,
his second son was on board another; and, in their voyages,
they were all wrecked or foundered, and their cargoes chiefly lost;
his two sons and several of the hands being drowned.
So that, from considerable affluence, he was soon after reduced so low,
as to be maintained by Friends, though he had been in good circumstances,
if not very rich, before those unexpected losses, at sea and land,
in houses and children, had befallen him.--The woman,
at whose house Peter was so uneasy at Scarborough,
_had put her husband to bed in a state of intoxication;_
which John Richardson had not known him guilty of before.

"`John Richardson further related, that after some time, he heard,
that Peter Gardner had died in Cumberland, on his return from Scotland;
and being attached to him in near affection, went to inquire how he ended.
John Bowstead, a Friend near Carlisle, gave account,
that Peter had been through Scotland, and came to Carlisle; the small-pox being there,
he took the infection very suddenly, and lay ill with it.
So John Bowstead went just as the pock was coming out upon him,
and took him to his own house; they did not come out kindly, but swelled him very much,
so that he was blind, and died about the seventh day.
He was _quite sensible_ to the last; and in a remarkable manner,
was given to know the inward states of those that came to see him.
And further, the money, which John Richardson had handed to him, actually lasted out,
so as to defray the expenses of his interment and other charges incurred there.`"
<<note-CC__xref_src,?LINKABLE-BACK>>

[#note-DD.centered]
=== Note DD.

The sentiment thus quaintly conveyed in the two last lines of this stanza,
has always been prominently held forth to view by the Society of Friends;
but has been not infrequently in a strange degree misunderstood,
as well as attempted to be perverted to our prejudice.
The following quotation from a small volume,
highly approved by orthodox members of the _"`Established Church
of England,`"_ may serve to illustrate its truth and import.--Though
holy and religious persons do much eye the law of God,
and have a great regard unto it, yet it is not so much the sanction of the law,
as its reasonableness, and purity, and goodness, which do prevail with them;
they account it excellent and desirable in itself,
and that in keeping of it there is great reward;
and _that divine love_ wherewith they are actuated,
makes them become _a law unto themselves._

[verse]
____
Quis legem det amantibus?
Major est amor lex ipse sibi.

Who shall prescribe a law to those that love?
Love`'s a more powerful law, which does them move.
____

"`In a word, what our blessed Saviour said of himself, John 4:34,
is in some measure applicable to _his followers,_
that _it is their food and drink to do their Father`'s will:_
and as the natural appetite is carried out toward food,
though we should not reflect on the necessity of it for the preservation of our lives;
so are _they_ carried with a natural and unforced propension towards that
which is good and commendable.`" [.book-title]#The Life of God in the Soul of Man,#
9th edit. p. 7.--This volume contains much that is of sterling, spiritual worth.
It has been already quoted in the course of these Notes, and as there stated,
was penned by Henry Scougal, styled, _professor of divinity_ at Aberdeen,
son of Patrick Scougal, Bishop of that place,
whose name has been repeatedly mentioned in these Memoirs.
_Bishop Burnet, the historian,_ first published it in 1691; and, in his preface, affirms,
that "`the author has written out _nothing_ here,
but what he himself did __well feel and know.__`"
No wonder, then, that Pinkerton,
in his [.book-title]#Iconographia Scotica,# should describe it as "`a work of eminent piety,
__without enthusiasm.__`"
<<note-DD__xref_src,?LINKABLE-BACK>>

[#note-EE.centered]
=== Note EE.

At page 225 of these Memoirs,
mention has been made of a connection in marriage between Jean Barclay,
sister to "`the Apologist,`" and "`Sir Ewen Cameron of __Lochiel.__`"
The family of _Lochiel,_ here spoken of,
as being visited by the son of "`the Apologist,`" in company with his three fellow travellers,
was the same.
And it further appears, by a minute of the Aberdeen Monthly Meeting, that "`Una Cameron,
daughter to Ewen Cameron of Lochell,`" laid before
them her intention of marriage with "`Robert Barclay,
grandson of the Apologist.`"
<<note-EE__xref_src,?LINKABLE-BACK>>

[#note-FF.centered]
=== Note FF.

When the 6th edition of this work had nearly gone through the press, the Author happened,
in a very unlooked for manner,
to meet with a MS. collection of small pieces penned by this Friend,
and _all of them_ dated during the season of his imprisonment at Aberdeen.
It embraces nearly 400 very closely filled quarto pages;
and consists chiefly of addresses to the public at large,
to the professors of religion in that city, or to his friends in Christ.
Much excellent doctrinal matter,
as well as practical exhortation in the love of the gospel, is to be found in the volume;
but what seemed particularly striking in regard to it, was the circumstance,
that 130 of these pages should bear the date of the _Iron-house,_--a cell,
it will be recollected, in which Patrick Livingston was confined for seven weeks,
where scarce any light was admitted,
and under circumstances almost intolerable to human nature.
<<note-FF__xref_src,?LINKABLE-BACK>>

[#note-GG.centered]
=== Note GG.

The following admission has recently appeared from the pen of the biographer of Baxter;
and forms no unimportant attestation in favour of that special service to which
the Society of Friends were eminently called.--"`Considering,`" says Orme,
"`the abuses of divine ordinances, which had so long and so extensively prevailed,
_it is not surprising,_ that such a system as _Quakerism_ should have arisen;
and,`" continues he, "`it may perhaps have answered a useful purpose,
in calling the attention of men professing Christianity,
_to the great design of all its ordinances,_
and to which they ought ever to be regarded as subservient--__the
promotion of spirituality of mind,
and the enjoyment of communion with God.__`" vol. ii. p. 349.
It is remarkable, too, that Baxter himself,
whose controversy lay for many years against the doctrine of the Spirit,
as it was so prominently held forth by our honourable predecessors, should,
latterly in life, have been brought thus far to acknowledge:--"`I am now,`" he says,
"`much more apprehensive than heretofore of the necessity
of well grounding men in their religion,
especially of _the witness of the indwelling Spirit,_--for I more sensibly perceive,
that _the Spirit is The Great Witness of Christ and Christianity to the world._
And though the folly of fanatics tempted me long to overlook
the strength of this testimony of the Spirit,
while they placed it in a certain internal assertion, or enthusiastic inspiration;
yet now I see that the Holy Spirit, in another manner, _is the witness of Christ,_
and his agent in the world.`"--[.book-title]#Life and Times,# by Orme, vol. ii. p. 459.

In connection with the subject of the present Note,
the Author cannot better do justice to his own sentiments
upon the important ground which the early Friends took,
than by quoting a few lines from a valuable pamphlet,
which has appeared while these sheets were passing the press.
"`The professors of Christianity in the time of George Fox,
had generally forsaken the spirituality of religion,
but were not in the least lacking with regard to a belief in the outward coming,
the divinity, and sacrifice of Christ.
Hence there was not _that_ necessity of insisting upon
faith in this last mentioned part of the covenant,
respecting which there was _no_ defect of faith,
as upon that part in which there was a deficiency.

I believe, that the more +++[+++of]
true, spiritual Christianity a man has, the better he will be qualified,
rightly to see and to estimate the doctrines of truth,
as contained in the Holy Scriptures,
_relative to the outward coming and offices of Jesus Christ._
And, for this very reason, I believe, and am abundantly convinced,
that our predecessors had much more of _the true faith,_
and had much clearer views of the meaning and standing of the Scriptures,
as well as _of the true divinity of our Lord and Saviour,
and the purposes of his sufferings,_ than other professors of that day,
who were making a high profession of their faith in them,
but many of whom were lacking in spiritual and vital religion.`" [.book-title]#Letters to a Friend,# etc. by John Wilbur, p. 26.
<<note-GG__xref_src,?LINKABLE-BACK>>

[#note-HH.centered]
=== Note HH.

However clear such doctrines may appear to many readers,
the Author cannot entirely quit the subject, without still further confirming it,
as the doctrine of the Society of Friends,
and even of "`the Established Church of England,`" by adducing
the following quotation from the writings of a learned man,
who had once been, a rector among the _latter religious class,_
but ultimately became a valued minister among the _former._

"`We say, then, according to the Scriptures, That Christ died for all,
that they which live, should not henceforth live unto themselves,
but unto him which died for them and rose again, 2 Cor. 5:15.
--that without faith it is impossible to please God, Heb. 11:6.
--that without repentance the sinner shall perish,
see Luke 13:3,5.--and without holiness no man shall see the Lord, Heb. 12:14. And,
(in the words of _Archbishop Tillotson_ in his Sermon 4th,
Concerning the Incarnation of our blessed Saviour, on John 1:14) we add, that,
'`The salvation which the Son of God has purchased for us,
and which he offers to us by the gospel,
is not to be accomplished and brought about any other way,
than by forsaking our sins and reforming our lives.
_The grace of God, which has appeared to all men, and brings salvation,_
will not make us partakers of it in any other way, or by any other means,
than _by teaching us to deny ungodliness and worldly lusts, and to live soberly,
and righteously, and godly, in this present world._
God sent his Son to bless us, by turning us away every one from his iniquities;
and unless this change be effectually wrought in us,
we are utterly incapable of all the blessings of the gospel of Christ.
All that he has done for us, without us, will avail us nothing,
unless we be inwardly transformed, and renewed in the spirit of our minds,
unless we become new creatures,
unless we make it the continual and sincere endeavour
of our lives to keep the commandments of God.`'

"`'`The obedience and sufferings of our blessed Saviour,`' continues the Archbishop,
'`are indeed accounted to us for righteousness,
and will most certainly redound to our unspeakable benefit upon the performance
of the condition which the gospel does require on our part,
namely, that every man that names the name of Christ, depart from iniquity.
And the grace of God`'s Holy Spirit, is ready to enable us to perform this condition,
if we earnestly ask it, and do sincerely cooperate with it;
provided we do what we can on our part, God will not be lacking on _his._
But if we receive the grace of God in vain, and take no care to perform the condition,
and neglect to implore the grace and assistance of God`'s Holy Spirit to that purpose,
we have none to blame but ourselves; because it is then our own fault,
if we fall short of that happiness which Christ has purchased and promised to us,
upon such easy and reasonable conditions as the gospel proposes.`'`"--[.book-title]#The
Life and Posthumous Works of Richard Claridge.# 1726. p. 453.
<<note-HH__xref_src,?LINKABLE-BACK>>

[.the-end]
The End.
