== Preface

In presenting this little selection to the public,
the compiler thinks it well to observe,
that many of the materials were long ago transcribed for his own improvement,--that,
in years which are past,
he was occasionally in the practice of producing these and
many other extracts from the writings of Friends,
among the fireside circle of his intimate acquaintances,
and that of late he was induced,
at very broken intervals during a time of much domestic affliction,
to adjust and prepare them for the press.
His chief aim, in the first instance,
was the instruction of young people in the Society of which he is a member,
but as the work grew under his hand,
he could not but anticipate for it a less confined circulation.
He doubts not all due allowance will be made by the critical eye,
for the style of those writers, who lived in an age of less refinement than the present,
most of whom had received at farthest a plain, useful education,
and whose utmost desire in communications for the benefit of their fellow creatures,
was to address themselves in simplicity to the heart and conscience.
"`Excellency of speech,`" or "`the enticing words of man`'s wisdom,`"^
footnote:[1 Corinthians 2:1 & 4]
was not their ambition: indeed precision and correctness are sometimes nearly wanting;
so that on this and other grounds some very slight liberties
have been occasionally taken with the text of the authors.

The compiler may also add, that for some observations he has ventured to intersperse,
he of course considers himself alone responsible.

[.signed-section-context-close]
London, 9th of Fifth month.
