== Chapter I

[.centered]
=== George Fox and the Jailer

In the year 1650, George Fox was imprisoned at Derby,
where he continued in confinement about a year.
The keeper of the prison, a high professor of religion, was greatly enraged against him,
speaking very wickedly of him,
and often endeavouring to draw some unguarded language from him, wherewith to accuse him.
But George was kept in such innocence and circumspection of conduct,
that though his words and actions were watched, no fault could be laid to his charge.
The following is expressed in his own words:

[.embedded-content-document]
--

It pleased the Lord one day to strike the jailer, so that he was in great trouble,
and under much terror of mind.
As I was walking in my chamber, I heard a doleful noise, and standing still,
I heard him say to his wife, "`Wife, I have seen the day of judgment;
and I saw George there, and I was afraid of him, because I had done him so much wrong,
and spoken so much against him to the ministers and professors, and to the justices,
and in taverns and ale houses.`"
After this, towards the evening, he came into my chamber and said to me,
"`I have been as a lion against you; but now I come like a lamb,
and like the jailer that came to Paul and Silas trembling.`"
He acknowledged also, that he had been plagued and his house too for my sake.
Afterwards he told me all his heart, and said,
he believed what I had said of the true faith and hope was true, and confessed,
that at those times when I had asked him to let me
go forth and speak the word of the Lord to the people,
and he had refused, and I had laid the weight of it upon him,
he used to be under great trouble, amazed, and almost distracted for some time after,
and in such a condition that he had little strength left him.
When the morning came, he rose and went to the justices,
and told them that he and his house had been plagued for my sake.
One of the justices replied (as he reported to me),
that the plagues were upon them too for keeping me.
This was Justice Bennet of Derby, who was the first that called us Quakers,
because I bade them tremble at the word of the Lord.

[.signed-section-signature]
_George Fox`'s Journal_

--

It is worthy the notice of the reader,
that this penitent jailer afterwards joined in society with Friends,
and instead of keeping a prison, had everything taken from him,
and there is little doubt suffered imprisonment also.
He wrote a lively feeling letter to George Fox at that time,
which plainly bespeaks a mind given up "`in the behalf of Christ,
not only to believe on him, but to suffer for his sake.`"^
footnote:[Phil. 1:29.]

Thus we see that the judgments and terrors of the Lord plague the hearts of the disobedient,
and that He is not wanting to plead the cause of the upright,
even in the very consciences of those that persecute and hate them.
Herein was the ancient proverb fulfilled which declares,
"`_Judgments_ are prepared for _scorners._`"^
footnote:[Prov. 19:29.]

[.asterism]
'''

[.embedded-content-document]
--

William Callow, of the Isle of Man, was detained eight weeks in prison there,
in the year 1657, for reproving a priest,
whom he had heard abusing the people called Quakers, in his sermon to the people.

Several persons were taken out of a meeting on the 1st day of the week,
and set in the stocks four hours in the market place; others were fined,
and William Callow among them, ten bushels of oats being taken from him by distress,
and laid in another person`'s barn.
On the next 1st day, after sermon,
the priest gave public notice for the poor of the
parish to go to the barn and take some corn,
which the governor had ordered to be distributed amongst them;
to this some of the poor people, his own hearers, answered,
that it had been more charity to have given his own goods to the poor than other men`'s,
and that they would receive none of it.
However, some of the poor went to the place with the priest and the soldiers,
and William Callow went also.
The priest called several times to the poor to hold their bags, but none of them would;
at this the priest grew angry, and looking sternly at William Callow,
called to the people, "`Why don`'t you take the corn?
Is there any one here that hath aught to do with this corn,
or saith it may not be given to the poor?`"
This he said to provoke from William some expression, but he held his peace.
The poor stood a while, and then withdrew one by one,
leaving the corn with the priest and soldiers.
On the following 1st day,
the parson again publishing the distribution of the corn as before,
signified how much the governor was displeased that they had not taken it.
For fear of the governor and the priest, some poor people went again to the place,
but only one of them would take any, and he vauntingly said to the rest,
"`You are so proud you will not take it: I have got this,
and there will be more of his goods taken before this be eaten,
and then I`'ll get more:`" but it so happened, that before he had eaten what he had took,
he was taken away by death.
His sudden exit was interpreted by the other poor as a judgment upon him,
and they were glad that they had kept themselves clear.
The rest of the corn lay till it was spoiled, for nobody would take it.

William Callow, and several others,
for two-pence each demanded by the priest for bread and wine,
of which they had received none, were imprisoned by warrant from the governor;
from whom also, in the 7th mo.
1659,
the priest procured another warrant for the imprisonment
of William Callow and another friend,
for refusing to pay tithes.
One morning early, as soon as they came on shore,
after being all night in the wet and cold at sea (for they were fishermen),
they were hurried to prison in their wet clothes,
and detained several days in the midst of their herring fishery,
the most advantageous season for their business.
This, however designed by their adversary,
was not productive of the prejudice which might be naturally expected;
for the next night after their release they caught
as many fish as they were able to bring to shore,
so that they had reason gratefully to acknowledge a peculiar providence attending them.

[.signed-section-signature]
_Gough`'s History of Friends_

--

[.asterism]
'''

Lord Baltimore and his lady,
with their retinue attended a meeting for worship at Treddhaven in Maryland,
in the year 1700, to which, being the yearly meeting, William Penn accompanied them;
but it being late when they came,
and the strength and glory of the heavenly power of the Lord going off from the meeting,
the lady was much disappointed, and told William Penn, she did not want to hear _him,_
and such as he, for he was a scholar and a wise man,
and she did not question but he could preach;
but she wanted to hear some of our mechanics preach, as husbandmen, shoemakers,
and such like rustics; for she thought they could not preach to any purpose.
William told her, some of them were rather the best preachers we had amongst us.

[.asterism]
'''

The following narrative occurring in [.book-title]#John Richardson`'s Journal,#
whilst it plainly bespeaks such earnest engagement
of soul as is worthy a true minister of the gospel,
conveys also towards the conclusion some idea of that precious peace,
which the prophet Isaiah speaks of as follows: "`Thus saith the Lord, thy Redeemer,
the Holy One of Israel; I am the Lord thy God which teacheth thee to profit,
_which leadeth thee by the way that thou shouldst go._
O that thou hadst hearkened to my commandments! then had thy _peace been as a river,_
and thy righteousness as the waves of the sea.`"^
footnote:[Isaiah 48:17. 18.]

[.embedded-content-document]
--

Having it on my mind to visit a meeting up the river called Perquimus,
on the west side of the river Choptank, and being +++[+++myself]
on the east aide, Henry Hosier and some more friends set forward with me in a small boat,
not in good condition but crazy, with only one small sail.
We sat out, as we thought, in good time to reach our desired port,
but when we were upon the great river, (as I remember,
it is ten miles over the shortest way,
but the manner of our crossing it made it more,) the wind veered much against us,
being then within about four points of our course, it rained hard also, and was so dark,
that we could scarcely see one another; and the water broke into the boat,
so that it was nearly one man`'s work to heave it out,
and all our company were discouraged, most of them being very sea-sick.
Henry Hosier, of whom I had the most hopes for help, said,
that he could not steer the boat any longer.
What by the extreme darkness, the roughness of the waves, boisterousness of the wind,
and hard rain, I, unwell as I was, was obliged to undertake the steering of the boat,
and not without some conflicts of mind,
not having any certainty from any outward rule what way we went; having no fire,
and the boat being open, we could not have any light to see our compass:
but my faith was in the Lord, that he would bring us to shore;
and I kept as near the wind as she would sail,
and told my poor sick and helpless company, I believed that we should not perish,
although we might miss of our port.
But the like imminent danger I think I was never in before upon any water; yet,
renowned over all be the great name of the Lord forever,
we put into the mouth of our desired river Perquimus,
as though we had seen it in the day, or steered by a compass,
neither of which we had the benefit of for several hours.
Here we went ashore, and made a great fire under the river`'s cliff,
and about midnight the moon rose, and it cleared up and froze, and was very cold.
My companions falling asleep, I turned them over,
pulling them from the fire as it increased, and putting them nearer as it failed,
but could not keep them awake; I sought logs of wood,
and carried them to and minded the fire,
which was work enough for the remaining part of the night; but, morning being come,
we got in our cold icy boat, and sailed away towards the meeting.

When we were come among Friends, notice was given of a stranger being there;
and a heavenly and sweet meeting it was,
so that we thought we had a good reward for all our trouble,
blessed be the name of the Lord now and forever, for He is worthy:
although he may see good to try us, sometimes,
one way and sometimes another,--how should we know that we have any faith,
if it be not tried?
How shall we know that we have any true love to God, if it never be proved?
The trial of the true believer`'s faith is more precious than gold.
The excellent sayings of Job came into my mind, "`Behold, I go forward,
but He is not there; and backward, but I cannot perceive him: on the left hand,
where he doth work, but I cannot behold him: he hideth himself on the right hand,
that I cannot see him.`"^
footnote:[Job 23:8.]
And then like a man in the true faith, saith, "`The Lord knoweth the way that I take:
when he hath tried me, I shall come forth as gold.`"^
footnote:[ver. 9.]

I have often thought of Moses, how far he went for the saving of Israel,
and how far Paul went for the saving of his kinsfolk after the flesh;
it was a great demonstration that these great and
good men had great faith and interest in the Lord,
and also a very great love to his people.
And such whose eyes are truly opened, cannot but see it is the love of God,
and love to the souls of men, that constrains us thus to take our lives as in our hands,
and labour under many weary steps, and many perils by sea and by land,
and in the wilderness, cold, and sometimes in tumults and noises,
sometimes in watchings and fastings, that we have been sometimes spectacles to men;
but the Lord hath given us faith and patience to bear and overcome all,
as we have singly stood in his heavenly counsel,
and been truly devoted to his will in all things.

--

[.asterism]
'''

[.centered]
=== Faithfulness Under Persecution

The same gospel labourer, when a youth,
was left by the decease of his father to the charge of a cruel step-father,
whom his mother married when he was about eighteen years old.
He had attended Friends`' meetings with diligence for some time,
and knew well the value of them,
and of the testimonies which we as a people are called upon to bear;
having previously passed through many of those conflicts,
which more or less are permitted to assail the awakened soul.
His stepfather soon became much displeased with him, on account of his going to meetings,
and though he worked very hard for him in his business,
it being almost incredible what his poor weak body went through,
yet all would not gain his love.
On his return from meetings, although as seasonably as his strength would admit,
he met with many an unkind look and word;
and his father usually sending him on first-day mornings
into the fields a mile or two on foot,
and as far upon a common to look at beasts, horses and sheep,
seemingly on purpose to render him incapable of going to meetings,
he was obliged to walk fast,
and sometimes ran with his shoes under his arm for want of time;
which affected many Friends, so that they could not forbear weeping,
to see him come into the meeting very much heated, having come two, three, four,
and sometimes six miles.

"`The Lord`'s mighty power bore me up,`" says John Richardson,
"`and he gave me as it were hind`'s feet, and enabled me to go through these exercises,
and to bear the burden in the heat of the day of my trials, inwardly and outwardly,
which were many and various.`"

After other stratagems used to hinder his going to Friends`' meetings,
and when he saw that neither frowns, threats, hardships,
nor great promises of kindness could prevail, his father told him bluntly and roughly,
he should stay no longer in his house, to which John innocently replied,
he could not help it if it must be so, as all he could do would not give him content,
without hurting his conscience and the peace of his mind, which, he said,
he valued above all mutable things of this world.

[.offset]
John Richardson proceeds thus in his narrative:

[.embedded-content-document]
--

Notwithstanding I pleaded with my father to let me stay until I could hear of a place,
he would not, though I was scarce fit for service, being +++[+++so reduced]
that most who knew me said, I should pine away in a consumption; but turn out I must,
and did, though weak, poor and low, in body, mind, pocket and clothes,
having then but twelve pence in my pocket, and very ordinary clothes on my back.
Thus I took my solemn leave of the family, with my heart full,
but I kept inward to the Lord, and under Truth`'s government;
many tears were shed in the family, especially by my poor mother; my father said little,
but appeared like one struck with wonder,
to see so much love manifested towards me by the family,
and so much wishing that I might not go away.

When I came out upon the great common, where I had had many solitary walks,
I thought of Abraham who was called out of Ur in the land of the Chaldeans,
as it is briefly mentioned by Stephen; but this was the difference betwixt us,
he was called, I was forced out.
But as I was walking upon the common, the sense of my weak condition,
not knowing whither to go, nor where to lay my head, (although I had many friends,
yet I could not be free to go to them, unless I had known they had business for me,
being not of a forward, but rather backward and shy disposition,)--I say,
the sense and weight of my condition came over me to that degree,
that it appeared to me as though my way was hedged up on every side,
inwardly and outwardly.
I even thought myself like a pelican in the wilderness, or as an owl in the desert,
there appearing to me scarce a man in all the earth in my condition,
every way considered;
and in the sense and deep consideration of my present wilderness state,
I felt myself under a great oppression of spirit, and my heart seemed full,
like a bottle that wanted vent.
I looked round about me to see that none were near to see my tears, nor hear my cries,
and in the very anguish and bitterness of my soul,
I poured forth my complaints to the Judge of all the earth,
who spoke to me and comforted me in this my deplorable state,
which was worse than Jacob`'s, when he lay upon the ground,
and had a stone for his pillow; he had his near kindred to go to,
whom he might expect would receive him gladly, but I had none to go to,
but such as rather reviled me, and gave me hard language: but the Lord said to me,
as if a man had spoken, "`First seek the kingdom of heaven and the righteousness thereof,
and all these things that thou standest in need of shall be given unto thee.`"
I then desired he would please to shew me the place I should go to;
and the Lord opened my way, and shewed me the house I should go to,
and abide in for a time.
I said, "`Good is the word of the Lord.`"
I believed; and it was a great means to stay my mind, and settle it in the Truth,
with full purpose of heart to follow the Lord,
and obey his requirings according to the knowledge and ability given me.

--

[.asterism]
'''

Some circumstances connected with the early religious course of Richard Davies,
are of that interesting edifying nature,
as to come within the object and range of these short anecdotes.

He was early convinced by the power and grace of God,
that the religious views held by our Society, were agreeable to scripture,
and to the Truth as it is in Jesus.
He lived in North Wales,
and appears to have been one of the first of our
Friends raised up in that part of the country.
His usefulness was great in the gathered churches of Christ thereabouts,
especially in times of persecution.
The testimonies of his brethren, prefixed to his journal, are expressive of his worth,
an extract from one of which may suffice to shew in what
esteem such hardy labourers were held by their survivors:

[.embedded-content-document.testimony]
--

O the wonderful wisdom and love of God, who called him and many others in those days,
and prepared and qualified them for the great work he had to do,
and strengthened them to tread the way before us, that were weak and feeble!
O how strong, bold and valiant instruments did the Lord God prepare,
to begin to strike at the great image of pride, haughtiness, etc.,
that was then and yet is in the world!
Indeed their memorial is worthy to be recorded,
that ages yet to come might see what the Lord hath done for his faithful ones,
who gave up their lives, and all they had, on Truth`'s account.

--

[.offset]
The epitome which follows is of greater length than could in a general way be desired;
but being calculated to elucidate many points of our Christian testimony and practice,
and given forth by one who became a father to many,
even an apostle and bishop over the flock in that principality,
it did not seem well to abridge it.

[.embedded-content-document]
--

About the year 1656, our ministers told us, that there was a sort of people,
come up in the north, called Quakers,
that were a people of a strange posture and principles; saying to us,
it was the last days and times, that Christ spoke of in the 24th chapter of Matthew,
"`Many shall come in my name, and deceive many.`"
ver. 5. "`For there shall arise false Christs, and false prophets,
and shall shew great signs and wonders; insomuch that, if it were possible,
they shall deceive the very elect.`"
ver. 24. These sort of people called Quakers, were much preached against; +++[+++we were]
told they were the false prophets, etc., that they denied the scriptures,
and all ordinances, and also denied the very Christ that bought them.
They were represented to us to be such a dangerous sort of people,
that we were afraid of any who had the name of Quaker lest we should be deceived by them.
Hitherto they had not been in these parts of the country,
neither did we know what were the principles held out by themselves;
but only such as were reported, though falsely, unto us by our preachers and others:
which kept us in blindness, and from making further enquiry, and trying all things,
and holding fast that which is good, according to the apostle`'s advice.^
footnote:[1 Thess. 5:21.]

Now, about the year 1657,^
footnote:[Richard Davies being then about 22 years of age.]
there came a poor man, in a mean habit to my master`'s house, named Morgan Evan,
of South Wales: he had met with the people called Quakers in his travels,
and was convinced of the Truth.
This poor man discoursed with my master about the principles of Truth,
and I being in the shop about my calling, my mistress came to me and said,
"`Why do you not go out to help your master?
for there is a Quaker at the door that hath put him to silence.`"
I, hearing this, made haste, and took my bible under my arm,
and put on what courage I could, to dispute with that poor man;
but he proved too hard for us all.
When I went to them, they were upon the words thee and thou;
but I very peremptorily asked him, what command he had to speak thee and thou;
for I acknowledged to him it was the language of God to Adam,
and the language of the scripture; "`but,`" said I,
"`that is not enough for us now in this day, we must have a command for it.`"
To which he answered, "`Hold fast the form of sound words, which thou hast heard of me.`"^
footnote:[2 Tim. 1:13.]
I told him, we heard the Quakers denied the scripture, and that they would not read them.
He said, they were many false reports of them.
And truly, when he read the scripture so readily, I concluded in myself,
that what was reported of them was not true;
and he saw that he had reached to the witness of God in me.
Then he exhorted me to take heed to that light which shined in my heart,
and shewed me my vain thoughts, and reproved me in secret for every idle word and action;
saying, _that_ was the true light, which lighteth every man that cometh into the world,
John 1:9; and in that light, I should see more light,
and _that_ would open the scriptures to me,
and I should receive a measure of the same spirit which gave them forth;
and further he told me, it was the more sure word of prophecy,
unto which I did well to take heed, as unto a light that shineth in a dark place,
until the day dawn, and the day-star arise in my heart.^
footnote:[2 Peter 1:19.]
And he spoke much of the inward work,
and the operation of God`'s Holy Spirit upon the soul;
recommending me to the grace of God, that bringeth salvation, teaching us, that,
denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in this present world.^
footnote:[Titus 2:11-12.]
And so he departed from our house, and I set him along on his way.

Now when I came back from him, the consideration of his words took fast hold on me,
so that I could not go from under them;
and the more I waited in that light to which he recommended me,
the more my former peace,^
footnote:[Richard Davies was born a member of the Established Church,
but joined the Independents.]
and that in which I formerly took comfort, was broken: and herein I came to see,
that our former building could not stand,
for we built upon that which the apostle called wood, hay, and stubble.
Thus I came to a loss of all my former knowledge,
and my former performances proved but a sandy foundation.
Then I did, with much humility and poverty of spirit, beg of Almighty God,
that I might build upon that rock which the true church of Christ was built upon,
that the gates of hell might not prevail against me.

But I was afraid of being deceived by the Quakers: yet where to go, outwardly,
for advice or counsel I knew not.
So I desired that the God of Abraham, Isaac and Jacob, would be my teacher;
for I believed that the Lord would make a new covenant with his people now,
as he promised by the mouth of the prophet Jeremiah.^
footnote:[Ch. xxxi.
31, 32, 33, 34.]

The like precious promises I was made willing to take hold on,
and _waited for the fulfilling of them in myself_ and
of that which Christ said to the Jews,
"`It is written in the prophets, And they shall be all taught of God.
Every man therefore that hath heard, and hath learned of the Father, cometh unto me.`"^
footnote:[John ch.
vi.]
And it is said, "`All thy children shall be taught of the Lord,
and great shall be the peace of thy children.`"^
footnote:[Isa. 54:13.]

When I come to know a little of the teachings of the Lord,
I took my leave of all my former formal teachers,
and many times went into the woods and other byplaces, where none might see me,
to wait upon the Lord, where I was much broken and tendered by the power of God.
And though I began to see a little of myself, and something of the goodness of God,
still I was afraid of being deceived, for I had read and heard,
that Satan himself is transformed into an angel of light.^
footnote:[2 Cor. 11:14.]
I desired of the Lord that I might see this poor man once again,
for I knew not where to see the face of any called a Friend;
and it pleased God that he came again that way, and I +++[+++requested]
of my master and mistress to give him lodging, and that he might be with me,
to which they consented.
Then I queried of him their way of worship, and concerning those two great ordinances,
so called, that we so much relied upon, namely, the bread and wine, and baptism,
and respecting the scriptures,
to know what was their judgment of them;--to which he gave me some satisfaction.
In the morning I parted with him,
and to the best of my knowledge I saw him no more for several years.

In all this time I still kept my retirement in the wood, or some other private place;
and there in my waiting I desired of the Lord,
that I might be farther satisfied by himself as to those things: first,
whether the scriptures were the Word of God, as was said and preached unto us they were,
and the way to life and salvation.
Then the first chapter of John came under my serious consideration in my meditation.
I, with many more, was under that mistake the Jews were,
who thought they might have eternal life in the scriptures; whereas Christ saith,
"`Search,`" or, "`ye search the scriptures; for in them ye think ye have eternal life:
and they are they which testify of me.
And _ye will not come to Me,_ that ye might have life.`"^
footnote:[John 39, 40.]
As He is the life, so He is the way to the Father; "`I am the way, the truth,
and the life: no man cometh unto the Father but by me.`"^
footnote:[John 14:6.]
As for the scriptures, I was a great lover and a great reader of them,
and took great pleasure in searching them,
thinking _that_ would make me wise unto salvation; as Paul said to Timothy,
"`And that from a child thou hast known the holy scriptures,
which are able to make thee wise unto salvation,
through faith which is in Christ Jesus.`"^
footnote:[2 Tim. 3:15.]
This main thing was wanting in me, the true and saving faith, which is the gift of God.
"`For by grace ye are saved, through faith, and that not of yourselves:
it is the gift of God.`"^
footnote:[Eph. 2:8.]
So it is the _grace of God_ that brings salvation,
and not the bare historical knowledge of the scriptures.

Men may have a great literal knowledge of the scriptures, and yet remain in error,
because they know them not as they ought to do,
nor the power that was in the holy men that gave forth; as Christ said to the Jews,
"`Ye do err, not knowing the scriptures, nor the power of God.`"^
footnote:[Matt. 22:29.]
_That which gives the true knowledge of God,_
and a right understanding of the scriptures is therefore the power of God:
"`For,`" says the apostle, "`God, who commanded the light to shine out of darkness,
hath shined in our hearts, to give the light of the _knowledge_ of the glory of God,
in the face of Jesus Christ.`"^
footnote:[2 Cor. 4:6.]
And as men and women come to mind this light, that is, the Spirit of God, and to obey it,
they shall come to the comfort of the scriptures,
of which the same apostle speaks:--"`Whatsoever things
were written aforetime were written for our learning;
that we, through patience and comfort of the scriptures, might have hope.`"^
footnote:[Rom. 15:4.]

And being under a serious consideration of what I read in the sacred writings,
I believed the Spirit of the Lord to be the interpreter thereof.
Those great mysteries that were hid from ages and generations,
and are hid now in this our age from many, are come to be revealed by the Spirit of God.
And though formerly I read the scriptures as too many do,
without a true sense and due consideration, yet now, I can bless God for them,
and have great comfort in the reading of them; they being no more as a sealed book to me,
and many more, who wait for the assistance of God`'s Holy Spirit,
in all their duties and performances which the Lord requires of them:
for without Him we know that we can do nothing that is pleasing unto Him.
Formerly we ran in our own time and wills to preach and pray,
not having such a due regard to the leading and moving of the Spirit of the Lord:
but many times, when I arose from my knees in a formal way of prayer,
the reproof was very near me, "`Who required this at thy hands?
It is sparks of thy own kindling.`"
I was afraid that I should lie down in sorrow, as was said to some by the Lord,
in Isaiah 1, 11.

I had much reasoning and various consultations in my mind concerning +++[+++water baptism]
and the bread and wine.
And when I was satisfied as to those weighty concerns, I thought I might rest there,
and keep my old customs, and fashions, and language; but that would not do,
I had no peace therein: God shewed me the +++[+++vain]
customs of the nation, and +++[+++that]
our language +++[+++was]
not according to the language of God`'s people, recorded in the scriptures of Truth.
And withal I knew a little grammar,
and how it was improper to say _vos_ (you) to one single person, instead of _tu_ (thou).
I also believed that the Lord would return to his people a pure language in these days,
as was promised in the days of old concerning Israel; then,
when they returned to the Lord, he would bring them out of their captivity:
for thus saith the Lord, "`Then will I turn to the people a pure language,
that they may all call upon the name of the Lord, to serve Him with one consent.`"^
footnote:[Zeph. 3:9.]

Thus I was conscientiously concerned to speak the
pure language of thee and thou to every one,
without respect of persons, which was a great cross to me,
though it seems to some but as a weak and foolish thing;
yet when the Lord lays the necessity of speaking the truth to all,
in the language that God and all his servants used,
it comes to be of greater weight than many light airy people think it is.
This necessity being laid upon me, I spoke to my master in that dialect:
he was not offended at it because he was convinced of the truth of it,
and that it ought to be spoken to every one.
But when I gave it to my mistress, she took a stick,
and gave me such a blow on my bare head,
that made it swell and sore for a considerable time; she was so disturbed at it,
that she swore she would kill me, though she should be hanged for it;
though before that time she very seldom, if ever, gave me an angry word.
But I considered the enmity was between the two seeds,
and that "`that which was born after the flesh persecuted
him that was born after the Spirit.`"^
footnote:[Gal. 4:29.]
I being well satisfied of the Truth in myself, remembered Christ`'s words,
"`He that loveth father or mother more than me is not worthy of me.
He that findeth his life shall lose it:
and he that loseth his life for my sake shall find it.`"^
footnote:[Matt. 10:37. 39.]

The Almighty put it into my heart to consider the cost,
and that through tribulation I was to enter into the kingdom of heaven;
and I was faithful in this testimony that I had to bear.
I was much encouraged to go on in that strait and narrow way,
that God shewed me I was to walk in.
I also considered the saying.
"`Whosoever doth not bear his cross, and come after me, cannot be my disciple:`" again,
"`Which of you, intending to build a tower, sitteth not down first,
and counteth the cost, whether he hath sufficient to finish it?`"^
footnote:[Luke 14. ch.
27, 28.]
This consideration was weighty with me, lest I should begin to take up the Cross,
and to walk in this way, and should not be able to hold out to the end:
for the temptation of Satan, the lust of the flesh,
and the sinful customs and fashions of this world, were very prevalent;
and the weight and burden that was upon me was great,
having none in the country to be an help to me in the time of my exercise,
but the Lord alone, who hath promised to be with His people in all their troubles,
and that He would not leave them nor forsake them.
I was very ready and willing to take hold of His promises, and my prayers unto Him were,
that He would enable me to go through all things that He required of me.

I was now first called a Quaker, because I said to a single person Thee and Thou,
and kept on my hat, and did not go after the customs and fashions of the world,
that other professors lived and walked in:
though some of these would complain of their own formalities;
and were weary of the fashions of the world,
yet they did not take up their cross and leave them.
In thus doing I had great comfort from the Lord,
and did receive from Him living satisfaction and encouragement to go on in my way;
remembering the scripture that saith, "`The righteous shall hold on his way,
and he that hath clean hands shall be stronger and stronger`"^
footnote:[Job 17:9.]
I might also say with Job, "`But He knoweth the way that I take: when he hath tried me,
I shall come forth as gold.
My foot hath held his steps; his way have I kept, and not declined,
neither have I gone back from the commandment of his lips:
I have esteemed the words of his mouth more than my necessary food.`"^
footnote:[Job 23:10.]

The Lord kept me, and his people, very meek and low in our minds,
in a self-denying spirit: we waited for the living word,
that came with a living voice from him that speaks from heaven to us by his Spirit;
and the living voice is the voice of "`Christ in us, the hope of glory;`"^
footnote:[Col. 1:27.]
which voice we esteemed more than our necessary food.
For obeying this voice we come to be mocked and derided;
and they spoke all manner of evil against us, and hated us for his name`'s sake.^
footnote:[Matt. 10:22]
I remembered what Christ had told us in Luke 21:12,
"`They shall lay their hands on you and persecute you,
delivering you up to the synagogues, and into prisons,
being brought before kings and rulers for my name`'s sake,`" etc.
These and the like afflictions I was to meet with,
if I truly and faithfully followed the Lord Jesus Christ;
therefore I laboured to put on the whole armour of light,
that I might be able to withstand the fiery darts of the wicked one.

The rage of my mistress was not yet abated, though she had nothing against me,
but not conforming to the corrupt language and vain customs of the world:
for I laboured to keep a conscience void of offence, both towards God and man.
One time, when she thought it a fit opportunity to execute her cruelty,
she fell into a great rage, and I was freely given up to die that hour by her;
but the Lord was pleased to accept of my free-will offering,
and I may say with the apostle, that I counted not "`my life dear unto myself,
so that I might finish my course with joy.`"^
footnote:[Acts 20:24.]
And the Lord alone appeared for my deliverance,
and made her more moderate the rest of my servitude, it being less than two years;
and after I went away, the Lord visited her with a sharp fit of sickness,
in which time she spoke to her husband and those that were with her,
that she thought she should not die till she had asked me forgiveness,
and desired them to send for me if it were at London; and so they did:
I could freely forgive her, for _that_ I had done long since,
and I prayed to my heavenly Father that he might forgive her also.
I sent to her; and it pleased God to touch her with a sense of his love,
and lengthened her days,
she confessing oftentimes the wrong she had done to an honest careful young man,
as she said I had been,
who minded her husband`'s inward and outward good more than they themselves did.

About this time (1657) it was the great talk of the country, that I was become a Quaker.
My parents were much concerned about me.
I had not been yet with my father nor mother,
but waited for freedom and clearness in myself, and then I went to see them.
It was a trouble to them to see that I did not, as formerly,
go down upon my knees to ask their blessing, and bow to them and take off my hat.
My father soon turned his back upon me.
I had heard of his displeasure, and that he had said, he would leave me nothing;
saying to my relations, that they thought to have had comfort of me,
but now they expected none, but that I would go up and down the country, crying, Repent!
Repent!
Now, if my father should have cast me off upon such an account,
I was well persuaded it was for Christ`'s and the gospel`'s sake.
I remembered David`'s condition, when he said, "`Thou hast been my help; leave me not,
neither forsake me, O God of my salvation.
When my father and my mother forsake me, then the Lord will take me up.
Teach me thy way, O Lord, and lead me in a plain path, because of mine enemies.`"^
footnote:[Ps. 27:9 to 11.]

At length my mother came tenderly to me, and took a view of me, looking on my face,
and she saw I was her child, and that I was not, as they said,
"`bewitched or transformed into some other likeness;`"
which was reported of Quakers then,
and that they bewitched people to their religion, etc.
Thus they deceived them and many others with such strange stories,
and we were accounted "`deceivers, yet true.`"^
footnote:[2 Cor. 6:8.]
And when I discoursed with her out of the scriptures,
her heart was much tendered and affected with the goodness of God towards me;
she went to see for my father, and said unto him, "`Be of good comfort,
our son is not as was reported of him, we hope to have comfort of him yet.`"

A little after this,
I came to hear that some of the people that were called Quakers were at Shrewsbury,
being distant from the place of my abode about eighteen miles;
I waited for an opportunity to go to see them, and the way of their worship,
for as yet I had not seen any of them, but that one poor man before mentioned.
When the time called Christmas came, I got leave to go so far.
I went first to the house of John Millington, where many Friends resorted,
and they of the town came to see me in great love and tenderness,
and much brokenness of heart was among us, though but few words.
We waited to feel the Lord among us, in all our comings together.
When the first day of the week came, we went to a meeting at William Pane`'s,
and though it was silent from words, yet the word of the Lord was among us,
it was as a hammer and a fire, it was sharper than any two-edged sword,
it pierced through our inward parts, it melted and brought us into tears,
that there was scarcely a dry eye among us:
the Lord`'s blessed power over-shadowed our meeting, and I could have said,
_that God alone was master of that assembly._
The next day as I was preparing homewards,
having had a considerable time with Friends there,
and being much comforted with the goodness of God, and unfeigned love of the brethren,
we heard that John ap John was to have a meeting there: I stayed that meeting,
where I heard for the first time a Friend called a Quaker preach in a meeting;
and when I heard him, I thought he spoke as one having authority, and not as the scribes,
his words were so sound and piercing.

I came home to my master`'s house, where I was under many considerations,
and especially that of Christ`'s words, "`Ye are the light of the world.
Let your light so shine before men, that they may see your good works,
and glorify your Father which is in Heaven.`"^
footnote:[Matt. 5:14,16.]

And afterwards, the Lord required of me to go and give my testimony for Him,
and to warn a company of people to think of their latter end,
who were met to dance and to play, not far from my master`'s house;
When I came within the room where they were dancing, the fiddler ceased playing,
and they dancing; I declared the word of the Lord among them.
That which was chiefly before me was that of Job;
"`They send forth their little ones like a flock, and their children dance.
They take the timbrel and harp, and rejoice at the sound of the organ.
They spend their days in mirth, and in a moment go down to the grave.`"^
footnote:[Job 21:11. 13.]
When I had discharged myself of what lay upon me, I parted in love and peace from them,
and they thanked me for my good exhortation, and some of them came to set me home.
I continued, as the Lord made way for me,
to visit those in whom I found any inclination to the things that were good:
and there was one William Davies convinced of the Truth with me.

After this, I still waited to know the will and counsel of God,
and that he might direct me in my way, and order my steps in this my spiritual travel;
for had none to look unto but to Him alone,
who was all-sufficient to carry on the work which He had begun, though often by weak,
poor, mean, and contemptible instruments in the eye of the world.
Well might I say with the apostle,
"`But God hath chosen the foolish things of the world to confound the wise;
and God hath chosen the weak things of the world to confound the things which are mighty;
and base things of the world, and things which are despised, hath God chosen, yea,
and things which are not, to bring to nought things that are.`"^
footnote:[1 Cor. 1:27. 28.]

About this time I went to visit some young men,
my former companions in profession of religion; two or three of them were convinced,
and received the Truth.
When we were come to the number of four, it was with me,
that we ought to meet together in the name of the Lord;
for I remembered the promise of Christ, who said,
"`Where two or three are gathered together in my name,
there am I in the midst of them.`"^
footnote:[Matt. 18:20.]
So we all agreed to meet together, but none of us had a house of his own to meet in.
We determined therefore to meet on a hill in a common, as near as we could,
for the conveniency of each other, we living some miles distant.
There we met in silence, to the wonder of the country.
When the rain and weather beat upon us on one side of the hill, we went to the other side.
We were not free to go into any neighbours`' enclosures, for they were so blind, dark,
and ignorant, that they looked upon us as witches, and would go away from us,
some crossing themselves with their hands about their foreheads and faces.

Thus we continued for some time, till two of them left me, +++[+++to live elsewhere.]
The third was William Davies: and we met together for some time;
but one time he stayed longer than usual, and a dark spirit possessed him,
so that the little time we were together was not comfortable to me,
and when he had broke up the meeting, he asked me, by way of discourse,
"`How I did think we should stand in the face of the whole country?`"
I answered him with great zeal, "`The serpent, the serpent,
the same that beguiled the woman in paradise, hath beguiled thee,
_thou_ wilt not be able to stand;`" And while we were yet discoursing,
I saw my master coming, two women following him, the one was his wife my cruel mistress,
the other was his sister; they both had staves in their hands, and when they came to us,
my mistress began beating William Davies.
So his trial came very quickly,
and he came no more to meet with me nor any other Friends for many years.
It so happened that I had not a blow among them; and if I had received any,
I had learned of Christ Jesus, my Lord and Master,
to suffer patiently for His name`'s sake, and not to depart from Him, though my trials,
temptations and afflictions were not a few.

These young men going away thus, I was left alone again,
but still I kept waiting upon the Lord, to know his will concerning me;
and when the time of my apprenticeship was over, I found freedom to go to London,
to visit Friends there, which was in the year 1658-9;
and finding many good and living Friends there, I settled to my trade,
being a felt maker, and very well satisfied I was,
that I could go to meetings and follow my business.
When any thing would come to my mind of this my native country,
barren and uninhabited with Friends and Truth, I endeavoured to shut it out,
and to keep where I was, and I did what I could;
but all my fair pretences and reasonings would not do, disobedient to the Lord I was,
and trouble and sorrow and judgment from the Lord came upon me,
for not obeying his command, to go to my own country to stand a witness for Him there.
In this my disobedience I continued, till I lost His presence,
and He smote me with trouble within, and pain in my bones,
that I could not work nor labor.
In this time, Friends of London were very kind and careful of me,
and would freely have administered to me,
but I was not willing to accept any thing from them, so long as I had of my own.

My pain of body and spirit increased upon me,
till at last I was forced to bow to the will of the great God, who was too strong for me;
and reasoning with Him one night upon the bed of my sorrows, he shewed me clearly,
that I was to go to my own country; and I was made willing to give up to go,
if He would be pleased to let me know his will and pleasure by this sign and token,
_that he would remove my pain._
I also reasoned with him thus; that I was alone, like a pelican in the wilderness,
or a sparrow on a house-top.
The Lord still _commanded me to go,_ shewing _that He would provide an help-meet for me._
And when I had made a covenant with the Lord to go, _immediately my pain was removed,_
and I had _peace and quietness of mind and spirit._
I arose next morning, and went to my work; and when those tender Friends,
that had a regard for me in my sickness, came to see me that morning, I was gone to work;
which was to their admiration.

So the Lord gave me in a little time, and He alone provided, an help-meet for me;
for I prayed unto him; that she might be of his own providing,
for it was not yet manifest to me where she was, or who she was.
But one time, as I was at Horslydown meeting in Southwark,
I heard a woman Friend open her mouth,
by way of testimony against an evil ranting spirit,
that did oppose Friends much in those days.
It came to me from the Lord, that that woman was to be my wife,
and to go with me to the country, and be an help-meet for me.
I was very willing to let the Lord order it as it seemed best to himself,
and therein I was easy; and in time the Lord brought us acquainted one with another,
and she confessed she had some sight of the same thing, that I had seen concerning her.
I told her, if the Lord did order her to be my wife,
she must come with me to a strange country,
were there were no Friends but what God in time might call and gather to himself.
Upon a little consideration, she said, if the Lord should order it so,
she must go with her husband, though it were to the wilderness;
and being somewhat sensible of the workings of God upon her spirit in this matter,
she was willing to condescend in her mind to what He wrought in her:
but by hearkening to one who had not well weighed the matter,
she became disobedient to what God had revealed to her;
which brought great sorrow and trouble upon her.
I went to see her in this poor condition,
and I rested satisfied with the will of God in this concern,
being freely resigned to receive her as His gift to me; and after some time,
we waiting upon the Lord together,
she declared before me and the other Friend who had
begat doubts and reasonings in her mind,
that in the name and power of God she consented to be my wife,
and to go with me whither the Lord should order us; and I said,
"`In the fear of the Lord, I receive thee as the gift of God to me.`"

Under a weighty consideration which way to take each other in marriage,
we concluded to lay our proceedings before our elders,
and especially our ancient Friend George Fox,
(people in those days were married by a priest,
or before a justice,) and I told George Fox,
we thought to take each other into a public meeting:
so he desired the Lord to be with us.
And when we saw our clearness in the Lord, we went to the Snail meeting in Tower street,
London, in the morning; and in the afternoon to Horslydown, Southwark;
and in that meeting, in the presence of God and that assembly,
we took each other to be man and wife.

God alone knew our innocency and integrity in coming together.
It was not for gold, nor silver, nor any outward thing;
but to be serviceable to Him in our age and generation,
and to stand witnesses for Him and His blessed Truth, where He should send us.
Soon after, in the Lord`'s time, we made what haste we could to come to the country,
where we believed the Lord would have us to be, and we said, "`O Lord,
if thou wilt go with us in our way, and give us bread to eat and raiment to put on, then,
O Lord, thou shall be our God.`"^
footnote:[See Gen. 28:20.]
And the Lord was with us in all our journey,
and gave unto us His sweet and comfortable presence.

[.signed-section-signature]
_Richard Davies`' Journal_

--
