[quote.epigraph, , "Ps. 124:2, etc."]
____
If it had not been the Lord who was on our side, when men rose up against us,
then they would have swallowed us up quick; then the waters would have overwhelmed us,
the stream would have gone over our soul.--Our help is in the name of the Lord,
who made heaven and earth.
____

== Introduction

In presenting to the reader this volume of letters
and other documents of our early Friends,
the greater part of which, it is believed, have never been in print,
it may be proper for the editor to state,
that they are mostly taken from originals or ancient copies,
contained in various collections, as well private,
as those in the possession of the Society in London and in the country.
The principal collection of manuscripts from which they have been selected,
is that which is denominated by the editor, the Swarthmore Collection:
it formerly contained a very large number of original letters of the early Friends,
mostly addressed to Margaret Fell, before her marriage with George Fox in 1669,
but some few subsequently, and others to George Fox himself.
These manuscripts were probably kept together at
Swarthmore Hall in Lancashire for many years,
or at least till the decease of Margaret Fox in 1702;
but in the course of the last century, the collection became divided,
and eventually a large portion of it was presented to the Society in London.
The letters of this collection are mostly endorsed by George
Fox,--as any other mass of papers might be for convenience
of reference,--with the name of the writer and the date;
and occasionally a brief memorandum has been added by him,
respecting the writer or the chief subject of the letter.
They record the earliest Gospel services of Friends
in various parts of this country and in foreign lands;
and it is probable that they were referred to by George Fox,
in the following passage of his will:--"`All the passages, and travels,
and sufferings of Friends, in the beginning of the spreading of the Truth,
which I have kept together, will make a fine history; and they may be had at Swarthmore,
with my other books:
for it is a fine thing to know the beginning of the spreading of the Gospel,
after so long a night of apostasy since the Apostles`' days;--that now Christ reigns,
as he did, in the hearts of his people; glory to the Lord forever!
Amen.`"--(Will, dated eighth month, 1688.)

In the arrangement of this volume, the editor has adopted the following divisions,
under which it was found that the letters and documents might be suitably classed:--

Part I.--Historical,--or letters which illustrate the history of the Society of Friends,
as regards events, services, or sufferings, in London,
and in the country,--with some few relating to Ireland.

Part II.--Documents illustrative of the early discipline and testimonies of the society.

Part III.--Epistles of counsel and exhortation to the churches, etc.

The letters under the first division of the work,
and more especially those relating to London, the seat of government,
will be often found to possess much interest,
both as regards the history of our own Society,--in its earliest periods especially,--also
the state of the religiously professing part of the community,
and as regards the passing events of the day, so far as they concerned Friends.
As these letters are of the character of private or intimate correspondence,
due allowance should be made for the introduction of other matters,
which may be deemed of trivial importance; yet with some readers,
this description of familiar correspondence possesses attraction,
from the vivid glimpses sometimes presented by a writer on the spot or at the time,
of circumstances, and of character, not always noticed by the general historian.
At the same time the remarks and peculiarities of style of writers in a distant period,
will sometimes call for careful attention fully to appreciate them;
as they may refer to events or circumstances deemed to be well known in their day,
though at the first not so obvious to us: also, expressions may be met with,
peculiar to the times, which may seem somewhat strange to our modern ear.

The editor has endeavoured to elucidate these historical
letters by notes from other public sources;^
footnote:[Those sources of information, namely, the public histories, memoirs,
or chronicles of that day,
prove very scanty in notices respecting Friends:--as a body they seem in general
to have been little understood or even regarded by the writers of those works;
who, more frequently than otherwise perhaps, introduce erroneous statements,
or remarks founded on prejudice or ignorance respecting the Society.]
also by occasional quotations from our own authors:
but the reader will probably find much more in the early writers of the Society,
to which he might refer with interest, in connection with these letters,
and vice versa:--the order of dates in which they are placed,
will facilitate such reference.
The reader, in passing through these historical letters,
can scarcely regret more than the editor has done, the lack of similar correspondence,
during some, and more especially the latter periods embraced in this volume,
and respecting remarkable events in our history of that time,
which are not to be found alluded to in this collection.
In setting on foot a search--however diligent and extensive--for ancient
manuscripts in this day,--like casting a net into the sea of distant ages,--we
must be content with what we may be able to bring up.
Should, however, this publication remind Friends of any manuscripts of the kind,
yet laying dormant in their possession,
a communication with the editor thereon would be very acceptable.^
footnote:[Fac-similes of some of the signatures to the Letters are introduced;
they may assist in identifying originals,--which when accomplished,
is always satisfactory.]

The documents introduced under the second division of the volume,
respecting the early discipline of the Society, are both curious and valuable;--curious,
as being nearly all of them of dates antecedent to the existing records
of the established meetings of the Society in London;--and valuable,
as setting forth the care and concern of our early Friends,
under the direction and help of the great Head of the church,
in the first institution of our discipline; the principles and objects of which,
continue to a great degree remarkably preserved to this day,
for our edification and the Christian welfare of the body.^
footnote:[From the great rarity of our London records previous to the year 1666,
there is little doubt but that they were all destroyed by the great fire
of London;--for "`the great meetinghouse`" at the Bull and Mouth,
was burnt down at that time.
Alexander Parker, in a letter to George Fox, dated London, 27th of 9th month 1676,
states:--"`At Robert Dring`'s I inquired for Friends`' letters and papers,
which were written in the beginning of the spreading of Truth;
but I could find none,--they being burnt in the firing of London,
as Dorothy did say.`"
{footnote-paragraph-split}
The accounts of Sufferings,
commenced by Ellis Hookes,
appear to be the earliest records relating to the Society at large,
now preserved in London:--they go back as far as 1654.
The minutes of a meeting called the Six Weeks`' Meeting, which is continued to this day,
and has the care of the London meetinghouse property, etc.,
commence in 1671:--those of the Meeting for Sufferings in 1675,
(5th month;)--those of the Morning Meeting of Ministers and Elders, in the 7th month,
1673:--those of the Yearly Meeting commence in 1672:
and of the Yearly Meeting of Friends in Ireland, in 1671.]

The epistles of counsel, etc. in Part III are not so numerous, perhaps,
as might be desired; for such was the diligence and the zeal of our forefathers,
that they were not disposed to allow what appeared to them
to have a service in it for the cause of Truth,
to lie dormant:
thus a very large portion of writings of this description
were in that day published abroad,
for the encouragement and consolation of the churches and of individuals.
Here, therefore, the limits of search were rather restricted; yet it is hoped,
that some of these selected epistles believed to be now for the first
time printed,--will be truly acceptable to not a few readers in this day.
The letters and epistles of Alexander Parker, have been more largely taken,
as but few of the writings of that eminent Friend have come down to us in print.

The editor, in conclusion, may observe,
that he has abstained in general from giving his own reflections
upon the remarkable events and circumstances affecting our Society,
brought forward in these letters;
being desirous that the mind of the reader should be left at liberty,
to draw his own conclusions and reflections upon what is contained therein.
The extraordinary patience of these our early Friends,
under the cruel sufferings to which they were subjected,--their exemplary
faithfulness to the cause of Truth and righteousness,--and the earnestness
they evinced by their repeated warnings to the rulers of this country,
that the wrath of heaven might be averted from the nation,
by their ceasing from such wicked acts of persecution and cruelty,--and
remarkably displayed in the early history of our Society.
"`All the powers of the nation seemed banded together`" to crush this people;--the
legislature itself taking that object most resolutely in hand:
but they were not permitted to prevail over them.
How truly then might they reverently and gratefully adopt the language
of Israel formerly;--"`If it had not been the Lord,
who was on our side, when men rose up against us; then they had swallowed us up quick,
when their wrath was kindled against us: then the waters had overwhelmed us,
the stream had gone over our soul: Blessed be the Lord,
who has not given us as a prey to their teeth.
Our help is in the name of the Lord, who made heaven and earth.`"
May it be the earnest concern of us,
the too much degenerated successors--must it not be said--of these sons
of the morning--these patient sufferers for the cause of Christ,--to walk
also as good soldiers and faithful followers of the Captain of our salvation:
then may we not humbly trust, that the Lord, in his abundant mercy,
would show himself to be on our side also;--would be our strength, help,
refuge and glory, as He was theirs;--and there would be no lack to us of any good thing;
neither would anything be able to pluck us out of His preserving hand of power,
or to separate us from His love in Christ Jesus our Lord.

Abram Rawlinson Barclay.

Leytonstone, near London, Eleventh month, 1840.

=== Explanation of the Text

Words in the text, printed in Italics,--excepting in the case of titles of works,
and of remarkable expressions, etc.,--denote, that they are taken to be phrases,
probably, then in common use, or peculiar to the times.

Large brackets, thus +++[+++ ],
are used to denote introductory remarks or quotations by the editor: smaller brackets,
thus +++[+++ ], occurring in a letter or document, show the addition by him of words,
in explanation of the text;--if followed by a (?),
it implies uncertainty as to the correct deciphering of the original manuscript, or,
as to the word or name added by the editor, or,
that there is presumptive evidence or probability for the same.

A long dash, implies an omission; a short one,--as now used,--a rest in punctuation,
or to connect parts of long sentences, etc.

In using the phrase at the end of a letter, etc., +++[+++From the original,]
it is of course intended that the manuscript letter is pronounced to be such,
on the usual presumptive evidence of comparison, or repeated view,
of other letters of the same writer, also from other obvious marks of originality,
as post marks, seals, etc.
