[short="Part II. Early Discipline and Testimonies"]
== Part II. Documents Illustrative Of The Early Discipline And Testimonies Of The Society.

[.centered]
=== No. CXII.

+++[+++The documents brought forward under this division of the work,
are almost wholly of dates antecedent to the records
of the established meetings of the Society at large,
held in London:
they will be found to possess much interest and value,--evincing
the earnest concern and holy care of our Early Friends,
in the first establishment of the Christian Discipline of the Society.
It is remarkable how large a portion of the subjects of advice or of regulation,
set forth in these early documents,
have continued to this day to be acknowledged or maintained
among us as a religious body:--the wisdom of Truth,
it is believed, was at the outset closely sought after,
in the building up of the edifice,--the only true foundation of which,
was often testified, and reverently owned, to be Christ,--the head of the church;
and His Spirit the cementing bond of union, of edification,
and the only right authority therein.

In some matters of disciplinary regulation, variations or modifications are observable,
(as would be expected,) when compared with the regulations of after times;
but the directing principle of Truth, it is believed,
was the warrant with our Early Friends for those subsequent modifications: the changes,
however, were but few and comparatively slight,
after the more general settlement of the several meetings for discipline,
including those of Women Friends and of Ministers and Elders, throughout the Society,
towards the close of the seventeenth century, or between the years 1670 and 1690.

The following interesting document on the subject of our early discipline,
is copied from an ancient manuscript in Thomas Aldam`'s
handwriting (apparently,) found in the Warmsworth Collection.
As it bears no date, neither signature, it is difficult to speak with confidence,
as to the period in which it was issued, or by what body or meeting of Friends;
but from the expression--"`serving the Commonwealth`" being used,
(a state term doubtless generally avoided after the restoration of the Stuarts,)
it is probable that the document was drawn up in the time of one of the Cromwells,--a
period very ancient as respects disciplinary records in the Society;
on that account, the editor places it the first in this part of the volume.
It is within the verge of probability,
that it was a paper issued by the General or yearly Meeting,
held at John Crook`'s house in Bedfordshire in the year 1657, to Friends in the North.]

[.blurb]
=== The Elders and Brethren send unto the brethren in the North these necessary things following; to which, if you, in the light wait to be kept in obedience, you will do well. Fare you well.

[.numbered-group]
====

[.numbered]
1+++.+++ That the particular meetings, by all the children of the light,
be duly kept and observed, where they be already settled, every first-day of the week;
except they be moved to other places.
And that general meetings be kept in order and sweet in the life of God,
on some other day of the week than on the first-day,
unless there be a moving to the contrary: that so in the light and life,
the meetings be kept, to the praise of God.

[.numbered]
2+++.+++ That care be taken, that as any are brought into the Truth,
meetings be in such places among them, as may be for the most convenience of all,
without respect of persons: and that hands be laid on none suddenly,
lest the Truth suffer.

[.numbered]
3+++.+++ That if any person draw back from meetings, and walk disorderly,
some go to speak to such as draw back; to exhort and admonish such with a tender,
meek spirit, whom they find negligent or disorderly.
And if any, after admonition, do persist in the thing not good,
let them again be admonished and reproved before two or three witnesses;
that by the mouth of two or three witnesses, everything may be established.
And if still they persevere in it, then let the thing be declared to the church:
and when the church has reproved them for their disorderly walking,
and admonished them in the tender and meek spirit, and they do not reform,
then let their names and the causes, and such as can justly testify the truth therein,
and their answers,
be sent in writing to some whom the Lord has raised
up in the power of his Spirit to be fathers,
His children to gather in the light,--that the thing may be known to the body;
and with the consent of the whole body, the thing may be determined in the light.

[.numbered]
4+++.+++ That as any are moved of the Lord to speak the word of the Lord at such meetings,
that it be done in faithfulness, without adding or diminishing.
And if at such meetings,
anything at any time be otherwise spoken by any out of the light,
whereby the seed of God comes to be burdened;
let the person or persons in whom the seed of God is burdened,
speak in the light (as of the Lord they are moved,) in meekness and godly fear, to him;
but let it be done in private, between them two,
or before two or three witnesses and not in the public meetings,
except there be a special moving so to do.^
footnote:[It will be seen by a subsequent document,
how earnest was the advice (afterwards) of the General Meeting in London,
against judging or reflecting on the ministry publicly.]

[.numbered]
5+++.+++ That collections be timely made for the poor, (that are so indeed,) as they are moved,
according to order,--for relief of prisoners, and other necessary uses,
as need shall require: and all moneys so collected, an account thereof to be taken;
from which every need may be supplied, as made known by the overseers in every meeting:
that no private ends may be answered, but all brought to the light,
that the gospel be not slandered.

[.numbered]
6+++.+++ That care be taken for the families and goods
of such as are called forth into the ministry,
or who are imprisoned for the Truth`'s sake;
that no creatures be lost for lack of the creatures.

[.numbered]
7+++.+++ That as any are moved to take a brother or a sister in marriage,
(marriage being honourable in all,
and the bed undefiled,) let it be made known to the children of the light,
especially to those of the meeting of which the parties are members;
that all in the light may witness it to be of God.
And let them be joined together in the Lord and in His fear,
in the presence of many witnesses;
according to the example of the holy men of God in the Scriptures of Truth recorded,
(which were written for our example and learning;)
that no scandal may rest upon the Truth,
nor anything be done in secret; but all things brought to the light,
that Truth may triumph over all deceit;
and that they who are joined together in the Lord, may not by man be put asunder,
whom God has joined together.
That there may be a record in writing, witnessing of the day, place, and year,
of such things, kept within that meeting, of which the one or both of them are members;
under which writing the witnesses present may subscribe their names,
or so many of them as be convenient; for the stopping of the mouths of gainsayers,
and for the manifesting the truth to all who are without.

[.numbered]
8+++.+++ That a record be kept in every meeting of the births
of the children of such who are members of that meeting,
and of the burials of the dead (who die in the Lord,) as they depart out of the body;
which be done after the manner of the holy men of God,
recorded in the Scriptures of Truth; and not after the customs of the heathen,
who know not God.

[.numbered]
9+++.+++ That husbands and wives dwell together according to knowledge,
as being heirs together of the grace of life.
That children obey their parents in the Lord;
and that parents provoke not their children to wrath,
but bring them up in the nurture and fear of the Lord,
walking before them as good examples, in gravity and godliness;
providing things honest in the sight of God and man.

[.numbered]
10+++.+++ That servants be obedient to them that are their masters in the flesh,
in things that are good, in singleness of heart as unto Christ; not with eye-service,
as men-pleasers, but as the servants of Christ; doing the will of God from the heart:
with good-will doing service as to the Lord, and not to men;
knowing whatsoever good thing any man does, the same shall he receive of the Lord,
whether he be bond or free.
And that masters give to their servants that which is just and equal;
forbearing threatening, knowing that their Master is also in heaven;
neither is there respect of persons with Him.

[.numbered]
11+++.+++ That care be taken that none who are servants depart from their masters,
but as they both do see in the light: nor any master to put away his servant,
but by the consent of the servant:
and if any master or servant in their wills do otherwise,
it is to be judged with Friends in the light.

[.numbered]
12+++.+++ That the necessities of the poor, widows and fatherless, may be truly supplied,
and that such as are able to work, and do not, may be admonished: and if,
after admonition, they refuse to work, then let them not eat.
And that the children of such as are in necessity, be put to honest employment;
that none be idle in the Lord`'s vineyard.

[.numbered]
13+++.+++ That care be taken, that as any are called before the outward powers of the nation,
that in the light, obedience to the Lord be given.

[.numbered]
14+++.+++ That if any be called to serve the commonwealth in any public service,
which is for the public wealth and good, that with cheerfulness it be undertaken,
and in faithfulness discharged unto God:
that therein patterns and examples in the thing that is righteous, they may be,
to those that be without.

[.numbered]
15+++.+++ That all Friends that have callings and trades, do labour in the thing that is good,
in faithfulness and uprightness;
and keep to their yes and no in all their communications:
and that all who are indebted to the world, endeavour to discharge the same,
that nothing they may owe to any man but to love one another.

[.numbered]
16+++.+++ That no one speak evil of another, neither judge one against another;
but rather judge this,
that none put a stumbling-block or occasion to fall in his brother`'s way.

[.numbered]
17+++.+++ That none be busy bodies in other`'s matters,
but each one to bear another`'s burdens, and so fulfill the law of Christ;
that they be sincere and without offence, and that all things which are honest,
be done without murmurings and disputings: that they may be blameless and harmless,
the sons of God without rebuke, in the midst of a crooked and perverse nation,
among whom they may shine as lights in the world.

[.numbered]
18+++.+++ That Christian moderation be used towards all men; that they who obey not the word,
may be won by those that in the word dwell, to guide in a holy life and godly conduct.

[.numbered]
19+++.+++ That the Elders made by the Holy Spirit, feed the flock of God,
taking the oversight thereof willingly, not by constraint, but of a willing mind;
neither as lords over God`'s heritage, but as examples to the flock of Christ.

[.numbered]
20+++.+++ That the younger submit themselves to the elder,--yes, all be subject one to another,
and be clothed with humility; for God resists the proud, but gives grace to the humble.

====

[.small-break]
'''

From the Spirit of Truth to the children of light, to walk in the light;
that all in the order be kept in obedience to God that He may be glorified,
who is worthy over all, blessed forever--Amen!

Dearly beloved Friends, these things we do not lay upon you as a rule or form to walk by;
but that all, with a measure of the light, which is pure and holy, may be guided:
and so in the light walking and abiding, these things may be fulfilled in the Spirit,
not in the letter; for the letter kills, but the Spirit gives life.^
footnote:[There is in this brief concluding paragraph, something remarkably instructive:
the true spirit of our church discipline, not the letter of it,
is upheld,--reference being made to the only right authority of it,
instead of to any outward sanction or authority.]

[.centered]
=== No. CXIII.

+++[+++This next early record was discovered in a register book of a monthly meeting in Hampshire,
since the last document was prepared for the press.
It is dated 1659,
and contains portions of advice similar to those in the preceding article,
and occasionally so in the same words: thus proving that some general advice of the kind,
had been issued from some influential body or meeting of the Society,
at or previous to that early period.]

[.blurb]
=== At a meeting of Friends of four counties, Kent, Sussex, Surrey and Hampshire, at the Lodge near Horsham, these as follows were judged necessary by Friends there met, and by them owned, and tendered as their counsel and advice unto all Friends in those places.

[.signed-section-context-open]
The Third Month, 1659.

[.numbered-group]
====

[.numbered]
1+++.+++ That all Friends at their several meetings in the aforesaid counties,
do make their collections orderly and timely for the use of the poor,
or such other necessary uses that shall be seen in the wisdom
of God to be serviceable for the good of the body:
and what is remaining over in the particular, to be brought into the general stock,
at the general meeting in each county, to them entrusted for the whole.

[.numbered]
2+++.+++ That all Friends intending marriage,
or witnessing a motion of the Lord unto that thing,
(before they go outwardly together,) bring it to
the body or that church to which they are joined;
that all in the power of the Lord may feel,
and in that particular nothing be done hastily or rashly, but in the fear of the Lord;
and in the presence of many witnesses they may be united,
according to the example of the holy men of God in the Scriptures of truth recorded;
so that no scandal or blemish may be laid upon the Truth,
but all to the light may be brought, which makes manifest deceit;
and that a record in writing of the day, place, and year of such things,
be kept within that meeting, whereof one or both are members;
under which the witnesses may set their names, or some of them.

[.numbered]
3+++.+++ That a record be kept (as Friends are moved) of the births
of children of such as are members or Friends,
and of the burial of the dead who die in the Lord,
(as they departed out of the body;) which be done after
the manner of the holy men of God recorded in the Scriptures,
and not after the custom of the heathen that know not God.

[.numbered]
4+++.+++ That burying places be provided as soon as conveniently may be,
in convenient places distinct from the world, as Friends are moved in it.

[.numbered]
5+++.+++ That if any person or persons draw back from the Truth and walk disorderly,
some to speak to such as draw back,
to exhort and admonish such with a tender and meek spirit,
whom they find negligent and disorderly;
and if any person or persons after admonition persist in the thing not good,
let them be again (as moved) admonished, and before two or three witnesses reproved,
that by the mouth of two or three witnesses everything may be established;
and if still they persist and come not to the Truth,
then let the thing be delivered to others that be in the Truth,
that it may be known to the body, and with the consent of the whole,
in the light be determined; and that nothing be done in haste or rashly.

[.numbered]
6+++.+++ That a tender care be taken of all such children, wives, servants, soldiers,
or others, who are turned out of their places and families, for the Truth`'s sake.
And that all single persons, men and women,
(who are not called forth in the public or general service in the
work of the Lord,) be ordered in the wisdom of God to several places,
whereby they may glorify God in their conversations,
and the Truth may be preserved by them without blemish, and them in it;
that all Friends may be kept in duty.

[.numbered]
7+++.+++ That all Friends in their several places (as they are moved,) observe
their general and particular meetings on the first-days and others,
(except any of them be moved forth by the Lord unto
some other places for the furtherance of Truth,
as in the wisdom of God shall be seen and judged serviceable, or just cause showed,
if desired, to the contrary;) for they who forsake the assembly of saints lose the unity.

[.numbered]
8+++.+++ That if any be moved of the Lord to speak in the steeple houses, streets, markets,
meetings, or beyond the seas, they are not to quench the Spirit of the Lord;
and that no Friends judge one another in meetings; but if any be moved to speak to such,
to do it after meeting in private.
And all Friends take heed of slothfulness and sleeping in meetings;
but live in the power of the Lord, that you may be kept in the unity:
that all things that are done, may be, in the moving power of the Lord God,
and nothing out of it.

====

[.blurb]
=== An addition of Friends who met together from the counties aforesaid, since the said meeting in the third month, 1659.

[.numbered-group]
====

[.numbered]
1+++.+++ That care be taken that all sufferings of Friends,
who suffer for conscience and Truth`'s sake, of what nature or kind soever,
be from time to time gathered up and recorded;
and to that end some Friends of every meeting convenient, be desired to record the same;
and that such Friends who suffer as aforesaid, do bring the whole matter,
with all material circumstances, speedily to him who is to record the same:
and that all such records of sufferings as aforesaid,
be by him returned at the next general meeting of Friends for that county,
there to be recorded in general for the whole county,
by him who is desired to record the same.

[.numbered]
2+++.+++ That if collections be made in the several counties as aforesaid,
and if the money collected in every particular county is
not sufficient to supply the necessity in the same county,
that then the other of said counties, who have any collections in the general stock,
do contribute towards the necessity of that county or counties which is in need.

====

[.offset]
The names of Friends met together the third month 1659, above-mentioned, namely,

+++[+++Then follow the names of many Friends arranged under the four counties of Kent, Sussex,
Surrey, and Hampshire.
While the above was in type, the following documents were met with,
among our ancient records in London, which, from their very early date and rarity,
are curious, and their contents interesting.]

[.blurb]
=== At a meeting of Friends out of the Northern counties of York, Lincoln, Lancaster, Chester, Nottingham, Derby, Westmoreland, Cumberland, Durham, and Northumberland, at Scalehouse +++[+++the district of Richmond Monthly Meeting] the 24th of the fourth month, 1658.

Having heard of great things done by the mighty power of God,
in many nations beyond the seas,
where He has called forth many of our dear brethren and sisters,
to preach the everlasting Gospel; by whom he has revealed the mystery of His Truth,
which has been hid from ages and generations, who are now in strange lands,
in great straits and hardships,
and in the daily hazard of their lives:--our souls yearn for them,
and our hearts are filled with tender love to those precious ones of God,
who so freely have given up for the Seed`'s sake, their friends, their near relations,
their country and worldly estates, yes, and their own lives also;
and in the feeling we are have of their trials, necessities and sufferings,
we do therefore in the unity of the Spirit and bond of Truth, cheerfully agree,
in the Lord`'s name and power,
to move and stir up the hearts of Friends in these counties,
whom God has called and gathered out of the world, with one consent,
freely and liberally, to offer up unto God of their earthly substance,
according as God has blessed everyone,--to be speedily sent up to London,
as a free-will offering for the Seed`'s sake:
that the hands of those that are beyond the seas in the Lord`'s work,
may be strengthened, and their hearts refreshed, from the love of their brethren.
And we commit it to the care of our dear brethren of London, Amos Stoddart,
Gerrard Roberts, John Boulton, Thomas Hart and Richard Davis,
to order and dispose of what shall be from us sent unto them,
for the supply of such as are already gone forth,
or such as shall be moved of the Lord to go forth, into any other nation;
of whose care and faithfulness we are well assured.

And such Friends as are here present,
are to be diligent in their several counties and places;
that the work may be hastened with all convenient speed.

[.signed-section-closing]
Signed by many Friends; among them are,

[.signed-section-signature]
Thomas Aldam, John Killam, Thomas Bewley, Thomas Taylor, Marmaduke Storr, John Richmond,
William Smith.

[.offset]
+++[+++The next document is addressed simply as follows:--]

[.salutation]
Brethren and Friends,

It having pleased God, in his marvellous love,
in these latter days to reveal the mystery of his gospel,
which has been hid from ages and generations, and to make manifest his glorious Truth,
which has been long lost in the dark night of apostasy,
since the days of the Apostles,--and chosen England before all the nations of the world,
as the land of his delight, and to bring forth many thousands therein,
(as a kind of first fruits to the glory of his name,) unto whom He has given to see
those days that many righteous souls long waited for and thirsted after;--let us all,
in the simplicity of Truth,
(which at the first was made manifest to us,) abide and dwell,
and in the liberty with which Christ Jesus has made us free, stand fast;
that we be not again led back into the errors of those that went before us,
who left the power and got into the form,
who brought in that darkness which has so long covered the face of the earth,
that no footsteps may be left for those that shall come after, or to walk by example:
but that all they may be directed by and left to the Truth, in it to live and walk,
and by it to be guided: that none may look back at us, nor have an eye behind them;
but that all may look forward,
waiting in the Spirit for the revelation of those glorious things,
which are to be made manifest to them.

It is needful that we call to mind, how long, and in what manner,
the world has been distracted and divided about those things which the Apostles practised;
and what sad calamity (besides the loss and departure
from the Truth) has come upon many nations,
about forms and ways of discipline and government of the
church (so called;) some saying the Apostles made bishops,
and gave them power, and they ordained Elders: others saying, no,
it was by the laying on the hands of the presbytery;
and others pleading it was the election and choice of the churches.
And how have men gathered themselves into forms and sects,
according to their various persuasions;
and how are others setting up committees to approve and send forth preachers,
and give them maintenance, seeing into the errors of the former:
but all being ignorant of the life, or of the true power.
And thus have men usurped one over another,
and intruded into those things they understood not; and by human policy and invention,
set up a carnal, worldly religion and worship,
which has for many hundred years overspread the whole face of the earth.

Therefore, in love and tenderness, and in the fear of the Lord, we exhort,
that we may all in the unity of the Spirit, dwell in the pure wisdom,
which is from above;
which comprehends that which would lead out to the setting up persons or things:
that the power of the Godhead may be known in the body,
in that prefect freedom which every member has in Christ Jesus;
that none may exercise lordship or dominion over another,
nor the person of any be set apart, but as they continue in the power of Truth.
And that none exercise any authority,
but such to whom it is freely given in the Lord for the good of the body;
that all the world`'s images and ways, and forms and sects,
may be condemned and confounded; and the glory of Christ`'s body made manifest,
in that wisdom and in that power, which the world cannot comprehend;
that Truth itself in the body may reign, not persons nor forms:
and that all such may be honoured, as stand in the life of the Truth;
wherein is the power, not over, but in, the body;
that our path may be as the way of a ship in the sea,
which no deceit can follow or imitate.

That for the better ordering of the outward state of Friends,
in all relations in and to the world and to one another,
in wisdom and as becomes the Truth,
and for making collections for the needs of the church,--let as many particular meetings,
or some Friends from each of them that are near, and can conveniently,
meet together once a month, or as occasion shall require:
and as many of such Monthly Meetings,
or some Friends from each of them in the northern parts of England,
as can conveniently come together in a General Meeting twice or thrice in a year,
or as occasion requires, be joined and united:
and that we may not tie up ourselves to the world`'s limits of counties and places;
but join together as may conduce to the union and fellowship of the church,
and to the mutual help of one another in the Lord;
and we wish the like may be settled in all parts, and one General Meeting of +++[+++or for]
England.

That for the supplying the needs of the church, and relieving such as are in need,
it may be laid upon Friends in every meeting to take care of their own poor;
to supply such as are aged and infirm in body;
to provide employment for such as lack work,
or cannot follow their former callings by reason of the evil therein;
and to help such parents for the education of their children,
as have more than they can maintain: that there may not be a beggar among us,
nor any whose soul need be oppressed with care for food or raiment.
And where Friends of one meeting are overburdened,
and under a greater charge than they can bear, that Friends at each Monthly Meeting,
take care to contribute to their assistance.

That Friends at each Monthly Meeting do take care to provide
supply for such as are in the ministry among them,
where there is need; as also for the relief of Friends in prison, or any other,
suffering for the Truth`'s sake, according to their several needs;
and to make collections from time to time for the same.

And where Friends of any Monthly Meeting are under
a greater charge and burden than they can well bear,
the General Meeting of Friends in the North to take care to contribute to them;
that we may all bear one another`'s burdens, and walk in love as becomes brethren.

That all collections made by any particular meeting, be paid to such hands,
and disposed to such ends, as Friends of that Meeting shall appoint;
and the same likewise to be observed by each Monthly Meeting with their collections;
and the like also by Friends of the North, at their General Meetings:
that the true power of the whole body, and of every part thereof, may be preserved;
that every member may act in its own freedom, and every meeting in its own authority,
as part of that body which Christ Jesus has set free.
And none to usurp over another; but let him that would be greatest, be servant unto all:
that as Friends according to their freedom do contribute,
they may be also satisfied it is laid out by the power and
in the wisdom of the body to whom they commit it.

That all collections made by Friends at their Monthly Meetings,
as also at their General Meetings, be for the needs of the churches in general,
and not limited for those only that are in the ministry; who will be as much grieved,
as others offended, to have a maintenance or hire raised on purpose for them.

That for the more clearness of Truth, and satisfaction of Friends,
two or more persons be still appointed in all trusts about moneys,
and be privy to all receipts and disbursements;
that the innocency of the upright may be known, and all deceit be prevented.

That all Friends that receive any collections, do from time to time,
make account to Friends of the particular meeting, Monthly Meeting or General Meeting,
by whom they were entrusted; and in order thereunto,
that a note under two or more hands be sent out of every county,
with such collections as are appointed by the General Meeting, to be produced,
together with an account how it has been disbursed at the next General Meeting,
together with an account how such are entrusted therewith;
and that particular notes from every Meeting,
under two or more hands be sent with their collections to such persons
as are appointed by the Monthly Meeting to receive the same,
to be produced together with the account how it has been discharged,
at the next Monthly Meeting after: and after every account so made and cleared,
all papers to be concealed, and no further remembrance thereof to be had,
which may beget many offences in future time, but cannot be of any service to the Truth.

Dear Friends, these things being agreed and +++[+++_word indistinct_]
in clearness of Truth, which hitherto have taken up much time at the General Meetings,
to the loss of many precious opportunities,--you will see greater things before you,
which more chiefly concern the state of the church,
and will be of greater service to the Truth;
as our Friends who bring this from us may lay before you,
as there is freedom and opportunity.

[.signed-section-context-close]
From Friends met together at Durham, from
several Meetings in and adjoining to the
county of Durham, the 1st day of the eighth
month, 1659; to Friends who shall meet together
out of the several Northern Counties, at Skipton, the 5th of the eighth month, 1659.

[.offset]
+++[+++Signed by twenty names; among them, Anthony Pearson, Richard Wilson,
Christopher Richmond, etc.]

[.small-break]
'''

[.postscript]
====

This letter was presented and read at the General Meeting at Skipton,
the 5th day of the 8th month, 1659; and was by all Friends owned and approved,
and agreed to be observed; and copies thereof to be sent to all Monthly Meetings:

====

[.signed-section-signature]
Thomas Killam, Samuel Watson, Henry Ward, William Gandy.

[.offset]
+++[+++_This document is endorsed_
"`To Thomas Doudney, at the Bell Savage in London, deliver this;
and for him to give or send it to George Fox, with speed and care to be delivered to him,
where he is.`"]

+++[+++Another document of a similar kind recommends a collection
to be raised for the service of Truth abroad,
dated from the General Meeting, held at Skipton, the 25th day of the second month, 1660;
it commences thus:]

[.salutation]
Dear Friends and Brethren,

We having certain information from some Friends of London,
of the great work and service of the Lord beyond the seas, in several parts and regions,
as Germany, America, and many other islands and places, as Florence, Mantua, Palatine,
Tuscany, Italy, Rome, Turkey, Jerusalem, France, Geneva, Norway, Barbados, Bermuda,
Antigua, Jamaica, Surinam, +++[+++?]
Newfoundland; through all which, Friends have passed in the service of the Lord,
and various other countries, places, islands and nations;
and among many nations of the Indians, in which they have had service for the Lord,
and through great travails have published His name,
and declared the everlasting gospel of peace unto them that have been afar off,
that they might be brought near unto God.`" etc.

[.small-break]
'''

+++[+++A collection is then recommended in every particular meeting,
to be sent "`as formerly to London, for the service and use aforesaid.`"]

[.centered]
==== CXIV.

[.blurb]
=== A testimony concerning the beginning of the work of the Lord, and the first publication of Truth, in this city of London; and also concerning the cause, end, and service of the first appointment and setting up of the Men`'s Meeting at the Bull and Mouth; that it may be known to all perfectly, how the Lord has begun and carried on His work to this day.

+++[+++This highly interesting document, signed by Edward Burrough, and dated 1662,
is taken from a collection of copies of letters and papers, in four folio volumes,
entitled [.book-title]#John Penington`'s Collection of his Father`'s Manuscripts,#
and preserved in London.
These volumes,
(which are very closely written) contain a large
number of Isaac Penington`'s letters and papers;
many of them have at different times been published.

The editor is not aware that the document in question has ever
been printed or referred to in any treatise upon our early discipline:
it is not only valuable as an ancient record, but very instructive.
Respecting the primitive meeting alluded to, held at the Bull and Mouth, London,
William Crouch gives us the following account:

"`After the taking of the house called Bull and Mouth, for a meeting place, as aforesaid,
the ancient men Friends about the city, did sometimes meet together,
to the number of eight or ten,
(sometimes a few more added,) in an upper room belonging to the place;
there to consult about, and consider of the affairs of Truth;
and to communicate to each other what the Lord opened in them, for the promotion thereof;
and also to make such provision to supply all necessary occasions,
which the service of the church might require.
And now also, some ancient women Friends did meet together,
to consider of what appertained to them, as their most immediate care and concern;
to inspect the circumstances and condition of such who were imprisoned on Truth`'s account,
and to provide things needful to supply their needs:
and what did or might more immediately concern men Friends,
the women would acquaint them therewith:
and all was done in great love and unity;--no jar
or discord among them,--no repining or murmuring;
but a sweet harmony and agreement was preserved in all things.
These women did also inquire into and inspect the needs and necessities of the poor,
who were convinced of the Truth: and they sat not still,
until the cry of the poor came to their houses;
but when they did suppose or discover a need for help,
their charity led them to inquire into their conditions,
and to minister to their necessities.
And thus things were carried on with cheerfulness and brotherly kindness,
in the infancy of the church: all whisperings and backbitings were shut out,
and love and good will to all were promoted and cherished.
And afterwards as Truth grew and prospered, and many came to be added to the faith,
the meetings came, through the Providence of God,
to be settled in order and method as at this day.`"--[.book-title]#Memoirs of William Crouch,# Sect.
III.]

[.blurb]
=== A Copy of the Testimony

It having pleased the Lord God of heaven and earth,
by his Spirit and power to move the hearts and spirits of several of us,
the ministers of his everlasting Gospel of truth and salvation,
to come to this great city of London, to publish and declare the message of eternal life,
which we had received power from the Father to do;
that people might be warned of the day of their visitation,
and turned from darkness to the light, and from Satan`'s power to God,
and be converted to the knowledge of the way of salvation, that their souls might live;
for our testimony was and is the same,
as ever was held forth by the holy prophets and apostles of old.
To which moving of the Lord in us, we were obedient; and though in much weakness,
and not without many trials, tribulations, and difficulties, we entered this city,
and as the wisdom of God prepared our way,
we began to publish and declare the things of the kingdom of God,
as we had received the gift thereof,
in power and authority,--to the wounding and piercing of many consciences,
and to the quickening and awakening the witness of God in many hearts,
as is well known to the faithful this day.

And though we met with, and were exercised in,
many trials and much opposition from men of all conditions; yet we were not discouraged,
nor of fearful hearts, nor fainting in the work of the Lord, nor overcome by oppositions;
but we went on in boldness and confidence in God,
holding forth the perfect way of salvation to all, both by doctrine, practice,
and conduct; which have been to this day,
every way according to the ancient and true gospel of peace, and there is not any other.
And we being carried on in faithfulness to this work,
unto which we were thus called and ordained,
it pleased the Lord to bless us and prosper his work in our hands;
and our labour and travails were successful,
to accomplish the good and happy end of converting and turning many to the Lord,
and to walk in his way of truth and peace;
wherein they found perfect rest and peace to their souls,
and assurance in his mercies forever, through faith in the gospel held forth by us.
The Spirit of the Father does testify this in the hearts of many in this city,
in whom the seed of God is raised up by his power,
by the ministry of Christ sent unto them; insomuch that they with us,
are now both partakers of the grace, love, wisdom,
and inheritance of the everlasting Father; and have no master but Christ,
and are all brethren;--no lord nor commander, no shepherd, nor preserver,
but the Lord Jesus Christ alone; and he is become all in all unto us all,
who have believed and received him, and are gathered into his fold,
and born of his seed elect, which is blessed forever.

And though some few of us were at first particularly
called and chosen of God to this work,
and have been instruments to publish his name,
and preach his gospel in this city these several years;
and the Lord by us has gathered many people to himself, to know him,
and be taught of him, according to his covenant of promise,
in conversion and regeneration;
yet of all this happy and blessed work accomplished and still carrying on,
the praise and worth thereof pertains not unto us, but unto the living God,
who is the fulness and fountain of all good things;
and has only chosen us as vessels of his glory, and instruments in his hand,
to bear and publish his name in the world; having endued us with power, wisdom,
and strength, from himself for such a work:
and his alone is the honour and renown of all his own works, now and forevermore.

Indeed, the Holy Spirit of the Father is witness, and bears full proof in us and for us,
that we have not sought ourselves in anything in this case, nor taken too much upon us,
nor been as lords over God`'s heritage, nor exalted ourselves among them,
nor preached ourselves, but Christ Jesus, and ourselves their servants for his sake.
We have been no otherwise in any case,
than becomes such a calling and profession in the gospel;
and are only to be accounted of, as stewards of the grace of God,
and dispensers of his holy word, and ministers of Christ,
and such as are instruments in his hand to gather the flock,
and go before them in truth and righteousness,
in meekness and uprightness and all the fruits of the Spirit,
both in doctrine and conduct, and also in sufferings, tribulations,
and afflictions for the same.
Thus ought we to be esteemed, loved and obeyed, and not otherwise:
and the Spirit of Christ thus witnesses, in us and for us,
in the hearts of the faithful in this city; to which we can,
in all boldness and confidence of our pure consciences,
commend ourselves to be approved and justified,--for to that testimony are we known.

And though we appeared at first in much weakness,
and for the name of Christ were despisable among men, and were liable to reproaches,
necessities, and afflictions for his sake, and had no men to stand by us,
or to help to bear our burdens, at our first coming to this place,
as being strangers both in body and spirit to the whole city;
yet the Lord appeared for us,
and his power and wisdom were manifest through us in a large manner; his strength,
authority,
dignity and riches were exalted and administered
through our weakness and poverty in spirit;
and many were made truly sensible thereof in their own souls,
in whose hearts the word of the Lord had place, to his own praise.
And as we began, so we went on, in the name and power of Christ Jesus,
in the work of the Lord in this city; and it prospered daily,
and grew honourable and fruitful in the hearts of many, who believed our testimony,
and received the Truth: and all such gave up themselves in soul, body and estate,
to obey the Truth, and to follow Christ as they had received him.
And in the space of about two years`' time, Truth was much spread,
and many were convinced, and turned to the Lord, to believe, obey,
and acknowledge the message of eternal life: and he kept us faithful in those times,
as at this day, to hold forth the testimony of his Truth in all trials,
through all tribulations, and against all oppositions.

And God has made his Truth to prosper through our ministry,
from the beginning until this moment;
and we have in a measure seen the blessed effect of the travail of our souls,
and are satisfied.
And, as I have said, in some space of time after our coming to this city,
the work of the Lord was much increased, and had grown into good esteem with many;
and it advanced greater and greater daily, in respect of the service pertaining to it.
And many occasions happened,
and various matters came to pass daily in relation to the Truth,
all which occasions and matters so coming to pass,
were to be ordered and managed with all heavenly wisdom and prudence,
for the prosperous carrying on the good work of the Lord,
so happily begun in this city and nation.
And the occasions and matters happening in relation to Truth to be managed as aforesaid,
were such as so properly did not belong or appertain
to us of the ministry to be exercised in,
as to the Friends of the city who had believed in the Truth;
namely,--concerning providing convenient meeting-places for the
publishing of Truth,--and how the poor people that believed,
should be honestly taken care for,
that nothing should be lacking among them,--and that the sick and weak
and impotent should be visited and provided for,--and that such servants
as were put away out of their services for receiving the Truth,
should be looked after, and placed in some honest employments.

These occasions, with many more of the like kind, relating to the service of Truth,
were administered to be looked after and managed in God`'s wisdom and power,
as Truth grew in the city and increased: which occasions and services, as I have said,
were not so proper for us of the ministry, as for the Friends of the city:
neither had we the opportunity of such exercises,
being wholly devoted to the work of the ministry, to which we were ordained of God,
and were continually exercised in preaching the gospel,
in answering books and manuscripts put forth against us,
and in disputes and contentions with such as opposed the Truth.
These and the like services have been our continual
work and exercise these several years,
faithfully performed by us in the sight of God; for which our reward is with us,
in our peace and comfort with the living God forever.

Therefore seeing such occasions, as aforesaid,
fell out to be managed for the service of Truth in this city,
and that they were not so proper for us, as for the Friends of the city,
to look after and serve in;
and also seeing necessity (for the carrying on the work of the Lord) required
the prudent and orderly management of such affairs;--we therefore,
in the name, power and wisdom of the Lord Jesus Christ, as we were endued with the same,
and as he had given us power and authority so to do,
for the furtherance of the gospel and prosperity of the work of the Lord,
committed to our charge,--did by virtue of the same,
ordain and appoint,--that the men Friends of the city,
or the ancientest of them in the Truth,
(not excluding any,) should meet together at the Bull and Mouth or elsewhere,
once in the fortnight, or once a month,
as they in the wisdom of God should find it necessary,
for the management of Truth`'s affairs.

And in such their meetings they should wisely consider and determine,
in and concerning the matters and occasions and such like before-mentioned;
and that they should order in outward things relating to Truth;
and be assisting one to another, for the good and honour and service of the Truth,
and the Friends of it, so much as in them lay,
according to that measure of the wisdom of God given to them,
in perfect love and unity together; bearing one another`'s burdens,
and helping together in mutual concord and good will:
that in all things in the respects before mentioned,
good and wholesome order and government and management
might be carried on among the flock of Christ;
so as that Truth might be honoured, and have a good report among all men,
while they behold the comely and honest order and government
of all outward affairs in the wisdom of God among us.

Thus for these causes, and for these ends, to the service and honour of the Truth,
was your meeting of men as aforesaid ordained and appointed;
that you in your places according to your gifts,
as well as we in our callings to which we were ordained and sent forth,
should be helpful and assistant one to another; and in unity together, advising,
and counselling, and agreeing, and assenting one to another,
for the management of Truth`'s affairs,
and to the carrying on of the blessed work of the Lord God
begun in this nation and city:--not to be divided,
I say,--you not contrary to us, nor we to you,
in any case relating to the good and wholesome ordering of affairs pertaining to Truth;
but we to go on in the ministry of the gospel, in our gifts and callings and works,
as aforesaid, to the gathering of more to the Lord;
and you to be faithful in your services and works appointed you in the wisdom of God,
and to go on in and by the counsel and instructions of the power, wisdom,
and authority of Christ Jesus, which gave you your power,
and ordained you to your service,--which through us,
(as ministers of the same,) was communicated to you from the Father:
that these gifts might dwell in you also, and enable you as well as us,
in dear and tender unity together, for the work of the Lord in our generation;
which he has appointed to be effected in his own power and Spirit dwelling in his people,
in the union and fellowship together,--in advising and consenting unto one another,
in what we are each of us called to manage and perform on the Lord`'s behalf,
for his service: not acting for self-ends, apart, reservedly,
or oppositely one to another, in any work pretendedly for the Lord;
but going on in unity together, asking, giving and taking counsel,
advice and information one of another in the Lord;
and all for the better carrying on his good work, that it may prosper in the earth.

And accordingly, in the counsel and authority of God,
and for the causes and ends aforesaid, that meeting was first set up, now some years ago;
and then entered upon its work and service,
and began to consider and order concerning the things and occasions before mentioned,
relating to the service of Truth: in which service the Lord blessed the meeting,
and made it in some measure prosperous,
(as at this day,) to the good government and well
ordering of the affairs of Friends in outward things:
and all this effected through the power and wisdom
of the Lord God manifest in the hearts of his people,
and in our concurrence together in the same; that we together one with another,
may give our judgment and advice,
for the just and righteous determination of all affairs in the service of Truth.
Thus we assisting one another in the work of the Lord, we in our callings and places,
and you in yours,--each one walking in the integrity of his heart to the Lord,
and concurring together in the consideration and
judgment of things pertaining to the Truth;
not you against us, nor without us, to proceed in the determination of Truth`'s affairs;
but in the same power, Spirit, and authority of the Lord Jesus Christ,
which is with us,--and in which we have been instrumental to turn you to the Lord,
and to watch over the flock of Christ unto this day;--nor we to judge nor determine
in the affairs of Truth otherwise than may answer the testimony of Christ in your consciences,
in which you may have unity.

Thus has it been, and shall it be manifest,
that the one Spirit of love and unity guides us, and rests with us in all our ways;
and that every one of us by that same Spirit do walk with the Lord,
and serve him faithfully, in whatsoever we are called unto, each one in his place.
And this way is of the Lord, to our everlasting peace, and the honour of his name,
to go on together in love and unity,
and without the least grain of contempt one of another, or lordliness over one another;
for this is not of the Father,
but tends to destroy and confound what we have wrought for the Lord in our day.
If, (I say) there be any such spirit of slighting or contempt on your part,
of the ministry and ministers of the gospel,
who have been faithful instruments to beget you to the Lord,
and do faithfully go before you in afflictions and persecutions
for the Truth`'s sake at this day;--or if on our part do arise
any lordliness or self-seeking over and among the flock of Christ,
which God has made us overseers of, to watch over their souls,
of which we must give an account unto Him;--this kind of spirit is not from above,
but is devilish; and its effects will be destructive,
and bring the wrath of the Lord against such as shall ever give place unto it.

Therefore it behooves all the saints,
always to be watchful against the spirit of the power of darkness,
lest at any time there should be a withdrawing or
turning aside from the paths of peace and prosperity;
which may also dishonour the God of heaven, who has thus far marvellously wrought for us,
in gathering us to be his chosen people to his praise;
who were sometimes strangers to him, as others,
but now are called and faithful and chosen.
Let us therefore stand always armed with his power and patience--with his meekness,
innocency and righteousness; and be in true subjection to him, and one to another,
each one minding to fulfill the will of the Father, in what he calls unto;
not intruding without the Lord`'s call into anything,
or to judge one of another beyond the measure of the Spirit of true judgment;
but everyone to live and walk in the particular measure of the life of righteousness,
begotten in him of the Father;
and in that let us all be joined to concur in judgment and practice,
in carrying on the work of the Lord, according to his purpose in our day;
being all of a weighty and careful spirit to do his will:
and this is a charge in the presence of God our heavenly Father, to all concerned;
and to whom I am moved of the Lord to write this for the service of Truth.

And this may truly inform all who desire it, concerning the cause, end,
and service of the aforesaid meeting; and may be as an answer to the question, why,
for what use and service, was that meeting at first appointed,
and what was the power and authority of it?
Herein, I say, is the same resolved,
which may be for the service of our age,--that all who are young in the Truth,
and have not frequented that meeting from the first beginning of it,
and such also as shall unite yet in that same assembly,
both in our age and in ages to come, may not be doubtful,
but certainly know the very just cause, end, and service,
and extent of this said meeting, and upon what ground it was first ordained;
and that this meeting still be continued and preserved in all wisdom and sincerity,
in the fear, and name, and authority, and power of the Lord Jesus Christ,
as it was ordained and begun at the first; that is to say:

[.numbered-group]
====

[.numbered]
_First,_ that the meeting do consist of just and righteous men, all believing in the Truth,
and walking in the same,--men of sound principles and judgment
in the truth of Christ,--of good and blameless conduct among men,--and
such that have kept their integrity and first principles,
and abide in love and unity in the Lord among themselves;
the meeting not limited to a number of persons, but freedom for all Friends in the Truth,
(none excepted,) as they are moved to come for the service of Truth,--to
assist in counsel and advice for the good of the body,
and carrying on the work of the Lord.
But if any person out of the Truth and of another spirit,
contrary to the faith of Christ professed and practised by Friends, come to the meeting,
such are not members thereof,
but are excluded from having their advice and judgment taken in matters of Truth,
pertaining to the service of the Lord.

[.numbered]
_Secondly,_ that the meeting be kept once a week or fourteen days,
as service and Truth`'s necessities do require,
as the Friends see cause when and where to appoint it: and being orderly come together,
not to spend time with needless, unnecessary and fruitless discourses;
but to proceed in the wisdom of God,
in such things as may upon occasion be moved among you,
for the service of Truth and good order of the body; to hear and consider,
and if possible to determine the same in justice and truth,--not in the way of the world,
as a worldly assembly of men, by hot contests,
by seeking to outspeak and over-reach one another in discourse,
as if it were controversy between party and party of men,
or two sides violently striving for dominion,
in the way of carrying on some worldly interests for self-advantage;
not deciding affairs by the greater vote, or the number of men, as the world,
who have not the wisdom and power of God;--that none
of this kind of order be permitted in your meeting.

But in the wisdom, love and fellowship of God, in gravity, patience, meekness,
in unity and concord, submitting one to another in lowliness of heart,
and in the holy Spirit of truth and righteousness, all things to be carried on;
by hearing and determining every matter coming before you, in love, coolness, gentleness,
and dear unity;--I say, as one only party, all for the Truth of Christ,
and for the carrying on the work of the Lord,
and assisting one another in whatsoever ability God has given;
and to determine of things by a general mutual concord,
in assenting together as one man in the spirit of truth and equity,
and by the authority thereof.
In this way and spirit all things are to be among you, and without perverseness,
in any self-separation, in discord and partiality;
this way and spirit is wholly excepted,
as not worthy to enter into the assembly of God`'s servants,
to give any judgment or counsel among them,
in any case pertaining to the service of the church of Christ;
in which his Spirit of love and unity must rule.

[.numbered]
_Thirdly,_--And if at any time, any matter or occasion be presented to the meeting,
which is doubtful or difficult, or not within the judgment of Friends then assembled,
they not having full knowledge or experience of the matters depending,--that
then on such occasions the judgment be suspended,
lest any unfruitful contest should arise through
a lack of full knowledge and discerning in that case,
or any determination be made unsoundly or untruly;
till more Friends that are anciently grown in the
Truth have the understanding of the matter,
as it has been from the beginning: and that we may be present,
assisting in counsel and judgment with that meeting in all such things,
for the carrying on the work of the Lord;
and that all things may be ordered in all verity and soundness of judgment,
for the honour of the Lord and happiness of his people,
in all outward affairs relating to the Truth.
For the proper work and service of the meeting is,
for the well ordering of the affairs of the Truth in outward things,
among the body of Friends;
and that a general concord and assent may be among the ancients of them,
for the government of the whole,
by hearing and considering of things fitting for the advancement of Truth.

[.numbered]
_Fourthly,_--But if at any time,
any strife or division shall happen to fall out among Friends,
as between any two Friends, or between a Friend and a stranger,
concerning any outward things, as bargains, debts,
or the like,--that then the said meeting, in the wisdom of God,
make inquiry or search into the same, if the matter be presented to them;
otherwise they may send two persons of the meeting, or send for the parties,
concerning whom such divisions are, before them;
and to inquire diligently into the cause and ground of the same,
and to use all possible fair means, in the wisdom of God,
for the ending of all such strifes and contentions,
which may happen among Friends aforesaid;
that the body may be preserved in peace and love together,
and not rent with divisions about outward things,
which are of no importance in comparison of the eternal substance.
And inasmuch as divisions and contentions of that kind are
exceedingly prejudicial to the wounding of the body,
and have woeful effects to the dishonour of the name of the Lord and his Truth,
professed by us,--therefore in the authority of Christ it is enjoined that meeting,
to take care upon it, and to be diligent as much as in you lies,
to stop and prevent all divisions and contentions among Friends,
that at any time may arise or happen to be; that peace and concord may flourish among us,
and the name of the Lord be kept undefiled,
and the work of the Lord may be carried on in all wisdom and power.

[.numbered]
_Fifthly,_--That cognizance be taken, and records faithfully kept, of all births,
marriages, and burials, that shall happen to be of and among Friends.
That marriages particularly, be carefully ordered in the wisdom of God,
according to the honest beginning used among us; and by so much the more,
as false and self-corrupted persons and ends may creep in among us,
upon pretence of motion from God in that case, to the hurt of the persons themselves,
and the dishonour of Truth,--the more diligent care is to be had concerning the same.
And that such marriages only be recorded, and none else, of such persons believing,
professing, and walking in the truth of Christ Jesus;
and such as are known to be of just, upright, and blameless conversations;
and of whom it is believed they are moved of the Lord,
or otherwise proceed upon reasonable causes, in the fear, counsel, and wisdom of God,
in their undertaking to come together in marriage:
so that their going together may be justified to be,
in and according to the truth of Christ;
that so it may be recorded among Friends in the light,
and testified to by them in prosperity or adversity, as occasion shall require;
otherwise not to be recorded,
but rather the parties reproved and rebuked in the power and authority of Christ Jesus.

[.numbered]
_Sixthly,_--That especial care be taken concerning provision
for the poor that believe and profess the Truth;
and that such who are of ability of body to labour, that have not whereon to work,
nor enough to maintain themselves; as servants,
who may happen to be put forth of their places,
or otherwise,--to be set to some employment to serve themselves in the creation:
for the end that all things of this kind may be wisely ordered among the flock of Christ,
and for the honour of Truth in the world; that as on the one hand,
complaints of necessity should not be ignored among such as be
poor and weak in body and estate,--so on the other hand,
no sloth or idleness be permitted in any that profess the way of Truth,
by depending on Friends for maintenance.
Thus shall the Truth be honoured, and the work of the Lord promoted in city and nation.

And that the meeting of the women Friends be assisting
to help the prudent ordering of affairs,
particularly in this case;
for which end that meeting was appointed in the wisdom of God by us on this occasion,
some years since the first appointment of the men`'s meeting, as before was showed.
It was seen and considered by us,
that the affairs concerning Truth being grown more large daily,
and that it was not so proper for the men as for the women to visit the sick,
and to search out the necessities of the poor, weak, widows,
and aged,--that therefore the women Friends should keep
a like meeting at such convenient times and places,
as they in God`'s wisdom should see cause; to be assisting, in what was convenient,
to the men; especially in that particular of visiting the sick and weak,
and looking after the poor, widows,
and fatherless,--and that provision should be made for them, how and after what manner,
as they in God`'s wisdom should be taught;
and this was the very occasion of the first setting up that meeting of women,
which since has continued for the body,
and been happy and prosperous in the work for which it was appointed;
and it is in the same manner ordered, in the authority of Christ,
to be continued in the service aforesaid.

[.numbered]
_Seventhly,_--That care be taken in the meeting of men,
for the collecting and preserving all Friends`' sufferings, past and to come,
which have been or shall happen to be, in and about this city and country;
and that the same,
with what remarkable passages falling out in relation to the Truth as it is judged fit,
be prudently recorded, plainly, fully and amply, for the service of this age,
and for the ages to come.

====

These also and what other things in relation to the service of Truth,
pertaining to the outward affairs thereof, as is found fitting,
are to be considered and managed by the Friends of Truth in the said meeting;
and that in unity and love, in the counsel and wisdom of the Lord God,
every person be diligent in his place to fulfill the service required of the Lord,
for the service of his Truth in general.

These things was I moved of the Lord to write forth, in the name, and power,
and authority of the Lord Jesus Christ, for the service of Truth; and in the same name,
power, and authority,
and by virtue of the love of Christ and the testimony of his Spirit which I have received,
do I enjoin the free and perfect observation of the things herein signified;
and that Friends in the Truth be diligent and careful,
everyone according to the grace and wisdom of God given, in that meeting;
and all this for the honour of the Lord God,
and the promotion of his blessed work in the world.

Written, as moved of the Lord, in the ninth year of the publishing of Truth in this city,
and is to be presented to the meeting of men to be
read among them in the fear of the Lord.

By one that from the beginning has travelled in the work of the Lord in this city,

[.signed-section-signature]
Edward Burrough.

[.signed-section-context-close]
1662.

[.centered]
=== No. CXV.

+++[+++The document to be next presented to the reader, is taken from an early manuscript,
apparently a copy: it is imperfect, which is greatly to be regretted;
yet the editor is not easy on that account to reject it,
seeing that it bears all the appearance from its style,
of having been drawn up by George Fox; and from the tenor of the last paragraph,
it is probable that not much more remained to be added, to complete the document.
This interesting account of the first establishment of meetings, the editor,
after diligent search, does not find to have been published or referred to,
by any of our authors who have written upon the subject.

Since the above was written,
the editor has found this document entered in a catalogue of [.book-title]#George Fox`'s Writings,#
preserved in London.
This catalogue,
(which appears in a handwriting very like that of
Thomas Ellwood,) commences with the year 1644;
and under each successive year, are entered the pieces written by George Fox;
and frequently the first and last concluding words of each, are also introduced.
Under the 6th month, 1689, is found the title of the present document,
with the first sentence of it, and the last--"`who is over all,
from everlasting to everlasting.
Amen.`"
A postscript is added: "`It may be serviceable for them that come after.`"]

[.blurb]
=== Concerning our Monthly and Quarterly and Yearly Meetings, wherein the Lord has owned, prospered, and blessed them; which has been of good service, to His glory, and the comfort of His people.

In this way occurred the first Monthly Meeting in
the North:--though we did meet concerning the poor,
and to see that all walked according to the Truth, before we were called Quakers,
about the middle of the nation in Nottinghamshire and Derbyshire,
and part of Leicestershire, where there was a great convincement.

In 1653, in Cumberland many of the Elders came to me at Swarthmore in Lancashire,
and desired that they might have a Monthly Meeting, to look after the poor,
and to see that all walked according to the Truth, etc.;
and they had a meeting settled there for the same purpose.
Then afterwards, when the Truth was spread in Cheshire, Lancashire, Westmorland,
Cumberland, Northumberland, Bishopric and Yorkshire, and the edge of Wales,
there was a meeting at Swarthmore, of some of the Elders of most of these places;
where we did consider to have Monthly Meetings, ordered by the power of the Lord,
in most of these places.
And then there was a Yearly Meeting settled at Skipton in Yorkshire,
for all the northern and southern counties; where in the wisdom of God,
they did see that all walked according to the glorious gospel of God,
and that there was nothing lacking among them; and if there was,
one county assisted another, either in relieving the poor,
(in the Lord`'s counsel,) or in advice in sufferings, or any other matters.

Afterwards many Friends the Lord opened their mouths, and some of them went to London,
and some to Bristol, and other places.
The substantial men and Elders in the Truth came to the Yearly Meeting at Skipton,
both from Bristol and London, and other places;
and there they gave an account of the prosperity
and the spreading of the Lord`'s blessed Truth,
and of what Friends the Lord had moved to go beyond the seas:
for all that did travel into any parts, (in the motion of the Lord,) or beyond the seas,
they made the Monthly, Quarterly, or Yearly Meeting acquainted;
so that all went in unity in the Spirit and fellowship of the church of Christ,
and power of the Lord: and if there was occasion,
Friends assisted them with that which is the least love.

And all these meetings looked to see that all walked according to the gospel of Christ,
and were faithful; and that all the poor in all the counties were looked after.
And then the Yearly Meeting was removed to John Crook`'s;
and all things there were looked into as before.
And many that were there, were moved of the Lord to go beyond the seas:
and marriages were looked into there, and settled,
as they had been before at the meeting at Swarthmore,
when many Friends met together out of many counties.
And afterwards the Yearly Meeting was kept at Balby in Yorkshire,
where there were many thousands of people: and likewise at Skipton the same year,
by the Elders there ordered from all parts, in the year 1660.
And from there, it was removed to London the next year,
where it has been kept ever since, as being looked upon a more convenient place.

And there we had intelligence from all parts beyond the seas,
how Truth prospered and spread, both in England, Wales, Ireland, Scotland, America,
Holland, and Germany; and how Friends did walk in the Truth, in their conversations,
both ministers and others, and as becomes the gospel;
and to see that the camp of God was kept holy and clean, to his glory;
and if there was any need of books concerning spreading the Truth beyond the seas,
or any other parts;
and all the sufferings were brought or sent up here (to the Yearly
Meeting,) from all parts of the world where Friends were.
And Friends were to assist and relieve them, in what they could, at the Yearly Meeting,
(or the Meeting for Sufferings in their absence,) with the King, Council, or Parliament,
that were in his dominions;
and they that were of other kingdoms or governments out of his dominions,
we applied to the ambassadors or great persons here, or wrote unto them beyond the seas,
to the Kings, Princes, or Governors, etc., to relieve Friends in their sufferings,
etc. assisting them in what we could for their relief:
and such as were taken captive by the Turks, the Yearly Meeting assisted and relieved,
or in their absence the Meeting for Sufferings;
and if there was any occasion for a collection, to help,
to refresh and relieve captives or prisoners, or for other needful services.

And there was not any public collection,
but what was done at the Yearly Meeting (with the consent
of all Friends from all parts,) for all general services;
and there it was agreed upon in unity and in the Lord`'s power,
by the consent of all Friends that came out of all counties to the Yearly Meeting.
And then, in the absence of the Yearly Meeting,
if there was any occasion for the relief of any captives, or prisoners, or sufferers,
either in Turkey or any parts beyond the seas, or here in England, to help the sufferers,
concerning Truth`'s affairs,
and other public services,--the Yearly Meeting did desire the Meeting for Sufferings,
between Yearly Meeting and Yearly Meeting,
to assist and relieve poor Friends in their sufferings,
both in England and beyond the seas, and all other needful services;
and to give them a true account next Yearly Meeting of what they had laid out,
and to whom, and for what services;
and at the Yearly Meeting they made up their accounts,
and had discharges under their hand.

So once a year the number of all the prisoners, both in England or beyond the seas,
and that are captives in all other kingdoms and dominions,
Friends are to have an account:
also the number of all Friends that have died prisoners for Truth;
and of all Friends in the ministry that have died every year.
And at the Yearly Meeting,
Friends have an account once a year from all the Yearly Meetings in the world,
which are about twenty-six;^
footnote:[In this number were doubtless included
the Circulating or Conty Yearly Meetings in the Country.
The following Yearly Meetings have been found mentioned in our records--Lancashire,
Bristol, Wales, Aberdeen, Edinburgh, Ebulin, Maryland, Jamaica, Long Island,
Rhode Island, Burlington--West Jersey, East Jersey, Pennsylvania, Bermudas, Holland,
Dantzic, London; and it is probable there were also Yearly Meetings of Colchester,
Norwich, Virginia, Antigua, Barbados, Nevis;
besides other Country Yearly Meetings in England.]
and Friends at the Yearly Meeting write to them again at their Yearly Meetings:
so that once a year at the Yearly Meeting, God`'s people know the affairs of Truth,
how it spreads, and how all walk according to the Truth;
having a heavenly correspondence one with another
in the heavenly society and fellowship.

And also if there be any differences from any part about any matter,
that cannot be ended at their Monthly or Quarterly Meetings,
then they present it to the Yearly Meeting, where some are chosen to make an end of it:
or any matters concerning sufferings, there it is answered at the Yearly Meetings,
sent there from the Quarterly Meetings;
for what the Yearly Meeting receives is from the Quarterly Meetings,
by them that are ordered from the Quarterly Meeting to the Yearly Meeting,
that be substantial elders,
that know the affairs of the church of Christ in their county;
they bring up their sufferings or any other case: but for private or particular letters,
they seldom receive any,
unless it be upon necessity or urgent occasions that fall out after the Quarterly Meeting;
for in all counties their sufferings or any other case,
are first brought to their Monthly Meetings; and if not ended there,
then it is brought to their Quarterly Meetings; and if not ended there,
then it is presented to their Yearly Meeting; where some are chosen out to hear it,
and make a final end of it in the Lord`'s wisdom, in truth and righteousness,
without respect to any.

For, in the first conversion to Christianity, after Christ was ascended,
there were seven men of honest report and full of the Holy Spirit, and of wisdom,
chosen out to be deacons, etc., and to look after the poor, and widows,
and to see that nothing was lacking; then all was well: and Nicolas,
a proselyte of Antioch was one; and you may see how he ran out into bad things,
and drew a company after him, that were called Nicolaitanes, whom God hated,
as in Rev. 2:15. And when the Gospel was spread abroad in the world by the apostles,
and any difference was in the churches,
they went up to Jerusalem to the apostles and elders;
and they declared all things that God had done with and by them;
and there they decided the differences: and the apostles and elders,
the church at Jerusalem, wrote epistles and sent them by Paul and Barnabas:
as they went through every city, they delivered them the decrees to keep,
that were ordained of the apostles and elders which were at Jerusalem:
and so were the churches established in the faith, and increased in number daily, Acts 16:4-5.

And the apostles, the ministers of Christ, ordained elders in every church:
so there was not a church but they had their elders also, Acts 14:23:
so you may see there was not a church but they had their elders;
then there was more than seven deacons, when elders were ordained in every church.
And the apostle says to Titus, "`For this cause left I you in Crete,
that you should set in order the things that are lacking,`" or left undone;
"`and ordain elders in every city,
as I have appointed you:`" Titus 1:5. Concerning both the aged
men and aged women,--men "`sound in the faith,`" etc.,
and "`holy women,`" etc.: Titus 2:3. And Peter writes "`to the elders:`" 1 Peter 5:1:
and John writes, "`The Elder unto the elect lady and her children;`" and said,
"`I rejoice greatly, that I found of your children walking in truth:`" 2 John 1:4:
and many other scriptures might be brought to the same purpose;
but this is sufficient to them that are in the same
power and Spirit that gave them forth,
and to correct the opposers of the order of Truth,
by the same Spirit that was in the apostles,
to the praise and glory of God:--the Lord increase his Truth and his order.
Amen!

Much more I could write of the passages of Truth and its order:
but these are short heads and memorandums to Friends
that have not known the beginning of it:
for many of that separate spirit have talked of things in the beginning,
and yet have opposed the order of Truth.

[.centered]
=== No. CXVI.

[.blurb]
=== A testimony from the brethren, who were met together at London in the third month, 1666, to be communicated to faithful Friends and Elders in the counties, by them to be read in their several meetings, and kept as a testimony among them.

We, your friends and brethren,
whom God has called to labour and watch for the eternal good of your souls,
being at the time aforesaid,
through the Lord`'s good hand which has preserved us at liberty,
met together in his name and fear,
were by the operation of the Spirit of Truth brought into a serious
consideration of the present state of the church of God;
which in this day of her return out of the wilderness,
has not only many open but some covered enemies to contest against;
who are not afraid to speak evil of dignities, and despise government; without which,
we are sensible our safety and fellowship cannot be kept holy and inviolable.
Therefore, as God has put it into our hearts,
we do communicate these things following unto you, who are turned from darkness to light,
and profess fellowship with us in the glorious gospel,
throughout nations and countries where we have travelled;
as well for a testimony against the unruly, as to establish and confirm you,
to whom it is given to believe the Truth; which unto us is very precious,
as we believe it is also unto you, who in love have received it,
and understood the principles, and felt the virtue and operation of it;
in which our spirits breathe, that we all may be preserved,
until we have well finished our course and testimony,
to the honour and glory of the Lord God, who is over all, blessed forever.

[.numbered-group]
====

[.numbered]
_First._--We having a true discerning of the working of that spirit,
which under a profession of Truth, leads into a division from, or exaltation above,
the body of Friends, who never revolted nor degenerated from their principles;
and into marks of separation from the constant practice of good ancient Friends,
who are sound in the faith which was once delivered unto us;
and also into a slight esteem of their declaration or preaching,
(who have and do approve themselves as the ministers
of Christ,) and of the meetings of the Lord`'s people,
whereby and wherein Friends are, and often have been preciously revived and refreshed:
and under pretence of crying down men and forms, do cry down the ministry and meetings,
or encourage those which do the same.--We say, the Lord having given us to see,
not only the working of that spirit, and of those that are joined to it,
who bring forth those ungrateful fruits,
but also the evil consequences and sad effects of the same,
which are of no less importance than absolutely tending to destroy the work of God,
and lay waste his heritage:^
footnote:[The spirit of disaffection and separation prevalent
at this period through the influence of John Perrot,
is here doubtless in view.
Several addresses were issued by faithful Friends to warn and exhort
the flock against this deceitful and wasting snare of the enemy;
among them might be mentioned an epistle of Stephen Crisp,
as very instructive and affecting, namely, [.book-title]#An Epistle to Friends, Concerning the Present and Succeeding Times,# etc. 1666.
On referring to the historical letters in this volume, page 372,
the subject will also be found adverted to.]--we do unanimously,
(being encouraged thereto by the Lord, whose presence is with us,) declare and testify,
that neither that spirit, nor such as are joined to it, ought to have any dominion,
office, or rule in the church of Christ Jesus, whereof the Holy Spirit,
that was poured forth upon us, has made us members and overseers:
neither ought they to act or order the affairs of the same;
but are rather to be kept under with the power of God,
till they have an ear open to instruction,
and come into subjection to the witness of God;--of the increase
of whose kingdom and government there shall be no end.

[.numbered]
_Secondly._--We do declare and testify, that the spirit of those that are joined to it,
who stand not in unity with the ministry and body of Friends,
who are steadfast and constant to the Lord and his unchangeable Truth,
(which we have received and are witnesses and ambassadors
of,) have not any true spiritual right,
nor gospel authority to be judges in the Church,
and of the ministry of the gospel of Christ, so as to condemn them and their ministry:
neither ought their judgment to be any more regarded by Friends,
than the judgment of other opposers, which are without;
for of right the elders and members of the church,
which keep their habitation in the Truth, ought to judge matters and things which differ;
and their judgment which is given therein, to stand good and valid among Friends,
though it be kicked against, and disapproved by them who have degenerated, as aforesaid.
And we do further declare and testify,
that it is abominable pride that goes before destruction,
that so puffs up the mind of any individual,
that he will not admit of any judgment to take place against him;
for he that is not justified by the witness of God in Friends,
is condemned by it in himself; though being hardened,
he may boast over it in a false confidence.

[.numbered]
_Thirdly._--If any difference arise in the church,
or among them that profess to be members thereof, we do declare and testify,
that the church, with the Spirit of the Lord Jesus Christ, have power,
without the assent of such as dissent from their doctrines and practices,
to hear and determine the same.
And if any pretend to be of us, and in case of controversy,
will not admit to be tried by the church of Christ Jesus,
nor submit to the judgment given by the Spirit of
Truth in the Elders and members of the same;
but kick against their judgment as only the judgment of
man,--it being given and manifested according to Truth,
and consistent with the doctrine of such good ancient Friends, as have been,
and are sound in the faith, and agreeable to the witness of God in his people;
when we testify in the name of the Lord,
that if judgment so given be risen against and denied by the party condemned,
then he or she,
or such as so far partake of their sin as to countenance and encourage them therein,
ought to be rejected, as having erred from the Truth.

[.numbered]
_Fourthly._--That the ministry may not be justly blamed,
we declare that if any go abroad hereafter, pretending to that weighty work and service,
who either in life or doctrine grieve good Friends
that are steadfast in the Truth and sound in the faith,
so that they are not manifest in their consciences,
but disapproved by the witness of God in them; then ought they,
whatever have been their gifts, to leave them before the altar, and forbear going abroad,
until they are reconciled to the church,
and have the approbation of the Elders and members of the same.
And if any, that have been so approved of by the church,
do afterwards degenerate from the Truth, and do that which tends to division,
and countenance wickedness and faction, as some have done,
then the church has a true spiritual right and authority to call them to examination;
and if they find sufficient cause for it by good testimony,
they may judge them unfit for the work of the ministry,
whereof they have rendered themselves unworthy;
and so put a stop to their proceedings therein:
and if they submit not to the judgment of the Spirit of Christ in his people,
then ought they publicly to be declared against,
and warning given to the flock of Christ in their several meetings to beware of them,
and to have no fellowship with them, that they may be ashamed;
and the lambs and babes in Christ Jesus preserved.

[.numbered]
_Fifthly._--And if any man or woman who is out of unity with the body of Friends, print,
or cause to be printed, or published in writing,
anything which is not of service for the Truth,
but tends to the reproach or scandal of faithful Friends,
or to beget or uphold division or faction;
then we do warn and charge all Friends that love the Truth,
as they desire it may prosper and be kept clear,
to beware and take heed of having any hand in printing, publishing,
or spreading such books or writings;
and if at any time such books be sent to any of you that sell books in the country,
after you,
(with the advice of good and judicious Friends,) have tried and find them faulty,
send them back where they came from.
And, we further desire that, from time to time, faithful and sound Friends and brethren,
may have the view of such things as are printed upon Truth`'s account,
as formerly it has used to be, before they go to the press;
that nothing but what is sound and savoury,
that will answer the witness of God in all people,
(even in our adversaries,) may be exposed by us to public view.

[.numbered]
_Sixthly._--We do advise and counsel,
that such as are made overseers of the flock of God by the Holy Spirit,
and do watch for the good of the church, (meeting together in their respective places,
to set and keep the affairs of it in good order,) to beware of
admitting or encouraging such as are of weak and of little faith,
to take such trust upon them; for by hearing things disputed that are doubtful,
such may be hurt themselves, and hurt the Truth;
not being grown into a good understanding to judge of things.
Therefore we exhort that you, who have received a true sense of things,
be diligent in the Lord`'s business, and keep your meetings as to Him;
that all may be kept pure and clean, according to that of God which is just and equal.
We also advise that not any be admitted to order public business of the church,
but such as are felt in a measure of the universal Spirit of Truth,
which seeks the destruction of none, but the general good of all,
and especially of those that love it, who are of the household of faith.

====

So dear Friends and brethren,
believing that your souls will be refreshed in the
sense of our spirits and integrity towards God,
at the reading of these things, as we were, while we sat together at the opening of them;
and that you will be one with us in your testimony
on the behalf of the Lord and his precious Truth,
against those who would limit the Lord to speak without instruments,
or by what instruments they list,--and who reject the counsel of the wise men,
and testimony of the prophets,
whom God sanctified and sent among you in the day of his love,
when you were gathered,--and would not allow Him liberty in and by his servants,
to appoint a place wherein to meet together, to wait upon and worship Him,
(according as He requires) in spirit, but call this formal,
and the meetings of man;--we say, believing that you will have fellowship with us herein,
as we have with you in the Truth, we commit you unto God, and to the word of life,
that has been preached unto you from the beginning; which is neither limited to time,
nor place, nor persons, but has power to limit us to each,
as pleases Him:--that you with us, and we with you,
may be built up in the most holy faith, and be preserved to partake of the inheritance,
which is heavenly, among all those that are sanctified.

[.signed-section-signature]
Richard Farnsworth, Alexander Parker, George Whitehead, Thomas Loe, Josiah Cole,
John Whitehead, Stephen Crisp, Thomas Green, John Moon, Thomas Briggs, James Parke.

[.centered]
=== No. CXVII.

[.blurb]
=== The Written Epistle From the Yearly Meeting, 1668

[.salutation]
Dear Friends,

In the seed of life and in the Truth of God, in whom our love is to you all,
in that which changes not,--this is to let you understand,
that at the last meeting of Friends in the ministry which met in London,
and who came out of most counties in England and Wales,
at the time called Christmas last,
(when we had several glorious meetings in the life and power
of God,)--we did conclude among ourselves to settle a meeting,
to see one another`'s faces, and open our hearts one to another in the Truth of God,
once a year, as formerly it used to be;
and once in two years for Friends in the ministry, that go in all parts beyond the seas,
to come up and meet with us at London.

The next meeting will be about the time called Easter, in the year 1670, at London;
when we shall desire to see your faces,--that we
may see in all meetings that the--+++[+++_word doubtful_]
be supplied, and that nothing be lacking;--then all is well:
and that all walk as become the order of the gospel,
which is the comely order in the power of God, which all uncomeliness is out of.

This is to be sent to C. Holder +++[+++and others named;]--and
if there be any other that labour in the work of God,
let them have notice, and copies of this;--and into all the plantations beyond sea,
from one to another; and also to Holland, Scotland, Ireland and Wales.

[.signed-section-signature]
George Fox.

[.signed-section-signature]
Leonard Fell, Stephen Crisp, John Story, George Whitehead, Alexander Parker, John Stubbs,
Thomas Briggs, John Whitehead.

[.signed-section-context-close]
London, the 16th of 11th month 1668.

[.centered]
=== No. CXVIII.

[.blurb]
=== At a General Meeting of Friends, for managing the public affairs of Truth throughout the nation, held at Devonshire House, London, 29th of 3rd Month, 1672.^
footnote:[The first part only of this minute is printed,
as the introductory article in the volume of the epistles of the Yearly Meeting in London,
8vo. This copy is taken from one of the circulars issued on the occasion.]

It is concluded, agreed, and assented unto, by Friends then present,
that for the better ordering, managing,
and regulating of the public affairs of Friends relating
to the Truth and the service thereof,
there be a General Meeting of Friends held at London, once a year,
in the week called Whitsun-week, to consist of six Friends for the city of London,
three for the city of Bristol, two for the town of Colchester,
and one or two from each and every of the counties of England and Wales respectively.
+++[+++_So far only printed in_ [.book-title]#Book of Epistles.#]
That the Quarterly Meetings in London, Bristol, Colchester,
and all and every the counties of England and Wales respectively,
at their Quarterly Meetings immediately preceding
the said week called Whitsun-week in every year,
do take care to nominate and appoint the number of Friends aforesaid,
to be present at the General Meeting aforesaid;
there to advise about the managing of the public
affairs of Friends throughout the nation.

That the Friends so to be chosen for the purpose aforesaid,
be desired to be at London by the second-day night of the Whitsun-week, so called,
in every year at furthest.
And upon their arrival there, the six Friends for the city of London,
together with a competent number of the other Friends of the country,
may then examine and appoint the time and place for
the then meeting of the said General Meeting,
sometime in the said week, called Whitsun-week, in every year accordingly,
until further orders be taken therein.
That as many Friends that labour in the Truth, as have freedom thereunto,
may be present at the said General Meeting: that all others,
except such as are nominated, appointed, and chosen,
be desired to forbear to come to the said General Meeting, except such Friends as they,
when met together, shall see fit to admit.
That copies hereof be sent to the respective Quarterly
Meetings throughout England and Wales,
for the better regulation in the matter.

[.salutation]
Dear Friends and Brethren,

In that universal love,
wherein we are mutually concerned in the service of Truth and one another,
do we dearly salute you; and therein do signify unto you, that upon consideration had,
of the public charge relating to Friends and Truth,
at a General Meeting for the city and country, held this day at this place,
it was found of absolute necessity, that a public collection be again made among Friends,
in the several counties throughout England and Wales,
for the management of Truth`'s affairs;
particularly for Friends`' supply who are called
into the service of the Lord beyond seas;
and for books that are disposed of and given away for the public service,
to the chief rulers and others concerned: as likewise considerable charge has been,
and may be, for packets of letters,
together with accounts of Friends`' general sufferings,
with the charge of recording and often transcribing the same.

Friends of London having made it appear, that for several years past,
they have laid out near one hundred pounds a year upon these general services aforesaid,
(besides that of the service beyond seas,) which do equally concern Friends in the country,
as well as in the city, to bear, especially for the future.
Therefore we desire you that are concerned in the Quarterly Meetings,
to take care that a collection be made accordingly in your county,
for the intent and purpose afore-mentioned; and sent up,
with as much convenient expedition as may be, to the hands of Gerrard Roberts,
Gilbert Latye, Edward Man, John Nelson, Arthur Cooke, or any one of them.

So not doubting your care herein, for the Truth`'s sake,
desiring that Friends may be open-hearted, cheerful, diligent therein,
as God has blessed and prospered them; we remain your faithful friends and brethren.

Signed in the name and by the appointment of the said General Meeting,

[.signed-section-signature]
George Whitehead, Alexander Parker, John Whitehead, Thomas Gouldney, Francis Rogers,
John Crook, William Welch, Stephen Crisp.

[.signed-section-context-close]
Devonshire House, London, 29th of 3rd month, 1672.

[.centered]
=== No. CXIX.

[.blurb]
=== Epistle From Friends of the General Meeting Held in London, the 31st of Third Month, 1672.^
footnote:[This epistle seems to be specially addressed to Ministers,
and those filling the responsible station of overseers of the flock:
the duties subsequently assigned to Elders, probably devolved at this time,
on the faithful, perhaps in both the stations above mentioned,
but more especially on overseers.]

[.salutation]
Dear Friends and Brethren,

From that universal love and care,
which the Lord our God has begotten in us towards one another, his church, and people,
these things following are opened in us by His Holy Spirit, to present both unto you,
who are called forth in a measure of the heavenly gift to
labour and travel abroad to minister unto others,
and unto you who are more resident in the several counties and meetings,
who have a care and oversight committed to you by the Lord, in your respective places,
counties and meetings, for the good order and comfort of the Church.

[.numbered-group]
====

[.numbered]
_First._--To those that are called forth with a testimony for God,
and those that are endued with a heavenly gift for that end,--our
tender advice and counsel in the Spirit of life and true love is,
that you all wait and dwell in the heavenly life and Spirit of the gospel,
wherein both true judgment and mercy are;
that thereby you all may be made manifest in men`'s consciences,
and be a good savour to God, both in life and doctrine: that your conversations,
as well as your words, may preach Truth, and shine in your sobriety and holy examples;
and so be instrumental in His hands for the conversion, salvation, comfort,
and establishment of others.
And our earnest desire is, that you all may be so preserved,
in diligence and subjection to the power of an endless life,
as that none may run on too hastily or forwardly in any exaltation of spirit,
away from the sense of the arising of the pure life and testimony:
nor yet any to quench its arising, motions, or testimony, through fear, negligence,
doubtings, secret dispute, or backwardness:
but that everyone may dwell in that living sense, willingness and diligence,
as tends to your enlargement and growth,
and to the increase of your gifts and measures in the life.
And that everyone who ministers, may be kept in the lowliness,
in subjection and tenderness of spirit to the Lord and his counsel;
so that a clear and heavenly understanding may be opened and increased in them,
and so in true meekness and humility retained, as that in the Spirit of the gospel,
they may be enabled gradually to demonstrate the Truth,
to the opening the understandings,
and for the conviction of the consciences of the hearers;
before either they pass positive judgment upon Truth`'s adversaries, or their principles.

Also, that the first principles of the true light, repentance,
and remission of sins through the name and power of our Lord Jesus Christ, be kept to,
held forth, and preached to the world, for the preparing their hearts for God:
and none suddenly to rush into, or strive out of God`'s counsel,
to speak of the high mysteries of the gospel, nor cast pearls before swine.
Neither hastily, or at first entrance, out of their own measures and attainments,
to assert the highest doctrines, as that of perfection, or height of attainments,
before people`'s minds are prepared by the secret
power of God for the first principles or beginnings;
that they may not be stumbled, nor their minds biased against Truth,
by any hasty or untimely asserting matters beyond their measures and capacities; that is,
without a deliberate progress in the work and travail of the Gospel: and that Christ,
his death, blood, and resurrection, be reverently spoken of,
according to Scripture expressions.

That none be forward or hasty in traversing the ways and principles of professors;
to propose objections, nor to make or raise more in preaching,
than they clearly answer by the plain evidence of the Spirit; lest any lose their matter,
entangle themselves, and leave the hearers more dark and doubtful than they found them.
And we warn and charge all concerned, both in England, Scotland, and elsewhere,
in the presence of the living God,
to take heed of coming too near the disobedient hypocritical spirit of contentious professors,
to gratify them with unsound words and nice distinctions; which tend to darken knowledge,
and veil the simplicity of the gospel, and to pervert the holy Truth.

Again, when anyone in speaking,
comes to feel both strength of life and matter of ministry to be lacking,
we advise such not to strive to bring forth and enforce words; but then to be still,
and wait till life arise to bring forth its own testimony:
for that is the way to be enlarged, and to be further accomplished in the work.
And not to run over or beyond the living sense of the heavenly life,
nor into vain repetitions, either in preaching or praying,
through striving or eagerness of mind; but to keep low and tender,
in the true sense and feeling of the holy seed and divine power,
which gives life and strength.
We desire and exhort all such as are young,
and not thoroughly experienced in the service and work of the gospel,
to keep in their own proper gifts, measures, and orders of the life;
and out of all striving or straining beyond their line, to be heard or seen of men:
and so to be kept clear, in the true sense and exercise of their own proper gifts,
out of all mere imitations and formed habits, which are not to edification.

And everyone so keep in the peaceable wisdom and life in your travails,
out of all extremes and whirlings, which tend to draw out and unsettle people`'s minds.
And avoid all imagined,
unseasonable and untimely prophesyings which tend not only to stir up persecution,
but also to the begetting airy and uncertain expectations,
and to the amusing and affrighting simple people from receiving the Truth:
for this practice, God`'s wisdom neither leads to, nor justifies.
And take heed of aggravating reflections and forward clashing at persons or people,
with unseasonably and rashly using names of distinctions;
which will be resented as reproachful to them,
and not only stumble and prepossess their minds with prejudice,
but also hinder their convincement: whereas our endeavours have been and are,
to open men`'s understandings, and to convince their consciences, that they may repent.

Be careful and labour in the peaceable gospel, to settle, stay,
and establish people`'s minds in the holy principle of life and light;
that they may not be puffed up, nor run into hurryings, or confusion in their own wills;
but that the living praises of God may naturally break forth in his own life;
that they run not into any singularity to admire
or wander after any particular man or persons;
for this tends to the hurt, both of themselves, and of some that labour among them,
and has been hurtful.
Our labour and travail has been and still is, to preach Christ, as servants for his sake,
and to gather to Him, and not to ourselves; nor to seek popularity, applause,
or praise of men, nor any self-interest; for if any do, they`'ll fall,
and the power of God will work them under, and without repentance cast them out.

And speak not evil one of another, to the lessening one another`'s reputation,
or testimonies for Truth; but be tender of one another`'s testimony,
not to weaken it,--we exhort you in the name and power of God.
As also, to let no strife, hard thoughts, or jealousies,
lodge in any of your minds one against another; but in brotherly love and tenderness,
speak privately and gently one to another, to remove all offences, jealousies,
and aggravations whatsoever.
And be sure not to judge, nor reflect publicly,
to the weakening or hindering the least gift,
or testimony that is in anyone for God and his Truth;
but where there is a sincerity and a tenderness,
and the least budding or breaking forth of life, or heavenly gift,
let it be nourished and encouraged, and those that are young, watched over and helped,
in the tender love of God.
Let there be no harshness or severity exercised, to the hurt or prejudice of any;
but feel the life and spirit of the Lamb through and over all.

[.numbered]
_Secondly._--And you, our Friends and brethren,
who have a care and oversight committed to you in your several places and meetings,
being set as pillars in the house of our God,--if
any of you shall at any time come to see any weakness,
lack of wisdom, or miscarriage, either in doctrine or practice,
by any who come abroad to labour or minister among you,--we tenderly request,
and earnestly desire, that you would in brotherly love and tenderness,
speak privately to them, for their good and preservation; that they,
and the testimony they have for the Truth, may be preserved, and rightly improved;
that none who have a call from God may be discouraged, nor any gift of God quenched.
And so, all forbear public judgings and reflections upon such as have a gift given them,
and a sincerity in their intentions;
though for a time there may be a lack of wisdom in some, in the management thereof,
yet do not discourage and wholly crush them under,
but help them in the love and counsel of God.
And as much as in you is, stop all false, depraving, and hurtful reports, whisperings,
tattles and backbitings; and set true judgment over all sowers of strife and discord,
we beseech you, for the Truth`'s sake.

And we desire you would be exemplary in your families,
and careful in the education of your children in the holy nurture and fear of the Lord;
that thereby it may appear unto the world, that you are of the true seed of Abraham;
of whom God testified, that He knew that he would command his children and household,
that they should keep the way of the Lord.
And we beseech you for the Truth`'s sake, with the power of God stop all busy,
discontented spirits,
(if any appear among you,) from reflecting upon and meddling with the powers,
or those in outward dominion,--and all fruitless discourses of that tendency and nature;
which,
with that old discontented professor`'s spirit (which
is neither valiant in times of suffering,
nor contented in times of liberty,) are to be shunned, rejected and reproved,
whenever met with:
that all among us walk innocently and peaceably with a good conscience
before all the world;--for that gives true boldness and confidence.

And all of us seriously to eye and mind the supreme Power and over-ruling Hand,
which commands the seas, and stops the floods, and stills the winds and storms;
and can restrain the remainder of men`'s wrath, and turn them like waters,
as seems good in the sight of Him, the Lord our God:--to whose love, oversight,
care and protection, we commit you all, with his whole family;
desiring that his peace and unity may remain and increase in and among you,
and the multiplying of all spiritual blessings and refreshments of life unto you all,
who are of the same mind and spirit with us in that eternal truth,
love and life;--wherein we dearly salute you all.

====

[.offset]
Our desire is,
that copies of this be communicated to Friends and brethren herein concerned.
Your faithful brethren in the Lord,

[.signed-section-signature]
George Whitehead, Alexander Parker, John Story, Thomas Salthouse, John Whitehead,
John Graves, Robert Hodgson, James Parke, Jasper Batt, Thomas Robertson, John Crook,
William Gibson, Stephen Crisp, William Smith, James Harrison, Thomas Green,
Thomas Curtis, William Brend, Samuel Thornton, William Yardley.

[.signed-section-context-close]
London, the 31st day of the 3rd month, 1672.

[.offset]
+++[+++_From an ancient copy, apparently in Thomas Ellwood`'s hand-writing,
on comparison with his original letters._]

[.centered]
=== No. CXX.

[.blurb]
=== Epistle From Friends Met in London, the 26th of Third Month, 1673.

[.salutation]
Dear Friends and Brethren,

The Lord our God having by his eternal power,
raised up and preserved many faithful and living
witnesses of his blessed Truth until this day,
both for the conversion of many from darkness to light, and for their building up,
establishment, and comfort therein,
by his own living eternal word of life and reconciliation;
and having also signally blessed this precious opportunity
of our assembling together with His glorious presence,
power and majesty manifest among us, which many were and are eye-witnesses of;
and in the unspeakable sense thereof many have been as melted,
and their hearts exceedingly broken, and their souls overcome,
and deeply affected with God`'s unspeakable goodness and power, love and life,
so plentifully shed abroad among us and in our hearts:--in the
sense whereof our hearts are open and affected towards you all,
even in the same dear and tender love and life that is abundantly shed forth unto us;
and from which our salutation is to all our dear Friends, brethren and sisters,
in this and other nations.

Having the general state of the churches and people of God opened unto us,
with a tender care upon our hearts, and breathing of our souls, that they all may grow,
prosper, and be preserved, in unity, grace, and good order:
that divine life and virtue may reign, and abundantly flow over and through all,
to your replenishment and unspeakable comfort;
that you may keep out the enemy in all his appearances,
that would make divisions and disturbances in the
churches:--for at this time the enemy is busy,
and secretly at work for that end, to make rents;
endeavouring thereby to bring the open opposers and adversaries of Truth over us.
It is, that strife and divisions may be stirred up among ourselves,
that they desire and watch for; and therefore, where any are instruments thereof,
they serve not the Lord Jesus Christ, but the enemy;
they that make divisions and cause offences contrary to the gospel,
and that seek to sow discord among brethren, are not only to be marked,
but the Lord will make them manifest; and his power will bring them under,
and debase them, as it has done and will do that spirit, which is guilty of jealousies,
evil surmisings, whisperings, and hard speeches against the brethren,
and faithful labourers in the Lord`'s work.
It is the accuser of the brethren that strikes at their testimony,
and seeks to undermine and to beget a disesteem and slight of them in it;
which adversary must be watched against, and forever cast down and out.
And we are assured from the Lord, that all sowers of discord,
accusers of the faithful brethren,
slighters and undervaluers of their testimony and gifts, self-seekers, whisperers,
backbiters, and all self-willed and self-exalted spirits, God will debase;
His eternal power will work them under, and all that which offends shall be removed.

God`'s pure power is at work--refining, thoroughly purging his floor,
and sanctifying his church and people; that there may be no rent or schism,
but that the Lord may be one, and his name one, among us:
and blessed are you that keep to your first love, and retain your integrity to the end.
O! dear Friends and brethren, watch in the light against all the enemy`'s wiles;
and pray for the peace of Jerusalem, that she may be seen in her beauty and splendour,
as a city without breaches; that peace may remain in her walls,
and prosperity within her palaces.
O! let it be the general care of all our brethren,
to whom the Lord has committed an oversight in the churches,
to keep things quiet and in good order, by the power and wisdom of God;
who is not the author of confusion,
but of peace:--and that the public affairs of Truth
be managed and carried on in the same power and wisdom,
which is pure and serviceable;
that all in humility may submit to Christ`'s rule and government,
in the spirit of meekness and condescension.

Keep out all roughness and harshness one towards another, and all self-rule and dominion,
that is not of the life, but in the will of the flesh; and let all that,
be kept down forever,--and that no strange fire be kindled among you,
nor in your meetings.
And elders and overseers must not be self-willed, nor soon angry,
nor given to haste or passion, nor to any shortness or brittleness;
for such keep not in a sound mind,
nor in the discerning either of true judgment or
mercy,--which are both to be exercised among you,
as the spirit of life opens to you the conditions
and states to which they properly belong.
For as all looseness, disorderly walking, and scandalous conduct and practices,
must be severely reproved and judged out,
especially among them that are convinced of the precious
Truth,--and the guilty to bear their judgment and burden;
so likewise mercy and forgiveness must be extended
to such as having been overtaken with a fault,
come to feel a true tenderness in their hearts through judgment--and to receive counsel,
that they may be preserved in fear and watchfulness.

And let not judgments and testimonies against miscarriages and offences,
be made more public than the miscarriages are,--to harden those that miscarry,
and give the adversaries of Truth advantage to throw dirt upon Friends:
but be careful and tender for the Truth and Friends in that matter;
and endeavour to save the souls even of those that are tempted and drawn aside.
As also, that private differences which may happen among any Friends or brethren,
be ended by some Friend, in the wisdom and counsel of God,
with as much privacy as may be,--without troubling or disturbing
the public meetings or churches with them,
and without public reflections upon persons,
where the difference or offence on either hand is not so notorious or publicly manifest,
but best to be ended privately;--both for the preservation
of them who are concerned therein,
and the prevention of such occasions as may either stumble the weak, cause confusion,
or give the world occasion to reproach Friends and Truth.

And Friends,
we desire that all differences may be ended in the several counties where they do arise;
and that the honour of God, and peace of the Church, may be minded,
both by those whose case is to be determined, and those who are to determine:
and that none join with such a singular spirit as
would lead him to be sole judge in his own cause,
but in the restoring and healing spirit of Christ, both the offended and the offender,
may, for the Truth`'s sake, submit to the power of God in his people, in those cities,
places, or counties, with such Friends,
as they with the parties concerned shall call to their assistance;
for they do and will judge for God.
And if any will not give up his matter to the judgment of Truth in his people,
he does but render himself and his cause suspicious,
and that he lacks the sense of the fellowship of the body:
and as Friends keep in wisdom and patience concerning such, it will come over him,
and be his burden; for the universal Spirit of Truth,
by which we are called and made a people, leads not into any such practice.

Dear Friends, let the authority of God`'s power, heavenly and peaceable wisdom,
be eyed in all your assemblies;
that the government of Truth and righteousness may be exalted over all,
that true judgment and mercy may have their place.
And though a general care be not laid upon every member,
touching the good order and government in the Church`'s affairs,
nor have many travailed therein, yet the Lord has laid it more upon some,
in whom he has opened counsel for that end,--and particularly
in our dear brother and God`'s faithful labourer,
George Fox,--for the help of many: and God has in his wisdom,
afforded those helps and governments in the churches, which are not to be despised;
being in subjection to Christ the one head and law-giver, answering his witness in all.
And so all necessary counsel, admonitions or testimonies, that have been given forth,
and received in the universal spirit of life and unity, have their service for God,
in subjection to his light and in subserviency thereto,
and in order to answer the great rule and law of the Spirit of life,
as proceeding from it.

And they that are spiritual,
will acknowledge those things spoken or written from this spirit, and for this end,
to be the requirings of the Lord.
Many in various places have received help and encouragement from Him,
through those helps and governments that He has afforded
in the Church--the true and living body,
which we are members of; in which as all keep their habitations,
there is a sweetness and harmony of life, unity and subjection one to another,
and a preferring one another in the Lord:
yet every man in his own proper order,--for every member of the body is not an eye;
and yet each member has its proper place and service,
and all in subjection to the one life, power, and Head, which is Christ.
And it has been observed by us, that that spirit which despises governments and dominion,
and speaks evil of dignities, is either a singular, or a self-righteous,
self-separating spirit, that would itself bear rule,
and be judge over all,--which also seeks to stumble and darken the simple; or a loose,
disobedient, careless spirit, that would not be reformed,
but live at ease in the flesh and fleshly liberty; which the power of God will rebuke.

But though He has given us dominion over that spirit and its perverse ways,
which oppose His power, and would work division, and lead into a corrupt liberty;
yet it is no dominion over your faith that we seek;--but
that we may be helpers of your joy in the Lord,
and you as diligent coworkers together in the faith and love of God;
wherein we all may be a mutual comfort, joy, and crown of rejoicing,
one to another,--as having one master, and we all brethren in Him,
who is the Lord of the household, and God of glory,--whose glorious presence is with us.
And it is a wrong spirit, that would surmise or insinuate jealousies,
or beget prejudice against the faithful labourers in the gospel,
and helpers in government;--to misrepresent such,
as aiming at any other ends and interests,
than Christ`'s interest and government over all; than which God is our record,
we are clear from seeking or aiming at any other.
And in His authority and power, we stand witnesses against that spirit forever,
both in our open and secret enemies, which either smites at our heavenly society,
or would break our unity.

To the Prince of peace, who is our head and lawgiver,--unto whom thrones, dominions,
principalities,
and powers are subject,--be glory forevermore! unto
whose power and government we commit you all,
and in true endeared love, rest

[.signed-section-closing]
Your dear brethren,

[.signed-section-signature]
Thomas Green, Alexander Parker, William Brend, William Gibson, Morgan Watkins,
John Graves, Samuel Thornton, John Whitehead, Jasper Batt, John Anderdon,
Thomas Salthouse, Samuel Watson, John Langstaff, James Adamson, John Cox, James Merrick,
John Bowldren, John Raunce, George Whitehead, Stephen Crisp, William Penn, Thomas Briggs,
John Moone, Charles Marshall, Luke Howard, Samuel Cater, Arthur Ismead, James Hall,
George Coale, Robert Barclay, Edward Bourne, Charles Lloyde, James Claypole,
Richard Almond, William Fallowfield, Robert Gary.

[.postscript]
====

We desire that true copies hereof may be communicated to, and read in,
the several Quarterly, Monthly, and other meetings of Friends and brethren,
throughout England, and elsewhere.

====

[.offset]
+++[+++_This Epistle is (by a careful comparison with Thomas Ellwood`'s
hand writing) taken from a copy believed to be written by him._]

[.centered]
=== No. CXXI.

[.blurb]
=== An Epistle From the Women Friends in London, to the Women Friends in the Country, Also Elsewhere, About the Service of a Women`'s Meeting. (1674.)

Dear Friends and Sisters in the eternal relation of one God and Father,
we with one heart greet you;
and in the blessed love and life in his Son Christ Jesus our Saviour,
(as in our measures we partake of,)--we in all sincerity of mind salute you;
who are heirs with us of the same fulness of grace, mercy, truth, and holiness,
by which the Lord alone is acceptably served and magnified;
who over all is worthy:--and in holy reverence and fear,
be at this time ascribed all dominion, power, and strength, and obedience,
to Him that sits upon the throne, and to the Lamb forevermore.
Amen.

And again, dear Sisters, we salute you,
as called of God to partake with us of the heavenly inheritance of the saints in light,
and to be fellow-helpers with us in the blessed work of the Lord,
and in the dispensation of kindness and good will in love and mercy unto all,--according
to our proportion of faith in the heavenly manifestation of that power and eternal life,
which is in his Son:--by which we have been gathered,
not only to the number of God`'s elect ones, through obedience to His Spirit;
but also by his arm of power we were gathered to be a meeting,
to the praise of his grace,
distinct (as we may say in some respects,) yet in perfect unity with our brethren.
We being in that humility and subjection of spirit to the Lord,
and therein preferring them +++[+++our brethren,]
it shuts out all usurpation and the spirit of it; so that we in a sincere mind,
are workers together with them in the same faith; only distinct as to the place,
and in those particular things which most properly appertain
to us as women;--still eyeing the universal Head,
in whom male and female are one;
where no division can be admitted of;--so that the
body is held entire in Christ Jesus our Head.
We, as members by virtue of this our Head, do reach forth this unto you;
we having been as a kind of first-fruits unto God, in this service of a Women`'s meeting.

Dear Sisters, we are stirred in spirit, through the love of God,
for your information and encouragement as to what our services are,
and to stir up you also unto diligence to yours;
knowing how the Lord has been with us therein from the beginning to this moment;
with His power assisting, and instructing with His counsel,
and with wisdom furnishing us, as our various services have required,
continually to our soul`'s satisfaction,--and confirmation in our daily travail.
These services have been and are;--to visit the sick and the prisoners,
that suffer for the testimony of Jesus; to see,
they are supplied with things needful;--and relieving the poor,
making provision for the needy, aged, and weak,
that are incapable of work;--a due consideration for the widows,
and care taken of the fatherless children and poor orphans,
(according to their capacities) for their education and
bringing up in good nurture and in the fear of the Lord;
and putting them out to trades in the wholesome order of the creation.

Also, the elder women exhorting the younger, in all sobriety, modesty in apparel,
and subjection to Truth:
and if any should be led aside by the temptations of Satan any way,
endeavouring to reclaim such;--and to stop tattlers and false reports,
and all such things as tend to division among us;
following those things which make for peace, reconciliation, and union.
Also admonishing such maids and widows as may be
in danger through the snare of the enemy,
either to marry with unbelievers, or to go to the priest to be married or otherwise,
and so to bring a reproach or scandal upon Truth or Friends.
And that maid servants that profess Truth and lack places,
be orderly disposed of and settled in their services: and likewise,
that the savoury life and good order of Truth,
be minded between mistresses and their maids.
For these things, we have a care upon us; and that we may answer our duty herein,
we meet every second-day, to communicate each to the other, from our several places,
the several necessities and other services; that none may stand idle, but everyone,
as a true member in the true order of the church, may in their places be diligent:
for our services still increase many ways; but chiefly our work is,
to help the helpless in all cases, according to our abilities.

Although more especially our provision is set apart for
the supply of the household of faith and family of God,
yet we cannot be limited:
but as the universal bounty of the Lord makes his sun to rise on the good and bad,
and sends rain on the just and unjust; so the same bounty,
according to its measure in us, oftentimes finds the same object of charity,
which cannot (as we find freedom) send empty away.
But as on the Lord we wait, and our eye is single unto Him,
from whom we daily receive our living supply for these our services;
the Lord has been and is with us,
as often as we meet together,--answering abundantly with what his work calls for.
And his arm of power is over us, which at first gathered us; and in it,
is our preservation to this day:--to which power we commend you,
dear sisters;--and the Lord of all grace, power, and peace, be with you and us,
in all our services, to his glory and dominion,
whose right it alone is to reign in righteousness forever.
Farewell.

[.signed-section-signature]
From our Quarterly Meeting.

[.offset]
+++[+++_Signed by very many women Friends, among whom are,_ Ann Travers, Ruth Crouch,
Ann Whitehead, Patience Camfield, etc.]

[.signed-section-context-close]
London, the 4th of 11th month, 1674.

[.centered]
=== No. CXXII.

+++[+++The following document, copied from (probably) a circular in Ellis Hookes`' handwriting,
relates to the first establishment of the Meeting for Sufferings in London:
it gives the names of the London and Country correspondents,
with the regulations agreed upon for the constitution and regulation of the said meeting.
This document does not appear recorded in the minutes of the Meeting for Sufferings.]

[.blurb]
=== The names of the persons appointed to meet upon the account of Friends`' sufferings, also the names of the persons in the country, to whom they are to send, upon any occasion about sufferings.

[.offset]
==== Bedfordshire and Northampton:

* _In Town:_ John Staples, Frances Camfield

* _In Country:_ Edward Chester, of Dunstable, for Bedford. Daniel Wills, physician in Northampton.

==== Berkshire and Bucks:

* _In Town:_ John Osgood. Thomas Zachary.

* _In Country:_ Benjamin Cole, in Reading. Thomas Ellwood.

==== Cornwall and Devonshire:

* _In Town:_ Thomas Taunton. Gilbert Latie. Edward Brookes.

* _In Country:_ Lawrence Growden, at St. Austle, so called. Arthur Cotton, merchant, in Plymouth.

==== Hampshire and Surrey:

* _In Town:_ Ellis Hookes. William Mackett.

* _In Country:_ George Embree, at Southampton. John Cooper, at Guildford.

==== Sussex and Kent:

* _In Town:_ William Welch. James Braines. Walter Miers.

* _In Country:_ Luke Howard, shoemaker, in Dover.

==== Essex and Suffolk:

* _In Town:_ Richard Whityand. Thomas Yoakley. Francis Moore.

* _In Country:_ Soln. Formantell, in Colchester. Robert Duncan, tanner, near Mendlesham.

==== Norfolk and Cambridge:

* _In Town:_ Thomas Cox. Clem. Plumstead.

* _In Country:_ Samuel Duncon, hosier, in Norwich. William Brasier, shoemaker, in Cambridge.

==== Ely and Lincolnshire:

* _In Town:_ George Watts. William Parker. Thomas Hart. Ralph Rudyard.

* _In Country:_ Samuel Cater. William Garland, at Gainsborough. Yorkshire. John Hall, near Mongsgate, in York.

==== Durham and Northumberland:

* _In Town:_ Thomas Rudyard. William Meade.

* _In Country:_ John Ayrey, soapboiler, in Newcastle, for both these counties.

==== Cumberland and Westmorland:

* _In Town:_ William Loaithwaite. Francis Dow.

* _In Country:_ James Collinson, at Penwrith, shopkeeper. Bryan Lancaster, at Kendal, tanner.

==== Lancashire and Cheshire:

* _In Town:_ John West. Thomas Matthews.

* _In Country:_ Thomas Green, shopkeeper in Lancaster. Edward Morgan, shoemaker, in Chester.

==== Staffordshire and Derbyshire:

* _In Town:_ James Claypoole. Thomas Rudyard.

* _In Country:_ William Fallowfield, at Leek. William Storrs, at Chesterfield, shopkeeper.

==== Leicestershire, Nottingham, Rutland:

* _In Town:_ John Elson. Arthur Cooke. Richard Mew. Thomas Robertson.

* _In Country:_ Samuel Wilson, baker, in Leicester. John Reekless, shopkeeper, in Nottingham.

==== Worcester and Gloucestershire:

* _In Town:_ Gerrard Roberts. Ezekiel Wooley.

* _In Country:_ Edward Bourne, physician, in Worcester.

==== Herefordshire and Shropshire:

* _In Town:_ Phillip Ford. John Dew.

* _In Country:_ James Merrick, at Ross. Constantin Overton, at Shrewsbury.

==== Warwick and Oxfordshire:

* _In Town:_ Francis Bellers. William Crouch. Hugh Lamb.

* _In Country:_ John Murdock, baker, in Coventry. Silas Norton, maulster, in Oxford.

==== Hunts and Hertfordshire:

* _In Town:_ Job Bolton. William Ingram.

* _In Country:_ Richard Jobson, fellmonger, in Huntington. Henry Stout, maulster, in Hartford.

==== Wiltshire:

* _In Town:_ Arthur Cooke. Ellis Hookes.

* _In Country:_ Thomas Neat, at Chipenham.

==== London and Middlesex:

* _In Town:_ Thomas Cooper. William Meade. Joseph Scott. John Kimble.

* _In Country:_

==== Bristol:

* _In Town:_ James Claypoole. Ezekiel Wooley.

* _In Country:_ Thomas Gouldney, grocer in Bristol.

==== North Wales:

* _In Town:_ William Goswell. Edward Man. Potter Evans.

* _In Country:_ Richard Davis, hatmaker in Welchpoole.

==== South Wales:

* _In Town:_ Benjamin Antrobus. William Poacher.

* _In Country:_

==== Ireland:

* _In Town:_ Samuel Newton. James Claypoole. William Penn.

* _In Country:_ Samuel Clarredge, merchant, in Dublin.

==== Scotland:

* _In Town:_ William Welch. John Swinton. Gawen Lawrey.

* _In Country:_

==== Barbados:

* _In Town:_ Thomas Hart. Gerrard Roberts.

* _In Country:_

==== New England, New York:

* _In Town:_ William Meade. Joseph Scott.

* _In Country:_

==== Virginia and Maryland:

* _In Town:_ Samuel Groom. Francis Camfield. James Braines.

* _In Country:_

==== Nevis and the Leeward Islands:

* _In Town:_ John Goodwin. Hugh Hartshorn.

* _In Country:_

==== Jamaica:

* _In Town:_ Edward Brush. William Crouch.

* _In Country:_

==== Holland:

* _In Town:_ William Crouch. William Welch.

* _In Country:_

[.small-break]
'''

At a meeting of aforesaid Friends and others, assembled upon the account of Sufferings,
held at James Claypole`'s, the 12th day of the 4th month, 1676:

[.offset]
Agreed as follows:

[.numbered-group]
====

[.numbered]
1.--That the whole Friends appointed for the Meeting of Sufferings,
do all meet the fifth-day next preceding every term.

[.numbered]
2.--That one-fourth part of the Friends of this meeting,
be nominated and appointed to meet weekly, every fifth-day,
at or before the eleventh hour in the forenoon, as a weekly Meeting for Sufferings;
leaving a liberty to any other faithful Friend concerned to meet with them:
which said Friends so appointed, are to continue as the Meeting for Sufferings,
until the fifth-day next before the next ensuing term;
and then a new choice to be made,--one other fourth
part of the Friends appointed for Sufferings,
to attend the next ensuing quarter, weekly as aforesaid;
and so for every fifth-day next preceding each term,
a new choice and appointment of other Friends,
to attend the service of Sufferings as aforesaid.

[.blurb]
=== The names of the Friends appointed for the present immediate service, to continue till the General Meeting for Sufferings, appointed to meet the fifth-day next before next term.

[.offset]
_Westminster:_
Gilbert Latey, Francis Dow.

[.offset]
_Wheeler Street:_
Francis Moore.
Francis Beller.

[.offset]
_Ratcliffe:_ Arthur Cooke.
James Braines.

[.offset]
_Southwark:_ William Shewen.
Henry Snook.

[.offset]
_Peele:_ William Parker.
John Elson.

[.offset]
_London:_ John Osgood.
Thomas Rudyard

[.offset]
_Foreign Parts:_ Thomas Hart and Joseph Scott.

[.small-break]
'''

[.numbered]
3.--That if any of the said fourteen Friends now nominated,
(or others to be hereafter nominated and appointed for this
service,) by reason of any urgency of occasions or business,
cannot attend at any respective meeting as aforesaid, that then such respective member,
send (if they can) a note to that meeting,
informing the meeting of their not being able to be there that day.

[.numbered]
4.--That Ellis Hookes, as well forthwith as from time to time hereafter,
send down into the several counties of England and Wales,
unto the Friends there appointed to correspond,
as well the agreements now made and to be made for the settling of this meeting,
as also the names of such persons here with whom they are now, or for the future,
from time to time to correspond;
that the country Friends may henceforward understand Friends`' care and order therein,
and direct their letters to the persons here appointed accordingly.

[.numbered]
5.--That only the present sufferings,
wherein the Friends in the counties expect some relief or redress,
be sent to the Friends of London before nominated to assist the Friends in the country;
and that such sufferings as are collected and intended to be recorded,
be as formerly sent to Ellis Hookes.

[.numbered]
6.--That a list or copy of all the Friends here of the Meeting of Sufferings,
and the names and habitations of all the country correspondents now appointed,
or to be appointed, be now and from time to time, with the agreements of this meeting,
delivered to each member of this meeting,
or at least to one of the two Friends respectively appointed,
or to be appointed here for each county;
that so each member thereof may know their respective service.

[.numbered]
7.--That when any Friends appointed here to correspond with the respective counties,
receive any letters from their respective counties,
that they take due care to send them expeditious answers to such questions,
or other matters, or things proposed to them,
or for which the country Friends desire their assistance in advice or otherwise;
and also give them speedy answers whether their respective cases and sufferings,
can have relief here or elsewhere, or not;
so that our country Friends may not lie under a tedious and fruitless expectation,
without our resolution, in cases of difficulty, distress, and suffering.

[.numbered]
8.--That a convenient room be allowed and taken,
for the Friends now and hereafter appointed, to meet weekly in, as aforesaid,
in such convenient place, as Gerrard Roberts, William Welch,
and John Osgood shall allow and approve of;
and that until such convenient room can be had and taken,
that the meeting be held and kept weekly, at Job Bolton`'s in Lumber street.

[.numbered]
9.--That country Friends be reminded of what formerly was signified unto them,
where the circumstances of time will admit,
to lay their sufferings and cases before Friends in their Monthly or Quarterly Meetings,
or two or more faithful Friends of that county;
to the end their cases and sufferings may be sent up, or recommended,
with the meeting`'s or particular Friend`'s testimonial and approbation.

[.numbered]
10.--That if any matter or thing happen in the interval of Monthly or Quarterly Meetings,
that then they lay the said sufferings before two
or more faithful Friends of the county as aforesaid,
appointed by the Monthly or Quarterly Meetings for that purpose;
and the names of such Friends to be sent up to Friends here.

[.numbered]
11.--And further, that Friends be careful to draw up their sufferings full and short,
according to former directions; it being the intention of Friends here, once a month,
to publish in print half a sheet or a sheet,
of the most remarkable and grievous sufferings;
to the end cruelty may not be acted in a corner, and not be known.

====

[.centered]
=== No. CXXIII.

+++[+++The following document has been found in the catalogue of George Fox`'s writings;
it is inserted under the year 1690:--in several respects it is a remarkable document.]

[.small-break]
'''

All Friends in all the world,
that used to write to me of all manner of things and passages,
and I did answer them,--let them all write to the Second-day`'s Meeting
in London directing them first to their correspondents there;
and the Second-day`'s Meeting in London, for them to answer them in the wisdom of God:
and let a copy of this be sent to all places in the world among Friends,
that they may know and understand this.

And for the Yearly Meeting in London,
to answer all the yearly and half-yearly letters or papers
that come once a year to the Yearly Meeting in London;
and they to see that all be carefully read,
and answered in the Truth and in righteousness, to the glory of God,
and to the comfort and refreshment of His people.

[.signed-section-signature]
George Fox.

[.offset]
+++[+++_From a copy._]
