== Part III. Epistles Of Counsel And Exhortation

[.centered]
=== No. CXXIV.

[.letter-heading]
Richard Farnsworth to Friends

[.signed-section-context-open]
From Balby, December (or 10th month) 2nd, +++[+++12th month]
1652.

All Friends in the Truth of God, be faithful in what you know;
and wait upon the Lord for the making out of himself to you.
Neglect not meeting together, and stirring up that which is pure one in another.
Live not in words, but mind the power of words: for words that proceed out of a vain,
light mind, destroy the simple, and draw your minds out above the cross,
to live in words;--and you will form something in your minds to rest in,
and so the fleshly mind will be kept alive:--but keep in the cross.
The power is the cross to the carnal part in all;
and words that come from the life will go to the life,
and raise up that which is pure in one another;
and so you will have unity with that which is pure in one another.

And being guided by the pure light in you,
it will cross that which would be forming anything in you;
and standing in the counsel of the Lord,
it will cross and crucify that which would consult with human wisdom and reason.
So you will be brought into a discerning, to savour truth from error, both in yourselves,
and also in one another,--and to savour everyone`'s words from what centre they do arise.
By standing in the counsel of the Lord, and keeping in the cross,
the old man will be brought to judgment daily; and that which is earthly, carnal,
and brutish, will be cut down in you;
and so there will be a way made for the pure seed to be raised up in you,
that the Lord alone may be glorified by every one of you.
Take heed of sitting down to rest in any gift; but press forward in the strait way,
and lay aside every weight and burden.
Cast off that which presses down, and let patience possess your souls;
endure to the end the working out of the corrupt nature,
and wait for the purification of the Lord, who will try you so as by fire.
Think it not strange concerning the fiery trial by
which the Lord will try you and prove you;
the trial of your faith will be much more precious than of gold that perishes.

Farewell, dear Friends;
and the God of love and power keep you all in the power of his love,
and in the power of his Truth, in faithfulness to Him alone,--that He maybe glorified;
to whom all honour and glory and dominion, praise and thanks belong, forever and ever!
Amen.

[.signed-section-closing]
Yours in the unity of the Spirit,

[.signed-section-signature]
Richard Farnsworth.

[.offset]
+++[+++_From the original apparently._]

[.centered]
=== No. CXXV.

+++[+++The following valuable letter is the more interesting,
as having been addressed at that early period to Margaret Fell (who became so conspicuous,
as a nursing mother in the church,) within about
six months after George Fox`'s first visit at Swarthmore;
when she, her children, and a great part of her servants became convinced.]

[.letter-heading]
Richard Farnsworth to Margaret Fell

[.signed-section-context-open]
Balby, +++[+++Yorkshire]
December 12th, +++[+++12th month]
1652.

[.salutation]
Dear Sister,

Mind to stand in the counsel of the Lord,
which will keep down everything that would be exalted;
and will not allow you to conform to anything but that which is pure.
O! be faithful, be faithful, in what you know; and stand perfect in the will of the Lord:
and the Lord will keep you in his own power to Himself,
and arm you every way with his love and power.--Stand in his counsel,
and it will discover all the consultations of the enemy;
and will scatter all imaginations, and will not allow them to take place in you,
being but obedient to Him.
Love not the world,
but mind that which would draw you to live in the pure obedience of Him who is pure:
and standing in the pure fear, it will take away all slavish fears,
and it will not allow you to conform to the world in anything;
but you will be preserved in obedience to the Lord, in what he does require:
for the fear of the Lord keeps the heart clean; and it will keep you clean,
and open to receive the teachings of the Father.

O! stand fast in the liberty with which Christ has set you free,
and it will keep you from the entanglements of the world; and your preservation will be,
in standing in the counsel of the Lord, who is the mighty counsellor,
the everlasting Prince of peace;
who will lead you and guide you into the everlasting kingdom of the Father,
where there is peace and joy, rest, quietness and assurance forever!
Give yourself up wholly to the Lord,
who will preserve you in faithfulness and purity;--and the everlasting
Lord God Almighty keep you and all the rest of our dear Friends,
in the power of his love, and in the power of his Truth, perfect in his will;
that you may grow from strength to strength,
and be established in the everlasting Truth:--and that he alone may be glorified,
who is Lord of lords, and King of kings; to whom be glory and honour, and praise,
and thanks, forever and ever!
Amen.

I received your letter, which did much rejoice me.
When your letter, with James and George, came,
I was then gone towards Derbyshire--where I met with a gathered church.
I have been in much service since I came from you:
Friends are much emboldened and courageous,
who have had great opposition and persecution here away: but all is at a stand;
the enemy is much in silence; and the Lord carries on his own work,
much to his own praise: to Him alone be glory, and honour, forever and ever!

My dear love in the Lord presents itself to you all, to your son George,
and to your daughters, and to all those your servants, in the Truth of God:
and the Lord cause them all to grow up into the Truth,
that He may be exalted among you all.
Ah! my dear hearts, prize the love and mercy of the Lord,
and daily mind your growth into that which is eternal:
and the everlasting love and power of the Lord keep
you all in faithfulness to Him in what you know.
Keep in the cross, and purity will grow;--the safest way is in the cross;
take up the cross daily; mind to be guided by that which crosses your own wills,
and it will bring every idle word, thought and deed to judgment in you;
and so the old man will be crucified, with the affections and lusts thereof;
and you shall find the Lord to sit as a refiner, to judge out all the old leaven,
the old nature;
and so the new man will be raised up;--and Christ the power
of God will rule and reign in righteousness in you,
who is the King of saints: to Him alone be all praise and thanks forevermore!
Amen.

[.signed-section-signature]
Richard Farnsworth

[.offset]
+++[+++_From the original apparently._]

[.centered]
=== No. CXXVI.

[.letter-heading]
Richard Farnsworth to Friends

[.signed-section-context-open]
Warmsworth, 18th of 7th month, +++[+++9th month]
1657.

[.salutation]
Dearly beloved in the Lord!

All be watchful and faithful against the enemy and adversary of your souls;
that you may stand, when you are tried.
The Lord will try you, like gold seven times purified;
and as you have had experience of God`'s love to you, and care over you,
when formerly you have been proved,--know assuredly that
He is the same;--and mind that you be so to Him,
still loving and faithful to Him and his Truth,
all you that in any measure have borne testimony to his name.
Take heed of coldness, deadness, and formality, that it get not entertainment among you;
lest thereby the enemy beguile you, and you lose your reward.
Therefore mind the movings and stirrings of that of God in you;
that you may move and stir in it in the behalf of His name.

Stand not to consult with the wicked one; but keep close, in the spirit of your minds,
to the measure of the light and Spirit of God manifested in you,
rightly to inform and guide your understanding;
that none of you may join with that which would draw you back,
lest the Lord`'s soul cease to delight in you.
For so long as you do well, you are the children of Abraham the father of the faithful:
but if any of you depart in the evil, he owns you not then,
no more than Christ did such as said they were of Abraham, while they were evil doers;
who also told them, that if they were of Abraham, they would do the works of Abraham;
but they did not his works,
and therefore they were known to be none of the true faithful Abrahamites.
Take heed that none of you give Him just cause to depart from you,
and leave you to yourselves.
He can and does wait to be gracious, and is ready to do good,
to those that truly and constantly wait and attend upon him.
Such are ever ready to speak well of Him, to the praise of His name: but the disobedient,
obstinate, slothful, and careless, they judge hardly of Him.

Take heed that none such be among you; for they will, upon trials,
be ready to join with the enemy, and start aside to the rejoicing of the wicked,
and to the dishonour of the seed; though they may profess the Truth for a time.
Take heed of watching with an evil eye,
and for seeking occasion one against another to break the true unity.
Such break their soul`'s peace, and their troubles will increase upon them:
but they that watch one over another, in the fear of the Lord, for good to edification,
and to mind the increase of love and preservation of the true unity,
their peace and joy in the Lord will increase, and they are, and shall forever be,
blessed.

[.signed-section-signature]
Richard Farnsworth

[.centered]
=== No. CXXVII.

[.letter-heading]
Alexander Parker to Friends

[.signed-section-context-open]
Given forth the 14th of 11th month, 1659, +++[+++1st month 1660.]

To all who are lovers of, and believers in, the true light,--grace, mercy,
and everlasting peace be multiplied among you.

Dear and precious souls, the infinite wise God, who is pure forever,
is just and equal in all his ways; who loves truth and delights therein;
who is strong and mighty to deliver, and able to save from sin and Satan,
from bondage and corruption, all who come unto him, and wait upon him in truth,
in meekness and sincerity of heart.
He is the God of the spirits of all flesh, who gives life and breath unto all;
who made the world and all things therein, by his power, and by his word,
(which is powerful;) He upholds all things at this day and time.
He is the same today as ever, in power and majesty;
his arm is not shortened that it cannot save, nor his eye closed that it cannot see,
neither is his mouth shut that it cannot speak; but he lives, and works, and speaks,
and sees, and discerns what is contrived and acted among the sons and daughters of men.
His living Word abides forever,
and is as quick and as lively as ever,--as powerful
and sharp for the cutting down of sin and corruption,
as it ever was in the days of old and ages past,
according to the testimony of the holy men of God, recorded in the Scriptures of truth.

Dearly beloved, it has pleased our gracious almighty God to appear in these last times,
according to his promise declared by his holy prophets concerning his great love,
in pouring forth of his holy Spirit upon his people;
and to gather them from off the barren mountains, and from the mouths of the wolves,
and all false shepherds; that they might no longer be preyed upon,
nor starved for lack of bread: but the promise of God is,
to feed them Himself in fresh and green pastures,
and to bring them back into the fold of the good shepherd,--and
that there shall be one sheepfold and one shepherd.
Dear hearts, both I and you, and all the rest of the sheep and lambs of Christ,
may truly confess and say, that we all like sheep have gone astray;
we were wandering upon the barren and dry mountains,
and feeding upon the husks and empty shadows, even as well as others.
But forevermore blessed and praised be the Lord our God,
who in a good and acceptable time did appear, and stretched forth his holy arm,
and gathered us into the fold of the good Shepherd;
whereby we are refreshed with the favour and lovingkindness of the Lord.
O! what manner of love is this, that even when we were enemies and rebels against God,
yet his eye was over us for good; and he waited to be gracious unto us,
(as he does now unto the world,) not willing the death and destruction of any;
but rather that all might turn unto him, and hearken unto his voice,
that their souls might live.

Dear Friends, as the Lord in his rich love has visited you,
and by his grace called you out of darkness into his marvellous light,--so,
prize his love, and walk worthy of that high and heavenly calling,
whereunto the Lord has called you,--pleasing him in all things: waiting in the light,
which is pure, which is of Christ, in you,
that you may all receive wisdom and counsel from God; that whatever you do,
or take in hand, may be done to the glory and praise of Him that has called you.
Remember, and always keep in mind the goodness of the Lord,
and let his word dwell and abide in you; lay it up in your hearts,
as a precious holy treasure: so will you be kept in a lively sensible state,
apt and fit to receive instruction from the Lord.
The living word seasons, and keeps the heart sweet and savoury,
so that corruption cannot grow there, neither any other evil, lust or bad thing;
but by the word it is cut down, and destroyed.
Blessed are they that keep the word of God in them;
such shall be kept in peace and unity with God in the light;
and there everyone shall see the honourable calling, unto which they are called.

He that calls, is holy and honourable; and the calling unto which you are called,
is likewise holy and honourable.
Consider what you are called from, and what you are called unto:
formerly you walked in darkness,
and had fellowship with the unfruitful workers of darkness;
now you are called out of darkness,
to walk in the light,--and there to have communion one with another,
and fellowship with God, who is light,
and with his Son Jesus Christ;--who likewise declared
himself to be the light of the world.
In the light is the precious unity with God and with Christ, and one with another.
If we walk in the light, (says the beloved disciple,) as He is in the light, then,
(not till then,) have we fellowship one with another,
and the blood of Jesus Christ his Son, cleanses us from all sin:
they that love the light, and believe in the light,
and walk in the light,--such receive remission of sins,--such worship God truly,--such
are of one heart and of one mind,--such only are accepted of the Lord.

And now, dear souls, as you have been called to such a high and heavenly calling,
everyone mind your particular duties, in walking answerably to the Lord in everything;
that good order may be kept among you, both in your meetings and solemn assemblies,
in your service and worship of God,
and also in your common occasions and affairs among men.
Something is upon my spirit to write unto you at this time,
concerning these two weighty things; and, first,
concerning the service and worship of God.--That which God requires of everyone,
is justice, mercy, and a humble and orderly conduct: for, as it is the love of God,
by his light to show you his will and mind, so it is your duty, to do the will of God;
which will is your sanctification: and,
as it was the manner and practice of the holy men of God,
(who were called in the light,) to meet together to wait upon God,
and to speak one to another, as the Spirit of Truth did move and give them utterance,
for the strengthening one another,
and building up one another in their most holy faith;--so it is
now judged fitting and good for all who are called to be saints,
to meet often together to wait upon the Lord,--that their strength may be renewed.

So Friends, when you come together to wait upon God, come orderly in the fear of God:
the first that enters into the place of your meeting, be not careless,
nor wander up and down, either in body or mind; but innocently sit down in some place,
and turn in your mind to the light, and wait upon God singly,
as if none were present but the Lord; and here you are strong.
Then the next that comes in, let them in simplicity of heart,
sit down and turn in to the same light, and wait in the Spirit:
and so all the rest coming in, in the fear of the Lord,
sit down in pure stillness and silence of all flesh, and wait in the light;
a few that are thus gathered by the arm of the Lord into
the unity of the Spirit,--this is a sweet and precious meeting,
where all meet with the Lord!

Those who are brought to a pure, still waiting upon God in the Spirit,
are come nearer to the Lord than words are: for God is a Spirit,
and in the Spirit is he worshipped; so that my soul has dear union with you,
who purely wait upon God in the Spirit,
though not a word be spoken to the hearing of the outward ear.
And here is the true feeding in the Spirit;
and all who thus meet together to wait upon the Lord, shall renew their strength daily.
In such a meeting, where the presence and power of God is felt,
there will be an unwillingness to part asunder, being ready to say in yourselves,
it is good to be here:
and this is the end of all words and writings--to
bring people to the eternal living Word.
So, all dear hearts, when you come together to wait upon God, come singly and purely;
that your meetings together may be for the better, and not for the worse.

And if any be moved to speak words, wait low in the pure fear,
to know the mind of the Spirit, where and to whom they are to be spoken.
If any be moved to speak, see that they speak in the power; and when the power is still,
be still.
And all who speak of the movings of the Lord, I lay it as a charge upon you,
to beware of abusing the power of God,
in acting a wrong thing under pretence of being moved
of the Lord:--for the pure power may move,
and then the enemy (who goes about like a roaring lion,
seeking whom he may devour,) he may present a wrong thing to the view of the understanding;
and here is a danger of abusing the power, acting in that which the true power condemns,
and yet pretending that the power moves to it;--this is a double sin.
Therefore, let everyone patiently wait, and not be hasty to run in the dark;
but keep low in the true fear,
that the understanding may be opened to know the mind of the Spirit;
and then as the Spirit moves and leads,
it is good to follow its leadings;--for such are led into all truth.

Thus, my Friends, as you keep close to the Lord, and to the guidance of his good Spirit,
you shall not do amiss; but in all your services and performances in the worship of God,
you shall be a good savour unto the Lord; and the Lord will accept of your services,
and bless and honour your assemblies with his presence and power.
And now for the ordering of your conversations among men,
you are to walk by the same rule; (that is,)--when your meeting is ended,
do not look upon the service of God to be ended; but keep in the fear of God,
that you may receive wisdom from Him, to order the creatures;
that the pure light may exercise your consciences towards God and men.
A time there was at your first convincement,
when you stood in the cross to the world`'s spirit,
and could not conform to their customs, many of them have stood off for a certain time,
and would not trade or deal with Friends: but when they saw your fidelity and honesty,
they came again; and many have a greater desire to deal with Friends,
than with many of their own generation, because they know that you will not wrong them,
nor deal deceitfully with them: and so the blessing of God attends the faithful,
and gives an increase both inward and outward.

Then is the danger of being lifted up in mind, or drawn back again into the earth,
so that the earth comes over, which chokes and hinders the growth of the seed:
but as everyone keeps in the dominion and power of God, then the blessing is continued,
as love to the Truth is continued.
Thus, dear Friends, in all companies, at all times and seasons,
so walk that you may be examples of good unto all, and answer the witness of God in all;
that God over all may be glorified,
and you by his power be daily kept and preserved in holiness and righteousness,
out of the world`'s wickedness; not for a day, or a week, or a certain time only,
but even all the days of your lives; for this is but just and reasonable,
that we should yield our members servants unto God, who gives us life, and strength,
and all other good things: glory and holy praises be rendered unto Him,
of all that know Him, forevermore!

And furthermore, dear Friends, as concerning those late overturnings,
and those distractions, divisions,
and confusions in this our native nation,--be not
troubled nor shaken in mind because of these things.
There is a secret hand working in and through all these overturnings;
and they come not to pass without the knowledge of the Lord,
for making way for greater things, which the Lord has to bring to pass in this nation;
for much is yet to be thrown down, before truth and righteousness be set up.
My advice and counsel is, that every one of you, who love and believe in the light,
be still and quiet, and side not with any parties;
but own and cherish the good wherever it appears, and testify against the evil in all,
wherever it appears; not like the children of this world,
warring with carnal weapons against flesh and blood, to destroy men`'s lives;
but like Christians with spiritual weapons, warring against spiritual wickedness,
and all sinful fleshly lusts, which war against the soul: not striking at creatures,
but at the power that captivates the creatures;
that so the creatures may be redeemed from the bondage of corruption,
into the glorious liberty of the sons of God.
So be not overcome by evil, but overcome evil with good;
so shall you have peace with God, and true unity with all who are of God.
The God of power strengthen you in every good word and work, and perfect his work in you,
to his glory, who is blessed forever!
Amen.

I rest your dear brother in the Truth, watching for all your good,

[.signed-section-signature]
Alexander Parker.

[.offset]
+++[+++_From the original._]

[.centered]
=== No. CXXVIII.

[.letter-heading]
Alexander Parker to Friends

[.signed-section-context-open]
Given forth in the prison at Chester, the 13th of the 8th month +++[+++10th month]
1660.

To all you, my beloved and dear Friends, who are called in Christ Jesus,
the light of the world, out of the ways and works of darkness,
to follow the Lord Jesus Christ in truth and righteousness, which way soever He goes,
through trials and troubles, tribulations and persecutions,
as he leads and guides by his light and Spirit:--Grace, mercy, and peace,
patience and heavenly wisdom,
with all other graces and virtues appertaining unto life and godliness,
from God the Father of Spirits, and Jesus Christ the light and life of men,
be increased and daily multiplied among you.

I, your dear brother and companion in tribulation,
who am a prisoner for the testimony of Jesus, do hereby greet you all,
who love and own the appearance of Christ in Spirit.
I do send these lines unto you as the tender of my love,
and the dear salutation of my life unto you all, my dear brethren and sisters;
who are born again of the immortal seed and word of God, which lives and abides forever.
My life is bound up with you, in the holy love and blessed covenant,
which cannot be broken;
and though this earthen vessel be shut up and kept under locks and chains,
from the fellowship and communion of my Father`'s children and family,
yet the treasure--the heavenly riches of love, life and power,
which my heavenly Father has put into this earthen vessel,
cannot be locked up by the powers of this world, neither can it be stopped;
but it flows forth according to the promise of the Lord of life, who has said,
"`Whoever shall drink of the water that I shall give, it shall be in him a well of water,
springing up unto everlasting life.`"
From this well, do streams of love flow forth, even to my very enemies and persecutors;
desiring also that their souls might live.
But much more do my love and breathings of life reach forth unto you,
the dearly beloved of my soul, who are of the same family and household of faith;
to everyone in the family, as well the servants and the handmaids,
as the sons and daughters, my dear love salutes you all,--even the doorkeepers,
and all that appertains to the house of God.
I have you all fresh in my remembrance, and am often present in Spirit with you.

Dear hearts, in brotherly love and heavenly fear, I do exhort you all, as dear children,
to walk together in truth and love; exhorting one another,
and building up one another in the holy faith, which works by love;
that you may be a family of love:
for true love is a mark whereby you are known to be children born from above,
as Christ formerly said, "`Hereby shall all men know that you are my disciples,
if you love one another;`"--this is the end and the sum
and substance of all that can be spoken or written.
Love fulfils the law,--it envies not, it thinks no evil;
love does not render evil for evil, but on the contrary, love renders good for evil:
love keeps the commandments of God; and if love be lacking, all preaching, praying,
and all other duties and performances whatsoever, all are in vain:
and the services and sacrifices of such are not acceptable unto God,
being ignorant of God; for he that loves not, knows not God, for God is love.
Love is a precious jewel, not to be valued with gold, nor any other earthly treasure;
and where love dwells, there needs few instructions;
for love performs all things freely without compulsion:
blessed are they who have the love of God dwelling in them.

But this is a high discovery, to know God as he is love; it is the last,
and abides forever.
Wait, dear ones, that you may attain to this knowledge;
and in the mean time be content with your present conditions,
and with that measure of knowledge which God has committed to every one of you;
for everyone is accepted, as they are faithful to God,
in that light and grace which God has freely given to them.
And it is a good thing to know God truly and experientially in any dispensation,--to
know God (or the operation of his Spirit,) as a fire,--this is good;
for all who are truly acquainted with God, must know him as a consuming fire,
before they know him as he is love;
"`For our God is a consuming fire,`" as it is written of him;--a
fire to consume and burn all wickedness and sinful lusts,
which have been harboured and lodged in the heart;
so that the heart may be purified by the spirit of judgment and burning,
and sanctified and made fit for the Father`'s use.

For though it has pleased God, so far to condescend and come down, as to dwell in men,
and to put his heavenly treasure in earthen vessels;
yet he does not dwell where sin and corruption dwell;
neither does he put his precious heavenly treasure in a filthy unclean vessel;
but first the vessel must be cleansed, the heart purified, by the living word of God:
for the word of God is powerful and precious,
and does work powerfully in the hearts of all that
do with meekness and patience receive it.
It is as a fire to burn up all corruption, both of flesh and spirit;
it is also as a hammer to beat down sin in its rise and conception:
when evil appears or rises in the heart, then keep the hammer going,
(the word of God,) to hammer it down within on the first motion,
before it break forth into words, or open actions.
Blessed are they that feel in themselves the operation of the word of God,
to purify and cleanse them, and who obey the gospel in truth of heart;
that God may delight to do them good.

And you, my dear Friends, that have tasted of the word of God,
and are truly sensible of a good work of reformation
begun in you,--in patience possess your souls:
wait upon God, and faint not; neither be discouraged,
because of the many trials and temptations that you endure; but sow to the Spirit,
and in good time you shall reap the good fruits of righteousness.
Be not shaken in mind, nor tossed to and fro with men`'s doctrines, which are changeable;
but all dwell and abide in the unchangeable light,
and let your faith stand in the power of God: and then you will stand sure and steadfast,
upon the sure foundation of God, which he has laid, and not man;
and as you are stayed there, nothing can move you, nor harm you, nor make you afraid.
The word of God is near you, even in your hearts, and in your mouths,
to obey it;--O! let it dwell and abide in you, and it will keep you from corruption,
and from all evil that abounds in the world.

So, dear Friends, as a people redeemed to God,
see that you walk blameless and harmless in the midst of this perverse generation;
that you may be a good savour to God among them,
that the Lord God of life may be glorified in and among you.
Be patient, be humble, and of a gentle, sweet carriage towards all,
so far as you may without offence to God or his dear children; and above all things,
live in peace and love among yourselves.
And the God of peace fill you with his peace and love and heavenly wisdom,
and establish you in the Truth; that you may live and die to his honour and glory,
who has called and loved you;--who is God over all, blessed forever.

This is written in the depths of love unto you all, by your dear brother,
a prisoner for the testimony of Jesus, in the common jail at West Chester.

[.signed-section-signature]
Alexander Parker.

[.offset]
+++[+++_From the original._]

[.centered]
=== No. CXXIX.

[.letter-heading]
Richard Farnsworth to Friends

[.signed-section-context-open]
Stanley, 11th of October (8th month)

[.salutation]
Dear Friends,

My endeared love to you all in the Lord Jesus Christ:--my love runs forth toward you,
desiring that the Lord would establish your hearts in Him;
who is the fountain of living mercies.
Wait on Him, and meet often together; and take heed of forming anything of self.
Stand always in the counsel of the Lord; and give up wholly to Him, to be guided by him.
Submit to his will in all things, and every condition will be good,
seeing the Lord always present in it.
Take heed to yourselves, lest any deceit get in among you;
for the adversary is very busy, and goes about like a roaring lion,
seeking whom he may devour:
and when the Lord is most manifesting himself among his people,
then the devil does most bestir himself.
There is a true work among you; but take heed, I beseech you for the Lord`'s sake,
that deceit does not mix with it.
Give not liberty to your own wills, but stand in the will of the Lord,
and let patience have its perfect work among you.--And
you shall find him a merciful Father;
and he will deal with you in tenderness and compassion.

Take heed of doing anything by imitation as from others;
but all mind your own conditions, and to be kept in the cross,
the pure light guiding your minds; it will cross your own wills in all things,
and will allow you to conform to nothing but that which is pure;
and so you will be kept always in the fear of Him who is pure:
and his pure fear will preserve and keep your minds close and pure,
and open to the Lord to receive his teaching,--for the teaching of the Lord is in silence.
And wait patiently upon Him, and give up yourselves wholly unto Him,
to be acted upon and guided by Him; and He will keep self under the cross,
that it cannot act;
and so you will be led by the Lord gently on your journey up to the land of living mercies,
where you shall find rest to your souls, even in the everlasting fountain of love.

Dwell in the pure wisdom, and it will teach you what to do in all things.
Walk in the light, and there will be no occasion of stumbling and falling:
but being disobedient to the light, then there is stumbling and falling down.
Everyone mind your own condition and your growth daily:
press forward in the straight way, and so be kept in the cross,
that keeps humble and lowly:--and being kept in the cross,
it will bring you to lay aside every weight and burden,
and to run with patience the race that is set before you;
that you may so run as to obtain the crown.
O! dear Friends, let patience possess your souls,
and it will keep you always in a sense of your condition.
The Lord keep you, and establish you,
that you may grow daily more and more into the everlasting Truth,
and bring forth fruit to the praise and glory of God;
that He in all things may be glorified by you:
to whom be glory and honour and everlasting praises forever and ever.
Amen!

All Friends here are well, praised be the Lord,--and desire to be remembered to you all.
My dear love to you all,--farewell;
and the God of love and power keep you in the everlasting power of his love,
and in the everlasting power of his Truth; that you may reign as kings upon the earth.

I shall see you again, when my Father pleases.

[.signed-section-signature]
Richard Farnsworth.

[.centered]
=== No. CXXX.

[.letter-heading]
Thomas Salthouse to Friends

[.blurb]
=== An affectionate salutation of fervent love, and a tender visitation to all the people of God called Quakers, at this day oppressed and persecuted for their obedience to the commands of Christ Jesus, the King of Righteousness, and Prince of Peace.^
footnote:[This and the next epistle from John Whitehead were addressed to Friends,
at about the commencement of their very severe persecutions in Charles II`'s reign.]

[.signed-section-context-open]
12th month, 1660, +++[+++2nd month 1661.]

Beloved Brethren and Sisters,
fellow-sufferers and companions in tribulation and persecutions,
which is your portion and heritage at this day in this present world,--my heart is open,--and
my dear unfeigned love flows forth abundantly unto every individual of you,
in every desert, den, and cabin, to which many of you are by constraint confined,
for your obedience to the commands of Christ,
the Prince of our peace,--and for your resolutions to follow the Captain of your salvation,
with the loss of your liberty, the hazard of your estates, and the peril of your lives,
in these last days and trying troublesome times.
O! my dearly beloved, whom the Lord has called and chosen out of the evil of the world,
and redeemed from the earth, to serve him acceptably, and to worship him in the Spirit;
unto whom it is given in the behalf of Christ Jesus, not only to believe,
but also to suffer affliction and persecution,--what can I communicate unto you,
that may augment your consolation in this day of trial and hour of temptation?
You have the evidence with you, and in you, that the Lord is your portion,
and the rock of your salvation;
and He that comforts his people in all their tribulations, is acquainted with your grief;
in all your afflictions he is afflicted with you;
and whosoever offends you for your religion and righteousness`' sake,
sins against his own soul, and resists his Maker,--against whom no man can prevail.
He that persecutes you, persecutes your Head; he that touches you,
touches the apple of his eye.

My dear brethren and Friends in the Truth,
who are now constrained to have your habitation as in the tents of Kedar,
among the sons of Ishmael and Belial, and whose lot, for a little season,
is to be among the pots, and to sit as by the rivers of Babylon,
in outward bondage and captivity,--think it not strange concerning these fiery trials,
as if an unexpected or strange thing had accidentally happened unto you:
for this day of trial of your faith, patience, and principles, is very precious,
and the Lord`'s end in it is good, and will so appear to be; and in an acceptable time,
will he appear for the salvation of his oppressed people, whose sighs and groans,
prayers and tears are heard and regarded by him.
For he brought you not out of the house of darkness and land of Egypt,
to slay you in the wilderness, nor to make you a prey to the uncircumcised,
if you obey his voice, and abide in his counsel, and walk in his light,
as a people saved by him.

Therefore, my dear Friends, let patience have its perfect work;
and remember the Lord`'s former mercies and wonderful deliverances,
and consider that his hand is not at all shortened,
that he cannot save and deliver you out of the deepest den and dungeon,
where you lie as among the lions in this day of Jacob`'s troubles.
Lift up your voice, and cry out of the deep, with one accord and consent unto Him,
who has not at any time said unto the house of Israel,
"`Seek my face in vain:`" and my spirit with yours
and our prayers will meet at the throne of grace,
in the presence of your Father and my Father; who has respect unto his covenant,
and will save his afflicted people,
and bring forth the prisoners out of the prison houses,
that they may show themselves in the land of the living.
In the meantime, suffer patiently, without murmuring and repining,
and wait to have your weak hands and feeble knees strengthened to endure hardships,
as good soldiers of Jesus Christ; and look unto Him,
the author and finisher of your holy faith, who, for the joy that was set before him,
endured the cross and despised the shame:
that all the sufferings of these light afflictions, which are but for a moment,
may be endured, as seeing Him that is invisible: be faithful unto death,
that you may be crowned with eternal life.

And, Friends, you that are not as yet in bonds for Christ`'s sake,
who are made as a gazing stock with us, and confess the same Truth,
and bear the burden of our bonds,
as bound with us,--you are witnesses of the same sufferings, and for the same cause;
and inasmuch as your hearts are open to visit the saints in prison,
and communicate your cup of cold water to them that keep the commands of Christ Jesus,--the
Lord will not exclude you out of the number of his jewels in that day,
when he gives a reward to the righteous,
and a recompense to every man according to his work.
Therefore, let none look upon themselves as members disjointed from the body,
or as branches broken from the tree;
and let none judge them that have liberty yet a little season given for a prey,
for ends best known to Himself: for thus has the Lord in his mercy, wisdom,
and compassion ordered it, that there may not be a full end made of his heritage at once,
but some are left at liberty to serve those that are under restraint,
and by such a sudden surprisal are separated from nearest relations, outward habitations,
ordinary employments, and all external privileges; which the law of God,
and law of nations and nature allow to men as men,
especially to men that fear God and work righteousness.

And in this respect you are joined to us, and are one with us,--and we own you,
and write unto you,
and embrace you as companions and fellow-sufferers for the testimony of Jesus,
and the word of God.
By this do I particularly salute you in the Lord, exhorting and beseeching you,
as in Christ`'s stead, to stand still and wait in patience with us,
that you and we may see that salvation from God, which cannot be expected from the hills,
nor from the mountains, nor from the arm of flesh.
And, dear Friends,
cast not away your confidence in this cloudy day and hour of temptation:
neither be afraid of him that can imprison, oppress, persecute, and kill your bodies;
but fear the God of heaven, and give glory to his name, and honour the King of nations;
and keep yourselves unspotted from the world, and your consciences void of offence,
both in the sight of God, and in the presence of men.

And if you suffer for well doing, and for righteousness sake,
the Lord will comfort you in all your tribulations, and will plead with your adversaries,
and reprove your oppressors, and vindicate your cause;
inasmuch as you are innocent in all your sufferings, sustained under every government,
since you were a people, for the exercise of your religion,
and the peace of your pure consciences.
For the God of heaven knows, and the sons of them that do afflict you will know,
that you are not in rebellion, nor in transgression in any particular,
whereof you are suspected, accused, and judged at this day;
but the occasion that is taken against you and us,
is chiefly concerning the law of our God, and the exercise of our religion.

Well, my dear brethren and sisters,
I know the oppression is great under which you suffer,
and your trials and travels are many in all the provinces
and parts of this land of our nativity;
I am sensible of it, and my heart is affected therewith;
for many women are left as widows, and their children as orphans at this season:
but the Creator of all things is a husband to the widow, a father to the fatherless;
and he is rich in mercy, large in lovingkindness and abundant in goodness and truth;
and his compassions never fail them that cast their care upon him,
and put their trust in him: neither can we say that He is as a way-faring man unto us,
or a stranger that turns aside to tarry for a night and no more;
for He has fed us all our life long, and is the portion of our cup forever,
and the lifter up of our heads in this the day of our confinements.

And now, my dear Friends, by this you may know,
that my dear brother J. Scafe and I have been under
restraint near two months at this place;
in which time the number of prisoners has increased,
insomuch that we are near two hundred Friends in prison in this place,
for no other cause but our obedience to the command of Christ Jesus,
and for frequenting solemn meetings for the exercise of our religion;
which we have both publicly and privately, as also in practice and principle,
declared to be in obedience and subjection to the higher powers,
and not in contempt of any person, power, or government appointed of God,
for the punishment of evil doers, and the praise of them that do well.
And this is an addition to our rejoicing and consolation,--that
we can call heaven and earth to record,
and the Spirit of God bears witness with us and for us,
that we know nothing on our parts as the original cause of our sufferings,
but our principles and persuasion in matters of religion,
and concerning the law and worship of our God.
So that it is wholly for the name of Christ, and for righteousness sake,
that we are called in question, and cast into prison at this day.

My dear brother and companion in tribulation, J. Scafe,
gives the remembrance of his unfeigned love to all Friends,
where this is read and received; and the rest of my fellow prisoners dearly salute you.
We are generally well, and well content to suffer for righteousness sake;
and the peace and presence of the Lord is in our habitations:
to whom you are all committed, as unto a faithful Creator,
by him that is your dear brother and fellow servant in persecutions and tribulations,
at liberty or in bonds.

[.signed-section-signature]
Thomas Salthouse.

[.signed-section-context-close]
Ilchester, 23rd of 12th month, 1660, +++[+++2nd month 1661.]

[.offset]
+++[+++_From the original._]

[.centered]
=== No. CXXXI.

[.letter-heading]
John Whitehead to Friends

[.signed-section-context-open]
Aylesbury Prison, 12th month, 1660.
+++[+++2nd month 1661.]

Dear Friends, both sons and daughters, among whom I have travailed,
that you might be gathered in the everlasting covenant of light and life,
to feed by the Shepherd`'s tent, among the sheep of His pasture and lambs of His fold.
When I consider that by departing from iniquity,
you are become a prey to all the beasts of the field,
who gather themselves together to rend and to devour
you;--how does my soul yearn towards you,
and my heart does melt into tenderness with the love
and life that is shed abroad in it unto you:
in which life my soul is often poured out in silence before the Lord,
(who knows how to deliver his little ones,
who have put their trust in him,) that you may be kept together in one mind and spirit,
and have your hearts established with grace upon Him,
who is the only begotten of the Father.

Hold fast your confidence in the word of his patience,
and in the living hope stand fast and immovable upon the spiritual Rock,
that you may not be shaken: for now the storms, tempests, and floods are come,
that the hearer may be known from the doer, and the false from the wise builders.
Therefore, let not the upright in heart be troubled, though some shake and fall,
and are by the floods swept away; but rather rejoice,
in that they which are approved shall be made manifest,
and their righteousness which God has given them,
shine forth as the stars of the morning: yes, blessed shall they be that overcome;
for they shall be as pillars in God`'s house,
which he is building and will finish of tried and lively stones,
that he may dwell in it forever.
Be not discouraged at the raging of the sea,
neither dismayed at the tumult of the people:
for the Lord your God is with you to deliver you, whether in life or death.
O! then, stand wholly given up unto his will;
and wait upon Him for strength and patience to lay down your own lives,
if nothing but that or the transgression of the law
of your God may satisfy them that persecute you;
for better is it to fall into the hands of men for transgressing their law,
than to fall into the hands of God for willful transgression of His law:
for you know man can only kill the body and no more; but God,
after he has killed the body, has power to cast into hell.

These things I write to remind you of God`'s power; that you may both trust,
fear and love him, whose glory is arising upon you,
and shall more abundantly appear in you, whose minds are stayed upon him;
who in mercy has called you, and chosen you to follow the Lamb,
who shall have the victory.
Therefore, fear not to go through any suffering for his name`'s sake;
because he has the words of eternal life;
by him your souls may be everlastingly satisfied and refreshed.
And what if God allows your bodies to be broken,
and turned to the ground from which they were taken,--that shall
not prevent us from partaking of the glory that shall be revealed.
And let not any look out with the wrong eye,
to search when shall be the end of these things;
for a thousand years with the Lord are but as one day, and his long-suffering is great.
Let all whose minds are turned towards God, keep out of the reasoning,
which draws back into self-safety; lest thereby the nobility of your minds be clouded,
and the plants choked, whose growth is but little in the Truth: but stand in God`'s fear,
and mind his witness in your consciences, and join not to anything against that,
and it will preserve you, though your strength be small.

And, dear brethren, whose portion is larger, remember that more is required of you,
and according to your ability improve your talent in strengthening the weak,
and considering the feeble-minded;
and though you cannot give the oil of your lamps unto the foolish,
having need for it all yourselves;
yet tell them in time where they may buy it without money or price,
that they may be prepared to meet the bridegroom, whose day is at hand.
And if there be any among you who do not wickedly depart from God,
but through weakness or violent temptations are ensnared by the enemy,
then you whom God does preserve and strengthen,
reach forth your hands to help out of the jaws of the devourer:
then shall the soul that is saved from death bless you,
and the Lord will requite you in the day of your need.
And see that you be inwardly armed;--for he that goes to war against principalities,
powers, and the rulers of the darkness of this world in another armour,
which he has not proved to be spiritual,
nor has inwardly received it from God in the light, he shall not overcome.
Now all lies at stake; and whosoever does fly, before the victory be obtained,
loses what he has wrought, and makes himself a scorn to fools.
Therefore let neither death, banishment, peril, sword, hunger or nakedness,
neither any other thing, whether present or to come, cause you to fly from the Truth;
but in all conditions cleave unto it, and it shall preserve you.

And you that have of this world`'s goods,
let the compassion of your hearts be open to your poor brethren;
and order that which God has made you stewards of in his wisdom,
for their and your own relief, before it become a prey to the spoilers:
and let tender love and mercy, as you have received it from the Lord,
abound in you one to another.
Live in the one Spirit of the Lord, that in it you may have unity and peace with God,
and one with another: and bear one another`'s burdens, and suffer one for another,
as Christ suffered for the body`'s sake, leaving to us an example;
which God has counted me worthy to follow,
who am among many brethren a sufferer for the testimony of his Truth.
Let not your hearts be troubled, but rather encouraged by my bonds,
in which I have peace with God; and though I should see your faces no more,
I am joined with you in a perpetual covenant, and the remembrance of you is sweet to me.
My life salutes every one of you with true inward breathings;
that under the shadow of the Almighty you may be preserved, and by his right hand upheld,
until the tempest be over:--that you, O! Zion, in your beauty may arise; and the Lord,
your light and glory, be in the midst of you,
as the sun from under a thick cloud;--that men may see Him whom they have pierced,
and the desire of nations be towards Him;
and the people that dwell therein may walk with us in the light
of the Lord;--that blessing and peace may fill the whole earth,
and nation not lift up sword against nation, neither learn war or persecution any more.
Amen, Amen!

And you that be at liberty in the outward,
give up yourselves to serve the Lord in the morning of life;
and visit your brethren that be in bonds for the Lord`'s sake;
so will the Lord take it as done to himself,
and give you a reward in the resurrection of the just.
And keep your meetings as you see most expedient, in the light of the Lord,
and in his fear, out of the fear of man; and be fervent in waiting upon God,
that a double portion of his Spirit and power may be upon both sons and daughters,
old men and babes;--in whose mouths,
O Lord God Almighty! ordain them strength to bring to naught the wisdom of the wise,
and to drive backward the counsel of the ungodly;
that the fold of your lambs may be preserved entire:
and let your life and virtue be unto them a fresh pasture, and open yourself among them,
O you Fountain of living waters!--that the thirsty among your people may be satisfied;
and fill their hearts with your love,
that therewith they may love their enemies;--that your witness may arise in them,
and clear the innocency of your own people:--for we have fled unto you for refuge,
and can use no other weapon to plead our cause but the words of your mouth.

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Written in the prison house in Aylesbury, the 2nd of 12th month, 1660.

[.postscript]
====

This to go among Friends, to be read when they are met together in the fear of God,
with understanding; and likewise to be sent to the prisons,
to be read among Friends which suffer for Truth`'s sake.
Fail not to communicate it one to another.

====

[.offset]
+++[+++_From the original._]

[.centered]
=== No. CXXXII.

[.centered]
William Bennit to Friends

[.signed-section-context-open]
Bury Jail, 6th month +++[+++8th month]
1668.

Dearly beloved Friends,
brethren and sisters in the Truth,--you whom the
mighty God of power once found as in a desert land,
and in a waste howling wilderness, sticking fast in the mire of your own corruption,
without help of your own;--and there still had been till this day,
had not the Lord God of infinite power, of love and compassion, helped us,
in great mercy to our immortal souls:
He freely reached forth the strong arm of his salvation to us,
who without the help thereof, must have perished in our sins eternally.
He brought us out of the horrible pit of ignorance and darkness, of sin and iniquity;
and has set our feet upon the rock of ages, Christ Jesus--the sure foundation,
which can never be removed;--praises and glory to our God forever! who
has freely done much for our souls,--even that work has he done for us,
which we without him, or none besides him, could ever do:
he awakened us that were asleep in sin, and quickened us that were dead in trespasses,
and raised us up that were buried in the grave of iniquity,
and said unto us that were dead--live.

He gave light to us that were in darkness,
and unto us that were in the region and shadow of death,
did his blessed dayspring from on high shine in our habitations;--glory to our God forever!
He has washed us, cleansed and sanctified us in measure, through his eternal Truth;
"`His word is Truth,`"--which we have felt and known, like to a fire, sword and hammer,
working mightily in and upon our hearts, to the mortifying, subduing,
and destroying of the power of darkness:--whose day of glad tidings,
and of redemption to his seed, and of destruction to his enemies, did burn as an oven;
in which the wicked one, and he that did wickedly, was as stubble and straw.
We knew a fire kindled in the earth of our hearts,
and a great desolation the Lord brought upon us;
and then did the tribes of the earth mourn, and our heavens were shaken,
and our fig-leaf garments rent, and our nakedness appeared,
and nothing of our own was able to cover our shame.

O! blessed be the Lord, who stripped us of our own, and made us bare,
that he might clothe us with his light.
He broke us in pieces, that He by his power might bind us up in the bundle of life;
he wounded us, because of sin, by the sword of his righteous judgment,
that he might heal us with the medicine of his mercy;
and by his light and Spirit he gave us to see the sinfulness of our state,
in which we were, when he first found us; under the sense whereof we groaned,
desiring deliverance therefrom.
He, through the washing of regeneration, and renewing of the Holy Spirit,
has cleansed us, who were unclean; and has made us his people,
who once were not his people; and has brought us near unto himself, who were afar off.
He sought us that were lost, and brought us back again,
who were driven from him by the enemy of our souls.

O! dearly beloved ones, what manner of love is this, which the Lord, our tender God,
has manifested to us! whose love and goodness, appeared towards us,
while we were enemies in our minds against him,
burdening and oppressing his pure seed in our own hearts.
O! dear Friends that the sense of his love, goodness, and mercy, showed to us,
may even daily break, melt, and humble our hearts before him;
and even be an obligation upon every particular one to engage us and oblige us,
to be faithful and obedient unto the Lord, in our particular places;
to walk answerable to his great love, infinite mercy, and rich grace, bestowed upon us.
O! the Lord stir up our hearts to watchfulness, and in the light to pray,
and to war against the enemy of our souls;
and know God`'s salvation to be as walls and bulwarks to us in the hour of temptation:
that when the enemy entices any of us, with the glory, honour, riches, pleasures,
and delights, of this world, or with anything below,
that would take away our hearts from the Lord and his truth,
we may not be overcome by him; but rather overcome him, and his temptations,
through the Lord;
who will strengthen all those that cleave unto him and diligently wait upon him.

Therefore wait, and rely upon him,
you tender one,--who in the sense of your own inability,
are ready to cry in your heart to the Lord--Lord let nothing ever separate me from you!--O!
let nothing steal away my heart from you!--O! that I may never forget your love,
or be unmindful of your mercies,
or slight your Truth and people!--Let your Truth never become an old thing to me;
but O! that it may be as near and dear unto me as ever it was!
O! Lord, whoever slights your Truth,
and forsakes the assemblies of your people,--whoever turns to their old lovers,
and descends downward toward the earth again,
and wheels about on their old centre,--whoever grows loose and vain,
careless and negligent,--whoever grows cold and dead, dry and barren,--Lord, do keep me,
and preserve me, who without you am poor, weak, and feeble;
and enable me to hold out to the end:
for alas! what good will talking of former experiences do to me,
and of what I have formerly enjoyed of you, received of you, or done or suffered for you,
in that day when my heart was tender, honest, and upright before you,
if I should now forget you,
and let the world again take away my heart from you,--and the earth again eat up my mind,
and bury your righteous seed; O! then my talking of you,
and of my former experiences and profession of your way, truth and worship,
will stand me in no stead; for if I faint by the way, and turn back again into Egypt,
I shall then lose the reward, which they have, that abide to the end.

Therefore, O Lord God Almighty! in a true sense of my own danger,
and in a sense of what has happened to some, whom I once thought might have stood,
and retained their integrity, I cry unto you;--desiring daily to wait upon you,
to feel the supporting, upholding, preserving power of your grace, to keep me low, meek,
and humble, and watchful; that so I may retain my integrity, and hold fast my first love,
and be enabled through your power,
to finish my testimony for you in faithfulness with joy, to your glory and praise,
O my God!
O! this is the frame of the innocent, honest, tender-hearted ones,
that love the Lord and his truth more than all.
O! that in this frame of mind we all may be kept, says my soul; which cries,--"`Lord,
not glory, honour, riches, and pleasure, in this world; but grace, truth, mercy,
and peace, unto the end of my days!`"

Dearly beloved Friends, unto the Lord I commit you,
who right well knows how it is with every individual;
unto whom is the cry of my soul for your good, welfare and preservation in his Truth,
which never changes, though some change and turn from it.
But Truth is the same, and those that abide therein, are of one heart,
of one mind and spirit, and have unity and fellowship therein with the Lord,
and one with another; and therein I desire our unity maybe continued,
and abound more and more;
and that which would hinder and break unity in the Truth among brethren,
may be wrought out and kept out, through unfeigned love of God in all your hearts:
whose love I desire may abound more and more, in and among you;
that all those things of a contrary nature, which tend to strife, debate, division,
rents, and confusion, may be thrown down, and kept under foot,
and shut out from among us; that so the love, power, and truth of the Lord,
and our unity therein, may flourish over all.

And, dear Friends, keep your meetings in the fear and name of the living God;
and be very diligent in waiting upon him in his gifts:
give not leave for your minds to wander,
and none to give way to drowsiness and sleeping in meetings; for surely,
it is even a shame to us that the thing, namely,
sleeping in the assemblies of the saints, should be found among any of us: truly,
Friends,
the very thing oftentimes greatly burdens the seed of God
in the hearts of many of his children:--therefore,
watch and war against it, and wait to feel life in yourselves,
to quicken both soul and body, in the work, worship and service of the living God;
that a living sacrifice from his own Spirit we may offer unto him.
For his worship is a living worship, and performed in and by his living Spirit;
in which let us wait diligently upon the Lord,
and a preparation we shall witness thereby; and feel and enjoy his presence,
and be edified, enlivened, and warmed thereby, though no words be heard among us.

So, dear Friends, bear with me, and receive in love this my salutation in love to you,
who am one that loves Zion, and travails in spirit for her prosperity.
And my dear and tender love is to all those who love the Lord;
and my soul reaches unto the honest and upright in heart,
and the remembrance of you dear ones makes glad my heart.
Though I am confined and separated from you in body, yet, verily,
I am often with you in spirit; and then my soul embraces you,
and sympathizes with you in your trials, straits, troubles, and tribulation;
all which I desire the Lord God everlasting, may carry you through,
and lift up your heads in his name.
And the Lord comfort the mourning ones among you, and heal the wounded,
and bind up the broken in heart; and lift up the weak hands that hang down,
and confirm the feeble knees, and cause the halting to go upright,
and leap over all the mountains of the enemy:
that those that have lain mourning in the pits of distrust, fears, doubting,
and carnal reasonings, may mount over all upon the wings of faith,
and flow to the goodness of the Lord,
and eat of His house and drink of the river of His pleasures,
and be satisfied;--and bless, praise, and magnify the Lord in the land of the living.

So the Lord God everlasting be with you,
and the Almighty Jehovah defend you;--and the everlasting
arm of His power uphold you over all,
and carry you through all which you yet may meet with,
within or without;--and strengthen the weak and little ones among you.
O! Friends, our trials are not yet all over,
though we have already waded and travelled through much,
in the strength and fear of the Lord.
Therefore, dearly beloved ones, let us watch and pray, and wait daily upon the Lord,
to be fitted for trials when they come; and that we may stand in the terrible storm,
and be like mount Zion, which can never be moved.
Good it is for us to watch, to take heed against wrong security,
and getting into a false ease, because it is at present a calm;
lest thereby we provoke the Lord to anger, and so induce him to allow a storm again,
before we be aware.
O! let us not sin; because grace, mercy, and many benefits from God to us abound;
lest the Lord turn his mercies into judgments.

O! let us watch, and be sober;
and hope to the end,--having grace whereby we may serve God acceptably,
with reverence and godly fear:--our words being few and savoury,
and our lives and conversations blameless and unreprovable;
walking as become saints of the Most High God;
shining as lights in the life of righteousness, in the midst of a dark, crooked,
and perverse generation.
And you all be followers of Christ the light,
who is the Captain of our salvation and walk, as you have those for an example,
who fully follow Christ.
But follow not the steps of those that walk disorderly,
neither have fellowship with them in any unfruitful works of darkness,
but rather reprove them who cause the Truth to suffer, and those that live in it,
to be evilly spoken of; who are enemies to the cross of Christ,
though professing him in words: whose god is their belly, whose glory is their shame,
who mind earthly things, and serve not the Lord Jesus Christ, but their own lusts;
whose end is destruction, except they repent.

But, dear Friends, let your conversation be in heaven,
and yet preach righteousness in the earth; that the Lord may be glorified through us;
who has raised us up a people to live to his honour, and to show forth the praise of Him,
who has called us out of darkness, to walk in his marvellous light.
The God of peace and consolation accompany them, and settle,
and stay them upon himself,--and bind them up in his Truth,
and cause them to grow in grace,
and in the knowledge of Christ Jesus our Lord and Saviour; to whom be all glory, praises,
and dominion, world without end.
Amen.

From your true friend and companion in the patience and tribulation of Jesus,
who has you often in his remembrance; and though close shut up in prison,
yet his love reaches to you all, and remains with you.
Farewell! dear Friends, farewell!

[.signed-section-signature]
William Bennit.

[.signed-section-context-close]
Bury common jail, the 2nd of 6th month, +++[+++8th month]
1668.

[.centered]
=== No. CXXXIII.

[.letter-heading]
Stephen Crisp to Benjamin Bangs

[.signed-section-context-open]
Colchester, 10th of 4th month +++[+++6th month]
1682.

[.salutation]
Dear Benjamin Bangs,

My dear love in the Truth salutes you.
I was greatly satisfied in my journey,
chiefly that I found a life up among Friends that can suffer; and I am sure it is that,
which will reign and conquer in the end;
and in this will be the safety of us all,--to follow our Captain in suffering and tribulation,
having an eye to the recompense of reward.
For that which can talk and not walk, and can profess and not suffer, is not the heir,
nor must be respected as the heir: for all respect shown to that birth, puffs it up;
but the true birth is low in heart.
So dear heart, dwell in that which gives a discerning of every sort and kind;
that you may deal out the bread to the children,
and the rod to the fool,--for these have their distinct ministry:
and every right ministry springs from the gift,
and the gift is from God,--the Giver and the gift are perfect:
and as long as the minister is ordered in and by His gift,
and takes not the ordering of it into his own hands,--his work is perfect,
and tends to the glory of the Giver, and the edification of his Church:
such carry their reward with them, and show themselves approved in God`'s sight,
and in his people`'s.

So now, my dear Benjamin Bangs, I love you,--therefore I write this to you;
heartily praying for your preservation and prosperity in the work of the Lord,
and shall be glad to hear from you.

I rest, and remain, your true and real friend and well-wisher,

[.signed-section-signature]
Stephen Crisp

[.offset]
+++[+++_From a copy._]

[.centered]
=== No. CXXXIV.

+++[+++The following short essay by William Penn,
written out and signed by himself on a plain half-sheet of paper, was probably composed,
like his maxims, as a detached reflection:--the editor has not found it in print.]

[.small-break]
'''

He is a wise and a good man too, that knows his origin and end;
and answers it by a life that is adequate and corresponds therewith.
There is no creature fallen so much below this as man;
and that will augment his trouble in the day of account,--for he is an accountable creature.
I pray God his Maker, to awaken him to a just consideration thereof;
that he may find forgiveness of God his Maker and Judge.

[.signed-section-signature]
William Penn

[.centered]
=== No. CXXXV.

[.letter-heading]
Isaac Penington to his Children

[.signed-section-context-open]
For my dear children J. J. and M. P. 10th of 3rd month +++[+++5th month]
1667.

[.salutation]
My dear Children,

Two things I especially desire in reference to your learning;--one is,
that you may learn to know and hearken to the voice of God`'s witness in you.
There is something in you, which will teach you how to do well,
and how to avoid the evil, if your minds be turned to it.
And the same thing will witness to you, when you do well,--and against you,
when you do evil.
Now to learn to know this, to hear this, to fear this, to obey this,
that is the chief piece of learning that I desire to find you in.
And your master or anyone of the family that turns you to the witness,
reminds you of the witness, reproves you for not hearkening to or obeying the witness,
O! love them, and bless God for them in that respect: and remember this,
that he that hearkens to reproof is wise, but he that hates or slights it is brutish.
That is the dark spirit, which would please itself in its dark ways,
and therefore loves not the light which makes them manifest and reproves them:
and that spirit is the brutish spirit, which hates the reproof of the light,
and would continue its vain foolish ways and delights,
which the light testifies against;--that spirit therefore debases man.

Therefore mind the witness which discovers these things to you,
and leads you out of them, as you hearken to it, and come to know,
fear and love the Lord God, by his instruction and testimony.
The way of youth is vain, and foolish, and defiles the mind: O! my children,
wait for the cleansing,--watch to that which cleanses the foolish way of children,
which is that which discovers and witnesses against your foolishness and vain tempers,
and the temptations of your minds, and leads out of them.
Learn to bear the yoke in your tender years.
There is a vain mind in you--there is something which
would be feeding and pleasing that vain mind;
and there is something near you, appointed by God to yoke it down.
O! give not scope to vanity, it will be an occasion of woe and misery to you hereafter.
But the yoke which keeps under the vain mind, O! take that yoke upon you:
and then you shall become not only my children, but the disciples of Christ,
and children of the Most High.
This is the first thing,
which I mainly and chiefly desire you should apply yourselves to learn.

The next thing is,
(which will also flow from the first,)--that you
learn how to behave yourselves as good children,
both in the family and to persons abroad, in a meek, modest, humble, gentle, loving,
tender, respectful way,--avoiding all rude, rough, bold,
unbeseeming carriage towards all; honouring your mother and me,
as God teaches and requires; dearly cleaving to one another in the natural relation,
which is of God, wherein you are loved,
having even a great proportion of natural affection and kindness one to another:
So to the servants, carry yourselves very lovingly, sweetly, meekly, gently;
that none may have any cause of complaint against you,
but that all may see your lowliness, and be drawn to love you.
And to strangers, carry yourselves warily, respectfully, in a sober, submissive,
humble manner of demeanour; not disputing and talking,
which becomes not your age and place; but watching what you may observe of good in them,
and what you may learn of those that are good, and how you may avoid any such evil,
as you observe in any that are evil.
Thus your time will be spent in profit,--and you
will feel the blessing of God and of your parents,
and be kept out of those evils, which your age and natural tempers are subject to,
and which other children, who are not careful nor watchful, are commonly entangled in.
Mind these things, my children, as you will give an account to God,
who through me thus instructs you,--who am your imprisoned father--and
have been much grieved when I hear of any ill concerning you,--it
being more matter of trouble and sorrow to me,
than my imprisonment, or anything else I suffer, or can suffer from man.

Your father, who desires your good, and that it may go well with you,
both here and hereafter.

[.signed-section-signature]
Isaac Penington

[.signed-section-context-close]
10th of 3rd month, 1667.

[.postscript]
====

And remember this one thing, which as a father I admonish you of,
and charge you to take notice of and observe,
which is this,--that you do not fly out upon one another, or complain of one another,
because of the evils you observe in one another;
but first take notice of that evil in yourselves:
if by the true light you find your own hearts cleansed from it,
bless God who has done it; and keep to his light and the testimony of his witness in you,
whereby he did it; and watch that you be not overtaken in it for the future.
But if you be guilty of the same evil, or have lately done the same thing,
or are liable suddenly to do it,--O! for shame! forbear accusing or blaming another:
and in the fear of God wait on him, and pray unto him that you may be delivered from it,
and kept out of it.
And then in tender pity, love and meekness,
admonish your brother or sister of his or her evil,
and watch to be helpful to preserve or restore them;
and pray to God to direct you how to be helpful to them.
But that is the bad spirit and nature,
(which God will sharply punish,) that is ready to accuse others:
and though it be never so bad and guilty, yet will be excusing itself,
and laying the fault upon others, or remembering some other fault of another,
when it should be sensible of and ashamed of its own.

Dear children, if you bend your minds to learn these things,
the Lord will help you therein, and become your teacher, guide and preserver,
and pour down his blessings upon you; and you will be a comfort to me and your mother,
and an honour to his Truth;
and He also may give me wise fatherly instructions to teach you further.
But if you be careless, foolish, vain, following your own minds,
and what rises up there from the wicked one, you will grieve my heart,
and provoke God against you, to bring evil upon you, both in this world and forever.
Therefore, children, mind that which is near you the light of God,
which discovers the evil and the good.
His witness, which observes all you do, is near you: yes, he himself is in that light,
and with that witness.

Therefore, know, you are in his presence at all times; who is a holy and just God,
hating that which is vain and evil, and loving that which is good and right before him:
and has appointed a day and set a time, wherein he will either reward you with peace,
joy, and eternal happiness, if you have been good, and done that which is good;
or with misery, destruction, and insufferable pain both of soul and body,
if you have been evil, and done that which is evil.
And God takes notice how many instructions you have heard from Friends in Truth,
and from your parents; and how many meetings you have been at,
wherein you have been taught and warned of these things:
so that if you turn your back upon his light, and will not hear its reproofs,
but will be vain, and idle, and foolish, and rash, and quarrelling,
and doing that which is naught, and then covering it with lies, and so be as bad,
if not worse,
than children who were never thus taught and instructed,--God
will be exceedingly angry with you;
and may in his just judgment and sore displeasure, separate you from his light,
give you up to the black, dark spirit,
(from whom all this wickedness is,) to sow in sin here,
and to suffer the flames of eternal fire hereafter;--which is his reward,
and the reward of all who are persuaded by him to be of his nature,
and who hearken to him, and let him work through them.

O! my children, mind the Truth of God in you;
and that will let you see and understand the truth of what I now
write,--and in what fatherly love and tender care of you,
I write these things;
that you might be warned of the great danger of neglecting the
time of your visitation by God`'s light and witness in you,
and of going on in the evil ways of the dark crooked spirit,
who will be tempting you to evil and hindering you from God,
as long as you hearken to him.
Therefore, be not fools, to be led by him to destruction, in the evil way and evil works,
which lead thereto; but be wise to hearken to the light, and follow it,
out of that which is evil,
into everything that is good,--to the salvation of your souls.

I desire that Friends in the family, watch over them in these respects;
and when they find just occasion, to put them in mind of any of these things,
in the fear and wisdom of God, with tenderness and gentleness,
that they may reach the witness; but to take heed of upbraiding them,
or aggravating anything, lest they be thereby hardened,
and the bad raised and strengthened in them.
And, my dear G.^
footnote:[Doubtless his step-daughter, Gulielma, afterwards the wife of William Penn.]
and Friends, watch over your hearts and ways, that you may be as examples to them;
that they may not only read these things from my writing,
but in your carriage towards them, and one towards another;
that they meet with nothing to strengthen or raise up the bad thing,
but to reach the witness, and bring and keep down the evil in them.
So the Lord bless your watchfulness, care, and endeavours therein;
that I may hear good of them,
and be comforted in the mercy and kindness of the Lord towards them.

====

[.centered]
=== No. CXXXVI.

[.blurb]
=== Christian Discipline, or Certain Good and Wholesome Orders, for the Well Governing of my Family in a Right Christian Conduct, as Becomes the Children of the Light and Truth of the Most High God. Divided into Two Parts.

[.section-author]
By _William Penn_

[.centered]
__"`Now, therefore, fear the Lord, and serve him in sincerity and in truth;
and put away the gods which your fathers served beyond the flood and in Egypt,
and serve the Lord: and if it seem evil unto you to serve the Lord,
choose for yourselves this day whom you will serve; whether the gods which your fathers served,
(that were beyond the flood) or the gods of the Amorites, in whose land you dwell;
but as for me and my house, we will serve the Lord.`"--Joshua 24:14-15.__

[.numbered-group]
====

[.numbered]
1.--As it becomes us, to whom is made known the only wise, invisible and omnipotent God,
and that heavenly, spiritual worship,
which only pleases Him,--always to retain Him in our knowledge with all due fear,
godly reverence and sincere obedience;
so more especially it is my appointment in the heavenly authority,
as a Christian master of my family, that all in it, and of it,
who profess the Truth with me, do meet and assemble every morning,
with all humility and godly fear, to wait upon the Almighty God or Creator,
and to receive and enjoy his living mercies and refreshing presence: that,
being sanctified by Him, we may hallow His name,
and return the praise which is due to him from men and angels forever.

[.numbered]
2.--That every day about the eleventh hour, (unless diverted by extraordinary occasions,
which is also intended and excepted of every time
herein appointed,) all come together again;
and everyone in his turn, read either the Scriptures of Truth or some martyrology.

[.numbered]
3.--That the same practice be observed about the sixth hour in the evening; to the end,
that we may be stirred up to abhor the actions of evil doers,
and to embrace and follow the example of patience, zeal,
holiness and constancy in the righteous,
who only were and are of the flock and family of God.

[.numbered]
4.--That those days which are appointed to meet publicly to worship God upon,
none on any pretence (being in health,
and not unavoidably engaged to the contrary) neglect going to such meetings;
but that they constantly and timely attend and frequent
the same as becomes a family fearing the Lord,
and that is zealous for his living Truth.

[.numbered]
5.--That there be a watch kept over every mind,
so as that it may not err from the counsel of God,
and the weighty government of his holy truth, in whatsoever it is exercised about;
lest darkness and deadness come over it, and the evil one enter,
to sow all manner of evil seeds, as strife, envy, evil watchings, levity, pride,
and such like: the latter end of such is worse than their beginning.

[.numbered]
6.--That everyone keep out of unsavoury words, and that provoke to lightness,
and which load the righteous witness in themselves and others.

[.numbered]
7.--That none call each other bad names, nor give themselves to wrath or railing;
but if anything of distance should happen, let none sleep upon it,
nor the sun go down upon his or her wrath; but confess to each other,
and seek peace and pursue it, for it is well pleasing to God.

[.numbered]
8.--That though everyone may have appointed a particular service,
yet that all so live in the life of Christ Jesus, who washed his disciples feet,
as to be ready and willing to assist each other,--for
that becomes brethren and fellow servants.

[.numbered]
9.--That all drunkenness, lasciviousness, lying, defrauding, emulations, variance,
back-biting, tale-bearing, swearing, cursing, taking the name of God or Christ in vain,
pride, stubbornness, flattery, slothfulness, falseness, eye-service,
or such like fruits of darkness, be not so much as named among you;
for you well know that those who do such things cannot inherit the kingdom of God;
and I would have you know and be assured that, after due reproof,
such shall not continue in my family.

[.numbered]
10.--And as it becomes a Christian master and mistress to require nothing
from servants that is not according to the righteous Truth of God,
so they are keeping in their place,
when they require that you all make it solemn matter of conscience before the Lord,
to be upright, faithful and diligent towards them;--not slighting them,
because they are your brethren.

====

As I have so far acquitted my conscience, in expressing what was enjoined me of the Lord,
to require from my family about those things which
particularly relate to God`'s holy worship,
and their Christian duty and conduct,--so it is my desire to declare my mind in matters,
though of lesser nature,
yet necessary for the civil discipline of my family:--and that now follows,
as proper to the second division or table of order.

[.numbered-group]
====

[.numbered]
1.--That the family rise every morning, from the first of the First month,
till the first of the Third month, about the sixth hour in the morning;
and from the first of the Third month, to the first of the Seventh,
about the fifth hour in the morning;
and from the first of the Seventh to the first of the Ninth month, about the sixth hour;
and from the Ninth to the first of the First month,
about the seventh hour in the morning.

[.numbered]
2.--That all come to breakfast about the ninth hour;
that all come to dinner about the twelfth hour;
that all come to supper about the seventh hour.

[.numbered]
3.--That everyone take it in their proper turns to knock or ring up all the rest,
according to the several appointed times, in their respective seasons,
whether to religious exercises, or meals, as they shall be ordered.

[.numbered]
4.--That every servant, after supper,
come and render to their master and mistress an account
of what has been done the same day,
and receive respective instructions for the ensuing day.

[.numbered]
5.--That everyone in their turn, take care that all gates and doors,
be locked and bolted, and all fires and candles extinguished before they go to bed;
and that the men`'s care be in what belongs to the men,
and the maids`' in what belongs to them.

[.numbered]
6.--That all retire to bed about the tenth hour at night.

[.numbered]
7.--And for preventing of all disorderly and troublesome noise in the family,
it is enjoined upon all, to forbear loud discourses,
and to go to the persons they have business with,--and
not to bawl and loudly call after them,
it being both offensive and unseemly.

[.numbered]
8.--That none go to any inn or other public house in the town,
but on business first known, and leave given.

[.numbered]
9.--That none take the liberty of absenting themselves on any pretence,
without leave first granted them, provided either master or mistress be at home,
or such one as by them shall be appointed to oversee the family;
and that the concerns thereof, or of one another, be not divulged abroad,
or made matter of public discourse.

[.numbered]
10.--That when anyone is sent of errands, they make no delay,
neither enter into unprofitable talk; but dispatch the business they are employed about,
whether errands or otherwise, according to their respective orders and instructions:
that all may be done, not with eye-service, but as fearing the Lord,
and making conscience of discharging their several trusts.

====

And,--"`whatsoever things are true, whatsoever things are honest,
whatsoever things are pure, whatsoever things are of good report; if there be any virtue,
and if there be any praise, think on these things;`" and the God of peace be with us.

[.signed-section-signature]
William Penn.
