[quote.epigraph, , Daniel 4:2-3]
____
I thought it good to show the signs and wonders that the high God has wrought toward me.
How great are his signs! and how mighty are his wonders!
His kingdom is an everlasting kingdom, and his dominion is from generation to generation.
____

== Introduction

This selection from the letters and papers of the late John Barclay,
has been made partly from accounts of his religious experiences and reflections,
recorded chiefly in early life, and partly from letters written to his friends,,
which have come within the reach of the editor.
From the state in which these accounts were found,
as well as from remarks made during his life-time,
there is no doubt that the author intended the publication of a compilation of them,
as a narrative of his religious experiences,
and as a testimony or memorial of the Lord's goodness to him:
to this collection of rough materials or notes, he had prefixed a title page,
of which the following is a copy:
"`Some Memorials of the Lord's goodness to a poor creature;`" to which was
subjoined the quotation from Scripture affixed to the title page of this work.

The intentions of the author in keeping a personal record of this intimate description,
are more particularly set forth in his own words,
as given at the commencement of the first chapter of this volume;
to which the reader is referred.

The latter portion of the materials of this selection
consists more generally of the letters of the author:
these are mainly of a religious character,
and were evidently written under a lively feeling of
Christian interest on behalf of his friends,
as well as of earnest concern for the best welfare and
prosperity of the religious Society of Friends,
of which he was a member and an acknowledged minister.

The letters which occur towards the close of this volume, from about the year 1832,
often refer to circumstances and events of a period of
deep trial and affliction to the Society.

It is naturally to be expected that the well concerned mind
would hardly fail to be deeply affected by occurrences,
involving the vital welfare of the cause of Truth and
the faithful maintenance of its principles.
Some readers may think that it would have been preferable to
have withheld letters of this description from the public eye,
in the present less disturbed period: but it should be seriously considered,
that it is one of the leading and most useful designs of biography,
as well as of history,
by means of faithful records to convey instruction and the benefit of past experience,
to the present and succeeding generations.

In the instance before us, we have the warnings, the exhortations,
and the encouragement of a faithful follower of his Lord,
while under the provings and sufferings of a dark and gloomy day to the militant church.

Considerations of a merely personal nature must comparatively
be soon lost or forgotten in the lapse of a single generation:
but the duty and trust of a faithful historian
or biographer should be uprightly fulfilled;
and whatever may tend to the religious benefit or edification of his readers,
should be honestly and discreetly portrayed.

The editor regrets that he has not been able to present the reader
with more of a connected biographical sketch of the author's life,
than will be found in this work,--a life which may perhaps be
said to afford but little variety of incident.
He believes, however,
to those whose minds delight to trace the blessed and
animating effects of Divine grace in the heart,
that the religious experiences of the pious and devoted Christian and fellow-professor,
which are to be met with even in his private memoranda or correspondence,
are often deeply instructive;
and they may be felt to supply the place of biographical variety to some readers,
with real interest and even more permanent satisfaction.

The following testimonial to the religious character of the author,
drawn up by one of his early and most intimate friends, now living, (J. F. Marsh,
of Croydon,) may, it is thought, be suitably introduced at this place:

[.embedded-content-document.testimony]
--

He was one with whom I shared no common intimacy and friendship,
both at an earlier period of our lives, and subsequently:
we often took sweet counsel together; and I may say,
were many times permitted to sit together as '`in heavenly places in
Christ Jesus.`' Our acquaintance commenced in the autumn of 1816,
at a time when his mind was sweetly visited by the day-spring from on high.
Ah! how fresh is my remembrance of the state of his mind at that period;
and how was my heart made to rejoice in the feeling of the
preciousness of the love of our heavenly Father towards him,
and the abundant shedding abroad thereof in his heart.
In this day of the Lord's power,
a willingness was wrought in him wholly to surrender himself to the Divine disposal,
and to count nothing too near or too dear to part with, which was called for at his hand.
Thus by meekly bowing his neck to the yoke of Christ, he found it to be made easy,
and his burden light; and thus was he enabled to take up his daily cross,
and follow his Lord and Master in newness of life.
By yielding obedience to the tendering operations of redeeming love and mercy,
he experienced an advancement in the way of holiness;
and he became valiant for the cause of Truth and righteousness in the earth:
deep was his experience in the things of God.

I write not to exalt the creature, but with desire to magnify the riches of that grace,
by which he was what he was, and which on him was not bestowed in vain.
As he lived, so he died, in the Lord: his memory is precious,
-- the savor of his life remains; and he being dead yet speaks.

And now, as I reverently believe, having fought the good fight, and kept the faith,
having come out of great tribulation and washed his robes,
and made them white in the blood of the Lamb,--he has finished his course with joy,
and is gone to inherit the crown of righteousness,
laid up for all them that love the appearing of Christ.

--

The reader is referred to the annexed testimony of Grace-church street monthly meeting,
for a further, but brief memorial of my beloved, departed brother.

[.signed-section-signature]
A+++.+++ R. Barclay.

[.signed-section-context-close]
Leytonstone, near London, Twelfth month, 1841
