== Chapter I.

[quote.scripture, , Psa. 78:4]
____
We will not hide them from their children,
showing to the generation to come the praises of the Lord, and His strength,
and His wonderful works that He has done.
____

[quote.scripture, , Psa. 102:18]
____
This shall be written for the generation to come;
and the people which shall be created, shall praise the Lord.
____

I have been long settled in the persuasion,
that it may be well for many of those who desire the promotion of truth and righteousness,
whether they may have moved in a private or in a public sphere, to leave behind them,
when they go hence to be seen no more here on earth, some written testimony,
however slight it may be, to the blessed cause.
As an individual, I confess that I have derived much instruction, comfort, and strength,
from the living memorials left us by many Christian
brethren and sisters now removed from works to rewards;
not only from their Journals and from Memoirs of them,
but even from testimonies of Monthly Meetings.
But especially I have to notice,
that the expressions of those who have arrived near the confines of the invisible world,
have sunk deep in my remembrance: nor do I know any other instrumental means,
that have proved to me so searching, softening, effectual and abiding,
as that last mentioned description of memorial.
I believe that the profitable impressions which are made,
particularly on the minds of well disposed children and young persons,
remain with them for the most part through life; so that many among us, now grown up,
can testify, that incidents and sayings, which in childhood they had heard or read,
of truly excellent characters,
do even at this day continue to have a beneficial effect on their minds:
and even in cases where young people have wandered far from the line of duty,
these things not infrequently arise in their remembrance.
I speak from some degree of experience, however small it may be,
compared with that of some others: for I have been a wanderer in my time,
yet can testify that even when most widely separated
by wickedness from the Author of all good,
the recurrence of the wisdom of the wise and of the sayings of the dying,
to my thoughtless heart, has not been either unfrequent or unseasonable.
But the advantages which my soul has received in recent times, are still more decided.
Many may think themselves unfit to tell of the Lord`'s
goodness to them in their early youth,
as well as under trials and troubles, and great variety of circumstances,
even to their old age;
but such humble-hearted ones are the very persons who are perhaps most fit,
or most called upon, to make mention in some form or other,
of the providences and mercies and many deliverances which they have met with.

Often when I hear of the death of eminent servants of the Lord,
I long that their wisdom and the weight of their long experience may not die with them;
but that some memorial may have been left by them,
for the instruction of those who are still travelling on their wearisome way.
And surely, the very least of those who strive to follow the Lord,
have had something happen, or have made some reflection worth leaving behind,
for the encouragement and benefit of such as survive them.
I indeed feel this practice of which I am speaking, to have been, and still to be,
the source of a renewed feast to me;
and I seldom recur to some of the manuscripts and scraps which I have written,
without precious feelings of gratitude,
and desires after a patient continuance in well doing unto the end.
Some of these which have been written in the very depth of affliction,
seem to stir up my faith in the Almighty power,
and animate me with fresh courage to endure all things, and to suffer,
even unto the death of all that within, which would have its own way and will,
and not the Lord`'s blessed will.

Indeed I have been so aware of the instruction to be derived,
both from writing such small pieces,
and from reading the productions of others in this way, that I dare not refuse,
however little I desire it, to allow of these little scraps,
the feeble tokens of Divine favour, being made as public as any prudent person,
after I surrender them up and go hence, may see right.^
footnote:[Under date of 1817.]

1814,
May--Some of the following reflections and remarks are taken from little books
called "`Accounts of Time,`" in which the hours of every day were accounted for,
and the occupation which filled every individual hour of each day was put down.
This was at all events an original design, if nothing better; but indeed it was of use,
and no doubt was the means of bringing me into active and industrious habits,
at a time when no sterling inward principle seemed to have full rule,
and when I was left very much to my own direction,
and at my own disposal as to my pursuits.
I have often felt that it was a preservative at the time, and a stimulus to exertion.
I think I may add, of this little contrivance for self-government,
as well as of many others which occupied my attention about the same period,
that they had their use,
in awakening my mind to see the importance of bringing self and sense into subjection;
and however insufficient they were of themselves to effect the same,
they nevertheless urged me forward to press after the knowledge and attainment of that,
which is now, (blessed be the Lord,
who has showed this to me,) experimentally found to be the only sure guide and leader.
As far as these little relics show, how the wrestling seed struggled within me,
and how tender and gradual were the leadings of the Shepherd of Israel,
how the good seed seemed at times almost crushed,
and every desire after such things as were truly desirable,
was at seasons very feeble and faint; so far they are indeed interesting to me,
and excite feelings of gratitude as often as they are examined.
These "`Accounts of Time`" were begun in the Fourth Month 1814,
+++[+++in the 17th year of his age], and were left off about the Eighth or Ninth Month 1816.
The reasons for preserving them,
apply equally I think to those weekly reports which I was in the habit of drawing up;
from which extracts will also be inserted in this book.

1814, August 8th.--I think I may say, that in proportion as I endeavour to do well,
I feel that I am enabled to do so;
that there is something within me that stimulates to good,
that encourages me to persevere in what is good, and which even tells me what is good.
Oh, may I ever listen to its silent but most important intimations,--may
I indeed follow that secret monitor within me,
and both desire and walk worthy of its reproofs and persuasions.

1814,
October 16th.--I have within me a fountain that sends forth bitter and black waters;
which instead of nourishing,
tend to poison the signs of vegetation and fruitfulness that may spring up within me.
Lord! make the waters of Marah sweet!

1814,
November 20th.--I could wish to be able to discover
those symptoms of religious habits within me,
which appear where religion exists.
I could wish that,
as "`out of the abundance of the heart the mouth
speaks,`" so those outward signs could be observed,
which inevitably follow a devotional spirit within.
Oh, that those evidences of true religion were produced,--a sincere
desire to promote the glory of God and the good of man,--a stimulating
and energetic propensity to discourage vice and folly,
though ever so disguised;--and +++[+++that]
my dispositions, affections, actions, words, and thoughts,
might more nearly conform to the pattern which is set before me, even to Jesus Christ!

No date.
+++[+++probably about the same time as the last.]--How inconsistent, how frail, how depraved,
how disposed to evil, and how unable to do right of himself and by his own strength,
is that fallen creature, man!
Every day, I see instances around me of inconsistency, of weakness, of blindness,
as well as of absolute wickedness, though often disguised and palliated.
But when I look to myself, when I examine my own heart,
I find sin mixing itself with almost everything I think, or speak, or do:
not merely do I see evil thoughts lurking in my bosom,
but I find them insinuating themselves into very many good motives, resolutions,
and actions.
How fully do I feel the force and truth of the Apostle Paul`'s expression, when he says,
"`I know, that in me, that is, in my flesh, dwells no good thing;
for to will is present with me, but how to perform that which is good, I find not:
for the good that I would, I do not; but the evil which I would not,
that do I.`" Rom. 7:8. It is not at remote intervals,
that I perceive the effects of my own frailty, but at most times.
Nor is the presence of sin confined to gay and giddy moments,
or to hours of industry and employment, but even in my solitary and thoughtful periods;
even in times when the heart should be most inclined to holiness,
and devoted to the service of its Maker,
even then are the intrusions of evil very frequent,
the imagination often under little control,
and the affections for the most part fixed on any thing but their right object.

1814, December 18th.--Be anxious and ever ardent in the work before you,
even your own eternal happiness, and that of your fellow creatures, to the glory of God.
There is such danger, such liability,
while in these frail bodies and in this wicked world,
even to those seemingly the most confirmed among us, to slacken and decline,
that on this head I cannot forbear suggesting a hint to myself,
who am but just setting out on the arduous journey to Zion:--I cannot
help urging myself to beware of that destructive indifference and lethargy,
which are and have been the ruin of thousands, in a religious sense;
which would palliate the guilt and error of others, and excuse our own,
which damp and chill any appearance of zeal in our neighbours, while they effectually,
though gradually, quench any like disposition in ourselves.

No date.--Domestic life presents many opportunities for the exercise of virtue,
as well as the more exalted stations of honour and ambition.
For though its sphere is more humble, and its transactions are less splendid,
yet the duties peculiarly incumbent on it, constitute the basis of all public character.
Perfection in private life is by far the more arduous attainment of the two;
since it involves a higher degree of virtue,
to acquire the cool and silent admiration of constant and close observers,
than to catch the undistinguishing applause of the vulgar.
Men, accustomed to the business of the world,
may think it a mean occupation to be engaged in the duties of a family.
It is, however, only by comparison that they are rendered to a superficial eye,
petty and insignificant.
View them apart, and their necessity, their importance immediately rises.
How many daily occasions there are for the exercise of patience, forbearance,
benevolence, good humour, cheerfulness, candour, sincerity, compassion, self-denial!
How many instances occur of satirical hints, of ill-natured witticisms, of fretfulness,
impatience, strife, and envyings; besides those of disrespect, discontent, sloth,
and very many other seeds of evil, the magnitude of which is perhaps small,
but for the guilt of which we shall most assuredly be judged.
When we consider that private life also has its trials, temptations, and troubles,
it ought surely to make us vigilant, when around our own fireside,
lest we should quiet our apprehensions, and cease from our daily watchfulness.

Prove your love and affection for your family,
and your friendship and attachment for all your connections, by using, not partial,
hypocritical, momentary acts of kindness, but one universal, constant,
animated effort,--one sincere desire of rendering others happy,
united with compassion for their sufferings, charity and candour for their errors,
and forgiveness for their injuries.

Especially cultivate a benevolent disposition,
an inclination rather to think and speak well than ill of those around,
accompanied with that candour which exposes not the errors,
but rather the virtues of others to view;
and which brings to light with regret their failings,
for no other end than their suppression.

1815, January.--Business, in its proper sphere, is useful and beneficial,
as well as absolutely necessary; but the abuse of it, or an excess in it,
is pernicious in many points of view: I cannot approve, in very many respects,
of the intense degree of application and attention,
which seems often to be required of those that are in business.

There is one danger to which the man of business is particularly exposed,
and the more alarming,
because it is concealed,--I mean the danger of gaining a worldly spirit,
and of losing that tenderness of conscience, that love of religion,
which is the ground of all virtuous conduct.
The person who is engaged in worldly affairs,
whether the sphere of his engagements be large or small,
should be most anxiously attentive to his eternal interests,
that they also may be kept in a flourishing, profitable condition:
if this be not the case,
the saying of William Penn is true in regard to such a one--"`He that loses by getting,
had better lose than gain.`"
He should also be very jealous of his scanty leisure,
that he may not omit to employ some of it in his daily duties to his Maker,
and in the constant cultivation of that holy frame of mind, which,
it is the slow though sure tendency of the spirit of the world, silently to counteract.
For I own I tremble at the very idea of any man`'s mainly pursuing his perishable interests,
when perhaps in one short moment he is gone.
How inconceivably terrible and exquisite must be that man`'s anguish,
while on the very brink of going he knows not where,
to think that he has given up an eternity of bliss,
for the empty grasp of that which is not.

1815,
January 15th.--The following reflection is taken from a "`weekly report,`" and
was penned just previous to my attendance +++[+++by way of initiation into business]
at my father`'s banking-house:

What an eventful period is this, what an epoch in my life!
When I look back upon the past,
when I review the calm and sequestered hours which have been so graciously granted me,
and which I have so happily enjoyed, I cannot help concluding,
that the same Almighty hand, which has hitherto upheld me,
will be "`stretched out still.`"
And when I cast my eye forward to the future, to that dark and dreary scene,
that chaos of troubles and perplexities, which human life for the most part discloses,
I remember with consolation the expressions of the apostle,
"`We know that if our earthly house of this tabernacle were dissolved,
we have a building of God, a house not made with hands, eternal in the heavens.`"
The time that has already elapsed,
seems to be a season of preparation mercifully allotted to me,
in order to qualify me for the part which I am henceforth to act; and those principles,
which I have stored, must now with assiduity be put in practice.
The greatest discretion employed at this first setting out in life,
will not be sufficient to direct and keep me in the right path,
unless accompanied with distrust in myself,
and a corresponding confidence in Divine assistance.

1815,
January 29th.--The very great benefit which may be (and which I trust
is) derived from the system of self-examination that I have adopted,
is more and more apparent to me every week.
Every week have I to reprove, to exhort, to encourage, and to recommend;
as it were to call in my accounts, and to ascertain the real state of my heart;
while every week--yes, every day, give me abundant cause for contrition and abasement.
I am thus led to a more intimate knowledge of the state of my internal affairs,
and of the filth which still lurks within:
while I am rendered less confident in my own unassisted efforts,
and more desirous to be strengthened in obedience.

Same date.--Though I feel myself but a novice in serious subjects,
yet further experience gives me fresh ardour and
eagerness to seek after and attain to that knowledge,
which alone "`makes wise unto salvation.`"
The more I study religion, and the more time and attention I devote to it,
the more I feel persuaded of its unspeakable importance.
There is no pursuit in life, whether of a philosophical, literary, commercial,
or worldly nature, which can be compared with the pursuit of religion,
in respect to the peace and joy, the profit and the pleasure,
which it yields to the willing student.
The immediate good effects of it, are only exceeded by its ultimate consequences.
In prosperity the true Christian is taught to be watchful and humble,
and to consider that "`the Lord has given, and the Lord`" can "`take away.`"
In adversity, how happy he is, if he do but remember,
that "`this also is the Lord`'s doing.`"
In all that he does, his design is ever to do good,--his motive the glory of his Maker.

Same date.--Oh, Lord, you have been pleased to bruise me with a sense of my own iniquity;
you have in some degree opened to me my own heart: deliver me in your own time and way,
from under the burden of my transgressions:
still continue to show me your lovingkindness,
and to direct me onward in the path that leads to salvation.
I know not, and it is better, O Lord! that I know not,
in what condition or situation tomorrow`'s light may find me;
nor can I see before me:--yet I pray you, if I do forget or forsake you,
Oh, forsake me not utterly, for your mercy`'s sake.

1815, February 5th.--Oh, may I not neglect or delay to take such effectual measures,
as may certainly lead me to the attainment of a firm belief
in the salvation brought about by the Saviour of men.
May I not be satisfied with a historical acquaintance with these things,
nor be content with what others may say, write, bear witness of, or believe in,
respecting a Redeemer; but may I be encouraged, like Thomas the Apostle,
to see and feel for myself; and may I make an availing use of every opportunity,
every appointed means to gain the excellency of the knowledge of Christ Jesus,
and him crucified,--that intimate knowledge and inward experience, compared with which,
Paul counted all things else but as "`loss`" and dross.
Surely,
such as are "`kept by the power of God through faith
unto salvation,`" are none but those,
who have submitted themselves to the government
and dominion of Christ by his Spirit in their hearts;
and these truly know Him to be their Redeemer.

1815, February 12th.--Oh, for that prevailing seriousness,
that habitual state of dependence, humility, and gratitude,
as in the sight of the Supreme Being;--that disposition of mind
which inclines to "`pray without ceasing,`" "`in everything to
give thanks,`" and to "`avoid every appearance of evil.`"
These symptoms of a soul that "`walks with God,`" have been indeed greatly lacking.
Although the outward tokens of a religious life,
may have continued much the same as before;
yet have I to acknowledge and lament a general tendency to indifference and coolness,
with respect to religious matters, as well as a neglect and forgetfulness of Him,
whose right it is supremely to reign in the hearts of His people.
How often is this half and half--this lukewarm temper,
which loves the Lord with divided affection,
the beginning of more flagrant transgression.
But may I not be discouraged,--rather may I remember that He,
who by his reproving witness has discovered to me this evil,
has done so that I should through His assistance subdue it;
and that he will by no means withhold that strength, which will enable me to do so.

When I look back at the long course and succession of blessings which have been
experienced by me,--when I review the opportunities which I have enjoyed of making
the attainment of vital Christianity my constant study;
and then see how very small has been my advance in religious principle and practice,
I cannot help feeling extremely sensible of the long-suffering
and compassion of that Being,
who has not merely heaped upon me, day after day, and year after year,
innumerable outward blessings,
but has in much mercy been pleased to rescue me from a state
of hardened forgetfulness and abandonment of Himself.
He has opened a way to me, whereby I might escape that bondage to sin,
(which did at one time nearly overwhelm me,) and that punishment
which would otherwise have inevitably overtaken me.
He still continues his forbearance and His tender mercies,
though I so often decline from the path which He has plainly pointed out.
How long then, Oh, my soul, will you despise the riches of His grace,
and reject His offered and extended salvation?
How long will you in words acknowledge, and in very deed deny Him?
How long will you in praises and in prayers draw nigh unto Him,
while in the particular conduct of every day you do abuse His gifts,
forget and forsake the Giver?

1815,
February 19th.--Oh, how transient is that momentary glimmer--that faint and feeble spark,
which at intervals seems to rekindle and revive in this poor, frail tenement of mine!
How soon is it quenched and smothered,--how quickly
does it disappear and leave me cold and cheerless!
What apathy, what indisposition and insensibility, to the beauty of eternal things,
does the absence of this glorious light leave in the soul,
which longs for the arising of the Sun of righteousness--for the appearance
of that "`which shines more and more unto the perfect day!`"^
footnote:[February 23rd, was the first Monthly Meeting I attended, it was at Wandsworth.]

1815, February 26th.--Blessed be the Lord!
I think that I am in some small degree enabled to trust and believe,
that there has been some little growth and advancement in lowliness and meekness,
which are the ground work of true wisdom.
How shall I sufficiently express what I feel, when I look upon myself,
when I consider what and where I have been, and who He is,
that has lifted me out of the mire, and rescued my soul from destruction.
