== Chapter II.

Sixth month, 1815.--I have attended the yearly meeting for the first time, this year,
through all the sittings, and have had very much satisfaction therein;
especially in observing the consistency which seems to run through
the conduct of the business coming under the care of Friends.
This was to me a very favored time,
and my soul was reached wonderfully by the visitations of the day-spring from on high.
Though I have but little to remark, either on the subject of Friends or their discipline,
I cannot help expressing how grateful I feel,
for the blessing of being in some degree alive to serious impressions,
and thirsting after a knowledge of Truth.

2nd.--How many are there who live in a state of sin,
of blindness as to their best interests, or of drowsy indifference!
The more I seek to know the Lord and to remember his mercies,
the more plainly and clearly does he graciously manifest himself;
and the longer I meditate on his attributes, the more firm is my conviction,
that the ardent and heavenly desires with which he has favored me,
will not sleep in death, but will pass, uninjured by the wreck of nature,
to those hallowed and happy regions,
where nothing will interrupt their enjoyment forever!

Ninth month 5th.--Surely one would think the bitter cup, of which so many, so very many,
of our fellow creatures have to drink,
ought to be enough to stop the dissipation of the gay,
to check the extravagance and the avarice of the rich,
to make the heedless pause and the wicked to consider.
For my own part, when I hear and see everywhere around me,
the affliction of the destitute, the cry of poverty, the groan of sickness,
and every extremity of anguish and trouble, both of body and mind, I cannot but exclaim,--
"`What am I, that I should be blessed so abundantly above others in every sense?
and what ought I not to be,
who am so eminently favored with almost every variety of earthly comfort?
How shall I dare to encourage or give way to pride, envy, passion, intemperance of joy,
or levity of heart,
when in one short day I may be deprived of every thing
in which I have outward comfort and confidence,
and in one moment may be leveled in the dust from which I came?`"

22nd.--There is that to be met with and felt,
in the company of and intimacy with Friends,
which is better experienced than described,-- a happy, serene, and calm temper,
full of forbearance and love, and affection to all,
and well seasoned with sober humility; such as elsewhere I have never been able to find.

Eleventh month.--"`Simon, do you sleep?
Could you not watch one hour?
Watch and pray, lest you enter into temptation.`"
I have been more than once strongly reminded,
of this short but very impressive expostulation of our Lord to his slumbering disciple,
and of the salutary exhortation that follows it.
I have thought how much need there is for every one of us,
often to apply the same language to ourselves.
O! how very few of us ever watch even one hour!
And although I am willing to believe many do remember him,
on whose extended mercy they every moment depend; yet this season is, I fear, but short,
and the impression but transient.
I cannot therefore help expressing my desire that every one of
us may be enabled to stand continually in the fear of the Lord,
to bear in mind our exceeding great liability to evil,
and to depend not upon our strength, but upon the power of Him,
through whose strength alone we can do valiantly.

No date;
probably late in 1815.--The first thing that I
would recommend to any one seriously inclined,
is, that he should not quench or stifle in any manner the precious spark,
which the Lord in infinite compassion, has kindled within him.
O! let such a one do nothing which is likely to impede
the growth of this divine seed of grace within.
Let not any deny to his own soul the nourishment which is to support it:
for though the world esteem him very lightly, and even ridicule him,
yet "`if his own heart condemn him not, then has he confidence towards God.`"

No date.--I am much displeased when I see a person accommodating his
character and turn of mind to those among whom he is cast,
changing his appearance according to the situation he is placed in.
I see little apology for such persons in that saying of the Apostle,
"`I am made all things to all men,
that I might by all means save some;`" because such persons omit the
latter part of that text,--"`and this I do for the gospel's sake.`"
In those of whom I speak, there is no intention by this variable conduct to serve others,
but rather to save and deliver themselves from the scandal, odium, and reproof,
likely to be cast by serious people upon levity, folly, or sin,
and by the less sober upon any thing like sobriety.

There is a consistency of character, which,
while it does not bring on religion the charge of moroseness and unyielding severity,
yet does not deny its great Master;
and which though it does not obtrude its opinions or practice upon the notice of others,
is not backward to show decidedly, to which standard it belongs,
and under whose banner it ranks.

1815 or 1816.--Surely I ought to thank and praise the
Lord for his abundant mercy in thinking of me;
and especially in wounding my vain confidence and self-dependence:
surely I am highly favored by his numerous and heavy corrections.
The worldly man, and the evil doer, and the indifferent nominal Christian,
go on "`fair and softly,`"--they have, perhaps, few and slight troubles;
but he whom the Lord visits and notices,--he whom the
Lord deigns to regard and to prepare for himself,
is purified in the fire of affliction, as silver seven times tried.
Why then should I be troubled and disquieted?
why not rather endeavor to co-operate with the Lord?
since I know verily that it is for my good,
to teach me from the consideration of the brevity of life,
the uncertainty and instability of earthly things,
the weakness and wickedness of my own heart, and the frailty of others; to teach me,
I say, from these and other considerations,
to press forward to the attainment of those things
which will open unto me a way to peace and joy eternal,
through Jesus Christ.

First month, 1816.--I am unexpectedly led at this time into much inward exercise of mind,
being earnestly desirous that I may lay hold,
and keep hold of those things which pertain to life and
salvation,--to run daily that race which is set before me.
Those who seek the Lord to serve him,
shall indeed find him and the knowledge of his will: where the desire is,
there is a favorable evidence;
seeing that every good gift and every perfect
gift comes down from the Author of all good.
Divine grace which begets this desire, though smothered in many hearts,
has freely been given, without respect of persons, to all; and is sufficient, if obeyed,
to work out the salvation of all, to lead them in the way they should go,
and to give them strength to walk in it:
how then should we cherish this precious desire after holiness, and that little seed,
which, if preserved and fostered, will grow up and become a large tree,
bringing forth fruit abundantly; and what injures,
what nips the tender bud in its springing forth, but those things that are evil,
or that tend to encourage evil.
Oh! how would this little spark, this divine fire, if not quenched in its arising,
burn up every piece of straw and stubble within us, every thing that is not durable;
and even such things as silver and gold would not escape the influence,
but would be melted down, refined, and seven times purified.
Now this light within may not at all times be equally discernible,
-- we may be deprived of the sense of it for a season; but when this is the case,
we ought especially to be very vigilant and sober; for it is in these intervals,
that the enemy most generally finds the door open, and the sentinel not at his post.
Let us beware lest we forget ourselves during this time of trial,
when we do not sensibly experience within us the presence of Him,
in whose presence there is fulness of joy.
Let us then seek unto the Lord still more earnestly, and patiently wait his coming,
in silent subjection of soul, desiring not our own will, way and time, but His.
Surely there is cause for thankfulness in the midst of the driest season,
and even when to our own apprehension we are forgotten
and forsaken by Him whom our soul desires:
for we know that it is the same Lord, who gave to us the gift of his grace,
that has himself permitted the sensible feeling of it to be taken away,
and all for our good, though we may not think so.
Let us then learn,
in whatsoever state it may please infinite wisdom and goodness to place us,
therewith to be content.

On the 24th of first month, my dear father, +++[+++who had been long an invalid,]
got rapidly worse.
I attended him nearly all the day, and but little thought of the event that followed.
I sat up with him till between two and three o'clock the next morning.
He died in much composure, at about a quarter past ten on fifth-day morning,
the 25th of first month.
I continued with the rest of our afflicted family to mourn,
and I trust humbly to submit to this severe dispensation, lifting up my soul unto Him,
who alone is able to sanctify our troubles to us, day and night with tears and sighs,
until the day of the burial,
when we accompanied the remains of the endeared object of our gratitude, affection,
and respect, to its resting-place.

Second month 4th.--I have been led to think that the only
substantial source of consolation in times of trouble,
is a firm and an abiding faith in our Maker and Redeemer.
Whatever anguish a sincere Christian may groan under,
whatever wretchedness is permitted to come upon him,
yet "`let him trust in the name of the Lord, and stay upon his God.`"
David seemed to trust with great energy, when he says, "`God is our refuge and strength,
a very present help in trouble; therefore will we not fear,
though the earth be removed,`" etc.: -- "`The Lord of hosts is with us,
the God of Jacob is our refuge.`"
Though man is born to trouble, and every one of us must sooner or later suffer;
yet a simple implicit reliance on him in whom we have believed,
will be found sufficient for our consolation and support.
We are allowed to mourn;--a blessing is attached to mourning;--the
effect of godly sorrow is said to be repentance;--Jesus himself wept;
and it is said of him, that "`he was a man of sorrows, and acquainted with grief.`"
But we are reminded not to "`sorrow, as those who have no hope.`"
Let us then, in the midst of the most acute and poignant grief, never despair;
but rather with upright Job,
let us endeavor to attain to that lowly submissive frame of soul,
which leads us to commit ourselves to the disposal of
an Almighty Creator and merciful Father.

8th.--The deepest affliction which is caused by
the privation of outward objects and things,
however near and dear those objects may have been to us,
cannot be compared to that utter distress, and anguish of spirit,
which the pilgrim is permitted at times to undergo on his journey towards Zion.
Who can have an idea of it, without having experienced this trying situation; when man,
who is by himself a poor, weak, helpless creature, dependent upon his Maker for strength,
encouragement, consolation, and ability to do and to think anything aright,
is thus left apparently, and exposed to the attacks of a relentless enemy,
without guide or guardian, naked, hungry, blind,
diseased,--where shall poor man find shelter in this stormy season of life?
Oh! "`let him trust in the Lord, and stay upon his God.`"

In this time of desertion,
when after "`toiling in the midst of the sea,`" being "`tossed with
the waves,`" and "`the wind contrary,`" he seems well nigh spent,
and apparently no nearer "`his desired haven;`" then,
if he cry unto the Lord in his trouble.
He will bring him out of his distresses: He will make the storm a calm,
so that the waves thereof will be still;
and the troubled disciple shall see Jesus coming unto him walking on the waves,
and shall hear him distinctly say, "`Be of good cheer, it is I, be not afraid.`"

18th.--The Lord in his infinite mercy has been
pleased to strike me to the earth like Saul,
with a sense of my sins, and to enable me sincerely and fervently to inquire of him,
"`What will you have me to do.`"
I can indeed testify that his forbearance and
long suffering towards me have been wonderful;
and I have great cause for daily thanksgiving,
that I have been taught in some small degree the knowledge of myself,
and in much mercy shown the abominations and gross evils,
in which my heart was enveloped:
the coverings of self and sense that disguised the real state of my mind from me,
have been in part removed;
and I have been permitted to discover a glimpse of what I ought to be.
My ardent desire therefore is, that He who has helped me thus far,
would be pleased to continue to extend his paternal care over me;
that he would preserve in me an invariable desire to do and abide by his will,
at all times and in all things; that he would teach me the knowledge of the Truth;
and that I might be so strengthened therein, as to be enabled to say in sincerity,
-- "`I am yours,--do with me what you will.`"

Third month 16th.--O! how exceedingly ought we to praise and to bless
the name of the Lord for all his dispensations and gifts:
my soul is at this time very much impressed with
a sense of the bounty of that great Giver,
who in mercy educes blessings from those things which least of all appear such.
But of what avail is such a sense of the goodness of the
Almighty--such a conviction that "`the Lord is good to all,
and that his tender mercies are over all his works,`"--unless this conviction leads
us to put our whole trust and reliance on Him in every circumstance and situation,--
unless we are induced with still greater firmness,
faith and "`patience,
to run the race that is set before us,`" to endure our appointed trials;--in short,
to take up our daily cross and deny ourselves, out of pure love to Him,
who first loved us, and still does love us.

31st.--I have thought that my state of mind much
resembled the luxurious growth of some stripling plant,
which springs up quickly, but requires much pruning and cutting back,
sometimes even to the ground,
in order that its strength may be proportioned to its height,
and that it may be brought into a bearing state.
Why should I not then submit to the management of the great Husbandman at all times?
Though like the skillful vine-dresser, he rub off every bud that does not show fruit,
though he bind me to the wall, though he cut out the canker in the bark,
and pierce to the very pith; yet do I most certainly know, that he cares for me,
and intends my purging unto fruitfulness and perfection.

Fourth month 3rd.--I can scarcely refrain from writing a few lines,
on the occasion of '`s bearing open testimony to those principles,
which I believe he very sincerely has espoused.
It must indeed be a trying time with him, not only just now,
but perhaps henceforth through life.
The change of dress and address, though a simple small thing in itself,
must doubtless be a pretty constant source of ridicule and contempt,
both in his presence and behind his back.
I could say much in favor of his sincerity,
and I think his exercises have not been few or slight, even as far as I have seen.
Though I have had but little direct communication with him on religious subjects, yet,
in his deportment and conduct, in general so reasonable and upright,
there has been much instruction for me.
I have seen many evils and errors in him,
evidently brought under correction and government,
and the chords of his practice and daily conduct drawn tighter and tighter into tune;
and in witnessing this process, my admiration has been not a little excited,
in the full belief, that it evinces a power greater than his frailty,
under the influence of which he endeavors to live:
he has proved and does prove a living lesson and example to me, and I think to others.
On looking again at the matter which gave me occasion for writing this,
I am inclined to add,
that the following considerations seem of too much importance long to defer examining;
First, whether I am satisfied to continue as I am, in respect of outward profession;
Second, if not, when is the right time to make any alteration; Third,
what precise change is to take place, in what particulars, and on what grounds.
And may He, who alone can preserve my soul from evil, be with me;
that so I may not err on the right hand, or on the left.

11th -- Having a short reprieve of a week,
before entering into a business which is marked out for me, +++[+++at a Solicitor's office,]
I avail myself gladly of it to record my heartfelt and sincere expressions of gratitude,
that amidst all my backslidings and omissions,
during the period of retirement which I have had of late,
there remain to me yet some small bright spots and points,
at which I can with satisfaction look back.
For though there have been many and great errors and failings,
and at times an almost total forgetfulness of that Being, whose wisdom made me,
and whose mercy is still over me; yet am I encouraged in the belief,
that at many seasons there has been a desire after, a searching for, the living God,
and for the knowledge of his will, whom to know is life.
I have indeed learnt by reiterated and painful experience,
the constant hability to which poor man is exposed,
of forgetting or forsaking the fountain of living waters, the Father of infinite mercy,
who is daily striving with his self-willed creature, man.
O! I have learnt, and may the lesson be indelibly impressed on my soul,
that it is good for a man to watch--to watch and be sober,--to
fear always,-- to abide in His love who first loved us.

14th.--Uncertainty as to the time and manner of our departure hence,
and certainty as to the fact itself,
seem to be the limit of our knowledge in regard to this awful subject.

We know indeed neither the day nor the hour when we shall be summoned,
by an all-righteous Judge to render an account.
Seeing then that such is our case,
may we yet more and more earnestly strive after a state of preparation,--
having "`our loins girded about and our lights burning;`" that,
so whenever the awful call shall go forth, whether at midnight, in the morning,
or at noonday, we may be found amongst the trusty servants, "`whom the Lord,
when he comes, shall find watching.`"

Fourth month.--O! how ardent at this moment is my desire and prayer
to the inexhaustible Fountain of transcendent love and mercy,
that it may please Him according to his marvelous compassion,
so to dwell in the hearts of his poor dependent creatures,
that through His sanctifying presence and power, they may be preserved from evil;
and not only this, but that the minds of men may be more and more opened, enlivened,
and enabled to discover the beauty and the bliss inherent in the Truth.

O! how largely I could dwell upon the wonderful goodness of that Being,
whose daily communication and connexion with his creatures,
by his providence and by his more immediate influence,
most clearly manifests Him to be the all-seeing God.
How do I long for that period, when loosed from all earthly impediments,
as well from the necessities as from the frailties of the body,
I may be enabled to offer pure and acceptable adoration and
hallelujahs to the infinitely glorious Source of love and mercy.

16th.--Went this day for the first time on trial to Solicitors;
being at the office at nine in the morning,
and leaving it at nine in the evening to return home at Clapham.
Did not attend a meeting in the middle of the week on first going there;
but the third week I went to Gracechurch Street Meeting,
and regularly afterwards to some one meeting, unless absolutely impracticable.

30th.--Independent of all other considerations which might
induce me to court the company and intimacy of Friends,
and many other reasons there are, this one would have much weight with me, namely,
that into whatever Friend's family I have gone,
I have not as yet failed to find them a happy set of people,-- cheerful yet sober,
liberal yet strict, and above all things, sincere and honest,
I have not had much acquaintance with Friends; but I may truly declare,
that I have seldom, if ever, gone away from a Friend's house,
without carrying with me a temper and feeling of mind so peaceable, so calm,
contented and cheerful, full of such warm desires of being and doing good,
as are by no means easily effaced.

Fifth month 1st.--Though pressed hard for time,
I am constrained to commemorate the admirable
goodness of the Lord to my soul this morning,
in evidently answering my petition, and affording me suitable instruction,
which was received, I trust, with benefit.
At Gracechurch Street Meeting this morning,
being weary with my own intruding imaginations,
and earnestly desiring to be rightly directed in the
awfully important business which I came about,
and for which I had given up much to obtain liberty of attendance,--a
secret prayer seemed to arise and run through me,
that, if it were best,
I might through some instrumental means be informed and
instructed in the great duty of public worship.
No sooner had such desires presented themselves, than Mary Savory rose,
with nearly if not exactly these words; '`Look not unto man,
whose breath is in his nostrils, O you of little faith; but look you unto the Lord,
who is mighty to deliver, and able to save to the uttermost,
them that trust in him.`' As if she had said,
'`Look not for direction in this matter to man, but to the Lord,
who can best instruct and incline you when and how to worship
himself acceptably.`' This instance of condescension was,
and still remains a memorable one with me,
and is not less gratefully remembered on account of having
experienced many especial favors of a similar nature and description;
some of which indeed have been still more striking.

8th.--My birthday; +++[+++nineteen years of age.]
I contrived to get one hour in the garden in the morning,
though so closely tied to business.
Many reflections appear to have been my companions in
the midst of much business at this time;
indeed my mind was greatly exercised and tried, yet also comforted, yes, unspeakably,
during this season.

Hitherto the Lord has helped me;
hitherto has he helped me exceedingly,--more than I could even have thought or asked:
and I can abundantly testify to this truth,
"`no good thing will He withhold from them that walk
uprightly,`" or even from them that seek to do so.

27th.--I cannot but believe,
that the Lord will redeem my soul from the depth of difficulty and distress,
which seems to encompass it; though there seems no way, he will make one over the pit,
which is dug about me by my enemy.
Thanks be to the adorable fountain of all goodness, my faith is yet firm.
I know in whom I have believed and trusted, and that He is still able and willing,
and shortly, in his own time, will make bare His arm,
which is indeed mighty to save and to rescue,
I read that the prayers of some formerly did ascend even into the ears of the most High,
and came before him as a memorial; now I do heartily and indubitably believe,
that "`He is the same yesterday, today,
and forever;`" that "`his arm is not shortened that he cannot save,
nor his ear grown heavy, that he cannot hear`" the cries of such as seek his direction.

29th.--O! Lord God of my fathers, the protector of every one that puts his trust in you,
be pleased in your unbounded compassion and unutterable mercy,
to look upon your afflicted servant for good.
O! Lord, you know my case and circumstances better than I can possibly relate;
you see all my needs, my troubles and my fears: in your abundant and overflowing mercy,
forsake me not in this time of trial and deep exercise of spirit.
O! you are mighty to save and to deliver, help me that I perish not in this extremity;
but that aided by you, I may be enabled to do your will while here, whatsoever it may be;
and be prepared to glorify you forever hereafter.

30th.--O Lord! the Father of the fatherless, the helper of the helpless,
the friend of the afflicted; who have promised never to forsake them that seek you,
and trust in you;
receive the sigh and tear of one whose spirit cries unto you day and night,--yes Lord,
you know, through every hour of the day.

I pray not that you would take me out of the world, or from that station and place in it,
which in your infinite goodness is appointed for me;
but this does my spirit crave of you with unspeakable fervency, even that in all things,
at all times, and in all places, you may be pleased to dwell with me,
and to keep me on every hand from all evil.

Sixth month.--According to my present feelings and experience,
I do verily believe that the business upon which I have entered,
is such as requires much more time, close study and attention,
than I can conscientiously give up thereto;
it does entail such entanglement and engrossment in the things of time,
as to leave to uncertainty and almost inevitable neglect the things of eternity,
I also am of the firm persuasion, that business is not of that first importance,
which is so generally attached to it;
but is and should be secondary and subordinate to the first and greatest object in life.

Same date.--If after all means and endeavors are made use of,
we believe that any thing is right to be done, surely it is our duty to do it.
We ought not to look at the effects or consequences of thus having acted,
but to leave them to divine wisdom,
that he may overrule or dispose of them as he sees best,
whether he is pleased to give us satisfaction within and the approbation of others,
or to withhold them.
None can tell us of our duty with certainty in every respect;
they can tell us of the great fundamental and indispensable rules of the moral law;
but in such actions and steps, the omission of which is no breach of morality,
others can only recommend what they think is right;
yet this is no infallible rule for us.
Now who is more likely to come to the knowledge of his duty in any particular,
than he who in sincerity and simplicity is daily and hourly
striving to conform himself to the will of his Maker,
as far as he knows it.
Such a one should not despair or grieve,
if in every respect he does not immediately and
clearly discover his way cast up before him;
but rather should join faith to his obedience;
endeavoring to be content and thankful that he is permitted to know what little he does,
and is enabled to act up to that little; humbly hoping, and patiently waiting for more,
if necessary.

12th.--I have often been struck with the close analogy,
which many narratives in the Bible bear to the state of our own minds.
The manner in which Thomas received the intelligence communicated by his fellow Apostles,
of the resurrection of our Lord from the dead, has more than once impressed my mind,
while I looked at myself and my own state.

I have been led to think,
that any hesitation or delay on my part to believe in
and to receive the Lord of life and light,
who is striving with me day by day, who is watching, waiting to be gracious,
who is knocking at the door of my heart almost every hour, who is calling me,
and running after me as a shepherd after his lamb that is gone astray,
--is somewhat like the tardy yet deliberate conviction of Thomas,
who overpowered at length by the abundant evidence
which the Lord was pleased to shower upon him,
was unable in the fulness of his heart to say more than "`My Lord, and my God.`"
O! I do indeed desire, not only to be firmly convinced of what is right,
but to be willing to sacrifice every thing to the performance of the same, with courage,
resolution, and constancy.

13th.--O! Lord, make me still more and more entirely devoted and dedicated,
given up and surrendered unto you: Teach me, I pray you,
still more perfectly the way that I should walk in,
each step that I should every moment take while here;
that so through your boundless mercy I may be safe on every hand from every thing evil.
O Lord! if it so please you,
I implore you to take from me all vain confidence in
myself or others,--all my own strength and wisdom;
and impress upon my soul an earnest sense of my own nothingness and helplessness:
that so through the low vestibule of true humility,
I may be enabled to enter your glorious temple,
and therein to offer acceptable sacrifice and praise unto you.

28th.--On considering the subject of the business proposed to me to enter upon,
+++[+++that of a Solicitor,]
I can acknowledge that I would this day sign the articles of clerkship,
if I thought it right to do so;
but I feel too much given up and dedicated in heart and mind to Him,
who has all my life long blessed and helped me,
for me to undertake this proposed occupation; and therefore I do trust,
that though my relations may not approve the decision, they will respect the motives.
It is, and has been day and night, my most ardent desire to acquaint myself thoroughly,
in spite of every obstacle, with the will of the Lord concerning me;
and I may safely and sincerely add, that there is and has been no fear, no grief, no joy,
so impressed on my soul, as the fear of not doing, the grief at not having done,
and the joy at having done, what I know or believe to be right.

Seventh month 6th.--Upon considering the Lord's extraordinary goodness to my soul,
and how he has blessed me more and more,
increasing my inward prosperity almost every day,
and especially of late in a remarkable manner, so that though outwardly much occupied,
my thoughts have been almost constantly raised and directed to Him in prayer
or praise;--upon these considerations my soul has been humbled at this time,
under the belief, that the Lord's hand is in an awful manner upon me,
to mould me as it seems good to him:
the feeling of this makes me fear and tremble before him.

10th.--The longer I am surrounded by the vanity and vice of this dissolute city, +++[+++London,]
the more is my mind vexed with the daily witnessing of such things;
the less also do I get reconciled to the perverted and depraved conduct and conversation,
which abound so deplorably in this place.
O! what a holy and diligent watch should we maintain,
who are placed in the midst of this vortex--this sink of filth and iniquity.
O! Lord, you alone can make and keep clean our garments;
you only can preserve in us a clean heart, and renew a right spirit within us.

25th.--The customs, fashions, vanities, and ways of the world,
have very often come under my serious consideration.
I have been, I may indeed say, oppressed with a sense of the mass of folly, which is sin,
prevalent among the children of men.
I believe the evil effects of these things are
but little calculated by many reflecting minds,
and that few look upon them in that serious light in which they deserve to be regarded,
or esteem them worthy of reformation.
It is in consequence of this lamentable remissness and weakness on the part of those,
who should stand up in resolute opposition,
that the torrent becomes stronger and stronger,
and the resistance of the few less and less effectual.

Under this impression, my soul has oftentimes mourned;
and my distress has been much excited of late,
while walking in the streets of this great city;
many of whose inhabitants seem bound in fetters, and enslaved by the caprice of pride,
luxury, and vanity.
How frequent and fervent have been my desires,
that the little band of those who professedly bear
testimony against the fruits and effects of these evils,
wherever and in whatsoever degree they appear, might be strengthened,
by a diligent recurrence to that principle which teaches a
denial of self and a renouncing of the world with the lusts
and vanities thereof,--still to hold out against the enemy.

Eighth month 3rd.--O that I might be helped this day to do the will of the Lord:
that I might be strengthened with inward might,
patiently yet firmly and constantly to persevere in what is right.
Though assaulted daily by the powerful enemy,
yet may I be favored with unwearied fortitude to watch and pray,
that he may not finally overcome.

How liable are we every moment of each day of our lives,
to fall or falter in our stepping;
and how blessed are they who are kept by the power of God through faith unto salvation.

My secret constant craving is, that in all things and at all times,
I may have such an awe and fear of Him, whom all should fear,
as to be preserved from evil; and that thus walking before him,
I may be led into the way of peace.

I remember, when under great exercise long continued on the subject of business,
and amidst many thoughts as to getting a livelihood in the world,
with my very restrained views every way,--I opened a
book in great fluctuation and sore grief of mind,
as it lay near me, craving that I might be secretly informed in this way,
or in any way with certainty, as to the line of duty prescribed to me by heavenly wisdom;
when, to my astonishment I found immediately to my hand,
this passage from William Penn's
__No Cross, No Crown,__--"`Whoever you are that would do the will of God,
but faintest in your desires from the opposition of worldly considerations, remember,
I tell you in the name of Christ, that he that prefers father or mother,
sister or brother, house,
etc. to the testimony of the light of Jesus in his own conscience,
shall be rejected of him in the solemn and general inquest upon the world,
when all shall be judged, and receive according to the deeds done,
not the profession made, in this life.
It was the doctrine of Jesus, that '`if your right hand offend you, you must cut it off;
and if your right eye offend you, you must pluck it out;`' that is, if the most dear,
the most useful and tender comforts you enjoy, stand in your soul's way,
and interrupt your obedience to the voice of God,
and your conformity to his holy will revealed in your soul, you are engaged,
under the penalty of damnation, to part with them.`"--Part I. Chap. 1. Sect. 21st.

O! here was a revelation indeed to me, if ever there was one;
for as surely as there is a secret divine power,
it was manifested in my soul in the reading of this passage;
and it so overcame me in gratitude to the Father of mercies, that my knees were bowed,
and my heart was contrited before Him at that favored season,
and tears fell in abundance.

There has indeed been a wonderful Providence all along about me,
too large to be fully set forth in order.
When the time for my decision and signing of the articles of clerkship arrived,
whereby I was to serve in an attorney's office for five years,
with every prospect that a handsome income would
succeed my application to this line of business;
and when the draft of the deed was about to be sent to be engrossed,
and I was to take it to the law-stationer's for
that purpose;--borne down by hidden trials,
my earnest fervent petition in a secret place,
where I stepped aside to pour out my soul unto God, was,
that if the Lord was my guide and my leader, he would make a way even now,
when there appeared none,
to get out of the predicament in which I was so closely confined:
and speedily that day I was taken ill, and obliged to see a physician,
who ordered me to Southampton as soon as I could go;
which was accordingly effected in three days.
I have cause to remember to this day,
how closely the mighty helper was about my bed and about my path at that time;
so that my tenderness of heart, and my cries and tears in secret,
were often remarkably answered, and were felt even to prevail with God.
My song was also unto him in the night season; and living praises would ascend,
in very small intervals of time,
when the soul had a few seconds only turn to its comforter.

When I returned from Southampton I resumed my station at the desk;
but my eye saw clearly that that place was not my lot,
though I did not even then think of giving up the profession altogether:
but that was also shown me in due season, when I was able to bear it.

So that there is indeed ground for me yet to trust and not be afraid,
as well as for others; seeing that there is One, who can make darkness light,
and crooked things strait, and hard things easy.

[.offset]
+++[+++He finally relinquished the pursuit of the law in the latter end of this year.]

Ninth month.--What inexhaustible goodness and loving
kindness has the Lord in store for those of every age,
class, and description, who strive to serve him in sincerity.
O! He sheds at times his refreshing presence and protection in
a remarkable manner round about his poor dependent little ones,
showering down upon them the dew of his grace.
I have thought indeed, that the inward consciousness of his approbation attending us,
is sometimes permitted to be as strong and evident as we could desire.
It has been graciously allotted me during this day or two,
to experience such a degree of his favor attending me,
and to feel such a measure of his divine blessing shed upon me,
that I can scarcely forbear in this manner testifying
to the continuance of his care for his creatures,
even for those who have widely strayed from his flock,
and have been long wandering in the wilderness.
Yes, O yes! "`His hand is stretched out still;`" -- praised be his name evermore!

19th.--Though I wish to be the last to find fault with the
innocent and natural sprightliness and liveliness of youth,
yet I cannot but excuse myself from joining in with what is commonly so termed,
having often felt thereby unsettled in mind, and indisposed for reflection.
I have found that by occasionally relaxing in the discipline of watchfulness,
the inclination to laughter, more particularly, gained much ground upon me;
and there has been no small difficulty in restraining this habit, when much indulged;
so that it strikes me to be a snare.
Though religion does not make a man gloomy, yet it never allows him to be off his guard;
no, he must "`watch and pray,
lest he enter into temptation,`"--taking up his daily
cross to all frivolous and foolish talking and jesting,
besides other more evident and open evils.
