== Chapter III.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to W. F.

[.signed-section-context-open]
London, October 10th, 1816.

[.salutation]
Dear Friend,

While taking up my pen to address you,
I feel very desirous not to incur the sentence denounced in Scripture,
against him that "`trusted in man, and made flesh his arm,
and whose heart departed from the Lord:`" for there is a
disposition to regard the creature more than the Creator,
in whom alone is everlasting strength.
And yet a saying of the apostles Peter and John, when brought before the Jewish council,
has often been comfortably remembered by me,
after much unreserved communication with some of my dear friends;
and I trust I may safely adopt it as my own on this
occasion:--"`for we cannot but speak the things,
which we have both seen and heard.`"
How shall I then be silent concerning the dealings of Infinite Goodness,
or how shall I forbear to testify of Him who "`delights in mercy;`" of whom it is said,
and has been experienced by thousands,
as well as by myself,--"`He will subdue our iniquities,
and will cast all our sins into the depths of the sea.`"
Indeed I have reason to say thus, and much more;
for few suspect the depth of perdition from which I have been rescued.
Awfully appropriate was that language twice repeated in the little company I sat with,
at our friend`'s house at S+++_______+++ "`You were as a brand plucked
out of the burning:`" I earnestly desire that what follows may
not equally apply,--"`yet you have not returned unto me,
says the Lord.`"
How strongly have I been encouraged, my dear friend,
to believe that even in these latter times the same
arm of everlasting mercy is still underneath,
the same crook of lovingkindness is jet conspicuously
stretched out to reclaim and to restore.
Though I have but little time or space to spare,
yet one circumstance attending my former course of life,
I may not omit to mention:--I remember, my dear friend,
(bear with me if you can,) a season when my wickedness had
arrived at such a complicated and aggravated height,
as to threaten (to all appearances and all probability) inevitably impending consequences;
and these so encompassed me round on every side, that, though a thorough adept,
I totally despaired of escaping that which was likely to follow.
At this eventful crisis, when my wretchedness was more than I can describe,
and almost more than I could bear,
there was a secret but fervent desire raised in my very inmost soul,
that if it were possible,
I might be delivered from this anguish of mind and dilemma of situation,
which were then owned +++[+++by me]
to have been brought on by my own sinfulness, and much less than was deserved.
There was also some thing like a covenant +++[+++on my part,]
that if I might be thus rescued,
no bounds should be placed to the dedication of my future life.
The sequel was as striking as the fact itself;--each black cloud of this storm,
from that very day forward, rolled gradually away,
and in a surprising manner withdrew and dissipated.
So that in truth I have had, and still have most feelingly to adopt a language,
as literally and remarkably applicable to myself,
as it could perhaps have been to him that used it,--"`He
brought me up also out of the horrible pit,
out of the miry clay:`" and I think I may add, it is equally my desire and belief,
that the remainder of this passage may and will be
as nearly my experience;--"`This is the Lord`'s doing,
and it is marvellous in our eyes.`"
Yes, my dear friend,
"`I am as a wonder unto many,`" among those who
knew me little more than three years ago,
then living in total forgetfulness, or rather abandonment of Him,
who notwithstanding did not utterly abandon me; but, as Fenelon says,
"`who followed me in my ways, which were those of sin; who has run after me,
as a shepherd in search of his strayed sheep.`"
So that I cannot be silent on this subject; but am constrained to acknowledge,
that in all my various difficulties, distresses, and dangers,
the power and presence of One,
"`who is able to save to the uttermost,`" has been with me and around me;
bringing about seeming impossibilities, making a way where no way was,
and effecting deliverance "`with a mighty hand, and with an outstretched arm.`"

With respect to that share of affliction which has been handed to me of late,
I can truly say, it is my desire, that others in their various trials,
may be equally enabled with myself to discover and acknowledge in them the hand of Him,
who "`is righteous in all His ways, and holy in all His works.`"
When privations are permitted to attend, what a consolation, my dear friend,
to find a Father of the fatherless;
when about to separate from those who have from childhood
shared the same mixed cup of joy and grief,
what a favour to feel, that wherever scattered, still each of us is near that Fountain,
to which we may all have access;
when a total revolution in our outward condition takes place, when luxury, delicacy,
splendour and vanity, together with all those objects endeared by fond recollection,
are to be relinquished,
how sweet to know "`it is the Lord--let him do what seems
him good:`" and in taking up the cross--the daily cross,
denying ourselves, and following our Leader through evil report and good report,
through sufferings, conflicts,
and probation,--what a blessing will it be if we "`are kept
by the power of God through faith unto salvation.`"

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
J+++.+++ B.

--

1816, October 22nd.--The farther I advance in my course
along this valley of mist and obscurity,
the more evidently am I permitted to discover--the
more frequently am I constrained to admire,
the infinite condescension of the Lord.
Oh, how sincerely can I exclaim with the Psalmist, "`What is man,
that you are mindful of him, or the son of man that you visit him.`"
Fervent indeed have been my desires, and still more and more so,
as the visitations of condescending mercy have been renewedly
extended--that my whole heart may be prepared for the reception
and further manifestations of this great and gracious Guest.
Oh, may there be in my inmost thoughts and imaginations,
as well as over my words and outward demeanour, such a constant watchfulness,
as may evidence a holy awe and fear of giving Him offence,
or occasioning a separation between Him and my soul.

Oh, you who see in secret, and to whom my most secret petitions are thoroughly known,
and known to ascend even daily and hourly,--be pleased,
in your exceeding great compassion and wonted mercy, to hand me a little help.
Grant that I may be made willing to follow you whithersoever you lead,
and to become whatsoever you would have me to be.

1816, October 25th.--I have been led to think that many are ready to inquire with Pilate,
"`What is Truth?`"
but not being willing to wait long enough for an answer,
(or to wrestle for the blessing),
have hastily gone out like him from the presence of Jesus, who is the only Way, Truth,
and Life, even as it were unto the Jews, the dark and outside professors;
and having consented, or been prevailed upon to join hands with those betrayers,
have fallen away from, and become opposers of the very Truth,
both in themselves and others.
Oh, that we may ever bear in mind the excellency and preciousness of the Truth;
and thus be made willing to encounter any thing that is, in the smallest degree,
an obstruction to our reception and acknowledgment of it.

1816, November.--Do not look at others,
whether their example seems to recommend one line of conduct or another,
no not even at such as are very industrious in business,
and yet accounted strictly religious characters;
they are no guide for you:--stand on your own ground;
nothing will justify what you are about to do, or to forbear to do,
but a full conviction of duty.
If you have that true peace which no man can give or take away,
it matters little what others may say or think.
Remember that the honest fishermen quitted their lawful concerns, no all,
to follow Him that called them,--but it was not till He called: the hundred fold reward,
and the everlasting inheritance were promised,
not to those who merely forsook all that they had,
but to those who did so for his name`'s sake.
I think it was William Penn who said,
"`it is not the sacrifice (however great) that recommends the heart,
but the heart that gives the sacrifice (however mean) acceptance.`"

1816, November 9th.--Oh, what shall I say, or what words shall I make use of,
to declare fully the Lord`'s goodness and compassion to this poor frame of mine!
Day by day, yes, all the day long, is his hand renewedly and refreshingly turned upon me,
for my present and everlasting welfare.
Even when the power of the wicked one came over my poor soul,
when all desires and endeavours after good--after "`those things
that make for peace,`" were to appearance utterly extinguished,
even in that dismal hour,
which was still more darkened by the insensibility which benumbed me,
the gloriously great and gracious Giver of all good, was pleased to pity me,
and to revive the latent spark within me, making it grow gradually brighter.
Surely, He is working a great work within me; his hand, his holy hand is upon me;
and if not through my own default, he will by no means draw back or desist,
until he has made me all that he would have me to be.
What a multitude of obstructions as well as snares and difficulties encompass me:
how shall I put one foot forward in the right way,
except the Lord himself condescend continually to "`direct my steps.`"
And Oh, then, what a constant need there is of acknowledging Him in all my ways;
that so this promise of safe and sure direction may
happily be fulfilled in my experience;--"`The Lord,
he it is that does go before you; he will be with you; he will not fail you,
neither forsake you.`"

1816,
November 12th.--O Lord God Almighty! it is of your exceeding mercy that I am raised up,
and enabled thus fervently thus solemnly to address you,
as the God which have led me unto this day.
Oh, how clearly and comfortably have you, during this time of need,
revived the remembrance of what you have done for
them that have sought or desired to seek you.
Where is not your "`mighty hand,`" and your "`outstretched arm,`" to be discovered?
When I "`look at the gene rations of old,
and see,`" through your grace I am enabled to silence every doubt,
every discouraging fear,
by that feeling and forcible interrogation,--"`Did ever any trust in the Lord,
and was confounded; did any abide in his fear, and was forsaken;
or whom did he ever despise, that called upon him?`"
Well might your servant say, "`The earth, Oh, Lord,
is full of your mercy;`" and your prophet exclaim--"`The
whole earth is full of his glory.`"
"`And now Lord! what wait I for?
my hope is in you:`"--in you, in you alone is my joy, my crown, my confidence.
I dare not ask of you deliverance out of trouble, except in your time;
but Oh, my very soul does crave of you,
that I may be kept from everything like evil;--that I may be supported and sustained
by that "`hidden manna,`" which is promised "`to him that overcomes.`"
Oh, grant, Lord, unto him,
who feels himself at this time awfully humbled under your
mighty hand,--that he may be made still more deeply sensible,
that "`you are God alone:`" and as often as you are pleased,
in your very abundant compassion,
to renew within him that which constrains him to cry out, "`My soul thirsts for God,
for the living God,`"--at such precious seasons,
may he be satisfied with nothing short of You;
and strengthen him to endure patiently through all,--waiting upon, hoping in,
and watching for you!

1816, November 23rd,--At the present favoured interval of retirement and leisure,
I am concerned to repeat an inquiry, more than once instituted before this time,
whether I am not now called upon to declare and profess before men,
the religious persuasion and principles which I most surely hold;
and to adopt that course of daily practice in conduct and conversation,
of the reasonableness and rightness of which I have not any doubt.
It does appear to my view highly and imperatively necessary,
that an internal change should precede an external one.
I believe that conversion is that of the heart; that profession must follow,
not go before possession;
and that an outward show and appearance of peculiar
seriousness is hypocrisy and increased condemnation,
if not accompanied by the inward work of sanctification in the soul.
Nevertheless,
it is certain to my mind that one invariable evidence of
true religion having entered and taken up its abode in us,
will always be,
that we shall no longer conform ourselves to this world in its vanity and folly;
and that, in our dress, address and general conduct in every particular,
we shall not be governed by worldly maxims or opinions,
but by the law written in our hearts.
How far then is this the case with me?
How far can I assuredly say, that this change of heart is my experience?
Oh, I feel indeed that I come short of what ought to be my practice;
that though I have given up my name to serve the living God,
even Him who has led me unto this day,--though I have withheld not some things
which were required of me to give up and to forsake,--yet has not my heart fully,
entirely, and without reserve resigned my all.
Oh, there have been those parleys and tamperings with sin, those secret relapses,
those connivances with the enemy, which the Lord abhors.
What a total surrender of self does our pure and righteous Lord call for;
what an abandonment of everything evil does He expect from his followers;
what a daily and hourly watchfulness and circumspection is required of those,
who would be heirs of a glorious mansion, where nothing impure can enter!
How very appropriately is it written, "`Be holy, for I the Lord your God am holy.`"

Same date.--How beautiful, how glorious a sight is it,
to behold the sun in the morning when it issues from its bed of crimson hue,
when it gradually ascends the horizon, dissipating the dusky gloom of fading night,
and tinging every object in nature with its golden rays.
And Oh, may I not say, that through the blessing of a gracious Creator,
I am enabled almost daily to witness the spiritual arising
of the "`Sun of righteousness with healing in his wings.`"
Surely the day-spring from on high, "`through the tender mercy of our God,`" has visited,
and is visiting me;
and assuredly the end and purpose of his arising is the same that it was formerly,--even
"`to give light to them that sit in darkness and in the shadow of death,
to guide their feet into the way of peace.`"
I think I say not amiss, when I declare my belief,
that the light within me seems to get brighter, and the fire warmer almost every day.
Oh, that I may be content to remain in the refiner`'s fire,
that so I may become purified and refined from everything evil.

1816,
November 27th.--I have been long in much trouble and difficulty about changing my dress,
as well as adopting those other distinctions and
testimonies which Friends uphold and practice;
and my anxiety respecting these things has been,
lest I should take them up without good ground,
and without being clearly and indubitably sensible that these sacrifices are called for.
Indeed, I have gone mourning on my way, day after day, and night after night.
Perplexity and discouragement, darkness and distress,
have at seasons clouded the horizon of the morning of my days; and mainly,
be cause I knew not certainly the Divine will, as to these external observances,
and as to many other sacrifices.
But I think that this subject has been cleared up very satisfactorily to me this day,
in much mercy, both by what I felt,
and by what was delivered through a servant of the Lord, at meeting.

Same date.--I see evidently,
that "`Jesus Christ came into the world to save sinners,`"
and that "`unto them that look for him,
shall he appear the second time,
with out sin unto salvation;`"--"`the wages of sin is death,`" and consequently,
that without repentance there is no remission of sin;--that we
must be in the way of being redeemed from the power of evil,
or the punishment will not be remitted;--that we must be delivered from sin itself,
before we can be delivered from the wages of it, which is condemnation;
for it is aptly expressed,
"`There is now no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the Spirit.`"
Oh, then my soul,
surely there is required of you a clean heart and a right spirit to be renewed within.
Oh, how shall I bestow pains and anxiety about cleaning the exterior,
while there lurks any filth in the interior.
How shall I garnish the outside with an appearance of the beauty of holiness,
and polish it after the similitude of a temple dedicated to the Lord,
when it stinks within by reason of the defilement there concealed.
Surely it was well said by the Lord to those hypocrites the Pharisees,
and it equally applies to many in these days as to them;--"`Cleanse
first that which is within the cup and platter,
that the outside of them may be clean also:`" and the latter part of this exhortation
remains strikingly true,--for I am fully persuaded that all cleansing of the exterior,
to be sincere and not hypo critical, must be the effect of a change of heart.

1816, December 4th.--Is it not beyond a doubt,
that the Lord will make known his will to his poor dependent creatures,
who with sighs and tears both day and night seek to serve him aright in all things?
Surely He is no hard master,
who does not evidently let his servants see what is required of them; nor,
I am persuaded, does he at any time call for more arduous service,
than he gives strength to accomplish.
But then He must and will be sought unto,
both in order that his will may be clearly known; and when known,
that sufficient strength may be handed to enable to perform the same.
All my desire is before the Lord; and he knows, and I believe,
hears my prayers,--he sees my watchings and my weepings, and is witness to all my woes.
I do indubitably believe that the present time is very precious to me,--that the hand,
the mighty hand of the Lord is upon me for good,--that he is extending
his gracious visitation to me his poor sinful creature,
who has been bound by the bond of darkness, by the power of the destroyer.
Oh, he is and has been arising for my help, for my deliverance;
he has assuredly in some measure,
brought me as it were out of the land of Egyptian and cruel bondage;
and it appears to me impossible, unless by my own default,
that his promises should fail in the midst of the fulfilment of them,
and that he should leave me in the wilderness to die in my sins,
to be destroyed by famine and need:--no,
he has a fountain of living waters in store for me;
and though I know not whether I may partake of that delicious and reviving consolation,
out of the bare and barren rock, or on the fruitful and flowery banks;
"`yet I will rejoice in the Lord, I will joy in the God of my salvation.`"

1817, January 27th.--"`Having food and raiment, let us be therewith content,`" etc.
I have admired the honest simplicity and plain speech, which the first Christians,
and especially their great pattern, made use of to instruct their hearers:
the reasoning of the apostle in this place is unanswerable,
and the process of his thoughts appears to me so natural,
as to be not easily mis understood.
The substance of that which he sets forth, is, without any strained exposition,
nearly as follows:--the gain of riches is by no means godliness,
nor can it be a substitute for godliness in the end; on the contrary,
godliness is profitable both here and hereafter, and therefore is alone true gain.
Wealth and possessions last us only while we live:
we had them not when we came into the world,
and it is certain we can retain them no longer than while we are here.
Seeing then, that soon, very soon, we must part with these things,
let us provide "`bags which wax not old,
a treasure in the heavens which fails not:`" and as to everything else, the riches,
the enjoyments of this vain and passing scene,
let us use these things as not abusing them; let us not be slaves to them,
but rather render them of service to us.
If we are rich, let us not hide our talent in the earth, but be rich in good works:
and if we are in a middling condition as to outward circumstances,
let us endeavour so to act,
as to be able strictly to adopt the apostle`'s language,--"`these
hands have ministered unto my necessities,
and to them that were with me.`"
Thus we shall be enabled more fully to understand, and more freely to accede to the text,
"`having food and raiment, let us be therewith content.`"

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to Lydia Ann Barclay

[.signed-section-context-open]
Clapham, January 29th, 1817.

[.salutation]
Dear Sister,

I am inclined to believe,
that we are somewhat similarly situated in a spiritual point of view,
and therefore that a few lines from one who desires to ac company you +++[+++you]
hand in hand through this painful pilgrimage, may not be unacceptable.
On reading to you the very reviving and refreshing Psalm which occurred to me yesterday,
I was ready to think that we could hardly take with us too
much courage on our perilous journey through life.
Some may look forward at the commencement of their course,
with no other feelings than those of cool complacency and comfort,
as if our life while here was somewhat like a summer`'s day;
others may view this state of being as a vivid and glittering scene of continued enjoyment,
and like the gay and giddy butterfly,
no sooner are they in existence than their sport begins.
But Oh, the longer I am permitted to remain here,
the truth of that view of life which the Scriptures present,
appears more and more evident.
Is it not there said to be a state of trial and of trouble?
"`Man is born unto trouble as the sparks fly upward.`"
When I look as far before me, as my imperfect and short-sighted senses will enable me,
I see mountains of opposition and difficulty, wastes of desolation and desertion,
floods of affliction,
and rivers of bitterness to wade through and to pass
over,--the heavens above appearing black,
and the horizon beyond veiled in obscurity.
Whatever, you, or I, or any, may think or say, be assured,
that the Christian`'s path through this state of being to a better,
is no other than that which it has always been, and will ever be; as it is said,
"`we must through much tribulation enter into the kingdom.`"
Oh, the path for you and me, as well as for all, is not such as the flesh could wish,
it is indeed a narrow path, too narrow for sense and self to walk in;
there is in it but just room and that is all:
it is not wide enough for us to pass pleasantly along with singing and with mirth;
but may rather be compared to those narrow defiles between the snow-topped Alps,
through which the traveller is directed to pass quickly, without trifling, without delay,
and in silence, lest the huge masses above him, or the parts on which he stands,
should in a moment consign him to destruction.

If this be true, then,
how very much occasion is there for us both to lay aside every weight,
everything that is likely to entangle, to ensnare, or to impede,
in the race that is set before us.
Is it not the case that we are less disposed to remember our providential escapes,
and the many mercies that have been granted,
than to murmur at the scantiness of our fare, or the bareness of our shelter.
It does then appear to me especially necessary,
that we should take with us all the strength and encouragement afforded.
And where is this to be found, but as it were in the very bosom of perfection,
in Him who alone is the true source of every good, and the resource in every evil.
Let us consider what is said of Him in Scripture,
that not one sparrow in his vast creation escapes the protecting hand,
and the ob serving eye of its Maker.
We have indeed a Parent, who is nothing but love, who created us out of the purest love,
who preserves our natural lives every moment,
whose love alone gave us immortal souls fitted for immortal joys,
and through his Son opened a way,
by which all might enter into the possession of eternal
life and glory:--and it is expressly said,
"`no good thing will God withhold from them that walk uprightly.`"
So that there is help, and hope, and happiness for all,
whatever may be their condition or situation,
excepting only such as willfully persist in refusing
or abusing extended and continual mercy.

[.signed-section-signature]
J+++.+++ B.

--

1817, February 8th.--The very important decision,
as to the line of life which I am to pursue,
has often for this year past given me much anxiety and inward exercise,--it
has often been the cause of restless nights and anxious days,
and even (I have reason to believe) to the injury of my health of body,
as well as of mind.
The anxiety which it excited in me, seems however to have been misplaced;
because I ought to have been desirous to know what was right to be done in the case,
and how, and when, rather than to find out what could be contrived or thought of,
by my own skill and management.
There ought to have been more of that simple reliance and dependence,
that trust and confidence,
which is the behaviour and feeling of a babe towards its mother; how quiet,
how calm it slumbers in her arms,--how safe and happy it is while there.
Oh, my soul, take heed,
lest after having experienced marvellous deliverances,--after having been,
like the Israelites of old, led in the daytime "`with a cloud,
and all the night with a light of fire,`"--after
having been fed as with manna in the wilderness,
and your thirst quenched with water as from the rock,--take
heed lest after all that has been done for you,
you should, through unwatchfulness or unbelief,
in the least degree doubt the strength of that hand that upholds you,
the depth of that wisdom which is directing you,
the providence of that eye which slumbers not, the extent or continuance of that love,
from which nothing but sin can disengage you.

Whatever is to be your lot, whatever task is assigned you in the vineyard,
wherever may be the scene of your earthly tarrying,
whether afflictions surprise you as a flood,
or your pleasures be as a full flowing fountain,
"`hope only in God,`" for "`from him comes your salvation.`"
Neither give place to doubt or disbelief,
nor to very much anxiety or disturbance of mind, respecting what may befall you:
never fear,--there is one that provides for the sparrows,
there is one to whom every event is in subjection,--He is good:
from his hand "`proceeds not evil;`" and he has said,
"`there shall no evil happen to the just.`"
In the mean time, in all your watchings and waitings, in all your poverty and weariness,
cease not to think of his mercies, his goodness, his tender dealings with you;
be mindful of these things; hide them not, be not ashamed of them;
but to show "`to the generation to come, the praises of the Lord, and his strength,
and his wonderful works that he has done.`"
Surely, Oh, my soul, if you do thus,
if you remember that God has been and will be your rock,
and your redeemer,--if you trust in the Lord,
and make him your hope,--you shall "`be as a tree planted by the waters,
and that spreads out her roots by the rivers;`" you shall prosper in your day,
and be established.

1817, February 14th.--O Lord! you who know all things,
the hearts of all men are open and bare in your sight;--you can not be deceived;--you
look upon the heart;--your regard is to the thought and intent of it,
and your controversy and your judgment only with the evil thereof.
O Lord! no one but yourself fully knows,
how fervently and frequently my soul does crave of you,
that you would enable your poor longing creature to step
forward with faith and firmness in the way of your requirings.
Oh, be present with me on this troubled ocean;--Oh, take me, I beseech you, by the hand,
saying, "`fear not:`" and if it be your gracious will,
be pleased to guard and govern me day by day, and hour by hour;
that so through your sufficient and availing help,
I may be made willing and able to become your true
disciple and servant,--to follow a crucified Redeemer,
through the tossings and tempests of this troubled scene,
to a glorious and an immortal inheritance.

1817, February.--I have been at this time, as at many others,
very seriously impressed with the belief of the immediate
influence of the Spirit of that great and gracious Being,
who promised by the mouth of Him whom He sent into the world, that it should be,
in his true disciples, a teacher of all things, and a guide into all truth.
There has been felt this evening a still small voice,
whispering in the secret of my soul, and gently opening what would be required of me.
It has been given me to see with an unusual degree of clearness,
that there will be an important post,--an honourable station for me to hold,
if I am but faithful to the smaller discoveries of duty;--that the track,
which for a short space I have been stepping in,
though likely to lead me in the way of usefulness,
is not the track appointed for me;--but that way will be opened, in due time and manner,
to engage in a more extensive occupation, even a high and holy calling.
I speak not here of a prospect of engaging publicly as a minister among Friends,
but of religious usefulness generally.
I desire not to be misunderstood, and thus to bring disgrace on the Truth,
or the true lovers of it:
I therefore can scarcely forbear to mention the view of my mind,
as it is and has been on this matter.
I have long mourned day and night,
and have been grievously affected with the rapid
advances which the enemy of souls is making,
on the earth at large, on professing Christians generally.
Under this impression my soul has been weighed down more or less,
for the space of above two years with little intermission,
even before I came into acquaintance with that Society,
of which I was born a nominal member.
My very health, I believe, has been at times injured by this constant anxiety;
which was not to be erased or smothered by close application to business, or by society,
or recreation.

My concern has been much increased,
by a review of the depth of perdition from which I have been plucked,
even as a brand from the burning: and by the deplorable effects of sin on those,
with whom in my vile courses I kept company.
Now I believe I may not with innocency or impunity quench, or reject,
or make light of such concerns and impressions as have their foundation in Truth,
and the end of which is the advancement of Truth;
nor am I at liberty to treat such thoughts as he did, who said,
"`Go your way for this time,
when I have a convenient season I will call for you;`" for as much
as I know not that another opportunity may be afforded me.
I therefore feel bound to encourage and cherish good
impressions by all means and at all times.
The oftener I have considered this important and extensive subject,
the more strongly have I been induced to believe,
that sacrifices will be called for at my hand;
and that I shall be constrained to take up my daily cross in a peculiar manner,
not only as to things which are wrong in themselves,
but as to those which have a tendency to evil,
and even in many things which religious people account innocent and allowable.
Oh, when I read in the Scriptures the very excellent
precepts and instructions given for us to follow;
and when I examine closely the conformity of the
lives of those by whom the precepts are delivered;
my admiration at the coincidence in every minute particular, is, as it were,
swallowed up in mourning,
at the declension of the present professors of the same religious duties.

By such considerations and reflections,
my soul is stimulated very fervently and frequently to petition Him,
who is the fountain of all good, that He would, in his own time and way,
aid his own cause;--that He would be pleased to regard the sighs, the cries,
and the tears of His exercised people--"`His own elect,
which cry day and night unto Him,`" for the advancement, extension,
and prosperity of everything that is good.

1817,
March.--The subject of dress has very frequently come under my serious consideration,--it
has of late been still more often and more deeply impressed on my mind;
and as I have kept quiet and calm,
singly desirous to know and to do whatever might be required,
the matter has opened more and more clearly before my view;
and some things with regard to it, which had been hitherto hid from me,
while in a disposition to follow my own reasonings and fleshly wisdom,
or concerning which I seemed then to be uncertain and undecided,
now brighten up into clearness,
so as to make me conclude that they are indisputably right for me to adopt.
And surely, I may add,
no sooner is a truth clearly manifested,--a duty distinctly marked out,
than it should without hesitation be obeyed.
With regard to my present dress, and outward appearance,
it is evident there is much to alter.
That dress, from which my forefathers have, without good reason,
and from improper motives departed, to that dress I must return:--that simple appearance,
now become singular,
which occasioned and still continues to occasion the professor of the Truth,
suffering and contempt, the same must I also take up,
and submit to the consequences thereof.
Some may object to this,
as if it were improperly "`taking thought;`" but I differ from them,
not in the rule itself about the anxiety bestowed on clothing,
but about the application of that rule.
It is right, if the vain customs, folly and fashion of this world,
have insinuated themselves into any branch of our daily conduct, to eradicate them,
with every one of their useless innovations, whatever trouble, anxiety,
or persecution it may cost us.
But after we have once broken our bonds, we shall find a freedom from anxiety, trouble,
or thought about our apparel, far surpassing the unconcern and forgetfulness,
which seems to deaden the spiritual eye and apprehension of the slave of custom.

1817, March 15th.--Nothing can show us and detect within us evil,
but that good principle which manifests what is evil.
It is therefore the business and duty of all men, in respect to their salvation,
to become acquainted with the grace and Spirit of the Lord Jesus Christ,
as it is revealed and appears to all men;--to follow its leadings, to obey its teachings,
to heed its reproofs.
And how are we to become acquainted with--how shall we know its appearance?
There is nothing of or in man that is good,
but that which is of and from God,--that which is of and from His grace and Spirit.
Therefore, Oh, reader, follow that which inclines to good in you;
and whatever gives you inward pain, and trouble of mind abstain from.
The more we turn away from and deny sin through Divine grace,
the more weak is its power in and over us; but the less we mortify our evil inclinations,
the less power we have to resist them, when next they assail us.
He that is faithful over one city, will be made ruler over many;
as he that improved his talent, was said in the Scriptures, to be entrusted with more.
If anyone says how shall I know assuredly the teachings of the
Holy Spirit from the suggestions of my own mind and reason,
or from the insinuations of him,
who sometimes puts on the resemblance of an angel of light?
Oh, inquiring reader, know of a truth,
that whatever may be the artifices and deceitful appearance of the enemy,
what ever may be the reasonings, imaginations,
and mental workings of the natural part in you, however specious,
however excellent they may appear,--yet are they easily and with certainty detected,
by the humble, waiting, patient, praying soul;--yes,
by every one who in sincerity and simplicity thirsts and hungers after
the knowledge and performance of the whole will of God concerning him.
These shall know the Truth, and the Truth shall make them free.
These shall know Him who is Truth; these shall be led and guided into all Truth.
