== Chapter IV.

Third month 13th, 1817.--I think it right at this time to set down my opinions,
or rather such opinions as I conceive to be sound and good,
relative to the subject of business:
I fear many of my near and dear friends have much mistaken my ideas on this matter;
and perhaps I myself have not entirely acted up in every respect to that standard,
into which the Truth leads those who follow its dictates.
I believe that it is good for man to earn his livelihood by the sweat of his brow.
If any one has,
or ever comes to have sufficient for the support of himself or family,--by a sufficiency,
I do not mean that which will satisfy all his desires,
nor that which may raise his family above the sphere in which they were born,
neither that which will furnish his children with large capitals to
enter lucrative or extensive concerns,--but if he has wherewith to
support himself and family in a moderate way of living,
and to afford his children a useful education, the knowledge of some honest employ,
and a little to begin with,--it is enough.

I am inclined to think, that such a one should consider,
whether it be not right for him to give up his business to his children,
to faithful dependents, or to relations that want it;
unless he be of a disposition that can hardly
find occupation for his mind out of business,
and in this case, let him continue to employ himself in it,
taking only a small share of the profits.

With respect to charity,
let not any in trade nicely glean their vine of the fruit with
which the Lord has so abundantly blessed them;
but let them gather sufficient, and the rest let them leave for the portion of the poor.
For my own part, if way open for my going into business,
I believe it will be safest for me to engage in such a one as is moderately profitable,
yielding regular returns, and tending to the general and substantial welfare of mankind,
to the injury of none, and which will not take up much attention or anxiety.
But especially I desire,
that I may never sell to others any article which has an evil tendency,
or which evidently and often is misapplied.

With respect to this particular, I have lamented to see that Friends,
who are fearful lest they should give way to the spirit of vanity, pride,
and extravagance, and who on that account decorate neither their persons nor houses,
nor even allow their servants to dress gaily,--that
these should yet feel easy to deal to others,
things which they disapprove of for themselves;--that
they should not hesitate to buy and sell such articles,
as they well know are inconsistent and incompatible
with the pure teachings of that principle,
by which they profess to be led.
This matter has impressed me much.
I know that by adopting this sentiment,
I show my disapprobation of the conduct of many sincere-hearted friends,
and I am also aware how few descriptions of occupation
in life are entirely free from this objection.

Nevertheless,
I do believe that the sincere-hearted amongst us will
not hesitate to give up that in their outward concerns,
which they see and know to be an encouragement to evil in any shape.
That these may come to see this matter, as clearly as I do at this present time,
is the warm desire of my soul.

But the ground upon which I think it best for me to be
not much engrossed in the things of this life,
is this: having experienced no small share of the forbearance and mercy of the Lord,
having been rescued and delivered from the pit of destruction,
having sincere and fervent desires for my own preservation and salvation,
as well as for that of my poor fellow-creatures
every where,--I have inclined towards the belief,
that the Lord will make use of me, if I am faithful to his requirings,
in the way and time, and for the purposes, which He sees best.
Under this impression it is,
that I believe it right for me to sit loose to this world and its anxieties,
and not to be too much entangled in them;
lest I should be incapacitated for performing
that service which may be shown to be my duty,
or unable from my situation in business to undertake it.

Though I scarcely think it my place to be out of business;
yet I believe that it is good for some to be entirely released from it; and also,
that well disposed persons should devote a considerable portion of their talents, time,
and money, to visiting and relieving the poor,
and advancing and promoting the good of mankind in various other ways,
according to their several gifts.

Fourth month 4th.--Last third-day week, the 25th of third month,
was our quarterly meeting;
at which precious opportunity I was much favored to feel refreshment and instruction:
the business of the meeting was conducted pretty much to satisfaction,
and the conclusion of the last sitting, I have reason to remember.
During the interval of ten days which has since elapsed,
I have frequently had on my mind an inclination to record the awful and weighty posture,
into which my soul was brought on that occasion,
by the merciful visitation of a tender Father.
Towards the latter part of the concluding sitting,
after the business of the meeting was transacted, and a suitable pause had ensued,
a minister got up with this most impressive language of
the apostle,--"`Other foundation can no man lay,
than that is laid, which is Jesus Christ.
Now if any man build upon this foundation, gold, silver, precious stones, wood, hay,
stubble; every man`'s work shall be made manifest; for the day shall declare it,
because it shall be revealed by fire; and the fire shall try every man`'s work,
of what sort it is.
If any man`'s work abide which he has built thereupon, he shall receive a reward.`"
I believe nothing was added to this by the Friend himself,
though R. Phillips carried forward the subject a little with much force and vigor.

After this another minister rose,
and in a solemn and earnest manner applied the foregoing to the youth then present:
he urged them in a powerful manner to look to their foundation,
and to examine what hope they were laying up against the time to come:
he reminded them how soon and how suddenly, even the young, the healthy, and the strong,
were cut off; and desired them to recollect, that the Lord loved an early sacrifice,
a sacrifice of time, and talents, and treasure,--a sacrifice of every thing:
and he recommended to those who were ready to
give up all and follow their crucified Savior,
fully to ascertain, that what they were about to offer,
was required and called for at their hands; and in all their undertakings and designs,
thoroughly to try "`the fleece.`"
I cannot repeat what I felt upon this awful occasion,
especially as the remarks came from one to whom I am not known,
nor do I even know him by sight.
I could scarcely speak to any one, after the meeting broke up;
but walked home in fear and trembling, under a renewed impression and belief,
that the Lord is yet as mindful of his poor frail creature as ever he has been.
As t was returning to Clapham in deep retirement of spirit,
and in silent waiting before Him,
"`who gives us all things richly to enjoy,`" these
texts of Scripture were revived in my recollection,
and sealed very firmly the instructive communications which I had heard:
"`Let every man prove his own work,
and then shall he have rejoicing in himself and not in another;`"--"`Be not deceived,
God is not mocked: for whatsoever a man sows, that shall he also reap.
For he that sows to his flesh,
shall of the flesh reap corruption but he that sows to the spirit,
shall of the spirit reap life everlasting.`"
I had also occasion to remember, that he it was, who came to Christ, heard his sayings,
and did them, that was likened to a man, who built upon a rock.

[.offset]
+++[+++It appears, that about this period,
the author felt it to be his duty to address his late schoolmaster;
having when under his charge been guilty of much irregular and disreputable conduct;
the reader may judge of his feelings on this occasion,
by the following extracts from his letter to this person,
after having left the school about four years.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
10th of Fourth month, 1817.

[.salutation]
Esteemed friend, B. H. M.

While taking up my pen to address you,
my mind is deeply affected by the vivid occurrence of past events,
with all the crowd of feelings which spring up on this occasion.

The mass of sin and folly through which I walked
when under your notice,--the exhortations,
the reproofs, the forbearance, and the warnings,
which I received and despised,--together with all the flood of
remorse and repentance which has since intervened;
and above all, the clear conviction, with which I am to this day favored,
that it was nothing short of "`the mighty hand and the outstretched arm,`"
which brought about my deliverance;--these are a few,
and but a few of the emotions that throng me,
while attempting to relieve myself of a burden of duty which has long been due.
The principal object in my view by this humiliating task, seems to be,
to procure from you,
for all these numerous injuries which in time past have been offered you,
such a free and full forgiveness, as I am encouraged to believe,
has been long since received from a still more injured Master, who is in heaven.

Whatever opinion or disposition you may entertain towards me,
even if likely to be at all different from that which I have every reason to expect;
yet such is the feeling of gratitude and respect,
with which I remember your wholesome discipline and
indulgent attention to me when under your protection,
that it seems as though I could receive with equal regard the
severest or the mildest reply which you may see best to make.
Amidst all the discouragements,
which in many ways attend the honorable and truly important post in which you are placed,
from the ingratitude, the perverseness,
the corrupt and hardened insensibility to what is good,
so often prevalent in early youth; still is there much cause to believe,
that many more of this class are arrested in their perilous career,
than return to acknowledge it, to such as have had the charge of them:
and it is probable, that even some, of whom,
after much solicitude and unwearied endeavors on your part,
you have given up almost every hope,
shall yet live to fill up their various stations
in society with satisfaction and with credit.
When I look back upon my own past conduct,
and take in all the various aggravating circumstances attending or connected with it,
many of which you are not acquainted with,
I find myself able to express very little of what I feel, not only towards yourself,
but towards all whom I have in any manner injured, whether more or less remotely.

With feelings of esteem for yourself and family, believe me to be your friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Clapham, 22nd of Fourth month, 1817.

[.salutation]
My dear +++_________+++

In the season of sore affliction, which has at this time overtaken me,
next to that consolation which springs from Him who is the source of all good,
I know of nothing that affords such refreshment
as the sympathy of dear and valued friends.
And that I have your tender sympathy and solicitude at this time of trial and of tears,
I feel too well assured to doubt.
How insignificant,
how comparatively light did the adoption of any
alteration in appearance and behavior seem to my view,
while they were looked upon at a distance: how little did I suppose,
that such trembling and distress would have been occasioned,
by so trifling a circumstance as the discontinuance of some paltry practices and habits,
which were clearly seen to have had their origin in evil, or tended to it:
how far was I from believing, that when the time should come for my standing forth,
and showing under whose banner I had enlisted, in whose chosen regiment I served,
there could be any other feeling in my heart but joy,
that I was counted worthy to suffer whatever might be the consequence.

Well, dear +++________+++, we have that which is better than words,
by and through which we can communicate; why then need I add more.
It may, however, relieve you a little of what I know you feels for me, to be assured,
that in every respect as to this important matter, whether I look at the time, the mode,
or extent of this act of dedication,
I have nothing for which to reprove myself as yet,--nothing
that I could really and truly wish to be otherwise than it is;
and that I have abundant cause for thankfulness and encouragement.

[.signed-section-closing]
Believe me, your affectionate friend,

[.signed-section-signature]
John Barclay

--

[.offset]
+++[+++In a letter to a Friend, dated about this time, he writes:]

[.embedded-content-document.letter]
--

We have truly witnessed the "`mighty hand,`" and the "`outstretched arm:`"
then let neither of us be using in effect any other language,
than, "`the will of the Lord be done.`"

Let us beware, lest we be in any wise counteracting the intention of Him,
who intends better for us, far better, than we can possibly provide for ourselves.
I believe there is a work assigned to each of us;
that while to one is given a talent of one kind wherewith to occupy,
to another may be handed one of a very different description;
and as long as we are in our allotted stations, a blessing attaches to us.
That you and I may both be found not blindly choosing our own path,
or laying down our own self-willed plans and projects;
for that which we may call our welfare in life, is my earnest desire.
For assuredly it is not the estimated usefulness or service
which we may be rendering to ourselves and to society,
by taking up this or the other course of life; but it is the being in our right places,
which is acceptable.
Or, as R. Barclay said, '`If Paul,
when his face was turned by the Lord towards Jerusalem,
had gone back to Achaia or Macedonia,
he might have supposed he would have done God more acceptable service,
in preaching and confirming the churches, than in being shut up in prison in Judea;
but would God have been pleased herewith?
No, certainly.
Obedience is better than sacrifice; and it is not our doing that which is good simply,
which pleases God, but that good which he wills us to do.`'

[.signed-section-signature]
John Barclay

[.signed-section-context-close]
Clapham, Fifth month, 1817

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. F. Marsh

I could say much to you at this time,
and could tell you what a precious interval the present is more and more felt by me;
how clearly matters seem daily to open before me, as a calm, willing,
watchful state is abode under; how hard things are made easy, bitter things sweet,
and how things that were expected to have brought suffering,
have yielded little else but joy and rejoicing as "`a song in the night.`"
It must be an encouragement to you,
and a cause of joy to see how very graciously and tenderly I am dealt
with day by day,--how the task is proportioned to the measure of
ability afforded,--and when the spark is cherished by obedience,
and every thing that tends to damp or check is removed,
how an increase in strength is experienced,
and especially what sweet peace is at intervals the result.
"`What shall we render to Him,`" for all our blessings and benefits;
is there any thing too great to sacrifice, or that any of us shall withhold?
May we become more and more learned, more and more deeply taught in that best of lessons,
humility; for without this seasoning virtue,
the highest attainments in religious knowledge,
are likely to produce nothing short of additional condemnation.
It is the humbled and contrited spirit that is an acceptable sacrifice,
and said to be "`precious in the sight of Him with whom we have to do.`"
Farewell.

[.signed-section-signature]
John Barclay

--

Fifth month.--I think I have heard a remark, made by some amongst us,
tending rather to the injury and prejudice of
them that give place to the sentiment,--namely,
that persons should not let their outward profession and appearance
outstep their inward and real condition and character.
This sentiment sounds very well, and perhaps is sound with some qualifications.
It is however in the neighborhood of error;
and therefore should be cautiously received and acted upon.
For, verily, the reason why I or any others have adopted a strict appearance in dress,
address, or other particulars,
is not that we thought ourselves better than those who
have not found this strictness expedient for them;
nor is this strictness of profession among men,
any certain or safe mark of taking up the cross of Christ.
The cross that we have daily to take up, as followers of a crucified Savior,
is a spiritual cross, a cross to our appetites, passions, affections, and wills.
The crucifying power will, no doubt, after cleansing us from all manifest wickedness,
cleanse also and purify our very thoughts and imaginations,
our very secret desires and latent motives; and amongst these,
will it also destroy "`the lust of the eye and the pride of life,`"
with all the fruits and effects thereof,
which have crept into, and are so apparent, in the daily conduct of men of the world.
Thus, no doubt remains with me, but that if we, as a society,
were more universally subject to the operative and
purifying power which we profess to believe in,
there would be found more strictness even in minor matters than is now seen,
and greater circumspection, seriousness, and a continual standing in awe.

13th.--I have been reading and have just finished the journal
of the life and religious labors of Mary Alexander:
I have not read very many of the journals of deceased Friends,
but from those which I have read,
there has been impressed upon me many an instructive lesson.
It is in such accounts that we gain that treasure of experience, which,
without books or writings, would be only attainable by the aged.
We see from these narratives, at one comprehensive view, the importance, the value,
the object, and the end of human life.
The travelers whose pilgrimages are described,
seem to traverse their course again under our inspection:
we follow them through their turnings and windings,--through their difficulties,
discouragements, and dangers; through the heights of rejoicing, and depths of desolation,
to which in youth, in age, in poverty, in riches, under all conditions and circumstances,
they have been subject.
From these accounts, we learn the many liabilities which surround us, and we may,
(unless through willful blindness,) unequivocally,
discover where the true rest and peace is to be found;
and in what consists the only security, strength, and sure standing.
How loudly do the lives and deaths of these worthies preach to us;
they being dead do indeed yet speak, exhorting and entreating, that we who still survive,
may lay hold and keep hold of those things,
in which alone they could derive any comfort in the end.
I have accompanied this dear friend, as it were, from place to place,
and from time to time;
I have seen her as she passed through the changing
circumstances and events of each revolving year;
and cannot but observe, that while she followed the gentle leadings of Israel`'s Shepherd,
giving up her own to His will, she found such peace,
as encouraged and strengthened her under every distress, perplexity and darkness.

It was an unwearied,
unshaken belief in the being of an infinitely great and gracious Master,
that enabled her, as it ever has, and as it does even now,
enable all who rightly embrace it, to encounter the buffetings of the enemy,
the perils and pains of the body, the exercises and conflicts of the soul,
the uncertainties and exigencies of time, with the same calm confidence, and at seasons,
even with triumphant joy.
You, dear fellow traveler,
dear to me in proportion as you are near to Him who is very tender to us all,
I do affectionately salute you, whoever you are that read what is here written,
whether a relation or a stranger, young or old,
born in a higher or more humble station,--I affectionately entreat you,
that you would weightily lay these things to heart,
while it is day unto you,--while the light,
which makes manifest what things are reprovable and what commendable,
shines in your heart,--while the Lord is in
exceeding mercy condescending to care for you,
and to plead with you.
O lay these things to heart.
I testify as in the sight of Him who sees in secret,
who knows your and my inmost thoughts,
that there is no other way to real rest amidst the contingencies of time,
nor to an unfading reward, when this earthly tabernacle is dissolved, but in obeying Him,
who said "`I am the way, the truth, and the life:`"--be warned--be prevailed upon,
dear reader, by one,
who acknowledges to you that he himself has been in great depths of wickedness,
through disobedience to the faithful unflattering monitor, and has found no peace,
no deliverance, but through the low portal of obedience to the same.
By this he has been from day to day encouraged and strengthened to
leave off one evil practice and disposition after another,
and has been helped in some very small degree to
put on a better righteousness than his own:
and he assures you,
that your repentance and your faith are to be measured
by your obedience to the appearance of Christ within,
"`the hope of glory,`" as he is received in his secret visitations,
and obeyed in his manifested requirings.

16th.--In what words shall I express your tender dealings, your loving kindness,
O Lord! to my poor soul?
How shall I approach you, how shall I speak of you, or speak to you, you,
the Giver of every good gift?
You are far more gracious than any language can commemorate,
or than any tongue can convey an adequate notion of.
You have wrapt me in a garment of praise;
you have covered me with a sense of your compassion.
I am swallowed up with love of you, with your love towards me.
Take pity upon the poor dust,
which you have been pleased to animate with the breath of your pure Spirit,
and to make a living soul;--still condescend to continue your
fatherly protection--your very tender mercies and forbearance,
hitherto vouchsafed; and enable me and all your poor creatures,
to answer yet more and more your end and purpose in
creating us,--still more and more to love and adore you,
who are our all in all.
May your kingdom, your power, and your glory,
yet more widely and triumphantly extend over every thing within us
and without us;--may your blessed will so come over all,
that the period may again be known, when
"`the morning stars sing together, and all your sons, O God, shout for joy!`"
