== Chapter V.

Fifth month 20th, 1817.--O! How fervently,
how earnestly have my cries and breathings ascended to Him,
who is the fountain and source of all good,
that all the true well-wishers to Zion`'s welfare, all the hearty, zealous,
living laborers may be preserved at this season,^
footnote:[The Yearly Meeting]
on the right hand and on the left; that they may be kept in their proper places,
and in subjection to the great Master of our assemblies;
that their spiritual eye and ear may be opened and enlivened by his healing hand
that their speech may be directed and their mouths filled in his own time and way,
to his glory!
May each one of these be kept low under his almighty hand;
may that which is of the creature within them be abased,
while that which comes from the source of life and glory,
is exalted above every obstacle or opposition.

O! you, who are pleased at times to favor your poor dependent little ones,
those who have no hope, or help, or happiness,
but in the smile of your benignant countenance;
be pleased at this time so to refresh their hearts with
the influence of your paternal presence,
so to overshadow them with a sense of your continued protection and care,
that they may be severally encouraged and confirmed to serve you with greater diligence,
to devote themselves afresh to your service and disposal,
and more sincerely and unreservedly to say and to feel,
that your will is best in all things!
Sixth month 1st.--I have attended the sittings of this yearly meeting,
as well as those of its large committee on Epistles, of which I was nominated a member;
and am inclined in this manner to notice it.
I think I never saw the importance of our assemblies,
or indeed of any system of church government, in so strong a light,
as previously to this yearly meeting.
For many days before it commenced,
my mind seemed engrossed with a sense of the weighty act of duty,
which we were going to take in hand.
I was encompassed with earnest desires and great exercise of soul,
that every individual attendant there, might be availingly instructed and benefited,
whether it should fall to his lot to be more or less prominently engaged;
and that thus whatever we might do in word or deed,
we might do all to the glory of the Lord, and for the promotion of his great cause.
I was favored to continue in the same tender feeling frame of mind,
with but little diminution, to the conclusion of our solemn engagement: at times,
the Lord did extend his precious gathering wing over his poor dependent little ones,
and enabled some to sing in their hearts to his praise;--blessed be his holy name.
O! what a privilege it is, to experience preservation on every hand,
to be each of us kept in our proper places, and under our own fig tree,
where none can make us afraid,--each of us abiding under our particular exercises,
and upon the watch-tower.

A few lines affectionately offered and addressed
to every young person whom they may concern.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Sixth month 10th, 1817.

[.salutation]
Dear fellow traveler,

In a little of that love which has been extended to me by Him,
who "`shows mercy unto thousands,`" I send you these few lines,
sincerely desiring that the eye of your soul may be so effectually
opened and enlightened by the healing hand of the great physician,
Christ Jesus, as to enable you clearly to see the things which belong unto your peace,
before they are hidden from you.

Dear fellow traveler, do you not at times,
when your mind is in some degree disengaged from the round of sin and folly,
or when your natural flow of health and spirits is somewhat broken,
do you not feel within you convictions of your wickedness, and condemnation for the same?
Have you not intelligibly heard at such intervals a language which whispers,
'`all is not right?`' Have you not felt that the end of these things,
in which your gratification is placed,
can never be peace,--can never be anything short of death,
eternal death to the soul that persists in them?
Be assured then, that although these are your secret feelings,
you are still the object of infinite condescension and loving kindness.
He who desires not the death of the evil-doer, but the death of the evil,
is still near you, notwithstanding all your rebellion;
following you in your ways which are those of sin, and running after you as a shepherd,
in search of his strayed sheep.
These pleadings of divine grace, these convictions of the Spirit of Christ,
which in spite of your concealment of them are pursuing you,
and in spite of your endeavors to appease them by partial reformations are galling
your soul,--even these are the evidences of His gracious hand upon you,
who wounds only to heal, and whose very judgments are in mercy.
Oh that you may come to see with undoubted clearness the truth of this;
that you may be encouraged and emboldened unreservedly to follow that, which is,
as I fully believe,
shown you to be right and acceptable in the sight of the great Judge of all the earth.
Assuredly, He has shown you, what He is requiring at your hands,
and what his righteous controversy is with:
He requires of you nothing but that which has separated you from Him,
the only source and center of true joy,--nothing but that which, if not forsaken,
will embitter your present life, and plunge you into utter darkness after it.

Dear fellow traveler, it may be that you have been, within these few years,
my companion in the walk of wickedness; that I have taken you by the arm,
have helped you forward in the broad and beaten track which leads downwards;
that we have taken delight to set at defiance the commandments of a great Creator,
and have yielded ourselves, and all that we possess,
the ready instruments of Satan:--bur time, our talents, our means, our youth, our health,
our peace, have been freely sacrificed at the altar of our soul`'s enemy.
Be then entreated by one who has himself trod in this path;
who has hurried forward with impetuosity down this fatal current, who,
borne by the rushing waters to the very brink of a tremendous precipice,
has been there snatched from the very mouth of destruction.

There is indeed, dear young person, neither help, nor hope, nor happiness,
even in this state of existence, but in the favor of Him, in whose favor is life;
in implicit obedience to the divine will as far as it is made known to us.
It is to no purpose that we reckon ourselves,
or are reckoned by others as belonging to this sect or the other church,
to this class or the other division of professing Christians--if we fall
short of those unalterable marks and evidences of true Christianity,
by which we shall be known and distinguished in that great day,
when every gloss will be removed,
and every ceremony and shadow shall fade before the eternal sun of truth.
We read that at that awful crisis, there shall be but two names or classes,
by which the inhabitants of the whole world shall be known;
the sheep and the goats,--the good and the bad.

Well, dear fellow traveler, it remains for each of us,
if we have any desire that this transient state of
being may terminate in an unfading inheritance,
to lay aside all the false and foolish reasonings, all the vain suggestions,
the cheating insinuations of an unwearied adversary;
and with sincerity and simplicity of soul,
to take up the holy resolution to seek and to serve the Lord our God,
during the few remaining days that may be allotted us; and to this end,
that we be found daily inquiring in his temple, the temple of our own hearts,
and waiting upon him there,
where his kingdom must come and his will be done
that so we may feel his presence and power,
to direct and to guide us into the saving knowledge of himself.
That you and I, as well as all our poor brethren upon the face of the earth,
may be of that gloriously happy number,
who shall inherit an eternity of joy unspeakable in the kingdom of heaven,
is the earnest desire of one who feels himself your soul`'s true friend.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Clapham, 18th of Sixth month, 1817.

While thinking of writing to you, a part of a beautiful meditation of the Psalmist,
on the works and wonders of Providence, occurs to me.
After dwelling much on the variety and immensity, the order, the harmony,
the excellent provision and appointment of all things both in heaven and upon the earth,
the poor servant cries out, as if unequal to the task;
"`O Lord! how manifold are your works! in wisdom have you made them all;
the earth is full of your riches.`"
I remember it is somewhere said,
"`all your works shall praise you, and your saints shall bless you;`"
and while we thus see that the heavens declare his glory,
and the firmament his handy work,--while we see that all his works praise him,
are we not convinced that his saints should likewise bless him?
Are we not abundantly persuaded, that man also,--whom we now see the only flaw,
the only speck in this vast production, perverted in himself,
and perverting the rest of the creation,--was
originally made pure and perfect in his kind,
and did then glorify his Maker.

Oh! how fully do I believe, how clearly do I see,
that it is only as we poor creatures come to be renewed in the spirit of our minds,
and to experience the putting on of the new man,
which after the image of Him that made us, is created in righteousness and true holiness;
that we can rightly worship, acceptably praise,
and truly give glory to so infinitely righteous and holy a Being with whom we have to do.
Thus alone are we brought inexpressibly to feel
the beauty of those scriptural or other writings,
which dwell on the works of the creation: thus also are the faculties of our mind opened,
enlarged, and quickened to examine, to perceive, and to adore,
the great first cause of all.
What a blessed experience, when everything within us and without us, the stars above us,
the dust under our feet, seem all to join with us,
and to show forth that Power which has made them,
and which supports and sustains this system, this machinery of the universe.
Surely the revolutions and vicissitudes to which the
spiritual as well as the natural kingdom seems subject,
the turnings and over-turnings, the storms and the calms,
the darkness and the brightness, the dreary and the cheering prospects,
the drooping and the delightful seasons, are equally in the hollow of his hand,
who is said to be "`all in all.`"
He says to the raging winds, "`peace be still,`" and to the foaming billow,
"`thus far shall you come, but no further.`"
What then should be the invariable language of our hearts;
what should be the clothing of our spirits day and night, in all extremities,
and under all the circumstances to which we are constantly liable,
but "`the will of the Lord be done.`"
O! that we might be privileged to continue from day to day, and all day long,
in such a prostrated, humbled, reverential frame of spirit,
as would indubitably evince our belief in the presence, protection, providence,
and power of Him, whom we profess to serve.
Your affectionate friend,

[.signed-section-signature]
John Barclay

--

24th.--I think I have never felt in so reduced a condition,
in so pitiable a state of mind, as during some intervals of late;
at this time especially,
it seems as though I were at the very boundary where distress of soul ends,
and where utter darkness and desolation begin.

Still is there something like hope;--still is there, through the infinite mercy of Him,
whose kingdom and whose power are far above the dominion of the wicked one,
something resembling the faintest glimmer of a spark of light,
through all the horror and gloom which reigns.
O Lord! this once help me; condescend to bless me, and be with me,
and I will follow you whithersoever you lead.
O! Lord God of my fathers, I have read of your goodness towards those who sought you,
towards those who trusted in you, in times that are past; I have seen, and I have known,
and am sure, that it shall ever be well with those who have no help, or hope,
or happiness, but in and by and through you, the source and center,
the spring and the river of all consolation and refreshment.

25th.--I attended our quarterly meeting held this day, under a weight of discouragement,
without being able to feel anything alive within me.
It seemed to some, however, to be an open time, a time of refreshment;
the truly hungry and thirsty were shown what a blessed condition they were in;
and they were directed to the fountain of living waters, the living bread from heaven,
whereby they might be nourished up into eternal life.
There was also a supplication put forth on behalf of some,
who were under discouragement and doubting whether they
ought not to enter upon some important duty;
and a desire for such,
that they might "`go forth in this their strength,`" in the
deep sense of their own weakness;--which much reached me.
The sittings for business were no less trying to me, and I believe to some others,
who mourn at the untempered,
(if I may use that expression,) or rather perhaps unleavened manner,
in which these our meetings for the promotion of good order,
Christian conduct and conversation, are sometimes held.
Oh! how little of an inwardly gathered and retired disposition do we see;
how little of that weighty concern and exercise of soul--that
abiding under the overshadowing canopy of pure fear,
which were witnessed by those amongst us in former times,
and spoken of in these words of William Penn: '`Care for others was then much upon us,
as well as for ourselves, especially the young convinced.`'

Often had we the burden of the word of the Lord to our neighbors, relations,
and acquaintances, and sometimes to strangers also:
we were in travail for one another`'s preservation,
treating one another as those that believed and felt God present;
which kept our conversation innocent, serious, and weighty.
We held the Truth in the spirit of it, and not in our own spirits,
or after our own will and affection.
These were bowed and brought into subjection,
insomuch that it was visible to them that knew us;
we did not think ourselves at our own disposal, to go where we list,
or say or do what we list or when we list:
our liberty stood in the liberty of the Spirit of Truth; and no pleasure, no profit,
no fear, no favor, could draw us from this retired, strict, and watchful frame.
Our words were few and savory, our looks composed and weighty,
and our whole deportment very observable.
I cannot forget the chaste zeal and humility of that day;--oh!
how constant at meetings,--how retired in them,--how firm to
Truth`'s life as well as to Truth`'s principles!`'^
footnote:[William Penn`'s _Rise and Progress of the People Called Quakers_]
Thus far William Penn; and oh! that we could say, that anything like all this,
did really and truly pervade our conduct now, as a religious body.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Clapham, 30th of Sixth month, 1817.

[.salutation]
Respected friend, Thomas Shillitoe,

Having fulfilled the object which induced me to send the preceding lines,
I am inclined to add a few more;
which I am ready to believe I should have done well to communicate to you,
when last in your company.
I faintly recollect, many years past, when but very young and at school,
hearing you (I think I cannot be mistaken as to its
being yourself,) in a meeting for worship at Wandsworth,
largely and powerfully engaged in testimony.

I also remember my own feelings at that season, how ready I was to laugh you to scorn,
and to despise you.
But I have been met with, like poor Saul; and am now brought to such a pass,
that I cannot find satisfaction or even safety,
in any thing short of a warm and unreserved espousal of that cause,
which I but lately made light of.
The subjects to which you were concerned to call the
serious attention of Friends at the last yearly meeting,
have been deeply felt by me; and I may truly say,
that nearly as long as I have been privileged by an
acquaintance with the houses and families of Friends,
which, though I was born a member, is not long,
I have at times almost mourned at the great relaxation from Gospel strictness,
and simplicity of living, so evident amongst us.
Surely I have thought if we were to cast out the crowd of opinions,
which have got the first place in our minds,--opinions founded or cherished by custom,
example, and education in the good, and by vanity, or something worse, in the bad;
and if we were coolly and calmly to listen to the silent dictates of best wisdom,
we should clearly see,
that the holy principle which we profess (to use the
words of John Woolman,) inevitably '`leads those,
who faithfully follow it,
to apply all the gifts of Divine Providence to the purposes
for which they were intended.`' I venture to say,
we should then find a greater necessity laid upon us,
to exercise self-denial in what we are apt to think little matters,
than is now often thought of;
we should have such a testimony to bear against superfluity, extravagance, ostentation,
inconsistency, and the unreasonable use of those things which perish with the using,
as we now profess to have,
against the more flagrantly foolish customs and fashions of the world.
Whatever some may think in regard to these things, I feel assured, that he,
who in his outward appearance or behavior,
bears any remnant of a testimony against the customs and fashions of the world,
ought to be ashamed of himself, if he belies his avowed sentiments,
by a departure from simplicity in the furniture of his house and way of living.

Will you excuse my saying a little more, dear friend,
on so important a subject as this has long felt to me?
I have been almost ready to blush for some, at whose houses I have been,
where pier-glasses with a profusion of gilt carving and ornament about them,
delicately papered rooms with rich borders,
damask table-cloths curiously worked and figured extremely fine, expensive cut glass,
and gay carpets of many colors, are neither spared nor scrupled at.
Some indeed seem to be desirous of disguising
and excusing their violation of the simplicity,
which their better feelings convince them they should practice, by saying,
that this or the other new or fashionable vanity is an improvement on
the old article,--that this gay and gaudy trumpery will wear and keep
its color better than a plainer one,
or that this precious bauble was given them by their relations.
Thus are they endeavoring to satisfy the
inquiries of those who love consistent plainness,
and to silence that uneasy inmate, the unflattering witness which is following them.
I have been much exercised and troubled on my own account, and on that of others,
as to these matters;
and have been very desirous that we may all keep clear of these departures.

Thus you see I have felt much freedom in addressing you,
even like that of an old acquaintance;
and hope I shall never lack this honest openness towards such
as are examples in conduct and conversation;
for when there is a lack in this respect, it seems with me to indicate a lack of that,
which brings with it boldness and confidence towards all men,
even a fear of One who is greater than man.
With desires that,
in receiving and reading this communication from
one who is so young in years and experience,
you may be encouraged in your arduous labor, in which I have felt much sympathy with you;
and trusting it may be blessed by the reward of peace to yourself,
and by the return of many a backslider to the living fountain;
I remain your sincere friend,

[.signed-section-signature]
John Barclay

--

Seventh month 4th.--In reading the 13th chapter of the first book of Kings,
I have at this time been much instructed,
and am ready to take the lesson to myself as a warning or special admonition.
Herein we see, that it availed nothing in respect to the future, that the prophet had,
though so lately, been favored with a divine commission,
and was hitherto upright in the faithful discharge of that arduous duty
which devolved upon him from his Lord,--even that of openly proclaiming the
vengeance of the Almighty against the idolatry that had overtaken the people,
--and boldly asserting the destruction of the priests even to their faces,
and in the presence of their king;
saying to him in reply to his invitation,--"`If you will give me half your house,
I will not go in with you;
neither will I eat bread or drink water in this place:`"--yet after all,
he was weak enough to give up his own clear convictions of duty,
as revealed in and to himself,
the truth of which was indubitably evinced and sealed by the
miracle which attended the partial performance of them,
and to prefer obeying the old prophet, before compliance with "`the word of the Lord.`"
Oh! how greatly have I longed in a peculiar and especial manner for myself,
as I am now situated and circumstanced,
that I may steadfastly adhere to no other law but the law written on the heart;
and closely attend to the secret dictates of best wisdom alone.
For assuredly there is no safety,
but in implicitly giving up to the reproofs of instruction,
which are and ever will be the way to life.

"`Be followers of me,`" says the apostle Paul;
but he adds,--"`even as I also am of Christ;`" intimating surely that
the examples of others in life and conversation are to be followed,
only so far as they accord with the example and precepts of Him, who said,
"`I am the light of the world,`"--
"`while you have the light believe in the light,`"--
"`walk while you have the light.`"
So that in looking back at such acts of dedication, as have been, according to my belief,
required at my hands,
and in contemplating the peace which has ensued after even the smallest surrender,
when the sacrifice has been offered out of a sincere and upright heart; I have earnestly,
and I may truly say above every other earthly consideration,
desired that nothing may be allowed to hinder me--to turn me aside,
even in trifling as well as in great matters and concerns, from carefully, closely,
unremittingly attending to, and abiding by,
the counsels and teachings of that divine principle, even the Spirit of Christ,
which is given to every one for his guide in the way of salvation.

I have found amongst many other acts and false suggestions and temptations,
which the enemy makes use of to deter us from giving up
ourselves to the guidance of the Holy Spirit,
one which is much talked of and acted upon by many, through their own inexperience,
and the deceit of the prince of darkness; namely,
that these leadings and secret influences and inspirations,
are not distinguishable from the workings of our own mental or rational powers;
and if they are distinguishable, that these persons have not felt them or known them.
Now in answer to this, which has been my own delusion, I may say,
that any one who has for a long season habitually
stifled by disobedience this divine monitor,
cannot expect to hear or to understand so plainly its voice,
as those do who have for a long period listened to its secret whispers,
and surrender themselves unreservedly to its injunctions: these can testify,
that they follow no uncertain vapor or idle tale;
but that its reproofs are to be plainly perceived,
and its incitements clearly to be felt;
and that the peace they witness cannot be imitated,
neither can it be expressed to the understandings, or conceived by the imaginations,
of such as have none of this blessed experience.
Nor let any poor, seeking, sincere, or serious minds be discouraged,
that they do not upon submission immediately or very quickly feel what they wait to feel,
even the arising of that secret influencing, actuating,
constraining and restraining power or spirit of the Lord.
Let them not be discouraged if this be their case,
nor be dismayed if even after some considerable
sacrifices and trying testimonies of sincerity,
they find not that rich reward of peace which they had expected.
Let such remember, it is written,--
"`he that endures to the end, the same shall be saved;`"
now where there is a moment`'s enduring only,
and that previous to or while in the performance of what is required,
this cannot be called "`enduring to the end;`" but it
is that "`resistance unto blood,`" as it were,
in faith and faithfulness,
that "`patient continuance in well doing,`" in defiance of difficulties, discouragement,
darkness, doubt, and distress, which will give us the victory,
and will make us through the mercy of God in Christ Jesus,
heirs of that eternity of peace, and rest, and joy,
which we know is prepared for such as overcome.

Ninth month 6th.--For more than a week past,
I have been plunged by the permission of best wisdom,
into such a depth of darkness and discouragement,
without any perceptible glimmer of alleviation or ray of comfort, that my poor, tossed,
troubled soul seems on the very point of giving up the contest,
and losing hold of its only support and security.
While the heavens are as brass, and the earth as it were iron, what is frail,
helpless man to do for himself?
It seems to my view, that there is nothing left for him to do to aid himself,
or to deliver himself out of his forlorn situation,
but to sink down into his own nothingness; and there, as in the dust,
to remain all the Lord`'s determined time,
until He shall see meet to appoint unto him "`beauty for ashes,
the oil of joy for mourning, the garment of praise for the spirit of heaviness.`"
When I took my pen to write what has thus been written,
I did not expect to come to the preceding conclusion,
or that any such reflection would arise out of the subject.
The Lord grant that what I have written, may be more than mere words;
and that through and over all difficulty and distress,
I may come forth the wiser and the better, and more devoted to his disposal,
and more patient under his dispensations.

17th.--I believe myself called upon to bear an open, unequivocal, unflinching testimony,
not only against all pride, extravagance, ostentation and excess,
but also in a peculiar manner against all the
secret insinuations and covered appearances,
under which they are creeping in, and growing up amongst us as a Society.
I have for years believed,
that the declension amongst Friends from the true standard of simplicity is great;
and I am of the mind, that if they had diligently hearkened unto,
and implicitly obeyed the dictates of best Wisdom they would have been led
to '`apply all the gifts of Divine Providence to the purposes for which they
were intended.`' I believe that it is my duty to live in such a humble,
plain, homely, simple manner, as that neither in the furniture, food, nor clothing used,
any misapplication of the gifts of Divine providence be admitted or encouraged.

Ninth month.--"`Day unto day utters speech, and night unto night shows knowledge;`"
and where is an end to praising the Lord for his mercy,
which "`endures forever,`" and which is abundantly shed abroad,
to the rejoicing of the hearts of those that seek to serve him,
and to the great comfort of their souls in the midst of much tribulation.
O! that there may be more and more reliance, unshaken, immoveable reliance on Him,
who thus daily scatters and profusely deals out tokens of his loving kindness.
That there may be an increase of faith experienced,
an increase of resignation proportioned to the nearer approach
of perplexity and difficulty and embarrassment on every hand.
And now when the waves of affliction run high, and the floods seem irresistible,
may the Lord Almighty,
who "`is mightier than the noise of many waters,`" in
his own time lift up a standard against them,--saying,
"`thus far, but no farther.`"
Surely,
He who remains as ever to be the only sure
"`confidence of all the ends of the earth,`"--
He who can overrule events for the good of those that sincerely seek him,
will not overlook or despise any of those who desire to look unto,
and who lean upon Him alone in all their troubles, "`O! Lord God of my fathers,
are you not God in heaven?
and do you not rule over all the kingdoms of the heathen?
and in your hand is there not power and might, so that none is able to withstand you?`"
Are you not my God, are you not my joy, my delight, my glory, the crown of my rejoicing?
Are you not He, that has hitherto helped me, that has brought me out of much evil,
that has inclined my heart to seek you, and my soul to love and fear you?
Will you not arise for my help in the time of trouble, of temptation, of darkness,
of distress, from whatever cause these may proceed, whether by your permission,
or by your appointment?

Lord, you know perfectly, what are the causes of my present disquietude,
and how to dispose of all things for the best,
both as to the present and as to the future: you know how poor, and weak,
and utterly incapable I am to help myself in any exigency that may arise;
and that without you, nothing but confusion, and sorrow, and desolation,
is likely to be my portion: make me yet more deeply and lastingly sensible of this,
and that "`I have no might against this great company that comes against me,
neither know I rightly what to do.`"
I beseech you, renew daily and hourly my faith and dependence,
and watchfulness unto prayer, and my love and fear of you.
Arm me with your glorious impenetrable armor;
and make me strong in you and in the power of your might;
that through your abundantly sufficient grace and truth,
I may be fit for all occasions and trials, to which you may see meet to call me; that so,
my eye being continually upon you, your precious cause may prosper,
and your name be exalted by me, in me, and through me,
both while my soul is confined in this frail body, and forever and ever.
Amen.
