== Chapter VI.

Ninth month 20th, 1817.--Truly do I rejoice in believing,
that I find myself losing more and more of that authority and
ability to do anything for the service of the blessed cause,
which proceeds from the creature; and in this happy experience,
I see advancement as well as safety.
O! that all shadow and appearance of confidence in the fleshly part,
may be still further removed;
that there may follow a yet more firm establishment on the Rock of sure strength,
the immoveable foundation of all true wisdom.
Man may possibly think in his reasoning that a
smooth path is best for the Christian pilgrim;
little knowing how it is,
that "`we must through much tribulation enter the kingdom,`"--
except perhaps as it respects outward affliction.
Yet we do see, and some of us feelingly know,
that deep plungings with buffetings and toilings and groanings of spirit,
are the "`bonds and afflictions that await us,`" down to the final hour, it may be,
of our departure hence; and we can of a truth declare at times,
that such heavily distressing dispensations are by the
permission of the Author of all good in love to our souls;
and we are sometimes enabled, in the blessed moment,
when we feel ourselves on the banks of deliverance, to extol His holy name;
who has made us a path through the mighty waters, and sustained us in the wilderness.

How shall my soul forbear to sing aloud unto Him,
who has preserved it in its travel through a land of pits and of snares,
through unspeakable darkness, and an almost utterly disconsolate state;
and has given me this hour of rest and of peace,
this little interval of refreshment and joy and great consolation.

O! that this precious season had never been graciously given unto me,
rather than that I should after such tender mercies,
turn away from following the Lord in the "`little moment,`"
when he may again be pleased to "`hide his face.`"

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 23rd of Ninth month, 1817.

[.salutation]
My dear friend, J. F. Marsh,

There are some bright spots in this wilderness journey,
and I think you will recognize them by my faint description;
when as from an eminence we are enabled to see to a
considerable distance both before and behind us;
feeling ourselves as it were removed into a purer atmosphere.
We can even distinguish the little stumbling blocks that have impeded our progress,
the rough and rocky ground that has sorely wounded our feet,
the very brambles and briary thickets that have jaded us,
the narrow passes and threatening precipices through which we have escaped,
and on the edge of which we have been preserved.

Here it is, on this interesting elevation,
while the eye of the mind is rapidly traversing over and
tracing the windings of the road by which we have come,
that we remember where and when "`the troubles of our hearts
were enlarged;`" we call to mind the perplexity that befell us,
the secret conflicts that attended,
and the temptations that waylaid us;--we can precisely point out the spot
where "`we sat down by the rivers of Babylon,`" where
"`we wept when we remembered Zion,`" and
"`hanged our harps upon the willows,`" and refused to
be comforted;--we can tell where it was that we
"`fell among thieves, who stripped and wounded`" us,
and left us, as it were, half dead;
and we shall not easily forget where the good Samaritan found us,
and had compassion on us, and how tenderly he treated us,
how diligently he took care of us, and provided for our needs.
Which of us at such a time can fail to discover,
and to admire the hand that is over us continually for good;
how seasonably it has been stretched out for our deliverance, for our encouragement,
when there seemed no one near to help,
and nothing to do but to give up the tedious travel.
It is in such a season that we are truly enabled to
"`praise Him, who is the help of our countenance and our God;`"
and to repose anew
in Him our confidence and trust for the time to come.
Your very affectionate,

[.signed-section-signature]
John Barclay

--

28th.--During the present and past fight of afflictions,
which the Lord has in wisdom appointed unto me, I have at times,
through the assisting grace of Him, who has been pleased to fight for me,
maintained a fierce and desperate contest;
and in degree have been enabled to stand firm against the fury of the enemy.

Yet at other seasons, after having been a long time under arms,
and very weary with watching and fasting,
there has been a relapse or retreat experienced;
and the ground that had been gained by hard fighting, has been lost or relinquished.
How difficult at such a moment, when harassed and oppressed, faint and ready to drop,
to keep from utterly falling away, and fleeing before the emboldened adversary; who,
exulting in his success, is proudly pushing forward at this critical juncture,
to make the most of his advantages.
But firmly persuaded I am,
that with the Lord there is sufficient strength and
power to enable us to overcome all our enemies;
I do very earnestly desire to trust in Him, and not be afraid,
to repose my reliance upon him afresh day by day, to keep near to Him at all times,
to be very faithful unto, his requirings,
to be very patient in waiting for his aid and counsel,
and increasingly watchful against the snares of the enemy.
And may His blessing come upon me, and prevent my utter destruction,
which at times seems fearfully impending.
Where is there hope, but in the Lord!

29th.--How shall words set forth the dispensation of desolation as to anything like good,
that seems to have come over my soul?
Darker and darker,--deeper and deeper; what will be the termination of this distress?
Yesterday, I attended Westminster meeting; upon sitting down,
my sorrows began to arise like a whirlwind, and I was ready soon to burst into tears,
exclaiming in secret,
"`the Lord has forsaken me, he has utterly forgotten and rejected me.`"
After a time of great trial and tossing, a young Friend got up with these words,
"`Fear not, for I am with you, be not dismayed for I am your God;
I will uphold you by the right hand of my righteousness.`"

Soon after which, F. Smith rose, and in a very tender manner addressed the poor,
afflicted, tossed, tried servants, whose conflict he described as being so heavy,
and their souls almost in despair;
he expatiated on the number of promises contained in Scripture for such as these,
if they still continued faithful and stedfast to the end,
if they still persisted in hoping in, waiting for, and trusting to the Lord alone.
He said he believed there were some present,
whose language was,--"`the Lord has forsaken and forgotten me:`"--with much more
for the encouragement of such to patience and perseverance under suffering.
As for me, I seemed utterly unable to receive any comfort or hope,
as if all hold was gone and out of reach, and like poor Job, who refused to be comforted.
This evening, after a day of heavy exercise and tears,
my brother read a portion of the Psalms.
While he was preparing to read, my heart said,
'`It is all over with me, there is no good at all for me; I am rejected of the Lord,
his presence and blessing are departed:`'--however, when he began to read,
the first words awfully ran through me, "`My God, my God, why have you forsaken me,
why are you so far from helping me, and from the words of my roaring?
O my God!
I cry in the day time, but you hearest not, and in the night season I am not silent.`"
Then I was somewhat comforted in remembering that this
was the language of David in great distress;
yet he was not forsaken,
but was greatly helped every way by the Lord in the appointed time.

Ninth month.--It is good to trust in the name of the Lord,
to repose in his arm of strength, his parental tenderness and compassion.

It is good to have our many strong holds invaded, our misplaced confidence unhinged,
our secret props struck away;
that we may more closely cling unto that which is not of ourselves, nor of our brethren,
but comes only from the source of all might and of all mercy.
Oh! it is good to have all sense of hope and of help withdrawn,--to
be laid low in the dust with all our pride and selfishness;
that we may feel that which is good to flow in upon us
in the Lord's own time as an unmerited gift,
and thus be enabled to give the praise to Him alone, from whom come grace and glory,
and every good thing.
How great is my desire, that the Lord would rather give me darkness and distress;
than that, enjoying his favor and blessing, I should be unmindful of the Giver,
or grieve him by saying or doing anything
inconsistent with his blessed will concerning me.

Date uncertain.--My mind has been much burdened,
and weightily affected with the present aspect of things,
relating to the growth and prosperity of the ever blessed truth;
and not only do I allude to the low state of things within my own bosom,
and in the circle of our privileged Society, but also in the world at large.
Under a very humbling sense of the infinite condescension,
which still spares us from day to day, and from year to year,
and of the unfathomable compassion which still pities, helps, preserves,
and provides for us with paternal tenderness,
I am ready to cry out,--'`Who will not love, and fear, and obey you, O! Lord;
and give themselves up to be moulded into accordance
with your blessed will?`' But Oh the ravages,
the desolations, which the enemy has effected on the face of all the earth;
how has he blighted the blooming bud, and blasted the richest grain,
and parched up the fruitful field;
so that the time of harvest is become the hour of desolation and darkness!
Here and there, through the gloom of this vast howling wilderness,
a patch of green revives the drooping eye, and cheers the desert scene; here and there,
amidst the straw and stubble in this great field, the earth,
a few single ears are to be discovered raising their heads,
and are just sufficient to show what the glory
of the crop and of the harvest would have been,
had it escaped the destroyer's hand, and not been trampled down by the wild beasts.

Tenth month 2nd.--"`When the Lord turned again the captivity of Zion,
we were like them that dream.
Then was our mouth filled with laughter, and our tongue with singing;
then said they among the heathen, the Lord has done great things for them.
The Lord has done great things for us, whereof we are glad.
Turn again our captivity, O Lord! as the streams in the south.
They that sow in tears, shall reap in joy.
He that goes forth and weeps, bearing precious seed,
shall doubtless come again with rejoicing, bringing his sheaves with him.`"

Oh! the precious applicableness to my present condition, which my soul perceives,
and warmly feels in the above written Psalm.
I seem as though I dare not omit testifying of the
abundant riches of his mercies and of his grace,
which the Lord has profusely shed upon me to the joy of my heart,
to the very lighting up of my countenance.
Weeping may endure in the night season, but joy comes in the morning,
when the Sun of righteousness arises with healing in his wings,
and gladdens the face of all things, making the whole heritage of God shout for joy.
My soul did,
during the several opportunities which were permitted us through this quarterly meeting,
earnestly crave and wrestle for a blessing,
even for the slightest token of the Lord's compassionate regard;
and Oh! how sweetly he has condescended to answer my petitions, my cries,
my longings for a little of the living bread,--that precious power and presence,
which is only of and from him, and is in his wisdom allotted or withheld.
Much instruction and comfort were also verbally conveyed at this time;
and I was rejoiced to see some young persons,
who appeared to have the cause of truth and righteousness at heart,
as well as their own individual advancement and preservation in the
strait and narrow way in which they have happily set their feet.
Yet alas! what a number of this class seem to be ready to leave us!
I believe with some confidence, that but few of those who do leave our religious Society,
truly thrive in a spiritual sense:--not that I confine
true religion to our own profession by any means;
but that I believe there is that grace and truth to be met with,
in a diligent and patient waiting for the teachings of the heavenly Guide,
which they who leave us are in great measure unacquainted with,
or do not much regard or value.
This I have found to be the case,
even with some of the few who profess to leave us on conscientious grounds.

But if all left us only for something, which, after solemn inquiry,
they believed to be nearer the truth, how few should we have to lament the loss of.
I was very earnestly desirous for our dear young Friends,
during our sitting together in the youths`' meeting,
appointed at the request of Mary Dudley, as well as during the first sitting for worship;
that they might come up,
in the strength and power of the living principle of grace and truth,
to the help of the great cause;--that they might in some measure make
up for the deficiency of standard bearers apparent among our sex;
even by such a steady, firm,
consistent life and conduct,-- by such an abiding in
the blessed life and power and strength of the gospel,
as is now too rarely to be discovered amongst us.

Same date,--I have been fearful of leaving any thing on record behind me,
but what upon clear conviction has appeared to be right;
and have often seen the necessity of looking as
closely to what is thus committed to paper,
as to anything that may be said or done, it being my earnest desire,
that nothing may even in secret be done or said,
but what will bear the test of being brought to light.

It may seem to many, who have not hitherto been much, if at all,
brought under the reducing and refining power of Truth,
that such heavy exercises as have been permitted to come upon me,
and as have come upon others,
are nothing but the effects of a weak mind and a bewildered imagination;
and such may not enter into any understanding or feeling of these trials,
which are described in such strong terms.
These may be yet more surprised when they read of such sudden changes and revolutions,
as some experience in their religious states.
Yet in the natural world, how often do we see the greatest storm preceded,
and at other times followed, by the smoothest calmest weather.
The analogy is striking, and it may be safely concluded,
that all these reverses are designed to produce a beneficial effect.

17th.--About a month ago I was at a young Friend's house,
concerning whose zeal and sincerity in the blessed cause, I have not a doubt.
He has appeared in the ministry, I believe acceptably to Friends in general,
and is a promising, growing character.
In the course of much intimate conversation, we approached the subject of prayer.
Upon which he asked me, whether I did not think that the end which Friends had in view,
by the practice of private retirement, was vocal prayer, that is,
the outward act and attitude of kneeling down and using words,
I felt very much at this question; and an awfulness came over me, and exercise,
lest either this person or myself should be adventuring,
without taking off our shoes upon holy ground.
In replying to him, I could scarcely refrain from using the language of William Penn,
'`Words are for others, not for ourselves, nor for God, who hears not as bodies do,
but as spirits should.`'
It is the heart or soul that can
alone cry acceptably through the drawings of that spirit,
which inclines to good and to the source of all good;
the mouth may speak out of the very abundance of the
heart:--there is nothing however in words as such,
nor in outward silence as such.
So that our prayers are none the better for being clothed in words,
nor the less likely to be accepted when not clothed in words.
There may be words when none should be used,
and there may be a silence when words are called for;
and herein stands the snare which should be carefully guarded against.

Eleventh month 10th.--I think I have seen the danger of young men or
women dwelling anywhere else than in the valley of humility.
Human learning, human attainments and excellencies,
I mean all those things that are obtained by the memory, judgment, reasoning powers,
and mental abilities,
separate from any immediate influence and assistance derived from the
source of all true wisdom,--these natural acquisitions and talents
are well in their places and are serviceable to us,
when kept in subjection to the pure teachings of Him,
"`who teaches`" by His Spirit "`as never man taught.`"
But when any natural faculty or talent of the mind,
or acquisition by virtue of that talent or faculty,
usurps and domineers over the little seed of the kingdom sown in the heart,
it had been better that such an enemy were cast as it were into the sea,
than that such mischief should be done.
I have been in company with some young persons of our Society,
who have been not a little injured by giving way to pride and foolish talkativeness,
in respect to many matters, in which, though they seem well informed,
yet not keeping in the littleness and lowliness, they have acquitted themselves but ill,
through letting in a forward, prating spirit.
Now, the best light in which we can view true talents and virtues,
and in which they are set off to the best advantage, is the sombre shade of humility.
For the more the frame-work is colored, or gilt, or carved, or ornamented,
the more there is to take off the attention of the eye from the picture itself.
So that it seems to me best for each of us to dwell in the littleness, in the lowliness;
always bearing in mind from what we are, even from the dust,
and where we shall return even to the dust;
and that we should not forget from where all that is good,
either immediately or mediately comes, even from the source of all good.
This would make us backward and timid at giving our judgment;
it would render us ready and willing to esteem others better than ourselves;
quick to hear, slow to speak, slow to wrath; because we should be patient, humble,
forgiving one another, loving one another, pitying one another;
for we should then know how frail man is.

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
London, Tenth month 10th, 1817.

This morning upon calling at J. S's., I found Samuel Alexander within and alone,
and spent about twenty minutes pleasantly with him:
upon inquiring after the American Friends, S. A. said, they were both there,
and that Hannah Field was unwell; but that I should see Elizabeth Barker.
Upon this he left the room, and soon returned, introducing E. B.,
whom I had felt dear to me,
indeed before I saw her:--she took my hand with the affection of a near relative,
and addressed me in as moving and affecting a manner as I remember ever witnessing.
She seemed to be speaking to one, whom she believed to be under the powerful, refining,
and preparing hand of the Lord, and with whom she tenderly entered into sympathy,
under His necessary provings and purgings;
using several times the words '`dear exercised child,`' and speaking especially of
the overruling power that is to be regarded and trusted to in all our affairs,
both temporal and spiritual: and these words,
(as it were,) still ring in my ears,--'` He can bless a little,
and he can blast a great deal.`' Oh! that we may all keep in the littleness,
in the lowliness; remembering what we are in the absence of our Beloved; how poor,
how mean, how unable to preserve ourselves from falling,
or to keep our souls alive to what is good;
that so we may truly know wherein our strength lies, from where our qualifications come,
how we may be, what we ought to be, and how become instrumental to good in any way.

You know that I have wished, in regard to my settlement in the world,
far more earnestly to obtain the blessing which makes truly rich,
than any other acquisition; you are also fully aware, that,
as this blessing is annexed to obedience,
so the nearest way to partake of it in our outward affairs,
is to submit to that which may be required of us.
I am ready to think if there be any thing for me to do in the line of business, it will,
be in a very humiliating way: that I must, whether in business or not,
descend into a rank far below the wishes of my dear relatives and friends,
and be subject to the needs of those poorer brethren and sisters,
who are often meanly esteemed and little regarded:--that I must thus
enter into their sufferings and taste of their cup of bitters;
and thus also loudly testify against the prevailing prejudices, pride,
and luxury of this age,
but more especially against many notions and opinions
that are creeping in amongst us as a people.
Oh! how is the prosperity of the precious cause of Truth
obstructed and impeded;--how grievously is it suffering under
some who call themselves its friends:--
"`you are my friends, said our Lord, if you do that which I command you;`"
you are the friends of Truth,
who obey the dictates of Truth:--But those would rob her of her simplicity,
and have her disguise the distinguishing features of her countenance,
and cover her with their own deceitful embellishments, their own vain inventions.

But I cannot express to you the warmth of feeling that prevails with me,
when I look around and consider the situation of that numerous class, the full, the rich,
and the gay; nor can I convey to you the pity that I have in my heart for them:
how are they encompassed about by their own selfish,
earthly satisfactions and comforts,--how are they snugly nestling themselves,
in that which is likely in the end to prove to them a bed of briars!
May we be favored to subject our own fallible faculties and powers,
our own reason and natural understanding,
which are ever apt to busy themselves in things that
cannot rightly be brought under their decision;
that we may each (I repeat) endeavor to sink down low and dwell low in that,
which shows indubitably the good from the evil in all our undertakings and designs.
Oh! this is an attainment that comes only by a diligent
attention to the voice of the true Shepherd.
Your very affectionate friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia A. Barclay

[.signed-section-context-open]
Tenth month 31st, 1817.

[.salutation]
My dear sister,

You are very near to me in the best sense;
how precious to feel one another to be under the continual observation of One,
who cares for us and watches over us for good.
Though I have passed over some wild heaths and dry deserts since I last saw your face,
and have been, as it were, parched with thirst and panting for the water-brook,
longing also for the shadow of the great Rock in this
weary land yet there has met me the good Samaritan,
while I lay by the road-side, bruised and buffeted by him who way-laid me.
What shall I say of all that has been done for me, by Him who had compassion on me;
how precisely can I point you out the spot where he saw me as I lay:
it was even at that spot where every human help forsook me,
and every hope seemed to be taken away;--the priest and the Levite had passed by!
I have, I think, seen by experience, somewhat of the narrowness of the right path;
and in prospect (as regards myself,) I see it more and more narrow:
still have I day by day the portion of encouragement that is best for me,
the good that is convenient,
and such timely support as enables me still to struggle forward, still to journey on.
May we be both aided to look over and beyond our trials,
to the inheritance laid up for those who persevere in faith and patience to the end.
Let not your feet slip insensibly from off the sure foundation, the Eternal Rock,
the unchangeable Truth; but often be concerned to survey your building,
and upon what it stands;
to examine whether it be firmly fixed upon that which is immoveable,
or whether it be in any degree propped up by inferior dependence: also, inquire whether,
if outward means, aids and instruments were removed,
your building would still withstand the inclemencies of the varied seasons.
For when the floods of affliction outwardly or inwardly arise;
when the winds of opposition or of persecution assail,
and when the rains descend,--it may be too late for any to lay to heart these things;
for their ruin may be at the door.
The approbation, the regard, the sympathy of such as love what is good,
have required from me all the watchfulness,
all the earnest desires for preservation that I have been blessed with.

How needful then is it that our foundation be on that,
in which there is no variableness neither shadow of turning.
Thus we may come to know in whom we have believed, and to see who is our Teacher,
and to feel Him a present help in the time of need, -- a shield, a tower, a rock,
a refuge, our joy and crown of glory.

I have longed that, amongst the many deceits of the enemy,
you may not be taken by a very subtle one--discouragement.
Oh! how many have set out well,
have made some strait steps with firm foot and steady eye,
have begun to show forth by some sweet fruits,
the great and marvelous power which has visited them;
yet through giving way to the wiles of the enemy,
they have let in discouragements like a flood,
which have borne down everything before them.
All unprofitable discouragement, all undue lamentation on account of frailty,
folly or disobedience may be considered to be the work of him,
who was a liar from the beginning.

We read that "`godly sorrow works repentance;`" and it is
indeed nothing short of an ungodly sorrow that induces despair.
Oh! that we may be content at such times of discouragement to
sink down with that which suffers within us;
that we may there wait in patience, in humility,
in true prostration and silence of all flesh, being determined to hope against hope,
being resigned to acquiesce in whatever may be called for.

We profess to believe, that that which is to be known of God, is manifested within;
and that there, is revealed or manifested what the Lord requires at our hands.
I believe that we have need to exercise a daily
and hourly watching and waiting in the light,
in order to be favored clearly to discover those things that belong to our peace.

--

[.asterism]
'''

Eleventh or Twelfth month.--The Lord ever hears and answers the prayers,
which he has put into the hearts of those that desire to fear him.
As far as I can recollect, those daily formal repetitions of words,
in the practice of which I was brought up,
were but seldom accompanied with that which is the essence of true prayer, that is,
a reverential breathing unto the Lord,
and a longing of the soul after those things that we need.
There were times too, in which my soul did ardently crave the attainment of best things;
but then my prayers being confined to certain times and certain words,
and I being taught this restricted notion of the act,
it did not allow of the springing forth of those secret desires,
which the Lord raised in my heart;
so that these seasons wherein true prayer was begotten by Him,
who teaches when and how to pray, were not rightly availed of or profited by.

I remember that after I refrained from repeating those forms of prayer,
which were taught me in my childhood,
I was much in the habit of kneeling down and repeating extempore prayers,
by dint of my natural abilities:
this I did for some little time with great fervor of youth and eloquence,
even sometimes aloud, both morning and evening;
until the Lord opened my eyes in this respect, and gave me clearly to see,
that these attempts in my own will, way, and time, were but sparks kindled about me,
and which availed nothing with Him,
whose own sacrifices (of his own preparing and kindling) were alone acceptable.
Thus in obedience, I was made willing to be silent and seek the Lord;
who is nigh at hand, and dwells in the hearts of his people,
and is not far from any one of us, if we look for and unto Him.
This silence of all the creaturely reasoning powers was very hard to something in me,
which would be judging and questioning; very unmeaning did it appear;
yet dared I not forbear to meet with my Lord and Master, or to strive to meet with him,
day by day, and oftener than the day;
and frequently crying in the depth and sincerity of my heart unto Him,
that he would be pleased to show me the way to call upon him aright,
and what to pray for, I was often in tears and lay down my head in grief upon my pillow,
fearing I should never be made sensible of true prayer,
and partake of the privilege of "`praying always.`"

The Lord did not long leave me without his blessing,
his blessed countenance and presence and comfort;
no,--he showered at times of his merciful goodness into my poor heart,
and kindled such love towards Himself, such earnest breathings after the further arising,
the glorious spreading and increasing exaltation of His name, and power, and truth,
as enabled me truly to praise and bless His holy name;
engaged me still more to cleave unto, obey,
and follow Him in whatsoever he might require.

My soul was also filled with living warmth of love and charity towards his creature man,
whom he created in his image;
with great pity also towards such as had deviated from
the path in which He would have had them to go,
and who had thus turned away from the Lord their leader:
an unspeakably sweet feeling of fellowship and sympathy arose in me,
towards those in whom the Lord had excited a love or desire of Himself.
Thus was true prayer in and by the true Spirit, in measure raised in my heart,
not according to the way or time which man's wisdom or inclination would lead and teach,
but the very contrary; for even to this time, I am often so situated,
as not to have any words for long seasons together to utter,
either audibly or in my heart; and still more often am in dryness, distress,
and apparent desolation: yet through all I can praise the Lord.

Eleventh month 27th.--I question whether they
who go empty away from our religious meetings,
or from those gatherings of two or three in the name of the Lord Jesus,
where He himself is in the midst,
ready to heal each one of his diseases and infirmities;--I question much whether
such as go home none the better for meeting with those thus gathered together,
are not "`rich,`"--are not full,--are not satisfied, confident,
"`settled on the lees,`" sluggish and sleeping in security.
We may remember, there is a woe against "`those that are at ease in Zion.`"

It is also worthy of remark, that all those that came to Jesus, when personally on earth,
to be cured of their maladies,
were in a very opposite state to that of those of whom I have spoken above;
these were destitute, afflicted, forsaken, despised; and what is still more,
they were sensible of their lamentable situation, their helplessness and distress;
and they knew or believed who it was,
that had power to stem the current of their troubles, the tide of their calamities.
"`Speak the word only,`" said one, "`and my servant shall be healed.`"
"`Believe you that I am able to do this'.`'`"
said Jesus to two, who answered, "`Yes, Lord.`"
"`Lord I believe,`" said another, "`help my unbelief.`"
So that the blessing which makes truly rich,
shall assuredly and inevitably come down in abundance upon those,
who with a humble and a contrite heart, wait upon the Lord,
and are exercised and engaged in truth and earnestness to seek Him.
What a rich reward of peace at times flows into the hearts of these true disciples,
these poor publicans, these buffeted, bruised, broken-hearted little ones;
whose help is placed, and hope fixed upon Him that is mighty,
the giver of glory and grace, and of every good thing;
but whose hands are ready to hang down, their knees to smite one against the other,
and their hearts to fail, because they find not Him whom their soul loves,
and feel not his aid "`who is able to save unto the uttermost.`"
These are the poor of the everlasting kingdom,
and are richer than the richest in outward mammon,
or even than the richest in good works,
(though these also will not be lacking herein,) because they are the
"`rich in faith,`" whom God has chosen as heirs of the kingdom,
which he has prepared for them that love him.

Twelfth month 10th.--I can look back upon many a favored season,
many an availing prayer,--sometimes a single sigh after what was good,
--sometimes the mental eye turned inward during a few spare minutes
of intermission or leisure from the hurry of business,
when in my father's banking-house; sometimes as I went and returned to and from town,
but especially before dinner.
At that particular time,
I was in the regular habit of secluding myself for a short season in private,
and either devoting that opportunity to reading the Scriptures,
or more commonly to silently seeking the Lord, and waiting upon him for support,
strength, sustenance, and whatever he saw needful for me.
After this period, the efficacy of the same spirit of dependence and reliance,
which the Lord had begotten and kept alive in me, was striking;
and it has been memorable to me since,
when I was engaged in the business of an attorney's office, and lived at lodgings:
there the same power, as I was concerned to keep close to it,
preserved me through all the difficulties and trials that were strewed in my path.
What sweet first-days have I spent at a disagreeable dull lodging;
what meetings have I had, what sweet meetings in the middle of the week,
when I gave up every thing that stood in the way,
and thus procured liberty to attend them.
What sighs, what cries unto the Lord in secret corners,
when a few minutes could be spared in the midst of the bustle of
worldly engagements:--when walking through the noisy crowded streets,
what songs unto the Lord God of all tender mercies,
who overshadowed me;--and when occasionally an afternoon was allowed me,
wherein to be absent from business,
what sweet contemplative walks in the meadows and country, a few miles out of town!
But how shall I stop, or where shall I end,
in speaking of the merciful compassion of Him, who regards the prayer of the humble,
under many circumstances which I have not mentioned.

How has the Lord ever had his eye upon and over me, to turn all to good,
as long as I have regarded, trusted in and resigned myself unto, his preserving power;
when I have been enabled to say, "`I am yours, do with me what you will.`"
So that surely we may never doubt but that "`whosoever
calls upon the name of the Lord shall be saved.`"

17th.--In the midst of much drought and distress and apparent
desertion which have encompassed me for a long season,
I cannot forget the grievous sufferings which the greater part
of my fellow-creatures are daily undergoing.

How my heart has been this evening affected with the sight of a heap of human creatures,
nestling together under the shelter of a wall,
striving to cover each other's half bare limbs from the piercing cold.
Ah! you rich, you gay, you proud, you professors of good words and good works,
the charity of this starving family will sooner be accepted of their Maker than yours;
for you of your abundance have cast the paltry pittance,
while they have in their wretchedness sheltered each other from the piercing cold,
and wept over each other's woe.
Surely, surely,
(I have been ready to exclaim in my heart at this, and at other times,)
the Lord Almighty will arise for the cry
of the poor and the sighing of the needy;--surely,
he will take vengeance upon such as spend their lives in fulness of
bread and abundance of idleness,--upon such as abuse his gifts,
and forget his creatures, and shut up their bowels of compassion against their own flesh,
and do not remember the many good things which the Lord has showered upon them.
Oh! how heavily has my soul been burdened, because of such who live in pleasure,
in luxury, and extravagance; and how deeply have I felt for the poor and needy.

Date uncertain, perhaps twelfth month, 1817.--It seems as if,
after such exercise and trouble as can scarcely be expressed to another,
I had now at length a glimpse of light thrown on the path before me,
through the free extension of abundant mercy.
Yet what a spark, what a faint flash, what a slender beam!
When I consider how easy it is, to mistake the true shinings of the heavenly star,
to listen to the whisperings of the deceitful one,
and to take them for the manifestations and leadings of the best Counsellor,
the infallible Guide;--my spirit is engaged in earnest desire,
that I may be preserved on every hand and protected from the evil.
How strongly does the instance of faithful Abraham, come to my mind,
while writing these lines; and firmly am I encouraged to believe, that He,
of whom it is said, "`faithful is He that has called you,
who also will do it,`" even the Father of faithful Abraham,
whose tender mercies are over all his works,
and who remains even now the same unfailing source of help and strength that
ever he was,--will be near to the very least of his contrite little ones;
even those that are bowed down and bruised and buffeted.
He knows indeed who these are, though no one else may cast an eye upon them,
esteem or regard them.
He knows their sufferings, their sighs, their tears; and oh! what a sweet savor,
what an acceptable incense, arises from the hearts of these,
even though no knee be bent or mouth be opened.

Surely under the shadow of His wings,
under the blessing of the strength of His extended arm shall
these go forth through this vast howling wilderness;
the floods and rivers shall be divided and dried up before them,
and the parched desert shall become a fruitful field.

Date unknown.--We are placed here on earth only for a season: like travelers at an inn,
we are permitted to take shelter for a night in
this frail habitation:--it is a strange place,
and has but temporary and middling accommodations; and all the comfort it affords,
is far inferior to the abundance,
which we have to expect will be dealt to us in our Father's mansion, our heavenly home.
None of those numerous objects which we see around, rightly belong to us;
they are not our property, strictly speaking;
but are lent to us for the supply of our necessities, for our comfort,
for the right enjoyment of them.
I have often wished that this view of life might occasionally occupy our minds.
Let us consider what would be some of the consequences of taking such a view of life,
as I have ventured to point out.

Let us see what ought properly to follow,
from the establishment of such a principle as this,
that the earth we inhabit is not our rest,
that we are but pilgrims and wanderers upon the face of it,
that none of those things which our senses can perceive, are our own;
but that we are only for a time permitted the use of them: how could we,
with this principle in sight, abuse those innumerable blessings,
which the great Giver of every good and perfect gift,
has been pleased to bestow;--how could we do
otherwise than apply all those natural things,
which are in mercy provided for us, to the purposes for which they were intended.

Then among many other good effects there would be no
servile and degrading obedience to custom and fashion;
but such simplicity in our way of living, such denial of whatever is superfluous,
expensive, useless, or productive of injury to the mind,
as is now scarcely thought of or understood.
