== Chapter VII.

1818,
First Month 12th.--The struggle which I have been enabled
to sustain against a flood of affliction and deep exercise,
still goes on, through unutterable mercy and condescension;
but it is daily with me a question how each succeeding day`'s conflict will terminate.
It seems sometimes as if there was no other language in my heart,
but--"`If it be possible, forsake me not, Oh, Most High!`" again, when a little relieved,
some thing seems to arise like this.--"`Save me from myself, leave me not to myself;
spare not, neither pity,
but utterly destroy all that in me--which is not of and from you.`"
What tomorrow`'s light may bring forth, what it may find me, or in what condition,
I know not; but this do I desire to know and to be assured of,--that the Lord is,
and that he is good,
and to feel his goodness overcoming and taking the place of the evil,
both in me and in all the world.
Oh, that I might be delivered from all looking out
for release from this chastising and purifying dispensation,
which has been in an increasing measure allotted me ever since I was made
willing more fully to follow the Lord in the way of his requirings.
Oh, that I might be preserved from all desire to take myself under my own care,
or to walk in the way which my own will approves: and as to outward matters,
that I might be made more and more entirely disposed
to acquiesce in whatever is manifested unto me,
to be the will of the Lord concerning me.
The highest good that I or any can attain to in this life,
seems to me at this time to consist and centre in
the ability to say and feel always,--"`Your will,
and not mine, be done, O Lord.`"

1818, First Month 20th.--Oh, how much dross,
how much evil is there still lurking within me,
how many and how deceitful are the modes by which
the enemy contrives to keep up his kingdom,
his seat in my soul; when shall I, through Him that fights for me, utterly expel, subdue,
and tread under foot, this unwearied enemy!
The Lord, my strength, give me patience;
that I may quietly confide in Him yet more and more; and embrace all the exercises,
chastenings, withdrawings, judgments and afflictions,
which he is pleased in mercy and love to bring upon me:
for I think I see plainly that his scourge and severity
is not dealt out to his tender babe like nature,
but to that nature which is not of Him, but of the wicked one,--even that selfish,
unfeeling, Egyptian spirit which is to be destroyed.
Oh, how much of this do I feel continually within me,
lurking in secret under cover of many plausible pretences,
eating out any appearance of good with which the Lord is pleased to favour me,
appropriating to self any good action, motive, or thought; endeavouring,
when it cannot hinder the entrance of good, to make me proud of it,
and so convert it into evil:--thus the best friends, the best books, the best feelings,
the best intentions with which I am at any time privileged,
these the wicked one endeavours so to pervert, as to render them a snare to me.
He cares not how busy I am in reading good books, how fond I am of waiting on the Lord,
how great a lover I am of the Lord`'s people and the Lord`'s cause;
if I will but fall down and worship him in these,
all shall be mine,--all the honour and praise of being a great and good character,
a saint shall be mine, if I will but let him have a little share, a little corner,
in my heart.
"`O Lord! disappoint him, cast him down; deliver my soul.
Let not your hand spare, neither let your eye pity, till all be utterly purged away,
which denies and is unseemly in your sight.`"
When my eye is opened rightly to see these things,
my heart craves that I may abide in patience,
under the operation of proving and refinement, however severe it may seem,
to wean me from this world and the wickedness thereof: not only from gross sins,
but also from hidden and secret faults,
and from the deepest insinuations of the enemy in my heart,
in the semblance of an angel of light.
I have had of late such a time of this discipline,
as had never before befallen me in my life;--such
apparent desertion of everything like good,
such distress in consequence of outward circumstances of various kinds,
that at many intervals, a deep conviction of the certainty of a future judgment,
seemed to prevent my choosing death, rather than life.
Yet through inexpressibly tender mercy,
I have been preserved to this day in earnest seeking after the Lord,
and with great desires after submission to his will, cost what it may.
And even in the hour of desolation and darkness,
I have often experienced such a sweet cessation from suffering,
and such an influx of love from the inexhaustible fountain,
as has enabled me still to struggle and hold on my way,
in a degree of hope (almost imperceptibly small,) that all would be well in the end,
if I was concerned to look unto Him, who is the author,
and also the finisher of our faith.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to S. A.

[.signed-section-context-open]
1818, Second Month 1st

I have been apprehensive that our views of these doctrines +++[+++of Immediate Revelation,
and the true and saving knowledge of God, and of his Truth]
which are closely accordant with those of the holy penmen of Scripture,
are but little known among the many religious denominations.
I have believed, both as to those within and without the pale of our own Society,
that there is in this day (as there ever has been,) more need of leading people,
in the first place, to the fountain of truth, the foundation-stone,
than of laying much stress upon the building,
the beautiful harmonious superstructure of doctrines, which arises from that base,
and can stand only upon it.
This corner-stone we well know is Christ, not merely testified of without us,
but also manifested within; and as we closely attend to,
and obey the manifestations of his Spirit and power in our hearts,
we come truly and savingly to know something of Him and his holy religion,
according to our present ability and growth:
and in following him in his leadings we are best able to
receive those true testimonies of him recorded in Scripture,
and livingly to understand, as well as availingly to believe,
what is there said of his appearance in the flesh, with all that he said, did,
and suffered.
There has been, and still continues to be a great deal said and written,
respecting correct and scriptural views, of the doctrines and duties of Christianity;
but I believe until men come to that,
which can alone give the true discernment of these spiritual things, they will,
they must continue to grope as in the dark, not knowing the Scriptures,
neither the power of God; and it is feared, resist Him, who the apostle said,
"`has shined in our hearts,
to give the light of the knowledge of the glory of God in the face of Jesus Christ.`"
It seems to me, that under the constraining influence of the love of Christ,
we should earnestly recommend people to believe in, and obey his light in their hearts;
that by following him in this manifestation, they may have the light of life,
as he himself has graciously promised.
No pointing to the written testimonies borne to the existence of this light within,
will avail, but as the mind is gathered (in some measure,
however small,) to that which witnesses those testimonies to be true,
and alone enables to receive them.
I cannot think that that Scripture, "`the letter kills,`" if rightly made use of,
could hurt any,
but those who walk not closely in accordance with that Spirit which gave it forth,
and which is able to give a true understanding thereof.
No man can availingly know or follow the directions laid down in Scripture,
but as he bows to the appearance and openings of that Light,
which enlightens every man more or less in the day of his visitation.
It seems to my view, that the greatest thing which we all have to guard against is,
the leaving our heavenly guide; and this may easily be done, both in reading Scripture,
and in every other religious engagement: if this be the case with us,
we cannot but wrest them, some way or other, to our own condemnation or even destruction,
whatever we may think or imagine; it may be by thinking to have life in them,
as the Jews did, whom Jesus reproved.
It was not that the Jews did wrong in diligently searching those writings,
or that there was any harm or noxious influence in Scripture,--it
was not in that sense that the letter killed,
or does kill; though on the other hand, we know, that they cannot give faith,
and that all their authority, and excellence, and efficacy in the work of salvation,
are only from that power and life from which they came.
But it was by reading in the light of their own reason,
which is indeed darkness;--heaping up a dead set of doctrines, in their own wisdom,
which is foolishness; presuming to pry into things too high for them,
things into which the Spirit of Truth led them not,
but their own speculations and imaginations;
thus they made the commandments of God of none effect, as many now do,
by their own traditions, and expositions, and interpretations, adding to,
and diminishing from, the true meaning of the Scriptures.
Being unstable and very unlearned in the Word, which spoke forth the Scripture,
though learned ever so much in the words, they cannot reach the essence;
but must stumble, as Nicodemus and other learned Jews did,
who knew nothing of the new birth;
though they could easily tell by the letter of the book, where Christ was to be born.

It is such in this day, who are crucifying unto them selves the Son of God afresh,
notwithstanding all their high professions about the atonement, etc.;
which they have very clearly in the notion and dead apprehension,
but out of the life of these things:--the evil spirits could testify of Christ, and say,
"`I know who you are, the holy one of God;`" and,
"`these are the servants of the Most High God,
which show unto us the way of salvation;`"--for even these had a knowledge of God,
and belief in him,--a knowledge of Christ,
and confession of him,--a knowledge also of Scripture.
The enemy also himself was ready at quoting Scripture,--witness
the temptation of our Lord;
and he can put men upon studying the Scriptures,
so long as through the carnal mind he may but interpret, and apply them to their states;
for by all this he has the poor soul the safer in his net.
He is not deterred from prosecuting his evil designs,
by our holding the Scriptures in ever so high estimation; if, in studying them,
we lean on our own understanding, although with great and apparently laudable zeal:
though we apply one part to confirm another,--though we get them by heart,--though
we extract all the doctrines and duties that are testified of therein,--though
we are able by this skill to give an expert answer to such as may inquire
a reason of the hope that we have adopted,
and the faith which we have formed out of the letter of the book,--though
we even set ourselves to do all that is commanded;--yet all these willings,
and runnings, and strivings, do not overthrow his government in the heart: no,
his snare is not broken, but made more subtle and intricate.
It is the simple, and those that abide in the simplicity of the Truth,
that are kept by the Truth out of his beguiling snares;
the Spirit of Truth is their shield and sure defence on the right hand as on the left,
and they lean not unto their own understandings;
so that the Scriptures and every other outward means are blessed to them,
as they keep to the anointing which they have of him; by which,
whether with or without instrumental aid,
they know all things requisite for their present need;
having "`an understanding given them to know him that is true.`"

--

1818, Third Month 3rd.--I believe if young persons were more fully open,
and implicitly given up to acts of dedication apparently small, and were willing to go,
to stay, to do, or to forbear in minor matters, as seemed best,
that they would thrive more vigorously in religious stature and strength.
One thing after another came gradually before the view of my mind; all that I had to do,
or believed was required at my hands, came not upon me at once:
for there was no hard task-master to obey, but one who knew my weakness,
and my inability to give up even to the least matter of duty, without His special aid.
As I was concerned to keep my eye open,
to see what ever He might show me was to be given
up to,--and as my desire from day to day unto him,
and the accomplishment of His will respecting me,--first one thing, then another,
at seasons opened before me with sufficient clearness:
sometimes these apprehended duties were very little matters,
at other times they were of fearfully great importance;
and often were they of a nature and complexion,
which the worldly-wise part in myself and in others, could not bear or understand.
Yet after having gone through and been favoured to
stand faithful in the performance of these things,
I have often seen the propriety of them;
and I have felt it a precious thing to be "`led about and instructed`" so suitably,
so seasonably, so safely.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to E. H.

[.signed-section-context-open]
16th of Fourth Month, 1818.

[.salutation]
Dear Edward,

It is my belief, that, according to your own expressions,
"`the Master is come,`" and coming, (what if I say,) to plead as in old time,
with the modern money-changers in the temple,
who turn the holy house of Him that is most holy,
into "`a den of thieves;`"--to upset their tables
and to scatter their silver and their gold;
the "`love`" of which, is said to be, the "`root of all evil.`"
His scourge is, as it were, in his hand; and the buyers and sellers being cast out,
the blind and the lame shall yet come to him in the temple,
the house of prayer for all nations, and he will heal them.
The little children shall yet cry in this temple, saying,
"`Hosanna to the Son of David;`" and out of the mouths of the very
"`babes and sucklings,`" whose hearts he has fed with "`the milk
of his Word,`" praises shall yet come forth unto Himself.

It is my belief, and I feel freedom to mention it to you, that there are`' or will arise,
those who will, in some sense, "`build the old waste places.`"
I live in the faith that the Truth shall spread;
and the number of those that are guided and governed by the teachings of that Spirit,
which leads into all truth, will be greatly multiplied.
Surely there are even now those that "`are left of the captivity,`"
who "`are in great affliction and reproach;`" we may also say,
that, in some acceptation of the passage, "`the wall of Jerusalem is broken down,
and the gates thereof are burned with fire.`"

May I not also add, that there are, even in this day, those,
who can in measure adopt a similar language with
that of Nehemiah,--"`When I heard these things,
I sat down and wept, and mourned certain days, and fasted,
and prayed before the God of heaven.`"
Surely there are those that can say, "`I arose in the night,
neither told I any man what my God had put in my heart to
do at Jerusalem:--then went I up in the night by the brook,
and viewed the wall, and turned back;--and the rulers knew not where I went,
or what I did: neither had I as yet told it to the Jews, nor to the priests,
nor to the nobles, nor to the rulers, nor to the rest that did the work.`"
There are doubtless some that are ready to laugh these to scorn, and to despise them;
and to say,
"`what is this thing that you do?`"--and I judge there are those that can reply,
"`the God of heaven, he will prosper us:
therefore we his servants will arise and build.`"
To such as endeavour to entice the sincere-hearted, and to take them off,
by whatever specious pretence, from their watch and work,
their unceasing concern and travail for the prosperity of the great cause;
I am clearly of the mind that the reply should be, "`I am doing a great work,
so that I cannot come down; why should the work cease,
while I leave it and come down to you?`"
Now the work that is needed,
as far as I have in this and some other favoured seasons had capacity to see, is,
a sinking down and bowing down yet lower and deeper than many of us have hitherto
humbled ourselves,--even under the government and dominion of the holy seed,
Christ Jesus; that so we may, through subjection to Him,
be led to "`cease from our own works,`" and to let Him do
and work all things in us according to his own divine will.
Wherever this blessed work has gone forward with strength and beauty,
wherever this constraining power has been fully and faithfully given up to,
I believe a necessity has been sooner or later felt,
to make a full surrender and sacrifice of everything,
which the law written in the heart may call for.

From one, who is much more often than otherwise, plunged into the depths,
and who finds himself yet weaker and weaker in himself
to will or to do any thing as of himself,
but is at times favoured to see still greater necessity
for a daily waiting upon the Lord,
that so his will may be daily known and done through his Spirit,
which brings into and preserves in a watchful,
weighty frame of mind at all times,--and who is, with feelings of affectionate regard,

[.signed-section-closing]
Your friend,

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to E. S.

[.signed-section-context-open]
Russell Square, 17th of Fourth Month, 1818.

[.salutation]
Dear Edward,

The true authority as well as beauty of our religious meetings,
in which I cannot exclude those for the right ordering of the affairs of truth,
stands upon and consists in that, without which the very form is a mockery,
though the best of forms.
It is not age, it is not any station in the church,
it is not an outward knowledge or experience in the letter of those laws,
which the Spirit of Truth has led our forefathers to adopt,--much
less is it any repute among men grounded upon outward possessions,--which
will make one living stone for the Master`'s use,
in the building up of his beautiful city, the new Jerusalem.
Now, if any man build with the straw and stubble,
or even with that which appears like gold or silver;--every
man`'s work shall be made manifest of what sort it is;
for it shall be revealed by fire, and the day shall declare it.`"
How much need then is there for all among us,
who fill any of the offices in the church,
and even for such as may be in the highest stations,
and may have been made of eminent service therein,
yet again and again to wait upon the Lord, yet again to bow down their souls;
so that every high thing, that would exalt itself within them, may be abased,
under the humbling influence of that power, which bruises and breaks in pieces,
which brings us low, and keeps us low, even as children and babes,
willing to be led about and instructed,
and ready to esteem another better than ourselves.
Now as individuals are brought into such a feeling tender state as this,
they become sweetly qualified to take those places,
which the master-builder orders for them in his house, in his family, in his vineyard.
They thus receive capacity and authority to labour for the great cause,
and in the name and power of their leader; they have strength to bind and to loose,
to help and to heal the weak and the wounded;
and they have the spirit of patience and of pity given them,
to plead with and to pray for the tempted, the tossed, the tried.
And Oh, the tenderness that is shown by such as these,
on behalf of their poor fellow creatures,
who may be overtaken or overcome of evil or error; knowing that they themselves stand,
only through the mercy of the Most High.

[.signed-section-signature]
J+++.+++ B.

--

1818,
Fourth Month 21st.--How little do we know what is
best for us:--Oh, how good a thing it is,
to be led about and instructed by our tender Parent, even as little children;
seeing that we, no more than they, can run alone with safety.
When I am ready to receive hurt from some precious gift or other,
which He has lent me;--when I am likely to be elated by seeing myself so favoured,
or to assume any thing to myself because the Lord showers upon me his blessing;--then
in the abundance of his compassion he takes away that which I was ready to abuse,
and leaves me in darkness and in the deeps,
it may be without a shadow of comfort or a ray of his heavenly presence.
And then, in the bitterness of my soul, in the absence of my Beloved,
I cry out and weary myself with bewailing;
being in my own apprehension on the point of despair.
But He, even my Father, regards not my crying, nor my weeping;
he knows best what is good for me,
and continues his dispensation of afflicting darkness and drought,
until in his wisdom he sees, that the set time to favour me is come.

1818,
Fourth Month 22nd.--Was much instructed by looking over a Monthly Meeting`'s early minute-book,
dated about 1666.
I thought I clearly saw that our Friends in the beginning,
were a simple plain set of people;
and that they mostly had but a very small proportion of learning or general knowledge,--very
many in early times not being able to write legibly or even some to read.
Various advantages have we above them in several respects; yet it has seemed to me,
that some of these very advantages have proved our hurt and stinted our growth,
so that we have not arrived at their stature or strength.
"`The love of other things,`" we read, choked the good seed; and this seems to me,
to be applied to our case,
who have many "`other things,`" (some of them very good when kept in subjection,)
which draw away our minds from the simplicity of the Truth,
and from a patient, humble, waiting frame of mind,
in which alone true safety can be witnessed.

1818, Fourth Month 26th.--I desire greatly not to be led away and ensnared,
by coveting or looking for the esteem and notice of any, even of religious characters;
I pray in my heart,
that I may be preserved from liking to hear my own voice and tongue in company,
and from the least approach to any thing like a love of showing off even good qualities.
If we are in the right spot, we shall forget ourselves,
and not esteem those things as our own, which are wrought in us,
or which we have been enabled rightly to do or say.

I have also seen,
that much care is needful not to be endeavouring or presuming
to correct the views and sentiments of others,
by our own strength and in our own will and time; I see danger in this for all,
but especially for young people, who are so likely to get into argument and much talking.
Nothing is gained often thereby;
but the way to openness and conviction respecting any matter, is much blocked up.
But after long patience and waiting, and much uneasiness has been undergone,
lest the right thing should by any means suffer,--and after not a little exercise
of mind on account of the person who may hold such a wrong sentiment,--then have
I seen a word in season put forth in meekness,
do more than all the ill-timed efforts of a man`'s own will and strength.

1818, Fifth Month 10th.--The day before yesterday, I completed my twenty-first year.
I may say, with some feeling, that my breathing in secret is unto the Lord,
that he would in mercy continue near to me, to help in time of need;
for I am still unable to take one right step, notwithstanding any thing already attained;
but have need day by day to wait upon him again and again, for a renewal of strength:
for assuredly He alone, who began the work, can safely carry it on,
and bring it to such a conclusion as will redound to his own praise.

1818, Fifth Month 10th.--The day before yesterday,
it seemed right for me to give up to go and sit among
Friends at their Monthly Meeting at Kingston.
I had no probable means of conveyance but on my feet, and it was a very rainy morning:
but I cried unto the Lord that he would direct me,
and give me sufficient strength to do whatever might be best.
I got there (it being,
I suppose more than thirteen miles) some time after the hour of assembling,
much wearied in body, but sweetly fresh and lively in mind,
through the extendings of mercy;
so that the driving rain and the length of my walk had not much effect upon me,
who am but a poor weakly one.
On my way there,
it rather vividly came to my mind,--"`what if I should have to speak in their meeting?`"
But the Lord quieted that spirit within me, which would be questioning and reasoning;
and I was favoured to feel great composure and calmness, notwithstanding that suggestion.
And Oh, the melting power and glorious influence which was enjoyed by me,
and I believe by others,
in the meeting for worship! how precious a half-hour did I spend among them! so much so,
that my heart was filled with the song of praise unto that great Being,
who remembers and cares for his poor little ones;
and who in his own time fills his hungry ones with good things--yes,
with the choice dainties of his table,--so that their cup runs over!
Oh, the tears of joy that were shed! may I never forget
the renewed mercies of the Lord my God,
while I have my being!
The next day, was our Monthly Meeting at Westminster,
where were present some choice servants;
through whose ministry the language of encouragement was held out to the little ones,
but especially to those young in years,
whose hearts the Lord had in measure melted into a willingness
to be conformed to his holy will respecting them.
Oh, the unutterable condescension of Him,
whose mercies are new every morning! may the objects
of his bounty be yet more and more mindful of him,
and of his goodness;
and be induced yet more fully and faithfully to give up to his requirings;
to bring all the tithe into the Lord`'s treasury (as two
dear Friends said in the meeting,) and prove him there with,
and see if He will not open the windows of heaven and pour them out a blessing,
until there be no room to contain.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to E. J.

[.signed-section-context-open]
Isle of Wight, 30th Sixth Month, 1818.

[.salutation]
Dear Edmund,

I have felt so much dissipation of mind since I arrived here,
as to unfit me for a calm enjoyment of the beauties of nature,
so profusely mingled as they are here.
The cares devolving upon me, not a little tend to lead away the mind from that "`retired,
strict,
and watchful frame,`" (as I think William Penn calls it,) which seems
to be the safest and most profitable state for me as an individual,
and a soil most conducive to my present growth.
I may truly say, that though I desire not to prescribe for any,
otherwise than seems to be my especial duty; yet, I believe that few, very few there are,
to whom an approach to unwatchfulness or levity is not dangerous--is not ensnaring.
How often have I been in different degrees unfitted
thereby for that sweet retirement of mind,
which seems to be, as it were, the element and atmosphere of the true Friend.

I think of you at your Quarterly Meeting this day.--I long that the many Pharisees,
who are in the formality,
and obtrude their services and "`much speaking`" in meetings for discipline,
and some even in those for worship, may be kept under; for assuredly,
the wisdom that is from below, is at enmity with the pure lowly seed of the kingdom,
and will do only mischief to the good cause;
its nature and tendency being to exalt itself, while its pretension is,
to forward the right thing.
But the foolish things of the world, and the weak things, and the base things,
are still preferred and chosen to confound the wise,
and to bring to nought everything else, but the power, the life, the wisdom,
the nobility of the Truth.
Paul, the learned Paul, the enlightened Paul,
when he came from the feet of Gamaliel the Pharisee, and sat at the feet of Jesus,
would not even speak in the words which man`'s wisdom taught;
he came not with enticing words or excellency of speech,
lest his hearers should admire him or his words rather than the power;
and so their faith should stand in the wisdom of man, and not upon that foundation,
than which no other can be laid, and besides which,
Paul determined to know nothing,--even Christ, the wisdom and power of God.

Dear Edmund, you know all this, yet I long that we both may keep to those things,
which we have in mercy been made sensible of;
that so we may be enabled to stand for the Truth and its simplicity,
over all that which looks like Truth, but is not,--being only an image,
which the enemy has patched up and embellished, wherewith to deceive the simple;
and he would have us worship this image, and highly esteem such as sacrifice to it.
But Truth needs no ornaments nor paint,--none of the "`vain philosophy "`of the learned;
the polite airs and customs which are in the world, she shrinks from and avoids:
the studied maxims, and gathered wisdom, and logical conclusions,
and distinctions of the schools, only clog and impede our growth in the Truth.
Oh, how little of the innocence, and artlessness, and openness, and simplicity,
and natural beauty of the Christian religion,
is to be seen and felt thriving among us at this time!
The state of our Society not a little reminds me of that of a large machine or mill,
which was made skillfully, and set a going admirably, and went well at the first:
and when one wheel broke, the master took it away and supplied its place;
and when any part of the machinery was worn away through much service,
the master took care the work should not suffer thereby, but raised up other instruments.
But at length the dry rot or some terrible mischief gets in and spoils it,
so that the sound parts can hardly act or work, because of the number of unsound members.
In such case, surely the machine must undergo a thorough repair;
surely every member of the body must come under and
submit to the reforming and refining hand:
even the sound parts must, as it were, be taken to pieces for the sake of the rest;
that all may be reestablished in their several places,
and according to their different capacities, by the ordering of the great Workman,
whose workmanship they are.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to a Friend

[.signed-section-context-open]
London, 29th of Eighth Month, 1818.

I believe there may be much show and appearance of excellent dispositions in some,
who have not had any call to service in the line which they may have set their feet in,
as well as in some that have not abode long enough under the refining hand,
which was fitting them for their allotted post.
These may talk of the degeneracy in the faith or
practice of others who profess with them,
and may lament or seem to lament the innovations or backslidings of their fellows;
and they may for a time keep within the limits of consistency,
imitating the actions of those,
whom they apprehend to retain something of primitive zeal and uprightness.
Some also of these may, in the heat and warmth of the sparks which they have kindled,
and with which they have compassed themselves, begin the work of reformation,
or rather set about it in their own wills, and after their darkened apprehensions;
and when they see their endeavours not owned nor seconded
so readily or quickly as they deem them worthy,
(for the faithful cannot own them,) then it sometimes happens that
these spirits burst out into open variance with the body;
and so manifest their foundation to the faithful,
whose eyes the Lord opens to see and to discern the good,
from that which only appears to be so.

Such a one, if he is ever favoured to see the error of his way and to turn from it,
will have to acknowledge, that all his stirrings, strivings, willings, runnings,
his labours and services, even to promote good, were out of that Spirit,
whereby alone good can be discovered, embraced, or promoted in his own heart,
or in the hearts of others.
There is then great need for all, to wait upon the Lord,
to feel his power discovering the evil and the good in us, raising up the one,
and enabling us to overcome the other: and as we continue faithful to these discoveries,
we shall be made partakers of more of his gifts,
and grow in a living experience of his Truth,
and in a lively understanding as to such things as are best for us to know;
until it please the Lord to dispose of us in that part of his vineyard,
where he "`has need of us.`"
Then as we abide in Him, from whom we derive our strength and vigour,
we shall bring forth much fruit, not only to his praise and our own peace,
but to the edification of the church and to the comfort of its living members.

[.signed-section-signature]
J+++.+++ B.

--
