== Chapter VIII.

+++[+++The subject of the religious instruction of our youth,
about this period attracted much attention in the Society;
upon which occasion the author felt a lively concern,
that so important a work might be undertaken upon the right ground,
and that a mere formal knowledge of Scripture on the part of young persons,
might not take the place of a true spiritual nurture in the Lord,
and an inward growth in grace.
On this subject he expressed himself as follows, in a letter to a Friend:]

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to R. B.

[.signed-section-context-open]
Fifth Month 1st, 1818.

[.salutation]
Dear R.,

Bear with me, who am but a younger brother, if in a little of that love,
which is ever ready to esteem another better than one`'s self,
I should be bold to express to you my opinion,
that any contrivances to store and stock the memories of young
persons with a literal knowledge respecting religious matters,
cannot of themselves be productive of that true and living faith,
which we as a people profess to seek an establishment in.
I am in the full belief, that Scripture doctrines cannot be really, rightly,
and savingly known and held by any,
if they come not to have them written in their hearts; so that,
though they may be ever so well initiated in something,
which looks like a perfect knowledge of these things,--though
they may be able by the exertion of their natural understanding,
and by dint of their memory,
skillfully and readily to reply to those who may make inquiry of
them,--though they may be wise as Apollos in the words of Scripture,
and seem competent to explain and support our religious
principles;--yet all this will avail nothing,
if the wrong wisdom be uppermost in them, and sit as an angel of light,
and rule and reign in their hearts; while the babe, the seed, the very Truth in them,
is crushed and crucified.
I desire therefore,
that I myself and all others might be engaged in patiently waiting
upon the Lord in the silence and subjection of the fleshly wisdom;
that so,
that disposition which would be setting us upon manufacturing
for ourselves something to believe in,
or to profess a belief in, might be starved and tired out: thus should we,
in the Lord`'s own time,
be led into a true and saving knowledge of those
truths which are needful for us to understand.

I well remember what Robert Barclay`'s experience was,
as described in that part of his Apology which treats of worship.
He says, that he did not come to receive the Truth, by strength of argument,
or by a particular disquisition of each doctrine,
and convincement of his understanding thereby;
but by being secretly reached by the life:--"`for,`" says he,
"`when I came into the silent assemblies of God`'s people,
I felt a secret power among them, which touched my heart; and as I gave way unto it,
I found the evil weakening in me, and the good raised up:
and so I became knit and united unto them,
hungering more and more after the increase of this power and life,
whereby I might feel myself perfectly redeemed.
And indeed this is the surest way to become a Christian;
to whom afterwards the knowledge and understanding of principles will not be lacking,
but will grow up so much as is needful, as the natural fruit of this good root;
and such a knowledge will not be barren nor unfruitful.
After this manner, we desire therefore, all that come among us to be proselyted;
knowing that though thousands should be convinced in their understandings,
of all the truths we maintain, yet if they were not sensible of this inward life,
and their souls not changed from unrighteousness to righteousness,
they could add nothing to us.`"
It seems a very truth with me, that though for good reasons we, as a people,
account our children to be our members, yet no one can be rightly and truly our member,
who comes into the fold by any other way than by the door, Christ Jesus;
and that although we may do all for our dear youth, which our wisdom is competent to do,
in the way of religious instruction,
yet nothing will supply the place of that earnest travail,
that patient exercise of spirit on their account,
which is indeed availing with our heavenly Father,
and which is much needed among teachers and guardians among us.
So that the line of our labour,
seems to me to be more in endeavouring to direct them to the fear of the
Lord,--to engage them to self-examination,--to show them the place of
true waiting,--to point out to them where the Fountain is,
where the treasure lies,--and to prevail with them to come, taste and see,
the goodness of the Lord, and what he has in store for them that love and wait upon him.

Some may be disposed to lament over the little acquaintance,
which young persons in our Society appear to have,
with the reasons or grounds of our peculiar religious profession.
No one, I am ready to think, laments it more than myself:
but if such think to patch up a remedy by the adoption of those creeds, catechisms,
and confessions of faith, which the worldly professors adopt,
and have adopted (as I believe,) ever since the apostacy,
and out of which Truth led our forefathers,--I lament this remedy,
still more than the disease.
Because then we stand in danger of having a set of young formalists rise about us;
whose heads are likely to be more filled with notions,
than with that nothingness of self,
which is as truly the introduction to all right knowledge on these subjects,
as the other is a snare and stumbling-block in the way of it.

I apprehend that the principal cause of the ignorance
above adverted to of our religious principles,
and of the reasons that may be rendered in support of them, is,
not so much the lack of having examined such books as have been written on these subjects,
as of a serious seeking unto Him,
"`in whom are hid all the treasures of wisdom and knowledge;`" who said, "`Seek,
and you shall find,`"--and whose promise of finding was, and is,
only to the wrestling seed of Jacob, who, doing the will of the Father,
know of the doctrine of the Son; and to whom it is given in the very hour of need,
what they shall answer, and what they shall say in defence of the Truth.

It seems well for me,
(though very sensible of my own state of childhood in religious
growth,) here to state how I came to believe and receive the Truth,
and the doctrines of it, as professed by us.
When it pleased an unutterably merciful Power to
pluck my feet out of the midst of mire and filth,
and clearly to show me what I was,
and what I should be,--then there sprang in me living desires
to know the way to the kingdom;--then it was,
that the enemy, as a transformed angel, took me into the wilderness of notional religion,
and set me upon examining different systems of religious belief, in my own will,
as well as upon judging of them by my own wisdom: and I compared doctrine with doctrine,
text with text, and became by diligent study, wise in notions,
though truths in themselves; and the enemy made me strong in argument,
and potent in Scripture.

But how shall I speak of His goodness, who broke the net in which I was entangled,
and delivered me from the snare;
and who introduced me in measure into the saving knowledge of Himself,
even that which is revealed, as in the cool of the day, by the still small voice.
Oh, how plainly did I then see, that all which I had learned, read, held,
and believed in my own will, was to be given up; how clearly did I see,
that all knowledge, faith, obedience,
but that which the Father was pleased to beget and raise in me in his own season,
was good for nothing,
and must be cast out as salt that has no savour--as manna not fit for present use.
And though I have read many books, which treat of and support our principles,
believing that they are very comfortable and confirming to him who has come to the Fountain-head,
while his mind is turned inward in reading them,
and also useful in satisfying the simple-hearted inquirer,
whose simplicity the Lord regards, and of service in stopping the mouths of gainsayers;
yet to this very day, I dare not sit down and study Friends`' opinions and principles,
as a science, but find myself constrained to wait upon the Lord day by day, that so,
as much strength, as much knowledge, as much satisfaction in regard to religious matters,
as is best for me in my religious condition, may be handed to me.
And in truth, this is the surest way, says my very soul, from daily experience;
for things have never been cleared up to my certain
satisfaction in such a wonderful manner,
as since I have been under this discipline of the cross to all selfish wisdom.
Oh, the sweetness of being under the tuition of Him,
who verily teaches as never man taught.

[.signed-section-closing]
I am, your affectionate friend,

[.signed-section-signature]
J+++.+++ B.

--

[.offset]
+++[+++In a letter to another Friend upon the same subject, he writes:]

[.embedded-content-document.letter]
--

As to religious instruction, it consists, if I mistake not,
in bringing up children in that nurture and admonition which is of the Lord,
as says the Scripture.
Now, how can any bring up children in the Lord`'s nurture
and admonition--in the Lord`'s ordering,
in his counsel,
direction and teaching,--I say how can this be rightly and effectually done,
except the parent or teacher stand in this counsel himself,
and abide himself under this best direction?
how can he be instrumental to instruct, help, and lead forward,
if he be himself out of this counsel,--if he be not under the ordering
of that which is meek and lowly in the heart--of that pure principle,
which is said to lead into all truth, as it is heeded, waited on, and submitted unto,
in its simple silent instructions?
How needful it is for a master or a parent to be brought to see
that that which is to be known of God is manifested in man;
and that there is no really knowing the things of God,
but by his light and Spirit in the heart,--as said
an eminent minister and messenger of the gospel,
George Fox,--"`no knowing the Son, nor the Father,
but by the revelation of the Holy Spirit;
no knowing the Scriptures but by the same Holy Spirit,
that moved the holy men to give them forth; no calling Jesus, Lord,
but by the Holy Spirit; no true wisdom, but from above; no true receiving it,
but in the fear of the Lord; no true understanding of spiritual things,
but what Christ gives; and no true love to God, but what he shed abroad in the heart.`"

I firmly believe, that as the deficiency complained of in our children,
chiefly arises from a lack of true living Christian concern in
the minds of parents and masters for their religious welfare,
so they ought not to be put upon, or to put themselves upon any contrivances,
which best wisdom does not lead them into, and control them in the use of;
but they must come to that,
which alone can quicken and raise up in them a living
concern for the religious welfare of their charge;
and they must yield themselves as obedient children to its teachings.
Thus will they come to know something of an establishment in the Truth,
and a growth in living experience and substantial
knowledge of the principles and precepts of the gospel,
which is the power of God.
Thus furnished, thus fitted to take the charge of youth, under a sense of duty,
and above all inferior views, the master will be a blessing to his little ones.
He will need no catechism to instruct them in, no creed to examine them by;
he will not think of making them give confession of their faith;
but his watchful eye will be continually over them for good,
his patient exercise will be great on their account,
his prayers will go up acceptably for them, not as a matter of habit,
but as it is put into his heart by his heavenly Master,
who knows what he has need of before he asks.
Opportunities will often occur of giving them counsel or reproof,
of opening and explaining the Scriptures of Truth,
of informing them respecting our religious testimonies and principles; but above all,
of directing them to turn and keep their minds inward
towards God,--showing them the place of true waiting,
the source of true wisdom,
and both by precept and example,--as was conspicuous among our early Friends.
Oh, here is the truly religious instruction;
a bringing up young people in the fear of the Lord, and in his new covenant of life;
wherein it is said,
all are to be taught of Him,--all are to know him from the least to the greatest:
and here is a building up in the true faith, of which the Lord, not man,
is the author and the finisher.

[.signed-section-closing]
Your affectionate Friend,

[.signed-section-signature]
J+++.+++ B.

--

1818, Tenth Month 11th.--I have of late put but little to paper by way of remark,
as to the state of my mind, not having felt much freedom this way;
yet I may here acknowledge, that the same Power,
that has all along helped and sustained me, is not, nor has been,
lacking in the needful hour; of which the Lord is the best judge,
and not I. My feeble cry is yet unto him under all
my discouragements and exercising seasons.
The little lowly tender seed, which he has quickened, and in measure raised in me,
does still look unto its Parent for daily sustenance; his ear is ever open,
unto the cry of his poor;
and his eye of pity and compassion is still upon that birth which is of him,
to cherish and to care for it, and to provide all things needful.
Oh, for the continuance of his fatherly goodness,
and for the renewed extension of his preserving arm of power around me;
that so I may be restrained thereby from all hurt
and harm through this vale of tears and temptations,
and sustained by the same through all the depths of affliction,
into which he may see it best for me to be plunged, for my purification and peace.
My heart is much tendered and impressed, while writing these lines;
for indeed I am not able sufficiently to mention
how good the Master is,--how worthy to be glorified,
trusted in, obeyed, and loved, by all his servants and children.

1818, Tenth Month 15th.--I thought I felt the tender mercies of the Most High,
renewedly extended at this time, to my great joy and refreshment;
and that I could scarcely forbear thus taking notice or making mention of the same,
from present feelings and impressions; which have not been self-kindled,
but have arisen very sweetly and prevailed in my mind,
during this season of retirement by my bedside:
as also from the close language of a favoured messenger
of the Lord at a late meeting for worship,
which has been sealed to me forcibly.
From these concurrent testimonies, I am induced to believe, that the visitations,
the tender calls, and merciful dealings, and withdrawings, and provings, and refinings,
which I have experienced from time to time,
ever since the Lord was pleased to awaken me out of the sleep of death,
and to raise me out of the darkness of sin,--are mercifully
intended to purify and to perfect his gracious work in me,
and to bring about his design respecting me; which I believe to be,
to raise me up a living instrument and chosen vessel in
his holy hand,--to show forth the glory of his name,
(which is his power,) to the sons of men,--to exalt his eternal truth, and lead others,
by prevailing with them to submit themselves to this power revealed in them;
that so they may live under its influence, know this eternal truth in and for themselves,
abide under its teachings, and come to witness an establishment therein,
and to have an inheritance thereby in that, which death cannot destroy,
nor corruption mar, nor sin defile, but which endures forever!
Amen!

1818, Tenth Month 19th.--Oh, the sweet influx of the Father`'s peace,
of the Father`'s joy and comfort,
with which he is pleased at times to refresh and revive the hearts of his humbled
contrited ones,--those that are through his mercy prevailed upon,
and through his heavenly help and strength enabled to count all things but as nothing,
that they may be found in him, and to suffer for his name`'s sake the loss of all things!
Oh, what a blessed evidence of his continued goodness
have I been favoured with this morning,
during the short space of a few minutes,
in my retirement to seek the lifting up of the light of his countenance,
and to wait for the shedding abroad of his love in my heart.
What encouragement does it afford me, to continue steadfastly looking unto Him,
the author of all my blessings, the director of all my footsteps,
the restorer of right paths to walk in.
What assurance have I had renewed at this season,
that I am (through his daily help and strength) in the way of his leadings;
so that in a fresh feeling of his directing and protecting
power being about me for my preservation on every hand,
I may boldly say with the Psalmist,--"`Though a host should encamp against me,
my heart shall not fear,`" the Lord being "`my light and my salvation.`"

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Twelfth Month 21st, 1818.

I have often thought +++_______+++ to be,
what our early Friends would have called a "`tender-spirited
young man;`" but Oh, how much must such go through,
who have been made willing to come to the Master, in the full belief that he is the Way,
the Truth, and the Life.
The Master looking upon such, loves them; yet must these give up their all,
as and when he calls for all or any of their "`great possessions.`"
We read that Zion was to be redeemed with judgment;
and with the spirit of judgment and of burning was her filth to be purged away.
Oh, this fiery baptism! few of us know enough the
necessity of it;--it is hard coming under it,
it is hard keeping under it:--then and not until then,
do we really know the full import of these deep expressions,--"`baptized
into his death,`"--"`planted in the likeness of his death,`"--"`crucified with him,`"
"`that I might, (as the apostle says) know Him, and the power of his resurrection,
and the fellowship of his sufferings, being made conformable to his death.`"
There is, as you know, a refiner`'s fire;
where the things that are even the most precious, the most pure metal,
the most fine gold, are to be put in, and to be again and again melted down and softened,
and rendered susceptible of the impression that it is designed to receive:
it must be passive as the clay; it cannot impress itself.
No more can we as creatures humble ourselves (truly and
acceptably and profitably) in or by our own will or way,
or by the voluntary exertion of any parts or powers of our own;
no,--we must not choose our own way of being good,
neither do good according to our conceits and conceivings,
else another thing is exalted in reality, than the principle and power of Truth.
I have been often instructed very deeply by these
expressions;--"`but we have this treasure (that is,
the Light shining in our hearts) in earthen vessels;
that the excellency of the power may be of God,
and not of us;`"--"`always bearing about in the body the dying of the Lord Jesus,
that the life also of Jesus might be made manifest in our body.`"
I think Penington says, that we are but vessels,
wherein the pure excellent oil may appear or disappear; and some one says,
these vessels must be emptied, before they can be cleansed from any dirt or sediment,
which they may have contracted while in use in this filthy world.
I remember John Churchman wrote,
that the vessels in the potter`'s house were to be set on the shelf to dry,
after they had been formed on the wheel; and then to be baked in the fire.

These things I write to you, dear +++_______+++, as they occur;
much more of this nature often passes through me,
unsought and unstudied in times of retirement,
which are seasons of refreshment to me oftentimes; and in them, I think,
I have learnt more effectually, and been strengthened more availingly,
than in any other way:
and though speaking of +++_______+++ seemed at first the occasion of them,
yet it is not for me to cast a stone;
though from the very little experience which I have had of these things,
I begin to see the necessity, and somewhat of the beauty of those deep baptisms,
and desire greatly that dear +++_______+++ may bear me company in coming
and keeping under them,--this being the true way of the cross.
For a cross that bears any marks of being our own manufacture will never do,
so at least I have been favoured clearly to see; it is no cross at all in reality.
The mind is a very active busy part;
and if it be any time quickened into a sensibility and admiration of what is excellent,
unless kept down in the true subjection by that which quickened it,
it will speedily put itself forth and rush into such actions, or words, or thoughts,
as it apprehends to be of a good tendency or nature,
and is very ready to hope and believe that these things are required;
forgetting that that which quickens in us the first spark of good,
and raises up the least desire after it,
the very same must preside over all our steppings,
the last equally with the first stepping;
the very same must strengthen us to choose the good and to follow it,
which gives us ability to refuse and shun the evil.
In this way self is cast out, and the principle and power of Truth alone exalted,
and then the seed reigns and is over all, as George Fox says; for that is to govern,
guide and go before, in this gospel day, and that is to lead;
and when it stops we are to stop and stand still, and when it goes forward,
we are to move with it and in it, as Israelites indeed.

--

1818, Twelfth Month 27th.--At this time it lay upon me to set up my Ebenezer,
as decidedly as this perishable method with paper and ink,
and this feeble representation by words,
(which are at best but inadequate symbols) will allow of.
My soul has been hitherto helped by the immediate handing forth of that power, wisdom,
support and indescribable consolation,
which comes from the holy sanctuary of the Most High.
My heart has been sweetly engaged at seasons to praise, honour, and glorify Him,
who lifts up the poor out of the very dung-hill, setting them among princes: verily,
He gives power to the faint, "`and to those that have no might, He increases strength.`"
And this is He, who was called the God of Abraham, and of Isaac, and of Jacob;
and who continues to be to all His living Israel in this day, as He ever was in old time.
For the devil is the god of the dead in trespasses and sins;
but the Lord has bruised his head by his seed, Christ Jesus,
who has purchased life for those that are willing to be made partakers thereof.

1818,
Twelfth Month 30th.--O Lord! if David your servant did say of the
love that prevailed between his fellow servant Jonathan and himself,
that it was "`wonderful,`"--if we may also say of those whom you have
knit and bound up together with us in the fellowship of your Gospel,
that they are as nursing fathers and nursing mothers,
as endeared brothers and sisters in your Truth;--O Father Almighty! how
shall we sufficiently commemorate your lovingkindness towards us,
your poor creatures; whom you have been pleased to gather into the heavenly relationship,
into the joyous fellowship, into the blessed flock of your family,
and have deigned to acknowledge as your children.
I thought I felt the sceptre of your paternal love stretched out,
renewedly inviting me to partake of the blessing that makes truly rich,
and adds no sorrow therewith,--inviting me to draw near, and to make my request unto you,
and to plead with you in the power of your love; into which you have gathered me,
and by which you may be prevailed with.
I am enboldened to ask of you at this season the
continuance of your holy help from time to time,
under all the provings and afflictions and chastenings,
which may in your wisdom be allotted me.
As all your servants of old, even unto this day, have shared in the cup of bitterness,
and partaken of the water of affliction, so Oh, Lord, may I also endure chastening,
and partake of the evidence of sonship; remembering the language of your servant,
"`If we suffer with Christ, we shall also reign with him.`"
This accept and grant, if it please you, Oh, my Father;
who have never yet denied that which you have put into my
heart to offer unto you in the prayer of faith:
and if I need at any hour any thing of you, I know that you hear me and are with me,
while I abide with you, and am in submission to your manifested will.
To you, therefore,
I desire at this time afresh to commend and commit all that I have or am,
and increasingly to become your child.

1818, Twelfth Month.--Does the best qualification,
even that which the true ministers have fresh from
the fountain of all-sufficient wisdom and strength,
even the aid and influence of the Holy Spirit, need any human help to bear it out,
or to assist the true ministers in the discharge of their gifts?
If human acquirements be of use, and helpful to those that have best help,
or advantageous to the cause they espouse, then the lack of it is a deficiency; that is,
the instrument is not of that service that he might be, if he had learning.
And therefore the apostles,
if they had had a good education would have been more extensively useful,
especially among the rulers and great people.
Why did not the apostle Paul, who had much learning,
and "`man`'s wisdom,`" use it in his preaching among the learned Corinthians?
and why did he determine to lay it all aside, and to know nothing among them,
save Jesus Christ and him crucified?
Why did Paul, in speaking of the things of God,
speak then "`not in the words which man`'s wisdom teaches,
but which the Holy Spirit teaches;`"--if his learning was beneficial to him as a preacher?
Was not his learning one of those things, which before was "`gain`" to him,
a profitable and advantageous thing, and which now he "`counted loss for Christ?`"
Why did our God choose foolish, weak, base, despised things, as his instruments; if wise,
mighty, honourable ones would have been more extensively useful,
as long as they were humble?
Why did Paul come among those of
Corinth "`not with excellency of speech or of wisdom?`" surely on this ground,
would he have gained more converts to the Truth in that place?

[.embedded-content-document.letter]
--

[.letter-heading]
To a person under convincement of our religious principles.

[.signed-section-context-open]
25th First Month, 1819.

When the Master sent forth his chosen ones to do
the work which he had appointed for them,
he said, "`Behold, I send you forth as sheep in the midst of wolves;
be therefore wise as serpents, and harmless as doves.`"
These few words of Scripture sprung up so forcibly in my mind,
in the midst of no little anxiety for your real welfare,
and sympathy with you under your various and peculiar trials,--that
it appeared right for me to convey them in this way,
and to relieve myself of some weight of solicitude on your account;
earnestly desiring that this little stepping-stone, thrown in your way,
may not in any sense prove a stumbling-stone, hurtful instead of helpful.
First then, and first and last, I would direct your attention to the Comforter,
the heavenly Instructor, the Spirit of Truth; under whose precious teachings,
I am persuaded you have been already brought, and so,
in that measure most profitable for you at present, are partaking of the refreshment,
peace, joy, faith, hope, strength, and holy fortitude and wisdom,
which are richly in store for all such as submit themselves to its guidance.
The apostle John directed the minds of those whom he addressed,
to the anointing which they had from the Holy One,
whereby they "`knew all things`" necessary to their growth in grace.

Though I know but little of you in an outward sense, yet I am persuaded,
that the hand of the Lord is truly upon you; and greatly do I crave,
that your continual care and caution may be, to keep close to this anointing.
That which anoints is Truth, the Spirit of Truth, the Power of Truth:
this is what secretly works upon the soul, bruises our self-confidence,
breaks our false peace, awakens out of our dreams of pleasure, riches,
honour and acquirements, shows us our real state, where we are,
how far we have missed the road, whether in principle or practice,
and clearly points the way to true and everlasting peace;--giving
us also such full directions that we cannot possibly miss of it,
if we do but follow them, and not our own reasonings and imaginations.
What holy invincible armour does our great Captain clothe his little
striplings with,--those that are after his own heart,
as young David was,--those that lay aside all their
own or other people`'s weapons and strength,
laying hold only of the hope set before them.
May your desire be unto your Lord, that He may furnish you with the sling,
and give you the smooth stone, as you are in the way to meet your enemy;
and may your true dependence be, yet more than ever you have known it to be,
immoveably fixed on your Rock, your Redeemer:
and do not let the enemy put you on any improper leaning on books or men,
but lean upon Jesus, as all his beloved disciples ever have done.
Oh, it is a safe spot to be sitting at the feet of Jesus,
rather than at the feet of Gamaliel;
and be not cumbered about many things,--remember one thing is needful;
and this one thing is a learning of Him who is meek and lowly in
heart,--that true learning which is not merely a hearing,
but a doing also his sayings;
who speaks with such authority and power in the secret of the soul,
as to make us cry out, "`He told me all that ever I did;`" is not this the Christ within,
the teacher, who it was said should never be removed into a corner,
as the Gospel-day prevailed?
There is indeed a leaving the pitcher of water, and going our way into the city,
to proclaim to others, by our life and conduct, the name or power of Christ,
as he has been pleased to manifest himself unto us, opening in us the well of water,
which springs up into everlasting life.
But how seldom,
(as Fenelon expresses it,) does the soul keep silent enough to hear His voice,
who speaks as never man spoke;
how seldom are we simple enough to follow him whithersoever he leads;
and when persecution or affliction arises because of the word nigh in the heart,
by and by we are offended or afraid;--forsaking our leader,
when he leads in the straight and narrow way of the cross; and denying him,
in whose name we may have done even some mighty works,--saying with poor Peter,
"`I know not the man.`"

There is, as you well know, a going before our guide,
a kindling of sparks and warming ourselves at them,
an offering of sacrifice before the prophet come;
and Oh, what burdens have the upright in heart at times made hereby;
what a "`lying down in sorrow,`"--what a close rebuke
from our great prophet and high priest,
"`You have done foolishly.`"
We may remember Saul said, "`the Philistines will come down upon me,
and I have not made supplication to the Lord;`" and he waited seven days for Samuel,
and the people were scattered from him and trembled for fear of the enemy.
Oh, here was an offering of something good, in the time and will of the creature;
but it was not counted good nor accepted,
because it was not prepared of the Lord`'s prophet, neither offered in faith,
but in faithless fear.

Truly I say not these things to cast any thing like discouragement in your way,
but rather as an encouragement for you to look up for help,
to steer clear of all things that would hurt or hinder your steady
progress and inward growth downward in the root and life of religion.
Be not very anxious about making fruits appear:
if you are chiefly seeking to be grafted into the true vine,
the precious fruits of that righteousness, which He is the author of,
will not be lacking in their season.
But there is a winter, when not a leaf appears;
insomuch that a superficial observer would say, What good comes of this graft?
Of what use has religion been to him?
Yet the husbandman knows the times and the seasons,
and that if even a bud were to be put forth, it would be struck by the frost.
Oh, there is a time to be empty, to be stripped, to be poor,
to be buffeted by the wintry winds, to be deprived of all sense of life, any relish for,
or savour of good: and then I have found it safe to lie low in the littleness,
in patient poverty, in the true insignificance:--waiting in the abandonment of self,
in the silence of all flesh, for His re-appearing,
"`in whose presence there is fulness of joy`" and abundance of consolation,
says my soul from undoubted experience.
Then wait in the filial fear, in the living faith,
though it seem small as the grain of mustard-seed, though it may lie very low: wait thus,
I say, upon the Lord; occupy with this your talent;
it is enough for your present needs,--the master knows what things you have need of,
before you ask for the food and raiment, even the daily bread, the wine of the kingdom.
He will not withhold the oil and the wine from your wounds or weaknesses;
neither do you know how much he has in store for you,
as you follow him in the way of his leadings in faith and faithfulness.
Keep not back part of the price--part of the inheritance
which you did inherit from your fallen father Adam,
and earnest into possession of by actual transgression; but give up all,
that you may be clothed as his lilies are, with his innocence,
not with your own righteousnesses, which are but as filthy rags.
Be wise then as a serpent; be wiser than the serpent that beguiles,
that lies in wait sometimes as an angel of light, to deceive the hearts of the simple.
He suits his baits with much artful wisdom,
according to the state and temper of mind in which he finds people.
Do they love what is good?
he is ready with an appearance or resemblance of good to entice them:
and how can any discover his deceits, or keep out of his snares,
but as they come to that which alone can give the true discernment.
What is that which enables us at any time to distinguish between the good and the evil,
to choose the one and to refuse the other, though ever so much gilded?
It is the true wisdom, of which Solomon wrote in his Proverbs,
which preserves out of the snares of death.
How clear, how intelligible is her voice, in and unto the awakened upright soul;
this word of wisdom is nigh you,
as you already know,--you need not go far away to find it,
you need not mind the "`Lo, here`'s`" and "`Lo, there`'s`"--the kingdom is within,
the king`'s laws are written in the heart.
Receive not then for doctrines the commandments of men:
try all things by this infallible touchstone, which never yet led any into error,
but out of all error "`into all truth.`"

And when you are examined concerning those principles or practices,
into which the Truth has led you,
and which nothing short of the same (I trust,) has
given you strength to profess before men,
be not dismayed, be not discouraged, be not disturbed; let the Truth plead for you,
"`for it is not you that speak;`" nor can you by any ability
short of that which the Lord gives in the very hour of need,
do any thing availingly in support of the great cause.
Remember those faithful valiants who replied to the king (Nebuchadnezzar,) "`We are
not careful to answer you in this matter:`" and remember how our great Master was silent,
and as one dumb before his accusers,
though Pilate put a very short question to him,--"`What is truth?`"
yet we read not of any answer being given,
to feed the subtle ensnaring wisdom in him who made the inquiry.

I desire for you an increase of the true strength and stability;
and that is to be had by daily waiting on the Lord in the closet of the heart.
A humble weighty deportment shows forth and best upholds
the dignity and beauty of the Christian religion;
it becomes and adorns the gospel.
A retired, calm, and watchful frame of mind is, in many respects,
a hedge and preservation about us, when thrown among those,
who are not acquainted with our high profession of
a principle of Truth sown in every heart as a seed;
which is truly the grace of God that appears unto and in all men,
leading them out of all evil into all good.
We have perhaps but few examples of what this heavenly influence would do,
for those who are passive as the clay under the potter`'s hand.
Look not out at the example of others, so as to stop short where they do;
look rather to your Master, and follow with a simple, submissive, grateful spirit,
all his secret intimations, wheresoever He leads; follow such only as they follow Him,
not by imitation but conviction;
for there are many services and sacrifices into which others are led,
which possibly you may never be called upon to evince
your love for the Truth by engaging in;
and some requirings may not be called for at your hand,
in the same way or time as they were at the hand of others:
it is also possible you may have a narrower path
than any brother or sister that you know of.
Keep then "`your eye single`" to the light of Christ;
let that lead you whithersoever and whensoever it will:
then only is the language of the heart, "`Your will be done, O Lord,
in and by and through this poor earthly vessel.`"
Then only do we availingly know and feel the blood of Jesus, the Mediator,
to cleanse from all sin, while we "`walk in the light, as God is in the light.`"
For it is not the outward name of Jesus, but his power revealed in us,
changing our hearts, that saves;
neither is it a historical faith alone in what the Saviour did for us while on earth,
that will avail any thing; for if we reject him as our sanctifier,
none of us can truly know him to be our sacrifice,
(as William Penn wrote.) We read that the very devils
could acknowledge that Jesus was the Christ:
yet they did not submit to his government, but rebelled against him,
or they would not have been fallen angels.
There are many that can talk about the atonement, the intercession, the justification,
the redemption of Christ,
and about baptism and the communion and heavenly
union between the saints and the King of saints,
who nevertheless confess they are "`miserable sinners,
bound and tied by the chains of their sins,`"--notwithstanding it is written,
"`let him that names the name of Christ depart from iniquity.`"

My desire is for you, and for all men,
that they may come to the true and saving knowledge of God and our Saviour;
which is only to be attained unto,
through obedience to the manifestations of his Spirit in the heart,
"`given to every one to profit withal;`" without which none can fear him acceptably,
or have true faith in his Son: for the things of God knows no man,
but by his Holy Spirit.

Farewell; keep to the Truth, and it will keep you.
Remember, "`He that dwells in the secret place of the Most High,
shall abide under the shadow of the Almighty.`"

[.signed-section-signature]
J+++.+++ B.

--

1819, First Month 29th.--This may I say, and leave upon record,
that though many almost indescribable temptations and presentations
of evil have been permitted to come about me,
sometimes like a mighty flood, so that in hours of extreme weakness and infirmity,
I have been many and many a time ready to give up the fight of faith;--yet to this day,
the Lord strong and mighty, the Lord mighty in battle,
has been pleased in his abundant compassion to encamp around me,
and to give me songs of deliverance, songs of triumph and of praise.
In his name will I set up my banner;
who is a Rock of defence and sure refuge to my poor weary soul
in all her afflictions as there is a concern to flee unto,
abide in, and under the shadow of this mighty rock in a weary land.
Oh, young man or young woman, to whom this may come,--my friend, my brother,
my sister;--who are seeking the better country, and Him who is the way, and the guide;
Oh, though you be weary and heavy laden,--take courage!
Oh, there is a staff, a stay, and strength and succour with Him and in Him,
who has gone before; and who leads on his little ones gently and sweetly,
as they are able to follow.
Take this as the counsel of one, who writes from a sure and living experience,
and who has indubitably known His name (which is
above every name,) to be a strong tower indeed.
He will be with his, even to the end of the world.
