== Chapter IX.

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Dear 3rd of Second month, 1819.

I have often believed that the blessing in store for those who hand "`the
cup of cold water,`" may not pass from you and yours,
as you are yet concerned to struggle on in the narrow way.
I desire to be your companion therein,
and an example in giving up faithfully to all that is set before me,
whether in the line of doing, or of suffering;
who am often sensible of something still blotting out and
wiping away many a spot contracted through unwatchfulness.

There is a very precious feeling that seems to prevail with me, while saying thus much;
and I may add, that though nearly day by day bowed down and broken,
under a view of the low state of things at home (in the heart) and abroad,
and of many sacrifices for the cause which are called for at my hand;
yet I may acknowledge that showers of refreshing help and strength have descended,
so that the encouragement is great for me and you and all, yet to struggle on;
laying aside that which hinders.
From your affectionate friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Fifth month 4th, 1819.

I have sometimes remembered the language or sentiment of a tried servant, who,
by being resigned to the Divine will through the tribulations that were in wisdom handed,
was enabled to comfort a brother in words like these; '`if we be but clean vessels,
no matter how empty;`' and I may add,
'`no matter how long on the shelf,`' and as one says,
like '`a pitcher placed upside down, on its mouth,`'--to keep the dust out.
The only danger I have found, when counted worthy,
or clean enough to be set in this trying position,
has been that of repining at the dispensation allotted,
or not quietly seeking after acquiescence.
If we were but willing to abide the operation of the Almighty hand,
which would make all of us vessels fit for a place in his holy temple,
and a service in the Lord`'s house;
and were but enough sensible of the benefit of these turnings and overturnings,
and of the blessing that they are to those that are patient enough to profit by them;
surely some of us who are now ready at seasons to give over struggling,
and to think it is to no purpose endeavoring to
hold out in faith and faithfulness any longer,
(presuming the Lord has forgotten us,) would rejoice
that we are counted worthy to drink of the cup,
and to be baptized with the baptism,
which alone can purify and prepare for a seat in the heavenly kingdom.
"`It shall be given to those for whom it is prepared,`"--
"`I go to prepare a place for you;`"--and did He not go through suffering;
--was He not said to be made
perfect through the same;--and shall we find a safer path than in His footsteps,
"`who endured the cross and despised the shame.`"
Some in this day of great profession and performance,
have to be renewedly baptized into a deep sense of the state of things,
both without and within;
and to labor earnestly after the pure and unshackled
arisings of the seed,--which is often very low,
and burdened with much that seems to be favorable, but yet greatly oppresses.

I desire for you, dear J.,
that you may not be without your full appointed share of such conflict of spirit,
and even apparent desertion of heavenly help and strength, as is best for you;
and that you may have the grain of faith renewed day by day, the hidden manna,
the secret sustenance which enables quietly to wait and patiently to hope,
even through all things:
so that if these dispensations should be in judgment or in mercy,
you may be favored through submission, to rise above all that has stood in the way,
steadily persevering in a course of humble, dependent, watchful, innocent conduct.
I believe that marriage is often made a means of furthering the religious growth,
and strengthening the mind in that which is good,
as we look to the Lord in our proceedings, having him in our eye,
above and before all idols.
But few measures taken in life, perhaps, are so likely to entrap the unwary,
as an injudicious engagement therein;
it unsettles and uncenters the mind from the great first object,
if much care be not exercised, and diligent watchfulness maintained.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. S.

[.signed-section-context-open]
Seventh month 22nd, 1819.

The examination of religious tracts proposed to be printed, is a weighty service.
If it were only to judge of words,
the consistency of the sense and meaning with the principles which we profess,
as far as human wisdom can distinguish, this would be easy,
and could be compassed by the spirit of a man:
"`but the things of God knows no man, but the Spirit of God;`"
so that man`'s spirit is unequal to it,
but must be in subjection,
with all the vain reasonings which he can muster up and
contrive by the natural powers of his understanding,
or by his acquired learning and erudition;
and he must wait to feel that raised up in him,
which is able rightly to discern and comprehend the precious,
and to distinguish it from the vile.

I believe a time may come, when the writings of many of our early members,
who shone brightly in their generation, may again rise into universal repute among us,
and also among others;
notwithstanding the unfashionable garb in which many of these writings are clothed,
so unsuitable (apparently) for these times.
So that one would like to see the avenues kept open, and the channels clear,
and the conduits clean; that whatever is to flow in the ordering of best Wisdom,
may flow freely.

As to what you say of the fear of some, about the style of our early Friends`' writings,
I think this fear is a weakness,
and proceeds from a sort of doubting in the mind about the writings themselves,
and not merely about the language.
I would ask these fearful ones,
whether in reading a peculiarly interesting history or travel,
the subject of it does not carry them above the style, so that almost any style,
however prosy and dull, is overlooked;
and this is the case tenfold more strongly with
the humble seeking soul in religious matters,
by whom the words are overlooked in the earnest desires after the substance.
Those who are admirers of words, whether they be words printed or words preached,
are very unlikely to be benefited really and truly by either,
having gone from that which is beyond words, and which alone can make words effectual.

--

Sixth month 5th.--Great have been my temptations: yet abundantly manifest through all,
have been the out-stretchings of the ancient and eternal arm of power:
so that to this hour, it is alone through the Lord`'s eminent mercy and long suffering,
and by his preserving strength and help daily extended toward me,
that I am yet alive in Him, and able to celebrate his name, and seek his face,
and wait for the fresh arisings of his holy heavenly virtue;
by which alone I can do any thing acceptably for
his great and glorious cause in the earth,
or be his dutiful and faithful son and servant.

Date uncertain.--O holy blessed Father! your love shed abroad in the heart,
your sweet refreshing influence, can make up for all your softening,
healing balm makes us forget our wounds and weeping.
O! how good you are to those who still struggle after resignation,
and sigh after submission to your holy will Though they fall many times,
yet how is your strength manifested for their recovery and relief,
for the renovation of their faith and courage;
so that all their transgressions are blotted out, and their unfaithfulness is wiped away.
This is precious indeed--to feel access to the fountain set open for sin and iniquity;
and thus to be brought nigh by the blood of the Lamb, and to feel its cleansing virtue.

Seventh month 15th.--O my Father! how precious is your love to my soul at this time,
and the manifestation of your life-giving presence, in and unto my poor tabernacle!
How has the sweetening,
sustaining influence of your pure and Holy Spirit refreshed and
animated my inward man!--how has it even invigorated the frail and
slender frame of this perishable body! so that you have,
at this season, prevailed upon and reduced into true passiveness,
everything that is within me; and I am renewedly prepared,
to offer unto you all that I have, or am; and can say,
in the ability which you give,--'`I am yours, and you,
blessed Lord God of power and of everlasting praise and of mercies infinite,
are mine;`' I live by you, and know, and love, and glorify you and your Son, the Lamb,
Jesus my Savior, through the eternal Spirit; praises, praises to your name forevermore.
Amen.

_Written in a grove at Knapton, in Yorkshire._

[.small-break]
'''

Eighth month 25th.--O! You that see in secret, that know all things,
that searches the hearts, and tries the inward parts of all men,
and in whose pure sight iniquity is discerned and judged,
may it please you yet once again to regard and pity your frail and faultering servant;
who am not worthy to be accounted of your household; and yet cannot rest satisfied,
in any thing short of a pure and perfect surrender and
sacrifice of my all unto your service.

Your presence, your purifying,
preserving energy and virtue inwardly communicated to my soul,--how has it helped
me along in my earthly pilgrimage,--how has it sustained me in the year of drought,
and in the hour of temptation and of trial!
In all the depths into which I have been, and may be, cast or permitted to be plunged.
Lord! you know that nothing has been able, or I trust shall be able,
to induce me to deny, that you have blessed me and done me good.
Though you slay me, yet will I endeavor after resignation and submission; for,
without you what am I? O my Father! is there yet a door of hope for me,
yet a little access left for me, before I go hence, and of men am seen no more?
May I presume to plead with you for forgiveness and pardon,
who am unworthy to hope for it;
having so often transgressed and offended by unfaithfulness and many backslidings.

_Written in a wood at Yealand, near Lancaster._

[.small-break]
'''

Ninth month 5th. (First-day.)--What a mixed race we are,
even the brightest and best,--what a dwarfish set:--it is most
true indeed that we have not attained to the stature,
strength, or standing of our fathers.
Yet oh! how bright in the horizon was the opening,
the breaking forth of the morning of the day of the Lord`'s everlasting power!
Verily his hand is not shortened,
the glory of his excellency and of his strength will yet be manifested more and more;
he will beautify his holy Church and peculiar people, and brighten up his jewels;
and they shall shine as the stars forever and ever.
And many nations shall flow together, and become one fold on his holy mount; and he,
the Shepherd, shall feed and lead them; and they shall lie down in his green pastures,
and drink of the pure river of his satisfying pleasures:
and as they abide where he would have them, nothing shall harm them,
nor any iniquity prevail against them; and they shall never perish,
neither shall any pluck them out of his holy hand.

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel Alexander.

[.signed-section-context-open]
21st Tenth month, 1819.

I omitted to mention our quarterly meeting: it was held to satisfaction.
It is lamentable to think how much harm is done,
by the talkativeness that sometimes manifests itself after such very solemn occasions;
and in meetings for discipline, there are those,
who knowing much of the outward rules which Truth has led our Society to adopt,
are not sufficiently careful to act in the life, in the liberty, in the sweetness,
in the dignity of it; but allow their mere adherence to rules,
without subjection to the power in which they were set up, to mar at times the beauty,
the benefit, and the glory of these meetings; which should be religious meetings,
and would often be made meetings of worship, to those whose minds are rightly engaged.
Surely the authority of these meetings is not the mere Book of Extracts;
nor does their excellency consist in a mere mechanical
compliance with what is there laid down;
nor does much talking in favor of any point, prove that the sense of Truth is that way,
though it may prove that the sense of the majority leans so.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
London, Eleventh month 6th, 1819.

My dear love has often been as fresh and warm towards you,
amidst much sympathy and solicitude on your account as on my own,
that we might both be preserved by the invisible,
invincible power and principle of Truth, through our patient seeking after, waiting for,
and following its pure and sure guidance: amidst earnest desires that this may be your,
and also my, experience,
it has not seemed unpleasant nor unexpected that little
should hitherto have passed between us in this way,
which true friends have found and do yet find to be but a feeble channel,
though profitable and comforting,
when the reader can discern and read the language of the heart of his friend.

It is a certain axiom,
though a strange paradox to such as have not yet come
to witness the truth of it in their own experience,
that the true silence speaks louder than the best words.
I sometimes think that I, for one,
have enough to do to steer my own frail vessel in the stormy sea of life,
with the aid afforded;
being willing often to leave others to the like engagement for themselves.
For one finds it is a good thing to mind one`'s own business,--to
endeavor to rule one`'s own little house well in the first place;
then will there be the better qualification to have charge over the house of the Lord;
and this latter is a duty, which all will find, in some way or other,
in due season to devolve upon them, if they are faithful, and as they through obedience,
come into a capacity for usefulness.
The useless members are to be cut off,--no,
they drop off as a withered bough that receives not the sap of life.
As soon as any have grown to the stature and strength for labor,
they are undoubtedly put out to service, and earn their livelihood,
even that which nourishes to life, and liveliness,
and healthfulness,--even the heavenly bread.

And every son and daughter are to mind that portion of work,
which is set them by their parent to do in his family; and they are to do nothing else,
but to attend thereto cheerfully,
handling the tools and implements that he supplies them with,
and at the seasons of his appointment.

To these diligent day laborers, the times of refreshment indeed come,
when it is seen to be needful,--in order that they faint not.
But in the Lord`'s family, those that will not work, must not eat, nor sit at his table,
nor have their penny of peace, nor the reward of "`well done.`"
The domestic economy here exercised, and the excellent discipline kept up,
and the comely order and beautiful harmony of
all the true members of this spiritual house,
I have seen and known to be wonderful in all its bearings and branches:
but those that are not of it, cry out,
"`He is a hard master;`" and would exact the uttermost farthing.
Yes, He is a hard master to the rebellious,
and terrible will they find Him in the reckoning day;
but very tender and pitiful is He found unto them, who are tender of His honor,
even before that day;
for they feel his unfailing mercy still blotting out and wiping away,
and extending afresh his hand of help,
to such as are willing to work out their own salvation with the true fear and trembling.
That you, my dear friend,
by diligent and close attention to none other than the Shepherd`'s voice,
and by a co-operation therewith,
even a simple subjection to that which it makes manifest to be the duty of each day,
may come to have this and much more verified with yet
greater satisfaction to you in your measure,
is often my desire.
The way of the Lord`'s coming, is even as a refiner with fire,
and a fuller with soap,--to melt, and to purify;
and blessed are they that so receive him.
Thus the house of Saul will become weaker and weaker,
and that of David stronger and stronger; though the latter may be hunted,
as the partridge on the mountains, for a long season, pursued yet escaping:
and the seed of David to this day,
have often to "`abide in the wilderness in the strong-holds`" and in the mountains,
and are ready sometimes to say, "`surely I shall one day fall by the hand of Saul.`"
This is a sore conflict, yet a glorious and honorable warfare;
and the victory is certain to all those that
hold out unto the end in faith and faithfulness.

I trust, my dear friend, that by this time many of your soul`'s enemies,
that have stalked their forty days like a Goliath, are laid low;
and that many of your doubts and fears, are in measure done away;
that with renewed vigor, courage, patience, and perseverance, you are journeying onward,
even with steady pace and simple eye;
not moved by the "`trial of cruel mockings,`" if that should be your lot;
nor yet dismayed by the many tribulations that are
permitted to attend the path of the righteous.
Yet I trust,
that an equal if not a greater degree of care and
caution will yet mark your every movement and stepping,
as you go along: I speak not of a silly slavish fear,
which keeps some far behind the footsteps of Christ and of his companions;
or of that weakness which would let the enfeebling reasoner prevail,
to the hindering or even stopping of a vigorous healthy growth.

Some have I known, who have permitted such an argument as this to nip their bud,
and so to check its putting forth, in the due and appointed season,
its natural blossoms and fruit; saying, '`others have professed great things,
and have come to nothing; who am I,
that I should pretend or presume so high? i Surely I shall disgrace the cause,`' etc.
Such reasonings are, as we abide in the light, clearly manifested to be of the enemy,
though greatly disguised: and he sometimes lays hold of good kind of people, who,
with upright intentions for the best,
and desiring our preservation from hurtful extremes,
are induced by a mistaken and blinded judgment,
to advise us against running risks (as they think,) by such a bold, firm,
and decided conduct, as we apprehend is required at our hands.
I have had to tread much alone; and I have found it safe,
and conducive to my true growth, to look mainly, and in the first place,
to that which is truly an infallible Teacher, and which leads out of all error and evil,
into all truth and goodness; and after sometimes great delay,
(not through willfulness or weariness,
but an upright desire to be led by nothing but the true guide,) I
have been made willing to resign myself to what has been cast up,
I trust with something of that singleness of heart and simplicity,
which the right thing does undoubtedly induce.
O! the comfort and divine consolation,
which such a procedure has drawn upon my poor soul,
even in the midst of much trouble and suffering.

The Truth does undoubtedly lead into a oneness in principle,
and even in practice as to generals: yet in regard to particular sacrifices and services,
very various are the allotments for each member of the church,--very
different are the gifts and dispensations which are meted out to each,
and the administrations of them also.
Blessed are those who know and keep their several places in the body,
always eyeing the Master, even the holy Head thereof.
These shall not be unduly moved by the revolutions and convulsions,
which may be permitted to arise, and to surprise the hypocrites, whether from within,
or from without;--these abide in their habitation and safe shelter during the storms,
nor are they supine and confident in the day of ease and of calm weather,
but are prepared,
no are (if it be best) forewarned often of the judgments that may be
impending or ready to be poured out upon the head of the disobedient.

Well, my dear friend, be valiant for the Lord and his precious Truth,
while you have a day in mercy granted you;
joyfully and unreservedly yield yourself and all that you have unto his disposal.
Keep to the root of righteousness; and as the divine sap of life is permitted to ascend,
and to circulate in and through your soul, you shall in due season be clothed,
or be strengthened to put on the excellent fruits of righteousness,
to the praise of Him who has chosen and ordained us,
that we should go and bring forth much fruit, and that our fruit should remain;
and who is ready thoroughly to furnish us unto every good word and work required of us.
Farewell, and believe me to be your affectionate friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Falmouth, 17th of Twelfth month, 1819.

[.salutation]
Dear +++_______+++,

My dear love is to you, though from a low spot,
which has more or less been my experience of late: but I can truly say,
in the lowest seasons I have longed for nothing
more than for preservation through all things;
even though there should be but little going forward,
or any vigorous growth in that which is good.
Yet should I be content in this the Lord`'s will, who does all things well,
could I find an assurance, that _finally_ the eternal rest of the righteous might be mine;
and that while buffeted and tempted here,
no reproach might be reasonably thrown on the blessed Truth,
through any unfaithfulness of mine.

A degree of sweet calmness seems to arise, while writing to you;
in which I feel you near to me, and myself still bound in a degree of tender love,
and refreshing fellowship unto the faithful everywhere.
At such seasons,
how strongly does the sentiment recur,--testimonies are
nothing comparatively,--words are nothing--outward,
perishable, changeable things are nothing;--but to know our sustenance, standing,
strength, and life, to be in the only unfailing Source,
and to feel that which is immortal,
invincible and unchangeable to bear up our minds above the billows;
this is worth living for, and suffering for, and dying for.

--

[.offset]
+++[+++In a letter to a friend, dated the 6th of first month, 1820,
speaking of drawing up accounts for Piety Promoted,
which he had diligently taken in hand as a duty ever since the year 1817,
also collecting and copying letters of Friends,--he says:--]

[.embedded-content-document.letter]
--

If these labors of love for the cause`'s sake should ever come to much,
or be made of extended utility,--if they be rightly carried forward
and introduced to public view,--I trust I shall rejoice,
whoever may have it laid upon him to undertake this part of the business.

It is enough for me, quietly to devote myself to the accomplishment of such share,
in laying the foundation and erecting the scaffolding, as seems required at my hands;
leaving the completion thereof to the disposal of the master-builder,
who knows the several abilities of his workmen,
and portions out their duty according to their day and
strength:--He knows how comparatively short and small mine are;
yet He withholds not the penny.

--

[.offset]
+++[+++And in another letter on the same subject, he says:]

[.embedded-content-document.letter]
--

My powers are very weak and small, I think,
in comparison to those of almost any one else, also shattered,
and partaking of my feeble frame of body:
but there is no knowing what the great "`I AM,`" may choose to do with such;
and those things are ever best left with Him, who can do all things for me.

I have had nothing in view in this work but the great cause,
and have sometimes thought I should leave it as a legacy among Friends;
but it is as my Master wills to this day, as it was when I set a hand to it.
If He please to take me from it, or it from me, it is well.

--

First month 19th, 1820.--I have had from one season to another, up to the present time,
many teaching intimations and timely warnings, from within and from without,
that there is no trust to be had in length of days,
nor dependence to be placed on health or strength or youth,
no nor yet on any services of sufferings for Truth`'s sake; but only upon the Rock,
Christ Jesus, the Lamb slain from the foundation of the world.
To know that renewed in us, which rightly gives an interest in his blood,
and in the salvation he purchased for us,--to feel the spring of immortal,
immaculate life and goodness,
bubbling up and breaking forth in and over us,--to be assured by hearing, knowing,
and following the Shepherd of Israel,
that we are his sheep,--to have a sure and satisfactory evidence,
that we are more and more coming out of the world`'s spirit,
into that of the weaned child,--becoming more and more
separated from sin and self,--more and more seasoned
with and leavened into the nature of a child of God;
this is sweet, and a safe spot, says my soul, for any poor mortal to be found in,
when the summons may be sounded forth.

"`The time is short,`" said the apostle; and it remains for us all,
whatever be our situation in this life, or our station in the Church,
or our standing in a religious sense,
to remember that "`the fashion of this world passes away.`"

These things that are mutable must pass away, and shall be as though they had not been:
yet shall the righteous stand and be established,
when the earth is removed out of its place, and the firmament swept away as with a flood.

Greatly do I desire to be found amongst those, who stay themselves upon the living,
eternal, Almighty Father and Savior;
and to be increasingly concerned to pass the remainder
of my time in true filial fear and faithfulness.

Fourth month 15th.--Surely my soul can praise and bless your holy name at this time,
O Lord Almighty! who are just and faithful,
and true to one of the least of the poor of your flock;
you are the compassionate friend of those who
are prevailed upon to surrender up all unto you,
to commit all into your care and keeping.
O! you Shepherd of Israel,
what can I render unto you for all your benefits and sure mercies,
which are new every morning?
Flow shall I exalt and extol your goodness, your tenderness,
your long-suffering compassion, manifested renewedly towards your unworthy servant?
Words cannot celebrate your wonderful bounty;
but the hearts of those that are concerned to yield themselves unto you,
can sing unto you of mercy, and of judgment, and of truth, eternal,
glorious and unspeakable.

O! you all-wise and Almighty one, bring to pass whatever is for your glory, your honor,
your majesty; and overrule the rest.

Limit the rage and roaring of the enemy, who still seeks to devour your seed,
and to cut up your people.
O! preserve your poor dependent ones,
wherever or however gathered or scattered all the world over,
within the holy and sure enclosure of the hollow of your hand, from this time forth,
even to the end of all things here below:--still stretch out the arm of your
power;--still cover them with the wing of your care and protection,
from the storms and from the blast;--still command deliverance for Jacob,
and send forth salvation for such as are your people, who are seeking your face,
and longing after you.
Still also, O Lord! plead with the rebellious, who indeed dwell in a dry land;
who know not the unutterable sweets of your holy religion.
If it be possible, yet lengthen out the day of your mercy towards these,
as you did unto me,
O blessed God! and give them yet to see the things that
concern their real peace and everlasting happiness.
For what is equal to the joy that your righteous have even here:
in the midst of all their trials they are with you, and you lead and feed them,
and are their strong-hold in the day of trouble,
sanctifying all their afflictions to them; adored forever be Your name!
In a sense of your living presence,
and many mercies vouchsafed unto me in an especial manner of late,
I thus commemorate your praise; desiring to return you thanks,
and to commit the keeping of my soul unto you henceforth;
and to crave of you that I may be preserved humble, holy and blameless unto the end,
increasingly consecrated in heart and life to your pure service;
so that my soul may be fitted, at the end of all things here, to enter into that rest,
which our blessed Savior, your beloved Son,
promised he would give unto those who come unto Him and keep with Him.
Amen.

[.offset]
+++[+++In the 4th month, 1820, he believed it right for him
(consistently with his views mentioned in some preceding letters)
to remove from his "`united family circle,`" and to pitch his "`tent`"
at Poole, in Dorsetshire as a "`temporary home,`" in allusion to which he
experesses an "`earnest desire that in this or any succeeding step that may be to be taken,
the _what,_ the _where,_ the _when_ and the _how_ may be clearly ascertained,
and rightly attended to in all respects`"--adding "`as we abide in that which is
meek and lowly in heart, I have found there is
_that_ which has never yet failed me, as I have been really engaged rightly to seek it;
and by this I have in degree known preservation, and help in every needful time--
it has administered counsel beforehand, comfort afterwards,
and courage in the midst of all the difficulties that have been permitted
to be strewed in the path of duty.`"+++]+++

[.offset]
+++[+++In a letter to a Friend, dated from Poole, 3rd of sixth month, 1820, he writes:-- ]

[.embedded-content-document.letter]
--

I may say that I have never considered it my place to maintain that station in the world,
or live in that mode of life in which I have been brought up,
however mortifying to poor self, and contrary to the habits and views of others.
It was one of the earliest convictions that settled on my mind,
when brought under serious impressions,
that I must come down and set an example of moderation and self-denial,
being content with such things as I have;
so that I have been most easy to decline even
such opportunities of advancing my condition,
as others, no doubt may, in many instances, wisely and rightly seek for and improve.
Some again may throw themselves into extensive channels of usefulness,
by increasing their outward means: I can only say, I am to do good in another way,
if my life be spared.
I have looked, with much solicitude, for best guidance in this matter:
and the comfort and peace with which, during my stay here,
I have been wonderfully favored, have been such,
as to enable me at times even to sing for joy.
I have also been greatly broken down, under a sense of that hand,
which is so eminently over me for good,
enabling me to look the greatest of my difficulties, perplexities,
and discouragements in the face, as it were, with a degree of calm confidence.
My heart and life, and all that I am and have, are to be surrendered up in such a way,
as may answer the Lord`'s holy will and purpose concerning me.
On this groundwork, and on this principle,
I have not hesitated cheerfully to relinquish those views of outward gain,
and habits and station in life, to which my education tended;
but which I have clearly seen are not exactly such,
as harmonize with the Divine intention respecting me,
and with that sphere I should occupy.

What I have expressed herein, is not the feeling of yesterday or today,
but gradually confirmed and rooted in my mind, through much secret conflict,
and a long course of humbling exercises,
and such as some of my sympathizing friends have been
remarkably made sensible of from time to time.
With much affection, I am your friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Poole, 24th of Sixth month, 1820.

Oh! it is a sweet thing to get into calmness,-- to that spot where all our cares, fears,
and doubts are swallowed up.--It is that which our sickened souls often need as a
cordial to revive and to recover us from the nausea of this world`'s joys and cares.
I often feel full occasion to press after a further purification,
from that which yet hangs about me, and which my spirit loathes:
to be released from the bondage is a great matter,
even to come into a degree of freedom from the workings of evil.
I wish many of our reformers, and some youthful ones especially,
knew more of this great work;
they would have shone brighter as vessels in the house of the Lord,
had they gone through the seventh furnace; they would have taken a better polish,
and the dust would not hang upon them, as it now lamentably does.
To feel something good visiting us,
is one thing;--but patiently to endure all the turnings of the holy Hand upon us,
both in breaking down the old nature,
and building up the new edifice on the sure foundation, is another matter.
I fear too many amongst us,
content ourselves with knowing but very little of the latter operation.

Since coming here, my mind is more thoroughly set at rest on some points than ever,
especially as to the propriety of my not entering into business,
a subject which used to harass me much; fearing sometimes, that by this conclusion,
I had given occasion for the cause to be evilly spoken of,
and the testimony of Truth to be let down.
The path is very narrow in many respects, which I have to tread in,
I have had glimpses of it for several years; "`the pride of life`" must be laid low,
however mortifying to the poor creature, as well as to those whose eyes are outward.

You see how much occasion there is for the help, the secret help,
of those who can intercede for me, and sympathize with me;
there is that which can preserve on every hand,
as hitherto it has marvelously done and as faithfulness is abode in,
and watchfulness with patience, who can doubt that the issue of all our movements will,
through holy help, be for the honor, and tend to the promotion of the great cause?

--

[.offset]
+++[+++In the tenth month of this year, he was married to Georgina Hill,
daughter of Major Hill, of Kingsbridge,
Devonshire:--she had joined the Society by convincement.]

1820, Tenth Month 28th.--
Seemed in this short illness to be brought near to the gates of death:
many awful reflections arose.
I longed exceedingly to become more meet to enter the celestial country:
but seemed to myself to have come short of such a state.
I have of late seen myself to have been very unwatchful;
my zeal for God and devoted ness to His cause, very greatly decayed.
Oh! how often have my prayers been put up in sincerity to the Father of mercies,
for His continued goodness to such an unworthy creature,
and for His help against my potent enemy.
But it seems as though all was to little or no purpose,
and that my soul is sinking fast into the pit of supineness and forgetfulness.
This is surely for want of more steady adherence to what is
from time to time seen to be right, and required of me.
Thus hath weakness crept over me, and great declensions in several respects.
Oh! how have my idol and my earthly outward delights run away with my heart and affection,
so that I forget or omit to lift up my soul as I ought to do,
with fervency and frequency of application to the Lord, my Redeemer,
who daily loads me with benefits.
When shall I arise from this dust, in which I am involved?
When shall I be aroused from this bed of ease
and sluggishness in which I have been reclining:
after all that I have seen, and known of the Lord`'s dealings,
is this declension to be the consequence?
Surely, I had rather die than live, to forget my good God!
I believe it would conduce to my comfort,
to be less fervent in outward though lawful affections,
and to be more fervent in spirit;
serving and loving my great Master more than any other object,
seeking Him more earnestly morning by morning,
and oftener than the day lifting up the heart to Him.
Earthly blessings should not so occupy the mind,
as to draw from the due attention to higher duties and more lasting pleasures.

[.offset]
+++[+++To a much valued friend, he wrote:+++]+++

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Penzance, 13th of Third month, 1821.

Often have I thought on you and your endearing friendship,
as commenced in days that are past, and strengthened in hours that are over and gone,
though not soon to be erased;
for to those winter-evening opportunities of
comfort and favor I enjoyed with you and others,
may I not refer much of the benefit and instructive
growth my soul received instrumentally,
at that period of my pilgrimage, when it seemed to be a time of espousals,
and when it might be said truly, "`Your time was the time of love.`"
In reverting to such seasons, I have often been sensible of many short-comings,
many wanderings, and much unwatchfulness;
and I am sometimes ready to apply to myself the language respecting Israel,
"`Of old time, I have broken your yoke, and burst your bands; and you said,
I will not transgress;`"--though some consoling hope attends,
that the succeeding complaint of degeneracy does not altogether belong to me.

To be bowed down under a sense of our infirmities, is profitable to the best,
and safe at seasons for all; and while we may look upon these dispensations,
as some small proof that we are not left without chastisement and fatherly correction;
they turn out not unfrequently, to be the forerunners of further displays of mercy,
and wholesome preparatives for usefulness and enlargement.
We often mar the benefits that are in store for us,
and the intended effects of our trials, by too great eagerness for deliverance.

We have great occasion to stay ourselves upon
the holy Rock in the day of trial and affliction,
having known favors beyond many; the high hand made bare,
and extended renewedly to deliver and protect.
That we may attend with vigilance to the fresh openings of duty in every respect,
is my earnest desire, amidst a deep consciousness of much to deplore,
as regards lack of more steady adherence thereto.

I hear you are richly visited in the ministerial capacity.
O! it is easy work to love them and their testimony from the very heart,
and to be attracted by the sweet influence of that which they live in;
but it is hard to labor in the desert for food and raiment,
and to have no intermediate helping-hand,
to cheer and to animate to constancy and endurance.
Oh! the extent of that labor and daily exercise,
which I feel needful for myself to be found in, lest my soul lose its hold!
Farewell.

[.signed-section-signature]
John Barclay

--

Fourth month 18th.--Quarterly meeting at Exeter.
Oh! that my soul may be moved effectually to strive for
further liberation from the borders and boundaries of sin;
when shall I have a conscience void of offense toward my good Lord,
who daily heaps favors upon me!
Paid a sweet and solemn visit at J. D.`'s.

Oh! that I may walk worthy of these renewed seasons of mercy and favor;
may I double my diligence, fight the good fight of faith,
and strive earnestly for the hope of the Gospel,
while it is held out in unmerited goodness to me, a poor backslider.

20th.--Reached Poole.
Blessed be the Lord who has preserved my soul and body
through many tribulations and temptations and dangers,
since I was last here.
O! my hardness of heart, not to be overcome by his abundant long-suffering and kindness,
and constrained to fall in with his designs respecting me,
which most assuredly are full of tenderness.

Tenth month 29th.--I set out from Poole, for London, with my beloved wife,
who has of late been a greater sufferer from illness,
her complaint being thought inflammation of the lungs.
At one time she seemed brought near to the gates of death; but she was not taken from me,
though I fear, I deserved it.
The Lord omnipotent preserve us in faith and patience,
and content under all the provings He is pleased to permit.
Oh! how much have we to be thankful for!
What great cause to live unto Him, who has thus spared the rod in pity, and heard our cry.
Many vicissitudes my poor soul has had; His dispensations towards me have been wonderful,
past all mention!
Twelfth month 25th.--Attended the London quarterly meeting, and was comforted.
The Lord will yet help and redeem my poor spirit, if I earnestly look unto Him always.
I was dealt with in mercy this day, both publicly and privately.

[.embedded-content-document.letter]
--

[.letter-heading]
To Samuel Alexander, of Needham.

[.signed-section-context-open]
Cheltenham, 18th of Seventh month, 1822.

We have had an account of the decease of our beloved and valued friend, Charles Parker;
my fellow-traveler, as I may call him, truly in more senses than one; having had,
as you may remember, the privilege of his company through Hampshire last autumn:
it affected us considerably.
Past events connected with him, dear and faithful man, were much revived in my own mind;
and I thought much of him on the day of the burial.
I bless the Giver of all good that I have sat under his ministry;
and I remember that the tenor of it often was,
the shortness and vanity of earthly enjoyments and trials,
the certainty and speed of death,
and the goodness and grace that visits and would gather all unto God,
the eternal excellency.

My soul is profitably instructed while I write;
and that may be the best use of my writing to you, my dear, valued,
and now ancient friend and brother, who have so often helped me to think of these things;
and who, I fully trust and believe, are looking for, and desiring at times,
the winding up of all things that are transitory and perishable.
O! that we who are young, may so tread in the path of the just,
that we may be prepared to fill up the vacated seats in the militant church,
of those who are gone before, and who have filled up their measure of enduring.
As to my poor self, if any thing may be said,
it should be but a middling account,--as hitherto, for a long season past;
often surrounded with fears and failings, sensible of short comings,
and a pensioner on that forbearance and pity,
which is not enough (I fear) regarded and remembered.
Watchfulness unto that which is good, seems to me the great thing in the work;
I am sensible we can thus only walk worthy of our vocation and privileges.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To An Unknown Recipient

[.signed-section-context-open]
Penzance, Ninth month, 1822.

My beloved partner`'s present state is comparatively very free from suffering,
or from symptoms that cause uneasiness.
After eight months of vicissitude in London, she was removed to Cheltenham,
where she had some drawbacks from the climate, which was cold and changeable,
also at Clifton, where we rested.
But, through a merciful hand, by which she seemed directed to a religious physician,
she was soon so much relieved, that we could set forward on our journey into Cornwall,
being very anxious to do so; though from the severity of the attack,
it seemed as if we should hardly be able to winter here.

I trust we are both holding on our way, and partaking at times of the brook by the way;
blessed be the great Name, the Giver of life, and of all our many blessings!
We seem remarkably resigned and prepared for whatever may be meted out;
though we have our trials, and besetments, and infirmities.

--

On the 23rd of sixth month, 1823,
my dearly beloved partner passed away to her
blessed eternal rest in the Lord Jesus Christ,
the beloved of her soul and her Redeemer.

On the 29th, the poor body was committed to the earth, to return to the dust as it was.
(She died at Marazion, in Cornwall,
and her remains were interred in Friends`' burying ground,
at that place.) At the grave`'s mouth, I was strengthened to utter these words in public,
on bended knees;--'`Blessing, glory, honor, thanksgiving, and praise, be given unto you,
O! Father of mercies, and God of all consolation! both for that you have given,
and for that you have taken into your resting place; Amen, O! Father,
for so it seemed good in your sight:--your holy will be done!`'
The Lord did marvelously regard and strengthen me:
He will be my guide and refuge, even to the end: surely he will, says my soul.
The Lord does daily help and comfort me; he is with me a poor creature,
and his strength is manifested in my abundant weakness: He is my portion even forever!
