== Chapter X.

16th of Eighth Month, 1823.
—-I resume this little book after a long interval,
and one marked, as perhaps no other part of my life has hitherto been.
O! mighty is the Lord, and able to sustain;—-
able also to finish his own glorious work in us, either by allowing us a longer continuance here,
or by taking us away to himself.
The Lord be praised for all!—-even in that dispensation which is still so bitter to nature;
but through his own consolation and strength it is wonderfully made tolerable.
Yea, life is pleasant; and this world or earth is his footstool,—-
a place He has glorified by his presence from age to age,-—
a place where, at all times, and in all the parts of it,
we may see traces of his goodness to poor man,
and tokens of what he will do in a better place for those that love and serve him.
Come then, O! my soul, take thy blessed privilege on this earth,
and serve him with a joyful cheerful heart;
for He reigns overall, and nothing happens but by his gracious providence.
All is limited, even the evil one;
and all trials and troubles are restrained by his permission,
and converted to the good of his chosen ones, his children.
O! He has taken my dear companion into the rest he had prepared for her;
I can bless his name, for I believe he will never leave me,
until he has consummated his glorious purpose and promise,
in my heavenly translation to eternal joy and peace unspeakable.
Now know I, that He, the Most High, is able to perfect that which concerns me,—-
is able to do all things for me,--
able to prepare me for his glory, and to support me in life and in death;—-
able also soon to cut short my day`'s work, to give me a release,
and to make good a wonderful provision to those that shall come after me;
turning _their_ mourning into joy,
as he has done _my_ sorrow for my beloved earthly friend.
Thus, and more also, will He do for them, and not forsake them.
Though He is invisible, yet He manifests himself through his dear Son,
even by the eternal Spirit; He is with his always,
even to the end of the world; and his are those that choose him for their portion,
falling in with his offers and visitations.
Even the wicked he visits by his rebukes and judgments;
and when they turn at his rebukes, he heals their backslidings, loving them freely.

I thought I received something like a summons to the eternal city two days ago;
when it may be confirmed and accomplished, I know not: but a great solemnity,
and much sweetness have since prevailed in my mind; insomuch that it seems as if
his wonderful power had effected a willingness to go or to stay, as He wills,
who is the God of my life, and who can and does make life sweet;
and who will also take away the bitter ness of death itself,
and no doubt will make up all, to those that remain, as he has done to me.
O! that all may be faithfull to him!
He is wonderful in his dealings to the children of men,
not only by what are called his providences, but also by his grace.

[.embedded-content-document.letter]
--

[.letter-heading]
To E. J.

[.signed-section-context-open]
Marazion, 15th of Eighth Month, 1823.

[.salutation]
My Dear Friend,

As a proof that I think of you, as of many, other beloved Friends _often,_
when it is well with me,--I take my pen at the present season;
being reminded of our fellowship in years that are past,
and wonderfully encouraged and confirmed as to the ground of it;
also fully believing that our progress in the heavenly way,
will not be suffered to be much impeded by any
of those things which are permitted to try and discourage us.
Oh! the ancient, mighty Hand of goodness is not shortened, is not withheld,
in its gracious dealings and dispensations towards us;
but is able to lift us up above all the obstructions which may dismay,--
is able to save to the uttermost,--
can give the oil of joy for mourning, the garment of praise and of salvation
for the spirit of heaviness,--
can do exceeding abundantly above all that the soul is capable of asking or of thinking:
and he will surely be our guide, even unto the end.

Thy kind letter, dear E., was no intrusion, but a
comfort to me in my sore affliction.
No one that has not witnessed such a time, can tell,
how welcome are even a few lines from a dear friend:
though they may excite afresh the tear of affectionate sorrow,
they serve again and again, to remind one of, and to refer one afresh to,
that inexhaustible source of consolation and of joy eternal,
which can make up to us, all we can suffer in our passing along through life.

I need not to thee enlarge on the bitterness of this bereaving blow:
you know a little of my long and heavy train of trials;
how acute was my sense of sympathy for my beloved earthly friend,
under every increase and variation of her sufferings.
Well!—-the great Disposer of all things has dealt very gently with us;
he has cut the work short in righteousness and peace, as respects the better part;
and has put a period to all sorrow, sickness, and sin as regards herself;
giving her abundantly more than this world could afford,
even in the utmost prosperity:--He has likewise bestowed on
me such resignation and strength and faith in Himself,
as I trust will carry me through, and enable me to lay down my head,
as my dear G., in peace.
Sometimes my assurance seems so strong and so clear that this will be the case,
even that "`_I shall go to her_`" (2 Samuel 12:20,)
that every thing in life is rendered pleasant, and every duty no longer a burden;
when I can bear in mind, that every event, every trial, all my occasions of sorrow,
are not only "`working for me`" the "`exceeding weight of glory,`"
but also as it were, bringing me nearer to that blessed period.

When the mind is disposed to commune in this way,
a letter seems to afford but little space for it.
It is not however best for me to go into any of the circumstances of the closing scene,
except to say, that I know not anything that then transpired,
but what seemed in my view, evidently ordered for good.
Oh! I felt that which I never could have supposed myself capable of feeling,
or fit to partake of,—-so helped outwardly and inwardly,
so equal to all emergencies and all duties,—-directed in every thing,
as if no further token of Divine regard could be wanting.
And O! how peaceful was the close, how clear and sensible was she to the last;
though, dear soul, she had not many hours`' notice of her release,
nor had she anything to spare in the awful time,
yet her expressions were all that could be wished.

I a m ready to think, that nothing in life could have happened to me so strengthening,
so helpful to the _better part,_ as her removal;
it carries with it an inexpressible weight of inducements,
binding me afresh to holiness, and lifting me, as it were,
upward towards the better country:--and what mighty evidence it affords,
none can tell but those that pass through it;—-
one`'s own bosom friend, who has been as one`'s own soul,
so graciously dealt with, so blessed in the passage,
and so rewarded, even eternally!—-
I cannot declare these things, as I feel them;
and I fear my broken way of expression is almost unintelligible.

How precious a thing it is, to feel the blessing of Divine regard extended towards us,
strengthening to our day`'s work both of duty and of trial;
O! I would not give up the sense I sometimes have of this, for any thing on earth;
this is that which makes life and all things therein sweet to me,
at a time, when otherwise all is indeed but vanity.

--

Ninth month 18th, 1823.--The sweet incomes of Divine love this day,
were such as made me very contemplative, so as unusually to absorb my mind,
especially while engaged in working in my garden.
I betook myself to a retired walk on the sea-shore to
enjoy the goodness of the Lord more quietly:
the outward beauty of the creation, and the calmness and harmony of all things around,
seemed in sweet unison with the state of my soul.
Oh! how I longed to be fully prepared for, and wholly made partaker of,
the joys of the blessed,-- of them who live to the Lord, and _die_ in the Lord!
I have a hope that I am journeying forward to this state.

Tenth month 9th.--My poor mind has been much under exercise since I left home,
and more particularly on one account;
apprehending some pretty strong drawings to
stand up in a meeting and express a few words.
This was the case first at Truro, then at Falmouth monthly meeting,
and then in degree at the quarterly meeting.
But I trust it was not in disobedience that I forbore;
many things seemed to stand in my way.
I desire not to be expecting great things, but I long for clearness;
and I believe I shall be favored with it.

The consideration of many infirmities, and in some sense unfaithfulness,
and lack of fitness for the work affects me often;
but I long that it may not hinder the setting of my hand to what is laid upon me to do.
I believe there is nothing to be done, unless through a simple surrender and submission.
I can fully believe that the Lord may call to some,
who may have had no previous expectation of such a call to service;
which indeed is by no means my case.
One thing is worthy of commemoration,-- that whereas I besought the
Lord to be assured that such a thing was required at my hands,
he gave me evidently some strong signs,
in the frequent testimonies of his ministers from meeting to meeting;
even very closely urging to faithfulness,
so as almost literally to say,--"`You are the man.`"
But though I could not gainsay,
yet I did not feel as though I had any very strong sense as to that being the right time:
for this I am now thankful; for, when the constraint was laid upon me afterwards,
not by man nor of man, I knew it to be of God, and beyond any man`'s appointment,
but a great cross to my own nature,
and under a sense of the Divine authority and presence.
May the Lord God of salvation and of mercy,
be pleased to show me the path of peace and of joy;
and may He lift up His countenance and light upon me, that I may see and do His will!

At several opportunities, in company with two dear Friends in the ministry,
who were visiting this meeting, I had a distinct sense of what was to be the service,
and what were the needs of the parties visited; especially was this the case,
in the public meeting held at Redruth.
At one family visit in this neighborhood,
I was sensible of the evident call and requiring of the Lord to utter a few words,
in addition to what dropped from others, to the young people present,
on this wise:--'`and then you will find fulfilled in your own experience this language,
as it has abundantly been mine;--"`Though I walk in the midst of trouble,
you will revive me; though I walk in darkness.
You, O! Lord,
will be a light unto me;--though I pass through the valley of the shadow of death,
I will fear no evil.`"

The weight and sweetness that dwelt on my mind, after this surrender, cannot be set forth.
It rested on my spirit all the day, in an unutterable manner; I felt so comfortable,
and at ease in my mind; it was a heavenly feeling,
and nothing short of Him who is in heaven, could give it!
At Wadebridge, in the public meeting, I had to speak to the people,
and in a way remarkable to myself,
for I felt _at home_ in it, if I may so express myself.
Self-possession seemed to be granted me, and self-abasement;
just as though it was not I that had spoken, but my Father, which is in heaven.
In this and other service hereafter mentioned, I had,
(praise be to the Lord! who turns the hearts,
and influences his own simple ones,) the countenance and encouragement of those, who,
I believe, know the voice of the true Shepherd from that of the stranger.
This often humbles me greatly; for next to the answer of peace from God in my own bosom,
what I have desired has often been, the unity of the church and the love of the brethren.

I went into Devonshire, and on my return home,
I had something to say in the next meeting I attended at Marazion:
also at one monthly meeting held at Falmouth, on the true church: and again,
in the chamber of a Friend,
who had been long an invalid,--"`Behold we count them happy which endure;`" take,
my sister, the prophets, who have spoken unto us in the name of the Lord,
for an example of suffering affliction, and patience:
you have heard of the patience of Job, and have seen the end of the Lord,
that he is very pitiful, and of tender mercy.
Behold, we count them happy which endure.
It is a blessed thing indeed, when flesh and heart fail,
to know God to be the strength of our heart and our portion forever.
God shall redeem your soul from the power of the grave, for he shall receive you!
Thus my Master, my tender Father and Teacher dealt with me; and now,
what should I wait for,
but the continuance of his mercy and his light to preserve and sustain me henceforth,
even forever.

I may add, that it was evident to me,
that he who in simplicity surrenders any thing to the Lord,
which in any wise seems called for, will not lose his reward;
but will find his way to open and enlarge, his peace extend,
and he will know more and more of the requirings
and business of the Lord consigned to him;
and the evidence and motions will often increase after the will is resigned.
Wonderful is the Lord`'s goodness to me from time to time, beyond words!
He fills me "`with the finest of the wheat;`" and he
reveals unto me "`the abundance of peace and truth.`"

O! how precious a season was our quarterly meeting
(14th of first month, 1824,) held at Austle.
Is there any thing too hard for the Lord?
"`Call unto me and I will answer you, and show you great and mighty things,
which you know not.`"

[.small-break]
'''

First month 22nd 1824.--Under a feeling of great discouragement at both meetings today,
I trust my mind was sensible where all-sufficient help lies;
though so little of this seemed manifested, or my soul so little capable of enjoying it.

23rd.--Found the overshadowing sweetness of Divine mercy renewed to me this morning,
in a large degree; so that my soul seemed to receive it,
as a token and foretaste of a more full fruition in a better state of being.
Blessed be the Lord, who can raise out of the dust!

27th.--I thought I saw very clearly,
that it is through obedience even in small matters, that our Society, in some respects,
has attained a standing beyond most: obedience is indeed,
a striking feature in the Christian dispensation.

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Marazion, 12th of Eleventh month, 1824.

Dear +++_________+++

I have heard scarce a word respecting you for a long time,
but nevertheless I hold you very preciously before my view;
and your humble waiting and walking is often encouraging.

I should be much pleased were you inclined, in the freedom of old friendship,
to salute me by letter at any time.
You know not of what service it might prove to me,
and be made instrumental to build me up in the most holy faith,
as heretofore used to be the case, when we were nearer in the outward one to another,
and at times blessed in each other`'s society.
I have a full persuasion,
however varied our habits and however distance as to space may have operated,
together with other circumstances,
that we are under the special keeping of the heavenly Shepherd who can feed, and lead,
and cause to lie down, and will permit nothing to make afraid,
or to scatter from his pasture of life and fold of eternal rest.
"`My Father is greater than all,`" and none shall pluck
out of his hand those who keep near Him,
and lean upon Him.
For he restores the soul, and leads in the paths of righteousness for his name`'s sake.
So that though we may have to walk through the valley of the
shadow of death we need fear no evil,--He is with us,
his rod and staff they comfort us.
And when he is pleased to anoint the head as with oil, does not our cup flow over;
and are we not ready to cry out,
"`Surely goodness and mercy shall follow me all the days of my life,
and I will dwell in your house forever?`"
This is, I believe, at times your experience, as it is my own.
Then for us the feeble ones, who may, under discouraging apprehensions of our own state,
be walking fearfully along, as with our heads often hanging down very low,
and who may be said, in some sense, to have answered the call of the Lord, as in Joel,
"`Turn you even to me with all your heart, and with fasting, with weeping,
and with mourning,`"--even to such the language will go forth,--"`be glad and rejoice,
for the Lord will do great things,`" "`for the pastures of the wilderness do spring,
the fig-tree and the vine do yield their strength; and you shall eat in plenty,
and be satisfied, and praise the name of the Lord your God,
that has dealt wondrously with you: and my people shall never be ashamed.`"

Truly in respect to these things that have happened unto me,
they have turned to the furtherance of the work of His glory and grace,
who does all things well; and up to this day, through heights and depths,
my experience is consistent with the language,
"`The right hand of the Lord is exalted,--the right hand of
the Lord does valiantly;`" for though he cause grief,
yet has he compassion, such as will carry through all.
The manifestations of Divine goodness and wisdom,
are indeed very great to the willing and attentive soul;
and while there are seasons when we are not so sensible of them, others are vouchsafed,
in which we _cannot_ doubt or fear but that as we continue the
diligent and patient followers of our crucified Master,
we shall reign with him in a glorious eternity of peace and joy.
My mind has been of late more or less,
since the decease or release of my beloved Georgina, set on its treasure in the heavens,
which will never pass away; and I have been assured,
that if I continue in faith to the end of my day, a place will be prepared for me;
it seemed almost as if permitted by foretaste, to lay hold of eternal life.
Such views are very awful, yet very sweet to me; so that whether they are premonitory,
or only admonitory, they have the effect of quickening me in the duties of life,
and of increasing my true enjoyment therein.--"`Work
while it is day;`" for "`this is not your rest.`"
Believe me, with warmth of affection, your friend,

[.signed-section-signature]
John Barclay

--

Third month 22nd, 1824.--I desire, when the hour of my departure draws nigh,
to be clothed with faith towards God,
and with resignation to commit my dear and only little one into His hand,
who gave him to me:
"`leave your fatherless children unto me;`"
"`let their widows also trust in me,`" "`the Father of the fatherless.`"

Fourth month 2nd.--I was this day inclined to believe, as I have been often of late,
that the bereavement I have sustained in the loss of my tender partner,
was intended in a peculiar manner for my good.
I have been led to think,
that as my dear wife was given to me at a time when I greatly needed a helpmeet;
and as she was one of a noble and capacious mind, inured to trouble and difficulty,
able to counsel and to assist me; so when the time was come,
for her to show me how to pass through the dark valley,
she fulfilled the Divine will in a wonderful degree, as I believe,
by setting me an excellent example, through Him who strengthened her,
and who bore up her afflicted spirit through all that was permitted to assail.
Oh! it is often wonderful to me, to think how suddenly at the last,
she was summoned to take her leave of all that was near and dear in this life,
and how this was accomplished; so that there seemed no agitation or disquietude,
but a holy magnanimity, a deep and solemn reflecting on her condition,
and a reverting to her only hope of glory.
And now I am left, with the image example of a dear devoted child of God,
my soul`'s fellow, often brought before me; to show me how to lay down these shackles,
how to put off this outward man,
and yield up my spirit to my God and her God!--How strongly
has the uncertainty of my continuance in life been before me;
and strong have been my hope and humble assurance, that mercy will compass me about,
and that the rest and portion of the righteous will be mine.
I am ready to say, that those that come after me, will be helped, as I have been;
at least in proportion as they follow the Lord`'s leadings:
for this has truly been my inexpressible desire and comfort;
and such will never be forsaken.

London, fifth month 11th.--I have had many bright seasons,
much assurance and earnest of a better state, as I have walked by the way,
and as I have been on my bed.
"`In all their afflictions,`" it is said,
"`he was afflicted; and the angel of his presence saved them.`"

This language has been fulfilled towards me, and towards my dear deceased partner;
and those that come after me will find, to their unspeakable support and consolation,
that the same Divine Being is rich toward all that call upon him: if faithful,
"`this God will be their God forever and ever; he will be their guide even unto death.`"

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Russel Square, 21st of Sixth month, 1824.

[.salutation]
My dear Friend,

It is pleasant to salute you thus, and to remember you from time to time,
as a brother and companion in the heavenly way and warfare,
striving together with me for an increase of strength and wisdom,
to enable us to stand stedfast, immoveable, and abounding in the work appointed us.
I trust, that as the circumstances of trial and distress,
which were on this very day last year, consummated in the release of my dear wife,
and of which my mind feels often keenly sensible,
were all turned to an unspeakable account and benefit, especially with regard to myself;
so the precarious delicate state of my own health for some time past, has operated,
and does continue to operate advantageously on the better part;
and although in this visit to London,
I may have been deprived of many seasons and showers of Divine good,
there has been no lack of the care and safe guidance of that
invisible hand of Him whose visitations uphold or preserve the spirit,
and whose comforts delight the soul.

--

Seventh month 16th.--So far recovered (from illness in London)
as to go to C. The Lord Almighty was eminently near me,
by support and help in the needful hour,
and through days and nights of tedious ailing and irritation;
my situation often caused many tears in my retirement,
but the Lord was near and comforted me,
and helped me to gratitude as well as acquiescence:
my tears were often turned into tears of joy.
Much have I thought in my distresses of that sweet answer of my dear partner,
which she quickly and smilingly gave me, when in great depression,
observing a sparrow on the house-top, opposite to her window, I said,
"`Like a sparrow alone on the house-top;`" she replied,--"`Not one of them
forgotten before God:`" I find it so to my unspeakable consolation in low seasons.
And I think, since my trials and bereavement,
that more of the consolations of Christ are poured into my soul,
than used to be the case.
Many have been the blessings shed on me abundantly in this tedious,
though short confinement.
May the Lord have the honor and praise, not only now, but for evermore!

17th.--Went out to ride with; a sweet day!
What a change from my sick room and sofa and the smoky city,
to the extensive prospects on the Downs, and the richness of nature`'s verdure.
Was engaged in conversation with +++_______+++:
I feel an interest in young invalids.
O! that the ends of Providence may be answered in them, and in me also;
then all will be well.
These light afflictions;--what a moment do they last,
when compared with the rich eternal recompense,
reserved for those that commit the keeping of their
souls in patient well-doing unto a faithful Creator.

18th.--First-day; at Croydon meetings.
I had a sweet night of pouring forth of the heart unto the Most High.
"`I will cry unto God Most High, unto God that performs all things for me!`"
Floods of tears,--tears of joy, because the Lord God sees me, and has mercy on me.
I had reference to my forlorn state and to the
circumstance of my late afflictive bereavement;
and I had a wonderful evidence that the Lord would be all in all to me,
as he had been to my beloved partner.

25th.--First-day.
Went to Gracechurch Street meeting, and had my mouth opened by the Lord.
O! the peace--the rich flow of it in my bosom, at dear P. B.`'s, after dinner;
the Lord was with me:
melting sweetness came over me in again giving up to express these and other words,
"`This God is our God forever and ever; he will be our guide even unto death.`"

[.offset]
+++[+++In a letter to a person under serious convictions,-- he wrote:]

[.embedded-content-document.letter]
--

[.letter-heading]
To M. B.

In taking up my pen to reply to your letter,
I have felt the occasion to be no small trial of my little measure of faith,
and have desired greatly, to be preserved in that pure and precious fear,
which is said to be the very "`beginning of wisdom,`"--
to have my own mind renewedly subjected to,
and seasoned by, and stayed upon,
that which can alone enable me availingly to lift up a finger in the cause of Truth.
I may tell you,
that I have had no little experience of the long-suffering
lovingkindness that has followed and been with me,
even as long as I can remember, unto this day; through many difficulties,
discouragements, dangers, distresses, and what if I add deaths,
(for he that lives in pleasure is dead while he lives.) When it pleased Him,
whom to know is life eternal, to reveal his Son in me,
(for "`no man knows the Father but the Son,
and he to whomsoever the Son will reveal him,`")--when it pleased Him,
in whom are hid all the treasures of wisdom and knowledge,
to give me an understanding that I might know him that is true,
then it was I was given to see that
"`God resists the proud, and gives grace to the humble,`"--that
"`the secret of the Lord is with them that fear him,
and he will show them his covenant,--the meek also will he guide in judgment,
and the meek he will teach his way.`"

But I found that these things were and are hid from the wise and prudent of this world,
and that the Scribes and Pharisees of this day, as in old time,
are spoken unto in parables; because they looking see not, and listening hear not,
neither do they understand; so also they ask and receive not, for the same reason,
even because they ask amiss; and they look with that eye of reason which can never see,
and listen with that ear of pride, prejudice, or passion,
which is shut out from any capacity to hear the things
which God has prepared for them that seek him.
So that of all things I was very solicitous,
that I might have mine eye rightly anointed with the eye-salve of the kingdom,
and be sent to the pool of Siloam; for I met with many whose eyes had been touched,
and they seemed satisfied with seeing men only as trees walking, and others who,
not having known the scales of mistaken zeal removed from their eyes,
were going about seeking some one to lead them by the hand.

But surely blessed are the eyes that see things as they really are,
in regard to religious truths, and those ears that hear, and who hearing,
obey Him that speaks from heaven; these I considered to be the babes,
to whom these truths are revealed,
and to whom it is given to know the mysteries of the kingdom;
whose ears are not dull of hearing, nor their eyes have they closed,
neither have they hardened their hearts; nor are they the stiff-necked generation,
that do always resist the Holy Ghost:
but unto them is given the spirit of wisdom and
revelation in the knowledge of Jesus Christ,
the eyes of their understanding being enlightened by Him, who said,
"`I am the light of the world,`" and who told his disciples
that he would be with them even to the end of the world.

Now mark, my friend, no sooner did the enemy of my soul`'s peace and welfare,
perceive that his power of darkness was broken in upon,
by the dawning of the day-spring from on high, and that he, the god of this world,
could no longer keep me in blindness and bondage to himself,
and thus prevent the light of the glorious gospel of Christ
from effectually and availingly shining in my heart;
than he, as it were, assumed the appearance of an angel of light;
and thus he laid a more subtle snare and gilded bait for my poor weary soul,
than even I had known before.
For the unwearied adversary observing,
that through the precious powerful visitation of the Almighty,
my mind was quickened and awakened to a lively sense of the exceeding sinfulness of sin,
began himself to set me at work to recover from it; which indeed can only be begun,
carried on, and accomplished by God,
through faith in the operation of the Spirit of his Son, Christ Jesus;
who remains to be the only sacrifice for sin, and Savior from sin,
and sanctifier of sinners.
And now being little by little led arid enticed to try, in my own will, wisdom and way,
to get to heaven and having let in the reasoner, the serpent,
in this his refined transformation,
I soon forgot that it is not to be attained by works of righteousness,
which we can do or have done in our own creaturely ability,
strength and activity but by an unreserved and
simple submission to the forming hand of Him,
who made all things good in the beginning,
and who can alone restore and bring back man into the holy heavenly image,
in which he was created.

So that instead of being created in Christ Jesus unto good works, I,
having the understanding darkened, and being alienated, in some degree,
from the life of God, became vain in my imagination;
and my foolish heart would be exercising itself
in things too high for me in my present growth;
and busying itself and wearying itself with my own conceivings, speaking evil,
or at least thinking lightly of things, which as yet I knew not.
Thus, though I professed myself wise in the knowledge of religious truths,
I became foolish.
For all the fine show of doctrines, and of duties, and of ordinances,
and of prayers in the market places, and as it were in the corners of the streets,
and in the synagogues, and the giving of one`'s body to be burnt,
and one`'s goods to the poor,
or such of these great performances as were not the product of his holy aid
and influence renewedly extended in the time of need,---were found to be but
at best a hindrance to the free course of that well-spring and water of life,
which had been opened within me.
Although through the delusion and deceit of the enemy,
I was thus tempted to build a very Babel of doctrines,
heaping up scripture upon scripture, text upon text, to support my fabric of confusion;
and although I was very zealous in searching
into these things in my own spirit and strength,
(notwithstanding it is written, "`No man knows the things of God,
but by the spirit of God,`" and no man can rightly and really own Jesus to be the Lord,
but by his Holy Spirit;)--yet in the midst of all this
departure from the fountain of living waters,
and this hewing out broken cisterns, that cannot receive or retain the water of life,
I was not altogether left desolate;
but the Lord regarded the integrity of my heart towards Him,
even in those very performances and high profession, which displeased Him.
Again and again he was pleased in unutterable mercy, to make known unto me that way,
which he would have his single-hearted, simple,
lowly babes to walk in:--no galley with oars,
neither gallant ships could pass that way;--nothing that was high or lofty, or lifted up,
however secretly, in its own estimation,--nothing of self,
or of that wisdom which is foolishness with God,
and which he-will utterly confound and destroy,
and by which the world never knew neither can know Him.
I found all my own strivings, and the strugglings of the will of the creature,
could not carry me one step forward in the narrow way;
neither was I able by taking thought to add one cubit to my stature,
in a religious sense; for I then saw it was not of him that wills,
neither of him that runs, but of God and his grace,
that cast up day by day the holy highway before
my view,--giving me the strength sufficient,
and the sustenance that was meet, and that degree of satisfaction,
in regard to religious truths, which was best for me.
And in that day, as also even to this very hour,
the language often was to me,--"`I have yet many things to say unto you,
but you can not bear them now.`"
But as I came from the feet of Gamaliel, to sit with Mary at the feet of Jesus,
and to be taught by Him in his inward and spiritual appearance,
(who is said to be the wisdom of God, and teaches as never man taught,
speaking with authority and not as the Scribes,)--I
found that this Minister of ministers,
did more for me as to the true and saving knowledge of Himself,
and the things relating to his kingdom, than any man or book whatever.
He (as his servant the apostle Paul said,) fed me with milk;
and as I grew to riper years, in a spiritual sense, he gave me stronger meat.
I found Him no hard master, nor austere man,
requiring more of me than He had given strength to perform.
In this humble, simple state, resting in the Lord,
and waiting patiently for him,--not stirring up nor attempting to
awake him whom my soul loved before he pleased,--not desiring to have
every thing all at once cleared up before my view,--not seeking great
things for myself in any sense,--but only longing for a seat,
if it might be the very lowest at his spiritual supper,
or even to partake of the crumbs that might fall
from his table,--willing also to fast long,
if it so pleased Him,
until the times of refreshing should come from his presence,--how was and is my safety,
my sure standing, my strength, my salvation, known and felt to be wrought out,
even with fear and trembling.
For here in this lowly valley, where self was of no reputation,
and the bleak gales passed over, and cut not the tender plant,
the quiet habitation was known, the still small voice was distinctly heard, which said,
"`This is the way, walk in it.`"
I then knew my peace made and daily kept; even a holy assurance was given me,
a holy confidence and repose,
as in the arms of a faithful Creator,--agreeably to the language of the prophet,
"`You will keep him in perfect peace, whose mind is stayed on you.`"

Here was communion and union with the Father and Fountain of mercies experienced;
joy such as no man could take from me; a peace which passes the natural understanding,
and a holy heavenly fellowship as with the just of all generations.
Here I could call God Father,
because he had sent forth the Spirit of his Son into my heart,
and I had received the spirit of adoption, whereby I could cry, Abba, Father.
For as many as are led by the Spirit of God, they are his sons.
How precious is this passive, patient,
submissive state of mind,--a giving up of all into His
holy care and keeping,--a resigning of our own wills,
wisdom, and the workings of our own spirits and nature, to be melted down,
and moulded into accordance with His divine and glorious nature and image.
Thus are we alone true witnesses and partakers of the first
resurrection,-- over such the second death has no power;
that part in us which is to die, being crucified, dead, and buried,
according to the apostle`'s testimony, where he says, "`knowing this,
that our old man is crucified with Him, that the body of sin might be destroyed,
that henceforth we should not serve sin.`"
How clearly, even with unclouded clearness,
were things opened to me while in this state and condition;
or rather how was my mind prepared and qualified (through a being clothed with humility,
and the meek and quiet spirit,
and by a daily waiting on the Lord for a renewal of spiritual strength,) to comprehend,
apply, and attain unto the blessed commandments, injunctions,
and instructions left on record in the Scriptures of Truth.
The Psalmist said to this effect;
"`Open my eyes, that I may behold wondrous things out of your law;`"--
a proof he needed this best aid,
or we may suppose, he would not have thus supplicated.

Now the divine law was to be written on the heart,
and put into the inward parts under the Gospel dispensation; and Solomon says,
"`The law is light:`" and we read that "`whatsoever makes manifest,
is light:`" so that according to Scripture, we have light sown in the heart,
unto which if we attend, it will manifest darkness, and the works of darkness,
and reprove them; and this we read is to be the law under the new covenant.
Then as I gave up, and was prevailed upon to yield unto the enlivening,
operative influence of this inward principle, it came to work out the evil,
and leaven the heart more and more into its own pure nature;
so that instead of the light within me becoming darkness,
my path seemed like that of the just man,
which shines more and more unto the perfect day.

Whatever profession we make among men, we must serve the Lord in newness of life,
and be born again, born of the Spirit, for the carnal mind is enmity against God;
and without holiness no man can see God, or his kingdom, (which is "`righteousness,
peace, and joy in the Holy Ghost;`") neither can he enter therein;
however high the profession, yet so much the greater may be the condemnation.
I have felt it to be a very awful consideration, my friend,
that the enemy of our soul`'s eternal welfare, hunts for the precious life,
the substance and root of religion;
if he can eat that out,--if he can deprive us of that,
though our branches of profession be spread forth as Lebanon, we shall be cut down,
and cast into the fire, as a tree that cumbers the ground of God`'s vineyard.
He, even the enemy, cares not how busy and eager we are,
in what we may be pleased to think is religion, and to call so;
and though we may hold the doctrines of the very apostles and primitive Christians,
yet he knows very well that a man`'s creed being scriptural and correct,
is no certain criterion or proof whereby to judge what spirit it is that rules him.
For we read, that the very devils believe and tremble; and they could easily cry out,
in the days of our Savior`'s appearance in the flesh,
"`You are Christ the Son of God;`"--and again, "`I know you who you are,
the Holy One of God.`"
But Jesus rebuking them, permitted them not to speak; because, no doubt,
their testimony of him,
though given in respect to the matter of fact which they declared,
was as it were a lie in their mouths,--agreeably to what Jeremiah says,
"`Though they (wicked men) say, the Lord lives, yet verily they swear falsely.`"
And we see in the account of our Savior`'s temptation in the wilderness,
how aptly Satan could quote scripture and bring texts to support his own vile purposes.

Now we may remember, that when Peter confessed and said,
"`You are Christ, the Son of the living God;`" Jesus answered and said unto him,--
"`Blessed are you,--for flesh and blood has not revealed it unto you,
but my Father which is in heaven.`"
Here was an acknowledgment and profession,
arising out of and flowing from a measure of the true, living, operative faith,
which works by love, to the purifying of the heart and life.
Here was something more--something far beyond, a mere hewing out of systems of faith,
and holding them merely in the dead notion in the will of the creature.
Few follow or feel after the spiritual guide and leader,
which is Christ Jesus in his inward and spiritual appearance; who said,
"`I will not leave you comfortless, I will come to you;`" and who further promised,
that he would manifest himself unto such as loved him; and that those who followed Him,
(who is the Light of the world,) should not walk in darkness,
but should have the light of life.

It is indeed the Spirit of Truth that can alone lead us into all truth;
and it is the Spirit which quickens, for the flesh,
and all that the creature can do by its own strivings and stirrings,
profits nothing in the work of God; and the spirit of man as well as the wrath of man,
cannot work the righteousness of God, but hinders and obstructs it greatly.
Now, the Lord Jesus Christ, the Lord from heaven, is that quickening Spirit,
who is the Way, the Truth, and the Life; whom the world cannot receive,
(nor those that are in the spirit of the world,) because it sees him not,
neither knows him; but to those that leave all, and are willing to deny themselves,
and renounce this world`'s spirit, and follow Him in the regeneration,
the blessed promise and assurance is, "`He dwells with you, and shall be in you.`"
"`I am the living bread,`" said Christ;
"`he that eats my flesh, and drinks my blood, dwells in me, and I in him;`"
such spiritual communicants know Christ in them their hope of glory;
and thus are they built up and elected in Him, the corner stone, elect and precious.

We also own all that the Scriptures speak of, respecting His most satisfactory sacrifice,
and that he tasted death for every man, purchased eternal redemption for us;
and that "`through this man is preached by us the forgiveness of sins:`"
none are saved but by and through Him;
for we are reconciled to God by the death of his Son,
and thereby put into a capacity to lay hold of that salvation which is freely offered,
on condition that we repent and believe.

--
