== Chapter XI

+++[+++In the autumn of this year, 1824, he visited Malvern for the benefit of his health.]

[.small-break]
'''

Ninth month 9th, 1824.--At Worcester meeting.
The Lord gave me some service in a private way these two days,
though at L+++_____+++ I was much shut up.
There is cause to remember how my mind was opened and enlivened at this time,
in a feeling of the good Hand that had been over me, in days that were long passed;
and how I was enabled to recount to others the mercies that had been granted,
and many deliverances which the right hand of the most High had wrought for me.
Surely He is ever worthy to be honored and served!
In meeting this day, my poor soul was constrained,
in the powerful feeling of gospel love,
to manifest by a public exhortation and testimony, my allegiance to my God.
The peace that flowed was very precious;
my soul would have been content to praise Him the Giver in secret,
had this been all that was required.
But I must bow down before the Lord, which I was enabled to do in much resignedness,
and holy fear; craving earnestly the continued favor and preservation of the Almighty,
on behalf of the visited ones; the savor of the precious life vouchsafed,
remains freshly with me.
Thus did my visit close in this part of the heritage,
to my humble admiration at the goodness of the Lord.

1824, Twelfth month 20th.--This day, as during many others of late,
the gospel light has risen in me with much and indescribable strength;
so that my poor vessel has seemed too full to contain, and I have been ready to pray,
that the oil might be stayed.
I have thought much of the language uttered by a worthy ancient;
'`The Spirit that now rules in me,
shall yet break forth in thousands.`' I have fully seen and been assured,
that the gospel day shall rise higher and higher upon the faithful;
and with regard to my poor soul, that the Lord,
whom I am concerned to serve and trust in, will carry me through, even to the end.
The Lord be magnified, and He only,--whether by life or death.

[.embedded-content-document.letter]
--

[.letter-heading]
To J. F. Marsh

[.signed-section-context-open]
Marazion, 24th of First month, 1825.

[.salutation]
My Beloved Friend,

The hearing of your late bereavement has affected my heart,
but to hear that you are, or have been, supported in calmness, is no surprise.

Nor do I think to add any thing to this gift and qualification,
--a resignedness to do and suffer whatever is,
in the ordering of the Divine will, meted out as your lot in life.
But as we may be animated and comforted by the mutual faith one of another,
it seemed as though it would be so to me, to address you at this time,
even in the love of our common Father; who brought us acquainted with each other,
and who knit us together in His blessed fellowship,
and has preserved us in the Truth to this day, so that we are members one of another.
I am persuaded, that nothing shall be permitted to shake our faith,
or separate us from his love, as we continue to be concerned to cleave to it,
in the heights as in the depths;
but that in the end we shall be more than conquerors through Him who gave himself for us,
and is very tender of us.
And though we are appointed unto such afflictions,
there is a time when the eye of the soul can see in these,
far more of the compassions that fail not,
and of the gentle leadings of the Shepherd of Israel,
than in seasons of prosperity and ease.
It is in these afflictions, that we see how in love and in pity He redeems,
bearing the lambs as ever in His bosom; so that under a sense of these things,
we are constrained, like the prophet,
to "`make mention of the loving-kindnesses of the Lord and his praises,
according to all that the Lord has bestowed on us, and His great goodness.`"

Dearly beloved, what a fine thing it is to be able to look beyond all outward things,
and to feel that our rest is not in this frail passing scene;
but that we are bound for a glorious state,
and are continually wrestling for an advancement in the way which leads to it;
none of the tribulations we meet with,
can then move us away from the joyful hope set before us, nor deprive us of that,
upon which alone we can place our hearts.
This is the language and experience of the faithful in all ages,
and what is taught the least scholar in the school of Christ.
And though there may be many, many seasons,
when we cannot sensibly get at this measure of experience;
yet the lowest smallest grain of true faith,
that was ever yet permitted or dispensed to the upright,
brings with it a sufficient "`evidence of things not seen,`"
to support and preserve from condemnation and despair.

Many, no doubt, continue to be your discouragements,
independent of this late source of trial.
O! dear brother, be animated,--put on strength in the name of the Most High God;
who is surely with you, and will help you, in every hour of need,
and enable you to rise over all that would keep you down,--
over all that would oppress his own precious life in you.
There is work for such as you are, up and down in the earth, and in this part too,
where there is much seed sown, and in ground prepared for its reception.
I hope you and others, often strengthen one another's hands in the Lord,
and in his work and service; for the time is short, at the longest;
and it is good to work while the day lasts,
and to glorify the great name in the way of his own leadings;
on which his blessing abundantly rests as ever!
Ah! what can we render unto, or do for Him, who has done so much for us!
With my dear love, from your old and true friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Marazion, 8th of Second month, 1825.

[.salutation]
Dear tried souls,

Cast down, but yet not forsaken, nor forgotten, but rather highly favored,
and under the peculiar care and preservation of
the Shepherd of the flock,--my soul salutes you.
Oh! think you in any hour of deep plunging, that a hair of your head,
(figuratively speaking,) shall be singed in the fiery
furnace,--or that they are not all numbered,
or that your tears are not treasured up in His bottle,--put into his
book,--that they do not come up continually before Him as a memorial!
Surely His wonderful, unsearchable purposes and wisdom, shall be all duly accomplished;
and his dealings will be found to have been in loving-kindness, in tenderest mercy.
Be then animated afresh to commit all into his hands,
to resign yourselves again and again unreservedly;
retaining nothing but the desire to do and to be what He would have you,
and to suffer all that He has or may permit, or purpose for you to pass through.
O! then, with what invincible meekness and patience and long-suffering,
will you be endued; then nothing will be impossible to you,
all things will be made sweet; your goings forth be even prepared like the morning,
and all the way cast up clear before you;
and abundance of peace will be your crown and portion forever.

But do I only say this; do you not know it at times; and are not his promises stedfast,
and his covenant sure?
Will he forsake those that seek to serve and to please him,
or forget the cry of the afflicted and the bowed down soul?
"`I am the Lord; I change not; therefore you sons of Jacob are not consumed.`"
Whatever may be the turnings or over-turnings of His holy hand,
may He have all the glory in your entire dedication;
and then no heights or depths will be able to separate you, or to shake your faith;
nor will you in any hour rest unduly by the way in any attainments,
but aspire after the further manifestations of His holy will and power;
that so you may prove a blessing to many upon His earth,
while ripening and brightening for a better world.
I know not whether we may meet, yes or no, in this state of being; if not, be it so:
but let us struggle on, let us be willing to endure all things.
Be valiant in suffering; it is far beyond all service,
to be made willing to partake of deaths oft, as a great Apostle;
and to be conformed to the image of the dear Son--the Lamb that was slain,
to suffer with him, that we may be clothed and crowned with his glory.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To E. H.

[.salutation]
Dearly beloved Friend,

Thou hast named several precious instruments and vessels,
that seem about to be made use of up and down,
and the mention of their names and prospects did me good;
who am, through wonderful dealing, more and more knit and tied to the good cause,
and united to those who are endeavouring to walk with their Master, and to serve him.
It will then be no surprisal to you to hear, that (as I have apprehended)
a weighty matter in the shape of a gospel errand,
has been spread before me, and now seems fast ripening.
O! the sweetness and even the blessedness,
which have from time to time attended my poor mind,
as there has been an endeavour after pure passiveness under this prospect:
so that indeed I am ready to say, let come what will, should it please
Infinite Wisdom to take me into his rest, or his work into his own hands,
so as altogether to release me from this requiring, I have no will in it.
I know it has been abundantly good for me to yield to these impressions,
and to have been exercised and proved this way hitherto;
and as to the future, I am wholly at his disposal, to be,
to do, or to suffer, what ever may be prepared for me.
In conversing with my dear sister one day on the subject,
I was induced to say, that if a small part of this engagement,
namely to visit the meetings of this county might be taken first,
and way should open for me therein, it would be a great comfort to me:
and in allusion to my present situation,
as not being acknowledged a minister, I said, we must not look for signs and wonders,
it is at least a weak ness to do so;
yet that if any thing might turn out like encouragement to me
at our ensuing Monthly Meeting, it would be a favour.
"`Show me a token for good, and let thy work appear unto thy servant,`"—-
was my secret breathing at the first meeting;
and after that was concluded, the women Friends being desired to stay,
dear A. T., was led to lay before Friends her desire to sit
with the several meetings of this Quarterly Meeting:
and when I was looking for something further,
she said that if any Friend in the
station of minister or elder should feel his mind drawn to accompany her,
it would be quite satisfactory to her.
Thus I was induced to expose myself by saying,
that though not standing in the acknowledged or appointed stations alluded to,
this thing had been before me, etc.;
leaving it wholly to Friends to do what they thought best about it.
So here I am on my way to the Eastern Monthly Meeting, hitherto helped,
and henceforth longing to trust more and more my Master.
Truly I cannot tell whether my life may be spared to accomplish what is before me,
or whether the concern may not be wholly removed from me.
In health I am just _above water;_ exceedingly delicate, but ailing little,
liable any day to have my health utterly broken up.
But I am not anxious,
longing only to be prepared and ready to give in my account with joy, whenever called upon.
It is often a glorious time with me, dear E—-.,
and if it were not for this prospect of a little labour of love,
I should be ready to take what I have received,
as an earnest of an early departure for a better country;
and it may be so notwithstanding.
Well, whatevermay be in store for us,
O! let us give up fully to honour and magnify the adorable Name, by life or by death,
by suffering or rejoicing;
for we know it to be as ointment poured forth,
and we have been anointed with it, and it teacheth us of all things,--
even the everlasting Truth;

In the love of it, I dearly bid you farewell,

[.signed-section-signature]
J+++.+++ B.

--

[.offset]
+++[+++It was in the fourth month of this year, 1825,
that he was acknowledged a minister by the monthly
meeting of the West Division of Cornwall.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia A. Barclay

[.signed-section-context-open]
Bradpole, 29th of Fourth month, 1825.

[.salutation]
My Dear Lydia,

When we think what unworthy creatures we are, even at the best,
and how goodness and mercy follow us, sustaining us under our trials,
and turning them all to our good, we have surely great occasion to lay hold of hope,
to take fresh courage, to put on strength, and be armed with patience,
cheerful submission, and full assurance of faith for the time to come.
My mind seems equal to very little beyond my more immediate calling,
and when not so engaged, it feels as poor, weak, and empty,
as ever I have known to be the case.

O! what a comfort from time to time to feel the Lord with me,
strengthening me and prospering his work in my hands, again and again,
to my humbling admiration at the power of his might,
the excellency of his loving-kindness and his grace.
It has more than once struck me forcibly, that if this work be of the Lord,
and I be engaged in it according to his will,
some that have been concerned to strengthen my weak hands,
will participate in the division of the spoil, that is,
in the earnest of the reward of the faithful.
These who have given the cup of cold water, have done what they could;
and what they have done in simplicity, on behalf of the poor servant,
it is esteemed as done to the Master himself; though they may be ready to say,
"`When saw we you in prison,`" etc.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia A. Barclay

[.signed-section-context-open]
2nd of Fifth month, 1825.

Having been helped to get over another mountain
in the attendance of this meeting yesterday,
and having been favored to wrestle and struggle with the powers of darkness,
and to suffer with a suffering seed in this desolate region,
my heart feels comparatively light, hoping that I stand acquitted of the blood of some,
and that through deep suffering,--yes, wading of spirit,
the good cause has been espoused in some sort, however feebly,
and the way of life set forth; in abundant condescension,
I was favored to get along safely, without, I trust, stumbling;
though truly it was hard work.

O! the lethargy, the lifeless, lukewarm condition of many: no hunger or thirst,
no sense of eternal things, no relish for heavenly goodness; and such as are otherwise,
sunk into a low, discouraged, dying state.
Yet even here, the spark of divine love is not wholly extinct and taken away;
but the Lord is waiting to be gracious, his repentings kindled together,
and his pleading voice to be heard, "`Why will you die?`"
I conclude, if it be his good pleasure,
that this place be favored with those professing the pure spiritual way of Truth,
there will yet be preserved a hidden remnant, who will not be utterly given over,
nor give over the pure Truth to utter reproach; but in their measure,
or according to the light received, will glorify, however imperfectly, the great Name!
You will feel tenderly for me; but I have been helped, so that I can say,
the Lord has been sufficient for me in this great time
of need and stress upon my mind and feelings.
I know not,
in the retrospect and amidst all the reflections that have been brought before me,
that there has been any other than a peaceful satisfaction respecting the past,
mixed with much occasion for gratitude,
in considering how bountifully and wonderfully I have been dealt with,
led about and instructed, kept from utterly perishing,
amply provided for and sustained hitherto;
favored also with ability at times to trust that all will be well with me and mine,
so long as we continue to seek and serve so good a Master,
who will never try us above our strength, nor afflict us willingly.

At, I called on a Friend,
and had a refreshing little opportunity of handing encouragement to himself and wife;
heavenly goodness seemed near us.
Oh! the work is very weighty, and the trials thereof are many;
but the Lord is sufficient, as he is trusted in.
I have not an anxious thought about you at home: I know who will watch over you,
and help you every way; only let not the tempter discourage you;
for it is the Master that says,
"`Fear not little flock;`"--"`Be of good cheer;`" "`Be strong,`" yes, be strong.

[.signed-section-closing]
Your very affectionate brother,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To P. H. Gurney.

[.signed-section-context-open]
Sixth month, 1825.

After a considerable space of intervening time, I take my pen to salute you,
though scarce knowing in what circumstances this may find you.
If the best of us are but in the land of the living,
partakers of life invisible and divine,
how much have we to be thankful for,--how much to answer for!

Whenever I address you, my dear cousin, in this way,
the slender tenure we each have of all things here below, seems to recur to my thoughts;
with earnest desires that my own state of mind and conduct,
may increasingly be moulded to the image of the heavenly Pattern,
and so be prepared to meet Him at His coming:
who Comes in one sense as a thief in the night.

But seldom have I known the evidences of divine peace and favor so veiled from me,
I think, as at times since publicly engaged in this awful line of the ministry.
To you, I need not expand my views by much expression hereon; no doubt,
you have known for many years, the dealings of inscrutable Wisdom,
and the discipline of heavenly love and mercy, in strippings, in tossings,
in wadings of the poor spirit; nor will it surprise you, should I say,
that sometimes it is so with me, that I seem pressed out of measure,
so as to despair of even the outward life,
as well as that which is described as being "`hid with Christ in God.`"
marvelous goodness however has provided all things well for me outwardly and inwardly,
especially during my deeply proving prospects and journey; I have,
as I suppose you have heard, taken meetings in Devon, Dorset, and Hants,
on my way to the yearly meeting,
and being likely to take the remaining ones in those counties with one or two in Surrey,
as I return, after attending the six London monthly meetings.
This last is to me in prospect crucifying, beyond what I can express,
especially as I have believed it best to go single-handed.

--

10th--At night under great anguish of spirit, I wrote as follows,
my heart being turned towards the Lord:

O! God, most holy, and almighty,
all wise and gracious,--regard me with your pitying eye; spare me, help me,
save me in this depth of need, which you only know, is beyond words.
Deliver and preserve me to the end,
and through all that which may in your wisdom be permitted.
Haste you to help me, O! my God--my all!
Let not my cruel enemy devour me; let not your Truth be dishonored by me;
conduct me safely, and, if it be best, speedily,
to my everlasting rest with you and with your Son.
Amen!
Amen!

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia A. Barclay

[.signed-section-context-open]
15th of Sixth month, 1825.

On the 7th, I attended Devonshire House monthly meeting,
and on the 8th that of Gracechurch Street;
in both which I had to declare the excellency of
that spiritual dispensation committed to us.
What arduous work it is to minister,
where the attention and desire of those present is very outward after words.

The extent of my wadings and exercises no one knows but the great Master;
they have been various and abundant indeed, since the yearly meeting;
the discouragements of the day I have never seen so deeply before,
though I am not blind to the encouraging features.

How short are we of what the Lord would do for us as a people, were we only simple,
sincere, plain, humble enough!
If we go on _but as we do,_ I fear, notwithstanding all that is stirring,
we shall as a Society be weaker than we now are.

On first-day evening, after due deliberation,
(which indeed had been going on in my mind many days, being much exhausted in powers,
both of body and mind,) I concluded it best to suspend all further proceeding,
with regard to visiting meetings in this city.
As my mind settled under this act of resignation,
I was confirmed in its being of the Lord's ordering, and of his abundant mercy;
who tries not any beyond what he sees good, and whose service is a reasonable service.
I wish greatly to be preserved on all hands,
and in all things from hurting the good cause, which is dearer to me than my life.
I am very feeble, and obliged to use the sofa very much, taking frequent nourishment, etc.
I propose going with my brother to Bognor,
in the hope of being better able (after ten days there) to undertake the journey home.
I desire for you as for myself,
that endeavoring to live in Christian faith and simplicity,
we may have our minds deeply centered and set upon nothing
short of the unerring and Divine will in all things;
then nothing that can happen to us will any way move us,
but all will work together for our good, and for the honor of the great name.

You must be sensible that this turn in my course,
though by no means one previously calculated upon, was no great surprise to me;
the wonder was,
that I should be enabled to go through any part
of the prospect set before me on quitting home,
indeed that I was strengthened to entertain it at all,
considering my weakly condition.--Give my love to Friends.
I am a poor creature,
but I trust not out of the reach of the infinite compassion of the Shepherd of Israel.
Farewell!

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Carshalton, 20th of Sixth month, 1825.

My dear +++________+++

I may state to you, that on sixth-day and seventh-day week,
my powers of body and mind were so exhausted and enfeebled, as clearly to excuse me,
in my judgment, from any further proceedings in my engagement for the present.
I saw I had no hard master,
nor unreasonable service,--that He knew what had been
given up and undergone for his pure name's sake;
and, were it called for, that I was ready to give up my natural life,
rather than shrink from suffering or from shame.

Deep indeed have been the conflicts and the baptisms,--crucifying,
yes mortifying have been the often silent labors of my soul before Him,
on account and on behalf of this people, and especially in this great city,
since coming to it:--whether I may ever complete what was presented to my mind,
as a religious obligation, I know not;
but I am very comfortable in an entire relinquishment of that part which respects London.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Lydia A. Barclay

[.signed-section-context-open]
Bognor, 24th of Sixth month, 1825.

I am favored indeed in being able to say how greatly the change of air,
and the suspension of mental exercises have revived me.

Truly, I felt both in mind and body,
failing beyond the usual vicissitudes or ups and downs that attend.
It was a great convulsion to my faith, though relieving to my poor frame,
to have to resign what had been received as clear duty; and I trust,
that if in any wise there was occasion for me at that crisis to remember Jonah's case,
when he was angry, because his Master's will declared through him was reversed,
the feeling was nothing worse than a jealousy for the honor of the great name,
and the high vocation professed by me, lest the Truth should suffer,
or any cause of offense be given.
I am altogether in the hands of One, who can see if I have gone down to Joppa,
and paid the fare to Tarshish.
It is an awful thing in this day, as ever it was in any other,
to take the name of the Most High into our lips, and to declare his commands; but if so,
how awful is the situation of those who reject these messages,--who do not,
like "`that great city`" of old, "`cry mightily,`" and turn from their evil ways.
The longer I was in that great city, the more was I baptized,
(as I thought,) into a sense of that which is lacking,
in an especial manner in our favored Society;
until the burden became more than I could sustain: and yet for a time,
I could not see any way rightly to get from under it.

When we consider what must be, and ever is,
the condition of those who follow not the Lamb in the leadings of his pure light,
and that it is said of them that love the world and the things of it,
that the love of the Father is __not in them,__--that the friendship of
the world is enmity against Him,--with many other such truths;
what shall we think the fair profession of many is worth,
in the sight of the Searcher of hearts.
How glorious a thing, to be daily growing in grace, daily receiving heavenly bread,
daily partaking of the Divine blessing, and in _that,_
moving and acting towards others in our several duties.
It is wonderful to me, how my constitution seems in so short a time to have rallied.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To a Friend

[.signed-section-context-open]
Bognor, Sussex, 30th of Sixth month, 1825.

[.salutation]
My Beloved Friend,

What a wonderful course have believers to tread in;--how led about,
and in all things instructed,--how wonderfully and wisely dealt with!
What a process it takes to purify us from self, and completely to redeem.
Nothing less than an infinite Hand can do it for us; both as to mercy, wisdom and power,
and that continually exerted in our behalf.
I feel these things more than ever I did,
and feel that I am yet but a child in the experience of them;
because that which is attained,
is as nothing compared with the fulness that is set before us.
I trust we are companions in this path,
wherein we are through many tribulations and
chastenings and even apparent desertion and death,
taught that we are poor creatures, able of ourselves to do nothing,
neither to keep ourselves alive in a spiritual sense.
It is hard work to endure patiently all that is needful for this purpose,
and to accept all the painful operations of the Holy and High One for our good:
yet there is no safety for us,
but in submitting thus to what may be called the death of the cross;
and "`if we be dead with _Him,_ we believe that we shall also live with Him; if we suffer,
we shall reign with Him.`"
I continue to feel peace of mind in the step taken or concluded on, when under your roof.
What a shelter, dear friends, it felt to me to be with you;
I wish often to be with you in spirit, and to partake of that which refreshes you,
and which animates to hold on to steadfastness.

My situation since I left you, has been one calculated to discourage;
but I trust the Lord is my stay,
though little evidence seems extended of that
sensible support which poor nature looks for.
It has been a sifting, searching time with me; the being thus suspended,
shall I say thrown on my back, and my purposes turned aside, causes much scrutiny;
but I cannot find that I have missed the way,--no, the language presents,
"`It was well it was in your heart;`" yet as regards the future,
I am earnest for clearness, though remembering that we are to "`be careful for nothing.`"
Alton quarterly and monthly meetings are to be on the fifth and sixth-days next week;
in being at these, I may see further what is best.
My health is certainly better for being here,
the bracing sea air has been very beneficial; but while this is the case,
every day shows me proofs of my exceedingly delicate state.
A religious meeting costs me much travail, much wrestling of spirit;
so does going about among Friends occasion much suffering and watching,
though often with a cheerful countenance.
If we are but kept simple, humble, patient, resigned to do or suffer,
nothing can harm us, nor will a hair of our heads be singed or fall to the ground;
all that can happen to us will only turn to our benefit,
and not one of our sacrifices but will accomplish that for which it is designed by Him,
who works in us and for us.

--

Ninth month 15th.--I got well home, with a peaceful mind, empty and low enough,
though not so as to be insensible of the powerful hand that had been over me for good,
and over all things else, to make them good to me.
In the midst of much bitter conflict, which has since been in wisdom dispensed,
it is a favor to have nothing to look back upon greatly
to grieve or condemn the poor tried spirit,
ready as it has been to halt, and to drink in discouragement; and in the feeling of it,
one is ready to exclaim,
how wonderful is the preservation and condescension handed to the poor instrument,
when it has thus given up all for the name of the Lord!--and yet on the other hand,
what weakness in any of the Lord's people can be greater than that which such feel;
so that every day and every way they would err and fall, and do evil,
were it not that an omnipotent power is ever near to uphold, to prevent and to restore!
The monthly meeting soon occurring, I returned my certificate to my own satisfaction,
and I believe that of my friends.

Tenth month.--Low times often: but out of the depths did I cry,
and He made these "`depths of the sea a way;`" He led me through them as on dry ground,
and showed me His wonders in them; so that I have been enabled to pass on,
leaving them behind, yes, leaving every thing past and to come, in his hands,
who can do all things for me.

New duties, new and arduous paths not cast up, no mark, no trace, no footing,
but just in His footsteps, who puts forth and goes before.
O! for a free, simple,
entire throwing myself into His care and keeping and disposal in all things,
now and evermore! for no one else can deliver or preserve, or carry through,
or enable to glorify Him, or bring about things,
that so they shall all redound to His praise.

[.offset]
+++[+++In the third month, 1826, he quitted his residence at Marazion,
and in the fifth month following, he again entered into the married state,
and settled at Alton, in Hampshire.]

Sixth month 22nd.--I have at times been almost ready to conclude it a vain thing,
to attempt in this way to commemorate the innumerable
blessings and mercies from day to day,
from week to week, from month to month, which have been heaped upon me;
and yet pure desires, I trust are at times known to arise,
that others may be induced to come, taste, and see,
how good the Lord is,--how wonderful are his dealings to the poorest,
most unworthy of his creatures.
Words cannot set forth what He is, and will ever remain to be,
towards those that trust in Him, and hope in his mercy;
and who still endeavor through all that may happen to them,--through all weaknesses,
repulses, temptations, and exercises,
to strive with a true heart to serve the God of their lives.

Oh! what has he wrought for me, more than in past times, if possible,
more than in years that have long passed over!
My removal out of Cornwall, my settlement in this allotment (Alton,) my many,
many comforts, a beloved and loving partner given me in the place of her,
that has been safely landed from this sea of troubles! how shall my
soul ever repeat all that God has wrought for me in these matters?
Yes, how has he preserved my goings out and my comings in,
my up-rising and my down-sitting; so that notwithstanding the many baitings, stumblings,
slippery and exceedingly difficult places,
the Lord has in good measure been my confidence, and kept my foot from being taken,
and my life from being smitten to the ground by the enemy.

He has made for me a way, where I could see none; he has made that to be possible; yes,
brought it to pass, which seemed impossible,-- and brought me safely through;
so that I can indeed yet praise him for his goodness.

[.embedded-content-document.letter]
--

[.letter-heading]
To E. S.

[.signed-section-context-open]
Alton, Fifth month, 1826.

[.salutation]
My dear Friend,

To say that my soul does tenderly and deeply
sympathize with you under your sore bereavement,
is saying little at such a time as this;
and yet well knowing how wonderfully the Divine compassions are extended in such an hour,
I cannot be anxious that my pen should be made helpful to you.
It is indeed a season when "`the powers of the world to come,`" and
the "`heavenly gift`" are to be tasted and deeply drunk of;
for whatever be the nature of man's extremity,
it is then the Lord is most inclined to draw near,
and manifest the excellency of his never-failing arm; inviting, no,
urging the sons of men to take refuge under his healing wing.
My belief is firm, that it is not only possible but easy,
through submission to this inward operation and aid,
for the soul to be raised above the outward, and settled in a holy calm,
where it can bless, and praise, and magnify through all, the name of Him,
who does all things well, and nothing in vain.
It will no doubt be your concern, as it is our duty,
to dwell on the various blessings connected with this painful dispensation;
that your dear wife should have reached her home, is one that strikes me forcibly.
But there is much of tenderness and gentleness in the Lord's severest dealings,
and in those which seem darkest or bitterest.

We know not the end and meaning of many designs, but they are developed by and by,
even to our own astonishment and satisfaction.

Yet in respect to these,
and all other indirect alleviations or abatements to the acuteness of feeling,
it may be said, at least for a time, in the language of Jeremiah,
"`When I would (thus) comfort myself against sorrow, my heart is faint in me.`"

Your dear little eldest child will often, I trust,
beguile away a heavy hour of musings and of mourning,
and take you from too selfish an indulgence in what has been termed,
'`the luxury of grief,`'--and help you also to cast an eye on the _future,_
rather than to dwell too much or unduly on the past,--and lift
your tried spirit out of the unprofitable depths of sorrow;
and her little prattle may sound like a call--
'`lead me to follow her you mourn.`'

O! What a spur to diligence,
to increased care in all the allotment of duty, does such a loss as you have sustained,
if rightly borne, bring with it.
If thus _I_ have been favored to see "`the end of the Lord,--that he is
very pitiful and of tender mercy,`" and that "`blessed are the dead
who die in him,`"--what shall I render,
and how shall I five,
and what shall I not endure for the sake of
"`so great salvation,`" so excellent a Savior.
Truly, dear E., I look for something out of all this;
for the Lord has done great things for you, as for _her,_ your precious partner;
and I cannot but think, you may lift up your head in hope,
and go on in the strength of the Lord.
For though many may be and must be our remaining tribulations, before it be said to us,
"`Your warfare is accomplished;`" yet while our dependence and
surrender of soul is maintained in even a small degree of simplicity.
He whom we serve will never leave nor forsake us,
nor fail to make good all that He has promised.

May the consolations of God be abundant with you;
and may nothing of this transitory world, whether heights or depths,
come between Him and you, to deprive you of the richness and fulness of his blessing,
yet poured on them that mourn.

My dear love attends you.
May we abound in grace, and every good fruit, even by abiding in the vine,
being often purged as fruit-bearing branches, and chastened as dear children.

Farewell, I remain your affectionate friend,

[.signed-section-signature]
John Barclay

--
