== Chapter XII.

+++[+++In the Eighth Month, 1826,
he informed his Monthly Meeting (Alton) of a religious
concern to visit the meetings of Friends in Scotland;
also, some other meetings in his way there and in returning: a certificate was granted,
and he left home on the 19th of that month,
taking the meetings of Newcastle and Edinburgh in his way; he then proceeded to Aberdeen,
and there attended the half-year`'s meeting.
The following are extracts from his letters written during this journey.]

[.small-break]
'''

25th of Eighth Month, 1826.--+++[+++From Edinburgh he writes:]
How poor do I feel,
and yet an engagement of heart in this line of duty--how humbling is it!
What but the power of Truth, livingly and fresh communicated can preserve,
much more enable to do any thing to the glory of God.
Oh, I feel my own childish growth,
as well as that inability we all share as men and creatures;
and I long that the Lord would be pleased to endue
me with more skill and capacity to advocate His cause,
as well as with simplicity to lay aside every weight, and keep clear of every snare.
Do often think of me for my good,
and help me with your most earnest fervent desires to the fountain thereof,
that I may be thoroughly furnished for every needful
time,--endued with wisdom and an understanding heart,
with clearness also of spiritual sense, and with might in the inner man.
The Lord direct my way and prosper it,
for He knows that in integrity I have sought His will only to do it.

Ury, near Stonehaven,
Ninth Month.--Our meetings (the General Meeting,) have been pretty large,
and much favoured with the manifestation of the ancient arm of power;
so that in the strength thereof a remnant could say,--"`one
generation shall praise your works to another,
and declare your glorious name and goodness.`"
I had, on First day morning, my time of silent admiration at this,
which is the Lord`'s doing; but in the afternoon meeting,
which was very largely attended by strangers,
I was led to stand up and open that great mystery, but to us most true ordinance,
of waiting on the Lord,--with the excellent benefits to be derived
from this practice in respect to spiritual attainments.
The people were very quiet and attentive, though still flocking in.
There were many Friends in the ministry who confirmed these things,
and further set forth the Christian life and doctrine.
Second day, the General Meeting was held,
when the Lord was pleased to appear among us to our great refreshment:
much instrumental labour was bestowed, especially on the unfaithful,
who were warned in a solemn manner again and again.

On Fifth day, I was at the Aberdeen meeting,
in which I had under a sweet feeling to encourage the little flock to hold on their way.
Oh, how preciously did the Lord work that day; I shall not easily forget it.

This place (Ury) has for some years been surprisingly improved, especially of late,
the walks and woods planted by the father of the present proprietor, are beautiful;
a bold rushing stream winds not far from the house, through a bed of rocks;
and the inequality of the ground is pleasing indeed.
It is a sweet spot.
The proprietor, Robert Barclay, received me very kindly, and welcomed me.
I am made very comfortable here, but must get through my business and be gone:
accordingly, I have this morning examined the library throughout,
and found already several interesting things; but the correspondence is what I want,
and hope to see.

On Second day, I completed my business here to my satisfaction,
having brought with me what was valuable.

16th, 4th day.--Was at Dunfermline, where a little solid company sit together:
none of them are yet acknowledged members.
The Lord was good to us, in bowing our hearts together low before him,
and I trust it was a favoured time; pretty much counsel was handed.
I thought there was evidently to be felt a good work upon some,
and I trust it will stand,
even in the face of a crooked and perverse generation
of professors of the Christian name,
among whom, living, powerful, operative religion is much needed.
On Fifth day, I attended the meeting at Edinburgh in course; I took my seat,
hardly knowing any besides the family in which I was received;
but the Lord gave me to labour abundantly,
for their arising out of their present low state: I rose early in the meeting,
going into things very particularly, laying before them the causes of weakness,
under which I apprehended they laboured;
with much more respecting the only sure foundation and resting place,
and what a building on this would make them:
The Lord was near to help,--blessed be his Name!

At Carlisle, I attended the meetings on First day;
wherein the great heavenly Shepherd`'s crook was extended, and his care was over us.
Oh, wonderful is the help handed to me, to do whatsoever I find to do.
Many hearts were I trust humbled that day; for the Lord was surely among us.
I met with some young plants, and made a call on a precious family,
and my heart was refreshed in the hope that they are bowing under the yoke of Christ.
I sometimes feel a temporary disadvantage in my youthful appearance,
until my Master makes way for me in the hearts of my friends.
I went to the Monthly Meeting held at Pardshaw,
a country meeting mentioned in George Fox`'s Journal as "`Pardshaw Cragg:`" here,
as I went, my friends pointed out the rock, where he preached among the mountains:
they also showed where John Burnyeat, John Banks, James Dickinson, and others lived.
At this meeting at Pardshaw the Lord was pleased this day to manifest his name,
and glorify it, which is as ointment poured forth: Oh, he worked marvellously,
giving His blessing and presence among us, who were a large company;
so that the flow of exhortation was as a mighty stream.
I felt the Lord to be very near, and my poor spirit was greatly refreshed;
and my soul somewhat filled with their company: but I find day by day,
that former things must be left, and not rested in,
that the mind may be free and unshackled against the next service.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to E. H.

[.signed-section-context-open]
Edinburgh, 14th of Ninth Month, 1826.

[.salutation]
My beloved Friend,

On the receipt of your account respecting our endeared companion,
who is gone before to his rest and reward,
my heart was wonderfully helped to a degree of quiet acquiescence
in the blessed purposes of Divine wisdom and goodness;
so that though few,
very few were nearer to me than he among the flock of the faithful in Christ Jesus,
I could not hold him on this side the grave;
but seemed entirely prepared and resigned to lose him, as to the outward;
well knowing our oneness was not to be destroyed by death.
Ah! dear +++_______+++, when we can look with anointed eyes on these things,
and are permitted to enter into the purposes and will of our heavenly Father,
whose ways are higher than ours, who does all things well,
nor any thing in vain,--what a favour, what a mercy is it,
that the message is given to the quickened soul,
"`Time to you here is no longer,`"--"`Come up here.`"
Oh, what a release, what a dismissal, what an enlargement to the poor tribulated spirit,
labouring amidst temptations and the assaults of the prince of darkness, yes,
amidst many infirmities, afflictions and doubtings:
but how unutterably awful is the voice of warning conveyed in this dispensation to others,
among whom that dear servant has gone testifying
in his life-time of the powers of the world to come,
and of the terms on which alone the gates of heaven are opened.
Surely, my soul said, on first hearing of his illness, this was a seal to his testimony,
and a crown to his labours of love, which the Lord has set; and let his will be done.
And now how is such a circumstance calculated to bind us who remain, one unto another,
and above all,
to the great Head of the church,--to stimulate us to an earnest heed to
the things that make for such peace as our beloved Edmund +++[+++Janson]
had, and is centred in;--for here is a fresh and indisputable evidence,
that "`these things are faithful and true,`"--that "`the Lord is at hand,`"
and watches over us for good,--that "`verily there is a reward for the
righteous,`"--that "`in due season even we shall reap,
if we faint not.`"
My heart flows in gratitude to the fountain of good,
in remembering all that He wrought for our dear E.; for truly the Lord was with him,
whatever were his snares or infirmities in common with many of us: my prayer is,
"`let my last end be like his;`" let me only get to the
end of this appointed warfare safely as he has!
There is a blessing upon those who hold fast the beginning
of their confidence in the Lord steadfast to the end;
who mourn not as those that have no hope: for as certainly as he who is taken from us,
has "`received the end of his hope,
even the salvation of his soul,`" so in due season they also shall surely reap,
who faint not; their tribulation will work patience;
and though they cannot as yet go to him,
yet those who follow the Lamb whithersoever He goes,
after their measure and testimony for Him is filled up, we well know,
will have of Him a place prepared for them.--Wherefore the language runs in me,
"`let not your hearts be troubled, neither let them be afraid.`"

My mind is often raised secretly in supplication,
that this dispensation may prove the raising of some
from their graves in a spiritual sense,
to glorify the God of their lives, (in whose hands their very breath is,) both in body,
soul and spirit.
For the Lord has spoken to them by his servants as yet much in vain;
and he has now given them a sign and token of what He can do,
by even snatching them from the earth, it may be in anger and not in mercy,
unless they repent and turn speedily, yes wholly unto Him.

I have been to the meetings in Scotland with certificate.
The Good Master is tender to me a poor creature;
and while sufficient strength seems to come in every needful hour,
I have nothing to spare, being borne along through heavy conflicts and deep baptisms.

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to L. C.

[.signed-section-context-open]
Wellingborough, 3rd of Tenth Month, 1826.

[.salutation]
My dear Friend,

Truly the feeling of love towards my many dear friends in Cornwall is so expanded,
that I thought it nearly impossible to confine my address to anyone in particular;
from there discouragement ensued,--general epistles being much out of date now-a-days.
But Oh, how often do I think of some in particular in your district;
yet longing for the preservation, yes, the growth of all.
What a noble company is the Captain of our salvation seeking to gather;
how glorious would be his arising among you,
designed indeed to form part of his "`army with banners,`"
and called to be more than conquerors through Him.
The Lord remains to be to his devoted servants the same yesterday, today, and forever,
unless they withdraw from his service: the Lamb and his followers shall now, as ever,
have the victory.
But some are ready to say with one of old, even to the mothers in Israel,
"`Except you go with me,
I will not go down;`" and the answer to such must
be expected to prove not altogether to their honour:
for such look too much to the poor prophetesses,
instead of diligently setting themselves about their own business,--which is, indeed,
to fight the good fight of faith.
The example of dedication set by many in Cornwall, oftentimes refreshes me;
and the more I think of them in this way,
the more I long that they may "`abound more and more;`"
for yet these many privileges and surely gracious visitations,
are to be improved accordingly.

I may now tell you how wonderfully the Lord`'s mercy has encompassed me about,
and his aid been afforded me in every hour of need; enabling me to do, I trust,
his will in some small measure,
while in this awful engagement of visiting the churches
in the love of the great Head thereof.
Oh, my heart overflows, when I think how great has been the condescension vouchsafed;
whereby preservation has been hitherto known in good
degree from the devices of the enemy,
and under all the discouragements and provings of the day, which are very many; yes,
strength has been known at times boldly and largely to advocate the good and great cause,
and to testify of that grace by which we must be
saved through faith in its operation in the soul.
I have been at all the meetings in Scotland, and at several of them more than once,
and have taken some others both in going and returning:
they have generally been to my great relief and comfort, and I trust, lasting benefit;
so that my soul is in degree qualified to utter the
language,--"`Oh, how great is Your goodness,
which you have laid up for them that desire to fear, serve, suffer for,
and trust in You!`"
How thankful ought we to be, dear friend, for all the mercies still handed to us,
even day by day; and Oh, how ought we to walk before Him, who thus deals with us!

--

[.offset]
+++[+++He returned home the 6th of Tenth Month, 1826,
having attended the meetings in Cumberland, York Quarterly Meeting,
and some meetings in Northamptonshire.]

1827, Third Month.--Attended our Spring Quarterly Meeting at Poole,
and the Monthly Meeting there; also our own at Andover in course.
At the latter, we had the company of dear H. and M. M.,
who had then completed a visit to the families of Friends in our Monthly Meeting;
in which engagement, as far as regards the sittings with the families in this place.
I joined them, and had comfort therein, it being remarkably brought about,
agreeably to my anticipation.
How gracious and tender towards me was my heavenly Father, the Head of his church,
in this opening; making a way where no way appeared, and safely leading me forth;
so that I trust in this little, but to me arduous service,
I could acknowledge that the Lord was near and helped.

1827, Fifth Month.--I was favoured to attend all the sittings of the Yearly Meeting.
We had very agreeably the company of dear William and R. Byrd,
on a religious visit to the families of Friends in our Quarterly
Meeting:--they stayed with us some days,
and the opportunity in our family may my soul ever remember, and take encouragement from,
and bless with reverence and humility the name of the Lord.

1827, Eighth Month.--My mouth, as a minister, has been so laid in the dust,
that I know not what to think of it;
my soul has been now a long time plunged into varied
discouragements respecting my spiritual condition,
so that I know not where this dispensation will end.
O Lord! preserve and sustain and redeem my poor soul!

1827, Ninth Month 11th.--Left home with certificate granted me by our Monthly Meeting,
to visit the meetings in Berkshire, Bedfordshire and Herts,
Buckinghamshire and Northamptonshire.

[.offset]
+++[+++Extracts from his letters written when on this service, are here subjoined.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Wycombe, 20th of Ninth Month, 1827.

We reached Reading in time for the Select Meeting,
where was T. B. I was favoured to my unspeakable comfort,
to break through the load by which I have seemed to be enveloped for a long season,
and had to declare of the goodness of the Lord,
in I trust some thing of the simplicity of the gospel, greatly to my peace of mind;
that season appearing like an earnest of future help and guidance.
J+++.+++ P. was there, and he and I went hand-in-hand,
being greatly favoured in being so one in our line of labour.
The next day, I had in some degree to take the lead; others confirmed the word,
to my humbling admiration at the condescension and wisdom of our Holy Head.
On sitting down in the second meeting,
a sudden exercise came over me about going into the women`'s meeting,
which endeavouring well to sift, I thought it might be passed by,
unless some other had a similar feeling; when presently after, J. P. rose,
and said he had such a concern, though without a certificate; he knew not why,
but wished to leave it with Friends: they fell in with it,
and then I named how it had been with me; when it was fully united with.
We went; and I trust the work of the Lord prospered by our giving up thereto.
I have been favoured to get along very simply, without reasonings, forethought,
or after reckonings; all is made good to me, and my soul dwells in a calm, easy way,
not over careful about any thing.
The Lord does all things well in and for me, and I have no lack;
though nothing to boast of, yet nothing to complain of,--blessed be the name of the Lord:
and may your soul continue in this acknowledgment, yes more and more;
for what can we render?
Time would fail me to say all I could of his mercy to me, even these few days back;
so that I hope I may humbly say, all is well, and that I am in the line of duty.
My prayer is, that when favoured to meet again,
we may be enabled to build one another up in everything good;
and more and more abound therein, to our mutual comfort, to the animating of others,
and to the praise of Him who has done great things for us, in helping and sustaining;
so that we have not been utterly consumed, though deserving nothing short of it.
Farewell.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to M. B.

[.signed-section-context-open]
Berkhamstead, 25th of Ninth Month, 1827.

I feel oftentimes a very poor creature; but we are not our own,
nor have we any real occasion of regret or discouragement,
that we have given up all for the sake of Him, by whom we enjoy all things.
It is a great favour that I am enabled to say, the Lord has helped me on my way.

On Sixth day, I went to Chesham meeting:
I trust the Lord was among us there in an eminent degree;
nor do I recollect often being so enlarged in the heavenly gift.
Oh, may the word have entrance and prosper, among a backsliding and halting generation.
That evening we returned as far as Amersham, having a meeting there with Friends.

On Seventh day, we went by Jordan`'s meetinghouse;
it is well known as the burial place of William Penn, Isaac Penington,
and Thomas Ellwood;--a secret solitude in the midst of a woody and hilly district.
I saw some original letters of Isaac Penington, etc.

On First day morning, I attended Wycombe meeting,
and was favoured to declare the Truth without fear of man.
That evening we reached this place (Berkhamstead,) a newly settled meeting,
and were comforted, I hope, together.
Yesterday, we went to Hemel Hempstead, an appointed meeting, and returned here.
My health is preserved, but at the end of some days`' work, I feel much wearied;
it is a comfort to have some evidence, that, however small my measure of labour,
it is nearly as much as my frame is equal to; yet the Lord makes up all.

--

1827, Tenth Month 7th.--First day, I attended the meetings at Devonshire House;
was silent in both: glory be to the great name!

First day, the 14th.--Attended the meetings at Uxbridge, on the 17th,
the Monthly Meeting; and on Second day following,
I reached our comfortable home at Alton, through the matchless condescension, goodness,
and forbearance of my Maker, Preserver, and Redeemer!

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Alton, 15th of Twelfth Month, 1827.

Be assured you have my very tender sympathy under
the important circumstances your letter unfolds;
and that my best, though feeble desires are, and will be, for your best welfare.
I cannot doubt but preservation and sufficient help will be extended, while a simple,
upright, unreserved surrender of the will is sought after and abode in.
I have thought, in a case of this kind, there is always abundant condescension,
gentleness, forbearance and long-suffering,
manifested towards us poor fallible creatures.
He that puts forth and goes before us, knows our frame, and himself took our infirmities:
when we take a step a little awkwardly, or with too much forwardness, or mistakingly,
mercy is near to hold us up and restore us; so long as we are not wilful,
but singly desire to be right in our movements.
We may be, and some of us know we have been, long borne with, in much that borders on,
and indeed proves to be, little better than thorough unbelief and disobedience.
We read that "`rebellion is as the sin of witchcraft:`"
we may have held back on different grounds,
very reasonably as we have thought:
but we have been chastised for this,--leanness and feebleness have come over us,
so that when we would afterwards have given up, the Divine sense, strength,
and blessing has receded:--neither have we enjoyed the answer of, "`Well done.`"
Our situation perhaps has somewhat resembled that of the Israelites, who after refusing,
attempted to enter the promised land: there is, nevertheless, forgiveness with Him,
that he may be rightly feared,--and also plenteous redemption.
I believe we are safe in resting under a holy, simple fear and caution,
as to so awful a proceeding as the first exercise of the ministry;
but how far this should be carried, cannot well be defined for another:
vessels are variously moulded,
and variously dealt with or used;--there may be too much of this
as well as too little,--for our snares and our tendencies differ.
Even though we wait for what we may suppose only
adequate strength and clearness for the occasion,
this may stand in the way of our having that degree of it, which was intended for us,
had we used more self-renunciation, or been more disinterested in our service.
It is plain,
we are not to expect to have just what evidence would please or satisfy our own feelings,
which may have become somewhat morbid by dwelling on things too much.
Ah! the simplicity of a true babe in Christ is what we need most,
far more than that kind of assurance we covet thus greatly:
a little of this goes a great way; it is the faith which pleases God,
and removes the mountains; and by which we are to walk, rather than by sight:
it leads to look not at self with anxiety,
how we shall be provided either with discernment, courage, or what else is needed;
but to rest in the Lord, and cast our burden on him, knowing he is ready to sustain such,
so that they shall lack nothing; nor are they much moved by what arises to perplex,
discourage, or prove them,--trusting over all in never-failing goodness.

I hope if what is now handed, should feel to you to be as a word in season,
and in any wise coming from the right source,
you will not hesitate to accept it through the fear of leaning on man.
I consider that when instruments are rightly engaged for the help of others,
they act not in their own name: such are ordained and needful in the church;
and if our eye be single to the great Head, the giver of every good and perfect gift,
and to his inward appearing and sense as to what comes through others,
we shall not be in danger of hurt,--bearing always in mind his injunction,
"`Take heed __how__ you hear.`"

--
