== Chapter XIII.

Second month 9th, 1828, (Alton.)--Thus far brought on my way,
through the gracious condescending care and preservation of my God.
Since I last wrote in this rough Memorial,
how much do I owe for all the mercies poured upon me every day!
Disease has prevailed all around;
some of our acquaintance cut down in the midst of youth and health:
why are we so dealt with, even in this one respect; and why in all others so blessed?
O! is it that we walk more acceptably before the Lord,
than those that may have been less privileged than ourselves?
No, far from it! who so worthless, so graceless,
in proportion to the talent bestowed as myself,
in dedication either in my family or in the church!
O! how the enemy wounds and smites my life down
to the ground! so that my faith is ready to fail,
and mine eye in looking upward.
To whom shall I go, to whom flee in every conflict,
if not to the only resource and refuge?
O! that my poor cry may be regarded,--'` Let not the enemy vaunt and
triumph over me;--let not that which you have begun in me,
O Lord! the author and giver of all good, be evilly spoken of;
and they that hate me rejoice when I am moved.`' O God! the strength, the power,
the victory are yours;
let me at this time return you thanks out of a humbled and honest heart,
for what you have hitherto effected,
in drawing me out of darkness into your marvelous light.
O! let me hope, that you will henceforth preserve, guide, and uphold my poor soul,
amidst the sea of temptation and conflict,
in which you may permit me again and again to be plunged.
Let me trust you for mercy, renewed pardon,--and plenteous redemption, yes,
for victory over all my besetments and weaknesses;
so that I may put on strength in your invincible name,
and under your holy banner make war in righteousness, against the world, the flesh,
and the devil.
O Lord! thus undertake and overcome for me, who cannot do any thing without you.
You have been my help; leave me not, neither forsake me, O! God of my salvation.
Break my bonds, I beseech you, and loose my captive spirit,
which through your grace longs for deliverance more and more;--
nothing can satisfy my cravings but your unbounded goodness.

Fifth month 18th.--First-day, during the yearly meeting:--every meeting day, yes,
every day, every hour of my life do I stand in the presence of Him,
who is the God of the spirits of all flesh, the Master of the assemblies of the faithful.
King of saints, the Judge of all the earth! "`Fear you not me?
says the Lord!`"

[.embedded-content-document.letter]
--

[.letter-heading]
To An Unknown Recipient

[.signed-section-context-open]
Alton, 29th of Fifth month, 1829.

Our quarterly and monthly meetings were seasons of sadness and depression,
as you may suppose: but some of us were given,
through and over all dismay and affliction, to trust and to cling to _that,_
which yet remains an immovable rock and refuge;
and therein to rejoice and be thankful on many accounts, though in tribulation.
Surely, the effect of such shakings and provings of the foundation,
whether it be the true one, and whether we be rightly established and preserved on it,
must be ultimately strengthening and beneficial,
at least to a remnant in our poor Society,
who desire in some degree of sincerity to be searched and tried,
and to be purified even seven times.

--

[.asterism]
'''

+++[+++In the ninth month of this year, 1829, he removed to Croydon,
within the compass of London and Middlesex quarterly meeting:
he had been much engaged in the preparation of works for the press,
and he believed the neighborhood of London would
afford him great facilities for such engagements.
One work which occasioned him great labor about this period,
was the _Diary of Alexander Jaffray,_
the original manuscript of which he had discovered at
Ury in Scotland;--the deciphering of this manuscript,
as well as its preparation for the press, called for much laborious exertion:
memoranda frequently occur in his private note book,
of his being engaged '`at Jaffray,`' '`seven`' to even '`nine hours`' a day.
And though it may be feared such close application was
prejudicial to his health and delicate constitution,
nevertheless he would often say,
that he believed it to be a line of service marked out for him by the Divine hand.

In the eighth month, 1830,
he obtained a certificate from his monthly meeting (Kingston,) for religious service,
in the quarterly meeting of Dorset and Hants, his concern being to visit the meetings,
as well as the families generally; with liberty to include the counties of Kent,
Sussex and Surry, if Truth should open the way.

In the first month, 1881, he returned the certificate,
at the same time acknowledging the gracious dealings of the Lord,
in supporting him through this engagement, and in granting the sweet incomes of peace.

The following are brief extracts from some of his letters,
written during this engagement,]

[.small-break]
'''

Alton, 22nd of eighth month,
1830.--Having now got through this part of our humiliating path,^
footnote:[He was united with his friend J. F. Marsh in the service.]
and being about to depart on the morrow,
I thought I might attempt a few lines to tell you that we got well here;
and we have been so closely engaged,
as indeed hardly to leave time for conversation with Friends,
or for relaxation of any sort.
It is humbling work indeed, and I have been so low,
that it seemed as if I should not have held out; but the water seems turned into wine,
beyond all expectation, I have not been silent in any sitting,
though nearly so in both meetings this day.
Oh! may the Lord continue unto us strength and wisdom; and if it be His will,
may He enlarge my poor soul a little, to testify and sing of his power.

Southampton, 25th.--Though I cannot say any thing of heights or of abundance,
yet sufficient strength and ability seem vouchsafed to my poor soul,
to raise it to a degree of cheerfulness, and of reverent thankfulness.
I find wonderful condescension and support administered in all times of need,
though the path is a very humiliating one.

Poole, 30th.--The good Master, whom we are longing to serve, though in abundant weakness,
is not lacking to extend his help in every needful season; so that from time to time,
He raises the acknowledgment of gratitude,
and renews the desire to be entirely resigned to His will and disposal.
We have been kindly received everywhere,
and I trust have been preserved from hurting the good cause, or those that love it.
My health and spirits are tolerable; and though the weight of things feels awful,
yet eyeing the Lord's mercy, I seem lifted over selfishness in some degree,
and am careful for nothing.

Horsham, 1st of Tenth month, 1830.
I trust I do feel, however inadequately,
that it is through renewed mercy and favor I am here,
and again made willing to do and to suffer, whatever may be meted out for me,
if it be but for the Lord's precious cause and to His glory.
O! says my soul, that the dwelling of each one of us may be so near the right spot,
that we may not only truly and fully discern, but appreciate,
what may make for our own peace, and our progress heavenward.

However heavily the hand of the Lord may in any wise be laid upon us, is it not for good,
and should we not even kiss it, as well as bear and submit?
It is but little, very little, that we can give up, and but for a short season, unto Him,
who has given us all things that we hold dear: O! then,
that we may prize and cherish the privilege of lending to the Lord;
who will assuredly love the cheerful giver,
and restore and enhance his own gifts to such with increase.

We have had a sweet, precious, uniting season together this day, not only in meeting,
but since; and though with myself it has not been a high day,
yet I have been sensible of that which has stayed and sustained,
and even animated my soul to run on with patience,
I am intending to be on first-day at Godalming, at the interment of a Friend,
whose awfully sudden removal will be affecting to you:
when sitting at dinner with her family, she was smitten as it were in a moment,
and was a corpse in a very few minutes:
I understand a striking silence prevailed with them,
from the time they sat down at table.

Guilford, 6th of Tenth month, 1830.
Since I wrote last, I have been favored to get along comfortably,
having been well in health and spirits, cheerful in mind,
and wound up in some good degree, I humbly trust, to my business, from hour to hour.
I have been enabled to go through what has come before me as duty, even with alacrity;
so that often the acknowledgment has arisen,
"`By you I have run through a troop, and leaped over a wall.`"

Do not, however, suppose that I am unduly elevated; but am rather preserved in a calm,
steady trust, and in resignation to the Lord and to His disposal;
desiring only to do all his good pleasure,
or that it may be fulfilled and accomplished in me; ever bearing in mind,
that I am not yet (so far as I can see of the future) putting off the armor or harness,
but have still to fight and to labor still to keep under this poor frail body;
and in soul and spirit also to seek to be sustained and
subjected in all things unto the end.

I attended the monthly meeting at Horsham, on seventh-day,
and was (notwithstanding the flow of doctrine and exhortation we had
had the day before) led pretty largely to testify among Friends.
I proceeded to Godalming on first-day morning, where the interment was to take place.
I concluded to join the mourners at dinner, and attended their evening meeting.
We commenced the next morning visiting the families, which we have now concluded,
much to my relief and satisfaction;
after much exercise and endeavor for a long season to
know what might be best as to this service,
and as to the time, I believe that I have been well directed thus far.
I feel that the Lord will fulfill his precious promises,
and be unto me all I stand in need of, while I look unto Him in simplicity and faith,
striving to obey Him.

Folkstone, 13th of twelfth month.--We have now completed at Dover,
and have entered this day into our labor here.
O! surely the Lord is no hard master, and sends not any forth at their own charges;
but is very graciously disposed to fit out according to his own purposes:
thus are removed all sufficiency or dependence on any thing
short of the fresh and humbling ability that He gives.
We have had some precious seasons, reviving to our drooping spirits,
when even at the lowest ebb; and we are bound to rejoice and give thanks,
and go on our way in faith, with alacrity, and patience of soul, come what may.

Canterbury, 18th.--I hope I may again say, notwithstanding low and trying seasons,
we are favored to proceed comfortably on our errand; feeling where our anchorage is,
and what we have alone to lean upon.
We have been led into some strait places;
but have always found in the hour of extremity that which has carried us through.
O! it is a comfort, beyond what I can set forth, to be quitting a place,
and feeling there is nothing to regret having done or not done.
We have had some very precious times, and some have been remarkably melted down,
in I trust true contrition.

[.offset]
+++[+++He was favored to return home from this close and laborious service in peace,
the 25th of twelfth month, 1830.]

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Second month, 1831.

While writing, I cannot well forbear expressing something of the sense I often have,
of your deep unremitted interest in the welfare of our Society,
and the sympathy which I believe, very many besides myself, feel towards and with you,
under the many exercises and engagements that are your portion,
and which may be said nearly to absorb the whole man.
I trust it will not prove unwelcome,
if I venture to say how I have longed that your hands
may be strengthened according to all your need.
No doubt you have at times occasions of dismay and discouragement on various accounts:
but it is consoling and animating,
to have the truth of the declared decree sealed afresh to our wearied spirits,
"`yet have I set my king upon my holy hill of Zion;`" and
again,--"`the enemies of the Lord shall be as the fat of lambs,
into smoke shall they consume away.`"
Be assured there are many with you,
(and with others that desire to be true-hearted laborers,)
when and wherein you little thinkest this to be the case:
and though the fathers and mothers in our Israel be removed, without any doubt,
it is the same almighty, all-wise hand, who removes these,
that is able of the stones to raise up children.

It is often remarkable, how from time to time the Head of the church,
possibly after a time of treading down and humiliation,
raises up instruments and aids in all the different offices, one here and another there;
even so,
that we cannot find any cause to murmur against "`the good man
of the house,`" although it be according to His own purposes,
grace, and goodwill,
and not according to our mere human apprehensions of what would be best.
Thus he renews the face of his earth spiritually,
and brings forth a song in the hearts of his children,
somewhat similar to those beautiful words in Psalm 89: 6-8, 16, 17 verses.
"`Who in the heaven can be compared unto the Lord,`" etc.

--

1831.--O! the glory,
the excellency of the power and wisdom and truth of our God and Savior!
How was he manifested, and his grace and goodness, and plenteous redemption,
when the groans and cries of some of his poor oppressed and exercised ones
went up as mingled clouds of incense! "`For the sighing of the poor,
for the cry of the needy now will I arise, says the Lord.`"
When things are apparently at the lowest,--when
our prayers seem to return into our own bosom;
when the heavens are wrapt in thick folded curtains of darkness,
then the coming of the Lord on high is often as the vivid lightning,
enlightening the skies, from the east to the west; in effect declaring to poor mortals,
that it is He alone who can create light and darkness,-- can
cause the light to shine in and out of darkness,--and can turn
the night season spiritually into the noon-day.

First month 14th, 1832.--Employed on Jaffray nine hours.
Some days this week, I was exceedingly stripped, low, and tempted, almost beyond measure:
but on fourth-day, had a good meeting,
and a sweet silent opportunity with a young person who has applied for membership.
These words were impressed on my mind; "`If you abide in me, and my words abide in you,
you shall ask what you will, and it shall be done unto you.`"

Fifth month 21st.--I resume these notes, and it is under a sense,
greater if possible than ever,
of my incompetency to set forth my many feelings and exercises,
either in reference to my own condition,
or that of the gathered church with whom I associate,
I cannot recur in this place to what has transpired,
since I last wrote in this little book; suffice it to say,
my soul does feebly desire to bless the great name of the Lord, my Savior,
for the very thought and hope now presented before me--that because He lives,
I live also.

To be preserved alive in the Truth unto this day,
and once more to meet with and recognize my friends in the Truth, in the life of it;
this is indeed a favor.
And to be given to know, in any measure, what has aimed at the life,
and is yet seeking to devour,
leads to some hope of a complete deliverance from the snares of death.
Ever since I have attended this yearly meeting,
my mind has been deeply exercised according to
my capacity for the welfare of this people.
As I proceed in my pilgrimage, I trust my confidence is increasing,
that the great "`I AM,`" the King of Zion, still reigns,
and will reign to the overthrow of all his enemies;
and that He alone is equal to take care of his church,
and to overrule all things for the good of his little dependent ones.

Yet, O I how awful do the times appear in which we live;
and how awfully critical is our standing among the various professions around us.
Doubtless, it always has been so, perhaps more so,
than those of any particular age may have thought.
Every period has had its dangers, its temptations, its responsibilities.

Yet surely ours are, if not new, very specious snares; and when I look around,
I am ready to think, who, even among the highest in knowledge, in faith, or in gifts,
is not fearfully liable to fall into some of these snares.
O! I have this day seen, as I think, in the light of the Lord,
the enemy endeavoring to deceive, if it be possible, the very elect.

There are baits already laid, golden baits, which, if they are not seen and shunned,
will even devour those who devour them.
I see not how some, who now take the lead amongst us,
will or can escape being carried away, as with a sweeping flood,
by that which hey are now swimming in; unless the Lord prevent,
I see not how this Society can escape being landed, yes stranded, on a rock.
Every day, every fresh occasion of witnessing the spirit and proceedings of these times,
convinces me beyond all hesitation,
that we are fast verging to a crisis,--an alarming crisis, and a shaking sifting crisis,
when every foundation will be discovered, every covering removed.
And though many will say, "`Lo here is Christ, and lo there!`" is he not with us,
and do we not own him and follow him?
Yet a clean separation will take place between the chaff and the wheat,
and nothing will be able to endure the refining heat of that day, beside the beaten gold.
O! how loose, how crude, how mixed are the views of many: how accommodating,
how shifting is the ground they stand upon; how lofty and superficial is their edifice,
though beautiful, and apparently solid also.
O! for more humiliation, fasting, waiting!
O! for less activity, less self-conceit, less taking of the name of Christ in vain!
May such a view of things conduce to drive and keep me yet
nearer to the Source of all safety and of all succor;
that I may abide in Him, and grow up in Him in all things who is the Head!^
footnote:[These remarks will doubtless appear the more striking to those readers,
who can recall to mind the circumstances of the Society in the
next and the succeeding three or four years more especially:
the publication of the work called the Beacon,
which occasioned so much painful excitement in the Society,
occurred about the beginning of 1835.]

[.offset]
+++[+++In the spring of 1833,
he was first attacked with an inflammatory complaint in the knee-joint,
brought on by a longer walk than usual,
but aggravated it was believed by a depressed state of constitution,
consequent in some degree on his too close application to the Diary of Alexander Jaffray,
etc.,--this left a weakness upon him so as never after
to be able to take his former portion of exercise,
on which he had felt his general health so much depended;
the limb was kept for some time under surgical care,
and many means were resorted to for its restoration, but without success.]

[.embedded-content-document.letter]
--

[.letter-heading]
To E. J.

[.signed-section-context-open]
Croydon, 17th of Eighth month, 1833.

[.salutation]
My dear Friend,

I must not longer omit assuring you of the acceptance of your letter,
which was truly cordial to me; evincing that your mind through all changes has remained,
as I trust, firmly anchored on that Rock which cannot be removed;
and comfortably proving to me, what I sometimes seem almost unable to assume, that,
my own poor tossed bark is yet preserved on the top of the waters,
and this by the skillful hand of the unerring pilot.
Truly it is reviving to know, that we have companions in this wilderness and warfare;
that we do indeed mutually desire to walk together by
the same rule and to mind the same thing;
and that no temptation or strange thing has happened, or is happening to us,
but what is common to men, yes, even the best; and that above all,
He is with us who can alone do all things for us,
and enable us to endure all things through faith,
of which He is the author and the finisher.

I earnestly trust that your mind is too much one with the wrestling seed of Christ,
to allow you to be in any way moved away from the humbling
engagement of filling up your measure of usefulness,
in whatever way may yet remain for you, or be pointed out;
even that you are endeavoring to be looking right on,
turning neither to the right hand nor to the left; allowing nothing overmuch to absorb,
disquiet, perplex, or divert you from that which makes for peace;
and pursuing the simple path of duty, wherever it may lead.

Ah! how easy to prescribe all this,--how difficult to get to that spot and to keep there,
where the yoke, the burden, the commandment are known and felt to be easy, light,
and most pleasant.

[.signed-section-closing]
I rest as ever your affectionate friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Croydon, Tenth month, 1833.

Your letter, my dear friend, I believe I have never acknowledged;
but be assured it was in all its parts very acceptable,
although it conveyed tidings of a truly mournful aspect.

These things, however, must be expected, and those who are entering into discipleship,
must bear to hear of what the Master forewarns them they must endure.
Though they "`hear of wars, and rumors of wars, men's hearts failing them for fear,
and for looking after those things`" that await, etc.,
yet "`see that you be not troubled;`" and
"`in your patience possess you your souls,`"
is still the watch word of perfect and divine Wisdom,
coincident with the blessed experience of the Psalmist,--
"`My heart is fixed, trusting in the Lord;`"
by whom the very hairs of the head are numbered,
and every thing overruled for the good of his chosen, now as ever!
And they are directed in all their movements, so far as the Master has need of them,
in steadying the ark, or bearing it aright, without over much anxiety;
trusting themselves and their cause, which is his, to his own keeping.

We have signs of the times enough to assure us that there is that at work in our Society,
which if not averted, may beguile and corrupt, if not shake us as in a sieve,
till we be reduced to a little remnant.
O! that we may individually be concerned to know the will of our Master;
doing neither more nor less, acting only in the obedience of faith, making faith perfect,
as says the apostle James.

Farewell, my dear friend: think of me for good, that I may hold out to the end safely.

John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To John Wilbur

[.salutation]
Croydon, 5th of Tenth month, 1834.

Most fully do I and many more unite in all you have conveyed in your last;
and especially in those clear views you have received to give
forth (as I believe) relative to the state of the church.
My heart salutes you, and bids you God speed on your journey, travail, and service;
desiring that no man, nor thing, may hinder you from doing all that you have to do,
in your measure and in your day, for Him and his glory, for his cause and people,
while life and strength are graciously vouchsafed.

O! how often have I remembered you, and thought of you,
as one whom the Lord has made use of in an eminent manner,
to uncover and bring out to view the working of the wily enemy, as it is this day;
and to manifest the path of the Just One, and the work of God in and among his people.
As surely as I believe the views, which we have ever held, to be according to Truth,
so I believe, that many up and down are preparing to acknowledge and embrace them;
and that the old fashioned testimonies which are upheld in our early

Friends`' writings, will come to be admired and sought out.
O! surely, there is a goodly company without our pale,
who may even take the places and the crowns of those,
(be they who they may within the camp,) that desert the cause,
which once was dear to them, and which they honored, but who now seek to undermine,
lay waste, or make of none effect; endeavoring also to lower the standard,
and make it square with their own notions and practice.
It seems to me,
that the snares and temptations are more and more seen through by Friends at large,
especially the lowly, contrite, little, teachable ones--the poor of the flock.

I have been absent from home three months this summer in Cornwall, etc.,
having liberty for religious service among Friends, as way might open;
and found myself obliged to join hands with a beloved Friend,
in visiting the families of Falmouth monthly meeting.
I have had much occasion to notice, that,
though the standing of many seems in slippery places and on shifting ground,
and many of understanding may yet fall, there is nevertheless a worthy remnant,
whose hands, though hanging down,
I trust will not let go their hold of that which they have truly handled,
and which they know to be their only hope, strength and safety.
No convulsion apparently awaits us, it might be better for us if it were so;--no, no;
the enemy is wiser than to foment this:
only let us be induced to give up the true foundation for another,
and he promises so gently and peaceably to glide us on it, that we shall not know it;
except that it will be less rugged and hard to
flesh and blood without any cross or struggle;
and there shall be nothing taken from us that we may affect to prize,
such as our customs and traditions, our church system,
and so forth,--nothing shall be disturbed of all this; and all the professors,
and the world too, shall love us the better.

How instructive it is to see,
that the most eminently gifted instruments are only really useful,
while in the Divine hand and ordering;
and that the Almighty is not bound to work by them, but as he sees meet:
and he can raise up striplings, that no flesh should glory!
It is the distinguishing feature of this heresy, that it runs among the rich,
and the great, and learned, and the eloquent, and the gifted, and experienced.
O! that all who are not with us would even go out from us, and show their true colors;
it would be more honorable, than to be endeavoring to insinuate something else among us,
which our fathers could not, neither can we adopt,--no, which we protested against,
and came out from, when we became a people.

Your affectionate remembrance of us is very precious; and it is our sincere desire,
that you will continue to think of us for good,
who often feel very sensible what poor unworthy unprofitable things we are,
and how we are borne with and favored!
Farewell, my beloved friend; may the Most High be our shield and exceeding great reward,
and a very present help in trouble!

[.signed-section-signature]
John Barclay

--
