== Chapter XIV.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to C. P. A.

[.signed-section-context-open]
Croydon, Tenth Month, 1834.

[.salutation]
My beloved Friends,

I am ready to believe you would not attribute my silence to neglect or lack of feeling,
were I even longer to forbear to communicate by pen and ink.
I trust we are too much like epistles written in one another`'s hearts,
that this should have place.
Be assured, however, that it is very pleasant to me to salute you from my home.

I visited dear William Byrd, and found him comfortable in mind;
he had lately been taken into the garden,
and was placed by the grave of his wife for a short time.
I thought him more bright, and clear, and collected in his faculties and memory,
than when his wife was living.
The retrospect of my journey, leaves me nothing but peace hitherto;
and my only disquietude is, lest I should not duly estimate this blessing,
with those also that have attended me throughout.
I think nothing has failed,
of what it seemed given me to expect beforehand would be allotted and meted out.
It has been an instructive humbling time; and in this I rejoice greatly,
for there is no state, I so desire to be preserved in, as that of pure dependence, fear,
and tenderness of spirit.
I gave in my report to our Monthly Meeting,
and endeavoured to stir up the poor flagging mind to faith, zeal, and love;
but things are flat now-a-day: sometimes under a sense of it, one is ready to say,
"`My soul is sick with sighing,`" and "`Oh! that
I had in the wilderness a lodging place,`" etc.
Yet at other times, when favoured to rise above a selfish interest and anxiety,
one cannot but see it is very needful there should be a falling away first,
that the man of sin may be revealed, and more and more discovered,
and that Zion may be more and more redeemed through judgment, and saved as by fire.
Oh, may nothing in low and trying seasons be permitted to intervene and trouble us unprofitably,
either as to our individual lot and state,
or as regards our precious fellowship and unity in that which is unchangeable,
or as to the state of the church or the world;
but may we continue in faith and patience to the end.

[.signed-section-signature]
J+++.+++ B.

--

[.offset]
+++[+++In a letter to another friend about the same date, alluding to his late journey,
he says;]

[.embedded-content-document.letter]
--

Though the humiliations have been frequent and great,
a sense of preserving help has never been withheld in the needful measure,
and at the needful time.
I have found no wonderful enlargement; but in my little way,
have endeavoured to sympathize with the suffering seed, the wrestling remnant,
who are concerned above all things to maintain the testimony of Jesus,
by dying daily to themselves.
And the Lord will still keep these in the hollow of his hand; and,
amidst all exercises and tribulations, such will grow.
May we ever be counted worthy of taking our lot among this number,
drinking into one Spirit.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
16th of Twelfth Month, 1834.

&hellip;Unless we have forfeited our privileges as Christians,
and are utterly lost to all right feeling of Divine help, is it not natural and likely,
and consistent with the provisions of Divine wisdom, that as our day is,
so should our strength be.
And Oh, the invincible, the unutterable strength of the true faith,
even but a grain;--it is calculated to overcome the world and the transient things of it;
as embraced and laid hold of, and cleaved unto, it makes us heirs of life,
and gives victory over death.
Oh, then, what cause, and also what ability may we find, even to "`rejoice evermore,
and in everything to give thanks,`" as poor John Woolman told his attendant,--for this is,
indeed,
the will and purpose of God in Christ Jesus concerning
us,--that thus we should "`glorify him in the fires.`"
Our business is to stay ourselves upon the Lord,
and fully to realize the truth,--that all things will be found to work together,
and to have happened, for the very best,
to those that above all things desire to love and serve Him.
May we more and more exercise ourselves in these views,
that we may in no way be moved by these or any afflictions; but that the further we go,
the more we may witness of the Lord`'s wonders in the deeps,
and be confirmed in the experience of his mercy, faithfulness, and strength;
though it should be continually made manifest and made perfect in our abundant weakness.
Oh, the times and the seasons are well left in his hand,
who orders or overrules all things well.
And in the present low and trying state of things, it is not to be wondered at,
that oppression and obstruction are permitted to be felt,
to the bowing down of the very souls of some!

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Croydon, 5th of First Month, 1835.

Your communication of the 6th of last month
was very welcome and refreshing to us.
Oh, how remarkable are the ways of omnipotent Wisdom, infinite love!
As Penington somewhere says,--if its outgoings are stopped in one direction,
it will break out with proportionate beauty and force in another.
Oh, what can the enemy do,
to hinder the glorious arising and irresistible spread of the gospel of Truth and salvation?
He may vaunt and do great things for awhile, such as may, if it were possible,
delude and carry away the very elect;
and all the world may wonder at the beast:--but the
Lamb and his followers must and shall have the victory;
and the kingdom and dominion are given to the saints,
even the tribulated witnesses and partakers of that power and faith of Jesus Christ,
against which the gates of hell itself shall never be able to prevail.
Though it would be very pleasant to be personally near to you,
and to the numerous company whom you and I have seen coming forth of the
barren wilderness of professions into the green pastures of life,
and into the quiet habitation where none can make afraid,--yet it seems
as if my right allotment for the present might be far otherwise;
and with that and every condition, I am desirous to be well content,
in the hope and assurance, that while in this state of resignation,
nothing can be better for me, and all things shall turn to my good,
and tend to His honour, who is all worthy forever.

It seems indeed as if the Lord was mustering his host for the battle,--his little remnant,
whom he ever delights to hide in the hollow of his hand,
while they are singly given up to serve Him in true-heartedness:
sometimes also he signally commands deliverances for them,
though the enemy may seem to be coming in as a flood, and ready to devour all before him.
But what, as you write, shall we say to these things?
Is there not occasion for us, through all that we meet with here,
in everything to rejoice and to give thanks.
"`The Lord lives,
and blessed be our Rock;`" "`because He lives,`" whose mercies are so renewed to us,
do we "`live also`" from day to day,
and have at times a precious degree of hope given to us,
that we shall outlive all that can happen to us here, and be safely landed in the end,
where joy and peace abound forevermore.
Oh, then, may we each in our allotment of labour, suffering, or rejoicing,
fill up our measure; and work with a good heart,
while it is day,--while we see the way open before
us,--in full assurance of faith and love;
turning neither to the right hand nor to the left,
and endeavouring (for we cannot always succeed herein,) to keep
the unity of the Spirit in the bond of sound and true peace.
I rejoice in every opening and appearance of good among any people;
but I cannot rejoice in finding a falling short of that,
in which Divine grace would establish all who know its teachings.
Some of us seem to be made more use of, in the way of inviting, attracting, grafting,
and gathering,--others in proving, confirming, settling and furthering those,
who are brought into the fold or planted in the enclosure.
I long that none of the labourers among you more particularly,
may interfere in their own will and wisdom with the services of others,
that our comfort in the Lord, and one in another, may not be marred.
May we all be built together, and seek also to build up one another,
in the main thing--our holy faith, which stands in power, in truth, in love, in peace,
and in the abasement of the creature.
Oh, may this blessed work, with you and everywhere else, go forward,
notwithstanding all opposition or misgivings; and may all that would let,
with every weight, be laid aside, and removed out of the way, says my soul!

Whatever may be the good pleasure of Him, who raised us up by the breath of his word,
with regard to our undisturbed enjoyment of those sweet privileges of fellowship together,
as a visibly distinct body,
of which we have so long and so unworthily partaken,--it is more and more clear to me,
that the faithful, and those that humble themselves in the dust before Him,
will never be utterly forsaken or forgotten:--that these
will never be altogether disappointed of their confidence,
though they have the bread of affliction and water of adversity
administered for a long season and in large measure:--the Lord
will still have a people peculiarly formed for Himself,
who shall purely show forth his praise,
and be enabled to lift up His standard to the nations.
Those who love our Lord Jesus Christ in very truth,
not feignedly,--and who in proof thereof are given
up to follow him in the regeneration and daily cross,
I trust will not be permitted to be moved by afflictions, nor carried away by delusions,
nor exalted by abundance of revelations,
nor turned aside by the business or the pleasures, the cares or the riches of this life,
or by love of other things: but these are concerned to lie low before the Lord,
and to be crucified with Christ; that so they may say in truth, "`I live, yet not I,
but Christ lives`" and moves and reigns "`in me.`"

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
12th of First Month, 1835.

&hellip;I understood +++_______+++ to say, that she believed,
from the extensive opportunities she had had of judging
among all kinds of churches and professions,
that the enemy was busily at work to scatter and divide; and that, therefore,
we had great need of care, that we do not his work,
by giving way to unfounded or unnecessary surmisings, or misgivings,
or apprehensions as to the existence of defection in doctrine among us.
So far from uniting with this sentiment in an unqualified manner, it seems to me,
that though the enemy is busily at work, as has been said, this is not all;
but that the Lord also is at work,
breaking up the false rests and old formal settlements of people; and saying to many,
"`Why do you seek the living among the dead?`"
and his design in all these shakings, and siftings, and overturnings is,
that that which cannot be shaken may be manifested and may remain; that men may see,
that it will not do any longer to go after the Lo, here`'s, or Lo, there`'s,
in this or that system of observations;
but that the kingdom and power are to be found within.
And so is Christ`'s own language fulfilling,--"`I came not to send peace,
(that is a false peace,) but rather division:`" he is separating,
and will make a clean separation, between the precious and the vile;
and is purging away all old leavens, of refined error as well as open evil!
And we, who look for all things being made and kept new, pure, and of God,
and who desire all old things to be done away that are not wrought in God,
should not shrink or be afraid.
We that desire to be searched and tried, also to prove all things,
and to be wholly given up to the Lord and his guidance,
should not give way to unreasonable or unwarrantable fears,
lest we be doing the enemy`'s work;
but simply to eye our Captain:--and if He show us the enemy at work,
attempting to insinuate poison into the church,
and put us upon resisting and withstanding him and those deluded by him,--this is not
the work of the enemy which thus engages us:--for Satan never yet did cast out Satan.
The giving place to such fears,
would lead us to esteem the guidance and instructions of
our holy Head by his Spirit uncertain and questionable:
whereas the way of the Truth is a plain way, so that the wayfaring man, though a fool,
is not to err therein; that is, as he looks to the Lord alone,
and does not lean to his own understanding.

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
8th of Second Month, 1835.

May the blessing of heaven above and of the earth beneath attend
you and yours,--the blessing which makes most truly rich,
and adds thereto no sting of sorrow!
This has been my secret petition in some of my best moments, when thinking of you;
and surely I shall be excused for telling you so.
There is that, which crowns all other blessings, as you well know:--there is that,
(let the thoughtless,
the unfeeling heart say what it may,) without which
our very blessings are of no benefit to us,
and every gift of Divine providence and grace is liable to be perverted and abused;
instead of being faithfully held in trust, and duly appreciated and applied,
to the enduring good of ourselves, and of all with whom we have to do.
This is nothing less than a sense of the presence, counsel and aid of Him,
who gives us all things richly to enjoy,
and will graciously condescend to show us how we may use these things
as not abusing them,--how we may no longer live to ourselves;
but whether we eat or drink, or whatever we do, may do all to His glory.
May this, my dear +++_______+++, be the first object in our eye,
the very business of our lives, in all we undertake, in all we have to pass through.
Then shall we not fail of that inheritance,
which our dear Lord and Saviour purchased for us by his coming and by his death;
then shall we be Christians indeed; and when our little moment of probation is over,
then the eternal weight of unmingled joy and glory shall follow!

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to Thomas E+++_______+++.

[.signed-section-context-open]
Croydon, Sixth Month, 1835.

No sooner was my eye opened to see the excellency there is in the Truth,
now just above twenty years ago,
than I began to appreciate the blessed experience recorded by those worthies,
(our early Friends;) who in the same line of testimony were counted worthy, as it were,
afresh to cast up the way and revive the ancient simplicity of the gospel.
Since that time, poor and feeble as I feel myself,
and unworthy to bear the precious name by which we are called,--in
the midst of blushing at my own dwarfishness and abundant
occasion of humiliation and of exercise,--I may say,
that this feeling and love to the pure cause of Truth, as professed by our poor Society,
has never slackened.
How animating it is, and comforting to believe,--as I have done at this time,
in the reading of your letter, and observing your exercises and efforts +++[+++in America]
on account of this most precious cause,--that the Lord has not forsaken those,
who desire to cleave to him, with full surrender of themselves;
that He is still near to help in the needful time, to limit the power of the enemy,
and lift up a standard against him,
and to overrule all for the good of those that fear Him.
Oh, how little do we know of the designs of His wisdom and goodness
to his church:--His people are permitted to be bowed down,
afflicted, oppressed;--He chastens them,
and reduces them;--and then (as the history of the church
sets forth,) He raises them up by his own arm of power,
beyond all expectation;--He even works by poor, little, feeble instruments,
and in unlikely ways; till he has effected, through suffering, the enlargement,
strengthening, and glorifying of the house of his glory.
Isaiah lx.
lxi., etc.

It is remarkable, that there is a numerous body of scattered and hidden seekers,
who have tried all other ways, and retired from them more or less;
and who are sincerely looking to the spirituality of religion,
and to us as holding up this view.
By these the most primitive productions are increasingly sought and prized.

With regard to cutting down some of our Journals, etc.,
I have always looked upon this as a delicate or difficult matter to do unobjectionably.
We are too apt, unconsciously to ourselves,
to choose that which in our present state and turn of mind we are impressed with,
or that which the present tendencies and exigencies of the times seem to us to call for;
and possibly (for often it has been so,) to the unequal upholding of divine truth,
or a partial exhibition of the character and line of testimony,
which a Friend in his life-time maintained.
This, doubtless, can be much guarded against by a judicious hand,
and under best direction: but still I have been afraid of paraphrasing upon,
or extracting the experience of others;
we may so readily give an aspect or colouring different from the original document.
There has been, in my opinion, ever since the creeping in of degeneracy,
a correspondent endeavour to refine upon, to remodel,
and soften down the rugged plain truths delivered by these ancients;
and I think I see this in many of the publications
that have of late years issued from the press.
The more pure days of the church yield to me much
the most interesting and impressive experience.
Oh, how is the simplicity overborne, even in dedicated minds, now-a-days; how refined,
how self-indulgent, and full of reasonings are we!
At what a low ebb in many places is our ministry; even strangers noticing the change,
and the approach to their pulpit eloquence: Scripture words indeed there are,
yet often attended with but little of that authority, weight, savour and life,
which tends to baptize and bow down the spirits of all,
and to humble the creature under the mighty hand of Him, who works all in all.
Surely, among many causes, our being so mixed up with all sorts of people,
sometimes for purposes very good in themselves,
has contributed to this state of things:--"`strangers`"
to the life of Christ inwardly revealed,
have "`devoured our strength.`"--Hosea 7:9. I must conclude with saying,
may the Lord by his power interpose, and show us from what we have fallen,
and preserve us from falling still more generally and utterly!

Farewell!
I shall be pleased to hear from you, whenever you have occasion or liberty to address me:
and sometimes, at least, think of me as one that longs to endure to the end,
to hold fast faith and patience, till the Lord say, it is enough.

[.signed-section-closing]
I remain a poor and weak brother,

[.signed-section-signature]
J+++.+++ B.

--

+++[+++In the Third Month of this year he became very ill with a severe attack of influenza,
and was reduced to such a feeble state of health,
as to afford little hopes of his recovery, either to himself or to those around him.
In this very weak condition,
he was desirous of being removed to the Isle of Wight for change of air,
which was accomplished by slow degrees and great care;
and at the end of ten days the improvement was surprising.
During the summer of this year, by frequent change of air,
he was favoured to regain nearly his former state of health; but in the Ninth Month,
in returning with his wife from a journey in the west of England,
he was again attacked with inflammation in the knee joint, which was so severe,
that he became from that time almost wholly deprived of further use of the limb:
great pain and suffering came on, and it was not until many weeks after,
that he could be removed home.
During this afflicting dispensation, while laid up at the house of a Friend at Melksham,
who with his wife, were very kind and most attentive to him, he wrote thus:]

[.embedded-content-document.letter]
--

I hope there is no cause for discouragement on my account up to this time:
Oh, I trust I have some sense of the tender mercies of Him, who deals gently with me!
But I think, there is no need to express much to you,
as to my feelings and state of mind, in reference to this dispensation of Providence.
You know I wish to hope the best,
and to prepare for what may seem the worst,--to be
prepared for all that may be in store for me:
and this is what I long for all who are near and
dear to me.--Oh, how much occasion there is to possess,
as though we possessed not,
and as those that are liable to be cut off from any of these enjoyments at a moment!
May we be strengthened to take every cup as at the Lord`'s hand,
and he will not fail to sweeten it.

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
26th of Eleventh Month, 1835.

"`Day unto day utters speech;`" and while every day
brings with it its peculiar duties and trials,
there is enough of mercy and help manifested,
to give abundant occasion for the engagement--"`While I live will I praise the Lord;
I will rejoice and give thanks while I have any being.`"
Oh, that you may have found, and may always find,
the Lord near to you in the time of need, as your bow and battle axe,
your shield and refuge!
I feel persuaded the Lord would do wonderfully for you, and make you a blessing to many;
that he waits and watches over you for good to build you up,
and to enable you to build one an other up in the most holy
invincible faith,--to animate and strengthen
each other in the good work,--to hold the beginning of your confidence
stedfast unto the end,--to endure hardness--run with patience--war a good warfare,
and win the unspeakable prize of salvation.
Faithful is He that has called, who also will accomplish all that He has promised,
if we do but cleave close to Him, and trust in Him at all times,
pouring out our hearts before Him, and giving up all,
even what is most near and dear to flesh and blood.

How much has He brought about, how great things has He wrought;--the strong men,
the high towers and fenced walls, and pleasant pictures has He marred,
and the lofty city laid low.
He has in exchange given to apprehend the simplicity,
the excellency there is in the Truth.
Oh, what a high calling, what a talent is consigned to us!
See that you magnify His work, said one:
and Oh, that our desires may be from day to day renewed,
that Christ and his thorough work may be exalted over all,
in and by us,--come life or death,--come wintry storms
or genial sunshine across our path.

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
13th of Twelfth Month, 1835

I hope you both live in a thorough willingness to come up to the help of the good cause.
Oh, what a self-saving, self-serving spirit is abroad;--shrinking and skulking,
instead of exposing all, life and reputation,--laying down all for the brethren,
for the church, for the Truth, for the Lord!
May you be strengthened and animated to know what is your part and duty;
for some are to be saviours on mount Zion, to turn the battle to the gate.
He that saves his life shall lose it--he that hates not father and mother, etc.,
yes and his own life also, cannot be Christ`'s disciple;--how awful!
Why have we not that holy zeal, and weighty concern, and true call,
to break down the altars of Baal,--to warn, to rebuke sharply,
to cut down deceit?--Oh, that I may be found, during my few remaining days,
fulfilling this course; and through all, dying daily!

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to Thomas E+++_______+++.

[.signed-section-context-open]
Stoke Newington, First Month, 1836.

[.salutation]
My dear Friend,

I have delayed, longer than I wished,
to answer your brotherly communication of Eighth Month last: one indirect cause of which,
perhaps I may say, has been my own invalid condition;
which has laid me by on the sofa for more than three months,
a cripple reduced to crutches; and suffering some considerable pain at times,
but far more from restlessness, helplessness, and various feelings of infirmity,
not readily enumerated.
Inflammation which had attacked my knee-joint near three years ago,
and by which I had been greatly tried, was renewed upon me;
and notwithstanding all means used, I have not been able to bear any weight upon the leg,
nor to lift it off the other when lying across it, except by hand.
Thus situated, wearisome days and nights having been my portion;
attentions to the poor body have much taken me up,
and perhaps shut me out from much active participation
in many things that have been passing.
Yet this only in a certain way;--for never have I had a livelier interest,
and as I think a clearer sense of the state of things up and down.
As "`the tidings`" reach me in my chamber,
of different movements and circumstances that transpire,
my mind seems permitted to travel on into the future,
and to see what some are contriving and concerting to strengthen their cause,
and to possess themselves as it were of the strong-holds and the passages.
Oh, the deceit and the workings of that spirit,
in those that despise and forsake the light of Christ in their own consciences!
Yet through all,
though I have sorrowful cause to believe some of understanding must and will fall, yes,
many tall and beautiful cedars,--I never felt more strongly
confirmed in the ground taken by our early Friends,
and in the belief that all will be made (as you express
it) to work together for the good of the poor little remnant,
who are concerned through all sufferings to keep to this ground.
Oh, I often feel inwardly cheered and animated, in the midst of the most gloomy prospects:
for the power of Truth is the same that ever it was; and the Lord can confound,
even by feeble instruments and unlikely means.
It matters not through whom help comes,
so that it comes from Him that made heaven and earth,
and has set a bound to the roaring waves.
Ah!
I often think of the language of one of our ancients on his deathbed,--"`The
Spirit that now lives and reigns in me,
shall yet break forth in thousands:`"--and this is my full belief,
even if the number of active and influential members in our Yearly Meeting,
were greatly diminished or even swept away.
Oh, the Lord can turn the fruitful field into barrenness,
and make the desert to blossom as the rose.

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Stoke Newington, 2nd of Second Month, 1836.

I can truly say, that with me often there has been no lack of feeling and sympathy,
where I have been but little drawn forth into expression,
perhaps checked in myself from it:
not that there are in the mind unpleasant reserves in such cases; but on the contrary,
this course naturally leads to great plainness, undisguised simplicity,
and honesty towards all.
It is in my view of much importance,
to endeavour to maintain entire the "`uncorruptness,`" the genuineness,
the unsophisticated artlessness, which is of the Truth.
Every little habit, every compliance with custom in things that are thought indifferent,
and which trenches upon these, endangers the tender principle of life; and indirectly,
perhaps almost imperceptibly, lands us in bondage, impedes us in a straightforward,
unaffected course of acting, thinking, and judging.
Thus the mind and character becomes involved and prejudicially affected.
The character of George Fox is as good an illustration as I can give,
of what I desire in this respect for myself and for my friends.
If I might venture to throw in a little counsel,
who am sensible that I also am not above the need of it most certainly,--I would say,
in a very tender feeling with you,
under whatever occasion of disquietude,--Look not so much at them,
as for the poor mind to be much taken up therewith;
endeavour to look over them up to Him, who orders all things that concern us,
and will not lay any thing out for us to pass through, but what is really needful for us.
Do not let us dwell too much upon any thing that happens to us;
but let us simply seek to be conducted through the circumstances that attend us,
and our allotted conflicts, with filial simplicity of submission,
and in a cheerful surrender of our all into the hands of our tender Shepherd and Preserver,
our Father, and ever constant Friend.
When we reflect upon the low condition we are in, it is seen to be a great mercy,
that we are not left to ourselves;
but are led about and instructed by many painful dispensations.
And when we look at the trials of the faithful in all ages,
bitter almost in proportion to their faithfulness,--also at the
sufferings of the Church as well as of the Head of the Church;
what are we that we should be spared,--or rather what are we,
that we should be honoured with them?
How light are our grievances, how great are our privileges and mercies,
how gently are we dealt with: we are as wayward children, that are ready to complain,
if aught be taken from us, with which we might have injured ourselves.
Ah! like as a father or a mother pities her babe, so does He,
who watches over us for good!

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
8th of Second Month, 1836.

--"`I will show him how great things he must suffer for my name`'s
sake;`"--and great tribulation must be passed through,
in order to have our garments washed and kept clean,
in and by the blood of the Lamb:--and these have often the sentence of death in themselves,
that they should not trust in themselves, nor in any other,
but in the Lord Jesus Christ.
Bonds and afflictions may, and must await them; yet none of these things move them,
for they know they are appointed thereunto,
even as it was appointed unto their Captain to be made perfect through suffering.
Indeed it is by these dispensations they live;
that is through their submission and faithfulness under them; and in all these things,
the spiritual life is exercised, maintained, and even raised; though they, as poor worms,
may be trampled upon and be very low in their own estimation,
and may be ready often to say, "`Surely I shall go softly all my days,
in the bitterness of my spirit.`"

Well, I long greatly for you, as for my own soul, and for every one that is raised up,
to stand as a monument of mercy, truth and righteousness, in and unto the church;
that neither heights, nor depths, principalities, nor powers, things present,
nor things to come,
may ever be able to separate us from that clear manifestation of Divine love,
in which we have felt near to Him, who has visited our souls, and one to another.
May we, my dear friend,
and all that are near and dear to each of us in the covenant of light and life,
go onward in that faith which gives the victory; laying aside every weight,
every hindering thing, every discouragement;
enduring and holding out to the end of all these bonds, trials, temptations,
humiliations, fastings, bruises, or occasions of disquietude, that may attend;
esteeming nothing strange, which may prove even as a fiery trial;
but rather counting it all joy,
that we are found worthy to suffer in any way for His cause,
who suffered so much before us and for us,
that He might open us a way out of this prison-house and place of proving.

Oh, my dear friend, my mind is enlarged,
and my eye opened to see something of the excellency of that quiet habitation,
where none can make afraid;
where the Lord is "`our peace,`" having ordained peace for us,
and being the portion of our cup: though the earth be removed,
and the mountains carried away, our hearts are then fixed and stayed;
though a host encamp against us,--"`though you slay me,
yet will I trust in you;`"--"`though I walk in the midst of trouble,
you will revive me;`"--"`though I pass through the valley of the shadow of death,
I will fear no evil,`" for even there shall your right hand lead me, and help me,
and save me.
It is in my best moments,
when such considerations as these weigh duly and fully upon my poor weak spirit,
that I feel that the present afflictions are comparatively light indeed.
However dark may appear to be the heavens above,--however inclement the elements
around,--though the proud waters may seem to come in unto our own souls as individuals,--and
the church labouring and tossing like a little vessel in the mighty deep;--yet
the Governor being on board--the Controller of winds and waves,
He is engaged to conduct her safely through all that He permits or appoints;
and not one of those who commit themselves to Him, is made desolate.
Doubtless many will fall on the right hand, and on the left:
for it seems a time of sifting and shaking, and but only just begun.
But I must not distress you,--no, no,--cheer up; for if Jerusalem become as heaps,
our holy invincible Head can raise up the stones of the street to be children,
can comfort all her waste places,
and make the streets thereof full of boys and girls playing,
as the prophet says:--"`therefore,`" adds he,
"`love the Truth and peace;`"--so will I save you, and you shall be a blessing:
"`fear not, but let your hands be strong.`"

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Stoke Newington, 19th of Second Month, 1836.

[.salutation]
My dear Friend,

It is a pleasure to greet such as yourself and dear husband, with others in your parts,
who retain, or are endeavouring to maintain, your integrity uncorrupted,
uninfluenced by the changeable principles, and shifting manoeuvring, unworthy motives,
and line of action, so manifestly prevalent in our day, and in our borders.

Ah!
I have thought,
(and the thought springs up afresh while I write,) what made them what they were,
and what alone can preserve any?
If they deny and turn away from this holy principle of light and life,
what must they not come to, whoever they be,--whatever station, gifts,
etc. they may possess, or have possessed.
And is it any thing very strange,
that the consequences should be commensurate with the cause;
and that wherever a wrong spirit is let in, it should eat as does a canker,
and spread as a leprosy?
Well, these things are come to pass, as some foresaw and foretold;
and unless stopped or limited by an overruling hand, they seem likely yet to extend.
It is not Beaconism merely, any more than it was Hicksism alone,
that the enemy has a preference for, as if he had no other forms of delusion,
or removes from the Truth, and semblances of it, wherewith to tempt the church.
When discovered in one shape, he will put on another,--any thing,
it matters not how refined, beautiful,
and apparently excellent,--if it but be not the very "`Truth
as it is in Jesus.`"--But I trust and believe you know this;
and are perfectly and sufficiently taught,
according to your need and according to your measure, to be aware of his devices.
Ah! no divination can prevail against the humble, teachable followers of our Lord:
they are preserved in the hollow of his hand, and under his wing;
and he delights to tabernacle with them.
Oh, that nothing may turn these aside from following
on to know the Lord in the way that he leads,
the good old way, in the footsteps of the flock; whose faith they may safely follow.

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
19th of Third Month, 1836

Your last called forth many a fervent aspiration for our mutual preservation, support,
and advancement.
Ah! we must cleave to our only sure refuge, our strong-hold,
our very present helper,--and then all will be well;
and we shall be conducted through all our exercises and strait places,
receiving the end of our faith.
Oh, it is sweet to be permitted in travelling along this weary land,
to give and receive a greeting in spirit,--to be refreshed together as before the Lord,
and to be made to feel that we are members one of another;--that
we are not without companions in warfare and suffering;
and cheered up by the countenance of a friend, by even a few lines,
or by a hearty extension of the right hand of fellowship.
It reminds me of David, and of his friend Jonathan,
who "`strengthened his hand in God;`" and we may instructively, and without presumption,
refer to the circumstances of these individuals,
with some degree of application to our own case.
Oh, the trials and strait places,
in which some of us are placed in the present day:--and how clear does it appear,
that if we flinch not, but are faithful to all that the Lord requires of us, to be,
to do, and to suffer, for his cause and people, we shall be made instruments,
in our measure, to carry forward his good work, to stand in the breach,
and to be (whatever we may think of ourselves) as saviours on mount Zion,
to judge the mount of Esau, yes, to turn the battle to the gate.
The Lord will assuredly, in his own time and way, send deliverance for his little ones;
for the Lamb and his followers must have dominion and victory.
Those who are engaged on the Lord`'s side,
and bound to stand by and uphold his pure cause,
cannot escape the peculiar notice of the all-seeing eye of the Captain of salvation;
who will not fail to promote, to honour, to make use of, and to dignify,
His true-hearted, firm-handed soldiers.
So look to it,--and Oh, my soul,
look to it,--that we lose not any portion of that weight of glory,
which the Lord designs for us,--any portion of that line of usefulness, or of suffering,
which should devolve upon us.
Let us not plead any excuses, whether it be trade, family,
our own meanness or insignificance; nor yet like one of old,
say to the servant of the Lord, "`If you will go with me,
then I will go,`" etc.--lest it be said,
"`the journey,`" or the proceeding "`shall not be for your honour.`"
Oh, for an unreserved sacrifice, and a going on in the strength of the Lord,
which is made perfect in weakness; and also, a standing still in the true faith,
to see and to wait for his salvation revealed, and his arm made bare for our help.

I may assure you, my dear friend,
that your exercises and self-humiliating baptisms are only such as are common to us all,
and no more than needful for the best of us,--to drive us home to the preserving power,
to lay us low and keep us there; and are rather marks,
how tenderly and closely our holy Head and High Priest,
our keeper and shade upon the right hand, hedges us about,
as Satan said was Job`'s favoured lot; not leaving us to ourselves,
as we are ready to suppose;
but constantly interposing with his fatherly chastenings
and stripes;--because he loves us,
and has a purpose of his own glory in our close proving and refining,
as his choice jewels and gold of Ophir.
Dear +++_______+++, believe it is even so, in all your overturnings and tossings.
Ah! would he have received a burnt-offering at our hands,
and would he have shown us all these things,
if He were displeased and ready to reject us?
as Manoah`'s wife pleaded.
Yes, though He slay you, trust in Him;--humble yourself low before him,
and in due season all will work together for your exceeding
good,--for your great enlargement in the things of God.
Therefore, be patient unto the coming, and through all the dispensations,
of your wonderful Counsellor.
I believe the little ones have no cause unduly to fear,
or to let in discouragement and doubts.
However, though we may be permitted to be trampled upon and broken to pieces,
yet the blessed Truth will outlive it all.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to J. B+++______+++, Cornwall.

[.signed-section-context-open]
Stoke Newington, 29th of Third Month, 1836.

[.salutation]
My beloved Friend,

It is a blessed privilege to be given to drink into one Spirit,
and to be renewedly baptized together; so that,
whatever apparent occasions of interruption come between, or clouds of temptation,
floods of affliction, mountains of opposition,
wild wastes and howling wildernesses,--we know that the Lord is over all;--we
know in whom we have believed;--we know we have passed from death unto life,
because we love the brethren;
and we know that He is able to keep that which we have committed unto Him.
Although since you wrote, I have had my portion of trial in many respects,
more than my outward allotment seemed to bring with it; in looking back, however,
although my tears have at times been as it were my food day and night,
yet the Lord has not been lacking to command his lovingkindness in the day time,
and in the night season too; His song has been with me,
and my prayer has been to the God of my life.
I am even ready to think, that it is through the prayers of many,
more fit to plead prevailingly than myself, that I am now in the land of the living,
bodily and spiritually too;--and as earnest and as willing at least,
if not as able as ever I was, to wield the weapons of our warfare,
in a cause dear to me as life itself, because crowned with immortality and blessedness.
I cannot say, "`I shall not die, but live,
and declare the works of the Lord;`"--but I can say, "`while I live,
will I praise the Lord; I will sing unto my God, while I have my being.`"

My general health is wonderfully upheld, and I have no suffering in my knee,
apparently nothing but debility from disuse and disease;
yet this I am continually sensible of, that my times are in His hand,
and He who has laid low, can do as it seems good in His sight,
even "`raise up and confirm the feeble knees.`"
Oh, what encouragement to present and commit ourselves to Him under every dispensation,
and thus to be allowed to feel, that whether we live or die,
we are the Lord`'s. Under precious feelings like these, when unable to attend meetings,
I have longed to be preserved, but as one of the wrestling seed of worm Jacob; who,
when he had rested on the pillow of stone,
did not forget to place it up as a pillar and a testimony to the Lord,
who appeared unto him, and spoke comfortably to him;--even that He was with him,
and would keep him in all places where he went; and would not leave him,
but would fulfill all He had spoken of to him.
But what shall I say, "`Though bonds and afflictions`" abide; yet through all,
some of us are encouraged beyond expectation,
and are obliged to hope against hope.--"`I will leave
in the midst of you an afflicted and poor people,
and they shall trust in the name of the Lord:`"--"`a
deceitful tongue shall not be found in their mouth;
for they shall feed and lie down, and none shall make them afraid.`"
"`It is enough for the servant to be as his master:`"--"`where I am,
there shall also my servant be,`" whether in tribulation or otherwise.
It is a fine lesson to learn, in whatsoever state we are permitted to be,
therewith to be content,--everywhere and in all things to be instructed.

The only time of late that I have been out to meeting, was last First day week,
when I had a sweet time; my mind was clothed with grateful and humbling feelings,
to which I had to give utterance;--"`O how great is your goodness,`" etc.
There may be, you know, a great door and an effectual one opened,
where there are many adversaries.
I am privileged with many visits from Friends, visitors or strangers,
and sometime have to speak very plainly to them on our duty in these times,
which I believe is, to be honest, firm, and uncompromising.

I have nearly exhausted my paper,
and a person would hardly know from it that I had
so many near and dear to me in your county;
yet they know it, whether they see these lines or not,
and whether I expressly address them or not: we are as living epistles to one another,
while and so long as the ministration of the Spirit is impressed upon our hearts.
Ah!
I can not easily forget how my poor,
dull heart was made to yearn towards your dear family, from one end to the other.

&hellip;Parents peculiarly have to plough and sow with tears,
often feeling their own infirmities, and how little they can do:
but the Lord often interferes for their help; and perhaps,
when they are laid in the dust, brings about and fulfills all their petitions,
even to the letter.
My love to Friends, and to the poor of the flock, who wait upon the Lord for mercy;
grace and peace be renewed unto them at all times.

[.signed-section-closing]
Farewell: your affectionate friend,

[.signed-section-signature]
J+++.+++ B:

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
22nd of Eighth Month, 1836.

Your last seemed to convey a low account.
"`Behold we count them happy that endure;`"--the spirit
of glory and of consolation is specially provided for these:
and however bitter the chastening may be at the time,
yet afterward it cannot but yield peaceable and blessed fruits,
to those rightly exercised, and endeavouring to be given up thereto.
The furnace is even made and heated for the gold,
and for nothing else but that which is worth refining: therefore,
what a blessed thing to be counted worthy to be chastened, as a dear child of the Lord,
and not to be left to one`'s self.
Oh, you know not what are the all-wise,
all-merciful intentions of our Wonderful Counsellor towards you,
and how he would work in, and for, and also through you.
Nothing is too hard for Him;
and all things are possible unto his simply obedient children
who believe,--He is able to do all things for them:
these He will never leave nor forsake, but keep in the hollow of his hand,
and as the apple of the eye.
Not one trial, not one pang will such have to pass through,
more than there is a "`need be`" for,
or more than will be made to work for good unto them, both here and forever.

My secret petition is,
that you may each discern what his good pleasure is concerning you,
and concerning each other, lest in any wise you mistake it;
and thus miss of any thing that did really belong to you.
May you be wholly given up, and give up each other freely, to His ordering and service,
whose gifts you are to one another;
lest if there be even the shadow of a withholding and drawing back,
the Lord should withdraw his hand so full of blessings temporal and spiritual.
We may easily reason away the tender gentle touches of his hand, so as to doubt,
whether they are the requirings of the Lord;
and those who are very jealous of his honour,
or clear in their discerning respecting the standing
and steppings and outgoings of others,
have the greater occasion to beware of placing so strong a guard against all outgoings,
as to cramp or cripple either themselves, or those with whom they have influence.
These are days in which the enemy would persuade some of us,
that we had better do nothing, lest we should do wrong,
or in our attempts to aid the cause,
only give pain and trouble to the rightly exercised by our meddling.
But Oh, how otherwise is the fact! what preservation, what help, what direction,
and qualification, have the simple-hearted received,
whose strength is made perfect in a humbling sense of their
own weakness;--out of weakness they are made strong.
My beloved friend, I must go further, and urge on you to weigh well,
(but without undue carefulness,
discouragement or distrust,) whether there is not
a call upon you to double diligence in coming up,
in a noble, disinterested, unbending, and unblushing way,
to the help of the Lord and his church,--to stand in the breach, and fill up your ranks,
as those that are deeply concerned for the spreading,
as well as the upholding of the testimonies of Truth.
Ah! it is high time that all who have been awakened
to a sense of the state of things in our poor church,
were up, to retrieve and turn the battle to the gate.
The enemy and his willing instruments are busy indeed;
we see the fruits springing forth on every hand;
and there are few given up to withstand him in a true-hearted, uncompromising,
plainness and boldness.

May we then join in an unqualified surrender of our all, to the disposing of Him,
who would work in us and for us, and also through us mightily,
to the subduing of all within us that would choose, or refuse,
or chalk out our own line for ourselves,
entrenching ourselves in the rectitude of our own wills and counsels: whereas,
we should be tender as the growing vine,
and teachable as the weaned babe,--no fretting,--but with
mortified wills even slain and nailed to the cross.
The time is verily come, when men shall be, and are, lovers of their own selves, I know;
but the time is also coming, when,
if I have any true vision of what shall be the end and outcome of these shaking times,
men shall not love their lives unto death; but lay down their lives for the brethren,
forego their ceiled houses, their "`pleasant bread,`" and their couches of ivory,
their boats and their nets, and their father, to become fishers of men;
and count all things but loss.

--
