== Chapter XV.

[.offset]
+++[+++In the course of the summer and autumn of 1836,
John Barclay passed some time by the seaside, with benefit to his general health.
While at Brighton in the eleventh month, under an apprehension of religious duty,
he addressed his monthly meeting as follows:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Grace-Church Street Monthly Meeting Of Friends.

[.signed-section-context-open]
Brighton, 9th of Eleventh month, 1836.

[.salutation]
Dear Friends,

In the love of our heavenly Father,
my soul at this time salutes his faithful children among you, of all degrees,
who love our Lord Jesus Christ in sincerity,
and can call him "`Lord,`" and bow before Him:
desiring that an increase of all spiritual blessings may be known amongst us through Him,
our Head and High Priest, and only hope of glory.

It seems best for me to acquaint you,
that while at this place for the benefit of my health,
a weighty feeling of duty has revived and fastened on my mind,
to pay a religious visit to the Friends in this place from house to house; a work which,
as regards a considerable portion of this quarterly meeting,
I was enabled to perform some few years ago, but did not then see my way further,
so as to embrace this particular meeting, and a few others.

Should you, on a solid consideration of my concern and situation,
think it right to make way at this time for the relief of my mind herein,
it may be safest for me to request the liberty to extend the family visit,
should this seem required, to a few small meetings in this quarterly meeting.

Desiring we may all be kept patiently and diligently
attentive to the voice of the true and tender Shepherd,
I bid you affectionately farewell.

[.signed-section-signature]
John Barclay

--

[.offset]
+++[+++In the twelfth month,
he returned to his monthly meeting the certificate granted for the above service;
acknowledging the goodness of the Lord in helping and sustaining him on his way,
and in favoring him with the reward of peace on his return home.
He paid visits to nearly all the families of the particular meeting of Brighton,
under circumstances as regarded his infirm state of health,
calculated to excite much sympathy on the part of his friends of that place;
he entered house after house, supported by his crutches,
and it is believed his visits were peculiarly acceptable generally.]

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Stoke Newington, 3rd of Twelfth month, 1836.

Ah! dear ​​​​+++_________+++, as you well know, home is home,
after such engagements and causes of absence from what
is dear to us in this outward state and lower region:
and home is home, in a higher and better sense, blessed be His name,
who makes heaven a home: for without Him, where is the rest,
where is the refreshing to the poor, craving, immortal part?
These feelings, and such as these,
while they moderate or sanctify the use of earthly objects, heighten and refine.
There is truly nothing here worth living for,
without the good presence of our "`Everlasting Father;`" but with that,
and in subjection and resignation to Him,
every thing is to be received with thanksgiving,
and used with joyfulness,--come pain of body, or conflict of mind,
loss of wife or children, or dearest friends, or house, or food.

This is our calling,--this is our privilege;
and O! that we may hold it up to others as such, both in life and in death.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To A Young Friend.

[.signed-section-context-open]
24th of Twelfth month, 1836.

Rely upon it, my dear +++_________+++, these associates of yours, whoever they be,
even if they stand high in general estimation, are no friends to your true interests,
your best welfare, however plausibly they reason.
The very circumstance of their endeavoring to undermine,
or upset the almost unformed views of so young and artless a person,
is a proof their unworthy purposes.
By your own account, they are in "`the seat of the scornful,`" as David said;
and when the subtle poison that is under their tongue,
is in danger of being rejected and exposed,
they can turn off the conversation with a laugh.
But if you are favored to withstand their crooked twisting arguments,
be also very careful lest their ridicule move you in any wise from the serious ground,
the safe because lowly abiding place, of the real Christian.

My advice to you is, avoid such company, shun such associates,
trust not yourself to dispute with them; you will not be likely to get good by it,
nor to do them good, but to receive harm in ways little suspected.
You are not to be supposed, nor shouldest you for a moment presume yourself,
to be competent to enter the lists of controversy; it requires one to be well grounded,
rooted and settled in the right way, to meet all the objections and cavils,
that may be urged by persons of more or less corrupt and uncontrolled minds,
who despise the truth and its simplicity; yet who would,
even with the semblance of truth, beguile others from the reality of it.

"`Be not conformed to this world,`" said the Apostle,
who knew that the fashions and customs of it are vain, and pass away.
To a mind disposed to avoid the very appearance and approaches to evil,
this text is alone sufficient to induce a hesitation, a scrupulousness or tenderness;
knowing that for every idle word he must give an account,
and that every thought must be brought into subjection to Christ.
But these libertines, who would think their own thoughts,
and choose their own ways and words, and also wear their own apparel,
must needs have things so cleared up to their blinded and darkened understanding, that,
like the lawyers, no express (much less implied) prohibition of Scripture,
would have satisfied them: they would shuffle from it and fritter it away,
bending it to their own wills.
Whereas the spirit of Christianity testifies, and has ever testified,
against such things, not only among Friends, but more or less,
and in different ways and degrees, wherever sufficient clearness has been arrived at,
even from the earliest ages.

Picture to yourself any set of people raised up to a deep sense of religion,
and carrying out their watchfulness and self-denial to all branches of their conduct,
and endeavoring to follow that exhortation,
"`Be holy in all manner of conduct,`"--and whatsoever you
"`do in word or deed, do all to the glory of God,`" etc.
Would they not soon come to be distinguished from other people,
who follow the course of this world, or who secretly yearn after their own heart`'s lusts,
and comfort themselves with trying to think there is
nothing in this and the other little thing,
and that religion does not consist in these things?
Would they not soon find themselves to be "`a peculiar people,`" a singular people,
a very simple people;--their outward appearance, their manners, their very gestures,
restrained and regulated after a mode totally
contrary to the generality of those around them?
According to that striking passage in one of the Apocryphal writings,
setting forth the language of the ungodly respecting the righteous,
so will it be respecting such a people or person
as I have described;--"`He is not for our turn,
he is clean contrary to our doings; he was made to reprove our thoughts;
he is grievous unto us even to behold; for his life is not like other men`'s,
his ways are of another fashion.`"^
footnote:[See Wisdom of Solomon, 2:12-16.]
Indeed it has never been any wonder with me,
that a people gathered and settled and preserved,
as I have hinted at,--or as Friends were,
when they found themselves estranged from the world at large,
and eccentric through this process of following their
convictions of duty,--should value this their privilege,
and these outward badges,
which tend to keep up this desirable distinction and separation from the world`'s spirit.

But they never set up a rule as to dress, or any particular color, cut or fashion,
on the same footing as the livery of the Monks, or religious orders of the Papists, etc.;
they only left off their ornaments,
and such things as were a burden to them as unnecessary and
unsimple:--it was the ever changeable tide of fashion,
which did the rest, and in time caused their dissimilarity and strangeness to appear.

But as to the bare assertion, that George Fox and the early Friends,
would have changed with the times,
it is a conjecture which has its origin in the mere
caprice and inclination of those "`he say so;
and the contrary may be as flatly and broadly asserted upon far stronger grounds,
even upon the actual facts of the whole tenor of their dissent,
as exhibited in their lives, and especially in their writings.

The common consent spoken of,
is the very conformity they objected to,--a consent of worldly men,
upon worldly principles; not the consent of men redeemed from the earth.
On the other hand, all that have ever rightly given up to make a plain appearance,
and to speak the plain language, etc., have done it on the very same sound ground,
and not merely because George Fox and others did it.
They, the truly convinced, have continued to feel on the subject, as he did;
and though the instances are rare, as the mercy is great, and the work marvelous,
and no light and superficial one, such instances are yet from time to time occurring;
they are the result of cleansing the inside of the cup,
that the outside may become clean also.

My case is, I trust, one of these, and, perhaps, rather an unusual one;
for I was brought up, as you know, in the entire disuse of,
and I even cherished a real contempt for, such singularities;
until I came to see that there was "`no peace to the wicked,`"--and that "`great
peace have all they who love`" "`the law of the Spirit of life in Christ Jesus.`"
Then as I yielded my mind to be in all things led and guided thereby,
nothing offended me but evil;--nothing seemed too hard to give up unto,
nor anything to be slighted as insignificant,
which in anywise contributed to this heavenly peace and
progress in what was esteemed so supremely excellent.
The cross of Christ, that yoke he puts upon his disciples, was very easy and sweet;
and peace was the reward of being faithful in ever so little.
It is in this way, I have been made ruler over more,
and not by despising the day of small things;
which is the sure way of falling "`by little and little:`" of
this we have most painful instances now around us;
and even some, who have deservedly stood high in our Society,
as teachers and examples to the flock, but who have even come to question, or have lost,
all their former impressions and tendering convictions,--those are, it seems all gone,
and almost forgotten, as the early dew that passes away,--and they have turned,
as the dog or the sow, to that which they once loathed and rejected.
And truly it is a striking and unanswerable fact, that there has not been one individual,
who has risen to any eminence for religious dedication in our Society,
but has had to tread the narrow and strait path;
and has had to attribute his progress to giving up, in the ability received,
to obey the secret monitions of the Spirit of Christ, even in little things:
nor has there I believe, been one who has swerved from this course,
that has ultimately turned out better than the salt that has lost its savor.

"`The fashion of this world,`" my dear +++__________+++, does indeed pass away; and as you say,
custom is capricious and changeable:
but Truth is the same that ever it was--unchangeable, and never fails:
and it will always stand by and bear out those, who are of it, and who keep to it,
"`Wisdom,`" we read, "`is justified of her children,`" and.
of few or none else;
and the natural man cannot understand or receive the
things that relate to the Spirit and kingdom of God,
they are mere foolishness unto him, while in that state;
for they are ever hid from the wise and prudent of this world, and revealed unto babes.
Therefore, may I not fitly wind up,
by subjoining to that scripture with which I commenced,
the language which follows it,--"`Be not conformed to this world,
but be transformed by the renewing of your minds, that you may prove what is that good,
acceptable, and perfect will of God.`"

I would earnestly urge you to press through any indisposition or inertness of mind,
and to sit down at your vacant moments to read Penn`'s No Cross,
No Crown;--redeeming your time from idle gossip,
avoiding occasions of exposure to unsuitable conversation,
and either retire and go aside, or boldly and simply take up such a book,
and go through it perseveringly; entering into the spirit of the writer,
and bending your mind to the subject.
The latter part of Jaffray, which contains the history of Friends in Scotland,
is another book which would really interest you.
But after all the helps to be derived from books or instruments, I trust,
my dear +++__________+++,
you need not to be reminded of the inexhaustible
unfailing source of all strength and goodness;
who alone, if applied to,
and the mind truly turned to Him in secret exercise and breathing desires,
is able to solve all our difficulties, to relieve us of our doubts,
to deliver us from temptation, to aid our drooping resolutions,
and quicken our souls to run with patience the race set before us,
and to hold out to the end in well doing.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
6th of Second month, 1837.

When the will is slain,--when we can say,
"`It is no more I,`"--then how easy is the task of dedication,
and how clear are the pointings, how light the burden of the cross of Christ.
Then self is of no reputation indeed, and all crowns are laid down;
nor does any snare of the enemy prevail.

The most unanswerable arguments, we of this day can give to the gain-sayers, is,
to live down their mis-representations:
and the best argument perhaps for the early Friends,
as was the case with the primitive Christians, is their life and conduct.
At times,
the low standing and feeble state of those that have a love for the cause of Truth,
and the shortcomings of most of us, depresses me.
Those who live within the hearing of the shouts of the Philistines,
are taken and perhaps disturbed by them.
I trust, such as, however,
know better than to give up to every "`Lo here`" and every hue and cry,
or to be afraid with any amazement.

We must keep low, keep quiet; minding our particular calling, our inward condition,
and feel the Lord inwardly as the Rock and Sanctuary, where none can make afraid.
Undoubtedly it is a trying day, a sifting time,--and I think must be yet more so;
for though a few leaders of faction and of error have left us,
and have swept away a number of followers, whom they have deluded,
and who were not settled in the faith,
and some of these hardly knowing why they belonged to us;--yet of those who remain,
what a remnant really are _one with us!_
And unless wonderful mercy, wisdom, and strength, be manifested towards the unstable,
as towards all of us,--what can hinder their being scattered and driven away.
Though the Society seems somewhat relieved,
yet grievous exercises remain to be borne,--and
a great deal to be worked through and worked out,
before this once self-denying and redeemed people,
can be reinstated to their former brightness and ancient purity.
The Lord waits to be gracious, and I believe will hasten this work in his time.
And O! that we may be so preserved and strengthened, as to be made willing,
through all baptisms, to be instrumental in our day, in ever so little a way or degree,
to bring about the period when the salvation of Zion shall go forth as a lamp that burns!

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Stoke Newington, Third month, 1837.

Time rolls on, and manifests things and persons quickly.
So many matters have transpired, even since I replied to your letter of eleventh month,
that I can hardly recur to circumstances: but may we not say, dear friend,
that all our views and feelings have been fulfilled and realized, or are fulfilling,
as to the state of our poor Society.
The conflict and contest is pretty well over, with what was called Beaconism;
but there are those still remaining, who occasion the true Friends great exercise;
being unwilling to go the whole length with our ancient primitive worthies,
but can readily find them in fault.
I trust this also shall in due season be broken up, and the testimony of Truth,
in all its completeness and simplicity, rise and shine over all opposition.

Modified Quakerism cannot stand the fire.

May we, or such of us as are permitted to continue in the warfare,
be preserved firmly and truly bound to the good cause,
as we have ever received it from the beginning;
and may we be perfectly knit and united together
in the same mind and in the same judgment;
even though we be left as a little remnant, and as spectacles to the world.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Stoke Newington, 31st of Third month, 1837.

How many and awful have been the warnings and the tender chastenings
of the all-wise hand of Divine Providence of later times;
all (I sometimes think) concurring with and bearing upon,
and bespeaking somewhat in relation to the spiritual
aspect of things in the church and in the world.
"`The wine of astonishment,`" indeed is given us to drink, in various ways:
yet the meek and patient followers of the Lamb, who know in whom they have believed,
and that He is able to keep their all, which they are engaged to commit to his keeping,
are not left desolate,--are not permitted to be
swallowed up of over much emotion of any kind;
they cannot be unduly "`afraid with any amazement;`"--no, truly,
"`all these things,`" they well know,
"`must needs be, or come to pass;`" and they are so far from saying with one,
"`This evil comes from the Lord, why should I wait for the Lord any longer,`"
that they rather feel, "`It is the Lord,---let him do what seems good to him;`"
and so in patience are engaged to possess their souls.
May then the peaceable and peaceful fruits of righteousness,
be more and more brought forth in us, my dear friend,
through and by means of all the losses, crosses, over-turnings and humiliations;
so that not only we may be rendered more meet for, and more earnest after,
that fruition of the end of our faith, which is endless, uninterrupted,
and perfect;-- but even here below may be the better
qualified to fill up our measure of service,
and glorify the good cause and blessed name of our holy Redeemer.
There is indeed great occasion to believe, though the evidences and tokens are,
now as ever,
sufficiently obscure to try the faith of God`'s
dear children,--that His glorious cause is,
through all discouraging circumstances, still going forward;
and that His wonderful and all-righteous purposes are fulfilling in the earth.
That this is substantially the case, should and must be matter of joy to us;
and even make us at times,
when we are given to see and appreciate it,--:exceedingly "`joyful in all
our tribulation;`" even though we should be pressed almost out of measure,
beyond strength or hope, having fightings and fears without and within.
This has been the portion of the faithful, more or less in all ages;
and I believe it will be so, till the end come.

Be assured, my dear +++________+++, I do much sympathize with,
and have often thought of you in several respects,
both before and since we heard of your bereavement.
I cannot doubt you feel your loss greatly, at times perhaps too much,
though I hope not so.
Surely sufficient support and consolation will not be lacking,
if you do not "`refuse to be comforted.`"

I desire you, my dear friend, to endeavor as much as may be, to look beyond your loss,
at the tabulated state of the church,
stripped of many a son and daughter,--promising and once thriving branches,
but now withering and corrupt, more or less dying and dead, yes, twice dead!

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient


[.signed-section-context-open]
Tunbridge Wells, 16th of Ninth month, 1837.

May you be strengthened and animated from time to time,
and your drooping faith sustained and increased,
to run with all patience and quiet confidence,
the wearisome journey that is yet before us.
In due season our reaping time and shouting time will come,
for which we have sown in tears; laying down as it were our all,
(O! that it may be our very all,) surrendering every thing that the Lord
calls for at our hands,--casting into the treasury even our mites,
of our poverty, being content to see ourselves to be very poor, helpless, worthless,
fit to be pitied, mere pensioners,
and dependents on the Lord`'s free mercy and renewed blessing.
This is the state that draws down the Divine regard, and, as it were,
commands the rich outpouring of those good and perfect gifts,
which dignify and adorn poor fallen human nature;--
which raise up the brother and the sister of low degree,
from lying among the pots, among the things that perish with the using, yes,
from the dunghill of pollution;--and from sitting like
poor Job among the ashes of despondency,
to reach forth, to mount up towards that inheritance incorruptible, undefiled,
and which never fades away.
It is prepared, it is reserved, it is laid up in store,
for those that are faithful unto death, who are kept by the power of God through faith,
and are not moved away from the blessed hope of the gospel; continuing stedfast,
immoveable, not soon shaken in mind, nor shrinking from suffering,
nor afraid of temptations or abounding tribulations;--but enduring to the end.

I have been much comforted, while from home,
in reading many precious letters of our primitive worthies of the first rank,
who loved not their lives unto death, but gave up all,
that they might keep a conscience void of offense, and be clear of the blood of all.
I hope (if life be spared, and strength given,) to hand some, yes,
many of these for the perusal of such as can receive and profit by them.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
Stoke Newington, 27th of Eleventh month, 1837.

[.salutation]
My Beloved Friend,

My poor and often tribulated spirit does salute yours, even as deep answers deep;
for I am ready to think, you have from time to time to drink into that cup of suffering,
which the livingly exercised every where up and down, in this day of treading under,
of rebuke, and of scattering, have more or less to partake of For, indeed,
how can it be otherwise, when those who have been as leaders and way marks to the flock,
and have seemed to be pillars in the house of the Lord,
are ready to stagger and to stumble, to be snared, and to be broken.

But I must not here expatiate on my feelings,
as to the state of things in regard to our still favored Society;
but I will refer you to my Preface to Pike`'s and Oxley`'s Journals,
to other parts of Joseph Pike`'s Journal, but especially to his letters,
and some of Deborah Bell`'s,
which show that times of trouble have befallen our Society before now,
in rather a similar way and degree.
The same power can rescue his tribulated remnant, and restore the waste places;
nor will He ever own proceedings which are not according to Truth and uprightness.
I am inclined to think that many have been, and are,
endeavoring uprightly to retrieve their outgoings;
seeing the palpable extremes and consequences of the track they have been on:
but others seem not sufficiently warned and instructed to return,
in honesty and in earnest, to original principles and practice, but are feignedly,
and in part only, doing so; retaining so much of the wisdom of the flesh,
and so much of self in a refined form,
as they think will make the Truth more palatable to our own people and to others;
thus shunning the shame of the cross, and the humiliating process thereof.
It will not do: our all-conquering Captain will discover and make bare all coverings,
and find out all his enemies,
and pursue and overtake them in all their retreats in
the precincts of and backways to Babylon.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
29th of Eleventh month, 1837.

I may truly and sincerely say, that we participated in a sense of the loss,
which many (doubtless) even among the more
distant connexions and friends of the deceased,
feel they have sustained.
Do I say loss, do I speak of deprivation,
when those who have humbly endeavored to love and follow their dear Redeemer on earth,
are taken from suffering and probation, as we trust, to their resting place in glory?
Ah! we have them still, if the apostle`'s language applies to us,
if we are indeed come to Mount Zion, the heavenly Jerusalem, to the innumerable company,
to the spirits of the just made perfect, to Jesus our Mediator.
May we then not sorrow as those who have no such
substantial enjoyment of things hoped for,
and evidence of things not seen.
May we be quickened on our way,
and animated by the cloud of witnesses with which we are encompassed,
still to persevere and run with patience; looking unto Jesus, learning of him,
leaning on him in pure dependence and childlike simplicity,--loving no one,
nor any one thing, better than him.

Being thus made willing to lose all, in and for him,
we may be assured of the fulfillment of his gracious promise,
of the hundredfold even in this life, besides the heavenly inheritance.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To One of Another Profession and a Zealous Minister.

[.signed-section-context-open]
26th of First month, 1838.

[.salutation]
My Dear Friend,

It is time I acknowledged your favor of the 21st ult.,
which has not been lost upon me.
I accept your kind and sincere notice of me, and also of my books, with, I trust,
the like genuine Christian feeling.
That we have been made somewhat acquainted one with another has been cheering to me,
as one of those many providential marks of favor shed upon us,
through our whole lives by the Author of mercies.
It has seemed to me sometimes, as though our dear Lord and Savior,
in condescension to our frequent breathings to him, the Head of his own church,
for the spread of his blessed gospel of peace, truth, and righteousness in the earth,
and our jealousy for his honor,
(according to our measure of light and discernment,)
had caused us to come across each other`'s path;
that he might renewedly show us, that he has other sheep who are not of this fold,
where we have been accustomed with joy and comfort to feed and lie down.

That we should find, on near inspection of each other`'s views on sacred things,
many and important shades of difference,
will not assuredly either stumble or surprise us.
The ways of God in his works of creation are higher than our highest thoughts of them,
as are also the acts of His Providence; how much more then must we expect them to be so,
in his dealings and dispensations with the soul of man individually,
and with his church collectively.
Truly the workings of his grace and power in and towards us, are infinitely diversified.
But through all, what He looks for in us all, however variously situated, dealt with,
and gifted, is,--that our hearts being quickened and renewed by Him,
should be turned towards Him, and knit to Him in faithfulness, in true uprightness,
to serve and to trust in Him, with a perfect heart, and with a willing mind.
Ah! how He touches, softens, humbles these proud, hard hearts of ours, these fallen,
but aspiring natures, these forward, wayward tendencies; and woos us to be wise indeed,
by learning of Him how to be simple as little children,--submitting, bearing,
and taking His yoke upon our spirits.

How prone we still are, to take back the government into our hands,
by leaning to our own understanding,
by consulting with flesh and blood,--while we profess
to be asking counsel of God and of Christ;
and thus practically we shrink back, and shun to offer up our all,
as a whole burnt-offering; but even keep back the best part of that,
which is often called for unequivocally at our hands.

Alas! in reference to divine things,
who is there that follows the Lamb whithersoever he leads,
or looks to the puttings forth of the Shepherd`'s hand,
and waits to hear his voice`'.`' Who is there,
that in all his proceedings and speculations, or opinions, says,
"`That which I know not, teach me;`"
"`lead me in your Truth and teach me, for you are the God of my salvation, on you do I wait all the day.`"

Who is there,
that takes up the daily cross in religious points,--
casting down imaginations and selfish reasonings,
despising the shame with the fear and favor of man?--Who is
not conformed to this world even in little things,
but transformed by the renewing of the mind,
and in this way proving what is the Divine will?
These effusions, which arise while responding to your communication, I trust,
will not be deemed obtrusive, if they are superfluous.

After all, my dear friend, how near one to another are all those,
who being once afar off, are brought nigh by the blood of Christ; who love him,
and his appearing, and who follow him in the regeneration.
They are brought near to each other in Him;
they are baptized bygone Spirit into one body,
and are given at times to drink into one cup.
Have these not abundant occasion to forbear one another in love,
if they do not willfully transgress against knowledge and beyond faith;
for whatsoever is not of faith is sin.
Surely those that are zealous for the fulfillment of what they
understand to be the command of Christ and his apostles,
have great need to see that they follow up all
that is commanded--such as to resist not evil,
to respect not the persons of the rich, as in the epistle of James;
and many other precepts,
that are very generally made of none effect by religious professors, and reasoned away.

To be able to say with the apostle, "`I am crucified with Christ; nevertheless I live;
yet not I, but Christ lives in me; and the life that I now live in the flesh,
I live by the faith of the Son of God, who loved me, and gave Himself for me,`" etc.;
how full,--how supremely desirable!
Then the wisdom of man becomes fully subjugated, where the gospel, the power of God,
has free course.

Farewell! the Lord be between us, and with us, henceforth and forever.
With Christian love to you and your wife, and sister.
I remain your friend,

[.signed-section-signature]
John Barclay

--
