== Chapter XVI.

[.offset]
+++[+++In the eleventh month 1837, he laid before his monthly meeting,
a religious concern which had rested a considerable time on his mind,
to pay a visit to the families of Friends of his
own particular meeting at Stoke Newington:
much sympathy and unity prevailed on this occasion,
and he received the encouragement of his friends.
Under his very infirm bodily condition, he could proceed but slowly in this service.
In the second month following, he believed it right to address his monthly meeting:
a copy of his communication will best explain his views and feelings on this occasion.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Grace-Church Street Monthly Meeting Of Friends.

[.salutation]
Beloved Friends, Brethren and Sisters,

Having now held a minute,
granted me by the monthly meeting, for above three months,
setting me at liberty to visit the families of Friends at Stoke Newington,
it seems to be upon me as a duty to communicate with you on it.
In the movement I made towards obtaining it, by an application rather unusually sudden,
and in that respect unexpected by myself, I had, and up to the present time have had,
sweet peace,--an ample reward,
(however unworthy,) for a sacrifice which cost
me no small degree of resignation of my own will.
I endeavored to give up "`in simplicity and godly sincerity,`" to that which
seemed to be manifested as present duty in the Divine sight;
and dared not look outward in any sense or manner; and therein I desired, if a spectacle,
to be also an ensample to the whole flock; for not one among us can, in my apprehension,
do better under any circumstances.

On proceeding in the weighty engagement before me, I may acknowledge, that,
although no wonderful outpouring of Divine power was my portion,
I was mercifully favored, during the few days that I entered upon the work,
with such a sense that the Lord preserves the simple and the upright,
insomuch that it was as my meat and drink, to be thus among my friends:
hard things were made very easy, and bitter things full of sweetness;
a gently flowing stream of heavenly goodness being extended in every hour of need,
though in a way humiliating to the creature, so that nothing of the flesh could glory.

Endeavoring to look closely to my steppings and to my Master's pointings as to them,
I did not see it my place to join any brother or sister, fellow-laborers in the ministry,
similarly exercised; yet truly rejoicing,
that the Lord of the vineyard should be pleased to lay his hand upon any,
and open their way before them.
With regard to myself, the burden seemed greatly withdrawn, and removed from me,
even before I was wholly laid by with indisposition; and ever since,
my mind has been altogether released from any further obligation to pursue the visit,
and now at length in a way that makes me believe it
safest for me to inform the meeting to this effect,
and to return the minute to your hands.

I cannot place this conclusion to any outward account,
though my heath and constitution seem more than usually affected,
so as for a long time entirely to prevent my getting out to meetings;
but in my best moments, I have the comfortable persuasion and trust, that He,
who is no hard master, and lays no more than is meet on any of his exercised children,
has an equal right to _call in_ as to _put forth;_--
to bring out his own purposes in his own ways,
which are higher than ours; and none of us should demur against his good pleasure,
or say "`what are You doing?`"
and the wonder and the mercy is, that any are made use of.

In conclusion, it seems with me, my dear friends, to express to you my belief,
that we have from time to time ample encouragement, as a meeting,
in patience to possess our souls, to hold on our way steadily,
and to lift up the head in hope.
Although occasions of discouragement and deep conflict have attended,
and may yet await the faithful and the honest hearted,
these keeping the daily watch unto prayer, will be preserved and sustained,
abiding in Christ, and being under his peculiar notice: after they have suffered awhile,
he will establish, strengthen, and settle them more and more;
and will give them to reap in due season the fruit of their often hidden exercises,
both on their own account, and on account of others.
Thus, those that hold the beginning of their confidence stedfast unto the end,
are made indeed partakers of Christ;
and the remnant who escape the tempter's crooked Leviathan, again take root downward,
and bear fruit upward. Isaiah 37:31.

Desiring we may truly cease from man, and lean wholly on the Beloved of souls,
with the salutation of love in our Lord Jesus Christ, I remain your friend,

[.signed-section-signature]
John Barclay

[.signed-section-context-close]
Second month 19th, 1838.

P+++.+++ S.--Should this concern return upon me, with weight and clearness.
Friends may believe, I shall not hesitate to cast myself upon them again.

--

[.embedded-content-document.letter]
--

[.letter-heading]
To an Unknown Recipient

[.signed-section-context-open]
First or Second month, 1838,

It is little we can do for one another;
yet let us be willing to do that little which offers.

I often think how short may be the season, wherein we may be permitted,
or may have occasion for, the comfort, aid, and support, one of another.
Many opportunities for giving a hand of help or a cup of cold water, we do not embrace;
but we permit them to go by unimproved,
or fritter them away in our interactions one with another,
even with those nearest and dearest to us in an outward or inward sense.
Everything indeed proves what poor creatures we are, and what a low, mixed,
imperfect state the present is;--at times favored with a few drops of comfort,
of strength, a little grain of faith, of hope, of qualification to struggle on,
administered in the hour of need, and in such a way, as utterly to hide pride,
and take away all occasion of boasting on the one hand, or repining on the other.
If we did enough cultivate our intimacy with
heaven and heavenly ones and heavenly things,
and avail of our privileges, remember our heirship and calling!--Why need we tarry here;
why should we grovel below?
instead of lifting up the soul, and resting in the beloved!
Farewell! onward, onward,--the time is short,
my brother and my sister;--we linger for one another:--
let us press forward;--and in due season we shall reap,
if we faint not.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To J. Jaffray, Scotland.

[.signed-section-context-open]
1st of Fourth month, 1838.

[.salutation]
Dear Friend,

Your letter of the 13th seems,
in conjunction with my own feelings in reading it,
to encourage me to salute you in Christian freedom.

It was animating in this wilderness to read such lines from one unknown,
trusting that we have but one object in view,
and are endeavoring to be found running the same race;
though occupying possibly very different posts,
according to what has seemed to be committed to each,
respecting the things of the blessed gospel and spiritual kingdom of our Lord and Savior.
My dear friend,
you know not what a poor thing your correspondent is
every way,--enfeebled in powers and constitution,
though but forty years old; a cripple on crutches these three or four years,
by a disease of the knee joint, and still longer disabled by the same disorder,
at times threatening amputation,
and always bearing about a most delicate shattered frame in other respects.
May I not say in every sense,
'`By You have I been upholden from my birth,`' "`My times are
in your hand!`"--therefore while I live will I praise the Lord,
and by his help keep my heart and order my conversation; and all my bones shall say,
who is like unto you, who have abundantly, and are yet, restoring, renewing,
and redeeming my life, my best life, from destruction.

If we do but hold fast the beginning of our confidence stedfast unto the end,
cleaving to the Lord, who first loved, and quickened, and had mercy upon us;
He will never leave nor forsake lis; but will perfect all that which concerns us:
and He will enable us to hold out to the end, in faith, patience, and well-doing.

I have had for a long season a strong persuasion,
that our dear Lord has a precious people in your country;
and though many may be the impediments and snares and discouragements,
how do I long that there, and in every place, "`a pure offering`" may be rendered,
with as little of creaturely policy or worldly wisdom intermixed as may be.

But as to the chief occasion of your letter,
I am able to give you scarcely any information as to the Jaffray family,
beyond what my book with its notes sets forth.
I have from circumstances, and perhaps by providential ordering,
got into a channel which I often indulge in,
to search out primitive zeal,--primitive faithfulness unto death,--the path of the just,
of whom the world was not worthy.
I do not love old things _because they are old,_ but because they are often more intrinsic,
less superficial.
I delight to restore the ancient way-marks,
the foundations of many generations,-- to hold up the scattered and
obsolete testimonies to ancient purity under every name;
many of which are purposely put into the background, slurred over, distorted,
and destroyed by historians and the theologians of these degenerate days.
I have a commonplace book for my collections,
but my bodily and mental ability is growing less and less,
and my opportunities are few indeed.
O! that Christendom might return to that state
she once knew,--might recur to first principles;
then would her reformation and salvation go forth with brightness,
she would be fair as the moon, clear as the sun, and terrible as an army with banners;
and all iniquity and infidelity should stop their many mouths.

Whether we ever meet, or write again,
or are as epistles in one another's hearts in certain
respects and to a certain extent,--may we,
"`whereto we have already attained, walk by the same rule,
and mind the same thing,`" and follow the things that
make for peace and if any thing be further needful,
I believe God will reveal even this to us, supplying all our needs by Jesus Christ;
who is with his faithful followers,
delighting to reveal unto them the abundance of peace and truth, but in his own way,
and time, and as we bow to his yoke and deny ourselves.
I remain sincerely your friend,

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
To Peter Bedford.

[.signed-section-context-open]
Stoke Newington, 10th of Fourth month, 1838.

[.salutation]
My Dear Friend,

I am on the eve of leaving home for Brighton, if able;
for I am very poorly, "`feeble, and sore broken`" outwardly;
though I trust alive in my spirit as ever,
and resigned to all that may be in store for me.
The enclosed packet came to my hand;
so I take this opportunity of conveying my dear love to you,
in that which changes not--the everlasting Truth.

Though unable to mingle with my Friends in person,
when they come together for the sake of this blessed cause,
to endeavor to strengthen one another's hands in God,
and to build up one another in that holy faith once and still
delivered to the saints,--my poor mind is as deeply,
as strongly concerned as ever, that every part and parcel thereof,
with all its genuine accompaniments and fruits in practice may be maintained inviolate,
and that nothing be forborne, or let fall, or slighted, through our degeneracy,
and dim-sightedness of that which our worthy ancients upheld through suffering.
What has our refinement, religious or civil, done for us?
and what has an approach or a condescending affinity
thereto done for us?--weakness has inevitably followed,
and even the strongest and the wisest have been utterly laid waste.
Some are not sufficiently warned and humbled by these things; and if they are,
they should openly acknowledge their error,
and forsake the very appearance of this track.

I am cheerfully confident, that if those, to whom we somewhat look, as watchers,
as seers, as standard-bearers, as counsellors, are removed,
(and they are removing,) to their rest,--or, if any of these that remain,
should not keep their habitations firm and undeviating,
but turn aside in any respect from the ancient testimony,--
that He who raised up such a people as we were at the first,
will never cease to raise up others,
and put forth some into the foreground--into the very seats of the unfaithful.
I have seen it wonderfully in my short day,--I
have read it of those that have gone before:
and therefore, let none ever throw away their shield,
and weakly compromise the trust devolving on them.

Farewell, my beloved friend; may the Lord preserve us purely to his praise.
With love from your affectionate friend,

[.signed-section-signature]
John Barclay

--

He left home on the 11th of fourth month, reached Brighton without much difficulty,
and seemed revived by the change.
Soon after his arrival, he consulted a physician,
who gave a somewhat encouraging opinion of his state,
thinking that with the returning spring his bodily strength would increase.

During his residence at Brighton, he occasionally appeared to rally;
and at times seemed so animated and cheerful about himself, that his near relatives,
long accustomed to the sight of his crippled condition,
were little prepared to suspect that deceptive disease, consumption,
(as it afterwards appeared,) was making its sure
and rapid inroads upon his delicate constitution.

Our beloved friend, Daniel P. Hack, of that place,
who evinced to the last the kindest and most tender solicitude and care respecting him,
thus wrote at a subsequent period concerning him:
-- '`When our beloved friend came to Brighton, it was evident to his friends,
who had not seen him for a considerable time, that his general health was much impaired;
and it soon became so much so, as to excite apprehensions in their minds,
that the life and labors of this devoted servant were fast drawing to a close.

His mind, however, still retained its vigor;
and the precious savor which was to be felt in his company was instructive and sweet,
to those who had the privilege of sharing in it.
His concern for the cause of his dear Lord and Master,
which had so long showed itself in fruits of self-denying dedication, continued unabated.
It was evident to those who had the most frequent opportunity of observing,
under the pressure of rapidly increasing bodily ailments,
that the object nearest to our dear friend's heart was,
the spread of the kingdom of our Lord and Savior,
Jesus Christ;--even of that kingdom which is not meat and drink, but righteousness,
and peace, and joy in the Holy Ghost, and which stands not in word,
but in power.`'--(1839.) He continued to decline,
and very rapidly so during the latter part of his stay at Brighton;
and on the 8th of the fifth month at his own urgent request,
and with the approval of his physician, he was removed to Tunbridge Wells;
where he survived but three days.

The day after his arrival, in the course of some conversation with his kind friend,
D+++.+++ P. Hack, it was evident that he believed his day's work was nearly accomplished;
and in the evening, on retiring to rest, his wife only being with him,
under a precious sense of the overshadowing of the Divine presence, he supplicated thus:
'`O gracious Father! if it please You, spare us to each other a little longer,
and make us more entirely devoted to You and to
your precious cause of Truth in the earth:
nevertheless not our will, O Lord! but yours be done.`' He continued to sink,
but apparently without much bodily suffering.
On the 10th,
he repeated these passages,--"`I am the light of the world;`"--"`That was the true light,
that enlightens every man that comes into the
world;`"--and then remarked,--it does not say,
that we shall all at once know all things, but as we can bear.
O! it is because they desire to know all at once, not as children learn,
that the light is taken away!`' And again,--'`They say there is no revelation;
but that which is made manifest to us as our duty, as the Lord's will,
is revelation:--this is my belief,--I am sure of it.`'--'` They slight revelation;
but it shall prevail; and the Spirit of the Lord shall reign over all;`' (often repeated,
with) '`the Truth shall prevail,--the Truth shall reign
over all.`' '`None that trust in the Lord,
shall be confounded; but they shall be as Mount Zion,
which can never be moved,--for the mouth of the Lord has spoken it.--Praise,
where it is due, and thanksgiving,
and melody!`' At another time he said,--'`You all know my desire to
be preserved near the Lord,--to be strengthened and upheld by the
Lord,--to be found in Him;--this is the way of peace.`' Again he said,
--'` Simple texts of Scripture contain a great deal:
"`Walk before Me, and be perfect;`"--beautiful language!
Such texts involve much,--comprehend the whole of a religious walk,--the
whole of what we are in the habit of referring to in a religious life.
We must be faithful to what is made known,--to
the smallest discoveries of the light of Truth.
I trust we shall be animated and strengthened to go through our day's work;
then we shall find mercy at the hands of the Lord.`'--'`
Let us then look to the Lord for strength at all times,
and under all circumstances.`'--'`The Lord will be your Lord,
and a sure refuge and hiding place.`'--'`Cleave unto the Lord, O! cleave unto Him;
love Him with all your heart.`' To his sister, who was seated beside his couch,
he remarked,--'`The quiet habitation! dear Lydia,
you looks as if you loved the quiet habitation:
O! how desirable!`' with an allusion also to faithfulness and greater dedication.

His difficulty of articulation was great;
he often spoke of the great thickness he felt upon him,
that he could not express himself clearly: and once he was heard to say,
'`This shackled state!`' and--'`ready to be offered!`' The latter
part of this day his voice was lifted up in a constant melody,
and for many hours together, like a song of praise;
during which these words were clearly distinguished,
and often repeated;--'`O Lord! dear Lord come;`'--'`I bless the Lord,`'--'`I
am the Lord's forever.`' The name of '`Jesus`' was often to be heard;
and the word '`Hallelujah!`' was for a long time uttered.

He many times said, '`Let us all be still and quiet.
Let us be retired in our minds.`' And again,
after some little attention to his comfort,--'`Now, shall we have the Lord with us?
if not, we shall have him by and by;`' and again sunk into the same sweet melody.

On sixth-day, about an hour before his departure, he roused a little from dozing:
on receiving some nourishment from his affectionate wife, he took the cup;
and she asked him, if he knew her?--he replied with a sweet smile, '`Yes,
my Mary.`' She then asked him; had he any pain?--'`No, not any:`'--was he happy?--'`Yes;
very!`' He then lay down again, and gently drew his breath shorter and shorter,
till he quietly and peacefully breathed his last,
about four o'clock in the afternoon of the 11th of fifth month, 1838;
and we reverently believe, is, through redeeming love and mercy,
entered into the everlasting joy of his Lord.
