== Testimony

[.chapter-subtitle--blurb]
A Testimony from Grace-church street monthly meeting of Friends, concerning John Barclay,
who died on the 11th of fifth month, 1838,
and his remains were interred at Winchmore Hill, Middlesex, on the 18th of the same.

[quote.scripture, , Matt. 5:8]
____
"`Blessed are the pure in heart, for they shall see God.`"
____

This, our dear friend, was the son of Robert and Ann Barclay,
and was born at Clapham in Surrey, in the year 1797.
His parents were members of our religious Society:
his mother died while he was very young.

From his own memorandums we find that he was early
visited with the convictions of divine grace;
but becoming exposed to the influence of bad example at a public school,
the sinful propensities of the natural mind were strengthened;
yet the strivings of the Holy Spirit were graciously continued,
and he was often brought into deep humiliation
and sorrow on account of his transgressions;
and his tears of repentance and his prayers for
preservation were poured forth in secret places.
In reference to the state of his mind at this time, he says,
'`As the evil tree cannot but bring forth evil fruit,
as long as it is permitted to live and thrive in the heart;
so this being the case with me, the fruits did show themselves abundantly indeed.
Oh! that all who have been injured by my evil example could be
shown a fiftieth part of the remorse and repentance,
sorrow and trouble, which has been, through unutterable mercy,
experienced by me.`' He was made willing to abide under the judgments of the Lord,
and was favored to know that these chastisements from
his heavenly Father`'s hand were administered in love;
in a sense of which, his heart was often made to overflow with thankfulness;
and he was brought into a state of submission to the Lord`'s will,
and humble dedication to his requirings.

Alluding, some years afterwards,
to the circumstances of this eventful period of his life, he writes thus:
'`This I may say and leave upon record,
that though many almost indescribable temptations and
presentations of evil have been permitted to come about me,
sometimes like a mighty flood, so that in hours of extreme weakness,
I have been many and many a time ready to give up the '`fight
of faith;`' yet to this day the Lord,
strong and mighty, has been pleased in his abundant compassion, to encamp around me,
and to give me songs of deliverance, songs of triumph and of praise.
In His name will I set up my banner; who is a rock of defense,
and sure refuge to my poor weary soul.
O! young man or young woman, to whom this may come,--my friend, my brother, my sister,
who are seeking the better country, and Him who is the way and the guide,
oh! though you are weary and heavy laden, take courage; there is a staff, a stay,
and strength, and succor with Him, and in Him, who has gone before,
and who leads on his little ones gently and sweetly as they are able to follow.

Take this as the counsel of one who writes from a sure and living experience,
and who has indubitably known His name, which is above every name,
to be a strong tower indeed.
He will be with His,
even to the end of the world.`' His mind for several years after his father`'s decease,
was brought under much concern on the subject of business;
and he felt it to be his duty to give up an offer,
which was considered to be very advantageous.
In a retrospective view of this step, he says in a letter,
'`I know not that I have taken any measure that now in seasons of calmness
seems to afford the like peace to me.`' Alluding to this subject again,
he adds,
'`The ground upon which I think it best for me to be
not much engrossed with the things of this life is,
that having experienced no small share of the forbearance and mercy
of the Lord,--having been delivered from the pit of destruction;
having sincere, hearty, and very fervent desires tor my own preservation and salvation,
as well as for that of my poor fellow creatures
everywhere,--I have inclined towards the belief,
that the Lord will make use of me, if I am faithful to his requirings, in the way, time,
and for the purposes which he sees best: under this impression it is,
and not to encourage or give way to an apathy, or lack of energy or exertion,
that I believe it right for me to sit loose to this world and the anxieties thereof;
lest I should be incapacitated for performing that service,
which may be shown to be my duty.
I believe it safest for me, if in any business, that it should be one of moderate profit,
and not involving much attention.`' He believed himself required to observe much
simplicity and moderation in providing the needful accommodations of fife;
and in reference to this subject, he says, '`I am clearly of the belief,
that it is my duty to live in such a humble, plain, homely, simple manner,
as that neither in the furniture, food, or clothing used,
any misapplication of the gifts of divine Providence
may be admitted or encouraged.`' About this time,
which was in the twenty-second year of his age, he writes thus:
'`O! the love that the Lord has shed abroad in my heart!
O! the divine joy, the unspeakable peace,
the blessed presence of the Most High,--how it seems to flow through me,
making up for all trials, and tears of disquietude and distress!
O! may this feeble testimony speak out His adorable mercy,
when this poor frail flesh shall be laid low in the dust;
may it induce others to fear Him that made the heavens and the earth,
and to trust in Him forever!
Praises to the Lamb that lives, yet was slain!--Amen.`'

Early in the year 1820, he believed it right for him to remove from the family circle,
and to reside for a time at Poole in Dorsetshire; and about the end of the same year,
he was married to Georgina Hill.
Their union was short, for in less than three years,
his dear companion was taken from him by death, at Marazion in Cornwall;
where they had removed for the benefit of her health.

His mind had for several years been impressed with an apprehension
that he should be called to the work of the ministry;
and in the prospect of it, he was preserved in a waiting dependent state;
and fervent was his concern to be entirely given up to
serve the Lord in the way of his holy requirings.
At the interment of his beloved wife, in the sixth month, 1823,
he was engaged in vocal supplication;
and in the autumn of that year he spoke as a minister.
In allusion to this solemn and important work,
after describing the fear and caution with which he had entered upon it, he says,
'`The weight and sweetness that dwelt on my mind after this surrender,
cannot be set forth.
O! how it rested on my spirit all the day in an unutterable manner!
and yet such freedom of spirit,--so that nothing seemed a trial,
or that to which I was unequal.
I shall not easily forget how comfortable and at ease in my mind I felt.
O! it was a heavenly feeling,
and nothing short of Him that is in heaven could give it.`' He
was acknowledged a minister by his Friends in Cornwall in 1825,
and in the following year was married to Mary Moates, and removed to Alton.
After a residence of three years at that place, he settled at Croydon; and in 1835,
he removed to Stoke Newington, within the compass of this monthly meeting,
where he resided during the remainder of his life.
In the course of the before mentioned period, he paid several religious visits,
with the unity of his friends;
and in one of these journeys he travelled into Scotland as far as Aberdeen.

He had been from his youth of a tender constitution,
and for the last few years of his life he had suffered much from a disease in his knee,
which rendered walking or other active exertion difficult to him.
He was, however, very exemplary in his efforts to attend our religious meetings;
in which the exercise of his dedicated spirit was strengthening to many.
His engagements in the line of ministry amongst us were not frequent;
but he was at times led to address his friends in a weighty and feeling manner;
endeavoring to turn their attention from a dependence on man,
and from all that is superficial in religion,
to a single reliance on the great head of the church,
"`the Minister of the sanctuary and of the true tabernacle, which the Lord pitched,
and not man.`"

Our dear friend was remarkable for integrity and uprightness of heart;
and in the private walks of life his conduct was strikingly circumspect,
and his conversation, while innocently cheerful, was instructive,
being seasoned with grace.
Notwithstanding he was, in the ordering of unerring wisdom,
much confined at home from bodily infirmity,
yet his concern for the prosperity of our Society remained unabated;
and his mind was actively employed in endeavoring to
promote the spiritual welfare of its members.
With this object, his time was much occupied in editing a series of publications,
selected from the writings of our honored predecessors in religious profession.

In the eleventh month, 1836, he paid an acceptable visit, in the love of the Gospel,
to the families of Friends at Brighton; and in the eleventh month, 1837,
he felt attracted by the same precious influence,
to a similar engagement in his own particular meeting of Stoke Newington.
After going through nearly half the families,
wherein his service was much to the comfort of his friends,
finding his constitution increasingly enfeebled,
he returned to the monthly meeting its minute granted him for that purpose,
accompanying it with a letter, replete with the expression of religious concern,
from which the following is extracted:
'`On proceeding in the weighty engagement before me,
I may acknowledge that although no wonderful outpouring of divine power was my portion,
I was mercifully favored, during the few days that I entered upon the work,
with such a sense that the Lord preserves the simple and the upright,
that it was as my meat and drink to be thus among my friends;
hard things were made very easy, and bitter things full of sweetness;
a gently flowing stream of heavenly goodness being extended in every hour of need,
though in a way humiliating to the creature,
and so as nothing of the flesh could glory.`' His health continuing to decline,
he went to Brighton; but there his indisposition increased,
and on the 8th of the fifth month, he was, by medical advice, removed to Tunbridge Wells;
after which he survived but a few days.

On the evening of the 9th, when about to retire to rest, on rising from his chair,
and leaning on the couch and on the arm of his beloved wife, he supplicated thus:
"`O! gracious Father! if it please you, spare us to each other a little longer,
and make us more entirely devoted to you and your precious cause of truth in the earth;
nevertheless, not our will, O Lord! but yours be done,`"

On the next day, which was the one immediately preceding his decease,
he uttered many weighty expressions; amongst which were the following:
"`The truth shall prevail.--Truth shall reign over all.--None
that trust in the Lord shall be confounded;
but they shall be as mount Zion, which cannot be moved.
You all know my desire to be preserved near the
Lord--to be strengthened and upheld by the Lord;
to be found in him;--this is the way of peace.
I trust we shall be strengthened and animated to go through our day`'s work;
then we shall find mercy at the hands of the Lord.--Let us look to the Lord for strength,
at all times and under all circumstances.`"

In the latter part of this day, his voice was lifted up in a constant melody,
and for many hours together, like a song of praise; during which,
these words were clearly distinguished,
"`O Lord!--dear Lord!--come.--I bless the Lord.--I am the Lord`'s forever.--Cleave to him,
O! cleave to him,--love Him with all your heart.`"
The name of Jesus was often to be heard, and the word hallelujah was frequently repeated.

About four o`'clock in the afternoon of the 11th of fifth month, 1838,
he peacefully passed away, aged forty-one years, a minister about fifteen years; and is,
we reverently trust, united to the redeemed before the throne, who sing the new song,
"`Worthy is the Lamb that was slain, to receive power, and wisdom, and riches,
and strength, and honor, and glory, and blessing.`"

Given forth by our monthly meeting, held at White Hart court, Grace-church street,
the 10th of tenth month, 1838,
and signed by--

[.offset]
+++[+++__Here follow the signatures of men and women Friends.__]

Read and approved in our quarterly meeting for London and Middlesex, held in London,
this 25th day of the twelfth month, 1838, and in and on behalf thereof,
signed by

[.signed-section-signature]
George Stagey, _Clerk._

Signed in and on behalf of the women`'s quarterly meeting, by

[.signed-section-signature]
Mary Forster, _Clerk._
