== Chapter V.

1817, Fifth Month 20th.--O! how fervently, how earnestly,
have my cries and breathings ascended to Him, who is the fountain and source of all good,
that all the true well-wishers to Zion`'s welfare,--all the hearty, zealous,
living labourers may be preserved at this season,^
footnote:[The Yearly Meeting in London]
on the right hand and on the left;--that they may be kept in their proper places,
and in subjection to the Great Master of our assemblies;--that their spiritual
eye and ear may be opened and enlivened by his healing hand;--that their
speech may be directed and their mouths filled in his own time and way,
to his glory!
May each one of these be kept low under His almighty hand;
may that which is of the creature within them be abased,
whilst that which comes from the source of life and glory,
is exalted above every obstacle or opposition.
O! Thou, who art pleased at times to favour thy poor dependent little ones,
those who have no hope, or help, or happiness,
but in the smile of thy benignant countenance,--be pleased at this time
so to refresh their hearts with the influence of thy paternal presence,
so to overshadow them with a sense of thy continued protection and care,
that they may be severally encouraged and confirmed to serve Thee with greater diligence,
to devote themselves afresh to thy service and disposal,
and more sincerely and unreservedly to say and to feel,
that Thy will is best in all things!

1817, Sixth Month 1st.--I have attended the sittings of this Yearly Meeting,
as well as those of its large Committee on Epistles, of which I was nominated a member;
and am inclined in this manner to notice it.
I think I never saw the importance of our assemblies,
or indeed of any system of church government, in so strong a light,
as previously to this Yearly Meeting.
For many days before it commenced,
my mind seemed engrossed with a sense of the weighty act of duty,
which we were going to take in hand:
I was encompassed with earnest desires and great exercise of soul,
that every individual attendant there, might be availingly instructed,
and benefited whether it should fall to his lot to be more or less prominently engaged;
and that thus whatever we might do in word or deed,
we might do all to the glory of the Lord, and for the promotion of his great cause.
I was favoured to continue in the same tender feeling frame of mind,
with but little diminution, to the conclusion of our solemn engagement: at times,
the Lord did extend his precious gathering wing over his poor dependent little ones,
and enabled some to sing in their hearts to his praise;--blessed be his holy name.
O! what a privilege it is, to experience preservation on every hand,
to be each of us kept in our proper places, and under our own fig tree,
where none can make us afraid,--each of us abiding under our particular exercises,
and upon the watch-tower.

[.embedded-content-document.epistle]
--

[.letter-heading]
A Few Lines Affectionately Offered and Addressed
to Every Young Person Whom they May Concern.

[.signed-section-context-open]
1817, Sixth Month 10th.

[.salutation]
Dear fellow traveller,

In a little of that love which has been extended to me by Him,
who "`showeth mercy unto thousands,`" I send thee these few lines;
sincerely desiring that the eye of thy soul may be so effectually
opened and enlightened by the healing hand of the great physician,
Christ Jesus, as to enable thee clearly to see the things which belong unto thy peace,
before they are hidden from thee.

Dear fellow traveller, dost thou not at times,
when thy mind is in some degree disengaged from the round of sin and folly,
or when thy natural flow of health and spirits is somewhat broken,
dost thou not feel within thee convictions of thy wickedness,
and condemnation for the same?
Hast thou not intelligibly heard at such intervals a language which whispers,
"`all is not right!`"
Hast thou not felt that the end of these things, in which thy gratification is placed,
can never be peace,--can never be any thing short of death,
eternal death to the soul that persists in them?
Be assured then, that although these are thy secret feelings,
thou art still the object of infinite condescension and lovingkindness;
he who desires not the death of the evil doer, but the death of the evil,
is still near thee,
notwithstanding all thy rebellion,--following thee in thy ways which are those of sin,
and running after thee as a shepherd, in search of his strayed sheep.

These pleadings of Divine grace, these convictions of the Spirit of Christ,
which in spite of thy concealment of them are pursuing thee,
and in spite of thy endeavours to appease them by partial reformations are galling
thy soul,--even these are the evidences of His gracious hand upon thee;
who wounds only to heal, and whose very judgments are in mercy.
O! that thou mayst come to see with undoubted clearness the truth of this;
that thou mayst be encouraged and emboldened unreservedly to follow that, which is,
as I fully believe shown thee to be right and acceptable
in the sight of the great Judge of all the earth.

Assuredly He has shown thee, what He is requiring at thy hands,
and what his righteous controversy is with:
He requires of thee nothing but that which has separated thee from Him,
the only source and centre of true joy,--nothing but that which, if not forsaken,
will embitter thy present life, and plunge thee into utter darkness after it.
Dear fellow traveller, it may be that thou hast been, within these few years,
my companion in the walk of wickedness;
that we have taken delight to set at defiance the commandments of a great Creator;
and have yielded ourselves, and all that we possess,
the ready instruments of Satan:--our time, our talents, our means, our youth, our health,
our peace have been freely sacrificed at the altar of our soul`'s enemy.
Be then entreated by one who has him self trod in this path;
who has hurried forward with impetuosity down this fatal current, who,
borne by the rushing waters to the very brink of a tremendous precipice,
has been there snatched from the very mouth of destruction.
There is indeed, dear young person, neither help, nor hope, nor happiness,
even in this state of existence, but in the favour of Him,
(in whose favour is life,) in implicit obedience to the
Divine will as far as it is made known to us.
It is to no purpose that we reckon ourselves,
or are reckoned by others as belonging to this sect or the other church,
to this class or the other division of professing Christians--if we fall
short of those unalterable marks and evidences of true Christianity,
by which we shall be known and distinguished in that great day,
when every gloss will be removed,
and every ceremony and shadow shall fade before the eternal sun of truth.
We read that at that awful crisis, there shall be but two names or classes,
by which the inhabitants of the whole world shall be known,--the
sheep and the goats,--the good and the bad.

Well, dear fellow traveller, it remains for each of us,
if we have any desire that this transient state of
being may terminate in an unfading inheritance,
to lay aside all the false and foolish reasonings, all the vain suggestions,
the cheating insinuations of an unwearied adversary;
and with sincerity and simplicity of soul,
to take up the holy resolution to seek and to serve the Lord our God,
during the few remaining days that may be allotted us; and to this end,
that we be found daily inquiring in his temple, the temple of our own hearts,
and waiting upon him there, where his kingdom must come and his will be done;
that so we may feel his presence and power,
to direct and to guide us into the saving knowledge of himself.
That thou and I, as well as all our poor brethren upon the face of the earth,
may be of that gloriously happy number,
who shall inherit an eternity of joy unspeakable in the kingdom of heaven,
is the earnest desire of one who feels himself thy soul`'s true friend.

[.signed-section-signature]
John Barclay

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to a Friend

[.signed-section-context-open]
Clapham, 16th of Sixth Month, 1817.

Whilst thinking of writing to thee, a part of a beautiful meditation of the Psalmist,
on the works and wonders of Providence, occurs to me.
After dwelling much on the variety and immensity, the order, the harmony,
the excellent provision and appointment of all things both in heaven and upon the earth,
the poor servant cries out,
as if unequal to the task,--"`O Lord! how manifold
are thy works! in wisdom hast thou made them all;
the earth is full of thy riches.`"
I remember it is somewhere said, "`all thy works shall praise thee,
and thy saints shall bless thee;`" and whilst we
thus see that the heavens declare his glory,
and the firmament his handy work,--whilst we see that all his works praise him,
are we not convinced that his saints should likewise bless him?
Are we not abundantly persuaded, that man also,--whom we now see the only flaw,
the only speck in this vast production, perverted in himself,
and perverting the rest of the creation,--was originally
made pure and perfect in his kind,
and did then glorify his Maker.
O! how fully do I believe, how clearly do I see,
that it is only as we poor creatures come to be renewed in the spirit of our minds,
and to experience the putting on of the new man,
which after the image of Him that made us, is created in righteousness and true holiness;
that we can rightly worship, acceptably praise,
and truly give glory to so infinitely righteous and holy a Being,
with whom we have to do.
Thus alone are we brought inexpressibly to feel,
the beauty of those scriptural or other writings,
which dwell on the works of the creation; thus also are the faculties of our mind opened,
enlarged, and quickened to examine, to perceive, and to adore,
the great First Cause of all.

What a blessed experience, when everything within us and without us, the stars above us,
the dust under our feet, seem all to join with us,
and to show forth that Power which has made them,
and which supports and sustains this system, this machinery of the universe.
Surely the revolutions and vicissitudes to which the spiritual
as well as the natural kingdom seem subject,
the turnings and overturnings, the storms and the calms, the darkness and the brightness,
the dreary and the cheering prospects, the drooping and the delightful seasons,
are equally in the hollow of his hand, who is said to be "`all in all.`"
He saith to the raging winds, "`peace be still,`" and to the foaming billow,
"`thus far shalt thou come, but no further.`"
What then should be the invariable language of our hearts,--what
should be the clothing of our spirits day and night,
in all extremities, and under all the circumstances to which we are constantly liable,
but--"`the will of the Lord be done.`"
O! that we might be privileged to continue from day to day, and all day long,
in such a prostrated, humbled, reverential frame of spirit,
as would indubitably evince our belief in the presence, protection, providence,
and power of Him, whom we profess to serve.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
J+++.+++ B.

--

1817, Sixth Month 24th.--I think I have never felt in so reduced a condition,
in so pitiable a state of mind, as during some intervals of late:
at this time especially,
it seems as though I were at the very boundary where distress of soul ends,
and where utter darkness and desolation begin.
Still is there something like hope;--still is there, through the infinite mercy of Him,
whose kingdom and whose power are far above the dominion of the wicked one,
something resembling the faintest glimmer of a spark of light,
through all the horror and gloom which reigns.
O Lord! this once help me,--condescend to bless me, and be with me,
and I will follow thee whithersoever thou leadest.
O! Lord God of my fathers, I have read of thy goodness towards those who sought thee,
towards those who trusted in thee, in times that are past; I have seen, and I have known,
and am sure, that it shall ever be well with those, who have no help, or hope,
or happiness, but in and by and through thee, the source and centre,
the spring and the river of all consolation and refreshment.

1817, Sixth Month 25th.--I attended our Quarterly Meeting held this day,
under a weight of discouragement, without being able to feel anything alive within me.
It seemed to some, however, to be an open time, a time of refreshment;
the truly hungry and thirsty were shown what a blessed condition they were in;
and they were directed to the fountain of living waters, the living bread from heaven,
whereby they might be nourished up into eternal life.
There was also a supplication put forth on behalf of some,
who were under discouragement and doubting whether
they ought not to enter upon some important duty;
and a desire for such,
that they might "`go forth in this their strength,`"--in the deep
sense of their own weakness:--which much reached me.
The sittings for business were no less trying to me, and I believe to some others,
who mourn at the untempered,
(if I may use that expression,) or rather perhaps unleavened manner,
in which these our meetings for the promotion of good order,
Christian conduct and conversation, are sometimes held.
Oh! how little of an inwardly gathered and retired disposition
do we see,--how little of that weighty concern and exercise of
soul--that abiding under the overshadowing canopy of pure fear,
which were witnessed by those amongst us, in former times,
and spoken of in these words of William Penn: "`Care for others was then much upon us,
as well as for ourselves, especially the young convinced.
Often had we the burden of the word of the Lord to our neighbours, relations,
and acquaintances, and some times to strangers also:
we were in travail for one another`'s preservation,
treating one another as those that believed and felt God present;
which kept our conversation innocent, serious, and weighty.
We held the Truth in the spirit of it, and not in our own spirits,
or after our own will and affection.
We were bowed and brought into subjection,
insomuch that it was visible to them that knew us;
we did not think our selves at our own disposal, to go where we list,
or say or do what we list or when we list:
our liberty stood in the liberty of the Spirit of Truth; and no pleasure, no profit,
no fear, no favour, could draw us from this retired, strict, and watchful frame.
Our words were few and savoury, our looks composed and weighty,
and our whole deportment very observable.
I cannot forget the chaste zeal and humility of that day;--O! how constant at meetings,--how
retired in them,--how firm to Truth`'s life as well as to Truth`'s principles!`"^
footnote:[William Penn`'s Rise and Progress.]
Thus far William Penn, and oh! that we could say, that anything like all this,
did really and truly pervade our conduct now, as a religious body.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to Thomas Shillitoe.

[.signed-section-context-open]
Clapham, 30th of Sixth Month, 1817.

[.salutation]
Respected Friend, Thomas Shillitoe

Having fulfilled the object which induced me to send the preceding lines,
I am inclined to add a few more;
which I am ready to believe I should have done well to communicate to thee,
when last in thy company.
I faintly recollect, many years past, when but very young and at school,
hearing thee (I think I cannot be mistaken as to its being
thyself,) in a meeting for worship at Wandsworth,
largely and powerfully engaged in testimony.
I also remember my own feelings at that season, how ready I was to laugh thee to scorn,
and to despise thee.
But I have been met with, like poor Saul; and am now brought to such a pass,
that I cannot find satisfaction or even safety,
in any thing short of a warm and unreserved espousal of that cause,
which I but lately made light of.

The subjects to which thou wast concerned to call the serious
attention of Friends at the last Yearly Meeting,
have been deeply felt by me; and I may truly say,
that nearly as long as I have been privileged by
an acquaintance with the houses and families of Friends,
(which though I was born a member,
is not long) I have at times almost mourned at the great relaxation from Gospel strictness,
and simplicity of living, so evident amongst us.
Surely I have thought if we were to cast out the crowd of opinions,
which have got the first place in our minds,--opinions founded or cherished by custom,
example, and education in the good, and by vanity, or something worse, in the bad;
and if we were coolly and calmly to listen to the silent dictates of best wisdom,
we should clearly see, that the holy principle which we profess,
(to use the words of John Woolman,) inevitably "`leads those, who faithfully follow it,
to apply all the gifts of Divine Providence to the purposes for which they were intended.`"
I venture to say, we should then find a greater necessity laid upon us,
to exercise self-denial in what we are apt to think little matters,
than is now often thought of;
we should have such a testimony to bear against superfluity, extravagance, ostentation,
in consistency, and the unreasonable use of those things which perish with the using,
as we now profess to have,
against the more flagrantly foolish customs and fashions of the world.
Whatever some may think in regard to these things, I feel assured, that he,
who in his outward appearance or behaviour,
bears any remnant of a testimony against the customs and fashions of the world,
ought to be ashamed of himself, if he belies his avowed sentiments,
by a departure from simplicity in the furniture of his house, and way of living.
Wilt thou excuse my saying a little more, dear friend,
on so important a subject as this has long felt to me?
I have been almost ready to blush for some, at whose houses I have been,
where pier-glasses with a profusion of gilt carving and ornament about them,
delicately papered rooms with rich borders,
damask table-cloths curiously worked and figured extremely fine, expensive cut glass,
and gay carpets of many colours, are neither spared nor scrupled at.
Some indeed seem to be desirous of disguising and excusing their violation of the simplicity,
which their better feelings convince them they should practice, by saying,
that this or the other new or fashionable vanity is an improvement on the old
article,--that this gay and gaudy trumpery will wear and keep its colour better
than a plainer one,--that this precious bauble was given them by their relations.
Thus are they endeavouring to satisfy the inquiries of those who love consistent plainness,
and to silence that uneasy inmate, the unflattering witness which is following them.
I have been much exercised and troubled on my own account, and on that of others,
as to these matters;
and have been very desirous that we may all keep clear of these departures.

Thus thou seest I have felt much freedom in addressing thee,
even like that of an old acquaintance;
and hope I shall never want this honest openness to wards such,
as are examples in conduct and conversation; for when there is a want in this respect,
it seems with me to indicate a want of that,
which brings with it boldness and confidence towards all men,
even a fear of One who is greater than man.
With desires that,
in receiving and reading this communication from one who is so young in years and experience,
thou mayst be encouraged in thy arduous labour,
in which I have felt much sympathy with thee;
and trusting it may be blessed by the reward of peace to thyself,
and by the return of many a backslider to the living fountain.

[.signed-section-closing]
I remain thy sincere friend,

[.signed-section-signature]
J+++.+++ B.

--

1817, Seventh Month 4th.--In reading the 13th chapter of the 1st book of Kings,
I have at this time been much instructed,
and am ready to take the lesson to myself as a warning or special admonition.
Herein we see, that it availed nothing in respect to the future,
that the prophet had (though so lately,) been favoured with a divine commission,
and was hitherto upright in the faithful discharge of that arduous duty which
devolved upon him from his Lord,--even that of openly proclaiming the vengeance
of the Almighty against the idolatry that had overtaken the people,--and boldly
asserting the destruction of the priests even to their faces,
and in the presence of their king;
saying to him in reply to his invitation,--"`If thou wilt give me half thine house,
I will not go in with thee;
neither will I eat bread or drink water in this place:`"--yet after all,
he was weak enough to give up his own clear convictions of duty,
as revealed in and to himself,
(the truth of which was indubitably evinced and sealed by the miracle
which attended the partial performance of them,) and to prefer obeying
the old prophet before compliance with "`the word of the Lord.`"
O! how greatly have I longed in a peculiar and especial manner for myself,
as I am now situated and circumstanced,
that I may steadfastly adhere to no other law but the law written on the heart;
and closely to attend to the secret dictates of best wisdom alone.
For assuredly there is no safety,
but in implicitly giving up to the reproofs of instruction,
which are and ever will be the way to life.--"`Be
ye followers of me,`" says the apostle Paul;
but he adds,--"`even as I also am of Christ;`" intimating surely that
the examples of others in life and conversation are to be followed,
only so far as they accord with the example and precepts of Him, who said,
"`I am the light of the world,`"--"`whilst ye have the light
believe in the light,`"--"`walk while ye have the light.`"
So that in looking back at such acts of dedication,
as have been (according to my belief) required at my hands,
and in contemplating the peace which has ensued after even the smallest surrender,
when the sacrifice has been offered out of a sincere and upright heart; I have earnestly,
and I may truly say above every other earthly consideration,
desired that nothing may be suffered to hinder me--to turn me aside,
even in trifling as well as in great matters and concerns, from carefully, closely,
unremittingly attending to, and abiding by,
the counsels and teachings of that divine principle, even the Spirit of Christ,
which is given to every one for his guide in the way of salvation.
I have found amongst many other acts and false suggestions and temptations,
which the enemy makes use of to deter us from giving
up ourselves to the guidance of the Holy Spirit,
one which is much talked of and acted upon by many, through their own inexperience,
and the deceit of the prince of darkness; namely,
that these leadings and secret influences and inspirations,
are not distinguishable from the workings of our own mental or rational powers;
and if they are distinguishable, that these persons have not felt them or known them.
Now in answer to this, which has been my own delusion, I may say,
that every one who has for a long season habitually
stifled by disobedience this divine monitor,
cannot expect to hear or to understand so plainly its voice,
as those do who have for a long period listened to its secret whispers,
and surrendered themselves unreservedly to its injunctions: these can testify,
that they follow no uncertain vapour or idle tale;
but that its reproofs are to be plainly perceived, and its incitements early to be felt;
and that the peace they witness cannot be imitated,
neither can it be expressed to the under standings,
or conceived by the imaginations of such, as have none of this blessed experience.
Nor let any poor, seeking, sincere, or serious minds be discouraged,
that they do not upon submission immediately or very quickly feel what they wait to feel,
even the arising of that secret influencing, actuating,
constraining and restraining power or Spirit of the Lord.
Let them not be discouraged if this be their case,
nor be dismayed if even after some considerable sacrifices
and trying testimonies of sincerity,
they find not that rich reward of peace which they had expected.
Let such remember, it is written,--"`he that endureth to the end,
the same shall be saved:`" now where there is a moment`'s enduring only,
and that previous to or whilst in the performance of what is required,
this cannot be called "`enduring to the end;`" but O! it is that
"`resistance unto blood`" (as it were,) in faith and faith fulness,
that "`patient continuance in well doing,`" in defiance of difficulties, discouragement,
darkness, doubt, and distress, which will give us the victory,
and will make us through the mercy of God in Christ Jesus,
heirs of that eternity of peace, and rest, and joy,
which we know is prepared for such as overcome.

1817, Ninth Month 6th.--For more than a week past,
I have been plunged by the permission of best wisdom,
into such a depth of darkness and discouragement,
without any perceptible glimmer of alleviation or ray of comfort, that my poor, tossed,
troubled soul seems on the very point of giving up the contest,
and losing hold of its only support and security.
Whilst the heavens are as brass, and the earth as it were iron, what is frail,
helpless man to do for himself?
It seems to my view, that there is nothing left for him to do to aid himself,
or to deliver himself out of his forlorn situation,
but to sink down into his own nothingness; and there, as in the dust,
to remain all the Lord`'s determined time,
until he shall seem meet to appoint unto him "`beauty for ashes,
the oil of joy for mourning, the garment of praise for the spirit of heaviness.`"
When I took my pen to write what has thus been written,
I did not expect to come to the preceding conclusion,
or that any such reflection would arise out of the subject.
The Lord grant that what I have written, may be more than mere words:
and that through and over all difficulty and distress,
I may come forth the wiser and the better, and more devoted to his disposal,
and more patient under his dispensations.

1817, Ninth Month 17th.--I believe myself called upon to bear an open, unequivocal,
unflinching testimony, not only against all pride, extravagance, ostentation and excess,
but also in a peculiar manner against all the secret insinuations and covered appearances,
under which they are creeping in, and growing up amongst us as a Society.
I have for years believed,
that the declension amongst Friends from the true standard of simplicity is great;
and I am of the mind, that if they had diligently hearkened unto,
and implicitly obeyed the dictates of best Wisdom,
they would have been led to "`apply all the gifts of Divine
Providence to the purposes for which they were intended.`"
I believe that it is my duty to live in such a humble, plain, homely, simple manner,
as that neither in the furniture, food, or clothing used,
any misapplication of the gifts of Divine providence be admitted or encouraged.

1817, Ninth Month.--"`Day unto day uttereth speech,
and night unto night showeth knowledge;`" and where
is an end to praising the Lord for his mercy,
which "`endureth forever,`" and which is abundantly shed abroad,
to the rejoicing of the hearts of those that seek to serve Him,
and to the great comfort of their souls in the midst of much tribulation.
O! that there may be more and more reliance, unshaken, immoveable reliance on Him,
who thus daily scatters and profusely deals out tokens of his lovingkindness.
O! that there may be an increase of faith experienced,
an increase of resignation proportioned to the nearer approach
of perplexity and difficulty and embarrassment on every hand.
And now when the waves of affliction run high, and the floods seem irresistible,
may the Lord Almighty,
who "`is mightier than the noise of many waters,`" in his
own time lift up a standard against them,--saying,
"`thus far, but no farther.`"
O! surely,
He who remains as ever to be the only sure "`confidence of all the ends of the earth,`"--He
who can overrule events for the good of those that sincerely seek him,
will not overlook or despise any of those, who desire to look unto,
and who lean upon Him alone in all their troubles.

"`O! Lord God of my fathers, art not thou God in heaven?
and rulest thou not over all the kingdoms of the heathen?
and in thy hand is there not power and might, so that none is able to withstand thee?`"
Art not thou my God, art not thou my joy, my delight, my glory, the crown of my rejoicing?
Art not thou He, that hath hitherto helped me, that hath brought me out of much evil,
that hath inclined my heart to seek thee, and my soul to love and fear thee?
Wilt thou not arise for my help in the time of trouble, of temptation, of darkness,
of distress, from whatever cause these may proceed, whether by thy permission,
or by thy appointment?
O! Lord, thou knowest perfectly, what are the causes of my present disquietude,
and how to dispose of all things for the best,
both as to the present and as to the future: thou knowest how poor, and weak,
and utterly incapable I am to help myself in any exigency that may arise;
and that without thee, nothing but confusion, and sorrow, and desolation,
is likely to be my portion: O! make me yet more deeply and lastingly sensible of this,
and that "`I have no might against this great company that cometh against me,
neither know I rightly what to do.`"
I beseech thee, renew daily and hourly my faith and dependence,
and watchfulness unto prayer, and my love and fear of thee.
O! arm me with thy gloriously impenetrable armour;
and make me strong in thee and in the power of thy might;
that through thy abundantly sufficient grace and truth,
I may be fit for all occasions and trials, to which thou mayst see meet to call me:
that so, my eye being continually upon thee, thy precious cause may prosper,
and thy name be exalted by me, in me, and through me,
both whilst my soul is confined in this frail body, and forever and ever. Amen.
