== Chapter IX.

John Barclay to +++_______+++

3rd of Second Month, 1819.

Dear +++_______+++,

I have often believed that the blessing in store for those who
hand "`the cup of cold water,`" may not pass from thee and thine,
as thou art yet concerned to struggle on in the narrow way.
I desire to be thy companion therein,
and an example in giving up faith fully to all that is set before me,
whether in the line of doing, or of suffering;
who am often sensible of something still blotting out and
wiping away many a spot contracted through unwatchfulness.
There is a very precious feeling that seems to prevail with me, whilst saying thus much;
and I may add, that though nearly day by day bowed down and broken,
under a view of the low state of things at home (in the heart) and abroad,
and of many sacrifices and services for the cause which are called for at my hand;
yet I may acknowledge the very windows of heaven have been opened,
and showers of refreshing help and, strength have descended,
such as cannot be contained or expressed:
so that the encouragement is great for me and thee and all, yet to struggle on;
laying aside that which hinders.
And I think I may safely say to thee dear +++_______+++,
there has already been received by me an equivalent to the hundred-fold,--houses,
brethren, sisters, with suffering; though I look for something still better in the end.

From thy affectionate friend,

J+++.+++ B.

John Barclay to +++_______+++

1819, Fifth Month 4th.

I have sometimes remembered the language or sentiment of a tried servant,
who by being resigned to the Divine will through
the tribulations that were in wisdom handed,
was enabled to comfort a brother in words like these;--"`if we be but clean vessels,
no matter how empty;`" and I may add,
"`no matter how long on the shelf,`" and as one says,
like "`a pitcher placed upside down, on its mouth,`"--to keep the dust out.
The only danger I have found, when counted worthy,
or clean enough to be set in this trying position,
has been that of repining at the dispensation allotted,
or not quietly seeking after acquiescence.
If we were but willing to abide the operation of the Almighty hand,
which would make all of us vessels fit for a place in his holy temple,
and a service in the Lord`'s house;
and were but enough sensible of the benefit of these turnings and overturnings,
and of the blessing that they are to those that are patient enough to profit
by them;--surely some of us that are now ready at seasons to give over struggling,
and to think it is to no purpose endeavouring to
hold out in faith and faithfulness any longer,
(presuming the Lord hath for gotten us,) would rejoice
that we are counted worthy to drink of the cup,
and to be baptized with the baptism,
which alone can purify and prepare for a seat in the heavenly kingdom.
"`It shall be given to those for whom it is prepared,`"--"`I go to prepare a
place for you;`"--and did He not go through suffering;--was He not said to be
made perfect through the same;--and shall we find a safer path than in His footsteps,
"`who endured the cross and despised the shame.`"

Some of us in this day of great profession and performance,
have to be renewedly baptized into a deep sense of the state of things,
both without and within;
and to labour earnestly after the pure and unshackled
arisings of the seed,--which is often very low,
and burdened with much that seems to be favourable, but yet greatly oppresses.
I desire for thee, dear J.,
that thou mayst not be without thy full appointed share of such conflict of spirit,
and even apparent desertion of heavenly help and strength as is best for thee;
and that thou mayst have the grain of faith renewed day by day, the hidden manna,
the secret sustenance which enables quietly to wait and patiently to hope,
even through all things:
so that if these dispensations should be in judgment or in mercy,
thou mayst be favoured through submission, to rise above all that has stood in the way,
steadily persevering in a course of humble, dependent, watchful, innocent conduct.
I believe that marriage is often made a means of furthering the religious growth,
and strengthening the mind in that which is good,
as we look to the Lord in our proceedings, having him in our eye,
above and before all idols.
But few measures taken in life, perhaps, are so likely to entrap the unwary,
as an injudicious engagement therein;
it unsettles and uncenters the mind from the great first object,
if much care be not exercised, and diligent watchfulness maintained.

John Barclay to E. S.

1819, Seventh Month 22nd.

The examination of religious tracts proposed to be printed, is a weighty service.
If it were only to judge of words,
the consistency of the sense and meaning with the principles which we profess,
as far as human wisdom can distinguish, this would be easy,
and could be compassed by the spirit of a man: "`but the things of God knoweth no man,
but the Spirit of God;`" so that man`'s spirit is unequal to it,
but must be in subjection,
with all the vain reasonings which he can muster up and
contrive by the natural powers of his understanding,
or by his acquired learning and erudition;
and he must wait to feel that raised up in him,
which is able rightly to discern and comprehend the precious,
and to distinguish it from the vile.
I believe a time may come, when the writings of many of our early members,
who shone bright in their generation, may again rise into repute among us,
and also among others;
notwithstanding the unfashionable garb in which many of these writings are clothed,
so unsuitable (apparently) for these times.
So that one would like to see the avenues kept open, and the channels clear,
and the conduits clean; that whatever is to flow in the ordering of best Wisdom,
may flow freely.
As to what thou sayest of the fear of some,
about the style of our early Friends`' writings, I think this fear is a weakness,
and proceeds from a sort of doubting in the mind about the writings themselves,
and not merely about the language.
I would ask these fearful ones,
whether in reading a peculiarly interesting history or travel,
the subject of it does not carry them above the style, so that almost any style,
however prosy and dull, is over looked;
and this is the case tenfold more strongly with the
humble seeking soul in religious matters,
by whom the words are overlooked in the earnest desires after the substance.
Those who are admirers of words, whether they be words printed or words preached,
are very unlikely to be benefited really and truly by either,
having gone from that which is beyond words, and which alone can make words effectual.

1819, Sixth Month 5th.--Great have been my temptations:
yet abundantly manifest through all,
have been the out-stretchings of the ancient and eternal arm of power:
so that to this hour, it is alone through the Lord`'s eminent mercy and long-suffering,
and by his preserving strength and help daily extended toward me,
that I am yet alive in Him, and able to celebrate his name, and seek his face,
and wait for the fresh arisings of his holy heavenly virtue;
by which alone I can do any thing acceptably for
his great and glorious cause in the earth,
or be his dutiful and faithful son and servant.

1819, Date uncertain.--O holy blessed Father! thy love shed abroad in the heart,
thy sweet refreshing influence, can make up for all;--thy softening,
healing balm makes us forget our wounds and weeping.
O! how good thou art to those who still struggle after resignation
and sigh after submission to thy holy will!
Though they fall many times,
yet how is thy strength manifested for their recovery and relief,
for the renovation of their faith and courage;
so that all their transgressions are blotted out, and their unfaithfulness is wiped away.
This is precious indeed--to feel access to the fountain set open for sin and iniquity;
and thus to be brought nigh by the blood of the Lamb, and to feel its cleansing virtue.

1819,
Seventh Month 15th.--O my Father! how precious is thy love to my soul
at this time! how glorious is the manifestation of thy life-giving presence,
in and unto my poor tabernacle!
How hath the sweetening,
sustaining influence of thy pure and Holy Spirit refreshed and
animated my inward man!--how hath it even invigorated the frail
and slender frame of this perishable body! so that thou hast,
at this heavenly season, prevailed upon and reduced into true passiveness,
everything that is within me: and I am renewedly prepared, O Lord! thou knowest,
to offer unto thee all that I have, or am; and can say,
in the holy confidence and courage and ability which thou givest,--"`I am thine,
and thou, blessed Lord God of power and of everlasting praise and of mercies infinite,
art mine; and I live by thee, and see, and know, and love, and glorify thee and thy Son,
the Lamb, Jesus my Saviour, through the eternal Spirit;--praises,
praises to thy name forevermore.
Amen!`" (Written in a grove at Knapton, in Yorkshire.)

1819, Eighth Month 25th.--O! Thou that seest in secret, that knowest all things,
that searchest the hearts, and triest the inward parts of all men,
and in whose pure sight iniquity is discerned and judged,--may it please
thee yet once again to regard and pity thy frail and faultering servant:
who am not worthy to be accounted of thy household; and yet cannot rest satisfied,
in any thing short of a pure and perfect surrender
and sacrifice of my all unto thy service.
O! thy presence, thy purifying,
preserving energy and virtue inwardly communicated to my soul,--how has it helped
me along in my earthly pilgrimage,--how has it sustained me in the year of drought,
and in the hour of temptation and of trial!
In all the depths into which I have been, and may be, cast or permitted to be plunged,
Lord! thou knowest that nothing has been able, or I trust shall be able,
to induce me to deny, that thou hast blessed me and done me good.
Though thou slay me, yet will I endeavour after resignation and submission; for,
without thee what am?
O my Father! is there yet a door of hope for me, yet a little access left for me,
before I go hence, and of men am seen no more?
May I presume to plead with thee for forgiveness and pardon,
who am unworthy to hope for it;
having so often transgressed and offended by unfaithfulness and many backslidings.
(Written in a wood at Yealand, near Lancaster.)

1819, Ninth Month 5th. (First day.)--What a mixed race we are,
even the brightest and best,--what a dwarfish set:--it is
most true indeed that we have not attained to the stature,
strength, or standing of our fathers.
Yet O! how bright in the horizon was the opening,
the breaking forth of the morning of the day of the Lord`'s everlasting power!
Verily his hand is not shortened,
the glory of his excellency and of his strength will yet be manifested more and more;
he will beautify his holy Church and peculiar people, and brighten up his jewels;
and they shall shine as the stars forever and ever.
And many nations shall flow together, and become one fold on his holy mount; and he,
the Shepherd, shall feed and lead them; and they shall lie down in his green pastures,
and drink of the pure river of his eternally satisfying pleasures:
and as they abide where he would have them, nothing shall harm them,
nor any iniquity prevail against them; and they shall never perish,
neither shall any pluck them out of his holy hand.

John Barclay to Samuel Alexander.

21st Tenth Month, 1819.

I omitted to mention our Quarterly Meeting: it was held to satisfaction.
It is lamentable to think how much harm is done,
by the talkativeness that sometimes manifests itself after such very solemn occasions:
and in Meetings for Discipline, there are those,
who knowing much of the outward rules which Truth has led our Society to adopt,
are not sufficiently careful to act in the life, in the liberty, in the sweetness,
in the dignity of it; but suffer their mere adherence to rules,
without subjection to the power in which they were set up, to mar at times the beauty,
the benefit, and the glory of these meetings; which should be religious meetings,
and would often be made meetings of worship, to those whose minds are rightly engaged.
Surely the authority of these meetings is not the mere Book of Extracts;
nor does their excellency consist in a mere mechanical
compliance with what is there laid down;
nor does much talking in favour of any point, prove that the sense of Truth is that way,
though it may prove that the sense of the majority leans so.

John Barclay to a Friend.

London, Eleventh Month 6th, 1819.

My dear love has often been as fresh and warm towards thee,
amidst much sympathy and solicitude on thy account as on my own;
that we might both be preserved by the invisible,
invincible power and principle of Truth, through our patient seeking after, waiting for,
and following its pure and sure guidance:--amidst earnest desires that this may be thy,
(and also my) experience,
it has not seemed unpleasant nor unexpected that little
should hitherto have passed between us in this way,
which true friends have found and do yet find to be but a feeble channel,
though profitable and comforting,
when the reader can discern and read the language of the heart of his friend.

It is a certain axiom,
though a strange paradox to such as have not yet come to
witness the truth of it in their own experience,
that the true silence speaks louder than the best words.
I sometimes think that I, for one,
have enough to do to steer my own frail vessel in the stormy sea of life,
with the aid afforded;
being willing often to leave others to the like engagement for themselves.
For one finds it is a good thing to mind one`'s own business,--to
endeavour to rule one`'s own little house well in the first place;
then will there be the better qualification to have charge over the house of the Lord:
and this latter is a duty, which all will find, in some way or other,
in due season to devolve upon them, if they are faithful, and as they, through obedience,
come into a capacity for usefulness.
The useless members are to be cut off,--nay, they drop off,
as a withered bough that receives not the sap of life.
As soon as any have grown to the stature and strength for labour,
they are undoubtedly put out to service, and earn their livelihood,
even that which nourishes to life, and liveliness, and healthfulness,
even the heavenly bread.
And every son and daughter are to mind that portion of work,
which is set them by their parent to do in his family; and they are to do nothing else,
but to attend thereto cheerfully,
handling the tools and implements that he supplies them with,
and at the seasons of his appointment.
To these diligent day-labourers, the times of refreshment indeed come,
when it is seen to be needful,--in order that they faint not.
But in the Lord`'s family, those that will not work, must not eat, nor sit at his table,
nor have their penny of peace, nor the reward of "`well done.`"
The domestic economy here exercised, and the excellent discipline kept up,
and the comely order,
and beautiful harmony of all the true members of this spiritual house,
I have seen and known to be wonderful in all its bearings and branches:
but those that are not of it, cry out,
"`He is a hard master,`"--and would exact the uttermost farthing.
Yes, He is a hard master to the rebellious,
and terrible will they find Him in the reckoning day;
but very tender and pitiful is He found unto them, who are tender of his honour,
even before that day;
for they feel his unfailing mercy still blotting out and wiping away;
and extending afresh his hand of help,
to such as are willing to work out their own salvation with the true fear and trembling.

That thou, my dear friend,
by diligent and close attention to none other than the Shepherd`'s voice,
and by a cooperation therewith,
even a simple subjection to that which it makes manifest to be the duty of each day,
mayst come to have this and much more verified with
yet greater satisfaction to thee in thy measure,
is often my desire.
The way of the Lord`'s coming, is even as a refiner with fire,
and a fuller with soap,--to melt, and to purify;
and blessed are they that so receive him.
Thus the house of Saul will become weaker and weaker,
and that of David stronger and stronger; though the latter may be hunted,
as the partridge on the mountains, for a long season, pursued yet escaping:
and the seed of David to this day,
have often to "`abide in the wilderness in the strong-holds "`and in the mountains,
and are ready sometimes to say, "`surely I shall one day fall by the hand of Saul.`"
O! this is a sore conflict, yet a glorious and honourable warfare:
and the victory is certain to all those that hold out unto the end in faith and faithfulness.

I fondly trust, my dear friend, that by this time many of thy soul`'s enemies,
that have stalked their forty days like a Goliath, are laid low;
and that many of thy doubts and fears, are in measure done away;
that with renewed vigour, courage, patience, and perseverance,
thou art journeying onward, even with steady pace, and single eye;
not moved by the "`trial of cruel "`mockings,`" if that should be thy lot;
nor yet dismayed by the many tribulations that are
permitted to attend the path of the righteous.
Yet I trust,
that an equal if not a greater degree of care and
caution will yet mark thy every movement and stepping,
as thou goest along: I speak not of a silly slavish fear,
which keeps some far behind the footsteps of Christ and of his companions;
or of that weakness which would let the enfeebling reasoner prevail,
to the hindering or even stopping of a vigorous healthy growth.
Some have I known, who have suffered such an argument as this to nip their bud,
and so to check its putting forth, in the due and appointed season,
its natural blossoms and fruit,--saying, "`others have professed great things,
and have come to nothing; who am I, that I should pretend or presume so high?
surely I shall disgrace the cause,`" etc.
Such reasonings are, as we abide in the light, clearly manifested to be of the enemy,
though greatly disguised; and he sometimes lays hold of good kind of people, who,
with upright intentions for the best,
and desiring our preservation from hurtful extremes,
are induced by a mistaken and blinded judgment,
to advise us against running risks (as they think,) by such a bold, firm,
and decided conduct, as we apprehend is required at our hands.
I have had to tread much alone; and I have found it safe,
and conducive to my true growth, to look mainly, and in the first place,
to that which is truly an infallible Teacher, and which leads out of all error and evil,
into all truth and goodness; and after sometimes great delay,
(not through willfulness nor weariness,
but an upright desire to be led by nothing but the true guide,) I have
been made willing to resign myself to what has been cast up,
I trust with some thing of that singleness of heart and simplicity,
which the right thing does undoubtedly induce.
O! the comfort and divine consolation,
which such a procedure has drawn upon my poor soul,
even in the midst of much trouble and suffering.

The Truth does undoubtedly lead into a oneness in principle,
and even in practice as to generals: yet in regard to particular sacrifices and services,
very various are the allotments for each member of the church,--very different
are the gifts and dispensations which are meted out to each,
and the administrations of them also.
Blessed are those who know and keep their several places in the body,
always eyeing the Master, even the holy Head thereof.
These shall not be unduly moved by the revolutions and convulsions,
which may be permitted to arise, and to surprise the hypocrites, whether from within,
or from without; these abide in their habitation and safe shelter during the storms,
nor are they supine and confident in the day of ease and of calm weather,
but are prepared;
nay are (if it be best) forewarned often of the judgments that may be
impending or ready to be poured out upon the head of the disobedient.

Well, my dear friend, be valiant for the Lord and his precious Truth,
while thou hast a day in mercy granted thee;
joyfully and unreservedly yield thyself and all that thou hast unto his disposal.
Keep to the root of righteousness; and as the divine sap of life is suffered to ascend,
and to circulate in and through thy soul, thou shalt in due season be clothed,
or be strengthened to put on the excellent fruits of righteousness,
to the praise of Him who hath chosen and ordained us,
that we should go and bring forth much fruit, and that our fruit should remain;
and who is ready thoroughly to furnish us unto every good word and work required of us.

Farewell, and believe me to be thy affectionate friend,

J+++.+++ B.

John Barclay to +++_______+++.

Falmouth, 17th of Twelfth Month, 1819.

Dear +++_______+++,

My dear love is to thee, though from a low spot,
which has more or less been my experience of late: but I can truly say,
in the lowest seasons I have longed for nothing more
than for preservation through all things;
even though there should be but little going forward,
or any vigorous growth in that which is good.

Yet should I be content in this the Lord`'s will, who doeth all things well,
could I find an assurance, that finally the eternal rest of the righteous might be mine;
and that whilst buffeted and tempted here,
no reproach might be reasonably thrown on the blessed Truth,
through any unfaithfulness of mine.
A degree of sweet calmness seems to arise, whilst writing to thee;
in which I feel thee near to me, and myself still bound in a degree of tender love,
and refreshing fellow ship unto the faithful everywhere.
At such seasons how strongly does the sentiment recur,--testimonies
are nothing (comparatively,)--words are nothing--out ward,
perishable, changeable things are nothing;--but to know our sustenance, standing,
strength and life, to be in the only unfailing source,
and to feel that which is immortal,
invincible and unchangeable to bear up our minds
above the billows,--this is worth living for,
and suffering for, and dying for.

+++[+++In a letter to a person under serious convictions,--he wrote:]

John Barclay to M. B. W.

In taking my pen to reply to thy letter,
I have felt the occasion to be no small trial of my little measure of faith,
and have desired greatly to be preserved in that pure and precious fear,
which is said to be the very "`beginning of wisdom,`"--to
have my own mind renewedly subjected to,
and seasoned by, and stayed upon that,
which can alone enable me availingly to lift up a finger in the cause of Truth.
I may tell thee,
that I have had no little experience of the longsuffering
lovingkindness that has followed and been with me,
even as long as I can remember, unto this day; through many difficulties,
discouragements, dangers, distresses, and what if I add deaths,
(for he that liveth in pleasure is dead while he liveth.) When it pleased Him,
whom to know is life eternal, to reveal his Son in me,
(for "`no man knoweth the Father but the Son,
and he to whomsoever the Son will reveal him,`")--when it pleased Him,
in whom are hid all the treasures of wisdom and knowledge,
to give me an understanding that I might know him that is true,
then it was I was given to see that "`God resisteth the proud,
and giveth grace to the humble,`"--that "`the secret
of the Lord is with them that fear him,
and he will show them his covenant,--the meek also will he guide in judgment,
and the meek he will teach his way.`"
But I found that these things were and are hid from the wise and prudent of this world,
and that the Scribes and Pharisees of this day, as in old time,
are spoken unto in parables; because they looking see not, and listening hear not,
neither do they understand; so also they ask and receive not, for the same reason,
even because they ask amiss; and they look with that eye of reason which can never see,
and listen with that ear of pride, prejudice, or passion,
which is shut out from any capacity to hear the things
which God hath prepared for them that seek him.
So that of all things I was very solicitous,
that I might have mine eye rightly anointed with the eye-salve of the kingdom,
and be sent to the pool of Siloam; for I met with many whose eyes had been touched,
and they seemed satisfied with seeing men only as trees walking, and others who,
not having known the scales of mistaken zeal removed from their eyes,
were going about seeking some one to lead them by the hand.
But surely blessed are the eyes that see things as they really are,
in regard to religious truths, and those ears that hear, and who hearing,
obey Him that speaketh from heaven; these I considered to be the babes,
to whom these truths are revealed,
and to whom it is given to know the mysteries of the kingdom;
whose ears are not dull of hearing, nor their eyes have they closed,
neither have they hardened their hearts; nor are they the stiff-necked generation,
that do always resist the Holy Ghost:
but unto them is given the spirit of wisdom and revelation
in the knowledge of Jesus Christ,
the eyes of their understanding being enlightened by Him, who said,
"`I am the light of the world,`" and who told his disciples
that he would be with them even to the end of the world.

Now mark, my friend, no sooner did the enemy of my soul`'s peace and welfare,
perceive that his power of darkness was broken in upon,
by the dawning of the day-spring from on high, and that he, the god of this world,
could no longer keep me in blindness and bondage to himself,
and thus prevent the light of the glorious gospel of Christ from
effectually and availingly shining in my heart--than he,
as it were, assumed the appearance of an angel of light;
and thus he laid a more subtle snare and gilded bait for my poor weary soul,
than even I had known before.
For the unwearied adversary observing,
that through the precious powerful visitation of the Almighty,
my mind was quickened and awakened to a lively sense of the exceeding sinfulness of sin,
began himself to set me at work to recover from it; which indeed can only be begun,
carried on, and accomplished by God,
through faith in the operation of the Spirit of his Son, Christ Jesus;
who remains to be the only sacrifice for sin, and Saviour from sin,
and sanctifier of sinners.
And now being little by little led and enticed to try, in my own will, wisdom and way,
to get to heaven; and having let in the reasoner, the serpent,
in this his refined transformation,
I soon forgot that it is not to be attained by works of righteousness,
which we can do or have done in our own creaturely ability,
strength and activity,--but by an unreserved and
simple sub mission to the forming hand of him,
who made all things good in the beginning,
and who can alone restore and bring back man into the holy heavenly image,
in which he was created.
So that instead of being created in Christ Jesus unto good works, I,
having the understanding darkened, and being alienated, in some degree,
from the life of God, became vain in my imagination;
and my foolish heart would be exercising itself in
things too high for me in my present growth;
and busying itself and wearying itself with my own conceivings, speaking evil,
or at least thinking lightly of things, which as yet I knew not.
Thus, though I professed myself wise in the knowledge of religious truths,
I became foolish.
For all the fine show of doctrines, and of duties, and of ordinances,
and of prayers in the market places, and as it were in the corners of the streets,
and in the synagogues, and the giving of one`'s body to be burnt,
and one`'s goods to the poor,
or such of these great performances as were not the product of his holy aid and
influence renewedly extended in the time of need,--were found to be but at best
a hindrance to the free course of that well-spring and water of life,
which had been opened as in high places within me.
Although through the delusion and deceit of the enemy,
I was thus tempted to build a very Babel of doctrines,
heaping up scripture upon scripture, text upon text, to support my fabric of confusion;
and although I was very zealous in searching into
these things in my own spirit and strength,
(notwithstanding it is written, "`No man knoweth the things of God,
but by the Spirit of God,`" and no man can rightly and really own Jesus to be the Lord,
but by his Holy Spirit;)--yet in the midst of all
this departure from the fountain of living waters,
and this hewing out broken cisterns, that cannot receive or retain the water of Life,
I was not altogether left desolate;
but the Lord regarded the integrity of my heart towards Him,
even in those very performances and high profession, which displeased Him.
Again and again he was pleased in unutterable mercy, to make known unto me that way,
which he would have his single-hearted, simple,
lowly babes to walk in:--no galley with oars,
neither gallant ships could pass that way;--nothing that was high or lofty, or lifted up,
however secretly, in its own estimation,--nothing of self,
or of that wisdom which is foolishness with God,
and which he will utterly confound and destroy,
and by which the world never knew neither can know Him.
I found all my own strivings, and the strugglings of the will of the creature,
could not carry me one step forward in the narrow way;
neither was I able by taking thought to add one cubit to my stature,
in a religious sense; for I then saw it was not of him that willeth,
neither of him that runneth, but of God and his grace,
that cast up day by day the holy high way before my view,--giving me the strength sufficient,
and the sustenance that was meet, and that degree of satisfaction,
in regard to religious truths, which was best for me.
And in that day, as also even to this very hour,
the language often was to me,--"`I have yet many things to say unto thee,
but thou canst not bear them now.`"
But as I came from the feet of Gamaliel, to sit with Mary at the feet of Jesus,
and to be taught by Him in his inward and spiritual appearance,
(who is said to be the wisdom of God, and teacheth as never man taught,
speaking with authority and not as the Scribes,)--I found that this Minister of ministers,
did more for me as to the true and saving knowledge of Himself,
and the things relating to his kingdom, than any man or book whatever.
He (as his servant the apostle Paul said,) fed me with milk;
and as I grew to riper years, in a spiritual sense, he gave me stronger meat.
I found Him no hard master, or austere man,
requiring more of me than He had given strength to perform.
In this humble, simple state, resting in the Lord,
and waiting patiently for him,--not stirring up or attempting to awake
him whom my soul loved before he pleased,--not desiring to have everything
all at once cleared up before my view,--not seeking great things
for myself in any sense,--but only longing for a a seat,
if it might be the very lowest, at his spiritual supper,
or even to partake of the crumbs that might fall
from his table,--willing also to fast long,
if it so pleased Him,
until the times of refreshing should come from his presence,--O! how was and is my safety,
my sure standing, my strength, my salvation, known and felt to be wrought out,
even with fear and trembling.
For here in this lowly valley, where self was of no reputation,
and the bleak gales passed over, and cut not the tender plant,
the quiet habitation was known,--the still small voice was distinctly heard, which said,
"`This is the way, walk in it.`"
O! how I then knew my peace made and daily kept; even a holy assurance was given me,
a holy confidence and repose,
as in the arms of a faithful Creator,--agreeably to the language of the prophet,
"`Thou wilt keep him in perfect peace, whose mind is stayed on thee.`"
Here was communion and union with the Father and Fountain of mercies experienced,--joy
such as no man could take from me,--a peace which passeth the natural understanding,
and a holy heavenly fellowship as with the just of all generations.
Here I could call God Father,
because he had sent forth the Spirit of his Son into my heart,
and I had received the spirit of adoption, whereby I could cry, Abba, Father.
For as many as are led by the Spirit of God, they are his sons.

O! how precious is this passive, patient,
submissive state of mind,--a giving up of all into His holy
care and keeping,--a resigning of our own wills,
wisdom, and the workings of our own spirits and nature to be melted down,
and moulded into accordance with His divine and glorious nature and image.
Thus are we alone true witnesses and partakers of the first
resurrection,--over such the second death hath no power;
that part in us which is to die, being crucified, dead and buried,
according to the apostles testimony, where he says,
"`knowing this that our old man is crucified with Him,
that the body of sin might be destroyed, that hence forth we should not serve sin.`"
O! how clearly, even with unclouded clearness,
were things opened to me whilst in this state and condition;
or rather how was my mind prepared and qualified (through a being clothed with humility,
and the meek and quiet spirit,
and by a daily waiting on the Lord for a renewal of spiritual strength,) to comprehend,
apply, and attain unto the blessed commandments, injunctions,
and instructions left on record in the Scriptures of Truth.
The Psalmist said to this effect,--"`Open thou mine eyes,
that I may behold wondrous things out of thy law;`"--a proof he needed this best aid,
or we may suppose, he would not have thus supplicated.
Now the divine law was to be written on the heart,
and put into the inward parts under the Gospel dispensation; and Solomon says,
"`The law is light;`" and we read that "`whatsoever maketh manifest,
is light;`" so that according to Scripture, we have light sown in the heart,
unto which if we attend, it will manifest darkness, and the works of darkness,
and reprove them; and this we read is to be the law under the new covenant.
Then as I gave up, and was prevailed upon to yield unto the enlivening,
operative influence of this inward principle, it came to work out the evil,
and leaven the heart more and more into its own pure nature;
so that instead of the light within me becoming darkness,
my path seemed like that of the just man,
which shineth more and more unto the perfect day.

Whatever profession we make among men, we must serve the Lord in newness of life,
and be born again, born of the Spirit, for the carnal mind is enmity against God;
and without holiness no man can see God, or his kingdom, (which is "`righteousness,
peace, and joy in the Holy Ghost;`") neither can he enter therein:
however high the profession, yet so much the greater may be the condemnation.
O! I have felt it to be a very awful consideration, my friend,
that the enemy of our soul`'s eternal welfare, hunts for the precious life,
the substance and root of religion;
if he can eat that out,--if he can deprive us of that,
though our branches of profession be spread forth as Lebanon, we shall be cut down,
and cast into the fire, as a tree that cumbereth the ground of God`'s vineyard.
He even the enemy, cares not how busy and eager we are,
in what we may be pleased to think is religion, and to call so;
and though we may hold the doctrines of the very apostles and primitive Christians,
yet he knows very well that a man`'s creed being scriptural and correct,
is no certain criterion or proof whereby to judge what spirit it is that rules him.
For we read, that the very devils believe and tremble; and they could easily cry out,
in the days of our Saviour`'s appearance in the flesh,
"`Thou art Christ the Son of God;`"--and again, "`I know thee who thou art,
the Holy One of God.`"
But Jesus rebuking them, suffered them not to speak; because, no doubt,
their testimony of him,
though given in respect to the matter of fact which they declared,
was as it were a lie in their mouths,--agreeably to what Jeremiah says,
"`Though they (wicked men) say, the Lord liveth, yet verily they swear falsely.`"
And we see in the account of our Saviour`'s temptation in the wilderness,
how aptly Satan could quote scripture and bring texts to support his own vile purposes.
Now we may remember, that when Peter confessed and said, "`Thou art Christ,
the Son of the living God;`" Jesus answered and said unto him,--"`Blessed
art thou,--for flesh and blood hath not revealed it unto thee,
but my Father which is in heaven.`"
Here was an acknowledgment and profession,
arising out of and flowing from a measure of the true, living, operative faith,
which works by love, to the purifying of the heart and life.
Here was some thing more--something far beyond, a mere hewing out of systems of faith,
and holding them merely in the dead notion in the will of the creature.
Few follow or feel after the spiritual guide and leader,
which is Christ Jesus in his inward and spiritual appearance; who said,
"`I will not leave you comfortless, I will come to you;`" and who further promised,
that he would manifest himself unto such as loved him; and that those who followed Him,
(who is the Light of the world,) should not walk in darkness,
but should have the light of life.

It is indeed the Spirit of Truth that can alone lead us into all truth;
and it is the Spirit which quickeneth, for the flesh,
and all that the creature can do by its own strivings and stirrings,
profiteth nothing in the work of God; and the spirit of man as well as the wrath of man,
cannot work the righteousness of God, but hinders and obstructs it greatly.
Now, the Lord Jesus Christ, the Lord from heaven,
is that quickening Spirit who is the Way, the Truth, and the Life;
whom the world cannot receive,
(nor those that are in the spirit of the world,) because it seeth him not,
neither knoweth him; but to those that leave all and are willing to deny themselves,
and renounce this world`'s spirit, and follow Him in the regeneration,
the blessed promise and assurance is, "`He dwelleth with you, and shall be in you.`"
"`I am the living bread,`" said Christ; "`he that eateth my flesh, and drinketh my blood,
dwelleth in me,
and I in him:`" such spiritual communicants know Christ in them their hope of glory;
and thus are they built up and elected in Him, the corner stone, elect and precious.

We also own all that the Scriptures speak of, respecting His most satisfactory sacrifice,
and that he tasted death for every man, purchased eternal redemption for us;
and that "`through this man is preached by us the forgiveness
of sins:`" none are saved but by and through Him:
for we are reconciled to God by the death of His Son,
and thereby put into a capacity to lay hold of that salvation which is freely offered,
on condition that we repent and believe.
