== Chapter X.

+++[+++In a letter to a friend, dated 6th of First Month,
1820,--speaking of drawing up accounts for Piety Promoted,
which he had diligently taken in hand as a duty ever since the year 1817,
also collecting and copying letters of Friends,--he says:]

[.embedded-content-document.letter]
--

If these labours of love for the cause`' sake should ever come to much,
or be made of extended utility,--if they be rightly carried forward
and introduced to public view,--I trust I shall rejoice,
whoever may have it laid upon him to undertake this part of the business.
It is enough for me, quietly to devote myself to the accomplishment of such share,
in laying the foundation and erecting the scaffolding,
as seems required at my hands;--leaving the completion
thereof to the disposal of the master-builder,
who knows the several abilities of his workmen,
and portions out their duty according to their day and strength:--He knows how
comparatively short and small mine are;--yet He withholds not the penny.

--

[.offset]
+++[+++And in another letter on the same subject, he says:]

[.embedded-content-document.letter]
--

My powers are very weak and small, I think,
in comparison to those of almost any one else, also shattered,
and partaking of my feeble frame of body:
but there is no knowing what the great "`I AM,`" may choose to do with such;
and those things are ever best left with Him, who can do all things for me.
I have had nothing in view in this work but the great cause, and have sometimes thought,
I should leave it as a legacy among Friends; but it is as my Master wills to this day,
as it was when I set a hand to it.
If He please to take me from it, or it from me, it is well.

--

1820, First Month 19th.--I have had from one season to another, up to the present time,
many teaching intimations and timely warnings, from within and from without,
that there is no trust to be had in length of days,
nor dependence to be placed on health or strength or youth,
no nor yet on any services or sufferings for Truth`'s sake; but only upon the Rock,
Christ Jesus, the Lamb slain from the foundation of the world.
To know that renewed in us, which rightly gives an interest in his blood,
and in the salvation he purchased for us,--to feel the spring of immortal,
immaculate life and goodness,
bubbling up and breaking forth in and over us,--to be assured by hearing, knowing,
and following the Shepherd of Israel,
that we are his sheep,--to have a sure and satisfactory evidence,
that we are more and more coming out of the world`'s spirit,
into that of the weaned child,--becoming more and more separated from sin and self,--more
and more seasoned with and leavened into the nature of a child of God;--this is sweet,
and a safe spot, saith my soul, for any poor mortal to be found in,
when the summons may be sounded forth.

"`The time is short,`" said the apostle; and it remains for us all,
whatever be our situation in this life, or our station in the Church,
or our standing in a religious sense, to remember,
that "`the fashion of this world passeth away.`"
These things that are mutable must pass away, and shall be as though they had not been;
yet shall the righteous stand and be established,
when the earth is removed out of its place, and the firmament swept away as with a flood.
Greatly do I desire to be found amongst those, who stay themselves upon the living,
eternal, Almighty Father and Saviour;
and to be increasingly concerned to pass the remainder
of my time in true filial fear and faithfulness.

1820, Fourth Month 15th.--Surely my soul can praise and bless thy holy name at this time,
O Lord Almighty! who art just and faithful,
and true to one of the least of the poor of thy flock;
O! thou art the compassionate Friend of those who
art prevailed upon to surrender up all unto thee,
to commit all into thy care and keeping.
O! thou Shepherd of Israel,
what can I render unto thee for all thy benefits and sure mercies,
which are new every morning?
How shall I exalt and extol thy goodness, thy tenderness, thy long-suffering compassion,
manifested renewedly towards thine unworthy servant?
Words cannot celebrate thy wonderful bounty;
but the hearts of those that are concerned to yield themselves unto thee,
can sing unto thee of mercy, and of judgment, and of truth, eternal,
glorious and unspeakable.
O! thou all-wise and Almighty one, bring to pass whatever is for thy glory, thy honour,
thy majesty; and overrule the rest.
Limit the rage and roaring of the enemy, who still seeks to devour thy seed,
and to cut up thy people.
O! preserve thy poor dependent ones,
wherever or however gathered or scattered all the world over,
within the holy and sure enclosure of the hollow of thy hand, from this time forth,
even to the end of all things here below:--still stretch out the arm of
thy power;--still cover them with the wing of thy care and protection,
from the storms and from the blast;--still command deliverance for Jacob,
and send forth salvation for such as are thy people, who are seeking thy face,
and longing after thee.
Still also, O Lord! plead with the rebellious, who indeed dwell in a dry land;
who know not the unutterable sweets of thy holy religion.
If it be possible, yet lengthen out the day of thy mercy towards these,
as thou didst unto me,
O blessed God! and give them yet to see the things that
concern their real peace and everlasting happiness.
For what is equal to the joy that thy righteous have even here;
in the midst of all their trials, they are with thee, and thou leadest and feedest them,
and art their strong-hold in the day of trouble,
sanctifying all their afflictions to them:--adored forever be Thy name!
In a sense of thy living presence,
and many mercies vouchsafed unto me in an especial manner of late, I thus commemorate,
as it were, publicly, thy praise; desiring to return thee thanks,
and to commit the keeping of my soul unto thee henceforth;
and to crave of thee that I may be preserved humble,
holy and blameless unto the end,--increasingly consecrated
in heart and life to thy pure service;
so that my soul may be fitted, at the end of all things here, to enter into that rest,
which our blessed Saviour, thy beloved Son,
promised he would give unto those who come unto Him and keep with Him.
Amen.

[.offset]
+++[+++In a letter to a Friend, dated from Pool, 3rd of Sixth Month, 1820, he writes:]

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to a Friend

I may say that I have never considered it my place to maintain that station in the world,
or live in that mode of life in which I have been brought up,
however mortifying to poor self, and contrary to the habits and views of others.
It was one of the earliest convictions that settled on my mind,
when brought under serious impressions,
that I must come down and set an example of moderation and self-denial,
being content with such things as I have;
so that I have been most easy to decline even such opportunities of advancing my condition,
as others, no doubt, may in many instances, wisely and rightly seek for and improve.
Some again may throw themselves into extensive channels of usefulness,
by increasing their outward means: I can only say, I am to do good in another way,
if my life be spared.
I have looked, with much solicitude, for best guidance, in this matter:
and the comfort and peace with which, during my stay here,
I have been wonderfully favoured, has been such,
as to enable me at times even to sing for joy.
I have also been greatly broken down, under a sense of that hand,
which is so eminently over me for good,
enabling me to look the greatest of my difficulties, perplexities,
and discouragements in the face, as it were, with a degree of calm confidence.
My heart and life, and all that I am and have, are to be surrendered up in such a way,
as may answer the Lord`'s holy will and purpose concerning me.
On this ground-work, and on this principle,
I have not hesitated cheerfully to relinquish those views of outward gain,
and habits and station in life, to which my education tended;
but which I have clearly seen are not exactly such,
as harmonize with the Divine intention respecting me,
and with that sphere I should occupy.
What I have expressed herein, is not the feeling of yesterday or today,
but gradually confirmed and rooted in my mind, through much secret conflict,
and a long course of humbling exercises,
and such as some of my sympathizing friends have
been remarkably made sensible of from time to time.

[.signed-section-closing]
With much affection, I am thy Friend,

[.signed-section-signature]
J+++.+++ B.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Poole, 24th of Sixth Month, 1820.

O! it is a sweet thing to get into calmness,--to that spot where all our cares, fears,
and doubts are swallowed up.--It is that which our sickened souls often need as a cordial,
to revive and to recover us from the nausea of this world`'s joys and cares.
I often feel full occasion to press after a further purification,
from that which yet hangs about me, and which my spirit loathes:
to be released from the bondage is a great matter,
even to come into a degree of freedom from the workings of evil.
I wish many of our reformers, and some youthful ones especially,
knew more of this great work;
they would have shone brighter as vessels in the house of the Lord,
had they gone through the seventh furnace; they would have taken a better polish,
and the dust would not hang upon them, as it now lamentably does.
To feel something good visiting us,
is one thing;--but patiently to endure all the turnings of the holy Hand upon us,
both in breaking down the old nature,
and building up the new edifice on the sure foundation, is another matter.
I fear too many amongst us,
content ourselves with knowing but very little of the latter operation;
and even when that is partially begun,
they are for taking down the scaffolding and boarding in front,
in order to show others what is going on.

Since coming here, my mind is more thoroughly set at rest on some points than ever,
especially as to the propriety of my not entering into business,
a subject which used to harass me much; fearing sometimes, that by this conclusion,
I had given occasion for the cause to be evil spoken of,
and the testimony of Truth to be let down.
O! the path is very narrow in many respects, which I have to tread in,
I have had glimpses of it for several years; "`the pride of life`" must be laid low,
however mortifying to the poor creature, as well as to those, whose eyes are outward.
Thou seest how much occasion there is for the help, the secret help,
of those who can intercede for me, and sympathize with me;
there is that which can preserve on every hand as hitherto it hath marvellously done;
and as faithfulness is abode in and watchfulness with patience,
who can doubt that the issue of all our movements will through holy help,
be for the honour, and tend to the promotion of the great cause?

--

[.offset]
+++[+++In the Tenth Month of this year, he was married to Georgina Hill,
daughter of Major Hill, of Kingsbridge,
Devonshire:--she had joined the Society by convincement.]

1820,
Tenth Month 28th.--Seemed in this short illness to be brought near to the gates of death:
many awful reflections arose.
I longed exceedingly to become more meet to enter the celestial country:
but seemed to myself to have come short of such a state.
I have of late seen myself to have been very unwatchful;
my zeal for God and devotedness to His cause, very greatly decayed.
O! how often have my prayers been put up in sincerity to the Father of mercies,
for His continued goodness to such an unworthy creature,
and for His help against my potent enemy.
But it seems as though all was to little or no purpose,
and that my soul is sinking fast into the pit of supineness and forgetfulness.
This is surely for want of more steady adherence
to what is from time to time seen to be right,
and required of me.
Thus hath weakness crept over me, and great declensions in several respects.
O! how have my idol and my earthly outward delights run away with my heart and affection,
so that I forget or omit to lift up my soul as I ought to do,
with fervency and frequency of application to the Lord, my Redeemer,
who daily loadeth me with benefits.
When shall I arise from this dust, in which I am involved?
When shall I be aroused from this bed of ease and sluggishness in which I have been reclining:
after all that I have seen, and known of the Lord`'s dealings,
is this declension to be the consequence?
Surely, I had rather die than live, to forget my good God!
I believe it would conduce to my comfort,
to be less fervent in outward though lawful affections, and to be more fervent in spirit;
serving and loving my great Master more than any other object,
seeking Him more earnestly morning by morning,
and oftener than the day lifting up the heart to Him.
Earthly blessings should not so occupy the mind,
as to draw from the due attention to higher duties and more lasting pleasures.

[.offset]
+++[+++To a much valued friend, he wrote]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Penzance, 13th of Third Month, 1821.

&hellip;Often have I thought on thee and thy endearing friendship,
as commenced in days that are past, and strengthened in hours that are over and gone,
though not soon to be erased;
for to those winter-evening opportunities of comfort
and favour I enjoyed with thee and others,
may I not refer much of the benefit and instructive growth my soul received instrumentally,
at that period of my pilgrimage, when it seemed to be a time of espousals,
and when it might be said truly, "`Thy time was the time of love.`"
In reverting to such seasons, I have often been sensible of many shortcomings,
many wanderings, and much unwatchfulness:
and I am sometimes ready to apply to myself the language respecting Israel,
"`Of old time, I have broken thy yoke, and burst thy bands; and thou saidst,
I will not transgress;`"--though some consoling hope attends,
that the succeeding complaint of degeneracy does not altogether belong to me.
To be bowed down under a sense of our infirmities, is profitable to the best,
and safe at seasons for all; and whilst we may look upon these dispensations,
as some small proof that we are not left without chastisement and fatherly correction;
they turn out not infrequently, to be the forerunners of further displays of mercy,
and wholesome preparatives for use fulness and enlargement.
We often mar the benefits that are in store for us,
and the intended effects of our trials, by too great eagerness for deliverance.

We have great occasion to stay ourselves upon the
holy Rock in the day of trial and affliction,
having known favours beyond many,--the high hand made bare,
and extended renewedly to deliver and protect.
That we may attend with vigilance to the fresh openings of duty in every respect,
is my earnest desire, amidst a deep consciousness of much to deplore,
as regards want of more steady adherence thereto.

I hear you are richly visited in the ministerial capacity.
O! it is easy work to love them and their testimony from the very heart,
and to be attracted by the sweet influence of that which they live in;
but it is hard to labour in the desert for food and raiment,
and to have no intermediate helping-hand,
to cheer and to animate to constancy and endurance.
O! the extent of that labour and daily exercise,
which I feel needful for myself to be found in, lest my soul lose its hold!

[.signed-section-closing]
Farewell,

[.signed-section-signature]
J+++.+++ B.

--

1821, Fourth Month 20th.--Quarterly Meeting at Exeter.
O! that my soul may be moved effectually and permanently,
to strive for further liberation from the borders and boundaries of sin;
when shall I have a conscience void of offence toward my good Lord,
who daily heaps favours upon me!
Paid a sweet and solemn visit at J. D.`'s. O! that I may
walk worthy of these renewed seasons of mercy and favour;
may I double my diligence, fight the good fight of faith,
and strive earnestly for the hope of the Gospel,
whilst it is held out in unmerited goodness to me, a poor backslider.

1821, Fourth Month 20th.--Reached Poole.
Blessed be the Lord who hath preserved my soul and body
through many tribulations and temptations and dangers,
since I was last here.
O! my hardness of heart, not to be overcome by his abundant long-suffering and kindness,
and constrained to fall in with his designs respecting me,
which most assuredly are full of tenderness.

1821, Tenth Month 29th.--I set out from Poole, for London, with my beloved wife,
who has of late been a greater sufferer from illness,
her complaint being thought inflammation of the lungs.
At one time she seemed brought near to the gates of death; but she was not taken from me,
though I fear, I deserved it.
The Lord omnipotent preserve us in faith and patience,
and content under all the provings He is pleased to permit.
O! how much have we to be thankful for!
What great cause to live unto Him, who hath thus spared the rod in pity,
and heard our cry.
Many vicissitudes my poor soul has had; His dispensations towards me have been wonderful,
past all mention!

1821, Twelfth Month 25th.--Attended the London Quarterly Meeting, and was comforted.
The Lord will yet help and redeem my poor spirit, if I earnestly look unto Him always.
I was dealt with in mercy this day, both publicly and privately.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to Samuel Alexander, of Needham.

[.signed-section-context-open]
Cheltenham, 1Sth Seventh Month, 1822.

We have had an account of the decease of our beloved and valued Friend,
Charles Parker,--my fellow traveller, as I may call him, truly in more senses than one;
having had, as thou mayst remember,
the privilege of his company through Hampshire last autumn: it affected us considerably.
Past events connected with him, dear and faithful man, were much revived in my own mind;
and I thought much of him on the day of the burial.
I bless the Giver of all good that I have sat under his ministry;
and I remember that the tenor of it often was,--the
shortness and vanity of earthly enjoyments and trials,
the certainty and speed of death,
and the goodness and grace that visits and would gather all unto God,
the eternal excellency.
My soul is profitably instructed whilst I write:
and that may be the best use of my writing to thee, my dear, valued,
and now ancient friend and brother, who hast so often helped me to think of these things;
and who, I fully trust and believe, art looking for,
and desiring at times the winding up of all things, that are transitory and perishable.
O! that we who are young, may so tread in the footsteps of the path of the just,
that we may be prepared to fill up the vacated seats in the militant church,
of those who are gone before, and who have filled up their measure of enduring.

As to my poor self, if any thing may be said,
it should be but a middling account,--as hitherto, for a long season past;
often surrounded with fears and failings, sensible of shortcomings,
and a pensioner on that forbearance and pity,
which is not enough (I fear) regarded and remembered.
Watchfulness unto that which is good, seems to me the great thing in the work:
I am sensible we can thus only walk worthy of our vocation, and privileges.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Penzance, Ninth Month, 1822.

My beloved partner`'s present state is comparatively very free from suffering,
or from symptoms that cause uneasiness.
After eight months of vicissitude in London, she was removed to Cheltenham,
where she had some drawbacks from the climate, which was cold and changeable,
also at Clifton, where we rested.
But, through a merciful hand, by which she seemed directed to a religious physician,
she was soon so much relieved, that we could set forward on our journey into Cornwall,
being very anxious to do so; though from the severity of the attack,
it seemed as if we should hardly be able to winter here.
I trust we are both holding on our way,
and partaking at times of the brook by the way,--blessed be the great Name,
the Giver of life, and of all our many blessings!
We seem remarkably resigned and prepared for whatever may be meted out;
though we have our trials, and besetments, and infirmities.

--

On the 23rd of Sixth Month, 1823,
my dearly beloved partner passed away to her blessed
eternal rest in the Lord Jesus Christ,
the beloved of her soul and her Redeemer.
On the 29th, the poor body was committed to the earth, to return to the dust as it was.
(She died at Marazion, in Cornwall,
and her remains were interred in Friends`' burying ground,
at that place.) At the grave`'s mouth, I was strengthened to utter these words in public,
on bended knees:--"`Blessing, glory, honour, thanksgiving, and praise,
be given unto thee, O! Father of mercies,
and God of all consolation! both for that thou hast given,
and for that thou hast taken into thy resting place; Amen, O! Father,
for so it seemed good in thy sight:--thy holy will be done!`"
The Lord did marvellously regard and strengthen me: He will be my guide and refuge,
even to the end; surely he will, saith my soul.
The Lord doth daily help and comfort me.
He is with me a poor creature, and his strength is manifested in my abundant weakness.
He is my portion, even forever!

16th of Eighth Month, 1823.--I resume this little book after a long interval,
and one marked, as perhaps no other part of my life has hitherto been.
O! mighty is the Lord,
and able to sustain;--able also to finish his own glorious work in us,
either by allowing us a longer continuance here, or by taking us away to himself.
The Lord be praised for all!--even in that dispensation
which is still so bitter to nature;
but through his own consolation and strength it is wonderfully made tolerable.
Yea, life is pleasant;
and this world or earth is his footstool,--a place He has
glorified by his presence from age to age,--a place where,
at all times, and in all the parts of it, we may see traces of his goodness to poor man,
and tokens of what he will do in a better place for those that love and serve him.
Come then, O! my soul, take thy blessed privilege on this earth,
and serve him with a joyful cheerful heart; for He reigneth over all,
and nothing happens but by his gracious providence.

All is limited, even the evil one;
and all trials and troubles are restrained by his permission,
and converted to the good of his chosen ones, his children.
O! He has taken my dear companion into the rest he had prepared for her;
I can bless his name, for I believe he will never leave me,
until he has consummated his glorious purpose and promise,
in my heavenly translation to eternal joy and peace unspeakable.
Now know I, that He, the Most High,
is able to perfect that which concerneth me,--is able to
do all things for me,--able to prepare me for his glory,
and to support me in life and in death;--able also soon to cut short my day`'s work,
to give me a release,
and to make good a wonderful provision to those that shall come after me;
turning their mourning into joy, as he has done my sorrow for my beloved earthly friend.
Thus, and more also, will he do for them, and not forsake them.
Though He is invisible, yet He manifests himself through his dear Son,
even by the eternal Spirit; He is with his always, even to the end of the world;
and his are those that choose him for their portion,
falling in with his offers and visitations.
Even the wicked he visits by his rebukes and judgments;
and when they turn at his rebukes, he heals their backslidings, loving them freely.

I thought I received something like a summons to the eternal city two days ago;
when it may be confirmed and accomplished, I know not: but a great solemnity,
and much sweetness have since prevailed in my mind;
insomuch that it seems as if his wonderful power
had effected a willingness to go or to stay,
as He wills, who is the God of my life, and who can and does make life sweet;
and who will also take away the bitterness of death itself,
and no doubt will make up all, to those that remain, as he has done to me.
O! that all may be faithful to him!
He is wonderful in his dealings to the children of men,
not only by what are called his providences, but also by his grace.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to E. J.

[.signed-section-context-open]
Marazion, 15th of Eighth Month, 1823.

[.salutation]
My Dear Friend,

As a proof that I think of thee, as of many, other beloved Friends often,
when it is well with me,--I take my pen at the present season;
being reminded of our fellowship in years that are past,
and wonderfully encouraged and confirmed as to the ground of it;
also fully believing that our progress in the heavenly way,
will not be suffered to be much impeded by any of those
things which are permitted to try and discourage us.
O! the ancient, mighty Hand of goodness is not shortened, is not withheld,
in its gracious dealings and dispensations towards us;
but is able to lift us above all the obstructions which may dismay,--is
able to save to the uttermost,--can give the oil of joy for mourning,
the garment of praise and of salvation for the spirit of heaviness,--can do exceeding
abundantly above all that the soul is capable of asking or of thinking:
and he will surely be our guide, even unto the end.

Thy kind letter, dear E.; was no intrusion, but a comfort to me in my sore affliction.
No one that has not witnessed such a time, can tell,
how welcome are even a few lines from a dear friend:
though they may excite afresh the tear of affectionate sorrow,
they serve again and again, to remind one of, and to refer one afresh to,
that inexhaustible source of consolation and of joy eternal, which can make up to us,
all we can suffer in our passing along through life.

I need not to thee enlarge on the bitterness of this bereaving blow:
thou knowest a little of my long and heavy train of trials;
how acute was my sense of sympathy for my beloved earthly friend,
under every increase and variation of her sufferings.
Well!--the great Disposer of all things has dealt very gently with us;
he has cut the work short in righteousness and peace, as respects the better part;
and has put a period to all sorrow, sickness, and sin as regards herself;
giving her abundantly more than this world could afford,
even in the utmost prosperity:--He has likewise bestowed
on me such resignation and strength and faith in Himself,
as I trust will carry me through, and enable me to lay down my head, as my dear Georgina,
in peace.
Sometimes my assurance seems so strong and so clear that this will be the case,
even that "`I shall go to her`" (2 Samuel 12:20)
that everything in life is rendered pleasant,
and every duty no longer a burden; when I can bear in mind, that every event,
every trial, all my occasions of sorrow,
are not only "`working for me`" the "`exceeding weight of glory,`" but also as it were,
bringing me nearer to that blessed period.

When the mind is disposed to commune in this way,
a letter seems to afford but little space for it.
It is not however best for me to go into any of the circumstances of the closing scene,
except to say, that I know not any thing that then transpired,
but what seemed in my view, evidently ordered for good.
O! I felt that which I never could have supposed myself capable of feeling,
or fit to partake of,--so helped outwardly and inwardly,
so equal to all emergencies and all duties,--directed in everything,
as if no further token of Divine regard could be wanting.
And O! how peaceful was the close, how clear and sensible was she to the last; though,
dear soul, she had not many hours`' notice of her release,
nor had she any thing to spare in the awful time,
yet her expressions were all that could be wished.

I am ready to think, that nothing in life could have happened to me so strengthening,
so helpful to the better part, as her removal;
it carries with it an inexpressible weight of inducements, binding me afresh to holiness,
and lifting me, as it were,
upward towards the better country:--and what mighty evidence it affords,
none can tell but those that pass through it;--one`'s own bosom friend,
who has been as one`'s own soul so graciously dealt with, so blessed in the passage,
and so rewarded, even eternally!--I cannot declare these things, as I feel them;
and I fear my broken way of expression is almost unintelligible.

How precious a thing it is, to feel the blessing of Divine regard extended towards us,
strengthening to our day`'s work both of duty and of trial;
O! I would not give up the sense I sometimes have of this, for any thing on earth;
this is that which makes life and all things therein sweet to me, at a time,
when otherwise all is indeed but vanity.

--

1823, Ninth Month 18th.--The sweet incomes of Divine love to me this day,
were such as made me very contemplative, so as unusually to absorb my mind,
especially whilst engaged in working in my garden.
I betook myself to a retired walk on the sea-shore,
to enjoy the goodness of the Lord more quietly: the outward beauty of the creation,
and the calmness and harmony of all things around,
seemed in sweet unison with the state of my soul.
O! how I longed to be fully prepared for,
and wholly made partaker of the joys of the blessed,--of them who live to the Lord,
and die in the Lord!
I have a hope that I am journeying forward to this state.

1823, Tenth Month 9th.--My poor mind has been much under exercise since I left home,
and more particularly on one account;
apprehending some pretty strong drawings to stand
up in a meeting and express a few words.
This was the case first at Truro, then at Falmouth Monthly Meeting,
and then in degree at the Quarterly Meeting.
But I trust it was not in disobedience that I forbore;
many things seemed to stand in my way.
I desire not to be expecting great things, but I long for clearness;
and I believe I shall be favoured with it.
The consideration of many infirmities, and in some sense unfaithfulness,
and want of fitness for the work, affects me often;
but I long that it may not hinder the setting of my hand to what is laid upon me to do.
I believe there is nothing to be done, unless through a simple surrender and submission.
I can fully believe, that the Lord may call to some,
who may have had no previous expectation of such a call to service;
which indeed is by no means my case.
One thing is worthy of commemoration,--that whereas I besought
the Lord to be assured that such a thing was required at my hands,
he gave me evidently some strong signs,
in the frequent testimonies of his ministers from meeting to meeting;
even very closely urging to faithfulness,
so as almost literally to say,--"`Thou art the man.`"
But though I could not gainsay, yet I did not feel,
as though I had any very strong sense as to that being the right time:
for this I am now thankful; for, when the constraint was laid upon me afterwards,
not by man nor of man, I knew it to be of God, and beyond any man`'s appointment,
but a great cross to my own nature,
and under a sense of the Divine authority and presence.
May the Lord God of salvation and of mercy,
be pleased to show me the path of peace and of joy;
and may He lift up His countenance and light upon me, that I may see and do His will!

At several opportunities, in company with two dear Friends in the ministry,
who were visiting this meeting, I had a distinct sense of what was to be the service,
and what were the wants of the parties visited; especially was this the case,
in a public meeting held at Redruth.
At one family visit in this neighbourhood,
I was sensible of the evident call and requiring of the Lord to utter a few words,
in addition to what dropped from others, to the young people present,
on this wise;--and then you will find fulfilled in your own experience this language,
as it hath abundantly been in mine;--"`Though I walk in the midst of trouble,
thou wilt revive me; though I walk in darkness, Thou, O! Lord,
will be a light unto me;--though I pass through the valley of the shadow of death,
I will fear no evil.`"
The weight and sweetness that dwelt on my mind, after this surrender,
cannot be set forth: O! how it rested on my spirit all the day, in an unutterable manner;
I felt so comfortable, and at ease in my mind; O! it was a heavenly feeling,
and nothing short of Him who is in heaven, could give it!
At Wadebridge, in the public meeting, I had to speak to the people,
and in a way remarkable to myself, for I felt at home in it, if I may so express myself.
Self-possession seemed to be granted me, and self-abasement;
just as though it was not I that had spoken, but my Father, which is in heaven.
In this and other service hereafter mentioned, I had,
(praise be to the Lord! who turns the hearts,
and influences his own simple ones,) the countenance and encouragement of those, who,
I believe, know the voice of the true shepherd from that of the stranger.
This often humbles me greatly; for next to the answer of peace from God in my own bosom,
what I have desired has often been, the unity of the church and the love of the brethren.

I went into Devonshire, and on my return home,
I had something to say in the next meeting I attended at Marazion:
also at one Monthly Meeting held at Falmouth, on the true church: and again,
in the chamber of a Friend,
who had been long an invalid,--"`Behold we count them happy which endure;`" take,
my sister, the prophets, who have spoken unto us in the name of the Lord,
for an example of suffering affliction, and patience:
thou hast heard of the patience of Job, and hast seen the end of the Lord,
that he is very pitiful, and of tender mercy.
Behold, we count them happy which endure.
It is a blessed thing indeed, when flesh and heart fail,
to know God to be the strength of our heart and our portion forever.
God shall redeem thy soul from the power of the grave, for he shall receive thee!
Thus my Master, my tender Father and Teacher dealt with me; and now,
what should I wait for,
but the continuance of his mercy and his light to preserve and sustain me henceforth,
even forever.

I may add, that it was evident to me,
that he who in simplicity surrenders any thing to the Lord,
which in any wise seems called for, will not lose his reward;
but will find his way open and enlarge, his peace extend,
and he will know more and more of the requirings
and business of the Lord consigned to him;
and the evidence and motions will often increase after the will is resigned.
Wonderful is the Lord`'s goodness to me from time to time, beyond words!
He filleth me "`with the finest of the wheat;`" and he revealeth
unto me "`the abundance of peace and truth.`"
O! how precious a season was our Quarterly Meeting (14th of First Month,
1824,) held at Austle.
Is there any thing too hard for the Lord?
"`Call unto me, and I will answer thee, and show thee great and mighty things,
which thou knowest not.`"

1824, First Month 22nd.--Under a feeling of great discouragement at both meetings today,
I trust my mind was sensible where all-sufficient help forever lies;
though so little of this seemed manifested, or my soul so little capable of enjoying it.

23rd.--Found the overshadowing sweetness of Divine mercy renewed to me this morning,
in a large degree; so that my soul seemed to receive it,
as a token and foretaste of a more full fruition in a better state of being.
Blessed be the Lord, who can raise out of the dust!

27th.--I thought I saw very clearly, that it is through obedience even in small matters,
that our Society, in some respects, has attained a standing beyond most:
obedience is indeed, a striking feature in the Christian dispensation.

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Marazion, 11th of Second Month, 1824.

[.salutation]
Dear +++_______+++,

I have heard scarce a word respecting thee for a long time,
but nevertheless I hold thee very preciously before my view;
and thy humble waiting and walking is often encouraging.
I should be much pleased wast thou inclined, in the freedom of old friendship,
to salute me by letter at any time;
thou knowest not of what service it might prove to me,
and be made instrumental to build me up in the most holy faith,
as heretofore used to be the case, when we were nearer in the outward one to another,
and at times, blessed in each other`'s society.
I have a full persuasion,
however varied our habits and however distance as to space may have operated,
together with other circumstances,
that we are under the special keeping of the heavenly Shepherd; who can feed, and lead,
and cause to lie down, and will permit nothing to make afraid,
or to scatter from his pasture of life and fold of eternal rest.
"`My Father is greater than all,`" and none shall
pluck out of his hand those who keep near Him,
and lean alone upon Him.
For he restoreth the soul, and leadeth in the paths of righteousness for his name`'s sake.
So that though we may have to walk through the valley of
the shadow of death we need fear no evil,--He is with us,
his rod and staff they comfort us.
And when he is pleased to anoint the head as with oil, does not our cup flow over;
and are we not ready to cry out,--"`Surely goodness
and mercy shall follow me all the days of my life,
and I will dwell in thy house forever?`"
This is, I believe, at times thy experience, as it is my own.
Then for us the feeble ones, who may under discouraging apprehensions of our own state,
be walking fearfully along, as with our heads often hanging down very low,
and who may be said, in some sense, to have answered the call of the Lord,
(as in Joel,) "`Turn ye even to me with all your heart, and with fasting,
and with weeping,
and with mourning,`"--even to such the language will go forth,--"`be glad and rejoice,
for the Lord will do great things,`"--"`for the pastures of the wilderness do spring,
the fig-tree and the vine do yield their strength:--and ye shall eat in plenty,
and be satisfied, and praise the name of the Lord your God,
that hath dealt wondrously with you: and my people shall never be ashamed.`"

Truly in respect to these things that have happened unto me,
they have turned to the furtherance of the work of His glory and grace,
who doeth all things well; and up to this day, through heights and depths,
my experience is consistent with the language,
"`The right hand of the Lord is exalted,--the right hand
of the Lord doeth valiantly;`" for though he cause grief,
yet hath he compassion, such as will carry through all.
The manifestations of Divine goodness and wisdom,
are indeed very great to the willing and attentive soul;
and whilst there are seasons when we are not so sensible of them, others are vouchsafed,
in which we cannot doubt or fear but that as we continue
the diligent and patient followers of our crucified Master,
we shall reign with him in a glorious eternity of peace and joy.
My mind has been of late more or less,
since the decease or release of my beloved Georgina, set on its treasure in the heavens,
which will never pass away; and I have been assured,
that if I continue in faith to the end of my day, a place will be prepared for me;
it seemed almost as if permitted by foretaste, to lay hold of eternal life.
Such views are very awful, yet very sweet to me; so that whether they are premonitory,
or only admonitory, they have the effect of quickening me in the duties of life,
and of increasing my true enjoyment therein.--"`Work,
while it is day;`" for "`this is not your rest.`"

[.signed-section-closing]
Believe me, with warmth of affection, thy friend,

[.signed-section-signature]
J+++.+++ B.

--

1824, Third Month 22nd.--I desire, when the hour of my departure draws nigh,
to be clothed with faith towards God,
and with resignation to commit my dear and only little one into His hand,
who gave him to me:--"`leave thy fatherless children unto me;`"--"`let
their widows also trust in me,`" "`the Father of the fatherless.`"

1824, Fourth Month 2nd.--I was this day inclined to believe,
as I have been often of late,
that the bereavement I have sustained in the loss of my tender partner,
was intended in a peculiar manner for my good.
I have been led to think,
that as my dear wife was given to me at a time when I greatly wanted a help-meet;
and as she was one of a noble and capacious mind, inured to trouble and difficulty,
able to counsel and to assist me; so when the time for her was come,
to show me how to pass through the dark valley,
she fulfilled the Divine will in a wonderful degree, as I believe,
by setting me an excellent example through Him who strengthened her,
and who bore up her afflicted spirit through all that was permitted to assail.
O! it is often wonderful to me, to think how suddenly at the last,
she was summoned to take her leave of all that was near and dear in this life,
and how this was accomplished; so that there seemed no agitation or disquietude,
but a holy magnanimity, a deep and solemn reflecting on her condition,
and a reverting to her only hope of glory.
And now I am left, with the image of a dear devoted child of God, my soul`'s fellow,
often brought before me; to show me how to lay down these shackles,
how to put off this outward man,
and yield up my spirit to my God and her God!--How strongly has
the uncertainty of my continuance in life been before me;
and strong have been my hope and humble assurance, that mercy will compass me about,
and that the rest and portion of the righteous will be mine.
I am ready to say, that those that come after me, will be helped, as I have been;
at least in proportion as they follow the Lord`'s leadings:
for this has truly been my inexpressible desire and comfort;
and such will never be forsaken.

London, 1824, Fifth Month 11th.--I have had many bright seasons,
much assurance and earnest of a better state, as I have walked by the way,
and as I have been on my bed.
"`In all their afflictions,`" it is said, "`he was afflicted;
and the angel of his presence saved them.`"
This language has been fulfilled towards me, and towards my dear deceased partner;
and those that come after me will find, to their unspeakable support and consolation,
that the same Divine Being is rich toward all that call upon him: if faithful,
"`this God will be their God forever and ever; he will be their guide even unto death.`"

[.embedded-content-document.letter]
--

[.letter-heading]
John Barclay to +++_______+++.

[.signed-section-context-open]
Russell Square, 21st of Sixth Month, 1824.

[.salutation]
My dear Friend,

It is pleasant to salute thee thus, and to remember thee from time to time,
as a brother and companion in the heavenly way and warfare,
striving together with me for an increase of strength and wisdom,
to enable us to stand steadfast, immoveable, and abounding in the work appointed us.
I trust, that as the circumstance of trial and distress,
which were on this very day last year, consummated in the release of my dear wife,
and of which my mind feels often keenly sensible,
were all turned to an unspeakable account and benefit, especially with regard to myself;
so the precarious delicate state of my own health for some time past,
has operated and does continue to operate advantageously on the better part;
and although in this visit to London,
I may have been deprived of many seasons and showers of Divine good,
there has been no want of the care and safe guidance of that invisible hand of Him,
whose visitations uphold or preserve the spirit, and whose comforts delight the soul.

--

1824,
Seventh Month 16th.--So far recovered (from illness in London)
as to go to C+++______+++. The Lord Almighty was eminently near me,
by support and help in the needful hour,
and through days and nights of tedious ailing and irritation;
my situation often caused many tears in my retirement,
but the Lord was near and comforted me,
and helped me to gratitude as well as acquiescence:
my tears were often turned into tears of joy.
Much have I thought in my distresses of that sweet answer of my dear partner,
which she quickly and smilingly gave me, when in great depression,
observing a sparrow on the house-top, opposite to her window, I said,
"`Like a sparrow alone on the house-top;`" she replied,--"`Not one of them forgotten
before God:`" O! I find it so to my unspeakable consolation in low seasons.
And I think, since my trials and bereavement,
that more of the consolations of Christ are poured into my soul,
than used to be the case.
Many have been the blessings shed on me abundantly in this tedious,
though short confinement.
May the Lord have the honour and praise, not only now, but forevermore!

17th.--Went out a ride with +++_______+++; a sweet day!
What a change from my sick room and sofa and the smoky city,
to the extensive prospects on the Downs, and the richness of nature`'s verdure.
Was engaged in conversation with +++_______+++: I feel an interest in young invalids.
O! that the ends of providence may be answered in them, and in me also;
then all will be well.
O! these light afflictions;--what; a moment do they last,
when compared with the rich eternal recompense,
reserved for those that commit the keeping of their
souls in patient well-doing unto a faithful Creator.

18th.--First day;
at Croydon meetings.--I had a sweet night of pouring
forth of the heart unto the Most High.
"`I will cry unto God Most High, unto God that performeth all things for me!`"
Floods of tears,--tears of joy,--because the Lord God sees me, and hath mercy on me.
I had reference to my forlorn state,
and to the circumstance of my late afflictive bereavement;
and I had a wonderful evidence that the Lord would be all in all to me,
as he had been to my beloved partner.

1824, Seventh Month 25th.--First day.
Went to Gracechurch Street meeting, and had my mouth opened by the Lord.
O! the peace--the rich flow of it in my bosom, at dear P. B.`'s, after dinner;
the Lord was with me:
melting sweetness came over me in again giving up to express these and other words,
"`This God is our God forever and ever; he will be our guide even unto death.`"
